### ISSUE TITLE
How do I switch user agent using the command line?

### ISSUE THREAD

**Issue by psonnosp** [instaloader/instaloader#1001]
Did a search but only found posts about scripts and stuff and that didn't help me.
The [documentation](https://instaloader.github.io/cli-options.html?highlight=user%20agent#cmdoption-user-agent) doesn't say much and when I use
`--user-agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36`
I just get some red angry letters thrown at me 😄

**Comment by AplhaSlayer1964** [comment]
try putting "quotation marks" around it. since you are passing a command line argument it uses spaces as a delimiter
