### ISSUE TITLE
Sleep / delay / rate limit between or after specific amount of download as command line option

### ISSUE THREAD

**Issue by skeith** [instaloader/instaloader#1006]
**Provide us a use case of the feature**
When downloading a lot of instagram posts with login, it will trigger account locking by instagram (last time I check it was after 200 posts being downloaded in a single run). This feature request hopefully will allow downloading without account issue. 

**Describe the solution you'd like**
I would like to request for a command line option that enforce rate limit or delay between downloads

**Describe alternatives you've considered**
I haven't got a clue for any alternative

**If the feature request is accepted, would you be willing to submit a pull request?**
I could submit pull request but I am still a beginner and would be clueless on how and where to start

**Additional context**
Reason for this feature request can also be read on issue #944

**Comment by Thammus** [comment]
> **Describe the solution you'd like**
> I would like to request for a command line option that enforce rate limit or delay between downloads

Instaloader has a logic to keep track of its requests to Instagram and defers subsequent ones in order to not reach Instagram's rate limits. This rate controlling logic also gets applied when using Instaloader through CLI.

**Comment by skeith** [comment]
I should have described my request better. 

I don't know if Instaloader CLI already have such logic, that's my bad. However, considering I always hit with account being locked, makes me think about this request. I was thinking, with this CLI option, one can force a slower delay to further avoid account being locked, such as one download per minute or something else even slower. 

That said, I have heard from a friend that Instagram is kind of strict to scrapper and stuff, so I understand the decision on this feature request of mine.

**Comment by Thammus** [comment]
When used through CLI, Instaloader applies its default rate control logic. Making adjustments to this logic is a non-standard use-case, for which a CLI is generally badly suited.

**Comment by calvinthefreak** [comment]
Thanks for not Implementing or pushing development this way. Not everybody is good at python and just want to use an CLI option like --custom-sleep=seconds or so...

**Comment by cyberfunk** [comment]
The built in rate limiter does not work and my account is eventually blocked returning error 400 for any subsequent download attempts. Also an easy method to resume where Instaloader left off/was blocked would be helpful. The explanation provided in Advanced Instaloader Examples dropwhile takewhle is not easily implemented to the novice command line user imho.
