### ISSUE TITLE
Download Followers/Following and some details about them

### ISSUE THREAD

**Issue by Deleora** [instaloader/instaloader#1008]
Hi, I'm trying to download all of my followers and followings into a csv file along with custom fields of each account in the list.
I'm using the following code but apparently after a while I get `Too many queries in the last time. Need to wait x seconds`
Is there any way to reduce the number of requests?

Here's the code:
```
import csv

import instaloader
from instaloader import Profile

your_username = 'myUsername'
target_profile = 'myUsername'

L = instaloader.Instaloader()
L.load_session_from_file(your_username)
P = Profile.from_username(L.context, target_profile)
print("Getting 'following'")
following = P.get_followees()
newFollowing = sorted(following, key=lambda x: x.userid, reverse=False)
print("Getting 'followers'")
followers = P.get_followers()
newFollowers = sorted(followers, key=lambda x: x.userid, reverse=False)

print("Saving to file...\nFollowing: ", following.count)
with open(target_profile + "_" + str(following.count) + "_following.csv", 'w', newline='') as followingCSV:
    followingWriter = csv.writer(followingCSV, delimiter=',')
    followingWriter.writerow(
        ['User ID', 'Username', 'Fullname', 'Followed by you', 'Blocked you', 'Follows you', 'Profile URL'])
    for f in newFollowing:
        followingWriter.writerow(
            [f.userid, f.username, f.full_name.encode("utf-8"), f.followed_by_viewer,
             f.has_blocked_viewer, f.follows_viewer, f.external_url])
# ---------------------------------------------------------------------------------------------

with open(target_profile + "_" + str(followers.count) + "_followers.csv", 'w', newline='') as followerCSV:
    followerWriter = csv.writer(followerCSV, delimiter=',')
    followerWriter.writerow(
        ['User ID', 'Username', 'Fullname', 'Followed by you', 'Blocked you', 'Follows you', 'Profile URL'])
    for f in newFollowers:
        followerWriter.writerow(
            [f.userid, f.username, f.full_name.encode("utf-8"), f.followed_by_viewer,
             f.has_blocked_viewer, f.follows_viewer, f.external_url])
# ---------------------------------------------------------------------------------------------
print("Saved")

```
I have around 200 accounts in each list.
Any help please?

**Comment by Thammus** [comment]
Looking at your code, we do not see how the number of requests can be reduced. `get_followers()` and `get_followees()` are very efficient and the fetched Profiles do already contain the following fields:
- userid
- username
- full_name
- is_verified
- followed_by_viewer
- requested_by_viewer

However, accessing some of the other fields like `has_blocked_viewer`, `follows_viewer` and `external_url` requires the full metadata to be present which gets fetched by an extra request.

**Comment by Deleora** [comment]
> However, accessing some of the other fields like `has_blocked_viewer`, `follows_viewer` and `external_url` requires the full metadata to be present which gets fetched by an extra request.

So if I remove these particular fields, can I avoid getting the **Too many queries in the last time. Need to wait x seconds** error (in my case at least)?

**Comment by aandergr** [comment]
I'd expect the script to be faster and that message to appear less, if these fields are removed.

**Comment by Deleora** [comment]
Alright I'll give it a go. Thanks for the suggestions.
