### ISSUE TITLE
When does QueryReturnedBadRequestException: 400 Bad Request occur?

### ISSUE THREAD

**Issue by brilam** [instaloader/instaloader#1011]
Hi,

I've been using Instaloader and was able to use it successfully once to acquire results for a hashtag using one account. I originally set a delay of 2 hours between each search session and it seemed fine. More recently, I've decided to run Instaloader across multiple accounts. I am wondering on if anyone has any idea of when QueryReturnedBadRequestException is returned. I know that it is done to block an account for suspicious activity. But I am wondering if this is done across a per account basis or per IP basis? In other words, do they consider number of API calls per IP or is it number of API calls per account?

Thanks!

**Comment by joseluismoreira** [comment]
I have the same question. May anyone help, please?
