### ISSUE TITLE
Count argument not working

### ISSUE THREAD

**Issue by bulkbuy** [instaloader/instaloader#1012]
`instaloader getinstastyle --count=5 --fast-update`

its proceeding to download all 3k+ posts in [getinstastyle](https://www.instagram.com/getinstastyle)

`instaloader --version`
4.5.3

**Comment by Showmaster3000** [comment]
``--count`` is only applied to #hashtag, %location id, and :feed - as stated in the manual:
https://instaloader.github.io/cli-options.html#cmdoption-count
You are trying to download a profile. So it's not a bug.
Btw. your instaloader version is out of date.

**Comment by miclejackson12** [comment]
> `--count` is only applied to #hashtag, %location id, and :feed - as stated in the manual:
> https://instaloader.github.io/cli-options.html#cmdoption-count
> You are trying to download a profile. So it's not a bug.
> Btw. your instaloader version is out of date.

Why is it only for #hashtag, %location id, and :feed ?
May I know why such an important feature is not shipped for profile.
It's too painful to traverse through all 10k posts when you need to download only the latest 10.
