### ISSUE TITLE
:stories: JSON Query to graphql/query: HTTP error code 500

### ISSUE THREAD

**Issue by MrJmpl3** [instaloader/instaloader#1014]
**Describe the bug**
Similar to the bug: https://github.com/instaloader/instaloader/issues/795

After using a command to download the most recent stories off my followees. I keep getting this error. The :stories command should use the least amount of API calls i thought....
Also when recreating the session file using the firefox cookies python script it does not help anymore.
Used from here: https://instaloader.github.io/troubleshooting.html#login-error

Edit: With the version 4.5.5, I don't have this bug

**To Reproduce**
`instaloader :stories --dirname-pattern="{profile}\stories" --no-captions --no-video-thumbnails --request-timeout=300 --login [USER] --password=[PASSWORD]`

**Expected behavior**
To download the most recent all stories of followees (91 in total)

**Error messages and tracebacks**

```
Retrieving all visible stories...
JSON Query to graphql/query: HTTP error code 500. [retrying; skip with ^C]
[skipped by user]
:stories: JSON Query to graphql/query: HTTP error code 500.
Saved session to C:\Users\JOSEMANUEL\AppData\Local\Instaloader\session-[hidden].

Errors or warnings occurred:
:stories: JSON Query to graphql/query: HTTP error code 500.
```

**Instaloader version**
4.6.1

**Comment by rocailler** [comment]
same here but in module.
```
for story in L.get_stories():
    # story is a Story object
    for item in story.get_items():
        # item is a StoryItem object
        L.download_storyitem(item, ':stories')
```
loop over stories doesn't work.
this works:
`stories = instance.il.get_stories(userid)`
and gets generator. But that doesn't:
```
for story in stories:
    pass
```
and returns:
`JSON Query to graphql/query: HTTP error code 500. [retrying; skip with ^C]`

**Comment by DReaper** [comment]
I am getting this error as well. I'm not sure what causes it as it seems to be on and off
