### ISSUE TITLE
Getting @profile to work

### ISSUE THREAD

**Issue by concord72** [instaloader/instaloader#1018]
I am a noob with CLI so I apologize in advance. I am trying to use the @profile feature and download all the profiles followed by one account. This is the the basic input I have been using:

.\instaloader --login=concord72i -V --no-captions --no-metadata-json concord72ig [@profile ...]

What am I doing wrong (it's probably an obvious mistake)? I've tried a few different variations, they all come back with an error that the username or profile is invalid/does not exist. I know everything in the beginning is correct, I've gotten that to work downloading entire profiles individually, using @profile is where things gets wonky. Any help is much appreciated.

**Comment by Deleora** [comment]
I'm not sure if I understood your case but maybe you wanna do [this](https://github.com/instaloader/instaloader/issues/924)?
