### ISSUE TITLE
Problem with login in instagram account

### ISSUE THREAD

**Issue by NikGorojanin** [instaloader/instaloader#1019]
When I try to login in instagram account
`L = instaloader.Instaloader()
  L.login(username, pwd)`
 I had the exception 
`instaloader.exceptions.ConnectionException: Login error: "fail" status, message "feedback_required"`

How I can fix it?

**Comment by Diyaa1** [comment]
I faced this several times when developing, it's just that you got blocked, usually from not following the rate limits or two many login attempts that requires two factor authentication.

for me the block just goes away after several days, I think there's nothing you can do.
