### ISSUE TITLE
Profile.get_followers() is not getting 100% of followers

### ISSUE THREAD

**Issue by JavierPiedra** [instaloader/instaloader#1021]
**Describe the bug**
After trying to fetch all the followers of accounts, I've seen it always lacks ~1 follower per each 200 followers.
I'm not sure what is the problem cause it's not showing any kind of exception when querying the data.
I try looking manually on the IG web interface at the followers that aren't being fetched and they are: 
1. Public
2. Some are being followed by the account in question
3. Some have been followers for more than 1 month

**To Reproduce**
```
username = 'username'
L = instaloader.Instaloader()
try:
    L.load_session_from_file(username)
except instaloader.BadCredentialsException:
    L.login(username, 'credentiales-password')
    L.save_session_to_file()
except instaloader.TwoFactorAuthRequiredException:
    L.two_factor_login()
    L.save_session_to_file()
pipaslastres = instaloader.Profile.from_username(L.context, 'pipaslastres')
pipaslastres_cls = [f_cls for f_cls in pipaslastres.get_followers()]
pipaslastres_followers = [{'a': 'pipaslastres', 'f': f.username} for f in pipaslastres_cls]

len(pipaslastres_followers) # 1469
# real followers count according to IG interface = 1474
```
**Expected behavior**
Download 100% of followers

**Instaloader version**
4.6.1

**Comment by Thammus** [comment]
According to https://help.instagram.com/801322493288277 some Instagram accounts like alcohol brands are only visible for people over a certain age. If Instagram does not know your age, these accounts are not visible and are also excluded from the list of followers you are able to fetch.

**Comment by JavierPiedra** [comment]
> According to https://help.instagram.com/801322493288277 some Instagram accounts like alcohol brands are only visible for people over a certain age. If Instagram does not know your age, these accounts are not visible and are also excluded from the list of followers you are able to fetch.

I checked with a particular user that I wasnt able to fetch: she has her age set on the IG app, she is over 28. I think this is not the problem

**Comment by Thammus** [comment]
I have added my date of birth in my account settings of Instagram. When executing your code snippet, all of the reported 1666 followers get fetched by `Profile.get_followers()`. Doing the same procedure with an Instagram account that is not age-verified, only 1646 followers get fetched.

```python
L = instaloader.Instaloader()
L.load_session_from_file('thammus')

pipaslastres = instaloader.Profile.from_username(L.context, 'pipaslastres')
pipaslastres_cls = [f_cls for f_cls in pipaslastres.get_followers()]
pipaslastres_followers = [{'a': 'pipaslastres', 'f': f.username} for f in pipaslastres_cls]

pipaslastres.followers      # output: 1666
len(pipaslastres_followers) # output: 1666
```
Not age-verified account:
```python
pipaslastres.followers      # output: 1666
len(pipaslastres_followers) # output: 1646
```

**Comment by JavierPiedra** [comment]
> I have added my date of birth in my account settings of Instagram. When executing your code snippet, all of the reported 1666 followers get fetched by `Profile.get_followers()`. Doing the same procedure with an Instagram account that is not age-verified, only 1646 followers get fetched.
> 
> 
> 
> ```python
> 
> L = instaloader.Instaloader()
> 
> L.load_session_from_file('thammus')
> 
> 
> 
> pipaslastres = instaloader.Profile.from_username(L.context, 'pipaslastres')
> 
> pipaslastres_cls = [f_cls for f_cls in pipaslastres.get_followers()]
> 
> pipaslastres_followers = [{'a': 'pipaslastres', 'f': f.username} for f in pipaslastres_cls]
> 
> 
> 
> pipaslastres.followers      # output: 1666
> 
> len(pipaslastres_followers) # output: 1666
> 
> ```
> 
> Not age-verified account:
> 
> ```python
> 
> pipaslastres.followers      # output: 1666
> 
> len(pipaslastres_followers) # output: 1646
> 
> ```

Ohh!!!! Ok, so the logged-in account is the one that has to be age verified! I understood that we were talking about the followers. Thank you for taking the time!

**Comment by JavierPiedra** [comment]
> I have added my date of birth in my account settings of Instagram. When executing your code snippet, all of the reported 1666 followers get fetched by `Profile.get_followers()`. Doing the same procedure with an Instagram account that is not age-verified, only 1646 followers get fetched.
> 
> 
> 
> ```python
> 
> L = instaloader.Instaloader()
> 
> L.load_session_from_file('thammus')
> 
> 
> 
> pipaslastres = instaloader.Profile.from_username(L.context, 'pipaslastres')
> 
> pipaslastres_cls = [f_cls for f_cls in pipaslastres.get_followers()]
> 
> pipaslastres_followers = [{'a': 'pipaslastres', 'f': f.username} for f in pipaslastres_cls]
> 
> 
> 
> pipaslastres.followers      # output: 1666
> 
> len(pipaslastres_followers) # output: 1666
> 
> ```
> 
> Not age-verified account:
> 
> ```python
> 
> pipaslastres.followers      # output: 1666
> 
> len(pipaslastres_followers) # output: 1646
> 
> ```

I double checked, and the account I'm using to log into IG is age-verified, so this time it doesn't apply the age limitation

**Comment by Thammus** [comment]
Would you mind sharing your new observations? Do the numbers match?
