### ISSUE TITLE
Save/load using .freeze() and .thaw()

### ISSUE THREAD

**Issue by Flamekebab** [instaloader/instaloader#1023]
Perhaps a silly question but a bit too generic to be easy to search for. There's some example code ([here](https://instaloader.github.io/module/nodeiterator.html)):
```
post_iterator = profile.get_posts()
try:
    for post in post_iterator:
        do_something_with(post)
except KeyboardInterrupt:
    save("resume_information.json", post_iterator.freeze())
```

Similarly:
```
post_iterator = profile.get_posts()
post_iterator.thaw(load("resume_information.json"))
```
The save/load functions don't exist as far as I can tell - are they pseudo code suggesting I should be implementing my own save functions? (Using [save_structure_to_file()](https://instaloader.github.io/module/structures.html#instaloader.save_structure_to_file)? That doesn't seem to exist either and gives a NameError)

Is there something additional I should be importing, other than instaloader itself?

**Comment by aandergr** [comment]
[save_structure_to_file()](https://instaloader.github.io/module/structures.html#instaloader.save_structure_to_file) is part of the instaloader module.

The following functions do not exist:
- do_something_with(post: Post)
- load(path: str) -> FrozenNodeIterator
- save(path: str, fni: FrozenNodeIterator)
