### ISSUE TITLE
Can Python module trap for 429 errors?

### ISSUE THREAD

**Issue by mpgraber** [instaloader/instaloader#1024]
I'm having fun playing with the Python module, but I'm curious if there is a way to trap for the http return values such as 429?  I'd like to log the event and pause the program myself, retrying/resuming on my own logic.

Pseudocode:

`While not 429
     do stuff here
     do more stuff

Log 429 Event
Close out
Wait()
Resume
`

Suggestions appreciated.

**Comment by aandergr** [comment]
When a request is responded with 429, Instaloader's rate controller is called to handle that. You could override the rate controller handle_429() method to raise an exception instead. See https://instaloader.github.io/module/instaloadercontext.html#ratecontroller
