### ISSUE TITLE
File naming convention based on img/post unique identifier

### ISSUE THREAD

**Issue by christoarmani** [instaloader/instaloader#1027]
Your question here...
Is there a setting to request when downloading files that it saves the files by their unique identifier? 
Such as: "99setups_149969160_1146170729172548_643197991318992924_n" for example? This would also apply to stories, igtv, etc.
If there isn't a way could this be a feature to add?

**Comment by Showmaster3000** [comment]
Have a look at the parameter `--filename-pattern`
manual: https://instaloader.github.io/basic-usage.html#filename-specification
