### ISSUE TITLE
Download images with mentions 

### ISSUE THREAD

**Issue by Masterjacker17** [instaloader/instaloader#1028]
I am want to download all images of a profile with mentions in caption but cannot do it. Can you please help

**Comment by aandergr** [comment]
See https://instaloader.github.io/basic-usage.html#filter-posts.

**Comment by Masterjacker17** [comment]
> See https://instaloader.github.io/basic-usage.html#filter-posts.

i did but shows error..can you give the command, for eg i want to download all pics with "@test" mentioned in caption

**Comment by aandergr** [comment]
I wrote that part of the documentation, so I'm afraid I cannot explain it any better than that. Sorry.
