### ISSUE TITLE
Option to get files oldest to newest

### ISSUE THREAD

**Issue by voegel916** [instaloader/instaloader#103]
Downloading takes newest files first, and results in 429 error after around 300 pictures. Using --fast-update, it stops at most recently downloaded. Is there option to get oldest first?

**Comment by Showmaster3000** [comment]
You can use --only-if for that case and filter by date. examples:
```
only elements with date after 2017
   --only-if="date_utc.year>2017"
only elements before given timestamp
   --only-if="date_utc.timestamp()<1506816000" 
```
All elements that do not match the filter are skipped. Look at the documentation for more details.

**Comment by voegel916** [comment]
I don't recall seeing from reading earlier, but thank you for pointing it out. I used the filter for date and utc timestamps, but it still read files that had already been downloaded, which again gave a 429 error at the same file as before. If I add --fast-update, it acknowledges the filter but still gets the newest image and ends.

Did I enter this wrong? The option I used was:

--only-if="date_utc.timestamp()<20170513014703"

**Comment by voegel916** [comment]
Strangely enough, I updated the newest version that came today and the issue is gone. I've been able to get all the photos without any error. Thank you for help!

**Comment by Showmaster3000** [comment]
You misunderstood how a timestamp is build. You entered a date combined from YYYYMMDDHHMMSS. Thats wrong. A timestamp counts the seconds passed since 01.01.1970. So the timestamp of your date is 1494640023. You can use https://www.epochconverter.com for generating timestamps from a date.

**Comment by aandergr** [comment]
> Is there option to get oldest first?

Instagram returns the posts newest first, and unfortunately, I am not aware of any manner to reverse the orden.
