### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by daniqueosinga** [instaloader/instaloader#1034]
Hi there,
I seem to get this message every time I try to log in ConnectionException: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/104893176/3GfFuvotw6/ - follow the instructions, then retry.

Logging in does not seem to be working for me. How do I fix this?

**Comment by Showmaster3000** [comment]
Too less information to help you.
maybe problem described in #984 or #849 or #741 or #985

**Comment by daniqueosinga** [comment]
I tried using the Firefox script but it says: 
SystemExit: No Firefox cookies.sqlite file found. Use -c COOKIEFILE. While I have instagram open in another page on firefox. I just don't seem to be able to log in

**Comment by Showmaster3000** [comment]
Did you try to use the -c COOKIEFILE option which is mentioned in the error message? If your firefox profile has another path as the default ones in the script, then nothing happens.
See here: https://instaloader.github.io/troubleshooting.html#login-error

And again: you gave too less information to help you!  Issue will be closed soon.

**Comment by daniqueosinga** [comment]
I am sorry for giving not enough information, I am new to this. Do you know how I can use the -c COOKIEFILE option? 

Do I need to download my cookies from instagram or does the code do this? I am not sure what to change In the code mentioned here: https://instaloader.github.io/troubleshooting.html#login-error. because if I just run the code it does not seem to be working.

**Comment by daniqueosinga** [comment]
I have found the path but if I insert this line in the def get cookie file part:  
"Darwin": "/Users/daniqueosinga/Library/Application Support/Firefox/Profiles/8lllf4nx.default-release/cookies.sql

It still says it can not find a cookie file. I am using google colab online is that a problem? How can I surpass this problem I really need to scrape instagram data

**Comment by daniqueosinga** [comment]
It worked!!

**Comment by daniqueosinga** [comment]
Oh no never mind it does work and now stores a session file to /root/.local/share/jupyter/runtime/kernel-2aa62854-3dc9-4eeb-9751-a99adcc74b16.json. 
But how can I use this session file to login or use the load session from file option? I can not seem to find the file to put in the L.load_session_from_file function and L.login still does not seem to work.

**Comment by Showmaster3000** [comment]
How about reading the manual?
https://instaloader.github.io/basic-usage.html#basic-usage
https://instaloader.github.io/as-module.html
As we still don't know much about your setup, this is the last reminder for that. Afterwards the issue will be closed
