### ISSUE TITLE
[Regression] Story Downloading is artificially rate limited

### ISSUE THREAD

**Issue by Liz-chan** [instaloader/instaloader#1035]
**Describe the bug**
Using 4.5.5, I would never hit a rate limit, but with 4.6.2, I get the "Too many queries in the last time" message even though I have always downloaded stories fine without the rate controller limiting me.

**To Reproduce**
1. Use 4.6.2 (:stories) to try to download the stories of around 100 accounts, or just a lot of stories in general.

**Expected behavior**
I don't get rate limited and it lets me download the stories.

**Error messages and tracebacks**
"Too many queries in the last time, wait 20 minutes" or something similar.

**Instaloader version**
4.6.2

**Additional context**
I use a custom setup to download all the stories from my account (:stories with marking stories as read), and it has always worked fine to download all the stories from my account. The rate controller started to limit me on 4.6.2, and downgrading to 4.5.5 seems to have fixed the issue, so it seems the rate controller is incorrectly rate limiting story downloading when it fact it's almost impossible to hit the limit under normal usage. I follow over 1.5k accounts and I've never been rate limited with my setup before now.

**Comment by Thammus** [comment]
Pull Request #712 introduced downloading of high quality story images that require additional requests. The rate control behavior has not changed, but because of these additional requests Instaloader has to wait more. It is a good trade-off to accept longer download times for higher quality images.
This change was released with version 4.6.

**Comment by Liz-chan** [comment]
Would it be possible to have an option to choose whether to download high quality images vs the ones that don't get rate limited?

**Comment by Thammus** [comment]
Yes, a flag to skip the additional requests for fetching higher quality story images could be nice to have. Such a functionality could also be useful for choosing quality of video posts (as suggested in #1022) or profile pics. One possibility to implement such a feature is to introduce a flag that skips all iPhone queries which are the ones that are stricter rate limited and are used to retrieve the higher quality images/videos.

**Comment by Liz-chan** [comment]
> One possibility to implement such a feature is to introduce a flag that skips all iPhone queries which are the ones that are stricter rate limited and are used to retrieve the higher quality images/videos.
That would actually be pretty great since currently it's kind of tricky to download a profile with more than 1k posts, since Instaloader goes over the posts you've already downloaded if you restart, it never really goes past 1.1k or so without getting hard rate limited.

**Comment by Thammus** [comment]
Would you be willing to create a pull request with the necessary changes?

**Comment by Liz-chan** [comment]
> Would you be willing to create a pull request with the necessary changes?

I would but I don't really know how to program haha, hopefully someone else improves it in the future.
