### ISSUE TITLE
get_comments() limited to 49 comments

### ISSUE THREAD

**Issue by josarago** [instaloader/instaloader#1036]
Awesome tool!

I'm trying to download comments from a post of my own account. The post has 389 comments but I can only download 49 using the `get_comments()`. Any way around this?

**Comment by emily2h** [comment]
Following. Does it only get comments that are not replies to other comments? That's been my experience I believe.

**Comment by josarago** [comment]
> Following. Does it only get comments that are not replies to other comments? That's been my experience I believe.

That's the case but that's expected behavior. What I'm describing is for a post for which most comments are NOT replies.
