### ISSUE TITLE
Scraping Follower and Follows

### ISSUE THREAD

**Issue by andrewsegas** [instaloader/instaloader#1038]
Your question here...
Is not possible anymore to get a list of Follows and Followers of someone?
If it is possible without selenium, please, can someone help me?
Thank you

**Comment by Deleora** [comment]
> If it is possible without selenium

Hi, have you been able to do this using selenium?

**Comment by andrewsegas** [comment]
> > If it is possible without selenium
> 
> Hi, have you been able to do this using selenium?

Just logged in and following the account
