### ISSUE TITLE
Instaloader no longer downloads. Failed to parse

### ISSUE THREAD

**Issue by artcer** [instaloader/instaloader#1039]
**Describe the bug**
Instaloader no longer downloads posts, stories or any other Instagram content.

**To Reproduce**
e.g. `instaloader joebiden`

**Expected behavior**
Download all posts from user joebiden feed.

**Error messages and tracebacks**
`JSON Query to joebiden/feed/: Failed to parse: https://www.instagram.com/joebiden/feed/ [retrying; skip with ^C]`
`JSON Query to joebiden/feed/: Failed to parse: https://www.instagram.com/joebiden/feed/ [retrying; skip with ^C]`
`joebiden: JSON Query to joebiden/feed/: Failed to parse: https://www.instagram.com/joebiden/feed/`

`Errors or warnings occurred:`
`joebiden: JSON Query to joebiden/feed/: Failed to parse: https://www.instagram.com/joebiden/feed/`

**Instaloader version**
4.6.2

**Additional context**
Everything worked fine before, but today without changing anything stopped working. I'm running on Ubuntu 20.10. I tried reinstalling instaloader, I tried rebooting pc, I tried to use another user-agent, I tried removing instagram account from instaloader (~/.config/instaloader/) but nothing helps. Tested on another machine (Linux Mint 20.1) and on that machine works fine. Don't know what happened on Ubuntu :(

**Comment by aandergr** [comment]
I just tried Instaloader on a fresh Ubuntu 20.10 and it works just fine. We cannot give any support for problems related to your system setup here.
