### ISSUE TITLE
Variable in stdoutput

### ISSUE THREAD

**Issue by jtauert** [instaloader/instaloader#104]
Hi there,

in my recent log file, I saw that a username / internal variable is not outputted correctly:
`Profile {} changed its name. If you use --login=USERNAME, I can find out the new name.`

Greetings

edit:

Instaloader breaks when a profile could not be found and then tries to lookup for the new name. When I use my instagram credentials, instaloader stops and returns: `return metadata['entry_data']['ProfilePage'][0]['graphql'], metadata
KeyError: 'ProfilePage'`

**Comment by aandergr** [comment]
Duplicate of #95
