### ISSUE TITLE
Scrapping All Comments into a Single CSV File?

### ISSUE THREAD

**Issue by Sherlock21B0** [instaloader/instaloader#1041]
First of all hats off to the developers of instaloader, there are just the real avengers out there. Bringing pure magic to us looking to hoard and scrap Instagram.

Is there any way to scrap comments from a profile directly into a CSV? instaloader does this by generating separate .json file per post. So I was looking if there is a way to modify the code in order to generate one CSV file that contains all the comments on all the posts of a user profile.

Also, if it's possible that the csv contains post Id, along with its corresponding post caption, tags Comments text, commenter username? And make the post link, and commenter username clickable? that would be super awesome. I know these are too advance things to ask but would love to see if anyone helps us with this. If someone could help me out on this, that would be really great. TIA

P.s. Also, is it possible to scrap FB groups like instaloader scraps user profiles? Would love to hear your thoughts on it, if there are other python scripts that can do it, and you guide me towards it, that would be great.

P.s.s. Make sure it's easy to run from CLI Windows CMD.

 @Deleora your help will be really appreciated sir!

An excerpt from the Basic CSV Should look something like this ...

Comments | username
-- | --
Precious! 😍👏🔥 | matildacerepi

While the advance CSV should look something like this...

Post ID | Caption | Created at | Tags | Comments | Commented_by
-- | -- | -- | -- | -- | --
CL4EkP2hM68 | A Tsavorite Garnet I set in a this Art Deco design. | 07-04-17 7:09 | #tsavorite#handmadejewelry #oneofkindjewelry #harryroastudio #gems#engagementrings #bezelsetting #tiffanysetting #tsavoritegarnet | Precious! 😍👏🔥 | matildacerepi

**Comment by Sherlock21B0** [comment]
Also, @Deleora did a wonderful job of modifying the code to Scrap Usernames of Followings and Followers of an Insta Profile. Is it possible to scrap a follower's number of followings and followers data too to the CSV? How many extra requests would be made to achieve that? 


Followings  | Has Followers | Has Followings
-- | -- | --
JamesAnderson | 5000 | 80

something like this.

**Comment by Sherlock21B0** [comment]
An excerpt from the Basic CSV Should look something like this ...

Comments | username
-- | --
Precious! 😍👏🔥 | matildacerepi


While the advance CSV should look something like this...

Post ID | Caption | Created at | Tags | Comments | Commented_by
-- | -- | -- | -- | -- | --
CL4EkP2hM68 | A Tsavorite Garnet I set in a this Art Deco design. | 07-04-17 7:09 | #tsavorite#handmadejewelry #oneofkindjewelry #harryroastudio #gems#engagementrings #bezelsetting #tiffanysetting #tsavoritegarnet | Precious! 😍👏🔥 | matildacerepi

**Comment by Deleora** [comment]
> First of all hats off to the developers of instaloader, there are just the real avengers out there. Bringing pure magic to us looking to hoard and scrap Instagram.
> 
> Is there any way to scrap comments from a profile directly into a CSV? instaloader does this by generating separate .json file per post. So I was looking if there is a way to modify the code in order to generate one CSV file that contains all the comments on all the posts of a user profile.
> 
> Also, if it's possible that the csv contains post Id, along with its corresponding post caption, tags Comments text, commenter username? And make the post link, and commenter username clickable? that would be super awesome. I know these are too advance things to ask but would love to see if anyone helps us with this. If someone could help me out on this, that would be really great. TIA
> 
> P.s. Also, is it possible to scrap FB groups like instaloader scraps user profiles? Would love to hear your thoughts on it, if there are other python scripts that can do it, and you guide me towards it, that would be great.
> 
> P.s.s. Make sure it's easy to run from CLI Windows CMD.
> 
> @Deleora your help will be really appreciated sir!
> 
> An excerpt from the Basic CSV Should look something like this ...
> 
> Comments	username
> Precious! 😍👏🔥	matildacerepi
> While the advance CSV should look something like this...
> 
> Post ID	Caption	Created at	Tags	Comments	Commented_by
> CL4EkP2hM68	A Tsavorite Garnet I set in a this Art Deco design.	07-04-17 7:09	#tsavorite#handmadejewelry #oneofkindjewelry #harryroastudio #gems#engagementrings #bezelsetting #tiffanysetting #tsavoritegarnet	Precious! 😍👏🔥	matildacerepi

This thing is freaking huge mann!!!
I'll get to the point tho, I don't think modifying the Instaloader code itself would be a good idea because what you want is a very specific use case and I don't think there are many others out there who would use such a feature if implemented. 
My suggestion would be to parse the downloaded JSON files (the ones containing comments ofc) and extract comments post-by-post into a separate CSV file. After looking at the structure of comments JSON file I can say that "Basic CSV" can be done quite easily. It contains both the fields you want your CSV to have.
However, to get your CSV in "advance CSV" format you'll have to use both the JSON files downloaded along with post media as the first 4 columns are saved in the other JSON file.

All in all, since you have all the required data already fetched on your computer (thanks to Instaloader), you simply need to create a script that would parse the JSON files and save the needed data into desired CSV files.

**Comment by Deleora** [comment]
> Also, @Deleora did a wonderful job of modifying the code to Scrap Usernames of Followings and Followers of an Insta Profile. Is it possible to scrap a follower's number of followings and followers data too to the CSV? How many extra requests would be made to achieve that?
> 
> Followings	Has Followers	Has Followings
> JamesAnderson	5000	80
> something like this.
> 
> That's something separate from the above.

I didn't actually "modify" the Instaloader code, I simply used it's already implemented features and a little bit of coding to get the job done. Please don't give me all the credit for things i didn't even do <_feeling embarrassed_> 😅

Anyways, I think it should be possible but I can't be sure about it. And right now I've got my hands full so can't experiment too

**Comment by Sherlock21B0** [comment]
How about we compile the data into CSV. All the comments directly exported to CSV. Opening multiple JSON is a laborious process, so somehow if there is already a script out there or this one is modified a little to generate the data into CSV, that would be super amazing!

And can you guide me towards the code where all the Comments.Jsons generated are exported to CSV? That would be ultra awesome!

**Comment by Sherlock21B0** [comment]
The coders of this script are the real-world Avengers! 

Oops my bad, I didn't know that, but still you Sir are very helpful in the issues section, and making it easy to understand for all us newbies and non-coders here.

Love you all, for inspiring us.

**Comment by Sherlock21B0** [comment]
Another side question, is Instagram automation completely dead, or its still possible to Auto Follow and Unfollow? As I am hearing Insta is slamming accounts showing Non-Humanly Interacted behavior, but in the age of AI there must be some way to do it.

If you can share some resources from Github or any other place on the internet that would be great!

**Comment by aandergr** [comment]
> Another side question, is Instagram automation completely dead, or its still possible to Auto Follow and Unfollow?

We have little knowledge about interacting with Instagram here, that's outside of Instaloader's scope. Instaloader does not change any of the online data.

> The coders of this script are the real-world Avengers!

Thanks ❤️

> Oops my bad, I didn't know that, but still you Sir are very helpful in the issues section, and making it easy to understand for all us newbies and non-coders here.

Absolutely! We are always very amazed to see that people in our community efficiently help each other.
