### ISSUE TITLE
Not downloading after "Too many queries in the last time" warning

### ISSUE THREAD

**Issue by kenneth1305** [instaloader/instaloader#1042]
I am using instaloader to download comments from many posts. I understand this is a rate limit protection so that the number of queries do not reach the limit. But after the waiting time, aren't the downloading should be resumed? But once this warning appeared for the first, no more new file would be download and stored in the targeted folder.
![image](https://user-images.githubusercontent.com/79964268/109767668-d9d8b880-7c32-11eb-8580-a004b4c0e84d.png)

**Comment by Thammus** [comment]
This seems to be a post with very many comments. The comments will be written to a file only after all the comments related to the post have been retrieved. Depending on the number of comments, this can take several hours.
