### ISSUE TITLE
Android support.

### ISSUE THREAD

**Issue by unldenis** [instaloader/instaloader#1043]
Hello,

I looked for something related to this topic but I could not find anything in 950 issues.
I've been using this library on a pc for a while and so far no problem. I have been trying to use the library on android for days but it always ends up with the program crashing. I tried using AndroidStudio along with Chaquopy and Kivy too but to no avail.

Is there any way to use it for mobile or not? Or is there a dedicated API for mobile?

**Comment by Deleora** [comment]
If your goal is just to use it one mobile, you can download python IDEs like [Pydroid 3](https://play.google.com/store/apps/details?id=ru.iiec.pydroid3). Navigate to it's terminal and use Instaloader as you do on your PC.
You can use pip as usual to install Instaloader onto your device. It may take some time for you to familarize yourself with the navigation and stuff but it gets the job done.

**Comment by unldenis** [comment]
My goal is to create an apk not only to test for me. Maybe the only solution is using instaloader from a server.
