### ISSUE TITLE
When using {target} give stories their own folder

### ISSUE THREAD

**Issue by AplhaSlayer1964** [instaloader/instaloader#1044]
**Provide us a use case of the feature**
When downloading an entire Instagram profile and using {target} it give a separate folder for highlights but just puts stories with the other user posts. It would be nice if the stories also had their own folder labeled stories.  

**Describe the solution you'd like**
When using {target} it creates a sub folder for story posts and doesn't mix them with regular posts. ie what it does for highlights already.

**Describe alternatives you've considered**
Running a second command just for stories to make sure that are placed in a separate folder

**If the feature request is accepted, would you be willing to submit a pull request?**
No. sorry I'm bad at coding

**Comment by Thammus** [comment]
An alternative feature which tackles this use case in a more abstract way has been suggested in #253.

The already downloaded stories can also be moved into a separate directory afterwards, using a simple Bash script.
With having `jq` installed the following script does the job from within the target directory (`cd` into the downoaded profile first).

```bash
mkdir stories
for FILE in *.json.xz
do
    if [[ "$(xzcat $FILE | jq -r .instaloader.node_type)" == "StoryItem" ]]
    then
        mv ${FILE%.json.xz}.* stories/
     fi
done
```

**Comment by AplhaSlayer1964** [comment]
I assume I can't be using --no-metadata-json I guess I will remove that from my scripts from now on. Also is there a way to make sure the highest quality version of a post is the one downloaded?

**Comment by Thammus** [comment]
> Also is there a way to make sure the highest quality version of a post is the one downloaded?

When logged in, Instaloader is always aiming to download the best quality available.

**Comment by AplhaSlayer1964** [comment]
I know that but does it know if a lower quality version was downloaded or does it just check filenames of already downloaded photos and videos?

**Comment by Thammus** [comment]
Already downloaded posts do not get replaced by a possibly available higher quality version. Instaloader does only check the filenames in this case.

**Comment by AplhaSlayer1964** [comment]
> Already downloaded posts do not get replaced by a possibly available higher quality version. Instaloader does only check the filenames in this case.

A ok thanks for the help.
