### ISSUE TITLE
If my Instagram account gets locked because of Instaloader, how long after unlocking it can I start Instaloading again? And will it remember my progress?

### ISSUE THREAD

**Issue by Delayedgram** [instaloader/instaloader#1045]
First of all, I hear other people manage to save several profiles worth of content **_at the same time_**, without getting their accounts locked. I only want to save one. Granted it's a big one (10,000 posts). How are you guys doing this? 

As for me, I just got stopped on Instaloader with "400 Bad Request." As I expected, my account was locked and I had to reset my password. This is the second time this has happened to me, the first time was about a month ago.

I only managed to save about 4,200 of the posts I need from the profile I'm Instaloading. I'd like to start again, but one, I don't want to get my account permanently locked so that I can never Instaload again, and for two I really don't want to have to start all over from the first post. It took me like 3 days to get this far into the profile I'm trying to Instaload. Has my progress been saved? If not, is there a way I can save it?

**Comment by Delayedgram** [comment]
> I also would be interested in an answer to this - did you find something out? :)

@shufps I'm sorry, I thought I responded to this days ago. I meant to, but I got caught up in trying to review what information I was able to find out. 

First, I tried asking on Reddit, but I didn't get any responses in my thread because the r/DataHoarder mods wouldn't approve my thread. And I got tired of waiting. So I after I unlocked my account I tried Instaloading again. And it didn't remember my progress. So I closed Command Prompt and decided to go around asking knowledgeable people individually. 

One suggestion I got was, if you can, don't Instaload on an account. Just don't login. Instaload as an anonymous browser. You can't get your account locked if you don't use it. 

But that doesn't really help if you HAVE to be logged in to Instaload a certain profile. And it tends to happen to all of us eventually. So the advice there is essentially to just try and appear as human as possible when Instaloading, and as unrobotly as possible. One particular piece of advice I got was, run Instaloader until you start getting errors. Once you start getting errors, pause/cancel the Instaload with **Ctrl+C**. Then wait, like, a day. Or longer. Lay low until the heat is off. Once you've laid low a sufficient duration, re-enter your Instaloader command and it should pick up where you left off. Or, re-enter the Instaloader command but log into a fresh account. If you haven't had your account locked and your Instaloader run subsequently bollixed, it should remember your progress.

I haven't tried it yet though.

**Comment by mpgraber** [comment]
I've added some counters and loops to my download routine.  Once I hit a max, I pause for a random amount of time.  I've found this greatly reduces the account checkpoints.  It does slow down the overall downloads, but I'd rather deal with slow AFK process than a fast one that requires regular intervention.  I added per-profile limits as well as per-session limits to look more human-like.

**Comment by Delayedgram** [comment]
> I've added some counters and loops to my download routine. Once I hit a max, I pause for a random amount of time. I've found this greatly reduces the account checkpoints. It does slow down the overall downloads, but I'd rather deal with slow AFK process than a fast one that requires regular intervention. I added per-profile limits as well as per-session limits to look more human-like.

@mpgraber are you doing this manually, or is there something you put in your string to make that happen? 

Me, I'm doing it manually. I run Instaloader for about 30 minutes, or until I see "Too many queries in the last time." Then I abort and wait, like, a day. Or half a day. Once early in the morning, and then again in the evening.

**Comment by mpgraber** [comment]
@Delayedgram I wrote a python script to fetch and update a list of profiles - kids sports teams, etc.  Then I pick and choose some to send to their grandparents' digital picture frames.  Here's the key part of the code:

`   profile = instaloader.Profile.from_username(loader.context, target.name)
    posts = profile.get_posts()
    status = ""
    for post in takewhile(lambda p: p.date > target.start_date, posts):
        session.tries += 1
        if post.shortcode in logged:
            target.skip += 1
            session.skip += 1
            # print("skipping", post.shortcode, session.skip)
        else:
            if loader.download_post(post, target=target.name):
                logged.append(post.shortcode)
                session.get += 1
                target.get += 1
                wait = random.randint(2,9)
                print("(", threading.current_thread().getName(), ") pausing fetch", wait)
                time.sleep(wait)
            else:
                print(post.shortcode, "should be skipped next time....")
                logged.append(post.shortcode)
                session.check += 1
                target.check += 1
            session.total += 1
        if (target.get >= target.max_get or target.check >= target.max_check):
            status = "Profile Limit "
            fetch_updates[target.name] = logged
            wait = 20
            print("(", threading.current_thread().getName(), ") Profile Limit, delaying next", wait)
            time.sleep(wait)
            return status
        if (session.get >= session.max_get or session.check >= session.max_check):
            status = "Session Limit "
            fetch_updates[target.name] = logged
            print(status)
            return status`

**Comment by Delayedgram** [comment]
I was supposed to manually stop Instaloader when I hit a "Too many queries" message. But I fell asleep and left it running. And so I hit the much harsher 429 Error. So I hit Ctrl+C and let it sit until I restarted it a few hours later.

But see, within about 30 minutes or so I'm supposed to get a "Too many queries" notice. It's been hours now and I haven't. It's too quiet. I feel like I've been lulled into a false sense of security by Instagram.

**Comment by Delayedgram** [comment]
Alright, thanks to careful stopping and starting, I managed to save the profile I was trying to save. Now, is there an intuitive way to keep my archive updated?

**Comment by AplhaSlayer1964** [comment]
--fast-update

**Comment by AplhaSlayer1964** [comment]
> @Delayedgram I wrote a python script to fetch and update a list of profiles - kids sports teams, etc. Then I pick and choose some to send to their grandparents' digital picture frames. The code didn't format well when I pasted it, so I'm attaching a snippet.
> [snippet.txt](https://github.com/instaloader/instaloader/files/6243423/snippet.txt)

Would you mind posting the full scrip if you don't mind I'm interested in maybe modifying and using it myself.

**Comment by mpgraber** [comment]
@AplhaSlayer1964 @Delayedgram here are the  files.  You can skip / comment the refresh_target process if you want - i wanted to fetch the most recent posts first, so I have it work backwards in time, year by year.  Not needed for most profiles.

You'll need to update the working path and file locations, as well as the login credentials IF any profiles require following and if you want hi quality downloads.  Let me know if you have questions.  Happy to help.
[targets2.txt](https://github.com/instaloader/instaloader/files/6290209/targets2.txt)
[refresh_target.py.txt](https://github.com/instaloader/instaloader/files/6290210/refresh_target.py.txt)
[grabber_v4.py.txt](https://github.com/instaloader/instaloader/files/6290211/grabber_v4.py.txt)
