### ISSUE TITLE
Comments not being scraped

### ISSUE THREAD

**Issue by Bowis** [instaloader/instaloader#1047]
Im trying to scrape all the comments associated with a post like so:

```
import instaloader
L = instaloader.Instaloader()
allComments = []

for post in instaloader.Hashtag.from_name(L.context, 'cat').get_posts():
    L.download_post(post, target='#cat')
    post.get_comments()
```

However, no comments, or 1 random comment is being scraped. Executing instaloader -C '#cat' gives the same results. What am I doing wrong?

**Comment by aandergr** [comment]
> However, no comments, or 1 random comment is being scraped. Executing instaloader -C '#cat' gives the same results.

What do you expect instead? Most of these posts do not have any comments.
