### ISSUE TITLE
Download most recent 5 post pictures

### ISSUE THREAD

**Issue by aidynabirov** [instaloader/instaloader#1048]
How is it possible to download only recent 5 post pictures? 

I've looked through the issues(both closed and open), but could not find my answer. I've tweaked several parameters, like max_count, total_count, etc, but it doesn't work. 
I noticed there was a discussion related to the specific timeline of the posts', but in my case, I don't need a timeline, I just need a recent 5 posts. 

I'm sorry If I haven't noticed somewhere in the issues. 
Thank you!

**Comment by aidynabirov** [comment]
Solved this problem, thanks a lot!

**Comment by miclejackson12** [comment]
Can you share your solution.

**Comment by miclejackson12** [comment]
Anyways  for anyone else who needs it, here is my solution https://github.com/miclejackson12/instaloader/commit/7a2621bf5971a128ba690e6d9e8b33396cc4d16e
The maintainers of this repo are so stubborn that they would never merge it, I have been saying then for more than a year now.
