### ISSUE TITLE
Is it possible to download just the photo thumbnails from a user's feed?

### ISSUE THREAD

**Issue by satvug** [instaloader/instaloader#1049]
Hey everyone, thanks for making this kickass project!

I am curious - is it possible to just download thumbnails instead of the fullsize photos of each post in a user's feed?
For my usage, I just need to download the photo thumbnails.

Right now, I am downloading all the full size images and resizing and cropping them myself, which seems unnecessary.

Is it possible to just download the thumbnails?

Thanks a lot.

**Comment by aandergr** [comment]
In the JSON files that Instaloader saves there is a field `.node.thumbnail_src`. This contains a URL that you could download e.g. with wget.

So you could first run Instaloader to get the post metadata files only:
```
instaloader profile --no-videos --no-pictures --no-profile-pic
```

and then download all post thumbnails with wget:

```bash
cd profile

for FILE in *.json.xz
do
    wget -O ${FILE%.json.xz}_thumbnail.jpg "$(xzcat $FILE | jq -r .node.thumbnail_src)"
done
```
