### ISSUE TITLE
Implementation download profile pic in java failed!

### ISSUE THREAD

**Issue by ahmadsl** [instaloader/instaloader#105]
hi, i want implement dowload profile posts in java. but i get 403 error! what's wrong in my code?

`        String urlToRead = "https://www.instagram.com/snapp/";
        String graphqlUrl = "https://www.instagram.com/graphql/query";
        URL url = null;
        try {
            url = new URL(urlToRead);

            Request request = new Request.Builder()
                    .url(url)
                    .build();
            OkHttpClient client = new OkHttpClient();
            Response response = client.newCall(request).execute();
            MessageDigest md5 = MessageDigest.getInstance("MD5");

            System.out.println(response.request());

            Document doc = Jsoup.parse(response.body().string());
            Elements json = doc.select("script");
//            System.out.println(json);
            String jsonstr = json.toString();
            jsonstr = jsonstr.substring(jsonstr.indexOf("window._sharedData = "),jsonstr.length());
            jsonstr = jsonstr.substring(0,jsonstr.indexOf("</script>"));
            jsonstr = jsonstr.replace("window._sharedData = ","");
            jsonstr =  jsonstr.substring(0,jsonstr.length()-1);

            System.out.println(jsonstr);

            String str = jsonstr;
            JSONObject obj = new JSONObject(str);
            JSONObject profileMetaData = obj.getJSONObject("entry_data").getJSONArray("ProfilePage").getJSONObject(0).getJSONObject("graphql").getJSONObject("user");
            Integer postCount = profileMetaData.getJSONObject("edge_owner_to_timeline_media").getInt("count");
            String first , after, id, rhx_gis;
            first = "12";
//            query_id = 17888483320059182;
            after = profileMetaData.getJSONObject("edge_owner_to_timeline_media").getJSONObject("page_info").getString("end_cursor");
            id = String.valueOf(profileMetaData.getInt("id"));
            rhx_gis = obj.getString("rhx_gis");

            String valuesForHash = rhx_gis + ":{\"id\":\""+id.toString()+"\",\"first\":12,\"after\":\""+after+"\"}\n";
            String x_instagram_gis = (new HexBinaryAdapter()).marshal(md5.digest(valuesForHash.getBytes()));
            Thread.sleep(3000);
            request = new Request.Builder().
                    addHeader("x-instagram-gis",x_instagram_gis)
                    .addHeader("accept","*/*")
                    .addHeader("authority","www.instagram.com")
                    .addHeader("scheme","https")
                    .addHeader("Set-Cookie","ig_pr=2")
                    .addHeader("referer",urlToRead)
                    .addHeader("ig_vw","1920")
                    .url(new URL(graphqlUrl))
                    .build();

            System.out.println(response.headers());
            System.out.println(request.headers());

            response = client.newCall(request).execute();
            System.out.println(response);

            profileMetaData.getJSONObject("edge_owner_to_timeline_media").getJSONObject("page_info").getBoolean("has_next_page");
            profileMetaData.getJSONObject("edge_owner_to_timeline_media").getJSONObject("page_info").getString("end_cursor");

`

**Comment by aandergr** [comment]
Does not seem at all related to Instaloader.
