### ISSUE TITLE
Flag to only show downloaded content

### ISSUE THREAD

**Issue by ready2r** [instaloader/instaloader#1056]
I follow about 20 users, i think a useful feature would be a flag that will make the output only display images downloaded and not "already exists"

It would make it easier to glance at a finished script run and know exactly which users uploaded new content.  If this is already a thing, can you point me in the correct direction? i scanned though the documentation and saw that you had a --quiet tag but from my understanding, it will only output errors?

**Comment by aandergr** [comment]
Please use our [Feature Suggestion Template](https://github.com/instaloader/instaloader/issues/new?labels=feature+suggestion&template=feature_request.md) for suggesting new features, as this makes it easier to see how the new feature could fit into Instaloader.
