### ISSUE TITLE
Support for Termux Android Terminal ??

### ISSUE THREAD

**Issue by waihankan** [instaloader/instaloader#1058]
**Describe the bug**
I'm trying to use instaloader in ***android terminal (Termux)**. The installation is fine, but when I call the `instaloader profile`, it just stop working, like nothing's happening. May be there is some errors with writing files, finding a specific folder or something like that?

**To Reproduce**
`instaloader [username]`

**Expected behavior**
It should start working like on the computer. It should start downloading the profile data.

**Error messages and tracebacks**
There's no error messages. Nothing returns, just freezing.

**Instaloader version**
4.6.2

**Comment by aandergr** [comment]
not reproducible; works for me.
