### ISSUE TITLE
Please help me understand how to use the resume function I dont understand 😖 

### ISSUE THREAD

**Issue by MicroJacksn** [instaloader/instaloader#1061]
Hello this is my first post and I wanted some help on how to resume a previously interrupted profile download. 

when I tried to do `--login=user --resume-prefix prefix profile user` and  `--login=user --resume-prefix iterator profile user`
it always started the download from the beginning 1/2728 when I was at around 1,000/2728

I have looked on days at examples of the `--resume-prefix` command being used but I still can't get it to work. I have looked on many websites and forums about instaloader and this specific question but I couldn't get it to work so I hope I can get some help.

I'm very new to code so maybe thats why I can't figure out what in doing wrong.

**Comment by AplhaSlayer1964** [comment]
How did you exit the command prompt? Did you just close it of ctrl+c? When you ctrl+c instaloader will create a file so it know where to resume. It does not work if you just close the instaloader process.

**Comment by MicroJacksn** [comment]
ah okay i think i did close it once using ctrl+c but that was while ago, so i guess i just have to start over the download again then use ctrl+c kinda as a save point and then i can resume from there?
