### ISSUE TITLE
Image Quality Degraded

### ISSUE THREAD

**Issue by schleeb** [instaloader/instaloader#1065]
I stumbled across this by accident, since I'm not normally looking at pictures downloaded via other means, but once I did, I ran a few comparisons to confirm.
**Describe the bug**
Images downloaded via Instaloader appear to be slightly degraded in quality compared to images downloaded via other means.
It's easy to miss at a glance, but if you look at the comparison images below, you should note the images downloaded via Instaloader are blurrier.

**To Reproduce**
Download an image via Instaloader
Download the same image (at the same resolution) via other means (e.g. GreaseMonkey/TamperMonkey Image Max URL script).
Compare the images.

**Expected behavior**
The downloaded images are in the highest quality available.

**Instaloader version**
4.6.2

Instaloader Image: 
![2021-03-09_20-44-36_UTC_2](https://user-images.githubusercontent.com/69768494/112253638-77714780-8c35-11eb-8544-a93f7643e4ea.jpg)

Image Max URL Image:
![194655658_madisonbeer-20210309-0002](https://user-images.githubusercontent.com/69768494/112253655-80faaf80-8c35-11eb-9839-e4b578752c0d.jpg)

**Comment by aandergr** [comment]
Thanks for reporting! This is fixed in version 4.7.1.
