### ISSUE TITLE
New 12 post limit?

### ISSUE THREAD

**Issue by tmcpheeters** [instaloader/instaloader#1067]
**Describe the bug**
For new profiles being downloaded, there seems to be a redirect after the 12th post has been retrieved.
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/

**To Reproduce**
instaloader  --no-compress-json --no-profile-pic --no-captions --fast-update --dirname-pattern=model____/{profile} --filename-pattern={profile}_{date_utc} nikirjensen2

**Expected behavior**
Would expect all posts to load as previously has happened.

**Error messages and tracebacks**
root@localhost:/igfiles# instaloader  --no-compress-json --no-profile-pic --no-captions --fast-update --dirname-pattern=model____/{profile} --filename-pattern={profile}_{date_utc} nikirjensen2
Stored ID 25974047476 for profile nikirjensen2.
Hint: Use --login to download higher-quality versions of pictures.
Retrieving posts from profile nikirjensen2.
[ 1/72] model____/nikirjensen2/nikirjensen2_2021-03-26_20-15-28.jpg json
[ 2/72] model____/nikirjensen2/nikirjensen2_2021-03-23_20-07-00.jpg model____/nikirjensen2/nikirjensen2_2021-03-23_20-07-00.mp4 json
[ 3/72] model____/nikirjensen2/nikirjensen2_2021-03-22_20-36-41.jpg json
[ 4/72] model____/nikirjensen2/nikirjensen2_2021-03-19_19-04-25.jpg model____/nikirjensen2/nikirjensen2_2021-03-19_19-04-25.mp4 json
[ 5/72] model____/nikirjensen2/nikirjensen2_2021-03-17_19-23-29.jpg json
[ 6/72] model____/nikirjensen2/nikirjensen2_2021-03-16_19-20-46.jpg model____/nikirjensen2/nikirjensen2_2021-03-16_19-20-46.mp4 json
[ 7/72] model____/nikirjensen2/nikirjensen2_2021-03-15_20-13-10.jpg json
[ 8/72] model____/nikirjensen2/nikirjensen2_2021-03-14_17-42-20.jpg model____/nikirjensen2/nikirjensen2_2021-03-14_17-42-20.mp4 json
[ 9/72] model____/nikirjensen2/nikirjensen2_2021-03-12_19-02-56.jpg json
[10/72] model____/nikirjensen2/nikirjensen2_2021-03-10_21-23-54.jpg json
[11/72] model____/nikirjensen2/nikirjensen2_2021-03-07_17-56-16.jpg json
[12/72] model____/nikirjensen2/nikirjensen2_2021-03-05_16-36-18.jpg json

HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
nikirjensen2: Redirected to login page. Use --login.

Errors or warnings occurred:
nikirjensen2: Redirected to login page. Use --login.

**Instaloader version**
4.7rc2

**Additional context**

**Comment by Showmaster3000** [comment]
Maybe Instagram changed what you can do without login.
There is no problem if you use --login as mentioned in the error message.

**Comment by aandergr** [comment]
I cannot reproduce this, the command works fine for me.

However, there has been a report that accessing the posts of a profile anonymously can lead to a 302 redirect (#1013), without a solution yet.

**Comment by artcer** [comment]
It's the IP problem. Today I also faced this problem. I downloaded 3 different posts from the same user and when I tried to download 4th post, I've got an error:
```
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
-: Redirected to login page. Use --login.

Errors or warnings occurred:
-: Redirected to login page. Use --login.
```

Of course, it works when you login with any account. But if you want to continue downloading Instagram posts without login, you should just simply change your IP (at least it works for me). I guess Instagram blacklisted your IP so it will not allow to download any post without login. So using VPN you should be able to download any post without login. I'm using Android Hotspot to get different IP address in my laptop and it works, instaloader downloads Instagram posts without login and previous error doesn't disappear.

**Comment by tmcpheeters** [comment]
Tried logging in and now it seems my account has been deleted... Any suggestions on getting it back?

**Comment by tmcpheeters** [comment]
OK to close.
