### ISSUE TITLE
how to set filenamepattern

### ISSUE THREAD

**Issue by frederik2000x** [instaloader/instaloader#1068]
i just started using instaloader and i want to change the filename pattern of all content i used this:"instaloader --login=myusername --filename-pattern={profile}/{date_utc:%Y}/{shortcode} :stories @profile" 
This is the error i get: 
+ instaloader --filename-pattern={profile}/{date_utc:%Y}/{shortcode}
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParameterBindingException
    + FullyQualifiedErrorId : ParameterSpecifiedAlready

**Comment by John147GHN** [comment]
This happens to me too, changing to other certain patterns changes the error to:

`error: unrecognized arguments: -encodedCommand cAByAG8AZgBpAGwAZQA= -inputFormat xml -outputFormat text`

The encoded command code will difer but it certainly doesn't work at all.

**Comment by lapourgagner** [comment]
> 
> 
> i just started using instaloader and i want to change the filename pattern of all content i used this:"instaloader --login=myusername --filename-pattern={profile}/{date_utc:%Y}/{shortcode} :stories @Profile"
> This is the error i get:
> 
>     * instaloader --filename-pattern={profile}/{date_utc:%Y}/{shortcode}
> 
>     * ```
>         + CategoryInfo          : InvalidArgument: (:) [], ParameterBindingException
>         + FullyQualifiedErrorId : ParameterSpecifiedAlready
>       ```

It seems you use Powershell, so you probably need to escape shell arguments with something like `instaloader "--filename-pattern={profile}/{date_utc:%Y}/{shortcode}"` or `instaloader --filename-pattern="{profile}/{date_utc:%Y}/{shortcode}"`

**Comment by John147GHN** [comment]
>--filename-pattern="{profile}/{date_utc:%Y}/{shortcode}"`

I can confirm this one worked out for me.
