### ISSUE TITLE
How to get comments for a specific post

### ISSUE THREAD

**Issue by ItafAHMADI** [instaloader/instaloader#1070]
Hello, I would like to find a way to download the comments for a specific post. Any help would be appreciated.

Thanks

**Comment by santinmike** [comment]
I am fairly new to python and I am using the Instaloader package to play around and learn more about it. To download comments I think you need to do it with the `get_comments()` method of the `post` class to iterate with a for loop over the comments in a post. You can check it out in more detail in the documentation in this link: https://instaloader.github.io/module/structures.html#posts

I hope it works
