### ISSUE TITLE
Is it possible to resume hashtag downloads?

### ISSUE THREAD

**Issue by EpiPhobe** [instaloader/instaloader#1071]
I tried 

`post_iterator = instaloader.Hashtag.from_name(L.context, 'hashtag').get_posts()
`

and

`post_iterator.freeze()`

and got the following error:

`AttributeError: 'generator' object has no attribute 'freeze'`

**Comment by aandergr** [comment]
Hi,

> Hashtag.get_posts() does not currently support to resume the iteration due to not using a graphql pagination. However, it seems we can get a [resumable iterator](https://instaloader.github.io/module/nodeiterator.html) for the recent hashtag posts like this:
> 
> ```python
> post_iterator = instaloader.NodeIterator(
>     L.context, "9b498c08113f1e09617a1703c22b2f32",
>     lambda d: d['data']['hashtag']['edge_hashtag_to_media'],
>     lambda n: instaloader.Post(L.context, n),
>     {'tag_name': HASHTAG},
>     f"https://www.instagram.com/explore/tags/{HASHTAG}/"
> )
> ```
> 
> With that, you can use [resumable_iteration()](https://instaloader.github.io/module/nodeiterator.html#resumable-iteration) as usual.

_(from https://github.com/instaloader/instaloader/issues/874#issuecomment-731561430)_
