### ISSUE TITLE
Tagged Stories downloaded in low quality s150x150

### ISSUE THREAD

**Issue by maxiannunziata** [instaloader/instaloader#1073]
**Describe the bug**
When i tag a #hashtag in a storie and try filter and download it by instaloader the downloaded image is a preview of the story and not the storie in HQ
  
**To Reproduce**
Publish a story with the hashtag #myowntestxxxx  
instaloader --post-filter="'myowntestxxxx' in caption_hashtags and date_utc >= datetime(2021, 2, 1)" "#myowntestxxxx"

**Expected behavior**
Download the image or video tagged story in HQ

**Instaloader version**
4.7.1

**Comment by aandergr** [comment]
Getting the stories of a hashtag is not yet implemented (#455).
