### ISSUE TITLE
Resumable iterations are failing since SAVE is not defined

### ISSUE THREAD

**Issue by emrahbaysal** [instaloader/instaloader#1075]
**Describe the bug**
Resumable iterations do not work since the save and load functions are not available

**To Reproduce**
post_iterator = profile.get_posts()
try:
    for post in post_iterator:
        do_something_with(post)
except KeyboardInterrupt:
    save("resume_information.json", post_iterator.freeze())

**Expected behavior**
Saving the state same as described in the below documentation.
https://instaloader.github.io/module/nodeiterator.html#nodeiterator

**Error messages and tracebacks**
    save("resume_information.json", followers.freeze())
NameError: name 'save' is not defined

**Instaloader version**
4.7.1

**Comment by aandergr** [comment]
Thanks for your issue. We had practically the same question in #1023, therefore I have now extended the documentation on this point.

In that example, the following functions do not exist:
- do_something_with(post: Post)
- load(path: str) -> FrozenNodeIterator
- save(path: str, fni: FrozenNodeIterator)

You can implement appropriate load and save functions for example with Instaloader's load_structure_from_file() and save_structure_to_file().

The FrozenNodeIterator is a Namedtuple, which can also be serialized/deserialized with all the common means, e.g. Python's json or pickle modules.
