### ISSUE TITLE
Need the shortcodes of 600k+ posts from a hashtag

### ISSUE THREAD

**Issue by eglur** [instaloader/instaloader#1077]
I'm working on a project where I'll measure some characteristics of the audio from videos with a specific hashtag ("#100daysofpractice").

This hashtag has currently 600k+ posts (including images and videos).

Probably, I won't be able to measure every single one of the videos, so I'll sample a subpopublation from the total of 600k.
But for this to be fairly random, I would need the list of videos.

My first attempt was to run the pure
`instaloader "100daysofpractice"`
first without, then with login, but it kept being stopped after some time, and I needed to restart from the beginning.

I thought this was due to the size of the files being downloaded, so I tried downloading only the json file with (in a bash script that gave sequentially min and max dates):
`instaloader --login ${IG_USER} --no-profile-pic --no-pictures --no-videos --no-captions --post-filter="date_utc >= ${MIN_DATE} and date_utc < ${MAX_DATE}" "#100daysofpractice"`
but it also broke, and had to restart from beginning.                          

I then tried to [just download the shortcodes](https://github.com/bits4waves/100daysofpractice-dataset/blob/master/get-shortcodes.py), but it had the same problem.

Does anybody have any idea on how to get those pesky 600k shortcodes?

With them in hand, I would just have to download enough videos to get a good average, not all the 600k, but I can't see how I could do it without the 600k shortcodes.

Any idea is appreciated!

Thanks!

**Comment by aandergr** [comment]
One effective trick may be to use the [Resumable Iterations](https://instaloader.github.io/module/nodeiterator.html) feature. This allows to restart the download at the point where it had been interrupted the last time. The download can be manually interrupted with Ctrl+C.

However, the out-of-the-box hashtag iterator does not support the protocol required for resumable iterations. Luckily though, in #874 there is a code snippet that allows us to get a resumable iterator for hashtag posts.

In the latest version (4.7.x) we also introduced a feature to automatically abort and save the iteration state if a request is responded with a certain error code (#920). This can be invoked by adding the parameter `fatal_status_codes` to Instaloader's contructor. Passing the HTTP error codes that led to the abortion of the download can make the overall process more robust.

Putting all that together, we get:

```python
import instaloader

SHORTCODE_FILE = "shortcodes.txt"
HASHTAG = "100daysofpractice"
IG_USER = ... # (insert your username)

L = instaloader.Instaloader(fatal_status_codes=[400, 429])
L.load_session_from_file(IG_USER)

# Resumable iterator for recent hashtag posts, from #874.
hashtag_posts = instaloader.NodeIterator(
    context=L.context,
    query_hash="9b498c08113f1e09617a1703c22b2f32",
    edge_extractor=lambda d: d["data"]["hashtag"]["edge_hashtag_to_media"],
    node_wrapper=lambda n: instaloader.Post(L.context, n),
    query_variables={"tag_name": HASHTAG},
    query_referer=f"https://www.instagram.com/explore/tags/{HASHTAG}/",
)

with open(SHORTCODE_FILE, "a") as file:
    with instaloader.resumable_iteration(
        context=L.context,
        iterator=hashtag_posts,
        load=instaloader.load_structure_from_file,
        save=instaloader.save_structure_to_file,
        format_path=lambda magic: f"resume_info_{magic}.json.xz",
    ) as (is_resuming, start_index):
        if is_resuming:
            # After resuming, the first post is the last post that had been returned in
            # the previous iteration. Here we avoid that this post shortcode is
            # repeated.
            next(hashtag_posts)
        # Here we write all shortcodes to the file
        for post in hashtag_posts:
            print(post.shortcode, file=file)
```

Nevertheless, actually we are conviced that Instaloader should go through the hashtag without any problems. If that is not the case we are always curious in how exactly it breaks.

> I then tried to [just download the shortcodes](https://github.com/bits4waves/100daysofpractice-dataset/blob/master/get-shortcodes.py), but it had the same problem.

This gives a 404 for me (maybe a private repo?).

**Comment by eglur** [comment]
Thanks for your answer, and the great script!
Using it, it was possible to download 250k out of the total 600k shortcodes.
This is way more than the 50k obtained with [get-shortcodes.py](https://github.com/bits4waves/100daysofpractice-dataset/blob/master/src/get-shortcodes.py) (the previous link was indeed broken, but this should work; please let me know if it doesn't).

At 250k, it stops with:
```
(venv) rafa@bach:~/sci/100daysofpractice-dataset/src$ python -i get-hashtag.py                                                                                                                 
Loaded session from /home/rafa/.config/instaloader/session-quickgamedev.                                                                                                                       
Traceback (most recent call last):                                                                                                                                                             
  File "get-hashtag.py", line 18, in <module>                                                                                                                                                  
    query_referer=f"https://www.instagram.com/explore/tags/{HASHTAG}/",                                                                                                                        
  File "/home/rafa/sci/100daysofpractice-dataset/venv/lib/python3.7/site-packages/instaloader/nodeiterator.py", line 90, in __init__                                                           
    self._data = self._query()                                                                                                                                                                 
  File "/home/rafa/sci/100daysofpractice-dataset/venv/lib/python3.7/site-packages/instaloader/nodeiterator.py", line 99, in _query                                                             
    self._query_hash, {**self._query_variables, **pagination_variables}, self._query_referer                                                                                                   
  File "/home/rafa/sci/100daysofpractice-dataset/venv/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 430, in graphql_query                                               
    session=tmpsession)                                                                                                                                                                        
  File "/home/rafa/sci/100daysofpractice-dataset/venv/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 328, in get_json                                                    
    host, path, resp.status_code, resp.reason, redirect                                                                                                                                        
instaloader.exceptions.AbortDownloadException: Query to https://www.instagram.com/graphql/query responded with "400 Bad Request"                                                               
>>>                                                                                                                                                                                            
(venv) rafa@bach:~/sci/100daysofpractice-dataset/src$                  
```

**Comment by aandergr** [comment]
Nice, I am glad that it worked fine and that we could help!

> One question, though: the search bar on instagram.com that there's 614,795 posts with the hashtag "#100daysofpractice", but
> the program downloaded 449,851.
> Is there a known explanation for this?
> Maybe Instagram only counts the hashtags at the time of posting, not editing and removing a hashtag or deleting a post?

There are some known guesses for this:
- Maybe the count includes private posts, but the listing doesn't; similarly, there are posts that require that the age of the viewer is verified
- Sometimes, posts that are too old are not included in the list of all hashtags
- Maybe the count is just not accurately kept track of and only a rough estimation (for databases the scale of Instagram, keeping an exact count causes much stress on the database)
