### ISSUE TITLE
Python script for conditional downloading story images

### ISSUE THREAD

**Issue by akasaa101** [instaloader/instaloader#1078]
Is there a way for download items with condition? 
For example if ctaUrl = "asd" download metadata and story, 
but if there is no ctaUrl download metadata without story.

My code snippet: 

```
    for story in loader.get_stories():
        for item in story.get_items():
            story_details = item._asdict()
            cta_url = story_details['story_cta_url']
            if cta_url is not None:
                if "asd" in cta_url:
                    loader.download_storyitem(item, ':stories')
                else:
                   (JUST DOWNLOAD METADATA)
```

**Comment by Deleora** [comment]
The snippet you shared isn't working?

**Comment by akasaa101** [comment]
Working now but actually I asking for How can I download metadata without story image?

**Comment by Deleora** [comment]
By metadata do you mean the `JSON` file of the `story_item`?

**Comment by akasaa101** [comment]
yes

**Comment by aandergr** [comment]
Maybe you are looking for [save_structure_to_file()](https://instaloader.github.io/module/structures.html#instaloader.save_structure_to_file) or [save_metadata_json()](https://instaloader.github.io/module/instaloader.html#instaloader.Instaloader.save_metadata_json)?
