### ISSUE TITLE
can i bruteforce acc

### ISSUE THREAD

**Issue by morpheuslord** [instaloader/instaloader#1079]
can u modify this to bruteforce acc? and can i use this in windows system?

see it is straight a great tool it worked in kali i didnt check in windows so i asked the secound question and i wanted to ask can u modify this to bruteforce acc if this can it will be a huge thing as it opens other ways to hack websites

thank u

**Comment by MrJmpl3** [comment]
I believe that the purpose of this program is different, it is not to hack or bruteforce.

And this works in Windows
