### ISSUE TITLE
I made a matrix / element room for instaloader

### ISSUE THREAD

**Issue by artiblaster** [instaloader/instaloader#1081]
I'm not sure if you use matrix / element. If you do, you can be the admin. #instaloader:matrix.org

**Comment by aandergr** [comment]
I think this is a good idea, giving our community the option for a faster-paced communication; however, personally I'm not using matrix/element and I'm generally not so much of a chat guy.

We could ['pin' this issue](https://docs.github.com/en/github/managing-your-work-on-github/pinning-an-issue-to-your-repository) for a while, if you want, to give this idea more attention, and allow the channel to gain traction.
