### ISSUE TITLE
hashtag bulk download

### ISSUE THREAD

**Issue by sunnydev3301** [instaloader/instaloader#1082]
when i bulk a Hashtag it downloads also a   .json and a .txt file how can I prevent to download also them and faster my download?

i use this command line:  $ instaloader "#bugsbunnychallenge"
on macos bigsur

**Comment by Showmaster3000** [comment]
I think you search for parameters ``--no-captions`` and ``--no-metadata-json`` ([source](https://instaloader.github.io/cli-options.html#what-to-download-of-each-post)). But using them does not make the process faster apart from not writing these files to disk.
