### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by osamaburashed** [instaloader/instaloader#1087]
I tried using 

instaloder profile [ target accout] 

And 

instaloder [ target account]

But in both cases, it told me 

NOTE: its privet a account 

`JSON Query to profile/feed/: 404 Not Found [retrying; skip with ^C]
JSON Query to profile/feed/: 404 Not Found [retrying; skip with ^C]
profile: Profile profile does not exist.
The most similar profiles are: icons.30, matchingpfp_, matchingpfp, _photo_de_profile_290, photo__de____.profile_.
Warning: Use --login to download higher-quality versions of pictures.
hfcn.jjb/2018-11-21_19-35-46_UTC_profile_pic.jpg already exists
hfcn.jjb: --login=USERNAME required.

Errors or warnings occurred:
profile: Profile profile does not exist.
The most similar profiles are: icons.30, matchingpfp_, matchingpfp, _photo_de_profile_290, photo__de____.profile_.
Warning: Use --login to download higher-quality versions of pictures.
hfcn.jjb: --login=USERNAME required.
`
``

**Comment by Deleora** [comment]
For accessing private accounts you need to login using `--login` attribute
For example, if your username is _**my_username_123**_ and the target profile's is _**target_username_123**_
then you can use this simple command line instruction to access the profile:

`instaloader --login my_username_123 target_username_123`

Then it'll prompt you to enter your instagram password which you won't be able to see getting typed (for security reasons of course)

**Comment by Deleora** [comment]
> instaloder **profile** [ target accout]

Btw this ☝🏻 is not a valid command at all. The **profile** word is not required and this is why you got this message

> profile: Profile **profile** does not exist.
