### ISSUE TITLE
Could not find "window._sharedData" in html response.

### ISSUE THREAD

**Issue by clb92** [instaloader/instaloader#109]
I'm getting a new error suddenly.

My command looks like this:

    python3.6 instaloader.py --login=USERNAME --password=PASSWORD --max-connection-attempts 1 --fast-update --no-video-thumbnails --stories-only --dirname-pattern=instagram-stories/{target} ANY_USERNAME_HERE

The full error returned is:

    JSON Query to ANY_USERNAME_HERE/: Could not find "window._sharedData" in html response.

**Comment by clb92** [comment]
Forgot to update and try newer version. Sorry about that. Will report back again in a moment...

**Comment by clb92** [comment]
Nope, still getting the error in 3.3.10

**Comment by clb92** [comment]
Am I going crazy, or is it working fine again now?

**Comment by klatif01** [comment]
Strange, working again :-)

**Comment by clb92** [comment]
Probably a temporary backend problem at Instagram. Closing the issue for now.

**Comment by aandergr** [comment]
Glad it works again. Thanks for reporting.

Feel free to reopen this issue if the problem reappears.

**Comment by iliv** [comment]
I'm having this problem with 4.2.10. As I mention in #495 I was able to download full copy of my personal account two times on the same day. Then came back a couple days after that to try to download geotags and I started to see this error message every time I try to download my profile:

```
$ instaloader --login=myinstagramusername --geotags profile --stories
Loaded session from /tmp/.instaloader-iliv/session-myinstagramusername.
Logged in as myinstagramusername.
JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
profile: JSON Query to profile/: Could not find "window._sharedData" in html response.
Saved session to /tmp/.instaloader-iliv/session-myinstagramusername.

Errors occured:
profile: JSON Query to profile/: Could not find "window._sharedData" in html response.
```

Can somebody, please, explain what this error means?

Does anyone else experience this very problem currently?

**Comment by en3rgetic** [comment]
> 
> 
> I'm having this problem with 4.2.10. As I mentioned in #495 I was able to download full copy of my personal account two times on the same day. Then came back a couple days after that to try to download geotags and I started to see this error message every time I try to download my profile:
> 
> ```
> $ instaloader --login=myinstagramusername --geotags profile --stories
> Loaded session from /tmp/.instaloader-iliv/session-myinstagramusername.
> Logged in as myinstagramusername.
> JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
> JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
> profile: JSON Query to profile/: Could not find "window._sharedData" in html response.
> Saved session to /tmp/.instaloader-iliv/session-myinstagramusername.
> 
> Errors occured:
> profile: JSON Query to profile/: Could not find "window._sharedData" in html response.
> ```
> 
> Can somebody, please, explain what this error means?
> 
> Does anyone else experience this very problem currently?

I have the same issue, (Used os Windows 10)

**Comment by iliv** [comment]
"Good"! :D Not good, but glad to hear it's not just my problem.

**Comment by dinoalesandro** [comment]
yeah same problem, hope someone can give solution about this problem

**Comment by FucaBala** [comment]
Same problem here.
The issue I have is that I can download the images from some profiles and other ones are working fine.
I'm using Windows 10 and calling the instaloader trough python, the code I'm using is below:

            # Create the instance of Instaloader and provide basic information
            L = instaloader.Instaloader()                               # Create the instance
            L.login(USERNAME, PASSWORD)                                 # Provide username and password
            L.load_session_from_file(USERNAME)                          # Reconnect using the cookie if username/pass were provided previously
            L.dirname_pattern = PATH[2:] + 'images/instagram/{profile}' # Path to save the images
            L.download_videos   = False                                 # Do not download videos
            L.download_pictures = True                                  # Download pictures
            L.compress_json     = False                                 # Leave as false otherwise the JSON files will be compressed into .GZ files
            L.save_metadata     = False                                 # Download JSON metadata of the post (can be used for advanced analysis)
            L.download_comments = False                                 # Download the comments from the followers
    
            # Download the posts related to images and only download the ones within the timeframe
            profile = instaloader.Profile.from_username(L.context, v_instagram_profile_name)
            for post in profile.get_posts():
                if post.date >= PERIOD:
                    print(post)
                    L.download_post(post, v_instagram_profile_name)

**Comment by FucaBala** [comment]
Hello,

This is an update for the tests I performed.

I changed my internet IP address and executed the code on a different computer just to test a possible BAN from Instagram and the error was still the same.

The test I tried was to authenticate using the username and password instead of the authorization cookie and then everything started to work again.

On the code posted above, I simply commented the line below and the issue was fixed for me.
        L.load_session_from_file(USERNAME)                          # Reconnect using the cookie if username/pass were provided previously

This could be a coincidence, so is anyone facing the same issue could do a test?

Cheers.

**Comment by Walia20** [comment]
jus

> I'm having this problem with 4.2.10. As I mentioned in #495 I was able to download full copy of my personal account two times on the same day. Then came back a couple days after that to try to download geotags and I started to see this error message every time I try to download my profile:
> 
> ```
> $ instaloader --login=myinstagramusername --geotags profile --stories
> Loaded session from /tmp/.instaloader-iliv/session-myinstagramusername.
> Logged in as myinstagramusername.
> JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
> JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
> profile: JSON Query to profile/: Could not find "window._sharedData" in html response.
> Saved session to /tmp/.instaloader-iliv/session-myinstagramusername.
> 
> Errors occured:
> profile: JSON Query to profile/: Could not find "window._sharedData" in html response.
> ```
> 
> Can somebody, please, explain what this error means?
> 
> Does anyone else experience this very problem currently?

just found that account which u're trying to find is renamed or doesn't exist.

In instagram the first name through which the account is created  is saved in database 
but in actual if that account is renamed or changed it can't be found 


try finding the account on which u're getting the error . It doesn't exist in instagram

just use try and except to skip these

**Comment by kleajmp** [comment]
The same problem here, I tested it on several computers and all have the same issue. The only workaround I've found is **deleting your session data** [`C:\Users\username\AppData\Local\Instaloader\*`] **before every download command** and re entering your password, which works but is really annoying.

Anyone found a real solution?

**Comment by kiranaananda** [comment]
I've tried dharun02 method today and it still appears.

**Comment by photogugi** [comment]
I was using this from 2021 but I don't get any error but now it's October 2023 and I am getting this error! Came to know that same thing is keep happening again and again like I see that problem from 2018. So maybe some backend problem! Hope it gets fix soon!!!
