### ISSUE TITLE
Only downloading the profile picture?

### ISSUE THREAD

**Issue by jasonhan-vassar** [instaloader/instaloader#1100]
Hi, I'm reading the documentation and I don't think it describes a way to only download a user's profile picture. Something like `instaloader profile` will download a user's posts in addition to their profile picture. Can someone help me do this? Thanks for reading.

**Comment by Showmaster3000** [comment]
the profile pic is downloaded by default.
You only need to exclude the posts, which you can do by using the parameter `--no-posts`
see manual: https://instaloader.github.io/cli-options.html#what-to-download-of-each-post

**Comment by jasonhan-vassar** [comment]
Thanks, that was simple!
