### ISSUE TITLE
A new command for downloading the post that has uploaded by my followees on that day

### ISSUE THREAD

**Issue by zehad2871** [instaloader/instaloader#1101]
The followees of any user's account are not small.
The followees upload many posts every day.
If a command was given to download the posts of any specific date, that would save many times.

In a nutshell, A command that will find all the posts posted on the very specified date of all my followees.

**Comment by lapourgagner** [comment]
Have a look at [--post-filter](https://instaloader.github.io/cli-options.html?highlight=post%20filter#cmdoption-post-filter), probably with [date_utc](https://instaloader.github.io/module/structures.html#instaloader.Post). You should have something like `--post-filter="date_utc <= datetime(2018, 5, 31)"`. You can find examples [here](https://instaloader.github.io/basic-usage.html#filter-posts).

**Comment by aandergr** [comment]
Please use our [Feature Suggestion Template](https://github.com/instaloader/instaloader/issues/new?labels=feature+suggestion&template=feature_request.md) for suggesting new features, as this makes it easier to see how the new feature could fit into Instaloader.
