### ISSUE TITLE
Resume download from post number? Or other ways to get around error 22 using captions as filenames

### ISSUE THREAD

**Issue by yohandsome** [instaloader/instaloader#1102]
I'm using captions as filename with the following command, useful when downloading paintings:

instaloader --filename-pattern="{caption:.255}" profile example

But this breaks when filenames uses disallowed characters for NTFS filenames I believe, and my workaround is to restart download a day or two before the creation date of the last image with --post-filter="date_utc <= datetime(2020, 6, 24)"

Is there a way to specify the post number to resume from? OR Is there a way to either ignore posts that throw error 22, or even replace the characters that break filename as was discussed here: https://www.gitmemory.com/issue/instaloader/instaloader/262/479178345

**Comment by Showmaster3000** [comment]
Apart of #262 you refered, you can download the posts with the default filename and use a separate script reading the caption from the txt-file, adjust the string to a valid filename and rename the post media.  Also, you can just combine instaloader as module with this step. The only thing you need to memorize is the last post you downloaded if you use the parameter `--fast-update`.

**Comment by yohandsome** [comment]
Thanks, not a bad idea using a separate script and could probably figure it out, only issue is that I have 0 experience with Python and very little with coding, do you have such a script perhaps?

**Comment by Showmaster3000** [comment]
No, I don't have such a script, it was just a theoretical idea to solve your problem.

If you google a bit, you can find the parts you need.
A function for cleaning the caption to use as filename f.e. is described here: https://gist.github.com/wassname/1393c4a57cfcbf03641dbc31886123b8
Reading caption txt file and renaming media can be done with core python functions.
Be careful, the file extension counts to the max length of the file, so the caption max length can be 251 chars. Another thing is the max length of path and file, I currently don't know the max value, afaik there was a change in recent Windows version.
