### ISSUE TITLE
Windows command can't run

### ISSUE THREAD

**Issue by iminet** [instaloader/instaloader#1104]
Hi All,

Can anybody help me, why this windows command can't run properly?
In Linux, this works well.

```
PS E:\tmp> instaloader -F -q --login='felixcsabok' --sessionfile='S:\Instagram\.session\session-felixcsabok' --dirname-pattern=S:\Instagram\{target} --filename-pattern '{profile}_{date_utc}' --stories --no-videos --no-captions --no-metadata-json manchesterunited
usage:
instaloader [--comments] [--geotags] [--stories] [--highlights] [--tagged]
            [--login YOUR-USERNAME] [--fast-update]
            profile | "#hashtag" | %location_id | :stories | :feed | :saved
instaloader --help
instaloader: error: unrecognized arguments: -encodedCommand manchesterunited -inputFormat xml -outputFormat text
PS E:\tmp>
```

Thanks in advance.

**Comment by hgkmaxymus** [comment]
Hello,

To me, you should use the "-F" and "-q" after the login, session, directories, etc, but it might not be required, of course.

Also, your `dirname-pattern` has no quote (') and the `filename-pattern` has no equal (=).

**Comment by iminet** [comment]
> Hello,
> 
> To me, you should use the "-F" and "-q" after the login, session, directories, etc, but it might not be required, of course.
> 
> Also, your `dirname-pattern` has no quote (') and the `filename-pattern` has no equal (=).

Hi,

You're right, those mistakes caused the problem. I fixed the dirname-pattern and the filename-patter, now everything works well. That's my mistake.
Thanks for your kind help!

**Comment by iminet** [comment]
I close this issue, because you offered a solution. Thanks again 🙂
