### ISSUE TITLE
[Feature] Save stories in a separate folder

### ISSUE THREAD

**Issue by rm1410** [instaloader/instaloader#1108]
It is currently difficult to distinguish stories from normal posts. To avoid this it would be helpful to save all stories in an extra folder, like it happens with tagged-posts.

**Additional context**
This would also fix the bug that if a story has the same name as a post the post is not saved and the download aborts if "--fast-update" was used.

**Comment by aandergr** [comment]
Please use our [Feature Suggestion Template](https://github.com/instaloader/instaloader/issues/new?labels=feature+suggestion&template=feature_request.md) for suggesting new features, as this makes it easier to see how the new feature could fit into Instaloader.

This is probably what would be solved with #253.
