### ISSUE TITLE
profile-pic-only

### ISSUE THREAD

**Issue by gnu-like** [instaloader/instaloader#111]
instaloader version 4 instead of downloading profile picture it produces `json.xz`

**Comment by mullier** [comment]
for me, it saves the picture, the metadata and the json file. however, unlike the other files which get proper UTC-matched date, the json file's modification date matches its creation date and thus is always the most recent. maybe that's why you thought it only saved jsons?

**Comment by gnu-like** [comment]
@mullier it doesn't save the picture only saves json
