### ISSUE TITLE
I keep getting the 429 Too Many Requests even though I tried the --max-connection-attemps parameter

### ISSUE THREAD

**Issue by mikewakawski** [instaloader/instaloader#1111]
Instaloader was working normally yesterday but when I tried it this morning it started downloading as usual then it just stopped and threw the `429 Too Many Requests Unable to fetch high quality image version`. I got that error this morning, I waited for sometime but i still got the same error and then I reran it after 6 hours or so but still the same thing happened.

The problem is when what I run this:
`instaloader --login ynotkys10 --max-connection-attempts 20 blkblssm`

I get this error:
`
C:\Users\A\Documents\scraper>instaloader --max-connection-attempts 20 --login ynotkys10 blkblssm
Loaded session from C:\Users\Adam\AppData\Local\Instaloader\session-ynotkys10.
Logged in as ynotkys10.
blkblssm\2020-08-16_08-57-33_UTC_profile_pic.jpg already exists
Retrieving posts from profile blkblssm.
Resuming from blkblssmi\iterator_xXaCpYfS.json.xz.
[190/647] JSON Query to api/v1/media/2212557887939281166/info/: 429 Too Many Requests [retrying; skip with ^C]
Number of requests within last 10/11/20/22/30/60 minutes grouped by type:
   d6f4427fbe92d846298cf93df0b937d3:    1    1    1    1    1    1
                              other:    1    1    1    1    1    1
                           iphone:    2    2    2    2    2    2
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 30 minutes, at 19:30.
`

I'm running the latest version(4.7.1). What should I do?

**Comment by aandergr** [comment]
Welcome to the community! Please see [Reporting Bugs](https://instaloader.github.io/contributing.html#reporting-bugs) for how to report a bug. There is little chance to understand an issue if the requested information is missing.
