### ISSUE TITLE
Download stories by shortcode

### ISSUE THREAD

**Issue by alisentinel** [instaloader/instaloader#1113]
As I found there is no way to download stories by shortcode (url). mentioned in #921 & #856 
e.g:
https://www.instagram.com/stories/highlights/17888433850617062/
https://www.instagram.com/stories/cats_of_instagram/2559020971962868562/
https://instagram.com/stories/physicsfun/2559106526795522708?utm_source=ig_story_item_share&igshid=vzbgvuszjs1m

Is it possible to download stories like post.from_shortcode()?

**Comment by Thammus** [comment]
Please use our [Feature Suggestion Template](https://github.com/instaloader/instaloader/issues/new?labels=feature+suggestion&template=feature_request.md) for suggesting new features, as this makes it easier to see how the new feature could fit into Instaloader.
