### ISSUE TITLE
Filename Profil ? Error ? 

### ISSUE THREAD

**Issue by NicotherZ** [instaloader/instaloader#1119]
Hi,
I don't really know how to use this, i use this command with windows 10 version of InstaLoader : 
.\instaloader --login=######## -- -PostNumber (for specific post) & 
.\instaloader --login=######## :stories --no-captions --no-metadata-json --no-compress-json --no-video-thumbnails (for stories)

Want to know 2 things, when i download post or stories, name file are only date, how to put automically name profil on file downloaded ?

And with the first command (for specific post) i can download pics/vid but  can't add --no-captions --no-metadata-json --no-compress-json --no-video-thumbnails to avoid download caption metadata..., i get error : 
--no-captions: Fetching Post metadata failed.
--no-metadata-json: Fetching Post metadata failed.
--no-compress-json: Fetching Post metadata failed.
--no-video-thumbnails: Fetching Post metadata failed.
Saved session to C:\######################## *(censure personal info ;p)*

Errors or warnings occurred:
--no-captions: Fetching Post metadata failed.
--no-metadata-json: Fetching Post metadata failed.
--no-compress-json: Fetching Post metadata failed.
--no-video-thumbnails: Fetching Post metadata failed.

How can i this option to work with specific post download ?

Thanks in advance for your help!

**Comment by lapourgagner** [comment]
@NicotherZ 
> how to put automically name profil on file downloaded ?

[https://instaloader.github.io/basic-usage.html#filename-specification](https://instaloader.github.io/basic-usage.html#filename-specification) ?
