### ISSUE TITLE
Need help! Can I skip the first Nth items in hashtag.get_all_posts() ?

### ISSUE THREAD

**Issue by ltc0909** [instaloader/instaloader#1120]
Hello to everyone! I am new to python and I have a question about skipping the first Nth items or resuming from what I left off earlier. 

I am trying to collect data on all posts of a hashtag, such as profile, date, caption, etc. The target hashtag has around 5000 posts. When I tried to do so, the loop stopped at around 4000 without any error messages (see below for sample codes). So, I wonder if there is a way that I can skip the first 4000 item and start to loop from 4001 to 5000? 

Thanks very much for your help!

How I did it originally (it may look stupid, feel free to give me more efficient ways!):

```
profile_dict = []
caption_dict = []
caption_hashtags_dict =[]
date_dict = []
shortcode_dict = []

for post in hashtag.get_all_posts():

    profile_dict.append(post.profile)
    caption_dict.append(post.caption)
    caption_hashtags_dict.append(post.caption_hashtags)
    date_dict.append(post.date)
    shortcode_dict.append(post.shortcode)
```

I have tried using itertools.islice but the loop stopped after just 20 items:

```
slice1 = itertools.islice(hashtag.get_all_posts(), 4001, None)
profile_dict = []
caption_dict = []
caption_hashtags_dict =[]
date_dict = []
shortcode_dict = []

for post in slice1:

    profile_dict.append(post.profile)
    caption_dict.append(post.caption)
    caption_hashtags_dict.append(post.caption_hashtags)
    date_dict.append(post.date)
    shortcode_dict.append(post.shortcode)
```

**Comment by MakiNaruto** [comment]
I hope this solution can help you.
you can use `posts.total_index` , it will return the number of post iterations, when iterations < 4000 skip it.
but it need to submit a large number of requests until you arrive 4000.
i’m looking for the other solution that program only need one times to skip Nth items,  if u found it pls answer me .
