### ISSUE TITLE
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/ 

### ISSUE THREAD

**Issue by dedio** [instaloader/instaloader#1121]
When i try to scrape some profile using python:

bot = instaloader.Instaloader()
bot.login('user', 'password')
profile = instaloader.Profile.from_username(bot.context, 'username')

I get this redirect

"HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/ "

Why is this happening?
How can I solve it?

**Comment by dumprop** [comment]
Try to change IP address
Probably banned

**Comment by dedio** [comment]
Thanks, I will try it.
