### ISSUE TITLE
Instagram CDN blockedaccess: Notsameorigin

### ISSUE THREAD

**Issue by OfirPearl** [instaloader/instaloader#1124]
**Describe the bug**
Hi All, I'm using instaloader for the past few month now to scrape data for my website (I'm using post.url directly in my <img> tag src attribute), and about a week ago I started getting a CORS error saying I can't display Instagram images from a different domain.

Is there a way around this? Have I done something wrong or did Instagram just hardened their policy? Thanks!

**Comment by kallewesterling** [comment]
Duplicate issue #1154.

@OfirPearl Check out my response there.
