### ISSUE TITLE
Highlights cover pictures are not the actual Highlights cover pictures!

### ISSUE THREAD

**Issue by MrJmpl3** [instaloader/instaloader#1126]
**Describe the bug**
When downloading the highlights the downloaded cover pictures do not match the ones that are showing in the web interface.

**To Reproduce**
instaloader PROFILE --highlights (--login USER --password PASS)

**Expected behavior**
I want the real cover pictures and not some size-down and cut versions of the first picture in the highlight. In the web interface I see only a 150x150 version. I do not know if there are bigger versions of these cover pictures.

**Instaloader version**
4.7.1

**Additional context**
Related
- https://github.com/instaloader/instaloader/issues/844
- https://github.com/instaloader/instaloader/issues/668

**Edit**

@aandergr Can add a param to download "cover_media_cropped_thumbnail" and "cover_media" together?

**Comment by UnixCro** [comment]
@aandergr Another question, is it possible to get a highlight cover larger than 150x150?
