### ISSUE TITLE
[question] How to ignore/exclude owner_username ?

### ISSUE THREAD

**Issue by nagualcode** [instaloader/instaloader#113]
I am crawling #hashtags, but would like to exclude a specific owner_username.
Can I do this with --post-filter= ?

**Comment by nagualcode** [comment]
or better yet: Download only 1 (the most recent) post from each user.
So a crawl with a count of -C 50 (for example) cannot get overtaken by a few users who overuse the given hashtag.

**Comment by aandergr** [comment]
> I am crawling #hashtags, but would like to exclude a specific owner_username.
Can I do this with --post-filter= ?

Yes, with `--post-filter="owner_username != 'USER'"`.

**Comment by aandergr** [comment]
> or better yet: Download only 1 (the most recent) post from each user.

You could create a `set` that contains the users of which a post has already been downloaded. When iterating the posts, check whether the post's owner already is in the set. If so, skip the post. Otherwise, download it and add the user to that set:

```python
import instaloader

L = instaloader.Instaloader()

posts = L.get_hashtag_posts('milfgarden')

users = set()

for post in posts:
    if not post.owner_profile in users:
        L.download_post(post, '#milfgarden')
        users.add(post.owner_profile)
    else:
        print("{} from {} skipped.".format(post, post.owner_profile))
```

**Comment by rinku-27** [comment]
> > or better yet: Download only 1 (the most recent) post from each user.
> 
> You could create a `set` that contains the users of which a post has already been downloaded. When iterating the posts, check whether the post's owner already is in the set. If so, skip the post. Otherwise, download it and add the user to that set:
> 
> ```python
> import instaloader
> 
> L = instaloader.Instaloader()
> 
> posts = L.get_hashtag_posts('milfgarden')
> 
> users = set()
> 
> for post in posts:
>     if not post.owner_profile in users:
>         L.download_post(post, '#milfgarden')
>         users.add(post.owner_profile)
>     else:
>         print("{} from {} skipped.".format(post, post.owner_profile))
> ```

How can this snippet be edited so that it only checks the first X posts of a user on if to download or not?

For example, on a daily basis I want to go through account 1, account 2 and account 3; For each, check the first 5 posts only and download if it hasn't been downloaded already. 

I'm hoping to reduce the number of queries sent because I get the "too many queries" wait message a lot. A lot of profiles have over 200 pictures and I'm hoping to avoid queries being used up on <skipped> posts.

**Comment by coderektor** [comment]
import instaloader

L = instaloader.Instaloader()

posts = L.get_hashtag_posts('milfgarden')

users = set()

for post in posts:
    if not post.owner_profile in users:
        L.download_post(post, '#milfgarden')
        users.add(post.owner_profile)
    else:
        print("{} from {} skipped.".format(post, post.owner_profile))

@aandergr Thank You for the above Code, It's really Helpful.
I want Your help with something: I want to skip both images, and videos. How do I Modify this code to do it?
