### ISSUE TITLE
Both a question and issue regarding multiple instances.

### ISSUE THREAD

**Issue by ERasnier** [instaloader/instaloader#1134]
Does the multiple instance issue specifically occur within a single computer or does it also include multiple computers within a network? 

I'm getting a continuous report of an 'other' instance that's preventing me from using it. It might've been a cronjob that I setup a while ago which I have since deleted but it might also be that I've been viewing Instagram on another computer.

This seemingly only happens on a per account basis. If I use a different account it works fine.

**Comment by AplhaSlayer1964** [comment]
Pretty sure it's by account and ip
