### ISSUE TITLE
email as username is not valid username

### ISSUE THREAD

**Issue by neutrongenious** [instaloader/instaloader#1142]
**Describe the bug**
Instagram user with email as username, throws error:
Errors or warnings occurred:
Warning: Parameter "abc@xyz.com" for --login is not a valid username.

**To Reproduce**
- use instaloader command line with --login=user@domain.com
- Warning: Parameter "user@domain.com" for --login is not a valid username.

**Expected behavior**
- Should pick up cookie and proceed with download.

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

**Instaloader version**
4.7.1

**Comment by Showmaster3000** [comment]
As already described in #624, the login with your e-mail-address is not supported. Please use your nickname.

**Comment by neutrongenious** [comment]
worked fine.

May be it's better to add this in error description.
