### ISSUE TITLE
How do I set the download location/path in the Python Module?

### ISSUE THREAD

**Issue by andyluu9** [instaloader/instaloader#1147]
I haven't found any solutions for this in Python, only for CLI. The code that I currently have is 

instance = instaloader.Instaloader()
    user = input ('What is the username: ')
    userpic = instance.download_profile(user, profile_pic_only=True)

**Comment by yassinbenmansour** [comment]
асс = input('Enter the Account Username: ')
    test.download_profile(acc, profile_pic_only = True)
