### ISSUE TITLE
Running multiple lines for each user vs using single text file

### ISSUE THREAD

**Issue by AplhaSlayer1964** [instaloader/instaloader#1149]
Does anyone know if the amount of api requests is greater having multiple cli commands running one after another for each user versus just having it read all users from a text file? The reason I have it like this is because if there is a dead account in my list that wasn't already recorded the program stops on the 404 (or at least it did last time I tried a few versions back). Also has the highlights name conflict been fixed? That is another reason I have each user have its own command since some names would break instalaoder.

**Comment by aandergr** [comment]
> Does anyone know if the amount of api requests is greater having multiple cli commands running one after another for each user versus just having it read all users from a text file?

It depends. It might be slightly more efficient in terms of the amount of API requests when using a single Instaloader invocation. E.g. when downloading stories, Instaloader accesses the stories of multiple profiles in one API request. Generally, if you have two alternative methods of doing one thing, an easy way to determine which one requires more requests is to run both with a [profiler](https://docs.python.org/3/library/profile.html) and compare the number of calls to [InstaloaderContext.get_json()](https://instaloader.github.io/module/instaloadercontext.html#instaloader.InstaloaderContext.get_json). In https://github.com/instaloader/instaloader/issues/1130#issuecomment-844966388 there is an example for that.

> Also has the highlights name conflict been fixed?

I think there wasn't any fix regarding highlight name conflicts in the last time. We always record the updates in the respective bugs, so it's best to look there for more accurate information.

**Comment by AplhaSlayer1964** [comment]
Well it seems that when running all my users in the args.txt file on some users it breaks the instaloader session and the whole thing fails. It seems to happens when a user is banned. It tried searching for the user and got sent to the login page and just hangs there as far as I can tell.

**Comment by AplhaSlayer1964** [comment]
ok so not really sure if it is due to not running instaloader on a vpn or moving all accounts into a single command but it seems to take much longer before the account gets locked. I believe it mainly has to do with the vpn but since a 404 doesn't end instaloader anymore I'm switching to just having it all in one command now.
