### ISSUE TITLE
Login error: JSON decode fail, 403 - Forbidden.

### ISSUE THREAD

**Issue by tndgpp** [instaloader/instaloader#1150]
**Describe the bug**
Today I tried to login from two different accounts, from different IPs, and received a login error, 429 forbidden.

**To Reproduce**
`instaloader --login <username> profile nasa`

**Expected behavior**
I expected to login and start downloading posts.

**Error messages and tracebacks**
Using above command line, I receive this:
`Fatal error: Login error: JSON decode fail, 403 - Forbidden.`

Using module, I get:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/instaloader/instaloadercontext.py", line 224, in login
    resp_json = login.json()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/ig-login.py", line 57, in <module>
    L.login(USER, PASSWORD)
  File "/usr/local/lib/python3.7/dist-packages/instaloader/instaloader.py", line 546, in login
    self.context.login(user, passwd)
  File "/usr/local/lib/python3.7/dist-packages/instaloader/instaloadercontext.py", line 228, in login
    ) from err
instaloader.exceptions.ConnectionException: Login error: JSON decode fail, 403 - Forbidden.
```

**Instaloader version**
4.7.1

**Additional context**
If I try to login via web or via app, I don't have any problems. My accounts seem perfectly fine. Also, without logging in, e.g.
`instaloader nasa`
I can download posts, so I guess my IP range is not banned.

**Comment by santinmike** [comment]
I have the exact same problem. I noticed the issue just now.

**Comment by cschwem2er** [comment]
Can confirm that this issue also happens on our end. Any idea what's going on here?

**Comment by fatpandaclub** [comment]
Same issue here.

**Comment by Javieralonb** [comment]
Same for me.

**Comment by JeanRomain** [comment]
Same for me

**Comment by r3538987** [comment]
Sounds like they changed something on their (IG) side, and application have no idea how to handle new stuff. 
Just an assumption.

**Comment by JeanRomain** [comment]
@r3538987 I agree

**Comment by JSerwart** [comment]
I have the exact same problem, anyone an idea how to solve it?

**Comment by DZweek** [comment]
Same here

**Comment by adamcheasley** [comment]
Just ran into the same issue.

**Comment by geekysid** [comment]
I am a freelancer from India and I am facing no such issues.... But one of my clients in France is facing the same issue... Could it be a Geographical issue?? But then again my other scripts which use different Instagram APIs seem to be working fine at his end... Can anyone please help???

**Comment by Javieralonb** [comment]
It seems to be Geographical. I'm in Europe and login fails when I try to execute. But if I use a Jupyter Notebook, login works just fine.

**Comment by Showmaster3000** [comment]
As a workaround for those having the login problem, you can use the script described in https://instaloader.github.io/troubleshooting.html#login-error
I also had the problem this morning and going this way to create the session file just works fine for me.

**Comment by cschwem2er** [comment]
> As a workaround for those having the login problem, you can use the script described in https://instaloader.github.io/troubleshooting.html#login-error
> I also had the problem this morning and going this way to create the session file just works fine for me.

Thanks, this works on my end as well! :) Still hoping for a permanent fix for this issue though.

**Comment by DZweek** [comment]
> As a workaround for those having the login problem, you can use the script described in https://instaloader.github.io/troubleshooting.html#login-error
> I also had the problem this morning and going this way to create the session file just works fine for me.

This worked for me as well, thanks a lot for the fix!

**Comment by r3538987** [comment]
Logged via Firefox.
Imported cookie via script.
Started login process again, and still same error. 

I'm in EU. Will wait for other suggestions. )

**Comment by rbochenski** [comment]
It looks that facebook require one more parameter.
with request:

URL: https://www.instagram.com/accounts/login/ajax/facebook/

We can receive hmac signature
x-ig-set-www-claim: hmac.A...3

And this needs to be used further requests to ask for resources.

**Comment by santinmike** [comment]
The workaround did not work for me. I guess I am doing something wrong. 1) I downloaded the script in [](https://instaloader.github.io/troubleshooting.html#login-error ), 2) logged in to Instagram in Firefox, and 3) I ran the the script using the terminal in my macbook. However, I receive the following error: 

"Not logged in. Are you logged in successfully in Firefox?"

What am I missing?

**Comment by santinmike** [comment]
The workaround did not work for me. I guess I am doing something wrong. 1) I downloaded the script in , 2) logged in to Instagram in Firefox, and 3) I ran the the script using the terminal in my macbook. However, I receive the following error:

"Not logged in. Are you logged in successfully in Firefox?"

What am I missing?

**Comment by Javieralonb** [comment]
> The workaround did not work for me. I guess I am doing something wrong. 1) I downloaded the script in https://instaloader.github.io/troubleshooting.html#login-error, 2) logged in to Instagram in Firefox, and 3) I ran the the script using the terminal in my macbook. However, I receive the following error:
> 
> "Not logged in. Are you logged in successfully in Firefox?"
> 
> What am I missing?

I had the same problem with this. Changing the profile worked.
In the line 15 of the script you have this:
`"Windows": "~/AppData/Roaming/Mozilla/Firefox/Profiles/*/cookies.sqlite"`

I changed it for this and it created the session file succesfully:
`"Windows": "~/AppData/Roaming/Mozilla/Firefox/Profiles/vglfs64j.default-release/cookies.sqlite"`

If this doesn't work for you try other profiles that are in your path. 
I hope it helps.

**Comment by santinmike** [comment]
> > The workaround did not work for me. I guess I am doing something wrong. 1) I downloaded the script in https://instaloader.github.io/troubleshooting.html#login-error, 2) logged in to Instagram in Firefox, and 3) I ran the the script using the terminal in my macbook. However, I receive the following error:
> > "Not logged in. Are you logged in successfully in Firefox?"
> > What am I missing?
> 
> I had the same problem with this. Changing the profile worked.
> In the line 15 of the script you have this:
> `"Windows": "~/AppData/Roaming/Mozilla/Firefox/Profiles/*/cookies.sqlite"`
> 
> I changed it for this and it created the session file succesfully:
> `"Windows": "~/AppData/Roaming/Mozilla/Firefox/Profiles/vglfs64j.default-release/cookies.sqlite"`
> 
> If this doesn't work for you try other profiles that are in your path.
> I hope it helps.

It seems for me it was a problem with Firefox cookies as describe din #877. It seems that login cookies in Firefox are saved to the default directory when the browser is closed. However, in my settings I had Firefox to delete cookies every time it closes. So nothing was being saved. After disabling cookies deletion the script worked well.

**Comment by alistvt** [comment]
> As a workaround for those having the login problem, you can use the script described in https://instaloader.github.io/troubleshooting.html#login-error
> I also had the problem this morning and going this way to create the session file just works fine for me.

@Showmaster3000 I used this approach but Instagram starts logging me out after only 10 minutes!

**Comment by DeltaBravo33** [comment]
Hi,

I get the same issue, and when I try to run the script, I get this error message: 
"  File "615_import_firefox_session.py", line 26
    conn = connect(f"file:{cookiefile}?immutable=1", uri=True)
                                                                               ^
SyntaxError: invalid syntax"

Thanks in advance for your help!

**Comment by adamcheasley** [comment]
Looks like you’re trying to run it on Python 2. Since this script uses f strings you’ll need Python 3.

Adam

**Comment by nusibrains** [comment]
Same problem from Paris

**Comment by Dyegop** [comment]
Same issue here
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by shyland89** [comment]
Hi all, 

Possibly a silly question but if I'm using the firefox login method outlined above, what area of the code am I changing in get_instagram_posts?

def get_instagram_posts(username, startdate, enddate):
   # Create an instaloader object with parameters
    L = instaloader.Instaloader(download_pictures = False, download_videos = False, download_comments= False, compress_json = False)
   # Log in with the instaloader object
    L.login("username" , "password!")   
     # Search the instagram profile
    profile = instaloader.Profile.from_username(L.context, username)
       # Scrape the posts
    posts = profile.get_posts()
    for post in takewhile(lambda p: p.date > startdate, dropwhile(lambda p : p.date > enddate, posts)):
        print(post.date)
        L.download_post(post, target = profile.username)


Thanks!

**Comment by haf** [comment]
It looks like they've started encrypting the password, maybe with the public key gotten from the request to `/data/shared_data/` — the string from instaloader doesn't at all match what the browser sends anymore.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/193115/120492327-442c0100-c3ba-11eb-9fa2-9ebfa342b072.png">

**Comment by gehl-developer** [comment]
> I am a freelancer from India and I am facing no such issues.... But one of my clients in France is facing the same issue... Could it be a Geographical issue?? But then again my other scripts which use different Instagram APIs seem to be working fine at his end... Can anyone please help???

I get this error in the EU, but if I set my VPN to India everything works just fine! So thanks for the tip :)

**Comment by fatpandaclub** [comment]
> I am a freelancer from India and I am facing no such issues.... But one of my clients in France is facing the same issue... Could it be a Geographical issue?? But then again my other scripts which use different Instagram APIs seem to be working fine at his end... Can anyone please help???

I get this error in the EU, but if I set my VPN to India everything works just fine! So thanks for the tip :)

**Comment by VicPitic** [comment]
Please fix this, I am from the EU and I dont want to buy a VPN :(

**Comment by sridharmani0510** [comment]
i am also having the same issues

**Comment by sridharmani0510** [comment]
each time is try a work through either user not found comes or line 1 column 1 shows up

**Comment by Dyegop** [comment]
Can we help anyway to fix this?

**Comment by sridharmani0510** [comment]
> Can we help anyway to fix this?

can u fix it?

**Comment by cmoscertified** [comment]
The solution mentioned by @Showmaster3000 works.

Just to make sure you are doing it right,

- Login from Firefox to your account.
- Run the [script](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py). (using python3)
- Now, keep in mind that this script saves a new session file in the default directory (~/.config/instaloader/session-YOUR-USERNAME.) So, if you're NOT using the default session file make sure to point that file in your instaloader script. 

This solution works even in EU, no need to use VPN services.

**Comment by Creat1veM1nd** [comment]
Does the workaround also works when using the python module of instaloader ?

**Comment by Michounet** [comment]
I've made some small modifications to the [615_import_firefox_session.py script](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py). I don't use Firefox and my Instaloader installation is on a Linux headless server. What I do is:

- Login to my Instagram account on my usual browser
- Export cookies from Instagram in JSON format (I personally use EditThisCookie but there are many addons and extensions available)
- On a ssh remote session, I create a "cookies.txt" file and I paste the exported cookies there (you can also create the file locally and/or transfer it to your remote machine (or use it locally)
- Finally, I use the modified script to create the user session from the cookies.txt file

This fixed the login problem for me, however a permanent fix in Instaloader itself would be the best approach.

**Comment by shyland89** [comment]
> I've made some [small modifications](https://github.com/instaloader/instaloader/pull/1184) to the [615_import_firefox_session.py script](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py). I don't use Firefox and my Instaloader installation is on a Linux headless server. What I do is:
> 
> * Login to my Instagram account on my usual browser
> * Export cookies from Instagram in JSON format (I personally use EditThisCookie but there are many addons and extensions available)
> * On a ssh remote session, I create a "cookies.txt" file and I paste the exported cookies there (you can also create the file locally and/or transfer it to your remote machine (or use it locally)
> * Finally, I use the modified script to create the user session from the cookies.txt file
> 
> This fixed the login problem for me, however a permanent fix in Instaloader itself would be the best approach.

Thanks for the work around I really appreciate it! I ran your script and it executed perfectly. I'm quite new to exploring python and was just wondering where do I update the previous script to call from your portion?

def get_instagram_posts(username, startdate, enddate):
   # Create an instaloader object with parameters
    L = instaloader.Instaloader(download_pictures = False, download_videos = False, download_comments= False, compress_json = False)
   # Log in with the instaloader object
    L.login("USERNAME" , "PASSWORD")   
     # Search the instagram profile
    profile = instaloader.Profile.from_username(L.context, username)
       # Scrape the posts
    posts = profile.get_posts()
    for post in takewhile(lambda p: p.date > startdate, dropwhile(lambda p : p.date > enddate, posts)):
        print(post.date)
        L.download_post(post, target = profile.username)


import os
from datetime import datetime
# instagram username
username = 'USERNAME'
# daterange of scraping
startdate = datetime(2021, 1, 1)
enddate = datetime(2021, 6, 1)
# get your current working directory
#current_wkdir = os.get_cwd()
os.chdir('/tmp')
current_wkdir = os.getcwd()
# Call the function. This will automatically store all the scrape data in a folder in your current working directory
get_instagram_posts(username, startdate, enddate)

Any help I'd really appreciate!

Thanks!

**Comment by Creat1veM1nd** [comment]
@shyland89 Not sure if that is what you need, but I got my python script working with that.

I excuted the script @Michounet did, calling it with `python <scriptname> -c <pathto>/cookies.txt`
With that I got a session.


Then I changed in my script

`L.login("USERNAME" , "PASSWORD")`

to

`L.load_session_from_file("USERNAME")`

Now my script works fine again so far.

**Comment by Dyegop** [comment]
Thank you @Creat1veM1nd, I was looking for that. It works perfect for me

**Comment by twitter-79** [comment]
This seems to be a problem with retrieving the csrf token
`session.get('https://www.instagram.com/web/__mid/')
 csrf_token = session.cookies.get_dict()['csrftoken']`

in line 214 of instaloadercontext.py does not work for me while 

`res = session.get('https://www.instagram.com/accounts/login/')
 csrf_token = re.findall(r"csrf_token\":\"(.*?)\"", res.text)[0]`
 
is working fine!

**Comment by pvita** [comment]
Is there any solution for command line usage?

**Comment by socialrupt** [comment]
I tried this but it still doesn't work. https://instaloader.github.io/troubleshooting.html#login-error
I check the location of where session files were downloaded and they were downloaded but still doesn't work.
What should I do?

**Comment by xTaromarux** [comment]
If someone still has the same problem this link is so helpful. 
https://github.com/nathan-149/automated_youtube_channel/blob/master/scrape_videos.py
This login method can be useful. 
Good luck
