### ISSUE TITLE
Can't put password in, when it's asking me to.

### ISSUE THREAD

**Issue by ichwillcashy** [instaloader/instaloader#1157]
I can't put my password it when i use instaloader -login USERNAME and it's saying: "Enter Instagram password for ogin: ". I think it should be login not ogin, so is this normal?
![image](https://user-images.githubusercontent.com/34011054/120026100-dcf50200-bff1-11eb-919e-af575a9fcd40.png)

**Comment by lapourgagner** [comment]
Hi,
Maybe just a typo error. Whoever, it's normal that's you don't see any character or * when you type your password.
So just try to type your password and press enter.

**Comment by aandergr** [comment]
It is `--login USERNAME` (two dash), or `-l USERNAME` (one dash, the space is optional).
