### ISSUE TITLE
instaloader is creating subdirectory with directory path as the sub-dir name

### ISSUE THREAD

**Issue by beakwood** [instaloader/instaloader#1158]
Basically, when executing the command and directory to save to. Instaloader will create that directory path AS a subfolder with path in the subdirectory name. Never had this problem before. Here's the command used

instaloader --login=myusername user_to_download -F --no-video-thumbnails --no-captions --no-metadata-json --no-compress-json --dirname-pattern="D:\\DIRECTORY-NAME\{profile}" --filename-pattern="{profile}_{date_utc:%Y-%m-%d %H.%M.%S}_UTC {mediaid}_{owner_id}"

[  1/ 91] D꞉﹨DIRECTORY-NAME\nnnn.mp4

the "D꞉﹨DIRECTORY-NAME\" would be a subdirectory in the location that I initiate the command. for example, if I run the command at only c:/ drive. I want it to download to my D drive but instead it will make a subdirectory in my c:/  with the subdriect with the name exactly "D꞉﹨DIRECTORY-NAME/" with the D drive letter in the subdrectory as showcased in the quotation marks. Any idea how to fix this? 

currently running 
instaloader 4.7.1
python 3.9.0
windows 10

EDIT# 
I tried even deleting "class _PostPathFormatter(_ArbitraryItemFormatter):" section from lines 122-137. Seeing as I'm having the same problem as issue#486 was having.

I've also tried using the "//?/D:" method as stated in Issue#185 . Using forward slash path I returned with
[WinError 53] The network path was not found: '//︖/D꞉/'

with backslash 
OSError: [Errno 22] Invalid argument: '\\\\?\\D:\\dirname\\targetname/id'

EDIT: 

SOLVED - Something was wrong with my 3.9 python. Uninstalled and installed 3.9.5 and everything is working as intended.

**Comment by kallewesterling** [comment]
Suggestion: Close this issue since it was resolved due to user's Python version.
