### ISSUE TITLE
Profile renamed message should be displayed even with --quiet

### ISSUE THREAD

**Issue by ekalin** [instaloader/instaloader#1159]
I believe the message 'Profile XXX has changed its name to YYY.' displayed when a profile gets renamed should be displayed even if `--quiet` is enabled.

While it's not really an error, it is something that requires user attention: for the next run, the new name must be used; the old name XXX will not be recognized anymore after the directory has been renamed to YYY.

**Comment by aandergr** [comment]
Yes, printing that message despite of `--quiet`, and probably printing it to stderr rather than stdout is probably a very useful change.



> While it's not really an error, it is something that requires user attention: for the next run, the new name must be used; the old name XXX will not be recognized anymore after the directory has been renamed to YYY.

I always recommend to invoke
```sh
instaloader [options] `ls -d */`
```
exactly because of this – but sure that might not be applicable for every use case.
