### ISSUE TITLE
429 error on first post retrieval from logged in account, successive attempts also fail

### ISSUE THREAD

**Issue by caneraydinbey** [instaloader/instaloader#1161]
I have also same error of this:
https://github.com/instaloader/instaloader/issues/902

**Describe the bug**
429 error on first or second attempt at post retrieval from logged in account, even after waiting several minutes or hours between requests. No 429 error when logged out of the account, but account login is necessary to download media from private profiles and for high quality images.

**To Reproduce**
instaloader --no-captions --no-profile-pic --no-metadata-json --no-video-thumbnails --login=xxx --post-filter="date_utc >= datetime(2020, 1, 1)"

Same 429 error if I use my local IP address or switch to a VPN for the account.

**Expected behavior**
Successful download of media that meets criteria

**JSON Query to graphql/query: 429 Too Many Requests [retrying; skip with ^C]
Number of requests within last 10/11/20/22/30/60 minutes grouped by type:**

ant solutions to get followers?

**Comment by Showmaster3000** [comment]
your issue is incomplete.
at least the missing version number required in the issue template
second thing is: your command line is incomplete - there is no account you want to download

**Comment by justusjonas9** [comment]
Same Problem.
Version instaloader-4.7.1

Command:
instaloader therockorg --login MYaccount

Traceback (most recent call last):
  File "/home/m/.local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/home/m/.local/lib/python3.8/site-packages/instaloader/__main__.py", line 445, in main
    _main(loader,
  File "/home/m/.local/lib/python3.8/site-packages/instaloader/__main__.py", line 104, in _main
    instaloader.login(username, password)
  File "/home/m/.local/lib/python3.8/site-packages/instaloader/instaloader.py", line 546, in login
    self.context.login(user, passwd)
  File "/home/m/.local/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 224, in login
    resp_json = login.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kallewesterling** [comment]
@caneraydinbey Are you using Instagram on, say, your phone or any other device where you're logged in at the same time? This has caused me issues in the past. The `429` response you're receiving is because Instagram has detected suspicious activity from your account, so it won't matter whether you're on a VPN or not, since you're logged in to your account.

@justusjonas9 your issue is not the same as this one, so I suggest you open a separate issue. Yours is a `JSONDecodeError` caused by Python, and not a `429` HTTP response, which is caused by Instagram's API/servers.
