### ISSUE TITLE
resumable_iteration + downloading posts from a specific period (takewhile, dropwhile)

### ISSUE THREAD

**Issue by bipsen** [instaloader/instaloader#1164]
Hi,

I have been struggling with finding the best way to combine resumable iterations with the itertools functions commonly used to download posts from a specific period. The problem is that wrapping the NoteIterator in a takewhile/dropwhile function means that resumable_iterations doesn't work, as they only work with NoteIterators. Thus the following doesn't save progress if broken:

```python
posts = instaloader.Profile.from_username(L.context, "instagram").get_posts()

SINCE = datetime(2015, 5, 1)
UNTIL = datetime(2015, 3, 1)

post_iterator = takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
    
with resumable_iteration(
        context=L.context,
        iterator=post_iterator,
        load=lambda _, path: FrozenNodeIterator(**json.load(open(path))),
        save=lambda fni, path: json.dump(fni._asdict(), open(path, 'w')),
        format_path=lambda magic: "resume_info_{}.json".format(magic)
) as (is_resuming, start_index):
    for post in post_iterator:
        do_something_with(post)
```

I am wondering whether this could be mitigated by constructing a NoteIterator with the date-limiting functions in there already?

Or is this best way simply to do something like:

```python
post_iterator = instaloader.Profile.from_username(L.context, "instagram").get_posts()

SINCE = datetime(2015, 5, 1)
UNTIL = datetime(2015, 3, 1)
    
with resumable_iteration(
        context=L.context,
        iterator=post_iterator,
        load=lambda _, path: FrozenNodeIterator(**json.load(open(path))),
        save=lambda fni, path: json.dump(fni._asdict(), open(path, 'w')),
        format_path=lambda magic: "resume_info_{}.json".format(magic)
) as (is_resuming, start_index):
    for post in post_iterator:
        if UNTIL <= post.date <= SINCE:
            do_something_with(post)
```

**Comment by aandergr** [comment]
Thanks for bringing up this question!

Indeed, resumable_iteration() needs a genuine NodeIterator to be able to handle the save&resume protocol. 

Your second approach will work; however you can still use the efficiency of takewhile and dropwhile when going through the posts, as long as you pass the original iterator to resumable_iteration():

```python
posts = Profile.from_username(L.context, "instagram").get_posts()

SINCE = datetime(2015, 5, 1)
UNTIL = datetime(2015, 3, 1)

with resumable_iteration(
    context=L.context,
    iterator=posts,
    load=lambda _, path: FrozenNodeIterator(**json.load(open(path))),
    save=lambda fni, path: json.dump(fni._asdict(), open(path, "w")),
    format_path=lambda magic: "resume_info_{}.json".format(magic),
) as (is_resuming, start_index):
    # use takewhile and dropwhile in the post iteration loop:
    for post in takewhile(
        lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)
    ):
        do_something_with(post)
```

**Comment by bipsen** [comment]
Hi @aandergr, sorry to reopen this discussion, but I just can't seem to get this to work with the code you provided. If the script breaks, no resumable iteration file gets saved. Are you sure that this is supposed to work? Thanks for your help!

**Comment by aandergr** [comment]
Hi! Yes, the script is supposed to work. Though, as stated in the documentation for [resumable_iteration()](https://instaloader.github.io/module/nodeiterator.html#resumable-iteration), it saves the resume file only if a KeyboardInterrupt or an AbortDownloadException occurs. However, you can catch any exception inside the resumable_iteration() context, and re-raise it as an AbortDownloadException to save the resume file.
