### ISSUE TITLE
Consider addding the ability to download specified saved collections instead of all of them

### ISSUE THREAD

**Issue by Dentrax** [instaloader/instaloader#1172]
**Provide us a use case of the feature**
Imagine if we have the bunch of thousands saved posts. I usually try to add in custom saved collections by grouping the post type. We may have dozens of saved collections. That said, we wouldn't want to download them all. I just interested in with a few collections. It would be a really nice UX!

(I couldn't find any information [in the doc](https://instaloader.github.io/search.html?q=saved), so I opened the feature request here.)

**Describe the solution you'd like**

Old way:
```bash
$ instaloader :saved  # downloads all collections
```

Proposed way:
```bash
$ instaloader --saved  # downloads all collections
$ instaloader --saved=foo, bar, baz  # downloads the only 'foo, bar, baz' collections
```

**If the feature request is accepted, would you be willing to submit a pull request?**
Not sure, I usually don't have a time. :(

**Additional context**

`:saved` command flag a bit weird for me. We may want to change `:foo` flag usages to `--foo` ones, in order to comply with Unix CLI standards. Wdyt?

**Comment by aandergr** [comment]
Thanks for sharing your ideas here.

For downloading saved items of a certain collection only, there is already #544; hence, we close this issue.

**Comment by Dentrax** [comment]
Thanks! Actually, I have seen that issue. I created a new one because this is slightly different from it. I pointed here to show _multiple tags_ use, and I also proposed flag usage change, i.e. from `:saved` to `--saved`. What do you think? Should we continue from there? 🤔

**Comment by aandergr** [comment]
No, we will not change :saved to --saved.

**Comment by Cyph3r** [comment]
This answer is a mistake. @Dentrax 's idea is good.
