### ISSUE TITLE
Consider allowing multiple hashtags usage and tag search strategy

### ISSUE THREAD

**Issue by Dentrax** [instaloader/instaloader#1173]
**Provide us a use case of the feature**
We all know that If we just search for a hashtag, it can return fake or irrelevant results, due to hashtag spam under post. Images with no _given tag_ in the photo with the specified hashtag #foo, which pollutes the images. If we had the chance to specify more than one tag, it would be a great UX!

**Describe the solution you'd like**

**Old way:**
```
$ instaloader "#3dprinter"
```

**New way:**

Strategy: default
```
# default tag search strategy can apply `or` logic
$ instaloader --tags=#3d,#printer,#electronics,#diy  # 
```
Strategy: and
```
$ instaloader --tags=#3d,#printer --tags-strategy=and  # both `3d` and `printer` have to be included in post
```

**Describe alternatives you've considered**

**Additional context**
If we give multiple hashtags at once, which one should we search with first? With the first tag we wrote? It doesn't seem to matter which one we're going to search since we already apply `and` logic.

What about `or`? Do we need to send search requests concurrently and give them the ability to process in parallel? So, in this case we may want to a concurrency flag, i.e., `--concurrency 4`

**Comment by Dentrax** [comment]
@Thammus Would you mind to explain what "no template" means exactly?

**Comment by Thammus** [comment]
We receive up to 60 issues per month; hence, we set up guidelines and issue templates, both very well visible when creating an issue, to make the process of going through the issues more efficient. They contain merely the basic questions that we always have to ask when handling a bug or deciding how to proceed with a feature suggestion. It is important for the project, that we devote our very limited free time to those issues that actually contribute to the project. Consequently, deleting parts of the template or leaving one of the questions unanswered disqualifies an issue and is labelled with 'no template'.

**Comment by Dentrax** [comment]
Hi @Thammus! I can understand your feelings. I think this issue now matches the [feature_request.md](https://github.com/instaloader/instaloader/blob/master/.github/ISSUE_TEMPLATE/feature_request.md) template. Please feel free to give feedback about this issue, what can I do here to re-open this issue?
