### ISSUE TITLE
Consider adding ability to transfering saved collections between accounts

### ISSUE THREAD

**Issue by Dentrax** [instaloader/instaloader#1175]
**Provide us a use case of the feature**
People may create a massive collection of saved posts - like hobby, art, gaming and material reference for work, etc. Instead of tracing them from the personal account, they may want to create a new account to split the contexts. Additionally, to keep Discover Feed page clean so that it only shows your area of interests on the Instagram.

**Describe the solution you'd like**

Not so sure but, what about:

```bash
# as a phase 1, we can transfer the saved collections!
# step 1. ask for login for both accounts
# step 1. fetch the given collections metadatas from `account_from`
# step 2. create given collections in `account_to`, if not exist
# step 3. traverse all the metadatas from `account_from ` and go to post by URL, and send a  `add to collection` request in `account_to`
$ instaloader transfer --saveds=foo,bar,baz --from account_from --to account_to
```

**Additional context**
Conflicts with https://github.com/instaloader/instaloader/issues/1172, what If we _may_ want to transfer several collections at the same time?

**Comment by Thammus** [comment]
Instaloader’s goal is to mimic the browser’s behavior to access the data that is available through the Instagram web interface, pack this data into complete and easily-(re)usable python objects, and provide a user interface for the most common downloading and metadata collection tasks, **without changing any of the online data**.

[https://instaloader.github.io/contributing.html#proposing-features](https://instaloader.github.io/contributing.html#proposing-features)
