### ISSUE TITLE
Alternate Between Instagram Accounts

### ISSUE THREAD

**Issue by Fragged123** [instaloader/instaloader#1178]
**Provide us a use case of the feature**
How could the user invoke the new function? Which problem would it solve? If new information is obtained, how would it be further processed?

Instead of logging into one account, the user can log into multiple accounts that are stored in the session file. This way users can download large instagram accounts without manually logging into each account to bypass the instagram download limit. The program would alternate between accounts once the limit of one account is reached. This can already be done manually, so having an automated function would be more convenient. 

**Describe the solution you'd like**

I'm asking for the --login function to store multiple account logins at a time and for instaloader to automatically switch accounts once the timeout error is given to continue downloading the target profile.

**Describe alternatives you've considered**

I have just been making my own hotkey shortcuts that type each account command line into CMD. This is still tedious because I have to constantly monitor the progress. I want to rip a profile and come back when it is finished.

**If the feature request is accepted, would you be willing to submit a pull request?**
No, I'm not familiar with programming.

**Additional context**
Add any other context about the feature request here.

**Comment by MrJmpl3** [comment]
This can be a good idea, but exists a problem, Instagram temp block your account if you login to multiples account without timeout

**Comment by aandergr** [comment]
This can be easily done from an external script, so I think there is no need to include this functionality in Instaloader itself.
