### ISSUE TITLE
Resumable iteration for hashtag?

### ISSUE THREAD

**Issue by GLivshits** [instaloader/instaloader#1182]
Hello. I'm currently using your code (i have slightly modified it with proxy rotation and some additional features and scripts). For profiles scraping it works perfectly, but with hashtag, it's not. I'm not able to download all posts for the hashtag (which has around 8 million posts) due to some errors from proxies (high timeout) or problems from Instagram. For profiles all this just gets solved by resumable iteration file - script just starts from it! But for hashtag one should start scraping over and over again. The max number of posts that I've been able to scrape is about 200k.
It would be quite nice if you would find a way to add a resumable iteration to the Hashtag structure. I understand, that this is not done yet not due to laziness, but due to fundamental issues with hashtags which are caused by Instagram itself.
Thanks!

**Comment by sofiavlachou28** [comment]
> Hello. I'm currently using your code (i have slightly modified it with proxy rotation and some additional features and scripts). For profiles scraping it works perfectly, but with hashtag, it's not. I'm not able to download all posts for the hashtag (which has around 8 million posts) due to some errors from proxies (high timeout) or problems from Instagram. For profiles all this just gets solved by resumable iteration file - script just starts from it! But for hashtag one should start scraping over and over again. The max number of posts that I've been able to scrape is about 200k.
> It would be quite nice if you would find a way to add a resumable iteration to the Hashtag structure. I understand, that this is not done yet not due to laziness, but due to fundamental issues with hashtags which are caused by Instagram itself.
> Thanks!

I have the same problem with `Hashtag.from_name()` , no longer works. 
Have you found another way to download posts from specific hashtags? 
I would be grateful if you post your code..! 

Thank you in advance 
Sofia

**Comment by EpiPhobe** [comment]
I was able to get a ~3 million hashtag [using this method:](https://github.com/instaloader/instaloader/issues/874#issuecomment-731561430)

```
post_iterator = instaloader.NodeIterator(
    L.context, "9b498c08113f1e09617a1703c22b2f32",
    lambda d: d['data']['hashtag']['edge_hashtag_to_media'],
    lambda n: instaloader.Post(L.context, n),
    {'tag_name': HASHTAG},
    f"https://www.instagram.com/explore/tags/{HASHTAG}/"
)
```

where HASHTAG is the hashtag string and:

```
try:
    for post in post_iterator:
        L.download_post(post, target = HASHTAG)
except:
    iteratorfreeze = post_iterator.freeze()
    with open(f'{HASHTAG}.pkl', 'wb') as resumefile:
        pickle.dump(iteratorfreeze, resumefile)
```

However, Instagram says that the hashtag contains more than 5 million posts. I'm not sure if that's including private or deleted posts.

**Comment by sofiavlachou28** [comment]
@EpiPhobe I really appreciate that you shared your code! It works for me  😊  but I have an additional question. 
How can we define the number of downalded posts e.g. ` max_count=200 ` in your snippet?? any idea? 

You will help me a lot if you answer! 

Thank you in advance!!

Sofia

**Comment by EpiPhobe** [comment]
Just noticed that I didn't include how to load the resume file. This would go after the `post_iterator = instaloader.NodeIterator()
`
```
#load
with open(f'{HASHTAG}.pkl', 'rb') as resumefile:
    resumeint = pickle.load(resumefile)
    post_iterator.thaw(resumeint)
```

@sofiavlachou28 I'm not sure if this is the best way:

```
i = 0
max_count = 200
try:
    for post in post_iterator:
        L.download_post(post, target = HASHTAG)
        i += 1
        if i > max_count:
            break
except:
    iteratorfreeze = post_iterator.freeze()
    with open(f'{HASHTAG}.pkl', 'wb') as resumefile:
        pickle.dump(iteratorfreeze, resumefile)
```

You can add `i = resumeint.total_index + 1` after `post_iterator.thaw(resumeint)` so it doesn't try to download an additional 200 posts

**Comment by sofiavlachou28** [comment]
> Just noticed that I didn't include how to load the resume file. This would go after the `post_iterator = instaloader.NodeIterator() `
> 
> ```
> #load
> with open(f'{HASHTAG}.pkl', 'rb') as resumefile:
>     resumeint = pickle.load(resumefile)
>     post_iterator.thaw(resumeint)
> ```
> 
> @sofiavlachou28 I'm not sure if this is the best way:
> 
> ```
> i = 0
> max_count = 200
> try:
>     for post in post_iterator:
>         L.download_post(post, target = HASHTAG)
>         i += 1
>         if i >= max_count:
>             break
> except:
>     iteratorfreeze = post_iterator.freeze()
>     with open(f'{HASHTAG}.pkl', 'wb') as resumefile:
>         pickle.dump(iteratorfreeze, resumefile)
> ```
> 
> You can add `i = resumeint.total_index + 1` after `post_iterator.thaw(resumeint)` so it doesn't try to download an additional 200 posts

Ok! thank you so much for sharing your code! I hope it works ! 
Sofia
