### ISSUE TITLE
Download only posts from e.g. 200 to 300

### ISSUE THREAD

**Issue by shufps** [instaloader/instaloader#1186]
For accounts with a large number of posts, it's almost certain to run into an Instagram block after a couple of 100 downloaded items.

I would like to split the download of all postings over e.g. 10 days and always only download a chunk of 100 on each day, but it would require that instaloader has a parameter for 

- starting at post
- count of posts to download

Would this be possible?

**Comment by aandergr** [comment]
You can use the [resumable iterations](https://instaloader.github.io/module/nodeiterator.html) feature to interrupt the download after 100 items and resume later.
