### ISSUE TITLE
JSON Query to graphql/query: HTTP error code 500 - Appearing everywhere

### ISSUE THREAD

**Issue by santinmike** [instaloader/instaloader#1188]
I receive this error message: `JSON Query to graphql/query: HTTP error code 500`.

When getting posts with: `Post.from_shortcode(L.context, SHORTCODE)` (always)
When testing my login with: `test_login()`   (half of the times)
When getting my followers' profile using: `profile.get_followers()`   (randomly during the iterations)
When trying to get a new session file with the code in the troubleshooting page: [https://instaloader.github.io/troubleshooting.html#login-error](https://instaloader.github.io/troubleshooting.html#login-error)  (randomly)

I am using Instaloader 4.7.1 and I am logged in to Instagram by means of a session file. Trying to use `login(user, passwd)` results the the error `Login error: JSON decode fail, 403 - Forbidden.`

Any ideas of what is going on?

**Comment by Deleora** [comment]
Even I'm getting the same error:

```
Loaded session from E:\Instaloader\session-files\session-username123.
JSON Query to graphql/query: HTTP error code 500. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 500. [retrying; skip with ^C]
Fatal error: JSON Query to graphql/query: HTTP error code 500.
```

**Comment by Yvan95** [comment]
I've h ad the same problem.
Due to constant requests, sometimes Instagram blocks my session file and I need to recreate it.
in the directory where I have my script a __pycache__ folder is also generated and deleting it the error disappears.
I don't know if things are related but my scripts are working now

**Comment by LaticePrime** [comment]
I am still getting when not logged in so with no session file

**Comment by EpiPhobe** [comment]
I am also getting the error but also not logged in. I was using both `instaloader.Post.from_shortcode()` and `L.download_post()` so I don't know which caused the error. Nonetheless, the posts seem to have been downloaded fine. I did not get the `Fatal error`

**Comment by Showmaster3000** [comment]
Error code 500 or any other 5xx error are server side things. No problem on instaloader side.
Just had a bunch of them yesterday, but currently everything seems to be ok again.

**Comment by LaticePrime** [comment]
Same. Everything running smoothly today. No problem.
