### ISSUE TITLE
Get Username from UserID

### ISSUE THREAD

**Issue by Deleora** [instaloader/instaloader#1189]
Hey, 
I would like to know if it's possible to get the username of profiles using their user ID which is downloaded by the Instaloader. I've never downloaded this profile but it had commented on my post (I have the comments JSON file) and now I can't find that account on Instagram. So any way to get the current username of the account using their user ID?

**Comment by kandayo** [comment]
https://github.com/instaloader/instaloader/blob/9ffdf258a9441ca680864fb468facfa261df9491/instaloader/structures.py#L617

`Profile.from_id`

**Comment by Deleora** [comment]
It worked. Thanks a lot!

**Comment by UnixCro** [comment]
I did not understand that exactly now. What exactly should you do with the code and what should you replace?
