### ISSUE TITLE
Error login using +args.txt

### ISSUE THREAD

**Issue by christoarmani** [instaloader/instaloader#1194]
**Describe the bug**
In the last week, this bug appeared where Instaloader is unable to login to my account/s and returns the error below. In short, Instaloader is unable to login to the account and download. 

**To Reproduce**
(e.g. Instaloader command line)
Run the command: 'instaloader +args.txt' and then returns the behavior below after several minutes.

In my text document are the following arguments:
--login=[username]
--password=[password]
--no-metadata-json
--no-profile-pic
--no-caption
--abort-on=400,429
--filename-pattern={profile}_{filename}

**Expected behavior**
A clear and concise description of what you expected to happen (even if it seems obvious).
Start downloading posts based on listed arguments.

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

JSON Query to graphql/query: Redirected to login [retrying; skip with ^C]
Number of requests within last 10/11/20/22/30/60 minutes grouped by type:
 * d6f4427fbe92d846298cf93df0b937d3:    1    1    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 666 seconds, at 22:55.
JSON Query to graphql/query: Redirected to login [retrying; skip with ^C]
Number of requests within last 10/11/20/22/30/60 minutes grouped by type:
 * d6f4427fbe92d846298cf93df0b937d3:    1    1    2    2    2    2
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 666 seconds, at 23:06.
Loaded session from C:\Users\[username]\AppData\Local\Instaloader\session-[instagramusername].

HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/

HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/

HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
Fatal error: JSON Query to graphql/query: Redirected to login

**Instaloader version**
`instaloader --version` output.
4.7.2

**Additional context**
Instaloader has worked on the account/s before, I am able to login to them via the web browser and they are unlocked. I triple-checked the password and any extra trailing spaces in the arguments text document.

**Comment by aandergr** [comment]
> **Instaloader version**
> `instaloader --version` output.
> 4.7.2

Does that still happen with 4.7.4 or 4.8rc2?

**Comment by christoarmani** [comment]
Yes, I still get the same error code in 4.7.4

**Comment by aandergr** [comment]
The error log output in your issue report does not seem valid or is incomplete in some way. Instaloader cannot print these messages in this order.

**Comment by thesuperfatcat** [comment]
Remove this arguments:
--login=[username]
--password=[password]

Run command like this:
instaloader --login "your user name" profile "enter profile name" +args.txt

**Comment by christoarmani** [comment]
> o

This is directly copied and pasted with the removal of the usernames.

**Comment by christoarmani** [comment]
> The error log output in your issue report does not seem valid or is incomplete in some way. Instaloader cannot print these messages in this order.

This is directly copied and pasted with the removal of the usernames.

**Comment by christoarmani** [comment]
> 
> 
> Remove this arguments:
> --login=[username]
> --password=[password]
> 
> Run command like this:
> instaloader --login "your user name" profile "enter profile name" +args.txt

I will try this. However, was this changed in recent versions past 4.7.2? Because my usual way worked just fine.

**Comment by christoarmani** [comment]
![Screenshot 2021-06-25 171827(2)](https://user-images.githubusercontent.com/70650761/123486507-28430600-d5da-11eb-9d3f-74224b211b92.png)
![Screenshot 2021-06-25 171840(2)](https://user-images.githubusercontent.com/70650761/123486522-3133d780-d5da-11eb-8af0-ee24274a7cef.png)
![Screenshot 2021-06-25 150527](https://user-images.githubusercontent.com/70650761/123486523-32fd9b00-d5da-11eb-8540-cb0d30db1509.png)
Attached are screenshots of the exact error and args.txt

**Comment by thesuperfatcat** [comment]
Not use quotation marks
like this: instaloader --login yourusername profile enterprofilename +args.txt

and you should remove these commands from your args.txt file and try them
--abort-on=400,429
--filename-pattern=....

**Comment by christoarmani** [comment]
![Screenshot 2021-06-26 120807](https://user-images.githubusercontent.com/70650761/123519168-a99ca600-d677-11eb-9d87-72397aae3fab.png)

Error still occurs.

**Comment by alvaroserrrano** [comment]
How can we avoid the redirection issue while working on a remote server? For example, I am thinking of a CI-CD server that builds a docker container and fails the build because you are redirected to validate your credentials (which you cannot do). I guess that using the import session approach does not work in this case either (please correct me if I am wrong).
As soon as Instagram detects an unknown ip for --login it prompts the user for entering its credentials and verifying the account
