### ISSUE TITLE
How to use --title-pattern?

### ISSUE THREAD

**Issue by fosam** [instaloader/instaloader#1196]
Hello,

I'm trying to use the option `--title-pattern` for profile pics but it returns an error everytime.

This is the command i run:

`instaloader --title-pattern={filename} --no-posts --login myusername esmuellert`

It returns:

<pre>
usage:
instaloader [--comments] [--geotags]
            [--stories] [--highlights] [--tagged] [--igtv]
            [--login YOUR-USERNAME] [--fast-update]
            profile | "#hashtag" | %location_id | :stories | :feed | :saved
instaloader --help
instaloader: <b>error: unrecognized arguments: --title-pattern={filename}</b>
</pre>

Can you provide an example on how `--title-pattern` works?

Version 4.7.4

**Comment by ekalin** [comment]
This feature it not available on version 4.7.4. You can try the 4.8rc2 version, or wait until 4.8 is released.

**Comment by fosam** [comment]
Oh, but could you give an example of how a command using `--title-pattern` would look like? i've been waiting for a feature like this for months and we finally will be having it soon, Thanks!

**Comment by ekalin** [comment]
That should work, but remember to quote the argument to prevent shell expansion. I myself am using `--title-pattern '{profile}_{date_local}_{typename}_{filename}'`.

**Comment by fosam** [comment]
I'm using CLI on Windows and have not used the quotes before, do i need to use quotes with this specific argument? (`--title-pattern`)
