### ISSUE TITLE
No subdirectories for :tagged or highlights

### ISSUE THREAD

**Issue by topotamadre023** [instaloader/instaloader#1197]
I'm trying to get all the files of the same profile into the same directory without any subdirectories such as :tagged.
I tried adding a dot to the output folder, however it doesn't change anything

`python3 instaloader.py --login=USERNAME --dirname-pattern={target}/. --tagged --highlights profile1`

Actually the resulting output folder seems like
```
/profile1
  /profile1/:tagged
  /profile1/highlight1
  /profile1/highlight2
...
```
And I'd like to find all the files in the same directory without subdirectories.

I'm working on a linux machine.

What can I do?
Thanks

**Comment by Liz-chan** [comment]
I use `--dirname-pattern={profile}` and it puts all the highlights and other stuff inside the same folder without any subdirectories.

**Comment by topotamadre023** [comment]
Thats what i'm doing now provisionally, however it's not a perfect solution as when you include :tagged new profiles appear
