### ISSUE TITLE
Acsess private profile

### ISSUE THREAD

**Issue by edvelloso** [instaloader/instaloader#1200]
Guys, does anyone know how to get access to a restricted profile?
There is no loophole in Instagram login? Type pass some parameter in the debug, or even a brutforce passed in the parameters to the instaloader?

**Comment by kandayo** [comment]
It's not possible. You won’t be able to see anything from a private profile.

**Comment by edvelloso** [comment]
Is it possible to develop a brute force that doesn't lock the login?

There has to be some method to be able to spy on a user's profile!

Att,

P Antes de imprimir pense em seu compromisso com o Meio Ambiente.

Em 2021-06-21 18:06, Kandayo escreveu:

> It's not possible. You won't be able to see anything from a private 
> profile.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] 
https://github.com/instaloader/instaloader/issues/1200#issuecomment-865344077
[2]

**Comment by edvelloso** [comment]
> 
> 
> It's not possible. You won’t be able to see anything from a private profile.

kandayo,
Is it possible to send a link, that when the person clicks, they add another profile to Instagram as a follower? This in silent mode?
