### ISSUE TITLE
KeyError: 'graphql' when trying to login

### ISSUE THREAD

**Issue by abpuma2** [instaloader/instaloader#1201]
**I ran this code**
`from instaloader import *`
`L = Instaloader()`
`L.login(username,pwd)`

**I get this error** 

`KeyError                                  Traceback (most recent call last)
<ipython-input-32-f83965545d67> in <module>
      1 L.login("ian_y0ng",'6J1anIan!')
----> 2 hasht = Hashtag.from_name(L.context,'ecofriendlykitchen')

~/opt/anaconda3/lib/python3.8/site-packages/instaloader/structures.py in from_name(cls, context, name)
   1249         """:class:`Profile` instance of the highlights' owner."""
   1250         if not self._owner_profile:
-> 1251             self._owner_profile = Profile(self._context, self._node['owner'])
   1252         return self._owner_profile
   1253 

~/opt/anaconda3/lib/python3.8/site-packages/instaloader/structures.py in _obtain_metadata(self)
   1263 
   1264     @property
-> 1265     def cover_cropped_url(self) -> str:
   1266         """URL of the cropped version of the cover."""
   1267         return self._node['cover_media_cropped_thumbnail']['url']

~/opt/anaconda3/lib/python3.8/site-packages/instaloader/structures.py in _query(self, params)
   1258 
   1259     @property
-> 1260     def cover_url(self) -> str:
   1261         """URL of the highlights' cover."""
   1262         return self._node['cover_media']['thumbnail_src']

KeyError: 'graphql'
`

I have tried every fix I could find.

**Instaloader version**
4.7.4

**Comment by Showmaster3000** [comment]
If I understand it right, you omitted parts of the code leading to the problem your output describes. You try to request the hashtag `ecofriendlykitchen`?
This problem is described in the pinned issue #1080 which is still open.

btw. if this is your account and password, then immediately change it!
