### ISSUE TITLE
Getting followers/following faster

### ISSUE THREAD

**Issue by jasonhan-vassar** [instaloader/instaloader#1202]
Hi, so I've noticed that getting the list of followers is quite slow (several seconds from my testing). I see from the code that it's based on the Graph API and it manually enumerates the edges to find all followers — even without running it, it already sounds quite slow. From my understanding, we don't know a better way to do this.

However, I've noticed that the Instagram app is a lot faster at this than [instagram.com](instagram.com). If you navigate to your profile and tap on your followers/following, the list is generated nearly instantly. It also refreshes instantly when you swipe down to refresh. Does anyone know how the app accomplishes this? Does it use a non-public API? I'm tempted to find a way to record the app's HTTP requests and see how it works. Let me know if this is worth looking into or a waste of time.

Thanks for reading.

**Comment by Deleora** [comment]
Hey, how do you plan on recording the app's HTTP requests?

**Comment by jasonhan-vassar** [comment]
@Deleora I'm not too sure at the moment but I'll let you know if I find a way. I don't have too much experience with iOS development. Did you have any ideas?

**Comment by Liz-chan** [comment]
On the website the followers/following list loads pretty fast for me when I click it, probably like max 2 seconds or so but usually around 1.
