### ISSUE TITLE
Instaloader command not found 

### ISSUE THREAD

**Issue by BigTree98** [instaloader/instaloader#1208]
Hi,

I Have installed Python 3,Python pip and installer on Ubuntu but when running the Following command installer profile i am receiving a error saying the command can not be found.

Can confirm that instaloader is installed but still receiving this message

**Comment by Showmaster3000** [comment]
I see no command line and also no error message in your report, please provide it otherwise issue will be closed.

**Comment by BigTree98** [comment]
> I see no command line and also no error message in your report, please provide it otherwise issue will be closed.

Hi,

Managed to find the solution using this post

https://github.com/instaloader/instaloader/issues/440
