### ISSUE TITLE
bypass timeout?

### ISSUE THREAD

**Issue by UnixCro** [instaloader/instaloader#1209]
Hi,

I like to download the Instagram stories from Youtubers. However, I have had several timeouts in the past few weeks and that led to my losing accounts. Nevertheless, I was able to bypass the timeout lock with multiple accounts.

I have a question about `--fast-update` if I used this, is it even more unlikely that an account should be blocked again or it will timeout again?

Thank you for your effort and for providing this great project.

**Comment by Showmaster3000** [comment]
`--fast-update` only helps to prevent double check/download elements you already have. Due to smaller amount of requests by skipping already downloaded elements, the process is finishing faster.
See manual: https://instaloader.github.io/cli-options.html#which-posts-to-download
