### ISSUE TITLE
Unable to download posts within a certian time period

### ISSUE THREAD

**Issue by BigTree98** [instaloader/instaloader#1215]
Hi,

Have used the following Python script to try and download all Instagram Posts between 1st January 2018 and 31st December 2018.

**SCRIPT** 

from datetime import datetime
import instaloader

L = instaloader.Instaloader()

posts = instaloader.Hashtag.from_name(L.context, "alessandraambrosio").get_posts()

SINCE = datetime(2018, 1, 1)  # further from today, inclusive
UNTIL = datetime(2028, 12, 31)  # closer to today, not inclusive

k = 0  # initiate k
#k_list = []  # uncomment this to tune k

for post in posts:
    postdate = post.date

    if postdate > UNTIL:
        continue
    elif postdate <= SINCE:
        k += 1
        if k == 50:
            break
        else:
            continue
    else:
        L.download_post(post, "alessandraambrosio")
        # if you want to tune k, uncomment below to get your k max
        #k_list.append(k)
        k = 0  # set k to 0

#max(k_list)

**Error Message that appears when trying to run the script**

HTTP redirect from https://www.instagram.com/explore/tags/alessandraambrosio/ to https://www.instagram.com/accounts/login/
Traceback (most recent call last):
  File "Python.py", line 6, in <module>
    posts = instaloader.Hashtag.from_name(L.context, "alessandraambrosio").get_posts()
  File "/home/callum/.local/lib/python3.8/site-packages/instaloader/structures.py", line 1324, in from_name
    hashtag._obtain_metadata()
  File "/home/callum/.local/lib/python3.8/site-packages/instaloader/structures.py", line 1338, in _obtain_metadata
    self._node = self._query({"__a": 1})
  File "/home/callum/.local/lib/python3.8/site-packages/instaloader/structures.py", line 1333, in _query
    return self._context.get_json("explore/tags/{0}/".format(self.name),
  File "/home/callum/.local/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 335, in get_json
    raise LoginRequiredException("Redirected to login page. Use --login.")
instaloader.exceptions.LoginRequiredException: Redirected to login page. Use --login.

**Comment by Showmaster3000** [comment]
The error message says the problem in the last line: you have to login for this task.

**Comment by BigTree98** [comment]
> The error message says the problem in the last line: you have to login for this task.

I tried to add --login to the script but was unsure where to put it

**Comment by Showmaster3000** [comment]
Ok, this is a bit confusing. The `--login` parameter is for command line usage. You are using instaloader as a module. 
Have a look at the manual where everything is described: https://instaloader.github.io/as-module.html

**Comment by BigTree98** [comment]
> Ok, this is a bit confusing. The `--login` parameter is for command line usage. You are using instaloader as a module.
> Have a look at the manual where everything is described: https://instaloader.github.io/as-module.html

Will have a look.Sorry for confusing you new to Linux and python
