### ISSUE TITLE
A way to break large collections into smaller downloads overtime. 

### ISSUE THREAD

**Issue by rouncewell** [instaloader/instaloader#1218]
**Provide us a use case of the feature**

Say someone wants to download their entire library of saved posts or profile pictures but the collection is large. I want to set a cron job to download the entire collection but only 100 or 200 posts at a time. This is to prevent receiving a 429 error from Instagram and to download a large collection over the course of days/weeks. 

**Describe the solution you'd like**

Run instaloader with a count of x ... but when it's re-run it picks up where it left off. It won't return "image-name" already exists, causing a query. So an example would be to run instaloader with a count of say 100 ... it will download 100, but once it's run again, it will pick up at image 101-200. This would be helpful with downloading large collections overtime. 

The only issue I could see would be if you've recently saved/added more posts during the time Instaloader has been running. In this case, there could be an overlap feature that will scan the previous x-% to cause less queries. 

For instance, I could set the overlap scan to be %10 and then Instaloader would pick up after my initial 100 count scan but it would back-track 10% of the count parameter (10 posts in this example) to help ensure that newly saved images/posts are downloaded. 

I'm sure there is a better way to ensure no posts are left behind, but I have yet to figure it out.

**Describe alternatives you've considered**

I've tried to figure out a way using the CLI options, but have not found a solution to downloading large collections without getting timed out. 

**If the feature request is accepted, would you be willing to submit a pull request?**

No

**Additional context**

**Comment by calvinthefreak** [comment]
If you run on Linux, you can pause the Process for a certain time with the sig-stop command.

I wrote me a little script, that pauses the process, and resumes it after a certain time again:
```bash
#!/bin/bash
source $(dirname "$0")/login.sh
PIDget=$(ps aux | grep instaloader | grep -v grep | grep "@$USERNAME" | awk '{print $2}')

kill -SIGSTOP $PIDget
sleep $((RANDOM%120));
kill -CONT $PIDget
```

**Comment by rouncewell** [comment]
Hi, Can you explain how I would make this work? I will write this as a .sh and make it runnable. Do I just execute this alongside Instaloader? Thanks in advance!

**Comment by aandergr** [comment]
This is a trivial use case for [Resumable Iterations](https://instaloader.github.io/module/nodeiterator.html); no need to implement anything in Instaloader, it's all there already. Just write a small script to do that.
