### ISSUE TITLE
check for the moved (but previously downloaded) files before downloading a profile

### ISSUE THREAD

**Issue by qodrinzo** [instaloader/instaloader#1221]
Hello. Providing free storage for new downloads, a user may want to move previously downloaded profiles/files to a new location out of the original Instaloader's download path (eg, one-way backing up to a cloud). It seems that Instaloader just checks for the real presence of the profile and all files before downloading them into a path.

Instaloader would be able to check for the previously downloaded files without their real presence in the path (because of moving to another place) if there were **a file consisting ids or hash-strings** of those posts, stories, igtvs, highlights, etc.

**Comment by Showmaster3000** [comment]
Do you mean a thing like in #1131 ? This will be included in the next release 4.8. You can already use the preview release if you instantly need it.

**Comment by qodrinzo** [comment]
Yes, that's it! Hopeful to add support for non-chronological items by using IDs or hash-strings or another way.

**Comment by aandergr** [comment]
> Hopeful to add support for non-chronological items by using ID/hash-strings or through another way.

We decided against that, see #1131 for the rationale behind.
