### ISSUE TITLE
Issue with geotags?

### ISSUE THREAD

**Issue by fyrkrans** [instaloader/instaloader#1222]
**Describe the bug**
Recently I started to run into problems when trying to use the geotags flag.

**To Reproduce**
instaloader -F --geotags -l my_ig_account -f /path/to/session_file another_ig_account

**Expected behavior**
It should execute without errors.

**Error messages and tracebacks**

>   File "/home/fyrkrans/.local/bin/instaloader", line 10, in <module>
>    sys.exit(main())
>  File "/home/fyrkrans/.local/lib/python3.7/site-packages/instaloader/__main__.py", line 460, in main
>    storyitem_filter_str=args.storyitem_filter)
>  File "/home/fyrkrans/.local/lib/python3.7/site-packages/instaloader/__main__.py", line 215, in _main
>    fast_update, post_filter, storyitem_filter)
>  File "/home/fyrkrans/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 1290, in download_profiles
>    total_count=profile.mediacount, owner_profile=profile)
>  File "/home/fyrkrans/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 922, in posts_download_loop
>    downloaded = self.download_post(post, target=target)
>  File "/home/fyrkrans/.local/lib/python3.7/site-packages/instaloader/instaloader.py", line 670, in download_post
>    if self.download_geotags and post.location:
>  File "/home/fyrkrans/.local/lib/python3.7/site-packages/instaloader/structures.py", line 557, in location
>    params={'__a': 1})['graphql']['location']
> TypeError: 'NoneType' object is not subscriptable

**Instaloader version**
$ instaloader --version
4.7.4

**Additional context**
The problem appeared just a couple of days ago.

Maybe it's just a problem with my system though?

**Comment by Showmaster3000** [comment]
This problem is already discussed in #1117 and #1109.

**Comment by fyrkrans** [comment]
I was looking for bug reports about this, but apparently didn't do a well enough job, because I definitely overlooked #1109.

I'm very sorry about that. If I can add anything of substance to #1109 (logs etc.) then please let me know.
