### ISSUE TITLE
Error: 'graphql'

### ISSUE THREAD

**Issue by JoseConi** [instaloader/instaloader#1225]
Hello!

I am trying to get the posts that have "#house" hashtag, but i cant. Here i show the code:

L = Instaloader()
L.login(USERNAME, PASSWORD)
hashtag = Hashtag.from_name(L.context, "house")

output:
"KeyError: 'graphql'".

![Sin título](https://user-images.githubusercontent.com/79027875/124849804-d3a67000-df75-11eb-8f83-9d3ee896b1d0.png)

Do you know why it brings this error? The code is exactly the same that instaloader's github shows here: https://instaloader.github.io/module/structures.html

Thank you!

**Comment by Leonardomorn** [comment]
Hi, so, this is already an open issue on #1080 , the cause may be the metadata changes on Instagram. Maybe #874  will work.
