### ISSUE TITLE
Version 4.0.3 Instagram story error

### ISSUE THREAD

**Issue by Purefreeman** [instaloader/instaloader#123]
While running a bat file containing multiple Instagram accounts to download their insta story. I receive this error, i also tried to run the accounts individually i still get the same error. This error doesn't occur when i run the bat file to download their page content.

JSON Query to graphql/query: HTTP error code 403. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 403. [retrying; skip with ^C]
Fatal error: JSON Query to graphql/query: HTTP error code 403.

**Comment by Showmaster3000** [comment]
I also had this error. Please use the official instagram app and login. After that you have to accept the new terms of service. All accounts got disabled that didn't accept the new terms before May 24th (reason is the european GDPR).

**Comment by Purefreeman** [comment]
i did this, but now i am getting "Fatal error: Login error: 400 Bad Request"
and when i do login on the official Instagram app it informs me about Suspicious Login Attempt

**Comment by aandergr** [comment]
We cannot reproduce this error. Both logging in and downloading stories seem to work. Ensure that you can login with an official Instagram app and if the problem should persist, feel free to reopen this issue and provide us more information.
