### ISSUE TITLE
Feature request: filter videos by size

### ISSUE THREAD

**Issue by ahsaassy** [instaloader/instaloader#1234]
**Provide us a use case of the feature**
 Sometimes the videos are big and it takes too much space for unnecessary videos (eg: igtv videos on profile). Normally this wouldn't be an issue on computers but I'm using my phone and storage fills up pretty fast.

**Describe the solution you'd like**
`--size-max` or `--size-min` (eg: `--size-max 5M`).
Basically an option to skip videos bigger than the specified amount in MB. 

**If the feature request is accepted, would you be willing to submit a pull request?**
No, unfortunately I do not have any programming knowledge :(

**Comment by Thammus** [comment]
Very few users would actually use this feature. It is way too specific to be supported via CLI.
