### ISSUE TITLE
Single image downloading doesn't work?

### ISSUE THREAD

**Issue by anta40** [instaloader/instaloader#1235]
I'm not sure if this is indeed a bug, or I don't understand the docs properly.

Let's say I want to grab this cat photo:
https://www.instagram.com/p/CRguM8OIht6/

Try using instaloader (https://instaloader.github.io/basic-usage.html):
```
instaloader -- CRguM8OIht6
JSON Query to crgum8oiht6/feed/: 404 Not Found [retrying; skip with ^C]
JSON Query to crgum8oiht6/feed/: 404 Not Found [retrying; skip with ^C]

HTTP redirect from https://www.instagram.com/web/search/topsearch/ to https://www.instagram.com/accounts/login/?next=/web/search/topsearch/%3Fcontext%3Dblended%26query%3Dcrgum8oiht6%26include_reel%3DFalse%26__a%3D1
CRguM8OIht6: Redirected to login page. Use --login.

Errors or warnings occurred:
CRguM8OIht6: Redirected to login page. Use --login.
```

I'm on MacOS Big Sur, with Instaloader 4.7.4 installed (via pip3)

**Comment by ekalin** [comment]
You have the prefix the code with `-`. (And you need `--` so it does not get confused with an argument):
`instaloader -- -CRguM8OIht6`

**Comment by anta40** [comment]
Ah I see, I didn't read the docs properly. Thank you :)
