### ISSUE TITLE
Import rips & information from 4Kstogram

### ISSUE THREAD

**Issue by atmos-o** [instaloader/instaloader#1236]
I've been using 4kstogram but want to switch over to instaloader to use on a headless server.

4k saved files naming them in this format `2017-03-03 04.40.41 1462100983227341806_4435586338` - date, time & ID. 
In a profile's folder it has folders named "highlights" "story" & ".thumb.stogram" the thumbs folder likely used to display small images in the 4kstogram UI.

In the root folder of 4kstogram (not a profiles folder) it has some files like ".stogram.sqlite". Maybe this can be used to pull all the necessary info out

### I think the way it has "stories" & "highlights separated is much sleeker too. Could we get an InstaLoader feature to organise it like that?

**Comment by UnixCro** [comment]
I would also be in favor of the fact that Instaloader is changed so that stories and posts are saved separately in folders, otherwise you have a confusion as to what a post and what a story was. 

Otherwise I think everything should stay that way. Unfortunately such an impressive program takes a lot of time.

**Comment by atmos-o** [comment]
I just wanted an easy import from 4kstogram. I don't want it to be more like that with sqlite db's and stuff. I'm bouncing around a few looking to see what I can work with. 

I wonder if a web GUI would be possible, not needed but an extra for sure. Coz I also want to host an easy Album viewer app so I can let users view all my data hoarded media, preferably loading from a CDN but its hard to find & maybe doesnt exist.
