### ISSUE TITLE
install

### ISSUE THREAD

**Issue by parsibox** [instaloader/instaloader#124]
hi
excuse me can you help me to setup python 3.6 with lzma  ?
i can not install lzma  in python 3.6
my python version is 3.4 and your code need more than 3.5
i install 3.6 but it say : ModuleNotFoundError: No module named '_lzma'
when i try  install lzma it say : No matching distribution found for pyliblzma

**Comment by psycholyzern** [comment]
How did you fixed this? I am on python 3.7

**Comment by psycholyzern** [comment]
I solved by using the solution from https://dausruddin.com/modulenotfounderror-no-module-named-_lzma/

In short  simply install `liblzma-dev` and recompile Python

**Comment by aandergr** [comment]
Actually I thought the `lzma` module is shipped with every Python installation, as it is part of the Python Standard Library, https://docs.python.org/3/library/lzma.html

Which distribution are you using, where lzma cannot be imported?

**Comment by psycholyzern** [comment]
I am using Ubuntu 18.04 and compile Python 3.7.1 from source. Compilation proceeds without lzma because I didn't have lzma installed on my system. 
 I installed liblzma-dev then recompiled Python and all went fine.

**Comment by ElusiveZatchmo** [comment]
Is there any way to run a fix to install liblzma-dev locally without root permissions?
