### ISSUE TITLE
Any way I can retrieve the "img alt" attribute of an image post?

### ISSUE THREAD

**Issue by czephyr** [instaloader/instaloader#1245]
![image](https://user-images.githubusercontent.com/28897641/128100307-9a3780d3-2bb1-49b0-a25d-453f4a0c8c67.png)

**Comment by aandergr** [comment]
That's the `accessibility_caption`, which is stored in the JSON file.

```sh
xzcat downloaded_post.json.xz | jq .node.accessibility_caption
```

**Comment by dfbadawi** [comment]
It seems that this has stopped working. The `accessibility_caption` attribute always returns `None`.

**Comment by dfbadawi** [comment]
Hi @aandergr 
It seems that this has stopped working. The `accessibility_caption` attribute always returns `None`.
