### ISSUE TITLE
Append instagram's unique post code to file names

### ISSUE THREAD

**Issue by Jon8RFC** [instaloader/instaloader#1248]
**Provide us a use case of the feature**
Easily referencing the original instagram post, no matter which file is being looked at, which I've often wanted to do.
If the post's unique code is in the file name, I can just copy and append that to _instagram.com/p/_**\<paste-here\>**

**Describe the solution you'd like**
Not:
`2021-08-05_13-10-37_UTC.jpg`
`2021-08-05_13-10-37_UTC.txt`
`2021-08-05_13-10-37_UTC.json.xz`
Instead:
`2021-08-05_13-10-37_UTC__CSMaOdnszpv.jpg`
`2021-08-05_13-10-37_UTC__CSMaOdnszpv.txt`
`2021-08-05_13-10-37_UTC__CSMaOdnszpv.json.xz`

**Describe alternatives you've considered**
Appending the post code to metadata, but that would only apply to pictures.
Although, that'd still be really convenient to have the code/full URL addition to the proposed file names.

**If the feature request is accepted, would you be willing to submit a pull request?**
Not a software developer by any means, although I'll look and see if it's easy enough to figure out some of it through trial and error.

**Additional context**
This is a great app, thank you!

**Comment by ekalin** [comment]
That's available as `{shortcode}` for `--filename-pattern`, see https://instaloader.github.io/basic-usage.html#filename-specification

**Comment by Showmaster3000** [comment]
Correct, to get the filename template in your example, use the following parameter: `--filename-pattern={date_utc}_UTC__{shortcode}`.

**Comment by Jon8RFC** [comment]
Wow, thank you both for letting me know AND for the usage exmple!
