### ISSUE TITLE
Download "stories" & "highlights into their own separate subdirectory.

### ISSUE THREAD

**Issue by atmos-o** [instaloader/instaloader#1249]
**Use case**:
Being able to locate different types of images much more easiy. So if someone wants to find a story from a specific date they can do so much faster.

**solution**: 
I think it should be fairly easy to do. Just simply have folders named "stories" & "highlights"

**considered alternatives**:
Manually trying to organise them all is not very feasible.

**Comment by Showmaster3000** [comment]
This feature was already requested in #253 some time ago, so closing this one.
