### ISSUE TITLE
collect all comment

### ISSUE THREAD

**Issue by parsibox** [instaloader/instaloader#125]
hi
I want to collect all comments from the post with 42,000 comments
i set this command
```
 instaloader --comments  --post-filter="comments>40000" xxx
```
but comment file has 3k comment
what can i do to get all 42k comments ?

**Comment by aandergr** [comment]
Most probably, Instagram does not return more than that amount of comments, and Instaloader goes through all retrievable comments and saves them.

Is there an official App that shows any comment that Instaloader doesn't? If not, there is nothing we can do about it.

(reminds me of #55 and #20, which was the same issue regarding hashtags)

**Comment by parsibox** [comment]
i see some site that they collect all comment
