### ISSUE TITLE
what exactly is the code to import only  say like 10 post from a profile which has 90 post

### ISSUE THREAD

**Issue by tenjiku** [instaloader/instaloader#1250]
what exactly is the code to import only say like 10 posts from a profile which has 90 posts?

is it  --count COUNT, -c¶ ?

if so how can I use it for:  instaloader therock

**Comment by Hassibayub** [comment]
I came here for the same question. 

`--count` only works at the feed. is it mean its only works on its own profile field not while downloading from other profile photos?

**Comment by tenjiku** [comment]
> 
> 
> I came here for the same question.
> 
> `--count` only works at the feed. is it mean its only works on its own profile field not while downloading from other profile photos?

could you paste the code you used which worked on the feed? maybe I can try a variation of it.

**Comment by sanmed02** [comment]
any idea on how to limit the count of downloaded posts ?

**Comment by robertzxz** [comment]
im dying for this feature, too bad i clueless with python so i cant modify shit

**Comment by Hassibayub** [comment]
I'm forking it and start working on this feature. hope the admin would accept the pull request.

**Comment by Hassibayub** [comment]
I'm forking it and start working on this feature. hope the admin would accept the pull request.
