### ISSUE TITLE
Download posts with certain caption or had certain string in captions.

### ISSUE THREAD

**Issue by APalJij** [instaloader/instaloader#1258]
How to download all posts (from Public accounts) on Instagram with a certain caption or certain string in the captions.

**Comment by Deleora** [comment]
You'll have to make some changes to the base code. Or perhaps use Instaloader as a module and write a script from scratch which would check for certain strings in each post caption and then only proceed to download.
PS: AFAIK Instaloader has all the methods required to get this implemented so you'll just have to insert the 'check caption' part somehow.

This is a very specific use case so I highly doubt that developers are going to implement it in the Instaloader as a feature.
