### ISSUE TITLE
Download stops after newest 12 posts.

### ISSUE THREAD

**Issue by Knuschberkeks** [instaloader/instaloader#1263]
I tried this on multiple insta profiles but it always stops downloading after the latest 12 posts.
I'm using version 4.8.1 on Ubuntu.
Example:
I input: `instaloader profile officialjeffhanneman --tagged --igtv`
and get the output:

> JSON Query to profile/feed/: 404 Not Found [retrying; skip with ^C]
> JSON Query to profile/feed/: 404 Not Found [retrying; skip with ^C]
> profile: Redirected to login page. Use --login.
> 
> HTTP redirect from https://www.instagram.com/web/search/topsearch/ to https://www.instagram.com/accounts/login/
> Stored ID 42798316760 for profile officialjeffhanneman.
> Hint: Use --login to download higher-quality versions of pictures.
> [1/1] Downloading profile officialjeffhanneman
> officialjeffhanneman/2020-10-13_17-43-36_UTC_profile_pic.jpg Download tagged of officialjeffhanneman: Redirected to login page. Use --login.
> 
> Retrieving tagged posts for profile officialjeffhanneman.
> 
> HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
> Retrieving IGTV videos for profile officialjeffhanneman.
> [1/1] officialjeffhanneman/2021-01-19_23-15-05_UTC.jpg officialjeffhanneman/2021-01-19_23-15-05_UTC.mp4 json 
> Retrieving posts from profile officialjeffhanneman.
> [  1/198] officialjeffhanneman/2021-08-25_15-06-51_UTC.jpg [Thank you Alvaro @AL S for se…] json 
> [  2/198] officialjeffhanneman/2021-08-24_17-19-49_UTC.jpg [Jeff with his parents George …] json 
> [  3/198] officialjeffhanneman/2021-08-22_16-05-09_UTC.jpg [Photo taken by @ndrewstuart O…] json 
> [  4/198] officialjeffhanneman/2021-08-20_20-39-10_UTC.jpg [That “confidence” and “attitu…] json 
> [  5/198] officialjeffhanneman/2021-08-19_13-50-15_UTC.jpg [This photo of Jeff in 1984 “a…] json 
> [  6/198] officialjeffhanneman/2021-08-17_15-07-24_UTC_1.jpg officialjeffhanneman/2021-08-17_15-07-24_UTC_2.jpg [Thank you Juan @lucifugeoffic…] json 
> [  7/198] officialjeffhanneman/2021-08-15_16-39-24_UTC.jpg [Jeff is New York 1987. Photo …] json 
> [  8/198] officialjeffhanneman/2021-08-13_22-51-37_UTC.jpg [Jeff with his Coors Light “st…] json 
> [  9/198] officialjeffhanneman/2021-08-11_23-43-29_UTC.jpg [Another photo of Jeff in Mont…] json 
> [ 10/198] officialjeffhanneman/2021-08-07_17-05-45_UTC_1.jpg officialjeffhanneman/2021-08-07_17-05-45_UTC_2.jpg [Drawing sent by Felix @fix_gt…] json 
> [ 11/198] officialjeffhanneman/2021-08-06_20-07-13_UTC.jpg [Another mid 80’s photo sent b…] json 
> [ 12/198] officialjeffhanneman/2021-08-05_15-24-07_UTC_1.jpg officialjeffhanneman/2021-08-05_15-24-07_UTC_2.jpg officialjeffhanneman/2021-08-05_15-24-07_UTC_3.jpg [Thank you Izabela@izaholyston…] json officialjeffhanneman: Redirected to login page. Use --login.
> 
> Errors or warnings occurred:
> profile: Redirected to login page. Use --login.
> Download tagged of officialjeffhanneman: Redirected to login page. Use --login.
> officialjeffhanneman: Redirected to login page. Use --login.
> 
> 
> HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/

removing `--tagged` and `--igtv` doesn't help.

**Comment by Showmaster3000** [comment]
Thats correct, but Instagram changed behaviour: downloading more than 12 posts mostly requires login these days.

**Comment by 89z** [comment]
https://github.com/instaloader/instaloader/issues/1278

**Comment by 89z** [comment]
https://github.com/instaloader/instaloader/issues/1293

**Comment by 89z** [comment]
> Thats correct, but Instagram changed behaviour: downloading more than 12 posts mostly requires login these days.

No, it doesnt. Other better options may exist, but I know you can get more than 12 using the embed links:

https://www.instagram.com/p/CT-cnxGhvvO/embed/
