### ISSUE TITLE
Cookie import failed: no such table: moz_cookies

### ISSUE THREAD

**Issue by Catralitos** [instaloader/instaloader#1264]
**Describe the bug**
I can not import my cookies using the 615_import_firefox_session-py script. I input it, passing the correct path with -c, and it doesn't matter if Firefox is open or closed, I get "Cookie import failed: no such table: moz_cookies".
I pass the {PATH TO FILE}\cookies.sqlite as an argument. (I have to pass the path, it does not pick up automatically, it might be cause I'm running on a different hard drive from C: where the Linux subsystem for Windows 10, in which I run python, is installed).

This is the latest version of the script, downloaded today, August 27th 2021.
 
This is frustrating as I have many accounts I want to save, but I get so many suspicious login attempts. I have tried 2FA, but the code I get (when I get it, cause sometimes insta is like "Nah, we're blackmailing your number for a week") never works. ("2FA error: This code is no longer valid. Please request a new one.")

I thought if I turned it on, logged in on Firefox, and imported my session from Firefox, it would not try to log in again on the command line. But I can't import the cookies.

**Comment by Showmaster3000** [comment]
This is not a bug in instaloader rather a thing of an additional script.
Please post the full commandline you (try to) use to import the cookies. Also include the output if there is any.

**Comment by Catralitos** [comment]
I use the command: 
python3 615_import_firefox_session.py -c "C:\Users\catra\AppData\Roaming\Mozilla\Firefox\Profiles\zjelovq3.default-release\cookies.sqlite"

And the output is:
Using cookies from C:\Users\catra\AppData\Roaming\Mozilla\Firefox\Profiles\zjelovq3.default-release\cookies.sqlite.
Cookie import failed: no such table: moz_cookies

I tried using python 3.9 instead given it's the most recent version of python, so with the same command, but python3.9 instead of python3, but I get:
Instaloader not found.
  pip install [--user] instaloader

Instaloader is installed, I use it. From both a script and the command line. I'm wondering at this point if putting a bunch of sleeps in my shell scripts so after a few logins it pauses a bit will do better. Maybe then Instagram would not complain as much about suspicious logins, but I don't know how long I'd have to take a pause and how frequently.

**Comment by aandergr** [comment]
> Using cookies from C:\Users\catra\AppData\Roaming\Mozilla\Firefox\Profiles\zjelovq3.default-release\cookies.sqlite.
> Cookie import failed: no such table: moz_cookies

This looks to me like your Firefox is not storing the cookies in the way our script expects, so I suspect that Firefox may have changed how the cookies database is organized. It would be interesting to know which Firefox version you are using. Personally, I use Firefox ESR (version 78.x) and the cookie import script still works fine with that.

> Instaloader is installed, I use it.

Yes it is; the cookies import script also uses Instaloader, and it would show a different error message if Instaloader was not properly installed. 

> I'm wondering at this point if putting a bunch of sleeps in my shell scripts so after a few logins it pauses a bit will do better. Maybe then Instagram would not complain as much about suspicious logins, but I don't know how long I'd have to take a pause and how frequently.

In general, we recommend using the login as rarely as possible. Login once manually, save the session file, and then use only that session file in your scripts. Naturally, the login procedure is their most delicate piece, and they carefully compare the login usage pattern to what is considered normal. Having multiple login calls in a script that is regularly executed is probably the highway to getting a 'suspicious login'.

**Comment by Catralitos** [comment]
How do I save the session file after one login? Do I just use login on the first command of the script?

**Comment by aandergr** [comment]
Which Firefox version do you use?

**Comment by Catralitos** [comment]
91.0.2 (64-bit)

**Comment by Catralitos** [comment]
Look the way I have it set up is a shell script where each line is:
instaloader --login [MY USER] --[ARGS] [PROFILE] 

and I have a lot of these lines.
Would making a python script or using +args.txt make it so it's only one login for all the profiles?

**Comment by Catralitos** [comment]
I'm doing a python script instead of a shell script now, like this, it should work for my needs:

```
import instaloader

bot = instaloader.Instaloader()

bot.login([USER], [PASS])

listUsers = ["USEREXAMPLE"]

profileList = []

for user in listUsers:
    profileList.append(instaloader.Profile.from_username(bot.context, user))

bot.download_profiles(profiles=set(profileList), profile_pic=True, posts=True,
                          tagged=True,
                          igtv=True,
                          highlights=True,
                          stories=True,
                          fast_update=True)
```

**Comment by lyndseawar** [comment]
Hey  @Catralitos , 

I'm actually trying to do some similar work. We are attempting to integrate our requests into a larger web interface and store our downloaded profiles inside GCS. I would enjoy chatting with you concerning our methods if you'd be open. 

Cheers.

**Comment by Catralitos** [comment]
This script's worked for one user, I'm testing it for a lot of them now. The thing is I can't use the --no-captions and --no-metadata-json options with this method as far as I'm aware. May have to do a second script to occasionally scrub and delete those extra files that aren't images or videos.

**Comment by lyndseawar** [comment]
@Catralitos , Where are you storing your downloaded profiles? Your script looks like you're downloading the whole node. Are you parsing the node after the download, or is your goal to simply download the post nodes of multiple profiles that you provide?

**Comment by Catralitos** [comment]
I just want to pass a list of profiles and rip them: tagged posts, stories, highlights, you name it. Just want pictures and videos, no captions or JSON. Managed to get rid of JSON by setting the bool to false on the instaloader constructor but getting rid of captions is proving tougher.

I have a folder where each subfolder is a profile. Because I'm not that tidy I just pasted the instaloader source code on this folder, so my python script can run on it.

**Comment by Catralitos** [comment]
I just went to the download_post method and commented out the 3 lines where it calls save_caption so I think it's working now.

**Comment by lyndseawar** [comment]
Nice! I'm working through getting everything to include the captions and JSONs so my parsing is a bit more detailed. Thanks for being so open! I'm working through the session log-in and retrieval right now.

**Comment by Catralitos** [comment]
Yeah my main problem is I was logging in once per profile. Now with this python script, I can just log in once, by the looks of it. I'm still testing on one profile, to check if I can get one with no captions/JSON right. 

But if this works as intended I'll report back and close this, even though my problem at the start ended up being fixed with a very different solution.

**Comment by Catralitos** [comment]
Ok, it's not finished yet (a lot of profiles, but it looks like it's working), but I had to make a small adjustment.
One thing I noticed when I ran the download_profiles method with a set of two is that it downloaded the stories of the first profile after beginning to download stuff from the second profile. It wasn't just "rip profile 1 completely, then move on to profile 2".
So because of this, when I passed a set of 100+ profiles, it crashed.
So instead of one time passing a set of X profiles, I X times pass a set of 1 profile in a cycle, and it's working and it's still only one login as far as I can tell.

So it's:

```
import instaloader

bot = instaloader.Instaloader()

bot.login([USER], [PASS])

listUsers = ["USEREXAMPLE"]

for user in listUsers:
      profile = instaloader.Profile.from_username(bot.context, user)
      bot.download_profiles(profiles=[profile], profile_pic=True, posts=True,
                          tagged=True,
                          igtv=True,
                          highlights=True,
                          stories=True,
                          fast_update=True)
```
you can change the parameters of the download_profiles method to pick what is downloaded. If you don't want captions or JSON, just open instaloader.py in the instaloader folder, and CTRL-F "#save caption" and "# save metadata" and comment those ifs/method calls so they skip it.

I don't know if this will trigger a "too many requests" error, maybe for profiles with a lot to download, but it looks like it's just one session and it's not gonna give me a suspicious login error.

Though after a while, it starts giving me 403 and 500 HTTP errors when trying to download images and such, so I don't know what's causing it and if I can fix it. Maybe it's just too many queries, and I should sleep or something every X profiles.

**Comment by Catralitos** [comment]
Never mind Instagram locked me out of my account again (my phone number is blacklisted, but if I wait like a week, it should let me get my account back, it's happened before). I'm confident that when I go back, there will only be one login for all these profiles, it's probably a number of requests thing. I have a second account, maybe I should get some profiles with that one, to decrease the chances of this happening.
But man Instagram is really strict.

**Comment by lyndseawar** [comment]
Dude for real. I have had the same issue with one of my accounts. I'm passing everything through beam to integrate into a larger request structure so things are a bit different on my end. I am currently getting the feedback_required message.

`class FetchUserPosts(beam.DoFn):
    def setup(self):
        # get instance of instaloader
        self.L = instaloader.Instaloader()
        # Optionally, login or load session
        self.L.login(USER, PASSWORD)  # (login)
        # saves internally stored requests.Session object
        # self.L.save_session_to_file(filename=tmp_session.txt)

    # TODO: create safe sessionto file
    # def save_session_to_file(self):

    def process(self, request):
        users = request["users"]
        for user in users:
            logging.info("Fetching Instagram user posts for username %s...", user)
            profile = Profile.from_username(self.L.context, user)
            posts = profile.get_posts()
            for post in posts:
                logging.info("Found post  %s", post)
                post_dict = {
                    "shortcode": post.shortcode,
                    "title": post.title,
                    "date": post.date_utc.isoformat(),
                    "owner_username": post.owner_username,
                    "owner_id": post.owner_id,
                    "url": post.url,
                    "typename": post.typename,
                    "mediacount": post.mediacount,
                    "caption_hastags": post.caption_hastags,
                    "pcaption": post.pcaption,
                    "tagged_users": post.tagged_users,
                    "is_video": post.is_video,
                    "video_url": post.video_url,
                    "video_view_count": post.video_view_count,
                    "likes": post.likes,
                    "comments": post.comments,
                    "is_sponsored": post.is_sponsored,
                    "display_url": post.display_url,
                    "text": post.text,
                    "id": post.id,
                    "lat": post.lat,
                    "lng": post.lng,
                    "name": post.name,
                    "slug": post.slug,
                    "table_name": request["table_name"],
                }
                yield post_dict


class FetchInstagram(PTransform):
    def expand(self, p):
        return p | "fetch instagram user" >> beam.ParDo(FetchUserPosts())`

**Comment by Catralitos** [comment]
But you're not downloading the files, right? Maybe it has to do with that?

**Comment by sohel510** [comment]
you need to locate cookies.sqlite file in my case i did it like this     cookiefile= 'cookies.sqlite'
    print("Using cookies from {}.".format(cookiefile))
    conn = connect(f"file:{cookiefile}?immutable=1", uri=True)

**Comment by sohel510** [comment]
there must be path issue,  locate "cookies.sqlite" from /snap/firefox/common/.mozilla/firefox/cookies.sqlite copy this file into working dir modified this part in the 615_import_firefox_session.py file and run it it should work 
    `
def import_session(cookiefile, sessionfile):
    cookiefile= 'cookies.sqlite'
    print("Using cookies from {}.".format(cookiefile))
    conn = connect(f"file:{cookiefile}?immutable=1", uri=True)`

**Comment by yadgire7** [comment]
I have added this line: loader.load_session_from_file(r'C:\Users\admin\AppData\Local\Instaloader\session-yadgire7')
to my code, but it throws an error: Invalid argument: 'c:\users\admin\appdata\local\temp/.instaloader-admin/session-c:\users\admin\a
ppdata\local\instaloader\session-yadgire7'
Please help me out with this.
