### ISSUE TITLE
--fast-update with stories download problem

### ISSUE THREAD

**Issue by Azureit** [instaloader/instaloader#1266]
**Describe the bug**
If you upload to instagram stories first a video and immediately a image, sometimes instagram will publish first the image and take some time to process and publish the video. In that time if you call instaloader it will download the story image and miss the video, then next time you call instaloader with --fast-update it will skip the image already downloaded and not care about the video.

**Expected behavior**
Disable --fast-update at stories download

**Instaloader version**
4.8.1

**Comment by Thammus** [comment]
This is a very rare edge case. To run into this bug one would need to instaload with `--fast-update` while the video story still is processing. But I am convinced that it is better to have the `--fast-update` feature for stories than to avoid rare bugs like this.
