### ISSUE TITLE
Incorrect follower/followee count

### ISSUE THREAD

**Issue by sarandafl** [instaloader/instaloader#1267]
**Describe the bug**
When retrieving a profile via username or id and then getting the follower or followee count, returns a "cached" value.
```
L = instaloader.Instaloader()
L.user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36'
L.login('USERNAME', 'PW')
print(instaloader.Profile.from_id(L.context, ID).followees)
```

**To Reproduce**

- Request followees for profile id using different accounts (A + B)
- View the iOS app with A + B
- View the web app with A + B 

**Expected behavior**
All three follower and followee counts should be the same. Only instaloader is returning outdated/incorrect values.

**Error messages and tracebacks**
N/A

**Instaloader version**
`instaloader 4.8.1`.

**Additional context**
This is in regards to a private user profile. But since the info is public it shouldn't be an issue. I have not tested this with a public account yet.

**Comment by Deleora** [comment]
From my observation I feel it's the Instagram app (or even web too) that doesn't show correct numbers. I've seen it showing different post count, followers & following counts on web (when viewing from account that doesn't follow the target profile) and android app (when viewing from account that follows the target profile). The target profile I'm talking about is private.
Have you tried this?

**Comment by aandergr** [comment]
With your codesnippet, Instaloader will show the value as returned by Instagram. With that invocation, the value is fetched directly and in no way "cached" by Instaloader. This issue is unclear.
