### ISSUE TITLE
JSON Query to graphql/query: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

### ISSUE THREAD

**Issue by wwsaghi** [instaloader/instaloader#1271]
**Describe the bug**
JSON Query to graphql/query: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
comment and get storeis

**Expected behavior**
I developed a program that can download Stories and post with their comments and was working well
anyway after 2 days ago, get_stories and get_comment method not working, but still I can download posts
![a](https://user-images.githubusercontent.com/76466331/132085839-5eaabd6a-09e8-49c7-a258-9e6065f6be53.PNG)

**Error messages and tracebacks**
 JSON Query to graphql/query: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

**Instaloader version**
4.8.1

**for get stories I used:**
```python
for story in L.get_stories():
    for item in story.get_items():
        L.download_storyitem(item, 'stories')
```

**and for get comments used:**
```python
post=instaloader.Post.from_shortcode(L.context,shortcode)
for x in post.get_comments():
     print(x.text)
```

**Comment by fireattack** [comment]
Probably obvious, but did you log in? Can you post the full code about how you create `L` object ?

I tried the following
```
import instaloader

my_username = '*****'
L = instaloader.Instaloader()
L.load_session_from_file(my_username)

for story in L.get_stories():
    for item in story.get_items():
        L.download_storyitem(item, 'stories')

shortcode = 'CTY4zs5Fm-T'
post=instaloader.Post.from_shortcode(L.context, shortcode)
for x in post.get_comments():
     print(x.text)
```

and they work fine.

**Comment by Showmaster3000** [comment]
Imo this is not a bug. In all my cases, the error message points out that the target profile is disabled or deleted. Please check that in a web browser if the profile is really avaiable (you don't need to login there, just open the profile page and see if it exists)

**Comment by wwsaghi** [comment]
Thanks for comments I reinstall Instaloader and my problem solved
