### ISSUE TITLE
When a profile is renamed, the folder name does not change

### ISSUE THREAD

**Issue by ungenio** [instaloader/instaloader#1276]
**Describe the bug**
When using the `--latest-stamps` parameter and a profile has changed its name Instaloader does not rename the folder with the new nickname but creates a new folder.

**To Reproduce**
Old profile data must be in `latest-stamps.ini` because Instaloader no longer uses the `id` file of the profile folder.
Run Instaloader using the old nickname.

**Expected behavior**
The name of the profile folder should automatically change with the new nickname.

**Error messages and tracebacks**
Instaloader displays a message that the profile has been renamed, but the folder name does not change.

**Instaloader version**
instaloader-v4.8.1-windows-standalone

**Comment by KertLynx** [comment]
The issue still persists.

**Comment by KertLynx** [comment]
The issue still persists. Is there a workaround?
