### ISSUE TITLE
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/

### ISSUE THREAD

**Issue by ThierryBegin** [instaloader/instaloader#1278]
After downloading 12 pictures we get 
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
errors
I tried switching IP and it's seem to do the exact same thing.

**Comment by Showmaster3000** [comment]
too less information, no template. looks like #1263
