### ISSUE TITLE
Add a cli option to choose the bind ip for outgoing connections

### ISSUE THREAD

**Issue by d3xt3r01** [instaloader/instaloader#1282]
**Provide us a use case of the feature**
I would like to use instaloader to be able to grab posts without an account. This should be doable on a box with multiple ips.

**Describe the solution you'd like**
I would like some parameters for:
debug - to see what http/https connection the application tries to do... maybe even some levels to see the parameters/headers, or even a stacktrace
ipv6 - to enable/disable the use of ipv6 ( I don't know if ipv6 is used right now anyway )
bindip - ability to bind to a specified address

**Describe alternatives you've considered**
I was thinking about writing my own code but I'm not that good.

**If the feature request is accepted, would you be willing to submit a pull request?**
No... because I have no idea what implications there are with the various modules used.

**Comment by bart4371** [comment]
I would like something like this but perhaps for different accounts. So one account downloads via one ip, another via a different one. In order to circumvent Instagram's rate limits. I'm getting a lot of bad requests now, even when rotating between 10 different accounts.
