### ISSUE TITLE
404 Not Found 

### ISSUE THREAD

**Issue by 89z** [instaloader/instaloader#1290]
~~~
PS C:\> instaloader profile britneyspears
JSON Query to profile/feed/: 404 Not Found [retrying; skip with ^C]
~~~

**Comment by Showmaster3000** [comment]
the word `profile` is not needed. Instaloader thinks you want to download the profile `profile` (which does not exist) and `britneyspears`.

**Comment by 89z** [comment]
@Showmaster3000 thanks for the help. The documentation is misleading, as it gives this example:

~~~
instaloader profile [profile ...]
~~~

which implies that `profile` should be inputted literally, same as `instaloader`. I think better would be something like:

~~~
instaloader <profile> [profile ...]
~~~
