### ISSUE TITLE
 Get post info 

### ISSUE THREAD

**Issue by 89z** [instaloader/instaloader#1291]
If I have a post such as this:

https://www.instagram.com/p/CT-cnxGhvvO/

How do I get the info for this post? Sorry for the basic question, but I have looked over the API and am not seeing a way to do this.

**Comment by Showmaster3000** [comment]
Too less information what you want to do. and if you use command line or python module.
Anyway, the manual gives you the following command: `instaloader -- -CT-cnxGhvvO` - see here: https://instaloader.github.io/cli-options.html

**Comment by 89z** [comment]
Is it possible without login?

~~~
PS C:\> instaloader -- -CT-cnxGhvvO
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
-CT-cnxGhvvO: Redirected to login page. Use --login.
~~~
