### ISSUE TITLE
When downloading a profiles images, instaloader stops at the 12th post

### ISSUE THREAD

**Issue by uzzywastaken** [instaloader/instaloader#1293]
![d32554062e20fa5bb095477512ecb609](https://user-images.githubusercontent.com/89166344/134505870-ee3c606f-f421-4898-a795-492e325ef61a.png)

**Comment by 89z** [comment]
Same problem

**Comment by Showmaster3000** [comment]
The error message is clear: you have to login to proceed. Use additional parameter `--login your-account` to get all elements.
Duplicate of #1263.
