### ISSUE TITLE
how to prohibit downloading

### ISSUE THREAD

**Issue by Mrakobes666** [instaloader/instaloader#1298]
how to prohibit downloading 2021-09-10_19-46-05_UTC. json.xz and 2021-09-10_23-46-11_UTC.txt files, not found in the help

instaloader.exe --login e*****t --password W*****6 --post-filter="not is_video" theartof***

**Comment by Showmaster3000** [comment]
The documentation I see says something about `--no-captions` and `--no-metadata-json` 
see here: https://instaloader.github.io/cli-options.html#cmdoption-no-captions
and here: https://instaloader.github.io/cli-options.html#cmdoption-no-metadata-json

**Comment by Mrakobes666** [comment]
thanks
