### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by Rcola1987** [instaloader/instaloader#130]
Is there a way to montarley support this project? You all are doing great work and franky this project is better than any of the commercial options out there and since i do not code in the languages you are using i was wondering if there was a way to donate to you all.

Thanks for the excellent project, fast and courteous support!

**Comment by aandergr** [comment]
Thanks a lot for praising our work. It is a pleasure for us to share our Instaloader to the world, and we are proud to have attracted such an active and motivating community, with so many users who share their suggestions and ideas with us. Buying a community-sponsored beer or coffee from time to time is very likely to further raise our passion for the development of Instaloader.

I now created a paypal.me link for donations:

https://paypal.me/aandergr

**Comment by santosh** [comment]
Shall this be closed?
