### ISSUE TITLE
Using the --latest-stamps argument may not download profile(s).

### ISSUE THREAD

**Issue by edgarkanye** [instaloader/instaloader#1304]
**Describe the bug**
Using the `latest-stamps` argument may cause **Instaloader** not to download profiles.  Since `latest-stamps` takes an optional string argument, using it as the last argument consumes the first profile argument (if many) leaving the program with less downloadable profiles by 1.

In other words, `latest-stamps` acts both as a string argument and also a boolean argument. 

**To Reproduce**
Try downloading/updating a profile with `latest-stamps` as the last argument before the profile name. For example, 
`instaloader +args.txt --no-captions --no-video-thumbnails --latest-stamps <profile_name>`

`+args.txt` here specifies the file with my login credentials.

**Expected behavior**
One should be able to use `latest-stamps` as the last argument in the list of arguments to the program and still download all specified profiles.

**Error messages and tracebacks**

#### With one profile to download
As a last argument, it takes the name of the profile to be downloaded as the name of  `latest-stamps-file`, leaving no profiles to be downloaded.

```sh
➜  ~ instaloader +args.txt --no-captions --no-video-thumbnails --latest-stamps jack
Using latest stamps from jack.
Loaded session from /Users/kertx/.config/instaloader/session-username.
Logged in as username.
Saved session to /Users/kertx/.config/instaloader/session-username.
No targets were specified, thus nothing has been downloaded.
```

#### With more than one profile to download/update
It assumes the first profile to be the provided name for the`latest-stamps` file but since it already exists as a directory, errors out. 

```sh
➜  ~ instaloader +args.txt --no-captions --no-video-thumbnails --latest-stamps jack zuckerberg
Using latest stamps from jack.
Loaded session from /Users/kertx/.config/instaloader/session-username.
Logged in as username.
Traceback (most recent call last):
  File "/opt/homebrew/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/instaloader/__main__.py", line 467, in main
    _main(loader,
  File "/opt/homebrew/lib/python3.9/site-packages/instaloader/__main__.py", line 182, in _main
    profile = instaloader.check_profile_id(target, latest_stamps)
  File "/opt/homebrew/lib/python3.9/site-packages/instaloader/instaloader.py", line 1325, in check_profile_id
    latest_stamps.save_profile_id(profile.username, profile.userid)
  File "/opt/homebrew/lib/python3.9/site-packages/instaloader/lateststamps.py", line 46, in save_profile_id
    self._save()
  File "/opt/homebrew/lib/python3.9/site-packages/instaloader/lateststamps.py", line 28, in _save
    with open(self.file, 'w') as f:
IsADirectoryError: [Errno 21] Is a directory: 'jack'
```

**Instaloader version**
4.8.1

**Additional context**
When the `latest-stamps` argument is tucked within other arguments, the profiles are downloaded normally. In the demo below, notice how `--fast-update` comes last before the target profiles.

```sh
➜  ~ instaloader +args.txt --no-captions --latest-stamps --fast-update jack
Using latest stamps from /Users/kertx/.config/instaloader/latest-stamps.ini.
Loaded session from /Users/kertx/.config/instaloader/session-username.
Logged in as username.
[1/1] Downloading profile jack
...
```

- Operating System: MacOS 11.6 (Big Sur), M1 MacBook Pro
- Python: 3.9.7

**Comment by ekalin** [comment]
That's how command line parsing works, and is this same behavior can be found in other applications that have similar command line options with optional arguments.

Since `--latest-stamps` can have an optional argument to specify the file where the timestamps are saved, any non-option text passed just after it is considered it's argument, since `jack` is a valid file name, `--latest-stamps jack` is interpreted as enabling `--latest-stamps` with an argument of `jack`. If you have another option after `--latest-stamps`, then the parser can know that you're not specifying the optional argument.

You can stop argument parsing with `--`: this indicates that everything that follows is not options, but rather plain arguments (which for instaloder represent targets to be downloaded):
```
instaloader --latest-stamps -- jack
```

**Comment by edgarkanye** [comment]
Thank you for the clarification @ekalin. 
Where as using `--latest-stamps -- <profile>` is the standard way of parsing command-line arguments, I feel it deviates from the previously existing API where every argument option to the program was a boolean, (except when downloading individual posts).

This could be my personal taste but I think having two arguments in this case would make for a more consistent API.
That is, 

`--latest-stamps` is a boolean that indicates that one needs to update their archive via latest stamps, using the default latest stamps file and then `--latest-stamps-file` which takes a filename. 

You could make the case that doing it this way would make `--latest-stamps` a drop-in replacement for `--fast-update`.
