### ISSUE TITLE
%z in datetime style formatting options doesn't return offset

### ISSUE THREAD

**Issue by SpL1Ne** [instaloader/instaloader#1305]
**Describe the bug**
%z in datetime style formatting options doesn't return offset

For example:
- `--latest-stamps` option for profile download return `2021-10-03T09:49:02.000000+0300` timestamp
- For latest post from same profile `--post-metadata-txt="{date:%Y-%m-%dT%H:%M:%S.%f%z}"` returns `2021-10-03T06:49:02.000000`
- For same post `--post-metadata-txt="{date_local:%Y-%m-%dT%H:%M:%S.%f%z}"` returns `2021-10-03T09:49:02.000000`

And in both cases %z is empty

**To Reproduce**
`instaloader --post-metadata-txt="{date_local:%Y-%m-%dT%H:%M:%S.%f%z}" -- -<post_id>`

**Expected behavior**
For second case `--post-metadata-txt` %z should return +0300

**Error messages and tracebacks**
None

**Instaloader version**
4.8.1

**Additional context**
None.

**Comment by aandergr** [comment]
Indeed, thanks for reporting! `date_utc` and `date_local` currently are naive datetime objects which do not carry timezone information, hence `%z` is empty.

**Comment by aandergr** [comment]
Fixed in [Version 4.8.3](https://github.com/instaloader/instaloader/releases/tag/v4.8.3).

**Comment by aandergr** [comment]
I have postponed the change that date_local returns a timezone-aware datetime object to version 4.9, and date_utc remains a timezone-unaware datetime object, as a compromise, especially to maintain compatibility between minor releases of version 4.8, and still provide a timezone-aware datetime object as of 4.9 as date_local, without breaking backwards compatibility in date_utc comparisons. Accordingly, I have also removed this change from 4.8 and moved it to 4.9.
