### ISSUE TITLE
429 Error (Too Many Requests)

### ISSUE THREAD

**Issue by ItsRaminTime** [instaloader/instaloader#1308]
Your question here...
Hi there! I've been using Instaloader for a while now but starting Monday, it is now throwing a 429 error after about a hundred or so requests and continues to do so. I've waited to let the IP cool down, changed out the IP, etc. but nothing has helped.
I've also looked through the other threads regarding 429 errors and neither of those seem to help either / come to a full conclusion. Is there something I can tweak to avoid these errors?

**Comment by 89z** [comment]
I found you can get more requests by logging in. Are you doing that?

**Comment by 89z** [comment]
Sorry I cant help you. From my recent experience, you can get a limited number of anonymous requests, then you are locked out until the next day, or until you log in. Good luck.

**Comment by IIJlOXOCIIAJl** [comment]
I have the same error. Did you manage to solve it?
