### ISSUE TITLE
instaloader returns likes count is -1 but browser data shows likes count

### ISSUE THREAD

**Issue by vanishinggradient** [instaloader/instaloader#1314]
**Describe the bug**

edge_media_preview_like is a finite value when seen in a browser i.e window._sharedData.entry_data.PostPage[0].graphql.shortcode_media

![2021-10-18_21-03](https://user-images.githubusercontent.com/61178871/137771308-d2c21f22-54c1-4fdc-81dd-fea838892b5a.png)

but in instaloader's in node object it is -1

![2021-10-18_21-02_1](https://user-images.githubusercontent.com/61178871/137771291-7454f66d-0849-4987-8522-ac393b6abb3f.png)

**To Reproduce**

https://www.instagram.com/p/CUrAS88Pr1G/

```
from instaloader import Instaloader, Post
loader = Instaloader()
post = Post.from_shortcode(loader.context, "CUrAS88Pr1G'')
print(post.likes) # prints -1
```

**Additional context**

It seems to happen only for logged in accounts on certain posts (ones with like_and_view_count_disabled = true), post.likes works if I am not logged in

but if you are rate limited on IP post.likes requests login

I have noticed a pop up opens up when I am logged in and then it calls https://www.instagram.com/p/CUrAS88Pr1G/likedby to get data but I just want to get number of likes

**Expected behavior**

It should return number of likes 1436 as of now

**Error messages and tracebacks**

None

**Instaloader version**
`instaloader --version` is 4.8.1

**Comment by aandergr** [comment]
> **To Reproduce**
> 
> https://www.instagram.com/p/CUrAS88Pr1G/
> 
> ```
> from instaloader import Instaloader, Post
> loader = Instaloader()
> post = Post.from_shortcode(loader.context, "CUrAS88Pr1G'')
> print(post.likes) # prints -1
> ```

With this code, i.e. anonymously, Instaloader returns the correct likes count. However, when logged in, the likes count or -1 is shown, depending on the account settings.

**Comment by beshoo** [comment]
> With this code, i.e. anonymously, Instaloader returns the correct likes count. However, when logged in, the likes count or -1 is shown, depending on the account settings

What do you mean by "Depending on the account settings", is there a setting I can turn on to see like count when being logged in?

**Comment by pvita** [comment]
> > **To Reproduce**
> > https://www.instagram.com/p/CUrAS88Pr1G/
> > ```
> > from instaloader import Instaloader, Post
> > loader = Instaloader()
> > post = Post.from_shortcode(loader.context, "CUrAS88Pr1G'')
> > print(post.likes) # prints -1
> > ```
> 
> With this code, i.e. anonymously, Instaloader returns the correct likes count. However, when logged in, the likes count or -1 is shown, depending on the account settings.

It seems to not depend on account settings, cause I'm triyng on many thousands of shortcodes and the results (collecting not anonimously) is always -1

**Comment by aandergr** [comment]
See https://help.instagram.com/113355287252104/

**Comment by pvita** [comment]
> See https://help.instagram.com/113355287252104/

Ok. Is there any workaround? Thanks
