### ISSUE TITLE
How to use proxies in instaloder instance?

### ISSUE THREAD

**Issue by Aditya-Rajgor** [instaloader/instaloader#1315]
How can I use **proxies** when login into the instaloder instance?
If possible, please provide the syntax.

Somewhere in the documentation, it's clearly written that you can/should not use two instaloader instances in parallel. Therefore I think we are only left with the option to run the different instances with different usernames and passwords right? I saw in one issue that lots of accounts got banned while running the scraper.  so **I want to add the proxy for my account security.**

Additionally, rotating the user-agent can help reduce the 429 error?

**Comment by Teresawithoutah** [comment]
Was having issues setting up the profixied version via https://github.com/restyler/instaloader -- interested to see answer.
