### ISSUE TITLE
The instructions for Windows are not helpful.. I Cannot make it work!

### ISSUE THREAD

**Issue by hosadokha** [instaloader/instaloader#1324]
I am a Windows user that usually deals with GUI's..
I downloaded the zip file which contains instaloader.exe  ... followed the instructions and I always get errors that my commands are not recognized... Do I need to install python nevertheless?, as I said I am just a USER not a coder...

**Comment by 89z** [comment]
Your comment is incredibly rude. If youre not happy with the software, dont use it. Perhaps I should remind you that this is free software, so you get what you pay for.

**Comment by hosadokha** [comment]
> Your comment is incredibly rude. If youre not happy with the software, dont use it. Perhaps I should remind you that this is free software, so you get what you pay for.

There, I edited it..
