### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by DarkSpeedKiller** [instaloader/instaloader#1327]
Other than the download.post 
how can i download stories/igtvs/highlights from a different profile than mine
im confused with the docs
can we get a youtube with all the commands

**Comment by Showmaster3000** [comment]
Your question is rather vague. Please describe your intention a little bit more. Looks like you try to use the python module? How about this section in the manual: https://instaloader.github.io/module/instaloader.html#instaloader.Instaloader.download_post ?

**Comment by DarkSpeedKiller** [comment]
Im pretty much trying to use the module to do a bunch of stuff that the module provides us. The documentation confuses me and i cant seem to make it work. 
I can use the download post even tho i got some trouble making it use the path i want to be saved + fast update not working
after loading an account i managed to use download saved posts + feed posts 
but cant download specific profile of my choice (stories/highlights/reels) the same way i use the download_posts

**Comment by DarkSpeedKiller** [comment]
> Im pretty much trying to use the module to do a bunch of stuff that the module provides us. The documentation confuses me and i cant seem to make it work. I can use the download post even tho i got some trouble making it use the path i want to be saved + fast update not working after loading an account i managed to use download saved posts + feed posts but cant download specific profile of my choice (stories/highlights/reels) nor hashtag posts the same way i use the download_posts so a youtube guide with examples of the docs would be pretty much appreciated



> Your question is rather vague. Please describe your intention a little bit more. Looks like you try to use the python module? How about this section in the manual: https://instaloader.github.io/module/instaloader.html#instaloader.Instaloader.download_post ?

**Comment by DarkSpeedKiller** [comment]
> Your question is rather vague. Please describe your intention a little bit more. Looks like you try to use the python module? How about this section in the manual: https://instaloader.github.io/module/instaloader.html#instaloader.Instaloader.download_post ?

Im pretty much trying to use the module to do a bunch of stuff that the module provides us. The documentation confuses me and i cant seem to make it work.
I can use the download post even tho i got some trouble making it use the path i want to be saved + fast update not working
after loading an account i managed to use download saved posts + feed posts
but cant download specific profile of my choice (stories/highlights/reels) nor hashtag posts the same way i use the download_posts
so a youtube guide with examples of the docs would be pretty much appreciated
