### ISSUE TITLE
Instaloader problem while getting images from hashtag with Sidecar

### ISSUE THREAD

**Issue by manthan340** [instaloader/instaloader#133]
I am experienced PHP developer but having very basic skills in python. But I am in desparate need of using Instaloader utility. I am facing some issues in fetching all the images of perticular hashtag. The only problem is **sidecar** images. I am describing my problem in 3 approaches I have used.

If you can guide me in **Any of them**, it will solve my problem.    
1. I want to extract images of particular hashtag. Images should also include all the images of _sidecar_ structure. But instaloader cli utility only fetches first photo of the sidecar. **Is there any way to get all the images from sidecar using cli utility**
2. When I use python code to get all the posts of hashtag, it shows wrong post type. 
`for post in L.get_hashtag_posts('cloudyweather2017'):`
`print(post.typename)` 
This code gives me 
`GraphImage`
`GraphImage`
Whereas one of them is a sidecar. I believe this is an issue.
3. In instagram PHP scraper, I found that when we get all posts using hashtag - We are not getting the sidecar images whereas if we try to fetch details of particular post - We are getting all the sidecar images. I tried to replicate the same behaviour here. But its not working. Following is the code.(P.S. I am getting too many timeouts in PHP scraper. that is why I want to use instaloader.) 
`from instaloader import Instaloader, Post`
`L = Instaloader()`
`post = Post.from_shortcode(L.context, 'BYkZsY2Avgz')`
`print(post.typename)`
When I execute this code, I am getting following error
`AttributeError: 'Instaloader' object has no attribute 'context'`
I have taken reference of [this example from Instaloader](https://instaloader.github.io/codesnippets.html#track-deleted-posts)

**Comment by Thammus** [comment]
Thanks for reporting. This was indeed a bug. We fixed it in version 4.0.4 and your approaches should work fine now.

**Comment by manthan340** [comment]
Hello @Thammus Can you please let me know which of the issue has been solved?

**Comment by Thammus** [comment]
Wiith version 4.0.4 a simple invocation of Instaloader like `instaloader "#cloudyweather2017"` should download all targeted posts including all pictures and videos inside sidecars.

Also when using Instaloader as a module the `typename` now gets correctly determined for sidecar posts:
```python
import instaloader
L = instaloader.Instaloader()
for post in L.get_hashtag_posts('cloudyweather2017'):
    print("Type of {}: {}".format(post, post.typename))
```
This code is expected to output:
```
Type of <Post Bbuhp3Th7X6>: GraphImage
Type of <Post BYkZsY2Avgz>: GraphSidecar
```
If you want to download the posts simply call [`L.download_post()`](https://instaloader.github.io/as-module.html#instaloader.Instaloader.download_post) from inside the loop while specifying the post object and a target string.

In the same manner the code of your third approach should work just fine.
