### ISSUE TITLE
Scrape post comments without being logged in?

### ISSUE THREAD

**Issue by quintu** [instaloader/instaloader#1330]
Until about a month ago, I could pull comments from public profile posts without being logged in, but now I immediately receive a 429 error. (I've tested this is a controlled setting with a residential IP address, no other calls to Instagram from the same IP, using a rate controller, etc.) I can, however, pull dozens of images without any issue, which leads me to believe that it's not actually rate-limit related, but that Instagram has blocked all comment-level data to non-logged in users.

In addition, I have no problem pulling comments when I'm logged in. 

This used to work, but now returns 429:
instaloader --comments -- -CViXWNxpzF4

This works:
instaloader --comments --login XXXXXXXXXXX -- -CViXWNxpzF4

**Has anyone observed similar behavior? Am I correct in understanding that Instagram has blocked comment-level data for non-logged-in users?**

Any input is appreciated, thank you!

**Comment by Aditya-Rajgor** [comment]
Yeah, I believe for Instagram scraping comments is quite a sensitive thing.

**Comment by 89z** [comment]
I have an alternate tool that works:

~~~
PS C:\> instagram -i CViXWNxpzF4
{Display_URL:https://scontent-hou1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/248826697_118016843992855_6873736538889054481_n.jpg?_nc_ht=scontent-hou1-1.cdninstagram.com&_nc_cat=1&_nc_ohc=oqUcXjDc_WsAX9YNVRx&edm=AABBvjUBAAAA&ccb=7-4&oh=b8d3a6aa625aba8e163ebad3ce78c216&oe=619F702B&_nc_sid=83d603&ig_cache_key=MjY5MzgxODIwODgxMDkwNTk3Ng%3D%3D.2-ccb7-4
Edge_Media_Preview_Like:{Count:4413397}
Edge_Media_To_Parent_Comment:{Edges:[{Node:{Text:Killer}} {Node:{Text:😍}}
{Node:{Text:😍}} {Node:{Text:😍}} {Node:{Text:Show off}} {Node:{Text:QUIT
SHOWING OFF WHEN THERES ALOT OF KIDS DYING FOR FOOD!!!}} {Node:{Text:😂}}
{Node:{Text:❤️}} {Node:{Text:😂}} {Node:{Text:sart}} {Node:{Text:❤️}}
{Node:{Text:See Dr ty Hi u}} {Node:{Text:❤️}} {Node:{Text:See Dr ty Hi u}}
{Node:{Text:Hyd}} {Node:{Text:What up}} {Node:{Text:😍}} {Node:{Text:First}}
{Node:{Text:O 🔥🔥🔥}} {Node:{Text:Pathetic}} {Node:{Text:Lblblb}}
{Node:{Text:I want 1 heel from there}} {Node:{Text:�😍😍}}}]}
Edge_Sidecar_To_Children:<nil> Video_URL:}
~~~
