### ISSUE TITLE
How to use 

### ISSUE THREAD

**Issue by DarkSpeedKiller** [instaloader/instaloader#1331]
Im pretty much trying to use the module to do a bunch of stuff that the module provides us. The documentation confuses me and i cant seem to make it work.
I can use the download post even tho i got some trouble making it use the path i want to be saved + fast update not working
after loading an account i managed to use download saved posts + feed posts
but cant download specific profile of my choice (stories/highlights/reels) nor hashtag posts the same way i use the download_posts
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
this also shows up and i cant bypass it 
so a youtube guide with examples of the docs would be pretty much appreciated

**Comment by Showmaster3000** [comment]
You won't have more luck if you open another issue. You didn't describe in detail in #1327. You didn't add much more details here.
The redirect to login wants you to login with a valid account to continue.

**Comment by DarkSpeedKiller** [comment]
> You won't have more luck if you open another issue. You didn't describe in detail in #1327. You didn't add much more details here. The redirect to login wants you to login with a valid account to continue.

its not about luck. Its about getting help
im literally describing what i wanna do and i cant do it
the account is valid the thing gets stack and i cant do anything at all
