### ISSUE TITLE
Ability to unfollow / remove follower

### ISSUE THREAD

**Issue by SirDankenstien** [instaloader/instaloader#1332]
**Provide us a use case of the feature**
- profile.unfollow('username')
- profile.remove_follower('username')
- It would help safely remove ghost followers and also improve engagement rate
- it would also help you safely bulk unfollow

**Describe the solution you'd like**
- once the respective command is run, it should accordingly unfollow or remove the specified username

**Describe alternatives you've considered**
- there are alternatives to this but as instaloader uses session files, it is easier to do the stated task repeatedly without having to login more than once

**If the feature request is accepted, would you be willing to submit a pull request?**
- Sadly I am not capable enough to meet the python coding requirements of this repo

**Comment by aandergr** [comment]
We have to reject this feature suggestion, Instaloader should not change any of the online data.

> Instaloader’s goal is to mimic the browser’s behavior to access the data that is available through the Instagram web interface, pack this data into complete and easily-(re)usable python objects, and provide a user interface for the most common downloading and metadata collection tasks, without changing any of the online data.

**Comment by manojsahukar** [comment]
You can use this.
https://github.com/manojsahukar/instagram_unfollower
