### ISSUE TITLE
Get stories anonymously

### ISSUE THREAD

**Issue by EzeKees** [instaloader/instaloader#1333]
Hello, first of all I greatly appreciate this application, the official Instagram API is very restrictive. I only need to download the latest latest stories, they are public stories, ideally you can download them without logging in. This is possible? I have tried this, but instaloader downloads all the stories at once, (but not the last ones), the --Story-filter option could not make it work. Any suggestion is welcome, thank you very much

**Comment by 89z** [comment]
Please provide example URL

**Comment by EzeKees** [comment]
> Please provide example URL

https://www.instagram.com/ltvnok/

**Comment by 89z** [comment]
I dont know what you mean by "stories", I dont really use Instagram that much. I have a program that can get images and video from individual posts. For example this link:

<https://www.instagram.com/p/CWIr_0MlvH->

Can get it like this:

~~~
instagram CWIr_0MlvH-
~~~

https://github.com/89z/mech

**Comment by EzeKees** [comment]
> No sé qué quieres decir con "historias", realmente no uso mucho Instagram. Tengo un programa que puede obtener imágenes y videos de publicaciones individuales. Por ejemplo este enlace:
> 
> https://www.instagram.com/p/CWIr_0MlvH-
> 
> Puede conseguirlo así:
> 
> ```
> instagram CWIr_0MlvH-
> ```
> 
> https://github.com/89z/mech

Hello, no no, the "stories" that I refer to are these https://www.instagram.com/stories/ltvnok. I wish I could download those anonymously.

**Comment by 89z** [comment]
Sorry, but I dont know what the hell that is. Is it a live stream or something? "stories" doesnt really describe what it is.

**Comment by aandergr** [comment]
`Instaloader.get_stories()` requires to be used with a logged-in instance, so accessing stories anonymously will not be possible. If `--storyitem-filter` does not fulfill your selection requirements, I recommend to write a custom script, e.g. to interrupt after the latest StoryItem is downloaded.

**Comment by EzeKees** [comment]
Thanks
