### ISSUE TITLE
What is the best rate for downloading followers/followees?

### ISSUE THREAD

**Issue by bipsen** [instaloader/instaloader#1335]
I was hoping we could discuss rate limits for downloading followers and followees from profiles. In my experience, I am able to download most structures without ever getting blocked simply be relying on the default RateController. But when downloading followers, while I don't get 429 errors, I frequently experience other problems like having to chance password, confirm in the app using their face-check, two factor auth with phone number etc.

If others are experiencing this too, I was wondering if it might be useful to think about having a separate rate control mechanism for these types of harvests. This could also include setting the `_graphql_page_length` to something other than 50. Has anyone found a rate at which they could avoid these issues and keep a continuous download stream going on the followers of many profiles? My best result so far has been in simply sleeping for two hours between every 5000 downloaded followers, and then again for two hours each time a profile completes. 

Of course, since it doesn't actually seem to be the rate limits and 429 errors that are causing the problem, but rather that Instagram seems to think my accounts are being hacked or that I am using some service to get more followers or something, are there other things one can do to avoid this, such somehow using the Instagram service more organically from that account? Or is it simply a matter of reducing the amount requests made? Thanks for the help.

**Comment by somera** [comment]
Your account will be banned more and more frequently. At some point you will have to activate it via video call.
