### ISSUE TITLE
[installation] '\xc3' in file setup.py on line 40

### ISSUE THREAD

**Issue by pigwa88** [instaloader/instaloader#1336]
Hello,
can someone help to fix problem with installation?
`C:\pyt\instaloader-4.8.1\instaloader-4.8.1>python setup.py
  File "setup.py", line 40
SyntaxError: Non-ASCII character '\xc3' in file setup.py on line 40, bu
ding declared; see http://www.python.org/peps/pep-0263.html for details`

Windows 7 & Python 3.8

**Comment by 89z** [comment]
https://github.com/instaloader/instaloader/blob/470fc0d905ae5f51867a4f0fb13ff9c0e8118bdd/setup.py#L40

**Comment by pigwa88** [comment]
Alright, I just removed "é" and jumped on to the next problem:
```
C:\pyt\instaloader-4.8.1\instaloader-4.8.1>python setup.py
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from setuptools import setup
ImportError: No module named setuptools

C:\pyt\instaloader-4.8.1\instaloader-4.8.1>
```
> https://github.com/instaloader/instaloader/blob/470fc0d905ae5f51867a4f0fb13ff9c0e8118bdd/setup.py#L6

I dont get it. I am better at PHP and I miss a folder here - what did I miss when installing Python?

**Comment by 89z** [comment]
Sorry but these are Python issues, not specific to InstaLoader. You should ask for Python help somewhere else.

**Comment by aandergr** [comment]
To me it looks like you might be running Python 2 rather than Python 3. Running `python --version` will show the Python version you are executing.

**Comment by pigwa88** [comment]
> To me it looks like you might be running Python 2 rather than Python 3. Running `python --version` will show the Python version you are executing.

BIG Thanks! I have 2.7.2 - but I installed 3.8 and the installation process was successful...
apparently I had version 2.7.2 installed before and 3.8 didn't overwrite the previous version - that's the only explanation. Thank you so much for your support!
