### ISSUE TITLE
Fatal error 400 Bad Request

### ISSUE THREAD

**Issue by ahsaassy** [instaloader/instaloader#1340]
**Describe the bug**
Fatal error: 400 Bad Request

**To Reproduce**
instaloader -l myacc --no-metadata-json --no-captions --no-video-thumbnails natgeo -F
Loaded session from /data/data/com.termux/files/home/.config/instaloader/session-myacc.
Fatal error: 400 Bad Request

**Expected behavior**
Profile starts downloading as usual

**Error messages and tracebacks**
Fatal error: 400 Bad Request

**Instaloader version**
4.8.1

**Additional context**
I wish I had more info but there's no output after the error. IL just ends.

**Comment by Showmaster3000** [comment]
This is not a bug. This error means, that your download account has been (temporary) blocked by Instagram. Check this by using the app.
See also other duplicate bugs like #942 or #828.

**Comment by NicotherZ** [comment]
Get error "400 Bad Request Unable to fetch high quality image version..." too I get 1350px image of post (not best quality so) but my account are not locked, try to login with app tablet and no problem, i can log in. So ? What's happen ? What can i do ?
