### ISSUE TITLE
Pass User IDs as commandline argument

### ISSUE THREAD

**Issue by Deleora** [instaloader/instaloader#1344]
Hi,

I was wondering if is it possible to pass userIDs (the integer) instead of usernames as command-line arguments to download profiles?
It is a pain to type the username again and again if they change it. So using userIDs would be a great thing in this scenario.

**Comment by aandergr** [comment]
> I was wondering if is it possible to pass userIDs (the integer) instead of usernames as command-line arguments to download profiles?

No, and I do not see any use case for that.

> It is a pain to type the username again and again if they change it. So using userIDs would be a great thing in this scenario.

I always recommend to invoke
```sh
instaloader [options] `ls -d */`
```

**Comment by Deleora** [comment]
> ```shell
> instaloader [options] `ls -d */`
> ```

What exactly is the purpose of `ls -d */` in here?

**Comment by aandergr** [comment]
On bash it seems equivalent to calling `instaloader [options] */`. So actually calling `ls -d` might be unnecessary.
