### ISSUE TITLE
Unhandled KeyError in Post.location when Instagram returns broken location data

### ISSUE THREAD

**Issue by hitboxr** [instaloader/instaloader#1349]
**Describe the bug**
I found a post that has a location tagged, but when the location is accessed, Instagram does not return the expected /explore/location/\<id\> page. Instaloader expects there will always be valid location data and directly accesses fields in the location metadata response, leading to KeyErrors.

The post: https://www.instagram.com/p/CVX6Q3EAlG_/
The expected location page: https://www.instagram.com/explore/locations/257207787/st-augustine-florida/

 For whatever reason, Instagram doesn't return expected fields like `lat` or `lng`, raising unhandled KeyErrors when Instaloader tries to build the `PostLocation` namedtuple. Here's the post's `loc` field after the location metadata request:
```
{"id": 257207787, 
 "has_public_page": True, 
 "name": "St. Augustine, Florida", 
 "slug": "st-augustine-florida", 
 "address_json": {
    "street_address": "", 
    "zip_code": " 32084", 
    "city_name": "", 
    "region_name": "", 
    "country_code": "", 
    "exact_city_match": false, 
    "exact_region_match": false, 
    "exact_country_match": false
    }
}
```

**To Reproduce**
```
post = Post.from_shortcode(L.context, 'CVX6Q3EAlG_')
print(post.location)
```

**Expected behavior**
Either `Post.location` should return None as no valid location could be found, or return a namedtuple with whatever location data can be gleaned from Instagram's malformed response and None for remaining fields.

**Error messages and tracebacks**
```
Traceback (most recent call last):
  File "<truncated>/scrape.py", line 124, in <module>
    if post.location is not None:
  File "<truncated>\venv\lib\site-packages\instaloader\structures.py", line 633, in location
    loc['lat'], loc['lng'])
KeyError: 'lat'

```

**Instaloader version**
4.9b1, although I'd be surprised if the same behavior is not present on the latest full release

**Comment by aandergr** [comment]
Thanks for reporting! This is fixed in [Version 4.8.2](https://github.com/instaloader/instaloader/releases/tag/v4.8.2).
