### ISSUE TITLE
View the actual characters instead of \u code

### ISSUE THREAD

**Issue by Deleora** [instaloader/instaloader#1351]
Hi,

I wanted to know if it is possible to view the characters in _full_name_,  _biography_, etc., in the JSON files downloaded by Instaloader, as they are displayed on the Instagram clients? If so, how? Currently the JSON has \u codes (which I feel are Unicode equivalents)

For example, below is the text from JSON of a profile
```
"biography": "\ud835\ude8a\ud835\ude95\ud835\ude95 \ud835\udea0\ud835\ude8e \ud835\ude91\ud835\ude8a\ud835\ude9f\ud835\ude8e \ud835\ude92\ud835\ude9c \ud835\ude97\ud835\ude98\ud835\udea0\n[omitted] \ud83d\udccd",
.
.
.
"full_name": "[omitted] \ud83d\ude0d\ud83d\udcab",
```

and below is how it is displayed on Instagram web
![image](https://user-images.githubusercontent.com/60055475/143985378-969cda0a-c518-4e11-899a-abad921b7171.png)

**Comment by Thammus** [comment]
If it is supported by your terminal and you have the necessary fonts installed, this is an example of how to print the characters using python:
```python3
bio = "\ud835\ude8a\ud835\ude95\ud835\ude95 \ud835\udea0\ud835\ude8e \ud835\ude91\ud835\ude8a\ud835\ude9f\ud835\ude8e \ud835\ude92\ud835\ude9c \ud835\ude97\ud835\ude98\ud835\udea0\n[omitted] \ud83d\udccd"
full_name = "[omitted] \ud83d\ude0d\ud83d\udcab"

print(bio.encode('utf-16-be', 'surrogatepass').decode('utf-16-be'))
print()
print(full_name.encode('utf-16-be', 'surrogatepass').decode('utf-16-be'))
```
prints
```
𝚊𝚕𝚕 𝚠𝚎 𝚑𝚊𝚟𝚎 𝚒𝚜 𝚗𝚘𝚠
[omitted] 📍

[omitted] 😍💫
```
