### ISSUE TITLE
Windows can't have ":" in directory or file names

### ISSUE THREAD

**Issue by misilot** [instaloader/instaloader#1352]
https://github.com/instaloader/instaloader/blob/6343e9a69d3e5214963fd2a1878595904d643782/instaloader/instaloader.py#L1214

I got an error that Dropbox couldn't sync my folder to my windows PC, and it is because of the directory name ":tagged". Windows doesn't allow ":" and a few other characters in directory or filenames.

Thanks!

**Comment by Showmaster3000** [comment]
Please see issue #526 where the problem is described.
