### ISSUE TITLE
Is it possible to download only reels?

### ISSUE THREAD

**Issue by ahsaassy** [instaloader/instaloader#1356]
Is there a way to ignore everything else and just download what's on the reels tab? As you can see below, instaloader goes through all posts one by one. There's only about 20 reels but over 900 posts, so I'd like to know if I could just grab them directly.

My command: 
>instaloader -l myacc --no-metadata-json --no-captions --no-video-thumbnails --no-pictures target

```
Loaded session from 
/data/data/com.termux/files/home/.config/instaloader/session-myacc.
Logged in as myacc.
Stored ID xxxxxxxxx for profile target.
[1/1] Downloading profile target
target/2021-09-04_08-59-58_UTC_profile_pic.jpg
Retrieving posts from profile target.
[   1/1565]
[   2/1565] target/2021-12-04_16-26-11_UTC.mp4
[   3/1565]
[   4/1565] target/2021-12-02_13-09-51_UTC.mp4
[   5/1565] target/2021-12-02_08-54-33_UTC.mp4
[   6/1565]
[   7/1565]
[   8/1565]
[   9/1565]
[  10/1565] ^C
Saved resume information to target/iterator_3D84.json.xz.
```

**Comment by Thammus** [comment]
In #812 a similar feature was suggested and discussed. However, unfortunately this has not yet been implemented although some ideas have been outlined.
