### ISSUE TITLE
What is the method of downloading and pausing?

### ISSUE THREAD

**Issue by james16000** [instaloader/instaloader#1358]
my friends
I am new to use
Python and installer
What is the method of downloading and pausing?
Example I want to download for limits
199
And it stopped for two minutes, how do I do that?
I hope you can explain to me in a detailed way what files need to be modified
Use this version Instaloader      v4.8.2 
I'm sorry my English is poor
thank you all

**Comment by SpL1Ne** [comment]
If you are familiar with powershell, I could share my PS script for pausing.

**Comment by james16000** [comment]
Welcome brother
I don't know how to use PowerShell
But can you explain how to use it on PowerShell

**Comment by james16000** [comment]
> If you are familiar with powershell, I could share my PS script for pausing.

Welcome brother
I don't know how to use PowerShell
But can you explain how to use it on PowerShell

**Comment by james16000** [comment]
Didn't solve my problem
Thank you all
