### ISSUE TITLE
Where is the binary on linux?

### ISSUE THREAD

**Issue by aseques** [instaloader/instaloader#136]
I used instaloader in windows, and mostly I am using the executable. When I installed instaloader in linux (pip3 install instaloader) i don't find any executable.
Am I missing something?

**Comment by aandergr** [comment]
`pip3 install --user instaloader` seems to put the script into `~/.local/bin/instaloader`, without the `--user` flag it should go into `/usr/local/bin/instaloader`.

Depending on your distribution, you might have to add `~/.local/bin` or `/usr/local/bin` to your `PATH` environment variable. I think, beginning with version 10 of pip, it prints a warning if this is the case.

**Comment by aseques** [comment]
Thanks @aandergr for your reply, yesterday I rebooted the rpi where I was installing instaloader and repeated the installation with the -v flag, all went as you told, being the binary in /usr/local/bin/ when installing with sudo.
I don't know why it failed on first time (I event used find to find the script and it wasn't anywhere).
Thanks a lot
