### ISSUE TITLE
Downloading :saved ended unexpectedly.

### ISSUE THREAD

**Issue by andy91129** [instaloader/instaloader#1360]
Your question here...

```
% instaloader --login=andy91129 --dirname-pattern=/Users/yao-antsai/Applications/Box\ Sync/Instaloader/{profile} --filename-pattern={profile}_{date_utc:%Y-%m-%d_%H-%M-%S} --no-captions --no-metadata-json --resume-prefix resume :saved
...
...
...
[27663/32115] /Users/yao-antsai/Applications/Box Sync/Instaloader/0907sonia/xxxxxxxxx_2016-09-29_00-55-29.jpg exists 
Iteration complete, deleted resume information file /Users/yao-antsai/Applications/Box Sync/Instaloader/:saved/resume_uPLl6Txc.json.xz.
Saved session to /Users/yao-antsai/.config/instaloader/session-andy91129.
```

I used instaloader to download all of my saved posts.

However, it ended in the middle of downloading at 2XXXXX posts.

I already tried to update to the lastest version and tried to download the saved posts from the beginning twice.

Is there anyway to solve this problem?

Thx.

**Comment by andy91129** [comment]
Did anyone encounter similar issues?

**Comment by ImjuzCY** [comment]
Did you count the posts that you can actually see in your saved posts? Instagram says that I have around 1300 saved posts, but I can only see around 1100, so only 1100 get downloaded. I guess around 200 posts have been deleted/archived/private accounts that you now don't have access to/blocked accounts, but Instagram still counts those in the total number of saved posts, but if you don't have permission to the posts, they won't get downloaded. That's just my guess tho

**Comment by dajotim937** [comment]
I have similar problem.
This is my output.
```
Loaded session from D:\*****.
Logged in as :\*****..
Retrieving saved posts...
Saved session to D:\*****.
```
When I open Saved from instagram app there is a lot of posts.
