### ISSUE TITLE
Create Custom JSON file

### ISSUE THREAD

**Issue by bmhlongo0228** [instaloader/instaloader#1361]
How do I customize an instaloader JSON file in python code? 
I do not use the command line to get the instaloader content.

I would like all the post information in one JSON file. 
All the photos, videos, and accompanying captions.

If this has already been answered before, I would greatly appreciate being directed to that solution.

Thank you

**Comment by bmhlongo0228** [comment]
I did something else to achieve what I was trying to

**Comment by rsa408** [comment]
> I did something else to achieve what I was trying to

hi,
I try to get Instagram standard JSON format in the output of requests. but context format really needs to structure in any key and value. could you please share your way?

Thanks
the best way I could get is using `.__dict__` but it also needs to reformat for each element.

```
profile = instaloader.Profile.from_username(L.context, 'XXXXXX')
data = profile.get_posts()
file = open(username+".json", 'w', encoding='utf-8')
for d in data:
	file.write(str(d.__dict__))
	file.close

```
above code in text format can be saved in the file but for JSON format it represents an error.
Thanks.
