### ISSUE TITLE
Disable retries after x seconds functionality

### ISSUE THREAD

**Issue by ezzcodeezzlife** [instaloader/instaloader#1363]
After some requests I encounter this Exception:
`The request will be retried in 666 seconds, at XX:XX`

I've seen this kinda has been coverd in the documentation [with the RateController](https://instaloader.github.io/module/instaloadercontext.html#ratecontroller), but its not really helping, because i can only set the length of the sleep and not fully diasable it. 

A example code for a custom rate controller would be much appreciated

**Comment by Showmaster3000** [comment]
you can cancel the download/process using the additional parameter `--abort-on=429`.

**Comment by ezzcodeezzlife** [comment]
@Showmaster3000 im currently not using the cli. instead i have a script that runs once a day. 
so how could i do that within a script?

**Comment by Showmaster3000** [comment]
You didn't write about that, cause your report does not meet the issue template.
In your case the parameter `fatal_status_codes` of the class Instaloader will be your friend.
