### ISSUE TITLE
set_last_post_timestamp doesn't set tzinfo

### ISSUE THREAD

**Issue by LucEast** [instaloader/instaloader#1369]
**Describe the bug**
`LatestStamps(STAMPS_FILENAME).get_last_post_timestamp(PROFILE)` expects tzinfo but
`LatestStamps(STAMPS_FILENAME).set_last_post_timestamp(PROFILE, post.date)` doesn't set tzinfo.
Therefore if one sets the last timestamp and then tries to get the last timestamp always gets `1970-01-01 00:00:00+00:00` as the last timestamp.

**To Reproduce**
```
for post in profile.get_posts():
        last_stamp = LatestStamps(STAMPS_FILENAME).get_last_post_timestamp(PROFILE)
        post_created = post.date
        print("Last time user posted: ", post_created)
        print("Last post-timestamp in stampsfile: ", last_stamp)
        LatestStamps(STAMPS_FILENAME).set_last_post_timestamp(PROFILE, post.date)
```
**Expected behavior**
Get/set expected post-timestamp.

**Instaloader version**
`instaloader --version` output.
4.8.2

**Comment by LucEast** [comment]
# Quick explanation and hotfix
## Explanation of why this problem occurs
The metadata of `post` contains "just" `datetime.datetime(yyyy, mm, dd, hh, mm, ss)` 
or in other words, the iso-format is `%Y-%m-%dT%H:%M:%S`
The method `set_last_post_timestamp` uses however the iso-format `'%Y-%m-%dT%H:%M:%S.%f%z'`.

## Hotfix
In the `LatestStamps` class change the line `ISO_FORMAT = '%Y-%m-%dT%H:%M:%S.%f%z'` to `ISO_FORMAT = '%Y-%m-%dT%H:%M:%S'`.

---

### This should be updated or is this just a problem on my client-side?

**Comment by ekalin** [comment]
`LatestStamps` uses the timezone information for proper comparison of timestamps, so it should not be changed. (It would also break compatibility with files generated by a previous version if it was changed.)

When `set_last_post_timestamp` (around line 1346 of `instaloader.py`) is called, the date returned from `post.date_local` is converted to a date containing timezone. (There has been a recent change to make `post.date_local` include the timezone, so that code needs to be checked, and maybe simplified. :thinking:)

For the record, `LatestStamps` was designed as an internal class, not really a public API class. If it works for your needs, that's great, but keep that in mind.

**Comment by LucEast** [comment]
> When `set_last_post_timestamp` (around line 1346 of `instaloader.py`) is called, the date returned from `post.date_local` is converted to a date containing timezone. (There has been a recent change to make `post.date_local` include the timezone, so that code needs to be checked, and maybe simplified. 🤔)

That's good to know. Btw it is line 1436. ;)
So basically `LatestStamps(STAMPS_FILENAME).set_last_post_timestamp(PROFILE, post.date_local.astimezone())` should work?

**Comment by ekalin** [comment]
As of 21365ec (already on master, but not on the latest released version), `date_local` already returns a timezone-aware object, so you don't even need that.

But for the latest release, that should work.

**Comment by LucEast** [comment]
My problem was that in the following code `post.date_local` doesn't contain timezone information.
For example it always printed: `date: 2021-12-27 19:36:58 / 2021-12-27 19:36:58+01:00`.
when I changed `post.date_local` to `post.date_local.astimezone()` it works flawlessly 
and print: `date: 2021-12-27 19:36:58+01:00 / 2021-12-27 19:36:58+01:00`

```
for post in profile.get_posts():
        last_stamp = LatestStamps(
            STAMPS_FILENAME).get_last_post_timestamp(PROFILE)
        post_created = post.date_local
        print(
            "Checking remote / local posts\ndate: {} / {}".format(post_created, last_stamp))
```
## Thx for your help @ekalin <3
