### ISSUE TITLE
Resume information not saved on `LoginRequiredException`

### ISSUE THREAD

**Issue by devydd** [instaloader/instaloader#1376]
When an anonymous user is being redirected to the login page (because of too many queries), a `LoginRequiredException` is raised. But it is not handled in `nodeiterator` and no resume information is saved. Thus the user is unable to resume downloading.

Suggested change:
```python
except (KeyboardInterrupt, AbortDownloadException, LoginRequiredException):
```
in https://github.com/instaloader/instaloader/blob/d6e5e310054aa42d3fd8d881389f04d1b4cdbe72/instaloader/nodeiterator.py#L284

**Comment by aandergr** [comment]
This can already be achieved with `--abort-on=302`.

**Comment by devydd** [comment]
Yes, but that's a quite common case given the current IG limits. I suggest adding it to the default settings.
