### ISSUE TITLE
+args.txt does not work

### ISSUE THREAD

**Issue by james16000** [instaloader/instaloader#1377]
Hi
I tried this file on cmd and it doesn't work +args.txt
`instaloader +args.txt`
Windows 7 operating system
pip 21.3.1
Python 3.7.6
instaloader 4.8.3
It shows me an error This is the error text

C:\Users\pc>instaloader +args.txt
usage:
instaloader [--comments] [--geotags]
            [--stories] [--highlights] [--tagged] [--igtv]
            [--login YOUR-USERNAME] [--fast-update]
            profile | "#hashtag" | %location_id | :stories | :feed | :saved
instaloader --help
instaloader: error: [Errno 2] No such file or directory: 'args.txt'

C:\Users\pc>

================================================================

This is the content of the file
--login=xxxx
--password=xxxx
--no-compress-json
--no-metadata-json
--no-captions
--no-video-thumbnails
instagram

================================================================

and screenshot What is the solution
![123456](https://user-images.githubusercontent.com/93964724/148665382-40993f6f-1ff3-493b-b508-24e8bd25c023.JPG)

**Comment by Squidu** [comment]
Ensure your "args.txt" file is within the containing folder for instaloader. Like this ->
![Directory](https://user-images.githubusercontent.com/97421233/148715150-6f786ed6-85ce-4c0f-8568-725c032e1300.png)
I get the same error when I move my "args1.txt" file up one folder level.

**Comment by james16000** [comment]
> Ensure your "args.txt" file is within the containing folder for instaloader. Like this -> ![Directory](https://user-images.githubusercontent.com/97421233/148715150-6f786ed6-85ce-4c0f-8568-725c032e1300.png) I get the same error when I move my "args1.txt" file up one folder level.

Hello Dear
I put 
args1.txt 
in instaloader folder
didn't work
This is the text that appeared to me
================================================================
JSON Query to args1.txt/feed/: 404 Not Found [retrying; skip with ^C]
JSON Query to args1.txt/feed/: 404 Not Found [retrying; skip with ^C]
args1.txt: Profile args1.txt does not exist.
The most similar profiles are: txt_arg_14, txt_argentina_19, txt.bts_1, txt_twic
e12345, bts_txt_15.

Errors or warnings occurred:
args1.txt: Profile args1.txt does not exist.
The most similar profiles are: txt_arg_14, txt_argentina_19, txt.bts_1, txt_twic
e12345, bts_txt_15.
================================================================
![12323423](https://user-images.githubusercontent.com/93964724/148893669-0a9d3f3b-3b8e-4cbe-9a14-6585bc4cec0e.JPG)

**Comment by james16000** [comment]
> Ensure your "args.txt" file is within the containing folder for instaloader. Like this -> ![Directory](https://user-images.githubusercontent.com/97421233/148715150-6f786ed6-85ce-4c0f-8568-725c032e1300.png) I get the same error when I move my "args1.txt" file up one folder level.

Hello Dear
I put 
args1.txt 
in instaloader folder
didn't work
This is the text that appeared to me


================================================================



JSON Query to args1.txt/feed/: 404 Not Found [retrying; skip with ^C]
JSON Query to args1.txt/feed/: 404 Not Found [retrying; skip with ^C]
args1.txt: Profile args1.txt does not exist.
The most similar profiles are: txt_arg_14, txt_argentina_19, txt.bts_1, txt_twic
e12345, bts_txt_15.

Errors or warnings occurred:
args1.txt: Profile args1.txt does not exist.
The most similar profiles are: txt_arg_14, txt_argentina_19, txt.bts_1, txt_twic
e12345, bts_txt_15.


================================================================

![12323423](https://user-images.githubusercontent.com/93964724/148893669-0a9d3f3b-3b8e-4cbe-9a14-6585bc4cec0e.JPG)

**Comment by Squidu** [comment]
By that error it looks like instaloader is using args.txt as an actual instagram user, so don't forget to put a "+" before args1.txt or whatever the name of your .txt file is. It should read, "instaloader +args1.txt" when you run it.

**Comment by james16000** [comment]
> By that error it looks like instaloader is using args.txt as an actual instagram user, so don't forget to put a "+" before args1.txt or whatever the name of your .txt file is. It should read, "instaloader +args1.txt" when you run it.

Hello
I've put
The "+" sign next to it
It did not solve the problem


![457457856856](https://user-images.githubusercontent.com/93964724/149269907-30e34e77-8b3f-41de-b256-ef5fadddbb8c.JPG)

Look

Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", lin
e 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", lin
e 85, in _run_code
    exec(code, run_globals)
  File "instaloader\__main__.py", line 11, in <module>
    from . import (AbortDownloadException, BadCredentialsException, Instaloader,
 InstaloaderException,
ImportError: attempted relative import with no known parent package

**Comment by james16000** [comment]
Didn't solve my problem
Thank you all
