### ISSUE TITLE
post-filter datetime - Filter evaluation failed

### ISSUE THREAD

**Issue by kygger** [instaloader/instaloader#1379]
----------------------------------------------------------------------------------------------------------------------------------

**Describe the bug**

windows console execution file(instaloader.exe) arguments
--post-filter="date_utc < datetime(2022,1,14)"

Filter evaluation failed: can't compare offset-naive and offset-aware datetimes

it's not possible to compare datetime
but version 4.8.2 is possible.

----------------------------------------------------------------------------------------------------------------------------------

**To Reproduce**

instaloader.exe romi.fit --dirname-pattern "folder" --fast-update -l "id"
-f "x:\xxx\session-id" --post-filter="date_utc < datetime(2022,1,14)" --no-video-thumbnails --no-captions --no-metadata-json --no-compress-json --filename-pattern "{date_utc} {owner_username} {shortcode}"

Only download posts with property "date_utc < datetime(2022,1,14)".
Loaded session from x:\xxx\session-id.
Logged in as udjoa10.
Stored ID 1078396896 for profile romi.fit.
[1/1] Downloading profile romi.fit
romi.fit 피트 신새롬 275\romi.fit_2022-01-06_09-30-40_UTC_profile_pic.jpg
Retrieving posts from profile romi.fit.
[  1/354] <Post CYu27w2P3GP> skipped. Filter evaluation failed: can't compare offset-naive and offset-aware datetimes
[  2/354] <Post CYsMWiGvgq6> skipped. Filter evaluation failed: can't compare offset-naive and offset-aware datetimes

----------------------------------------------------------------------------------------------------------------------------------

**Expected behavior**

I dont't get it.

----------------------------------------------------------------------------------------------------------------------------------

**Error messages and tracebacks**

no trackbacks

----------------------------------------------------------------------------------------------------------------------------------

**Instaloader version**
4.8.3

----------------------------------------------------------------------------------------------------------------------------------

**Comment by aandergr** [comment]
Thanks for reporting! This is fixed in version 4.8.2.
