### ISSUE TITLE
Failed to establish a new connection: [Errno 11004] getaddrinfo failed'

### ISSUE THREAD

**Issue by RubyFan120** [instaloader/instaloader#138]
Hi,
I have tried downloading profiles, but I always get this:

JSON Query to rrruby120/: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /rrruby120/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000214B3624048>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

Could anyone give me some suggestions? I really appreciate that.

**Comment by aandergr** [comment]
Might be similar to #91 or #107. Is there a DNS blocking in your country, or a firewall or ad blocker installed on your network?

**Comment by aandergr** [comment]
I am closing this since it seems like a problem on behalf of your network, which we cannot fix. If it still cannot be solved, please reopen this issue and provide us more information.

**Comment by aandergr** [comment]
I see that this issue ultimately receives high traffic. If someone, where access to Instagram is not restricted via firewalls or law regulations, gets this error and can provide us new information, could she please open a new issue or comment here?

**Comment by mark545154** [comment]
У меня тоже такая проблема возникла. Жаль что нет решения(
