### ISSUE TITLE
Downgrade quality in story images

### ISSUE THREAD

**Issue by buttermybun** [instaloader/instaloader#1381]
**Describe the bug**
Story images quality from various profiles has downgraded to 1080x1920 pixels and less, even some of them were changed into 640x1138 pixels.

**To Reproduce**
instaloader --login (username) profile1 profile2 profile3 --stories --no-posts --no-metadata-json 

**Expected behavior**
Download a maximum quality (if possible) of story images.

**Error messages and tracebacks**
None.

**Instaloader version**
Ver. 4.8.4

**Additional context**
Prior to this I'm still using ver. 4.7.1 until I noticed the change in image quality a few days ago, then it keep persistent even after upgrading to the latest version. I'm not sure whether the issue comes directly from Instagram server or not, but I believe it's worth to mention.

**Comment by remlap** [comment]
I am seeing this in other methods to get Instagram stories so it is not just Instaloader.

**Comment by buttermybun** [comment]
I see. I noticed that today it's starting to change back into bigger quality again. Thanks for the input!
