### ISSUE TITLE
Can I use --latest-stamps or --fast-update while not missing restored archived posts?

### ISSUE THREAD

**Issue by RgHVcN2bvs9xbP4z** [instaloader/instaloader#1385]
This is kind of a Question/Feature Request depending on the answers given.

Some accounts archive and restore posts on a regular basis. Are these restored posts caught if using the --latest-stamps or --fast-update? I couldn't find anything in the documentation material. 

If I am not running those filters does Instaloader just re-download and overwrite the files I have already acquired? I couldn't find any information on that either. Assuming It's the case it would be using up the Instagram request limit unnecessarily.

Is there maybe a way to differentiate restored archive posts from normal posts?

**Comment by ImjuzCY** [comment]
I'm looking for an answer to this too

**Comment by ImjuzCY** [comment]
From my quick tests, it seems that restored posts do not get downloaded with `--latest-stamps` or `--fast-update`.

However, if you do not use either of the tags, the existing media files do not get redownloaded, however the json.tz metadata file does get updated every run. You can use `--no-metadata-json` to prevent this, but it will still open the post's page (https://www.instagram.com/p/{shortcode}/), so from Instagram's side the metadata of each post are still loaded individually, but the media files are not accessed. 

I hope I explained it clearly. This is from my short tests tho, and I did not study the source code closely to be sure that is what it does.

**Comment by RgHVcN2bvs9xbP4z** [comment]
Thanks for checking. With Instagram being so stringent in their efforts to prevent automation I was worried about extra commands that would add up towards my total actions. Seems like it would do that.

TBH I've kind of given up using instaloader because of how zealous instagrams become; it's gotten to technical and impractical for me. Ideally there would be some basic interface that I could just throw a bunch of logins and account IDs into; tick a few boxes and let it go. I don't expect the devs to do that; they already do a lot.

**Comment by ImjuzCY** [comment]
I made a mistake. Instaloader does not load posts if it has been downloaded. It checks if the file is downloaded first before loading the post.

Check #1562 and [the code](https://github.com/instaloader/instaloader/blob/5a240640126e556ba70c8132ed5e5be5b9ef4ac5/instaloader/instaloader.py#L343)
