### ISSUE TITLE
python istaloader proxies problem

### ISSUE THREAD

**Issue by xx0bb** [instaloader/instaloader#1386]
hello guys i use proxy , with my humble windows 11 , i can login and getting session id . 

I USE python and here is the code :

from requests.auth import HTTPProxyAuth
import os
import requests
import getpass
import json
import io
import time
import sys
from datetime import datetime

proxies = {"http": "209.127.191.180:9279"}
auth = HTTPProxyAuth("zscsubsh", "e18k5037lmd2")

username = 'xxx'
password = 'xxx'

link = 'https://instagram.com/accounts/login/'
login_url = 'https://instagram.com/accounts/login/ajax/'

user_agent = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)\ Chrome/59.0.3071.115 Safari/537.36'

session = requests.Session()
session.headers = {'user-agent': user_agent}
session.headers.update({'Referer': link})

time = int(datetime.now().timestamp())
response = session.get(link, proxies=proxies, auth=auth)
print(session.cookies)
print(response.status_code)
csrf = response.cookies['csrftoken']

payload = {
    'username': username,
    'enc_password': f'#PWD_INSTAGRAM_BROWSER:0:{time}:{password}',
    'queryParams': {},
    'optIntoOneTap': 'false'
}

login_header = {
    "User-Agent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36",
    "X-Requested-With": "XMLHttpRequest",
    "Referer": "https://www.instagram.com/accounts/login/",
    "x-csrftoken": csrf
}

login_response = requests.post(login_url, data=payload, headers=login_header)
json_data = json.loads(login_response.text)

if json_data["authenticated"]:

    print("login successful")
    cookies = login_response.cookies
    cookie_jar = cookies.get_dict()
    csrf_token = cookie_jar['csrftoken']
    print("csrf_token: ", csrf_token)
    session_id = cookie_jar['sessionid']
    print("session_id: ", session_id)
else:
    print("login failed ", login_response.text)
`

when i try to use the same code with same proxy on my ubuntu server . 
i get 429 Instagram responded with **HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence.**

is there any helpful answer ? 
i simply want session id only.

**Comment by johngao01** [comment]
thats mean when you use this program,dont login same account that already login in pc or phone.
