### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by AmirAflak** [instaloader/instaloader#1387]
Hi,
Are there any ways to ignore comments replies ? 
I wanna fetch just pure comments without replies.

**Comment by rsa408** [comment]
@AmirAflak may I know how do you get the comments? plz. I need to retrieve all the comments even reply.
could you please share your code with us?

**Comment by AmirAflak** [comment]
> @AmirAflak may I know how do you get the comments? plz. I need to retrieve all the comments even reply. could you please share your code with us?
                                from instaloader import Post
                                from instaloader import Instaloader
                                L = Instaloader()
                                L.login(user_name, password)
                                post = Post.from_shortcode(L.context, post_code)
                                # get comments with all details :
                                comments = post.get_comments()
                                # get just comment's text : 
                                comments_text = [comment.text for comment in comments]

**Comment by rsa408** [comment]
> > @AmirAflak may I know how do you get the comments? plz. I need to retrieve all the comments even reply. could you please share your code with us?
> 
> ```
>                             from instaloader import Post
>                             from instaloader import Instaloader
>                             L = Instaloader()
>                             L.login(user_name, password)
>                             post = Post.from_shortcode(L.context, post_code)
>                             # get comments with all details :
>                             comments = post.get_comments()
>                             # get just comment's text : 
>                             comments_text = [comment.text for comment in comments]
> ```

Dear @AmirAflak  thanks for sharing your code. I've tested, this is exactly retrieving the first layer comments regardless of they have or get a reply or not.

For analyzing feedback of a post: 
Many of the information is on the reactions in comments (likes, replies)
=> who liked, 
=> who replied

your code returns the like count but not who liked who replied.
`likes_count=1,  answers=<generator object Post.get_comments.<locals>._postcommentanswers at 0x00000000045D3970>)`

This is what I exactly looking 
I would like to know, is it possible for you to share your Idea or may possibly help?
Regards.
Reza
