### ISSUE TITLE
Is it possible to minimize the used request to download posts by providing an index of the last downloaded post?

### ISSUE THREAD

**Issue by Snickbrack** [instaloader/instaloader#1388]
My Idea is:

1. I am downlaoding posts from a profile but this profile has too many posts for the Rate Limits of Instagram.
2. Instaloader returns an index of the currently loaded posts
3. If I let the Instagram Limits settle I can restart Instaloader and provide the Index from before so I dont need to waste requests for the other already downloaded posts.

Is this possible to realize?

**Comment by Showmaster3000** [comment]
Is it something like the resume iterator which is already available?
Have a look at the manual:
https://instaloader.github.io/module/nodeiterator.html and
https://instaloader.github.io/cli-options.html#cmdoption-resume-prefix
