### ISSUE TITLE
JSON files with iphone_struct

### ISSUE THREAD

**Issue by jpramirez87** [instaloader/instaloader#1392]
I'm using Instaloader to download and parse JSON files, however I'm getting different file structures:

Normal JSON file = No 'iphone_struct' node.
Iphone JSON file = 'iphone_struct' node.

1) instaloader.Hashtag.from_name(L.context, hashtag).get_top_posts() + sessionfile = Iphone JSON files
2) instaloader.Hashtag.from_name(L.context, hashtag).get_top_posts() + No sessionfile = "Normal" JSON files
3) instaloader.Profile.from_username(L.context, username).get_posts() + sessionfile = "Normal" JSON files

I fixed my code changing:
`tagged_users = [edge['node']['user']['username'].lower() for edge in data['node']['edge_media_to_tagged_user']['edges']]`
to:
`tagged_users = [i['user']['username'].lower() for i in data['node']['iphone_struct']['usertags']['in']]`

**But my question is: Is there a way to get only NORMAL JSON files?**

**Comment by rsa408** [comment]
Did you find a way to get requested queries in json formst?
I try to get comments and reply in json format but I can't.
