### ISSUE TITLE
Specify download folder?

### ISSUE THREAD

**Issue by masterofobzene** [instaloader/instaloader#1394]
Many options, complex ones....  but no option to set the downloads folder?

**Comment by dajotim937** [comment]
There is option to set downloads folder: [link](https://instaloader.github.io/cli-options.html#cmdoption-dirname-pattern)

**Comment by masterofobzene** [comment]
OK it sounded like it was only the folder name created as part of the process, not the whole path.
I solved this by setting the "start in" properties menu on windows, to my desired download location.
