### ISSUE TITLE
Problem with specifying file names

### ISSUE THREAD

**Issue by KoalaPancake** [instaloader/instaloader#1397]
Hey guys, I'm trying to download my saved posts but i'm having some trouble. I'm using the windows exe 4.8.4 version.

I'm trying to download my saved posts and I want the filenames to be: profile name_year-month-day

This is the command i'm trying to use:
`.\instaloader --login=myname --filename-pattern={profile}_{date_utc:%y-%m-%d} :saved`

But I get this error:
```
instaloader.exe : The command parameter was already specified.
At line:1 char:1
+ .\instaloader --login=myname --filename-pattern={profile}_{da ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParameterBindingException
    + FullyQualifiedErrorId : ParameterSpecifiedAlready
```

Unfortunately I don't know what that means or how to fix it.

I tried to see if the profile name was the problem and to only get the date in the filename with this command:

`.\instaloader  --login=myname  --filename-pattern={date_utc:%y-%m-%d} :saved`

But then I get this error:

`error: unrecognized arguments: -encodedCommand -inputFormat xml -outputFormat text`

Am I doing something wrong or is it not possible to have profile name and then the date as the filenames?

Thank you for your help!

**Comment by fireattack** [comment]
Try to quote your arguments

```
.\instaloader --login="myname" --filename-pattern="{profile}_{date_utc:%y-%m-%d}" ":saved"
```

**Comment by KoalaPancake** [comment]
That worked! Thank you so much!
