### ISSUE TITLE
Password with special characters result in "wrong password" error

### ISSUE THREAD

**Issue by DubHacker-chan** [instaloader/instaloader#1399]
**Describe the bug**
Cannot login with my secure 64 character password with special characters but without special characters its possible.

Example password:
VrrsBr+1&n~Jt"]QMl^#G5!X'"n*'D&;DLMPa|*cR&P^tT<>X9aP/,=l`OG0NE]-

**To Reproduce**
Windows:
Run ".\instaloader.exe --login your-username"

**Expected behavior**
Can input correct password and login succeeds

**Error messages and tracebacks**
Get error "Login error: Wrong password."

**Instaloader version**
4.8.4

**Comment by dajotim937** [comment]
Does your password contains a `:` symbol?

**Comment by DubHacker-chan** [comment]
Yes

**Comment by aandergr** [comment]
Duplicate of #1292.
