### ISSUE TITLE
Algorithm breaks fast-update

### ISSUE THREAD

**Issue by e5150** [instaloader/instaloader#140]
Due to the new-ish algorithm (that I've been assigned at least), that seemingly randomizes that posts from the last day or so, downloading the feed with `--fast-update` will prematurely break the download loop. On the web site I get post from (17h, 16h, 20h, 13h, 13h, 5h, 15h, 13h, 14h, 20h, 50min, 3h, 8h, 17h) ago, with the 11th post being the newest.
Skipping `--fast-update` and setting a `--count` kind of solves the issue. But I'm thinking that `--fast-update` could optionally take an integer argument, so that `instaloader --fast-update=15 :feed` would continue until 15 already downloaded posts have been encountered.
(Optimally any non-downloaded from the current "page" would be downloaded, but that seems more difficult to implement into the current code, since `get_feed_posts()` yields the `Post` objects that are considered for downloading. So I would suggest simply changing `fast_update` from `bool` to `int`.)

**Comment by e5150** [comment]
Otherwise it could be alleviated by something like `yield from sorted(posts, key=lambda p: p.date)` (or, should that be `-p.date.timestamp()` to be reverse chronological order?) so that at least each scrolled page is sorted newest to oldest.

**Comment by aandergr** [comment]
I installed a cron job that regularly goes through my `:feed` and records the order in which posts are returned. It shows that, even if the posts are not ordered by their date, they seem to be always returned in the same order. I conclude that the feed post order is seldomly changed, and hence `--fast-update :feed` should work. In that experiment period, I did and didn't use the app between invocations, and I added new followees, so I expect the result to be representative.

Profile post iterators return posts ordered by date. `:saved` sorts by when the post was saved, which is the perfect order regarding `--fast-update`.

So according to my observations we do not need to change anything regarding `--fast-update`.

We cannot `sorted()` the feed iterator, it would go through all the infinite posts until it starts yielding elements.

**Comment by e5150** [comment]
Yes, it was probably just the first day or so, before the sorting alogirthm had propagated to all servers (or however they push these changes onto users), when I found unseen posts way below older ones. And the order /seemed/ to change between times I loaded the feed on the web page (I didn't bother to keep a record).
