### ISSUE TITLE
Anonymous requests

### ISSUE THREAD

**Issue by 89z** [instaloader/instaloader#1400]
It used to be possible to make a limited number of anonymous requests, but lately anonymous requests dont seem to be working at all. Is it still possible to do this?

**Comment by afterdelight** [comment]
how many number of posts is possible to view before?

**Comment by 89z** [comment]
Was 15 per day, then 5, then 1. I think its back up to 5

**Comment by afterdelight** [comment]
what about stories? can it downlaod stories anonymously?

**Comment by 89z** [comment]
please provide example URL

**Comment by afterdelight** [comment]
https://www.instagram.com/natgeo/?hl=en

**Comment by 89z** [comment]
sorry I dont provide support for bulk downloading, only individual posts

**Comment by afterdelight** [comment]
i was talking about downloading stories anonymously, not downloading post

**Comment by 89z** [comment]
I don't support bulk downloading period. If you want help, you need to link to a single post or story, not an entire account as you've done.

**Comment by afterdelight** [comment]
i don't know how to link single story timeline, sorry
