### ISSUE TITLE
Attempting to download stories from a private account not followed using --no-posts doesn't result in error

### ISSUE THREAD

**Issue by bart4371** [instaloader/instaloader#1402]
**Describe the bug**
While attempting to download stories with an account which does not follow a particular user, I don't get an error message if I use the --no-posts flag.

**To Reproduce**
Type this command, with private_account_not_followed and your_account replaced with the appropriate accounts:
instaloader private_account_not_followed --login=your_account --no-posts --stories

**Expected behavior**
I expect there to be an error message like if I try to download posts from this user with the same account. If I try to download with posts, I get the message private but not followed.

**Instaloader version**
4.8.3

**Comment by aandergr** [comment]
Indeed, download_profiles() performs a check whether the profile in question is followed or public, and if not raises a PrivateProfileNotFollowedException with the error message "Private but not followed." This check is only performed when downloading tagged media, igtv, highlights and regular posts, but not for stories. It would be appropriate to raise said exception also, when only stories are to be downloaded.

**Comment by bart4371** [comment]
A very similar issue which I don't know if it has been solved is also to check if someone has blocked you from seeing their stories (but not blocked you from seeing their profile), so that you can switch to a different account. I know that a different IG downloader (Raider) appears to handle this case pretty well.
