### ISSUE TITLE
Object of type Profile is not JSON serializable.!!

### ISSUE THREAD

**Issue by rsa408** [instaloader/instaloader#1403]
in any way, I try to make JSON file of comments it is not possible:
it returns: **_` Object of type Profile is not JSON serializable`_**
```
file = open(SHORTCODE+".json", 'w', encoding='utf-8')
for x in post.get_comments():
	post_info = {
        "post_shortcode": post.shortcode,
        "commenter_username": x.owner,
        "comment_text": (emoji.demojize(x.text)).encode('utf-8', errors='ignore').decode() if x.text else "",
        "comment_likes": x.likes_count
    }
    file.write(json.dumps(post_info, ensure_ascii=False, indent=4))

```

any kind of help will be useful.

update: postinfo:
`{'post_shortcode': 'xxxxxxxxxx', 'commenter_username': <Profile benita1971 (4472977016)>, 'comment_text': 'lovely', 'comment_likes': 1}`

**Comment by aandergr** [comment]
This is not an appropriate place to seek basic Python programming help. As already indicated in the issue template, we unfortunately do not have the necessary capacity for that.
