### ISSUE TITLE
Downloading 1000+ posts

### ISSUE THREAD

**Issue by leothewolf** [instaloader/instaloader#1405]
Hey guys, 
First of all thanks for this tool. Am seeking to download posts from an account which has 1400 posts, it worked fine till first 300 posts but then it started to stop bcs of too many requests and console stated better video quality aint downloaded....is there some kind of trick for this?

**Comment by faiblesse2** [comment]
you have to wait because of instagram's rate limits. scraping 300 posts in one go is too much for instagram

**Comment by leothewolf** [comment]
> you have to wait because of instagram's rate limits. scraping 300 posts in one go is too much for instagram

Ohh yea I got it......It was downloaded after I restarted within 1hr or so ig....thanks for the reply

Ill close this now that its solved
