### ISSUE TITLE
 Instagram original quality 

### ISSUE THREAD

**Issue by 89z** [instaloader/instaloader#1406]
Using this command:

~~~
instaloader -- -CZVEugIPkVn
~~~

I get result image 1080x1080 - however with other tools, I am able to get 1241x1241. Can instaloader get the original quality?

**Comment by UweLau** [comment]
You have to provide a login name and  a password (or enter the password when asked) to get the original size. Up to 1440x1440 for post if the original picture is big enough. Stories can go higher with over 2000px.
Which other tools did you use to get 1241x1241? To my knowledge there are not many working instagram scrapers.
Care to tell us which other tools are able to

**Comment by 89z** [comment]
https://github.com/89z/mech
