### ISSUE TITLE
Is there any way to get requests in json format? 

### ISSUE THREAD

**Issue by rsa408** [instaloader/instaloader#1407]
Hi guys,
In such below code we will get comments and replies of each comment in context format

```
comments= []
for comment in post.get_comments():
    comments.append(comment)
    for answer in comment.answers:
        comments. append(answer)

```
The output is not in json format. 

Is ther any way to get out put in json format with the same form that command line generates?

Regards

**Comment by aandergr** [comment]
This is not an appropriate place to seek basic Python programming help. As already indicated in the issue template, we unfortunately do not have the necessary capacity for that.
