### ISSUE TITLE
Maximum download limit

### ISSUE THREAD

**Issue by remlap** [instaloader/instaloader#141]
Hi I would like the option to only download the most recent posts from a user, say --maximum 2 (if multiple pictures it will download them all) would download the two most recent posts.

Thanks

**Comment by aandergr** [comment]
Similar to #121. One could implement an only-if-/post-filter- style `--takewhile` where besides the post's date something like the post count is defined.

**Comment by peak-load** [comment]
It's issue as I can't download more than 1000 posts - I got banned.

**Comment by movAX13h** [comment]
not possible via cli; see #1660
