### ISSUE TITLE
Images are being downloaded as .webp instead of .jpg

### ISSUE THREAD

**Issue by EpiPhobe** [instaloader/instaloader#1414]
**Describe the bug**
Images are being downloaded as `.webp` files instead of the usual `.jpg` files.

**To Reproduce**
I'm using the Python module.
`L = instaloader.Instaloader(download_geotags=False, compress_json=False, filename_pattern='{mediaid}')`
I first saved thousands of shortcodes from a particular hashtag by iterating through:
```
post_iterator = instaloader.NodeIterator(
    L.context, "9b498c08113f1e09617a1703c22b2f32",
    lambda d: d['data']['hashtag']['edge_hashtag_to_media'],
    lambda n: instaloader.Post(L.context, n),
    {'tag_name': hashtagname},
    f"https://www.instagram.com/explore/tags/{hashtagname}/"
)
```
Then I downloaded the post using:
```
post = instaloader.Post.from_shortcode(L.context, 'shortcode')
L.download_post(post, target='target')

```
This is one of the posts that saved as `.webp`:
`'CZbzQ5vL0tB'`

**Expected behavior**
Save the image as a `.jpg` instead of `.webp`

**Error messages and tracebacks**
N/A

**Instaloader version**
4.8.4

**Additional context**
I had not tried scraping posts since about two weeks ago so it seems like this is something new. I'm only getting `.webp` files for posts from this year (although not all). I downloaded 417 posts from this month (February) and the image files I got were 638 jpgs and 106 webps.
I'm not expecting this to be fixed if this is considered an non-issue but I thought I should bring it up

**Comment by bschollnick** [comment]
I'm having the same issue, and it would be nice to have the option to convert the web to JPG or PNG, if we choose to.

**Comment by adityaa-codes** [comment]
Facing the same

**Comment by faiblesse2** [comment]
Same issue. What is weird is that I previously downloaded an account and all images were jpg with very few webp. Downloaded the same account again & now there are much more webp images, including images that were previously downloaded as jpg.

**Comment by tndgpp** [comment]
The same happens here, but analyzing the .webp files with a hex editor, it turns out that they are in fact regular .jpg files.  It seems they were simply given the wrong extension.

**Comment by afterdelight** [comment]
i got some of those .webp when i was downloading stories

**Comment by aandergr** [comment]
Thanks for reporting. Indeed, Instaloader extracts the file extension from the URL and thus saves some of the downloaded JPEG files with a `.webp` extension. 

> **Expected behavior**
> Save the image as a `.jpg` instead of `.webp`

I agree, if the image is a JPEG, it should be saved as a `.jpg`.

**Comment by bschollnick** [comment]
Well, if the URL file extension is not dependable.  Why not check for the image file signature (aka magic bytes) to identify the file type, and then use that file extension instead?

I know there are a variety of different ways to identify the file header/signature/magic bytes.  But for example, pyfsig's matches function, eg:

 file_type = matches(file_contents[0:30])

would certainly be one way to handle that.  If we wanted to optimize, then this could be gated only for services that return unreliable file extensions.

(I'm really surprised that Pillow doesn't offer something equivalent for image files, but If it does, then my google fu was/is broken.

**Comment by miriq** [comment]
On linux, you can use this command to automatically rename all the wep3 files to jpg:

```
find . -depth -name "*.webp" -exec sh -c 'mv -vi "$1" "${1%.webp}.jpg"' _ {} \;
```

**Comment by miriq** [comment]
On linux, you can use this command to automatically rename all the webp files to jpg:

```
find . -depth -name "*.webp" -exec sh -c 'mv -vi "$1" "${1%.webp}.jpg"' _ {} \;
```

**Comment by afterdelight** [comment]
what about on windows platform?

**Comment by faiblesse2** [comment]
bump

**Comment by fireattack** [comment]
Instead of hacking, we can fix it by reading the response header and correct the format if it does not match with `resp.headers['Content-type']`.

**Comment by EpiPhobe** [comment]
> what about on windows platform?

This worked for me:
`ren *.webp *.jpg`

**Comment by faiblesse2** [comment]
^

**Comment by faiblesse2** [comment]
A temporary fix I found is using irfanview, its an alternative image viewer to windows photos. all you have to do is open the webp image, and you will be given a prompt that states that the image is a jpeg given an incorrect extension. it will ask you  if you wish to convert it to jpeg
