### ISSUE TITLE
greatfon or imginn support

### ISSUE THREAD

**Issue by nascentt** [instaloader/instaloader#1416]
**Provide us a use case of the feature**
How could the user invoke the new function? Which problem would it solve?
If new information is obtained, how would it be further processed?

in order to download more than a few dozen instagram posts you get redirected to login.
if you login, your account gets banned (I've gone through five accounts already)
there are instagram caching services like greatfon and imginn that let you access instagram images without login.
Can instaloader not add support for these to get around these limitation?

It would mean this script as actually usable as any time it is run the account it is logged into gets banned.

**Describe the solution you'd like**
greatfon.com or imginn.org support

**Describe alternatives you've considered**
There's no alternative solutions.  I've hunted through every instagram downloader and none offer this. 
**How do you achieve the here-described goal without the feature you are requesting?**
I can't

**If the feature request is accepted, would you be willing to submit a pull request?**
No

**Additional context**
Add any other context about the feature request here.

**Comment by aandergr** [comment]
No.
