### ISSUE TITLE
profile image file extension sometimes broken

### ISSUE THREAD

**Issue by Showmaster3000** [instaloader/instaloader#142]
Since some days I noticed unexpected extentions of downloaded profile images. Mostly I got *.yJ9 instead of *.jpg. Just checked the problem and it seems that the url has changed with an additional parameter at the end. So the current extension detection code using the last three characters is broken.

sample:
from profile json:
`"profile_pic_url": "https://scontent-ber1-1.cdninstagram.com/vp/xxxxxxxxxx/t51.2885-19/s150x150/123456789_1234567890_1234567890_n.jpg?efg=xxxxxxxxxxxxxxxxxxxxxyJ9"
`
-> filename gets `2018-06-03_07-45-17_UTC_profile_pic.yJ9` instead of `2018-06-03_07-45-17_UTC_profile_pic.jpg`
If the parameter changes, another file is downloaded with the same image if its not changed by the user.

possible solution: maybe we can split the url at the "?" and use the first part to get the extension.

**Comment by aandergr** [comment]
Thanks! We fixed it in 2df1419 and will soon release 4.0.5 with this fix included. Our solution was to just hardcode 'jpg' as filename.
