### ISSUE TITLE
Missing comments collected due 429 error

### ISSUE THREAD

**Issue by pvita** [instaloader/instaloader#1422]
**Describe the bug**
I'm triyng to collect almost 5k comments from a single post (I have the shortcode).
After almost 2 hours (3000, 35000 i read in the CMD) I'm encountering 429 error repeatedly, so I can't to anything else. I can only stop the collection. I tried to wait a bit, but the collection doesn't restart.

Anyway, when I stop the collection (ctrl+c), i lose also the comments collected yet (3000, 3500). The folder is empty.

**To Reproduce**
instaloader --login XXX --comments --no-pictures --no-videos --no-captions --no-metadata-json --max-connection-attempts 0 -- **-shortcode**

**Expected behavior**
I would save the comments collected before the error, at least.

**Instaloader version**
4.8.4

**Additional context**
I tried also with different profiles logged in.

**Comment by aandergr** [comment]
Does this problem still occur with version 4.9?

Also, is there any shortcode where it occurs reliably?

**Comment by pvita** [comment]
> Does this problem still occur with version 4.9?
> 
> Also, is there any shortcode where it occurs reliably?

I didn't try with the new update. I will let you know.
If you want a test shortcode try this one: CaAGxjMqI45

**Comment by pvita** [comment]
> Does this problem still occur with version 4.9?
> 
> Also, is there any shortcode where it occurs reliably?

The problem stlil occurres. When you stop the collection (ctrl+c after 429) it doesn't close the file, losing all the already collected comments.

**Comment by aandergr** [comment]
> When you stop the collection (ctrl+c after 429) it doesn't close the file, losing all the already collected comments.

The current state of downloaded comments is saved with ctrl+c or with AbortDownloadException together with a resume file. This works fine for me, I do not understand the bug that you are reporting.
