### ISSUE TITLE
Cant access new pages of hashtag posts, max_id doesn't work

### ISSUE THREAD

**Issue by scanansi** [instaloader/instaloader#1423]
I am using the hashtag.get_posts() function, and im aware that there is an alternative json data interpretation required, which i have implemented. My problem is that i can't get page 2 of the hashtag's posts. Is anyone else experiencing this?

`
if hasNextPage:

        jsonData = session.context.get_json(
            path="explore/tags/" + hashtag + "/",
            params={"__a": 1,
                    "max_id": jsonData['data']['recent']['next_max_id']}
        )
`
jsonData has the exact same sections and posts as the previous request

thanks in advance

**Comment by scanansi** [comment]
I found that i can get the rest of the posts if i make an anonymous call. So the issue is linked to the user I login with, and its a issue Instagram is creating on their side for 'flagged accounts' ?

**Comment by Busterfake** [comment]
Did you manage to solve your problem, i think i have the same issue... After downloading 30 posts, it starts all over again from the begining. I didn't manage to find a solution yet, i tried with multiple different accounts but same issue.

**Comment by scanansi** [comment]
anonymous call i mean the session isnt with a logged in user

**Comment by scanansi** [comment]
I think the issue has gone away, anyone else notice the same?

**Comment by yeahalti** [comment]
Hasn't for me. After every 25 posts, it creates duplicate entries. If the issue is resolved for you, do you mind sharing your code?

**Comment by scanansi** [comment]
Ok, it's not entirely fixed. It works for some accounts, some not. I created a new instagram account that gets a different hashtag data results. You can try with different usernames, it might start to work for you
