### ISSUE TITLE
Best method to use multiple instances of instaloader?

### ISSUE THREAD

**Issue by Blazingfairy** [instaloader/instaloader#1426]
My current understanding is that:

L = instaloader.Instaloader()

creates a new Instaloader instance which is stored in the variable L. Every time instaloader.Instaloader() is executed, a new instance is created and it is recommended to keep a single instaloader instance to fetch stories/etc repeatedly with whatever logic to wait between subsequent calls.

The logic of my current set-up is:
```

loop start:
instaloader.Instaloader() line
load_session_from_file() line
...
Profile.from_username() line
...
repeat loop (where the target profile is different and the account used to login may change)
```

Would it be wiser to place the instaloader instance outside of and before the loop? And leave the load_session_from_file line at the start of the loop? I'm hesitant to log into a different account with the same instance. Is that problematic?

Would it be wiser to perform calls on multiple profiles at once before ending my loop? Such that account 1 would make calls to 10 accounts in one go, then repeat loop enabling account 2 to make another 10 calls to different accounts? I have a delay between each iteration of the loop, but I'm wondering if it is better to have a delay between multiple uses of the Profile.from_username() line within a loop.

**Comment by afterdelight** [comment]
Please provide your full script, so i can see whats best

**Comment by afterdelight** [comment]
hi bot
