### ISSUE TITLE
manual for debian

### ISSUE THREAD

**Issue by Nilsonfsilva** [instaloader/instaloader#1429]
Good afternoon!
My name is Nilson Silva, I'm a contributor to the Debian project.

There is a packaging request for the instaloader:
 ##https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=914909

 In order for the project to be accepted within Debian's policies, a manual on the construction of the binary is required.
Therefore, I had to create one so that the instaloader can enter the distribution's repositories.

It's attached, if you want to make improvements and corrections, I'm waiting!
[manual.txt](https://github.com/instaloader/instaloader/files/8164450/manual.txt)

**Comment by aandergr** [comment]
Hi Nilson!

Thanks for your efforts to create a Debian package. This sounds interesting!

> In order for the project to be accepted within Debian's policies, a manual on the construction of the binary is required.

Instaloader is a Python script, no binary is constructed during its installation.

The manual page describes Instaloader as `isntagran automatic photo downloader`, which is weird.

> My question is: Does the binary of this program depend on this file to work?

`docs/_static/instaloaderdoc.js` is only required for the HTML documentation. The program itself does not depend on this file.
