### ISSUE TITLE
Is there a way to export all the post I liked?

### ISSUE THREAD

**Issue by aseques** [instaloader/instaloader#143]
I would like to automate downloading all the posts have liked. So far I am using the combination with #hashtag + --post-filter=viewer_has_liked, but it's not very convenient.
If there is no hashtag added, I get the message "No targets were specified, thus nothing has been downloaded."
Are there any options for this in instaloader I have missed?

**Comment by aandergr** [comment]
Unfortunately not. As alternatives, there is `--post-filter=viewer_has_liked :feed`, which only loads the pictures of the feed, or saving all interesting pictures and using the `:saved` target.

**Comment by aseques** [comment]
@aandergr  thanks a lot, both options will go for me 👍

**Comment by e5150** [comment]
It is possible to see all the posts you've liked in the app, so it's not impossible to do similarly to how stories were handled before they were available on the web page...
```
import instaloader
import json
l = instaloader.Instaloader()
l.load_session_from_file(USERNAME)
del l.context._session.headers['Host']
del l.context._session.headers['Origin']
del l.context._session.headers['X-Instagram-AJAX']
del l.context._session.headers['X-Requested-With']
l.context._session.headers['User-Agent'] = 'Instagram 10.3.2 (iPhone7,2; iPhone OS 9_3_3; en_US; en-US; scale=2.00; 750x1334) AppleWebKit/420+'

params = {}
done = False
while not done:
	data = l.context.get_json(path='api/v1/feed/liked/', host='i.instagram.com', params=params)
	for item in data['items']:
		p = instaloader.Post.from_shortcode(l.context, item['code'])
		if not l.download_post(p, ':liked'):
			done = True
			break
	if not data['more_available']:
		break
	params['max_id'] = data['next_max_id']

```

Unfortunately, the responses to the "app" are incompatible with the json node format that `Post` expects,  so each post has to be infered from its shortcode. While I don't think the requests to instagram.com/p/code/ are counted towards the limit, it slows down the process. In either case it seems to be necessary to be able to tell if a post has a video or multiple images (might be solved by setting some magic HTTP headers).

A quick-and-dirty variant would be to rawly download just the base image itself:
```
for item in items:
	url = item['image_versions2']['candidates'][0]['url']
	l.context.get_and_write_raw(url, item['code'] + '.jpg')
	print(url)
```
(On a side note related to #80 , each `item` has a numerically encoded `filter_type` attribute.)

**Comment by e5150** [comment]
ADDENDUM:
Yes, by setting a newer user agent, such as: `Instagram 10.26.0 (iPhone7,2; iOS 10_1_1; en_US; en-US; scale=2.00; gamut=normal; 750x1334) AppleWebKit/420+` all "album"/"sidecar" images gets exposed in the returned json.
```
for item in data['items']:
  def _get(x):
    url = x['image_versions2']['candidates'][0]['url']
    l.context.get_and_write_raw(url, item['user']['username'] + '-' + x['pk'] + '.jpg')
  if 'image_version2' in item:
    _get(item)
  elif 'carousel_media' in item:
    for i in item['carousel_media']:
      _get(i)
```
Ought to work (not tested) as a more complete fast way, without spamming the servers for each shortcode.

**Comment by minijoo** [comment]
> 	data = l.context.get_json(path='api/v1/feed/liked/', host='i.instagram.com', params=params)

Curious, where do you find the docs for api? A brief search is telling me it's a mobile-only endpoint. Seems to be the only way of getting a user's likes. Thanks!
