### ISSUE TITLE
Download posts from hashtags stops after 30 posts

### ISSUE THREAD

**Issue by Busterfake** [instaloader/instaloader#1430]
Hello, I'm using Instaloader for a while now to download images from specific #. Everything was working well so far but now when i try to use it, the download process start again after 30 posts dowloaded and starts to download the same 30 again again. 
Is there any reason for that ? 
I didn't change my script at all and i tried to log with a new account but same issue. 
Moreover, most of the images that i manage to download are now in .webp format and not in .jpg. 

![image](https://user-images.githubusercontent.com/36502499/156398410-e886e54a-af18-486f-867c-7081dd7f0e75.png)
You can see on the image that after 30 downloads it downloads images already downloaded.

I put my code here if anyone wants to check: 

     
      import time
      import instaloader

    from random import randint
    from time import sleep

    htag = ["portjacksonshark", "muraenahelena", "redgurnard", "soldierfish", "yellowtang", "holacanthustricolor", "blueringangelfish", 
    "redsaddlebackanemonefish", "denisonbarb"] 

    for fish in htag:

    max_count = 1000
    # Create an instance of Instaloader class
    bot = instaloader.Instaloader(dirname_pattern=fish, save_metadata=False, post_metadata_txt_pattern=None, download_videos=False,download_video_thumbnails=False)
    bot.load_session_from_file('azerty_yolo5')
    current_count = 0

    for post in bot.get_hashtag_posts(fish):
        current_count = current_count + 1
        if (current_count > max_count) :
            print("we got enough, next")
            break
        

        try:
            # Download the post
            bot.download_post(post, target='#'+fish)
            sleep(randint(1,3))
        except:
            print("fail to download image")
            break # If there are any errors, we break out of the loop
        print(current_count,"/",max_count)

    print("sleep 30s")
    time.sleep(30)

Thank you !

**Comment by scanansi** [comment]
Hi Busterfake

I noticed the same issue [on my side](https://github.com/instaloader/instaloader/issues/1423). It seems to be an update from Instagram that doesn't allow subsequent pages (size 30) to be fetched with the /explore/tags/{tag name} end point. 

Having looked at the Instagram hashtagged posts webpage, i believe the only way forward is to [implement access their new endpoint](https://github.com/instaloader/instaloader/issues/1428) to keep up to date with how the Instagram API works. 

Let me know if there is something I don't know, open to hearing insight on this issue

**Comment by GGImpact** [comment]
Hi all, I also have this issue, Hashtag.from_name(...).get_posts() continuously generate the latest 30 posts repeatedly.
Much appreciate if this could be solved, thanks.

**Comment by OfraKlein** [comment]
I also am experiencing this issue. I hope this can be solved, thank you so much!

**Comment by nibu147** [comment]
same issue here

**Comment by hitboxr** [comment]
Version 4.9 side-steps this issue by adding `Hashtag.get_posts_resumable()`, which uses a GraphQL query hash to pull hashtag data instead of the new `/sections/` endpoint, since apparently instagram has not deprecated serving paginated hashtag content through GQL. However, the issue remains that Instaloader's implementation of fetching from the new `/sections/` endpoint is broken for both hashtags and locations (see #1470)
