### ISSUE TITLE
Retrying 400 bad request

### ISSUE THREAD

**Issue by bart4371** [instaloader/instaloader#1431]
**Provide us a use case of the feature**
It appears that no retries are made when a 400 bad request is encountered, which happens to random story items that I try to download. This results in failure to obtain the high-quality version. IMO, this should be retried at least once if it fails. Now it requires painstaking effort to look through every single failed item.

There would be very little change, perhaps none, but you could have an option like --retries=5 for a maximum of 5 retries for each failed item.

Also, you could skip downloading the poor quality version unless it still fails at the max number of attempts.

**Describe the solution you'd like**
A number of retries are made until the missing items are successfully downloaded, or still fail for some reason.

**Describe alternatives you've considered**
Rerunning until the issue no longer appears, for every account that has items for which the error appeared.

**If the feature request is accepted, would you be willing to submit a pull request?**
I'm not fluent in Python, so I don't think so.

**Additional context**
I have started getting these a lot recently even when my accounts have not been locked.

**Comment by afterdelight** [comment]
put --abort-on 400 so it doesnt download low quality pictures

**Comment by bart4371** [comment]
> put --abort-on 400 so it doesnt download low quality pictures

I might add that I would rather have the low quality versions than none at all. But more than one attempt at the max quality should be made.

**Comment by aandergr** [comment]
When a query is responded with 400 Bad Request, does an immediate retry lead to a successful response? Have you experimented with that?

**Comment by bart4371** [comment]
I have retried manually just a few times but the times I retried the error didn't show up again. 400 bad request also shows some false responses, I have recognized. Most of the time, the high quality version is downloaded even when it says that it is not (but not always).

**Comment by afterdelight** [comment]
use mobile user agents such as android or iphone then approve the login activity on instagram app. it will reduce the instance of getting blocked

**Comment by afterdelight** [comment]
> > put --abort-on 400 so it doesnt download low quality pictures
> 
> I might add that I would rather have the low quality versions than none at all. But more than one attempt at the max quality should be made.

i usually run the script multiple times to get all the skipped images by error 400

**Comment by bart4371** [comment]
> use mobile user agents such as android or iphone then approve the login activity on instagram app. it will reduce the instance of getting blocked

Thanks. Preliminary results suggest that this is useful as I seem to be getting 400 bad request less often.

**Comment by AplhaSlayer1964** [comment]
> use mobile user agents such as android or iphone then approve the login activity on instagram app. it will reduce the instance of getting blocked

Do you use the Instagram app user agents or just a safari user agent, the mobile version?

**Comment by afterdelight** [comment]
I use instagram's android or iphone app user agents
