### ISSUE TITLE
Help with the --post-filter function

### ISSUE THREAD

**Issue by jhiwatig** [instaloader/instaloader#144]
Hello everyone,

First of all, thanks for a wonderful instagram scraper. :)

Now, I am stuck on how to use the filter function in the command line. My goal is to download all posts of a specific user that matches the hashtag that i need. For example, I want to download all my posts with the #ocean. I get  "SyntaxError: unexpected EOF while parsing" when i use this: instaloader iguser --post-filter="#ocean". Any help would be appreciated. Thanks!

**Comment by aandergr** [comment]
Hello,

the right way to do that is
```
instaloader iguser --post-filter="'ocean' in caption_hashtags"
```

Here is an explanation of the syntax of these strings, among with a few examples: https://instaloader.github.io/basic-usage.html#filter-posts

Happy Instaloading!
Alex

**Comment by jhiwatig** [comment]
hello aandergr!

Thanks! it worked! How do you implement this in python though?

**Comment by aandergr** [comment]
> How do you implement this in python though?

`Instaloader.download_*()` methods accept a parameter `post_filter`, which is a function that gets a `Post` object and returns True or False, whether the Post should be downloaded or not. Instaloader converts the `--post-filter` string (which syntactically is a Python code that evaluates to True or False) into such a function using this magic:
https://github.com/instaloader/instaloader/blob/b5aa268344a52c86e7aa15df594ac1b4d1a2e4c4/instaloader/__main__.py#L27-L56

It uses Python's [ast -- Abstract Syntax Trees](https://docs.python.org/3/library/ast.html) module to parse the `--post-filter` string. Then it goes through the AST representation of that code and replaces each occurence of a variable load (e.g. `caption_hashtags`) by an attribute load in the object `item` (e.g. `item.caption_hashtags`). The function returned by `filterstr_to_filterfunc()` evaluates the modified AST, with the `item` object set to the particular post.
