### ISSUE TITLE
Get @/id of user who uploaded picture? Name picture like this.

### ISSUE THREAD

**Issue by jcjms** [instaloader/instaloader#1442]
Dear community,

I would like to download a certain number of hashtags - posts (instaloader #hashtag [how can I add number of posts?]) and I would like to get the @/id of the account that uploaded the respective image. It should be set as the picture name. How would that work? Is there a command for this? Best wishes.

**Comment by ulrichhave** [comment]
Hi @jcjms 
Try this:
`instaloader --login <your_username> --count 10 --filename-pattern={profile}_{date_utc}_UTC "#peace"`

to fetch 10 posts w. hashtag 'peace' saving them with the profile name as the first part of the file name.

You can find the different naming options here:
[https://instaloader.github.io/basic-usage.html#filename-specification](https://instaloader.github.io/basic-usage.html#filename-specification)

If you're only interested in the pictures, consider adding these two options 
`--no-captions --no-metadata-json`

Hope that answers your question?

Best regards, Ulrich

**Comment by jcjms** [comment]
Many thanks for your response. Unfortunately, I've gotten that far. But I keep getting this error. What can I do? 

```
    return self._context.get_json("explore/tags/{0}/".format(self.name),
KeyError: 'graphql'
```

**Comment by jcjms** [comment]
#1450 my issue/bug
