### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by UnixCro** [instaloader/instaloader#1443]
I can no longer log in with any account

`21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 x86_64; Python 3.8.9; Python 2.7.18; 4.9b2`

```
instaloader --login=
Session file does not exist yet - Logging in.
Enter Instagram password for : 
Fatal error: Login error: "fail" status, message "".
```

**Comment by 42shells** [comment]
Same thing.
I believe this is a temporary issue.
Roscomnadzor banned Instagram and Facebook in Russia yesterday.
