### ISSUE TITLE
Once it downloads 12 images it asks me to login

### ISSUE THREAD

**Issue by 123Axo** [instaloader/instaloader#1444]
**Describe the bug:**
Ok, so, just today I installed this program. I´m an artist so i need lot´s of references so I found this Heavenly program.
I tried for the first time using this tool on the profile of the artist "jordi_lafebre", he has a total of 183 posts, i was perfect but it stopped on the post number 162; so I tried again... but this time it stopped on the post number 12. I've tried with other profiles but every profile stops at #12.

I already logged in so i don't get why it asks me to login.

**To Reproduce**
Virtually any command. I've also tried with "instaloader --latest-stamps -- jordi_lafebre" and the same thing happens.

**Expected behavior**
It is supposed to download every picture and video from a profile, but it just stops at 12.
It has already saved my login data so it shouldn't ask me to login again.

**Error messages and tracebacks**
I will put two pictures.

**Instaloader version**
My version is 4.8.4.

**Additional context**
Well... i don't know anything about programming, so please have compassion xd
It just happens that i used BCML for Zelda BOTW mods; that's why I already had python (BCML uses python).

Thanks guys!!!

![Screenshot 2022-03-14 183427](https://user-images.githubusercontent.com/101610859/158290017-94968c52-e6ea-4a33-8baf-ad9d262f5ed0.jpg)
![Screenshot 2022-03-14 184319](https://user-images.githubusercontent.com/101610859/158290020-829abed0-1c15-4629-b959-af3ed5c53353.jpg)

**Comment by 42shells** [comment]
Use your Instagram profile name and password to login
```
instaloader --login 42shells jordi_lafebre
```
![scr-220315-0446 28 691714887](https://user-images.githubusercontent.com/69177357/158296053-c21628b2-6203-4728-8915-2e8ca6d5da2b.jpg)

**Comment by ielenik** [comment]
After login I got 'Checkpoint required' message (url is slightly cutted in log below)
After visiting urls nothing is changed

C:\projects\python\instagram>instaloader ielenik --login ielenik
Session file does not exist yet - Logging in.
Enter Instagram password for ielenik:
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/AXEE0DV_mAiEHrhydugghYIMUN6ZxgQK/ - follow the instructions, then retry.

C:\projects\python\instagram>instaloader ielenik --login ielenik
Session file does not exist yet - Logging in.
Enter Instagram password for ielenik:
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/AXEMIW57LRsayQ_HK1OKFGlHonCFoO/ - follow the instructions, then retry.

**Comment by 123Axo** [comment]
> Use your Instagram profile name and password to login
> 
> ```
> instaloader --login 42shells jordi_lafebre
> ```
> 
> ![scr-220315-0446 28 691714887](https://user-images.githubusercontent.com/69177357/158296053-c21628b2-6203-4728-8915-2e8ca6d5da2b.jpg)

Bro!, Thanks, it worked!!!

Taking advantage of the fact that you are here, I have a question.: Is it possible to make the program download only the images and videos of the profile?
It's just that it also downloads a RAR .json file and a text file which are not necessary.

Additionally, is there a way for the program to download the images only as .jpeg or .PNG, because some of them seem to be downloaded as html?

Thanks in advance man!!!

**Comment by aandergr** [comment]
> Is it possible to make the program download only the images and videos of the profile?
> It's just that it also downloads a RAR .json file and a text file which are not necessary.

There is `--no-metadata-json`: https://instaloader.github.io/cli-options.html#cmdoption-no-metadata-json



> Additionally, is there a way for the program to download the images only as .jpeg or .PNG, because some of them seem to be downloaded as html?

None are downloaded as html, however, we had a bug that some images were saved with a `.webp` extension, which has been fixed with today's new releases of Instaloader.

**Comment by 123Axo** [comment]
> > Is it possible to make the program download only the images and videos of the profile?
> > It's just that it also downloads a RAR .json file and a text file which are not necessary.
> 
> There is `--no-metadata-json`: https://instaloader.github.io/cli-options.html#cmdoption-no-metadata-json
> 
> (just for the sake of completeness: they are saved XZ-compressed, rather than RAR)
> 
> > Additionally, is there a way for the program to download the images only as .jpeg or .PNG, because some of them seem to be downloaded as html?
> 
> None are downloaded as html, however, we had a bug that some images were saved with a `.webp` extension, which has been fixed with today's new releases of Instaloader.


Thanks man, this is the pattern that I usually use: instaloader --no-metadata-json --no-captions --login (my account name) (the name of the artist).

Thanks to all of you for helping me!!!
