### ISSUE TITLE
How do I get collaborators?

### ISSUE THREAD

**Issue by MiguelX413** [instaloader/instaloader#1445]
How do I get collaborators (like [@uf.rei.plush](https://instagram.com/uf.rei.plush/) in https://instagram.com/p/CZpzmnlO6io/ )?

**Comment by aandergr** [comment]
This information seems to be missing in Post instances that are created by most means, and I did not find it in the information that is fetched by `Post._obtain_metadata()` and `Post._iphone_struct`. 

However, Instagram introduced a new format that we call 'sections'-style responses. Starting with Version 4.9 of Instaloader, hashtag posts are obtained in this new format. These Post instances carry the collaborators information inside their `iphone_struct` structure, such that when saved to a JSON file by Instaloader, you can get the collaborators at `.node.iphone_struct.coauthor_producers`, which is an array of structures that are directly supported by Instaloaders `Profile` class.

This gives hope that there is a way to systematically and easily obtain this information. Hence, I would like to track this as a feature suggestion.
