### ISSUE TITLE
Username in '--title-pattern'

### ISSUE THREAD

**Issue by jcjms** [instaloader/instaloader#1449]
Hello, I would like to set the name of the user who uploaded the picture as the filename. I tried running this command: instaloader "#cars" --filename-pattern {profile} But that doesn't seem to work. Is there any way at all to do this? I definitely need the user name somewhere, whether it's in a json doesn't really matter to me, but it has to be there. Kind regards.

**Comment by ulrichhave** [comment]
Hi @jcjms 
I answered your other question (issue #1442) and it's similar:
`--filename-pattern={profile}_{date_utc}_UTC` so it seems that you just need to add`=`?

**Comment by jcjms** [comment]
Thank you. Got another error. Added it to the old question.
