### ISSUE TITLE
Image or Json file exists: only getting less than 40 images searching for a hashtag

### ISSUE THREAD

**Issue by OfraKlein** [instaloader/instaloader#1457]
I am using the new version of Instaloader, the command line (4.9b2) and am experiencing problems gathering hashtags and  metadata. I am gathering data from small hashtags (with around 20 posts) to bigger ones (a few hundereds). Every time that I try to gather data of a hashtag, instaloader only provides you around 30 images, not more, while you would expect to receive more images. I have tried this for several hashtags using the following codes in the interface: 

.\instaloader --login ACCOUNTNAME --post-metadata-txt="{likes} likes, {comments} comments, {caption} caption." "#hashtag"

.\instaloader --login ACCOUNTNAME --no-metadata --no-videos --no-captions --no-profile-pic "#hashtag"

.\instaloader --login ACCOUNTNAME --no-pictures --no-videos --no-profile-pic --no-captions --metadata-json "#hashtag"

The image below shows an example of the error message that I get: ".jpg exists", even though it does not. Is there any idea what the cause of this problem can be, and whether there is a solution?

![image](https://user-images.githubusercontent.com/26406791/159037524-68f98f1f-5b98-446f-aa99-ec3d15dd350e.png)

**Comment by aandergr** [comment]
Thanks for trying out our beta release and for reporting this bug. Indeed, I can reproduce that when downloading hashtags, Instaloader attempts to download the first page of the hashtag infinitely in a loop.
