### ISSUE TITLE
QueryReturnedNotFoundException: 404 Not Found

### ISSUE THREAD

**Issue by jhiwatig** [instaloader/instaloader#146]
Hello guys! I was scraping 100 posts from each IG user then after the second user finished, it returned this error:

QueryReturnedNotFoundException: 404 Not Found

What does this mean?
Thanks!

The whole error is:

QueryReturnedNotFoundException            Traceback (most recent call last)
<ipython-input-7-73b24e138250> in <module>()
      4 for post in posts:
      5     start = time.time()
----> 6     ig_name = post.owner_username
      7     if num_users == 5:    #number of users to output
      8         break

~\Anaconda3\lib\site-packages\instaloader\structures.py in owner_username(self)
    171     def owner_username(self) -> str:
    172         """The Post's lowercase owner name."""
--> 173         return self.owner_profile.username
    174 
    175     @property

~\Anaconda3\lib\site-packages\instaloader\structures.py in owner_profile(self)
    164                 # is contained.
    165                 # Note that we cannot use Profile.from_id() here since that would lead us into a recursion.
--> 166                 owner_struct = self._full_metadata['owner']
    167             self._owner_profile = Profile(self._context, owner_struct)
    168         return self._owner_profile

~\Anaconda3\lib\site-packages\instaloader\structures.py in _full_metadata(self)
    132     @property
    133     def _full_metadata(self) -> Dict[str, Any]:
--> 134         self._obtain_metadata()
    135         return self._full_metadata_dict
    136 

~\Anaconda3\lib\site-packages\instaloader\structures.py in _obtain_metadata(self)
    126     def _obtain_metadata(self):
    127         if not self._full_metadata_dict:
--> 128             pic_json = self._context.get_json("p/{0}/".format(self.shortcode), params={})
    129             self._full_metadata_dict = pic_json['entry_data']['PostPage'][0]['graphql']['shortcode_media']
    130             self._rhx_gis_str = pic_json['rhx_gis']

~\Anaconda3\lib\site-packages\instaloader\instaloadercontext.py in get_json(self, path, params, host, session, _attempt)
    265                 raise QueryReturnedBadRequestException("400 Bad Request")
    266             if resp.status_code == 404:
--> 267                 raise QueryReturnedNotFoundException("404 Not Found")
    268             if resp.status_code == 429:
    269                 raise TooManyRequestsException("429 Too Many Requests")

QueryReturnedNotFoundException: 404 Not Found

**Comment by aandergr** [comment]
QueryReturnedNotFoundException means that a 404 HTTP response came while obtaining some of the requested data. Your call stack trace suggests that it happened while obtaining a post's full metadata structure, which queries the URL https://www.instagram.com/p/SHORTCODE/. Here, QueryReturnedNotFoundException most probably means that the Post does not exist.

My first guesses: If the Post was instantiated with `Post.from_shortcode()`, the shortcode might have been invalid. If the Post was returned by one of Instaloader's `get_*_posts()` methods, the unlikely case might have happened that the Post was deleted immediately before Instaloader could query its metadata.

**Comment by jhiwatig** [comment]
The Post was instantiated from: posts = L.get_hashtag_posts('hashtag')

We're trying to get the usernames of the posts that have this particular 'hashtag'. That hashtag returns around 200 million posts. The weird thing is every time I rerun the code, 404 error is raised after every 150 - 200 posts scrapes from 2-3 usernames. I have time.sleep(60) for every user. I'm not sure if Instagram blocks me for a few seconds after I scraped a certain number of posts. Also, I am scraping the data but I am not logged in. I'm not sure if this has an effect on the error.

**Comment by MatthieuBonenfant** [comment]
I am getting the 404 error right away not even after downloading 1 image using this simple #darthmaul tag, but #darthvader works. I wonder if we all get the same error using the same tags.

**Comment by aandergr** [comment]
This should have been fixed with 8764947d10d861eff166445dca89fae9617bf780, which will be included in Instaloader 4.3.

To get an installation with this fix included, do
```
pip3 install --upgrade git+https://github.com/instaloader/instaloader
```

**Comment by alexeysofin** [comment]
@aandergr can you please explain how https://github.com/instaloader/instaloader/commit/8764947d10d861eff166445dca89fae9617bf780 fixes that instagram may randomly return 404 on hashtag scans?

**Comment by aandergr** [comment]
> @aandergr can you please explain how [8764947](https://github.com/instaloader/instaloader/commit/8764947d10d861eff166445dca89fae9617bf780) fixes that instagram may randomly return 404 on hashtag scans?

Of course it doesn't fix that instagram may randomly return 404. Obviously, we cannot do that. But it handles how Instaloader reacts when a 404 is returned.

**Comment by dir** [comment]
Been getting this all day today on a perfectly working account, in a completely normal use case of:


```
L = instaloader.Instaloader()
L.login("username", "password")

word = "attention" # random, real account for testing purposes

profile = instaloader.Profile.from_username(L.context, word)

print(profile)
```
