### ISSUE TITLE
Application doesn't create lastest-stamps.ini on its own

### ISSUE THREAD

**Issue by Marcinolak** [instaloader/instaloader#1467]
**Describe the bug**
Application doesn't create lastest-stamps.ini on it's own

**To Reproduce**
```
@echo off
cd %~dp0
instaloader.exe (about 35 accounts to download) --no-compress-json --stories --latest-stamps --login xyz
```

**Expected behavior**
In my opinion app should create AppData\Local\Instaloader\latest-stamps.ini on its own.

**Error messages and tracebacks**
![Screenshot_1](https://user-images.githubusercontent.com/70728051/160260754-aac1c2ce-be74-4216-bef4-bdb516cbf089.png)

**Instaloader version**
I checked v4.8.4 & v4.9

**Additional context**
After creating the directory and file manually everything works fine.
Running as administrator has the same effect.

**Comment by canh** [comment]
fyi, I fixed this on https://github.com/canh/instaloader/commit/f88f965272b9f3a42ebe98b416692e76ecc4537f

I'll make it a PR once upcoming/v4.10 branch is created.
