### ISSUE TITLE
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2217)

### ISSUE THREAD

**Issue by RubyFan120** [instaloader/instaloader#147]
Hi,

I was downloading photos and comments using hashtag while I encountered this error:

ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2217)

I couldn't find any proper solution so I think someone here may know.

Any suggestion will be appreciated.

Regards,

**Comment by aandergr** [comment]
Hi,

I have never heard of this error before. Are your Python, Requests, SSL and SSL certificates up to date?

Regards

**Comment by RubyFan120** [comment]
Hi.

Thank you for your reply. I am sure they are up to date, so could you please come up with other solutions?

Regards,
