### ISSUE TITLE
Do not download reels

### ISSUE THREAD

**Issue by Memo58Memo** [instaloader/instaloader#1473]
Is it possible to don't download reels using instaloader?

I use this currently:
`instaloader --login XX --no-captions --slide 1 --no-metadata-json --no-compress-json --post-filter="likes>400 and comments>20" --no-profile-pic --no-videos %username%`

When i use `--no-videos`. Reels get still downloaded

**Comment by aandergr** [comment]
You could use (hacky but it works)
```
instaloader --login XX --no-captions --slide 1 --no-metadata-json --no-compress-json \
        --post-filter='("product_type" not in _full_metadata or _full_metadata["product_type"]!="clips") and likes>400 and comments>20' \
        --no-profile-pic --no-videos \
        %username%
```

**Comment by pvita** [comment]
> You could use (hacky but it works)
> 
> ```
> instaloader --login XX --no-captions --slide 1 --no-metadata-json --no-compress-json \
>         --post-filter='("product_type" not in _full_metadata or _full_metadata["product_type"]!="clips") and likes>400 and comments>20' \
>         --no-profile-pic --no-videos \
>         %username%
> ```

instaloader: error: unrecognized arguments: metadata-json not in _full_metadata or _full_metadata[product_type]!=clips)
