### ISSUE TITLE
Instaloader module does not download stories from a profile, but command line works

### ISSUE THREAD

**Issue by avagut** [instaloader/instaloader#1477]
**Describe the bug**
Instaloader module does not download stories from a profile but running command line options correctly downloads stories

**To Reproduce**
This works, the stories are downloaded:
`instaloader --login=myIGaccount selected_user --stories --no-captions --no-compress-json --no-metadata-json --no-posts --dirname-pattern ./downloads/{profile}`

The below recreation in the module does not work, its only the profile pic that is downloaded, stories are not downloaded
```
def fetch_stories_only(selected_user: str):
    USER = "myIGaccount"
    SESSION_FILENAME = 'config_files/session-myIGaccount'
    loader = instaloader.Instaloader()
    loader.load_session_from_file(username=USER, filename=SESSION_FILENAME)
    profile = instaloader.Profile.from_username(L.context, USER)


    choices = {'stories': True,
               'posts': False,
               'profile_pic': True,
               'raise_errors': True}
    selected_profile = instaloader.Profile.from_username(
        loader.context, selected_user)
    profiles = {selected_profile}
    loader.save_metadata = False
    loader.dirname_pattern = './downloads/{target}'
    loader.compress_json = False
    loader.post_metadata_txt_pattern = ''
    loader.storyitem_metadata_txt_pattern = ''
    loader.download_profiles(profiles, **choices)
```

**Expected behavior**
All stories should be downloaded from the selected user profile

**Error messages and tracebacks**
No errors are generated

**Instaloader version**
`instaloader --version` output is 4.9

**Additional context**

**Comment by aandergr** [comment]
Works for me.

**Comment by Muditjain13** [comment]
Was not working for me either then used -s instead of --stories
