### ISSUE TITLE
How to add new lines in `--post-metadata-txt` parameter

### ISSUE THREAD

**Issue by victoryy2003** [instaloader/instaloader#1478]
```
--post-metadata-txt={typename}\nPosted at {date_utc:%-d%b%Y%-I:%M:%S %p}\nBy {profile}\nOwner ID {owner_id}\nShortCode {shortcode}\nMedia ID{mediaid}\n\n{caption}\n\n{likes} likes\n{comments} comments
```

I'm using `\n` as a add new line indicator, I don't know what is the correct method, can somebody gives me suggestions?

**Comment by aandergr** [comment]
https://instaloader.github.io/basic-usage.html#metadata-text-files

> Specifying these options multiple times results in output having multiple lines, in the order they were given to Instaloader.
