### ISSUE TITLE
how to download just video?

### ISSUE THREAD

**Issue by imanbahmani** [instaloader/instaloader#148]
how to download just video? 

I want to just download video?! but I don't know which syntax using for this!

**Comment by nagualcode** [comment]
Hello, I have a somewhat similar question, I will add here to avoid opening another issue:
- How to download just stories ?
Thank you.

**Comment by aandergr** [comment]
> how to download just video?

`--post-filter=is_video`, which is explained here: https://instaloader.github.io/basic-usage.html#filter-posts.

> How to download just stories ?

`--stories-only`, which is explained here: https://instaloader.github.io/cli-options.html#cmdoption-stories-only and in the `instaloader --help` output.
