### ISSUE TITLE
File Not Founded!

### ISSUE THREAD

**Issue by loverboyXD** [instaloader/instaloader#1490]
Hello Devs 
I had Getting Issue in Login to get session file Which Gets Solved By this code ~ https://instaloader.github.io/troubleshooting.html#login-error

but i am not able to find where that session file is saved? it Gives me path but it doesn't exist 
CODE output Gives: ![image](https://user-images.githubusercontent.com/79841865/163207838-d77edadb-a9e9-4e6b-80be-d3f1dcea6652.png)

When i try to find it: 
![image](https://user-images.githubusercontent.com/79841865/163208350-df8fbe42-791f-4cb3-896f-0913583848a6.png)

How can i give Custom path to save this session file?

**Comment by Showmaster3000** [comment]
the last part of the output `session-mesterious-person` ist the filename of the session. So the part before `C:\Users\...\instaloader\` is the full path.
