### ISSUE TITLE
Examples of how to use --login

### ISSUE THREAD

**Issue by jeffreylm** [instaloader/instaloader#1491]
Hello Everyone,

I have been reading the help file and I can see what a function will do, but there is no example of how to use it. For instance the --login function. Can someone write an example of how you actually use it?

Thank you in advance,
Jeffrey

**Comment by ussaohelcim** [comment]
`instaloader --login username`
After that you will be asked to insert your password.

**Comment by hadzb** [comment]
after the `--login yourusername` add `-p yourpassword` 
if it gives you a link, go to chrome and login through that link, once your logged in, re-run the code
