### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by canh** [instaloader/instaloader#1493]
There are a bunch of[ unofficial instaloader docker images](https://hub.docker.com/search?q=instaloader) on Docker hub, but afaik no official image. Thus, people want to run instaloader under docker/kubernetes must either make their own image or pick one of those unofficial ones which might not always come with the latest version.

**Provide us a use case of the feature**

If a user needs or wants to run instaloader in a container for whatever reason, they can use the official docker image. For example,

`docker run --rm -v $(pwd):/out instaloader/instaloader --latest-stamps apple zuck`

This will also enable users to schedule instaloader as a [CronJob under kubernetes](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/).

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes

**Comment by javiermunooz** [comment]
This sounds like a great idea!

**Comment by aandergr** [comment]
Yes, this is a great idea. The image could be also updated automatically with each release in our "Publish Packages" Github Action. How can we help you with this?

**Comment by canh** [comment]
Thanks @aandergr I think setting up a docker hub account for instaloader is all I need from you. I can work on the Dockerfile and Github Action on my own fork and send a PR once everything is working. Then you feed dockerhub credentials into GitHub secrets and that's it.

**Comment by aandergr** [comment]
I think we should aim to participate in the [Docker "Offical Images" program](https://docs.docker.com/docker-hub/official_images/). Would you also be willing to go through the process of proposing an "Official" Instaloader image?

**Comment by AriESQ** [comment]
Still a good idea
