### ISSUE TITLE
Content count separator in sidecar posts

### ISSUE THREAD

**Issue by SpL1Ne** [instaloader/instaloader#1495]
Hi. Is there a possibility to change separator between filename and content count that added when post has 2+ items in it?
I mean change `_1`, `_2`, `_3` etc to `~1`,`~2` or `@1`,`@2` or something like that using build exe from releases section.

**Comment by aandergr** [comment]
Hi. This separation character cannot be changed using the CLI.

**Comment by SpL1Ne** [comment]
Should I recreate issue for feature request?
Because we can't rely on post id length because I found at least 10 chars length for old posts and now it's 11 chars. I guess It will be 12 chars in near future. Also I had post which end on `_{digit}` and then there was `_{digit}` from content number in post.

**Comment by aandergr** [comment]
What are you trying to achieve?

You could still use the JSON file saved along with the post to determine whether it is a sidecar.

**Comment by SpL1Ne** [comment]
> What are you trying to achieve?
To have possibility to split filename to account\data\post id\content number if there more than one in post.
For now we can't do that because separator is '_' and also post id can have '_' in it.

**Comment by aandergr** [comment]
I am not so convinced of the use of such a feature. Does that have any further goal? Which problem would it solve? How do you currently solve that problem without the possibility to split filename to account\data\post id\content number?

**Comment by SpL1Ne** [comment]
> Which problem would it solve?
Inconsistent in filenames, as I said. 
> How do you currently solve that problem without the possibility to split filename to account\data\post id\content number?
Download post into folder with post code, then split filenames by folder name (i.e by post code) and then replace '_' in second part from split if there anything left.

> Does that have any further goal?
Well. There were posts with 10 symbols in post code that I downloaded.
And, I believe there will be 12 symbols codes in near future. And now, for post with code `qwerty1234` app will download files `qwerty1234_1.jpg` and `qwerty1234_2.jpg`. When there will be 12-symbols code you can't tell difference between `qwerty1234_1` for `qwerty1234` post and one filename for post with `qwerty1234_1` and qwerty1234_2` codes.

I general app shouldn't use separator\split symbol from post code symbols set.

**Comment by SpL1Ne** [comment]
I'm still interested in changing separator.
But you can close issue if you won't do that.

**Comment by iWajdi** [comment]
me too, I need that seperator to be changed; I also use this naming sceme but it's not what I hoped for `--filename-pattern="{profile} {date_utc:%Y-%m-%d %H.%M.%S} {mediaid}_{owner_id} - {shortcode}` hoping to mimic 4K Stogram naming scheme, but when I download a sidecar post that {mediaid} prints the same code across all the posts which results in the _1 _2 _3 _4 _5 seperators. Meanwhile in 4K Stogram the sidecar posts prints a unique code for each photo or video within that sidecar so I don't get the seperators part.
