### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by oren** [instaloader/instaloader#1497]
**Describe the bug**
I can't login

**To Reproduce**
instaloader --login xxx -p xxx

i see a link. i click on it and sign in to IG in my browser. i run the login command again and get the same link. 

**Expected behavior**
log me in after the second time i enter the --login command

**Error messages and tracebacks**

**Instaloader version**
4.9

**Additional context**
ubuntu on chrome in incognito mode

**Comment by Showmaster3000** [comment]
Your description lacks of an error message/output. the link you see is maybe a challenge link.
Logging in with browser does not say that you can then login with instaloader afterwards.
Maybe you try this: https://instaloader.github.io/troubleshooting.html#login-error

**Comment by oren** [comment]
there are no errors or output beyond what I wrote. I'll look into your link. thank you!
