### ISSUE TITLE
[question] tracking down ghost followers

### ISSUE THREAD

**Issue by nikartz** [instaloader/instaloader#150]
This is a continuation of #120 but also kind of a new question.
First of all thanks to everybody helping me with my questions in #120 especially to @Thammus and @aandergr 

I now use the given approach, but wanted to only output profiles, that follow more accounts than a certain amount. For example: only output profiles, that are following me and also more than 2000 other profiles. This is what I got so far and it seems to work:

```
import instaloader
from datetime import datetime, timedelta
from itertools import takewhile
import time

NOW = datetime.now()

L = instaloader.Instaloader()

USER = 'username'
PASSWORD = 'password'
PROFILE = 'profile_that_should_be_checked'

DAYS = 365 #number of days that the script looks at. e.g. all posts in the last 365 days
MAX_FOLLOW_NUMBER = 2000 #maximum of other accounts a profile can follow

L.login(USER, PASSWORD)

profile = instaloader.Profile.from_username(L.context, PROFILE)

print('Fetching followers of profile {}.'.format(profile.username))
followers = set(profile.get_followers())

time.sleep(6000) #so that there isn't too many requests

likes = set()
print('Fetching likes of all posts of profile {}.'.format(profile.username))

for post in takewhile(lambda p: NOW - p.date < timedelta(DAYS), profile.get_posts()):
    print(post)
    time.sleep(180)
    likes = likes | set(post.get_likes())


ghosts = followers - likes


small_accounts = set()
for ghost in ghosts:
	checkprofile = ghost.username
	profile_to_check = instaloader.Profile.from_username(L.context, checkprofile)
	profile_to_check_followers = set(profile_to_check.get_followees())
	if len(profile_to_check_followers) < MAX_FOLLOW_NUMBER:
		small_accounts = small_accounts | set(checkprofile)

final_ghosts = ghosts - small_accounts

print('Storing ghosts into file.')
with open('path/to/store/files/ghosts_instaloader.txt', 'w') as f:
    for ghost in ghosts:
        print(ghost.username, file=f)

print('Storing final_ghosts into file.')
with open('path/to/store/files/final_ghosts_instaloader.txt', 'w') as f:
    for ghost in final_ghosts:
        print(ghost.username, file=f)
```

Most of the work has of course not been done by me, but by [this post](https://github.com/instaloader/instaloader/issues/120#issuecomment-391741189) and [this post](https://github.com/instaloader/instaloader/issues/120#issuecomment-395704135).

As you might already think: this uses lots of requests, because the script needs to get every followee of every profiles that follows me. Even if only 10 people are following me and every profiles follows only a few hundred other profiles: lots of requests.

**Question: better approach?**
So my question: is there a way so return only the number of followees a profiles has without getting every followee? I wasn't able to find something in the code.

**Question: error 429**
Also: I get 429 literally all the time I run the script. My current workaround is to wait double the amount of time, so `time.sleep(2*waittime)` of something like this. As @aandergr already mentioned in [this post](https://github.com/instaloader/instaloader/issues/120#issuecomment-396176813) and in several other thready I am aware of the way the requests are counted, however I am using a dedicated testing-profile, that isn't used for anything else. So it is not logged in at any computer or phone and there are no other scripts running on this profile. If I am right I should not get 429 with this profile. However even with my workaround I geht error 429 all the time. Is there any solution to this?

**Comment by e5150** [comment]
Have a look at the `Profile` class in structures.py, the number of followers, followees, posts and such can be obtained for free via the `followers`, `followees`, `mediacount` properties. (Using `Profile.from_username` is basically like viewing the profile in a browser, you get the basic stats, even for private accounts without having to be logged in.)

```
profile_to_check_followers = set(profile_to_check.get_followees())
if len(profile_to_check_followers) < MAX_FOLLOW_NUMBER:
```

can be replaced by
```
if profile_to_check.followers < MAX_FOLLOW_NUMBER:
```
