### ISSUE TITLE
private downloader does not work

### ISSUE THREAD

**Issue by jesuschirst523** [instaloader/instaloader#1506]
so how do i download private stuff. coz i put the command: instaloader --login xxx [profile name] but it says private but not followed
and it just downloads the propic id and some folder with scripts. but the real questions is how to make instaloader download private stuff without actually you following the account. in the desc it says it can but now i doubt it 
if someone knows plz let me know thanks.

**Comment by Showmaster3000** [comment]
This is NOT possible. You have to be an accepted follower by the profile you want to download.
