### ISSUE TITLE
Method download_post() should return a python object

### ISSUE THREAD

**Issue by lucabinotti** [instaloader/instaloader#1508]
**Provide us a use case of the feature**
I would suggest to replace or add a method as download_post() but that return an object of the post downloaded.

**Describe the solution you'd like**
For example a get_post() method that return an object with the path of all the images/videos downloaded or (if the user has specified to not download) the links of the posts (useful if you use other APIs that don't require to have the media downloaded). The way how it works the download_post() isn't really helpful since that you have to grab by hand the path of images or video that are downloaded. Another problem is that with download_post() the user can't decide what it is needed to download and what it isn't (description, preview of a video, etc.).

**Describe alternatives you've considered**
Currently I'm using the os module for getting the paths of the media downloaded but it's kind of inconvenient, and I don't really need to have the media downloaded, I would prefer to have just the links of the media (seeing the json that return download_post() I guess that could be possible).

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes, if I can

**Comment by aandergr** [comment]
I do not understand your proposal. What do you need – the `Post` object that has been downloaded, the paths on the filesystem that would be created to download a Post, or the links of the media represented by the Post object?
