### ISSUE TITLE
latest_stamps parameter in Python Module

### ISSUE THREAD

**Issue by tmpfx00** [instaloader/instaloader#1509]
Hi everyone! 

Recently I've been using download_profiles() instead of download_profile() since it was deprecated since version 4.1. 

In download_profile(), it would save the profile ID .file into the directory, however with download_profiles() it does not. Thus, username changes are not detected and, the directory is not renamed. I understand that the latest_stamps function saves [profile-ids] but I am unsure how to use the latest_stamps (Optional[LatestStamps]) parameter. Do I need to create a latest-stamps.ini file?

Similarly, I trailed --latest-stamps in the CLI version instead, and it does create a latest-stamps.ini file. However, I'm hesitant to use latest stamps since when a profile rename occurs it does not rename the directory, instead it creates a new one as seen in issue https://github.com/instaloader/instaloader/issues/1276.

Thank you.

```
L = instaloader.Instaloader()

L.download_profiles(profiles=[profile], latest_stamps=None)
```

**Comment by gardn12** [comment]
Can confirm issue #1276 is still an known bug.
