### ISSUE TITLE
[question] inconsistant metadata

### ISSUE THREAD

**Issue by nagualcode** [instaloader/instaloader#151]
I am downloading my :saved posts, and metadata such as username and profile_pic_url is important to me.
But it seems many post's json files are saved without those.
How can I force instaloader to get them?

**Comment by aandergr** [comment]
These JSON files only contain metadata that has been obtained during Instaloader's run. Their structure is as returned by Instagram, which sometimes changes. We cannot guarantee how it is structured, or which fields are saved there. They are mainly intended to be loaded by Instaloader (with `load_structure_from_file()`, and can be given as command line parameter to Instaloader to re-download a post or metadata.

It should be possible to load a JSON with Instaloader and then obtain the profile_pic_url:
```python3
import instaloader
L = instaloader.Instaloader()
P = instaloader.load_structure_from_file(L.context, JSON_FILENAME)
print(P.owner_profile.profile_pic_url)
```

I just pushed commit 7f81985, which allows specifying `--post-metadata-txt={owner_profile.profile_pic_url}`. Then the profile_pic_url would be saved in the text file along with each post, and it would additionally be saved in the JSON as Instaloader is required to obtain that information.

(maybe we should add a flag that instructs Instaloader to obtain all possible metadata structures before it calls `save_structure_to_file()`)
