### ISSUE TITLE
How to get url?

### ISSUE THREAD

**Issue by z8512** [instaloader/instaloader#1510]
Your question here...

How to get url similar to yt-dlp --get-url option?

**Comment by terry-zc** [comment]
One possible solution to build a url with shortcode if you can write scripts... 
"https://www.instagram.com/p/"+post.shortcode+"/"

**Comment by z8512** [comment]
@terry-zc I can't write scripts. I 'm not developer. My school hadn't taught me python

**Comment by MiguelX413** [comment]
> One possible solution to build a url with shortcode if you can write scripts... 
> "https://www.instagram.com/p/"+post.shortcode+"/"

I would recommend f-strings instead btw.

**Comment by MiguelX413** [comment]
> One possible solution to build a url with shortcode if you can write scripts... "[https://www.instagram.com/p/"+post.shortcode+"/](https://www.instagram.com/p/%22+post.shortcode+%22/)"

I recommend using f-strings like
```python
f"https://instagram.com/p/{post.shortcode}/"
```
instead. @terry-zc

**Comment by MiguelX413** [comment]
> @terry-zc I can't write scripts. I 'm not developer. My school hadn't taught me python

What exactly are you trying to do right now?

**Comment by z8512** [comment]
> > @terry-zc I can't write scripts. I 'm not developer. My school hadn't taught me python
> 
> What exactly are you trying to do right now?

I want to get url in easiest way, `instaloader -g https://instagram.com/p/aoqkrjc`
