### ISSUE TITLE
Download single post by Instagram url

### ISSUE THREAD

**Issue by z8512** [instaloader/instaloader#1511]
**Provide us a use case of the feature**
How could the user invoke the new function? Which problem would it solve?
If new information is obtained, how would it be further processed?
` $ instaloader https://www.instagram.com/p/CcszHJ-on3O`
**Describe the solution you'd like**
`Download a single post using the url exactly same as what yt-dlp does`
**Describe alternatives you've considered**
How do you achieve the here-described goal without the feature you are requesting?

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes / No

**Additional context**
Add any other context about the feature request here.

**Comment by Showmaster3000** [comment]
This feature is already implemented. Usage `instaloader -- -XXX` where `XXX` is the code of the element - in your example `CcszHJ-on3O`. Be aware that you need the double dash, space dash before the code
More info see manual: https://instaloader.github.io/basic-usage.html#what-to-download

**Comment by z8512** [comment]
@Showmaster3000 Please I want `instaloader https://www.instagram.com/p/CcszHJ-on3O`

**Comment by z8512** [comment]
I want like yt-dlp
