### ISSUE TITLE
Discrepancies in Reels Video Views Count

### ISSUE THREAD

**Issue by terry-zc** [instaloader/instaloader#1512]
When I retrieve viewcount of a REEL post, I get a number that is lower of the real one that I see on Instagram. This doesn't happen with the normal VIDEO posts, only with REELS. How to get the correct number?
![image](https://user-images.githubusercontent.com/104498558/165497976-9ba2ed23-0ffb-4954-98da-e0ff66c14ef2.png)

Thanks.

**Comment by terry-zc** [comment]
(Only a guess.....) My guess is that the mechanism to count views for reels and common feed video is different. Reels count a view once the Reels start playing.... Instead, views for feed video or IGTV count a view only when a user views the video for more than 3 seconds. Could that be a possible reason for the data discrepancies?

**Comment by terry-zc** [comment]
![image](https://user-images.githubusercontent.com/104498558/165658509-7af3b4b3-39ea-4565-91f4-78aae3620672.png)
![image](https://user-images.githubusercontent.com/104498558/165658539-1adf14ad-bb71-4dc2-a66f-434d097944a7.png)
Please see the data retrieved above.

**Comment by aandergr** [comment]
There is a view count and a play count, they are different measures. The play count cannot be accessed with a Post property, but would be trivial to implement.

**Comment by terry-zc** [comment]
> There is a view count and a play count, they are different measures. The play count cannot be accessed with a Post property, but would be trivial to implement.

Thanks @aandergr , that's helpful. Will there be a future support plan of retrieving play count?  Thanks!

**Comment by aandergr** [comment]
This is a simple feature. Would you be willing to implement it and submit a PR?

**Comment by terry-zc** [comment]
> 

Thanks @aandergr . That could be too difficult for me since I am very new to Python lol. I found it difficult to understand the source code. It would be great if your team could take some time to implement it when you are available. Thanks!
