### ISSUE TITLE
Asks for login, login doesn't change behavior, extremely limited output

### ISSUE THREAD

**Issue by innerchihiro** [instaloader/instaloader#1514]
**Describe the bug**
I'm trying to use instaloader to download specific posts from a list of URLs (not scraping entire profiles or hashtags etc.) I can get maybe a handful of urls downloaded before I'm asked to login (these are public posts, not private). I've gone ahead and logged in and I have a session file, but there's no change to the behavior, it will still ask for the login. If I wait about a day I'll be lucky to download another post or two before it asks for a login. I have no warnings on my instagram account.

**To Reproduce**

instaloader --filename-pattern={owner_username}_{date_utc} --no-video-thumbnails -- -CaoASaDgtPj

**Expected behavior**
I expect this command to download the file with or without login, especially since I'm downloading at such a low volume (maybe 30 posts per day)

**Error messages and tracebacks**
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/?next=/graphql/query
-CbudG9vqB08: Redirected to login page. Use --login.

Errors or warnings occurred:
-CbudG9vqB08: Redirected to login page. Use --login.

**Instaloader version**
`instaloader --version` 4.9.

**Additional context**
MacOS 11.6.1 Intel

I have attempted to troubleshoot this issue with the 615_import_firefox_session.py script on the troubleshooting page and I get this error:

python3 615_import_firefox_session.py
Instaloader not found.
  pip install [--user] instaloader

I have uninstalled and re-installed instaloader with pip3 install instaloader, no changes to behaviour.

**Comment by Showmaster3000** [comment]
your command line does not include the login part, so add `--login XXX` where XXX is your profile name you logged in before. Then you should see an output like `Loaded session from ...\session-XXX.` and `Logged in as XXX.`

**Comment by innerchihiro** [comment]
Oh boy, thanks so much for clarifying that for me! Working now 👍
