### ISSUE TITLE
How do I know if an account with the specified nickname?

### ISSUE THREAD

**Issue by wineSecure** [instaloader/instaloader#1520]
I couldn't find anything about it on the Internet, so I have a question. Does the tool have a nickname verification feature? And if not, it would be nice to add such a feature. So far, I've found a rather strange way of making a request to unload data from an account with an error handler. But it doesn't seem quite right to me.

**Comment by MiguelX413** [comment]
What do you mean by nickname?

**Comment by wineSecure** [comment]
I have a list of users whose stories I would like to receive. But it often happens that users change their Instagram nickname. In that case, an error pops up that breaks all the code. I wrote a handler, but I think it would be nice to have a function inside this tool to check nicknames. To put it simply: there is an account with this nickname or not.

**Comment by MiguelX413** [comment]
> I have a list of users whose stories I would like to receive. But it often happens that users change their Instagram nickname. In that case, an error pops up that breaks all the code. I wrote a handler, but I think it would be nice to have a function inside this tool to check nicknames. To put it simply: there is an account with this nickname or not.

Though it's not a solution it sounds like you'd benefit from using user IDs instead!

**Comment by MiguelX413** [comment]
> I have a list of users whose stories I would like to receive. But it often happens that users change their Instagram nickname. In that case, an error pops up that breaks all the code. I wrote a handler, but I think it would be nice to have a function inside this tool to check nicknames. To put it simply: there is an account with this nickname or not.

Thought it's not an answer to your question I think a solution would be to use User IDs instead!

**Comment by wineSecure** [comment]
Even though it's not the answer to my question, it helped me a lot. Thank you very much! However, it would be nice to have a function to check existing nicknames. Have a great day!
