### ISSUE TITLE
There is no longer need to login for view public content!

### ISSUE THREAD

**Issue by samanmalekian** [instaloader/instaloader#1522]
Instagram policies seem to have changed, in the web version you can view the content of public pages without logging in, it seems that Instaloader should also **change the login step to optionally**.

**Comment by tpeebs** [comment]
Hi, I noticed this, too, but when not logged in it seems that only the first 12 posts can be downloaded by Instaloader

**Comment by Showmaster3000** [comment]
Logging in is already optional, just skip the `--login` parameter. But as mentioned before, you can only download a limited amount of posts until you are forced to login.
