### ISSUE TITLE
Login issue with saved session

### ISSUE THREAD

**Issue by Divetoxx** [instaloader/instaloader#1523]
**Describe the bug**
If I use --login AND I have saved session in C:\Users\User\AppData\Local\Instaloader then I get error.

**To Reproduce**
instaloader --login=myname someprofile

**Expected behavior**
instaloader works as usual.

**Error messages and tracebacks**
Loaded session from C:\Users\User\AppData\Local\Instaloader\session-myname.
Logged in as myname.
JSON Query to someprofile/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to someprofile/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

**Instaloader version**
4.9

**Additional context**
If I delete folder C:\Users\User\AppData\Local\Instaloader and use --login and --password then it works good.

**Comment by MrC0D3** [comment]
Getting the same issue here. I'm trying to work around it and trying a bash script to iterate through one profile at a time, and before instaloader starts, delete the session file then log in with --login and --password.

I'm testing against 10 profiles. This works for the first 8 profiles, then I get another error for the last 2 profiles:
```
Session file does not exist yet - Logging in.
Fatal error: Login error: "fail" status, message "".
```

Here is the bash script if anyone wants to try/report what happens.
```
#!/bin/sh
# backup method to update profile while 'login error by cookie' fails

FILENAME="profiles.txt"
LINES=$(cat $FILENAME)
for LINE in $LINES
do
  echo $LINE
  if [ -f $FILENAME ];
  then
    rm xxx/.config/instaloader/session-xxx
  fi
  instaloader "$LINE" --no-captions --no-profile-pic --no-metadata-json --no-video-thumbnails --fast-update --login=xxx --password xxx
  sleep 5
done
```

**Comment by aandergr** [comment]
This works fine for me. Is there any way to reliable reproduce this error?

**Comment by ekalin** [comment]
I have seen the error described in the original post. I haven't fully isolated it yet, but it seems to happen on "new" logins.

I have a saved session that I've been using for weeks, and this works fine between runs. But if I switch to another user, the first run works fine, and saves the session as expected. But in a next run, even though the session file is loaded and login seems to be successful, I get the `Could not find "window._sharedData" in html response.` error and then `X has changed its name to X` (#1530). Erasing the session file forces a new login and everything starts working again, for that session.

Meanwhile, if I go back to the other user with the older session, the problem never happens.

**Comment by MrC0D3** [comment]
Unfortunately I encountered this issue with my only account, which would generally use an older session cookie. Then I first saw the error, logged out, deleted cookie, logged back in, copied cookie, and I see the error after the first profile.

**Comment by ekalin** [comment]
Now, for whatever reason, the session that used worked stopped working, I had to delete it and log in again. And now it is only good for one use, in subsequent runs this error appears.

So it does not seem related to the user, but to the sessions only. My guess is that new sessions have some different attributes that cause them not to be recognized when loaded from a file.

**Comment by ekalin** [comment]
I've tried creating a session from Firefox's cookies (as described in the documentation), and while it seems to have worked (login was reported as successful), the window._sharedData error happens just the same.

**Comment by BartBruh** [comment]
I'm using Instaloader through the python module and my logins through saved sessions were working fine until yesterday when I started getting the same issue. Session gets loaded but when instaloader tries to create a profile instance of the given profile (@instagram in my example) I get this error:
`JSON Query to instagram/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]`
It works fine if I login directly using the username and password but doing this marks the account as suspicious and severely limits how many actions I can do before getting my account compromised or banned.

Also worth mentioning that when the exception gets raised VSCode Debugger shows me the "ProfileNotExistsException" dialog popup and tells me a few similar profiles that are available. In my test case of trying to get a profile instance of @ instagram it gives me @ instagram itself as a similar existing profile.

I'm using Python 3.10 and Instaloader 4.9

I've seen @Thammus help through a lot of issues so hope they can help with this asap too.
