### ISSUE TITLE
ValueError: check_hostname requires server_hostname

### ISSUE THREAD

**Issue by android0221** [instaloader/instaloader#1524]
I got an error when I started Instaloader with V2Ray.
![微信截图_20220508174700](https://user-images.githubusercontent.com/31181601/167290770-156e4970-7fc7-48f0-83e6-4951132fde0e.png)
![微信截图_20220508171747](https://user-images.githubusercontent.com/31181601/167290771-6d2e5026-c18d-4e92-b2f8-f6f3d9e6e077.png)

**Comment by Showmaster3000** [comment]
And what is your question?
Btw. you didn't anything about your commandline...
