### ISSUE TITLE
#อนิเมะ isn't detected properly.

### ISSUE THREAD

**Issue by MiguelX413** [instaloader/instaloader#1526]
**Describe the bug**
Because #อนิเมะ has combining characters that can't be normalized into composed characters, the current regex fails to capture the hashtag entirely.

**To Reproduce**
Apply the regex to a caption with the hashtag.

**Expected behavior**
'อนิเมะ' should be in the hashtags of the post.

**Instaloader version**
`4.9`

**Comment by aandergr** [comment]
Thanks for reporting!

Similar to #1446 in that it refers to a problem with the regex for hashtags when certain characters are involved.

**Comment by MiguelX413** [comment]
> Thanks for reporting!
> 
> Similar to #1446 in that it refers to a problem with the regex for hashtags when certain characters are involved.

Indeed, it wasn't fixed by #1453 because this hashtag contains conbining characters with no composite equivalent @aandergr
