### ISSUE TITLE
At some point the downloads die for no reason and wont download past a certain point

### ISSUE THREAD

**Issue by MMJv3** [instaloader/instaloader#1529]
any idea how to fix this? i log back in but it still wont download more than like 12

![image](https://user-images.githubusercontent.com/36246145/168195011-7aa50b69-fcbf-4ce1-b8e6-994e1f2a0b5b.png)

**Comment by james16000** [comment]
> any idea how to fix this? i log back in but it still wont download more than like 12
> 
> ![image](https://user-images.githubusercontent.com/36246145/168195011-7aa50b69-fcbf-4ce1-b8e6-994e1f2a0b5b.png)

I am also facing the same problem 
I was previously downloading the complete public profiles without me getting this error now I must log in to download the files This issue should be fixed in the next update

**Comment by Showmaster3000** [comment]
The output message says it all: you have to login to proceed.
Instagram limited anonymous access. Same thing as in #1514 or #1067.

**Comment by james16000** [comment]
> The output message says it all: you have to login to proceed. Instagram limited anonymous access. Same thing as in #1514 or #1067.

Public profiles do not need to be logged in
I don't know why you don't want to allow public profiles to be uploaded without logging in
Login causes account ban Use login only with private accounts
instaloader is a failed tool
What is the use of this tool?
I will look for others

**Comment by MrC0D3** [comment]
> instaloader is a failed tool
> What is the use of this tool?

No one is making you use it, feel free to find another and report back if you find a better alternative that has all the features of Instaloader. Instagram API limits what Instaloader can download anonymously. Try going on a browser without logging in and clicking more than 12 posts, it will redirect you to login.

**Comment by MMJv3** [comment]
thing is when trying to login it never lets me. it always says some shit like “must be in a text file” and i tried that but it didn’t work. idk how to login properly

**Comment by Greenwavemonster** [comment]
> idk how to login properly

Did you try 'instaloader -l <USERNAME>' ? Run it on the promt and it will ask u for your pw. 
Then it will create a session which you can the use in your script with:

    s = instaloader.Instaloader()
    s.load_session_from_file(USERNAME)  # Load the created Session
