### ISSUE TITLE
invalid username

### ISSUE THREAD

**Issue by younes313** [instaloader/instaloader#1533]
**Describe the bug**
i use instaloader version 4.9 and everything was okay until today. but now I am facing with error `instaloader.exceptions.QueryReturnedBadRequestException: 400 Bad Request`
when trying to get profile with username 
`instaloader.Profile.from_username(loader.context, username)`

I am sure that username is valid and was working until today

**Error messages and tracebacks**
`  File "instaloader/structures.py", line 692, in from_username`

`    profile._obtain_metadata()  # to raise ProfileNotExistsException now in case username is invalid
  File "instaloader/structures.py", line 761, in _obtain_metadata
    metadata = self._context.get_json('{}/feed/'.format(self.username), params={})`

`  File "instaloader/instaloadercontext.py", line 345, in get_json
    raise QueryReturnedBadRequestException("400 Bad Request")`

`instaloader.exceptions.QueryReturnedBadRequestException: 400 Bad Request`
**Instaloader version**
4.9

**Comment by aandergr** [comment]
Works for me. Is there a way to reliably reproduce this error?

**Comment by fstarkenberg** [comment]
I also got `400 Bad Request`. When using the app (iPhone) with the same account it asked me for age verification to confirm I'm over 13 years old. After confirming that instaloader started working again.

**Comment by younes313** [comment]
the problem was solved automaticaly after two days!!!
