### ISSUE TITLE
+args.txt => implement comment function to disable arguments

### ISSUE THREAD

**Issue by bachig26** [instaloader/instaloader#1534]
### **Provide us a use case of the feature**
How could the user invoke the new function? 
_add the # before the arguments similar to text editor comment addition._

Which problem would it solve?
_prevent every arguments provided in the args.txt file, this function needed for session case, if needed can be executed or not silent the argument._

### **Describe the solution you'd like**
_add the # before the arguments similar to text editor comment addition._ I'm requesting this because I can add the arguments in one go and can use comment case to disable certain argument for particular run.

### **If the feature request is accepted, would you be willing to submit a pull request?**
Yes, but need an example to work as I'm not an programmer.

**Comment by aandergr** [comment]
Yes, this would be a nice feature!

We use [fromfile_prefix_chars](https://docs.python.org/3/library/argparse.html#fromfile-prefix-chars) for the `+args.txt` feature, hence it may suffice to override [ArgumentParser.convert_arg_line_to_args()](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.convert_arg_line_to_args) to implement this feature.

**Comment by EveryDirection** [comment]
As mentioned in #1625, besides allowing lines to be marked as comments, please also allow blank lines (currently, blank lines will cause an error). Comments and blank lines will make the config files much more readable and editable.

**Comment by Hassibayub** [comment]
Can you elaborate on the feature your requested @bachig26. 

Is anyone working on this feature or should I start?

**Comment by bachig26** [comment]
> Can you elaborate on the feature your requested @bachig26.

_for example_, in **python you use "#"and in js and swift you use "//" to indicate the line as comment.**

this function is not available for executing the argument file (args.txt), because currently even if you add # or // to a line in args.txt, while reading the file, the # or // is also read as a character like a profile name or whatsoever... it doesn't think as --fast-update, because fast update is coded to read.

In this, I want to have a comment condition or function added for argument file, so I can hide the commands or profile from executing while it reads for execution.

please let me know if this clarifies you.

> Is anyone working on this feature or should I start?

I think no one is working on it, as I'm also not good at programming to work this....
I think **help wanted** label needed to be added.

**Comment by Hassibayub** [comment]
Yes, it is all clear what exactly you are requesting. 

I will start working on it.

**Comment by EveryDirection** [comment]
@Hassibayub If you're working on this, an additional important feature, as mentioned above, is to also allow blank lines (currently, blank lines will cause an error).

**Comment by Hassibayub** [comment]
Thank you for pointing this out, @EveryDirection.

One thing you guys can help me with is sharing your dummy `args.txt` file so I can get a better idea of the input files.

@bachig26

**Comment by bachig26** [comment]
> One thing you guys can help me with is sharing your dummy `args.txt` file so I can get a better idea of the input files.

this is my two args.txt file that I use, **one with --fast-update (args_bachfu.txt) and other without --fast-update (args_bach.txt)**:
1. [args_bach.txt](https://github.com/instaloader/instaloader/files/9334010/args_bach.txt)
2. [args_bachfu.txt](https://github.com/instaloader/instaloader/files/9334011/args_bachfu.txt)

**Comment by Hassibayub** [comment]
Requested feature added and pending pull request.

This kind of file now works.
```
<Blankline>
# foo
cristiano
--no-video-thumbnails 
--no-metadata-json 
--no-compress-json # this is test comment 
--no-profile-pic # this is another comment
--dirname-pattern=cristiano 
--count=10

```

**Comment by afterdelight** [comment]
thank you for this, this is what i needed too
