### ISSUE TITLE
JSON QUERY HTTP ERROR 403

### ISSUE THREAD

**Issue by Kerago** [instaloader/instaloader#1539]
**Describe the bug**
It skips the images and i cant fix it!
![image](https://user-images.githubusercontent.com/93339246/169702512-1468523b-1c16-4489-9b74-8261590246b2.png)

**To Reproduce**
instaloader --no-metadata-json --no-compress-json -q -l username-p password profile xbox.pfps

**Expected behavior**
Its supposed to download the pfps from the profile

**Error messages and tracebacks**
JSON Query to api/v1/media/2494076866094536405/info/: HTTP error code 403. Unable to fetch high quality image version of <Post CKcvbIOFZbV>.

**Instaloader version**
`instaloader --version` output.

**Comment by aandergr** [comment]
> **Instaloader version**
> `instaloader --version` output.

Works for me, with the newest version.

**Comment by aandergr** [comment]
Closing, as version is missing.
