### ISSUE TITLE
HTTP 403, API ban?

### ISSUE THREAD

**Issue by Greenwavemonster** [instaloader/instaloader#1545]
Hey

First of, yes I have read some other issues concering the 403 problem but I have a diffrent question.

Is it possible to be "banned" from using the API after to much usage? (not the Too many request) 

 ### Problem: 
Im working on a scraper (not on GitHub atm) and it is supposed to download images from account set on a list. 
I have set breaks in between to avoid a "Too many Requests" (After 200 rounds it waits 1h). Last week, this worked good for about two rounds when the requests suddenly increased (idk why). (Start: Wait 1h, download, wait, download, wait, download + fail 403 + Too many req.)

Today i started the same script again but instantly got the 403 unable to fetch high qualitly [...]  After creating a new session with a new acc (two weeks old, never used w/ instaloader) the same happend after +/- 50 downloads...

Also going on my phone, instagram logged me out from this new accounts. No "sus" warning, just logged out. (It did the same with the other account last week). 

 ### Conclusion ?

So, any ideas to whether im just stupid or the API "blacklisted" me? Anyone else just beeing auto loged out?

Thanks, Greenwave

<sup><sup>sry for my bad english </sup></sup>

**Comment by MrC0D3** [comment]
I'm also seeing the 403 error after downloading a few profiles with --fast-update (also about 50 posts). But I am having to start a new session for each profile as I describe in https://github.com/instaloader/instaloader/issues/1523#issuecomment-1127159892. 

Also seeing account logout after the 403; after logging back in, SMS confirmation is required which I have completed. I am going to retry after several hours but I am thinking the same issue will occur unfortunately...

**Comment by stevesbrain** [comment]
Yeah I downloaded approx 25 posts before I was banned entirely :/

**Comment by Greenwavemonster** [comment]
> I'm also seeing the 403 error after downloading a few profiles with --fast-update (also about 50 posts). But I am having to start a new session for each profile as I describe in [#1523 (comment)](https://github.com/instaloader/instaloader/issues/1523#issuecomment-1127159892).
> 
> Also seeing account logout after the 403; after logging back in, SMS confirmation is required which I have completed. I am going to retry after several hours but I am thinking the same issue will occur unfortunately...

So you are suggesting i should try and create a new session for each time I want to download something? Isn't that a but sus, say loggin in 100 times in one hour?

**Comment by Greenwavemonster** [comment]
> Yeah I downloaded approx 25 posts before I was banned entirely :/

wdy by that? They terminated your account?

**Comment by stevesbrain** [comment]
Instagram did yeah
