### ISSUE TITLE
Automatic loading of default parameters from config directory

### ISSUE THREAD

**Issue by ziemek99** [instaloader/instaloader#1549]
**Provide us a use case of the feature**
User creates a file under a hard-coded name (e.g. `default.txt` or `config.txt`) inside Instaloader's config directory (`~/.config/instaloader/` on Linux) and enters here default parameters.

**Describe the solution you'd like**
Default parameters are loaded automatically.

**Describe alternatives you've considered**
Currently I use a file with a one-letter filename (`a`) inside current working directory, so I have to type `+a` as a part of every command.

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes

**Comment by aandergr** [comment]
I do not see a need for this feature.

As a convenient alternative to passing `+a` every call, you could define an alias in your `.bashrc`, like
```sh
alias instaloader='instaloader +~/.config/instaloader/default'
```

**Comment by ziemek99** [comment]
> I do not see a need for this feature.
> 
> As a convenient alternative to passing `+a` every call, you could define an alias in your `.bashrc`, like
> 
> ```shell
> alias instaloader='instaloader +~/.config/instaloader/default'
> ```

Okay, that actually might be a solution. Feel free to close the issue now or later if it gets stale with no one else submitting another feedback.
