### ISSUE TITLE
python syntax for target / dirname_pattern, filename_pattern

### ISSUE THREAD

**Issue by MazrimT** [instaloader/instaloader#1550]
I can't seem to get the hang of the dirname_pattern and/or target of the download_storyitem functions in python.
I'm on windows and don't know if this is causing the issue or not.

I'm trying to achieve that highlights goes into subfolders:
```
for highlight in L.get_highlights(user=profile.userid):
    for item in highlight.get_items():
            L.download_storyitem(item, target=f"highlights/{highlight.owner_username}/{highlight.title}")
```

What ends up happening is that a folder actually called "highlights / username / title" is created, instead of a subfolder structure.
I've tried backslash and forward slash in different configurations but doesn't seem to want to work.
I've tried playing around with dirname_patterns when calling Instaloader() but whatever I put just ends up as the directory name.. so I get a directory actually called "{profile}" for example.

I thought it might have to do with the _PostPathFormatter class replacing strings, but after commenting out all the replace() stuff it's still making a single dir with a long name instead of subdirs.

also saw/tried variations where you make an string from os.path.join("highlights", "username", "title") but same thing just happens.

Anyone have any examples of what the syntax of "target=" should be in download_storyitem ?

**Comment by MazrimT** [comment]
also saw/tried variations where you make an string from os.path.join("highlights", "username", "title") but same thing just happens.

**Comment by fireattack** [comment]
The way it works is kinda confusing I'd admit especially when directly called as a Python module, but you are supposed to manipulate `dirname_pattern` and  `filename_pattern` of your Instaloader instance, instead of changing `target`. It just happens that the default `dirname_pattern` is `{target}`.

So, the correct way to do is:

```python
for highlight in L.get_highlights(user=profile.userid):
    for item in highlight.get_items():
        L.dirname_pattern = f'highlights/{highlight.owner_username}'
        L.filename_pattern = f'{highlight.title}'
        L.download_storyitem(item, target='') # target doesn't matter, but it's required so just pass in empty string.
```
