### ISSUE TITLE
Resume download with --count argument

### ISSUE THREAD

**Issue by userqq** [instaloader/instaloader#1551]
Hi guys, I'm trying to redownload archive of my favourites from instagram, which is about 8500 posts now.
Such attempts are blocked by instagram and after 200 posts each time I getting notice with password reset.
Also this could be a problem when i get more than 200 posts between instaloader runs.

I noticed, if I start instaloader, wait untill it download ~150 posts, hit Ctrl+C, then I can resume download after few hours, download 150 posts more and repeat untill I get all my archive. But manually handle such case is very exhausting.

Is there any possibility to combine resumable downloads with --count argument, to be able run instaloader in cron periodically and download large sets of posts by chunks. Currently --count just download %n posts starting from the latest and next run it will not resume previous download, starting from the latest post again.

**Comment by ImjuzCY** [comment]
I think this would be a useful thing for CLI. Currently the only way to achieve this is with a Python script with `instaloader` module

**Comment by aandergr** [comment]
The CLI does not do that; however, this would be trivial with a custom script; see https://instaloader.github.io/as-module.html
