### ISSUE TITLE
Private Story Likes: Addding method for downloading users who liked your story

### ISSUE THREAD

**Issue by bipsen** [instaloader/instaloader#1552]
**Provide us a use case of the feature**
In February 2022, Instagram added the "Private Story Likes" feature, enabling users to like each other's stories. These likes are private, but it is possible for the recipient to see a list of usernames who have liked their particular story in the Instagram App. I propose the feature to download the users who have liked a user's own story. 

**Describe the solution you'd like**
I propose a method, ".get_likes()", added to the user story item class (StoryItem). It would work like the post.get_likes() method.

**Describe alternatives you've considered**
Currently, Instaloader does not have a way to do this that I am aware of.

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes.

**Comment by aandergr** [comment]
Yes, this feature would be nice to have!
