### ISSUE TITLE
Add Facebook login to passwordless Instagram accounts

### ISSUE THREAD

**Issue by ziemek99** [instaloader/instaloader#1554]
**Provide us a use case of the feature**
Some Instagram accounts don't have passwords at all because you have to login via Facebook. Right now you can only use them with Instaloader via cookie file extracted from a full-blown browser since `--password` fails due to... well, lack of password.

**Describe the solution you'd like**
`--facebook` option, not taking any arguments and requiring `--login`, that allows you to login to an Instagram account via Facebook, including support of their 2FA mechanisms (6-digit code or waiting for confirmation in another logged-in Facebook instance).

**Describe alternatives you've considered**
As described above, browser-generated cookie files are currently the only way to use passwordless Instagram accounts.

**If the feature request is accepted, would you be willing to submit a pull request?**
Unfortunately no, this stuff is way too advanced for me atm 😞

**Additional context**
Using cookies becomes more and more problematic because of #1553, #1530 and #1523. Logging in again and reimporting new cookies from a browser isn't an option since many of us want to automate Instaloader, e.g. via cron.

**Comment by aandergr** [comment]
Thanks for this suggestion!

I agree that it would be nice to have the option to support the Facebook login and I would be very happy to review a pull request for this.
