### ISSUE TITLE
Could not find "window._sharedData"

### ISSUE THREAD

**Issue by jmiguelf** [instaloader/instaloader#1559]
Version: 4.9
cmd usage: ./instaloader.py  --login myuser_name --stories  --fast-update demo_user
results:
Logged in as myuser_name.
JSON Query to demo_user/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to demo_user/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
^C[skipped by user]

**Comment by Showmaster3000** [comment]
Duplicate of #1553.
