### ISSUE TITLE
Download restored posts, but don't load posts that are already downloaded

### ISSUE THREAD

**Issue by ImjuzCY** [instaloader/instaloader#1562]
**Provide us a use case of the feature**
For example, `--include-restored`, to be used when downloading profiles or saved posts. 

Currently, if `--latest-stamps` or `--fast-update` is not provided, Instaloader will load all posts (every shortcode is loaded) individually, although previously downloaded posts are not overwritten. This will cause a lot of requests to Instagram and cause frequent `429: Too many requests`.

If `--latest-stamps` or `--fast-update` is provided, Instaloader will stop upon encountering an existing post or date. But there might be older posts that are dated older than the latest downloaded post, and Instaloader will not see that because it has already stopped before the iteration has arrived at the restored post.

**Describe the solution you'd like**
After getting the list of saved posts, before loading each individual post for downloading, compare the posts (shortcodes?) to the files that have already been downloaded. If the shortcode `n` has already been downloaded, skip the post and go to the next (`n+1`) without loading post `n`. Iterate this until the list ends.

**Describe alternatives you've considered**
`--latest-stamps` or `--fast-update`  stops downloading when a downloaded post is encountered. But there might be a restored post below that has not been downloaded yet.

I have also written a script with Python that does exactly what I described above, but after the recent API change the script is now broken. I can share the script for reference if needed.

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes, but my current proficiency of Python does not allow me to write the necessary codes to do it. It might take ages for me to learn to write the code. 

**Additional context**
Refer to #1385 . That issue describes the problem.

**Comment by fireattack** [comment]
> Instaloader will load all posts (every shortcode is loaded) individually, although previously downloaded posts are not overwritten. This will cause a lot of requests to Instagram and cause frequent 429: Too many requests.

Correct me if I'm wrong, but from what I get by briefly reading the code, Instaloader already check existing files before trying to "load" the post. It only uses the info that is already present by listing posts so there is no extra request. 

If you can help spot where these extra requests come from it would be helpful.

**Comment by ImjuzCY** [comment]
It seems that you're right. I forgot how I came to the conclusion last time that posts are loaded even if downloaded, which is not true. It was my mistake.
