### ISSUE TITLE
Got 520 error using proxies in Instaloader

### ISSUE THREAD

**Issue by AnonC0DER** [instaloader/instaloader#1563]
Hi, I want to use proxies in Instaloader to prevent **429 error**. But when I set the proxy using the below function, I get **520 error**.

Function :
```python
def SwitchProxy():
    '''This function switch proxy'''
    # Set verify=False
    os.environ['CURL_CA_BUNDLE'] = ''
    os.environ['HTTP_PROXY'] = 'I use proxycrawl.com smartproxy '
    os.environ['HTTPS_PROXY'] = 'I use proxycrawl.com smartproxy'
```
I'm not sure if the problem is the smart proxies or not, but I didn't get a 520 error when I simply requested to Instagram using this proxy and the below code.
```python
import requests
import os

url = 'https://instagram.com/accounts/login'

os.environ['CURL_CA_BUNDLE'] = ''
os.environ['HTTP_PROXY'] = 'I use proxycrawl.com smartproxy'
os.environ['HTTPS_PROXY'] = 'I use proxycrawl.com smartproxy'

req = requests.get(url)
print(req.text)
```
Full error :
```python
JSONDecodeError                           Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/instaloader/instaloadercontext.py](https://localhost:8080/#) in login(self, user, passwd)
    224         try:
--> 225             resp_json = login.json()
    226         except json.decoder.JSONDecodeError as err:

6 frames
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

ConnectionException                       Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/instaloader/instaloadercontext.py](https://localhost:8080/#) in login(self, user, passwd)
    227             raise ConnectionException(
    228                 "Login error: JSON decode fail, {} - {}.".format(login.status_code, login.reason)
--> 229             ) from err
    230         if resp_json.get('two_factor_required'):
    231             two_factor_session = copy_session(session, self.request_timeout)

ConnectionException: Login error: JSON decode fail, 520 - .
```

Does anyone have a solution?

**Comment by AnonC0DER** [comment]
I've just found an answer for my issue.
Right now, you can't use proxycrawl.com to scrape Instagram.
You should use other proxy services such as webshare.

**Comment by zakrian07** [comment]
there is no way to verify ssl false or add pem file in cert bundle
os.environ['HTTPS_PROXY'] = 'http://myproxy:22225'
https://requests.readthedocs.io/en/latest/user/advanced/#proxies
from requests.utils import DEFAULT_CA_BUNDLE_PATH
print(DEFAULT_CA_BUNDLE_PATH)
You override this default certificate bundle by setting the REQUESTS_CA_BUNDLE (or CURL_CA_BUNDLE) environment variable to another file path:

$ export REQUESTS_CA_BUNDLE="/usr/local/myproxy_info/cacert.pem"
$ export https_proxy="http://10.10.1.10:1080"

$ python
>>> import requests
>>> requests.get('https://example.org')   this is not working can you add to verify ssl or i can give path of my pem file in library for each method?
