### ISSUE TITLE
download into existing folder without creating a new one within it

### ISSUE THREAD

**Issue by EibeGrabung1** [instaloader/instaloader#1564]
Hi there! I was wondering if there is a way to tell instaloader to not create a new folder when downloading from a profile. I would like my downloaded posts all to be in the same folder without any folders within. any help would be highly appreciated!

thank you in advance!

**Comment by Showmaster3000** [comment]
Did you check the parameter `--dirname-pattern`?
See manual: https://instaloader.github.io/basic-usage.html#filename-specification

**Comment by EibeGrabung1** [comment]
> Did you check the parameter `--dirname-pattern`? See manual: https://instaloader.github.io/basic-usage.html#filename-specification

Hi there, thanks for your comment! yeah I have read into that, but since I am very new to coding and there wasnt a example online, I wasnt able to implement it.

**Comment by fireattack** [comment]
Use `--dirname-pattern="."` to download directly to the current folder without creating subfolder.

**Comment by EibeGrabung1** [comment]
> Use `--dirname-pattern="."` to download directly to the current folder without creating subfolder.
> 
> Or use absolute path, like `--dirname-pattern="D:\myinsta"`

Hi, thank you! could i do the same to name the files after the instagam caption?

**Comment by EibeGrabung1** [comment]
> Use `--filename-pattern`. Check the doc for the details.

will do thank you!
