### ISSUE TITLE
Filename Specification?

### ISSUE THREAD

**Issue by j57123** [instaloader/instaloader#1566]
hi
How do I set file names while downloading posts reels videos tagged stories highlights
It means the target username + the code for the photo or video everything?
Example **`instagram - Cc8HKM8jQpi`** With the addition of **`-`**
I read this and didn't know how to do it
https://instaloader.github.io/basic-usage.html#filename-specification
Use cmd version 4.9

**Comment by harislapo** [comment]
Add --filename-pattern="{profile}_{filename}". This will output **username_1111_1111_1111_1111_n**

**Comment by Showmaster3000** [comment]
I think `--filename-pattern="{profile} - {shortcode}"` is more the string @j57123 wants...

**Comment by Showmaster3000** [comment]
for profile image add the parameter [--title-pattern=...](https://instaloader.github.io/cli-options.html#cmdoption-title-pattern) as described in the manual. But you can't use `shortcode` here because these images don't have it.

**Comment by SpL1Ne** [comment]
> @Showmaster3000 what's the difference between them **`{target}`** and **`{profile}`**
> Would anything change if I used either of these?

If you will try to download this post [Ceep5tzJdBu](https://www.instagram.com/p/Ceep5tzJdBu/) by providing shortcode, that target will be `Ceep5tzJdBu`, profile will be `Microsoft`.
If you will try to download tagget posts from microsoft profile than for first post in tagget section ([this post](https://www.instagram.com/p/Bq-mLEfHhIV/) for now) target will be `Microsoft` and profile `maxroeck`.
Target is what you provide in command. Profile is account name for each downloaded post.
