### ISSUE TITLE
Could not find "window._sharedData" in html response

### ISSUE THREAD

**Issue by Georgetanny** [instaloader/instaloader#1569]
**Describe the bug**
login with no issue

**To Reproduce**
(e.g. Instaloader command line)
instaloader --login username--no-captions --no-metadata-json profiletodownload -s --no-posts
**Expected behavior**
A clear and concise description of what you expected to happen (even if it seems obvious).
downloading of photos etc
**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.
Logged in as username.
JSON Query to profiletodownload/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to profiletodownload/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Profile profiletodownloaddoes not exist.
The most similar profiles are: profiletodownload,
Trying again anonymously, helps in case you are just blocked.
**Instaloader version**
`instaloader --version` output.
4.9
**Additional context**

**Comment by faiblesse2** [comment]
> Duplicate of #1553.

Any idea when the patch is going live

**Comment by Showmaster3000** [comment]
> Any idea when the patch is going live
New release 4.9.1 is published.
