### ISSUE TITLE
Story download half broken with 4.0.6

### ISSUE THREAD

**Issue by gituzzer** [instaloader/instaloader#157]
Got 3 accounts downloading data using the same procedure as follows:

python3 /home/blablabla/instaloader.py -l USER -p PASSWORD @USER --no-captions --fast-update --stories-only --filename-pattern={date} --no-profile-pic --no-metadata-json

Account 1 with 180 followees downloads stories fine.
Account 2 with 300 followees fails with following error, right at the start, after showing all followees:
...
Downloading stories
JSON Query to graphql/query: HTTP error code 431. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 431. [retrying; skip with ^C]
Download stories: JSON Query to graphql/query: HTTP error code 431.
Saved session to /tmp/.instaloader-USER/session-USER.

Errors occured:
Download stories: JSON Query to graphql/query: HTTP error code 431.
Sat Aug  4 23:07:11 WEST 2018
$
$

Account 2 with 3K followees fails with following error, right at the start, after showing all followees:
...
Downloading stories
JSON Query to graphql/query: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)) [retrying; skip with ^C]
JSON Query to graphql/query: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)) [retrying; skip with ^C]
Download stories: JSON Query to graphql/query: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Saved session to /tmp/.instaloader-USER/session-USER.

Errors occured:
Download stories: JSON Query to graphql/query: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
$
$
$

Reverting back to 4.0.5, starts to download stories again, but ofc, a lot of stories are missed ( USER XXXX does not have any stories) wrongly.

I can provide more info/logs if required.
Keep up the GREAT work.

**Comment by e5150** [comment]
This is somewhat related to #153, but the main issue I think is that with "too many" followees the request for their stories is too large (HTTP 431) for instagram's servers to handle. You ought to, rather than `@user --stories-only`,  use the `:stories` target, which will download all currently visible stories, without downloading the list of followees first.

**Comment by aandergr** [comment]
Thanks @gituzzer for reporting, and @e5150 for fixing `:stories`!

I just released 4.0.7 with the `:stories` fix and a fix for this particular issue included (however, almost 4 hours after sunrise, time I needed for testing and fixing another bug).

The latter error, `JSON Query to graphql/query: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))` has already been reported in #134, I hope it is fixed as well.
