### ISSUE TITLE
concatenate ig stories

### ISSUE THREAD

**Issue by jinthoa** [instaloader/instaloader#1572]
Hello, 

Is it possible to concatenate all IG stories into one single media at download ?

Here's my current command line: 

`instaloader.exe +args.txt --no-video-thumbnails --no-metadata-json --no-captions --stories-only --dirname-pattern C:\IGTEST --profile thedrewbarrymoreshow`

Also is there a way to not download profile pic with my command ? 

Thanks !

**Comment by Jon8RFC** [comment]
--no-profile-pic

**Comment by jinthoa** [comment]
> --no-profile-pic

Thank you! Nothing on concatenate ?
