### ISSUE TITLE
Stories really slow since update!!

### ISSUE THREAD

**Issue by LaticePrime** [instaloader/instaloader#1575]
**Describe the bug**
Downloading of stories suddenly much slower since update

**To Reproduce**
L.download stories([profiles])

**Expected behavior**
To download really fast with no errors

**Error messages and tracebacks**
Also now getting 'Too Many Queries in the last time' followed by 18 minute wait which NEVER got before with stories

**Instaloader version**
4.9.1

**Additional context**
This isn't a bug as such because it is working just WAY slower than before the update plus now throwing 'Too Many Queries in the last time' which it NEVER DOES with stories usually. Consequently a download of 500 profiles stories which would normally take about 30 minutes will now take about 5 hours.

UPDATE: finally got error 400 and account locked for the first time ever downloading stories.

IMPORTANT!!! I just reverted back to the previous version of instaloader from a backup and it worked again like a charm! 500 profiles stories in 25 minutes! I even used the same account that instagram has just blocked and there were no Too Many Queries errors or 400 bad requests. 

This is important because it seems the latest update exposes accounts to being flagged for suspicious activity whilst downloading stories. I've been using this account since 2019 to download stories and the first time it got blocked was today. Reverted back to previous version and fast download, no errors, no block, no problem!

**Comment by notBradPitt** [comment]
Which version did you revert to exactly? I hadn't updated mine in like a year and was getting window sharedData error before the update which fixed the issues, but I want to avoid getting my account flagged

**Comment by LaticePrime** [comment]
I have reverted back to version 4.7.5

Obviously this throws the window shared data error, but ONLY when scraping posts while logged in: I don't log in while scraping posts because I only do the first 10 ever few days

The scraping of stories has worked perfectly for years at high speed without triggering suspicious activity or rate limits

**Comment by LaticePrime** [comment]
Maybe switch it back from the iPhone json for stories only but leave it for posts as it's worked brilliantly for years and would be a shame to lose that functionality
