### ISSUE TITLE
Could not find "window._sharedData" in html response.

### ISSUE THREAD

**Issue by kleajmp** [instaloader/instaloader#1577]
**Describe the bug**
Have to delete my session data and re enter my password on every download command. 

**To Reproduce**
Z:\Instaloader>instaloader --login myusername profile_to_download -F --stories --highlights --tagged
Loaded session from C:\Users\myusername\AppData\Local\Instaloader\session-myusername.
Logged in as myusername.
JSON Query to profile_to_download/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to profile_to_download/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Trying to find profile profile_to_download using its unique ID 6854829704.

**Expected behavior**
I expect my download starts without this error using my saved session data. 

**Error messages and tracebacks**
JSON Query to profile_to_download/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Trying to find profile profile_to_download using its unique ID 6854829704.

**Workaround**
I tested it on several computers (all with Windows 10) and all have the same issue everywhere. The only workaround I've found is **deleting my session** data [`C:\Users\username\AppData\Local\Instaloader\*`] before every download command and re entering your password, which works but is really annoying.

**Instaloader version**
4.9

Does anyone have a real (permanent) solution for this problem?
Thanks in advance.

**Comment by joshuajbrunner** [comment]
I'm running into this issue as well. I usually just grab stories. But even deleting my session and logging back in doesnt fix it.
I'm on linux. Been happening for the past few days. I was on version 4.7.x before, updated to 4.9 and still same issue

**Comment by christoarmani** [comment]
I had a similar issue. Did you try to update to 4.9.1? I think the issue has been fixed.

**Comment by joshuajbrunner** [comment]
> I had a similar issue. Did you try to update to 4.9.1? I think the issue has been fixed.

Ah, that seems to have fixed it for me.

**Comment by kleajmp** [comment]
> I had a similar issue. Did you try to update to 4.9.1? I think the issue has been fixed.

Yes that fixed the problem for me too. Thanks a lot for the simple solution :)

**Comment by uvx0ol** [comment]
Stll have the same issue on 4.9.1

**Comment by Lrnvrybthksa** [comment]
I was on version 4.8 and this happened, just upgraded and now it's working, thanks

**Comment by Lrnvrybthksa** [comment]
> I was on version 4.8 and this happened, just upgraded and now it's working, thanks

**Comment by Lrnvrybthksa** [comment]
> I had a similar issue. Did you try to update to 4.9.1? I think the issue has been fixed.

I was on version 4.8 and this happened, just updated and now it's working, thanks

**Comment by imraxy** [comment]
I changed the function to 

def get_shared_data(html):
    #print(html)
    match = re.search(r'XIGSharedData.*?.*?:("{.*?})', html)
    matchJ = match.group(1) + '}"'
    #print(json.loads(json.loads(matchJ))['config']['csrf_token'])
    return json.loads(json.loads(matchJ))
