### ISSUE TITLE
Resuming Download From Specific Number

### ISSUE THREAD

**Issue by belthsazarliem** [instaloader/instaloader#1578]
Excuse me. I just recently started using Instaloader to download a bunch of tutorials. And I'm very grateful for the works you've done.

The thing is, the profiles I'm downloading from usually have posts (and thus, pictures and videos) numbering in hundreds or thousands.
And after some tens or several hundreds, the download stopped. I assume this is the bot protection (or something) from Instagram to prevent DDOS (or something)

My question is, can I use Instaloader to resume download from the last stopped one? As you can see from this screenshot below, it stopped at (262/6456). Can I resume download from 262/6456? If so, how? I dug around the docs and didn't find anything mentioning this particular situation.

Thank you

![loader](https://user-images.githubusercontent.com/10377688/173169617-665285bc-157e-4615-ab63-8bbac5c26fff.PNG)

**Comment by belthsazarliem** [comment]
no response. I assume you are busy squishing the bugs

**Comment by neodimx** [comment]
The only workaround is to manually delete the previously downloaded posts; Instagram has introduced post selection to faster the process.
