### ISSUE TITLE
Instagram responded with HTTP error "429 - Too Many Requests".

### ISSUE THREAD

**Issue by android0221** [instaloader/instaloader#1580]
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/?next=/graphql/query
JSON Query to graphql/query: Redirected to login [retrying; skip with ^C]
Number of requests within last 10/11/20/22/30/60 minutes grouped by type:
 * XXXXXXXXXXXXXXXXXXXXXXXXXX:    1    1    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 664 seconds, at 20:22.
instaloader version:4.9.1

**Comment by iWajdi** [comment]
Force close your instagram app on your phone, close the instagram tab on your browser, and just wait few seconds, or a minute and re-try.

**Comment by android0221** [comment]
> instagram

I haven't opened instagram on my phone and browser, still the same problem.

**Comment by android0221** [comment]
> 强制关闭手机上的 Instagram 应用程序，关闭浏览器上的 Instagram 选项卡，然后等待几秒钟或一分钟，然后重试。

I haven't opened instagram on my phone and browser, still the same problem.

**Comment by android0221** [comment]
> Force close your instagram app on your phone, close the instagram tab on your browser, and just wait few seconds, or a minute and re-try.

I haven't opened instagram on my phone and browser, still the same problem.

**Comment by Showmaster3000** [comment]
You missed important things like your commandline/code you run. So we can't say much about your problem.
anyhow, some infos in the manual: https://instaloader.github.io/troubleshooting.html#too-many-requests

**Comment by bipsen** [comment]
I am also experiencing exceptional 429 errors, mainly when using the `get_likes` method. I have a setup that is usually very stable with several isolated web connections and Instagram profiles, but currently, I get an immediate 429 whenever I try to harvest likes.  I am very carefully following the too-many-requests instructions, and normally do not have problems, so it seems to me something has changed. 

My code looks likes this:

```
import instaloader

L = instaloader.Instaloader()
L.load_session_from_file('username')
post = instaloader.Post.from_shortcode(L.context, 'CeqpDjnvQyR')

# This runs fine.
L.download_post(post, 'target')  

# This errors.
for l in post.get_likes():
    print(l)
```

Error message:

```
JSON Query to graphql/query: 429 Too Many Requests [retrying; skip with ^C]
Number of requests within last 10/11/20/22/30/60 minutes grouped by type:
   2b0673e0dc4580674a88d426fe00ea90:    1    1    1    1    1    1
 * 1cb6ec562846122743b61e492c85999f:    1    1    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 666 seconds, at 12:05.
```

**Comment by w298102526** [comment]
i also 429, then i add time.sleep(random.randint(18,22)) to solving 429 error ,but download post very low , about 1 hours 100+ post,how can i do to fast download
code like this:
```
SINCE = datetime.datetime(1900, 8, 30)
UNTIL = datetime.datetime(2020, 4, 20)
L = instaloader.Instaloader(download_videos=False)
L.load_session_from_file("user")
posts = instaloader.Profile.from_username(L.context,insuser).get_posts()
#today = datetime.datetime.today()
#SINCE = today - datetime.timedelta(days=1)  # further from today, inclusive
print('ready post')
for post in posts:
    if UNTIL > post.date > SINCE:
        try:
            postn  = Post.from_shortcode(L.context,post.shortcode)
            L.download_post(postn,insuser)
            time.sleep(random.randint(18,22))
        except:
            print('error but continue')
```
