### ISSUE TITLE
Make the ordering of the returned iterator of 'Profile.get_posts()' be chronological

### ISSUE THREAD

**Issue by 1155159410** [instaloader/instaloader#1582]
About a week ago, Instagram announced a new function, _'Pin to profile'_. (reference: https://twitter.com/instagram/status/1534227704802729985)

Before this function was announced, the returned iterator of `Profile.get_posts()` is always in chronological order (from most recent to oldest). But now, if there are pinned posts in the profile, the iterator will no longer always be in chronological order.

Chronological ordering is helpful when we want to update the downloaded profile. We can stop iterating when the post's date is earlier than the latest downloaded one. For example:
```
latest_date_local = datetime.fromisoformat("2022-06-11T18:09:22+08:00")  # assume this datetime is the datetime of newest downloaded post
posts = instaloader.Profile(instaloader_.context, "username").get_posts()
for post in posts:
    if post.date_local <= latest_date_local:
        break  # stop iterating
    else:
        ... # download the post
```
But the above implementation way does not work now since the iterator may not be in chronological order (when there are pinned posts in the profile).

There is an easy way to order the `Post` nodes chronologically, but the overhead is really large. When there are many posts in the profile, it costs lots of time, and easily causes `'Too Many Requests'` errors. Here is the implementation way:
```
posts = instaloader.Profile(instaloader_.context, "username").get_posts()
posts = sorted(posts, key=lambda _: _.date_local, reverse=True)
```
Therefore, I would like to ask, if there is any better way to solve the _posts pinning problem_, that causes the returned iterator of `Profile.get_posts()` not be in chronological order.

**Comment by 1155159410** [comment]
> Is there anything in the post json that indicates it's a pinned post? If so, pinned posts could be ignored in the `post.date_local <= latest_date_local` comparison.

I have tried to use `get_json_structure()` to inspect the json of `Profile` and `Post`, to find sth like `num_of_pinned_posts` (profile class) or `is_pinned` (post class). But seems there is no such related key.

May I suggest adding _class property_ such as, `pinned_count: int` in `Profile` class or `is_pinned: bool` in `Post` class if feasible.

**Comment by hardestus** [comment]
> Is there anything in the post json that indicates it's a pinned post? If so, pinned posts could be ignored in the `post.date_local <= latest_date_local` comparison.

Yes. "pinned_for_users" contains the user's details if the post is pinned and it is empty if not.

**Comment by 1155159410** [comment]
> > Is there anything in the post json that indicates it's a pinned post? If so, pinned posts could be ignored in the `post.date_local <= latest_date_local` comparison.
> 
> Yes. "pinned_for_users" contains the user's details if the post is pinned and it is empty if not.

Oh, thank you! I missed it, sorry.

**Comment by 1155159410** [comment]
> > Is there anything in the post json that indicates it's a pinned post? If so, pinned posts could be ignored in the `post.date_local <= latest_date_local` comparison.
> 
> Yes. "pinned_for_users" contains the user's details if the post is pinned and it is empty if not.

May I ask how to get the value of `pinned_for_users`?
I have try the method below:
```
post_json = instaloader.get_json_structure(post)
post_json['node']['pinned_for_users']
```
But I got a _KeyError_.

**Comment by ekalin** [comment]
Can you provide a profile with pinned posts so we can test?

**Comment by 1155159410** [comment]
> Can you provide a profile with pinned posts so we can test?

NP, here is one example: https://www.instagram.com/mosseri/



> > > Is there anything in the post json that indicates it's a pinned post? If so, pinned posts could be ignored in the `post.date_local <= latest_date_local` comparison.
> > 
> > 
> > Yes. "pinned_for_users" contains the user's details if the post is pinned and it is empty if not.
> 
> May I ask how to get the value of `pinned_for_users`? I have try the method below:
> 
> ```
> post_json = instaloader.get_json_structure(post)
> post_json['node']['pinned_for_users']
> ```
> 
> But I got a _KeyError_.

BTW, I can now use my above-mentioned way to get the value of `pinned_for_users`. I cannot reproduce the problem again. But it is good, since I can use `pinned_for_users` to identify if a post is pinned and skip it to make `get_posts()` iterator be in chronological order.

**Comment by 1155159410** [comment]
Maybe I would close this _Issue_ thread first, since there is already _Pull_ working on this chronological ordering issue. Thanks!
