### ISSUE TITLE
Skip pinned posts

### ISSUE THREAD

**Issue by hardestus** [instaloader/instaloader#1584]
When "--fast-update" is used and the first post is already downloaded, the process stops. Sometimes, the first post is not the most recent one since instagram allows about three posts to be pinned.

The downloading process should continue, even if the pinned posts are downloaded, until it finds an already-downloaded regular post.

Otherwise, you could miss some posts thinking you are up to date. In that case, you will need to omit "--fast-update" option and download all posts whenever you think you missed some.

Thanks

**Comment by nzec** [comment]
Related to #1582
