### ISSUE TITLE
Error when downloading Hashtags: `Expecting value: line 1 column 1 (char 0)`

### ISSUE THREAD

**Issue by rayamberg** [instaloader/instaloader#1588]
**Describe the bug**
Hashtags not found when using session

**To Reproduce**
```
$ instaloader -l rayamberg "#lisaandrewsartist"
Loaded session from /home/rsa/.config/instaloader/session-rayamberg.
Logged in as rayamberg.
JSON Query to explore/tags/lisaandrewsartist/: Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]
JSON Query to explore/tags/lisaandrewsartist/: Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]
Get hashtag #lisaandrewsartist: JSON Query to explore/tags/lisaandrewsartist/: Expecting value: line 1 column 1 (char 0)
Saved session to /home/rsa/.config/instaloader/session-rayamberg.

Errors or warnings occurred:
Get hashtag #lisaandrewsartist: JSON Query to explore/tags/lisaandrewsartist/: Expecting value: line 1 column 1 (char 0)
```

**Expected behavior**
I expected to be able to download the posts for the given hashtag. Note that it works when I supply the password directly to instaloader:
```
$ instaloader -l rayamberg -p ****** "#lisaandrewsartist"
Session file does not exist yet - Logging in.
Logged in as rayamberg.
#lisaandrewsartist/2022-04-20_06-34-03_UTC_profile_pic.jpg 
Retrieving pictures with hashtag #lisaandrewsartist...
[  1] #lisaandrewsartist/2022-04-20_06-42-39_UTC.jpg [Meet the Artist Lisa Andrews …] json 
[  2] #lisaandrewsartist/2022-04-20_06-42-33_UTC.jpg [Meet the Artist Lisa Andrews …] json 
[  3] #lisaandrewsartist/2022-04-20_06-37-47_UTC.jpg [We love this painting of Swee…] json 
...
Saved session to /home/rsa/.config/instaloader/session-rayamberg.
$
```

**Error messages and tracebacks**
See traceback above

**Instaloader version**
`4.9.1`

**Additional context**
It's happening for all hashtags I am testing. They all return posts when I don't use a session and return the JSON Query error when I do use a session. I can download other things when I use a session, e.g. `instaloader -l rayamberg someprofile` works.  I'm writing a python script and getting the same unexpected behavior when I use `load_session_from_file("rayamberg")` and expected behavior when I use `login("rayamberg", "mypass")`. I used the Firefox script on the troubleshooting page to try to resolve the issue, and although it appeared to successfully import the session, the issue persists.

**Comment by fwkhan** [comment]
Hi,

I am getting the same error, it used to work just fine earlier.

HASHTAG:  dubai
JSON Query to explore/tags/shutelbitdown/: Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]
JSON Query to explore/tags/shutelbitdown/: Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]
06/16/2022 11:17:15 AM - Internal Server Error: /api/fetch_insta_new_posts
Traceback (most recent call last):
lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 370, in get_json
    resp_json = resp.json()
lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
lib/python3.9/json/__init__.py", line 346, in loads    return _default_decoder.decode(s)
lib/python3.9/json/decoder.py", line 337, in decode     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib/python3.9/json/decoder.py", line 355, in raw_decode    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by rayamberg** [comment]
I no longer achieve expected behavior when I input the password directly:

```
instaloader -l rayamberg -p **** "#lisaandrewsartist"
Session file does not exist yet - Logging in.
Logged in as rayamberg.
JSON Query to explore/tags/lisaandrewsartist/: Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]
JSON Query to explore/tags/lisaandrewsartist/: Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]
Get hashtag #lisaandrewsartist: JSON Query to explore/tags/lisaandrewsartist/: Expecting value: line 1 column 1 (char 0)
Saved session to /home/rsa/.config/instaloader/session-rayamberg.

Errors or warnings occurred:
Get hashtag #lisaandrewsartist: JSON Query to explore/tags/lisaandrewsartist/: Expecting value: line 1 column 1 (char 0)
```

**Comment by JoeGarcia2** [comment]
I'mam having the same problem.

**Comment by Professor-Carlos** [comment]
Got the same issue, any luck with how can we fix it? thanks heaps

**Comment by coticoticotty** [comment]
I got same issue when i use "Hashtag.from_name".
My code and Error Message are here.

```download_from_instagram.py
import instaloader

L = instaloader.Instaloader()
L.login(USER, PASSWORD)
for post in instaloader.Hashtag.from_name(L.context, 'cat').get_posts():
    L.download_post(post, target='#cat')
```

Error
> JSON Query to explore/tags/cat/: Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]
> JSON Query to explore/tags/cat/: Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]
> Traceback (most recent call last):
>   File "C:\Users\Kohei Okamoto\anaconda3\envs\face_recognition\lib\site-packages\requests\models.py", line 972, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "C:\Users\Kohei Okamoto\anaconda3\envs\face_recognition\lib\json\__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "C:\Users\Kohei Okamoto\anaconda3\envs\face_recognition\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "C:\Users\Kohei Okamoto\anaconda3\envs\face_recognition\lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by aru12** [comment]
I have same problem.

I use instaloader version is 4.9.2.

The error message is the same as yours.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 370, in get_json
    resp_json = resp.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/myusername/instapy/get_hash_tag_posts.py", line 14, in <module>
    posts = L.get_posts_by_hash_tags(search_hash_tag)
  File "/home/myusername/instapy/insta_loader.py", line 25, in get_posts_by_hash_tags
    hashtag = instaloader.Hashtag.from_name(self.loader.context, hashtag)
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 1506, in from_name
    hashtag._obtain_metadata()
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 1520, in _obtain_metadata
    self._node = self._query({"__a": 1})
  File "/usr/local/lib/python3.10/dist-packages/instaloader/structures.py", line 1515, in _query
    json_response = self._context.get_json("explore/tags/{0}/".format(self.name), params)
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 394, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 394, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/usr/local/lib/python3.10/dist-packages/instaloader/instaloadercontext.py", line 384, in get_json
    raise ConnectionException(error_string) from err
```

Any thoughts or solutions?

thx.

**Comment by Thammus** [comment]
Thanks for the bug report. I was able to reproduce the error. It actually appears both when using an existing session and when using a fresh login.

**Comment by YMALOT** [comment]
I'm having the same issue. I investigated a bit, I hope this helps:
It seems it comes from the `get_json` method of the `InstaLoaderContext` class, so I compared the behaviour of this method when calling `Profile.from_username` vs. when calling `Hashtag.from_name`. The result I see differs on line 325 in `instaloadercontext.py`, that is:
`resp = sess.get('https://{0}/{1}'.format(host, path), params=params, allow_redirects=False)`

In the first case when calling `Profile.from_username` in my main code, the line mentioned above yields a `requests.models.Response` object whose content is well formatted, so that calling `resp_json = resp.json()` on line 370 of the same file works fine. When calling `Hashtag.from_name`, the same request result returns a `Response` object whose content is the html code of the page, which cannot be processed correctly and crashes when calling `resp_json = resp.json()` on line 370.

**Comment by kuahhx** [comment]
Same, im getting the html in my resp and it crashes. Any clues or any details on fixes?

**Comment by jamesdidit72** [comment]
> Worked fine on yester day, now encountered silimar issues with error: `JSON Query to explore/tags/{hashtag}/: [Errno Expecting value]`

What did you change? Or did it just stop working

**Comment by leunglong0123** [comment]
> What did you change? Or did it just stop working

It just stop working today, I didn't change anything,  below is the code.
```python
  L = Instaloader()
  L.login(username, password)
  hashtag = Hashtag.from_name(L.context, 'football')
  post_iterator = hashtag.get_posts_resumable()
  post = next(post_iterator)
  L.download_post(post, 'football_post')
```

**Comment by aru12** [comment]
Is there any chance to fix it?

**Comment by giovsta** [comment]
Yeah this issue is insane that has been like this for so long

**Comment by lyndonnixon** [comment]
Also waiting on a fix or a workaround.
If HTML is now being returned in place of JSON, couldn't the HTML be scraped?

**Comment by agavili** [comment]
I am also waiting for this to be fixed

**Comment by agavili** [comment]
I am still getting this error after upgrading the version of instaloader I have.  This is the error I am getting: ConnectionException: JSON Query to explore/tags/win/: Expecting value: line 1 column 1 (char 0)

my code:
`HASHTAG = "win"
hashtag = Hashtag.from_name(L.context, HASHTAG)`

**Comment by roccopietrini** [comment]
@agavili are you sure you are using the latest version of instaloader (4.9.5)? I just tried the following and works:

    from instaloader import Instaloader, Hashtag
    
    username = <user>
    password = <password>    
    L = Instaloader()
    L.login(username, password)
    hashtag = Hashtag.from_name(L.context, 'football')
    post_iterator = hashtag.get_posts_resumable()
    post = next(post_iterator)
    L.download_post(post, '#football')

**Comment by incomer** [comment]
I get this error too, after a couple of posts (it looks like it is randomly)

**Comment by agavili** [comment]
yeah like if i want to iterate through all the top posts for a hashtag i get a connection exception.  Not sure if I have to constantly login in a loop? How would I be able to iterate through all posts for a certain hashtag, can you go through the iterator without just using next()?

**Comment by IL2C** [comment]
@agavili @incomer #1751

**Comment by SingSIvetim** [comment]
Does someone fix it now i cant download anything yet! hopeful gonna get on it very soon! thank you so much for your hard work!
