### ISSUE TITLE
Found an error in Hashtag

### ISSUE THREAD

**Issue by sajaddadgar** [instaloader/instaloader#1589]
Tried using a hashtag to download some posts, but it gives the following error.
It is worked fine for getting posts from a profile. Also, it worked fine for Hashtags yesterday, 
I also checked the documentation, but I still couldn't download any posts.
I tried other objects, but I can't fix it just for Hashtags.

Am I just getting this error, or is it a new bug?

`JSONDecodeError                           Traceback (most recent call last)
c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\instaloader\instaloadercontext.py in get_json(self, path, params, host, session, _attempt)
    369             else:
--> 370                 resp_json = resp.json()
    371             if 'status' in resp_json and resp_json['status'] != "ok":

c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\requests\models.py in json(self, **kwargs)
    899                     pass
--> 900         return complexjson.loads(self.text, **kwargs)
    901 

c:\users\lenovo\appdata\local\programs\python\python37\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:

c:\users\lenovo\appdata\local\programs\python\python37\lib\json\decoder.py in decode(self, s, _w)
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()

c:\users\lenovo\appdata\local\programs\python\python37\lib\json\decoder.py in raw_decode(self, s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

ConnectionException                       Traceback (most recent call last)
<ipython-input-5-7dd2ff0c21f8> in <module>
      1 # L = instaloader.Instaloader()
----> 2 hashtag = instaloader.Hashtag.from_name(L.context, 'mercedesbenz')
      3 post_iterator = hashtag.get_posts()
      4 with instaloader.resumable_iteration(
      5         context=L.context,

c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\instaloader\structures.py in from_name(cls, context, name)
   1468         # pylint:disable=protected-access
   1469         hashtag = cls(context, {'name': name.lower()})
-> 1470         hashtag._obtain_metadata()
   1471         return hashtag
   1472 

c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\instaloader\structures.py in _obtain_metadata(self)
   1482     def _obtain_metadata(self):
   1483         if not self._has_full_metadata:
-> 1484             self._node = self._query({"__a": 1})
   1485             self._has_full_metadata = True
   1486 

c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\instaloader\structures.py in _query(self, params)
   1477 
   1478     def _query(self, params):
-> 1479         json_response = self._context.get_json("explore/tags/{0}/".format(self.name), params)
   1480         return json_response["graphql"]["hashtag"] if "graphql" in json_response else json_response["data"]
   1481 

c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\instaloader\instaloadercontext.py in get_json(self, path, params, host, session, _attempt)
    392                     if is_other_query:
    393                         self._rate_controller.handle_429('other')
--> 394                 return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
    395             except KeyboardInterrupt:
    396                 self.error("[skipped by user]", repeat_at_end=False)

c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\instaloader\instaloadercontext.py in get_json(self, path, params, host, session, _attempt)
    392                     if is_other_query:
    393                         self._rate_controller.handle_429('other')
--> 394                 return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
    395             except KeyboardInterrupt:
    396                 self.error("[skipped by user]", repeat_at_end=False)

c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\instaloader\instaloadercontext.py in get_json(self, path, params, host, session, _attempt)
    382                     raise QueryReturnedNotFoundException(error_string) from err
    383                 else:
--> 384                     raise ConnectionException(error_string) from err
    385             self.error(error_string + " [retrying; skip with ^C]", repeat_at_end=False)
    386             try:

ConnectionException: JSON Query to explore/tags/mercedesbenz/: Expecting value: line 1 column 1 (char 0)`

**Comment by XordK** [comment]
Exact same issue here. Cannot get anything using instaloader.Hashtag.from_name

**Comment by Showmaster3000** [comment]
What is the difference betwen #1588 an yours? Looks like duplicate for me...
