### ISSUE TITLE
Download pictures only from post (Instaloader Module)

### ISSUE THREAD

**Issue by music-lover99** [instaloader/instaloader#1590]
**WHAT I'M DOING:**
So I'm trying to go through through a profile post by post while only downloading the pictures. 

**MY PROBLEM:**
I don't know how to ONLY download pictures from a post. Currently my code downloads pictures, the caption, and a json file. Plus, if my script runs into a Reel, it downloads the first frame for some reason. I'd like to only download pictures.

Any help would be greatly appreciated, since I was having trouble finding how to do this via the module (documentation showed a way to do it via command-line).

**MY CODE:**
```
#Main variables
USER = 'instagram_account'
PASSWORD = open(PASSWORD_TEXTFILE, "r").read()
VALID_FILE_TYPES = ['.jpg', '.jpeg', '.png']
PROFILE = 'girls'

#Login to Instagram
L = Instaloader()
L.login(USER, PASSWORD)

#Set profile and attributes
profile = Profile.from_username(L.context, PROFILE).get_posts()
L.download_pictures = True
L.download_comments = False
L.download_geotags = False
L.download_videos = False

chdir(r'C:\Users\music\Downloads\instagram')
counter = 0
for post in profile:
    if counter < 10:
        sleep((rand(10,15)/rand(2,4))*(rand(80,120)/100))
        L.download_post(post, PROFILE)
        counter = counter + 1
    else:
        break
```

**Comment by fireattack** [comment]
Use `L.save_metadata = False` to turn off metadata downloading.

Use `L.download_video_thumbnails = Flase` to turn off video thumbnail downloading.

**Comment by fwkhan** [comment]
Try this:
post_url = "https://www.instagram.com/p/"+post.shortcode
L.download_pic(f'static/{user}/{post.date_utc}', post.url, post.date_utc)

this will download single post specific picture
