### ISSUE TITLE
Downloading posts by hashtag from a profile

### ISSUE THREAD

**Issue by Josephinelse** [instaloader/instaloader#1594]
Hello, 

I'm trying to use InstaLoader to download posts from three specific Instagram accounts, I'd like to download the posts based if they include a specific example. For example, downloading posts from WWF's Instagram if the post is associated with "#Biodiversity". 

I'm currently able to do the two separately but wondered if there's a way to filter post downloads by hashtag? Alternatively, by caption wording would also be great. 

Thank you!

**Comment by aandergr** [comment]
Please have a look at the documentation: https://instaloader.github.io/basic-usage.html#filter-posts
