### ISSUE TITLE
JSON Query: 404 Not Found preventing continuation of loop

### ISSUE THREAD

**Issue by Kal-Toh** [instaloader/instaloader#1596]
I've written some code using instaloader to run hashtag counts on various Instagram accounts from an xlxs doc.

However, some of these accounts have a '.' in the username which a hashtag cannot. When this happens I receive the following error: python JSON Query to explore/tags/xxxxx/: 404 Not Found [retrying; skip with ^C]

This itself is fine and to be expected, I added the following if statement to try to remove the '.' from the tag and rerun it:

if "." in htag:
            htag2 = htag.replace('.', '')
            print(htag2)
            h = Hashtag.from_name(l.context, htag2)
            print(h.mediacount)
            sheet.cell(cell.row, col7).value = h.mediacount

Unfortunately instead of continuing onto the 'if "." in htag:' it skips and returns to the top of the loop and moves onto the next tag in the doc.

**Minimal, Reproducible Example:**

from instaloader import Hashtag, Instaloader
htag = "python.hub"
l = Instaloader()

print(htag)
h = Hashtag.from_name(l.context, htag)
print(h.mediacount)
if "." in htag:
    htag2 = htag.replace('.', '')
    print(htag2)
    h = Hashtag.from_name(l.context, htag2)
    print(h.mediacount)

**Comment by aandergr** [comment]
This is not an appropriate place to seek basic Python programming help. As already indicated in the issue template, we unfortunately do not have the necessary capacity for that.
