### ISSUE TITLE
Proxy support 

### ISSUE THREAD

**Issue by fwkhan** [instaloader/instaloader#1597]
Hi,

Is it possible to add proxy support for instaloader?

Thanks,
FK

**Comment by aandergr** [comment]
Instaloader supports proxies.

**Comment by makako-dev** [comment]
@aandergr I do not see how to use proxies on the docs. If there are any docs, can you point me where? Thanks!

**Comment by aandergr** [comment]
It follows the widely used convention of having proxies set via environment variables `HTTPS_PROXY`.

https://requests.readthedocs.io/en/latest/user/advanced/#proxies
