### ISSUE TITLE
Not able to download currently-visible stories of my followees

### ISSUE THREAD

**Issue by ShubhVaishnav** [instaloader/instaloader#1599]
**Describe the bug**
When I try to download all stories from all my followers, it shows me an HTTP error 560, which was working fine till yesterday.

**To Reproduce**
instaloader --filename-pattern='{profile}_{date_utc}' --login= username --fast-update --no-video-thumbnails --no-metadata-json --no-compress-json :stories

**Expected behavior**
download all my followers' stories

**Error messages and tracebacks**
Logged in as "username".
Retrieving all visible stories...
JSON Query to graphql/query: HTTP error code 560. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 560. [retrying; skip with ^C]
:stories: JSON Query to graphql/query: HTTP error code 560.
Saved session to "username session"

Errors or warnings occurred:
:stories: JSON Query to graphql/query: HTTP error code 560.

**Instaloader version**
4.9.1

**Comment by pueptastisch** [comment]
same with latest version 4.9.1 and also older version 4.7.5 (used as a workaround for #1575)

is there a way to download stories (i.e. get HQ story post media URLs) without accessing profiles first?

**Comment by thariq-nugrohotomo** [comment]
I got the same error yesterday, but now the error disappears and I can download stories as usual.

**Comment by kandayo** [comment]
This kind of error is usually a problem on Instagram's end.

The GraphQL query used to fetch stories was timing out or returning a server error yesterday. For me, changing the code to execute the stories query for each user instead of doing it in batches temporarily solved the issue. It pretty much confirms it was instability on Instagram's end.

**Comment by ShubhVaishnav** [comment]
Hey, now its working totally fine without raising any issues. It must have been problem with Instagram's side. Thanks.
