### ISSUE TITLE
Can I pull who is mentioned in a story or story text?

### ISSUE THREAD

**Issue by mvibert88** [instaloader/instaloader#1600]
Is the text written on a story and mentions included in the StoryItem class? Is there a way I can extract just the mentions or text from a story? 

Thanks

**Comment by ShubhVaishnav** [comment]
Yes, If you download the metadata of StoryIteam ( .json.xz file) and then search through it, there will be one attribute "tappable_objects" and you can find the **_username_** and _**full name**_. 

It will be something like `"tappable_objects":[{"__typename":"GraphTappableMention","x":0.766702320031161,"y":0.290679397209822,"width":0.15329453253219602,"height":0.019888166601669,"rotation":0.0,"custom_title":null,"attribution":null,**"username":"abcxyz","full_name":"ABC XYZ"**,"is_private":true}],`   so from there you can find out who is mentioned in the story. 

Not sure about the text written on a story though.
