### ISSUE TITLE
Download Reels

### ISSUE THREAD

**Issue by applehong5013** [instaloader/instaloader#1602]
Hi, I wish to add feature to download the **Reels** portion.

**Comment by Showmaster3000** [comment]
Duplicate of #1195 and #812, but both are currently closed.

**Comment by anuraag488** [comment]
Isn't this already possible?

**Comment by 1155159410** [comment]
I also would like to suggest this feature, and here is the reason for me:

Generally, there can be 5 categories of posts in a profile: **Posts**, **Reels**, **Videos**, **Saved**, **Tagged**.
For the other 4, we have `get_posts()`, `get_igtv_posts()`, `get_saved_posts()` and `get_tagged_posts()` respectively.
But currently, there is no instance method to get URLs of **Reels**.

Therefore I would like to suggest adding a method to the `Profile` class for getting URLs of **Reels**, and also a target `--reels` for command-line users.

**Comment by aandergr** [comment]
Duplicate of #812
