### ISSUE TITLE
Download highlights doesn't respect provided dirname-pattern

### ISSUE THREAD

**Issue by SergeySypalo** [instaloader/instaloader#1608]
**Describe the bug**
When downloading highlight's --dirname-pattern is not respected, a folder with instagram username is created inside specified in --dirname-pattern directory and highlights downloaded there

**To Reproduce**
instaloader username1 --login=MyLogin --password=MyStrongP@ssword --no-metadata-json --no-profile-pic --no-captions --latest-stamps --stories --no-video-thumbnails --highlights --dirname-pattern "D:\Insta\Firstname Lastname"

**Expected behavior**
Highlight should be downloaded to the dirname-pattern specified directory, instead of (in my case):
D:\Insta\Firstname Lastname\username1

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

**Instaloader version**
4.9.1

**Comment by fireattack** [comment]
It doesn't save the highlight stories to the wrong folder, only the cover. 

To fix it, manually assign `--title-pattern {date_utc}_UTC_{typename}`.

The reason behind it, in case you care, is that the default filename pattern for highlight items (actual stories) is `filenmae_pattern` which defaults to `{date_utc}_UTC`, while the filename for the highlight cover is `title_pattern` which will become `{target}_{date_utc}_UTC_{typename}` if you your `dirname_pattern` does not contain `{target}`, which is the case here. 

Here the `{target}`is `{profile}/{highlight_name}` so it would always create a sub folder (also add highlight name to the front of the file). 

The whole filename_pattern, dirname_pattern, target and how the recursively substitute each is really a mess and needs major refractor IMO.

**Comment by SergeySypalo** [comment]
Ah, gotcha, just confirmed, really only cover is stored in the highlight folder, I can leave with it. I don't really want to change default naming conventions to don't break something and because I already have some data downloaded, but thanks for the suggestions and explanations.
