### ISSUE TITLE
use --post-filter= to get post containing certain words

### ISSUE THREAD

**Issue by PandoricGalaxy** [instaloader/instaloader#1611]
Basically what i want to do is use --post-filter=<keyword> or any way to download images from specific post contaning the keyword from a specific user
rn what i am using

`instaloader --dirname-pattern={profile} --filename-pattern={profile} --no-profile-pic --no-metadata-json --no-compress-json --no-captions --no-videos <username> --latest-stamps latest-stamps.ini`

**Comment by Showmaster3000** [comment]
`--filename-pattern={profile}` is a really bad idea cause every file you download will get the same name which is the profile.
The question is: where do you expect the keyword?
maybe its `--post-filter="'foo' in caption"` you want to use.

**Comment by PandoricGalaxy** [comment]
Yeah actually thanks!Also i did this since i wanted just 1 name since i download the file and use in other code. I just need 1 name since only 1 file will be download due to --latest-stamps
