### ISSUE TITLE
Exit codes when unable to successfully complete?

### ISSUE THREAD

**Issue by ItsABlackScreen** [instaloader/instaloader#1614]
When instaloader fails to download due to a too many requests error, then the exit code of instaloader is still zero, rather than an error code. I do have --abort-on=302,400,429 in my arguments.
Since i run instaloader as a cronjob, i rely on the exit code to pop a notification indicating if the job was successful, but it just always shows the job as successful as the return code is always 0.
Is there any way to change that, so that there is a non-zero return code on a 302,400,429 error?

**Comment by aandergr** [comment]
Instaloader does not provide a way to configure how the exit code to be returned is determined.
