### ISSUE TITLE
Instaloader downloads older highlights then in latest-stamps

### ISSUE THREAD

**Issue by SergeySypalo** [instaloader/instaloader#1615]
**Describe the bug**
I'm using instaloader with --latest-stamps parameter, so I downloaded a profile with everything (posts, stories, highlights, igtvs), cleaned up photos/videos from the disk, and re-run instaloader with the same parameters, but it started to download photos/videos from highlights dated 2021, while in latest-timestamps.ini latest synchronized for this profile May 2022 

**To Reproduce**
instaloader user_profile --login=my_login --password=my_pass --stories --highlights --tagged --igtv --no-metadata-json --no-profile-pic --no-captions --no-video-thumbnails --latest-stamps --dirname-pattern "D:\test"

**Expected behavior**
As stated in documentation, I should be able remove some old posts and instaloader should download it again with --latest-stamps option

**Instaloader version**
4.9.2

**Comment by Showmaster3000** [comment]
Your description is mixing things. The title says stories have a problem, the description talks about highlights. These are slightly different things.
Refering to the manual https://instaloader.github.io/cli-options.html?highlight=latest%20stamps#cmdoption-latest-stamps 

> Only works for media associated with a specific profile, and that is returned in chronological order: profile posts, profile stories, profile IGTV posts and profile tagged posts.

**Comment by SergeySypalo** [comment]
Sorry, that was a typo, fixed the title

**Comment by SergeySypalo** [comment]
Tested downloading of some small profile to a separate folder and here are my findings:

If `--dirname-pattern` parameter is specified, then regardless of using `--fast-update` or `--latest-stamps` params all media is downloaded to the specified directory and only one subdirectory called the same as a username you are downloading will be created within target directory and will contain covers for each highlights "folder"

If `--dirname-pattern` parameter isn't specified, then folders created for each highlights as in user's instagram profile. Works the same with `--fast-update` or `--latest-stamps` params.

So the reason issue happened - I downloaded user profiles to some main folder and later when decided to rename each user's folder to firstname_lastname and specify `--dirname-pattern` - old media that I cleaned up started to download to the "root" folder, as mentioned in the first behavior of this comment.

So ideally use one approach to the folder structure, with highlights folders or without. Easier to implement - without. But with folders, it's easier to browse contents.

Also with highlights folders if say a story was downloaded it will be stored in the user's folder and if later this story is added by a user to highlights, it will be stored in the appropriate highlights folder, so we'll end up with duplicates. Also if one story is added to different highlights and we use highlights folders (i.e. don't specify `--dirname-pattern` param) - the same media will be duplicated in different highlights folders.

So as a fix I can propose to add a check to go through all files in the target folder and try to find a media in the highlights subfolder and skip it if it already exists and don't download to the root folder when moving from one folder or all downloaded profiles to per person by specifying `--dirname-pattern` param.

The best solution would be to keep the highlights folder structure and use symlinks, to not waste disk space, so 1 media can show up in the root folder and different highlight folders and if a user deletes a media it will be removed everywhere

**Comment by Karmac** [comment]
Hi,

I've also noticed that --latest-stamps doesn't work for highlights. Is there any workaround for this?

It would be cool if instaloader would save the timestamp of the latest highlight, and then discard any previous file (I mean, so files are not saved, even if they must be downloaded someway).

Thanks.
