### ISSUE TITLE
Instaloader directed to login.

### ISSUE THREAD

**Issue by KillaRanks** [instaloader/instaloader#1617]
**Describe the bug**
As many have reported in the past, i just found yesterday that instaloader was not able to scan any image. Not for a single profile and not for a bunch. 
I do not use an account for security reasons, as i got permanently banned once before in a work account and not even downloading more than 20 items and it was my own profile... (although this is not related with the actual issue as instaloader was working normally till yesterday)

**To Reproduce**
The normal thing even further i do not let the thing get anything more than the items as in: 
python -m instaloader profile --dirname-pattern=G:\IG\{profile} --no-captions --no-video-thumbnails --no-metadata-json --no-compress-json --no-profile-pic --fast-update

**Expected behavior**
The usual behavior is that the thing scans and downloads only if there is new items, although i have tried without the fast update.

**Error messages and tracebacks**
HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=profile to https://www.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
**Profile** : Redirected to login page. Use --login.

Profile: Redirected to login page. Use --login.

**Instaloader version**
4.9.2

**Additional context**
I have checked if i can enter IG from the web browser and it's all ok it seems, i have a suspicion that they have changed their url? idk for sure. That's it, if anyone have the same result when not using an account and scanning profiles please let me know also whoever reads this, so we can assure it is not an isolated case and it is repeatable.

**Comment by aandergr** [comment]
Not reproducible, for me it works, I can download a high amount of data, complete profiles with way beyond hundred posts, without being logged-in.

**Comment by senaykt** [comment]
Same issue is occured for me right now. It does not work.

**Comment by senaykt** [comment]
> Not reproducible, for me it works, I can download a high amount of data, complete profiles with way beyond hundred posts, without being logged-in.

It's not working now.

**Comment by mauronr** [comment]
My 2c, as I have suffered and worked to work around Instagram's unpredictable behavior.

My assumption, based on trial-and-error experiments is that Instagram has become much more sensitive to repeated activity from anonymous sessions coming from the same IP.  My guess is they rate and track each IP's reputation, so the behavior will differ for different IPs and at different moments, as they may update the IPs reputation depending on the traffic pattern coming from it. 

For example, I ran the OPs exact command on a very large profile (@hugogloss, 47K posts) from my residential IP. It gave the "redirect to login" error after downloading 62 posts. Every further tentative gives me the "redirect to login" right away. Also,  it will redirect me to login even if I try any URLs like `http://instagram.com/p/*` in the browser.

Then I tried the exactly same command, just adding the `--login` and using my personal credentials (one I assume IG considers as normal traffic coming from my IP). It started to download the posts, just at a very slow pace.

**Comment by mauronr** [comment]
Adding to my previous comment, I just got this error (see the image) on my mobile.
This pretty much suggests Instagram has added much stricter controls.

![Screenshot_20220728-114557_Instagram.jpg](https://user-images.githubusercontent.com/5508880/181564834-0227a1f8-4ad4-4cb7-85bd-f5408cbd6b6c.jpg)

**Comment by mauronr** [comment]
We tested some rotating proxies providers and managed to work around this issue, but it still requires some error handling and backoff-and-retry strategies.  Of course, that would mean additional cost.

**Comment by KillaRanks** [comment]
> We tested some rotating proxies providers and managed to work around this issue, but it still requires some error handling and backoff-and-retry strategies. Of course, that would mean additional cost.

How does the websites that show the IG profile photos in their sites work? is this aimed to take them down too?

Also will this be a future update?

**Comment by mauronr** [comment]
As I mentioned in a previous comment, success is a hit-and-miss depending on how lucky you are staying below Instagram's decision of what can be downloaded by whom and when, especially on non-authenticated sessions. 

We managed to get around it with a combination a retry loop leveraging Instaloader's ability to resume previously aborted download loop (see command-line `--resume-prefix` option ), rotating proxies and changing the proxy between each retry.
Proxy set via environment variable `HTTP_PROXY` and `HTTPS_PROXY` (in Linux & Mac, not sure about Windows). 

IMHO, there's not much Instaloader maintainers can do (I'm not one of them, just a heavy user) as this issue would also happen to Instagram's app if we did the same download pattern with it.

**Comment by cam-au** [comment]
Confirming some of the above comments around IG limiting use.
Just tried running without login from VPN and it failed.
Disconnected from VPN back to residential IP, and it managed to run fine. Downloaded full (albeit small) profile no issue.

**Comment by Robin-garg23** [comment]
Exactly similar issue is happening again, it was working till yesterday!
Anyone knows any work around?

Error messages and tracebacks
HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=profile to https://www.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
Profile : Redirected to login page. Use --login.

**Comment by shashnkvats** [comment]
Facing the same issue.
File [~/miniforge3/envs/wgsn/lib/python3.9/site-packages/instaloader/instaloadercontext.py:337](https://file+.vscode-resource.vscode-cdn.net/Users/shashankvats/Competitive%20Intelligence/~/miniforge3/envs/wgsn/lib/python3.9/site-packages/instaloader/instaloadercontext.py:337), in InstaloaderContext.get_json(self, path, params, host, session, _attempt)
    334 if (redirect_url.startswith('https://www.instagram.com/accounts/login') or
    335     redirect_url.startswith('https://i.instagram.com/accounts/login')):
    336     if not self.is_logged_in:
--> 337         raise LoginRequiredException("Redirected to login page. Use --login.")
    338     # alternate rate limit exceeded behavior
    339     raise TooManyRequestsException("Redirected to login")
...
--> 337         raise LoginRequiredException("Redirected to login page. Use --login.")
    338     # alternate rate limit exceeded behavior
    339     raise TooManyRequestsException("Redirected to login")

LoginRequiredException: Redirected to login page. Use --login.

When I try to login using the below code

```
L = instaloader.Instaloader()
user_name = 'aibot0110'
passw = 'Impact@2023'
L.login(user_name, passw)  
```
I'm getting
    261         # triggers re-asking of password in Instaloader.interactive_login(), which makes no sense if the
    262         # username is invalid.
    263         raise InvalidArgumentException('Login error: User {} does not exist.'.format(user))

BadCredentialsException: Login error: Wrong password.

Even though my username and password are correct.

**Comment by shashnkvats** [comment]
Facing the same issue.
File [~/miniforge3/envs/wgsn/lib/python3.9/site-packages/instaloader/instaloadercontext.py:337](https://file+.vscode-resource.vscode-cdn.net/Users/shashankvats/Competitive%20Intelligence/~/miniforge3/envs/wgsn/lib/python3.9/site-packages/instaloader/instaloadercontext.py:337), in InstaloaderContext.get_json(self, path, params, host, session, _attempt)
334 if (redirect_url.startswith('https://www.instagram.com/accounts/login') or
335 redirect_url.startswith('https://i.instagram.com/accounts/login')):
336 if not self.is_logged_in:
--> 337 raise LoginRequiredException("Redirected to login page. Use --login.")
338 # alternate rate limit exceeded behavior
339 raise TooManyRequestsException("Redirected to login")
...
--> 337 raise LoginRequiredException("Redirected to login page. Use --login.")
338 # alternate rate limit exceeded behavior
339 raise TooManyRequestsException("Redirected to login")

LoginRequiredException: Redirected to login page. Use --login.

When I try to login using the below code

L = instaloader.Instaloader()
user_name = 'username'
passw = 'password'
L.login(user_name, passw)  
I'm getting
261 # triggers re-asking of password in Instaloader.interactive_login(), which makes no sense if the
262 # username is invalid.
263 raise InvalidArgumentException('Login error: User {} does not exist.'.format(user))

BadCredentialsException: Login error: Wrong password.

Even though my username and password are correct.

**Comment by PinkMonkeyBirdCoder** [comment]
@aandergr 
I am still getting this issue, not sure what invalid means in this context?

**Comment by tharsim** [comment]
I have the same problem, and I am using a pool with thousands of paid residential proxies. I don't know why I am getting this because each request for each profile is being made via a different proxy/IP. And I did a proxy check to make sure of that, everything seems okay with my code.
