### ISSUE TITLE
Instagram 560 errors when trying to download stories from lots of accounts

### ISSUE THREAD

**Issue by ryandtw** [instaloader/instaloader#1622]
**Describe the bug**
I'm receiving 560 errors when downloading multiple stories at the same time. This is happening on multiple accounts, not just one.

**To Reproduce**
Using stories.cmd batch:
`instaloader +args.txt --no-posts --no-profile-pic --stories --no-metadata-json --no-iphone --abort-on=400,429`

Inside the args text:
`--login="<IG username>"
--password="<IG user password>"
--fast-update
<Accounts to fetch stories from>`

**Expected behavior**
Should be downloading stories. If I download stories from only one account or a few, then the stories download should work, if the user has any active stories. But...

**Error messages and tracebacks**
When I try to download stories from lots of accounts at the same time, Instagram is sending out 560 error code instead:

`JSON Query to graphql/query: HTTP error code 560. [retrying; skip with ^C]`

`Errors or warnings occurred:
Download stories: JSON Query to graphql/query: HTTP error code 560.`

**Instaloader version**
4.9.2

**Additional context**
This is happening starting just today. Is it just me or are others facing the same issue? If so, are Instagram servers overloaded for some reason?

**Comment by pueptastisch** [comment]
same here

**Comment by pueptastisch** [comment]
forgot about #1599

**Comment by ryandtw** [comment]
Day 2 of 560 error issues. Still being triggered. Trying to do the workaround https://github.com/instaloader/instaloader/issues/1599#issuecomment-1165459346 but it doesn't work all the time. I hope Instagram resolves this error soon (TM).

**Comment by pueptastisch** [comment]
@ryandtw I don't think it has to do with specific accounts... but yes day 2 :(
560 is even triggered sometimes by `download_stories()` without any arguments

**Comment by LaticePrime** [comment]
I tried to scrape 400+ accounts stories tonight using #1599 workaround and it took 10 minutes longer but it completed and did get error 560 even once.

**Comment by fireattack** [comment]
You can simply modify this line:

https://github.com/instaloader/instaloader/blob/5e232fd4f521b1700c122827d973fd868c6ae483/instaloader/instaloader.py#L793

to a smaller number instead of running the accounts one by one. 5 works for me at the moment, but you can try literally 1.

Also yeah, I still encounter 560 issue today.

**Comment by arsenico13** [comment]
Yeah, I'm still getting the 560 error today, too.
I'll try the workaround to see if it works.

**Comment by ryandtw** [comment]
These 560 errors are downright annoying. Even going one-by-one I occasionally get 560 errors, particularly from those who have a lot of stories in the backlog. Ugh. And that's not before I get tired of having to wait significantly longer because I have to 're-login' before checking each target account one-by-one - and risking the Instagram 'bot cops' that can occasionally lock my accounts down!

I just hope Instagram fixes this 560 error nonsense.

(Off-topic: It's also been over a month and a half that Instagram broke the Oh My IG chrome extension and having to go through Instagram's dreaded 'algorithm' timeline. I hope there's an alternative to this extension with the revised API soon (tm).)

**Comment by ryandtw** [comment]
Not alone: #1633

**Comment by LaticePrime** [comment]
I've changed my script from 400 profiles at once to one at a time exiting if it throws any errors, and it takes 10 minutes longer but I've not had error 560 for three days now.

**Comment by Showmaster3000** [comment]
> i got error 400 now since eror 560 was fixed

this error 400 is another problem, see #1633. Please see there and do not spam this issue.

**Comment by DReaper** [comment]
> You can simply modify this line:
> 
> https://github.com/instaloader/instaloader/blob/5e232fd4f521b1700c122827d973fd868c6ae483/instaloader/instaloader.py#L793
> 
> to a smaller number instead of running the accounts one by one manually.
> 
> 5 works for me at the moment, but you can try literally 1.
> 
> Also yeah, I still encounter 560 issue today if using default 50 to download 23 account at once.

I was consistently getting 560 errors. This fixed it, but only when set to 1. 5 errors out for me.

I hope the Windows version has an option to change this specific setting going forward.

**Comment by DReaper** [comment]
> These 560 errors are downright annoying. Even going one-by-one I occasionally get 560 errors, particularly from those who have a lot of stories in the backlog. Ugh. And that's not before I get tired of having to wait significantly longer because I have to 're-login' before checking each target account one-by-one - and risking the Instagram 'bot cops' that can occasionally lock my accounts down!
> 
> I just hope Instagram fixes this 560 error nonsense.
> 
> (Off-topic: It's also been over a month and a half that Instagram broke the Oh My IG chrome extension and having to go through Instagram's dreaded 'algorithm' timeline. I hope there's an alternative to this extension with the revised API soon (tm).)
> 
> _**EDIT:**_ Now I have not one - but TWO - accounts temporarily banned from accessing Instagram over the past week, one today. Redirected to login error, but **they're asking me for my phone number, only for Instagram to NOT send the SMS with the required verification code**. **Ugh. I've dealt with this multiple times already this year.** _**Really angry at Instagram - and META.**_
> 
> (And I also got the 429 too many requests error as well.)
> 
> Now I have to wait for at least a week for these accounts to get 'unbanned' without trying to repeatedly send the phone number to send an SMS for verification code only to repeatedly fail. It seems Instagram doesn't really care about us.
> 
> Sorry for the rant. I'm just tired with Instagram changing up API (at the beginning of June), 560 errors (this week), etc. They don't really like us extracting stuff from there automatically, having to do this manually is going to be a time waster without Instaloader.
> 
> I'm really, really concerned about this situation. If Instagram doesn't fix this 560 error nonsense I'm fearing that they could be doing all they can to intentionally try to screw Instaloader - and us users - up.
> 
> For now I'm going to have to suspend fetching IG stories for now, at least a week. Again, hopefully, hopefully Instagram fixes the 560 error for fetching stories while I'm taking a break. I'm simply too tired to fight with this. It was almost a month and a half it was running smooth scraping stories, but this week's 560 error nonsense have first made fetching stories longer - and now two of my accounts are temporarily banned from using Instagram for scraping too much, not allowing me to get the recovery code SNS before Instagram unlocks these accounts by itself. At least I'm still able to fetch regular posts normally (if not impeded by account lock).
> 
> (I have **over 500 accounts** to check, which is a lot. More than someone here who said earlier that he was trying to scrape over 400 accounts. Mostly Japanese stuff.)

I believe IG has a limit on how many SMS codes or how many accounts it will send to and it will not warn you when sending a code. I believe the limit resets weekly. Try another phone number if possible and you would get the code.

**Comment by twitter-79** [comment]
I'm having the problem of frequent 560 errors too (see #1616) so I was trying to find the root cause of the problem.

When I'm browsing through the network requests on instagram I can see a request I have never seen before. Maybe it is new? It's going  to this endpoint:
`https://i.instagram.com/api/v1/web/get_ruling_for_content/?content_type=PROFILE&target_id=x`

where `target_id` is the id of the profile I opened in the browser. The request is directly before the one fetching the new profile information from:
`https://i.instagram.com/api/v1/users/web_profile_info/?username=x_username`

The response is just `{"title":"","description":"","status":"ok"}` so nothing special in there...

Did someone see this type of request before? Maybe it sets some cookie we need for fetching user profiles now or anything like that?

**Comment by Nova6K0** [comment]
Let's see why, although my knowledge is low, and more in Python. I was investigating a little, things that surely many already know, but they don't sound to me. The subject is as follows:

The API:

api/v1/users/web_profile_info/? Username = (Username)

Give the error, that User-Agent is missing, which is the problem.

It turns out that if we put the web directly from Instagram:

https://www.instagram.com/(username)/?__a=1&__d=dis

Returns the appropriate data (JSON). Of course as I say, my low knowledge about Python, they do not allow me to fix the program.

Greetings.

**Comment by twitter-79** [comment]
This is a good catch! For some reason my web version of instagram does not use this endpoint but it seems to work if we substitute the lines 767-771 in structures.py (again) with the following:

```
metadata = self._context.get_json('{}/'.format(self.username), params={"__a": 1, "__d": "dis"})
self._node = metadata['graphql']['user']
```

I'll try this version out for a few days on my fork of instaloader and will report back.

**Comment by Nova6K0** [comment]
I tried to try, changing the Structures.py. But it gives me an error 301 of redirection (Json Query 301), I imagine that it is because I am from Spain, and you have to somehow put the location.

Greetings.

**Comment by twitter-79** [comment]
sorry, this is not happening for me (germany). No clue why this happens for you though

**Comment by Nova6K0** [comment]
Thanks. The error that gives me is of the type:
```
HTTP redirect from https://i.instagram.com/(username)/ to https://www.instagram.com/(username)/?__a=1&__d=dis
JSON Query to (username)/: HTTP error code 301. [retrying; skip with ^C]
```

Greetings.

**Comment by twitter-79** [comment]
I'm a bit confused why it tries to reach i.instagram.com/(username)/ for you when it should request www.instagram.com/(username)/

are you maybe still using the `self._context.get_iphone_json` method?

**Comment by rayman0530** [comment]
It seems like the errors are gone if you delete story timestamps in your latest-stamps file.

**Comment by hgrias** [comment]
Getting 560 Errors when trying to get stories from many accounts. Tried all work-arounds in this thread and still getting the same 560 errors.

**Comment by afterdelight** [comment]
> This is a good catch! For some reason my web version of instagram does not use this endpoint but it seems to work if we substitute the lines 767-771 in structures.py (again) with the following:
> 
> ```
> metadata = self._context.get_json('{}/'.format(self.username), params={"__a": 1, "__d": "dis"})
> self._node = metadata['graphql']['user']
> ```
> 
> I'll try this version out for a few days on my fork of instaloader and will report back.

this change doesnt prevent error 400

**Comment by Nova6K0** [comment]
That does not avoid error 400. It only allows access to metadata. And it is worth everything, I mean the following:

`https:\\www.instagram.com\{}\[shortcode]\?__a=1&__d=dis

{} = tv, reel, p...`

Greetings.

**Comment by afterdelight** [comment]
i still got error 560 with this change, what fixed for me is reducing userids_per_query from 50 to 3

**Comment by artenax** [comment]
> It seems Instagram doesn't really care about us

Instagram takes care of the children who have taken a fancy to this social network. So I would advise avoid Instagram, there are better services. It is one of the most fascist services, that's right, there's no reason to use it at will.

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com
