### ISSUE TITLE
Avoid Instagram suspecting if trying to connect with the API to my Instagram account

### ISSUE THREAD

**Issue by JustWhit3** [instaloader/instaloader#1627]
**Describe the bug**
I am using the Instaloader Python API for a project. Every time I successfully log-in I get a notification on my Instagram app that someone tried to connect to my account. Everything is ok, I can simply mark the option that was me to connect, but I would like to know if there is a way to directly login from Instaloade avoiding this troublesome situation.

**To Reproduce**
```
import instaloader as ig

if __name__ == "__main__":
    
    username = "user"
    password = "passwd"
    loader = ig.Instaloader()
    
    loader.login( username, password )
```

**Expected behavior**
I expect a normal login without any warning by the Instagram app.

**Instaloader version**
4.9

**Comment by Showmaster3000** [comment]
The notification is a feature of Instagram. Even logging in with a browser sometimes leads to the message of suspected login. You can just ignore the message.
Btw. it is helpful to use saved sessions which prevents the notifications.

**Comment by AloneInSky** [comment]
> The notification is a feature of Instagram. Even logging in with a browser sometimes leads to the message of suspected login. You can just ignore the message. Btw. it is helpful to use saved sessions which prevents the notifications.

Even saved session prevents notifications instagram will lock the account and tell users to reset password. And when saving new session it need to pass the damn checkpoint

**Comment by aandergr** [comment]
> **Describe the bug**
> I am using the Instaloader Python API for a project. Every time I successfully log-in I get a notification on my Instagram app that someone tried to connect to my account. Everything is ok, I can simply mark the option that was me to connect, but I would like to know if there is a way to directly login from Instaloade avoiding this troublesome situation.

This is not a bug.
