### ISSUE TITLE
Can't download post in certain username

### ISSUE THREAD

**Issue by kiranaananda** [instaloader/instaloader#1630]
I use this script in .py file.

> for post in takewhile(lambda p: p.date >= UNTIL, dropwhile(lambda p: p.date >= SINCE, posts)):
>     print(post.date)
>     L.download_post(post, "xxxbrand")

Usually it will auto download by creating a folder, but the code does not work in downloading certain brands just yesterday, but weirdly for only 2 users.

**Comment by Showmaster3000** [comment]
Too less information. You missed the issue template. Closing issue soon.

**Comment by kiranaananda** [comment]
I've figured out the issue by changing the date script as below.

> for post in posts:
    if UNTIL < post.date < SINCE:
        L.download_post(post, "xxxbrand")

Is there any issues with order of date?
