### ISSUE TITLE
unable to fetch HQ version of reshared story/post

### ISSUE THREAD

**Issue by giturfreakon** [instaloader/instaloader#1633]
**Describe the bug**
It looks like instaloader is unable to fetch HQ version of reshared story/post. Only started happening today.

**To Reproduce**
`instaloader mina_sr_my --stories --no-posts --no-profile-pic --login <user> --dirname-pattern=C:\_dump\instaloader\{profile} --filename-pattern={shortcode} --no-video-thumbnails`

**Expected behavior**
fetch HQ version of reshared story/post

**Error messages and tracebacks**
```
[1/1] Retrieving stories from profile mina_sr_my.
[  1/  4] 400 Bad Request Unable to fetch high quality image version of <StoryItem 2882069669219364271>.
C:\_dump\instaloader\mina_sr_my\Cf_Kxgjv22v.jpg json
[  2/  4] C:\_dump\instaloader\mina_sr_my\Cf-8O74vvdv.jpg json
[  3/  4] Unable to fetch high-quality video version of <StoryItem 2881898094290972910>: 400 Bad Request
C:\_dump\instaloader\mina_sr_my\Cf-jww9FrDu.mp4 json
[  4/  4] Unable to fetch high-quality video version of <StoryItem 2881897862429726532>: 400 Bad Request
C:\_dump\instaloader\mina_sr_my\Cf-jtZBFNdE.mp4 json
```

**Instaloader version**
`4.9.2`

**Comment by ikuchan122** [comment]
I have experienced the same issue and my account was eventually locked by Instagram. Perhaps there might me some changes to the json response when retrieving stories?

**Comment by tbm** [comment]
I also see this. Started yesterday

**Comment by pueptastisch** [comment]
+1

**Comment by chainria** [comment]
> I have experienced the same issue and my account was eventually locked by Instagram. Perhaps there might me some changes to the json response when retrieving stories?

I had to do the reset-password-your-account-is-compromised shinanigan as well. Strangely enough, this only applies to one of my accounts, the other one seems to be doing well. Maybe some kinda trap by Meta?

**Comment by ikuchan122** [comment]
It seems that the following api endpoint no longer works (i.e. api/v1/media/{}/info): 

https://github.com/instaloader/instaloader/blob/da0dcb106cd1aba7d44d3dcdd133532f730245ed/instaloader/structures.py#L1175


This line of code appears twice in structure.py. Once inside the class Post and once inside the class Story. Disabling the following lines of code could solve the issue temporarily in my own user case (which deals with video stories). However, I don't know if it might break other parts of the program for other user cases. My suggestion may not work for everybody. 


https://github.com/instaloader/instaloader/blob/da0dcb106cd1aba7d44d3dcdd133532f730245ed/instaloader/structures.py#L1262-L1266


If you wish to disable the same with regards to image stories, disable the following line of codes:

https://github.com/instaloader/instaloader/blob/da0dcb106cd1aba7d44d3dcdd133532f730245ed/instaloader/structures.py#L1233-L1240


To the best of my knowledge, the function that contains the above code aims to find out the best video/image quality to download. It takes  the json response returned from the 'api/v1/media/{}/info/' endpoint . As I am not familiar with the iphone api endpoints, perhaps someone else could help find out the correct endpoint to use and suggest the appropriate changes to be made. 

Alternately, it might also be feasible to replace the iphone api with the instagram web api which offers more stability and consistency. 

Thoughts?

**Comment by afterdelight** [comment]
no need to change anything, it was the correct end point for hq images and videos

**Comment by ikuchan122** [comment]
> no need to change anything, it was the correct end point for hq images and videos

During debugging, it returns 400 Bad Request. Perhaps something has changed. Meanwhile, the web api endpoints work fine.

**Comment by afterdelight** [comment]
it because you fetch too many downloads. try to put some delays or stop downloading for a few hours

**Comment by ikuchan122** [comment]
> it because you fetch too many downloads. try to put some delays or stop downloading for a few hours

What you said is plainly wrong. The "400 Bad Request" response has absolutely nothing to do with "too many requests" or "too many downloads".  In your case, Instagram server would return "Error 429". 

FYI, for debugging purpose, I used a rarely used account to download just 2 stories (a reshared video story and a reshared image story) from 1 target instagram account. Then, I checked the variable self._iphone_struct which should store a dictionary of the json data returned. However, there was no data returned because 400 occurred. Hence, line 1264 of structure.py threw an exception.

[giturfreakon] made it clear that only reshared story/post would throw this error and I can confirm that he was right. Others may have yet to encounter this issue but that doesn't mean this issue isn't real.  I believe the community would appreciate more helpful ideas on how to fix the bug.

**Comment by ikuchan122** [comment]
> > it because you fetch too many downloads. try to put some delays or stop downloading for a few hours
> 
> What you said is plainly wrong. The "400 Bad Request" response has absolutely nothing to do with "too many requests" or "too many downloads". In your case, Instagram server would return "Error 429".
> 
> FYI, for debugging purpose, I used a rarely used account to download just 2 stories (a reshared video story and a reshared image story) from 1 target instagram account. Then, I checked the variable self._iphone_struct which should store a dictionary of the json data returned. However, there was no data returned because 400 occurred. Hence, line 1264 of structure.py threw an exception.
> 
> [giturfreakon] made it clear that only reshared story/post would throw this error and I can confirm that he was right. Others may have yet to encounter this issue but that doesn't mean this issue isn't real. While you yourself thumbing up your own reply would not help, I believe the Instaloader community would appreciate more helpful ideas on how to fix the bug.

https://github.com/instaloader/instaloader/issues/1640#issue-1306778503

Another example that downloading just 1 story would cause Error 400 to occur. This issue is definitely not caused by 'too many downloads' .

**Comment by chainria** [comment]
> > it because you fetch too many downloads. try to put some delays or stop downloading for a few hours
> 
> What you said is plainly wrong. The "400 Bad Request" response has absolutely nothing to do with "too many requests" or "too many downloads". In your case, Instagram server would return "Error 429".
> 
> FYI, for debugging purpose, I used a rarely used account to download just 2 stories (a reshared video story and a reshared image story) from 1 target instagram account. Then, I checked the variable self._iphone_struct which should store a dictionary of the json data returned. However, there was no data returned because 400 occurred. Hence, line 1264 of structure.py threw an exception.
> 
> [giturfreakon] made it clear that only reshared story/post would throw this error and I can confirm that he was right. Others may have yet to encounter this issue but that doesn't mean this issue isn't real. While you yourself thumbing up your own reply would not help, I believe the Instaloader community would appreciate more helpful ideas on how to fix the bug.

You're right! ALL my 400's seem to be reshares. But it seems that instagram blocks the account after enough of those, so the question is: Can these be somehow detected? BEFORE hitting Instagram with a request which clearly could only come from an outside app? I guess the request simply doesn't work for reshares and therefore it shouldn't be done at all.

**Comment by afterdelight** [comment]
still got 400 error

**Comment by Showmaster3000** [comment]
Looks like the error is gone for me - at least for 15 hours.

**Comment by AyluinReymaer** [comment]
Same here.

I'm currently not having issues since yesterday.

I'll monitor my app for a few more days and will report back here if I'm still having bad requests for story items.

**Comment by ikuchan122** [comment]
> Looks like the error is gone for me - at least for 15 hours.

The error was gone yesterday. But it haa come back just a few minutes ago. It got a 400 Bad Request tried to fetch a reposted story. When it retried, my account got temporarily locked. 

Will continue to monitor the situation and update you guys if any development. 

FYI, another script of mine which calls the instagram web api (the "reel_media" endpoint) continues to work fine.

**Comment by AyluinReymaer** [comment]
I've just got the same issue again...

Most likely, instagram is making changes **again** to the api...

**Comment by afterdelight** [comment]
yeah the issue is back today

**Comment by AyluinReymaer** [comment]
Is the issue still occurring for everyone?

For some reason, instagram kicked me out from all my devices and had to log back in, instaloader included.

I wasn't blocked or banned or anything, just logged out for some reason...

I thought that instagram did something, but the issue is still ongoing for me...

**Comment by ikuchan122** [comment]
@AyluinReymaer  Yes. When I activated instaloader just now, instagram locked my account immediately on the first try. Instaloader showed the below error message:

> Traceback (most recent call last):
>   File "/usr/local/bin/instaloader", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/site-packages/instaloader/__main__.py", line 471, in main
>     _main(loader,
>   File "/usr/local/lib/python3.9/site-packages/instaloader/__main__.py", line 107, in _main
>     if not instaloader.context.is_logged_in or username != instaloader.test_login():
>   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloader.py", line 625, in test_login
>     return self.context.test_login()
>   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 191, in test_login
>     data = self.graphql_query("d6f4427fbe92d846298cf93df0b937d3", {})
>   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 428, in graphql_query
>     resp_json = self.get_json('graphql/query',
>   File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 328, in get_json
>     raise AbortDownloadException("Query to https://{}/{} responded with \"{} {}\"{}".format(
> instaloader.exceptions.AbortDownloadException: Query to https://www.instagram.com/graphql/query responded with "400 Bad Request"
>

**Comment by chainria** [comment]
> @AyluinReymaer Yes. When I activated instaloader just now, instagram locked my account immediately on the first try. Instaloader showed the below error message:
> 
> > Traceback (most recent call last):
> > File "/usr/local/bin/instaloader", line 8, in 
> > sys.exit(main())
> > File "/usr/local/lib/python3.9/site-packages/instaloader/**main**.py", line 471, in main
> > _main(loader,
> > File "/usr/local/lib/python3.9/site-packages/instaloader/**main**.py", line 107, in _main
> > if not instaloader.context.is_logged_in or username != instaloader.test_login():
> > File "/usr/local/lib/python3.9/site-packages/instaloader/instaloader.py", line 625, in test_login
> > return self.context.test_login()
> > File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 191, in test_login
> > data = self.graphql_query("d6f4427fbe92d846298cf93df0b937d3", {})
> > File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 428, in graphql_query
> > resp_json = self.get_json('graphql/query',
> > File "/usr/local/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 328, in get_json
> > raise AbortDownloadException("Query to https://{}/{} responded with "{} {}"{}".format(
> > instaloader.exceptions.AbortDownloadException: Query to https://www.instagram.com/graphql/query responded with "400 Bad Request"

The same just happened for me. I guess they somehow block instaloader now. Although after the reset it seems to work.

**Comment by fireattack** [comment]
There doesn't seem to have a way to tell if a post/story is reshared or not in the node data. 

```json
{
  "audience": "MediaAudience.DEFAULT",
  "__typename": "GraphStoryVideo",
  "id": "2892247832508454562",
  "dimensions": {
    "height": 1136,
    "width": 640
  },
  "display_resources": [
  ],
  "display_url": "...",
  "media_preview": "...",
  "gating_info": null,
  "fact_check_overall_rating": null,
  "fact_check_information": null,
  "sharing_friction_info": {
    "should_have_sharing_friction": false,
    "bloks_app_url": null
  },
  "media_overlay_info": null,
  "sensitivity_friction_info": null,
  "taken_at_timestamp": 1659002820,
  "expiring_at_timestamp": 1659089220,
  "story_cta_url": null,
  "story_view_count": null,
  "is_video": true,
  "owner": {
    "id": "4009894782",
    "profile_pic_url": "...",
    "username": "caririn.official",
    "followed_by_viewer": true,
    "requested_by_viewer": false
  },
  "tracking_token": "...",
  "has_audio": true,
  "overlay_image_resources": null,
  "video_duration": 12.0,
  "video_resources": [
    {
      "src": "...",
      "config_width": 480,
      "config_height": 852,
      "mime_type": "video/mp4; codecs=\"avc1.42E01E, mp4a.40.2\"",
      "profile": "BASELINE"
    }
  ],
  "tappable_objects": [
    {
      "__typename": "GraphTappableMention",
      "x": 0.5,
      "y": 0.571392141414043,
      "width": 0.8055839082649361,
      "height": 0.8055839082649361,
      "rotation": 0.0,
      "custom_title": null,
      "attribution": null,
      "username": "amusemobile",
      "full_name": "Amuse+(アミュプラ)",
      "is_private": false
    }
  ],
  "story_app_attribution": null,
  "edge_media_to_sponsor_user": {
    "edges": []
  },
  "muting_info": null
}
```

Otherwise we probably can find a way to only call iPhone API when it's "original".

**Comment by afterdelight** [comment]
have anyone try this old api change?

[-scraping-instagram-media-by-adding-at-the-end-of-url-a-1/72582413#72582413](https://stackoverflow.com/questions/72467565/error-when-scraping-instagram-media-by-adding-at-the-end-of-url-a-1/)

**Comment by fireattack** [comment]
Can someone provide a re-shared **post** (not story) for testing? All the examples I saw across multiple tickets are stories.

**Comment by Nova6K0** [comment]
Hi friends. I was doing tests. Forwarding a request, changing the user agent (with the Firefox development options, in my case).

Error 400, gives it when the request is wrong. For example if you use:

`i.instagram.com/api/v1/users/web_profile_info/?username={username}`

JSON error:

```
message:    "useragent mismatch"
status:     "fail"

```

If we do what I put, changing the (mobile) user agent (complete user agent) and with the right header, of course. The petition is accepted, giving a message 200.

JSON:

```
data: -> user: -> ...
status: "ok"

```
Greetings.

**Comment by fireattack** [comment]
> Hi friends. I was doing tests. Forwarding a request, changing the user agent (with the Firefox development options, in my case).
> 
> Error 400, gives it when the request is wrong. For example if you use:
> 
> `i.instagram.com/api/v1/users/web_profile_info/?username={username}`
> 
> JSON error:
> 
> ```
> message:    "useragent mismatch"
> status:     "fail"
> ```
> 
> If we do what I put, changing the (mobile) user agent (complete user agent) and with the right header, of course. The petition is accepted, giving a message 200.
> 
> complete user agent (example):
> 
> `Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 243.1.0.14.111 (iPhone12,1; iOS 15_5; en_US; en-US; scale=2.00; 828x1792; 382468104)`
> 
> JSON:
> 
> ```
> data: -> user: -> ...
> status: "ok"
> ```
> 
> Greetings.

The current included UA works fine. Sometimes you just need to re-create your session/cookie.

**Comment by Nova6K0** [comment]
@fireattack Friend, your code works perfect. Not a single 400 error.

Greetings.

**Comment by mitchcapper** [comment]
Confirmed.  I cleared the session logged in using a proxied mobile device and then copied its exact UA.  Accounts that had not worked for weeks worked again.   I could guess you could also do something similar using chrome's emulated mobile mode (not that it is required but I figure the more it matches the better).

**Comment by fireattack** [comment]
You don't need any of that. You just need to re-create your session for some reason. It would get "stale" after a while for whatever reason.

**Comment by mitchcapper** [comment]
@fireattack even completely erasing the session and recreating it would flag quickly on shared stories/posts for me.   As others mentioned here it seemed one hit to the extended url with the wrong agent could result in the account flagged.  
Yes I am sure exactly duping the agent the session is created on is not needed here, but if their goal is to continue to ratchet down on 3rd party access the closer it is to looking the exact same the better.

**Comment by jlntrt** [comment]
@mitchcapper seems to be the case for me. I sill get the 400 response with the user agent string that @fireattack [mentioned](https://github.com/instaloader/instaloader/issues/1633#issuecomment-1203629435) and also removing the session before.

**Comment by fireattack** [comment]
Just to clarify. As you said, the key here is to not trigger HTTP 400. 

It happens when you trying to retrieve media info for a reposted story (whose `mediaid` isn't valid for that API endpoint). And that would cause your session being flagged, or even account suspended. 

Using the "wrong UA" won't cause that; the API would simply return "useragent mismatch" (no 400). And the UA in the code currently, albeit old, won't even cause that. I never see "useragent mismatch" when using Instaloader myself.

Once your session/account got flagged, it would constantly throw HTTP 400 on other otherwise valid API endpoint, (such as `api/v1/users/{}/info/` we used to retrieve highQ profile pic) regardless your UA.

**Comment by afterdelight** [comment]
looks like your fork fixed the problem. ty!

you can use this user agent to make it more legitimate
https://developers.whatismybrowser.com/useragents/explore/operating_platform_string/oneplus/8

**Comment by Nova6K0** [comment]
Precisely from there I obtain it, for the tests.

Greetings.

**Comment by afterdelight** [comment]
i got this new error now
Unable to fetch high quality image version of <StoryItem xxxxxxxxxxxxxxxxxxxxx>: 'image_versions2'

**Comment by fireattack** [comment]
You need to provide the exact story ID.

Also if you're downloading highlights with old stories, it sometimes happens since iPhone API don't always give all the stories.

**Comment by denbartman** [comment]
Don't know if it is the same problem since there was a 403 first, but then the error 400 locked my account.

The first error occurred when the 3rd item (a video) of a picture set was downloaded. (The rest of the set was not downlaoded)
https://www.instagram.com/p/CWn9B0kogve/

The second error downloaded nothing: https://www.instagram.com/p/CWdE_P2o6mD/

Args

```
--login=xxxx
--password=xxxx
--dirname-pattern=m:/IG_Instaloader/{target}/Posts/
--filename-pattern={date_local:%Y-%m-%d_%H-%M-%S}-000 {profile} (P) {mediaid}
--title-pattern={profile}_ProfilePic_{date_local:%Y-%m-%d_%H-%M-%S}
--no-video-thumbnails
--no-compress-json
--latest-stamps=c:/Programs/Instaloader/latest-stamps.ini
--comments
--abort-on=400,429
pommelienthijs

```

logging:
```

Using latest stamps from c:/Programs/Instaloader/latest-stamps.ini.
Loaded session from C:\Users\xxxx\AppData\Local\Instaloader\session-xxx.
Logged in as xxxx.
[1/1] Downloading profile pommelienthijs
Retrieving posts from profile pommelienthijs.
Resuming from m:/IG_Instaloader/pommelienthijs/Posts/iterator_IA07fVif.json.xz.
[ 65/238] m:/IG_Instaloader/pommelienthijs/Posts/2021-11-24_13-14-42-000 pommelienthijs (P) 2714017191658948728_1.jpg m:/IG_Instaloader/pommelienthijs/Posts/2021-11-24_13-14-42-000 pommelienthijs (P) 2714017191658948728_2.jpg comments json 
[ 66/238] m:/IG_Instaloader/pommelienthijs/Posts/2021-11-23_16-59-48-000 pommelienthijs (P) 2713405706519841758_1.jpg m:/IG_Instaloader/pommelienthijs/Posts/2021-11-23_16-59-48-000 pommelienthijs (P) 2713405706519841758_2.jpg m:/IG_Instaloader/pommelienthijs/Posts/2021-11-23_16-59-48-000 pommelienthijs (P) 2713405706519841758_3.jpg [ 67/238] m:/IG_Instaloader/pommelienthijs/Posts/2021-11-21_15-38-24-000 pommelienthijs (P) 2711915184299029818_1.jpg m:/IG_Instaloader/pommelienthijs/Posts/2021-11-21_15-38-24-000 pommelienthijs (P) 2711915184299029818_2.jpg m:/IG_Instaloader/pommelienthijs/Posts/2021-11-21_15-38-24-000 pommelienthijs (P) 2711915184299029818_3.jpg [Big smootch] comments json 
[ 68/238] m:/IG_Instaloader/pommelienthijs/Posts/2021-11-20_11-26-33-000 pommelienthijs (P) 2711063650082285911_1.jpg m:/IG_Instaloader/pommelienthijs/Posts/2021-11-20_11-26-33-000 pommelienthijs (P) 2711063650082285911_2.jpg [Videoclip voor meisjes van ho…] comments json 
[ 69/238] txt 
Saved resume information to m:/IG_Instaloader/pommelienthijs/Posts/iterator_IA07fVif.json.xz.
Saved session to C:\Users\xxxx\AppData\Local\Instaloader\session-xxx.

Download <Post CWn9B0kogve> of pommelienthijs: 403 when accessing https://scontent-bru2-1.cdninstagram.com/v/t50.2886-16/260216748_196281196006152_3827572863716622542_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjQ4MC5jYXJvdXNlbF9pdGVtLmRlZmF1bHQiLCJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSJ9&_nc_ht=scontent-bru2-1.cdninstagram.com&_nc_cat=100&_nc_ohc=2XiWZaCcJ5UAX9L-bT4&edm=APU89FABAAAA&vs=17907720245252094_3986488486&_nc_vs=HBksFQAYJEdLeVhnZzhJeS1aR2hMSUFBTTRBd1gwOVJSNDFia1lMQUFBRhUAAsgBABUAGCRHQzUtZ3c4VFVmT1JyekFDQU1yNmdndVlWaWNOYmtZTEFBQUYVAgLIAQAoABgAGwGIB3VzZV9vaWwBMBUAACaSwLHvpau9PxUCKAJDMywXQCQzMzMzMzMYEmRhc2hfYmFzZWxpbmVfMV92MREAde4HAA%3D%3D&ccb=7-5&oe=62D69FBA&oh=00_AT91Np1Vz6bN7hCEMWWZdYU2qqmKvFn4tgs9LbMCQmO7iw&_nc_sid=86f79a.
Download aborted: Query to https://i.instagram.com/api/v1/media/2710344489282808195/info/ responded with "400 Bad Request".
Errors or warnings occurred:
Download <Post CWn9B0kogve> of pommelienthijs: 403 when accessing https://scontent-bru2-1.cdninstagram.com/v/t50.2886-16/260216748_196281196006152_3827572863716622542_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjQ4MC5jYXJvdXNlbF9pdGVtLmRlZmF1bHQiLCJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSJ9&_nc_ht=scontent-bru2-1.cdninstagram.com&_nc_cat=100&_nc_ohc=2XiWZaCcJ5UAX9L-bT4&edm=APU89FABAAAA&vs=17907720245252094_3986488486&_nc_vs=HBksFQAYJEdLeVhnZzhJeS1aR2hMSUFBTTRBd1gwOVJSNDFia1lMQUFBRhUAAsgBABUAGCRHQzUtZ3c4VFVmT1JyekFDQU1yNmdndVlWaWNOYmtZTEFBQUYVAgLIAQAoABgAGwGIB3VzZV9vaWwBMBUAACaSwLHvpau9PxUCKAJDMywXQCQzMzMzMzMYEmRhc2hfYmFzZWxpbmVfMV92MREAde4HAA%3D%3D&ccb=7-5&oe=62D69FBA&oh=00_AT91Np1Vz6bN7hCEMWWZdYU2qqmKvFn4tgs9LbMCQmO7iw&_nc_sid=86f79a.
```

**Comment by afterdelight** [comment]
> You need to provide the exact story ID.
> 
> Also if you're downloading highlights with old stories, it sometimes happens since iPhone API don't always give all the stories.

it was a story not highlight posts

**Comment by afterdelight** [comment]
> Don't know if it is the same problem since there was a 403 first, but then the error 400 locked my account. And this is on a post not a story.
> 
> The first error occurred when the 3rd item (a video) of a picture set was downloaded. (The rest of the set was not downlaoded) https://www.instagram.com/p/CWn9B0kogve/
> 
> The second error downloaded nothing: https://www.instagram.com/p/CWdE_P2o6mD/
> 
> Args
> 
> ```
> --login=xxxx
> --password=xxxx
> --dirname-pattern=m:/IG_Instaloader/{target}/Posts/
> --filename-pattern={date_local:%Y-%m-%d_%H-%M-%S}-000 {profile} (P) {mediaid}
> --title-pattern={profile}_ProfilePic_{date_local:%Y-%m-%d_%H-%M-%S}
> --no-video-thumbnails
> --no-compress-json
> --latest-stamps=c:/Programs/Instaloader/latest-stamps.ini
> --comments
> --abort-on=400,429
> pommelienthijs
> ```
> 
> logging:
> 
> ```
> 
> Using latest stamps from c:/Programs/Instaloader/latest-stamps.ini.
> Loaded session from C:\Users\xxxx\AppData\Local\Instaloader\session-xxx.
> Logged in as xxxx.
> [1/1] Downloading profile pommelienthijs
> Retrieving posts from profile pommelienthijs.
> Resuming from m:/IG_Instaloader/pommelienthijs/Posts/iterator_IA07fVif.json.xz.
> [ 65/238] m:/IG_Instaloader/pommelienthijs/Posts/2021-11-24_13-14-42-000 pommelienthijs (P) 2714017191658948728_1.jpg m:/IG_Instaloader/pommelienthijs/Posts/2021-11-24_13-14-42-000 pommelienthijs (P) 2714017191658948728_2.jpg comments json 
> [ 66/238] m:/IG_Instaloader/pommelienthijs/Posts/2021-11-23_16-59-48-000 pommelienthijs (P) 2713405706519841758_1.jpg m:/IG_Instaloader/pommelienthijs/Posts/2021-11-23_16-59-48-000 pommelienthijs (P) 2713405706519841758_2.jpg m:/IG_Instaloader/pommelienthijs/Posts/2021-11-23_16-59-48-000 pommelienthijs (P) 2713405706519841758_3.jpg [ 67/238] m:/IG_Instaloader/pommelienthijs/Posts/2021-11-21_15-38-24-000 pommelienthijs (P) 2711915184299029818_1.jpg m:/IG_Instaloader/pommelienthijs/Posts/2021-11-21_15-38-24-000 pommelienthijs (P) 2711915184299029818_2.jpg m:/IG_Instaloader/pommelienthijs/Posts/2021-11-21_15-38-24-000 pommelienthijs (P) 2711915184299029818_3.jpg [Big smootch] comments json 
> [ 68/238] m:/IG_Instaloader/pommelienthijs/Posts/2021-11-20_11-26-33-000 pommelienthijs (P) 2711063650082285911_1.jpg m:/IG_Instaloader/pommelienthijs/Posts/2021-11-20_11-26-33-000 pommelienthijs (P) 2711063650082285911_2.jpg [Videoclip voor meisjes van ho…] comments json 
> [ 69/238] txt 
> Saved resume information to m:/IG_Instaloader/pommelienthijs/Posts/iterator_IA07fVif.json.xz.
> Saved session to C:\Users\xxxx\AppData\Local\Instaloader\session-xxx.
> 
> Download <Post CWn9B0kogve> of pommelienthijs: 403 when accessing https://scontent-bru2-1.cdninstagram.com/v/t50.2886-16/260216748_196281196006152_3827572863716622542_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjQ4MC5jYXJvdXNlbF9pdGVtLmRlZmF1bHQiLCJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSJ9&_nc_ht=scontent-bru2-1.cdninstagram.com&_nc_cat=100&_nc_ohc=2XiWZaCcJ5UAX9L-bT4&edm=APU89FABAAAA&vs=17907720245252094_3986488486&_nc_vs=HBksFQAYJEdLeVhnZzhJeS1aR2hMSUFBTTRBd1gwOVJSNDFia1lMQUFBRhUAAsgBABUAGCRHQzUtZ3c4VFVmT1JyekFDQU1yNmdndVlWaWNOYmtZTEFBQUYVAgLIAQAoABgAGwGIB3VzZV9vaWwBMBUAACaSwLHvpau9PxUCKAJDMywXQCQzMzMzMzMYEmRhc2hfYmFzZWxpbmVfMV92MREAde4HAA%3D%3D&ccb=7-5&oe=62D69FBA&oh=00_AT91Np1Vz6bN7hCEMWWZdYU2qqmKvFn4tgs9LbMCQmO7iw&_nc_sid=86f79a.
> Download aborted: Query to https://i.instagram.com/api/v1/media/2710344489282808195/info/ responded with "400 Bad Request".
> Errors or warnings occurred:
> Download <Post CWn9B0kogve> of pommelienthijs: 403 when accessing https://scontent-bru2-1.cdninstagram.com/v/t50.2886-16/260216748_196281196006152_3827572863716622542_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjQ4MC5jYXJvdXNlbF9pdGVtLmRlZmF1bHQiLCJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSJ9&_nc_ht=scontent-bru2-1.cdninstagram.com&_nc_cat=100&_nc_ohc=2XiWZaCcJ5UAX9L-bT4&edm=APU89FABAAAA&vs=17907720245252094_3986488486&_nc_vs=HBksFQAYJEdLeVhnZzhJeS1aR2hMSUFBTTRBd1gwOVJSNDFia1lMQUFBRhUAAsgBABUAGCRHQzUtZ3c4VFVmT1JyekFDQU1yNmdndVlWaWNOYmtZTEFBQUYVAgLIAQAoABgAGwGIB3VzZV9vaWwBMBUAACaSwLHvpau9PxUCKAJDMywXQCQzMzMzMzMYEmRhc2hfYmFzZWxpbmVfMV92MREAde4HAA%3D%3D&ccb=7-5&oe=62D69FBA&oh=00_AT91Np1Vz6bN7hCEMWWZdYU2qqmKvFn4tgs9LbMCQmO7iw&_nc_sid=86f79a.
> ```
try to put delay between each request
and remove
--abort-on=400 
from command

**Comment by Nova6K0** [comment]
So the old method, for direct access to the photos (include video thumbnails), continues to work:

`https://www.instagram.com/p/{shortcode}/media/?size=[resolution]`

size = l -> Largue -> High Resolution Photo.

size = m -> Medium  (Default resolution)

size = t -> Thumbnail.

Greetings.

**Comment by thereareno** [comment]
Practical question - when I see the "unable to fetch HQ image", it appears the IL is still downloading an image - is it?

**Comment by afterdelight** [comment]
yes its downloading normal resolution photos

**Comment by denbartman** [comment]
> How can i add a delay from de command prompt?
Won't removing abort on 400 increase the rick of account being locked?

**Comment by Nova6K0** [comment]
> > try to put delay between each request
> > and remove
> > --abort-on=400
> > from command
> 
> How can i add a delay from de command prompt?
> 
> Won't removing abort on 400 increase the rick of account being locked?

It is explained in the program documentation. If you put the parameter:

´--request-timeout N

N = seconds (default 300)´

Also if you need to create a pause or time, between several profiles or between a set of orders, commands ... you can use the Timeout command in Windows or Linux, although it has different parameters. But basically it is worth the same; Put time, before going to the next order (this is worth when you believe, for example, a batch process file).

Greetings.

**Comment by afterdelight** [comment]
i edited the script to put 6 seconds delay in between each request to make it safer

**Comment by thereareno** [comment]
> yes its downloading normal resolution photos

Thank you for your the reply. How do know which ones that downloaded are normal resolution - is there a way to automatically replace them?

**Comment by m-sundman** [comment]
> > yes its downloading normal resolution photos
> 
> Thank you for your the reply. How do know which ones that downloaded are normal resolution - is there a way to automatically replace them?

Yeees, I really want to know this, too. And I would also like to disable the fallback to lower resolution versions.

**Comment by Showmaster3000** [comment]
@thereareno @m-sundman you see that this issue is fixed and closed?
