### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by zeug93** [instaloader/instaloader#1635]
**Describe the bug**
im executing a script in google colab, until last week it worked fine but suddenly im getting this message in the console

Login error: Unexpected response, this might indicate a blocked IP

**To Reproduce**
the error is referenced to the line of login (iniciar_sesion)
in my main i have
             x = InstaGET(usuario, clave)
---->    x.iniciar_sesion()

and what i have in that function is
    def iniciar_sesion(self):
        self.sesion.login(self.user, self.pass)
        print('sesion iniciada --- {0}'.format(self.user))

**Expected behavior**
the expected behavior is to log on the account without problems

**Error messages and tracebacks**
this is the console exit
---------------------------------------------------------------------------

ConnectionException                       Traceback (most recent call last)

[<ipython-input-15-ccc249faf6a3>](https://localhost:8080/#) in <module>()
      3 print('iniciando')
      4 x = InstaGET(user, pass)
----> 5 x.iniciar_sesion()

2 frames

[<ipython-input-10-5ee6a5f1ab22>](https://localhost:8080/#) in iniciar_sesion(self)
     13 
     14     def iniciar_sesion(self):
---> 15         self.sesion.login(self.user, self.pass)
     16         print('sesion iniciada --- {0}'.format(self.user))
     17 

[/usr/local/lib/python3.7/dist-packages/instaloader/instaloader.py](https://localhost:8080/#) in login(self, user, passwd)
    633         :raises TwoFactorAuthRequiredException: First step of 2FA login done, now call
    634            :meth:`Instaloader.two_factor_login`."""
--> 635         self.context.login(user, passwd)
    636 
    637     def two_factor_login(self, two_factor_code) -> None:

[/usr/local/lib/python3.7/dist-packages/instaloader/instaloadercontext.py](https://localhost:8080/#) in login(self, user, passwd)
    251                 raise ConnectionException("Login error: Unexpected response, \"{}\".".format(resp_json['message']))
    252             else:
--> 253                 raise ConnectionException("Login error: Unexpected response, this might indicate a blocked IP.")
    254         if not resp_json['authenticated']:
    255             if resp_json['user']:

ConnectionException: Login error: Unexpected response, this might indicate a blocked IP.

**Instaloader version**
4.9.2

**Comment by rAugustos** [comment]
+1

**Comment by afterdelight** [comment]
got this too, any solution?

**Comment by AyluinReymaer** [comment]
I am having trouble with this as well.

For some reason, instagram decided to log me out of instaloader (and just instaloader. All other devices are properly logged in...).

I had the same instaloader version as the OP, 4.9.2.

Upgraded to the latest version 4.9.4 and having the same issue.

I don't get any error message or stack trace, just the error: `Fatal error: Login error: Unexpected response, this might indicate a blocked IP.`

I went to the source code of instaloader to print the response I'm getting from instagram and this is the response: `{'errors': {'error': ['Sorry, there was a problem with your request.']}, 'status': 'ok', 'error_type': 'generic_request_error'}`

I tried googling this error and found this article which also states that this is due to temp blocked IP: https://www.followchain.org/sorry-problem-request-instagram

But, it's weird that this is the case... I don't have this issue either on my PC or my phone which are using the same account in the same network.

Only instaloader is having this issue...

**Comment by tbrtje** [comment]
Having the same issue

**Comment by 0x113** [comment]
It is still present with 4.9.5

**Comment by m-sundman** [comment]
I've had this problem for a while already. I'm not using any special code, just running an up-to-date instaloader with `--login` and `--password`. It was working just fine, and then suddenly this. I've tried changing the user agent as was suggested in #1758 and removing the session file but those things didn't help either.

The first time this happened I also couldn't log in with my browser without first choosing the "remove this account from this browser" option at the login page. After that logging in with the browser went just fine, but removing the session file didn't help logging in with instaloader.

**Comment by dojoarun** [comment]
I faced this same issue

Solution : I Just use a VPN and run my code again. It works for me.

Hope this will help you

Thank you

**Comment by ewrika** [comment]
> I faced this same issue
> 
> Solution : I Just use a VPN and run my code again. It works for me.
> 
> Hope this will help you
> 
> Thank you

How you use library with vpn/proxie

**Comment by mauronr** [comment]
> How you use library with vpn/proxie

I use Instaloader as a module with  proxy configured via environment variables. It should work if you use it as a command line, too.

I set these variables before running Instaloader.
```
export HTTP_PROXY="<<< PROXY SETTINGS >>>"
export HTTPS_PROXY="<<< PROXY SETTINGS >>>"
```

**Comment by dojoarun** [comment]
If our IP is blocked we can bypass it through using VPN by obtaining a new IP. This is how i solved the issue

**Comment by dojoarun** [comment]
> > I faced this same issue
> > Solution : I Just use a VPN and run my code again. It works for me.
> > Hope this will help you
> > Thank you
> 
> How you use library with vpn/proxie

If our IP is blocked we can bypass it through using VPN by obtaining a new IP. This is how i solved the issue

**Comment by JunedKhan101** [comment]
Facing the same issue, but before receiving the login error Instagram is forcing me to change my password for reasons unknown.
