### ISSUE TITLE
Setting HTTP proxy besides  'HTTP_PROXY' and 'HTTPS_PROXY' env vars

### ISSUE THREAD

**Issue by mauronr** [instaloader/instaloader#1638]
CONTEXT
We run Instaloader inside a docker container serving an API.  We need different requests to our API to assign a proxy in the moment Instaloader connects to Instagram. Each Instagram credential we manage and use to authenticate Instaloader is assigned to a certain geography and we need to use a proxy that's physically hosted in that credential's geography.
 
That means we can't go just assign env vars `HTTP_PROXY` and `HTTPS_PROXY` as used by `requests`, as their value is at the container scope, and we need to set the proxy at the scope of each request.

We tried to "hack" the `context._session` object (a `requests.sessions.Session`) with the code below, but no luck. We can see Instaloader connects  directly to Instagram.
```
il = Instaloader()
il.login(user="some_user", passwd="some_password")

proxies = {
    'http': proxy_url,
    'https': proxy_url
}
il.context._session.proxies = proxies
profile = Profile.from_username(il.context, "some_profile")
```
Is there any other way to set the proxy at the request level?

If not, is this a feature the maintainers would be interested my team contributed to the code base?

PS: We gathered evidence of proxy usage by forcing the underlying `requests` log level to DEBUG, as described here https://secariolabs.com/research/logging-raw-http-requests-in-python

**Comment by aandergr** [comment]
> If not, is this a feature the maintainers would be interested my team contributed to the code base?

Yes! We would be happy to review a pull request for that.

> Is there any other way to set the proxy at the request level?

Yes, technically you could set the proxy-related environment variables programatically for each request, as suggested in https://github.com/instaloader/instaloader/pull/174#issuecomment-577011167. Your assumption that they are at container-scope is wrong.

**Comment by mauronr** [comment]
> Yes, technically you could set the proxy-related environment variables programatically for each request, as suggested in [#174 (comment)](https://github.com/instaloader/instaloader/pull/174#issuecomment-577011167). Your assumption that they are at container-scope is wrong.

[#174 (comment)](https://github.com/instaloader/instaloader/pull/174#issuecomment-577011167) is exactly that we're doing for now, but doesn't meet our needs.

The issue is a race condition between concurrent requests in the same docker container instance because the underlying environment variables are common to all requests running in that instance.

Here's a sequence of events that breaks our usecase:

1. Docker container starts request 1
2. Docker container starts request 2
3. Request 1 sets env var `https_proxy` to proxy_1
4. Request 2 sets env var `https_proxy` to proxy_2
5. Request 1 starts some Instaloader operation, say `Profile.from_username()` 
     Instaloader will fetch data using proxy_2, instead of the intended proxy_1

We believe we'd need the `requests.Session` object inside `InstaloaderContext`[[this](https://github.com/instaloader/instaloader/blob/5e232fd4f521b1700c122827d973fd868c6ae483/instaloader/instaloadercontext.py#L62)] to own the proxy settings and use them in the low-level HTTP requests to Instagram.

BTW, we could force one concurrent request per docker container to prevent the issue, but that would unnecessarily scale the infrastructure horizontally, including much higher cost.

**Comment by aandergr** [comment]
> The issue is a race condition between concurrent requests in the same docker container instance because the underlying environment variables are common to all requests running in that instance.
> 
> Here's a sequence of events that breaks our usecase:
> 
> 1. Docker container starts request 1
> 2. Docker container starts request 2
> 3. Request 1 sets env var `https_proxy` to proxy_1
> 4. Request 2 sets env var `https_proxy` to proxy_2
> 5. Request 1 starts some Instaloader operation, say `Profile.from_username()`
>    Instaloader will fetch data using proxy_2, instead of the intended proxy_1

Request 2 cannot change the environment variables of request 1 if the two requests are executed in different processes. Instaloader itself does not do concurrent requests.

However, as stated in my last comments, we would still be happy to review a pull request implementing a clean way of settings proxies at context level.
