### ISSUE TITLE
Fatal Error: Login: Checkpoint

### ISSUE THREAD

**Issue by NasmodorN** [instaloader/instaloader#1642]
Hi,
Have a problem, cannot download anymore, each time i try, get message : "Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/............/ - follow the instructions, then retry."
With my both acc.
Can someone help me please ?

**Comment by Showmaster3000** [comment]
see https://instaloader.github.io/troubleshooting.html#login-error

**Comment by Marcinolak** [comment]
Any idea how to fix it on Windows?

**Comment by jhough-veritone** [comment]
I am having the same problem now. Before I could log in without an issue but recently Instagram is issuing checkpoint challenges. The program catches the challenge and provides a URL but after following the URL it still issues a challenge.

**Comment by Marcinolak** [comment]
Unfortunately, the script doesn't seem to work. It still prints:
``Instaloader not found.
  pip install [--user] instaloader``
no matter where i execute it. Adding instaloader to PATH does nothing.

**Comment by al4sk4s** [comment]
> see https://instaloader.github.io/troubleshooting.html#login-error

but how would I implement this code to read a google chrome cookie?

**Comment by vicmac-github** [comment]
> pip install [--user] instaloader



> I am having the same problem now. Before I could log in without an issue but recently Instagram is issuing checkpoint challenges. The program catches the challenge and provides a URL but after following the URL it still issues a challenge.

This can be solved waiting a few days and try again?
