### ISSUE TITLE
Cant scrape any username

### ISSUE THREAD

**Issue by MMJv3** [instaloader/instaloader#1643]
**Describe the bug**
Cant scrape any username
**To Reproduce**
(e.g. Instaloader command line)
instaloader command line, trying to scrape a username with any args dosent scrape that username and says it dosent exist
**Expected behavior**
A clear and concise description of what you expected to happen (even if it seems obvious).
it would scrape the username with the args specifiec
**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.
![image](https://user-images.githubusercontent.com/36246145/179564794-a25c1fdf-312c-4c62-9997-d971643f0f36.png)
**Instaloader version**
`instaloader --version` output.
4.9
**Additional context**

**Comment by Showmaster3000** [comment]
You are using an old version of instaloader. Update to the latest and this problem should go away.
