### ISSUE TITLE
Since today, any request gets "Redirected to login page. Use --login."

### ISSUE THREAD

**Issue by Florentn** [instaloader/instaloader#1645]
I have an algo that runs daily to get posts from a select number of accounts with about 1 minute delay between each request.
It has been working for a few months now with any hiccup using version 4.9
Today I first got faced with 'Could not find "window._sharedData" ' error which prompted me to upgrade the library to 4.9.2
Since then, I'm getting "Redirected to login page. Use --login." right away. I have seen it happen a few times in the past for very specific accounts or when I had a too short delay but relaunching the algo would be enough to get over those hiccups.

I would expect to get the posts linked to the account requested
instaPosts = instaloader.Profile.from_username(L.context, club["instagram"]).get_posts()

The "Error" I'm getting is "Redirected to login page. Use --login."
This looks like something systemic, as if Instagram had changed something in their system which is causing this issue.

Is this temporary? Is it due to a change with Instagram? Is there a solution besides logging in?

Thanks in advance

**Comment by Showmaster3000** [comment]
The error message says it all, you have to login to proceed. As a result of fixing the "window._sharedData" error, it is possible that you reach the anonymous limit earlier. See description at [#1575 comment](https://github.com/instaloader/instaloader/issues/1575#issuecomment-1152371229) in similar context:
> The fix partly switches to the iphone json, which maybe brings up other problems like faster reaching the rate limit, but currently no other solution is available.
> Downloading without logging in is possible but requests are limited by Instagram. Downloading stories requires to login.

**Comment by JJsmabrums** [comment]
I have had the same issues as of yesterday. 
If I use sessionfiles or stay logged in for multiple profile download triggers, no account will download and so I have to use --login for each account and then delete sessionfile for each account after download. And that usually trips out the account and I have to go in and click "this was me" like 10 times on each instances. They asked me to reset my password today. Wish insta would allow you to add trusted ips/connections. 

My code is just a bat file that runs each morning.  Cringe if you must, but its on the edge of my ability right now. 1 main bat that deletes the previous session, runs instaloader + an args.txt for each profile, waits 5 mins and then loads the next:

@echo on
del c:\Users\(myusername)\AppData\Local\Instaloader\session-(myusername)
instaloader +profile1.txt
TIMEOUT /T 300
del c:\Users\(myusername)\AppData\Local\Instaloader\session-(myusername)
instaloader +profile2.txt
TIMEOUT /T 300
del c:\Users\(myusername)\AppData\Local\Instaloader\session-(myusername)
instaloader +profile3.txt
TIMEOUT /T 300
...(a bunchmore profiles but you get the jist)
echo off
echo %date%, %time% >> DailyCollector_Lastrun.txt
echo Current date/time is %date%, %time%.
@pause
exit

The text files is for each profile and location on my server where I want things dumped: 
--login=(myusername)
--password=(mypassword)
(profile I want)
--no-captions
--no-video-thumbnails
--no-metadata-json
--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
--dirname-pattern=//(UNC folder path).

**Comment by Florentn** [comment]
> The error message says it all, you have to login to proceed. As a result of fixing the "window._sharedData" error, it is possible that you reach the anonymous limit earlier. See description at [#1575 comment](https://github.com/instaloader/instaloader/issues/1575#issuecomment-1152371229) in similar context:
> 
> > The fix partly switches to the iphone json, which maybe brings up other problems like faster reaching the rate limit, but currently no other solution is available.
> > Downloading without logging in is possible but requests are limited by Instagram. Downloading stories requires to login.

It used to work with having the need to login.
So I did login.
I got to the checkpoint to confirm it was me....and it seemed to work fine but since I didnt need to do any scraping. I stopped it. 

When I wanted to restart it, I once again got prompted to the checkpoint but this time, relaunching the scraping, led to another checkpoint....without never being able to get past it. I did try the firefox workaround. Since I run the algo on a remote server, I copied the cookie to it, ran the script which seemed to work fine...but running the procedure still wouldnt work

As things stand right now, and seeing that other users are facing the same issues as I am, it does look like a pretty harduous issue. I'd love to help but I dont think I'm good enough to help out. Hope you guys manage to resolve the issue and if you do, i'd be glad to contribute monetarily.
