### ISSUE TITLE
JSON Query to <username>/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

### ISSUE THREAD

**Issue by Sabrebar** [instaloader/instaloader#1646]
**Describe the bug**
Since yesterday, I get this error while everything was working fine before :
`JSON Query to <username>/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]`
where `<username>` is the account im trying to query

**To Reproduce**
any query using instaloader

**Expected behavior**
Instaloader is supposed to fetch the datas as usual

**Instaloader version**
4.9.2

**Comment by Florentn** [comment]
Pretty sure that's a 4.9 error. 4.9.2 tells you that you need to login

**Comment by lucianor** [comment]
same error here

L = instaloader.Instaloader(user_agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0")
L.login(user, pass)
profile = instaloader.Profile.from_username(L.context, userProfile)

**Comment by Sabrebar** [comment]
I found the issue, you guys were right. I had two version of instaloader with two version of python.
So `instaloader --version` were showing 4.9.2 while I was actually using 4.9 starting the file with python.
Sorry for the inconvenience 😅
