### ISSUE TITLE
Download posts with specific mentions

### ISSUE THREAD

**Issue by windu777** [instaloader/instaloader#1647]
Hi! I just started using instaloader and I can't find a way to download posts that mention a specific username (either mentioned in the post or comments).
Is it possible to do that with instaloader?

**Comment by windu777** [comment]
Just to make it clearer. For example if you search for an account without @, on the mobile app, it will show a list of Top posts that mention that account (accounts with many followers show other top accounts, idk why).
I wonder if it's possible to retrieve that list of posts, which mention that username either on the caption or comments

**Comment by aandergr** [comment]
This is not yet immediately possible with Instaloader's current features, but I could imagine that with some research and development effort it would be possible to execute this query with Instaloader and further process the result in Instaloader structures.
