### ISSUE TITLE
Instaloader is not "waiting" when rate limit hits

### ISSUE THREAD

**Issue by jakku13** [instaloader/instaloader#1648]
Up until yesterday, Instaloader would impose a self wait once many requests have been processed in a short time with a message below:

Too many queries in the last time. Need to wait 300 seconds...

I'm not seeing this behavior anymore. Instaloader refuses to connect again once my rate limit hits. Can someone tell me how I can get across this issue? Would clearing the session cookies help me?

**Comment by Nova6K0** [comment]
They are increasingly limiting requests by IP. It is what gives me the impression.

Greetings.

**Comment by aandergr** [comment]
Your bug description is incomplete; however, this might be related to #1616.
