### ISSUE TITLE
Python get_feed_posts() issue

### ISSUE THREAD

**Issue by Tydoki** [instaloader/instaloader#1650]
**Describe the bug**
Python error `'NoneType' object is not subscriptable` when running code that i've used for awhile 
Started a few days ago around the same time the #1633 (I assume unrelated just giving time frame)

**To Reproduce**
```
        L = instaloader.Instaloader()
        L.load_session_from_file("xxx")
        L.filename_pattern = "{profile}_{date_utc}_UTC"
        L.dirname_pattern = "./data/images/insta/{target}"
        L.download_video_thumbnails = False

        z = 0
        posts = []
        for x in L.get_feed_posts():   <-- ERROR HERE
            folder_name = f"{x.owner_username}-{str(x.mediaid)}"
            if os.path.exists(f"./data/images/insta/{folder_name}"):
                z = z + 1
                if z == 20:
                    break
            else:
                posts.insert(0, x)
                
        ....
```
         
**Error messages and tracebacks**       
```
Loaded session from C:\Users\xxx\AppData\Local\Instaloader\session-johnrobins30002.
Job "Bot.instaloader_setup (trigger: cron[minute='0,30', second='0'], next run at: 2022-07-21 13:30:00 EDT)" raised an exception
Traceback (most recent call last):
  File "D:\Programs\Python310\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "D:\xxx\Coding\Bots\xxxBot\lib\bot\__init__.py", line 202, in instaloader_setup
    for x in L.get_feed_posts():
  File "D:\Programs\Python310\lib\site-packages\instaloader\instaloader.py", line 1064, in get_feed_posts
    feed = data["user"]["edge_web_feed_timeline"]
TypeError: 'NoneType' object is not subscriptable
```

**Version**
4.9.2

**Expected Behavior**
No error

**Comment by chrisbuetti** [comment]
Where are you providing the username?

**Comment by Tydoki** [comment]
> Where are you providing the username?

2nd line of the code
`L.load_session_from_file("xxx")`

**Comment by chrisbuetti** [comment]
Is that your username? Or the account you are trying to scrape?

**Comment by Tydoki** [comment]
> Is that your username? Or the account you are trying to scrape?

Obviously mine?

**Comment by Thammus** [comment]
Unfortunately, I am not yet able to reproduce this issue. I just executed `get_feed_posts()` and was able to download over 100 posts without any error.

**Comment by Tydoki** [comment]
> Unfortunately, I am not yet able to reproduce this issue. I just executed `get_feed_posts()` and was able to download over 100 posts without any error.

Odd. Wonder why mine isn't working.

**Comment by leunglong0123** [comment]
it seems maybe problem related to specific instagram account
I have multiple accounts fetching and only a single account have this error
