### ISSUE TITLE
Use custom headers for http requests

### ISSUE THREAD

**Issue by Sabrebar** [instaloader/instaloader#1652]
**Provide us a use case of the feature**
Sometimes, when I use a lot instaloader with the same account, my account is locked until I type a code sent via email or until I change my passeword. I think this is because the headers sent in the http requests by instaloader are different than the headers I send with my browser. Instagram detects instaloader as a Linux os, which is not commun and triggers the security protocol.

**Describe the solution you'd like**
Currently, we instance the loader like this `L = instaloader.Instaloader()`
One should be able to precise custom headers like this 
`
DefaultHeaders = {'Accept-Encoding': 'gzip, deflate',
                  'Accept-Language': 'en-US,en;q=0.8',
                  'Connection': 'keep-alive',
                  'Content-Length': '0',
                  'Host': 'www.instagram.com',
                  'Origin': 'https://www.instagram.com',
                  'Referer': 'https://www.instagram.com/',
                  'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 ' \
           '(KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36',
                  'X-Instagram-AJAX': '1',
                  'X-Requested-With': 'XMLHttpRequest'}
L = instaloader.Instaloader(headers = DefaultHeaders)`

where headers is an optional argument.

What do you guys think about it?

**Comment by aandergr** [comment]
> I think this is because the headers sent in the http requests by instaloader are different than the headers I send with my browser. Instagram detects instaloader as a Linux os, which is not commun and triggers the security protocol.

There is an option `--user-agent`. Are there any other headers different from what your browser sends?
