### ISSUE TITLE
Unable to fetch images by using tags

### ISSUE THREAD

**Issue by 7wiCey** [instaloader/instaloader#1656]
**Describe the bug**
Unable to fetch images by using tags 

**To Reproduce**
JSON Query to explore/tags/wallgt/: Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]
JSON Query to explore/tags/wallgt/: Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]

**Expected behavior**
There should be able to pull image from it

**Comment by 7wiCey** [comment]
Codes FYR

`import os
import instaloader
import uuid

from instaloader import Hashtag

L = instaloader.Instaloader()
print(L)
HASHTAG = "demo"
hashtag = Hashtag.from_name(L.context, HASHTAG)
print(hashtag)

for post in hashtag.get_posts():
    L.download_post(post, target="#"+hashtag.name)
`

**Comment by Showmaster3000** [comment]
duplicate of pinned #1588.

**Comment by xozxro** [comment]
then fix it?

**Comment by Showmaster3000** [comment]
@xozxro you are free to help solving the problem. Otherwise be patient.
