### ISSUE TITLE
Corrupted images 

### ISSUE THREAD

**Issue by AmrWassiem** [instaloader/instaloader#1659]
After i had downloaded a profile without metadata json or compress json, i got only 12 (from 269) normal photos, anrd the rest are corrupted, i tried to open them in binary viewer and found all of them bytes are `ÿ`

The command which i used :
`instaloader --no-metadata-json --no-compress-json --login "username"  "profile name"`

The profile is exist and public

**Comment by thereareno** [comment]
> After i had downloaded a profile without metadata json or compress json, i got only 12 (from 269) normal photos, anrd the rest are corrupted, i tried to open them in binary viewer and found all of them bytes are `ÿ`
> 
> The command which i used : `instaloader --no-metadata-json --no-compress-json --login "username" "profile name"`
> 
> The profile is exist and public

I've had this happen a few times; each time, the corrupted images were different. After several more attempts, everything downloaded correctly. Not sure if that helps.
