### ISSUE TITLE
Mobile App User Agent?

### ISSUE THREAD

**Issue by Blazingfairy** [instaloader/instaloader#1661]
I use the instagram app on a mobile device. Is it possible to retrieve the user agent of my profile's session on the mobile device? How may one do so?

**Comment by Blazingfairy** [comment]
In my research I've come across this website: https://developers.whatismybrowser.com/useragents/explore/software_name/instagram/ but it's daunting to decipher which exactly is my user agent

**Comment by giovsta** [comment]
I provided some details [here ](https://github.com/instaloader/instaloader/issues/1702#issuecomment-1222372535)on how you can parse a phone's user agent
