### ISSUE TITLE
Only 60 posts with location as target

### ISSUE THREAD

**Issue by pvita** [instaloader/instaloader#1664]
**Describe the bug**
I'm triyng to collect data from a location, but instaloader doesn't take more then 60 posts.
After them, it continues to collect the same contents.

**To Reproduce**
instaloader %104031319657620 --no-pictures --no-videos --metadata-json --login #####

**Expected behavior**
I would take all the posts published in this place.

**Instaloader version**
4.9.2

**Comment by aandergr** [comment]
Duplicate of #1341.
