### ISSUE TITLE
Doesn't work anymore "window._sharedData" error.

### ISSUE THREAD

**Issue by Gitphex** [instaloader/instaloader#1665]
**Describe the bug**
Simply doesn't work anymore.

**To Reproduce**
(e.g. Instaloader command line)

.\instaloader ylegall

**Expected behavior**

To download the images and video from that user.

**Error messages and tracebacks**

JSON Query to ylegall/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

**Instaloader version**
`instaloader --version` output.

Version 4.9.2

**Additional context**

I think, but not sure, that Instagram changed something.

**Comment by Showmaster3000** [comment]
Are you sure that you are using v4.9.2? cause your description looks like #1646 and the error like #1553.

**Comment by Qypol342** [comment]
on 4.9.2 and I have the same issues

**Comment by veronicawonghy** [comment]
> I've check `python3 -m pip list` and it was a diffrent version there, simple fix: `python3 -m pip install instaloader -U `

this fix works for me.
