### ISSUE TITLE
HTTP Error code 410 and then instaloader skip the available picture too

### ISSUE THREAD

**Issue by rayman0530** [instaloader/instaloader#1669]
### Describe the bug
When trying to download highlights from a profile, Instagram gives an HTTP error. But I can see some pictures of the post from web.

### To Reproduce
The command I have used is instaloader PROFILE --login=USER -- -BiZqjS3lOju

### Expected behavior
Downloads the available pictures.

### Error messages and tracebacks
Instaloader gives the following errors:
download_pic(): HTTP error code 410. [retrying; skip with ^C]
download_pic(): HTTP error code 410. [retrying; skip with ^C]
-BiZqjS3lOju: download_pic(): HTTP error code 410.

### Instaloader version
Version 4.9.2

**Comment by aandergr** [comment]
This post also returns a 410 when opening in the web app. No bug here.
