### ISSUE TITLE
JSON Query to api/v1/users/web_profile_info/?username=profile: HTTPSConnectionPool

### ISSUE THREAD

**Issue by ajayghoshrr** [instaloader/instaloader#1671]
**Describe the bug**
Getting HTTPSConnectionPool Issue

**To Reproduce**
instaloader profile "foodie_bebo"

**Expected behavior**
There should not be any error

**Error messages and tracebacks**
C:\MyScripts\ML\Practice\instagram\t\test>instaloader profile "foodie_bebo"
JSON Query to api/v1/users/web_profile_info/?username=profile: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/web_profile_info/?username=profile (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)'))) [retrying; skip with ^C]
JSON Query to api/v1/users/web_profile_info/?username=profile: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/web_profile_info/?username=profile (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)'))) [retrying; skip with ^C]
profile: JSON Query to api/v1/users/web_profile_info/?username=profile: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/web_profile_info/?username=profile (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)')))
JSON Query to api/v1/users/web_profile_info/?username=foodie_bebo: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/web_profile_info/?username=foodie_bebo (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)'))) [retrying; skip with ^C]
JSON Query to api/v1/users/web_profile_info/?username=foodie_bebo: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/web_profile_info/?username=foodie_bebo (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)'))) [retrying; skip with ^C]
foodie_bebo: JSON Query to api/v1/users/web_profile_info/?username=foodie_bebo: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/web_profile_info/?username=foodie_bebo (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)')))

**Instaloader version**
4.9.2

**Comment by Showmaster3000** [comment]
first the keyword `profile` should be omited, it is treated as the target/nickname "profile". (see your output)
Concerning your problem with ssl connection: I cannot replicate this problem. Are you sure that you do not have any proxy software like anti-virus/malware or anything on your pc? or similar thing in your connection line?

**Comment by james-msr** [comment]
same problem. locally everything is fine, but when I deploy application to a server it gives this error

**Comment by samuel06santos** [comment]
It's giving me the same problem
`JSON Query to api/v1/users/web_profile_info/?username={INSTAGRAM_USERNAME} : 404 Not Found [retrying; skip with ^C]`
