### ISSUE TITLE
It stops downloading?

### ISSUE THREAD

**Issue by FatalFlawz** [instaloader/instaloader#1672]
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/?next=/graphql/query
myusername: Redirected to login page. Use --login.
Errors or warnings occurred:
myusername: Redirected to login page. Use --login.

It goes along perfect then i started to get this error and it would stop the download? Could someone help thanks

**Comment by Showmaster3000** [comment]
duplicate of #1617 (and #1666).

**Comment by FatalFlawz** [comment]
My bad did not read those
