### ISSUE TITLE
download_pic(): HTTP error code 500. [retrying; skip with ^C]

### ISSUE THREAD

**Issue by aidilaryanto** [instaloader/instaloader#1674]
**Describe the bug**
HTTP error code 500

**To Reproduce**
Highlights from Profile

**Expected Behavior**
There should be download all hightlights without error

**Error messages and tracebacks**

> download_pic(): HTTP error code 500. [retrying; skip with ^C]

**This is my command** 

> instaloader --login=USERNAME +args.txt --highlights --igtv PROFILE --no-iphone --quiet

**Comment by Showmaster3000** [comment]
very minimal report. for bug reporting do not use `--quiet` parameter.
additionally error 500 is server side, not a bug in instaloader.

**Comment by aidilaryanto** [comment]
> 

I use `--quiet` because highlights title contain emoji.
