### ISSUE TITLE
Getting more frequent 400 error

### ISSUE THREAD

**Issue by christoarmani** [instaloader/instaloader#1676]
I am aware of Instagrams and Instaloaders rate limitations, but I have noticed that I am getting a 400 error more frequently and having to unlock my account more often. I am curious to see if others have been noticing the same thing. 

For context, I use the +args.txt method in the command line to download. Within my file I am calling the following arguments:

```
--login=username001
--password=pasw*rd
--abort-on=400
--abort-on=403
--abort-on=429
--no-metadata-json
--no-profile-pic
--no-caption
--filename-pattern={profile}_{filename}
```

I wonder if I should be using the [session login](https://instaloader.github.io/cli-options.html#cmdoption-sessionfile) or if Instagram has been further cracking down on downloads.

**Comment by Showmaster3000** [comment]
propably duplicate of #1633.
also incomplete bug report!

**Comment by afterdelight** [comment]
you can write it like --abort-on=400,403,429
