### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by delameter** [instaloader/instaloader#1679]
**Describe the bug**
DNS error even using VPN tunnel

**To Reproduce**
```
instaloader --profile <whatever>
```

**Expected behavior**
Application works

**Error messages and tracebacks**
```
HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/web_profile_info/?username=whatev (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feb05188a00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')) [retrying; skip with ^C]
```

**Instaloader version**
```
> instaloader --version
4.9.2
```

**Additional context**
Google Chrome was refusing to resolve instagram's address too, but I solved it by setting CloudFlare DNS server for Chrome. Unfortunately, there seems no way to do the same thing for the app.

**Comment by Showmaster3000** [comment]
This is not a bug in instaloader!

**Comment by delameter** [comment]
Yeah.. it's not a bug. But is there a way to make things work in my case?
