### ISSUE TITLE
Feature : Get highlight by his ID

### ISSUE THREAD

**Issue by json1c** [instaloader/instaloader#1682]
**Provide us a use case of the feature**
This feature will allow you to get a highlight by its ID. Useful if you do not know the author and have only link to the highlight

**Describe alternatives you've considered**
Get a profile and then its highlights. But this will not work when there is only a link to the highlight.

**If the feature request is accepted, would you be willing to submit a pull request?**
Maybe

**Additional context**
https://www.instagram.com/s/aGlnaGxpZ2h0OjE3OTMyOTA5NDgxMTQzNjky?story_media_id=2817727749675458468&igshid=YmMyMTA2M2Y=

This is how the highlight link looks like.

`aGlnaGxpZ2h0OjE3OTMyOTA5NDgxMTQzNjky` - base64.
`2817727749675458468` - storyitem ID

If we decode this, we get `highlight:17932909481143692` - this is the highlight ID

This feature will allow you to get and download the highlight (or his storyitem) only from the highlight url

**Comment by 12dasad** [comment]
Good 
We want that

**Comment by afterdelight** [comment]
interesting

**Comment by aandergr** [comment]
Thanks for your suggestion. Yes, it would be nice to have a `Highlight.from_mediaid` to get a highlight by its mediaid.
