### ISSUE TITLE
Problem with highlights download

### ISSUE THREAD

**Issue by awilliansd** [instaloader/instaloader#1686]
Hi guys,

I attached a picture with error.

![image](https://user-images.githubusercontent.com/4139802/183459424-f8cd5f9a-6e49-4e17-84c8-cbad0a01d7a8.png)

**Comment by awilliansd** [comment]
Some information?

**Comment by Showmaster3000** [comment]
the label says it: you missed the issue template. Your screenshot is cropped. Too less (not to say no) information to help you.

**Comment by awilliansd** [comment]
There is no information, I cropped just the error, not the private information.
