### ISSUE TITLE
 The term 'instaloader' is not recognized

### ISSUE THREAD

**Issue by DrSpeedy2** [instaloader/instaloader#1687]
instaloader : The term 'instaloader' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ instaloader cobratate
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (instaloader:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by DrSpeedy2** [comment]
?????????????????????

**Comment by Showmaster3000** [comment]
patience is everything. Btw. you missed important things. and also the issue template.
