### ISSUE TITLE
How to check only new highlights?

### ISSUE THREAD

**Issue by uvx0ol** [instaloader/instaloader#1688]
Hi guys, 

I'm wondering how to prevent Instaloader from checking **all** the highlights on an account.

Even filtering by date (like below) will not stop Instaloader.  It will check, if there is a new picture/video in **each and every highlight on an account** (even very old ones). It generates many unnecessary requests and makes Instagram block accounts. I would like to check only 2-3 newest highlights. 

--post-filter="date_utc >= datetime(2022, 8, 8)" --stories --highlights --tagged --igtv --fast-update target
--post-filter="date_utc <= datetime(2022, 8, 8)" --stories --highlights --tagged --igtv --fast-update target

Thank you for any suggestion.

**Comment by afterdelight** [comment]
you can't its the program nature

**Comment by uvx0ol** [comment]
Well, then it means if you run Instaloader as cronjob you cannot rely on it. It will make your account softbanned (of totally banned if you're unlucky) because this can easily generate 50 unnecessary requests per 1 account you're scraping. This should be possible to fix.
