### ISSUE TITLE
Error output (what am I doing wrong)?

### ISSUE THREAD

**Issue by tsmitsmitonline** [instaloader/instaloader#1691]
What am I doing wrong?

Input:
instaloader profile USERNAME (I actually used a real Instagram account username)

Output:
JSON Query to profile/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to profile/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

HTTP redirect from https://www.instagram.com/web/search/topsearch/ to https://www.instagram.com/accounts/login/?next=/web/search/topsearch/
profile: Redirected to login page. Use --login.
JSON Query to USERNAME/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to USERNAME/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

HTTP redirect from https://www.instagram.com/web/search/topsearch/ to https://www.instagram.com/accounts/login/?next=/web/search/topsearch/
USERNAME: Redirected to login page. Use --login.

Errors or warnings occurred:
profile: Redirected to login page. Use --login.
USERNAME: Redirected to login page. Use --login.

**Comment by Showmaster3000** [comment]
what's wrong? You are using an outdated version. Update and it should work.

**Comment by tsmitsmitonline** [comment]
I use the latest version, but can't get out of the loop: 
----
~/insta-loader$ instaloader --version 4.9.3
~/insta-loader$ instaloader --login piethendriks232
Session file does not exist yet - Logging in.
Enter Instagram password for piethendriks232: 
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/AXGEvGXLoOaR2UhRVu8LAJWP93GPulqxQfHho5ad8aAeWhBXK3Tao0P0SuTCVse902VGuCo/Afx5s2_UCVvfAcpXU34-33_K2xSb5KS91CqEV5BICzjOzFqr-gK7o-vpFZEfvh30WtQ2Dzhlue7u7A/ffc_LsWezNKdMETNvcJuzayGngaNIohK4IZj6cQ60AHfZlADQ1dXem9B6Yd1q5mGaeNT/ - follow the instructions, then retry.
----
When I go to the browser and hit 'it was me', I come into a loop when I run the "~/insta-loader$ instaloader --login piethendriks232" command.

How to fix?

**Comment by computersandstuff** [comment]
> ## I use the latest version, but can't get out of the loop:
> ## ~/insta-loader$ instaloader --version 4.9.3
> ~/insta-loader$ instaloader --login piethendriks232
> Session file does not exist yet - Logging in.
> Enter Instagram password for piethendriks232:
> Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/AXGEvGXLoOaR2UhRVu8LAJWP93GPulqxQfHho5ad8aAeWhBXK3Tao0P0SuTCVse902VGuCo/Afx5s2_UCVvfAcpXU34-33_K2xSb5KS91CqEV5BICzjOzFqr-gK7o-vpFZEfvh30WtQ2Dzhlue7u7A/ffc_LsWezNKdMETNvcJuzayGngaNIohK4IZj6cQ60AHfZlADQ1dXem9B6Yd1q5mGaeNT/ - follow the instructions, then retry.
> When I go to the browser and hit 'it was me', I come into a loop when I run the "~/insta-loader$ instaloader --login piethendriks232" command.
> 
> How to fix?

I have the same issue: When prompted to allow request I do so. When I go back the session was not saved and I have to type my password and accept the suspicious request again. I did have a working version on another computer. I reinstalled python3, pip3, etc and still the same issue. I am on windows10
