### ISSUE TITLE
How do I make instaloader make folders automatically for stories, posts, reels, etc.

### ISSUE THREAD

**Issue by KazKaz90** [instaloader/instaloader#1693]
Is it possible to make folders automatically for stories, posts, reels etc. and put the downloads in their respective folders/directory? I want it to be more organized, Sorry but I don't really know much about this

**Comment by KazKaz90** [comment]
For example, when downloading from a profile, instaloader will organize the type of media downloaded and place it in a folder named after the type of media inside the user's profile folder.

**Comment by KazKaz90** [comment]
> You can read the documentation here: https://instaloader.github.io/basic-usage.html#filename-specification
> To specify the folders pattern, use the `--dirname-pattern` and the desired pattern.

It works, but how do I place it in the username folder of the user's profile? The post, reels, and so on Also, what are the possible patterns?

This is what I've done. Please let me know if anything is incorrect or what I missed.
 `--dirname-pattern={feed,stories,reels,igtv,highlights,post}`

**Comment by KazKaz90** [comment]
I think I did it incorrectly, it only downloads the post, and I believe you can only set one target.

**Comment by NicoWeio** [comment]
> you can only set one target

You can definitely pass multiple targets, like this: `instaloader … :stories someguy anotherguy`. Regarding your directory structure, I'm not sure what you are asking for.

**Comment by KazKaz90** [comment]
@NicoWeio 
> You can definitely pass multiple targets, like this: `instaloader … :stories someguy anotherguy`.

Should I removed the *commas*?, I think you're implying that it's should be *space* in.

> Regarding your directory structure, I'm not sure what you are asking for.

When downloading a profile, I want to have the `reels, highlights, post, story` inside the user's profile directory. The screenshot below should probably make it clear to understand, I hope.

![Screenshot_20220820-060204.png](https://user-images.githubusercontent.com/90075041/185712959-d4c8ef2c-0f3c-4baf-8df1-1e78ad51a476.png)

**Comment by NicoWeio** [comment]
> Should I removed the commas?, I think you're implying that it's should be space in.

Indeed, the targets should be at the end of the command and separated by spaces. 
I don't see where you had commas in the first place, though. `--dirname-pattern` has nothing to do with this.

---
> When downloading a profile, I want to have the reels, highlights, post, story inside the user's profile directory.

How about `instaloader --dirname-pattern={profile} --filename-pattern={typename}/{date_utc}_UTC target1 target2 …`?
You can add `--title-pattern={typename}/{date_utc}_UTC` to also save things like profile pictures in subdirectories.

**Comment by cam-au** [comment]
I tried the above, but am getting an error.

```
instaloader.exe : The command parameter was already specified.
At line:1 char:1
+ instaloader --dirname-pattern={profile}/{typename} profile #########
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParameterBindingException
    + FullyQualifiedErrorId : ParameterSpecifiedAlready
```

**Comment by NicoWeio** [comment]
@cam-au, I can't reproduce this on Linux – `instaloader --dirname-pattern={profile} --filename-pattern={typename}/{date_utc}_UTC someprofile` works for me, and I don't have a Windows install to test against. Maybe someone else can help.

**Comment by cam-au** [comment]
I read the error and because it was referring to the instaloader.exe file, I decided to uninstall it properly
`pip3 uninstall instaloader`
And then unzip a clean version of the package and not run the install via python.

Still had the same issue running it via Powershell with the commands
`py instaloader.py --dirname-pattern#######...`
But it referenced the py file, not the exe so I decided to have a look at the code.

Within the Instaloader-4.9.3/instaloader/instaloader.py file, I found the relevant lines and made the below changes to Line 242 & 243:
```
        # configuration parameters
        self.dirname_pattern = "Profiles/{target}"
        self.filename_pattern = "{typename}/{date_utc}_UTC"
```
And now it works. Permanent solution, which is what I wanted and I did have to create the /Profiles/ folder manually (I wanted to store them in a sub directory rather than the app root).

Not an ideal solution, looks like there is some reason the app wont allow changes to dirname-pattern from the prompt and locks it as per the py or exe
