### ISSUE TITLE
Getting exception "ConnectionException("Login: Checkpoint required. Point your browser to " when trying to Login

### ISSUE THREAD

**Issue by prateek-sibit** [instaloader/instaloader#1694]
I run a simple script that logs in and performs some actions. Until now I hadn't been receiving any login exceptions, I'm running this on the same machine I usually do but am receiving this exception 

raise ConnectionException("Login: Checkpoint required. Point your browser to "
instaloader.exceptions.ConnectionException: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/<ID>/ - follow the instructions, then retry.

Does anyone know how to fix this? First time experiencing this issue. Would appreciate any help.

**Comment by fireattack** [comment]
Your account is flagged. Try to login on web to see if it shows something strange. Resolve them, and re-login with Instaloader (make sure to delete your old session file).

**Comment by Showmaster3000** [comment]
also see https://instaloader.github.io/troubleshooting.html#login-error
duplicate of #1642.

**Comment by afterdelight** [comment]
me too i got this issue, open instagram on web then approve suspicious login then paste the challange link. it solved the problem for me

**Comment by prateek-sibit** [comment]
> also see https://instaloader.github.io/troubleshooting.html#login-error duplicate of #1642.
This worked. Had to make the change for the script to use load_session_from_file instead of the login method. Following the steps mentioned it worked perfectly. Thanks for the help!

**Comment by afterdelight** [comment]
> > also see https://instaloader.github.io/troubleshooting.html#login-error duplicate of #1642.
> > This worked. Had to make the change for the script to use load_session_from_file instead of the login method. Following the steps mentioned it worked perfectly. Thanks for the help!

could you show me the modified script? maybe useful for the future
