### ISSUE TITLE
Can't download specific old really low quality posts error 400

### ISSUE THREAD

**Issue by KazKaz90** [instaloader/instaloader#1695]
**Describe the bug**

*Reminder:* **The posts are little bit NSFW**

Specific old posts from user can't be downloaded ``Errors or warnings occurred:                          Download <Post CEL2H4NHW49> of nagaimariaa: download_pic(): HTTP error code 400.
Download <Post CDDcN-tnrS3> of nagaimariaa: download_pic(): HTTP error code 400.``

**To Reproduce**
`instaloader --login USERNAME --no-video-thumbnails --no-captions --no-metadata-json nagaimariaa`

**Expected behavior**
Should download because these post are still available on IG

**Error messages and tracebacks**
`Errors or warnings occurred:                          Download <Post CEL2H4NHW49> of nagaimariaa: download_pic(): HTTP error code 400.
Download <Post CDDcN-tnrS3> of nagaimariaa: download_pic(): HTTP error code 400.`

**Instaloader version**
4.9.3 [Termux]

**Additional context**
I tried using a VPN, but it's still not downloading. I'm not sure what the issue is, but it's probably because it's an old post with poor quality and not even at 1000 dimensions. It can be downloaded with an app called Instander though, also tried only downloading them as single post and with `--no-iphone` option but still getting `HTTP error code 400`.

**Comment by fireattack** [comment]
Your error message is ambiguous. Which exact post?

I can download Post CEL2H4NHW49 fine.

Post CDDcN-tnrS3 does have no video but that's the same if I visit via instagram.com.

**Comment by fireattack** [comment]
Note: Post `CDDcN-tnrS3` claims to be "GraphVideo" but video is apparently broken on Instagram's end. The `video_url` field is `https://static.cdninstagram.com/rsrc.php/null.jpg` which gives HTTP 400.

**Comment by KazKaz90** [comment]
> Your error message is ambiguous. Which exact post?

Both of them

> I can download Post CEL2H4NHW49 fine.

I can't download both of them, I always get HTTP error 400

**Comment by KazKaz90** [comment]
> Note: Post `CDDcN-tnrS3` claims to be "GraphVideo" but the video is apparently broken on Instagram's end. 
> 
> The graphql `video_url` field is `https://static.cdninstagram.com/rsrc.php/null.jpg` which gives HTTP 400.

I see, how about CEL2H4NHW49 I still can't download it even as a single post download `instaloader --login USERNAME --no-video-thumbnails --no-captions --no-metadata-json -- -CEL2H4NHW49`

**Comment by KazKaz90** [comment]
``.../DCIM/Instagram $ instaloader --login USERNAME --no-video-thumbnails --no-captions --no-metadata-json -- -CEL2H4NHW49 -v
Loaded session from /data/data/com.termux/files/home/.config/instaloader/session-USERNAME.
Logged in as USERNAME.
-CEL2H4NHW49/2020-08-22_08-35-38_UTC_1.jpg download_pic(): HTTP error code 400. [retrying; skip with ^C]
download_pic(): HTTP error code 400. [retrying; skip with ^C]
-CEL2H4NHW49: download_pic(): HTTP error code 400.
-v: Fetching Post metadata failed.
Saved session to /data/data/com.termux/files/home/.config/instaloader/session-USERNAME.

Errors or warnings occurred:
-CEL2H4NHW49: download_pic(): HTTP error code 400.
-v: Fetching Post metadata failed.``

**Comment by fireattack** [comment]
Try to re-login as mentioned in #1694?

**Comment by KazKaz90** [comment]
> Try to re-login as mentioned in #1694? 

Already did, I even used all of my other IG accounts

**Comment by KazKaz90** [comment]
I think I got it figured out, post CEL2H4NHW49 has a video like with CDDcN-tnrS3 but it's broken as well which is why it's returning `HTTP error code 400`.
