### ISSUE TITLE
Story's caption can get in 4.9.2 but null in 4.9.3

### ISSUE THREAD

**Issue by JC-Chung** [instaloader/instaloader#1698]
**Describe the bug**
Lost story's caption is null in 4.9.3 . (Same story in 4.9.2 still can get caption.)
`caption` : `node > iphone_struct > caption`

**To Reproduce**
(e.g. Instaloader command line)
`instaloader download_account -l my_account --stories --no-posts --no-compress-json`

**Expected behavior**
Still can get caption in 4.9.3 .

**Error messages and tracebacks**
Didn't have any error messages.

**Instaloader version**
`instaloader --version` output.
4.9.3

**Additional context**
Or because it uses a different api in 4.9.2 and 4.9.3?

**Comment by aandergr** [comment]
Instaloader does not provide a caption property for StoryItems.

Instaloader tries to do as few metadata requests as possible, so it may occur that the JSON files do not contain the complete available metadata structure, and it may also change between versions. This is not a bug.

**Comment by JC-Chung** [comment]
So, is it because the requests are different?
But caption can effectively get the text on Story. (caption > text)
I think this is an important effect in saving Story.

Thank.
