### ISSUE TITLE
Got account suspended and then removed twice in 24 hours - First time this happened

### ISSUE THREAD

**Issue by giovsta** [instaloader/instaloader#1702]
It has been three years since I first used Instaloader. I massively downloaded data from profiles and hashtags many times, and that has often brought to my accounts being suspended.

Nonetheless, it never happened so quickly and consistently as in the last two days, when I had two accounts suspended and removed after scraping less than a thousand posts. It may be that Meta decided to fingerprint devices now, but I also think it must be some kind of change on the server side that lowered the number of requests that one account can do drastically.

I invite the devs to look into it, as it seems a rather recent change, and please provide info (if you have any) on how we can start using this tool again in a consistent manner. I am using the latest version (4.9.3), as a module, on a Windows 10 machine, with a VPN.

**Comment by tchikl-h** [comment]
Hey,

I discovered this tool recently. I did not have any restriction issues but I think it is because I download only 5-10 medias per day. I think the limit is above (like thousands in your case).

Isn't there any software to change your device fingerprint ? The main goal would be to trick instagram in thinking your a new user every 50-100 downloaded medias.

Does it solve your problem when your changing the location of your vpn ?

**Comment by giovsta** [comment]
There are many ways to trick Instagram to think that you're a completely different user. User-agents/different browsers, wipe-cleaning your browser data and changing where you are connecting from (I can even tell you there are some locations, like India, for which Meta has generally higher tolerance of requests). Problem is that that does not change that now data gathering operations are severely limited. I even set up a random wait time in between each request between 4 and 9 seconds) I did not download more than 150 posts that Instagram locked me out of an account created from a phone, with a couple of followers and with human interaction activities performed for a couple of hours.

I hope the Devs won't consider this a waste of time because they have better knowledge of the platform and take for accounted that most do, because I am better than many other colleagues of mine at using Instaloader, but I never struggled like now.

**Comment by christoarmani** [comment]
I try to limit the number of requests, and even then, I am noticing a similar issue where I constantly have to re-login to my accounts every other day, even when I took a day or two off from downloading. This started happening within the last two months. I am usually able to get about less than ~200 to 400 posts when before I was easily able to get 1000.

**Comment by uvx0ol** [comment]
Same issue here. 
I try to download (10-20 posts daily per 1 Instagram account, having 3-4 accounts). This is around ~50-100 pics/day overall. Instagram wants me to change my password, enter the SMS code, do the checkpoints etc. Now this happens almost everyday. I really limited the number of requests last weeks, but it didn't help at all.

**Comment by Thetail001** [comment]
me too, years ago I can easily download almost 1000~1500 per day with 2~4 different accounts . Now I almost lost ten accounts but can't download hundreds posts. Is instagram tighten something to let us can't use those tools download posts?

**Comment by esj42** [comment]
About a week ago there was a sudden change and I can no longer even log in with instaloader.  The first attempt to log in flags my account. When it first happened, I upgraded to 4.9.3 to see if that helped, and it didn't.

I have used instaloader for about a year dowloading 1-50 posts per day. Now, any attempt to log in with instaloader gives "Fatal error: Login: Checkpoint required.". I go through the checkpoint (the link it gives never works, but just attempting to log in takes me through the account recovery process).

I left it alone for a couple of days and just tried again and the first login attempt with instaloader fails and flags the account.

**Comment by christoarmani** [comment]
I have also encountered today like @esj42 with one of my accounts. I tried twice and got the "Fatal error: Login: Checkpoint required." but my other two accounts never got that error.

**Comment by faiblesse2** [comment]
Stopped scraping for now cause instagram has been getting more aggressive with lockouts. Lost three accounts recently when there was no issues before

**Comment by demib72** [comment]
I guess wait until current US politics blow over. The timing of it seems too much to be a coincidence.

**Comment by nns33213** [comment]
What connection did you guys use? Was it VPN/proxy or a normal residential/mobile connection?

I have a feeling that the problems are caused not by the bots themselves, but by Instagram cracking down on VPN usage. I've got accounts that I've never used for scraping flagged for suspicious activity just because they were logged in via VPN.

For me the last week has been horrible. New accounts instantly banned. Freshly bought ready-made accounts banned. 2-year old accounts banned. Phone verification doesn't even matter anymore.

instadp.com is shut down after at least 3 years of working perfectly. It's getting hard to even check stories manually using public tools because nothing works.

Maybe as a last resort switch to Selenium or AutoIT, ahah. Just kidding.

**Comment by esj42** [comment]
I'm not using a VPN. It's a residential cable modem. I am on a Linux machine; maybe that raises suspicion. I haven't been permanently banned (yet) but I've had a dozen soft bans in a week just from trying to log in.

**Comment by christoarmani** [comment]
I am also not using a VPN. I am using a residential connection. My accounts haven't been banned yet, but I know if I keep re-logging into them at this higher frequency to unlock them, they will eventually be locked out.

**Comment by afterdelight** [comment]
the locking is because of 'mismatch user agent'

**Comment by demib72** [comment]
Doubtful. I am a linux user and have used the user-agent of my firefox browser. Same suspension issue as well.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by afterdelight** [comment]
you must use the useragent of instagram app not the one on PC

**Comment by Nova6K0** [comment]
That is more complicated, because the other day, I received an error 403, which indicates that you are prohibited from accessing that resource. That is because the headers of each request to the API, basic, Graph, and Mobile are different. In fact, the Instagram API Graph is limiting a lot, and from what I could see, you can only make ten requests per hour, and for IP.

These are all the parameters that appear in the Instagram web version, in my sailor, when you logged in:

```
POST /ajax/bz?__d=dis HTTP/3

    Host: www.instagram.com

    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0

    Accept: */*

    Accept-Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3

    Accept-Encoding: gzip, deflate, br

    X-CSRFToken: [alphanumeric string]

    X-Instagram-AJAX: [int]

    X-IG-App-ID: [int]

    X-ASBD-ID: [int]

    X-IG-WWW-Claim: [alphanumeric string]

    Content-Type: application/x-www-form-urlencoded

    X-Requested-With: XMLHttpRequest

    Content-Length: [int]

    Origin: https://www.instagram.com

    Alt-Used: www.instagram.com

    Connection: keep-alive

    Referer: https://www.instagram.com/?__coig_login=1

    Cookie: mid=[alphanumeric string]; ig_did=[alphanumeric string]; datr= [alphanumeric string]; shbid= [alphanumeric string]; shbts= [alphanumeric string]; dpr= [float]; csrftoken= [alphanumeric string]; ds_user_id= [int]; rur= [alphanumeric string]; sessionid= [alphanumeric string]

    Sec-Fetch-Dest: empty

    Sec-Fetch-Mode: cors

    Sec-Fetch-Site: same-origin

    DNT: 1

    Sec-GPC: 1

    TE: trailers

```

Greetings.

**Comment by afterdelight** [comment]
well you must use the one on instagram app, its useless to use web browser version.
google how to parse an useragent

**Comment by giovsta** [comment]
Just providing extra information for anyone interested, I did not write anymore as I only had time to come back to test more today.
So using a residential connection improved the issue, as well as other two measures I added. First, I use python as a module, and I set-up a random wait time between each post scrape using the line:
```
sl = round(random.uniform(4, 9), 3)
print('waiting for', sl)
time.sleep(sl)
```
This improved, but using it in a VPN connection was still getting me permabanned, just later on.
So I also added a personalised user-agent, tailored for the exact mobile device and Instagram app version that the account is logged on (IMPORTANT: I did not test with a VPN as I am afraid I would lose another fake account). Now I relied on @afterdelight suggestions, but it still took me a lot of time to understand and find the useful resources, so here are some links that helped me:
[MITM Proxy](https://mitmproxy.org/) to parse my device's user agent as I use the Instagram app;
[This guide on how to parse a phone's user agent while using apps] (https://medium.com/testvagrant/intercept-ios-android-network-calls-using-mitmproxy-4d3c94831f62);
[This other Instagram Scraper on GitHub](https://github.com/ping/instagram_private_api/blob/master/instagram_private_api/constants.py) in particular the file I linked, which gave me an idea of the structure that the User-Agent should resemble if I want it to work with the Instagram API.
I have been able to scrape more posts now than before, and still got no warning or softban.

**Comment by giovsta** [comment]
update: I got softlocked (phone number verification and then free to go immediately) after downloading 351 posts. Still, at this point it is usable compared to before, even if not as much as a year ago

**Comment by afterdelight** [comment]
i have a simpler solution:

put this link into your instagram bio/website
https://developers.whatismybrowser.com/useragents/parse/
then browse your profile and click the link through instagram app. it will open the link through instagram internal browser then click 'Parse your own user agent instead?'
it will show your instagram mobile user agent. use that user agent on insta loader.

**Comment by afterdelight** [comment]
ur welcome. tell me if it worked.

**Comment by EnthusiastAnon** [comment]
@afterdelight after using user-agent I get a challenge error. It gives a link that I should open in browser and confirm that "it's me" and then instaloader says to retry. I do that, I retry, and again the same thing happens. What am I doing wrong?

**Comment by afterdelight** [comment]
did you sue vpn connection? have you try to delete session file after solving the challenge? 
try to open instagram web browser while loggin in the new session through instaloader and then immidiately confirm the login was you through web browser before instaloader starting downloading media. if you set a delay in between each request you will have enough time to do the confirmation.

**Comment by EnthusiastAnon** [comment]
> did you use a vpn connection? have you try to delete session file after solving the challenge? try to open instagram web browser while loggin in the new session through instaloader and then immidiately confirm the login was you through web browser before instaloader starting downloading media. if you set a delay in between each request you will have enough time to do the confirmation.

I don't use VPN.
I use this command, I only download stories.

instaloader -l myusername --user-agent "the user agent I got from your instructions" --no-metadata-json --no-profile-pic --no-posts -s targetprofile

I'm not sure I understand your instructions...

**Comment by afterdelight** [comment]
hey why are the comment deleted

**Comment by afterdelight** [comment]
recently, I got 
Fatal error: Login error: Unexpected response, this might indicate a blocked IP.

any work around?

**Comment by Showmaster3000** [comment]
Currently there seem to be login problems. I also cannot login with Firefox on one account. A red error mesage appears below the login form after entering user data saying something like "there was an error. try again later." But this account works fine in the app on my tablet. Seems a thing on instagram side.

Nevertheless on the initial problem there seem to be some changes making it stricter.

**Comment by afterdelight** [comment]
yeah, my condition is exactly like yours

**Comment by asdub** [comment]
I am having the same issue, "Login error: Unexpected response, this might indicate a blocked IP." 
Does anyone know what has been changed?

**Comment by afterdelight** [comment]
> @afterdelight have you actually tried your method before suggesting it? Seems like Instagram doesn't like changing user agent because you cannot even login when it's changed.
> 
> I'm not sure of the benefit of using Instagram UA. This is what instagram-scraper uses but not instaloader (instaloader just uses a standard web browser user agent) but the end result is the same for both programs.

what are you saying is non sense. have you read the conversations of this thread? if you use standard web browser user agent instagram will ask you again and again to do verify challenge on browser.

**Comment by nns33213** [comment]
> what are you saying is non sense. have you read the conversations of this thread? if you use standard web browser user agent instagram will ask user again and again to do verify challenge on web browser.

@afterdelight this conversation is about Instagram permanently banning accounts. This is something new. Asking to verify phone number is nothing new and has happened forever.

According to you, changing the user agent to `Instagram/...` mobile UA will fix the problem, but this is what another scraper `instagram-loader` has been doing for a long time and it does not prevent banning the account. I don't think the user agent is the main cause why Instagram is permanently banning accounts.

**Comment by afterdelight** [comment]
Because instagram-scraper using a random iphone user agent which is different from what user is using. Also the instagram version on that user agent is very old. If you have and android and the user agent is an iphone of course user will get soft lock, no? The banning is because the user was using vpn and the locking is because of user agent mismatch. 

He was saying after using my method, he is no longer got banned and only got soft locked and can continue scraping more then the usual. Have you even read the whole conversations and not just the issue title?

**Comment by RazeBerry** [comment]
@fireattack Thank you very much for your solution and I was wondering if it is still possible to circumvent ban or 401 by using your method of trying to imitate mobile user-agent to scrap. In addition, I was wondering where would I get the cookie session from the mobile. I assume if I continue using firefox cookie session it will be suspicious to the Instagram system?

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com

**Comment by Grace2290** [comment]
I want to thank Chloe_consultant on 1nstagram for her tireless efforts she had put into this work that is beyond excellence chloe_consultant . Take my cordial thanks! You are really an efficient, organized and result-oriented woman. I haven’t seen such quality work in a long time. Great job, Keep it up. And I will make sure the world knows more about you and the good deed you have done for me in recovering my business Page.. Her email Is Chloe.consultant1@gmail.com she is Legit 105%

**Comment by manasgunakar1-jpg** [comment]
@manav_jee_44 I'd suppend insta plz unban 😭😭
