### ISSUE TITLE
User Agent change doubt

### ISSUE THREAD

**Issue by bachig26** [instaloader/instaloader#1703]
From Instaloader Documentation "[How to Download](https://instaloader.github.io/cli-options.html#how-to-download)":
`--user-agent USER_AGENT`
User Agent to use for HTTP requests. Per default, Instaloader pretends being Chrome/92 on Linux.

From the file [instaloadercontext.py](https://github.com/instaloader/instaloader/blob/master/instaloader/instaloadercontext.py):
`def default_user_agent() -> str:`
`    return 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 ' \
           '(KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36'`

I want to change the default user agent to a custom one, but from the documentation, there is no example of how the command line should and in the default user agent from the code looks different.

As I don't know how to enter them in the `args.txt`.

is the user agent command need to look like:
1. `--user-agent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.83 Safari/537.36`
2. `--user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 ' \
           '(KHTML, like Gecko) Chrome/104.0.5112.83 Safari/537.36'`

please let me know which of the two option that I need to use or is it in different way.

**Comment by afterdelight** [comment]
i used it like this --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 ' \ '(KHTML, like Gecko) Chrome/104.0.5112.83 Safari/537.36"

and you should use the same user agent as the one used in instagram app
