### ISSUE TITLE
How to remove a session

### ISSUE THREAD

**Issue by E0697** [instaloader/instaloader#1705]
I have an obsolete login session and I keep getting 429 error when trying to login again. Is it possible to remove the session altogether?

Also, are options like --user-agent and --abort-on saved automatically, or do I need to use them everytime?

**Comment by Showmaster3000** [comment]
session files are saved in your user folder. 
for windows: %LOCALAPPDATA%\instaloader\session-YOUR-USERNAME
for linux: ~/.config/instaloader/session-YOUR-USERNAME

command line options are always needed. some are default. everything is described in the manual: https://instaloader.github.io/cli-options.html

**Comment by E0697** [comment]
I deleted the session file, I suppose that's sufficient right?

**Comment by E0697** [comment]
I deleted the session file, thank you!
