### ISSUE TITLE
command line: instaloader new version update

### ISSUE THREAD

**Issue by bachig26** [instaloader/instaloader#1706]
**Provide us a use case of the feature**
How could the user invoke the new function?
- _`instaloader.exe -U` or `instaloader.exe --update`_

Which problem would it solve?
- _this function is to solve the instaloader update via command line easily instead of downloading the new version from the GitHub every time._

If new information is obtained, how would it be further processed?
- _for example, this function is available in the [yt-dlp](https://github.com/yt-dlp/yt-dlp) {**Self-updater**: The releases can be updated using `yt-dlp -U`}, which I use every time to update and easy for the user._

**If the feature request is accepted, would you be willing to submit a pull request?**
No, I can't do programming. 
possibly add `help wanted` label if this feature request pr needs to be done by someone other than you.

**Comment by bachig26** [comment]
@aandergr @Thammus @Hassibayub I want to ask if this is possible and what do you think about this?

**Comment by Hassibayub** [comment]
You are good at thinking out of the box. I'll check on this in my free time today 👍👍

**Comment by Hassibayub** [comment]
I'll possibly complete this request tomorrow. @bachig26

**Comment by bachig26** [comment]
> I'll possibly complete this request tomorrow. @bachig26 

Thank you. Looking forward to try it once got the release.

**Comment by Hassibayub** [comment]
Feature added and pull request created. It's the basic implementation that just works. I will add wait animation and stylize terminal output in future, meanwhile I am occupied with my piles of projects.

Thank you @bachig26 for suggesting this update.

**Comment by aandergr** [comment]
Running `pip3 install --upgrade instaloader` is in no way more complicated than something like `instaloader --upgrade` would be. Hence, I do not see a benefit in this feature suggestion.
