### ISSUE TITLE
Profile xxxx does not exist

### ISSUE THREAD

**Issue by SharonGao1992** [instaloader/instaloader#1709]
Does anyone get the same error as me?
The package used to run very well on my laptop, but today I keep getting the same error:
Profile sooyaaa__ does not exist.
The most similar profiles are: sooyaaa__, sooyaaa_pic, sooyaaa__diary, _sooyaaa_bp_blink, sooyaaa_stans.

I have tried different user names and run into the same problem, and their first recommendation is the profile name I provided in the code. I have also updated the package to the most recent version, and it doesn't solve my problem.

**Comment by Showmaster3000** [comment]
are you really sure that you are using the latest version? check `instaloader --version` output if its at least 4.9.2

**Comment by LegacyofAden** [comment]
Yes same problem here:

JSON Query to gi_gomes78/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to gi_gomes78/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Profile gi_gomes78 does not exist.
The most similar profiles are: gi_gomes78, gigomes783, giovanna_gomes789, gigomes78, gih_gomes78.
Trying again anonymously, helps in case you are just blocked.
JSON Query to gi_gomes78/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to gi_gomes78/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Profile gi_gomes78 does not exist.
The most similar profiles are: gi_gomes78, gigomes_78, giovanna_gomes789, gil_gomes78, gilson_gomes78.
Saved session to C:\Users\supor\AppData\Local\Instaloader\session-brsilvarp.

Errors or warnings occurred:
Profile gi_gomes78 does not exist.
The most similar profiles are: gi_gomes78, gigomes_78, giovanna_gomes789, gil_gomes78, gilson_gomes78.
PS F:\instaloader-v4.9.3>

**Comment by cjrobe** [comment]
Mine says this then proceeds to download images just fine. Weird.

**Comment by Showmaster3000** [comment]
Difficult to guess the differences between you, cause you missed one of the most important things: the command line you use!

**Comment by cjrobe** [comment]
> Difficult to guess the differences between you, cause you missed one of the most important things: the command line you use!

If you looked closely, you would see the "PS" in LegacyofAden's post, which means PowerShell ;). I'm using Powershell too.

**Comment by Showmaster3000** [comment]
> If you looked closely, you would see the "PS" in LegacyofAden's post, which means PowerShell ;). I'm using Powershell too.

@cjrobe Are you funny? I didn't ask for the CLI, but hey, no more comments.
