### ISSUE TITLE
Can property ["import_taken_at"] be supported?

### ISSUE THREAD

**Issue by cykac04** [instaloader/instaloader#1710]
**Provide us a use case of the feature**
Some instagram photos have a property ["import_taken_at"], which should be the time of the photo taken on phone.

**Describe the solution you'd like**
Use as {import_date_utc} and {import_date_local} in filename specification.

**Comment by aandergr** [comment]
Could you give an example for a photo that has import_taken_at?

And are we talking about posts or storyitems?

Generally, if hat property is null in the majority of cases, it is not suited to be used in the filename specification. However, I think it still might be worth to export it as a property.
