### ISSUE TITLE
Night run auto shutdown pc on fail or finish

### ISSUE THREAD

**Issue by Muggeren** [instaloader/instaloader#1713]
Hello everyone. I am currently using the Windows version of Instaloader.

I would like to make it run overnight, and if it encounter either failure like an 400 code or it finish, i want it to shutdown the pc. 

My extra question is, if this is possible, and i want to resume it the next day, how do i do that? I just tried to test "--resume-prefix" but im bit confused how it works. ive tried "instaloader --login=USERNAME --tagged --highlights --resume-prefix" but it asks for an extra argument? I added a target after the line but thats the same as without "--resume-prefix"?

Hope you guys can understand and help me. 
Thanks alot, Muggeren.

**Comment by Showmaster3000** [comment]
How about creating a batch file containing the call of instaloader using `--abort-on` and as second command `shutdown` to close down your pc? but be aware that you have to log the output to see if it was successful or ended with an error.

`--resume-prefix` is for renaming the resume file, see manual: https://instaloader.github.io/cli-options.html#cmdoption-resume-prefix

**Comment by lx30011** [comment]
use a unix system

**Comment by Muggeren** [comment]
> How about creating a batch file containing the call of instaloader using `--abort-on` and as second command `shutdown` to close down your pc? but be aware that you have to log the output to see if it was successful or ended with an error.
> 
> `--resume-prefix` is for renaming the resume file, see manual: https://instaloader.github.io/cli-options.html#cmdoption-resume-prefix

Cant seem to find out how to use the resume function

**Comment by Muggeren** [comment]
> use a unix system

I have no experince in that, but ill look at it, thanks.

**Comment by Showmaster3000** [comment]
> Cant seem to find out how to use the resume function

Reading the manual I linked above tells you

> This feature is enabled by default for targets where it is supported

And I think, anything else you need to know is also descibed there.

**Comment by Muggeren** [comment]
> > Cant seem to find out how to use the resume function
> 
> Reading the manual I linked above tells you
> 
> > This feature is enabled by default for targets where it is supported
> 
> And I think, anything else you need to know is also descibed there.

So to continue, all i have to do is using the same code as the last run?
