### ISSUE TITLE
Do Proxies work with Instaloader and what to do to avoid getting IP-banned?

### ISSUE THREAD

**Issue by thebeautyofcoding** [instaloader/instaloader#1716]
I am building an insta downloader page. On my backend I am using Flask with instaloader. It worked well for downloading profile pictures and individual pictures of posts. Unfortunately, after downloading a few, I wasn't able anymore and Instaloader told me to login. By using the login method, I was able to login and download a few more pictures, but then I got another message that my IP has probably been blocked.
My question is how can I avoid being blocked? And, is it possible to use proxies?

Here is an endpoint of my flask app:

```
@app.route('/downloadDP', methods=['POST'])
def downloadDP():
    profile_name=request.json['url'].split('/')[3]
    dp = Instaloader()
    dp.context._session.proxies={
        "http":"myproxyxxx"}
    profile=Profile.from_username(dp.context, profile_name)
    
    return jsonify({'display_pic':profile.profile_pic_url+"&dl=1"})
```
I also have an URL for IP rotation, but it seems not to have an effect, which leads me to believe that my proxy might be not properly connected to instaloader?
Thanks for any help :)

**Comment by monty-dev** [comment]
The code above wouldn't be proxied. Try `"https":"myproxyxxx"}`. Requests must have a proxy defined for http and https

**Comment by Mujadid-Ali** [comment]
Hi, I am getting the same error of blocked IP. have you found any solution that how we can unblock our IP address or in how many days Instagram automatically unblock our IP?
And also is there any proper solution which prevents to blocked again our IP address. Any lead would be appreciated.

**Comment by HirtLocker128** [comment]
@Mujadid-Ali did you ever find a solution for this? Struggling now and not much out there!

**Comment by Mujadid-Ali** [comment]
> @Mujadid-Ali did you ever find a solution for this? Struggling now and not much out there!

@HirtLocker128 No, I am still finding the solution.
