### ISSUE TITLE
Unable to fetch high quality image version of ... (Using Instaloader 4.9.3)

### ISSUE THREAD

**Issue by SnakeEve** [instaloader/instaloader#1719]
Hello guys, so i have an issue, i was unable to download high quality image/video, i've been using Instaloader for these couple years and it works fine, some temporary bans here and there and that's it.

So I'm using some python script, i don't use the plain command because i need to iterate my download list, these are the codes: 

```
L = instaloader.Instaloader(
    max_connection_attempts=0,
    request_timeout=500.0,
    download_videos=True,
    download_video_thumbnails=False,
    download_geotags=False,
    download_comments=False,
    post_metadata_txt_pattern="",
    save_metadata=False,
    rate_controller=lambda ctx: MyRateController(ctx)
)

L.load_session_from_file("DUMMY_ACCOUNT")

profile = instaloader.Profile.from_username(L.context, id)
    post_iterator = profile.get_posts()
    
    for current_post in post_iterator:
        L.download_post(current_post, id)
```

**Expected behavior**
Back then it used to be able to download Higher quality of the media files

**Error messages and tracebacks**
`Unable to fetch high quality image version of <Post Cc5CmwbvqUA>: JSON Query to api/v1/media/2826301700589921536/info/: HTTP error code 403.`

**Instaloader version**
4.9.3

Thanks!

**Comment by Nova6K0** [comment]
Instagram has changed its API in mid -August. This is producing many problems, such as 40x errors.

https://github.com/yt-dlp/yt-dlp/pull/4708

Greetings.

**Comment by afterdelight** [comment]
that was a nice discussion there, maybe someone can implement it to insta loadeer?

**Comment by thereareno** [comment]
> that was a nice discussion there, maybe someone can implement it to insta loadeer?

Open source - nothing stopping ya

**Comment by afterdelight** [comment]
i cant im just a very newbie programmer

**Comment by aandergr** [comment]
It works for me. Is there any profile where this error reproducably occurs?

**Comment by curya** [comment]
@aandergr I can reproduce the error with this profile: https://www.instagram.com/therealunklchng/

Once you get to about post 350 or so, the 403 error starts happening.
