### ISSUE TITLE
Save Caption as Filename

### ISSUE THREAD

**Issue by gelsas** [instaloader/instaloader#172]
Hello!
I would love to see this as a feature. 
I have a script for social media autoposting which allows to use filename as caption (nowadays the emojis in the captions are no problem for windows as far as i know).

Thats why I am searching for a way to download the images and videos with its original filenames.
(There was an project which exactly did this but that was 2-3 years ago and since then I have not found any 
 other software which could do this - https://www.blackhatworld.com/seo/get-download-all-instagram-photos-videos-from-any-user-with-caption-as-file-name.857462/)
![image](https://user-images.githubusercontent.com/282734/44635931-10218700-a9a9-11e8-89bf-4a2e2d6b9537.png)

**Comment by MatthieuBonenfant** [comment]
Something to consider if you were to implement such function. 

I do not remember which software/script I was using to do this with Tumblr a few years ago but the main issue I encountered was that the filenames were getting too long for the path the images were saved in. The script did not prevent creating the files with a path longer than what windows could handle and somehow those files were "stuck" in folders but could not be read, unless I manually renamed the parent folders to a path length + filename length under the limit of what Windows could handle.

I would suggest an option where a character limit could passed to the script.

**Comment by aandergr** [comment]
Hello!

`--filename-pattern={caption}` instructs Instaloader to use the Post's caption as filename. With `--filename-pattern={caption:.30}`, the first up to 30 chars of the caption are used as filename. However, the captions may not be unique, and there is no logic to handle that. Also, a Post caption may contain characters that are not allowed in filenames, but our latest alpha version, 4.1a1, substitutes these by allowed characters.

I am unsure what you mean by original filename. There is `--filename-pattern={shortcode}` to use the shortcode (of the Post URL https://instagram.com/p/SHORTCODE/) as filename, but there is currently no way to use the filename part of the picture's URL as stored on Instagram CDN servers, if that is what you mean.

Best regards
Alex
