### ISSUE TITLE
JSON Query to profile/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

### ISSUE THREAD

**Issue by sa1yi2** [instaloader/instaloader#1721]
I would like to know how the following problem should be resolved.

**Comment by Showmaster3000** [comment]
reading #1553.

**Comment by sa1yi2** [comment]
I fixed it. MY account was temporarily banned and instaloader didn't be upgraded . So I could now smoothly run instaloader when I recoverd my account and upgraded instaloader. Thank you！

**Comment by joshgavinhong** [comment]
Hi @sa1yi2 - Ive encountered the same issue with my version of Instaloader - which is an older version that was working well until last week.. 

What version are you currently using?

**Comment by Showmaster3000** [comment]
You must use at least v4.9.2 or better (always) the most recent.

**Comment by joshgavinhong** [comment]
Thanks very much @Showmaster3000 !
