### ISSUE TITLE
Windows Defender Flags

### ISSUE THREAD

**Issue by thereareno** [instaloader/instaloader#1722]
Windows "Defender" just started flagging my existing 4.9.3 (Windows 11) as "Behavior:Win32/DefenseEvasion.A!ml". Microsoft describes this as a "generic threat"; I'm guessing WD simply flags what it doesn't understand, and there is no threat here. Anyone else getting this message?

**Comment by iouzzrj** [comment]
My instaloader.exe and .zip package is deleted today by Windows Defender today, flagged the same as "Behavior:Win32/DefenseEvasion.A!ml".
