### ISSUE TITLE
Console login with username and password

### ISSUE THREAD

**Issue by Riffecs** [instaloader/instaloader#1723]
Hi guys, 
Can you do this somehow that you can log in completely without the profiles with username and password?

I imagine it as follows:

```
instaloader --user="USER" --password="PASSWORD" --profile="PROFILE"
```

This would be very handy, because then you can build your own scripts around the tool. 

Thank you.

**Comment by Showmaster3000** [comment]
Did you read the manual? Especially https://instaloader.github.io/cli-options.html#login-download-private-profiles ?
The parameters `--login` and `--password` are your friend. Hint: `--profile` is not required, just enumerate the profiles you want to load.
