### ISSUE TITLE
Problem When Downloading

### ISSUE THREAD

**Issue by Carton9** [instaloader/instaloader#1726]
Yet the user do exist/

Loaded session from C:\Users\****\AppData\Local\Instaloader\*****
Logged in as *****.
JSON Query to ******./feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Trying to find profile ******. using its unique ID ******.
Profile  ******.. has changed its name to ******.
JSON Query to  ******./feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Profile ******. does not exist.

**Comment by Showmaster3000** [comment]
incomplete bug report.
duplicate of #1553 (and many more).
