### ISSUE TITLE
Instaloader is too aggressive

### ISSUE THREAD

**Issue by lx30011** [instaloader/instaloader#1729]
I run
```
instaloader --comments --geotags --stories --highlights --tagged --igtv --no-compress-json --login <account> --fast-update <profile>
```
and it causes a 429 error. This account is wholely dedicated to scraping and I currently only scrape this profile once a day.

```
Number of requests within last 10/11/20/22/30/60 minutes grouped by type:
   d6f4427fbe92d846298cf93df0b937d3:    1    1    1    1    1    1
                             iphone:   11   11   11   11   11   11
   e31a871f7301132ceaab56507a66bbb7:    1    1    1    1    1    1
   2b0673e0dc4580674a88d426fe00ea90:    3    3    3    3    3    3
                              other:    2    2    2    2    2    2
 * 97b41c52301f77ce508f55e66d17620e:    3    3    3    3    3    3
   7c16654f22c819fb63d1183034a5162f:    1    1    1    1    1    1
   45246d3fe16ccc6577e0bd297a5db1ab:    7    7    7    7    7    7
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 589 seconds, at 14:11.
```

Please increase the delays or something. Thank you

**Comment by dewey** [comment]
I'm also running into this error even though I'm just storing the `:saved` posts of my account (` instaloader --comments --login=username :saved`).

Would it be possible to have a way to configure a custom rate limit. I don't care if it takes a 5 second break between each requests as speed isn't the issue, completeness is more important in that case.

**Comment by Arthurpmrs** [comment]
So, I used the instaloader Python module to make a script to do this. It waits 40 seconds + a random amount of seconds every post, then 480 seconds + a random amount every 10 posts, and then 3000 seconds + a random amount every 100 posts. It stops with 200 posts. The other day when you execute the program again it will start where it stopped if posts were not downloaded. If you know Python you could use it. 

It is worth mentioning that my account gets errors 400 a frequently, despite the waiting time and low amount of posts per day. Maybe I'm blacklisted? Don't know. But maybe the script could help you.

`Python
from instaloader import Instaloader
from instaloader import Profile
from instaloader import FrozenNodeIterator
import os
import sys
import json
import time
import random
import datetime
import configparser
from FileOrganizer.fileorganizer import FileOrganizer


class PostAlreadyDownloaded(Exception):
    pass


class DownloadSaved:
    def __init__(self, root=os.getcwd(), folder="saved"):
        self.root = root
        self.is_to_be_organized = False
        os.chdir(self.root)

        self.folder = folder
        self.get_credentials()

        # Trying to avoid 400 ERROR and account locking.
        self.remove_session()

        self.L = Instaloader(
            save_metadata=False,
            compress_json=False,
            download_comments=False,
            post_metadata_txt_pattern="",
            filename_pattern="{date_utc:%Y-%m-%d}_{profile}_{shortcode}",
        )

        self.set_login()
        self.profile = Profile.from_username(self.L.context, self.USER)

    def get_credentials(self):
        configpath = os.path.join(self.root, "config.ini")

        if not os.path.exists(configpath):
            config = configparser.ConfigParser()
            time.sleep(2)
            config["ig"] = {
                "username": input("Username: "),
                "password": input("Password: "),
            }

            with open(configpath, "w") as file:
                config.write(file)

            self.USER = config["ig"]["username"]
            self.PASSWORD = config["ig"]["password"]
        else:
            config = configparser.ConfigParser()
            config.read(configpath)

            self.USER = config["ig"]["username"]
            self.PASSWORD = config["ig"]["password"]

    def set_login(self):
        session_filename = f"session-{self.USER}"
        session_filepath = os.path.join(self.root, session_filename)

        if not os.path.exists(session_filepath):
            self.L.login(self.USER, self.PASSWORD)
            self.L.save_session_to_file(filename=session_filename)
        else:
            self.L.load_session_from_file(self.USER, filename=session_filepath)

    def download(self):
        current_time = round(time.time())

        freeze_filename = "resume.json"
        freeze_filepath = os.path.join(self.root, freeze_filename)

        saved_posts = self.profile.get_saved_posts()

        if os.path.exists(freeze_filepath):
            print(">> Back from where it stopped...")
            print(" ")

            with open(freeze_filepath) as f:
                saved_posts.thaw(FrozenNodeIterator(*json.load(f)))

        try:
            for self.count, post in enumerate(saved_posts):
                time_sleep_lvl_1 = 40 + random.randint(20, 80)
                time_sleep_lvl_2 = 480 + random.randint(60, 180)
                time_sleep_lvl_3 = 3000 + random.randint(100, 700)

                if (self.count + 1) == 200:
                    json.dump(saved_posts.freeze(), open(freeze_filepath, "w"))

                    print(" ")
                    print(">> 200 Posts downloaded! Stopping...")
                    break

                elif (self.count + 1) % 100 == 0:
                    self.check_existence(self.L.download_post(post, self.folder))
                    json.dump(saved_posts.freeze(), open(freeze_filepath, "w"))

                    print(" ")
                    print(
                        f">> 100 Posts downloaded. Waiting {time_sleep_lvl_3} seconds!"
                    )
                    time.sleep(time_sleep_lvl_3)

                elif (self.count + 1) % 10 == 0:
                    self.check_existence(self.L.download_post(post, self.folder))
                    json.dump(saved_posts.freeze(), open(freeze_filepath, "w"))

                    print(" ")
                    print(
                        f">> 10 Posts downloaded. Waiting {time_sleep_lvl_2} seconds!"
                    )
                    time.sleep(time_sleep_lvl_2)

                else:
                    self.check_existence(self.L.download_post(post, self.folder))

                    print(f">> Waiting {time_sleep_lvl_1} seconds!")
                    time.sleep(time_sleep_lvl_1)

        except KeyboardInterrupt:
            json.dump(saved_posts.freeze(), open(freeze_filepath, "w"))

        except PostAlreadyDownloaded:
            json.dump(saved_posts.freeze(), open(freeze_filepath, "w"))
            os.rename(freeze_filename, f"{current_time}_{freeze_filename}")
            print(">> Todos os novos posts já foram baixados!")
            folder = os.path.join(self.root, "saved")
            if self.is_to_be_organized:
                _ = FileOrganizer(folder, by="month", keep_last=True, only_root=True)

        except Exception as e:
            json.dump(saved_posts.freeze(), open(freeze_filepath, "w"))
            print(">> Something went wrong.")
            print(e)

    def check_existence(self, downloaded):
        if not downloaded and self.count > 0:
            raise PostAlreadyDownloaded

    def remove_session(self):
        session_file = f"session-{self.USER}"
        session_path = os.path.join(self.root, session_file)

        if os.path.exists(session_path):
            os.remove(session_path)


def main():
    saved = DownloadSaved(root=path)
    saved.download()


if __name__ == "__main__":
    main()
`

**Comment by lx30011** [comment]
I feel like the issue might be running the script at a predictable interval, for example every day at 2am. Because I never ran into these issues until I started periodically fetching.

Also I feel like I should note that during 2020 I ran a selfmade script that only fetched stories. I made it using the InstaPy library. I never had any issues, it worked flawlessly. I'll try only fetching stories instead of every bit of the profile from now and and see how it goes.

**Comment by aandergr** [comment]
Please use our [Feature Suggestion Template](https://github.com/instaloader/instaloader/issues/new?labels=feature+suggestion&template=feature_request.md) for suggesting new features, as this makes it easier to see how the new feature could fit into Instaloader.
