### ISSUE TITLE
Download only photos

### ISSUE THREAD

**Issue by raseduly** [instaloader/instaloader#1731]
In this code I can download only videos from a profile, how can I download only photos?

```
from instaloader import Instaloader, Profile

L = Instaloader()
L.login("username","password")

PROFILE = "instagram"
profile = Profile.from_username(L.context, PROFILE)
posts_sorted_by_likes = sorted(profile.get_posts(), key=lambda post: post.likes, reverse=True)

for post in posts_sorted_by_likes:
        if post.is_video:
                L.download_post(post, PROFILE)
```

In this line `if post.is_video:` I tried with some different code but it's not working.

**Comment by fireattack** [comment]
`if not post_is_video:`?

Or you can use `L.download_videos = Flase`.

**Comment by raseduly** [comment]
I tried both but it did not work.
I found a new code  `L.download_pictures` is available it's saying `TypeError: 'bool' object is not callable` 
Is there any way to solve this?

**Comment by fireattack** [comment]
What do you mean by "not work"

**Comment by raseduly** [comment]
If i use `if not post.is_video:` video is also downloading
and `L.download_videos = False` it's finished without downloading anything

**Comment by christoarmani** [comment]
Why not use the [command line](https://instaloader.github.io/cli-options.html) option with the following arguments?
```
--login=username
--password=pasword
--no-videos
--no-metadata-json
--no-profile-pic
--no-caption
profiletodownload
```

**Comment by fireattack** [comment]
It works for me.

```
from instaloader import Instaloader, Profile

L = Instaloader()
L.load_session_from_file("myaccount")

PROFILE = "XXX"
profile = Profile.from_username(L.context, PROFILE)
posts_sorted_by_likes = sorted(profile.get_posts(), key=lambda post: post.likes, reverse=True)

for post in posts_sorted_by_likes:
    if not post.is_video:
            L.download_post(post, PROFILE)
```
Posts with video are not downloaded.

And if you're using `L.download_videos = False` obviously you need to also remove `if post.is_video:` part.

**Comment by raseduly** [comment]
> Why not use the [command line](https://instaloader.github.io/cli-options.html) option with the following arguments?
> 
> ```
> --login=username
> --password=pasword
> --no-videos
> --no-metadata-json
> --no-profile-pic
> --no-caption
> profiletodownload
> ```

My client is using pycharm and he couldn't use the command line. He only takes the code and paste it. That is the problem 😢 that's why I'm learning without command line code.

**Comment by raseduly** [comment]
> It works for me.
> 
> ```python
> from instaloader import Instaloader, Profile
> 
> L = Instaloader()
> L.load_session_from_file("myaccount")
> 
> PROFILE = "XXX"
> profile = Profile.from_username(L.context, PROFILE)
> posts_sorted_by_likes = sorted(profile.get_posts(), key=lambda post: post.likes, reverse=True)
> 
> for post in posts_sorted_by_likes:
>     if not post.is_video:
>             L.download_post(post, PROFILE)
> ```
> 
> Posts with video are not downloaded. It will still download video thumbnails though. You can turn that off by another flag.
> 
> Also if you're using `L.download_videos = False` instead, obviously you need to also remove `if post.is_video:` part. Otherwise it will download nothing.

Perfect, It's working. Can you please tell me how to turn off the thumbnail and json file? Or which documentation should I read?

**Comment by fireattack** [comment]
If you are using it as a module, I recommend you to read the code directly. The settings are here:

https://github.com/instaloader/instaloader/blob/master/instaloader/instaloader.py#L252-L259

**Comment by raseduly** [comment]
I tried with this code `L.save_metadata = False`  `L.download_video_thumbnails = False` and it's working. Thank you so much for helping.
