### ISSUE TITLE
Support downloading personal collections

### ISSUE THREAD

**Issue by weiweihuanghuang** [instaloader/instaloader#1733]
**Provide us a use case of the feature**
Download collections.

**Describe the solution you'd like**
`instaloader collection [collection ...]`

**Describe alternatives you've considered**

**If the feature request is accepted, would you be willing to submit a pull request?**
No

**Additional context**
This would be very useful, there's no tool capable right now of downloading collections.

**Comment by aandergr** [comment]
Duplicate of #544
