### ISSUE TITLE
Instaloader won't collect the media for accounts with pinned posts.

### ISSUE THREAD

**Issue by BurnsDillion** [instaloader/instaloader#1735]
Code:
profiles = ['account_name']

loader = instaloader.Instaloader()
loader.login(ig_user, ig_pass)

START = datetime(2022, 8, 28)
STOP = datetime(2022, 8, 1)

for profile in profiles:
    print(profile)
    posts = instaloader.Profile.from_username(loader.context, profile).get_posts()

    for post in takewhile(lambda p: p.date > STOP, dropwhile(lambda p: p.date > START, posts)):
        print(post.date)
        loader.download_post(post, profile)
        time.sleep(.5)

Just a simple media downloader for Instagram accounts. This week it won't collect a few accounts on a list I use, and the only thing I can pin down is that it doesn't seem to collect media for accounts with Pinned posts on the first row of their gallery. Not sure why that is. I had a few friends pin some posts to their accounts and the script won't collect their media, but once they unpin I rerun the script and it collects fine. Any help on this would be greatly appreciated! Thank you!

**Comment by ekalin** [comment]
If there are pinned posts, they're returned as the first items, and the sequence is no longer strictly chronological. I guess one of the pinned posts is older than the STOP date, so the iteration immediately stops.

Perhaps `p.date > STOP and not p.is_pinned` (or something similar) might work.

**Comment by fireattack** [comment]
As ekalin said, this can be resolved by adding _ispinned to conditional in some way.

Instaloader's built-in download functions already dealt with this in `posts_download_loop()` since 4.9.2. You need to re-implement it yourself if you want to manually process posts this way.
