### ISSUE TITLE
JSON Query to accounts/login/: Could not find "window._sharedData" in html response.

### ISSUE THREAD

**Issue by axelmiami** [instaloader/instaloader#1737]
Exactly the same problem:

```
$ instaloader --login=<username>
Session file does not exist yet - Logging in.
Enter Instagram password for p2i.berest:
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Fatal error: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.
```
help me please

Moreover, when launched locally from the IDE, everything connects and works, but on the server it gives an error.

All Python packages are the same and updated to the latest versions.
```
$ python3 -m pip install instaloader -U
Requirement already satisfied: instaloader in ./venv/lib/python3.8/site-packages (4.9.3)
Requirement already satisfied: requests>=2.4 in ./venv/lib/python3.8/site-packages (from instaloader) (2.28.1)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.8/site-packages (from requests>=2.4->instaloader) (2022.6.15.1)
Requirement already satisfied: charset-normalizer<3,>=2 in ./venv/lib/python3.8/site-packages (from requests>=2.4->instaloader) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.8/site-packages (from requests>=2.4->instaloader) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.8/site-packages (from requests>=2.4->instaloader) (1.26.12)`
```

All of the above methods did not help.
Both the call from Python and the call in the console do not work on the server

**Comment by axelmiami** [comment]
I tried following the instructions in #1740, but I still can't log in

**Comment by aandergr** [comment]
Indeed, it seems that the login is currently not working.

Similar errors have been reported in #1635 and #1758.

Until this is fixed, we recommend the workaround described in https://instaloader.github.io/troubleshooting.html#login-error.

**Comment by anuraag488** [comment]
> Indeed, it seems that the login is currently not working.
> 
> Similar errors have been reported in #1635 and #1758.
> 
> Until this is fixed, we recommend the workaround described in https://instaloader.github.io/troubleshooting.html#login-error.

Can you give some option for command line? I want to import cookies in Termux Android.

**Comment by akafanfan** [comment]
Logged in as xxxx
JSON Query to xxxx/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to xxxx/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Profile songyuxin_hitomi does not exist.

**Comment by yarodevuci** [comment]
same problem here... don't understand why

**Comment by Dragos-Lion** [comment]
Same as @PrabhatProxy, tried 2 accounts

**Comment by selukov** [comment]
same problem, tried on two machines with Python 3.9.2 and Python 3.10.12

**Comment by Subhan122** [comment]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Traceback (most recent call last):
  File "C:\Users\Subhan Sarwar\pythonProject\venv\lib\site-packages\instaloader\instaloadercontext.py", line 410, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.


Process finished with exit code 1

**Comment by prem573** [comment]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Fatal error: JSON Query to accounts/login/: Could not find "window._sharedData" in html response. same error still any one help me please
