### ISSUE TITLE
Too much accounts have gotten banned from Instagram

### ISSUE THREAD

**Issue by AnonC0DER** [instaloader/instaloader#1738]
Hello,
I've been using Instaloader for about 6 months. And it works really well in these 6 months. I had a few banned accounts once a week.
But it's started working weirdly. I even decreased my requests to Instagram quite a lot these days. It hasn't changed anything.
I've just checked a few profiles and 4 or 5 of my accounts have gotten banned.
I want to know if this problem is only for me or other users have same experienced these days.
And if so, is there any solution?

**Comment by Showmaster3000** [comment]
Similar things described by other users in #1702 or  #1711. Looks like recent locking down activities by instagram.

**Comment by nns33213** [comment]
At some point, all native scrapers like Instaloader will stop working. It's trivially easy for Instagram to detect bots/fake clients and if they allow some scraping, it's out of their good will. New implementations will either use headless browsers or play cat-and-mouse game of browser emulation endlessly.

**Comment by CaseyYang** [comment]
what's worse, they may stop supporting browser (like a lot of Chinese apps now) and only support their own apps, which makes scrapping much harder
