### ISSUE TITLE
Fatal error: Login: Checkpoint required. Point your browser to [link]

### ISSUE THREAD

**Issue by andreasnico06** [instaloader/instaloader#1740]
i did verify the login through that link in the browser [this was me]. But still it won’t let me login as it generate new "Fatal error: Login: Checkpoint required. Point your browser to [link]" with new link over and over even after verification.
is this just me?
i'm no programmer, correct me if i'm wrong. From what i understand, instagram detect my login on browser and my login on instaloader (terminal) is 2 different device/login. Is there any command like --cookies which you can f.e. grab cookies.txt from browser and use it on instaloader --cookies examples.txt
Thank you.

**Comment by Showmaster3000** [comment]
do you search for https://instaloader.github.io/troubleshooting.html#login-error ?

**Comment by andreasnico06** [comment]
> 

yeah i saw, then again i'm no progammer i don’t really know how it works lol
