### ISSUE TITLE
All my accounts have been banned

### ISSUE THREAD

**Issue by uvx0ol** [instaloader/instaloader#1741]
Hello, I download ~50 pics per day, with 3 accounts. I use my phone's user-id, use Instaloader 4.9.3, don't login at 3AM (only randomly at day), and basically follow all the tips and tricks found in other topics, but finally all my accounts have been totally banned. Instagram knows I am not using my phone, so is there any way to change it? I have no idea what to do anymore.

**Comment by Showmaster3000** [comment]
Nearly same question some hours ago in #1738.
