### ISSUE TITLE
Old Instagram-version within the user-agent used to receive iphone json

### ISSUE THREAD

**Issue by JeremyKj87** [instaloader/instaloader#1743]
I have noticed that the Instaloader is using an old instagram version inside its user-agent to receive the iphone structured json.
It is possible to set a custom user-agent as a Instaloader parameter, but in this specific case the user-agent is hardcoded and it uses the version 146.0.0.27.125. This version is a few years old. (latest Instagram-version: 251.1.0.11.106)

` tempsession.headers['User-Agent'] = 'Instagram 146.0.0.27.125 (iPhone12,1; iOS 13_3; en_US; en-US; ' \
                                                'scale=2.00; 1656x3584; 190542906)'`

Can this effect the stability of this software? Maybe Meta checks the version to notice or detect scraping software?
Is it possible to update this version or make it configurable and are there any benefits of doing it?

**Comment by aandergr** [comment]
This user agent has been updated in #1744, currently in `upcoming/v4.10`.

We have observed in the past that changing this user agent does have an impact on the structures that are returned by Instagram, so making it configurable might introduce a new class of problems stemming from new, incompatible response structures.
