### ISSUE TITLE
Download Reels Covered in Documentation?

### ISSUE THREAD

**Issue by c5001481cepheus** [instaloader/instaloader#1745]
Hi, I've been using Instaloader and I've found it's the best for downloading Instagram media! I've noticed however that Reels don't seem to download, so I checked the documentation to find which flag enables 'Reels' downloading and I've been having trouble finding it. I've searched similar issues on here but I can't seem to determine whether or not the feature is even implemented at all.

Is there any downloading of Reels feature, and if there is how can I use it?

Will there be any feature for Reels downloading in the future if it doesn't currently exist? Thanks!

**Comment by jamesdidit72** [comment]
Does is_video not download them?

**Comment by Showmaster3000** [comment]
Downloading reels is currently not implemented.
Duplicate of #812.
