### ISSUE TITLE
what does HTTP error code 401 mean?

### ISSUE THREAD

**Issue by jellypuppy** [instaloader/instaloader#1756]
hello i tried using instaloader and i was downloading a profile but suddenly it said JSON Query to graphql/query: HTTP error code 401.

i searched around here but i could not find anything about this.

**Comment by keygenx** [comment]
I can confirm. I have the same issue. In my case the I can download profiles with no problem, but run into this issues when trying to download hashtags.

Simplest working code to reproduce the error:
```
import instaloader
downloader = instaloader.Instaloader()
downloader.download_hashtag('cat')
```

The output:
```
JSON Query to explore/tags/cat/: HTTP error code 401. [retrying; skip with ^C]
JSON Query to explore/tags/cat/: HTTP error code 401. [retrying; skip with ^C]
Get hashtag #cat: JSON Query to explore/tags/cat/: HTTP error code 401.
```

**Comment by IL2C** [comment]
Login into an account to avoid for certain posts.

**Comment by s4shahryar** [comment]
I am facing the same issue
![image](https://user-images.githubusercontent.com/49944846/198825916-cc8847d9-2175-424c-8f66-eeaf9fa296b9.png)

**Comment by RecSRG** [comment]
I'm having the same problem. 
It appears that now Instagram is not allowing to download more than initial few photos without signing in

**Comment by s4shahryar** [comment]
When I try to sign in then it says blocked IP

**Comment by damaregapenn** [comment]
Its the same case for me. Please fix :)

**Comment by elishaovarest2000** [comment]
i have faced the same problem..and i don't know where to start.

**Comment by nebhenaytas** [comment]
There has to be a solution for this. Otherwise, this project will only serve for testing...

**Comment by nebhenaytas** [comment]
There has to be a solution for this. Otherwise, this project will only serve for testing.

**Comment by pinjiewu** [comment]
Same problems here, I did sign in for my account and I could't get_comments.

**Comment by Dileep-Vidyadara** [comment]
Finally found SOLUTION this ERROR

Earlier this **instaloader** package was used to download the content without signup.
After a few attempts, you will receive this 401 Error due to Authentication issues.

All you need to use  **L.login('USERNAME', 'PASSWORD')** as shown below 


![image](https://user-images.githubusercontent.com/47067439/202537681-81f4c39a-f8ff-487c-8ef5-8d250b36186f.png)


Thank me later :)

**Comment by safakhde** [comment]
> Finally found SOLUTION this ERROR
> 
> Earlier this **instaloader** package was used to download the content without signup. After a few attempts, you will receive this 401 Error due to Authentication issues.
> 
> All you need to use **L.login('USERNAME', 'PASSWORD')** as shown below ⬇️
> 
> ![image](https://user-images.githubusercontent.com/47067439/202537681-81f4c39a-f8ff-487c-8ef5-8d250b36186f.png)
> 
> PS: DO NOT USE VPN WHILE RUNNING THIS SCRIPT ELSE YOU MAY FIND YOURSELF IN TROUBLE. Instagram might suspend your account if you use a VPN for this script as shown below ⬇️
> 
> ![image](https://user-images.githubusercontent.com/47067439/202538751-2d6138e7-64f9-4c79-86c5-b4134319e3a5.png)
> 
> Thank me later :)

I tried this. But this error come out Login: Checkpoint required. Point your browser to the "Link of Instagram"

**Comment by RikPi** [comment]
I found myself in the same situation while logged in and from command line. The solution was to delete the session file in `AppData\Local\Instaloader\`. After I entered the password again, the problem was solved

**Comment by javierjrueda** [comment]
> Finally found SOLUTION this ERROR
> 
> Earlier this **instaloader** package was used to download the content without signup. After a few attempts, you will receive this 401 Error due to Authentication issues.
> 
> All you need to use **L.login('USERNAME', 'PASSWORD')** as shown below ⬇️
> 
> ![image](https://user-images.githubusercontent.com/47067439/202537681-81f4c39a-f8ff-487c-8ef5-8d250b36186f.png)
> 
> PS: DO NOT USE VPN WHILE RUNNING THIS SCRIPT ELSE YOU MAY FIND YOURSELF IN TROUBLE. Instagram might suspend your account if you use VPN for this script as shown below ⬇️
> 
> ![image](https://user-images.githubusercontent.com/47067439/202538751-2d6138e7-64f9-4c79-86c5-b4134319e3a5.png)
> 
> Thank me later :)

The problem is that, once you're logged in, now I have a Error 400 and my Instagram account blocked (:

**Comment by alinabel** [comment]
same here, tried with proxy and same, tried with get request works fine why is that?

**Comment by amansingh9097** [comment]
still getting the issue even after logging in. Its been months and no resolution, seems this is only good for testing after all.

**Comment by jayagopalk11** [comment]
Seems there is some rate limiting set in Instagram end that either drop's the session or logs out the user after an X number of calls. I was able to get around it by finding the count at which the session usually times out / kicks me out. I did a re-login attempt with "_L.login('USERNAME', 'PASSWORD')_" just before the magic number where it times out with some cushion. Resumed the further iterations and it worked perfectly fine for me

**Comment by votemp** [comment]
Possibly you can hit /api/v1/feed/timeline/ and get a new _sessionid_ cookie instead. At least the browser does that now and then. Have not had time to investigate that further though.

**Comment by AdamJMilton** [comment]
I don't think its a solution as much as it is a work around but I stopped logging in when I scrape accounts.

**Comment by gradus0** [comment]
anyone found a solution?
I change the proxy and the problem repeats
I can buy )

**Comment by vvazharksi** [comment]
@jayagopalk11  how did you do this, can you show example or at least explain where you do the change ? I tried looking in the classes but couldn't navigate well enough I guess..

**Comment by gradus0** [comment]
> @jayagopalk11 how did you do this, can you show example or at least explain where you do the change ? I tried looking in the classes but couldn't navigate well enough I guess..

This method works up to 20 requests, after 5 repeated authorizations, the account will be banned.
I solved this problem, now I make more than 100 requests without repeat authorizations. but it takes time to test for a complete solution

**Comment by vvazharksi** [comment]
@gradus0  how did you accomplish this ?

**Comment by gradus0** [comment]
> @gradus0 how did you accomplish this ?

Since the problem is in all libraries. Because Instagram updated protection. And I write my self software.
It took me two days to bypass the algorithm.
Not ready to tell for free)

**Comment by vvazharksi** [comment]
Fair! Share how to proceed then, price?, contact ? :)

**Comment by jayagopalk11** [comment]
@gradus0 my option would not work for cases where you could scrape multiple pages over and over. 

I usually trigger scrapping of posts for one user at a time and go with the logic below. usually I noticed that the first authorization checkpoint gets thrown around 1000 requests (Can vary depending upon the user ID used)

`
count = 0
flag = False
for post in profile.get_posts():
	print(str(count))
	'''
	if count < 1000:
		count += 1
		continue
	
	count += 1
	'''
	if count > 1000 and flag is False:
		print("Sleeping for 3 mins....")
		time.sleep(180)
		flag = True

		try:
			L.login("username", 'pass')
			print("re logged in")
		except:
			print("relogin failed")
			sys.exit(1)
	if count > 1050 and count % 50 == 0:
		flag = False

	try:
		result = L.download_post(post, PROFILE)
		if result:
			time.sleep(3)
	except:
		print("Unable to download for post: "+post.shortcode.lower())
		pass
`

After roughly 1000 records , I perform a re-login every 50 attempts and reduce the download frequency with some added delay. 
Not 100% fail proof but works. Also I uncomment the bunch of lines that I have commented on this example on retries with the count where it failed previously so that I dont have to keep checking for the files that are already downloaded.

**Comment by gradus0** [comment]
> @gradus0 Fair! Share how to proceed then, price?, contact ? :)

in my profile)

**Comment by snijesh** [comment]
You can try 
`instaloader --login=your_user_name profile houseplan2d` where `houseplan2d` is the profile you want to download

**Comment by felipeggrod** [comment]
Having the same issue

**Comment by estatistics** [comment]
Hello, I use tickle to limit the download speed inlinux.  `trickle -d 10 -u 1024 instaloader  --tagged           --abort-on=302,400,401,429  --no-captions  --no-metadata-json USER_PROFILE/`. It appears you can download about 1000 posts per day if you download fast. You must wait 24hour before you can download again. However, my problem arises in tagged posts. When there are 1000+ tagged posts, for some reason "401 error" appears even i deleted my instaloader session and itiration file, and created a new one using `python3 ./615_import_firefox_session.py`. So, i hope the programmers will succesfully find the solution to download again insta profiles and tagged posts... Do anyone has tried gallery-dl? However, changing utils that are not crossed-compatible create problems in updating insta profiles. They may think some corporation?

**Comment by milliorn** [comment]
I'm also hitting a 401. None of the above solutions are working for me.

**Comment by tojestzart** [comment]
remove C:\Users\NAME\AppData\Local\Instaloader cookie or whatever it is inside this folder?

**Comment by Shahmir-Zubair** [comment]
If there are any solutions to this please tell me it is really urgent and important for me.

**Comment by wpraiz** [comment]
Same problem

**Comment by Hedie-rashidian** [comment]
i have same problem

**Comment by stephenhky** [comment]
I have the same issue too and I didn't log in....

**Comment by Koko-boya** [comment]
After using this method to get the Session. and retrying to download this issue was fixed for me
which i founded out on https://instaloader.github.io/troubleshooting.html

**Method:**
1. Download the script: [Example 615_import_firefox_session.py](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py),
2. Login to Instagram in Firefox, (if you dont have firefox install it)
3. Execute the snippet, e.g. with python 615_import_firefox_session.py,
4. Then, run the following instaloader instaloader --login=<Yourusername used to login in firefox> <profileusername to download>
eg: instaloader --login=weebuser kawaiigallery

**Comment by liangying-Ke** [comment]
> After using this method to get the Session. and retrying to download this issue was fixed for me which i founded out on https://instaloader.github.io/troubleshooting.html
> 
> **Method:**
> 
> 1. Download the script: [Example 615_import_firefox_session.py](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py),
> 2. Login to Instagram in Firefox, (if you dont have firefox install it)
> 3. Execute the snippet, e.g. with python 615_import_firefox_session.py,
> 4. Then, run the following instaloader 
>    eg: instaloader --login=weebuser kawaiigallery`instaloader --login=<Yourusername used to login in firefox> <profileusername to download>`
Its method is useful. it makes my crawler work now.

**Comment by liangying-Ke** [comment]
> After using this method to get the Session. and retrying to download this issue was fixed for me which i founded out on https://instaloader.github.io/troubleshooting.html
> 
> **Method:**
> 
> 1. Download the script: [Example 615_import_firefox_session.py](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py),
> 2. Login to Instagram in Firefox, (if you dont have firefox install it)
> 3. Execute the snippet, e.g. with python 615_import_firefox_session.py,
> 4. Then, run the following instaloader 
>    eg: instaloader --login=weebuser kawaiigallery`instaloader --login=<Yourusername used to login in firefox> <profileusername to download>`

Its method is useful. it makes my crawler work now.

**Comment by yarodevuci** [comment]
in my case it works locally, but 401 if i run it on server

**Comment by kingoo123** [comment]
> Hello, I use tickle to limit the download speed in linux. `trickle -d 10 -u 1024 instaloader --tagged --abort-on=302,400,401,429 --no-captions --no-metadata-json USER_PROFILE/`. It appears you can download about 1000 posts per day if you download fast. You must wait 24hour before you can download again. However, my problem arises in tagged posts. When there are 1000+ tagged posts, for some reason "401 error" appears even i deleted my instaloader session and itiration file, and created a new one using `python3 ./615_import_firefox_session.py`. So, i hope the programmers will succesfully find the solution to download again insta profiles and tagged posts... Do anyone has tried gallery-dl? However, changing utils that are not crossed-compatible create problems in updating insta profiles. They may think some corporation?
> 
> * Note that i can download normally stories but not tagged posts (401 error).
I try to execute this script. But on the third step, I get the error of "cookie import failed: JSON Query to graphql/query: HTTP error code 401". I can confirm that my ins account can log in normally on firefox.

**Comment by kingoo123** [comment]
> After using this method to get the Session. and retrying to download this issue was fixed for me which i founded out on https://instaloader.github.io/troubleshooting.html
> 
> **Method:**
> 
> 1. Download the script: [Example 615_import_firefox_session.py](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py),
> 2. Login to Instagram in Firefox, (if you dont have firefox install it)
> 3. Execute the snippet, e.g. with python 615_import_firefox_session.py,
> 4. Then, run the following instaloader `instaloader --login=<Yourusername used to login in firefox> <profileusername to download>`
>    eg: instaloader --login=weebuser kawaiigallery

I try to execute this script. But on the third step, I get the error of "cookie import failed: JSON Query to graphql/query: HTTP error code 401". I can confirm that my ins account can log in normally on firefox.

**Comment by HanJunSeoJB** [comment]
> in my case it works locally, but 401 if i run it on server

It's the same as my situation. It works locally, but the server shows 401

**Comment by mezhgano** [comment]
Same problem here, with and without Firefox session snippet.

**Comment by thinsoldier** [comment]
I have the same problem. I only ever download a handful of photos per day manually so I shouldn't be running into the same problem as someone downloading entire profiles systematically.

There are some post ids that download without problems and others that give the 401 error.

For example, this post with multiple photos downloads fine: CsqlrawLx5b
This post with 1 photo gives HTTP error code 401: CsyowrVtj6J
In both cases if I open these post URLs directly in an incognito browser the instagram website never loads (in Firefox).
https://www.instagram.com/p/CsqlrawLx5b/
https://www.instagram.com/p/CsOn01Wo-17/

I tried using my login and password and every time it fails and directs me to a link where instagram forces me to change my password.

```
Session file does not exist yet - Logging in.
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/AXHah....../Afw3w...../ffc_jGpROgjXnPWfpo...../ - follow the instructions, then retry.

```

**Comment by avsym** [comment]
> > After using this method to get the Session. and retrying to download this issue was fixed for me which i founded out on https://instaloader.github.io/troubleshooting.html
> > **Method:**
> > 
> > 1. Download the script: [Example 615_import_firefox_session.py](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py),
> > 2. Login to Instagram in Firefox, (if you dont have firefox install it)
> > 3. Execute the snippet, e.g. with python 615_import_firefox_session.py,
> > 4. Then, run the following instaloader `instaloader --login=<Yourusername used to login in firefox> <profileusername to download>`
> >    eg: instaloader --login=weebuser kawaiigallery
> 
> I try to execute this script. But on the third step, I get the error of "cookie import failed: JSON Query to graphql/query: HTTP error code 401". I can confirm that my ins account can log in normally on firefox.

Hi, i had same issue. Try to change number in 21 line of `615_import_firefox_session.py` file. For me work this
```
return cookiefiles[1]
```

**Comment by QdotD** [comment]
> in my case it works locally, but 401 if i run it on server

yep me too

**Comment by aimbot6120** [comment]
One workaround is using a sleep timer. I let the process sleep for 0.1s after every 5 posts (I am only downloading metadata, so the request rate is rather high). I am running it locally but I think it should work on servers as well.

**Comment by RazyRo** [comment]
Still having same issue

**Comment by Manwithpants812** [comment]
Trying to fully scrape a profile, Instagram says Instaloader is logging in from "Linux" and marks it as suspicious activity. Why is instaloader using a Linux User Agent by default rather than a more common one like Chrome or Firefox? Pretty dumb (unless there's an already established strategy why).

I'm getting 401 errors after a dozen minutes, deleting the login file and letting instaloader re-login "fixes" it and resumes downloading, going to IG Settings on the website and marking the login as safe and not suspicious seems to probably help.

**Comment by satoshinotdead** [comment]
I'm facing the same issue and I don't know what the issue is closed.

Instagram logged out all my accounts after using Instaloader. I'm using VPN as daily basis and I wonder where can I remove all login data on Instaloader, just for testing?

Instaloader download saved data but not in collections, so I need to run it again for download that 'new' saved data that I get out of collections :(

**Comment by RedValis** [comment]
The issue as it appears only occurs on linux and its subsystems, works just fine on my win machine, but not on a linux command line

**Comment by reln549** [comment]
It's an authentication problem. Deleting the instaloader cookie file and logging in again solves the problem for only a few posts. The web browser session is closed and asks for captcha. And on the meta profile management center page, by clicking on password and security it tells me that I have access from Linux, but by validating the access it still doesn't let me download and disconnects me, with a 401 error.

**Comment by Manwithpants812** [comment]
> how did you do that "deleting the login file and letting instaloader re-login "fixes" it" ? can you explain please.

Instaloader logs in to Instagram and creates a "session file" where the login details are saved. Anytime you use Instaloader, it reuses the same session file (if indicating to use the same account). If you delete the session file manually (located at "C:\Users\USER\AppData\Local\Instaloader\session-USERNAMEOFACCOUNT", Instaloader will login again and create a new session file.

To what I described in my previous comment, I can still confirm that instaloader always uses a Linux User Agent, when providing the login user/pass to instaloader or when using the new feature to load cookies from browser, specifically this:
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`

Again, I don't know why it's using a Linux UA instead of something more common or the specific UA from the browser the cookies are being loaded from that could probably not trigger Meta's detections as much, unless there's a specific tried strategy for using it that I'm not aware of.

**Comment by satoshinotdead** [comment]
This still being an issue and should to be opened.

**Comment by phoenix1887** [comment]
This is still a big issue and needs to be addressed officially.

**Comment by satoshinotdead** [comment]
I can confirm that [loading cookies works](https://github.com/instaloader/instaloader/issues/2165#issuecomment-2041230960) and bypass this error so far.

**Comment by JoseAndresMoraila** [comment]
How you can save cookies?

**Comment by satoshinotdead** [comment]
@JosephMoraila you can read, you just need to follow the instructions that will use the cookies from your web-browser.
