### ISSUE TITLE
How do I slow the download rate for not getting banned??  

### ISSUE THREAD

**Issue by girowue** [instaloader/instaloader#1757]
Hi! 

I was looking at [https://instaloader.github.io/module/instaloadercontext.html#instaloader.RateController](https://instaloader.github.io/module/instaloadercontext.html#instaloader.RateController) but I don't know to effectiveely slow down the download rate.

Could someone give a example?? Is there a way to pass an argument with the "sleep" time between each download? (it would be great to have this feature, as I haven't seen it in the documentation).

Thanks in advanced!

**Comment by rum416** [comment]
Use this fork, it has time sleep delay.
https://github.com/rum416/instaloader

**Comment by rum416** [comment]
You can edit the seconds value in `instaloadercontext.py`
under line 'if is_graphql_query:`

**Comment by cunlem** [comment]
Did you get your account banned for using instaloader @girowue? I want to download profile but I'm afraid I will lose my account as soon as they detect automated behavior. If default delay results in ban then it should be increased (and randomized) rather then being left as an exercise to the user or forks.

**Comment by girowue** [comment]
> Did you get your account banned for using instaloader @girowue? I want to download profile but I'm afraid I will lose my account as soon as they detect automated behavior. If default delay results in ban then it should be increased (and randomized) rather then being left as an exercise to the user or forks.

No, I didn't get banned my account. Just couldn't download with instaloader for some 20-30 minutes. 



> You can edit the seconds value in `instaloadercontext.py` under line `if is_graphql_query:`

Ok, thanks!! :)  It would be a great feature to have this option on the main instaloader git.

**Comment by rum416** [comment]
I've made the time delay random between 9 and 14 seconds. You can install and update the script again.

**Comment by Allen-Kwan** [comment]
> I've made the time delay random between 9 and 14 seconds. You can install and update the script again.

Rudimentary question, but how do I install your version of the script?  Is it the same pip command?  Is there a compiled executable like in this version?

**Comment by rum416** [comment]
No, there is no compiled exe of this version.

`pip uninstall instaloader`
then
`pip install https://github.com/rum416/instaloader/archive/refs/heads/add-sleep-delay.zip --no-cache-dir`

**Comment by top31** [comment]
> rubbish tool

**Comment by confidencedrawer** [comment]
In case anyone has the same problem (since it's a relatively common problem), this solution works.

**Comment by Allen-Kwan** [comment]
Hi @rum416  , not sure if you're still checking this at all but is there anyway you could update it with the latest version of instaloader?  For some reason it just stops running after it sleeps once now.
