### ISSUE TITLE
Cant get --dirname-pattern to work with :stories

### ISSUE THREAD

**Issue by aaasddd** [instaloader/instaloader#176]
I want all my followers stories downloaded into their respective folders. I read the documentation but can't seem to get --dirname-pattern to work, and I'm a little confused by the documentation. Tried it as below and also --dirname-pattern{profile}, but same error. 

`instaloader -l username -p passwd --dirname-pattern --no-video-thumbnails --no-captions --no-metadata-json :stories`

`instaloader --dirname-pattern={profile} --filename-pattern={profile}_{date_utc} -l username -p password --no-video-thumbnails --no-captions --no-metadata-json :stories`

**Comment by Thammus** [comment]
I just tried the last invocation you commented and Instaloader behaves as intended: For each followee who has a visible story, a new folder (inside the current working directory) gets created which contains all associated stories.
How is Instaloader behaving on your side and what problems or errors are you experiencing?
