### ISSUE TITLE
Reels: Difference between "play_count", "view_count" (or "video_view_count")

### ISSUE THREAD

**Issue by mauronr** [instaloader/instaloader#1761]
Hi there.

The context of this question is videos posted as Reels.

The number of plays (or views) shown on the Instagram UI (see the screenshot below) under the Reels tab doesn't match the field `video_view_count` in the JSON Instaloader produces when requesting the data from a specific post.

Investigating the requests from Instagram app to their server via the browser console apparently there are 2 different fields related to how many times as video has been played or viewed: `play_count` and `view_count`. These differ quite a lot and  Instaloader reports only `view_count` 

My two questions are:
   - Is it known the difference from `play_count` to `view_count`? I tried googling and browsing FB's docs, but no luck;
   - Is there any way to make instaloader bring both fields, instead of only one, be it in the command line or using it as a python module?

Here's what I found while investigating:

#### From `instaloader --no-compress-json -- -ChiewJsF6MO`
The JSON shows `video_view_count: 322` 

The same when I "curl" from `i.instagram.com/api/v1/users/web_profile_info/?username=<username>`
Apparently this endpoint is where Instaloader fetches the data. 

#### Curl'ing  `i.instagram.com/api/v1/media/<media_id>/info` and ``http://i.instagram.com/api/v1/clips/user``
The resulting JSON shows 2 related fields
  - `play_count: 624`
  - `view_count: 322`

#### The screenshot from Instagram's web UI, in the Reels tab.

![Screen Shot 2022-10-07 at 15 50 56](https://user-images.githubusercontent.com/5508880/194632052-4417738d-fabf-48ac-a989-7523ca245665.png)

**Comment by IL2C** [comment]
1. https://developers.facebook.com/ads/blog/post/2018/07/31/mapi-video-metrics/
2. A method would have to be implemented for the `play_count` field.

**Comment by mauronr** [comment]
Thanks a lot @IL2C !!

Looking at the source code a bit deeper, I managed to get what I needed using Instaloader as a module, with `Post._phone_struct` with an authenticated session.

That'll issue a request to `https://i.instagram.com/api/v1/media/<<MEDIA_ID>>/info/` which contains the data I was looking for

Sample code:
```
instaloader = Instaloader()
instaloader.load_session_from_file(username, sessionfile)
post = Post.from_shortcode(instaloader.context, shortcode)
post_details = post._iphone_struct
```
