### ISSUE TITLE
Get Instagram Feed Following insteed of default feed given by algorithm ?

### ISSUE THREAD

**Issue by mrousse83** [instaloader/instaloader#1762]
Hello,

I use this command :
`instaloader.v4.9.5.exe --fast-update :feed`

But i don't get feed in chronological order, just order given by the algorithm of Instagram.
And i have for a long time no update and after sometimes, big update.
But when i check, i don't get all feed update. It's not complete.

Did you know a way for get feed in chronological order ?

You can test on Instagram, go on your "Home Feed", tap on “Instagram” on top of your screen, choose “Following” :
https://www.instagram.com/?variant=following

Thanks,
Mathieu

**Comment by aandergr** [comment]
I would like to track this as a feature suggestion, since it would be a nice enhancement to allow for downloading that variant of the feed again.
