### ISSUE TITLE
get_top_posts() throws ConnectionException

### ISSUE THREAD

**Issue by MatthiasEg** [instaloader/instaloader#1763]
**Describe the bug**
get_top_posts() throws ConnectionException whereas get_posts_resumable() does not.

Stacktrace of exception:
File "../sectioniterator.py", line 44, in __next__
    self._page_index, self._section_index, self._data = 0, 0, self._query(self._data["next_max_id"])
  File "../sectioniterator.py", line 32, in _query
    self._context.get_json(self._query_path, params={"__a": 1, **pagination_variables})
  File "../instaloadercontext.py", line 394, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "../instaloadercontext.py", line 394, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "../instaloadercontext.py", line 384, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to explore/tags/bodybuilding/: Expecting value: line 1 column 1 (char 0)

**To Reproduce**
Run and compare : 
`instaloader.Hashtag.from_name(self.loader.context, "food").get_top_posts()`
with:
`instaloader.Hashtag.from_name(self.loader.context, ht).get_posts_resumable()`

**Expected behavior**
get_top_posts() should yield the top posts of the hashtag in a resumable way, as get_posts_resumable() does, without throwing a ConnectionException.

**Instaloader version**
4.9.5

**Comment by aandergr** [comment]
Thanks for reporting; indeed, even though all top posts are fetched (and hence you could interrupt the function with islice()), it fails when attempting to access the next page of top posts, similar to what has been outlined in #1751, which uses the same mechanism.
