### ISSUE TITLE
Virustotal false positives?

### ISSUE THREAD

**Issue by h82b8** [instaloader/instaloader#1766]
Hey, virustotal shows a few positive results in the latest standalone v4.9.5 .exe for windows, I assume these are false positives?

https://www.virustotal.com/gui/file/e61b19c53f5a5624e4758e2866114d0bc1082f82ca79ccd2744fe446063b2304

**Comment by Showmaster3000** [comment]
yeah, the report is false positive. This happens from time to time. reported before in #1002.

You could report this false-positive to your antivirus vendor, helping them to ship better software and sparing other users that scary message.
