### ISSUE TITLE
it doesn't proceed to login

### ISSUE THREAD

**Issue by micromatrix14** [instaloader/instaloader#1767]
once, I start instaloader, it doesn't even initiate a download or even could login (by the fact that, when I repeat the common I need to enter my password again"

instaloader --login myprofile_name profile the_profile_I_want_to_download

and it gives me this msg
![instaloader](https://user-images.githubusercontent.com/22969054/195048894-5ba722cd-cc8f-48d9-900c-1792ec65a489.png)

**Comment by Showmaster3000** [comment]
Duplicate of #1758.
