### ISSUE TITLE
Invalid username ...]  Errors or warnings

### ISSUE THREAD

**Issue by roher-dotcom** [instaloader/instaloader#1768]
**Describe the bug**
roher@linux-vm:~$ instaloader gungungupta137 [gungungupta137 ...]

HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=gungungupta137 to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/

HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=gungungupta137 to https://www.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
gungungupta137: Redirected to login page. Use --login.
[gungungupta137: Invalid username [gungungupta137
...]: Invalid username ...]

Errors or warnings occurred:
gungungupta137: Redirected to login page. Use --login.
[gungungupta137: Invalid username [gungungupta137
...]: Invalid username ...]
roher@linux-vm:~$ 

**To Reproduce**
instaloader gungungupta137 [gungungupta137 ...]

**Expected behavior**
download profile

**Error messages and tracebacks**
Invalid username [gungungupta137
...]: Invalid username ...]

**Instaloader version**
roher@linux-vm:~$ instaloader --version
4.9.5

**Additional context**

**Comment by roher-dotcom** [comment]
> It is that you are putting the parameters badly. You should not put anything after the username. Thus:
> 
> `instaloader gungungupta137`
> 
> The square brackets only indicate, an iteration. That is to say that you can put several names in a row (without square brackets, of course).
> 
> Example:
> 
> `instaloader profile1 profile2 profile3`
> 
> Greetings.

roher@linux-vm:~$ instaloader gungungupta137

HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=gungungupta137 to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/

HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=gungungupta137 to https://www.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
gungungupta137: Redirected to login page. Use --login.

Errors or warnings occurred:
gungungupta137: Redirected to login page. Use --login.

**Comment by Showmaster3000** [comment]
The message is clear: you have to login to proceed. Anonymous download is limited to a very minimum of posts.

**Comment by roher-dotcom** [comment]
> The message is clear: you have to login to proceed. Anonymous download is limited to a very minimum of posts.

Okk...even after login it is showing same msg.. and it is not working in linux for me..I don't know what going wrong...so finally I'm install it on windows and it is working fine in my windows pc

**Comment by roher-dotcom** [comment]
Is there any way to download all reels of a profile..bcz in post download option it download only picture and video and metadata...but post didn't cover all reels of a profile.. so I had to do manually work to download reels of a profile.. is there any way to download all reels of a profile at once ..if yes pls inform me...
.
Grateful towards all of u guys and instaloader..thanks
