### ISSUE TITLE
"name='csrftoken', domain=None, path=None"

### ISSUE THREAD

**Issue by WalidHadri-Iron** [instaloader/instaloader#1770]
It has been some weeks that I am getting this:

KeyError: "name='csrftoken', domain=None, path=None"

When I try to login
L = instaloader.Instaloader()
L.login(username, password)

**Instaloader version**
`instaloader --version` 4.9.5.

Thanks for the help !

**Comment by Showmaster3000** [comment]
Duplicate of #1758
