### ISSUE TITLE
[Feature Request] Let the user choose an arbitrary sleep timer

### ISSUE THREAD

**Issue by curya** [instaloader/instaloader#1775]
**Provide us a use case of the feature**
Since Instagram is very quick to lock or ban accounts for downloading a lot of pictures. It would be nice if the user could choose a longer sleep timer of their choice to get around this.
I don't think many people have an immediate need to download all the pictures on a profile as quickly as possible. I'm perfectly happy queueing up a few profiles that won't finish for 24 hours as long as it means Instagram will never detect what I'm doing.

**Describe the solution you'd like**
I should be able to type something like --sleep=60 to sleep 60 seconds between posts.

**Describe alternatives you've considered**
Nothing.

**If the feature request is accepted, would you be willing to submit a pull request?**
No. I'm not a programmer.

**Additional context**
No other context.

**Comment by Showmaster3000** [comment]
Request seems a dulicate of #1006 and #1668.

**Comment by curya** [comment]
Oh my mistake. Is there any reason why this hasn't been implemented before? It seems like a very useful thing to have...

**Comment by Showmaster3000** [comment]
From the linked issues:
> Instaloader has a logic to keep track of its requests to Instagram and defers subsequent ones in order to not reach Instagram's rate limits. This rate controlling logic also gets applied when using Instaloader through CLI.
_Originally posted by @Thammus in https://github.com/instaloader/instaloader/issues/1006#issuecomment-774186067_

**Comment by curya** [comment]
Except it doesn't work judging simply from the amount of issues open about people getting errors or locked out of their account...

**Comment by aandergr** [comment]
> It would be nice if the user could choose a longer sleep timer of their choice to get around this.

There is; please read the documentation, especially https://instaloader.github.io/module/instaloadercontext.html#instaloader.RateController.

As already discussed in #1006,

> When used through CLI, Instaloader applies its default rate control logic. Making adjustments to this logic is a non-standard use-case, for which a CLI is generally badly suited.
