### ISSUE TITLE
GUI instead commands

### ISSUE THREAD

**Issue by Lucas559-noob** [instaloader/instaloader#1776]
**Provide us a use case of the feature**
People that don't like to do commands each time will think the program is hard/boring to use, so a GUI would make it simpler and more intuitive

**Describe the solution you'd like**
With a GUI, the user could select some checkboxes of what download, after that, the user place on a textbox the user or users he wants to download stuff

**Describe alternatives you've considered**
An command creator for browser, this can help a bit if a GUI would not be created

**If the feature request is accepted, would you be willing to submit a pull request?**
No

**Comment by aandergr** [comment]
Out of scope.
