### ISSUE TITLE
Each time that i try to login to download stories, insta gets that and says "suspisicion behavior". 

### ISSUE THREAD

**Issue by estatistics** [instaloader/instaloader#1778]
instaloader    --login=USERNAME  --stories-only   --no-metadata-json profile/

Each time that i try to login to download stories, insta gets that and says "suspisicion behavior". 

```
In module products sys.path[0], __package__ == /home/elias/.local/bin instaloader
Session file does not exist yet - Logging in.
Enter Instagram password for USERNAME: 
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/XXXXXXXXXXXXXXXXXXXXXXXXXX/ - follow the instructions, then retry.
```

**Comment by estatistics** [comment]
version 4.8.4 in linux kde bullseye11

**Comment by Showmaster3000** [comment]
see https://instaloader.github.io/troubleshooting.html#login-error
The "suspisicion behavior" (which should be a mail) is normal for non-instagram-own systems and can be ignored.

**Comment by estatistics** [comment]
When i installed the latest version, the error were fixed. Thanks.
