### ISSUE TITLE
profile-pic without login 

### ISSUE THREAD

**Issue by gnu-like** [instaloader/instaloader#178]
In previous I used: 
`instaloader -P 'cat target.txt'`
but now I got : 
--login=USERNAME required

**Comment by aandergr** [comment]
Please read https://instaloader.github.io/contributing.html and obey the bug report issue template. Without the error message or the instaloader invocation we have no chance to see what's wrong.

**Comment by aandergr** [comment]
Ah now I see. When downloading profiles with `--profile-pic-only`, Instaloader prints the login required error message for each profile, but still downloads the profile pictures.
