### ISSUE TITLE
Pulling Followers but only pulling followers that haven't yet been pulled 

### ISSUE THREAD

**Issue by zachasman** [instaloader/instaloader#1781]
Hello,

I have a script that is trying to pull followers for an Instagram account. The account has about 100K followers. When I run the script below, it pulls about 45K of those followers, which is pretty good, but obviously not even half of what I need.

Is there a way I can setup a script where with each run, it only collects the followers it hasn't previously already extracted? So the next time I run it, it will exclude extracting those first 45K.

For reference, here is the script:

```
# Get instance
import instaloader

L = instaloader.Instaloader()

# Login or load session
username = "XXXXX"
password = "XXXXX"
L.login(username, password)  # (login)

# Obtain profile metadata
profile =  .Profile.from_username(L.context, 'zheng_max_')

# Print list of followees
follow_list = []
count = 0
for followee in profile.get_followers():
    follow_list.append(followee.username)
    file = open("zheng_max_followers.txt", "a+")
    file.write(follow_list[count])
    file.write("\n")
    file.close()
    print(follow_list[count])
    count = count + 1
# (likewise with profile.get_followers())
```

**Comment by zachasman** [comment]
Bumping this!

**Comment by roncam82** [comment]
Hi,

can this be done please ?

thanks
