### ISSUE TITLE
Instaloader get_stories returning an empty list or BadResponseException

### ISSUE THREAD

**Issue by cipherbreaker** [instaloader/instaloader#1786]
**Describe the bug**
Instaloader is supposed to fetch instagram stories from an specific user. However the L.get_stories() returns an error. If an username is provided the function returns an empty iterator (no stories, even if they exist in the profile).

```
Traceback (most recent call last):
  File "/home/user/Documents/insta/main.py", line 15, in <module>
    for story in stories:
  File "/home/user/Documents/insta/venv/lib/python3.10/site-packages/instaloader/instaloader.py", line 787, in get_stories
    raise BadResponseException('Bad stories reel JSON.')
instaloader.exceptions.BadResponseException: Bad stories reel JSON.
```

**To Reproduce**
I tried the code shown in [documentation](https://instaloader.github.io/module/structures.html#user-stories). Also added some code to load session and configure usernames.

```
import instaloader

my_username = 'omitted'
target_username = 'rudauffoficial'

L = instaloader.Instaloader()
L.load_session_from_file(my_username)

profile = instaloader.Profile.from_username(L.context, target_username)
profile_id = profile.userid

#stories = L.get_stories([profile_id])
stories = L.get_stories()

for story in stories:
    for item in story.get_items():
        L.download_storyitem(item, ':stories')
```

**Expected behavior**
The function get_stories() should return an iterator of Story or provide the link to story itself.

**Error messages and tracebacks**
They are explained above but, for the sake of description, if an username is provided it returns an empty list. When no username is provided, an error occurs.

```
Traceback (most recent call last):
  File "/home/user/Documents/insta/main.py", line 15, in <module>
    for story in stories:
  File "/home/user/Documents/insta/venv/lib/python3.10/site-packages/instaloader/instaloader.py", line 787, in get_stories
    raise BadResponseException('Bad stories reel JSON.')
instaloader.exceptions.BadResponseException: Bad stories reel JSON.
```

**Instaloader version**
4.9.5

Thanks in advance.

**Comment by aandergr** [comment]
I just tried your code, both variants (both with a specified profile_id and without), and it worked for me.

**Comment by Demi-O** [comment]
Hi, I am running into this exact issue. I am trying to use get_stories() with a profile_id and I get an empty list, and when trying without any id's, I get the `instaloader.exceptions.BadResponseException: Bad stories reel JSON.` as soon as I try to loop through the iterator.

@cipherbreaker did you ever get this working?
@aandergr what version of instaloader do you have installed? I am on the latest `4.10`
