### ISSUE TITLE
How to download reels

### ISSUE THREAD

**Issue by Octo-Siddharth** [instaloader/instaloader#1788]
How to download Reels or specific reel files using instaloader, please help. Suggest me with the code if possible. Thanks a ton in advance.

**Comment by Octo-Siddharth** [comment]
How to download Reels or specific reel files using instaloader, please help. Suggest me with the code if possible. Thanks a ton in advance.

**Comment by n0x5** [comment]
import instaloader
import time
import os
import argparse

user_agent1 = 'YOUR_USERAGENT'
filename_pattern1 = r'{profile}_{date_utc}_{filename}'
login = 'YOUR_USERNAME'

L = instaloader.Instaloader(user_agent=user_agent1, filename_pattern=filename_pattern1)
parser = argparse.ArgumentParser()
parser.add_argument('reel')
args = parser.parse_args()


L.load_session_from_file(login)


post = instaloader.Post.from_shortcode(L.context, args.reel)
L.download_post(post, target=args.reel)

**Comment by aminitindas** [comment]
the python file: reels-dl.py

giving:
usage: reels-dl.py [-h] reel
reels-dl.py: error: the following arguments are required: reel
