### ISSUE TITLE
Download of saved posts does not reach the end

### ISSUE THREAD

**Issue by booskahmed** [instaloader/instaloader#1792]
**Describe the bug**
After running a command for saved posts scraping, the download does not complete until the end
The number progress at the beginning of each line (for example : [500/600]) stops before the total number of shown saved posts

I ran a command to download all my saved posts. I have 1254 of them
I waited enough for the command to finish and the rate limitations... so i know it's not a problem of too much requests.
The download ends at the 1173th post and the terminal shows : Iteration complete, deleted resume information file...

**To Reproduce**
downloaded all my saved posts : 
instaloader --login "myaccount" --title-pattern={profile}/{date_utc} :saved

**Expected behavior**
The download goes until it reaches [1254/1254]

**Instaloader version**
4.9

**Additional context**
May be the posts missing have been deleted, i just want to know why iy doesn't finish

cmd : https://prnt.sc/dmfSD7Gao-Xb

**Comment by alexlyee** [comment]
Having the same issue.

**Comment by aandergr** [comment]
If you scroll down in your browser or in the app of your saved posts page, are there any pictures shown which are not downloaded by Instaloader?
