### ISSUE TITLE
How to use .get_comments() function from Posts using python module

### ISSUE THREAD

**Issue by ErikJAS** [instaloader/instaloader#1793]
This question should perhaps be converted to a bug issue, but since I don't know if I'm just doing something wrong, I'll start my quest here:

I have tried many various ways of using the .get_comments() function from Posts instagram structure.

I receive the following message regardless of method:
"JSON Query to graphql/query: HTTP error code 401."

I am not logged in, but from the documentation it is not clear that this is needed to use this function.

Does anyone have a similar issue or am I just completely out to lunch with my coding?

**Comment by iSkyN3t** [comment]
Hi, unfortunately I am facing the same issue. Additionally I tried to login, but I always get back "raise ConnectionException("Login: Checkpoint required. Point your browser to". Then I need to accept in browser, that it was really me, who tried to login. After many retries, still the same exception raises. I assume, that you need to be logged in, but I can't login properly :D

**Comment by ErikJAS** [comment]
Yes, I have also faced the same login-problem as well.

**Comment by Joemol94** [comment]
Facing the same issue. Even after confirming the prompt for security authentication on my Instagram account.
Anyone facing the same issue was able to resolve it?
