### ISSUE TITLE
Idk what is going on here but it's not working for private profiles

### ISSUE THREAD

**Issue by Parth589** [instaloader/instaloader#1796]
Your question here...

Session file does not exist yet - Logging in.
Enter Instagram password for xyz:
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/someLink/ - follow the instructions, then retry.

**Comment by Showmaster3000** [comment]
Did you see #1787?
Anyway I can't see your question...

**Comment by top31** [comment]
> > Did you see #1787? Anyway I can't see your question...
> 
> You only see what you want to see

**Comment by Parth589** [comment]
Yeah I got it 🙂
