### ISSUE TITLE
Ability to prune comments so that massive comment sections don't take hours to download

### ISSUE THREAD

**Issue by alexlyee** [instaloader/instaloader#1799]
I'd like to download all of my saved posts w/ comments, but some of them have absurd numbers of comments (as we're speaking, one of them is up to 50,000.) This adds a huge amount of time to the download.

**this would be cool:**
An ability to only save the top n comments (by likes)
An ability to only consider the first n comments (in intervals of 250, how they are packaged from instagram)

**a note:**
I have not tried using the API to do this myself, and I'm pretty sure I could get it to work there, but it isn't so important to be that I'd need to do that.

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes

**Comment by aandergr** [comment]
This does not seem to fit into Instaloader itself, as it can be easily done with a script that uses Instaloader as a module.
