### ISSUE TITLE
Option to download only high quality version of posts

### ISSUE THREAD

**Issue by duoside** [instaloader/instaloader#1800]
I see that Instaloader downloads lower quality images (1080x1350) and videos when it is unable to retrieve the higher quality (1440x1800) versions. This situation is encountered when Instaloader tries to download too many posts at a time. It would be nice to have an option to instruct the program to stall/exit in such situations instead of downloading posts in lower quality.

If the feature request is accepted, would you be willing to submit a pull request?
Will take time but yes

**Comment by Showmaster3000** [comment]
Did you check the lower quality posts that there are versions with a higher resolution available? Sometimes people upload smaller images and they will not be upscaled.

**Comment by afterdelight** [comment]
halo

**Comment by duoside** [comment]
Yes, I can confirm that higher quality versions are available and Instaloader is actually able to retrieve them when using a different account that hasn't been used much for scraping

**Comment by thereareno** [comment]
OMG yes this feature. Devs, I would be happy to donate again for this feature.

**Comment by aandergr** [comment]
Instaloader usually tries to load the media in the best possible quality first. If the associated requests are answered with certain error codes, it will fall back to downloading a lower quality.

So the suggestion seems to be to introduce an option to abort with an error instead in such a case. I would find that ok.
