### ISSUE TITLE
Add Option to Automatically Get Cookies from Browser So Downloading with Instaloader Can Actually Work

### ISSUE THREAD

**Issue by EveryDirection** [instaloader/instaloader#1801]
As discussed in issue #1787, Instaloader is often or always now completely failing at downloading  unless cookies are loaded from the browser after first logging into Instagram via browser. So my suggestion is adding an option to Instaloader like

`--load-cookies browser`

wherein you can specify that _browser_ string as `chrome`, `firefox`, etc., or as a path to a specific browser cookies file, to automatically load cookies from that browser so that downloading can actually work.

Note that the YouTube downloader [yt-dlp](https://github.com/yt-dlp/yt-dlp) has a working similar option, `--cookies-from-browser browser`, for just this reason. Similar code could be used here.

**Comment by Eikreis** [comment]
This would be great. I've noticed a significant increase in failed logins or suspicious/challenge flags, culminating in a complete blockage preventing instaloader from working. I can login fine from browser but it flags every time using instaloader now.

**Comment by rouncewell** [comment]
I too am no longer able to use Instaloader. It's always requiring a checkpoint challenge now.

**Comment by estatistics** [comment]
download instaloader from source, go to instaloader-master/docs/codesnippets/, and run 615_import_firefox_session.py and then instaloader. It loads the cookies from your browser.

**Comment by Eikreis** [comment]
> download instaloader from source, go to instaloader-master/docs/codesnippets/, and run "python3 615_import_firefox_session.py" and then instaloader. It loads the cookies from your browser.

I've tried this with an active session on firefox but it fails with this response:
```
Using cookies from C:\Users\username/AppData/Roaming/Mozilla/Firefox/Profiles\8v7eb9lq.default\cookies.sqlite.
Cookie import failed: no such table: moz_cookies
```

**Comment by Eikreis** [comment]
No luck either with or without admin on windows.

**Comment by aandergr** [comment]
There is a script at https://instaloader.github.io/troubleshooting.html#login-error which loads the firefox cookie file from a default path, or from a path specified via a CLI argument, and saves it into an Instaloader session file.

This is clearly thought as a fall back for when the login does not work; however, given that the login is among the parts that break the most, it would be convenient for many users to have that feature directly implemented into Instaloader, and I will be happy to review a pull request for this.

**Comment by tathastu871** [comment]
But Such Scripts wont work on android platform when instaloader is used from termux. 
Howver it may work on proot-distro inside termux as they have firefox/chromium

**Comment by tathastu871** [comment]
Instead add small selenium code to open browser then login and use edit this cookie chrome extension to copy the Cookies in **NetscapeFormat** to clipboard and use that cookies to login.

Slenium based method will also work in proot-termux
Also now termux offivial repo has selenium and firefox and gecko driver Via x11

**Comment by JunedKhan101** [comment]
@aandergr I have a PR ready for this, I'm testing it out right now testing has been intermittently slow because I'm getting this error #2011 

Let me know if that sounds good, meanwhile maybe you can tell me about how to counter getting the JSON query error?

**Comment by JunedKhan101** [comment]
I have created a PR for this. Please review and let me know if it requires any changes.

**Comment by thebix** [comment]
Hi @JunedKhan101 
Thanks for working on this really desired feature 🙌

I've noticed that the cookie feature with the current implementation [Feature/load cookies from browser](https://github.com/instaloader/instaloader/pull/2040) works only on desktop machines which makes it impossible to run instaloader in, for instance, normal docker containers or on the machine without X11.

In the [issue description](https://github.com/instaloader/instaloader/issues/1801#issue-1437304979) @EveryDirection mentioned another way of loading cookies
> or as a path to a specific browser cookies file

Since the [yt-dlp](https://github.com/yt-dlp/yt-dlp) was used as an example and its way of loading cookies from the browser was used as a base for the implementation, maybe its feature of loading cookies from plain-text files can be used in instaloader as well?

Here is [Filesystem Options](https://github.com/yt-dlp/yt-dlp#filesystem-options) part of yt-dlp configuration that describes the idea

```
--cookies FILE                  Netscape formatted file to read cookies from
                                and dump cookie jar in
```

This makes it possible to provide plain-text file with cookies and, I guess, avoid using the `browser_cookie3` library that requires some X11 dependencies.
For the yt-dlp it perfectly works making it possible to run app on machines without X11.

Unfortunately, my knowledge in Python is very low. So I wonder if it's possible for you or anyone else interested in this topic to implement this feature to make instaloader independent from GUI dependencies.

**Comment by ekalin** [comment]
You should be able to copy the cookies.sqlite file (in the case of Firefox -- for Chrome it's another file, but the principle is the same) to the container or remote server, and then import the cookies from this file. There should be no need for an actual browser or even X libraries.

**Comment by thebix** [comment]
wow, thanks for such a quick answer and for your suggestion, @ekalin 
I did try that, but it didn't work. Maybe I did something wrong.

Here are my steps

1. Login to instagram in Google Chome on my Macbook
2. Copy file `~/Library/Application Support/Google/Chrome/Default/Cookies` to the docker container I'm using for tests
3. Run instaloader (in the directory with `Cookies` file)

As far as I can understand the implementation ([instaloader/__main__.py](https://github.com/instaloader/instaloader/pull/2040/files#diff-2a6ddd8f53c1561481e20a62b9efa7b637e532c42804e6cd3d41d597d8ae0ed3R153)), `--load-cookies` parameter is mandatory for the feature to work and at the same time `--login` must be specified as well.

- Run with all these parameters

```
instaloader \
--no-pictures \
--no-videos \
--no-captions \
--no-compress-json \
--login *** \
--load-cookies Chrome \
--cookiefile Cookies \
-- -Cz8TXVKIClF
```

Got 

```
Session file does not exist yet - Logging in.
browser_cookie3 library is needed to load cookies from browsers
```

Installed `browser_cookie3` but then started to get more issues about X11 dependencies, was trying to install them as well but end up that it still doesn't work. 
The latest error was related to `DBUS_SESSION_BUS_ADDRESS` which tied to X11.

I also tried to run it with fewer parameters but this didn't work as well

- No `--login` and `--load-cookies`

```
instaloader \
--no-pictures \
--no-videos \
--no-captions \
--no-compress-json \
--cookiefile Cookies \
-- -Cz8TXVKIClF
```

Got `JSON Query to graphql/query: HTTP error code 401.`

- No `--load-cookies`

```
instaloader \
--no-pictures \
--no-videos \
--no-captions \
--no-compress-json \
--login *** \
--cookiefile Cookies \
-- -Cz8TXVKIClF
```

Got

```
Session file does not exist yet - Logging in.
Enter Instagram password for ***:
```

**Comment by JunedKhan101** [comment]
> As far as I can understand the implementation ([instaloader/main.py](https://github.com/instaloader/instaloader/pull/2040/files#diff-2a6ddd8f53c1561481e20a62b9efa7b637e532c42804e6cd3d41d597d8ae0ed3R153)), --load-cookies parameter is mandatory for the feature to work and at the same time --login must be specified as well.

`--load-cookies` parameter is optional not required if you use instaloader with login and without `--load-cookies` it obviously asks for username and password if your are logging in for the first time.
It doesn't make sense to use both `--login` and `--load-cookies` options, if you're loading cookies you don't need username and password (@ekalin correct me if I'm wrong)

Also, try to use lowercase when loading browser names for example 'chrome' instead of 'Chrome'

**Comment by thebix** [comment]
> It doesn't make sense to use both --login and --load-cookies options, if you're loading cookies you don't need username and password (@ekalin correct me if I'm wrong)

yes, I thought the user name will be loaded from the cookies. But currently the whole cookie loading logic lays inside the branch `if username is not None:`

```python
    if username is not None:
        # ... unrelated code here ...
        if browser is not None:
            if bc3_library:
                import_session(browser.lower(), instaloader, cookiefile)
            else:
                raise SystemExit("browser_cookie3 library is needed to load cookies from browsers")
```

[[link to the code section](https://github.com/instaloader/instaloader/blob/08bf0fef29f3964b77814fa4288058d26a675e8f/instaloader/__main__.py#L144-L153)]

I did try with lowercase before, but the result was the same

```shell
instaloader \
--login *** \
--load-cookies chrome \
--cookiefile Cookies \
-- -Cz8TXVKIClF

# Output
Session file does not exist yet - Logging in.
browser_cookie3 library is needed to load cookies from browsers

# install browser_cookie3
pip3 install browser_cookie3

# Run instaloader again, getting output - see in the expandable section below
```

<details>
<summary>Output when browser_cookie3 is installed</summary>

```shell
Session file does not exist yet - Logging in.
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/instaloader/__main__.py", line 530, in main
    _main(loader,
  File "/usr/local/lib/python3.10/dist-packages/instaloader/__main__.py", line 155, in _main
    import_session(browser.lower(), instaloader, cookiefile)
  File "/usr/local/lib/python3.10/dist-packages/instaloader/__main__.py", line 107, in import_session
    cookie = get_cookies_from_instagram('instagram', browser, cookiefile)
  File "/usr/local/lib/python3.10/dist-packages/instaloader/__main__.py", line 90, in get_cookies_from_instagram
    browser_cookies = list(supported_browsers[browser](cookie_file=cookie_file))
  File "/usr/local/lib/python3.10/dist-packages/browser_cookie3/__init__.py", line 1160, in chrome
    return Chrome(cookie_file, domain_name, key_file).load()
  File "/usr/local/lib/python3.10/dist-packages/browser_cookie3/__init__.py", line 626, in __init__
    super().__init__(browser='Chrome', cookie_file=cookie_file,
  File "/usr/local/lib/python3.10/dist-packages/browser_cookie3/__init__.py", line 416, in __init__
    self.__add_key_and_cookie_file(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/browser_cookie3/__init__.py", line 431, in __add_key_and_cookie_file
    USE_DBUS_LINUX).get_password(os_crypt_name)
  File "/usr/local/lib/python3.10/dist-packages/browser_cookie3/__init__.py", line 232, in get_password
    return self.__get_secretstorage_password(os_crypt_name)
  File "/usr/local/lib/python3.10/dist-packages/browser_cookie3/__init__.py", line 247, in __get_secretstorage_password
    return self.__methods_map.get('secretstorage')(schema, os_crypt_name)
  File "/usr/local/lib/python3.10/dist-packages/browser_cookie3/__init__.py", line 303, in __get_secretstorage_item_jeepney
    with _JeepneyConnection(*args) as connection:
  File "/usr/local/lib/python3.10/dist-packages/browser_cookie3/__init__.py", line 195, in __enter__
    self.__connection = open_dbus_connection()
  File "/usr/local/lib/python3.10/dist-packages/jeepney/io/blocking.py", line 341, in open_dbus_connection
    bus_addr = get_bus(bus)
  File "/usr/local/lib/python3.10/dist-packages/jeepney/bus.py", line 53, in get_bus
    return find_session_bus()
  File "/usr/local/lib/python3.10/dist-packages/jeepney/bus.py", line 42, in find_session_bus
    addr = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'DBUS_SESSION_BUS_ADDRESS'
```

</details>

Just to ensure it doesn't work without login information

```shell
instaloader \
--load-cookies chrome \
--cookiefile Cookies \
-- -Cz8TXVKIClF

# Output
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
-Cz8TXVKIClF: JSON Query to graphql/query: HTTP error code 401.

Errors or warnings occurred:
-Cz8TXVKIClF: JSON Query to graphql/query: HTTP error code 401
```

**Comment by JunedKhan101** [comment]
> yes, I thought the user name will be loaded from the cookies. But currently the whole cookie loading logic lays inside the branch if username is not None:

Ah I remember now, you need to specify the username with `--login` in order to tell instaloader which account you're gonna pull the cookies from.

**Comment by thebix** [comment]
> you need to specify the username with --login in order to tell instaloader which account you're gonna pull the cookies from.

Yes, which is okay.
But relying on external `browser_cookie3` library to read the cookie file makes the whole feature tied to X Server.  When just a few plain text `key=value` pairs are needed to proceed with the session creation.

> I think it's better to check if anyone has been facing these issues with browser_cookie3 library when used inside a docker container.

Good point. I can prepare a guide on how to run it and post it here, maybe someone from the thread can prove the issue exists.

**Comment by ekalin** [comment]
> But relying on external `browser_cookie3` library to read the cookie file makes the whole feature tied to X Server. When just a few plain text `key=value` pairs are needed to proceed with the session creation.

Why do you say that? The browser_cookie3 library depends on pycryptodomex and jeepney, but these two libraries are each self-contained and definitely do not pull any X libraries (let alone an X server).

**Comment by thebix** [comment]
Could be that I misused the "X Server" here.

I meant that the usage of browser_cookie3 makes it tied to the desktop environment. 

I made this assumption based on the output I've posted in [this](https://github.com/instaloader/instaloader/issues/1801#issuecomment-1826737714) message in section "Output when browser_cookie3 is installed".
Here is a part of this output

```shell
File "/usr/local/lib/python3.10/dist-packages/jeepney/io/blocking.py", line 341, in open_dbus_connection
    bus_addr = get_bus(bus)
  File "/usr/local/lib/python3.10/dist-packages/jeepney/bus.py", line 53, in get_bus
    return find_session_bus()
  File "/usr/local/lib/python3.10/dist-packages/jeepney/bus.py", line 42, in find_session_bus
    addr = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'DBUS_SESSION_BUS_ADDRESS'
```

So it seems to rely to D-Bus (Desktop Bus). Which, from my understanding, requires the desktop environment.

**Comment by ekalin** [comment]
I think it might be possible to start a DBus server without a full desktop environment, but it probably wouldn't help because the services/values/whatever it's called would not be available.

This seems to be a Chrome thing, I guess the cookies are encrypted or something. With Firefox, I have been able to use the library to import cookies from Firefox in a bare-bones docker image that definitely did not have DBus (it didn't even have Firefox - I just copied the files from another computer).

**Comment by thebix** [comment]
> This seems to be a Chrome thing, I guess the cookies are encrypted or something. With Firefox, I have been able to use the library to import cookies from Firefox

Thanks a lot for your help 🙌 I was able to successfully run the instaloader in the Docker container using Firefox cookies.
Then my initial assumption that  *browser_cookie3 makes it tied to the desktop environment* is not valid.

You're right, it seems it's just a Chrome thing. It's probably worth documenting to avoid questions/open issues in the future.

**Comment by JunedKhan101** [comment]
> You're right, it seems it's just a Chrome thing. It's probably worth documenting to avoid questions/open issues in the future.

This was changed while I was working on this feature chrome cookies are encrypted now, chrome won't allow you to direcly read cookies this has been an open issue in browser_cookie3 library as well.
link to the issue: https://github.com/borisbabic/browser_cookie3/issues/180

More similar issues can be found with Brave, Edge and other browsers who run Chromium

**Comment by aandergr** [comment]
> > yes, I thought the user name will be loaded from the cookies. But currently the whole cookie loading logic lays inside the branch if username is not None:
> 
> Ah I remember now, you need to specify the username with `--login` in order to tell instaloader which account you're gonna pull the cookies from.

Oh sorry for that, I totally missed that during the PR review process. There should be no need to specify `--login` for importing the browser cookies. The username for the imported cookie can be retrieved with `instaloader.test_login()` just like the old [cookie import script](https://instaloader.github.io/troubleshooting.html#login-error) does. The way the if branches are currently nested, it also behaves badly when passing a username and a browser cookie that do not match. 

`--load-cookies` should not require `--login`. If both options are given, I think the best behavior would be to exit with a message that these two options cannot be used together.

@JunedKhan101 just in case you still have the time and inclination, would it be okay for you to set a PR to fix it? Otherwise I'll just do it myself.

**Comment by JunedKhan101** [comment]
@aandergr I'll do it.

**Comment by JunedKhan101** [comment]
@aandergr Please review and let me know if it requires any changes.

**Comment by thariq-nugrohotomo** [comment]
> I've also made changes that prevents the user from using both `--login` and `--load-cookies`

Yet in the official documentation https://instaloader.github.io/cli-options.html#cmdoption-load-cookies I see the following:

> After loading the cookies run the [--login](https://instaloader.github.io/cli-options.html#cmdoption-login) option as it is required to download high quality media and to make full use of Instaloader’s features.

Now I'm confused, should we use `--login` alongside `--load-cookies` or not?

Thanks again for making this feature available.

**Comment by JunedKhan101** [comment]
@thariq-nugrohotomo it says **"After loading the cookies"** meaning once you have loaded the cookies using `--load-cookies` or -`--cookiefile` its better to run `--login` option 😄 

I believe the `--login` options logs you in into Instaloader context which allows you make use of all the features of instaloader.

The way that I explained it is pretty abstract so here an example:

`instaloder --load-cookies=firefox`

then run

`instaloader --login=USERNAME`

Please note: username here needs to be the same Instagram username in which you're logged in, in your browser in this case it's firefox.

The `--login` option just grabs the saved session file meaning it won't ask for username and password (contrary to running it without loading cookies before) because of course there is no need to as the cookies are already loaded.

**Comment by thariq-nugrohotomo** [comment]
> @thariq-nugrohotomo it says **"After loading the cookies"** meaning once you have loaded the cookies using `--load-cookies` or -`--cookiefile` its better to run `--login` option 😄
> 
> I believe the `--login` options logs you in into Instaloader context which allows you make use of all the features of instaloader.
> 
> The way that I explained it is pretty abstract so here an example:
> 
> `instaloder --load-cookies=firefox`
> 
> then run
> 
> `instaloader --login=USERNAME`
> 
> Please note: username here needs to be the same Instagram username in which you're logged in, in your browser in this case it's firefox.
> 
> The `--login` option just grabs the saved session file meaning it won't ask for username and password (contrary to running it without loading cookies before) because of course there is no need to as the cookies are already loaded.

Thanks, your explanation is really helpful.

I usually run only a single command for both authenticating and downloading the content. It didn't occur to me that we can use a sequence of multiple commands = the first call will converting the browser cookie into a session file for the latter use, then the second call will use that session file for downloading the content.

Thanks again.
