### ISSUE TITLE
Fetching Post metadata failed

### ISSUE THREAD

**Issue by andre-santos1** [instaloader/instaloader#1803]
**Describe the bug**

When I run: instaloader --login XXXXXX --password XXXXXX -- -SHORTCODE

I get: 

Errors or warnings occurred:

-SHORTCODE: Fetching Post metadata failed.

**To Reproduce**

instaloader --login XXXXXX --password XXXXXX -- -SHORTCODE

**Expected behavior**

Running that command I expect to download post picture and associated metadata.

**Error messages and tracebacks**

Errors or warnings occurred:

-SHORTCODE: Fetching Post metadata failed.

**Instaloader version**

4.9.5

**Additional context**

No additional context

**Comment by Thammus** [comment]
Did you replace "SHORTCODE" by the actual shortcode of the post you want to load?

**Comment by andre-santos1** [comment]
I tried today and it worked!!! \o/ Tks
