### ISSUE TITLE
401 Error on Basic Queries

### ISSUE THREAD

**Issue by thereareno** [instaloader/instaloader#1807]
Example Query:

.\instaloader --login <instagram id> --no-captions --no-metadata-json <instagram id>
<img width="599" alt="Screenshot 2022-11-11 at 00 05 36" src="https://user-images.githubusercontent.com/110756585/201271100-ae909031-c0dc-414d-a86b-10ae834428c8.png">

**Comment by EveryDirection** [comment]
Can confirm that I am getting this too.

**Comment by Showmaster3000** [comment]
You are required to add your username which you want to use for login
`.\instaloader --login myaccount --no-captions --no-metadata-json `

**Comment by EveryDirection** [comment]
> You are required to add your username which you want to use for login `.\instaloader --login myaccount --no-captions --no-metadata-json `

I am not OP, and I can confirm that this error occurs intermittently even with `--login` set.

**Comment by b5kaa** [comment]
I have the same issue even if I have my cookies saved an imported to instaloader.

Loaded session from C:\Users\11qq\AppData\Local\Instaloader\session-***.
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Fatal error: JSON Query to graphql/query: HTTP error code 401.

I started getting CSRF token missing or incorrect after a few days when I imported session file to instaloader when trying to login to any account on instagram. The accounts are fine. looks like a hardware ban or something.

**Comment by pinjiewu** [comment]
Same here, I loaded data with login user. It happened to me when I wanted to load the comments.

**Comment by SoulReav** [comment]
I am getting an error when loading any posts. When creating a new session, the error disappears, but returns after a while

**Comment by raleighlittles** [comment]
I'm having this same issue -- the original workaround suggested (using `--login`) doesn't work because the account I'm trying to download from is blocked, which normally wouldn't be an issue since it's a public profile.

**Comment by ghbenl** [comment]
I'm having the same error. Looks like it is the API calling rate limit...

**Comment by ciaomark** [comment]
Yeah same issue here.

**Comment by lonewanderer80** [comment]
Same issue. What is the cause of this? I installed Instaloader yesterday but after approximately 6000 posts it gave me this error. Same happened today after 5000 posts.

**Comment by yarodevuci** [comment]
it happens to me on the server, but not locally...
