### ISSUE TITLE
Instaloader failing after 12 posts (401 error)

### ISSUE THREAD

**Issue by Allen-Kwan** [instaloader/instaloader#1809]
I've been able to scrape public profiles until today without logging in, but now it is constantly failing after 12 posts.  I've tried different machines and VPNs as well, so I just wanted to check if anyone else may be encountering the same issue?

**Comment by pinjiewu** [comment]
Same here

**Comment by Showmaster3000** [comment]
description looks similar lik #1617. Please check that.

**Comment by Allen-Kwan** [comment]
> description looks similar lik #1617. Please check that.

Hrm, yeah, it turns out it might have been an IP-based soft-ban that lasted much longer than previously.   Cheers.
