### ISSUE TITLE
Unable to download stories only, other posts download fine

### ISSUE THREAD

**Issue by avagut** [instaloader/instaloader#1811]
**Describe the bug**
When I specifically want to download the **stories only** from a profile that I follow using the python module having logged in, literally nothing is downloaded and the script runs all the way to the end without error.

**To Reproduce**
```
import instaloader 

def download_stories_only(loader, target_username):
    target_profile = instaloader.Profile.from_username(loader.context,
                                                target_username)
    profiles = {target_profile}
    actions_dict = {'profile_pic': False,
                    'raise_errors': True,
                    'fast_update': False,
                    'highlights': False,
                    'stories': True,
                    'tagged': False,
                    'igtv': False,
                    'posts': False,
                    }
    loader.save_metadata = False
    loader.compress_json = False
    loader.post_metadata_txt_pattern = ''
    loader.storyitem_metadata_txt_pattern = ''
    loader.dirname_pattern = './{target}'
    loader.download_profiles(profiles, **actions_dict)

loader = instaloader.Instaloader()
loader.load_session_from_file(username=USER, filename=SESSION_FILENAME)
download_stories_only(loader, target_username)

```
**Expected behavior**
Several videos and photos to be downloaded to the targetname directory, having confirmed that those videos are visible from the app

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.
No errors, traceback messages generated

**Instaloader version**
`instaloader --version` output.
4.9.5

**Additional context**
None

**Comment by aandergr** [comment]
Why have you closed this issue?
