### ISSUE TITLE
Invalid username

### ISSUE THREAD

**Issue by blg002** [instaloader/instaloader#1813]
**Describe the bug**
```
$  instaloader meta/+args.txt -l blg002
Loaded session from /Users/blg002/.config/instaloader/session-blg002.
Logged in as blg002.
meta/+args.txt: Invalid username meta/+args.txt
Saved session to /Users/blg002/.config/instaloader/session-blg002.

Errors or warnings occurred:
meta/+args.txt: Invalid username meta/+args.txt
```

**Instaloader version**
4.9.5

**Comment by avagut** [comment]
@blg002 it appears you have passed a parameter in the wrong place, what were you looking to get with the meta/+args.txt?

**Comment by blg002** [comment]
> @blg002 it appears you have passed a parameter in the wrong place, what were you looking to get with the meta/+args.txt?

```
--latest-stamps=/Users/blg002/Downloads/instaloader/meta/latest-stamps.txt
--no-captions
--no-videos
--no-video-thumbnails
--no-metadata-json
--no-compress-json
nasa
espn
...continuing list of instagram handles...
```

**Comment by avagut** [comment]
Start with the command line examples provided in the documentation, you are not setting up correctly

**Comment by blg002** [comment]
I did start there. Then slowly migrated to the args.txt file example from the docs. That all worked until the other day. I received the following type of errors

```
HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=USERNAME to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/

HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=USERNAME to https://www.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
USERNAME: Redirected to login page. Use --login.
```
So i followed the examples for `--login` from the docs and am now at this point.

I'll try again from the command line, like you suggest, but would be surprised if thats the issue… but crazier things have happened.

**Comment by blg002** [comment]
Figured it out. the `+` character has to begin the path to the "args.txt" file, i.e. ` instaloader +meta/args.txt`. I forgot I had moved that file into its own folder.
