### ISSUE TITLE
Instagram ban

### ISSUE THREAD

**Issue by Yvan95** [instaloader/instaloader#1817]
it is now 1 month that I can no longer create an account to make requests with Instaloader.
Every time I try to create an Instagram account either from web or mobile (even with cloned application) with a temporary email at the final step it gives me the error 'Oops, an error occurred.'
I think my ip's and/or devices have been blocked by Instagram. 
Can anyone give me any advice? Thank you very much

Translated with www.DeepL.com/Translator (free version)

**Comment by sQur1** [comment]
I would be really surprised if your device was blocked. It is most likely your IP. Don't you have a VPN? Just change location.

**Comment by j-quintas** [comment]
Usually it's the account that gets "limited", it logs in but it does not display any feed and if you click on any story (besides the 1st one) it will not load and give an "failed to load error".

Been getting this constantly with my main account, reduced the archiving to only 4 accounts query'ing every 12h, still gets limited, right now it's limited, no feed but the stories work.

Logs show 429 throwing up, sometimes 500, even when downloading 5 files every 12h. (in this case)

I know this may be unrelated, but instagram's probably been liimting API calls for any account, as i also use Instaloader on mobile (though not at the same time and not THAT usually)

Anyway, sorry for butting in, i could open an issue but it would be what i just said above and i already am downloading the cookie from firefox to use with the query (on linux as MAIN) so it doesn't show me any "new login" e-mails, but interestingly more issues this way i guess.

**Comment by nagyjanosgeza** [comment]
Hello, I did exactly the same thing.
I can't register either, it always asks me for additional email verification, then a phone number and then a photo verification

**Comment by Yvan95** [comment]
I assumed the device ban because even trying to register even via vpn I get this after email verification.

We suspended your account on the following date: <today>

**Comment by tetrahydra** [comment]
> Usually it's the account that gets "limited", it logs in but it does not display any feed and if you click on any story (besides the 1st one) it will not load and give an "failed to load error", i never got any IP block from instagram, although YMMV.
> 
> Been getting this constantly with my main account, reduced the archiving to only 4 accounts query'ing every 12h, still gets limited, right now it's limited, no feed but the stories work.
> 
> Logs show 429 throwing up, sometimes 500, even when downloading 5 files every 12h. (in this case)
> 
> I know this may be unrelated, but instagram's probably been liimting API calls for any account, as i also use Instander on mobile (though not at the same time and not THAT usually)
> 
> Anyway, sorry for butting in, i could open an issue but it would be what i just said above and i already am downloading the cookie from firefox to use with the query (on linux as MAIN) so it doesn't show me any "new login" e-mails, but interestingly more issues this way i guess.


I am having this issue. Where can i find information on extracting cookies from firefox to bypass manual login?

**Comment by j-quintas** [comment]
> > Usually it's the account that gets "limited", it logs in but it does not display any feed and if you click on any story (besides the 1st one) it will not load and give an "failed to load error", i never got any IP block from instagram, although YMMV.
> > Been getting this constantly with my main account, reduced the archiving to only 4 accounts query'ing every 12h, still gets limited, right now it's limited, no feed but the stories work.
> > Logs show 429 throwing up, sometimes 500, even when downloading 5 files every 12h. (in this case)
> > I know this may be unrelated, but instagram's probably been liimting API calls for any account, as i also use Instander on mobile (though not at the same time and not THAT usually)
> > Anyway, sorry for butting in, i could open an issue but it would be what i just said above and i already am downloading the cookie from firefox to use with the query (on linux as MAIN) so it doesn't show me any "new login" e-mails, but interestingly more issues this way i guess.
> 
> I am having this issue. Where can i find information on extracting cookies from firefox to bypass manual login?

https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py

usage is simply "python3 615_import_firefox_session.py"

You need to login to instagram before.

Can't remember if i did any configuration for the location of the cookies it generates, but i think i did change some path, i'm using linux btw.

**Comment by Bazooka69** [comment]
https://www.instagram.com/vanessapereiracamara/
https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py

**Comment by reddere** [comment]
> > > Usually it's the account that gets "limited", it logs in but it does not display any feed and if you click on any story (besides the 1st one) it will not load and give an "failed to load error", i never got any IP block from instagram, although YMMV.
> > > Been getting this constantly with my main account, reduced the archiving to only 4 accounts query'ing every 12h, still gets limited, right now it's limited, no feed but the stories work.
> > > Logs show 429 throwing up, sometimes 500, even when downloading 5 files every 12h. (in this case)
> > > I know this may be unrelated, but instagram's probably been liimting API calls for any account, as i also use Instander on mobile (though not at the same time and not THAT usually)
> > > Anyway, sorry for butting in, i could open an issue but it would be what i just said above and i already am downloading the cookie from firefox to use with the query (on linux as MAIN) so it doesn't show me any "new login" e-mails, but interestingly more issues this way i guess.
> > 
> > 
> > I am having this issue. Where can i find information on extracting cookies from firefox to bypass manual login?
> 
> https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py
> 
> usage is simply "python3 615_import_firefox_session.py"
> 
> You need to login to instagram before.
> 
> Can't remember if i did any configuration for the location of the cookies it generates, but i think i did change some path, i'm using linux btw.

I am creating a similar version of instagram acc creator but just with requests, to make it easier to use. The problem is that after phone verification, even if the phone number is verified, when making a request to the create_validated endpoint of instagram API, it throws a status code 500 with showing the message "Oops, an error occured". 

So all you are doing is logging in before creating the account itself to avoid the photo verification? and after login you store the cookies and session to create account? it sounds weird but thats what I understood. Thanks for the next replies!

**Comment by dorey973** [comment]
Same, log on my phone, log off on firefox, it's like I can only use ig on one device.

**Comment by rafaelsupport** [comment]
the same thing happened to me @Yvan95 
I realized that it happened because when using the instaloader with another IP using the cookies of my main browser (mozilla)
for while I solved the problem like this: I opened my account in chrome, exported the cookies to the instaloader and continued using it on the computer only with firefox, so as not to cause more conflicts
that way my account was never disconnected again

**Comment by reddere** [comment]
> the same thing happened to me @Yvan95 I realized that it happened because when using the instaloader with another IP using the cookies of my main browser (mozilla) for while I solved the problem like this: I opened my account in chrome, exported the cookies to the instaloader and continued using it on the computer only with firefox, so as not to cause more conflicts that way my account was never disconnected again

what do you mean by "exported the cookies to the instaloader", did you save them as a file in your project directory and them imported them with instaloader or...?
