### ISSUE TITLE
Is there a Chrome script for getting the login session?

### ISSUE THREAD

**Issue by Jono1991** [instaloader/instaloader#1821]
I seem to be having the same issue as a lot of other people about the 2FA checks, but I don't have Mozilla Firefox, so I'm just wondering if there's something I can use for Chrome? I've seen other software instruct to check the network tab and get the session ID that way.

**Comment by Showmaster3000** [comment]
have a look at #1780 where @OMGhozlan proposed such a script.

**Comment by Jono1991** [comment]
> have a look at #1780 where @OMGhozlan proposed such a script.

Oh nice, thanks man.
