### ISSUE TITLE
get_followers() is not working

### ISSUE THREAD

**Issue by peetceenatoo** [instaloader/instaloader#1822]
It's been a while that I can't get my followers through instaload anymore, as this function seems to be returning an empy list of followers.

I had a script which would return all the accounts which started following me and all the accounts which unfollowed me since the last time I runned it. Now, I just don't get anything, and I think that it is cause of the get_followers() function.

There is no error message.

Instaloader 4.9.5

**Comment by aandergr** [comment]
get_followers() works for me.

**Comment by itsfaraaz** [comment]
This is also occurring for me.

**Comment by dr-pandit-69** [comment]
Same bug here get_followers() and get_followees() is not working for me too

Instaloader v4.9.5

**Comment by j8dla** [comment]
Same problem for me.

**Comment by zeinramadan** [comment]
I am having an issue while looping through all followers with get_followers() as follows:

```python
for follower in profile.get_followers():
    # do something
```

The code only iterates through 50 followers. Not sure why this is the case. Any ideas?

**Comment by angelotc** [comment]
My issue stems from using username/pw auth, not cookies. @j8dla  opposite from
you.

**Comment by Physsikal** [comment]
Use this function instead:

```python
import instaloader

# Create an instance of Instaloader
L = instaloader.Instaloader()

def get_followers(username):
    # Load the profile of the given username
    profile = instaloader.Profile.from_username(L.context, username)

    # Retrieve the followers and return as a list
    followers = []
    for follower in profile.get_followers():
        followers.append(follower.username)
    
    # Returns the followers as a list.
    return followers
```

**Comment by peetceenatoo** [comment]
@Physsikal what would be the difference? That's what I do already...

**Comment by peetceenatoo** [comment]
Update: now the command "instaloader -l aberratom" fails and triggers Instagram which will force me to change the password. This module is useless, it's been months and it just does not work.

**Comment by Physsikal** [comment]
> @Physsikal what would be the difference? That's what I do already...

Maybe a smart reason to share the code snippet next time instead of assuming that people know what you wrote.

**Comment by its-me-navee** [comment]
Is there any way to scrape a insta account which has more than 10k followers?
