### ISSUE TITLE
Command Line Option: Skip Private Profile Warning/Error

### ISSUE THREAD

**Issue by someC0d3r** [instaloader/instaloader#1831]
Hello :)

Is there a command line parameter which allows to skip private profiles?

For example if I try to run Instaloader.exe with following parameters:
```
--no-compress-json --no-metadata-json --no-video-thumbnails --no-captions --stories --highlights --tagged --igtv --fast-update -profile PROFILE1 PROFILE2 PROFILE3 -l MYLOGIN
```

And let's say PROFILE1 is private then it ends the whole execution and throws an exception (/warning/error) with following message:
```
PROFILE1: Private but not followed.

Errors or warnings occurred:
PROFILE1: Private but not followed.
```

So is there an option to say: "If download possible, download - if not, go on with the next profile"?

Greetings! :)

**Comment by aandergr** [comment]
> So is there an option to say: "If download possible, download - if not, go on with the next profile"?

that is what Instaloader does.
