### ISSUE TITLE
Set filename

### ISSUE THREAD

**Issue by milliorn** [instaloader/instaloader#1832]
Hello, I am new to this repo, love it.

I am unsure how to set the filename of each image downloaded. Is that an option? What I want to be exact is the filename of the image, just as if you did `Save as` in the browser and downloaded the file.

Example. If I went to [instagram page](https://www.instagram.com/instagram/) and download [this picture](https://www.instagram.com/p/ClOwgNOp9LT/) the filename for that picture would be `316162014_174356501933524_8936866640852037659_n`. I assume this is how Instagram makes this unique? Anyhow, I checked the json when download from this profile, and the docs you provide, and I am still unsure how I can grab that?

Is there a way? Did I miss the documentation? Thank you for your help. Apologize for any inconvenience.

**Comment by EveryDirection** [comment]
It's in the documentation at https://instaloader.github.io/basic-usage.html#filename-specification

The options you are looking for are `--dirname-pattern`, `--filename-pattern`, and `--title-pattern`.

**Comment by milliorn** [comment]
@EveryDirection thank you very much!
