### ISSUE TITLE
Instaloader Skips Over Many Posts in a Profile That Otherwise Downloads Fine

### ISSUE THREAD

**Issue by EveryDirection** [instaloader/instaloader#1833]
Instaloader is skipping over many posts in a profile that otherwise downloads fine.

For example, do a profile download as follows:

`instaloader whitney_thornqvist`

This is a public profile which currently has 276 posts, of which 50 are subscription posts, leaving 226 public posts.

The console output will be something like... (wherein "*filenames*" is replaced with the actual filenames):

[  1/276] *filenames*
[  2/276] *filenames*
[  3/276] *filenames*
[...]
[ 85/276] *filenames*

That is, the profile download stops "early" at 85/276 instead of continuing to 276/276. Now, because of the subscription posts, we should expect downloading to stop at around 226 posts, but instead, downloading is stopping way earlier at 85 posts.

I went through and compared the downloaded files against the posts on the actual profile, and downloaded post 85 actually is post 276 on the profile. So Instaloader is not actually stopping "early"; instead, what is happening is that Instaloder is correctly reaching the end of the profile, but it is skipping over many of the posts between the beginning and end of the profile. For example, all the posts between the dates 2021-02-18 and 2022-11-29 are getting skipped for no apparent reason.

I have verified that:

* this is not being caused by the profile having subscription/private posts, as I accounted for those posts in my counting of posts above
* this is not being caused by a filter set with the `--post-filter` option
* this is not being caused by reels (most of the missing posts are not reels; they are just regular posts, like many successfully-downloaded posts, but for some reason, Instaloader is not "seeing" those posts)

**Comment by EveryDirection** [comment]
Update: A week later, I tried downloading again with the exact same version of Instaloader and the exact same settings, and now all the posts are being correctly downloaded.

So the issue appears to have been temporary, though still worth noting in case it happens again in the future.

**Comment by aandergr** [comment]
Alright, thanks for the update. We can close the issue then.
