### ISSUE TITLE
Get mutual followers

### ISSUE THREAD

**Issue by Tower1999** [instaloader/instaloader#1834]
Hi!
I searched but I didn't understand how to get the number of mutual followers from the Profile object with the python module.
With mutual followers I mean the writing "Followed by x, y, z and other 15 people" when you visit a profile from the app.
Can you help me? Thank you!

**Comment by aandergr** [comment]
Instaloader's Profile class does not directly expose that information, however the number of mutual followers is saved in the metadata JSON and can be accessed as `.node.edge_mutual_followed_by.count`.

```
xzcat <profile>/<profile>_<id>.json.xz | jq .node.edge_mutual_followed_by.count
```
