### ISSUE TITLE
Story fetcher not working properly.

### ISSUE THREAD

**Issue by yuribranco** [instaloader/instaloader#1835]
I was using instaloader to daily download the stories of 20 accounts I want. 
A few days ago an error is ocurring that after a few stories fetched, it blocks the account (I have to change the password). Is anyone having the same issue?

Here's an example of what happens:

![image](https://user-images.githubusercontent.com/16180805/208453669-875b0142-1e59-4ba6-bab3-c2138cbbdf2e.png)

**Comment by subvert221** [comment]
Well, can confirm. Couldn't download stories today, stuck in the loop of bad request => restore account by changing password => bad request.

**Comment by wireman21** [comment]
its been like this for a while for me, can't download stories, my account gets blocked and i have to reset password
