### ISSUE TITLE
Error 401, Server blocking and others

### ISSUE THREAD

**Issue by BlabberBlabbing** [instaloader/instaloader#1836]
Hello, I'm trying the SW out (Windows standalone executable) but I've had a few issues.

1) .\instaloader PROFILE. It seems like it proceeds with a first 12 attempts, then if these have already been DL, it goes by 50 up to those still to DL. After a couple of days where it seemed to work fine (except after some massive # of DL - like after DLing 1000 posts, IG blocked it), today it just downloads the first 12 posts and then it's like IG rejects the connections (error 401 as per the attachment). Retrying doesn't work. 

2) Using the --login=ID option with my personal account to DL like 60 private posts, IG blocked the DL halfway through and required a change of password. So I guess it's not safe at all unless you want to risk getting blocked/banned.

Is it a known problem? Is IG targeting the too fast connections? Is there a plan for an option to create a (random) delay between DLs for the standalone executable?

Thanks.

![immagine](https://user-images.githubusercontent.com/121065151/208541023-4c603c7e-981f-437b-aafe-5a4586d2752f.png)

**Comment by lonewanderer80** [comment]
I haven't download anything for 2 days to see whether or not it will reset itself but it didn't and still giving me this error after 12th post and hashtags.

**Comment by BlabberBlabbing** [comment]
> I haven't downloaded anything for 2 days to see whether or not it will reset itself but it didn't and still giving me this error after 12th post and hashtags.

Guess IG wins this... it's time for 4.9.6 :D

**Comment by ciaomark** [comment]
Happens almost every time for me too. Waiting a few days doesn't seem to solve the problem either.

**Comment by skeith** [comment]
I used to had similar error, but after adding a proper user agent, it continues to work

**Comment by skeith** [comment]
> > I used to have similar error, but after adding a proper user agent, it continues to work
> 
> And could you share what that proper UA "value" is ?
> 
> Indeed seeing other people still asking questions I guess not everyone is modifying the SC to bypass IG's firewalls and there's something easier to do...

Proper UA value would be Instagram App UA

**Comment by lonewanderer80** [comment]
> > > I used to have similar error, but after adding a proper user agent, it continues to work
> > 
> > 
> > And could you share what that proper UA "value" is ?
> > Indeed seeing other people still asking questions I guess not everyone is modifying the SC to bypass IG's firewalls and there's something easier to do...
> 
> Proper UA value would be Instagram App UA

Excuse me I'm not a programmer but how do you change the ua? Can you give me an example?

**Comment by BlabberBlabbing** [comment]
> 

Yep, with Instagram UAs it works again, thanks! But I guess it's just a matter of time before IG blocks all these fast connections indipendent of the UA...

**Comment by BlabberBlabbing** [comment]
> > > > I used to have similar error, but after adding a proper user agent, it continues to work
> > > 
> > > 
> > > And could you share what that proper UA "value" is ?
> > > Indeed seeing other people still asking questions I guess not everyone is modifying the SC to bypass IG's firewalls and there's something easier to do...
> > 
> > 
> > Proper UA value would be Instagram App UA
> 
> Excuse me I'm not a programmer but how do you change the ua? Can you give me an example?

It's in the documentation: use the --user-agent parameter. Possible values can be found online under IG App UAs.

**Comment by skeith** [comment]
> Yep, with Instagram UAs it works again, thanks! But I guess it's just a matter of time before IG blocks all these fast connections indipendent of the UA...

You will still hit a wall even with IG's UA, but at least it's not 401. Just add abort flag on certain errors

**Comment by lonewanderer80** [comment]
> > > > > I used to have similar error, but after adding a proper user agent, it continues to work
> > > > 
> > > > 
> > > > And could you share what that proper UA "value" is ?
> > > > Indeed seeing other people still asking questions I guess not everyone is modifying the SC to bypass IG's firewalls and there's something easier to do...
> > > 
> > > 
> > > Proper UA value would be Instagram App UA
> > 
> > 
> > Excuse me I'm not a programmer but how do you change the ua? Can you give me an example?
> 
> It's in the documentation: use the --user-agent parameter. Possible values can be found online under IG App UAs.

i did  the user agent thing couple of days ago. it's much much better but still time to time it gives me the error 401. I delete the session or use vpn for a while to fix it. I don't know how it works but it works

**Comment by DaniSanchez01** [comment]
> > Yep, with Instagram UAs it works again, thanks! But I guess it's just a matter of time before IG blocks all these fast connections indipendent of the UA...
> 
> You will still hit a wall even with IG's UA, but at least it's not 401. Just add abort flag on certain errors

Hello! I am facing the same problem, I am trying to download photos and their comments from a list of profiles and every time I download 12 I get a 401 error. I have tried changing the user agent to some of the ones I found on this page - > https://user-agents.net/applications/instagram-app , but it doesn't change anything. Do you know if I have to use some specific IG user agents and if there are other solutions to avoid this problem? Thank you for your time

**Comment by skeith** [comment]
> > > Yep, with Instagram UAs it works again, thanks! But I guess it's just a matter of time before IG blocks all these fast connections indipendent of the UA...
> > 
> > 
> > You will still hit a wall even with IG's UA, but at least it's not 401. Just add abort flag on certain errors
> 
> Hello! I am facing the same problem, I am trying to download photos and their comments from a list of profiles and every time I download 12 I get a 401 error. I have tried changing the user agent to some of the ones I found on this page - > https://user-agents.net/applications/instagram-app , but it doesn't change anything. Do you know if I have to use some specific IG user agents and if there are other solutions to avoid this problem? Thank you for your time

Make sure you are not logged in on multiple device

**Comment by BlabberBlabbing** [comment]
> 

Also what I do:

1) Change UA from time to time and use it for public profiles only
2) Give up for the day at the first 401 (OFC with the abort parameter as well on 401)
3) Use it during high traffic time for IG servers (in Europe it's 6PM to 24PM): it may be contrary to logic but it seems like I get blocked less often... they may implement less strict policies to avoid stressing the servers? I don't know...

Still, after a while (Can be the 1st account after 12 pics, can be 10k items downloaded and depending on the day) I get blocked. Not really ideal and hopefully a new version that solves these problems will be released soon...

**Comment by skeith** [comment]
I actually hitting 403 lately, not 401. I might need to stop scraping for a while
