### ISSUE TITLE
pip3 install instaloader incorrect syntax error on python

### ISSUE THREAD

**Issue by g0osebumps** [instaloader/instaloader#1837]
>>> pip3 install instaloader
  File "<stdin>", line 1
    pip3 install instaloader
         ^^^^^^^
SyntaxError: invalid syntax

This is the error I get every time I try to install instaloader, anyone have any clue as to what I need to do to fix? I have the newest version of python and pip installed.

**Comment by rafaelsupport** [comment]
you started python and entered the command
but you just need to open terminal and type this command, instead of opening python first
