### ISSUE TITLE
JSON Query to graphql/query: HTTP error code 401 for profile.get_posts() and post.get_comments()

### ISSUE THREAD

**Issue by Shaonpiana** [instaloader/instaloader#1838]
**Describe the bug**
profile.get_posts() and post.get_comments() is not working properly!

**To Reproduce**
![image](https://user-images.githubusercontent.com/120463816/208726542-61416df3-e268-4951-ada9-fc636bebc0f0.png)
![image](https://user-images.githubusercontent.com/120463816/208727824-4b0ead20-f7d0-40a4-9899-2c6014d4443c.png)

**Expected behavior**
It supposed to scrape until query is done!

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

**Instaloader version**
`instaloader --version` output.

**Additional context**
profile.get_posts() is working few times. after 5-7 posts, it shows this error.

-->

**Comment by Gabriel-Aragao** [comment]
Same here, the account used gets a suspicious activity warning, and is needed to change the password, tried more than once with more than one account, same result.

**Comment by Gabriel-Aragao** [comment]
Tried windows and linux same result. after 5 posts it gets a "HTTP Error 400 (Bad Request) on GraphQL Query. Retrying with shorter page length.                               HTTP Error 400 (Bad Request) on GraphQL Query. Retrying with shorter page length."

and on phone a "suspicious activity detected" warning, demanding a password change

**Comment by Shaonpiana** [comment]
Don't know why it's happening. Once I solved this by switching Instagram accounts
