### ISSUE TITLE
Instaloader seems outdated and depreciated

### ISSUE THREAD

**Issue by mhyjacinto** [instaloader/instaloader#1840]
It's been a while since the last September 27 update, Instagram API is changing up things frequently (To prevent automation requests in their safety reasons) and other IG Scrapers out there are also updating their client programs very often to make their downloads working as possible.

_Download Interval Time could have been a feature like today to avoid Bad Requests, Instead of Timeouts after downloading a lot of photos and videos in a short period of time._

`--interval [Number in Seconds]`

**Comment by EnthusiastAnon** [comment]
Which other IG scraper do you recommend?

**Comment by mhyjacinto** [comment]
For now, **I can't recommend stuffs and no other Python Repos have a same features like Instaloader as a Top Tier**.

_Well, There's some Py Repos like InstaLooter by @althonos but their features is not my favorite. (They don't scrape Metadata on posts like Captions and Comments)_

_There's another like InstaTouch by @drawrowfly, But it's written in TypeScript and I don't use Node.js on my Ubuntu OS._

_You can try using JDownloader, It only downloads Photos or Videos by each posts and that's it. (No Metadata and Miscellaneous, Just a content.)_

_Others are in Firefox and Chrome Extensions that only downloads Pictures and Videos like Instagram-Downloader by @HOAIAN2, InstagramDownloader by @Huiibah and useful-script by @HoangTran0410._

Actually, I don't use Browser Extensions for Bulk Downloads and they break sites that isn't intended for since 2020.
_There was a Good Chrome Extension called Batch-Media-Saver-for-Instagram by @fattynoparents that only downloads Pictures and compressed in a Zip File, But it's been discontinued for about 4 Years ago and Chrome just yanked on updated Instagram API as the Extension can't handle the URL._

**Comment by MrJmpl3** [comment]
> For now, **I can't recommend stuffs and no other Python Repos have a same features like Instaloader as a Top Tier**.
> 
> _Well, There's some Py Repos like InstaLooter by @althonos but their features is not my favorite. (They don't scrape Metadata on posts like Captions and Comments)_
> 
> _There's another like InstaTouch by @drawrowfly, But it's written in TypeScript and I don't use Node.js on my Ubuntu OS._
> 
> _You can try using JDownloader, It only downloads Photos or Videos by each posts and that's it. (No Metadata and Miscellaneous, Just a content.)_
> 
> _Others are in Firefox and Chrome Extensions that only downloads Pictures and Videos like Instagram-Downloader by @HOAIAN2, InstagramDownloader by @Huiibah and useful-script by @HoangTran0410._
> 
> Actually, I don't use Browser Extensions for Bulk Downloads and they break sites that isn't intended for since 2020. _There was a Good Chrome Extension called Batch-Media-Saver-for-Instagram by @fattynoparents that only downloads Pictures and compressed in a Zip File, But it's been discontinued for about 4 Years ago and Chrome just yanked on updated Instagram API as the Extension can't handle the URL._

Are you tried gallery-dl?

**Comment by mhyjacinto** [comment]
> Are you tried gallery-dl?

No, It's very confusing that you need a text file to make things work.
_While Instaloader will saved a login file and can able to use it on the next session (Unfortunately, Instagram's API is the problem today and multiple downloads in an Instance will suspend your IG account for preventing some automated requests. Affecting the login file and will marked as Expired Login Credentials)_
