### ISSUE TITLE
How does --latest-stamps works?

### ISSUE THREAD

**Issue by Lucas559-noob** [instaloader/instaloader#1843]
Does it work like get recent posts from the last time I downloaded them?
For example: I run and download on 01/01/2023(dd/mm/yyyy) and run again on 15/01/2023, it will check for new stuff after 01/01/2023 right? 
and what about posts that were made private and made public that it did not download
for example on day 14 I run it and downloaded stuff, but the owner made a post public from day 12, will it download too on next run?

**Comment by ekalin** [comment]
As described in the documentation: https://instaloader.github.io/cli-options.html#cmdoption-latest-stamps, it stores the time the profile was last downloaded, and on the next run starts downloading (starting from the newest item) and stops once it reaches a post older than the time stored.

So for your first question, yes, it'll download the newer stuff and stop. But for the second question, no: it will download any post from before the previous run.

`--fast-update` wouldn't work in this case either, as it stops once it sees an already downloaded item. Your only possibility would be to run a full download each time: already downloaded items will be skipped, but requests have to be made to IG to get the complete list of posts, so unless it's a very small profile, you'll probably end up rate limited by IG.
