### ISSUE TITLE
Creation of a Stories folder

### ISSUE THREAD

**Issue by Lucas559-noob** [instaloader/instaloader#1846]
**Provide us a use case of the feature**
If I download a profile on full(pics, videos, stories, etc) mode, I will have a lot of mixed stuff from videos and stories, so it would be good to change it, having a folder for stories is way better, also a subfolder for each date, so is easier to find stuff from a day

**Describe the solution you'd like**
It would send stuff from stories to a different path, on a new folder with or without subfolders

**Describe alternatives you've considered**
I have 0 alternatives since this is the only way I could think to know what's a story and what's a video post

**If the feature request is accepted, would you be willing to submit a pull request?**
No

**Comment by aandergr** [comment]
Not desired; use Instaloader as a module if you need more flexibility regarding directory structure than what the CLI provides.
