### ISSUE TITLE
File name

### ISSUE THREAD

**Issue by razamokarram** [instaloader/instaloader#1849]
How can I name the file as the titel of th post on Instagram

**Comment by Lucas559-noob** [comment]
Well for that I think you would need to edit the python script

**Comment by Showmaster3000** [comment]
I don't really understand what you are trying to do, cause your question lacks on information.
maybe look at the manual describing things about naming files: https://instaloader.github.io/basic-usage.html#filename-specification

**Comment by EveryDirection** [comment]
> How can I name the file as the titel of th post on Instagram

`--filename-pattern={caption}`

**Comment by Showmaster3000** [comment]
> Use:
> `--filename-pattern={caption}`

If you try that, be aware of #262. Using caption as filename is generally a bad idea, cause of invalid characters for files and the length of the filename is limited. both problems will crash your task.

**Comment by razamokarram** [comment]
> > Use:
> > `--filename-pattern={caption}`
> 
> If you try that, be aware of #262. Using caption as filename is generally a bad idea, cause of invalid characters for files and the length of the filename is limited. both problems will crash your task.

Thanks for your suggestions
