### ISSUE TITLE
Fix highlights downloading: add token for highlight title for dirname/filename_pattern, and add option to download only highlights matching a title

### ISSUE THREAD

**Issue by EveryDirection** [instaloader/instaloader#1850]
Currently, for the parameters `--dirname-pattern` and `--filename-pattern`, there is no available token, such as a hypothetical `{highlight_title}`, for just the highlight title.

When downloading highlights with the `--highlights` parameter, there is thus no way to organize the downloaded files by which highlight they belonged to, and all the files just end up an undifferentiated mass in the same download directory, instead of being organized by highlight title as they are on the Instagram profile. And if we afterwards manually organize the downloaded files into different directories, without something like `--filename-pattern={highlight_title}\...`, on a download session later in the future, there is no way for Instaloader to check/know if a highlight file has already been downloaded on a previous session.

Such an available token would also be useful for downloading only highlights that match a specific title; in this example, we are matching for the title "_foobar_":

`--highlights-filter="highlight_title==foobar"`

Months ago, I posted about this issue, and it was suggested that the `{target}` token be used as a workaround, since with `--dirname-pattern={target}`, Instaloader will place each highlight into a different folder.  However, the `{target}` token does not actually work to solve this issue, since it gets replaced not with the highlight title by itself, but with the combination of profile name and highlight title. For example, if we are downloading with...:

`instaloader --dirname-pattern=somepath\{target} --highlights --no-posts dogsofinstagram`

...then the highlights are not downloaded to the directory pattern "somepath\highlight_title", but instead to the directory pattern "somepath\dogsofinstagram\highlight_title".

Moreover, this behavior for `{target}` is at odds with that described by the documentation at https://instaloader.github.io/cli-options.html, which says:

> --dirname-pattern DIRNAME_PATTERN

> {target} is replaced by the target you specified, i.e. either :feed, #hashtag or the profile name.

Per that documentation, `{target}` should refer to _just_ the target specified, not a combination of the target _with something else_. There should be a separate token for highlight title, for three reasons: first, to be in agreement with the documentation; second, to allow other directory patterns; and third, to use as a filter to download only highlights matching a specific title.

For example, if we are downloading with...:

`instaloader --dirname-pattern={target} --highlights --no-posts dogsofinstagram`

...then the specified target is "dogsofinstagram". So the documentation would suggest that the highlights would be downloaded to the directory pattern "dogsofinstagram", but instead, the highlights are downloaded to the directory pattern "dogsofinstagram/highlight_title".

Suppose we want to download do a directory that is not in that exact format, for example, to the directory pattern "foobar/highlight_title" or to the directory pattern "dogsofinstagram/Highlights/highlight_title". Currently, there is no way to do either of those examples, since `--dirname-pattern={target}` forces the directory pattern "dogsofinstagram/highlight_title".

`{highlight_title}` should be a separate token from `{target}`, so that we can, for example, download to "foobar/highlight_title" by setting `--dirname-pattern=foobar/{highlight_title}` or download to "dogsofinstagram/Highlights/highlight_title" by setting `--dirname-pattern={target}/Highlights/{highlight_title}`.

Finally, such an available token would also be useful for downloading only highlights that match a specific title; in this example, we are matching for the title "_foobar_":

`--highlights-filter="highlight_title==foobar"`

**Comment by Thammus** [comment]
The problem with introducing an additional token for the highlight title that would be supported by the dirname pattern is, that dirname patterns which uses the new token would break for non-highlight downloads e.g. regular posts. For example, if using a `--dirname-pattern={profile}/{highlight_title}` what value would it have for regular posts? Since the dirname pattern affects the dirname of all posts and is not specific for highlights, it would be difficult to properly introduce such a new token.

**Comment by EveryDirection** [comment]
> The problem with introducing an additional token for the highlight title that would be supported by the dirname pattern is, that dirname patterns which uses the new token would break for non-highlight downloads e.g. regular posts. For example, if using a `--dirname-pattern={profile}/{highlight_title}` what value would it have for regular posts? Since the dirname pattern affects the dirname of all posts and is not specific for highlights, it would be difficult to properly introduce such a new token.

We already have existing tokens that are not valid in certain situations: for instance, `{caption}`, which is meaningless when downloading stories or highlights. If the user is using "{caption}" when downloading stories, that's the fault of the user for not using that token as intended. Similarly, if the user is using "{highlight_title}" when not downloading highlights, that would be on the user for not using the token as intended.

For non-highlights, the token `{highlight_title}` would just have no value, that is, have the value of an empty string (""), so that example given of `--dirname-pattern={profile}/{highlight_title}` would, for non-highlights, after substitution, just become "profile/", which still works fine.

**Comment by EveryDirection** [comment]
> However, at least in the way the feature (or set of at best weakly related features) is presented here, we would not be able to accept it, as it is not logically consistent.

On the contrary, I'm trying to fix logical inconsistency: as mentioned in the original post, this behavior for the `{target}` token is inconsistent. The `{target}` token is usually substituted with the target, except when the --highlights option is set, when it instead is substituted with the combination of target and highlight title.

> Further, it is unclear to me - even after reading through your issue several times, by the way - what problem your proposed feature is trying to solve. This makes it difficult to meaningfully argue for or against a proposal, let alone decide.

Okay, the core problem: highlights cannot currently be downloaded to arbitrary directory names. Suppose I want to download highlights of the profile dogsofinstagram to the directory "C:\Foobar", with the highlights sorted to different subdirectories of that directory by highlight title. If you look at the dogsofinstagram profile right now, the three most recent highlight groups are "Giveback", "Great Pet Care", and "Holiday". So the desired behavior is that the "Giveback" highlights would be downloaded to "C:\Foobar\Giveback", the "Great Pet Care" highlights would be downloaded to "C:\Foobar\Great Pet Care", and the "Holiday" highlights would be downloaded to "C:\Foobar\Holiday".

The problem is that this is currently impossible for Instaloader to do.

Using

`--dirname-pattern=C:\Foobar`

does not work because then the downloaded highlights are not sorted to different subdirectories by title; instead, all the highlights get downloaded to "C:\Foobar".

The previously suggested workaround of using the `{target}` token does not work either. Using

`--dirname-pattern=C:\Foobar\{target}`

will not work because the highlights instead get downloaded to subdirectories of "C:\Foobar\dogsofinstagram", not to subdirectories of "C:\Foobar":

* "Giveback" highlights would be downloaded to "C:\Foobar\dogsofinstagram\Giveback" instead of "C:\Foobar\Giveback"
* "Giveback" highlights would be downloaded to "C:\Foobar\dogsofinstagram\Great Pet Care" instead of "C:\Foobar\Great Pet Care"
* "Giveback" highlights would be downloaded to "C:\Foobar\dogsofinstagram\Holiday" instead of "C:\Foobar\Holiday"

**Comment by aandergr** [comment]
We do not like the fallback of `{highlight_title}` resolving to an empty string if not a highlight is being downloaded.

This seems like a case where a custom script should be used rather than the Instaloader CLI. The custom script could be even as simple as an invocation of Instaloaders CLI followed by an `mv` command.

We are not convinced that this would be a meaningful addition to Instaloader.

**Comment by EveryDirection** [comment]
> We do not like the fallback of `{highlight_title}` resolving to an empty string if not a highlight is being downloaded.

`{caption}` resolves to an empty string for posts without captions, for stories, and for highlights, so there should be no problem with the same thing happening for `{highlight_title}`.

> This seems like a case where a custom script should be used rather than the Instaloader CLI. The custom script could be even as simple as an invocation of Instaloaders CLI followed by an `mv` command.

But that causes problems whenever the user wants to update the highlights later for new highlights added to the profile.

To continue on from the example previously used, if what the user wants is highlights in the directory

C:\Foobar

So the user uses

--dirname-pattern=C:\Foobar\{target}

on the profile `dogsofinstagram`, and then afterwards the user uses `mv` commands to move everything from those subdirectories of "C:\Foobar\dogsofinstagram" up a directory level to "C:\Foobar".

A week later, the user wants to update the downloaded highlights for NEW highlights since added to that profile. The user would then have to use `mv` commands to move everything from "C:\Foobar" BACK to "C:\Foobar\dogsofinstagram" before the update so that Instaloader only downloads NEW highlights without wasting a lot of requests re-downloading highlights that have already previously been downloaded.

This process of moving all the highlights back and forth from "C:\Foobar\dogsofinstagram" to "C:\Foobar" (after the previous Instaloader CLI invocation) and from "C:\Foobar" to "C:\Foobar\dogsofinstagram" (before the next Instaloader CLI invocation) would have to be repeated EVERY time the user is attempting to update highlights, a move which is not so trivial for profiles that have hundreds or thousands of highlights.

All this could be avoided and solved with just the addition of a `{highlight_title}` token.

**Comment by duoside** [comment]
@EveryDirection I understand your request and it is a very valid one. Since the devs are refusing to acknowledge the issue, I would suggest you write a small script yourself to automatically restructure your downloads path once Instaloader finishes its job. It's trivially easy. If you're on linux you can do something like:

```
mv ig_downloads/mrbeast/mrbeast/highlights ig_downloads/mrbeast/.
rm -rf ig_downloads/mrbeast/mrbeast
```
