### ISSUE TITLE
Downloading Instagram posts from Shortcode

### ISSUE THREAD

**Issue by MiguCosta** [instaloader/instaloader#1851]
Hey there, I'm using instaloader with 1Saas and trying to download Instagram posts & reels through a Shortcode. 
I'm a very newbie at coding so I can't troubleshoot properly. 

This is the code I'm using 

`import instaloader

L = instaloader.Instaloader()

post = Post.from_shortcode(L.context, 'CmUIFXNA6cN')

L.download_post(post, target='-CmUIFXNA6cN')`

I've gone through the documentation and can't make it work, What am I doing wrong? 

P.S. I'd like to download the profile name as well.

Thank you in advance!

**Comment by ypendi** [comment]
if you use "import instaloader", you have to change to this:
```python 
post = instaloader.Post.from_shortcode(L.context, 'CmUIFXNA6cN')
```
also the in the L.download_post line, the target parameter is the filepath (where you want to store your post)
if you want to store the post in a folder named like the username of the account you would have to do
```python 
L.download_post(post, target=post.owner_username)
```

**Comment by MiguCosta** [comment]
Thanks a lot for your quick answer @ypendi !! I'm building an automation with Make.com. The idea is to create an API call that downloads the file and then uploads to a Google Drive folder. How do I set that target? Or maybe don't set a target, and then perform a html request to upload the file to that foldeR?

**Comment by MiguCosta** [comment]
Ideally, creating a link that I can call html request to download the file.

**Comment by MiguCosta** [comment]
I've also tried this code with the same outcome: 

`import instaloader
import urllib.parse

L = instaloader.Instaloader()

post = instaloader.Post.from_shortcode(L.context, "CmUIFXNA6cN")

# Get the URL of the file
url = L.get_post_media(post)

# Encode the URL to make it safe to use in an HTTP request
encoded_url = urllib.parse.quote(url, safe=" ")

print(encoded_url)`
