### ISSUE TITLE
Is there a way to only get a specific amount of (the latest) posts?

### ISSUE THREAD

**Issue by ypendi** [instaloader/instaloader#1852]
I dont want to use

```python
profile = Profile.from_username(L.context, PROFILE)
post_list = profile.get_posts()
```
because this gets all posts, I only want to get a specific amount of posts, is there a way to do that, so far I haven't found one.

**Comment by Showmaster3000** [comment]
see example in manual: https://instaloader.github.io/codesnippets.html#only-one-post-per-user
and modify for your needs

**Comment by ypendi** [comment]
@Showmaster3000 yeah I was just thinking if there was a more effiecient method because you always have to get all posts first (which takes a lot of time and memory) and then you can select a few from those... but is there a method where you dont even have to get all posts, you can just get like 30..?
