### ISSUE TITLE
Resume downloads while using custom file/folder pattern, fast update and :stories 

### ISSUE THREAD

**Issue by netherlink117** [instaloader/instaloader#1854]
Hi veryone, I was looking for more info about this in the docs but I'm new on this and I didn't find how to do it.

Is it posible to resume downloads while using custom file/folder pattern and :stories options on the CLI?

In addition on that, I tried to re-run same command but instaloader tries to reach same profiles and tells "exists" on each story, instead of getting the stories of profiles that hasn't been downloaded yet. 

Is there an option I'm missing to avoid checking on profiles already downloaded today? Here are the options I pass to the CLI command:

```
instaloader \
--sessionfile=... \
--login=... \
--dirname-pattern=... \
--filename-pattern=... \
--abort-on=... \
--no-video-thumbnails \
--no-captions \
--no-metadata-json \
--no-profile-pic \
--fast-update \
--no-posts \
--stories \
:stories
```

I'm running instaloader 4.9.5

Any correction will be really welcome. 
Thanks in advance. And sorry is this kind of question has been alredy answered before.

**Comment by Showmaster3000** [comment]
You ask for resuming, but do not describe anything about canceling a running operation.
Reading the part about  [`--resume-prefix`](https://instaloader.github.io/cli-options.html#cmdoption-resume-prefix) in the manual, resuming of story downloads is not supported.

**Comment by netherlink117** [comment]
> You ask for resuming, but do not describe anything about canceling a running operation.
> Reading the part about  [`--resume-prefix`](https://instaloader.github.io/cli-options.html#cmdoption-resume-prefix) in the manual, resuming of story downloads is not supported.

It is canceled when it reaches any http error code listed on --abort-on option.

I checked the --resume-prefix and does not say anything about supporting :stories, so adding it to the command I run would it allow me to get an iterator/resume file?

Currently the command does not save any iterator file as it does with profile's post.

Thanks in advance.

**Comment by Showmaster3000** [comment]
> I checked the --resume-prefix and does not say anything about supporting :stories, so adding it to the command I run would it allow me to get an iterator/resume file?
>> resuming of story downloads is not supported
