### ISSUE TITLE
Script Stops after 1000_1100 Followers Scraping 

### ISSUE THREAD

**Issue by zeyadkhaled1** [instaloader/instaloader#1858]
Iam using the following code to scrape usernames of followers from a certain page , but it just scrapes 1000_1100 follower and then finishes without raising error or anything
Here is the code :
```
from instaloader import Instaloader, Profile
#!/usr/bin/env python3
login_name = 'ahmedk123643'
target_profile = 'joinrepublic'
loader = Instaloader()
# login
try:
    loader.load_session_from_file(login_name)
except FileNotFoundError:
    loader.context.log("Session file does not exist yet - Logging in.")
if not loader.context.is_logged_in:
    loader.interactive_login(login_name)
    loader.save_session_to_file()
# Obtain profile metadata
profile = Profile.from_username(loader.context, target_profile)
# Print list of followers
followers = profile.get_followers()
with open('file.txt', 'a') as f:
    for followee in followers:
        username = followee.username
        f.write(f"{username}\n")
```
Currently it doesn't scrap anything it's just runs and finishes and the text file created is empty, if i Deleted the Session file located in : 
AppData\Local\Instaloader\session-ahmedk123643.
it works but generates the same 1000_1100 followers

**Comment by n4ff4h** [comment]
Is the issue not getting all the usernames of the followers? In my case I could not get all the posts. Does not raise an error or anything. But since I am not downloading any posts, I omitted L.login() and somehow it is fetching all the posts from the profile.
