### ISSUE TITLE
Instaloader stops at a specific post. Can I skip it ?

### ISSUE THREAD

**Issue by RangerKevin2** [instaloader/instaloader#1859]
I'm downloading all my saved posts using this command: 
instaloader --no-video-thumbnails --no-captions --no-metadata-json --no-iphone --login Myusername :saved

The 6240th post of my collection systematically gives the HTTP error 400. It appears that this post doesn't exist anymore but it is still in my IG collection (weird). I'm only using the windows executable version, is there a way to skip it ? Like manually setting a period of time or prevent instaloader from fetching it ?

I'm using Instaloader for windows v4.9.5 
![20230111_173413](https://user-images.githubusercontent.com/64848329/211864648-826734b0-e0da-427b-a4d5-74321a29c970.jpg)

**Comment by TahaHydra** [comment]
had the same problem created fake insta account and logged in it stopped

**Comment by n4ff4h** [comment]
Happened to me too. Since I am not downloading the posts. I ommited L.login(). However this time it gets all the post info.

**Comment by aandergr** [comment]
If you scroll down in your browser or in the app of your saved posts page, are there any pictures shown which are not downloaded by Instaloader?
