### ISSUE TITLE
Able to get Profile info in local but not in AWS EC2

### ISSUE THREAD

**Issue by patilaum** [instaloader/instaloader#1863]
**Describe the bug**
When i use following code snippet in my local pc, I get the response correctly, but when I run the same in AWS EC2 it shows redirecting to login page. I am guessing this has something to do with cookies and sessions. How can I export my session from local to ec2? Also I am not been able to login to Instagram in AWS EC2. It flags my account as suspicious.

**To Reproduce**
```
import instaloader

from datetime import datetime
from itertools import dropwhile, takewhile
import csv
username = ""
L = instaloader.Instaloader()
prof = instaloader.Profile.from_username(L.context, username)
met = prof._metadata()
```

**Error messages and tracebacks**
```
HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=librarymindset to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/

HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=librarymindset to https://www.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?cc02f33c-4b45-427a-b29f-0e4f99f19a96)
---------------------------------------------------------------------------
LoginRequiredException                    Traceback (most recent call last)
/home/ubuntu/scraping/Untitled.ipynb Cell 39 in <module>
      [6](vscode-notebook-cell://ssh-remote%2Bec2-54-91-134-125.compute-1.amazonaws.com/home/ubuntu/scraping/Untitled.ipynb#X66sdnNjb2RlLXJlbW90ZQ%3D%3D?line=5) username = "librarymindset"
      [8](vscode-notebook-cell://ssh-remote%2Bec2-54-91-134-125.compute-1.amazonaws.com/home/ubuntu/scraping/Untitled.ipynb#X66sdnNjb2RlLXJlbW90ZQ%3D%3D?line=7) L = instaloader.Instaloader()
----> [9](vscode-notebook-cell://ssh-remote%2Bec2-54-91-134-125.compute-1.amazonaws.com/home/ubuntu/scraping/Untitled.ipynb#X66sdnNjb2RlLXJlbW90ZQ%3D%3D?line=8) prof = instaloader.Profile.from_username(L.context, username)
     [10](vscode-notebook-cell://ssh-remote%2Bec2-54-91-134-125.compute-1.amazonaws.com/home/ubuntu/scraping/Untitled.ipynb#X66sdnNjb2RlLXJlbW90ZQ%3D%3D?line=9) # .from_username(username = username)
     [11](vscode-notebook-cell://ssh-remote%2Bec2-54-91-134-125.compute-1.amazonaws.com/home/ubuntu/scraping/Untitled.ipynb#X66sdnNjb2RlLXJlbW90ZQ%3D%3D?line=10) met = prof._metadata()

File ~/.local/lib/python3.8/site-packages/instaloader/structures.py:704, in Profile.from_username(cls, context, username)
    702 # pylint:disable=protected-access
    703 profile = cls(context, {'username': username.lower()})
--> 704 profile._obtain_metadata()  # to raise ProfileNotExistsException now in case username is invalid
    705 return profile

File ~/.local/lib/python3.8/site-packages/instaloader/structures.py:773, in Profile._obtain_metadata(self)
    771 try:
    772     if not self._has_full_metadata:
--> 773         metadata = self._context.get_iphone_json(f'api/v1/users/web_profile_info/?username={self.username}',
    774                                                  params={})
    775         if metadata['data']['user'] is None:
    776             raise ProfileNotExistsException('Profile {} does not exist.'.format(self.username))

File ~/.local/lib/python3.8/site-packages/instaloader/instaloadercontext.py:488, in InstaloaderContext.get_iphone_json(self, path, params)
    486 for header in ['Host', 'Origin', 'X-Instagram-AJAX', 'X-Requested-With']:
...
--> 336         raise LoginRequiredException("Redirected to login page. Use --login.")
    337     # alternate rate limit exceeded behavior
    338     raise TooManyRequestsException("Redirected to login")

LoginRequiredException: Redirected to login page. Use --login.


```

**Instaloader version**
`instaloader --version` output. - 4.9.5

**Comment by Showmaster3000** [comment]
Instagram checks the ip addresses from where the requests come from. So there is a difference between your local and any other system. If you do too many anonymous requests from your local, you will get the same error forcing you to login.
You can copy your session file from your profile folder to your remote host and use it for your requests. More info see manual.

So it seems that this is not a bug in instaloader.

**Comment by patilaum** [comment]
Hi. This thing works, but it gives me a 429 too many Requests error after a while. I followed your troubleshooting page. Can you tell me whats the exact rate limit? It shows wait for 30 mins, but when I try again after 30 mins, it shows wait for 30 mins again. This goes on and I am not able to use the same session again. Any suggestions here?

**Comment by valentimmx** [comment]
@patilaum did you find a way to resolve this? Im taking the same problem.

**Comment by mauronr** [comment]
> @patilaum did you find a way to resolve this? Im taking the same problem.

We worked around it connecting via a proxy.

**Comment by rishy05** [comment]
@mauronr I'm having the same issue. What proxy service did you use?

**Comment by mauronr** [comment]
> @mauronr I'm having the same issue. What proxy service did you use?

There are many providers that can provide good service. Each of them has slightly different technical integration and pricing. You should evaluate a few to choose the best for your workloads before making your final decision.

Having said that, we evaluated Bright Data, Oxylabs and SmartProxy about 2 years ago and have chosen SmartProxy.

**Comment by rishy05** [comment]
@mauronr Alright thanks for your reply!

**Comment by rishy05** [comment]
@mauronr I tried using squid proxy server and running the script, getting this error. raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001EF6DE38190>, 'Connection to <my proxy ip address> timed out. (connect timeout=300.0)'))). Any work arounds ?

**Comment by mauronr** [comment]
> @mauronr I tried using squid proxy server and running the script, getting this error.
> 
> raise ProxyError(e, request=request) requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001EF6DE38190>, 'Connection to timed out. (connect timeout=300.0)'))).
> 
> Any work arounds ?

This is a proxy issue. You have to work with the proxy provider on how to handle the errors they may suffer. That's why I mentioned that the evaluation and selection must consider integration technical aspects.
 
Be aware that residential proxies are flaky by nature. In my experience some 20% of the proxy-routed requests fail for some issue not related to Instaloader not Instagram. You must implement robust exception handling and retry mechanisms so your code works continuously.
