### ISSUE TITLE
ImportError: attempted relative import with no known parent package (line 21 in <module> from .exceptions import *)

### ISSUE THREAD

**Issue by mammuthus** [instaloader/instaloader#1865]
Hello, guys. I'm getting "ImportError: attempted relative import with no known parent package" when trying to run instaloader.
Could you help me?

**Sysinfo:**
macOS Ventura 13.1 (22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4 / RELEASE_ARM64_T6000 arm64)
pip 22.3.1 from /Users/omavel/Library/Python/3.9/lib/python/site-packages/pip (python 3.9)
Python 3.9.6

**Steps:**
1. `pip3 install instaloader`

Result: 
```
Successfully built instaloader
Successfully installed certifi-2022.12.7 charset-normalizer-3.0.1 idna-3.4 instaloader-4.9.5 requests-2.28.2 urllib3-1.26.14
```
2. `sudo python3 /Users/omavel/Library/Python/3.9/lib/python/site-packages/instaloader/instaloader.py -l myusernamehere -p mypasshere --no-videos --no-video-thumbnails --no-captions --no-metadata-json --no-profile-pic targetusernamehere`

Result:
```
Traceback (most recent call last):
  File "/Users/omavel/Library/Python/3.9/lib/python/site-packages/instaloader/instaloader.py", line 21, in <module>
    from .exceptions import *
ImportError: attempted relative import with no known parent package
```

**Comment by mammuthus** [comment]
Funny, but I faced the same issue on Windows (same steps)

**Comment by aandergr** [comment]
> 2. `sudo python3 /Users/omavel/Library/Python/3.9/lib/python/site-packages/instaloader/instaloader.py -l myusernamehere -p mypasshere --no-videos --no-video-thumbnails --no-captions --no-metadata-json --no-profile-pic targetusernamehere`

Start Instaloader simply with `instaloader` if it is in your PATH, or `/Users/omavel/Library/Python/3.9/bin/instaloader`.
