### ISSUE TITLE
Trying to scrape posts and hitting 401

### ISSUE THREAD

**Issue by FeliX6440** [instaloader/instaloader#1870]
I want  to scrape the posts of a user, while NOT logging in. This works without issues for the first 12 posts, then retries, then fails with 401. Any suggestions or ideas?

**Comment by Eksx** [comment]
@FeliX6440 Instagram recently made some changes and it looks like without logging in you can only load 12 posts. Take a look at any instagram page without logging in any local browser.

**Comment by FeliX6440** [comment]
Yes I have seen that aswell... the weird thing is that sometimes I can do it, and sometimes I can't so that's really annoying. Also I have noticed that some apps still can access all of a users data without logging in... like grin for example... I wonder how they do it?

**Comment by G-force78** [comment]
cant even get 12 images

**Comment by vuhuulan** [comment]
**Problems**
Want to download from public profiles, however could only download all N (>12) posts the first time, after this capped at 12 posts.
Tried logging in using instaloader, however could not pass instagram challenge link (eg. #1873, #1872)
 
**Workaround**
Logged out of all accounts existing on web, then download will not be capped at 12 posts anymore.
