### ISSUE TITLE
HTTP error code 401 while not logged in, Suspicious activity when logged in. 

### ISSUE THREAD

**Issue by CNRP** [instaloader/instaloader#1872]
So I was playing around with the datetime example class with a python script, trying to filter posts between certain dates which I could not get to work correctly for some reason, it wouldn't download anything, so I ran this multiple times and I decided to go back to my previous script which I did have working and it started getting the error message 

> JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
> JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
> JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]

I've then tried to run the script in the terminal and the result was similar, I tried also to login and would get the following message

> Session file does not exist yet - Logging in.
> Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/A...

Upon following this step, It would ask me to do it again on the next login attempt, without ever actually letting me in.  Forced me to reset my password a bunch of times due to "suspicious activity" on my account .

Is this Instagram blocking my requests now as it deems me suspicious? Is there any way around this so I can continue to use the program? Appreciate any help, this program seems to be the best solution for my personal website instagram gallery so It would be ideal if there is a way around these issues. 

Is it possible that it will just resume working after some amount of time? 

This is on Instaloader v4.9.5

**Comment by CNRP** [comment]
I've tried using a different account and still get the same error. 
I am now able to download the first 12 posts without a login though.

**Comment by Mehmet-Erkan** [comment]
Just a matter of time until you get blocked.  This happened to me after the password changes I got a final warning and then got banned.  I do scraping with Selenium  Driver to simulate human behavior. I like this package but to do really serious scraping you have to act like a human and do it slowly. Instagram is fighting hard against bots.
