### ISSUE TITLE
Download of public, saved posts not dependent on login

### ISSUE THREAD

**Issue by PedroM25** [instaloader/instaloader#1877]
Attempting to download my own saved posts leads to some nasty `HTTP Error 400 (Bad Request) on GraphQL Query. Retrying with shorter page length.` followed by the "Suspicious activity" warning.

From my quick analysis of the code, it seems you only really need the user to log in to fetch all saved posts, not to actually download them.

My feature request is: By default, the account would be used to download private posts and the remaining, public posts could be downloaded without using the account. There could also be a flag to skip the download of private posts.
This would lower the chances of a user having it's account blocked by Instagram.

I assume the download of posts is being done through my account and triggering the alerts because I keep getting the 400 code.

**Comment by PedroM25** [comment]
I am having some trouble understanding the codebase
But if someone is willing to give me some pointers on how this could be achieved, I am more than happy to contribute

**Comment by haidar4243** [comment]
facing the same issue right now. did you find any solution?

**Comment by haidar4243** [comment]
same code working on my mac but when i upload my code to ubuntu server then instaloader throws this error
