### ISSUE TITLE
[BUG]: 400 Bad Request

### ISSUE THREAD

**Issue by Niffecs** [instaloader/instaloader#1890]
The first few images run through correctly and without problems. At some point, however, the tool obviously has problems continuing to work. Can you fix this or tell me what I can do differently?

![image](https://user-images.githubusercontent.com/117777659/218258158-6ff90e3e-35f1-4705-a8eb-43db4b519098.png)

**Comment by Showmaster3000** [comment]
Error 400 mostly indicates a locked account. Please check in the app or browser if you can use your account.

**Comment by Niffecs** [comment]
> Error 400 mostly indicates a locked account. Please check in the app or browser if you can use your account.

Hi,
I can use all the normal functions with the account both in the app and on the website. Therefore, I don't know exactly what you mean. The username and password are correct. Can you please describe in more detail what you mean?

**Comment by EnthusiastAnon** [comment]
Is this with the newest version?

**Comment by Niffecs** [comment]
> Is this with the newest version?

To be honest, that was version ``4.9.5``. I have now upgraded to ``4.9.6``. But that does not solve the problems.

**Comment by Niffecs** [comment]
To avoid Issue #1889 a bit, I tried to do the whole thing without registering.
But that only went well for a short time.

**Comment by Showmaster3000** [comment]
> Can you please describe in more detail what you mean?

Instagram detects usage of scraping tools like instaloader. If you extensively use it, your downloading account gets blocked or banned. A softer version is blocking the session you are using. Error 400 usually points to this situation.
This problem doesn't depend on any version of instaloader.

Btw. you missed the issue reporting template. So important information is missing like the command line you used...

**Comment by kevinhower** [comment]
If I want to catch this 400 bad request in a try: except: block in python, how do I label the error so it properly catches it? I have tried to find it in the documentation— and maybe I am just missing it— but so far have not found it.  

I want to be able to pause the downloading at the error, go fix the issue in the browser and then resume downloading... 

I really HATE Instagram's stupid limits ...

**Comment by fireattack** [comment]
> If I want to catch this 400 bad request in a try: except: block in python, how do I label the error so it properly catches it? I have tried to find it in the documentation— and maybe I am just missing it— but so far have not found it.
> 
> I want to be able to pause the downloading at the error, go fix the issue in the browser and then resume downloading...
> 
> I really HATE Instagram's stupid limits ...

You can't do it simply at least, because it was already captured inside Instaloader. You have to modify the existing code to some extent to enable that. Try look around QueryReturnedBadRequestException

**Comment by Niffecs** [comment]
> > Can you please describe in more detail what you mean?
> 
> Instagram detects usage of scraping tools like instaloader. If you extensively use it, your downloading account gets blocked or banned. A softer version is blocking the session you are using. Error 400 usually points to this situation. This problem doesn't depend on any version of instaloader.
> 
> Btw. you missed the issue reporting template. So important information is missing like the command line you used...

**Describe the bug**
The script works well for a while. Then it throws the error described in the picture. Then the tool breaks down completely.


**To Reproduce**
I run the script with and without login. 
```python
import instaloader

# Create an instance of Instaloader
L = instaloader.Instaloader()

# Define the username of the public profile
username = "example_username"

# Download the public profile
profile = instaloader.Profile.from_username(L.context, username)

# Iterate through all the posts in the profile
for post in profile.get_posts():
    # Download the picture or video
    L.download_post(post, profile)

# Close the Instaloader session
L.context.session.close()
```

**Expected behavior**
I expected the script to download all images properly. 

**Error messages and tracebacks**
![image](https://user-images.githubusercontent.com/117777659/218258158-6ff90e3e-35f1-4705-a8eb-43db4b519098.png)

**Instaloader version**
`instaloader --version`: 4.9.6

I don't know what that tells you more now, but here is the report

**Comment by Niffecs** [comment]
Since it is obviously no longer about the issue and I don't think I can find a solution here, I will close the issue now. Maybe the bug will be fixed sometime.

**Comment by AndrejGorodnij** [comment]
Got same error... but I use library for the first time. Owner profile is open, without any limitations.

```
Traceback (most recent call last):
  File "main.py", line 20, in instagram
    video_file = download_insta_video(message.text)
  File "/home/deployer/VideoPosterBot/loaders/instagram.py", line 5, in download_insta_video
    post = Post.from_shortcode(loader.context, url.split("/")[-2])
  File "/home/deployer/VideoPosterBot/venv/lib/python3.8/site-packages/instaloader/structures.py", line 88, in from_shortcode
    post._node = post._full_metadata
  File "/home/deployer/VideoPosterBot/venv/lib/python3.8/site-packages/instaloader/structures.py", line 205, in _full_metadata
    self._obtain_metadata()
  File "/home/deployer/VideoPosterBot/venv/lib/python3.8/site-packages/instaloader/structures.py", line 192, in _obtain_metadata
    pic_json = self._context.graphql_query(
  File "/home/deployer/VideoPosterBot/venv/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 429, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "/home/deployer/VideoPosterBot/venv/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 346, in get_json
    raise QueryReturnedBadRequestException("400 Bad Request")
instaloader.exceptions.QueryReturnedBadRequestException: 400 Bad Request
```

**Comment by aandergr** [comment]
Does it work with the upcoming 4.10 version, where the HTTP headers for these kind of requests where updated?

```
pip3 install --upgrade --pre git+https://github.com/instaloader/instaloader@upcoming/v4.10
```

**Comment by yarodevuci** [comment]
@aandergr have you tried?

**Comment by fireattack** [comment]
@aandergr : after updating to the newest header, it works much better. I can now update more than 5 accounts together without triggering andy 4xx errors.

**Comment by fireattack** [comment]
Started to get 4xx errors again after a week of usage. Unfortunately I don't think we're going to get as stable as a few months ago. Instagram is working hard with its anti-bot algorithms.

**Comment by Niffecs** [comment]
Hello people 
Here a few words. 
I currently have no idea why @aandergr reopened the thread. The new version does not really solve the problem. 
I agree with @fireattack. 

> @aandergr : after updating to the newest headers ([1074a74](https://github.com/instaloader/instaloader/commit/1074a74a595f63f8db27fac53b3c1d09c85aaae3)), it works much better. I can now update more than 5 accounts together without triggering any 4xx errors.


This is a significant improvement, but it is in no way a solution to the problem. In the end, one expects the tool to run completely. 

> Started to get 4xx errors again after a week of usage. Unfortunately I don't think we're going to get as stable as a few months ago. Instagram is working hard with its anti-bot algorithms.

In the end, the present version is quite usable. It would be nice if the bot doesn't keep trying to download the images in a worse quality. Then you would not always have to look at which images are in decent and which are in poor quality. 


Finally, I would ask you to create a new issue and not to continue using my old one. I am of course happy that people continue to discuss it here, but I don't think a solution will be found in the foreseeable future. You are welcome to refar to the issue here, but please keep the issue here closed or delete the issue here. 



I wish you good luck with the implementation.

**Comment by paboum** [comment]
I confirm, changing the account helps to overcome this issue. Thus, the script should handle this situation by either:
- detecting it and pausing for the timeout (which is...? 24h? I don't know)
- ending the execution and saying "your account has been flagged by Instagram, use another"
- using multiple accounts for the process in round-robin fashion, smartly load balancing between them to minimize the chance of Instagram detecting this
Since some timeouts are already there, I suggest the session stores the timeout information. If I cancel the run and start it again, I get error 400 again. Instead, I would expect the script knows that "there is a 20 minute timeout on this account until 12:34" and it should not attempt using it until explicitly requested by the user (e.g. `--ignore-known-timeout`).
Finally, the same account is still able to use Instagram with the mobile app, see the media in full resolution, thus somehow the user agent or whatever affects the server response. This should be investigated further and remediated.
