### ISSUE TITLE
Doesn't download in higher resolution (1080 instead of 1440)

### ISSUE THREAD

**Issue by Rocket3192** [instaloader/instaloader#1893]
Hello, the software downloads in 1080x1350 at best, even though pictures are available in 1440x1800

Is there a setting I'm missing or is the software just not able to do it ?

Thanks

**Comment by fireattack** [comment]
Example?

**Comment by Rocket3192** [comment]
For example : https://www.instagram.com/p/CoovJ36N6rB/
Pictures are available in 1440x1800 and I can get them with instantgram, but instaloader get them in 1080x1350

**Comment by fireattack** [comment]
Interesting. When I test at the moment you posted that reply, I indeed have the same issue.

But now I try again, I can download the 1440x1800 ones just fine.

Could you test?

**Comment by Rocket3192** [comment]
Still 1080x1350 here, are you using an account ? I'm not cause there is a big risk of getting banned, plus I can't even connect, last time i tried it made me change my password cause Instagram believed I was getting hacked... there was no way of allowing it, even though I clicked on "That was me" it forced me to change my password

**Comment by fireattack** [comment]
Yes, I'm logged in.

It's possible to use a Cookie file, but AFAIK not directly using instaloader binary. You need to use this short Python script: https://instaloader.github.io/troubleshooting.html#login-error

**Comment by duoside** [comment]
Duplicate of #1800
