### ISSUE TITLE
Download of public, saved posts not dependent on login

### ISSUE THREAD

**Issue by PedroM25** [instaloader/instaloader#1897]
**Provide us a use case of the feature**
As a user of Instaloader, I want to be able to download public, saved posts without triggering "Suspicious activity" warnings in my account.

**Describe the solution you'd like**
As a user of Instaloader, I want to be able to download public, saved posts without being logged in. A login would only be necessary to fetch the list of saved posts, not to actually download them. I could then specify wether I wanted to download private, saved posts using my account or not (through a flag).

This would reduce the risk of my account being banned.

**Describe alternatives you've considered**
Download saved, public posts one by one, using `instaloader -- -CnoEudAuEhy`

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes

**Additional context**
This is something that occurred to me while downloading the saved posts of my own account. Since the majority of them are public, I did not expect my account to be flagged for "suspicious activity" as they can be easily viewed and downloaded without needing an account.

**Comment by gutomaia** [comment]
Can´t we use TOR or some proxies to by pass that restriction?
