### ISSUE TITLE
Upgrade to 4.9.6 not working on rpi

### ISSUE THREAD

**Issue by zero0n3** [instaloader/instaloader#1907]
Hello
i've installed instaloader 4.9.5 on Rpi via command:
`pip3 install instaloader`
and all works well.

Today I discovered the new release 4.9.6 so i used the command
`pip3 install --upgrade instaloader`
but it says
`Requirement already up-to-date: instaloader in /folder/`

Where am I doing wrong?

This is my Rpi build:
```PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
Kernel: Linux 5.15.89-v7+
      Architecture: arm```

**Comment by aandergr** [comment]
> This is my Rpi build:
> 
> ```
> NAME="Raspbian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=raspbian
> ID_LIKE=debian
> Kernel: Linux 5.15.89-v7+
>       Architecture: arm```
> ```

Debian buster ships only up to python version 3.7; however Instaloader 4.9.6 requires at least python version 3.8, which is shipped with the current version of Debian, bullseye.

**Comment by zero0n3** [comment]
> > This is my Rpi build:
> > ```
> > NAME="Raspbian GNU/Linux"
> > VERSION_ID="10"
> > VERSION="10 (buster)"
> > VERSION_CODENAME=buster
> > ID=raspbian
> > ID_LIKE=debian
> > Kernel: Linux 5.15.89-v7+
> >       Architecture: arm```
> > ```
> 
> Debian buster ships only up to python version 3.7; however Instaloader 4.9.6 requires at least python version 3.8, which is shipped with the current version of Debian, bullseye.

Thanks. Solved!

**Comment by zero0n3** [comment]
Solved by using and updated version of python
