### ISSUE TITLE
instaloader PID ID

### ISSUE THREAD

**Issue by VladimirGorin** [instaloader/instaloader#1910]
Hi all! A simple question is how to get the process pid id? I need this so that I can stop it remotely, if there is another way, write.

**Comment by subvert221** [comment]
Inside your python script:
```
import os
print(os.getpid())
```

Outside (bash):
`pgrep -a <python interpreter name> | grep <script name> | awk '{print $1}'`

e.g. if the python interpreter used to run the script is "py" and the script name is "main.py"
`pgrep -a py | grep main | awk '{print $1}'`

You can limit the output of pgrep to give you only the newest (-n) or the oldest (-o) PID that matches the given pattern.
You can then kill the process specifying its PID. As a matter of fact, you may want to write a bash restart script that would first kill the old script and only then run another one.

However, if you have multiple scripts with the same name, the better strategy would be writing PIDs to files by the scripts themselves inside their working folders.
I prefer to do it like this:

main.py
```
import os
...
with open('latest.txt', 'w') as pidfile:
    pidfile.write(str(os.getpid()))
```
restart.sh
```
kill `cat latest.txt`
python3.10 -u main.py
```

**Comment by VladimirGorin** [comment]
ty
