### ISSUE TITLE
Downloaded some but not all images with a certain hashtag

### ISSUE THREAD

**Issue by karticus123** [instaloader/instaloader#1912]
**Describe the bug**
I tried to download pictures with the hashtag kidkfotos2023. Instagram has 47 fotos, but only 32 were downloaded. Interestingly not even all images from the same user. For example the user wolfgang_freimark uploaded seven images with the same tags, but only four were downloaded. 

**To Reproduce**
Command line was: instaloader "#kidkfotos2023" --filename-pattern {profile}

**Expected behavior**
As above: i have exepected that all images are downloaded

**Error messages and tracebacks**
no error messages

**Instaloader version**
4.9.6

**Additional context**
none

**Comment by aandergr** [comment]
> **Describe the bug** I tried to download pictures with the hashtag kidkfotos2023. Instagram has 47 fotos, but only 32 were downloaded. Interestingly not even all images from the same user. For example the user wolfgang_freimark uploaded seven images with the same tags, but only four were downloaded.
> 
> **To Reproduce** Command line was: instaloader "#kidkfotos2023" --filename-pattern {profile}

With `--filename-pattern {profile}` the files are named after the profile, and for each profile at most one will be downloaded.
