### ISSUE TITLE
get_followers() only allows me to iterate through 50 followers

### ISSUE THREAD

**Issue by zeinramadan** [instaloader/instaloader#1915]
**Describe the bug**
I am trying to loop through all the followers for a specific instagram username using a for loop on the get_followers() function but it is only allowing me to loop through 50 followers before completing.

**To Reproduce**
```python

# initialize Instaloader
L = instaloader.Instaloader()

# Log in
username = ""
password = ""
L.context.log("Logging in as %s..." % username)
L.context.login(username, password)

profile = instaloader.Profile.from_username(L.context, username)

for follower in profile.get_followers():
       follower_info = {
                        'username': follower.username,
                        'name': follower.full_name,
                        'bio': follower.biography
                    }

       # save follower info to file
       with open(os.path.join(username, follower.username, 'profile.json'), 'w', encoding='utf-8') as f:
                  json.dump(follower_info, f, ensure_ascii=False)

```

**Expected behavior**
I expect the code to iterate through every follower for username and get each follower's username, bio, and full name.

**Error messages and tracebacks**
No error messages, code just completed after going through 50 followers.

**Instaloader version**
using instaloader v4.9.6

**Comment by zeinramadan** [comment]
I can't find if there is a default parameter for get_followers() in the documentation that sets the max number of accounts to iterate through..

**Comment by tripaak** [comment]
its Instagram limit . it only allows 50 account to appear for each request.

**Comment by tathastu871** [comment]
How are you still able to login. My 3 account got banned on using login option with instaloader

**Comment by aandergr** [comment]
The instaloader.login() function is currently known to cause issues, we recommend using the firefox cookie import workaround described in https://instaloader.github.io/troubleshooting.html#login-error.

However, accessing followees and followers works fine for me, in numbers well exceeding 50.

**Comment by Macerul** [comment]
> The instaloader.login() function is currently known to cause issues, we recommend using the firefox cookie import workaround described in https://instaloader.github.io/troubleshooting.html#login-error.
> 
> However, accessing followees and followers works fine for me, in numbers well exceeding 50.

So this is exactly what I need, using my account I want informations about my followers (username, number of follower, if it's private, etc), using that script is enough to not get blocked?Also  I would run the script once I get like 1k follower, can I retrieve all the information at once or do I need to execute the code with some kind of intervals?

**Comment by aandergr** [comment]
Not reproducible.
