### ISSUE TITLE
instaloader

### ISSUE THREAD

**Issue by Hedie-rashidian** [instaloader/instaloader#1916]
i want to get the data from insta by instaloader to a sqlite database but i could not.if you can tell me why i would appreciate

import instaloader
from datetime import datetime
from itertools import dropwhile, takewhile
import time
import csv
import urllib3, socket
import sqlite3
from sqlite3 import OperationalError, connect

l = []
db = sqlite3.connect("database1.db")
cur = db.cursor()
cur.execute(
    """CREATE TABLE IF NOT EXISTS hedie(
    id INTEGER PRIMARY KEY,
    captions TEXT)"""
)
loader = instaloader.Instaloader()
loader.login('hedrashidii', '09227365701Hedi@')

def get_post_info_csv(hashtag):
    with open(hashtag+'.csv', 'r', newline='') as file:
        writer = csv.writer(file)
        posts = instaloader.Hashtag.from_name(loader.context, hashtag).get_posts()
        for post in posts:
            print("post caption: " + str(post.caption))
            for i in posts:
                l.append(i)
    posturl = "https://www.instagram.com/&__d=dis" + post.shortcode
    print("post url: " + posturl)
    writer.writerow(
        ["post", post.caption])

hashtag = "به"
get_post_info_csv(hashtag)

cur.executemany("""INSERT INTO hedie(captions)VALUES(?)""", l)
db.commit()
db.close()

**Comment by zeinramadan** [comment]
This is not worth posting as an issue. This is more of a stackoverflow question, but likely won't get a response on stackoverflow because you haven't described what issue you're facing, and how you're trying to do it.

**Comment by Hedie-rashidian** [comment]
thank you
