### ISSUE TITLE
Why not using multiple ids in "api/v1/feed/reels_media/"?

### ISSUE THREAD

**Issue by cykac04** [instaloader/instaloader#1917]
When using iphone api to download stories of about 40 users, it is easily to get blocked with this message:

`JSON Query to api/v1/feed/reels_media/?reel_ids=371948731: HTTP error code 500. [retrying; skip with ^C]`

Maybe it is due to large number of requests to "api/v1/feed/reels_media/" ?

Is it possible to use the format "api/v1/feed/reels_media/?reel_ids={id_a}&reel_ids={id_b}..." to reduce the number requests in one download?

**Comment by aandergr** [comment]
> Is it possible to use the format "api/v1/feed/reels_media/?reel_ids={id_a}&reel_ids={id_b}..." to reduce the number requests in one download?

Have you tried that? The JSON structure of the response looks like it could allow containing the information of multiple StoryItems at once.
