### ISSUE TITLE
Example of adding proxies and limits?

### ISSUE THREAD

**Issue by skintflickz** [instaloader/instaloader#1926]
I am currently using 

`for post in instaloader.Hashtag.from_name(L.context, 'cat').get_posts():
    # post is an instance of instaloader.Post
    L.download_post(post, target='#cat')`

How do I add a proxy to this? (could you please add example code and not just point at a post that "says", this is how you do it.. thanks you)
Also how can you limit the amount of downloads ?

**Comment by leunglong0123** [comment]
Since Instaloader use request library, setting ENV like 
```
export HTTP_PROXY=10.10.1.10:3128
export HTTPS_PROXY=10.10.1.11:1080
export FTP_PROXY=10.10.1.10:3128
```
[https://stackoverflow.com/questions/8287628/proxies-with-python-requests-module](url)
should be work

**Comment by zakrian07** [comment]
i need verify ssl false how can i do ?
