### ISSUE TITLE
:stories sort into folders

### ISSUE THREAD

**Issue by MattyG7** [instaloader/instaloader#1928]
I was using :stories the other day and found that all the stories just saved into one folder called :stories. I noticed in the command line window that the program knew when it’s a different user/profile. So I was wondering if the stories could save into individual folders within the :stories folder?

**Comment by YisusChrist** [comment]
What is the purpose of that?

I mean, I guess it could be 'useful' if those stories could be grouped in a folder that represents the date of that story.

In case that is not the purpose how would you save them in individual folders?

**Comment by MattyG7** [comment]
The same reason other commands don't chuck everything into just a single folder, and it's great for organisation and finding too. Atm, they're all just chucked in there and no one would really know which images/videos are from which profile. I dunno about folder names based on date but saving into individual folders based on profile names would be simple to implement and be very useful too :)
