### ISSUE TITLE
Download stories (`-s`) should not require login for public profiles

### ISSUE THREAD

**Issue by lukehutch** [instaloader/instaloader#1929]
https://storysaver.net/ has no problem downloading stories for public profiles without a login. Why does instaloader require a login?

**Comment by Showmaster3000** [comment]
Downloading stories generally requires to login. Try to see a story on Instagram in browser - its not possible.
Storysaver and all other pages where you can download stories are using either the official API or just use dummy accounts in background.

**Comment by lukehutch** [comment]
OK, thanks for explaining, I didn't realize that.
