### ISSUE TITLE
Get downloaded comments

### ISSUE THREAD

**Issue by kooshazarei** [instaloader/instaloader#193]
**Describe the bug**
I download the specific post and save it just like this:

post = instaloader.Post.from_shortcode(L.context, "BpVo89eAQjJ")
instaloader.save_structure_to_file(post, "test")

when i load the file and start to get the comments:

post = instaloader.load_structure_from_file(L.context, "testk")
for c in post.getcomments():
...

it doesn't consider the data that is downloaded. and just try to connect to internet again and get comments data. so what is the problem?

**Instaloader version**
4.1.1

**Additional context**

**Comment by aandergr** [comment]
save_structure_to_file() does not save the post's comments. There is [Instaloader.update_comments()](https://instaloader.github.io/as-module.html#instaloader.Instaloader.update_comments) to save a Post's comments into a JSON file.
