### ISSUE TITLE
Login Unusual Detected Whenever try to Login Instaloader

### ISSUE THREAD

**Issue by alwifearzz17** [instaloader/instaloader#1930]
i try to login using this command to download a post [instaloader --login=xxxxx -- -xxXxXxX] whenever i try to login and download it will popup this error in cmd as below :-
Errors or warnings occurred:
-XxxXXxX: 400 Bad Request
After that my intagram will detect unusual login and ask me to change my password every time if i try to download a post by login.. Before this im using Login to download post without any issues.. Now i cant download it because Instagram will always ask me to change the password.. Any help?

**Comment by leondong1017** [comment]
same question, what's the fix?

**Comment by snowbie** [comment]
Don't keep resetting your password. I did this, and after a few password resets, you get locked out until you prove your identity. If you don't prove your identity within 180 days, they will delete your account.
I did it on my personal account, so I didn't really mind all that much, but to do photo identification four different times is really annoying.

**Comment by leondong1017** [comment]
> u also facing the same issue?

Exactly, every time I try to download profile, it asked me to login in. As long as I typed in the password, it sent me a link to reset my password for the sake of security. 😭

**Comment by alwifearzz17** [comment]
> > u also facing the same issue?
> 
> Exactly, every time I try to download profile, it asked me to login in. As long as I typed in the password, it sent me a link to reset my password for the sake of security. 😭

i hope someone got solution for us

**Comment by EricWu91** [comment]
Same happened to me, but I managed to download data by logging in via Firefox and running the python script described at https://instaloader.github.io/troubleshooting.html#login-error
