### ISSUE TITLE
Profile Pic is not full resolution

### ISSUE THREAD

**Issue by rohansingh1126** [instaloader/instaloader#1932]
**Describe the bug**
The `profile_pic_url_hd` in profile info no longer contains full resolution image.

**To Reproduce**
(e.g. Instaloader command line)

```
instaloader profile <username>
```

**Expected behavior**
profile picture saved to be of full resolution

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

**Instaloader version**
`instaloader --version` output.
4.9.6

**Additional context**

**Comment by Showmaster3000** [comment]
The last profile pic I downloaded was on 28th with hd resolution. Maybe the pic of the profile you try to download is rather small? Sometimes users upload very cropped ones. You didn't gave an example where it fails. And maybe it has sth. to do with logged in vs. not.
How did you check that there is a larger version available?
