### ISSUE TITLE
How to download all post without login?

### ISSUE THREAD

**Issue by ankit0183** [instaloader/instaloader#1933]
can you please remove the login mechanism to download posts ? Anonymous access is very limited, can you increase more than 12 posts.. please

**Comment by Showmaster3000** [comment]
I don't understand your problem. You do not need to login. Just omit the `--login`. But anonymous access is limited - and that is done by Instagram, not by instaloader!

**Comment by tathastu871** [comment]
Login is needed to access private accounts

**Comment by ankit0183** [comment]
yeah but while we log in it suddenly logs out from my account and shows a red flag for suspicious activity ?.. can you please tell us an alternate method to use this or increase the post limit of downloading
