### ISSUE TITLE
Unable to fetch high quality image version of <post>

### ISSUE THREAD

**Issue by EricWu91** [instaloader/instaloader#1936]
**Describe the bug**
Same as https://github.com/instaloader/instaloader/issues/1539: 

![image](https://user-images.githubusercontent.com/9344516/229331680-d16d2f20-132d-493f-87cd-2eca04499661.png)

Attempting to download data from specific profiles causes 403 errors.

**To Reproduce**

instaloader --login <mylogin> xbox.pfps 

The reported profile is not public, but I have not attempted without the login data. Even so, there were cases with private (followed) profiles as well.

**Expected behavior**
Expected it to download data. 

**Error messages and tracebacks**
No error messages after these

**Instaloader version**
![image](https://user-images.githubusercontent.com/9344516/229331722-6f420fb0-344e-4c18-9d01-3a1bef0e8fbe.png)

**Additional context**
After these error messages, my session is broken and I have to login again (via firefox, and retrieving the cookies).

**Comment by nnhieu97** [comment]
i have the same problem

**Comment by aandergr** [comment]
Does it work with the upcoming 4.10 version, where the HTTP headers for these kind of requests where updated?

```
pip3 install --upgrade --pre git+https://github.com/instaloader/instaloader@upcoming/v4.10
```

**Comment by neocity12** [comment]
I'm facing the same problem even after trying v4.10

**Comment by linkyndy** [comment]
I'm having the same issue, also on `4.10`.

**Comment by amirAlamian** [comment]
same here

**Comment by Nycto97** [comment]
I remember having this a year ago as well, that was version 4.9.5. I even made a simple Chrome extension to be able to download picture in original quality, using the src, but only downside it, that's not bulk download.

Still hoping for a day Instaloader downloads original quality and not downsized pictures 🙏🏻
