### ISSUE TITLE
I have now lost my second account on instagram for using this script.

### ISSUE THREAD

**Issue by anoduck** [instaloader/instaloader#1937]
**Describe the bug**
I am not blaming anyone, so chill. Facebook has always been strict on anything they didn't code. I do think the issue needs to be addressed, though. It only takes using this script two or three times for your account to be suspended or banned.

**To Reproduce**

1. It is installed with pipx `pipx install instaloader`.
2. Then I run the script using my login to acquire my friends accounts. ` instaloader -V --no-video-thumbnails --no-captions --dirname-pattern ~/pattern/to/some/path/{profile} --login my_login desired_profile`
3. It only takes once or twice until I recieve the "400 bad request" error.
4. Then I discover I have to reauthenticate with a photo, but this has not worked in the past, and my account was still banned.

**Expected behavior**

I expected to be able to use this account to view my feed without being flagged, banned, or suspended.

**Error messages and tracebacks**
`Fatal error: 400 Bad Request`

**Instaloader version**

4.9.6

**Additional context**
I known it is completely out of control of the developer, but I do not understand why facebook even offers APIs if they are going to ban individuals for using them. 

Maybe slow down the rate at which the requests are made.

**Comment by tathastu871** [comment]
Same My three accounts got banned. Now i lost acess to all friends on insta. Also theyy would not accept another friend request from another account

**Comment by anoduck** [comment]
@tathastu871 Such a pity... Not the biggest fan of the zuckinator.

If there could be an option to set a min and max rest value between each request, and allow the script to randomly select a variable between those two maxims. It might prove useful in avoiding further account suspension. 

Better yet, implement a function that would automatically increase this value upon the first reception of the error 400 return.

**Comment by Arrmm** [comment]
Your account will be banned if you use -login option to download pictures and videos, especially if you are doing a large pull.  It's all about moderation.

**Comment by anoduck** [comment]
> Your account will be banned if you use -login option to download pictures and videos, especially if you are doing a large pull. It's all about moderation.

Eventually it will, but not instantaneously in my experience. You have to log in to acquire “high-resolution” images or to download/view a private accounts.

**Comment by tathastu871** [comment]
It doesnt matter if it takes 2 min rest betwen each image download.

But problrm is just using login option 2 times causes instant ban.

**Comment by yarodevuci** [comment]
any solution how not to get banned?

**Comment by anoduck** [comment]
> any solution how not to get banned?

It is Instagram's API that is causing the user's account to get band. As @Arrmm so subtly put it, "It's all about moderation." If you are going to use the script, **just ensure that you do not log in**. If a login is required to access a private account, then an entirely different approach is required. One could either use their web browser and employ one of the many bulk image download extensions, or a new script would need to be created from scratch that employs selenium or pyppeteer. 

-----

The author of the plugin, @instaloader, needs to remove the ability to login from the script altogether, which is what I was hoping would happen when I created this issue. This is primarily because by leaving it in the script, the author is encouraging further banning of innocent users who are unaware of this behavior. Thus, by performing no action, he is unconsciously taking part in their banning by not taking steps to prevent it.

**Comment by tathastu871** [comment]
Dev of intaloader should now consider making chrome extenion instead of python tool
 as extension would work in browser in real cookie issue will not happen

**Comment by anoduck** [comment]
> My account was **permanently** (after appeal) **banned** for using this script ONE TIME. Thanks for the warning, I should've listened...

It doesn't get any rougher than this. One time use, and bam, you are now banned. 

**What is important and unfortunately learned the hard way:** Is the ban is permanent and appeals will not be successful. In fact, appealing the ban will only serve to further jeopardize your own privacy, as it requires a photo of your face, your private phone number, and a verification number to link to the offending account. 

**So, if you are banned for using this script. Whatever you do, do not appeal it.**

**Comment by tathastu871** [comment]
> > My account was **permanently** (after appeal) **banned** for using this script ONE TIME. Thanks for the warning, I should've listened...
> 
> It doesn't get any rougher than this. One time use, and bam, you are now banned.
> 
> **What is important and unfortunately learned the hard way:** Is the ban is permanent and appeals will not be successful. In fact, appealing the ban will only serve to further jeopardize your own privacy, as it requires a photo of your face, your private phone number, and a verification number to link to the offending account.
> 
> **So, if you are banned for using this script. Whatever you do, do not appeal it.**

Yeah better losing a account than getting in hitlist with our face and photo roaming all over instagram databases and may be used by instagram for police case against us in future if we are caught abusing it

**Comment by tathastu871** [comment]
Use ig downloader extension. However it is not good at downlaoding over 1000 images

**Comment by anoduck** [comment]
This is not the place for this discussion, but as a word of warning. Not only will you be banned from Instagram, they are now instituting IP blanket bans. Which might be an act of negligence.
![Instagram_flags_IP](https://user-images.githubusercontent.com/9925396/232181208-3501f877-fb23-423d-b770-6ead026b36c4.png)

**Comment by tathastu871** [comment]
This repo should be archived. No longer working

1) login not works -> Instant ban
2) Without login after downloding 10 post it says error 400 401

Instaloader served during its time. Now its time to be archived

**Comment by RazeBerry** [comment]
One way I have briefly circumvented the ban is to login to instagram with my current firefox, retrieve the user-agent, copy the user agent to imitate as if I am using instagram on my firefox. However as soon as I have updated the firefox unintentionally, and the user-agent changed, my account was immediately flagged by Instagram as exhibiting automatic behavior and threatening a ban.

**Comment by anoduck** [comment]
> 

This is how I used to run instaloader, before I became dumb and lazy. Although, I do not believe it will make any difference, because the default user agent is a mozilla firefox user agent. Meow, if you were able to use the cookie you acquired from your browser with the script, that would make some difference. Another flag to use would be the `--abort-on 400`, which would abort the fetch at the first warning shot.

If only there was a means to download the full resolution image without logging in.

**Comment by skmachine** [comment]
it's a shame that instaloader is not working with IG anymore.. I am now using https://rapidapi.com/neotank/api/instagram130/ and they somehow manage to download account json info (I am using /account-info endpoint of this api and it returns basic account info and 12 latest posts in JSON) - and they do not require to supply any cookies or login info - but this is a paid API..

**Comment by anoduck** [comment]
> ... but this is a paid API...

There is the kicker. Paid for APIs are not open source. 

-----

## [How to appeal a ban on Instagram](https://donotpay.com/learn/banned-from-instagram/)

For all of those who were banned on Instagram for using this script, and did not know any better. From what I can gather, you can appeal the ban, and stand a good chance of having it removed. According to Instagram's own bylaws, users are banned from using automated scripts if they perform actions to manipulate profile information or batch liking operations. There is nothing in the bylaws that reference banning for using scripts to fetch images.

**Comment by anoduck** [comment]
@Not4GoodBoyThou GraphQL... cringe...

Performing requests using the Iphone useragent, was at one time a diversionary tactic to prevent being identified as a scraper. This was from back in the day (all three or four years ago) when scraping from a cellphone was not so feasible. Apparently, now, this little tactic will do the exact opposite, and encourage quicker identification for scraping.

**Comment by sa1g** [comment]
> **Describe the bug** I am not blaming anyone, so chill. Facebook has always been strict on anything they didn't code. I do think the issue needs to be addressed, though. It only takes using this script two or three times for your account to be suspended or banned.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. It is installed with pipx `pipx install instaloader`.
> 2. Then I run the script using my login to acquire my friends accounts. ` instaloader -V --no-video-thumbnails --no-captions --dirname-pattern ~/pattern/to/some/path/{profile} --login my_login desired_profile`
> 3. It only takes once or twice until I recieve the "400 bad request" error.
> 4. Then I discover I have to reauthenticate with a photo, but this has not worked in the past, and my account was still banned.
> 
> **Expected behavior**
> 
> I expected to be able to use this account to view my feed without being flagged, banned, or suspended.
> 
> **Error messages and tracebacks** `Fatal error: 400 Bad Request`
> 
> **Instaloader version**
> 
> 4.9.6
> 
> **Additional context** I known it is completely out of control of the developer, but I do not understand why facebook even offers APIs if they are going to ban individuals for using them.
> 
> Maybe slow down the rate at which the requests are made.

good to know. Any suggestion on how to download posts from public accounts (like every 6 hours download only new posts)? I just want to automate my apartment seaching and not waste hours reading instagram posts U_U

**Comment by anoduck** [comment]
@sa1g At the rate you are desiring, you would probably be best using one of the paid for api's that @skmachine was referring to above, and quoted below. He would have to provide you with more information on how to use the rapidapi api. 

> it's a shame that instaloader is not working with IG anymore.. I am now using https://rapidapi.com/neotank/api/instagram130/ and they somehow manage to download account json info (I am using /account-info endpoint of this api and it returns basic account info and 12 latest posts in JSON) - and they do not require to supply any cookies or login info - but this is a paid API..

**Comment by Macerul** [comment]
> > any solution how not to get banned?
> 
> It is Instagram's API that is causing the user's account to get band. As @Arrmm so subtly put it, "It's all about moderation." If you are going to use the script, **just ensure that you do not log in**. If a login is required to access a private account, then an entirely different approach is required. One could either use their web browser and employ one of the many bulk image download extensions, or a new script would need to be created from scratch that employs selenium or pyppeteer.
> 
> The author of the plugin, @instaloader, needs to remove the ability to login from the script altogether, which is what I was hoping would happen when I created this issue. This is primarily because by leaving it in the script, the author is encouraging further banning of innocent users who are unaware of this behavior. Thus, by performing no action, he is unconsciously taking part in their banning by not taking steps to prevent it.

Hi, I'm using Instaloader to try to get the information about my follower like username, bio, number of follower etc, but I'm now reading about all the issues caused by logging in with the script. Am I risking to get banned even tho I'm not downloading pics or posts but just public information about my followers?

**Comment by anoduck** [comment]
@Macerul There is other software better suited for this. https://github.com/Datalux/Osintgram

BUT, this program suggests you create a secondary account for it's use to avoid getting banned.

**Comment by Macerul** [comment]
> @Macerul There is other software better suited for this. https://github.com/Datalux/Osintgram
> 
> BUT, this program suggests you create a secondary account for it's use to avoid getting banned.

Thank you so much, but from what I see it's comman line based. It's for a university project so I was searching for something more 'script-based' so that I can 'play with it', that's why I was hoping I could use Instaloader.

**Comment by anoduck** [comment]
@Macerul I can't make any promises, and am on the borderline of advising against it. As in my case, I lost years of photos that documented some of my happier moments in life, photos that can't be replaced. If you chose to:

1. Ensure to only use it from the university's network.
2. Make as few requests to it as possible.
3. Spread your requests as far as possible from each other.
4. Never use it to download any media.
5. Never use it to view anyone else's profile except those who follow you.
6. Logout of instagram on all other devices, and never use them during your use of the script.
7. If it returns any error whatsoever, abandon use immediately.

If anything happens, refer to the post above and formally appeal the ban in writing to Instagram.

**Comment by Macerul** [comment]
> @Macerul I can't make any promises, and am on the borderline of advising against it. As in my case, I lost years of photos that documented some of my happier moments in life, photos that can't be replaced. If you chose to:
> 
> 1. Ensure to only use it from the university's network.
> 2. Make as few requests to it as possible.
> 3. Spread your requests as far as possible from each other.
> 4. Never use it to download any media.
> 5. Never use it to view anyone else's profile except those who follow you.
> 6. Logout of instagram on all other devices, and never use them during your use of the script.
> 7. If it returns any error whatsoever, abandon use immediately.
> 
> If anything happens, refer to the post above and formally appeal the ban in writing to Instagram.

Thank you so much again for the tips, I was also thinking of using selenium to scrape those info. What I was thinking is... will it block all of my account or just the one I use to scrape, cause I fear it woul block any account associated with my device or idk IP? I really don't understand how does it work

**Comment by anoduck** [comment]
@Macerul It should only block the account you are using for the script. Doing more than this would be considered questionable and aggressive administrative policy, and would allow you to appeal the ban successfully. But to be on the safe side, create an account with a temporary phone number. Use the TextFree app, to acquire a temporary phone number. Instagram is enforcing IP bans, which is why I recommend using your university's network. It is highly unlikely they will ban those. 

I don't quite understand why the bans are occurring myself. They normally occur due to rate limitations, but from what has been documented in this issue report, it appears they are just flat out banning anyone who uses the API for media download.

The problem with Mark Zuckerberg's social media empire is that it assumes all the rights of the user for itself. Anything and everything uploaded or written on those sites belongs to Meta Inc regardless of origin, intent, or investment. This gives the user absolutely zero rights, and does not encourage a trusting relationship with a company who greedily claims all.

**Comment by Macerul** [comment]
> @Macerul It should only block the account you are using for the script. Doing more than this would be considered questionable and aggressive administrative policy, and would allow you to appeal the ban successfully. But to be on the safe side, create an account with a temporary phone number. Use the TextFree app, to acquire a temporary phone number. Instagram is enforcing IP bans, which is why I recommend using your university's network. It is highly unlikely they will ban those.
> 
> I don't quite understand why the bans are occurring myself. They normally occur due to rate limitations, but from what has been documented in this issue report, it appears they are just flat out banning anyone who uses the API for media download.
> 
> The problem with Mark Zuckerberg's social media empire is that it assumes all the rights of the user for itself. Anything and everything uploaded or written on those sites belongs to Meta Inc regardless of origin, intent, or investment. This gives the user absolutely zero rights, and does not encourage a trusting relationship with a company who greedily claims all.
> 
> Just for the info: I was one of the few early adopters of facebook, way back in 2007.

Mh okay so I could try to use a temporary phone number and maybe a temporary email too to create the account? Maybe I could try scrape something like 100 accounts per time and every time I switch the account. Don't know if it could work. But again, thank you so much for the suggestions.

**Comment by anoduck** [comment]
Not 100 per time, but one every 2-3 minutes. If you use shell at all, you might be able to use the following to do this:

```bash
#!/usr/bin/env bash

# Add usernames to this file
PROFILES="$PWD/profiles.txt"

# Change to the instaloader command below:
CMD="instaloader YOUR_COMMAND_HERE"

cat "$PROFILES" | xargs -I % gnuwatch -p -i 73 "$CMD"

```

**Comment by Garettbillk** [comment]
> **Describe the bug** I am not blaming anyone, so chill. Facebook has always been strict on anything they didn't code. I do think the issue needs to be addressed, though. It only takes using this script two or three times for your account to be suspended or banned.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. It is installed with pipx `pipx install instaloader`.
> 2. Then I run the script using my login to acquire my friends accounts. ` instaloader -V --no-video-thumbnails --no-captions --dirname-pattern ~/pattern/to/some/path/{profile} --login my_login desired_profile`
> 3. It only takes once or twice until I recieve the "400 bad request" error.
> 4. Then I discover I have to reauthenticate with a photo, but this has not worked in the past, and my account was still banned.
> 
> **Expected behavior**
> 
> I expected to be able to use this account to view my feed without being flagged, banned, or suspended.
> 
> **Error messages and tracebacks** `Fatal error: 400 Bad Request`
> 
> **Instaloader version**
> 
> 4.9.6
> 
> **Additional context** I known it is completely out of control of the developer, but I do not understand why facebook even offers APIs if they are going to ban individuals for using them.
> 
> Maybe slow down the rate at which the requests are made.

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost account ,message him on telegram his telegram username is https://t.me/Blackhathacker11

**Comment by anoduck** [comment]
@Garettbillk The instructions on how to formally appeal a ban on Instagram are posted in this thread above. No third party is needed to appeal a ban, furthermore, no third party should be trusted to appeal a ban for you.

@Garettbillk May I remind you phishing for newbs on Github is a prime violation of ethical code, and universally abhorred.

**Comment by alwifearzz17** [comment]
> Use ig downloader extension. However it is not good at downlaoding over 1000 images

is the quality good?

**Comment by anoduck** [comment]
> How is it that if we enter Instagram with a phone or a browser and let's say that we quickly look at the posts of a user account with high resolution and go on, it will not be recognized as a robot or inappropriate behaviour? 

For several reasons including rate limitations, application identification (useragents), API access portals, encrypted cookies, and cache obfuscation. 

> Now, if only to be able to download all the images without interruption and since these images are stored in the cache memory of the Instagram program or the browser, is it possible to extract the necessary photos and information from the same data that has been stored? 

Maybe if you teleport yourself back to the 90s, which was once possible. Cache is often not written as whole files. Larger files are broken down into numerous smaller files, smaller files can be combined into larger files, and those files are usually written as binary files for faster loading.

> Isn't this a better solution than using this Python app and sending repeated requests to the Facebook servers to identify us as bots and then block our user account forever? 

See above.

> How does the Instagram program itself receive the information? 

The script uses the API provided to developers by Meta Inc. This API is typically accessed over the HTTP protocol or in some instances websockets.

> So, can't the developer make this Python app based on the same Instagram principles? 

Not with its current approach, and it would completely have to be rewritten from the ground up.

> Well, when we quickly see the posts in the program, it does not identify us as a robot! But downloading with this program identifies us as a robot? How? I don't understand!

With many things in this existence, the answer is both more complicated and more simple than we first understand it to be. The important part is the journey, not the destination.

**Comment by herei0147** [comment]
Like thousands of other Instagram users, I've been observing this farce for a week. I've searched the web, read through every bit of information available, and tried to find or get in touch with any human being who can truly help. However, I'm beginning to realise that this is not going to be an easy problem to solve. I was directed to Marieconsultancyoz@gmail com. On Instagram, she goes as Marie_consultancy. By successfully recovering my locked Instagram and Facebook account, she was able to provide me with appropriate and sincere services; you can get in touch with her as well.

**Comment by anoduck** [comment]
@herei0147 Please do not phish on GitHub, it is unquestionably in poor taste.

The only means by which a third party could aid another in removing a ban from an account, is if that individual was a properly licensed attorney.
