### ISSUE TITLE
instaloader not downloading every post of a profile?

### ISSUE THREAD

**Issue by arv6** [instaloader/instaloader#1938]
hi, i've been using instaloader for a while to download posts from a profile i follow, the problem is when i want to download every media from that profile (posts, videos, reels, igtv etc) some specific posts are always left out. i don't know why that happens, i thought they were instagram tv posts but even including that command they don't get saved. i know for a fact they're named reels on instagram, but i'm not sure if this option exists here. is there a way to actually download every media from a profile without nothing left out so that i don't have to find and download them manually? thanks.

**Comment by Showmaster3000** [comment]
Difficult to say what is missing, but possibly some reels, because instaloader doesn't support downloading them. Some reels are loaded cause they behave like posts, others are "real" reels which are potentially missing.
See #812, but issue is currently closed.
