### ISSUE TITLE
Download Top X Photos of User

### ISSUE THREAD

**Issue by eyazilikaya** [instaloader/instaloader#194]
**Provide us a use case of the feature**
If we can set a parameter for top photos and download X of them that would be a great feature. This parameter can be Engagement Rate, let's say a user has 10k followers and user has 500 media, if we sort all media by their engagement rate(likes+comments of media/follower count) and only download top 100 or top %10 of media, we can just eliminate downloading low engagement media.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by aandergr** [comment]
This should better be implemented in a separate script rather than as an Instaloader feature. For the sake of documentation / examples, we can then publish it here: https://instaloader.github.io/codesnippets.html

**Comment by aandergr** [comment]
This is an approach of a code snippet doing what you want:

```python
from itertools import islice
from math import ceil

from instaloader import Instaloader, Profile

PROFILE = ...        # profile to download from
X_percentage = 10    # percentage of posts that should be downloaded

L = Instaloader()

profile = Profile.from_username(L.context, PROFILE)
posts_sorted_by_likes = sorted(profile.get_posts(), key = lambda p: p.likes + p.comments)

for post in islice(posts_sorted_by_likes, ceil(profile.mediacount * X_percentage / 100)):
    L.download_post(post, PROFILE)
```

**Comment by RualLozun** [comment]
> 
> 
> This is an approach of a code snippet doing what you want:
> 
> ```python
> from itertools import islice
> from math import ceil
> 
> from instaloader import Instaloader, Profile
> 
> PROFILE = ...        # profile to download from
> X_percentage = 10    # percentage of posts that should be downloaded
> 
> L = Instaloader()
> 
> profile = Profile.from_username(L.context, PROFILE)
> posts_sorted_by_likes = sorted(profile.get_posts(), key = lambda p: p.likes + p.comments)
> 
> for post in islice(posts_sorted_by_likes, ceil(profile.mediacount * X_percentage / 100)):
>     L.download_post(post, PROFILE)
> ```

It seems like this script downloads the least liked posts instead of the most liked posts... I made it work changing this line, thought it could be useful to somebody to know this:
`posts_sorted_by_likes = sorted(profile.get_posts(), key = lambda p: p.likes + p.comments, reverse = True)`

**Comment by aliasgar1530** [comment]
im getting this error while using script 

`Traceback (most recent call last):
  File "194_top_x_of_user.py", line 6, in <module>
    PROFILE = usernaname       # profile to download from
NameError: name 'SIGRIDIG' is not defined`
