### ISSUE TITLE
Fetching Post metadata failed.

### ISSUE THREAD

**Issue by pelirodri** [instaloader/instaloader#1940]
Certain short codes trigger said error when trying to initialize a Post object with them.

This is the line triggering the error:

`post = instaloader.Post.from_shortcode(insta_loader.context, short_code)`

It works just fine for most short codes, but I have already encountered two that cause this issue, namely “CnojlJ2LR2w” and “CqPsfdCJDjR.” Meanwhile, if I pass the links with those codes to services for downloading Instagram posts, they work just fine.

Version 4.9.6.

Code sample that triggers the error:

```
import instaloader

insta_loader = instaloader.Instaloader()
short_code = "CnojlJ2LR2w"
instaloader.Post.from_shortcode(insta_loader.context, short_code)
```

Which gives this:

> Traceback (most recent call last):
>   File "/Users/pelirodri/test.py", line 5, in <module>
>     instaloader.Post.from_shortcode(insta_loader.context, short_code)
>   File "/opt/homebrew/lib/python3.11/site-packages/instaloader/structures.py", line 88, in from_shortcode
>     post._node = post._full_metadata
>                  ^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/instaloader/structures.py", line 205, in _full_metadata
>     self._obtain_metadata()
>   File "/opt/homebrew/lib/python3.11/site-packages/instaloader/structures.py", line 198, in _obtain_metadata
>     raise BadResponseException("Fetching Post metadata failed.")
> instaloader.exceptions.BadResponseException: Fetching Post metadata failed.

**Comment by pelirodri** [comment]
Just found a third one, for what it’s worth: CqgIlrqIQje.

**Comment by pelirodri** [comment]
It would actually seem that there are certain profiles whose entire post collections have this problem, for some reason, as far as I can tell. They are obviously not private or anything and, as mentioned before, typical downloading services still appear to work just the same with them, but this library keeps failing.

**Comment by HarutaLuna** [comment]
same this shortcode can't be downloaded

CpXR0o5BasasM0

**Comment by Esoppant** [comment]
Can confirm that same thing's happening with the instaloader exe file. the command "instaloader -- -postID" works with some posts and not with others right now. Seems to be a profile specific thing (though they are not private profiles). Logging in doesn't help either; gives the "JSON Query to graphql/query: HTTP error code 401" error.

**Comment by aandergr** [comment]
Downloading the posts of both valid mentioned shortcodes works for me, both with 4.9.6 and 4.10a1 when logged in.

Both posts cannot be accessed anonymously (neither in the browser).

> same this shortcode can't be downloaded
> 
> CpXR0o5BasasM0

This is not valid.

**Comment by pelirodri** [comment]
> Downloading the posts of both valid mentioned shortcodes works for me, both with 4.9.6 and 4.10a1 when logged in.
> 
> 
> 
> Both posts cannot be accessed anonymously (neither in the browser).

I was not aware there were special profiles which required logging in to be viewed… Either way, such an error message doesn't even point you in the right direction; couldn't it be improved somehow?

**Comment by stevenkader** [comment]
I came across this today and see that one reason is that the profile is age restricted so will only work when logged in.

**Comment by rishikeshshede** [comment]
### Soved ✅
I was facing the same issue today.

### Cause

For me the issue was happening because the url i was getting from instagram (when i try to share the post and copy url) was something like this: https://www.instagram.com/share/BA-Zo3dPT0, it had `share` keyword in it, which means it is a redirect url and not the actual url of the post.

### Solution

When you open this url in the browser, you get he real url of the post which you can use to download the post successfully.

---

**Code:**
```python
import requests

def get_real_instagram_url(share_url):
    try:
        response = requests.get(share_url, allow_redirects=True)
        return response.url  # This is the real post URL
    except Exception as e:
        print(f"Error fetching real Instagram URL: {e}")
        return None

# Example
share_url = "https://www.instagram.com/share/BA-Zo3dPT0"
real_url = get_real_instagram_url(share_url)

if real_url:
    print(f"Real Instagram URL: {real_url}")
else:
    print("Failed to retrieve real URL.")
```

**Comment by Godly-Avenger** [comment]
Getting this issue as well. Can't seem to download restricted posts/reels from my script or via the command line (getting "can't find metadata"). I am using the "real URL" of the post.

**Comment by himanshuu-dev** [comment]
happened with me, some content is age restricted


<img width="1550" height="847" alt="Image" src="https://github.com/user-attachments/assets/994b8d5e-b79c-46e6-b433-617d201663b2" />
