### ISSUE TITLE
Problems with --comments option in Instaloader command line: JSON Query to graphql/query: HTTP error code 401.

### ISSUE THREAD

**Issue by fussballlinguist** [instaloader/instaloader#1945]
**Describe the bug**
I cannot download comments anymore.

**To Reproduce**
Instaloader command line v 4.9.6 with the following command:
`instaloader --comments tagesschau`
It does download posts and captions, but not the comments.

**Expected behavior**
For each post, a JSON file containing the comments should be created.

**Error messages and tracebacks**
`[1/1] Downloading profile tagesschau
tagesschau/2014-06-19_15-42-08_UTC_profile_pic.jpg already exists
Retrieving posts from profile tagesschau.
Resuming from tagesschau/iterator_GZM60Sqo.json.xz.
[    2/19965] tagesschau/2023-04-11_11-04-09_UTC_1.jpg exists tagesschau/2023-04-11_11-04-09_UTC_2.jpg exists tagesschau/2023-04-11_11-04-09_UTC_3.jpg exists tagesschau/2023-04-11_11-04-09_UTC_4.jpg exists tagesschau/2023-04-11_11-04-09_UTC_5.jpg exists tagesschau/2023-04-11_11-04-09_UTC_6.jpg exists tagesschau/2023-04-11_11-04-09_UTC_7.jpg exists [Die US-Dokumente, die auf Twi…] unchanged JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Download <Post Cq5L1YnoHD_> of tagesschau: JSON Query to graphql/query: HTTP error code 401.
`

**Instaloader version**
4.9.6

**Additional context**

**Comment by akafanfan** [comment]
**JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Fatal error: JSON Query to graphql/query: HTTP error code 401.**

how to solve this problem

**Comment by akafanfan** [comment]
> 

D:\Desktop> instaloader --version
4.9.6

**Comment by akafanfan** [comment]
i found a way to fixed it
https://github.com/instaloader/instaloader/issues/1947#issuecomment-1523518467

**Comment by zero0n3** [comment]
Hi everyone. Watch out because it seems that Instagram has figured out how to block downloads made by instaloader regardless of IP or account.
Having banned my home IP, I tried to connect via a mobile hotspot, with a different IP and a different operator. Same result: 401 error.

And I don't use session files or logins to download. And I know for sure that the photo is public and does not need to login to be seen.

So watch out
