### ISSUE TITLE
NameError("name 'Profile' is not defined",)

### ISSUE THREAD

**Issue by cristianCarrerasCastillo** [instaloader/instaloader#195]
```
import instaloader

user="test"
L = instaloader.Instaloader(download_video_thumbnails=False,download_videos=False,download_comments=False)
profile = Profile.from_username(L.context,user)#<<---- Profile. ....... error

for post in profile.get_followees():
    # post is an instance of instaloader.Post
    L.download_post(post, target=user')
```

When compiling this program, I get this error message. I do not understand how I have to define Profile
**NameError("name 'Profile' is not defined",)**

**Comment by aandergr** [comment]
If you import Instaloader with `import instaloader`, which you do in your code listing, you have to use `instaloader.Profile` rather than `Profile`.
