### ISSUE TITLE
when i do --help this error comes

### ISSUE THREAD

**Issue by penda556** [instaloader/instaloader#1952]
![image](https://user-images.githubusercontent.com/99551485/233790410-4b90a425-6e5f-4dfc-aa12-0c55c8368275.png)

and this ins.exe comes from this youtube vid i watched 
https://youtu.be/RN1TKMO9aUY

**Comment by Showmaster3000** [comment]
Didn't watch the video complete. But "ins" seems a shortcut by the user who created the video cause of lazyness.
writing the complete name `instaloader` should work.
