### ISSUE TITLE
Locales other than English have a problem with Last-Modified header parsing

### ISSUE THREAD

**Issue by jggithub2017** [instaloader/instaloader#1956]
https://github.com/instaloader/instaloader/blob/cc8c9ff88323716f0e25a958d6673b73646991f4/instaloader/instaloader.py#L529

Under Linux, if someone uses other locale settings than English, they are not able to parse the last modified header from http. This is due the `%a` and `%b` depends on the locale settings [Python strptime documents](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior).

**Comment by aandergr** [comment]
Similar to #1814, #1825.

> In https://docs.python.org/3/library/locale.html#background-details-hints-tips-and-caveats the documentation says
> 
> > Initially, when a program is started, the locale is the `C` locale, no matter what the user’s preferred locale is.
> 
> Hence, strptime should work correctly in parsing the weekday names as required per HTTP protocol, regardless of the language settings.
> 

You need to explicitly use `locale.setlocale()` for the parsing to fail.
