### ISSUE TITLE
Use browser-cookie3 library to import cookies from browser

### ISSUE THREAD

**Issue by SayanthD** [instaloader/instaloader#1958]
**Provide us a use case of the feature**
Since the login is broken (for now I hope), the best method to login is by loading session generated from Firefox. With the use of external library we can solve the problem where the user is having other browsers namely Chrome and Edge

**Describe the solution you'd like**
Use the library in the import cookie script and write to the session file or integrate it as a flag `--cookies-from-browser=<browser_name>` where it will fetch the cookies and use temporarily during runtime.
Homepage: https://github.com/borisbabic/browser_cookie3
License: LGPL-3.0 license

**Describe alternatives you've considered**
I don't have an alternative. Cookies from chrome are encrypted, so it requires some other library to take on the decryption task. Using the aforementioned library will reduce the work and is working for wide variety of browsers and OS.

**If the feature request is accepted, would you be willing to submit a pull request?**
Maybe

**Additional context**
.

**Comment by Showmaster3000** [comment]
have a look at #1780 where @OMGhozlan proposed a script for importing cookies from Chrome.

**Comment by SayanthD** [comment]
> have a look at #1780 where @OMGhozlan proposed a script for importing cookies from Chrome.

Yeah, that's working, although I had to change the script's default path with my profile path. There was no reason given when that PR was closed.
