### ISSUE TITLE
KeyError: 'date_utc' with downloading stories with custom dir pattern

### ISSUE THREAD

**Issue by Not4GoodBoyThou** [instaloader/instaloader#1959]
**Describe the bug**
I tried to download only stories of a profile and it resulted with this error.
`--dirname-pattern` was set to custom "downloads/{profile}/{date_utc:%Y-%m-%d}"

**To Reproduce**
`--login=username
--no-iphone
--fast-update
--latest-stamps
--no-compress-json
--dirname-pattern=downloads/{profile}/{date_utc:%Y-%m-%d}
--sanitize-paths
--no-posts
--no-video-thumbnails
--stories
profile_name`

**Expected behavior**
Successfully download all storyitems in the preferred directory
When it is 28th April
`downloads/profile_name/2023-04-28/default_filename`

**Error messages and tracebacks**
```Traceback (most recent call last):
  File "c:\Users\PC\Desktop\Work\instaloader\instaloader.py", line 6, in <module>
    main()
  File "c:\Users\PC\Desktop\Work\instaloader\instaloader\__main__.py", line 470, in main
    _main(loader,
  File "c:\Users\PC\Desktop\Work\instaloader\instaloader\__main__.py", line 219, in _main
    instaloader.download_profiles(profiles,
  File "c:\Users\PC\Desktop\Work\instaloader\instaloader\instaloader.py", line 1450, in download_profiles
    json_filename = os.path.join(self.dirname_pattern.format(profile=profile_name,
KeyError: 'date_utc'
```

**Instaloader version**
4.9.6 and 4.10b1

**Additional context**
The profile picture was downloaded correctly in the given dirname pattern
`downloads\profile_name\2022-11-14\2022-11-14_03-05-56_UTC_profile_pic.jpg`

**Comment by Showmaster3000** [comment]
`{date_utc}` is not available for `--dirname-pattern`.
I think you can instead use `--dirname-pattern=downloads/{profile} --filename-pattern={date_utc:%Y-%m-%d}/{date_utc}_UTC` to achieve the format you want to have.
See manual for details: https://instaloader.github.io/basic-usage.html#filename-specification

**Comment by Not4GoodBoyThou** [comment]
> I think you can instead use `--dirname-pattern=downloads/{profile} --filename-pattern={date_utc:%Y-%m-%d}/{date_utc}_UTC` to achieve the format you want to have.

Thats it! @Showmaster3000 Thanks so much, this was want I wanted :)
Issue fixed closing now
