### ISSUE TITLE
:stories: JSON Query to graphql/query: HTTP error code 502

### ISSUE THREAD

**Issue by gregoryswayyy123** [instaloader/instaloader#196]
**Describe the bug**
Unable to run :stories for 3 days.

**To Reproduce**
instaloader -l @AccountName --password ~AccountPassword :stories --no-compress-json --dirname-pattern={profile}

**Expected behavior**
I have been running the same command for about 20 days consecutively and download all the storie s

**Error messages and tracebacks**
Retrieving all visible stories...
JSON Query to graphql/query: HTTP error code 502. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 502. [retrying; skip with ^C]
:stories: JSON Query to graphql/query: HTTP error code 502.
Saved session to /tmp/.instaloader-me/session-@swayyydata.
Errors occured:
:stories: JSON Query to graphql/query: HTTP error code 502.

**Instaloader version**
4.1.1

**Additional context**

**Comment by Thammus** [comment]
Hi,
http error codes 5XX indicate an error on the server side. So this does not seem to be a problem with Instaloader. We test the ":stories" target daily without the occurrence of any error.
Are you able to see the stories in your browser?

**Comment by aandergr** [comment]
I am closing this since this issue is inactive and on first glance it seems a problem on server's side. Please feel free to reopen this issue if there are any updates.
