### ISSUE TITLE
location

### ISSUE THREAD

**Issue by yakushevhk** [instaloader/instaloader#1960]
<img width="778" alt="Screenshot 2023-04-29 at 21 44 06" src="https://user-images.githubusercontent.com/78789455/235313997-c58b0bf0-48b0-4077-8c0b-42b3c83dea3e.png">
Hello
I cant get latest photos (location)

**Comment by Showmaster3000** [comment]
missing essential information: instaloader version.
also 5xx error codes are server side, so this can be a temporary thing.
