### ISSUE TITLE
I dont know why, but with admin permission, the video is downloaded in system32!

### ISSUE THREAD

**Issue by LineCatOvO** [instaloader/instaloader#1961]
Maybe set the default download location always at least be users folder?

**Comment by LineCatOvO** [comment]
By the way, version is 4.9.6

**Comment by JunedKhan101** [comment]
I think it's because it downloads the files in the folder you're already in when you open the terminal.
For Administrator its C:\Windows\System32

Or are you saying that even after being in the right directory or path it downloads it into the System32 folder?

**Comment by LineCatOvO** [comment]
> I think it's because it downloads the files in the folder you're already in when you open the terminal.
> For Administrator its C:\Windows\System32
> 
> Or are you saying that even after being in the right directory or path it downloads it into the System32 folder?

Oh, I think you're right, I forget the cmd folder is system32, so the download folder is decided by it... well that's my fault. Thanks.

**Comment by JunedKhan101** [comment]
Glad to help! 🙌
