### ISSUE TITLE
Private but not followed. 

### ISSUE THREAD

**Issue by Howardjohnson1** [instaloader/instaloader#1968]
Your question here... i have followed all the step but in the end its show "Private but not followed"

can you plz help or or show me the step without follow that person and get all the photos of an insta private account

**Comment by Showmaster3000** [comment]
This is not possible.
You have to be an approved follower of a private profile to access and download it.

**Comment by Howardjohnson1** [comment]
Hi Thanks for your Reply
Its Possible its shows the same what ive told u
okay, its not possible without following or being follow to the user?

**Comment by Showmaster3000** [comment]
As I said before: You have to be an approved follower of a private profile to access and download it.
Anyway you can access and download a private profile if your are a approved follower and use the approved account as login.
