### ISSUE TITLE
How can handle multiple account??

### ISSUE THREAD

**Issue by nebula0225** [instaloader/instaloader#1969]
As a tittle
How can handle multiple account ?
There are login with session id?
How can set useragent, device info, locale info?

**Comment by Showmaster3000** [comment]
How about reading the manual first? https://instaloader.github.io/basic-usage.html
Most of your questions are answered there.
Please be more detailed with your questions what you want to do. Also there is a bunch of already answerd questions in the issuses history - just use the search function.

**Comment by nebula0225** [comment]
I solved that problem
Thx
