### ISSUE TITLE
why we cant download public account stories without login, is this restricted by instaloader or instagram

### ISSUE THREAD

**Issue by sarvagya1277** [instaloader/instaloader#1972]
why we cant download public account stories without login, is this restricted by instaloader or instagram

**Comment by dr-pandit-69** [comment]
probably a limitation by instagram to prevent spam bots

**Comment by Showmaster3000** [comment]
as already described in [#1929](https://github.com/instaloader/instaloader/issues/1929#issuecomment-1491051623), stories ar restricted by Instagram.

> Downloading stories generally requires to login. Try to see a story on Instagram in browser - its not possible.
Storysaver and all other pages where you can download stories are using either the official API or just use dummy accounts in background.
