### ISSUE TITLE
Instaloader not working on Ubuntu 23.04

### ISSUE THREAD

**Issue by kdumps17** [instaloader/instaloader#1973]
When I run instaloader, I get following error,

$ instaloader -V --no-captions --no-metadata-json -s --highlights official_niharica_raizada
Traceback (most recent call last):
  File "/home/ashu/.local/bin/instaloader", line 5, in <module>
    from instaloader.__main__ import main
ModuleNotFoundError: No module named 'instaloader'

When I try to check the version, again this happens,

$ instaloader --version
Traceback (most recent call last):
  File "/home/ashu/.local/bin/instaloader", line 5, in <module>
    from instaloader.__main__ import main
ModuleNotFoundError: No module named 'instaloader'

Just to confirm I have version instaloader-4.9.6 installed.

**Comment by nebula0225** [comment]
That error is not problem with os and instaloader
Check document
