### ISSUE TITLE
Stop downloading after 12 pictures

### ISSUE THREAD

**Issue by VSP-HungPV** [instaloader/instaloader#1978]
Instaloader  - Python 3.8 - Windows 10
Script stop downloading after 12 pictures and show this error

JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]

Errors or warnings occurred:
JSON Query to graphql/query: HTTP error code 401.

**Comment by Not4GoodBoyThou** [comment]
This usually happens when you aren't logged in with Instaloader. 
Check this out for getting session file https://instaloader.github.io/troubleshooting.html#login-error
