### ISSUE TITLE
python download_post KeyError: 'date_utc'

### ISSUE THREAD

**Issue by wAOndering** [instaloader/instaloader#1981]
**Describe the bug**
I got a KeyError: 'date_utc' while trying to use the download_post function
In [4]: instaloader.__version__
Out[4]: '4.9.6'

**To Reproduce**
   ...: loader.download_post(url, target=r'C:\Users\Windows\Downloads\lo.mp4')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-79e8d411fe4c> in <cell line: 2>()
      1 url = "https://www.instagram.com/p/CrJd3OYPBmz"
----> 2 loader.download_post(url, target=r'C:\Users\Windows\Downloads\lo.mp4')

~\Anaconda3\envs\python310\lib\site-packages\instaloader\instaloader.py in download_post(self, post, target)
    695
    696         dirname = _PostPathFormatter(post, self.sanitize_paths).format(self.dirname_pattern, target=target)
--> 697         filename_template = os.path.join(dirname, self.format_filename(post, target=target))
    698         filename = self.__prepare_filename(filename_template, lambda: post.url)
    699

~\Anaconda3\envs\python310\lib\site-packages\instaloader\instaloader.py in format_filename(self, item, target)
    662
    663         .. versionadded:: 4.1"""
--> 664         return _PostPathFormatter(item, self.sanitize_paths).format(self.filename_pattern, target=target)
    665
    666     def download_post(self, post: Post, target: Union[str, Path]) -> bool:

~\Anaconda3\envs\python310\lib\string.py in format(self, format_string, *args, **kwargs)
    159 class Formatter:
    160     def format(self, format_string, /, *args, **kwargs):
--> 161         return self.vformat(format_string, args, kwargs)
    162
    163     def vformat(self, format_string, args, kwargs):

~\Anaconda3\envs\python310\lib\string.py in vformat(self, format_string, args, kwargs)
    163     def vformat(self, format_string, args, kwargs):
    164         used_args = set()
--> 165         result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
    166         self.check_unused_args(used_args, args, kwargs)
    167         return result

~\Anaconda3\envs\python310\lib\string.py in _vformat(self, format_string, args, kwargs, used_args, recursion_depth, auto_arg_index)
    203                 # given the field_name, find the object it references
    204                 #  and the argument it came from
--> 205                 obj, arg_used = self.get_field(field_name, args, kwargs)
    206                 used_args.add(arg_used)
    207

~\Anaconda3\envs\python310\lib\string.py in get_field(self, field_name, args, kwargs)
    268         first, rest = _string.formatter_field_name_split(field_name)
    269
--> 270         obj = self.get_value(first, args, kwargs)
    271
    272         # loop through the rest of the field_name, doing

~\Anaconda3\envs\python310\lib\site-packages\instaloader\instaloader.py in get_value(self, key, args, kwargs)
    147
    148     def get_value(self, key, args, kwargs):
--> 149         ret = super().get_value(key, args, kwargs)
    150         if not isinstance(ret, str):
    151             return ret

~\Anaconda3\envs\python310\lib\site-packages\instaloader\instaloader.py in get_value(self, key, args, kwargs)
    124         if hasattr(self._item, key):
    125             return getattr(self._item, key)
--> 126         return super().get_value(key, args, kwargs)
    127
    128     def format_field(self, value, format_spec):

~\Anaconda3\envs\python310\lib\string.py in get_value(self, key, args, kwargs)
    225             return args[key]
    226         else:
--> 227             return kwargs[key]
    228
    229

KeyError: 'date_utc'

**Comment by aandergr** [comment]
Please look at the documentation. `download_post` expects a `Post` instance, not a URL string.

https://instaloader.github.io/module/instaloader.html#instaloader.Instaloader.download_post
