### ISSUE TITLE
Issue 401 by Ubuntu Server 

### ISSUE THREAD

**Issue by PandorasBoxTool** [instaloader/instaloader#1983]
I have already tried with an Amazon AWS EC2 server and also with an IONOS dedicated root server no matter what I do I get the error code 401 but if I also install VirtualBox Ubuntu Server it works therefore the question what is the reason or which server or provider I can use best?

**Comment by aandergr** [comment]
Closing these as duplicate of #2011 – no need to track the 401 problem in several different issue threads.
