### ISSUE TITLE
PLS Add Proxy 

### ISSUE THREAD

**Issue by PandorasBoxTool** [instaloader/instaloader#1985]
Please add the possibility to finally use a proxy server

**Comment by Showmaster3000** [comment]
As described in [comments of #1597](https://github.com/instaloader/instaloader/issues/1597#issuecomment-1504669115) you can already use the proxy feature:
> It follows the widely used convention of having proxies set via environment variables `HTTPS_PROXY`.
> 
> https://requests.readthedocs.io/en/latest/user/advanced/#proxies

**Comment by nebula0225** [comment]
change os setting on your code
