### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by LucaRocco** [instaloader/instaloader#1989]
**Describe the bug**

During comments iteration i got a weird exception `'NoneType' object is not subscriptable`. Is there maybe any instagram changes or am i doing something wrong? You can find the stacktrace below.

**To Reproduce**

I got this error while iterating posts comments a couple of times. The error is random and I can't say a precise way to reproduce it.

**Error messages and tracebacks**

```text
...
File "/usr/local/lib/python3.9/site-packages/instaloader/nodeiterator.py",line 141, in __next_
    query_response = self._query(self._data['page_info'] ['end_cursor'])
File "/usr/local/lib/python3.9/site-packages/instaloader/nodeiterator.py",line 102, in query_
    data = self. _edge extractor (
File "/usr/local/lib/python3.9/site-packages/instaloader/structures.py", line 569, in <lambda>
    lambda d: d['data' ] ['shortcode_media'] ['edge_media_to_parent_comment'],
TypeError: 'NoneType' object is not subscriptable
```

**Instaloader version**
I am running the 4.9.6

Hope it helps.

**Comment by Physsikal** [comment]
Can you share the line of code (or function) that is generating this error?

**Comment by LucaRocco** [comment]
Hi @Physsikal, thanks for your answer, below you can find the code that generate the error

I am trying to insert all the comments and their answers in the same list with this simple code

```python
for comment in post.get_comments():
    comments.append(comment_to_dict(comment, post))
    for answer in comment.answers:
        comments.append(comment_to_dict(answer, post, parent_id = comment.id))
```

Thanks for your help

**Comment by aandergr** [comment]
post.get_comments() works for me. Is there a specific post where this error happens?
