### ISSUE TITLE
Number of shares

### ISSUE THREAD

**Issue by ihabpalamino** [instaloader/instaloader#1990]
hello i would like to ask i want to get the number of shares in instagram using instaloader how either for reels or a picture how can i get this?

**Comment by Physsikal** [comment]
Share counts are not being displayed by Instagram anymore. Instaloader cannot pull this data anymore since it will display an error:
`JSON Query to graphql/query: HTTP error code 401.`

**Comment by zero0n3** [comment]
Hi everyone. Watch out because it seems that Instagram has figured out how to block downloads made by instaloader regardless of IP or account.
Having banned my home IP, I tried to connect via a mobile hotspot, with a different IP and a different operator. Same result: 401 error.

And I don't use session files or logins to download. And I know for sure that the photo is public and does not need to login to be seen.

So watch out

**Comment by Physsikal** [comment]
> Hi everyone. Watch out because it seems that Instagram has figured out how to block downloads made by instaloader regardless of IP or account. Having banned my home IP, I tried to connect via a mobile hotspot, with a different IP and a different operator. Same result: 401 error.
> 
> And I don't use session files or logins to download. And I know for sure that the photo is public and does not need to login to be seen.
> 
> So watch out

Could you share the code you're trying to use? Maybe there's an error in the way you're implementing it!

**Comment by awilliansd** [comment]
![image](https://github.com/instaloader/instaloader/assets/4139802/8bbf205a-bd9e-46d9-b977-23490f4df6ad)

Now, we need to login and we're at risk to get a ban

**Comment by Physsikal** [comment]
> ![image](https://user-images.githubusercontent.com/4139802/241778919-8bbf205a-bd9e-46d9-b977-23490f4df6ad.png)
> 
> Now, we need to login and we're at risk to get a ban

It depends what you need to log in for. If you want to get a list of the followers of a user account, then yes, you do need to log in. However, if you just want to download reels then I am pretty sure that you can just do it without having to log in.

**Comment by awilliansd** [comment]
> > ![image](https://user-images.githubusercontent.com/4139802/241778919-8bbf205a-bd9e-46d9-b977-23490f4df6ad.png)
> > Now, we need to login and we're at risk to get a ban
> 
> It depends what you need to log in for. If you want to get a list of the followers of a user account, then yes, you do need to log in. However, if you just want to download reels then I am pretty sure that you can just do it without having to log in.

![image](https://github.com/instaloader/instaloader/assets/4139802/164889a9-ae98-4e6f-be32-67e5e5293314)

No, even only photos feed, now, login is required

**Comment by Physsikal** [comment]
> > > ![image](https://user-images.githubusercontent.com/4139802/241778919-8bbf205a-bd9e-46d9-b977-23490f4df6ad.png)
> > > Now, we need to login and we're at risk to get a ban
> > 
> > 
> > It depends what you need to log in for. If you want to get a list of the followers of a user account, then yes, you do need to log in. However, if you just want to download reels then I am pretty sure that you can just do it without having to log in.
> 
> ![image](https://user-images.githubusercontent.com/4139802/241779523-164889a9-ae98-4e6f-be32-67e5e5293314.png)
> 
> No, even only photos feed, now, login is required

Yup, just checked it. I am afraid that at this point we'll have to log in if we want to grab content from Instagram. What I would recommend in this case is just to use burner accounts that are not linked to the same email as the one you're using.

**Comment by zero0n3** [comment]
> 

`instaloader --quiet --no-captions --no-metadata-json --dirname-pattern="{profile}" --filename-pattern="{profile} - {shortcode}" -- -Cs04fmGRQS4`

**Comment by ekalin** [comment]
> No, even only photos feed, now, login is required

That can happen even in the browser and without using instaloader: if you try to browser without logging in, eventually it will start asking you to login.

**Comment by awilliansd** [comment]
> > No, even only photos feed, now, login is required
> 
> That can happen even in the browser and without using instaloader: if you try to browser without logging in, eventually it will start asking you to login.

no, I only use in cmd

**Comment by zero0n3** [comment]
It would seem as if now, in order to see any profile on Instagram, you have to be logged in regardless. Even if the profile is public, you still need to be logged in to view it.

**Comment by awilliansd** [comment]
maybe, i can be banned now or change password everytime
