### ISSUE TITLE
Too many request

### ISSUE THREAD

**Issue by JohannesHelleve** [instaloader/instaloader#1991]
Hi, i do not understand why i am getting this error. I am quite new to coding so any help would be apriciated. Now mater what i do i always get the Too many request errror. I am using a VPN to hide my IP, do i need proxies as well? 
Here is the code: 
```
import instaloader
import config

# Get the most liked photo in Oslo in the last day
client = instaloader.Instaloader()
client.login(config.username, config.password )

# Set the rate controller to sleep for 1 second between requests
client.set_rate_controller(instaloader.RateController(sleep_time=1))

# Get the most liked photo in Oslo in the last day
photos = client.get_geotagged_media("59.912898,10.752222", max_likes=1)

# Download the photo
photo = photos[0]
client.download_photo(photo, "most_liked_photo_in_oslo.jpg")
´´´

**Comment by GijsSi** [comment]
Hi there,

I am not 100% sure but, since you are using a vpn your IP will be from a datacenter. Chances are that these will be blocked by instagram. I think your safest bet will be residential proxies. It should work after that.

**Comment by nebula0225** [comment]
I think your VPN is work for Instagram first time
but it not changed ip so it banned

**Comment by JohannesHelleve** [comment]
Yes, you were right, i used Nord VPN and they probably had it on some watchlist. Just using my own wifi worked perfet, thanks!

**Comment by aandergr** [comment]
> 

This looks like fantasy code, or written by ChatGPT. The Instaloader class does not provide methods `set_rate_controller()`, `get_geotagged_media()` or `download_photo()`, the `RateController` does not have a `sleep_time` parameter. This is for sure not the code that you executed.
