### ISSUE TITLE
Download TopSearchResults Content

### ISSUE THREAD

**Issue by JohannesHelleve** [instaloader/instaloader#1995]
Is it possible to download pictures/videos/etc. from the TopSearchResults class? And if possible, how so?

**Comment by aandergr** [comment]
[TopSearchResults](https://instaloader.github.io/module/structures.html#topsearchresults) does not return pictures/videos/etc., instead it provides methods to access the search results as profiles ([Profile](https://instaloader.github.io/module/structures.html#instaloader.Profile)), locations ([PostLocation](https://instaloader.github.io/module/structures.html#instaloader.PostLocation)) and hashtags ([Hashtag](https://instaloader.github.io/module/structures.html#instaloader.Hashtag)).
