### ISSUE TITLE
Warning: Restricted account due to automated process detected

### ISSUE THREAD

**Issue by cyberfunk** [instaloader/instaloader#1997]
Instaloader failed to download all images and after almost 100 photos began to report Error 400 bad request. My instagram account was logged out and I received a message saying my account might be restricted permanently due to automated activity. Do I need to limit the number of downloads in one session or abandon Instaloader altogether now that my account has been flagged?

**Comment by ekalin** [comment]
If this is a real account that you don't want to lose, don't use instaloader.

It's better to use a throw-away account just for scraping, and if you lose the account, you can just create another. When an account is flagged it's better to stop using this account on instaloader for some days.

**Comment by cyberfunk** [comment]
Ok thanks. I was also looking at liniting downloads to a lesser ammout of images but can't make th esuggested script work. How would I execute this script in th econtext of macos terminal and instaloader? I did this and it did not work:

instaloader --login=my_profile target_profile

from datetime import datetime
from itertools import dropwhile, takewhile

import instaloader

L = instaloader.Instaloader()

posts = instaloader.Profile.vector_garage(L.context, "instagram").get_posts()

SINCE = datetime(2022, 24, 2)
UNTIL = datetime(2022, 1, 1)

for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
    print(post.date)
    L.download_post(post, "instagram")

**Comment by Garettbillk** [comment]
> Instaloader failed to download all images and after almost 100 photos began to report Error 400 bad request. My instagram account was logged out and I received a message saying my account might be restricted permanently due to automated activity. Do I need to limit the number of downloads in one session or abandon Instaloader altogether now that my account has been flagged?
Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost account ,message him on telegram his telegram username is https://t.me/Blackhathacker11
