### ISSUE TITLE
JSON Query to graphql/query: HTTP error code 401. Also when iam trying to donwload a private account photos this isi hwat ima getting rivate but not followed

### ISSUE THREAD

**Issue by hacker07UK** [instaloader/instaloader#2000]
Your question here...
JSON Query to graphql/query: HTTP error code 401. 

Also when I am trying to download private account photos this is what I am  getting "private but not followed"

if a private user is being followed then he can download directly from instagram right whats the point in coming here ?

**Comment by iansquenet** [comment]
Same issue. How do I login with Firefox cookies?

**Comment by aandergr** [comment]
Closing these as duplicate of #2011 – no need to track the 401 problem in several different issue threads.
