### ISSUE TITLE
After downloading exactly 12 medias from any profile whether its private or not, the instaloader is not working.

### ISSUE THREAD

**Issue by Octo-Siddharth** [instaloader/instaloader#2001]
After using instaloader profile profile_name, it downloads exactly 12 medias, even after logging in, please help what to do.
After downloading 12 pictures it says

Errors or warnings occurred:
profile: JSON Query to web/search/topsearch/: HTTP error code 401.
Profile name : JSON Query to graphql/query: HTTP error code 401.

Thank you in advance

**Comment by mumarkhann** [comment]
same here, i need to know if you found some solution?

**Comment by Octo-Siddharth** [comment]
> same here, i need to know if you found some solution?

Could'nt find any solution, please anyone help.

**Comment by lo-fo** [comment]
same

**Comment by AmineMahdioui** [comment]
have u used a wait time between calls?
