### ISSUE TITLE
JSON Query to graphql/query: HTTP error code 401.

### ISSUE THREAD

**Issue by ismatBabirli** [instaloader/instaloader#2002]
I am getting the error on the Ubuntu server. But it is working on the local machine.
`JSON Query to graphql/query: HTTP error code 401.`

**Comment by GarethFreeman** [comment]
Having the same problem, it seems to be triggered by the login function, works fine on public accounts.

**Comment by ismatBabirli** [comment]
@GarethFreeman But I am trying to download a public video. I think it is related to the server or smth

**Comment by aandergr** [comment]
Closing these as duplicate of #2011 – no need to track the 401 problem in several different issue threads.
