### ISSUE TITLE
Running instaloader on linux

### ISSUE THREAD

**Issue by mumarkhann** [instaloader/instaloader#2003]
I'm facing difficulties running Instaloader on a Linux server. Whenever I try to run it, the program prompts me to log in to Instagram. However, I'm unable to successfully log in, both on Linux and on a Windows Remote Desktop Protocol (RDP).

My goal is to set up a service on the Linux server that runs Instaloader once a day for a list of saved users. I need a short break of 1-2 minutes between each user. Unfortunately, I'm unable to proceed with this because I can't get Instaloader to run successfully on Linux in the first place.

Can anyone guide me if you have solved this issue or worked your way around it. VPS for linux is Ubuntu 22, and windows rdp is window 10 server.

**Comment by Pixel2075** [comment]
what's the error?

**Comment by Ayush0Chaudhary** [comment]
There was some PATH issue last i remember, but software worked fine for me.

**Comment by mumarkhann** [comment]
the issue is that, are you guys able to run instaloader on LINUX or Window's RDP for fetching any type of publicly available data?

**Comment by wilmort** [comment]
> There was some PATH issue last i remember, but software worked fine for me.

This happened to me as well on a Debian VM.

echo $PATH
export PATH=<your echo output>:<path to instaloader script>

worked for me.

**Comment by ashutoshbookeve** [comment]
hey, i am getting the same issue, is there any solution that worked for you?

**Comment by GonzalesPy** [comment]
getting the same error @ashutoshbookeve you got any solution?
