### ISSUE TITLE
Facing issue while getting profile information using username, previously It was working

### ISSUE THREAD

**Issue by iyashjayesh** [instaloader/instaloader#2005]
```python
import instaloader
 
ACCOUNT_USERNAME=""
ACCOUNT_PASSWORD=""
# Creating an instance of the Instaloader class
bot = instaloader.Instaloader()
bot.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD)
 
# list of users > 1000
# this is just for example 
username = "instagram"
profile = instaloader.Profile.from_username(bot.context, username)
print("Trying to scrape profile of:", profile.username)
print("Number of Posts: ", profile.mediacount)
print("Followers Count: ", profile.followers)
print("Following Count: ", profile.followees)
```
I'm trying to run the above code but facing the bellow issue,

issue:
```md
HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=instagram to Number of requests within last 10/11/20/22/30/60 minutes grouped by type:
                              other:    1    1    1    1    1    1
 *                           iphone:    1    1    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 30 minutes, at 18:04.
```

can anyone please help me to resolve this? After every 30 mins, it's saying the same thing again and again, any resolution?

**Comment by ihabpalamino** [comment]
you may be connecting with the same account you're scraping with in your phone disconnect from your phone

**Comment by iyashjayesh** [comment]
> you may be connecting with the same account you're scraping with in your phone disconnect from your phone

**Comment by iyashjayesh** [comment]
> you may be connecting with the same account you're scraping with in your phone disconnect from your phone

no I'm not doing that.

**Comment by ihabpalamino** [comment]
i faced the same problem hen i disconnect from my phone and get cookies and import session file from firefox it works fine after that

**Comment by iyashjayesh** [comment]
> i faced the same problem hen i disconnect from my phone and get cookies and import session file from firefox it works fine after that

how can we do that? can you provide me with any quick steps?

**Comment by rashaed44** [comment]
> ```python
> import instaloader
>  
> ACCOUNT_USERNAME=""yf19518
> ACCOUNT_PASSWORD=""776926749@o
> # Creating an instance of the Instaloader class
> bot = instaloader.Instaloader(e163_1169BOT)
> bot.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD)
>  
> # list of users > 1000
> # this is just for example 
> username = "instagram"
> profile = instaloader.Profile.from_username(bot.context, username)
> print("Trying to scrape profile of:", profile.username)
> print("Number of Posts: ", profile.mediacount)
> print("Followers Count: ", profile.followers)
> print("Following Count: ", profile.followees)
> ```
> 
> I'm trying to run the above code but facing the bellow issue,
> 
> issue:
> 
> ```
> HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=instagram to Number of requests within last 10/11/20/22/30/60 minutes grouped by type:
>                               other:    1    1    1    1    1    1
>  *                           iphone:    1    1    1    1    1    1
> Instagram responded with HTTP error "429 - Too Many Requests". Please
> do not run multiple instances of Instaloader in parallel or within
> short sequence. Also, do not use any Instagram App while Instaloader
> is running.
> The request will be retried in 30 minutes, at 18:04.
> ```
> 
> can anyone please help me to resolve this? After every 30 mins, it's saying the same thing again and again, any resolution?

**Comment by rashaed44** [comment]
e163_1169BOT

**Comment by sumitbatwani** [comment]
@iyashjayesh, @rashaed44 You must use a rotating proxy to avoid 429 errors. Check this: [https://github.com/instaloader/instaloader/issues/459](https://github.com/instaloader/instaloader/issues/459)
