### ISSUE TITLE
How do i get saved posts using command prompt?

### ISSUE THREAD

**Issue by SheruBOI** [instaloader/instaloader#2006]
Hey guys, I'm not really experience in JSON and shell commands etc. and I've been trying to figure out the command to get all my saved post using the command prompt. so I would love if anyone would be willing to tell me the command i need to use for that and also the command to set directory. Thanks guys.

p.s: I've read the docs but my monke brain didn't really understand them. thnx.

**Comment by nagualcode** [comment]
-- saved

**Comment by SheruBOI** [comment]
> -- saved

The thing is I don't know the whole command I've scanned the docs and I didn't really figure it out also it won't log in either just keeps on failing.
