### ISSUE TITLE
instaloader returning empty list

### ISSUE THREAD

**Issue by ihabpalamino** [instaloader/instaloader#2007]
username = request.form.get('username')
    since_date = request.form.get('since')
    until_date = request.form.get('until')
    PLATFORM_NAME = request.form.get('plateform')

    session_cookiefile = get_cookiefile()
    sessionfile = "thescraper12"

    import_session(session_cookiefile, sessionfile)  # Import the session cookie

    L = instaloader.Instaloader()
    L.load_session_from_file(sessionfile)

    posts = instaloader.Profile.from_username(L.context, username).get_posts()
    SINCE = datetime.strptime(since_date, "%Y-%m-%d")
    UNTIL = datetime.strptime(until_date, "%Y-%m-%d")

    data = []
    for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
        if post.is_video:
            viewVideo = post.video_view_count
        else:
            viewVideo = None

        post_data = {
            "id_post": post.mediaid,
            "Date": post.date.strftime("%Y-%m-%d"),
            "Heure": post.date.strftime("%H:%M:%S"),
            "content": post.caption,
            "username": post.owner_username,
            "likecount": post.likes,
            "viewVideo": viewVideo,
            "comments": post.comments,
            "platformname": PLATFORM_NAME
        }
        data.append(post_data)

    df = pd.DataFrame(data, columns=["id_post", "Date", "Heure", "content", "username", "likecount", "viewVideo",
                                     "comments", "platformname"])
    csv_path = "C:/Users/HP Probook/OneDrive/Images/Bureau/CsvScraping/instagram.csv"
    df.to_csv(csv_path, mode="w", sep=";", encoding='utf-8', index=False)
    Infos_json = df.to_json(orient='records', indent=4, force_ascii=False)
    clean_insta_json = re.sub(r"[\x00-\x1F\x7F-\x9F]", "",
                              Infos_json)  # Supprimer les caractères de contrôle non valides
    response = jsonify(json.loads(clean_insta_json))
    response.headers['Content-Type'] = 'application/json'

    return response
the code is returning an empty data list while there is informations in the account i am  trying to scrape

**Comment by wuharlem** [comment]
I am experiencing a similar issue despite being logged in. It appears to be related to a request limit rather than a ban on my account, such as a 429 or 401 IP ban. To address this, I have implemented a solution by incorporating a proxy and time sleep to avoid appearing like a robot. Additionally, if the list remains empty, logging in again is necessary., logging in again is necessary.
