### ISSUE TITLE
Not works on TopSearchResults

### ISSUE THREAD

**Issue by hofong428** [instaloader/instaloader#2009]
Dear Sir, 

I use the following scripts from your demo, but it cannot works and shows error:
JSON Query to web/search/topsearch/: HTTP error code 401. [retrying; skip with ^C]

would you tell me how to modify the code?

import instaloader
 
# Creating an instance of the Instaloader class
bot = instaloader.Instaloader()
 
# Provide the search query here
search_results = instaloader.TopSearchResults(bot.context, 'music')
 
# Iterating over the extracted usernames
for username in search_results.get_profiles():
    print(username)
 
# Iterating over the extracted hashtags
for hashtag in search_results.get_hashtags():
    print(hashtag)

**Comment by frapava98** [comment]
I have the same issue.

**Comment by wuharlem** [comment]
Lately, this API seems to be limited somehow. I tested the API without a login session and found a success rate of less than 5%. However, using a login session can lead to a higher success rate.
