### ISSUE TITLE
Upload abilities?

### ISSUE THREAD

**Issue by bingbucks** [instaloader/instaloader#201]
Great tool. Played with it to recover a friend's set of pictures when her account was hacked, so I used your tool to get all her photos & hashtags, which she didn't have backups too. And she is waiting to hear back from Instagram to hopefully recover her account.

So, in case there is no recovery of her old account, she's already started a new account. Question is, anything in the works to upload everything (to a new profile) that was downloaded with Instaloader originally (from an old profile)? Kind of like a full clone.

Thanks.

**Comment by aandergr** [comment]
We consider this beyond the scope of Instaloader. Instaloader's goal is to mimick the browser's behavior to access the data that is available through the Instagram web interface, pack this data into complete and easily-(re)usable python objects, and provide a user interface for the most common downloading and metadata collection tasks, without changing any of the online data.

**Comment by bingbucks** [comment]
I appreciate the answer. No worries about the clone/upload. She's already started a new Instagram account as Instagram support was next to useless.

Great tool. All the best.
