### ISSUE TITLE
Even the test not works on  basics work

### ISSUE THREAD

**Issue by hofong428** [instaloader/instaloader#2010]
Dear Sir,
It looks even the basics work is rejected by IG now. it shows the error:
 raise LoginRequiredException("Redirected to login page. Use --login.")
instaloader.exceptions.LoginRequiredException: Redirected to login page. Use --login.

How should I do next?

import instaloader

# Creating an instance of the Instaloader class
bot = instaloader.Instaloader()

# Loading the profile from an Instagram handle
profile = instaloader.Profile.from_username(bot.context, 'cristiano')
print(profile)

**Comment by Florentn** [comment]
I can confirm that instaloader does not work anymore either in anonymous mode(asks to login) or even logged in (each time IG asks to confirm identity, change password...) 

I have seen it happen in the past and get resolved at some point. I hope that will be the case again.
To the people working and maintaining Instaloader, I'd like to thank you all for all the work you've put in in creating this great library.

**Comment by k12978** [comment]
You can only view up to 12 pages on Instagram without logging in.

**Comment by volkv** [comment]
> You can only view up to 12 pages on Instagram without logging in.

Not anymore. It even fails to retrieve `Profile.from_username(L.context, profile)` without --login.

Probably it's because of bad IPs. But I've tried a lot

**Comment by MosEisley34** [comment]
Any alternatives being recommended as of now?
