### ISSUE TITLE
JSON Query to graphql/query: HTTP error code 401

### ISSUE THREAD

**Issue by keisanng** [instaloader/instaloader#2011]
**Describe the bug**

**To Reproduce**
1. Instaloader Python module
2. Scrape an Instagram page for *videos only*.

**Expected behavior**
I expected for the program to function correctly and download the videos.

**Error messages and tracebacks**
JSON Query to graphql/query: HTTP error code 401

```shell
Traceback (most recent call last):
  File "DRIVE:\PATH\.venv\Lib\site-packages\instaloader\instaloadercontext.py", line 352, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 401.
```

**Instaloader version**
4.9.6

**Additional context**
It worked for a little bit today after similar behavior yesterday... maybe it's just Instagram cracking down on me?

**Comment by k12978** [comment]
#2000 #2001 #2002 are recent issues with the same problem, I think Instagram changed internally; sorry this is all information I can contribute.

**Comment by aandergr** [comment]
Thanks for reporting. Indeed, this problem has been reported more frequently lately.

The seemingly most effective way to alleviate this is outlined here: https://instaloader.github.io/troubleshooting.html#too-many-requests – especially that restarting or reinstantiating Instaloader within short time should be avoided, to allow the rate controller to throttle requests.

**Comment by frozenpandaman** [comment]
Would love to see this fixed, if possible! It seems the suggested "solution" for now is just "wait".

**Comment by satoshinotdead** [comment]
> Would love to see this fixed, if possible! It seems the suggested "solution" for now is just "wait".

I can confirm [we can load cookies from browser](https://github.com/instaloader/instaloader/issues/2165#issuecomment-2041230960) and everything works like a charm.

**Comment by Lokawn** [comment]
Not working even after loading cookies, gives following error
```
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Fatal error: JSON Query to graphql/query: HTTP error code 401.
```

**Comment by satoshinotdead** [comment]
> Not working even after loading cookies, gives following error
> 
> ```
> JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
> JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
> Fatal error: JSON Query to graphql/query: HTTP error code 401.
> ```

That's probably related with our instance (unauthorized error message) and should be followed on a separate issue if you want to open it.

**Comment by sajaltiwari999** [comment]
I am also facing this issue can anyone help me

![Screenshot 2024-07-18 200204](https://github.com/user-attachments/assets/3e8bb4a4-089d-4f10-9f96-6fcc55bdab6f)

**Comment by rafikabir85** [comment]
![image](https://github.com/user-attachments/assets/d28a3a9b-d0e1-4e43-ad0e-c30b04e8406d)

**Comment by rharley99** [comment]
> ![image](https://private-user-images.githubusercontent.com/37447247/354823529-d28a3a9b-d0e1-4e43-ad0e-c30b04e8406d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTEzMTAsIm5iZiI6MTcyMjk5MTAxMCwicGF0aCI6Ii8zNzQ0NzI0Ny8zNTQ4MjM1MjktZDI4YTNhOWItZDBlMS00ZTQzLWFkMGUtYzMwYjA0ZTg0MDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAwMzY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYTM1YzdlYjY3NzIyNzdiOTY5M2Q0ZTE3ZTJmZTc1ZTQ1YTMyN2VkNWZjMTRhYTkxNGNiNWEzY2E2NzhkNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NYagl_kZTE7QD9HykodKtXEyDAVCW_7zshhRgAh-bMI)

I;m hgaving this same issue

**Comment by dmerces** [comment]
Hi Everybody.
Same issue here since October, 1st.

**Comment by changja88** [comment]
Hi Everyone.
Same issue here since april 25
