### ISSUE TITLE
Used this for gathering references. Anyone know of an alt for this?

### ISSUE THREAD

**Issue by neato82** [instaloader/instaloader#2015]
This was such a gem to use for gathering references. Seems like (I'm guessing) either IG changed some stuff internally that this used, or the dev might have abandoned the project. Either way, has been very useful so thank you to the devs. Was wondering if any users who see this know of an alternative for this?

Let me know.

Thanks!

**Comment by k12978** [comment]
Instagram changed stuff internally, I know this because I re-wrote my code with [Instagrapi](https://github.com/adw0rd/instagrapi/) and experience the same issues.
