### ISSUE TITLE
Unusual activity login

### ISSUE THREAD

**Issue by alwifearzz17** [instaloader/instaloader#2019]
How to i avoid "We noticed unusual activity from your account so we've logged you out.
Follow the next steps within 1 day so we can try to get you back into your account before it's disabled." It is really annoy me whenever im trying to login to intaloader.

**Comment by taxen** [comment]
I came across the following error for the first time (v. 4.9.6.)

```
>instaloader --login **** -F -p **** --no-posts --no-profile-pic --no-captions --stories ****
Loaded session from C:\Users\user\AppData\Local\Instaloader\session-****.
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/****/****/****/ - follow the instructions, then retry.
```

When I open the URL, Instagram made me to make sure if the above login was a legit one.
Although I confirmed it was mine, they made to change my password.

Now I am afraid to use the new password to work with Instaloader in case the same happens again and my account will be banned.

**Comment by alwifearzz17** [comment]
> I came across the following error for the first time (v. 4.9.6.)
> 
> ```
> >instaloader --login **** -F -p **** --no-posts --no-profile-pic --no-captions --stories ****
> Loaded session from C:\Users\user\AppData\Local\Instaloader\session-****.
> Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/****/****/****/ - follow the instructions, then retry.
> ```
> 
> When I open the URL, Instagram made me to make sure if the above login was a legit one. Although I confirmed it was mine, they made to change my password.
> 
> Now I am afraid to use the new password to work with Instaloader in case the same happens again and my account will be banned.
> 
> Before that, yesterday, I came across this issue #2025. Even before that, a few days back, I also came across #2011. But the password I used was always the same as I used on my web browser, which worked without any problem.

did u manage to solve the problem?

**Comment by Gertje79** [comment]
I got it to work with another function... Now I am banned :-(
downloaded 10 posts...lol
not worth it

**Comment by alwifearzz17** [comment]
> I got it to work with another function... Now I am banned :-( downloaded 10 posts...lol not worth it

is it ur main account got banned? i have stopped using instaloader for now

**Comment by makako-dev** [comment]
@alwifearzz17 See my comment on [this](https://github.com/instaloader/instaloader/issues/1927#issuecomment-1556256540) thread. I have not been flagged since using instaloader this way. Hope this helps.

**Comment by alwifearzz17** [comment]
> @alwifearzz17 See my comment on [this](https://github.com/instaloader/instaloader/issues/1927#issuecomment-1556256540) thread. I have not been flagged since using instaloader this way. Hope this helps.

noted..I will try this method.. thank you so much
