### ISSUE TITLE
Download only the mp3 version of videos.

### ISSUE THREAD

**Issue by Pranshul2002** [instaloader/instaloader#2024]
There are many music creators on Instagram. Some of them do not post their covers to other platforms. Using this feature users will be able to download just the audio version of the songs. Additional functionality can be added as after the song is downloaded, we can use audio recognition api like shazam to find the song and create a playlist in platforms like spotify or youtube music.

How could the user invoke the new function? Which problem would it solve?
By using --create playlist flag to create a playlist or --audio-only flag to listen only to audio.
If new information is obtained, how would it be further processed?
No new information is required for this. This library already has the option to download videos. We only need to keep the audio part of that. 
**Describe the solution you'd like**
There are many music creators on Instagram. Some of them do not post their covers to other platforms. Using this feature users will be able to download just the audio version of the songs. Additional functionality can be added as after the song is downloaded, we can use audio recognition api like shazam to find the song and create a playlist in platforms like spotify or youtube music.

**Describe alternatives you've considered**
Videos can be listened as audio but the playlist creation feature is not possible. 
How do you achieve the here-described goal without the feature you are requesting?
If I want to listen to the reels by a specific creator as audio there is no tool to do that. 
**If the feature request is accepted, would you be willing to submit a pull request?**
Yes

**Additional context**
Implementation and scope of this feature can be discussed further and any input on the same would be appreciated.

**Comment by aandergr** [comment]
This is out of scope, Instaloader should not postprocess the downloaded content or invoke further APIs. The downloaded data can be easily processed in external tools.
