### ISSUE TITLE
Fatal error: Login: Checkpoint required.

### ISSUE THREAD

**Issue by GillesMorysse** [instaloader/instaloader#2027]
Bonjour,
J'ai essayé de telecharger des stories d'un profil public instagram.
je rentre la ligne de commande, mon mot de passe instagram et j'ai le message suivant : Fatal error: Login: Checkpoint required.
J'ai essayé les autres solutions proposée mais aucune ne fonctionne.
Suis je le seul à avoir cette erreur ?
Merci

**Comment by Showmaster3000** [comment]
Duplicate of #1787.
And please write in English here, so more people can understand your issue.
