### ISSUE TITLE
Post details from list of users

### ISSUE THREAD

**Issue by Anuradhe007** [instaloader/instaloader#203]
Below code is use to get posts from list of users. 

`for userName in userNameList:`
`     posts = instaloader.Profile.from_username(self.loaderObject.context, userName).get_posts()`
`     time.sleep(60)`

But after iterating the list few times, It gives following error.

JSON Query to graphql/query: 429 Too Many Requests [retrying; skip with ^C]
The request will be retried in 641 seconds, at 21:23.
HTTP error code 429 was returned because too many queries occured in
the last time. Please do not use Instagram in your browser or run
multiple instances of Instaloader in parallel.
Made 1 GraphQL requests.

Please anyone can help me to solve this?

**Comment by aandergr** [comment]
A general note about **429 - Too Many Requests**:
> Instaloader has a logic to keep track of its requests to Instagram and to obey their rate limits. Since they are nowhere documented, we try them out experimentally. We have a daily cron job running to confirm that Instaloader still stays within the rate limits. Nevertheless, the rate control logic assumes that
> - at one time, Instaloader is the only application that consumes requests. I.e. neither the Instagram browser interface, nor a mobile app, nor another Instaloader instance is running in parallel,
> - no requests had been consumed when Instaloader starts.
>
> The latter one implies that restarting or reinstantiating Instaloader often within short time is prone to cause a 429. When a request is denied with a 429, Instaloader retries the request as soon as the temporary ban is assumed to be expired.
