### ISSUE TITLE
This is just not working?

### ISSUE THREAD

**Issue by Gertje79** [instaloader/instaloader#2031]
Am I the only one that just does not get this to work? I am falling in error after error. the L.login() does not work.
The workaround... gives me errors
does anyone has this working and is able to download videos from a followee?

**Comment by AcidkoHorkaCokolada** [comment]
hi im able to scrap but after while i have trouble to continue as i get banned.

**Comment by AmineMahdioui** [comment]
it is working for me but like @AcidkoHorkaCokolada said im facing challanges to not get banned

**Comment by Gertje79** [comment]
I got it to work with another function... Now I am banned :-(
downloaded 10 posts...lol
not worth it

**Comment by AcidkoHorkaCokolada** [comment]
@Gertje79 had same issues at the begining - wait couple days and then try. also i had this issue from VPS, from my personal machine i can do like 1500 posts then i get small ban
