### ISSUE TITLE
limits

### ISSUE THREAD

**Issue by AcidkoHorkaCokolada** [instaloader/instaloader#2032]
Hello everyone,

what would be the best practice to scrap 200 IG profiles? 
im constantly getting bans or errors after a while.. also keep firefox open on my profile page. 

`instaloader --login my_user--sessionfile=....Local\Instaloader\session-file --comments --post-metadata-txt="{likes} likes, {comments} comments" --request-timeout=400 --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0" --post-filter="date_utc > datetime(2022, 6, 30)" --latest-stamps --no-videos --no-video-thumbnails  --no-profile-pic --max-connection-attempts=1 --abort-on=302,400,401,429  --count 200`

what would be your advise?

**Comment by Gertje79** [comment]
stay out of it... it will get you account life time banned asap

**Comment by AcidkoHorkaCokolada** [comment]
@Gertje79 so i create a new one :D

**Comment by AmineMahdioui** [comment]
i am also trying to scrap a "large" number of accounts at some point i found that having multiple accounts alternate in scrapping with a lot of random wait time worked well until it didnt :(. got suspended or the bots encounter a login challenge (HTTP error 400) still trying again

**Comment by space-base96** [comment]
Write your telegram
