### ISSUE TITLE
Instaloader suddenly stops downloading saved posts without error

### ISSUE THREAD

**Issue by tillkaufmann** [instaloader/instaloader#2038]
**Describe the bug**
I have the newest Instaloader running (4.10)
I try to save my saved posts with instaloader --login myUserName :saved
I enter the password and the instaloader does it's magic.
`Logged in as myUserName .
Retrieving saved posts...`

And then it downloads the images
`[   1/3736] ：saved\2023-07-19_13-57-45_UTC_1.jpg exists`
But always when it reaches #47 it stops without explanation.
This is the last output line.
`[  47/3736] ：saved\2023-06-01_03-27-20_UTC_1.jpg exists ：saved\2023-06-01_03-27-20_UTC_2.jpg exists ：saved\2023-06-01_03-27-20_UTC_3.jpg exists ：saved\2023-06-01_03-27-20_UTC_4.jpg exists ：saved\2023-06-01_03-27-20_UTC_5.jpg exists ：saved\2023-06-01_03-27-20_UTC_6.jpg exists ：saved\2023-06-01_03-27-20_UTC_7.jpg exists ：saved\2023-06-01_03-27-20_UTC_8.jpg exists ：saved\2023-06-01_03-27-20_UTC_9.jpg exists ：saved\2023-06-01_03-27-20_UTC_10.jpg exists [Baracco+Wright Architects, Ga…] unchanged json
Saved session to C:\Users\My Name\AppData\Local\Instaloader\session-myUserName .`

I tried it multiple times, it always stops at post #47

I saved a random post, and retried save the posts, but it still stops after #47
This is the last output line.
`[  47/3737] ：saved\2023-06-22_11-59-33_UTC.jpg exists [LINDOWER [1/3]  places to sit…] unchanged json
Saved session to C:\Users\My Name\AppData\Local\Instaloader\session-myUserName .`

**To Reproduce**
instaloader --login myUserName :saved

**Expected behavior**
I expect instaloader to download all 3736 saved posts, or print an error message if something wents wrong

**Error messages and tracebacks**
Sadly no error messages

**Instaloader version**
4.10

**Additional context**
Never expected this problem before

**Comment by davoricla** [comment]
I get the exact same issue, except mine terminates at #50 instead of #47. That tells us something, but I don't know exactly what.
