### ISSUE TITLE
:stories only downloads 500 stories from an account with several thousand available stories

### ISSUE THREAD

**Issue by gituzzer** [instaloader/instaloader#204]
**Describe the bug**
- instaloader used with :stories with an account that has many story-active followees (7000 in my case) **only downloads stories from EXACTLY 500 followees and then stops**.
I didn't find any 500 magic number inside instaloader or from instagram "scholars", so I wonder where is this 500 limitation come from.

**To Reproduce**
<user> has a few thousand followees with available stories.
- instaloader.py -l user -p passwd :stories --dirname-pattern={profile} --filename-pattern={date} --no-metadata-jso

**Expected behavior**
- Instagram account has about 7000 followees, 4000 of them story-active, so I'd expect about 4000 folders of followees stories to be updated/created.

**Error messages and tracebacks**
- There are no error messages, only the normal messages:
Retrieving all visible stories...
Retrieving stories from profile "profile1"
Retrieving stories from profile "profile2"
Retrieving stories from profile "profile3"
...
Retrieving stories from profile "profile499"
Retrieving stories from profile "profile500"
and then it goes back to prompt.

**Instaloader version**
- 4.1.1

**Additional context**
- NOTE1: The "old way" of getting stories downloads all stories, not just 500, using @user and --stories-only, 
EXAMPLE: instaloader.py -l user -p passwd @user  --no-captions --fast-update --stories-only --filename-pattern={date} --no-profile-pic --no-metadata-json.
But this old way takes 2+hours has it loads all the followee names before the stories are downloaded.
- NOTE2: If an account with less than 500 story-active followees is used, then :stories and --stories-only download the same number stories (up to 500). Confirmed it with several accounts.

**Comment by e5150** [comment]
Iteresting little bug you've found there. You might try changing the query hash in `get_stores()` from `d15efd8c0c5b23f0ef71f18bf363c704` to `60b755363b5c230111347a7a4e242001`, which seems to be what the website uses.
I'm assuming instagram limits the response to 500 users. Are you able to see more than 500 users in the story list on the web page? Does it load more users after scrolling past the first 500? There might be a `has_next_page=True` and `whatever_cursor=...` in the response.

**Comment by gituzzer** [comment]
e5150, thanks for the reply. I replaced the hash but the behavior remains. 
I did as you asked, checked the # of users in the story list on the web page and you're right, it's 500, and the users that show up match those that I get through :stories using instaloader.
It does not load more users as i drag the scrollbar down, even if I read some stories. Also no "next" button shows up, so I guess the next_page feature is hidden or simply does not exist.

**Comment by aandergr** [comment]
Hi,



> e5150, thanks for the reply. I replaced the hash but the behavior remains.
> I did as you asked, checked the # of users in the story list on the web page and you're right, it's 500, and the users that show up match those that I get through :stories using instaloader.
> It does not load more users as i drag the scrollbar down, even if I read some stories. Also no "next" button shows up, so I guess the next_page feature is hidden or simply does not exist.

I'm afraid if this info cannot be obtained in the browser app, there is nothing we can do, as Instaloader mimics the browser's behavior.

> * NOTE1: The "old way" of getting stories downloads all stories, not just 500, using @user and --stories-only

Then this is probably the best way of getting all stories when following more than 500 accounts :disappointed:
