### ISSUE TITLE
JSON Query to api/v1/media/3156440125857379289/info/: HTTP error code 403. [retrying; skip with ^C]

### ISSUE THREAD

**Issue by ihabpalamino** [instaloader/instaloader#2042]
my code is import json
import re

from flask import Flask, request, jsonify
import instaloader
import pandas as pd

from sqlite3 import connect, OperationalError
from glob import glob
from datetime import datetime
from itertools import takewhile, dropwhile

# app = Flask(__name__)

def get_cookiefile():
    default_cookiefile = {
        "Windows": "~/AppData/Roaming/Mozilla/Firefox/Profiles/*/cookies.sqlite",
        "Darwin": "~/Library/Application Support/Firefox/Profiles/*/cookies.sqlite",
    }.get(system(), "~/.mozilla/firefox/*/cookies.sqlite")
    cookiefiles = glob(expanduser(default_cookiefile))
    if not cookiefiles:
        raise SystemExit("No Firefox cookies.sqlite file found. Use -c COOKIEFILE.")
    return cookiefiles[0]

def import_session(cookiefile, sessionfile):
    print("Using cookies from {}.".format(cookiefile))
    conn = connect(f"file:{cookiefile}?immutable=1", uri=True)
    try:
        cookie_data = conn.execute(
            "SELECT name, value FROM moz_cookies WHERE baseDomain='instagram.com'"
        )
    except OperationalError:
        cookie_data = conn.execute(
            "SELECT name, value FROM moz_cookies WHERE host LIKE '%instagram.com'"
        )
    instaloader = Instaloader(max_connection_attempts=1)
    instaloader.context._session.cookies.update(cookie_data)
    username = instaloader.test_login()
    if not username:
        raise SystemExit("Not logged in. Are you logged in successfully in Firefox?")
    print("Imported session cookie for {}.".format(username))
    instaloader.context.username = username
    instaloader.save_session_to_file(sessionfile)

# @app.route('/scrape-instagram', methods=['POST'])
# def scrape_instagram():
# username = request.form.get('username')
# since_date = request.form.get('since')
# until_date = request.form.get('until')
# PLATFORM_NAME = request.form.get('plateform')
username = "al_aoula"
since_date = "2023-07-28"
until_date = "2023-07-24"
PLATFORM_NAME = "instagram"
# if not username:
#  return jsonify({'error': 'Username is required.'}), 400

session_cookiefile = get_cookiefile()
sessionfile = "thescraper12"

import_session(session_cookiefile, sessionfile)  # Import the session cookie

L = instaloader.Instaloader()
L.load_session_from_file(sessionfile)

posts = instaloader.Profile.from_username(L.context, username).get_posts()
SINCE = datetime.strptime(since_date, "%Y-%m-%d")
UNTIL = datetime.strptime(until_date, "%Y-%m-%d")
data = []
for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
        if post.is_video:
            viewVideo = post.video_view_count
        else:
            viewVideo = None

        post_data = {
            "id_post": post.mediaid,
            "Date": post.date.strftime("%Y-%m-%d"),
            "Heure": post.date.strftime("%H:%M:%S"),
            "content": post.caption,
            "username": post.owner_username,
            "likecount": post.likes,
            "viewVideo": viewVideo,
            "comments": post.comments,
            "platformname": PLATFORM_NAME,
            "postUrl": post.url

        }
        data.append(post_data)

df = pd.DataFrame(data, columns=["id_post", "Date", "Heure", "content", "username", "likecount", "viewVideo",
                                     "comments", "platformname"])
csv_path = "C:/Users/HP Probook/OneDrive/Images/Bureau/CsvScraping/instagram.csv"
df.to_csv(csv_path, mode="w", sep=";", encoding='utf-8', index=False)

Infos_json = df.to_json(orient='records', indent=4, force_ascii=False)
clean_insta_json = re.sub(r"[\x00-\x1F\x7F-\x9F]", "",
                              Infos_json)  # Supprimer les caractères de contrôle non valides
response = jsonify(json.loads(clean_insta_json))
response.headers['Content-Type'] = 'application/json'
it was working fine then it still working but i got this error message with the result
Imported session cookie for thescraper12.
Saved session to thescraper12.
Loaded session from C:\Users\HP Probook\AppData\Local\Instaloader\session-thescraper12.
JSON Query to api/v1/media/3156440125857379289/info/: HTTP error code 403. [retrying; skip with ^C]
JSON Query to api/v1/media/3156440125857379289/info/: HTTP error code 403. [retrying; skip with ^C]
Unable to fetch high quality image version of <Post CvN7ZIohLPZ>: JSON Query to api/v1/media/3156440125857379289/info/: HTTP error code 403.
JSON Query to api/v1/media/3155715335458180292/info/: HTTP error code 403. [retrying; skip with ^C]
JSON Query to api/v1/media/3155715335458180292/info/: HTTP error code 403. [retrying; skip with ^C]
Unable to fetch high quality image version of <Post CvLWmC-PMzE>: JSON Query to api/v1/media/3155715335458180292/info/: HTTP error code 403.
JSON Query to api/v1/media/3155519061354778170/info/: HTTP error code 403. [retrying; skip with ^C]
JSON Query to api/v1/media/3155519061354778170/info/: HTTP error code 403. [retrying; skip with ^C]
Unable to fetch high quality image version of <Post CvKp94eBo46>: JSON Query to api/v1/media/3155519061354778170/info/: HTTP error code 403.

**Comment by Showmaster3000** [comment]
And what is your problem? You missed a description what you try to do.
Anyway error code 403 can happen sometimes. But it also gives a hint that your account may be flagged or blocked  by Instagram.
