### ISSUE TITLE
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

### ISSUE THREAD

**Issue by turboteun2** [instaloader/instaloader#2044]
The code I use for this is:

```
import instaloader

loader = instaloader.Instaloader()

loader.login(user="", passwd="")
print("✅ 1- Logged in")
```

The output is:
```
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 357, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 357, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 357, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/teungrondman/Documents/projects/python/getfollowers_insta/test.py", line 5, in <module>
    loader.login(user="the_followweb", passwd="Aapje40")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instaloader/instaloader.py", line 634, in login
    self.context.login(user, passwd)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 214, in login
    csrf_json = self.get_json('accounts/login/', {}, session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 395, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 395, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 383, in get_json
    raise QueryReturnedNotFoundException(error_string) from err
instaloader.exceptions.QueryReturnedNotFoundException: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.
```

**To troubleshoot this issue I tried the following:**

- Double-check your Instagram username and password for correctness
- Disable two-factor authentication for your account temporarily and see if that resolves the issue.
- Update the instaloader library to the latest version using pip: `pip3 install --upgrade instaloader.`

**Comment by mohebbi-1386** [comment]
Hello
Do not be tired
Good time

I and several of my colleagues have been working with instaloader since the past and are still working. But for the last time (after the new update), we came across a serious problem in the login account of Instagram and we found out that not only us, but many people are facing this problem.

Code Snippet:
```
import instaloader

# Get instance
L = instaloader.Instaloader()

# Optionally, login or load session
L.login(USER, PASSWORD)        # (login)

```
error:
```
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Traceback (most recent call last):
  File "/home/runner/code/venv/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 410, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/code/venv/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 410, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/code/venv/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 410, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    L.login(..., ....)
  File "/home/runner/code/venv/lib/python3.10/site-packages/instaloader/instaloader.py", line 651, in login
    self.context.login(user, passwd)
  File "/home/runner/code/venv/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 259, in login
    csrf_json = self.get_json('accounts/login/', {}, session=session)
  File "/home/runner/code/venv/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 448, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/home/runner/code/venv/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 448, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
  File "/home/runner/code/venv/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 436, in get_json
    raise QueryReturnedNotFoundException(error_string) from err
instaloader.exceptions.QueryReturnedNotFoundException: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.

```
To troubleshoot this issue I tried the following:

1. Double-check your Instagram username and password for correctness
2. Disable two-factor authentication for your account temporarily and see if that resolves the issue.
3. Update the instaloader library to the latest version using pip: pip3 install --upgrade instaloader.

**Comment by Jarsky** [comment]
Facing the same error running in Docker. I have cloned the latest 4.10 from Git, and generated new session file. Receiving this error. 

```
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Loaded session from /session-filename.
Fatal error: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.
```

**Comment by killergod143** [comment]
i am facing same issue , so i go to troubleshooting section from following link
https://instaloader.github.io/troubleshooting.html
search for "Login error" on page
so solution is there
- First download "[https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py]" this file
To use this script,

    Download the script: [Example 615_import_firefox_session.py](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py),

   - Login to Instagram in Firefox,

    - Execute the snippet, e.g. with python 615_import_firefox_session.py,

    - Then, instaloader -l USERNAME should work fine.

**Comment by ronakjain2012** [comment]
As @killergod143 mentioned 

follow the same steps and last step is not needed. 
( Then, instaloader -l USERNAME should work fine )

It works!! Thanks :)

**Comment by mohebbi-1386** [comment]
> تا از این اسکریپت استفاده کنید،
> 
> اسکریپت را دانلود کنید: [مثال 615_import_firefox_session.py](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py) ،
> 
> * ورود به اینستاگرام در فایرفاکس،
> * قطعه را اجرا کنید، به عنوان مثال با پایتون 615_import_firefox_session.py،
> *



> [من با همین مشکل روبرو هستم، بنابراین از لینک زیر https://instaloader.github.io/troubleshooting.html](https://instaloader.github.io/troubleshooting.html) به بخش عیب یابی می روم "خطای ورود" را در صفحه جستجو کنید تا راه حل وجود داشته باشد.
> 
> * ابتدا این فایل "[https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py]" را دانلود کنید 
>   تا از این اسکریپت استفاده کنید،
>   اسکریپت را دانلود کنید: [مثال 615_import_firefox_session.py](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py) ،
>   
>   * ورود به اینستاگرام در فایرفاکس،
>   * قطعه را اجرا کنید، به عنوان مثال با پایتون 615_import_firefox_session.py،
>   * سپس، installoader -l USERNAME باید به خوبی کار کند.



> i am facing same issue , so i go to troubleshooting section from following link https://instaloader.github.io/troubleshooting.html search for "Login error" on page so solution is there
> 
> * First download "[https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py]" this file
>   To use this script,
>   Download the script: [Example 615_import_firefox_session.py](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py),
>   
>   * Login to Instagram in Firefox,
>   * Execute the snippet, e.g. with python 615_import_firefox_session.py,
>   * Then, instaloader -l USERNAME should work fine.

Does the library use Firefox cookies in this method?

**Comment by Jarsky** [comment]
> * https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py

This is what I already do. 
I tried it again today and its working so i'm not sure what was happening, something on Instagrams end maybe. I had already used this to generate a new session cookie file. Tried it today and it just works again.

**Comment by yah00078** [comment]
Have the Same Issue Too, I'll prefered stay on Login/Password connection instead of import session.
i'll try again Following Jarsky Comment, or change my code to session.

**Comment by davoricla** [comment]
I had the same issue, and attempting to import my Firefox cookies as instructed on the troubleshooting page wasn't working. I figured out that it's because I use Firefox as my default browser, while most people are using it just to access the cookie file, so I had to change the '*' in the cookie path in the code to the name of the folder for my Firefox profile (should end in 'default-release' instead of 'default').

**Comment by taxen** [comment]
I followed the instruction below basically and it worked!

Here are some additional info to share:

1. I use several web browsers including Chome (main use), Waterfox G and Classic, Firefox (barely using).
2. When I checked my login info on the browsers except for Chrome, they were all outdated and wrong. So I updated the browsers login info.
3. I first tried to login Waterfox G, but running the script and instaloader failed as error messages "Cookie import failed: JSON Query to graphql/query: HTTP error code 401." and "JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]" returned respectively. Waterfox Classic also failed.
4. Firefox (106.0.5, which is very old) worked fine.

I do no know what "last step" in ronakjain2012's comment mean, but both "Login to Instagram in Firefox" and "Execute the snippet, e.g. with python 615_import_firefox_session.py" seem to be needed.

> i am facing same issue , so i go to troubleshooting section from following link https://instaloader.github.io/troubleshooting.html search for "Login error" on page so solution is there
> 
> * First download "[https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py]" this file
>   To use this script,
>   Download the script: [Example 615_import_firefox_session.py](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py),
>   
>   * Login to Instagram in Firefox,
>   * Execute the snippet, e.g. with python 615_import_firefox_session.py,
>   * Then, instaloader -l USERNAME should work fine.

**Comment by korean-1** [comment]
###########################################################
from argparse import ArgumentParser
from instaloader import Instaloader, Profile, ConnectionException
from os.path import expanduser
from sqlite3 import OperationalError, connect

def import_session(cookiefile, sessionfile):
    conn = connect(f"file:{cookiefile}?immutable=1", uri=True)
    try:
        cookie_data = conn.execute(
            "SELECT name, value FROM moz_cookies WHERE baseDomain='instagram.com'"
        )
    except OperationalError:
        cookie_data = conn.execute(
            "SELECT name, value FROM moz_cookies WHERE host LIKE '%instagram.com'"
        )
    instaloader = Instaloader(max_connection_attempts=1)
    instaloader.context._session.cookies.update(cookie_data)
    username = instaloader.test_login()
    if not username:
        raise SystemExit("Not logged in. Are you logged in successfully in Firefox?")
    instaloader.context.username = username
    instaloader.save_session_to_file(sessionfile)
    return instaloader, username

cookiefile = "C:\\Users\\Administrator\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\9v8gbj0x.default-release\\cookies.sqlite"

instaloader, username = import_session(cookiefile, None)

loader = Instaloader()

loader.load_session_from_file(username)

profile = Profile.from_username(loader.context, 'targetid')

for story in loader.get_stories(userids=[profile.userid]):
    for item in story.get_items():
        loader.download_storyitem(item, f"{profile.username}_stories")
###########################################################
i use this python code but the output was just 

Saved session to C:\Users\Administrator\AppData\Local\Instaloader\session-instid.
Loaded session from C:\Users\Administrator\AppData\Local\Instaloader\session-myinstid

I think I'm getting the login information just fine, but it's not down, what should I do?

**Comment by Mikamikaz** [comment]
When I try to dl public story after use 615_import_firefox_session.py, I get 401 error, same with profile picture (and not in HD). Does nyone know another module which can do the same thing?

**Comment by aleaksah** [comment]
And you can manually transfer cookies, you need only `sessionid` and `csrftoken`.
Something like this:
```
L = instaloader.Instaloader()
try:
    L.load_session_from_file("cookies.txt")
except:
    try:
        L.login("<your username>", "<your password>")
    except:
        L.load_session("<your username>", {"sessionid": "<your session>", "csrftoken": "<your csrf>"})
L.save_session_to_file("cookies.txt")
```
Of cause you need to get real values intead of my placeholders. You can use any tools that your browser provide.

**Comment by TheSadhak** [comment]
> i am facing same issue , so i go to troubleshooting section from following link https://instaloader.github.io/troubleshooting.html search for "Login error" on page so solution is there
> 
> * First download "[https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py]" this file
>   To use this script,
>   Download the script: [Example 615_import_firefox_session.py](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py),
>   
>   * Login to Instagram in Firefox,
>   * Execute the snippet, e.g. with python 615_import_firefox_session.py,
>   * Then, instaloader -l USERNAME should work fine.

can you share your code and what changes you made in the trouble shooting file

**Comment by stephanvierkant** [comment]
I've installed instaloader on Ubuntu (just `apt install instaloader`) and it worked, but when using Docker I had the same problem.

**Comment by Mikamikaz** [comment]
Almost one month and no solution (we can use "get_stories() with load_session solution), anyone have an alternative ?

**Comment by sapphirepro** [comment]
Session file does not exist yet - Logging in.
Enter Instagram password for optimuspager: 
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Fatal error: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.


Long term bug without any fixes. Login doesn't work at all. Any fix coming at all?

**Comment by reasadazim** [comment]
The session loaded but when I try to login it does not work. 

Loaded session from C:\Users\Bappy\AppData\Local\Instaloader\session-MYUSERNAME.
Enter Instagram password for natureloverbd2023:
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Fatal error: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.

**Comment by aleaksah** [comment]
> The session loaded but when I try to login it does not work.

Loading session could work instead of login, not with it.

**Comment by Hsyn-07** [comment]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Traceback (most recent call last): 

I am encountering the error. I couldn't handle it.

**Comment by fabrizio-palumbo** [comment]
how would this change if i am using macOS? I am struggling to replicate the solution

**Comment by kminito** [comment]
The only solution worked for me is @aleaksah's comment above. I manually bring cookie data from chrome and it worked. Firefox method didn't work for me.

**Comment by preze93** [comment]
I'm getting the same login error. @aleaksah I tried your method but still unsucessful. What message is to be expected when the script runs?
Also did you use the URL encoded sessionID?

**Comment by fabrizio-palumbo** [comment]
also is it any different on MacOS?

**Comment by Mikamikaz** [comment]
> The only solution worked for me is @aleaksah's comment above. I manually bring cookie data from chrome and it worked. Firefox method didn't work for me.

@kminito where do you find sessionid and csrftoken ?

**Comment by preze93** [comment]
Why isn't this being merged to solve the login issue?
https://github.com/instaloader/instaloader/pull/2040/files#diff-2a6ddd8f53c1561481e20a62b9efa7b637e532c42804e6cd3d41d597d8ae0ed3

**Comment by philip47** [comment]
Same.. still waiting for a update!

**Comment by pd2871** [comment]
In python, I followed this way and it's solved. Thanks to @killergod143  and @aleaksah for their answers

Steps:
- Make firefox as your default browser and log in instagram with your username and password in firefox browser
- Download this [script](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py) as a .py file and run the script as:
```
python 615_import_firefox_session.py
```
- After the script is run, it will save the data inside this local path:
```
C:\Users\{USER}\AppData\Local\Instaloader\session-{USERNAME}

For Example: C:\Users\Acer\AppData\Local\Instaloader\session-test123
```
- Now copy this full file path and use it here:
```
from instaloader import Instaloader

L = Instaloader()
try:
    L.load_session_from_file("test123", r"C:\Users\Acer\AppData\Local\Instaloader\session-test123") #1st argument should be username and 2nd argument should be the saved file location
    print("Logged In Successfully")
except Exception as e:
    print("Error", e)

L.get_feed_posts()
```

**Comment by RAiZ0K** [comment]
where is the developers? it been a long while for this error? we cant login damn instaloaderrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

**Comment by Cyph3r** [comment]
+1

**Comment by usernamefound** [comment]
> In python, I followed this way and it's solved. Thanks to @killergod143 and @aleaksah for their answers
> 
> Steps:
> 
>     * Make firefox as your default browser and log in instagram with your username and password in firefox browser
> 
>     * Download this [script](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py) as a .py file and run the script as:
> 
> 
> ```
> python 615_import_firefox_session.py
> ```
> 
>     * After the script is run, it will save the data inside this local path:
> 
> 
> ```
> C:\Users\{USER}\AppData\Local\Instaloader\session-{USERNAME}
> 
> For Example: C:\Users\Acer\AppData\Local\Instaloader\session-test123
> ```
> 
>     * Now copy this full file path from above and use it below:
> 
> 
> ```
> from instaloader import Instaloader
> 
> L = Instaloader()
> try:
>     L.load_session_from_file("test123", r"C:\Users\Acer\AppData\Local\Instaloader\session-test123") #1st argument should be username and 2nd argument should be the saved file location
>     print("Logged In Successfully")
> except Exception as e:
>     print("Error", e)
> 
> L.get_feed_posts()
> ```

Thanks! This fixed the problem, although I skipped the last step.

**Comment by kooozie** [comment]
I followed the instructions, and it still not working. Logged into my instragram account in Firefox. Then when I run the script, I get the following error:
ImportError: attempted relative import with no known parent package

**Comment by pd2871** [comment]
> I followed the instructions, and it still not working. Logged into my instragram account in Firefox. Then when I run the script, I get the following error:
> ImportError: attempted relative import with no known parent package

You can follow the steps from my answer 🙂

**Comment by JuaoSea** [comment]
> Almost one month and no solution (we can't use "get_stories()" with load_session solution), anyone have an alternative ?

`import instaloader

bot = instaloader.Instaloader()


username = input('Username: ')
bot.load_session_from_file("<USER>", "session-<USER>")

bot.download_profile(username, download_stories_only=True)`

**Comment by JuaoSea** [comment]
> Almost one month and no solution (we can't use "get_stories()" with load_session solution), anyone have an alternative ?

```
import instaloader

bot = instaloader.Instaloader()

username = input('Username: ')
bot.load_session_from_file("<USER>", "session-<USER>")

bot.download_profile(username, download_stories_only=True)
```

**Comment by AhmadSablouh** [comment]
After i tried this method:
* Make firefox as your default browser and log in instagram with your username and password in firefox browser

* Download this [script](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py) as a .py file and run the script as:
python 615_import_firefox_session.py
* After the script is run, it will save the data inside this local path:
C:\Users\{USER}\AppData\Local\Instaloader\session-{USERNAME}

For Example: C:\Users\Acer\AppData\Local\Instaloader\session-test123
* Now copy this full file path from above and use it below:
from instaloader import Instaloader

L = Instaloader()
try:
    L.load_session_from_file("test123", r"C:\Users\Acer\AppData\Local\Instaloader\session-test123") #1st argument should be username and 2nd argument should be the saved file location
    print("Logged In Successfully")
except Exception as e:
    print("Error", e)

L.get_feed_posts()

this's what i get 
Loaded session from /home/kali/.config/instaloader/session-xxx.
Fatal error: 400 Bad Request

**Comment by Jarsky** [comment]
Try logging into Instagram on a device; make sure your account hasnt been *locked* for suspicious activity. 
You'll need to unlock it if it has. 

From experience. Close any of your other apps (sessions) while Instaloader is running, and end instaloader before you start using it again.

**Comment by Lerazy** [comment]
> i am facing same issue , so i go to troubleshooting section from following link https://instaloader.github.io/troubleshooting.html search for "Login error" on page so solution is there
> 
> * First download "[https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py]" this file
>   To use this script,
>   Download the script: [Example 615_import_firefox_session.py](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py),
>   
>   * Login to Instagram in Firefox,
>   * Execute the snippet, e.g. with python 615_import_firefox_session.py,
>   * Then, instaloader -l USERNAME should work fine.


thanks bro   perfectly fixed my error.
