### ISSUE TITLE
Getting 'no such table: moz_cookies' when importing Firefox cookies? Do you use Firefox as your default browser?

### ISSUE THREAD

**Issue by davoricla** [instaloader/instaloader#2048]
**Description**
Script given for importing Firefox cookies only works if you are signed into Instagram from the default Firefox profile, otherwise returning `Cookie import failed: no such table: moz_cookies` if the user is signed in through their own Firefox profile.

**Replication**
Steps to reproduce the behavior (Windows 10):

1. Download [615_import_firefox_session-py](https://raw.githubusercontent.com/instaloader/instaloader/master/docs/codesnippets/615_import_firefox_session.py) and move to python's working directory.
2. Open Firefox with your own Firefox user profile.
3. Log into Instagram.
4. Open Terminal and run `py 615_import_firefox_session.py`

**Expected behavior**
Expected script to detect the active Firefox profile and get the cookie file from the corresponding profile folder.

**Error messages and tracebacks**
`Cookie import failed: no such table: moz_cookies`

**Instaloader version**
4.10

**Additional context**
Managed to get it working by replacing '*' in the script's cookie file paths with the name of the correct profile folder.

**Suggested Fixes**

- Tip given with 'no such table:  moz_cookies' error: `print("No cookies detected for selected Firefox profile. Please edit the path to select the cookie file from the folder that corresponds to the active Firefox profile (profile folder name ends in 'default-release', not 'default')")`
- Write script to detect active Firefox profile.
- Specify on troubleshooting page to log into Instagram with the default Firefox profile.

**Comment by Showmaster3000** [comment]
Looks like your Firefox profile is not in a default path? Did you try the parameter `-c` which the script supports to point to your cookie file?
