### ISSUE TITLE
Instaloader very slow get usernames from hashtag post

### ISSUE THREAD

**Issue by Anuradhe007** [instaloader/instaloader#205]
I am accessing the Instagram posts by hashtag. I need to get the post creator user name. Check below code.

`posts = self.loader.get_hashtag_posts(hashtag)`
`for post in posts:`
   `print(post.owner_username)`

It takes nearly 5 hours to collect 10k usernames. Is there any way to improve the performance?

**Comment by aandergr** [comment]
The constructor of class `Instaloader` has an intentionally undocumented parameter `sleep`. When set to `False` (default is `True`), Instaloader does not wait between requests unless absolutely required to not hit rate limits. That would make collecting the usernames faster, but on the other hand raise the risk to be blocked by Instagram servers.
