### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Not098** [instaloader/instaloader#2051]
![IMG_20230815_134349_570](https://github.com/instaloader/instaloader/assets/88423723/7774ac75-4df4-46ab-a4da-5a5027492751)
Using in termux don't know what happened

**Comment by St0RM53** [comment]
same problem here

**Comment by stephanvierkant** [comment]
Please don't use screenshots to share error messages. It makes searching for similar issues impossible (something you didn't do in the first place: there are already several similar issues).

**Comment by sapphirepro** [comment]
I have the same problem. Any idea how to fix that? Also reports a problem is getting shared data and unable to download anything at all using login

**Comment by ScroungerTT** [comment]
Same issue is still reported. Look here #2044

**Comment by stephanvierkant** [comment]
This is a great explanation why images are not a good idea to share code/error messages: [https://meta.stackoverflow.com/questions/285551/why-should-i-not-upload-images-of-code-data-errors/285557#285557](https://meta.stackoverflow.com/a/285557/1405981)

@Not098 This is clearly is duplicate issue, can you please close this issue? Thanks!
