### ISSUE TITLE
JSON QUERY // invalid username

### ISSUE THREAD

**Issue by iagomota2** [instaloader/instaloader#2052]
Hi, im new here

i used few times and now its not working

![image](https://github.com/instaloader/instaloader/assets/69031197/30acb04d-c221-41a6-b34f-7bf696721072)

**Comment by stephanvierkant** [comment]
Please don't use screenshots to share error messages.

**Comment by iagomota2** [comment]
> 

Hi. Sorry, i didnt know about.

**Comment by Showmaster3000** [comment]
@stephanvierkant  I'm not sure if its a duplicate of #2044. 
First thing: the word `profile` has to be omitted. Just use `instaloader downloadthisprofile`.

**Comment by makako-dev** [comment]
Make sure you do not have any trailing white spaces after the username. :)
