### ISSUE TITLE
The cover image download feature downloads the wrong image.

### ISSUE THREAD

**Issue by AltanOzkan** [instaloader/instaloader#2053]
The cover image download feature downloads the wrong image. It downloads the old cover photo that was changed a long time ago.

**Comment by IcyConfidential** [comment]
Same issue encountered here, the highlight covers downloaded are not correct. Instaloader seems to be pulling the covers from the highlights themselves rather than the actual image.

**Comment by powerfulzeus** [comment]
Same issue still persisting, the highlight covers downloaded are not correct. Instaloader seems to be pulling the covers from the highlights themselves rather than the actual image.
