### ISSUE TITLE
Get tagged posts returns ConnectionException: JSON Query to graphql/query: HTTP error code 401.

### ISSUE THREAD

**Issue by Juapatral** [instaloader/instaloader#2057]
**Describe the bug**
Getting tagged post from profile using Python API keeps returning ConnectionException: JSON Query to graphql/query: HTTP error code 401.

**To Reproduce**
```
from instaloader import Instaloader, Profile, Post

L = Instaloader()

profile = Profile.from_username(L.context, "vivebeauty_")

profile.get_tagged_posts()
```

**Expected behavior**
Should return an NodeIterator object with the tagged posts.

**Error messages and tracebacks**
`---------------------------------------------------------------------------
ConnectionException                       Traceback (most recent call last)
~\anaconda3\lib\site-packages\instaloader\instaloadercontext.py in get_json(self, path, params, host, session, _attempt, response_headers)
    406             if resp.status_code != 200:
--> 407                 raise ConnectionException("HTTP error code {}.".format(resp.status_code))
    408             is_html_query = not is_graphql_query and not "__a" in params and host == "www.instagram.com"

ConnectionException: HTTP error code 401.

During handling of the above exception, another exception occurred:

ConnectionException                       Traceback (most recent call last)
~\anaconda3\lib\site-packages\instaloader\instaloadercontext.py in get_json(self, path, params, host, session, _attempt, response_headers)
    406             if resp.status_code != 200:
--> 407                 raise ConnectionException("HTTP error code {}.".format(resp.status_code))
    408             is_html_query = not is_graphql_query and not "__a" in params and host == "www.instagram.com"

ConnectionException: HTTP error code 401.

During handling of the above exception, another exception occurred:

ConnectionException                       Traceback (most recent call last)
~\anaconda3\lib\site-packages\instaloader\instaloadercontext.py in get_json(self, path, params, host, session, _attempt, response_headers)
    406             if resp.status_code != 200:
--> 407                 raise ConnectionException("HTTP error code {}.".format(resp.status_code))
    408             is_html_query = not is_graphql_query and not "__a" in params and host == "www.instagram.com"

ConnectionException: HTTP error code 401.

The above exception was the direct cause of the following exception:

ConnectionException                       Traceback (most recent call last)
<ipython-input-4-5d9edb9f1df5> in <module>
      5 profile = Profile.from_username(L.context, "vivebeauty_")
      6 
----> 7 profile.get_tagged_posts()

~\anaconda3\lib\site-packages\instaloader\structures.py in get_tagged_posts(self)
   1066         .. versionadded:: 4.0.7"""
   1067         self._obtain_metadata()
-> 1068         return NodeIterator(
   1069             self._context,
   1070             'e31a871f7301132ceaab56507a66bbb7',

~\anaconda3\lib\site-packages\instaloader\nodeiterator.py in __init__(self, context, query_hash, edge_extractor, node_wrapper, query_variables, query_referer, first_data, is_first)
     91             self._best_before = datetime.now() + NodeIterator._shelf_life
     92         else:
---> 93             self._data = self._query()
     94         self._first_node: Optional[Dict] = None
     95         self._is_first = is_first

~\anaconda3\lib\site-packages\instaloader\nodeiterator.py in _query(self, after)
    101         try:
    102             data = self._edge_extractor(
--> 103                 self._context.graphql_query(
    104                     self._query_hash, {**self._query_variables, **pagination_variables}, self._query_referer
    105                 )

~\anaconda3\lib\site-packages\instaloader\instaloadercontext.py in graphql_query(self, query_hash, variables, referer, rhx_gis)
    483                 tmpsession.headers['x-instagram-gis'] = x_instagram_gis
    484 
--> 485             resp_json = self.get_json('graphql/query',
    486                                       params={'query_hash': query_hash,
    487                                               'variables': variables_json},

~\anaconda3\lib\site-packages\instaloader\instaloadercontext.py in get_json(self, path, params, host, session, _attempt, response_headers)
    448                     if is_other_query:
    449                         self._rate_controller.handle_429('other')
--> 450                 return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
    451                                      response_headers=response_headers)
    452             except KeyboardInterrupt:

~\anaconda3\lib\site-packages\instaloader\instaloadercontext.py in get_json(self, path, params, host, session, _attempt, response_headers)
    448                     if is_other_query:
    449                         self._rate_controller.handle_429('other')
--> 450                 return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
    451                                      response_headers=response_headers)
    452             except KeyboardInterrupt:

~\anaconda3\lib\site-packages\instaloader\instaloadercontext.py in get_json(self, path, params, host, session, _attempt, response_headers)
    438                     raise QueryReturnedNotFoundException(error_string) from err
    439                 else:
--> 440                     raise ConnectionException(error_string) from err
    441             self.error(error_string + " [retrying; skip with ^C]", repeat_at_end=False)
    442             try:

ConnectionException: JSON Query to graphql/query: HTTP error code 401.`

**Instaloader version**
>>> instaloader --version
4.10

**Comment by princetechs** [comment]
its may be,bacause of you use it in cloud colab(like google colab or jupitor) or in any cloud server,i am facing the same, i think the instagram server detect use , may be we need header change.
