### ISSUE TITLE
downloading random profiles fails

### ISSUE THREAD

**Issue by codeman101** [instaloader/instaloader#2058]
**Describe the bug**
Downloading doesn't work for all profiles. I hit one where it said the profile didn't exist even though it did and was public. (see below)

**To Reproduce**
instaloader wendywilkes2022

**Expected behavior**
For it to download everything like it did with all other profiles I tried.

**Error messages and tracebacks**
Error message: wendywilkes2022: Profile wendywilkes2022 does not exist.

Errors or warnings occurred:
wendywilkes2022: Profile wendywilkes2022 does not exist.

**Instaloader version**
4.18

**Additional context**
Here's a link to the profile as proof of existence https://www.instagram.com/wendywilkes2022/

**Comment by GijsSi** [comment]
Do you have the code?

**Comment by Showmaster3000** [comment]
What is version 4.18? Did you mean 4.1.8? Then its totally outdated! Update to the latestet version and try again.

**Comment by codeman101** [comment]
sorry I misread it I meant 4.10

**Comment by bschollnick** [comment]
Also having a similar problem (?) with Abbydarkstar's profile on instagram...(https://www.instagram.com/abbydarkstar/)

JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Fatal error: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.

This occurs if logged in or not...

This is with Instaloader v4.10
