### ISSUE TITLE
 Potential Malicious Detection for instaloader.exe

### ISSUE THREAD

**Issue by crossdefalt** [instaloader/instaloader#2060]
Issue Description
I came across a concerning situation while working with the instaloader.exe file. Upon scanning the file using VirusTotal, the results indicated the presence of several potential malware detections from different antivirus engines. This is quite alarming and needs to be addressed to ensure the safety and integrity of the file.

Detected Malware:
Bkav Pro: W32.AIDetectMalware.64
Cynet: Malicious (score: 100)
McAfee-GW-Edition: BehavesLike.Win64.Backdoor.wc
SecureAge: Malicious
Trellix (FireEye): Generic.mg.93b12db8d80368eb
Acronis (Static ML): Undetected unusual detection

Additional Information
I will attach an image of the VirusTotal scan results for reference. Your expertise and assistance in resolving this issue are greatly appreciated. Let's work together to ensure the safety of the instaloader.exe file and maintain the integrity of this project.
![Screenshot (1)](https://github.com/instaloader/instaloader/assets/106070707/c09ebb0a-28e3-4ac9-981d-81bbae9d1ec4)

**Comment by Showmaster3000** [comment]
As already described in #1432 and #1002 this is a false positive.
The complete source available in this repo, you can build it at your own if you want.

**Comment by crossdefalt** [comment]
i think i will stick with virtual machine until it get fixed
