### ISSUE TITLE
only retrieves around 9,000 comments

### ISSUE THREAD

**Issue by guestprogrammer10** [instaloader/instaloader#2066]
For posts with over 10,000 comments, it only retrieves around 9,000 comments as output and does not continue. It also does not produce any errors.

**Comment by DylanFromm** [comment]
I have also been running into this, seems a bit random. I always get a good chunk of a posts comments, but will eventually exit out with like 1000/1800 comments, or 9000/17000 comments etc..

may be related, what does the comment in node iterator's count  function mean?
  """The ``count`` as returned by Instagram. This is not always the total count this iterator will yield."""
in that what's the reason for the discrepancy, does it hit a page limit?

**Comment by galileor97** [comment]
Has everyone tried to identify this bug yet?
