### ISSUE TITLE
How to create an alternative account and not lose it?

### ISSUE THREAD

**Issue by procobain** [instaloader/instaloader#2067]
I want to have an account with a different name and photos than me, I want to add some people. 

I manage to have an SMS number to register, I post photos and interact with random people, but after a while Instagram blocks my account and asks me to send a photo holding a piece of paper with something written on it, how to have an account without it being blocked? Is there any other method?

**Comment by kooozie** [comment]
The SMS number you're using and/or IP can be flagged. You should limit the amount of actions you perform on the account for the first few days, and gradually increase the number of actions each day. Use reasonable delays between action. Avoid using the browser, as the app gives an increase trustscore. Lastly, add 2FA to the account.. this will increase the trustscore aswell, and from my experience never have an issue with having to take the selfie when doing these steps with new accounts.
