### ISSUE TITLE
 get all the comments in a single post by URI ?

### ISSUE THREAD

**Issue by juanfelizari** [instaloader/instaloader#207]
why i cannot get the comments de pictures by URI ? and why i cannot get of the a picture?
This really intrigues me, about the code and the instaloader , the project it's amazing, really, admire the work

**Comment by JOCILEUDO** [comment]
Hello, Juan, looking at all the documentation I concluded that one of the ways to get a certain post can be from the shortcode that comes incapsulated in the url, so just separate the shortcode and then run the search query.
installoader -- -{shortcode}

To bring together the comments of the publication use the command
--comments

joining the two looks like this:
installoader --coments - - {shortcode}
