### ISSUE TITLE
Unable to download using code snippet in putty ubuntu but works in local [ConnectionException: JSON Query to graphql/query: HTTP error code 401]

### ISSUE THREAD

**Issue by Devaryalakhanpal** [instaloader/instaloader#2071]
I'm using the following code snippet in my python program which downloads videos to aws. And I'm able to download successfully in my local on visual studio but when I do the same in putty ubuntu server I get **instaloader.exceptions.ConnectionException: JSON Query to graphql/query: HTTP error code 401.** I've imported instaloader==4.10

I'm not able to tell if it's because of some cookies that got saved in local but aren't in the putty server maybe?

Here's the code snippet:
```
async def instLoad(from_num,link):
    I = Instaloader(
        filename_pattern="video", download_pictures=False, save_metadata=False, post_metadata_txt_pattern='',
    )
    id_pattern = r"(/p/|/reel/)([a-zA-Z0-9_-]+)/"
    match = re.search(id_pattern, link)
    if match:
        id = match.group(2)
        post = Post.from_shortcode(I.context, id)
#[CHANGED] cipher.py in (Python311\Lib\site-packages\pytube) line 30: var_regex = re.compile(r"^\$*\w+\W")
        video_url = post.video_url
        r = requests.get(video_url, stream=True)

        random_string = ''.join(random.choice(string.ascii_letters) for _ in range(4))
        s3_file = from_num+random_string+'.mp4'
        s3_client.upload_fileobj(r.raw, bucket, s3_file, ExtraArgs={
            'ContentType': 'video/mp4',
            'ContentDisposition': 'inline'
        })
        video_link = f"https://{bucket}.s3.amazonaws.com/{s3_file}"
    return video_link
```
Here's the error: 

> File "/home/ubuntu/.local/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 405, in get_json
>     raise ConnectionException("HTTP error code {}.".format(resp.status_code))
> instaloader.exceptions.ConnectionException: HTTP error code 401.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/asgiref/sync.py", line 277, in _call_
>     return call_result.result()
>   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
>     return self.__get_result()
>   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
>     raise self._exception
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/asgiref/sync.py", line 353, in main_wrap
>     result = await self.awaitable(*args, **kwargs)
>   File "/home/ubuntu/app.py", line 151, in bot
>     video_link = await instLoad(from_number, incoming_msg)
>   File "/home/ubuntu/app.py", line 31, in instLoad
>     post = Post.from_shortcode(I.context, id)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/instaloader/structures.py", line 135, in from_shortcode
>     post._node = post._full_metadata
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/instaloader/structures.py", line 252, in _full_metadata
>     self._obtain_metadata()
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/instaloader/structures.py", line 239, in _obtain_metadata
>     pic_json = self._context.graphql_query(
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 483, in graphql_query
>     resp_json = self.get_json('graphql/query',
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 448, in get_json
>     return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 448, in get_json
>     return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 438, in get_json
>     raise ConnectionException(error_string) from err
> instaloader.exceptions.ConnectionException: JSON Query to graphql/query: HTTP error code 401.

**Comment by QingsiLiu** [comment]
I also encountered the same problem. I guessed that too frequent visits caused the IP to be officially banned by Instagram. I changed the IP and the problem was solved.

**Comment by QingsiLiu** [comment]
If your aws fixed ip is banned by ins, it will be difficult to do it. I also initiated the request on the Google server. The difference is that I used a dynamic ip as a proxy so that it can be successful. Otherwise, there is nothing I can do.

**Comment by Devaryalakhanpal** [comment]
Okay, from what I've found the error is due to the following reason:
I logged in to instagram on my browser at some point, the code ran on local and Instaloader automatically downloaded certain cookies which it used for the session. Later when I logged out it still had the cookies and could use them.

Obviously since there is no browser on the putty/aws etc. it can't get the cookies to use in session file. Maybe there is way to find where it saves the cookie and manually putting that file in aws/putty server.

I'm not sure if this is why, because I found this out by deleting the instagram account, since the account was deleted of course the cookies of that account are going to be useless.

**Comment by Devaryalakhanpal** [comment]
> I also encountered the same problem. I guessed that too frequent visits caused the IP to be officially banned by Instagram. I changed the IP and the problem was solved.

If multiple visits was the reason it wouldn't work in my local as well, not just the putty ubuntu server.

**Comment by Devaryalakhanpal** [comment]
> I am running this on AWS instance, it works fine in local but not in aws, any solution? I tried updating header but no luck. Any help will be appreciated. Let me know if I can use my static IP and get this running.

Best advise I can give is try to look for a way to find the place it stored the cookies sessionfile and add it to the aws instance?

**Comment by felp99** [comment]
Also having the same error. Someone used VPN to trick this error? It's ok?
