### ISSUE TITLE
Extending Instaloader to collections: finding query hash?

### ISSUE THREAD

**Issue by Intimague** [instaloader/instaloader#2073]
I'm interested in extending Instaloader so that users can download their saved posts by collection. For example, I've got ~15 collections, each with 100+ posts. `Profile.get_saved_posts()` is good, but as far as I can tell it doesn't have any functionality to sort by collection. 

Adding a 'collection' structure to wrap nodes returned by `NodeIterator` shouldn't be a big deal for me, and I think I can figure out the edge extractor. However, I spent all day yesterday digging around in my network tab trying to find a query hash of any kind (even the ones that are already hardcoded into Instaloader) with no luck. Old guides on finding query hashes like this:
https://github.com/mineur/instagram-parser/blob/master/docs/setup.md#how-to-get-your-query-hash-old-query-id
seem to be out of date, as those urls are nowhere to be found.

I tried to compare with the tagged posts page, and the url that loads the relevant JSON there ([edge_user_to_photos_of_you]) now takes the format `www.instagram.com/graphql/query/?doc_id={NUMBER}&variables={'id', 'after', 'first'}`. No sign of a query hash anywhere.

However, the various `Profile.get_*_posts()` methods all work, so clearly query hashes are still in use.

The URL that produces a JSON of collection info is `https://www.instagram.com/api/v1/collections/list/?collection_types=%5B%22ALL_MEDIA_AUTO_COLLECTION%22%2C%22MEDIA%22%2C%22AUDIO_AUTO_COLLECTION%22%5D&get_cover_media_lists=true&include_public_only=0&max_id=`.

**Comment by Abeldewit** [comment]
Hi, were you able to figure this out? I also found this thread: https://github.com/instaloader/instaloader/issues/544 where people expressed interest in accessing collections. I'm at the same crossroads as you. 

I think the steps would be:
1. Generate a query (with hash?) that is able to retrieve a profile's collections using: `https://i.instagram.com/api/v1/collections/list` 
2. Map the collection IDs to their names for easy selection in the python module/CLI
3. Query the saved posts
4. In the NodeIterator only yield posts that adhere to the collection ID

This would greatly help a project I'm working on so if you or anyone else could point me in the right direction I'd love to contribute to this project!

**Comment by Intimague** [comment]
@Abeldewit Nope, no luck. Admittedly I didn't spend too long on it because I'm not too sure where to start poking around. Could be I'm looking in the wrong place.

Hopefully someone more familiar with the Facebook API happens upon this.
