### ISSUE TITLE
download reels 

### ISSUE THREAD

**Issue by Floppaboppa** [instaloader/instaloader#2076]
how do i download reels? in the documentation I couldn't find an option to download the reels from a profile

**Comment by YisusChrist** [comment]
Before opening a new issue, please ensure you have reviewed the [Contribution guide lines](https://instaloader.github.io/contributing.html) and checked for existing issues or discussions related to your question or bug report.

If you take a little reseach time, you will find #1938, #1745 and #812 where there are a lot of explanations.

**TL;DR**
Currently, the project does not support fetching 'pure reels', it only works with the reels that are visible in the list of posts on a given profile. To download the full set of reels from https://instagram.com/username/reels I highly recommend other open source projects as a workaround like [gallery-dl](https://github.com/mikf/gallery-dl) which currently provides support for this functionality.

In my current workflow,I use **instaloader** to download media information from profiles, and **gallery-dl** exclusively for downloading reels.
