### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by kooozie** [instaloader/instaloader#2081]
I'm using the latest instaloader, but when I attempt to login after the password, I recieve the following: 

JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Fatal error: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.

Is this because the account is using 2FA?

**Comment by KiranZafar23** [comment]
I'm also facing the same issue
