### ISSUE TITLE
I am not able to login with instaloader

### ISSUE THREAD

**Issue by nawar-unxd** [instaloader/instaloader#2084]
**Not able to login**
I am trying to use login(username, password) or interactive_login(username), however both of them are not working

**Here is my log after running these functions**
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Traceback (most recent call last):
instagram-scraper/venv/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 410, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
instagram-scraper/venv/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 410, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):instagram-scraper/venv/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 410, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
instagram-scraper/instagram_client.py", line 19, in <module>
    save_session(username, password)
instagram-scraper/instagram_client.py", line 7, in save_session
    L.login(username, password)
instagram-scraper/venv/lib/python3.9/site-packages/instaloader/instaloader.py", line 651, in login
    self.context.login(user, passwd)
instagram-scraper/venv/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 259, in login
    csrf_json = self.get_json('accounts/login/', {}, session=session)
instagram-scraper/venv/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 448, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
instagram-scraper/venv/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 448, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
instagram-scraper/venv/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 436, in get_json
    raise QueryReturnedNotFoundException(error_string) from err
instaloader.exceptions.QueryReturnedNotFoundException: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.

**4.10**

**Comment by i-was-lost** [comment]
Did you try the Firefox session token workaround? Look [here](https://instaloader.github.io/troubleshooting.html#login-error).

**Comment by dstansb** [comment]
Firefox workaround does appear to work for some users https://github.com/instaloader/instaloader/issues/2062
