### ISSUE TITLE
Profile.get_followers() and Profile.get_followees() returning empty list

### ISSUE THREAD

**Issue by peetceenatoo** [instaloader/instaloader#2085]
Instastalk 4.10
Python 3.10.2
Windows

This is my script: 

```
L = instaloader.Instaloader( )
L.load_session_from_file(...)
p = Profile.from_username(L.context, ...)

# so far everything works as p contains the Profile instance

try:
      followers = p.get_followers()
except Exception as e:
      print("Ex")
      sys.exit()

try:
      followees = p.get_followees()
except Exception as e:
      print("Ex")
      sys.exit()
```

The execution does not stop, just followers and followees are both empty.

**Comment by sarvagyaah** [comment]
hi
how did you able to login and use instaloader
i am getting this error:
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
i am login using L.login(username,password)
please help

**Comment by nebula0225** [comment]
Is account public?
