### ISSUE TITLE
Login Error JSON Query to accounts/login/: Could not find "window._sharedData" in html response.

### ISSUE THREAD

**Issue by sarvagyaah** [instaloader/instaloader#2086]
import instaloader
L = instaloader.Instaloader()
L.login('username','password')

Error:
JSON Query to accounts/login/: Could not find "window._sharedData" in html response.[retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

Please fix this issue 
is there any alternative to instaloader liabrary 
please fix i need urgently

**Comment by EveryDirection** [comment]
+1, issue confirmed. Issue #2084 seems related. But I never had this problem before today; Instaloader was PREVIOUSLY working fine until today.
