### ISSUE TITLE
HD profile picture (HTTP redirect, HTTP error code 301)

### ISSUE THREAD

**Issue by redcupperboi** [instaloader/instaloader#209]
I'm using the latest version of Instaloader (4.1.1).

My script is:

instaloader --login=username --password=password --geotags --comments --stories --no-compress-json --max-connection-attempts=0 --fast-update [usernamehere]

I run this script everyday and never have an issue. This morning I'm getting hit with the following (on any account I try):

HTTP redirect from https://i.instagram.com/api/v1/users/[usernumberhere]/info/ to https://www.instagram.com/accounts/login/?next=/api/v1/users/[usernumberhere]/info/
JSON Query to api/v1/users/[usernumberhere]/info/: HTTP error code 301. [retrying; skip with ^C]

I tried waiting a few hours but got the same error. Tried restarting my computer, clearing all cookies etc. Nothing seems to work.

**Comment by n1amr** [comment]
I think this happens when instaloader tries to download profile pic anonymously. You may disable downloading profile pic temporarily in instaloader/instaloader.py line 829 until it gets fixed.

**Comment by a1johnson** [comment]
If I use "--no-profile-pic" everything else still works.

I tried manually visiting https://i.instagram.com/api/v1/users/[userid]/info/ in a browser and I get the same redirect to https://www.instagram.com/accounts/login/?next=/api/v1/users/[userid]/info/. It doesn't matter if I'm previously logged in or not.

**Comment by aandergr** [comment]
At the moment, Instaloader fails to obtain the link to the highest-quality version of the profile picture because the endpoint used in `Profile._iphone_struct` has been removed. However, Instaloader falls back to a lower quality version of the profile picture.

**Comment by i-cant-git** [comment]
I only get this error for profile pics.

```
JSON Query to api/v1/users/123456789/info/: HTTP error code 301. Unable to fetch high quality profile pic.
```

**Comment by neeos** [comment]
instadp.com got their full profile res pictures working

**Comment by aandergr** [comment]
> instadp.com got their full profile res pictures working

Just tried it, and no: It is the same 320x320 px version which Instaloader downloads.

**Comment by neeos** [comment]
after loading the profile, try clicking on the picture first, then the download button

**Comment by neeos** [comment]
@aandergr
after loading the profile, try clicking on the picture first, then the download button

**Comment by aandergr** [comment]
Ah, indeed!

**Comment by piggaruolo** [comment]
Same problem , any updates?

**Comment by aandergr** [comment]
Unfortunately no updates. Until we encounter a new way to get the HD profile picture, Instaloader will download a low-resolution version of profile pictures; the Error 301 message has been removed.
