### ISSUE TITLE
Can I use instaloader with proxy?

### ISSUE THREAD

**Issue by sssyrbu** [instaloader/instaloader#2094]
Hello everyone, so the issue is that I can't access instagram from my region, and I need to use either VPN or proxy.
And my simple program doesn't work. So is there a way I can use proxy with instaloader? Thanks.

```
import instaloader
 
# Creating an instance of the Instaloader class
bot = instaloader.Instaloader()
 
# Loading the profile from an Instagram handle
profile = instaloader.Profile.from_username(bot.context, 'cristiano')
print(profile)
```

**Comment by abhranil26** [comment]
yes!
here are some references

https://github.com/instaloader/instaloader/pull/174#issuecomment-577011167
https://stackoverflow.com/questions/8287628/proxies-with-python-requests-module
https://github.com/instaloader/instaloader/issues/459

**Comment by berbunda** [comment]
Can I use proxy in standalone utility?

**Comment by puzanov** [comment]
> Can I use proxy in standalone utility?

what do ya mean?

**Comment by berbunda** [comment]
> what do ya mean?
I mean to write something like: --proxy socks5://127.0.0.1:2080 in the keys (options) to the Instaloader executable file to proxy requests to Instagram due to its blocking in Russia. But I solved the problem using the Proxifier software

**Comment by puzanov** [comment]
@berbunda actually it's quite easy, just define the env var before calling the instance of instaloader
```python
os.environ['https_proxy'] = "http://proxy.server"
```

**Comment by xxyy-leo** [comment]
Change the os proxy works fine. But I have have other script working on the same server, if change the server proxy then everything will use proxy. How can I only instaloader is using the proxy?
Thanks,
