### ISSUE TITLE
python login drops after ~1 hour of session

### ISSUE THREAD

**Issue by alxkvx** [instaloader/instaloader#2097]
Hello, I am using python module to fetch posts of specific username ~ once per 30 mins. 

firstly, main auth method  `L.login(INST_login, INST_passw)` does not work, it always show error:
```
raise ConnectionException("Login: Checkpoint required. Point your browser to "
instaloader.exceptions.ConnectionException: Login: Checkpoint required. Point your browser to https://www.instagram.com...
```

instead i am using [615_import_firefox_session.py] script to import session file and then use `L.load_session_from_file(INST_login, session_file)`

after that it allows me to download posts and stories, however after ~ 6-7 attempts of check updates (download last posts) whithin 2-3 hours, it fails with errors:

```
HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=estethic to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
...
JSON Query to graphql/query: ('Connection aborted.', HTTPException('got more than 100 headers')) [retrying; skip with ^C]
JSON Query to graphql/query: ('Connection aborted.', HTTPException('got more than 100 headers')) [retrying; skip with ^C]
2023-10-30 06:05:41,121 asyncio ERROR Task exception was never retrieved
```
or:
```
ConnectionException: JSON Query to graphql/query: HTTP error code 401.
Traceback (most recent call last):
  File "/var/www/bots/instagram_parser/lib/python3.9/site-packages/instaloader/instaloadercontext.py", line 405, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 401.
```
so every 2-3 hours i have to go again to mozilla browser, re-login, save cookies and process 615_import_firefox_session.py over again.

so i have a few question here please:

1. what do i do wrong , why does it log me off so fast even when i use session file? any body else experience same issues?

2. how may i automate the process of getting cookies from mozzila browser? could anyone suggest here please any practice on ubuntu w/o gui? maybe using selenuim or anything else? thank you.

**Comment by alxkvx** [comment]
so looks like it is some instagram detection algo,  i set to check posts/stories with frequency > 2h, and it is working ok

**Comment by nebula0225** [comment]
Instagram is catching macro action

**Comment by alxkvx** [comment]
year checking not offer than 2hours, works ok for the last 3 days.

**Comment by yarodevuci** [comment]
@alxkvx what do use to check posts/stories? can you throw an example?

**Comment by alxkvx** [comment]
> @alxkvx what do use to check posts/stories? can you throw an example?

`L.download_post(post, target=f"{username}-post-{shortcode}")`

and 

`L.download_storyitem(item, f'{username}-story-{shortcode}')`

**Comment by yarodevuci** [comment]
> > @alxkvx what do use to check posts/stories? can you throw an example?
> 
> `L.download_post(post, target=f"{username}-post-{shortcode}")`
> 
> and
> 
> `L.download_storyitem(item, f'{username}-story-{shortcode}')`

@alxkvx are you always using same username?

**Comment by yarodevuci** [comment]
Ok that's total BS, with downloading and watching stories. Session is still getting suspended and Instaloader returns error 403...

**Comment by yarodevuci** [comment]
anyone??

**Comment by alxkvx** [comment]
> anyone??

what is your specific issue?
