### ISSUE TITLE
Problem with using --latest-stamps

### ISSUE THREAD

**Issue by Duong-Vux** [instaloader/instaloader#2100]
Is it only me or  --latest-stamps normally not work while download highlights?
I'm using `instaloader --latest-stamps --no-captions --no-metadata-json --no-compress-json --stories --highlights --login=myname targetname` in window cmd. I notice --latest-stamps works great with posts and stories but fail to skip highlights. 
Do you have any way to make it work?

**Comment by Showmaster3000** [comment]
as written in the documentation:

> Only works for media associated with a specific profile, and that is returned in chronological order: profile posts, profile stories, profile IGTV posts and profile tagged posts.

source: https://instaloader.github.io/cli-options.html#cmdoption-latest-stamps
