### ISSUE TITLE
[python] how to download posts without login ?

### ISSUE THREAD

**Issue by alxkvx** [instaloader/instaloader#2103]
Hi, i am using python module to download posts:

```
L = instaloader.Instaloader()

profile = instaloader.Profile.from_username(L.context, username)
for post in profile.get_posts():
        L.download_post(post, target=f"{username}-post")
```

however it fails with use login error:
exception=LoginRequiredException('Redirected to login page. Use --login.')>

as we know checking public account posts does not require to login,  how to check posts using instaloader without login?

**Comment by mauronr** [comment]
Instagram requires authentication after too much activity with unauthenticated sessions. From my experience, apparently Instagram flags the IP address and will require authentication for almost everything after that IP did has too much activity with unauthenticated sessions.  You can see this happening with a browser, using incognito mode.

**Comment by alxkvx** [comment]
ok, i admit that, so what is the save interval of checking posts and stories? to not get flagged?  i am checking it once per 3 hours

**Comment by mauronr** [comment]
Again in my experience, it's not as simple as just "running and pausing a bit". Instagram's automation detection is quite sophisticated, as one would expect. As an example, after having tested experimented quite a lot, my IP address has  probably been flagged for good and I see Instagram is much more sensitive to repetitive activity from my network than it is for other networks. Using proxies to connect are one the way to distribute the activity and avoid blocks.

**Comment by alxkvx** [comment]
i got your idea, thanks, i also thinking about using proxies.
