### ISSUE TITLE
It doesn't download in HI-RES (1440p)

### ISSUE THREAD

**Issue by bekam11** [instaloader/instaloader#2104]
The software is downloaded the images in **1080x1349** , but the best resolution available is **1440x1800**.

Please, is it a bug?... how can I download the images in 1440p?.

Thanks.

**Comment by nf24eg** [comment]
same here , not download HD

**Comment by oliverjrose99** [comment]
can you link to a post in 1440p for testing please

**Comment by aandergr** [comment]
Please provide a reproducible example, version used, etc.
