### ISSUE TITLE
How to import cookies using json file?

### ISSUE THREAD

**Issue by alxkvx** [instaloader/instaloader#2106]
Hi,

i am using selenium to automate login process to instagram, then i would like to import cookies into instaloader that i get from selenium (json format).

i know that there is [615_import_firefox_session.py]  script, but it uses sqlite to import cookies from firefox sqlite file:

`cookie_data = conn.execute("SELECT name, value FROM moz_cookies WHERE host LIKE '%instagram.com'")`

i tried to convert json to dict() array and pass it to `instaloader.context._session.cookies.update(cookie_data)`  but it does not like that format.  so please advise in what format should i pass cookies.

**Comment by alxkvx** [comment]
ok, another question would be: how to create session file, if i have session_id from cookies?

**Comment by ekalin** [comment]
You could point the script to the cookies.sqlite file of the browser profile Selenium uses. By default I think it's a temporary profile, but you can configure it to use any directory for the profile.

**Comment by alxkvx** [comment]
i also see` .load_session()` method, how to pass session data to it? what data is mandatory, i assume login and session_id?
