### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by isPique** [instaloader/instaloader#2107]
**I think logging in with a username and password is impossible.**
Every time I attempt to log in with a username and password, I consistently encounter the following output:

```console
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
```

Therefore, I am logging in with the CSRF token and session ID, and it works fine.

here is the code:
```py
import instaloader

instance = instaloader.Instaloader()

# Personal account is not recommended. To use it, simply create a new account.
username = "YOUR INSTAGRAM USERNAME HERE"
password = "YOUR INSTAGRAM PASSWORD HERE"

instance.compress_json = False

# Check if you have a session file to load, if not, login using credentials
try:
    instance.load_session_from_file(username, "cookies.txt")

except FileNotFoundError:
    try:
        instance.login(username, password)

    except:
        # If login fails, load the session using sessionid and csrftoken (not recommended if you use VPN)
        instance.load_session(username, {"sessionid": "YOUR SESSION ID HERE", "csrftoken": "YOUR CSRFTOKEN HERE"})

# Save the session to a file for future use
instance.save_session_to_file("cookies.txt")
```

**Comment by sohang3112** [comment]
@isPique I'm having the same issue. How did you fix the issue??

**Comment by isPique** [comment]
> @isPique I'm having the same issue. How did you fix the issue??
Take a look at this [link](https://github.com/isPique/Instaloader-Scripts/). I explained it there.

**Comment by sohang3112** [comment]
@isPique I'm able to login with cookies. The problem is that cookies expire after some time, that's why I need to login with username and password to regenerate cookies.

**Comment by isPique** [comment]
@sohang3112 Idk bro. That's why I'm saying "I think logging in with a username and password is impossible.". The best thing you can do for now is to refresh and log in again when your cookies expire until this issue is fixed.

by the way, after a long time I tried `pip3 install --upgrade instaloader.` again and it worked. Give it a try.

```py
import instaloader

loader = instaloader.Instaloader()

loader.login(user="ANY_USERNAME_HERE", passwd="ANY_PASSWORD_HERE")
print("✅ 1- Logged in")
```
