### ISSUE TITLE
Attribute to return List[String] of followers and followees (faster)

### ISSUE THREAD

**Issue by felp99** [instaloader/instaloader#2110]
**Provide us a use case of the feature**
When inside the class Profile, is possible to access the list of followers or followees, but just the string. This would permit to see better the relations within users, create network visualisations, see who doesn’t follow you back and stuff.

**Describe the solution you'd like**
Ex: Profile.getListOfFollowers() -> ['foo', 'bar', 'cla']

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes, I can work on this.

**Comment by aandergr** [comment]
see https://instaloader.github.io/module/structures.html#instaloader.Profile.get_followees and https://instaloader.github.io/module/structures.html#instaloader.Profile.get_followers, use https://instaloader.github.io/module/structures.html#instaloader.Profile.username to get the username string.
