### ISSUE TITLE
to download specific period is not working

### ISSUE THREAD

**Issue by nf24eg** [instaloader/instaloader#2111]
to download specific period is not working, it not gives any result or errors.
is there a code that at least gives the option to choose the date of start scraping ?

**Comment by Showmaster3000** [comment]
Your report is incomplete. At least describe what you did and what you expected. The template for bug reports should help you.

**Comment by gamerlmfao** [comment]
https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period

**Comment by nf24eg** [comment]
> https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period

many thanks for your help, that's the code I tried but seems that I added it to the wrong file or misused it because of the not enough info and examples.
Thanks again

**Comment by nf24eg** [comment]
> https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period

many thanks for your help, that's exactly what I did, I used this code 

> Your report is incomplete. At least describe what you did and what you expected. The template for bug reports should help you.

for sorry that's exactly how I felt when I use the code :), too much information and options without explanations to most of it or enough examples of how to use it.
after all I use it as basic now. thank you for being giving a hand

**Comment by Kartik-Swt** [comment]
@nf24eg I have been facing the same issue. It doesn't throw any error; however, no post is downloaded. I also tried without the date filter. It worked for a few seconds, and then I got the following error - 
JSON Query to explore/tags/food/: HTTP error code 401. [retrying; skip with ^C]
JSON Query to explore/tags/food/: HTTP error code 401. [retrying; skip with ^C]

I tried getting a workaround by adding delays and multiple try and except blocks, but still, I got no progress.

**Comment by xialuoke4062** [comment]
encoun

> @nf24eg I have been facing the same issue. It doesn't throw any error; however, no post is downloaded. I also tried without the date filter. It worked for a few seconds, and then I got the following error - JSON Query to explore/tags/food/: HTTP error code 401. [retrying; skip with ^C] JSON Query to explore/tags/food/: HTTP error code 401. [retrying; skip with ^C]
> 
> I tried getting a workaround by adding delays and multiple try and except blocks, but still, I got no progress.

encountering the exact same problem...
