### ISSUE TITLE
hide or fix JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]

### ISSUE THREAD

**Issue by usgitAz** [instaloader/instaloader#2113]
hi i use quiet=True in  loader = instaloader.Instaloader but i see JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C] in output !! How can I prevent it from being displayed? 

also i use instaloader witout login and use http proxy to connect But it does not connect or connects with difficulty ! my code :

loader.context._session.proxies = {"http": "http://" + proxy, "https": "https://" + proxy}   -->  'http' : 'http://123.456.789.01:80 ' 
post = instaloader.Post.from_shortcode(loader.context, self.url.split("/")[-2])
 loader.download_post(post , target='post')
 
 I check my proxy list  and it works fine but i get this error again and again and again 
 how can fix my problems ?

**Comment by Showmaster3000** [comment]
Searching trough the issue list, there are some mentions which could answer your question.
First thing could be that instagram blocks one or more of the proxies you use.
Second: anonymous access to instagram is limited, so you have to login to continue (HTTP error 401 means unauthorized, see description on the web).

**Comment by RichardHeise** [comment]
The only way I've found to solve this was by logging in (I've created a new account just for scrapping, which was already flaged by instagram in a matter of minutes after some scrapping tests) and using this script I've found in other posts:

`#!/bin/python3

from argparse import ArgumentParser
from glob import glob
from os.path import expanduser
from platform import system
from sqlite3 import OperationalError, connect

try:
    from instaloader import ConnectionException, Instaloader
except ModuleNotFoundError:
    raise SystemExit("Instaloader not found.\n  pip install [--user] instaloader")

def get_cookiefile():
    default_cookiefile = {
        "Windows": "~/AppData/Roaming/Mozilla/Firefox/Profiles/*/cookies.sqlite",
        "Darwin": "~/Library/Application Support/Firefox/Profiles/*/cookies.sqlite",
    }.get(system(), "~/.mozilla/firefox/*/cookies.sqlite")
    cookiefiles = glob(expanduser(default_cookiefile))
    if not cookiefiles:
        raise SystemExit("No Firefox cookies.sqlite file found. Use -c COOKIEFILE.")
    return cookiefiles[0]

def import_session(cookiefile, sessionfile):
    print("Using cookies from {}.".format(cookiefile))
    conn = connect(f"file:{cookiefile}?immutable=1", uri=True)
    try:
        cookie_data = conn.execute(
            "SELECT name, value FROM moz_cookies WHERE baseDomain='instagram.com'"
        )
    except OperationalError:
        cookie_data = conn.execute(
            "SELECT name, value FROM moz_cookies WHERE host LIKE '%instagram.com'"
        )
    instaloader = Instaloader(max_connection_attempts=1)
    instaloader.context._session.cookies.update(cookie_data)
    username = instaloader.test_login()
    if not username:
        raise SystemExit("Not logged in. Are you logged in successfully in Firefox?")
    print("Imported session cookie for {}.".format(username))
    instaloader.context.username = username
    instaloader.save_session_to_file(sessionfile)

if __name__ == "__main__":
    p = ArgumentParser()
    p.add_argument("-c", "--cookiefile")
    p.add_argument("-f", "--sessionfile")
    args = p.parse_args()
    try:
        import_session(args.cookiefile or get_cookiefile(), args.sessionfile)
    except (ConnectionException, OperationalError, subprocess.CalledProcessError) as e:
        raise SystemExit("Error: {}".format(e))`
        
        
        
 Then, you have to login in instagram with Firefox opened. This solved the issue.

**Comment by alxkvx** [comment]
> also i use instaloader witout login and use http proxy to connect But it does not connect or connects with difficulty ! my code :
> 
> loader.context._session.proxies = {"http": "http://" + proxy, "https": "https://" + proxy} --> 'http' : 'http://123.456.789.01:80 ' post = instaloader.Post.from_shortcode(loader.context, self.url.split("/")[-2]) loader.download_post(post , target='post')
> 
> I check my proxy list and it works fine but i get this error again and again and again how can fix my problems ?

instaloader code does not support changing proxies variables. i would recommend using traditional way:
`os.environ['https_proxy'] = proxy`
