### ISSUE TITLE
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C] pscbrixton: JSON Query to graphql/query: HTTP error code 401.

### ISSUE THREAD

**Issue by nf24eg** [instaloader/instaloader#2117]
**Describe the bug**
after some downloads it gives this error 
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]

pscbrixton: JSON Query to graphql/query: HTTP error code 401.

**To Reproduce**
`instaloader --no-video-thumbnails --filename-pattern={date_utc:%Y%m%d%H%M%S}_UTC_ eye.on.palestine`

**Expected behavior**
the account have 39k file, I try to download what's in it (videos, meta, pictures) without duplicates

**Error messages and tracebacks**
I run the command, it downloads some items, then it display the words (exists) for those files which downloaded before, but then after awhile it the throw the above error 
 
**Instaloader version**
4.101
`instaloader --version` output.

**Additional context**

**Comment by alxkvx** [comment]
401 - means not authorized. so instagram does not allow frequent request without login. so try to  --login
