### ISSUE TITLE
Can not download in dir1/dir2

### ISSUE THREAD

**Issue by ehsansh84** [instaloader/instaloader#2118]
**Describe the bug**
When I want to download into `app/files/videos` with this command
            loader.download_post(post, target='app/files/videos')
It will create a folder named:  `app/files/videos`
I don't know how it is possible to have a folder containing `/` but it will happens.

**To Reproduce**

```
import instaloader

loader = instaloader.Instaloader()
profile = instaloader.Profile.from_username(loader.context, 'cook.mag')
print(f'Get posts from {profile.username}')
posts = profile.get_posts()

for post in posts:
    if post.is_video:  # Check if the post is a video
        loader.download_post(post, target='app/files/videos')

```

**Expected behavior**
A folder will be created with the name of: 'app/files/videos'
**Error messages and tracebacks**
No error 
**Instaloader version**
4.10.1

**Additional context**

**Comment by alxkvx** [comment]
use `Path` for that purpose:
```
from pathlib import Path

base_path = Path(f"{username}-posts")
target_path = base_path / shortcode
L.download_post(post, target=target_path)
```
