### ISSUE TITLE
Unable to Enter Password

### ISSUE THREAD

**Issue by SheAsuna** [instaloader/instaloader#2124]
I'm new to Instaloader and was just checkin' out it. But when I try to run it using --login, it doesn't allow me to enter password.

Here's a screen recording of the issue I'm facing:
> https://github.com/instaloader/instaloader/assets/92502151/ec91ec8c-1a05-40dd-80ed-97a5534b4f3a

**Comment by jaffster595** [comment]
> Also got error 401 after download finished when I used without --login
> 
> > ![Screenshot_2023-12-04-19-31-09-17_84d3000e3f4017145260f7618db1d683~3](https://private-user-images.githubusercontent.com/92502151/287727457-36f786d0-b752-4e6b-9a11-c6f1267aefce.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MTQ3MjgsIm5iZiI6MTcwMTcxNDQyOCwicGF0aCI6Ii85MjUwMjE1MS8yODc3Mjc0NTctMzZmNzg2ZDAtYjc1Mi00ZTZiLTlhMTEtYzZmMTI2N2FlZmNlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE4MjcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwOWYyZjQ3ZmZhZDU0ZmRjZDNkMWRmZTc2OTg1NzZlZmY3ODA0OWNiMzRiMTI5YjkwNTY4ZTAxMTEzYjE0NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.baGjMh5XBsl77BXEBBeUnlkp2UIpu3WynkiHcf-vDjw)

Are you using a VPN or connecting from a public location? I get a 401 error if I'm using my VPN. As soon as I disconnect, it works fine.

**Comment by SheAsuna** [comment]
> > Also got error 401 after download finished when I used without --login
> > > ![Screenshot_2023-12-04-19-31-09-17_84d3000e3f4017145260f7618db1d683~3](https://private-user-images.githubusercontent.com/92502151/287727457-36f786d0-b752-4e6b-9a11-c6f1267aefce.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MTQ3MjgsIm5iZiI6MTcwMTcxNDQyOCwicGF0aCI6Ii85MjUwMjE1MS8yODc3Mjc0NTctMzZmNzg2ZDAtYjc1Mi00ZTZiLTlhMTEtYzZmMTI2N2FlZmNlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE4MjcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwOWYyZjQ3ZmZhZDU0ZmRjZDNkMWRmZTc2OTg1NzZlZmY3ODA0OWNiMzRiMTI5YjkwNTY4ZTAxMTEzYjE0NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.baGjMh5XBsl77BXEBBeUnlkp2UIpu3WynkiHcf-vDjw)
> 
> Are you using a VPN or connecting from a public location? I get a 401 error if I'm using my VPN. As soon as I disconnect, it works fine.

Nope, I'm not using any VPN or custom DNS

**Comment by SheAsuna** [comment]
Anyone help #2124
