### ISSUE TITLE
Feature: Loading cookies from text

### ISSUE THREAD

**Issue by NutchapolSal** [instaloader/instaloader#2131]
**Provide us a use case of the feature**
As v4.11rc1 has `--load-cookies` from browsers, importing cookies in a text format should be available as a fallback for more tech-savvy people.

**Describe the solution you'd like**
An option that will take in cookies in some text format, exported from a browser using [one (or all) of these extensions probably](https://support.jdownloader.org/Knowledgebase/Article/View/account-cookie-login-instructions/3), either from the option parameter, stdin, or file.

**Describe alternatives you've considered**
`--login` with password have never worked for me, and the session can expire (from inactivity?) so had to manually create/update the file.
- Using Python REPL and the Instaloader Python API to manually modify and save the session object (very annoying)
- Using Python REPL and manually unpickling the session file, changing the values, and pickling it to file (annoying)
  - Why is the session file not in JSON or some text format? Would make doing these one-off changes to the file much easier.

**If the feature request is accepted, would you be willing to submit a pull request?**
Maybe.

**Comment by aandergr** [comment]
More tech-savvy people should simply use the methods of the Instaloader module, i.e. [instaloader.context.update_cookies](https://instaloader.github.io/module/instaloadercontext.html#instaloader.InstaloaderContext.update_cookies). I do not see what is very annoying about that.

**Comment by NutchapolSal** [comment]
I really feel like this should be implemented as a fallback option incase browser extraction fails in the future or the user isn't running a supported browser. It's weird how extracting cookies from a browser's database is supported but not reading them from a file.
