### ISSUE TITLE
Is it possible to retrieve a list of users who have liked a post on Instagram?

### ISSUE THREAD

**Issue by innicoder** [instaloader/instaloader#2132]
Is it possible to retrieve a list of users who have liked a post on Instagram?
The APIs don't work and I couldn't find any options to get the likers (in metadata) and/or comments.

**Comment by innicoder** [comment]
_Additional Note_

Is there a facebook alternative?

**Comment by saurabhtakle** [comment]
> Is it possible to retrieve a list of users who have liked a post on Instagram? The APIs don't work and I couldn't find any options to get the likers (in metadata) and/or comments.

Yes, you can get usernames of all likers and/or commenters. But, it is listing only recent 50 activities. 
assuming you know how to get posts.

for post in Profile.get_posts():
       likes = post.get_likes()
       comments = post.get_comments()
       
       likes.owner.username()
       comments.owner.username()

**Comment by innicoder** [comment]
Is it possible to get this with the `CLI` and have it written automatically in the `.json` it produces?
