### ISSUE TITLE
JSON Query to web/search/topsearch/: HTTP error code 401.

### ISSUE THREAD

**Issue by kb1ibt** [instaloader/instaloader#2135]
**Describe the bug**
Looks like Instagram changed their permissions again.
`JSON Query to web/search/topsearch/: HTTP error code 401.`

**To Reproduce**
`instaloader +args-group7.txt`
with the following sanitized args-group7.txt:
`--login=<username>
--dirname-pattern=profiles/{target}
--filename-pattern={date_utc:%Y}/{profile}_{date_utc}_UTC_{shortcode}
--sanitize-paths
--stories
--igtv
--no-video-thumbnails
--latest-stamps=/Users/shawn/instaloader/stamps-file
--abort-on=302,400,429
--no-iphone
--user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0"
-f/Users/me/instaloader/session-firefox
<user list>
`

**Expected behavior**
A cleaner list of possibly deleted or removed users at the end of the script run instead of a list of the "Errors or warnings occurred:"

**Error messages and tracebacks**
I noticed this initially at the end of the script when I was first writing up the bug report, but as I was digging in more, it looks like this was triggered during the output post an account being deleted:
`JSON Query to api/v1/users/web_profile_info/?username=<removed user>: 404 Not Found [retrying; skip with ^C]
JSON Query to api/v1/users/web_profile_info/?username=<removed user>: 404 Not Found [retrying; skip with ^C]
Profile <removed user> does not exist.
Trying again anonymously, helps in case you are just blocked.
JSON Query to api/v1/users/web_profile_info/?username=<removed user>: 404 Not Found [retrying; skip with ^C]
JSON Query to api/v1/users/web_profile_info/?username=<removed user>: 404 Not Found [retrying; skip with ^C]
JSON Query to web/search/topsearch/: HTTP error code 401. [retrying; skip with ^C]
JSON Query to web/search/topsearch/: HTTP error code 401. [retrying; skip with ^C]
JSON Query to web/search/topsearch/: HTTP error code 401.`
since it occured between "Logged in as <username>" and "Downloading 97 profiles:"

**Instaloader version**
4.10.2

**Additional context**
After checking Instagram directly, it looks like `<removed user>` was actually removed, not just them blocking me. Since I tried both on and off my current network, and both logged in and logged out.

**Comment by Vladimir-russian** [comment]
Got same error. it was working fine but now getting this error too

JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
francety: JSON Query to graphql/query: HTTP error code 401.

Errors or warnings occurred:
francety: JSON Query to graphql/query: HTTP error code 401.
PS E:\WINGBETA\F\Local Disk\Apps\Instaloader>

**Comment by IcyConfidential** [comment]
> Got same error. it was working fine but now getting this error too
> 
> JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C] JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C] francety: JSON Query to graphql/query: HTTP error code 401.
> 
> Errors or warnings occurred: francety: JSON Query to graphql/query: HTTP error code 401. PS E:\WINGBETA\F\Local Disk\Apps\Instaloader>

Getting this as well today, did it clear up for you since yesterday?

**Comment by RazyRo** [comment]
Same error for downloading Stories

**Comment by acedev666** [comment]
> Same error for downloading Stories

which api url u use for downloading stories ?

**Comment by RazyRo** [comment]
> > Same error for downloading Stories
> 
> which api url u use for downloading stories ?

Just on the command line, no () in below, just for info sake.
instaloader (profiles) --login just_scrolling_p --sessionfile session-(file name) --stories --no-profile-pic --no-posts --no-videos

**Comment by TheMissingPort** [comment]
Did you resolve?

**Comment by RazyRo** [comment]
> Did you resolve?

on cmd  instaloader --login (profile)
Loaded session from c:\users\Darth\appdata\local\temp/.instaloader-rohit/session-(profile).
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Fatal error: JSON Query to graphql/query: HTTP error code 401.

**Comment by kb1ibt** [comment]
Looks like a lot of the responses were referencing a completely separate issue because I specifically mention `web/search/topsearch/` not `graphql/query`
