### ISSUE TITLE
error in versioning the new version

### ISSUE THREAD

**Issue by Nilsonfsilva** [instaloader/instaloader#2137]
Hello!
I am a maintainer of the "installer on "Debian"
You released version 4.10.2 on December 9, 2023.

And released version 4.11rc1 released on November 15, 2023.

The way you named the version Version 4.11rc1, the debian tracking system is reading version 4.11rc1, as it would be higher than version 4.10.2.

This way I can't update the installaloader to version 4.10.2.

Would you agree with that?

**Comment by aandergr** [comment]
> The way you named the version Version 4.11rc1, the debian tracking system is reading version 4.11rc1, as it would be higher than version 4.10.2.

Version 4.11rc1 is higher than version 4.10.2.

> This way I can't update the installaloader to version 4.10.2.

Why?

Could you elaborate more on how the versioning causes problems for the debian package?

**Comment by Nilsonfsilva** [comment]
Hello, Alexandre Graff!
It's a pleasure talking to you!

Therefore, everything in Debain is automated. When we place a program in the repositories, we are committed to keeping it updated. For this we have this file https://salsa.debian.org/debian/instaloader/-/blob/debian/master/debian/watch?ref_type=heads

This "regex" is what makes this all work. And in this case it is as if version 4.11rc1 was superior to version 4.10.2.

Finally, what's new? is it 4.10.2?
If so, could you resolve this?

**Comment by Nilsonfsilva** [comment]
I'm seeing if I try to change the regex

**Comment by Nilsonfsilva** [comment]
Hey!
I managed to solve it.
I adjusted the regex to ignore pre-release.
Thanks!
