### ISSUE TITLE
Pinned posts are not correctly detected anymore, causes --latest-stamps to fail

### ISSUE THREAD

**Issue by ekalin** [instaloader/instaloader#2142]
**Describe the bug**
Pinned posts are not detected anymore by `Post.is_pinned`. The "pin" icon is also missing when opening the profile on the browser. This missing pin icon seems to be happening for a long time, but `Post.is_pinned` would correctly return whether the post was pinned, but now `Post.is_pinned` is returning `False` for all posts.

**To Reproduce**
See for example https://www.instagram.com/fefe/. The first three or four posts are older, then the regular chronological sequence starts. There's no real way to see the behavior, but with debugging statements one can see that `Post.is_pinned` returns `False` for those first items.

**Expected behavior**
`Post.is_pinned` should return `True` for pinned posts, so they can be treated specially when downloading only the newer posts.

**Instaloader version**
v4.10.2

**Additional context**
This is breaking `--latest-stamps` (kind of like when pinned posts were introduced): since the first post is older, no new posts are downloaded. It is also setting the date of the last downloaded post to the date of that old post, so when the problem is fixed some posts will be downloaded again.

Hopefully there's still some other flag in the post json structure that indicates whether it's a pinned post.

**Comment by ekalin** [comment]
This change seems to have happened sometime between December 18th (`--latest-stamps ` working as expected) and December 19th (no longer works).

**Comment by ekalin** [comment]
Looking at the node struct for a post, it seems `pinned_for_users` is not returned anymore, and I could not find any other property that indicates that it's a pinned post. But I would appreciate if someone else could take a look.

**Comment by ekalin** [comment]
If there is no way to know if a post is pinned, one solution I can think of is:

The first N posts are treated specially: if the post is older than the stored date, skip the post but continue the loop. After those firts N posts, resume normal behavior: stop when a post older than the stored date is found.

It seems that only 3 (or maybe 4) posts can be pinned, so N could be 4, or perhaps slightly more (5 or 6) just to be safe. But if IG decides that more posts can be pinned, it'll have to be changed.

One disadvantage is that if a user has, for example, 1 pinned post, 1 new post that should be downloaded, and then a series of older posts that have already been downloaded, the iteration will not stop at this third post (which would be the ideal situation), but only at the Nth post. Media won't be downloaded, but the metadata will have to be fetched. I believe this won't actually result in extra requests because 12 posts are queried at a time so the metadata is already available.

**Comment by aandergr** [comment]
Nice change and a good idea to simply disregard the fast-update and takewhile stop criterium for the first five posts. Thanks for also updating the docstring of `is_pinned`.

I only have two minor suggestions:

Only up to three posts can be pinned, so it would suffice to limit the check to the first three posts.

> You can pin up to 3 posts you share on Instagram to the top of your profile.

(https://help.instagram.com/318456537074409/?cms_platform=iphone-app)

Also, posts_download_loop is used for every target that yields post, not only for Profiles, whereas only for Profiles Posts can be pinned. I would prefer to have that criterium only for Profiles and for other targets it should still stop as soon as the first already-downloaded post is encountered.
