### ISSUE TITLE
Add a funtion to get the count of plays from Instagram Reels

### ISSUE THREAD

**Issue by ericmarquesf99** [instaloader/instaloader#2145]
**use case of the feature**

- **How could the user invoke the new function? ->** Just calling "reels_plays_count" function.
- **Which problem would it solve? ->** With the massive amount of Reels being created in Instagram, a function to get it's plays count (it's different from the current _video_views_count_ function) would be amazing cause it would provide a way to perform analysis on this famous type of content. Your tool would be even more utilized.
- **If new information is obtained, how would it be further processed? ->** Just by running the yet to be created  "reels_plays_count" function

**solution I'd like**
The creation of a function that would allow me to proper get the plays count of a Instagram Reels video.

**Describe alternatives you've considered**
I've considered using the current video_views_count function but it doesn't return the exact same value displayed in instagram insights. Example below:

- **Plays from instagram app:**
 ![image](https://github.com/instaloader/instaloader/assets/153955382/3ed909fb-0b6c-454a-9518-15dea8afd882)

- **Count from _video_view_count_ function:**
![image](https://github.com/instaloader/instaloader/assets/153955382/cfb7ade9-9a0a-4bc3-8919-aa8b7da5d945)

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes. I would need assistance.

**### I looooooooved the instaloader tool, it's amazing and so simple to use. You guys rock!!!**

**Comment by aandergr** [comment]
Yes, this seems a good idea to export that field as a property. The `play_count` is already present in the `iphone_struct` of the Post structure.

**Comment by nirbhaychaubey** [comment]
Please please add this feature 🙏🏾

**Comment by bruhmoment03** [comment]
found a quick fix, go to the structure.py and add the function below:
```
@property
def video_play_count(self) -> Optional[int]:
    """View count of the video, or None. """
    
    if self.is_video:
        return self._field('video_play_count')
    return None
```
        
and then go find the line where the part `fake_node["video_view_count"] = media["view_count"]` appears
and then paste `fake_node["video_play_count"] = media["play_count"]` down below
