### ISSUE TITLE
error code 403 when accessing

### ISSUE THREAD

**Issue by nf24eg** [instaloader/instaloader#2146]
**Describe the bug**
error code 403 when accessing https xxx for some accounts, it downloads some videos and some throw error

**To Reproduce**
instaloader --no-video-thumbnails --latest-stamps --fast-update --filename-pattern={date_utc:%Y%m%d%H%M%S}_UTC_ robert_martin_palestine_

**Expected behavior**
to download what this account posts video's and pictures 

**Error messages and tracebacks**
`[  10/3683] [“And in the end the only way …] Download <Post C0bfRjzLOJQ> of robert_martin_palestine_: 403 when accessing https://instagram.fkwi12-1.fna.fbcdn.net/v/t50.2886-16/10000000_1353615481923746_8218855628891922785_n.mp4?_nc_ht=instagram.fkwi12-1.fna.fbcdn.net&_nc_cat=102&_nc_ohc=8WPmRfB13s4AX81olyp&edm=AOQ1c0wBAAAA&ccb=7-5&oh=00_AfDAGp8yFB-09TdBPCQe0Q-d98y5NhBF2aP7AjF4SCvuKA&oe=65738D33&_nc_sid=8b3546.
[  11/3683] [Who is Hamas and what do they…] Download <Post C0ay_pUrFhD> of robert_martin_palestine_: 403 when accessing https://instagram.fkwi12-1.fna.fbcdn.net/v/t50.2886-16/10000000_710908634298454_1535002817695234080_n.mp4?_nc_ht=instagram.fkwi12-1.fna.fbcdn.net&_nc_cat=110&_nc_ohc=IjAvoZ1pUi8AX_INmFq&edm=AOQ1c0wBAAAA&ccb=7-5&oh=00_AfDiIYaBwN9hvRoXsmzQ01RBMa5DvSgnCLnJqlpxaVIHsA&oe=65734DAE&_nc_sid=8b3546.
[  12/3683] Download <Post C0abI3Mv_g9> of robert_martin_palestine_: 403 when accessing https://instagram.fkwi12-1.fna.fbcdn.net/v/t51.2885-15/405790671_1774218066346225_335217375325470510_n.jpg?stp=dst-jpg_e35&_nc_ht=instagram.fkwi12-1.fna.fbcdn.net&_nc_cat=101&_nc_ohc=1I-3jem-pl8AX99kDog&edm=AOQ1c0wBAAAA&ccb=7-5&ig_cache_key=MzI1MDAyOTQzNzM4MjU1NTcwOQ%3D%3D.2-ccb7-5&oh=00_AfC41uEUtPvDeHE4pIsqlYw8a7y69BnS3UngV-8Nkp0iYA&oe=65773400&_nc_sid=8b3546.
[  13/3683] [Let me introduce you to a few…] robert_martin_palestine_\20231203095420_UTC_.mp4 json
[  14/3683] [My best mate @iamthenassman] robert_martin_palestine_\20231203042404_UTC_.mp4 json`

**Instaloader version**
4.10.2

**Additional context**

**Comment by jhemsley** [comment]
We get this when we are trying to download comments from a video with a lot of comments. This could be related to a rate limit? Or trying to get replies on comments? The video this happens on for us has 1553 comments. The other video this happens to us on has about 2500 comments. We are happy to provide more information if it is needed.
