### ISSUE TITLE
Not downloading all stories

### ISSUE THREAD

**Issue by dirtyvi** [instaloader/instaloader#2151]
Hello,

I am having a problem where it doesn't download all the stories, for example, yesterday I tried the simple code:

instaloader --login MY_USERNAME :stories --dirname-pattern="F:\Users\Documents\Instagram\!stories\{profile}" --filename-pattern={profile}_{date} --no-metadata-json --no-compress-json

And it only downloaded 58 out of the 78 stories that were avaible.

Even if I try to write user by user, like:

instaloader --login MY_USERNAME target1 target2 target3...  --dirname-pattern="F:\Users\Documents\Instagram\!stories\{profile}" --filename-pattern={profile}_{date} --no-video-thumbnails --no-captions --no-metadata-json --no-compress-json --stories --no-video-thumbnails --no-posts --no-profile-pic

It doesn't download everything, it appears that only a % of it.

Why does this happen? 

Help appreciated, happy new year to everybody!

**Comment by TheFirstMonster** [comment]
Have the same issue, I found 2 ways to mitigate this problem:

- Decreasing userids_per_query from 50 to 5 (https://github.com/instaloader/instaloader/blob/5509ea7daf7f5e81534d4eb996c8afd478704426/instaloader/instaloader.py#L809C33-L809C33).
Maybe higher than 5 also works but I didn't test that.
- Calling get_stories with all ids that had no stories returned previously repeatedly until there are no more stories returned.

Obviously those are just temporary solutions and result in way more requests then necessary

**Comment by dirtyvi** [comment]
I tried to run 5 names at a time, but it still ignores some users, maybe it's because I'm putting users who don't have stories posted that day together, I don't know

**Comment by kb1ibt** [comment]
> Have the same issue, I found 2 ways to mitigate this problem:
> 
> * Decreasing userids_per_query from 50 to 5 (https://github.com/instaloader/instaloader/blob/5509ea7daf7f5e81534d4eb996c8afd478704426/instaloader/instaloader.py#L809C33-L809C33).
>   Maybe higher than 5 also works but I didn't test that.

I can confirm that 10 works, 20 usually works (depending on how many stories a user posts), but more than 30 almost never works.
What I also run into is if I don't pass any userids into get_stories, I only get 90 users back, and even then that is wrong compared to the result of (https://github.com/instaloader/instaloader/blob/5509ea7daf7f5e81534d4eb996c8afd478704426/instaloader/instaloader.py#L805) which lists 150 userids (of my 943 followees). So what I've been doing is loading my own profile and calling get_followees(), then batching them into blocks of 10 to pass to download_stories
