### ISSUE TITLE
Can I get post detail JSON from Python API?

### ISSUE THREAD

**Issue by stevenkader** [instaloader/instaloader#2153]
Would like to use the Python API to to retrieve details about a single post by shortcode.  I don't see a way to get the full JSON detail that is usually outputted as a file with the command line interface.  Is there a way to get that perhaps?

Thanks.

**Comment by newwangzhicheng** [comment]
There is no such command line interface right now, but you can get details of one single post by write code as follows:
``` python
# get the instance
insta = instaloader.Instaloader()

# login if you got HTTP 401 error
insta.login('your username', 'your password')

# get post from shot code
# you can get the post infomation by this 'post' dictionary
post = Post.from_shortcode(insta.context, 'shortcode')
```

**Comment by stevenkader** [comment]
I may not have been clear.  That code is helpful and I am aware of it.  It is at this point I was hoping to be be able to retrieve the original JSON (as seen attached).....the same JSON that is saved in the file with command line interface.
![Screenshot 2024-01-08 at 8 37 00 AM](https://github.com/instaloader/instaloader/assets/9343718/d3888273-2a59-4b8f-8d03-f5434d87e2df)

Something like this would be great  for the next line :

json = post.getRawJSON();

I am trying to avoid recreating it myself using the details from the post structure.  Thanks!
