### ISSUE TITLE
Error! Error! Error! Can anybody help me ?

### ISSUE THREAD

**Issue by Czaib** [instaloader/instaloader#2155]
I want to download all files of #astronautgalaxyprojector. i used this script below here. i tried so many scripts but it's always showing error. i'm not a programmer. i just wanna learn how to do that. can anybody help me ?

![Screenshot 2024-01-07 011450](https://github.com/instaloader/instaloader/assets/155396569/8b1c5307-31d3-4ffd-b444-aba3f029a885)

**Comment by newwangzhicheng** [comment]
It seems that you skipped inputting an number by tapping "Enter" Key.
You should enter a number after string "100:" when then programme waiting for your operation.
