### ISSUE TITLE
Reopen: Location download 'loop'

### ISSUE THREAD

**Issue by tari3x** [instaloader/instaloader#2159]
Please let me know if there's a better way to do this! 

Reopening https://github.com/instaloader/instaloader/issues/1341 - looks like it was never actually solved but it was closed by the bot, despite multiple other issues being duplicates of it.

I see exactly the same problem as described there.

**Comment by tari3x** [comment]
https://github.com/instaloader/instaloader/issues/1470 seems to have the most information. I don't know much about web tech or instagram APIs, but if someone could consult me on those, I'd be happy to do the coding part.

**Comment by aandergr** [comment]
Alright, we reopened that issue. :+1:
