### ISSUE TITLE
The logic of downloading order

### ISSUE THREAD

**Issue by coolwaiman** [instaloader/instaloader#216]
**Describe the bug**
When using quick-update:
Currently the program download posts from latest to oldest, however if the download is terminated unexpectedly (too many request error or Ctrl X) in the middle of the process(e.g. only downloaded 13/63 posts), the next instaloader process will not download the rest post (50 posts will not be download in the future)

**To Reproduce**
Ctrl X when downloading the post.

**Expected behavior**
Next instaloader process should redownload the rest of the photo

**Error messages and tracebacks**
N/A

**Instaloader version**
4.2

**Additional context**
Suggested: To download the oldest post first instead.

**Comment by aandergr** [comment]
If the download is terminated unexpectedly in the middle of the process, do not use `--fast-update` in the next Instaloader run.

Instaloader iterates through the posts in the order they come from Instagram, which is from new to old. Hence, to reverse the order, we would have to go through all posts first, so there would not be any gain compared to just not using `--fast-update`.

**Comment by hackmoore** [comment]
> If the download is terminated unexpectedly in the middle of the process, do not use `--fast-update` in the next Instaloader run.
> 
> Instaloader iterates through the posts in the order they come from Instagram, which is from new to old. Hence, to reverse the order, we would have to go through all posts first.
> 
> In either case, also by going from the posts from old to new, there would not be any gain compared to just not using `--fast-update`, since we'd have to go through all posts to fill the gaps of missing posts.

I'm not sure that's entirely correct right? If you don't use `--fast-update` then once if find the post it was up to (say 500/1000) then it will continue to check all the posts after that whereas if you did use `--fast-update` with a reversed order then it would stop once if finds the newest existing post (saving 500 queries).

I'm not familiar with the conditions around access of the information that IG returns but couldn't you add all the posts to a list and then access that in reverse once it's contained in the python memory space?
