### ISSUE TITLE
unable to log in

### ISSUE THREAD

**Issue by penguinpatrol** [instaloader/instaloader#2162]
**Describe the bug**
i am totally unable to log in even though i am entering the details correctly

![image](https://github.com/instaloader/instaloader/assets/117539617/e4d12ef3-a178-467e-8e18-c47d87478847)

**Comment by estatistics** [comment]
you tried? instaloader  --user-agent "my-user-agent is this" --abort-on=302,400,401,429,403  --stories insta_name/ 

google it "what is my user agent?"

**Comment by penguinpatrol** [comment]
![image](https://github.com/instaloader/instaloader/assets/117539617/b3d2a36a-49bb-4684-bcc3-938fbd3e3659)
 like this?

**Comment by estatistics** [comment]
are you log in in your browser chrome in instagram? or you are logged out?

**Comment by estatistics** [comment]
see here if this can help: "https://github.com/instaloader/instaloader/issues/109"

**Comment by ardian708** [comment]
since the 4.10.3 version, I have been unable to log in too
