### ISSUE TITLE
615_import_firefox_session.py: Cookie import failed: JSON Query to graphql/query: HTTP error code 401.

### ISSUE THREAD

**Issue by estatistics** [instaloader/instaloader#2163]
sudo python3 ./docs/codesnippets/615_import_firefox_session.py -c /mnt/firefox/default/cookies.sqlite 

Using cookies from /mnt/firefox/default/cookies.sqlite 
Cookie import failed: JSON Query to graphql/query: HTTP error code 401.

 instaloader --version
4.10.2

linux bookworm 12

**Comment by aandergr** [comment]
Duplicate of #2157
