### ISSUE TITLE
Error 401 - Instaloader can't login

### ISSUE THREAD

**Issue by satoshinotdead** [instaloader/instaloader#2165]
**Describe the bug**
Instaloader shows 401 error when I try to login into my account for download saved data.

If I remove the session I get a challenge to resolve from URL but then Instagram webpage shows ``Something went wrong - There's an issue and the page could not be loaded.``

**To Reproduce**
Use instaloader with --login option as described on #1756. The workaround suggested on Firefox didn't work:

```
Using cookies from /home/user/.mozilla/firefox/esfbrosb.default-release/cookies.sqlite.
Cookie import failed: JSON Query to graphql/query: HTTP error code 401.
```

**Error messages and tracebacks**
```
Loaded session from /home/user/.config/instaloader/session-userig.
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
```

**Instaloader version**
4.10.2

**Comment by adamkpurdy** [comment]
Seeing the same. I ran it to get :saved and about a quarter of the way in it threw an error about not finding a hi-res resource, then when I went to run the same command instaloader --login=my_username :saved it threw the same error as this issue.

**Comment by TheMissingPort** [comment]
does anyone ever plan on fixing this?

**Comment by satoshinotdead** [comment]
Unfortunately my skills don't allow me to fix this issue but I can test or debug if it's need :)

**Comment by eplinux** [comment]
I have a similar issue:
JSON Query to graphql/query: HTTP error code 401

However, I think this is ultimately due to Instagram's suspicious activity detection systems. I tend to query the same profiles and sometimes I even get logged out of my instagram app if I see the stories of these accounts too often.

**Comment by satoshinotdead** [comment]
There is a workaround currently?

**Comment by mathgarcia1** [comment]
in %appdata% search for "Instaloader", delete your session file and try to run it
`instaloader profile {someuserfrominsta} --stories --login {youruser}`

**Comment by TheMissingPort** [comment]
> in %appdata% search for "Instaloader", delete your session file and try to run it `instaloader profile {someuserfrominsta} --stories --login {youruser}`

Where would it be on a mac

**Comment by reln549** [comment]
See `--load-cookies` in the documentation and [#1801](https://github.com/instaloader/instaloader/issues/1801) and [#2040](https://github.com/instaloader/instaloader/pull/2040)

**Comment by satoshinotdead** [comment]
Loading cookies worked, I just forgotten to update to last version previously (my bad).

**Comment by michaelhodara** [comment]
@satoshinotdead Hi! Glad to read it worked out for you! I am still struggling haha.
do you still have to login after loading the cookies? To load the cookies, one just has to execute the script given [here](https://instaloader.github.io/troubleshooting.html#too-many-requests) right ?

**Comment by satoshinotdead** [comment]
I just used `--load-cookies` flag on the binary:

https://instaloader.github.io/cli-options.html#cmdoption-load-cookies

**Comment by varundeva** [comment]
Even if you use cookie file in deployed version it gives 401 after 5-10 calls
