### ISSUE TITLE
CSV list of who the user is following?

### ISSUE THREAD

**Issue by yada-yoda** [instaloader/instaloader#2171]
Is there a way for instaloader to get a scrape of the users the user is following each time and update the list or csv of if the user has followed someone new, or unfollowed someone that was in the past csv and is now not?

Any help is appreciated, if this is not a feature yet, could we make it one? If it's possible to at least scrape the current people they are following and/or followers for the meantime that would be great for now.

**Comment by kb1ibt** [comment]
You could do something like that using the Profile.get_followees() function, and the LatestStamps. The following example would get you a list of Profiles followed. Which you could then use with the python csv module to output to a file.
```
import instaloader
from instaloader import Profile, LatestStamps
loader = instaloader.Instaloader()
userProfile = Profile.from_username(loader.context, "example_username")
following = userProfile.get_followees()
followingSet = set(following)
stamps = LatestStamps("example_user_stamps.ini")
newFollowing = []
for user in followingSet:
    if not (user.username in stamps.data.sections()):
        stamps.save_profile_id(user.username, user.userid)
        newFollowing.append(user)
```

You could also use a block like the following to get a set of unfollowed accounts:
```
profile_usernames_set = {profile.username for profile in followingSet}
latest_stamps_section_set = {profile for profile in stamps.data.sections()}
removed_usernames_set = latest_stamps_section_set - profile_usernames_set
for removed_username in removed_usernames_set:
    stamps.data.remove_section(removed_username)
```
you notice in both blocks I'm using the LatestStamps to add or remove accounts from the local file of who is currently followed.
