### ISSUE TITLE
How to slow down request via command line?

### ISSUE THREAD

**Issue by sgtpepperaut** [instaloader/instaloader#2172]
Instagram seems to be very strict with rate limits these days. Im using my own account and my own IP. 
Even when trying to only "fastupdate" one profile i am getting kicked out and getting a 401. 

When i return to the browser version i get:

_"We suspect automated behavior on your account
To prevent your account from being temporarily restricted or permanently disabled, ensure that no other users or tools have access to your account and that you're following our Terms of Use. Also consider changing your password to a stronger one to prevent unauthorized access to your account by third parties."

**Is there a way i can slow down the request?**

**Comment by tari3x** [comment]
Here are the changes that work for me. I should maybe submit a pull request.

# in ~/.local/lib/instaloadercontext.py
# in class RateController:
#
# fast_sleeps = 10
#
#    def sleep(self, secs: float):
#        global fast_sleeps
#        if fast_sleeps > 0:
#            fast_sleeps = fast_sleeps - 1
#        else:
#            wait_time = random.uniform(15, 30)
#            print(wait_time)
#            time.sleep(wait_time)
#
# Remove > 0 guards in front of sleep further down

**Comment by smasonlawrence** [comment]
> Here are the changes that work for me. I should maybe submit a pull request.
> 
> ```
> # in ~/.local/lib/instaloadercontext.py
> # in class RateController:
> #
> # fast_sleeps = 10
> #
> #    def sleep(self, secs: float):
> #        global fast_sleeps
> #        if fast_sleeps > 0:
> #            fast_sleeps = fast_sleeps - 1
> #        else:
> #            wait_time = random.uniform(15, 30)
> #            print(wait_time)
> #            time.sleep(wait_time)
> #
> # Remove > 0 guards in front of sleep further down
> ```

Can you please explain where I make this change? I cannot find any of these strings in any of the py files.. sorry, sorta python noob here still figuring things out.

**Comment by tari3x** [comment]
Made a pull request.

**Comment by tari3x** [comment]
Still pertinent.

**Comment by nothing2obvi** [comment]
I am wondering the same thing. I got the warning for suspicious activity...I don't want Instagram to ban my account!
