### ISSUE TITLE
429 error for getting likes

### ISSUE THREAD

**Issue by guestprogrammer10** [instaloader/instaloader#2175]
The new problem that happened recently is that it cannot read the likes of any post and it keeps giving the error 429 Too Many Requests.
I checked this issue with different accounts and different IPs, but the problem still persists.

**Comment by Skuxblan** [comment]
Instagram must have changed something. The query_hash that is used 1cb6ec562846122743b61e492c85999f isn't working anymore. If you go to https://www.instagram.com/graphql/query/?query_hash=1cb6ec562846122743b61e492c85999f you will see that
```
message: ""
spam: true
status: "fail"

```

I wonder where to find update for it?

**Comment by kb1ibt** [comment]
The URL to view the likes that I am seeing is 
`https://www.instagram.com/api/v1/media/:mediaid/likers/`
which has a response of {"users":Array[Dict{}],"user_count":int,"status":"ok"}

Additionally, it looks like IG has changed the way that you can query a user's feed
`https://www.instagram.com/api/v1/feed/user/:userid/?count=#&max_id=:mediaid_:userid` where the max count is currently 33, max_id is optional (page marker, and the next page is in the prior page's dict), and the result of this query also includes the liked count for each post.

**Comment by Skuxblan** [comment]
> The URL to view the likes that I am seeing is `https://www.instagram.com/api/v1/media/:mediaid/likers/` which has a response of {"users":Array[Dict{}],"user_count":int,"status":"ok"}

It is available for years. This has no pagination so you can download up to ~ 100 likers due of instagram limitations

**Comment by jpedrojpedro** [comment]
I noticed that since yesterday some functions that perform yield are failing.
I tried the following with no success:
- `Profile.get_followees()`
- `Profile.get_followers()`
- `Post.get_likes()`
- `Post.get_comments()`

**Comment by guestprogrammer10** [comment]
Can anyone find a solution to this problem? Does it mean that Instagram doesn't output likes anymore?
But I was able to get it with another library, but because it has limitations, it is not possible to output all the likes.

**Comment by bondobrus** [comment]
> Can anyone find a solution to this problem? Does it mean that Instagram doesn't output likes anymore? But I was able to get it with another library, but because it has limitations, it is not possible to output all the likes.

There are two possibilities

1. Instagram disabled query hashing for likers so we can't get all likers.
2. Instagram only has changed the query hash for likers.

I've been researching a lot but sadly there's nowhere any explanation how to get `query_hash` on Instagram. All what I was able to find - few years back you could find it in Network tab in browser dev tools, but they must moved it somewhere else.

**Comment by guestprogrammer10** [comment]
If the problem is with Instagram, why do other libraries output at least part of the likes?

**Comment by Skuxblan** [comment]
> If the problem is with Instagram, why do other libraries output at least part of the likes?

Because it uses different method that has no pagination. Check it yourself in your browser go to user profile click on likers count so the popup will users will show up. open dev tools and analyse network tab. Something like this: `https://www.instagram.com/api/v1/media/media_id/likers/
`  in the preview you can find likers data, but as I said that has no pagination so your results are limited. 

I would really appreciate if somebody would share anything about `query_hash` on instagram. Instaloader uses query_hash that is outdated. Few years ago query_hash was easily accesiaable in browser dev tools in network tab, but it's not here anymore. I hope somebody who may knows that topic will share anything.
