### ISSUE TITLE
Login error: Wrong password.

### ISSUE THREAD

**Issue by qjvk2880** [instaloader/instaloader#2176]
I wrote code like this:
```
def download_reels_as_audio(reels_url, uuid):
    L = instaloader.Instaloader(compress_json=False,
                                download_pictures=False,
                                download_comments=False,
                                download_video_thumbnails=False,
                                download_geotags=False
                                # ,
                                # max_connection_attempts=1
                                )
    L.login('my_username', 'my_password')
    # L.test_login()
    post = instaloader.Post.from_shortcode(L.context, extract_shortcode(reels_url))
    filename = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'audios', uuid)
    L.download_pic(url=post.video_url, filename=filename, mtime=post.date_local)
    new_filename = file_util.convert_video_to_audio(filename)
    return ShortFormDownLoaded(
        uuid=uuid,
        description=post.caption,
        file_name=new_filename,
        url=reels_url
    )
```
The username and password I entered work fine in the browser.
But if I run that code "Login error: Wrong password." occurs.
My password contains only lowercase letters and numbers.
and I tried r'my_password' but not worked.

Here's full Error messages:

```
Traceback (most recent call last):
  File "C:\Users\.\Desktop\gd\backend_python\main.py", line 4, in <module>
    consumer.main()
  File "C:\Users\.\Desktop\gd\backend_python\utils\videoUrlListener.py", line 40, in main
    chan.start_consuming()
  File "C:\Users\.\AppData\Local\Programs\Python\Python310\lib\site-packages\pika\adapters\blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "C:\Users\.\AppData\Local\Programs\Python\Python310\lib\site-packages\pika\adapters\blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "C:\.\minuk\AppData\Local\Programs\Python\Python310\lib\site-packages\pika\adapters\blocking_connection.py", line 851, in process_data_events
    self._dispatch_channel_events()
  File "C:\Users\.\AppData\Local\Programs\Python\Python310\lib\site-packages\pika\adapters\blocking_connection.py", line 567, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "C:\Users\.\AppData\Local\Programs\Python\Python310\lib\site-packages\pika\adapters\blocking_connection.py", line 1510, in _dispatch_events
    consumer_info.on_message_callback(self, evt.method,
  File "C:\Users\.\Desktop\gd\backend_python\utils\videoUrlListener.py", line 26, in on_message
    publisher.send_summary(body_json['url'], body_json['uuid'])
  File "C:\Users\.\Desktop\gd\backend_python\utils\videoSummarySender.py", line 29, in send_summary
    video_info = insta.download_reels_as_audio(url, uuid)
  File "C:\Users\.\Desktop\gd\backend_python\utils\instagram_util.py", line 19, in download_reels_as_audio
    L.login('my_username', 'my_password')
  File "C:\Users\.\AppData\Local\Programs\Python\Python310\lib\site-packages\instaloader\instaloader.py", line 651, in login
    self.context.login(user, passwd)
  File "C:\Users\.\AppData\Local\Programs\Python\Python310\lib\site-packages\instaloader\instaloadercontext.py", line 306, in login
    raise BadCredentialsException('Login error: Wrong password.')
instaloader.exceptions.BadCredentialsException: Login error: Wrong password.
```

I use instaloader version 4.10.3 and Pycharm

**Comment by Jarsky** [comment]
I don't think you can login like that, I think you need to get the cookie and use that?
You can use [615_import_firefox_session.py](https://github.com/instaloader/instaloader/blob/master/docs/codesnippets/615_import_firefox_session.py) with Firefox to generate the session hash

**Comment by qjvk2880** [comment]
> I don't think you can login like that, I think you need to get the cookie and use that? You can use [615_import_firefox_session.py](https://github.com/instaloader/instaloader/blob/master/docs/codesnippets/615_import_firefox_session.py) with Firefox to generate the session hash

I'm sorry  for late reply. I'm running my python project on AWS EC2. and I successfully logged in by manually injecting the session ID and csrf token into the project. ( used Chrome Developer tool and copied sessionID and csrf token).
But I wonder how can I automatically get a new session ID when previous session ID  is expired.
Do you know a solution related to this?

**Comment by Jarsky** [comment]
> > I don't think you can login like that, I think you need to get the cookie and use that? You can use [615_import_firefox_session.py](https://github.com/instaloader/instaloader/blob/master/docs/codesnippets/615_import_firefox_session.py) with Firefox to generate the session hash
> 
> I'm sorry for late reply. I'm running my python project on AWS EC2. and I successfully logged in by manually injecting the session ID and csrf token into the project. ( used Chrome Developer tool and copied sessionID and csrf token). But I wonder how can I automatically get a new session ID when previous session ID is expired. Do you know a solution related to this?

I generate it on my PC, since you need a browser session to; and remotely upload it to my server. You could use my Powershell script [here](https://github.com/Jarsky/Instaloader-Docker/blob/main/Instaloader.ps1) as a basis for doing this. I dont run it that often so I havent automated the process fully since I manually trigger Instaloader. 

You could fully automate it and have your python script check the modified date/time of the session file if it hasnt been modified recently (your specified time) then wait / skip and try it again later

**Comment by qjvk2880** [comment]
Your answer was very helpful!
I would like to ask one last question. 
Do you know how long sessionId is valid?

**Comment by Jarsky** [comment]
> Your answer was very helpful! I would like to ask one last question. Do you know how long sessionId is valid?

Not sure sorry. I typically update the session ID every day though. I havent looked into the expiry time.

**Comment by jasursadikov** [comment]
Same issue on my side 
@Jarsky is there a way to import my session from chromium instead?
