### ISSUE TITLE
Errors or warnings occurred: profile: JSON Query to web/search/topsearch/: HTTP error code 401.

### ISSUE THREAD

**Issue by EJMBoomer** [instaloader/instaloader#2181]
**Describe the bug**
The program is facing some issues with finding certain information and accessing specific features due to authorization problems. Ethier this is an exclusive club called "web/search/topsearch/" or possibly the program couldn't find what it was looking for at a specific address.

**To Reproduce**
instaloader --fast-update profile thisoldhouse
JSON Query to api/v1/users/web_profile_info/?username=profile: 404 Not Found [retrying; skip with ^C]
JSON Query to api/v1/users/web_profile_info/?username=profile: 404 Not Found [retrying; skip with ^C]
JSON Query to web/search/topsearch/: HTTP error code 401. [retrying; skip with ^C]
JSON Query to web/search/topsearch/: HTTP error code 401. [retrying; skip with ^C]
profile: JSON Query to web/search/topsearch/: HTTP error code 401.
Hint: Use --login to download higher-quality versions of pictures.
[1/1] Downloading profile thisoldhouse
thisoldhouse\2017-10-20_15-30-20_UTC_profile_pic.jpg already exists
Retrieving posts from profile thisoldhouse.
[   1/2084] thisoldhouse\2024-01-27_18-01-12_UTC_1.jpg exists thisoldhouse\2024-01-27_18-01-12_UTC_2.jpg exists thisoldhouse\2024-01-27_18-01-12_UTC_3.jpg exists thisoldhouse\2024-01-27_18-01-12_UTC_4.jpg exists [🪑If you need more seating for…] unchanged  json
[   2/2084] thisoldhouse\2024-01-25_23-14-08_UTC.jpg exists [Waste not want not! Tom took …] unchanged json
[   3/2084] thisoldhouse\2024-01-24_21-11-44_UTC.jpg exists [One of the highlights of #TOH…] unchanged thisoldhouse\2024-01-24_21-11-44_UTC.mp4 exists json
[   4/2084] thisoldhouse\2024-01-23_15-45-52_UTC.jpg exists [You could be on This Old Hous…] unchanged thisoldhouse\2024-01-23_15-45-52_UTC.mp4 exists json

Errors or warnings occurred:
profile: JSON Query to web/search/topsearch/: HTTP error code 401.

**Expected behavior**
download all pictures and videos of a profile, as well as the profile picture

**Error messages and tracebacks**
[2084/2084] thisoldhouse\2013-02-05_16-00-45_UTC.jpg exists [Saturday afternoon @ Frank Th…] unchanged json

Errors or warnings occurred:
profile: JSON Query to web/search/topsearch/: HTTP error code 401.

**Instaloader version**
Instaloader version 4.10.3

**Additional context**
Device name   Laptop01
Processor	Intel(R) Celeron(R) CPU 1007U @ 1.50GHz   1.50 GHz
Installed RAM	16.0 GB (15.9 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Home
Version	22H2
Installed on	‎3/‎21/‎2022
OS build	19045.3930
Experience	Windows Feature Experience Pack 1000.19053.1000.0

 conda version : 23.11.0
    conda-build version : not installed
         python version : 3.11.6.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64
                          __conda=23.11.0=0
                          __win=0=0

conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch

  platform : win-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.6 Windows/10 Windows/10.0.19045 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.6 aau/0.4.3 c/igvwp2W-ThfM7YLu_GhltA s/buWjofm6H3SiXz4zIodUeg e/HU5dI84R_dg4lK8WeaPXPQ

**Comment by Showmaster3000** [comment]
I think this issue is a duplicate of #2135, is it?

**Comment by Jarsky** [comment]
Mine just started doing this yesterday. Nothings changed
Running latest version 4.10.3 instaloader on Docker (Linux)

`Fatal error: JSON Query to graphql/query: HTTP error code 401`

**Comment by raniaamina** [comment]
Just happen today

```bash
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Fatal error: JSON Query to graphql/query: HTTP error code 401.
```

**Comment by sammas72** [comment]
It happen me too, there no solution?
