### ISSUE TITLE
Want to download 24h/7d/1m/1y content

### ISSUE THREAD

**Issue by SubZero5** [instaloader/instaloader#2185]
**Provide us a use case of the feature**
For example I want to download a specific content that was made available in a specified time limit or window. 

**Describe the solution you'd like**
As the items in the list is sorted, first on pinned item that falls outside the specified time window should either be skipped or to download process could be also terminated.

User might set the parameter to only download content in x amount of seconds minutes hours days weeks months or years.

**Describe alternatives you've considered**
I have not done anything on this issue. I just either terminate to download process manually or because of a lot of errors the account that I'm using to download gets blocked and it is how the process stops by itself. 

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes / No / *Maby*
As I am using a Windows build, I have never submitted a pull request.

**Additional context**
Nope...

**Comment by SayanthD** [comment]
Tried this?

https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period

**Comment by SubZero5** [comment]
@SayanthD, I use instaloader.exe from the Windows BAT File or via Command Line instead of Python version.

**Comment by SayanthD** [comment]
Then try this
https://instaloader.github.io/basic-usage.html#filter-posts

Use **date_utc** for your case

**Comment by aandergr** [comment]
You could use `--latest-stamps` for that case (which was discussed in #1122 and #1131). With that, Instaloader maintains and follows a little configuration file that specifies the earliest post that should be downloaded, in the style of 

```ini
[selenagomez]
profile-id = 460563723
post-timestamp = 2021-05-10T18:26:39
```

**Comment by FreePhoenix888** [comment]
> You could use `--latest-stamps` for that case (which was discussed in #1122 and #1131). With that, Instaloader maintains and follows a little configuration file that specifies the earliest post that should be downloaded, in the style of
> 
> ```ini
> [selenagomez]
> profile-id = 460563723
> post-timestamp = 2021-05-10T18:26:39
> ```

What if me .ini file looks like this?
```
[freephoenix888]
profile-id = 5997655
profile-pic = 461310553_980131430537583_403398051434667406_n.jpg
```
There is no post-timestamp

I have started this command `instaloader --latest-stamps -- profile "heidy.espaillat"` and interrupted by `Ctrl`+`C` because I have downloaded some images before and want to download only some images after, for example, 2023 May

**Comment by FreePhoenix888** [comment]
https://instaloader.github.io/basic-usage.html#filter-posts helped me, I have used date_utc filter
