### ISSUE TITLE
Check instagram profile's private or public

### ISSUE THREAD

**Issue by npereira89** [instaloader/instaloader#2189]
Is there anyway to check/validate if some instagram profile is private or public? 
As you know, there are some instagram profile are private, which photos and reels are available if someone follow that profile.
My idea is the following:

```
if instaloader.profile.check_is_public=="true" then
   instaloader.download_posts(posts)
else
   print("you must first login in profile")
   instaloader.login(instagram_account)
   
```

**Comment by SayanthD** [comment]
Solution for this already exists
https://instaloader.github.io/module/structures.html#instaloader.Profile.is_private

The value will be **True** for private accounts

**Comment by mrzing** [comment]
please send me the edited code too like full file please

**Comment by npereira89** [comment]
> Solution for this already exists https://instaloader.github.io/module/structures.html#instaloader.Profile.is_private
> 
> The value will be **True** for private accounts

It's been resolved. Thanks for your support and thanks @mrzing anyway
