### ISSUE TITLE
Instaloader CLI get private profiles

### ISSUE THREAD

**Issue by Wulfheart** [instaloader/instaloader#219]
Hello,

I'm currently using instaloader in a Powershell Script.
Is there any way in the CLI to determine machinally if a given profile is private?

Greetings

**Comment by aandergr** [comment]
Hello,

If the profile is already downloaded, and you have [jq](https://stedolan.github.io/jq/) installed, you can read the corresponding variable in the JSON file
```
$ xzcat <PROFILE>/<PROFILE>_<USERID>.json.xz | jq .node.is_private
false
```

If you use Instaloader programmatically, each `Profile` object has a [`is_private`](https://instaloader.github.io/as-module.html#instaloader.Profile.is_private) property.

Happy Instaloading
Alex
