### ISSUE TITLE
gaierror/NewConnectionError/MaxRetryError/ConnectionError

### ISSUE THREAD

**Issue by Mikamikaz** [instaloader/instaloader#2191]
When I try to download profile picture or story, sometime I have gaierror/NewConnectionError/MaxRetryError/ConnectionError  errors that are triggered, is it from me or from the library or Instagram?

**Comment by nikitabcn** [comment]
It seems that Instagram have problems with their DNS server last 3-4 days. I have same errors, I figured out that in moments, when I get errors I can't get the IP for the domain with images. 

You can check by yourself, when you have a problem with downloading a picture, do nslookup on domain with picture.
