### ISSUE TITLE
Related to get likes

### ISSUE THREAD

**Issue by y3-rawat** [instaloader/instaloader#2193]
def get_likes(self) -> Iterator['Profile']:
        """
        Iterate over all likes of the post. A :class:`Profile` instance of each likee is yielded.

        .. versionchanged:: 4.5.4
           Require being logged in (as required by Instagram).
        """
        if not self._context.is_logged_in:
            raise LoginRequiredException("--login required to access likes of a post.")
        if self.likes == 0:
            # Avoid doing additional requests if there are no comments
            return
        likes_edges = self._field('edge_media_preview_like', 'edges')
        if self.likes == len(likes_edges):
            # If the Post's metadata already contains all likes, don't do GraphQL requests to obtain them
            yield from (Profile(self._context, like['node']) for like in likes_edges)
            return
        yield from NodeIterator(
            self._context,
            '1cb6ec562846122743b61e492c85999f',
            lambda d: d['data']['shortcode_media']['edge_liked_by'],
            lambda n: Profile(self._context, n),
            {'shortcode': self.shortcode},
            'https://www.instagram.com/p/{0}/'.format(self.shortcode),
        )

this is the function of the library which is under 

C:\Users\*****\AppData\Local\Programs\Python\Python39\Lib\site-packages\instaloader\structures.py

so the problem with this is it is not working 

getting this error 

--------------------------------------------------------------------
ConnectionException                       Traceback (most recent call last)
File [c:\Users\y3raw\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloadercontext.py:409](file:///C:/Users/y3raw/AppData/Local/Programs/Python/Python39/lib/site-packages/instaloader/instaloadercontext.py:409), in InstaloaderContext.get_json(self, path, params, host, session, _attempt, response_headers)
    [408](file:///C:/Users/y3raw/AppData/Local/Programs/Python/Python39/lib/site-packages/instaloader/instaloadercontext.py:408) if resp.status_code != 200:
--> [409](file:///C:/Users/y3raw/AppData/Local/Programs/Python/Python39/lib/site-packages/instaloader/instaloadercontext.py:409)     raise ConnectionException("HTTP error code {}.".format(resp.status_code))
    [410](file:///C:/Users/y3raw/AppData/Local/Programs/Python/Python39/lib/site-packages/instaloader/instaloadercontext.py:410) else:

ConnectionException: HTTP error code 401.

During handling of the above exception, another exception occurred:

ConnectionException                       Traceback (most recent call last)
File [c:\Users\y3raw\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloadercontext.py:409](file:///C:/Users/y3raw/AppData/Local/Programs/Python/Python39/lib/site-packages/instaloader/instaloadercontext.py:409), in InstaloaderContext.get_json(self, path, params, host, session, _attempt, response_headers)
    [408](file:///C:/Users/y3raw/AppData/Local/Programs/Python/Python39/lib/site-packages/instaloader/instaloadercontext.py:408) if resp.status_code != 200:
--> [409](file:///C:/Users/y3raw/AppData/Local/Programs/Python/Python39/lib/site-packages/instaloader/instaloadercontext.py:409)     raise ConnectionException("HTTP error code {}.".format(resp.status_code))
    [410](file:///C:/Users/y3raw/AppData/Local/Programs/Python/Python39/lib/site-packages/instaloader/instaloadercontext.py:410) else:

ConnectionException: HTTP error code 401.

During handling of the above exception, another exception occurred:

ConnectionException                       Traceback (most recent call last)
File [c:\Users\y3raw\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\instaloadercontext.py:409](file:///C:/Users/y3raw/AppData/Local/Programs/Python/Python39/lib/site-packages/instaloader/instaloadercontext.py:409), in InstaloaderContext.get_json(self, path, params, host, session, _attempt, response_headers)
    [408](file:///C:/Users/y3raw/AppData/Local/Programs/Python/Python39/lib/site-packages/instaloader/instaloadercontext.py:408) if resp.status_code != 200:
--> [409](file:///C:/Users/y3raw/AppData/Local/Programs/Python/Python39/lib/site-packages/instaloader/instaloadercontext.py:409)     raise ConnectionException("HTTP error code {}.".format(resp.status_code))
...
--> [425](file:///C:/Users/y3raw/AppData/Local/Programs/Python/Python39/lib/site-packages/instaloader/instaloadercontext.py:425)         raise ConnectionException(error_string) from err
    [426](file:///C:/Users/y3raw/AppData/Local/Programs/Python/Python39/lib/site-packages/instaloader/instaloadercontext.py:426) self.error(error_string + " [retrying; skip with ^C]", repeat_at_end=False)
    [427](file:///C:/Users/y3raw/AppData/Local/Programs/Python/Python39/lib/site-packages/instaloader/instaloadercontext.py:427) try:

ConnectionException: JSON Query to graphql/query: HTTP error code 401.

-----------------------------------------------------------
code i have used 
=================
# Retrieve likes
likes = post.get_likes()

# Print profiles who liked the post
print("\nProfiles who liked the post:")
for like in likes:
  print(f"{like.username} - {like.userid}")

**Comment by Skuxblan** [comment]
The query_hash that is used `1cb6ec562846122743b61e492c85999f` is not working. Instagram changing their API since few weeks.  The issue with likes is already [here](https://github.com/instaloader/instaloader/issues/2175)
