### ISSUE TITLE
 Failed to resolve 'scontent-sin6-4.cdninstagram.com' ([Errno -2] Name or service not known)"))

### ISSUE THREAD

**Issue by Andikazidanef15** [instaloader/instaloader#2196]
**Describe the bug**
Some of the post failed to download because `instaloader.download_post(post)` throws error `Failed to resolve 'scontent-sin6-4.cdninstagram.com' ([Errno -2] Name or service not known)")) [retrying; skip with ^C]`

**To Reproduce**
```
import numpy as np
import instaloader
import time
from pathlib import Path

class CustomizedRateController(instaloader.RateController):
    def sleep(self, secs):
        # Choose lower bound randomly
        lower_bound = np.random.randint(5, 7)

        # Choose upper bound randomly
        upper_bound = 10

        # Generate random number with addition of random number from a gaussian distribution
        # This is for generate random number pattern
        random_number = np.random.randint(lower_bound, upper_bound) + np.random.normal(0, 1, None)
        
        # Sleep
        time.sleep(random_number)

    def count_per_sliding_windows(self, query_type):
        # Limit sliding windows to 50 requests in duration of 11 minutes
        return 20
    
    def query_waittime(self, query_type, current_time, untracked_queries = False):
        return 10

# Get instance
L = instaloader.Instaloader(
            download_video_thumbnails = False,
            rate_controller = lambda ctx: CustomizedRateController(ctx),
            iphone_support = False,
            fatal_status_codes = [302,400,401,429,403]
 )

# Load sessionfile if exist
scrapper_username = 'XXX'
if sessionfilepath:
    logger.info(f'Logging with account {scrapper_username}')
    L.load_session_from_file(scrapper_username, filename = sessionfilepath)

# Define post object
user_id = '623140511'
posts = instaloader.Profile.from_id(loader.context, user_id).get_posts()

# Loop each post
output_filename = 'data/metadata/XXX/'
for post in posts:
    instaloader.download_post(post, target = Path(output_filename))
    time.sleep(3)
```

**Expected behavior**
Download the video files in the output filename

**Error messages and tracebacks**
Some error output:

`[Cheers to savings and sweets!…] download_pic(): HTTPSConnectionPool(host='scontent-sin6-4.cdninstagram.com', port=443): Max retries exceeded with url: /v/t66.30100-16/321208122_411516044740503_771619796115598426_n.mp4?_nc_ht=scontent-sin6-4.cdninstagram.com&_nc_cat=103&_nc_ohc=Wv5BbGzqqCsAX_3-S48&edm=APU89FABAAAA&ccb=7-5&oh=00_AfCvA3z1taam29KZasa-yotCZ9DRmbPUbW69AsRDB9Bzmw&oe=65CC674B&_nc_sid=bc0c2c (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ff20cb93910>: Failed to resolve 'scontent-sin6-4.cdninstagram.com' ([Errno -2] Name or service not known)")) [retrying; skip with ^C]`

**Instaloader version**
4.10.3

**Additional context**
Some of the posts successfully downloaded while the other throws the same error

**Comment by nikitabcn** [comment]
#2191

**Comment by Andikazidanef15** [comment]
I see, I did scraping again 1 day after the issue and Instaloader can scrape and download posts again, closing this issue
