### ISSUE TITLE
Instaloader doesn't seem to be working without a login  anymore. Even after login in, I get signed out after one request.

### ISSUE THREAD

**Issue by devaash88** [instaloader/instaloader#2198]
Instaloader doesn't seem to be working without a login  anymore. Even after login in, I get signed out after one request.

For example, I wanted to get the user ID of a specific user. But without login in, I am getting this error

Enter the Instagram user ID:1741
JSON Query to : Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]
JSON Query to : Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]
The username corresponding to user ID 1741 is: An error occurred: JSON Query to : Expecting value: line 1 column 1 (char 0)

If I do login, then it works only once after which I get automatically logged out.

**Comment by satoshinotdead** [comment]
Related, without updates:

https://github.com/instaloader/instaloader/issues/2165

**Comment by Showmaster3000** [comment]
- no version information
- no command line
- looks like a self created script cause the prompt is not included in the code
- and your account is maybe flagged by instagram for doing things they don't like

**Comment by devaash88** [comment]
@satoshinotdead  yes, the link you provided showcases a similar issue. Still not fixed.

@Showmaster3000  sorry for being thick, but not sure what your bullet points mean except the last one. Is there any workaround?

**Comment by Showmaster3000** [comment]
> @Showmaster3000 sorry for being thick, but not sure what your bullet points mean except the last one. Is there any workaround?

You omited to use the prepared issue template which asks for essential information - thats what the first points say. At least the mentioned points are required to help you.

**Comment by reln549** [comment]
See `--load-cookies` in the documentation and [#2040](https://github.com/instaloader/instaloader/pull/2040), [#1801](https://github.com/instaloader/instaloader/issues/1801). `--load-cookies` is a new feature of version 4.11.
