### ISSUE TITLE
Check if a specific account is a follower/followee - partial username search through an account's followers/followees[to avoid download of large lists]

### ISSUE THREAD

**Issue by smokingaverage** [instaloader/instaloader#2199]
**Provide us a use case of the feature**
This feature is useful if you want to check if a private account is following or is followed by certain public accounts with a large number of followers/followings.

**Describe the solution you'd like**
In order to avoid downloading large lists of followers/followees, a query can be performed via instagram API to retrieve only a smaller portion of the list(for example only a partial username string). 

**Describe alternatives you've considered**
Download the large lists of followers/followees and check via a script it the account is a follower or a followee.

**If the feature request is accepted, would you be willing to submit a pull request?**
No

**Comment by aandergr** [comment]
> **Describe the solution you'd like** In order to avoid downloading large lists of followers/followees, a query can be performed via instagram API to retrieve only a smaller portion of the list(for example only a partial username string).

How? Could you provide more details about this query?
