### ISSUE TITLE
Caption without hashtags as filename

### ISSUE THREAD

**Issue by blarg3891** [instaloader/instaloader#2200]
I would like to use the caption as a filename without the hashtags.  Currently using 
.\instaloader.exe profilename "--filename-pattern={date_utc}_UTC_{caption:.30}" per article found here
https://github.com/instaloader/instaloader/issues/172

There isn't anything about using caption as filename in the documentation so I was hoping there might already be a way to include the caption excluding the "#xxxxx."

Current settings result is "Sushi #xyz #eatk#......."
I was hoping to see something like "Sushi"

Thanks.

**Comment by Showmaster3000** [comment]
Using the caption is generally a bad idea cause of different problems: invalid characters for filenames, the length of text, duplicate captions in different media
As you can further read in the referenced issue #172 

> [...] However, the captions may not be unique, and there is no logic to handle that. Also, a Post caption may contain characters that are not allowed in filenames, but our latest alpha version, 4.1a1, substitutes these by allowed characters.

_Originally posted by @aandergr in https://github.com/instaloader/instaloader/issues/172#issuecomment-417021234_
