### ISSUE TITLE
Fatal error and challenge url not working

### ISSUE THREAD

**Issue by Causing2012** [instaloader/instaloader#2201]
**Describe the bug**
When trying to login to instaloader using the --login optin and password i get fatal error, and the URL provided does not work. My account is not locked when logging in in Chrome.

**To Reproduce**
instaloader --login MY-USERNAME

**Expected behavior**
Instaloader logging me in making me able to download profiles.

**Error messages and tracebacks**
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.comhttps://www.instagram.com/challenge/AXHgJId2cK31LtuA45EtMwXjK38DaiT_lft3VJb3JAR8fQpn7c3O7LuaOa2RhR7tt7U1AA/AfzZPAxVgOtAE4Laa0SGqJYHcIQAAthA0cIA1wN8EaaSzid-UiIGxSNtfqOoeBrmyl8z1xUL2msJsw/?challenge_context=Af6egxo2Oewlli8KesIrxxsZ2Crs64lKwFkYDU7gCDhO5kYsC-x0bB6XWkw8C1-qmq8d_t2R9VSEa7PXnNMViKiHQLRtRy4fewvM3c6N_G80NiA-DY85HJMNWFKTQmFUJq32TvH4aF0oq12JSYHBslniQ4_05AXzcTutvmPAoNH3qiuUNQ7RA_DG1E2H-REEDf_Ibfu3DdqtfwmijyRXIF00h4uQ9Sf8H3bs0gdq9alj6_FlFPZmI5dIpWNr1bHaud0HxwBO7BLrt8xFc2vXPGkYuu0G9YCQFMomEyGxCI9iUA7wP5dWFAumyqM8u3o1b7A5JwjfkvqLxEtDtjgAqf8YDXEoQq117TNkCNKKF7yZsLuD9VsjLXzCGORK5z6tE_ewHBmWUmq7AuOPhB2P1MqsTwj8FH-_E50Dg5_TJLIGaNdIpD3EdnLJKK7O8EehLLraj7HqiFhZgl-GjPCud_qZQoFQvohd2g35F8C-qO546HcZ1EB1P5-LWxLNQEE-tOvLVboSu01XkKw5Hi4D999mk9vjc3ApoxjShNOCsXe5QYu3nOeLrhW1hTHxAFRScJgy0RGmsFyLKPuAyqk26mXl7VkJGB_48yOC8mwsw0JSc3XvQCOzl-J38txJ7wJGRx2R3ZAPQ-ABEu2ZiTIspWrA0zONMV-hC2UnEOJiRqp9Ixpvn58_cJPUxQJ7eEYQsuigmm0DO6g5ex_w1UWXiOTFMZGxh0FZw-fYhV8dIfn7LXMSnsGUjRiXM9QzneJmKyM68bslPcHV7DgeZxg51uxuk6Vcmf8SgkgUa4PoOUBqg5kNX7tuxjtoY0NkI-v55MJrF3OrNpe7Ppjbl1IECjWcHV8knc40CrEUpLfJxNNFtXQGHmTwSxs2HMuhqZe42bTETX4S0zytb_wG-O45QHyR82uQasuF-HB4QtX1A1L6TbTD7I9Da_G5wKFZX4-NLYXsyhs5F0BPo_NU2JDsJUwy7IrFUmJihY-H5bnjhBswAmEwaFVMlWA7vu6PGDRQx6OX_JhNk054j4n8uzAN7h7JsINJycfDTnA5maf-Iz8M300QbGfXtM4CKSjScudCuVRq2ewRGJK__34lPSOltuguy66aoFkezHht4jNQLy0awNttpWqaRQGJkBy4h2acwtNOkc0eK-6AAmxhsmBubs4XRZwVt8k4X0Kwnq9ev6YBdpcdAjCaJ-TWw9wubI6t-g - follow the instructions, then retry.

**Instaloader version**
4.10.3

**Additional context**

**Comment by Showmaster3000** [comment]
The challenge thing has problems since longer time which haven't been solved. Same thing as in #1787 or #2027.
You can grab the session from your browser as descibed in #1787 or use the parameter `--load-cookies` (requires preview version 4.11) and (re-)use saved sessionfile with instaloader.

**Comment by windviki** [comment]
Based on the firefox solution, I write a new script to import hand-made cookies and it works.
First, use Chrome or Firefox to login and use developer tools to find out your cookies (or copy as HAR to find out cookies).
Then, write them into a txt file "cookies.txt" with JSON format. e,g.,
`[
            {
              "name": "dpr",
              "value": "1.31243",
              "path": "/",
              "domain": ".instagram.com",
              "expires": "2024-03-02T03:41:01.000Z",
              "httpOnly": false,
              "secure": true,
              "sameSite": "None"
            },
            {
              "name": "mid",
              "value": "xxxxxxxxxx3UmPXDZxxxxxxH3K",
              "path": "/",
              "domain": ".instagram.com",
              "expires": "2025-03-30T03:40:37.752Z",
              "httpOnly": false,
              "secure": true
            }
]` 

The use this script to import it automatically. You can modify the cookie parsing part to support other formats you like:
`
from argparse import ArgumentParser
from glob import glob
from os.path import expanduser
from platform import system
import json

try:
    from instaloader import ConnectionException, Instaloader, get_default_session_filename
except ModuleNotFoundError:
    raise SystemExit("Instaloader not found.\n  pip install [--user] instaloader")


def import_session():
    cookie_data = {items["name"]:items["value"] for items in json.load(open("cookies.txt", "r"))}
    print("Using cookies {}.".format(cookie_data))
    instaloader = Instaloader(max_connection_attempts=1)
    instaloader.context._session.cookies.update(cookie_data)
    username = instaloader.test_login()
    if not username:
        raise SystemExit("Not logged in. Are you logged in successfully in Firefox?")
    print("Imported session cookie for {}.".format(username))
    instaloader.context.username = username
    sessionfile = get_default_session_filename(username)
    instaloader.save_session_to_file(sessionfile)
    print("Saved session to {}.".format(sessionfile))


if __name__ == "__main__":
    try:
        import_session()
    except (ConnectionException, OperationalError) as e:
        raise SystemExit("Cookie import failed: {}".format(e))
`
