### ISSUE TITLE
Downloading picutures from a given location

### ISSUE THREAD

**Issue by herves-pardavila** [instaloader/instaloader#2202]
**Describe the bug**

I have previously (1 month ago) downloaded pictures using the target %location_id for several locations. However, this feature is not working anymore. For example, for this location, https://www.instagram.com/explore/locations/216323844/zaragoza-spain/?hl=es.

I tried with several new locations which I checked pictures exist and locations I prevoiusly obtained photos. I also created a new account and tried with other computer, getiting same result.

Can anyone reproduce this example an let me know if they get same error.

**To Reproduce**
In ubuntu terminal, $instaloader --login=USERNAME %216323844

**Expected behavior**

Start downloading photos for location 216323844

**Error messages and tracebacks**

%216323844: JSON Query to explore/locations/216323844/: 404 Not Found 

**Instaloader version**
4.10.3

**Comment by npereira89** [comment]
@herves-pardavila Good morning. This situation is normal. Instagram could be block temporarily your IP and denied new access, if you invoke several times the application in short period of time.
Check later if the error continue.

**Comment by herves-pardavila** [comment]
Good Morning and thanks for your reply. I did use the application recently so my access could be denied. However, if a try to download pictures from a private profile I follow (requires login), it works. Does this make sense? 

David

**Comment by npereira89** [comment]
> Good Morning and thanks for your reply. I did use the application recently so my access could be denied. However, if a try to download pictures from a private profile I follow (requires login), it works. Does this make sense?
> 
> David

Hi David. It works even profile follow you or not, but if it's private profile, that means required login. However, you can use my python script which works with all type of profile. Try it and tell me your feedback.
[insta_download.zip](https://github.com/instaloader/instaloader/files/14438281/insta_download.zip)
