### ISSUE TITLE
get_likes for post is not working

### ISSUE THREAD

**Issue by mustafasu** [instaloader/instaloader#2205]
**Describe the bug**
when get the usernames of  users who liked post gives error that simplejson.errors.JSONDecodeError. 

**To Reproduce**
from instaloader import Post
post = Post.from_shortcode(loader.context,<post_id>)
liked_users = [like.username for like in post.get_likes()] --> this line gives this error

**Expected behavior**
it should gives us usernames of users who liked the post we give.

**Error messages and tracebacks**
"/instaloader/instaloadercontext.py line 411, in get_json resp_json = resp.json()"
"simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

**Instaloader version**
`instaloader==4.10.3` output.

**Additional context**

**Comment by Skuxblan** [comment]
Query_hash that is used for get_likes has been changed/disabled. As far I know they replaced some Graphql with REST so that's the reason. I guess we have to wait until they get the query_hash enabled or somebody who figure out what really happen and find solution for that. Temporary solutin from me is: Use old likers method that has (sadly) no pagination: `https://www.instagram.com/api/v1/media/media_id/likers/`

**Comment by mustafasu** [comment]
thank for reply but it gives error that login requeired. How can i solve?

**Comment by Skuxblan** [comment]
If you want to scrape data such as likers you should be logged in. Instagram doesn't allow view likers in public request

**Comment by MateuszAbramczuk** [comment]
@Skuxblan  How to you use the method you talked about? I'm new to programing but I would like to be able to download information about who liked the post. Could you point me in the direction that would help me?

**Comment by Skuxblan** [comment]
> @Skuxblan How to you use the method you talked about? I'm new to programing but I would like to be able to download information about who liked the post. Could you point me in the direction that would help me?

First of all as I mentioned already you have to be logged in so simplest solution and probably the best of terms on 'not detecting suspicious activity from instagram' is - use cookies exported from your browser e.g with cookie-editor extension. I don't really know what you want to achieave so it's hard to me to tell. I'll just give any example that I used. First get user id with that endpoint so we can use it later `https://www.instagram.com/api/v1/users/web_profile_info/?username=username_here` 

Then let's use user_id so we can get some post info: `https://www.instagram.com/graphql/query/?variables=%7B%22id%22%3A{user_id}%7D&query_hash=e7e2f4da4b02303f74f0841279e52d76`

In response we getting posts_id so we can finally get likers data with: `https://www.instagram.com/api/v1/media/{media_id}/likers/`

All these endpoints except that graphql with query_hash are available in your browser dev tools, so you can try it yourself, figure out what data it returns etc. 

Btw there's actually something that returns paginated likers! Some API here actually handling likers pagination despite disabling query_hash by instagram: https://rapidapi.com/search/instagram

**Comment by MateuszAbramczuk** [comment]
Thanks a lot @Skuxblan, the website that you have provided is amazing. It is helping me a lot. I'm really grateful for it. Thank you a lot really, you made my day when I have read your comment
