### ISSUE TITLE
hastag.get_posts() doesn't seem to be working anymore

### ISSUE THREAD

**Issue by goodbyenary** [instaloader/instaloader#2206]
I'm attempting to download all posts associated with a particular hashtag that were posted within a specified timeframe. I've followed the instructions provided, and after troubleshooting, it appears that Instaloader is unable to locate any posts associated with the hashtag or doesn't have access to them. I've experimented with multiple hashtags and timeframes, including popular hashtags like #gender and broader time periods, yet the issue persists.

Upon running the code, the first line displays: 'JSON Query to explore/tags/#gendern/: 404 Not Found.'

Any assistance would be greatly appreciated!

**Comment by jmatzen** [comment]
Yup I've also run into this.

**Comment by thamaradias** [comment]
Me too

**Comment by anmnmnn** [comment]
me too

**Comment by cbyya** [comment]
me too，
How to solve this problem?

**Comment by natashacarpcast** [comment]
I have the same issue!

**Comment by giovsta** [comment]
I have the same issue, tried everything from changing user agent to switching to many different types of connections, both through VPNs and using different domestic WiFis. I think Instagram changed the way hashtag pages are called, and the Instaloader team has not addressed this yet. 
I don't understand why though, considering that hashtags are the primary thing I download and many I know do the same

**Comment by mobylabch** [comment]
Same issue here. Error 404.

**Comment by debora-alayo** [comment]
same here :c Errors or warnings occurred:
Get hashtag #kitten: JSON Query to explore/tags/kitten/: 404 Not Found

**Comment by kentdtran** [comment]
I am also getting this error when trying to explore hashtags:
Get hashtag #kitten: JSON Query to explore/tags/kitten/: 404 Not Found

**Comment by TheSnowGuru** [comment]
> Same issue here. Error 404.

please test this , for me it [worked](https://apify.com/apify/instagram-scraper?fpr=cfknx )

**Comment by dennyabrain** [comment]
I just encountered the same issue. for a hashtag like "#standup", the error says `JSON Query to explore/tags/standup/: 404 Not Found`

When I inspected what instaloader was doing under the hood, I learnt that its using the requests library's session object to make a get request  
The code for it is in `instaloadercontext.py` 

`sess.get('https://{0}/{1}'.format(host, path), params=params, allow_redirects=False)`

By logging the variables host and path, I can see that instaloader is trying to make a GET request to `www.instagram.com/explore/tags/standup/` with params = `{'__a': 1, '__d': 'dis'}`

When I inspect the networks tab of my browser, one of the request that seems to be related to this tag look like this `https://www.instagram.com/api/v1/tags/web_info/?tag_name=standup` 

Is it possible that the API endpoint for this has changed?

**Comment by giovsta** [comment]
The 

> I just encountered the same issue. for a hashtag like "#standup", the error says `JSON Query to explore/tags/standup/: 404 Not Found`
> 
> When I inspected what instaloader was doing under the hood, I learnt that its using the requests library's session object to make a get request The code for it is in `instaloadercontext.py`
> 
> `sess.get('https://{0}/{1}'.format(host, path), params=params, allow_redirects=False)`
> 
> By logging the variables host and path, I can see that instaloader is trying to make a GET request to `www.instagram.com/explore/tags/standup/` with params = `{'__a': 1, '__d': 'dis'}`
> 
> When I inspect the networks tab of my browser, one of the request that seems to be related to this tag look like this `https://www.instagram.com/api/v1/tags/web_info/?tag_name=standup`
> 
> Is it possible that the API endpoint for this has changed?

The API surely changed, but I think it is just a change of the labels of some elements in the hashtag webpage. I don't understand why Instaloader's developers haven't addressed this yet, as the hashtag scraping part is a major function of the script.

**Comment by dennyabrain** [comment]
its free software at the end of the day :) we're as responsible for fixing the issues.

**Comment by giovsta** [comment]
I haven't expressed a valorial judgement, just an observation of something I find weird. They did two releases already and none addresses the problem.

**Comment by Tallerian** [comment]
> its free software at the end of the day :) we're as responsible for fixing the issues.

True. By any chance, have you found an existing solution for scraping hashtags?

**Comment by dennyabrain** [comment]
Its not a very urgent priority for a project that I am working on but I do have to get scraping posts by hashtags working soon. So i might have an update on this for you later. 
One approach we've been trying is to write a selenium based automation that visits the webpage with hashtag and automates the process of clicking on videos and getting their URLs and certain metadata. Not the most elegant and low resource solution though. 
I did fairly basic debugging of instaloader itself and will continue on that as well. especially if its just a matter of changing few endpoints and fields. Will update here if i make any progress.

**Comment by giovsta** [comment]
I think this should remain open

**Comment by goodbyenary** [comment]
Hi, it seems like this issue is still there. Did anyone figure out any alternatives at all?

**Comment by RazyRo** [comment]
Yes
