### ISSUE TITLE
error 429, how to bypass the rate limit?

### ISSUE THREAD

**Issue by bigiluigi** [instaloader/instaloader#2208]
How can I bypass error 429?
I tried to implement the use of proxies but it didn't work (maybe I did something wrong). Could someone give me an example on how I can use proxies with instaloader or alternative solutions on how to bypass the rate limit.

**Comment by Skuxblan** [comment]
Hi, more details would be useful, but if you use public request (not logged into account) request switching your ip with proxy will be enough. If you sending private request (with account)  you should switch account.

**Comment by bigiluigi** [comment]
> Hi, more details would be useful, but if you use public request (not logged into account) switching your ip with proxy will be enough. If you sending private request (with account)  you should switch account. 

are you sure about private requests? secondly, even if I change accounts I think it always depends on the IP, but in any case I would like to use only one account. Could you give me an example of how to use proxies and which ones to use (possibly free proxies)

**Comment by bigiluigi** [comment]
> I wish you good luck with free proxies. 99% of them are marked as spam IP by instagram so you will always hit limit. You should use high quality paid proxies for social media. I can confirm while I'm scraping for example followers data when I hit limits on one account just switching it to another account (same ip) helps to avoid it.

ok thank you. other methods other than proxies and account switching?

**Comment by Skuxblan** [comment]
I'm not sure is there any other solutions that makes sense. You can buy instagram accounts for few cents and rotating residential proxies costs ~3$ per 1 gb. Not a fortune really but time saving.

**Comment by bigiluigi** [comment]
@Skuxblan I have a question, if I were to use account switching, could I also use saved sessions or should I log in every time to bypass the rate limit? If both methods were fine, what do you recommend?

**Comment by Skuxblan** [comment]
> @Skuxblan I have a question, if I were to use account switching, could I also use saved sessions or should I log in every time to bypass the rate limit? If both methods were fine, what do you recommend?

I think saved session is best way. Instagram may detect unusual activity and want you to do captcha for example, so saved session with cookies is your best choice

**Comment by bigiluigi** [comment]
I have another problem, using saved sessions (I used Firefox's cookies.sqlite file to extract saved sessions), while the code is running some accounts are logged out. 

```
#first there is the initial part of the code which is not important

current_username_index = 0

async def scarica_storie_e_post():
    global L
    global current_username_index

    try:
        username = ACCOUNT_USERNAMES[current_username_index]
        L = Instaloader()
        L.load_session_from_file(username)
        current_username_index = (current_username_index + 1) % len(ACCOUNT_USERNAMES)

        for username in utenti_da_monitorare:
            profile = L.check_profile_id(username)
            stories = L.download_stories(userids=[profile.userid], filename_target='{}'.format(profile.username))

#continuation of the code...
```

it's an automated code that repeats every minute, using 9 accounts I didn't have any rate limit problems but the only problem is that some saved sessions disconnect after about 24/48 hours.
