### ISSUE TITLE
--max-connection-attempts only works when directly specifying

### ISSUE THREAD

**Issue by Moquo** [instaloader/instaloader#221]
**Describe the bug**
--max-connection-attempts can't be used with the options in a file (`instaloader +options.txt`). It only works when directly specifying it when executing the command (`instaloader --max-connection-attempts 0`).

**To Reproduce**
First of all, here is my args-file:
```
--login=<login>
--sessionfile=.instaloader-session
--stories
--highlights
--tagged
--comments
--geotags
--post-metadata-txt="{caption} || {likes} likes, {comments} comments"
--storyitem-metadata-txt="Will expire/Expired on {expiring_utc}."
--filename-pattern={date_utc}_UTC/{date_utc}_UTC
--max-connection-attempts 0
--quiet
--fast-update
```
Then I'm executing this with the command `instaloader +instaloader-args.txt <profile>` and then it says that the option `--max-connection-attempts 0` is unrecognized (look down for the error).  
When I'm directly passing it to the command (`instaloader --max-connection-attempts 0 <profile>`) it works fine.

**Expected behavior**
The command shouldn't throw an error because of an unrecognized argument.

**Error messages and tracebacks**
```
usage: 
instaloader [--comments] [--geotags] [--stories] [--highlights] [--tagged]
            [--login YOUR-USERNAME] [--fast-update]
            profile | "#hashtag" | %location_id | :stories | :feed | :saved
instaloader --help
instaloader: error: unrecognized arguments: --max-connection-attempts 0
```

**Instaloader version**
4.2

**Comment by e5150** [comment]
Might depend on the python version. I don't get an exception with your argument file, it is just silently ignored, and `args.max_connection_attempts == 3`. By putting an equal sign in the file (i.e. `--max-connection-attempts=0`) I get the expected result.

**Comment by Moquo** [comment]
> Might depend on the python version. I don't get an exception with your argument file, it is just silently ignored, and `args.max_connection_attempts == 3`. By putting an equal sign in the file (i.e. `--max-connection-attempts=0`) I get the expected result.

Using an equal sign in the file (`--max-connection-attempts=0`) works for me.  
Is this intended or is this a bug?
