### ISSUE TITLE
Impossible to retrieve Location info | Especially Latitude and Longitude

### ISSUE THREAD

**Issue by alebuffoli** [instaloader/instaloader#2212]
**Describe the bug**
Impossible to retrieve Location info, especially Latitude and Longitude

**To Reproduce**
```
for post in profile.get_posts():
    post.location
```

**Expected behavior**
I expect a location info object

**Error messages and tracebacks**
JSON Query to explore/locations/815623301860707/: HTTP error code 201. [retrying; skip with ^C]
JSON Query to explore/locations/815623301860707/: HTTP error code 201. [retrying; skip with ^C]
JSON Query to explore/locations/815623301860707/: HTTP error code 201.

**Instaloader version**
instaloader==4.10.3

**Additional context**
If i do the following, I get some location info, but no latitude and longitude

```
post._node['location']
{'id': '26058259', 'has_public_page': True, 'name': 'Forestis Dolomites', 'slug': 'forestis-dolomites'}

```

**Comment by PyroFilmsFX** [comment]
Encountering the exact same issue.
