### ISSUE TITLE
The cover image download feature downloads the wrong image

### ISSUE THREAD

**Issue by powerfulzeus** [instaloader/instaloader#2213]
the highlight covers downloaded are not correct. Instaloader seems to be pulling the covers from the highlights themselves rather than the actual image.

**Comment by trupax8** [comment]
I have the same problem, the actual cover image I don't see in the downloads. It took the first image of the Highlight

**Comment by EveryDirection** [comment]
I can confirm this bug. When you specify the --highlights option, the image file that is downloaded as the cover image often does not match the cover image actually seen in the profile.
