### ISSUE TITLE
Multiple post owners

### ISSUE THREAD

**Issue by edoardocolella** [instaloader/instaloader#2217]
**Provide us a use case of the feature**
A user may need to have the profile owner list of a post. Instagram currently offers the ability to make posts shared among multiple profiles

**Describe alternatives you've considered**
The owner property should be identified by a vector (or other container).
Other options should be evaluated to provide compatibility with previous versions, for example a new property "owner_list"

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes, i could try

**Comment by aandergr** [comment]
Yes, this would be a nice feature!

However, it would be better to not change the `owner_profile` property, both as there still seems to be one designated owner, even in posts that are shared among multiple profiles, and as that would cause trouble regarding compatibility between Instaloader versions. Hence, we would prefer a new property, e.g. named `owner_list`.
