### ISSUE TITLE
Get hashtag #vegan: JSON Query to explore/tags/vegan/: 404 Not Found

### ISSUE THREAD

**Issue by estatistics** [instaloader/instaloader#2219]
**Describe the bug**
instaloader do not download hashtags

**To Reproduce**
trickle -s -v -d 100 instaloader --login=USER --fast-update    --user-agent "Mozilla........." --abort-on=302,400,401,429,403  "#vegan"

**Expected behavior**
To download hashtags

**Error messages and tracebacks**
Loaded session from .......
Logged in as .......
JSON Query to explore/tags/vegan/: 404 Not Found [retrying; skip with ^C]
JSON Query to explore/tags/vegan/: 404 Not Found [retrying; skip with ^C]
Get hashtag #vegan: JSON Query to explore/tags/vegan/: 404 Not Found
Saved session to /home/.........

**Instaloader version**
4.10.2

**Comment by Nosratimrn** [comment]
same here

**Comment by giovsta** [comment]
it's been an issue for some months now, I have no idea why not even one of the developers has addressed it yet

**Comment by goodbyenary** [comment]
i have the same issue

**Comment by Showmaster3000** [comment]
Duplicate of #2144
