### ISSUE TITLE
[Question] Default settings? Config file?

### ISSUE THREAD

**Issue by m4gnet98** [instaloader/instaloader#222]
Hey.
Been using Instaloader for a few days and I think it's awesome.
Something I'm missing though is a config file for default settings, like always downloading stories, always fast updating, without having to specify it in the command line.

Also having a list of profiles I want to auto download, without having to type them in myself every time.

I'm aware this can be done with some coding, cronjob, windows tasts etc, but I'm not smart enough to do that without guides etc.

Thoughts?

thanks
-M

**Comment by aandergr** [comment]
Instaloader can take its parameters (options or targets to download) from a file, as described here: https://instaloader.github.io/cli-options.html#cmdoption-arg-args-txt

So you could for example create a file `config.txt` and a file `profiles.txt` and call Instaloader with
```
instaloader +config.txt +profiles.txt
```

**Comment by m4gnet98** [comment]
Totally missed that, thanks a lot!
