### ISSUE TITLE
Add more return fields on 'get_sidecar_nodes' method

### ISSUE THREAD

**Issue by Sprizgola** [instaloader/instaloader#2222]
**Provide us a use case of the feature**
The user should call _get_sidecar_nodes()_ or adding a list of GraphImage fields at the method call such as __get_sidecar_nodes(fields=["id", "shortcode", ....])_.
The return type should be either a GraphImage or a PostSidecarNode (as currently is)

**Describe the solution you'd like**
It could be a nice thing to add the fields in the `instaloader.structure.Post.get_sidecar_nodes` method. 
The node is already in memory during the execution, so it could be a nice feature to add.

The actual implementation _yield_ this response:
 
`  yield PostSidecarNode(is_video=is_video, display_url=display_url, video_url=node['video_url'] if is_video else None)`

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes (with some assistance during PR!)

**Additional context**
This feature could be a cool thing because, in my case, i need the metadata for every image without the needing to access private attribute.

**Comment by aandergr** [comment]
PostSidecarNode could be modified to contain more of the fields that are provided with the sidecar nodes. PostSidecarNode is currently implemented as a NamedTuple, however, these can be easily and backwards-compatibly refactored to a proper class, like has recently been done with PostComment.
