### ISSUE TITLE
Is it possible to download a instagram reel with audio, using instaloader?

### ISSUE THREAD

**Issue by om2007** [instaloader/instaloader#2227]
I have been trying to download a instagram reel using instaloader, but it downloads the reel without audio every time. How can I download the unmuted reel or is it even possible.

**Comment by Showmaster3000** [comment]
Reels which are listed on the tab reels cannot be downloaded with instaloader cause it is not supported yet (see #2207)
If it's also listed in posts tab, then downloading is possible. You can download what so see in the app. Sometimes the audio track is removed by instagram cause the lack of rights.
Can you give an example where it doesn't work?
