### ISSUE TITLE
Trying to load_session_from_file, but it's looking in /var/folders/...

### ISSUE THREAD

**Issue by maxiedaniels** [instaloader/instaloader#2228]
So, i had the issue where i was getting a wrong password error, so i tried the firefox session cookie import snippet in the docs, which resulted in this:
`Saved session to /Users/myusername/.config/instaloader/session-myuser.`

Now i do:
```
L = instaloader.Instaloader(download_pictures=False, download_videos=False, download_video_thumbnails=False, download_comments=False)
L.load_session_from_file("/Users/myusername/.config/instaloader/session-myuser")
```

But i get this error:
`FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/05/bzkf04vj585f_nw3nqbzhy0m0000gn/t/.instaloader-myusername/session-/users/myusername/.config/instaloader/session-myuser'`

Seems like a bug to me, as I'm using a full path and it's looking in /var/folders...

**Comment by danhimalplanet** [comment]
I looked at the function signature, this worked for me:

>INSTAGRAM_USER="myuser"
>SESSIONFILE="/Users/myusername/.config/instaloader/session-myuser"
>L = instaloader.Instaloader(download_pictures=False, download_videos=False, download_video_thumbnails=False, download_comments=False)
>L.load_session_from_file(username=INSTAGRAM_USER, filename=SESSIONFILE)

**Comment by morpheuslord** [comment]
I am not able to save a session file and I am getting this error:

 with open(filename, 'rb') as sessionfile:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\chira\\appdata\\local\\temp/.instaloader-user/session-user'
