### ISSUE TITLE
401 error using post.get_comments().

### ISSUE THREAD

**Issue by guptaxvivek** [instaloader/instaloader#2230]
**Describe the bug**
Getting 401 error while login and using post.get_comments() function.

**To Reproduce**
I'm using this code to extract all comments and post details:
```
def insta_com(uname, shortcode):
    L = instaloader.Instaloader()
    comments = []
    L.load_session_from_file(username=uname,filename=f"session-{uname}")
    post = instaloader.Post.from_shortcode(L.context, shortcode)
    for comment in post.get_comments():
        comments.append(comment.text)
    print({
        "caption": post.caption,
        "likes": post.likes,
        "comments": comments,
        "posted_at": post.date_local,
        "media_type": post.typename,
        "media_url": post.url,
    })
```
**Expected behavior**
get all the comments and post details

**Error messages and tracebacks**
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Traceback (most recent call last):
  File ".\venv\lib\site-packages\instaloader\instaloadercontext.py", line 413, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 401.

**Instaloader version**
4.11

**Comment by H-F-T** [comment]
Same issue with version 4.10.2
