### ISSUE TITLE
posts views not accurate  

### ISSUE THREAD

**Issue by MohamedArif-thaagam** [instaloader/instaloader#2231]
**Describe the bug**

**To Reproduce**
(e.g. Instaloader command line)

**Expected behavior**
A clear and concise description of what you expected to happen (even if it seems obvious).

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

**Instaloader version**
`instaloader --version` output.

**Additional context**

**Comment by Showmaster3000** [comment]
nothing more than the title set. so closing with no template
