### ISSUE TITLE
Fatal error: Login error: "fail" status, message "CSRF token missing or incorrect".

### ISSUE THREAD

**Issue by aivanouski** [instaloader/instaloader#2232]
instaloader --login=x --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"  y

provides 
```
Session file does not exist yet - Logging in.
Enter Instagram password for x
```
```
Fatal error: Login error: "fail" status, message "CSRF token missing or incorrect".
```

same with user-agent and without

**Comment by Showmaster3000** [comment]
your bug report is incomplete. which version are you using?
Login was changed in the last release but tends to be buggy. Check alternatives like grabbing session from browser by script or cmd parameter [`--load-cookies`](https://instaloader.github.io/cli-options.html#cmdoption-load-cookies)
