### ISSUE TITLE
How to download Ig story only using cmd command? download more than 1500 posts?

### ISSUE THREAD

**Issue by BlackRed993** [instaloader/instaloader#2235]
How to download Ig story only using cmd command?

also, If an ig account has more than 1500 posts, e.g.5000 posts, how to download over 1500 posts in cmd command ? download over 1500 posts will get blocked. I used the "instaloader --latest-stamps" command, but it didn't work.
After being blocked, the next time I download it, it will automatically start downloading from the first photo, and then be blocked again. In this way, I can only download the first photo to the 1500th photo, and cannot download the 1501st photo to the 5000th photo.

**Comment by Showmaster3000** [comment]
Everything is described in the manual: https://instaloader.github.io/basic-usage.html#what-to-download

To download story only use: `instaloader --stories  --no-posts --login youraccount targetaccount`

**Comment by BlackRed993** [comment]
> --stories --no-posts

I can't download, it shows an error message.

Loaded session from C:\Users\ABC\AppData\Local\Instaloader\session-XXXXX.
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Fatal error: JSON Query to graphql/query: HTTP error code 401.
