### ISSUE TITLE
Last 30 days Followers & Following  count

### ISSUE THREAD

**Issue by shubham-spreadd** [instaloader/instaloader#2239]
**Provide us a use case of the feature**
As a user, I want to track the follower growth of a specific Instagram creator over the last 30 days. This feature would enable me to monitor the trend of follower growth and visualize it on a dashboard, allowing for insights into the creator's audience engagement and overall popularity. If new information is obtained, such as spikes or dips in follower count, it could be further processed to analyze the factors contributing to these changes, such as content strategy adjustments or external promotions.

**Describe the solution you'd like**
I would like a function that retrieves the follower count of an Instagram user for each day over the last 30 days. This function should return a dataset or JSON object containing the date and corresponding follower count, allowing for easy plotting and analysis. Additionally, it would be beneficial if this function could be integrated into existing analytics tools or dashboards for seamless monitoring and reporting.

**Describe alternatives you've considered**
One alternative solution could be manually recording the follower count each day and plotting the data using spreadsheet software or programming languages like Python with libraries such as Matplotlib or Plotly. However, this approach is time-consuming and prone to errors, especially for users with a large number of followers or multiple creators to track.

**If the feature request is accepted, would you be willing to submit a pull request?**
No

**Additional context**
This feature would be valuable for social media managers, marketers, and creators themselves to assess the effectiveness of their content strategies and promotional efforts. By visualizing follower growth trends, users can make informed decisions to optimize their Instagram presence and maximize audience engagement.
```

**Comment by samadbek-e** [comment]
That's very clever idea, but I don't think it should be implemented into instaloader library. What are you saying is very niche. Still, You can create your own library using instaloader, and people who need this feature would love to use your library

**Comment by aandergr** [comment]
Nice idea, however, it is out of scope.
