### ISSUE TITLE
Daily Follower Growth Tracking

### ISSUE THREAD

**Issue by shubham-spreadd** [instaloader/instaloader#2240]
Could Instaloader incorporate a feature to track the daily follower growth of Instagram creators over the last 30 days? This functionality would be immensely beneficial for users seeking to monitor trends in follower counts and analyze audience engagement strategies. Thank you for considering this enhancement!

**Comment by Showmaster3000** [comment]
Is this information available via Instagram? If no, then this feature is not possible. But you can build it for your own.
Use instaloader to grab the follower count each day using a cron job or something similar, save the information f.e. in a database and just use the data.
