### ISSUE TITLE
Filter by date doesn't seem to be working for me

### ISSUE THREAD

**Issue by bialyrycerz** [instaloader/instaloader#2246]
I am using the construct `instaloader --post-filter="date_utc <= datetime(2018, 5, 31)" target` from the documentation, but instaloader seems to be ignoring that and downloading all posts anyway.

Using the command line:
`instaloader +/Users/user/Documents/iloader.txt`

iloader.txt contains:
```
--filename-pattern={date_utc:%Y-%m-%d_%H-%M-%S}_{mediaid}_{owner_id}
--no-captions
--no-videos
--post-filter="date_utc >= datetime(2024,1,1)"
username
```

Based on the documentation, I would've expected this to download posts after 1/1/2024, but it's downloading everything.
It _is_ the first time downloading this user; does that supersede any filter commands?
Or, is there something incorrect I'm doing here?
Thanks

**Comment by samadbek-e** [comment]
> I am using the construct `instaloader --post-filter="date_utc <= datetime(2018, 5, 31)" target` from the documentation, but instaloader seems to be ignoring that and downloading all posts anyway.

Isn't it supposed to be `date_utc >= datetime(2018, 5, 31)`

**Comment by bialyrycerz** [comment]
After. Wouldn't `date_utc >= datetime(2024,1,1)` scrape posts after 1/1/2024? Or am I misunderstanding something?

**Comment by giovsta** [comment]
I did date filtering like this:
`SINCE = datetime(2023, 1, 1)  # further from today, included
print("Downloading since: ", SINCE)

UNTIL = datetime(2024, 1, 1)  # closer to today, not included
print("Downloading until: ", UNTIL)
    
for post in profile_posts:
    postdate = post.date
    time_stamp = str(postdate)
    if postdate > UNTIL:
        print("Ain't there yet! The post is from " + time_stamp)
        continue
    elif postdate < SINCE:
        print("I may have gotten too far: the post is from " + time_stamp)
        break
    else:
        print("Downloading from " + time_stamp)
        L.download_post(post, username)'

I haven't tested it right now, but a few weeks ago it worked, let me know if this helped!

**Comment by bialyrycerz** [comment]
Thank you -- I am trying to do this via the command line option, though...but maybe that won't work.

**Comment by bialyrycerz** [comment]
Update: I am finding that `--post-filter `seems to work when I use it directly on the command line, but not from an args file.

So:
`instaloader --post-filter="date_utc > datetime(2024, 1, 1)" --filename-pattern={date_utc:%Y-%m-%d_%H-%M-%S}_{mediaid}_{owner_id} <target>` skips earlier posts as expected. But using it in the args file I posted originally does not.

**Comment by makako-dev** [comment]
@bialyrycerz OK I was having the same issue and I got it working. On your args files, you need to remove the quotes from the conditional expression, such as: 

--filename-pattern={date_utc:%Y-%m-%d_%H-%M-%S}_{mediaid}_{owner_id}
--no-captions
--no-videos
--post-filter=date_utc >= datetime(2024,1,1)
username

Now my only question is, if the posts are "skipped", does this count against our rate limit?
