### ISSUE TITLE
Login requirement on Profile download

### ISSUE THREAD

**Issue by samadbek-e** [instaloader/instaloader#2249]
`Profile.from_username(L.context, username)`

I read on documentation that says "Login will be required to get data from username", but still I can get information from username. If I get too much information later, will login be required? Thanks

![image](https://github.com/instaloader/instaloader/assets/96782970/eb7e51d5-c249-4d11-9aee-6699da0cb622)

**Comment by samadbek-e** [comment]
I hadn't add `L.login`

**Comment by F04C** [comment]
Yes, I have this problem also where i have been `updating` all profiles on my local and i get a user-mismatch after some time. Gonna check what i can PR on this problem. 

But if, for example, there's only a small number of profiles to be updated then there's no need for the `--login` to be used
