### ISSUE TITLE
i.instagram.com redirecting to login page

### ISSUE THREAD

**Issue by NobodyJuno** [instaloader/instaloader#2250]
It looks like Instagram is cracking down and made another update.  I'm getting "Redirected to login page. Use --login" for all download attempts.
Creating a new account gets the account disabled with the first pull and banned within a day.

HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=xxxxxxx to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
xxxxxxx : Redirected to login page. Use --login.

Errors or warnings occurred:
xxxxxxx : Redirected to login page. Use --login.

**Comment by samadbek-e** [comment]
Did you login? `L.login(username, password)`
