### ISSUE TITLE
Checkpoint Required is not working

### ISSUE THREAD

**Issue by samadbek-e** [instaloader/instaloader#2251]
![image](https://github.com/instaloader/instaloader/assets/96782970/fe94134f-288b-4550-9b9c-057d30c50152)

So, first of all it is giving me a wrong url. But I copied second https address but still...

![image](https://github.com/instaloader/instaloader/assets/96782970/630da32b-28ed-483a-b02b-e8d07589cfd6)

It didn't work. I tried different browsers. If someone had this kind of issue, please help me to solve this. Thanks

**Comment by F04C** [comment]
Same error I got on this. 

`L = instaloader.Instaloader()`

Using `L.login(username, passwd) `on my code (same as using `--login`) gives me an error 

`An error occurred: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/AXFCafOiDQ_XRypUz57tb4J0shSaWvKiw_CNDaYaCWl7X4bO2hpKQqjRqVt4vtbY0qcfOmo/AfzMJ6PjvSZXM46Rc68381t_Ute8WryRwJ7hKCJIXcc7P3cJdAPcrCmBhVHZnQKHL2Kiy11cY4cpVQ/ffc_KWeTmh26zKnnfhBZWHMfv8cI5hNKFqWUhhU9hO1DfuagAbIqjnOUWmrqIn5xu7mZ/ - follow the instructions, then retry.`

Following the url got me this
![Screenshot 2024-05-10 224611](https://github.com/instaloader/instaloader/assets/81340347/179d2f29-c804-492a-b99e-6f6ca38b3c15)

**Comment by tcdent** [comment]
Same is happening for me. I ran the login command on another IP address (outside AWS) and it succeeded, so I just copied the session file over to my instance.
