### ISSUE TITLE
why I can't log into my account using cmd command?

### ISSUE THREAD

**Issue by BlackRed993** [instaloader/instaloader#2267]
It shows an error message.

Loaded session from C:\Users\ABC\AppData\Local\Instaloader\session-XXXXX.
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Fatal error: JSON Query to graphql/query: HTTP error code 401.

**Comment by arsenico13** [comment]
Exactly the same for me.

```
Loaded session from /Users/abcd/.config/instaloader/session-abcd.
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 401. [retrying; skip with ^C]
Fatal error: JSON Query to graphql/query: HTTP error code 401.
```

**Comment by arsenico13** [comment]
This is happening with both versions 4.11 and 4.10.3

**Comment by QuentinJ54** [comment]
Good morning,
I have the same problem like you when using cookies?

**Comment by arsenico13** [comment]
@QuentinJ54 
> Good morning, I have the same problem, how do you use cookies?

On "how do you use cookies", Instaloader does this automatically:

> When logging in, Instaloader stores the session cookies in a file in your temporary directory, which will be reused later the next time --login is given. So you can download private profiles non-interactively when you already have a valid session cookie file.

What you see in previous posts, the line that says "Loaded session from..." is about this, instaloader using a cookies session.

If your are asking about "how do you take a new browser cookie and use it" you can read about it here:
https://instaloader.github.io/troubleshooting.html#login-error
