### ISSUE TITLE
get_posts() with limit

### ISSUE THREAD

**Issue by BobikRekordik** [instaloader/instaloader#2269]
Hi. Make the **get_posts()** method accept the limit on the received data as an argument. There are pages with more than 100 thousand posts and it took me about an hour to do this.
I would like to get only the last n posts instead of all the posts by sending an argument. 
`posts = user.get_posts(50); #latest 50 posts only :)`

**Comment by Mesheo** [comment]
Hey @BobikRekordik! I saw your issue when running into the same problem. I went a little bit inside the code and I believe it does not make sense to change the behave of get_post() function, since is more a Node Generator at the end of our scrapping process.
I made a PR with the changes that worked here, you just need to use the new **recommend function** to get profile posts: `instaloader.download_profiles()`

Here it is a snippet code of how get some limiting amount of posts after this change
from instaloader import Instaloader, Profile
```py

USERNAME = "cachorroquentealex"
Instaloader = Instaloader()
profile = Profile.from_username(Instaloader.context, USERNAME)
Instaloader.download_profiles(profiles=[profile], max_count=2) # it will download only 2 posts on your destination folder
```

**Comment by BobikRekordik** [comment]
> Hey @BobikRekordik! I saw your issue when running into the same problem. I went a little bit inside the code and I believe it does not make sense to change the behave of `get_post()` function, since is more a NodeGenerator at the end of our scrapping process. Also, it already has this functionality of limiting posts download inside the `self.posts_download_loop()` method, for some reason the external calling functions were just not adjusted to receive and pass this argument further
> 
> I made a PR with the changes that worked here, you just need to use the new **recommend function** to get profile posts: `instaloader.download_profiles()`
> 
> Here it is a snippet code of how get some limiting amount of posts after this change
> 
> ```python
> from instaloader import Instaloader, Profile
> 
> USERNAME = "cachorroquentealex"
> Instaloader = Instaloader()
> profile = Profile.from_username(Instaloader.context, USERNAME)
> Instaloader.download_profiles(profiles=[profile], max_count=2) # it will download only 2 posts
> ```

Thanks, it's a good option, but the method downloads the whole page, I need it to return a List[] from these posts, there is a shortcode, id, description and others...

**Comment by aandergr** [comment]
To limit the number of posts retrieved by the `Profile.get_posts()` method in Instaloader without modifying the library itself, you can use Python's `itertools.islice` function to slice the result iterator. Here’s a brief explanation of how to implement this:

1. **Import the Required Libraries**: Ensure you import `islice` from the `itertools` module.

2. **Call the `get_posts()` Method**: Use the `get_posts()` method to get the iterator of posts for a specific user.

3. **Use `islice` to Limit the Posts**: Pass the result of `get_posts()` to `islice`, specifying the desired number of posts you want to retrieve.

Here’s an example of how to implement this:

```python
from instaloader import Instaloader, Profile
from itertools import islice

# Initialize Instaloader
loader = Instaloader()

# Log in to your Instagram account (optional)
loader.login("your_username", "your_password")

# Get the profile of the user
profile = Profile.from_username(loader.context, "target_username")

# Limit the number of posts to the latest n posts
n = 50  # specify the number of posts you want
posts = islice(profile.get_posts(), n)

# Iterate through the limited posts
for post in posts:
    print(post)  # You can access post attributes here
```

### Explanation:
- **`islice(profile.get_posts(), n)`**: This line takes the iterator returned by `get_posts()` and slices it to include only the first `n` posts.
- **`for post in posts:`**: This loop allows you to process or print the limited number of posts.

This way, you can easily get the latest `n` posts without modifying the `Instaloader` code directly.
