### ISSUE TITLE
Allow usage of zstd compression on json files

### ISSUE THREAD

**Issue by ealgase** [instaloader/instaloader#227]
Instaloader currently compresses json files with xz.  While xz offers good compression ratio, zstd has a specific and optimized mode for compressing many similar small files.  It would be very useful to use zstd compression instead of xz (and I anticipate it would save a significant amount of disk space). 

Edit: I've managed to get ~50% size reduction using zstd, and that's with a relatively small amount of training data.  711kb for zstd vs 1.4mb for xz.  Both were running with maxinum compression on this set of files: 

https://drive.google.com/file/d/1uWh83FDaIqMWqgojOhG_no6QOWcK0YyT/view

**Comment by aandergr** [comment]
I don't see any importance for this. XZ compresses fine, is part of the Python Standard Library, which I consider a major advantage, and I think that for the majority of users the size of these JSON files doesn't matter. However, I would probably merge a PR for this, if it is cleanly implemented and the extra dependency is optional.

**Comment by HCWcoder** [comment]
@aandergr  how can i read a json.xz file ?

**Comment by ealgase** [comment]
@HCWcoder `unxz FILE` makes it a normal json file.

**Comment by HCWcoder** [comment]
> @HCWcoder `unxz FILE` makes it a normal json file.

@ealgase Can i know how to use it ?

sorry im new here

**Comment by ealgase** [comment]
@HCWcoder A JSON file is just a text file, you can open it with a text editor to see the contents.

Most programming languages have libraries for using JSON files, if you're interested in doing that.

**Comment by HCWcoder** [comment]
If i need to open the json.xz in python and read it how can i do it ? @ealgase 
I tried searched everywhere nothing worked for me

**Comment by ealgase** [comment]
@HCWcoder https://docs.python.org/3/library/lzma.html should help you.

**Comment by aandergr** [comment]
I close this issue due to its inactivity and the low relevance of the suggested feature.
