### ISSUE TITLE
Can't re-log-in account

### ISSUE THREAD

**Issue by Yumahiro1015** [instaloader/instaloader#2272]
Hi! I would like to know the way of re-log-ining.
I log-ined my account a week ago. Then I can get about 100 pictures. Todoy I try to log-in the same account by this code, but I can't.
This account doesn't get banned, and is asked to register new password.
`L = instaloader.Instaloader()
L.login(my_user_name, password)`

**Comment by Showmaster3000** [comment]
any (error) message or something while executing your script?
Anyway it is better to login once and save it in a session file. Next time use that session file.

**Comment by Yumahiro1015** [comment]
Thanks for your comment!

Error message is 
> Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/action/~/ - follow the instructions, then retry

After displaying the message, "There is a possibility of unauthorized login from a third party." is desplayed in my instagram app.
And, I was asked to change its password.
After changing the password, I can't log-in this account whose password I changed then.
