### ISSUE TITLE
Instaloader Redirected to login page. Use --login Issue

### ISSUE THREAD

**Issue by pdbarma** [instaloader/instaloader#2275]
I ran into the issue of Redirected to login page. Use --login
It seems Instagram changed their API, Is there any new fix to this or is this a new issue?

**Comment by frozencap** [comment]
Was working fine until I pulled the same 3 profiles 10 times within 5 minutes, then I got a similar message

```
An error occurred while processing profile 'some_profile': Redirected to login page. Use --login.
```
