### ISSUE TITLE
Profile.from_username

### ISSUE THREAD

**Issue by abolfazlMKazemi** [instaloader/instaloader#2282]
wher i use 

profile = instaloader.Profile.from_username(loader.context, profile_name)
get error
HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=bbcpersian to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/

**Comment by SaurabhS78** [comment]
Facing the same issue. After logging in with my credentials this seem to be working for a few requests but idk if this is a reliable approach for handling large number of requests. I found a similar issue #1662 with no resolution

```
L = instaloader.Instaloader()
user_name = 'username'
passw = 'password'
L.login(user_name, passw)  
```

**Comment by F04C** [comment]
u getting rate limited. try another day. 

I suggest not to use your main acc when doing --login.
