### ISSUE TITLE
How to use cookie login to download in cmd?

### ISSUE THREAD

**Issue by BlackRed993** [instaloader/instaloader#2284]
https://instaloader.github.io/cli-options.html#login-download-private-profiles

I've read the instructions, but I still don't understand
how to find the cookies in chorme?

**Comment by Showmaster3000** [comment]
a little bit deeper in the manual you can find the following:
https://instaloader.github.io/troubleshooting.html#login-error

For Chrome there is a scipt in #1780.

In the last time a new function was implemented. You can grab the session from your browser using the parameter `--load-cookies` (requires version 4.11) and (re-)use saved sessionfile with instaloader.

similar issues #1787, #2027
