### ISSUE TITLE
formatting wrong

### ISSUE THREAD

**Issue by ShadowPeak** [instaloader/instaloader#2293]
So i'm having a problem with downloading posts in either jpg or mp4 format all posts are downloading as json files only. It starts out good by pulling the profile picture as a jpg but then every post after is only json how can i change that ?

**Comment by F04C** [comment]
if you're using the default instaloader and not referencing instaloader for your code then you can use this

`instaloader profile <profile_name>`

by using this, it automatically downloads all jpg, mp4, and txt 
![image](https://github.com/instaloader/instaloader/assets/81340347/eb1ca23e-19de-4bdd-a3f3-d562716b45db)
