### ISSUE TITLE
Banned account from instaloader

### ISSUE THREAD

**Issue by hdma** [instaloader/instaloader#230]
Hi, and sorry for my English!

Yesterday I tested some teams, logging into an account without a session, and as a result, my account was banned. The browser shows a message about an unusual login attempt - [https://i.imgur.com/DCCzE4F.png](https://i.imgur.com/DCCzE4F.png) But when I indicate that it was me - the instaloader still does not start: the cmd window flashes and closes. After 6 hours of waiting, they also did not unban. What can be done?

**Comment by hdma** [comment]
Through the browser you can go, but through the instaloader does not enter.

**Comment by hdma** [comment]
Hi!
I can’t login through the application, even when I copy the link from the screenshot and open it in the browser - https://i.imgur.com/bEPPoRL.png. I also blocked my account for 15 hours, but after unlocking it still doesn't come through the instaloader. What can be done?

**Comment by Showmaster3000** [comment]
> the cmd window flashes and closes

Why do you have a window flashing and closing? Sounds like you are using a batch-file. what about manual opening a cmd window and execute it there to see the output and maybe post it here?
Maybe I have a similar problem like you, but without output, nobody can say this or help you.

**Comment by hdma** [comment]
**Showmaster3000**, уes, I used batch-file - before I thought of entering the "pause" command)) After that, the window no longer closes and shows the following (I gave this screenshot above) - https://i.imgur.com/bEPPoRL.png

**Comment by hdma** [comment]
It seems to me that the solution is to enter the data given in the last screenshot (account confirmation with a code through an email) - not through a browser, but through cmd. But how to do that?

**Comment by Showmaster3000** [comment]
why not using a browser? what happens if you enter the link in a browser? The message advises you to do that.

**Comment by hdma** [comment]
**Showmaster3000**, every time I enter this link in the browser, but the Instaloader is not unlocked - the account is unblocked from the browser.

**Comment by hdma** [comment]
**Showmaster3000**, however, after a 20-hour break, account in Instaloader — worked!) Now I would like to know how to set up the "session" command correctly? Will it be correct if I point out like this? —

`--sessionfile=../session --login=... --password=...`

**Comment by AndCycle** [comment]
I get caught by instagram too,
some extra info, the resp_json response with generic error.
```
$ ./batch_insta3.sh
{'errors': {'error': ['Sorry, there was a problem with your request.']}, 'status': 'ok', 'error_type': 'generic_request_error'}
Traceback (most recent call last):
  File "/home/batch/local/bin/instaloader", line 11, in <module>
    sys.exit(main())
  File "/home/batch/local/bin/py3_virtualenv/runtime/lib/python3.6/site-packages/instaloader/__main__.py", line 410, in main
    storyitem_filter_str=args.storyitem_filter)
  File "/home/batch/local/bin/py3_virtualenv/runtime/lib/python3.6/site-packages/instaloader/__main__.py", line 89, in _main
    instaloader.login(username, password)
  File "/home/batch/local/bin/py3_virtualenv/runtime/lib/python3.6/site-packages/instaloader/instaloader.py", line 355, in login
    self.context.login(user, passwd)
  File "/home/batch/local/bin/py3_virtualenv/runtime/lib/python3.6/site-packages/instaloader/instaloadercontext.py", line 224, in login
    if not resp_json['authenticated']:
KeyError: 'authenticated'
```
