### ISSUE TITLE
Getting likers of posts doesnt work

### ISSUE THREAD

**Issue by Cpanthony05** [instaloader/instaloader#2303]
Hello everyone, i've been trying to scrape the users who have been recently liking the posts of a certain account, but with no succes. I tried logging in both directly and by session cookies.

The following code should demonstrate:
import instaloader
L = instaloader.Instaloader()
L.login(user, password)
profile = instaloader.Profile.from_username(L.context,profile)
for post in profile.get_posts() :
    post_likes = post.get_likes()
    for likee in post_likes :
         name = likee.username
         #do something

I'd expect the name variable to run through the names of the usernames who liked posts on that account but i get an error instead.

The error is this 
raise QueryReturnedBadRequestException(self._response_error(resp))
instaloader.exceptions.QueryReturnedBadRequestException:
400 Bad Request - "fail" status, message "feedback_required" when accessing (QUERY LINK)

I have the most recent version of instaloader downloaded.

**Comment by nikist97** [comment]
+1

**Comment by caozrich** [comment]
+1

**Comment by Yevgeniy-Ten** [comment]
+1

**Comment by ahianf** [comment]
+1
