### ISSUE TITLE
Ignore huge posts downloading 

### ISSUE THREAD

**Issue by gnu-like** [instaloader/instaloader#2308]
**Don't wanna download large file**
Is it possible ? post that is greater than 50 MB ,instaloader to avoid downloading

**Comment by Showmaster3000** [comment]
not possible. similar question as in issue #1234.
posts greater than 50mb can only be a video. you can exclude all videos by using the parameter `--no-videos` as a workaround.

**Comment by gnu-like** [comment]
I want other videos , live videos after saving is large more than 500 MB I don't want to download only large videos
