### ISSUE TITLE
download_pic function error

### ISSUE THREAD

**Issue by 1099271** [instaloader/instaloader#2309]
**Describe the bug** When using the download_pic method of the Instaloader class, a TypeError occurs if the mtime parameter is a float (representing a Unix timestamp). The method expects the mtime to be a datetime object, but when a float is passed, it attempts to call the .timestamp() method on the float, which results in the error 'float' object has no attribute 'timestamp'.

To Reproduce Steps to reproduce the behavior:

Create an instance of the Instaloader class.
Call the download_pic method with a filename, URL, and a float for the mtime parameter (e.g., the result of time.time()).
Observe the TypeError.
Example code snippet:

```
import instaloader
import time

L = instaloader.Instaloader()
current_time = time.time()  # This is a float representing the current Unix timestamp
L.download_pic('profile_pic.jpg', 'https://example.com/image.jpg', current_time)
```

Expected behavior The download_pic method should handle both datetime objects and floats for the mtime parameter without raising a TypeError. If a float is provided, it should be used directly as the modification time for the downloaded file.

Error messages and tracebacks
```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    L.download_pic('profile_pic.jpg', 'https://example.com/image.jpg', current_time)
  File "C:\path\to\instaloader\instaloader.py", line 97, in call
    return func(instaloader, *args, **kwargs)
  File "C:\path\to\instaloader\instaloader.py", line 357, in download_pic
    os.utime(filename, (datetime.now().timestamp(), mtime.timestamp()))
AttributeError: 'float' object has no attribute 'timestamp'
```

Instaloader version
```
instaloader --version
Output: instaloader 4.12
```

Additional context The mtime parameter is documented as a datetime object, but it is common to use Unix timestamps (floats) for file modification times in Python. The os.utime function, which is used internally by the download_pic method, can accept a float for the modification time. The issue seems to be a mismatch in expected data types between the mtime parameter and the internal usage in the download_pic method.

To resolve this issue, the download_pic method should be modified to check the type of the mtime parameter before attempting to call the .timestamp() method. If mtime is already a float, it should be used directly. Here is a suggested code change:

```
def download_pic(self, filename: str, url: str, mtime: Union[datetime, float], ...):
    # ... (rest of the code remains unchanged)

    # Modify the os.utime call to handle both datetime and float for mtime
    current_time = datetime.now().timestamp()
    if isinstance(mtime, datetime):
        mtime = mtime.timestamp()
    os.utime(filename, (current_time, mtime))

    # ... (rest of the code remains unchanged)

```

**Comment by aandergr** [comment]
Note that the `download_pic` method is designed to accept only a `datetime` object for the `mtime` parameter. The expectation is that users will pass the correct type as documented.

We recommend converting the float timestamps to `datetime` objects before calling the method. This way, you can ensure compatibility without introducing type ambiguity.
