### ISSUE TITLE
«--tagged» option

### ISSUE THREAD

**Issue by hdma** [instaloader/instaloader#231]
Hi, and sorry for my English!

When I add the "--tagged" option to my command, other profiles start downloading to the destination folder, which I did not specify. And when I remove the "--tagged" option from the command, the profile is downloaded normally. What is the reason?

Full command I am using:

`"%PYTHON%" "%FOLDER%\instaloader.py" --sessionfile="%FOLDER%\.session" --login=LOGIN --password=PASS --geotags --comments --stories --highlights --tagged --no-metadata-json --no-video-thumbnails --max-connection-attempts=0 --post-metadata-txt="{caption} || {likes} likes, {comments} comments" --dirname-pattern={profile} --filename-pattern={date_utc}_UTC.{shortcode} --fast-update PROFILE`

**Comment by aandergr** [comment]
`--tagged` downloads the posts where the given profiles are tagged (in the Instagram app the rightmost tab in the profile view). People get tagged mostly in posts of other profiles, and in the filename/dirname pattern, `{profile}` is always replaced by the one who posted the post.
