### ISSUE TITLE
download_pic(): [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted'

### ISSUE THREAD

**Issue by mef51** [instaloader/instaloader#2311]
**Describe the bug**

I have a script that archives some profiles. I can download a few posts and then I start getting this error almost incessantly. This started about two days ago, and the script was having no issues beforehand.

This is the output (urls edited for length)
```
Download <Post C9YD3XQtBR8> of khames.alrefi: download_pic(): HTTPSConnectionPool(host='instagram.fyto1-1.fna.fbcdn.net', port=443): 
Max retries exceeded with url: /v/XXX 
(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E2023DB9D0>:
Failed to establish a new connection: 
[WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted'))
```

It's complaining about port 443. I checked that I have nothing listening on that port.

**To Reproduce**

`instaloader --abort-on=400,401,403,429,404 --fast-update --no-resume khames.alrefi`

**Expected behavior**
Download post.

**Error messages and tracebacks**
See above

**Instaloader version**
4.12. Also happened with 4.10.

**Additional context**
I'm on windows.

Thanks for your time

**Comment by Showmaster3000** [comment]
Sounds like a problem with your Windows not sth. with instaloader. Any active firewall or antivirus?

**Comment by mef51** [comment]
No, none :( Issue started mid script, after running it nearly weekly.
My firewall was on, I turned it off and the issue still happens (though with the profile url instead of a post url)

**Comment by mef51** [comment]
I will close as it seems to be working again and is probably not an instaloader issue
