### ISSUE TITLE
Get_posts() is broken with login (Python)

### ISSUE THREAD

**Issue by Avisz** [instaloader/instaloader#2321]
**Describe the bug**
        get_posts() doesnt work with login 

**To Reproduce**
```
L = instaloader.Instaloader()
L.load_session_from_file(*session File*)
posts = instaloader.Profile.from_username(L.context, "username").get_posts()

for post in posts:
    L.download_post(post, target)
```

**Expected behavior**
        downloads posts from a profile

**Error messages and tracebacks**
        No error message
        process finishes with exit code 0

**Instaloader version**
        4.12

**Additional context**
        if  L.load_session_from_file(*session File*) is disabled , the profile downloads normally 
        # doesnt download age restricted profiles 
        # downloads only 12 posts  for non restricted profiles

**Comment by JalgasAralbaev** [comment]
Как вы вообще получили посты через get_posts()? у меня она ничего не возвращает просто пусто. Но вот stories работает

**Comment by Avisz** [comment]
> How did you even get posts via get_posts()? It doesn't return anything for me, just empty. But stories works

currently if u use session file (login) , it doesn't return anything , 

try this and it should return first 12 posts 

```
L = instaloader.Instaloader()
posts = instaloader.Profile.from_username(L.context, "username").get_posts()

for post in posts:
    L.download_post(post, target)
```

**Comment by JalgasAralbaev** [comment]
> > Как вы вообще получили посты через get_posts()? Он ничего не возвращает для меня, просто пусто. Но stories работают
> 
> в настоящее время, если вы используете файл сеанса (логин), он ничего не возвращает,
> 
> попробуйте это и это должно вернуть первые 12 сообщений
> 
> ```
> L = instaloader.Instaloader()
> posts = instaloader.Profile.from_username(L.context, "username").get_posts()
> 
> for post in posts:
>     L.download_post(post, target)
> ```

и в правду, из-за чего это может быть? я попробовал откатить версию instaloader но это не помагает

**Comment by ekalin** [comment]
Duplicate of #2319

**Comment by hmobinizade** [comment]
> > > Как вы вообще получили посты через get_posts()? Он ничего не возвращает для меня, просто пусто. Но stories работают
> > 
> > 
> > в настоящее время, если вы используете файл сеанса (логин), он ничего не возвращает,
> > попробуйте это и это должно вернуть первые 12 сообщений
> > ```
> > L = instaloader.Instaloader()
> > posts = instaloader.Profile.from_username(L.context, "username").get_posts()
> > 
> > for post in posts:
> >     L.download_post(post, target)
> > ```
> 
> и в правду, из-за чего это может быть? я попробовал откатить версию instaloader но это не помагает

This solution to make a login request without login is not the right way! First of all, it is not possible to get the list of posts to the end and it only gives 12 posts. Second, after a few requests, it is quickly limited!
