### ISSUE TITLE
Fetching Post metadata failed.

### ISSUE THREAD

**Issue by vishay28** [instaloader/instaloader#2322]
**Describe the bug**
When trying to fetch the comments for any post whilst logged in it downloads the image of the post but gives the error `Fetching Post metadata failed.`

**To Reproduce**
1. Logged in using the command line
2. Ran the command `instaloader -- -C5LRl2jsA5t --comments`

**Expected behavior**
Download the comments for the post

**Error messages and tracebacks**
`--comments: Fetching Post metadata failed.`

**Instaloader version**
4.12.1

**Comment by vishay28** [comment]
Solved:

Command requires the `--comments` to be before the post id so the command that worked was like this:
`instaloader --comments -- -C5LRl2jsA5t`

**Comment by fireattack** [comment]
To be more accurate, it needs to be before `--`, which marks the end of any keyword arguments.
