### ISSUE TITLE
i'm unable to scrape reels data

### ISSUE THREAD

**Issue by husnainwahid** [instaloader/instaloader#2323]
i was using instaloader to scrape reels data like views , numbers of comment etc but its not working anymore i have logged in using the session cookie 

standalone code for testing if instaloader was working or no and it did not returned any data

import instaloader
from instaloader.exceptions import ConnectionException, QueryReturnedBadRequestException, LoginRequiredException

def scrape_instagram_reels(username):
    L = instaloader.Instaloader()

    # Use session cookie for login
    session_cookie = '(my session cookie)'
    L.context._session.cookies.set('sessionid', session_cookie)

    try:
        # Load the profile
        profile = instaloader.Profile.from_username(L.context, username)
        print(f"Profile {username} loaded successfully.")

        reels = []
        for i, post in enumerate(profile.get_posts()):
            if post.typename == 'GraphVideo':  # Reels are videos
                reel = {
                    'id': post.mediaid,
                    'shortcode': post.shortcode,  # Add the shortcode
                    'video_url': post.video_url,
                    'views': post.video_view_count,
                    'likes': post.likes,
                    'comments': post.comments,
                    'caption': post.caption,
                    'upload_date': post.date.strftime("%Y-%m-%d %H:%M:%S")  # Format the date as desired
                }
                print(f"Scraped reel: {reel}")  # Debug print
                reels.append(reel)

        if not reels:
            print("No reels found or profile is private.")
        else:
            reels.sort(key=lambda x: x['views'], reverse=True)
            return reels
    
    except ConnectionException as e:
        print(f"Connection error while fetching posts: {e}")
    except QueryReturnedBadRequestException as e:
        print(f"Bad request error: {e}")
    except LoginRequiredException:
        print("Login required. Please check your session cookie and try again.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

    return []

if __name__ == "__main__":
    username = input("Enter the Instagram username to scrape: ")
    reels_data = scrape_instagram_reels(username)
    print(f"\nScraped data for {username}:")
    for reel in reels_data:
        print(reel)

**Comment by MonkeyKingViper** [comment]
Probably same as #2319
