### ISSUE TITLE
Trying to make a fix to get_posts, how can I figure out iphone endpoints?

### ISSUE THREAD

**Issue by maledictionmeyerson** [instaloader/instaloader#2325]
Get posts is broken when you are logged in (at least with a session file).

As attested to here:
https://github.com/instaloader/instaloader/issues/2319

I remember when get_comments was broken the author switched to an iPhone endpoint, and posted the gist of the code here:
https://gist.github.com/aandergr/35ad3881e726e2be8925cf09e719a68b

I'm having trouble figuring out the endpoint for posts of users however.
So far I'm trying variants like:
f"api/v1/users/{user.userid}/posts/"
or
f"api/v1/users/{user.userid}/info/posts/"

inspired by the iPhone structs in the source code and especially
f"api/v1/media/{post.mediaid}/comments/"
From the temporary (gist) solution he posted.

However, I am getting 404s.

Is there an API reference? I'm having trouble finding it if there is.

**Comment by fireattack** [comment]
`https://www.instagram.com/api/v1/feed/user/{user.userid}/`

**Comment by hmobinizade** [comment]
> Get posts is broken when you are logged in (at least with a session file).
> 
> As attested to here: #2319
> 
> I remember when get_comments was broken the author switched to an iPhone endpoint, and posted the gist of the code here: https://gist.github.com/aandergr/35ad3881e726e2be8925cf09e719a68b
> 
> I'm having trouble figuring out the endpoint for posts of users however. So far I'm trying variants like: f"api/v1/users/{user.userid}/posts/" or f"api/v1/users/{user.userid}/info/posts/"
> 
> inspired by the iPhone structs in the source code and especially f"api/v1/media/{post.mediaid}/comments/" From the temporary (gist) solution he posted.
> 
> However, I am getting 404s.
> 
> Is there an API reference? I'm having trouble finding it if there is.

Hi, I answered at https://github.com/instaloader/instaloader/issues/2319. You can check and comment. I hope your problem will be solved.

**Comment by sjorspa** [comment]
I tried it on an Android Emulator, too bad the app uses certificate pinning and my knowledge on the work around is a bit limited, I know it is possible but takes install of other tooling which was quite a lot of steps.
