### ISSUE TITLE
Cannot scrape followers on the second time 

### ISSUE THREAD

**Issue by Graychii** [instaloader/instaloader#2327]
**Describe the bug**
So instaloader worked just fine the first time after trying using it for the second time to scrape the list of followers (Around 400 followers) it gave me back this error I tried changing the password/ using a different account still the same issue

**Expected behavior**
To scrape the list of followers of the username I specified
**Error messages and tracebacks**
HTTP Error 400 (Bad Request) on GraphQL Query. Retrying with shorter page length.
HTTP Error 400 (Bad Request) on GraphQL Query. Retrying with shorter page length.
Failed to scrape followers: 400 Bad Request - "fail" status, message "checkpoint_required" when accessing https://www.instagram.com/graphql/query?query_hash=...

**Instaloader version**
`instaloader --version` output.
4.12.1

**Additional context**

**Comment by theresia** [comment]
Hi @Graychii how did you resolve this? I have been using instaloader for months but only now am running into this issue.

**Comment by theresia** [comment]
I saw IG provided a way / interface to confirm that these activities are from me, but now I get alternating error message of checkpoint_required and login_required https://accountscenter.instagram.com/password_and_security/login_activity/

**Comment by Graychii** [comment]
> Hi @Graychii how did you resolve this? I have been using instaloader for months but only now am running into this issue.

Didn't, gave up basically
