### ISSUE TITLE
Instaloader not downloading all photos

### ISSUE THREAD

**Issue by wongcc2012** [instaloader/instaloader#2328]
**Describe the bug**
Instaloader not downloading all photos
**To Reproduce**
(e.g. Instaloader command line)
instaloader (SomeoneProfile)

**Expected behavior**
Downloaded all photos from a profile

**Error messages and tracebacks**
[ 12/428] **SomeoneProfile**/2024-05-22_17-17-39_UTC_1.jpg **SomeoneProfile**/2024-05-22_17-17-39_UTC_2.jpg **SomeoneProfile**/2024-05-22_17-17-39_UTC_3.jpg **SomeoneProfile**/2024-05-22_17-17-39_UTC_4.jpg [💥🔫🤠 Patreon🧡 https://www.patr…] json
Iteration complete, deleted resume information file **SomeoneProfile**/iterator_e55wY8db.json.xz.
[root@KW-Cent-SMTP instaloader]#

**Instaloader version**
`instaloader --version` output.

 instaloader --version
4.9.5 (linux)

C:\Users\Desktop\instaloader-v4.12.1-windows-standalone>instaloader.exe --version
4.12.1
(Windows)

**Additional context**

**Comment by MonkeyKingViper** [comment]
If you're not logged in, yep that's happening right now. And if you're logged in and it's downloading nothing...yep that's happening right now.
#2319

**Comment by sapphirepro** [comment]
Any solution? I have the same thing, no posts being downloaded logged in. only stories and profile pic

**Comment by xathian** [comment]
Seems something changed on instagrams end, and it appears they might be detecting scraping more quickly. Bans are not rare to happen when you're scraping but today a lot of users of 4K Stogram are reporting being instantly banned the moment they tried to download an accounts posts.

**Comment by MonkeyKingViper** [comment]
> Any solution? I have the same thing, no posts being downloaded logged in. only stories and profile pic

Someone in #2319 seems to have figured out a way to fix it, but after saying they did, they didn't give any instructions for others to do so

**Comment by wongcc2012** [comment]
then it is Instagram limitation and we have nothing to do?

**Comment by MonkeyKingViper** [comment]
It's not a limitation. Instagram changed something so the old query doesn't return anything anymore. Something about parameters but it's code speak so I don't understand it.
https://github.com/instaloader/instaloader/issues/2319#issuecomment-2265725643
If you look at this post they say they did something but don't say what they did. So we're all just sitting here dead in the water until someone can either translate that, or a dev makes an update.

**Comment by wongcc2012** [comment]
any workaround?

**Comment by MonkeyKingViper** [comment]
Yes there's a workaround. https://github.com/instaloader/instaloader/issues/2319#issuecomment-2265725643
But you have to translate what they said into a usable click/type path. Otherwise it's just Jargon.

**Comment by Showmaster3000** [comment]
Please check the newest release v4.13 which should solve the problem.
