### ISSUE TITLE
Only able to scrape the first 10 posts

### ISSUE THREAD

**Issue by Annaldasula** [instaloader/instaloader#2335]
im using instaloader to scrape instagram profiles and get details of their posts like image , url, like ount , comment count , caption etc
from last 2 days im only able to scrape the first 10 posts . i used a filter of no_of_posts where i can give any no scrape the posts.
can anyone explain why is this happening and how to resolve this.

**Comment by Showmaster3000** [comment]
More information helps us to try to help you... 
- what are you trying - command line or script snipset
- instaloader version

**Comment by Annaldasula** [comment]
import pandas as pd
from instaloader import Instaloader, Profile
from datetime import datetime

# Define the profile username and number of posts to fetch
PROFILE = "atherenergy"
POSTS_COUNT = 100

# Initialize Instaloader with proxy settings
L = Instaloader()

# Load the profile
profile = Profile.from_username(L.context, PROFILE)

# Create an empty list to store the data
data = []

# Get all posts for the profile
posts = profile.get_posts()

# Iterate over each post and extract its data
for post in posts:
    if len(data) >= POSTS_COUNT:
        break
        
    try:
        data.append({
            'caption': post.caption,
            'likes': post.likes,
            'comments': post.comments,
            'date': post.date_local.strftime('%Y-%m-%d %H:%M:%S'),
            'post url': f"https://www.instagram.com/p/{post.shortcode}/",
            'location': post.location.name if post.location else None,
            'post_type': post.typename,
        })
    except Exception as e:
        print(f"Error processing post {post.shortcode}: {e}")

# Create a pandas DataFrame from the data list
df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv('instagram_posts.csv', index=False)

# Print the DataFrame
print(df)

instaloader version : 4.13

**Comment by estatistics** [comment]
same here. it seems that instagram something changed. try to download the stories of this profile: https://www.instagram.com/chiaraferragni/

only the first 10 stories are downloaded. This is a BUG. 
version 4.12

**Comment by estatistics** [comment]
another profil - no story is downloaded from instaloader https://www.instagram.com/xresenthhh_____/

**Comment by Showmaster3000** [comment]
@estatistics  you are writing about stories, the original author created this issue about posts - these are different things with different commands. Btw. if you are using instaloader less than 4.12.2, downloading posts (not stories) doesn't work anymore.
