### ISSUE TITLE
JSONDecodeError: Expecting value - Issue with Profile.from_id

### ISSUE THREAD

**Issue by AliZamaniJ** [instaloader/instaloader#2338]
Hello,

I have a large number of UserIds for which I need to retrieve profile information. Since the Instaloader library allows retrieval of profile information by username, my goal is to convert these UserIds into usernames. However, I'm encountering an issue when trying to do this using the Profile.from_id method in the Instaloader library. The issue seems to be related to a JSONDecodeError that occurs when attempting to parse the JSON response from the server.

Use the following code snippet to retrieve profile information:

```
import instaloader

L = instaloader.Instaloader()

user_id = 1234567
profile = instaloader.Profile.from_id(L.context, user_id)

print(profile.username)
```

**Expected Behavior:**
The profile information, specifically the username, should be retrieved and printed.

**Actual Behavior:**
The script fails with the following error message:

```
JSON Query to : Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]
...
instaloader.exceptions.ConnectionException: JSON Query to : Expecting value: line 1 column 1 (char 0)
```
**Additional Information:**

- Python Version: Python 3.12
- Instaloader Version: 4.12.1

I have checked my internet connection, and it seems stable. I have also tried using a VPN, but the issue persists. It seems that the server might be returning an empty or invalid JSON response.

Could you please advise on how to resolve this issue, or if this might be related to changes in Instagram's API?

Thank you for your help.

**Comment by ekalin** [comment]
Yeah, this is happening if you're not logged in. If you are logged in, it works.

It seems the endpoint used to fetch profiles from an id only works when logged in. I know that there's a different endpoint that is now being used by the web interface, but I'm not sure if it works without logging in, it would need to be tested.

**Comment by ekalin** [comment]
It's not the query for the profile info that is failing, but a previous query to get a `rxh_gis` parameter. I'm not exactly sure what this is, but it seems it was some kind of "signature" to authenticate requests, but it is only used in anonymous requests.

Apparently this is only used in this query (profile from ID, when not logged in), so I suppose all the code relating to `rxh_gis` can be removed.

For a quick fix, try editing `structures.py`, around line 912 (in the `Profile.from_id` function), removing the `rhx_gis` parameter from the `graphql_query` function.

**Comment by AliZamaniJ** [comment]
Hello,

Thank you for addressing the issue I raised.

However, obtaining profile information by user ID still requires login, and this issue has not been resolved with the removal of rhx_gis.

You can test it with the following code without logging in to verify:

```
import instaloader

L = instaloader.Instaloader()

user_id = 1234567
profile = instaloader.Profile.from_id(L.context, user_id)

print(profile.username)
```

Thank you again for your attention.
