### ISSUE TITLE
New "Max Count" Functionality

### ISSUE THREAD

**Issue by MonkeyKingViper** [instaloader/instaloader#2339]
In the notes for 4.13, one of the items included was an update to make "--count" work for profiles. At least I think that's what it meant. I just tried "--count 10" on a profile and had to manually abort after 11. 

The documentation for CLI options does not have an update to reflect how we are to use this from the command line. 

Can we please get an explanation and the documentation for this be updated please?

**Comment by Showmaster3000** [comment]
According to the coresponding issue #2269 the max_count parameter can only be used in scripting mode, not at the command line. see also [manual](https://instaloader.github.io/module/instaloader.html#instaloader.Instaloader.download_profiles)

**Comment by mumixam** [comment]
@Showmaster3000 This is incorrect. when this recently pull request was merged it was missing passing the max_count arg for function instaloader.download_profiles.

I'll submit a PR to fix this soon

**Comment by MonkeyKingViper** [comment]
Fantastic.! I was hoping that I hadn't been mistaken. This will be a very useful update
