### ISSUE TITLE
«Too Many Requests»

### ISSUE THREAD

**Issue by hdma** [instaloader/instaloader#234]
Hi, and sorry for my English!

I use the option "**--max-connection-attempts = 0**", but there are always big pauses between downloads (messages "**Too Many Requests**"), because of which it takes a long time to wait. Is there no way to increase the pause between calls, so that files download more slowly but steadily?

**Comment by aandergr** [comment]
No.

**Comment by aandergr** [comment]
You could of course modify InstaloaderContext._sleep() to wait longer, but what's the point of that?

https://github.com/instaloader/instaloader/blob/15fe3d5f2de3777c6c7488adc42c285df8863b6b/instaloader/instaloadercontext.py#L264-L267

**Comment by hdma** [comment]
Thanks for the reply, dear **aandergr**! If, as a result, the changes in InstaloaderContext._sleep() pauses will be less than those that are usual in the CMD window - it seems to me that it is worth it. Please tell me if I made a replacement for a pause from 2 to 5 seconds? — `time.sleep(min(random.expovariate(2.0), 5.0))`

**Comment by VasiliPupkin256** [comment]
Are there evidences that random sleep really prevents instagram from blocking the client or is it a reassurance?

**Comment by hdma** [comment]
> The second parameter of min (5.0) is the maximum time to wait, you may increase it to get longer waiting times.
Did I understand correctly that the second parameter should increase ("5.0") and that the increase in the first ("0.7") does not make sense?

**Comment by aandergr** [comment]
> Are there evidences that random sleep really prevents instagram from blocking the client or is it a reassurance?

No, there's no evidence about that, we're merely precautious. Generally, it is common to analyze access patterns to identify automated access, and we want to keep our access patterns a little more human-looking. Also, we certainly don't want to molest Instagram too much, especially considering the popularity our tool already has. There is, however, a "secret" flag --no-sleep to disable pauses between requests.

> Did I understand correctly that the second parameter should increase ("5.0") and that the increase in the first ("0.7") does not make sense?

Yes. For longer wait times decrease the first parameter and increase the second one.

**Comment by hdma** [comment]
With the setting `time.sleep(min(random.expovariate(3.2), 14.0))` in 13 hours 193 posts (500 files) were downloaded from 3937 posts (193/3937). Is it possible before a random pause to make a fixed pause? That is, download like this? -

1. file is being prepared for download
2. a fixed pause is made in 2 seconds
3. standard random pause is done
4. file is downloaded

It seems to me that a pause before a random pause is necessary, because when the random pause is triggered too early, in the initial range, the instagram begins to block the connection.
