### ISSUE TITLE
Instaloader doesn't appear to download all posts, and instead stops just short? (Not old 12 post limit bug)

### ISSUE THREAD

**Issue by xathian** [instaloader/instaloader#2342]
This is difficult to note since I can't tell if it's a software bug with downloading all the posts or a bug listing total posts as the wrong number.

Either way, since 4.13 I've noticed every time I download a new account the number it downloads never reaches the total count it displays. For example, I just downloaded an account and instaloader says there are 166 posts. The download only went to 160/166 and stopped. This is the 5th account I've downloaded since 4.13 and all 5 have done this, where they stop 5-10% short of the number of posts the downloader claims exists.

Also, running the downloader a second time does not grab these missing posts, it simply reaches the same number and stops.

**Comment by MonkeyKingViper** [comment]
I don't think you're actually experiencing a bug. I think you don't realize that the total post count (what IG says exists) includes hidden/archived posts. The tool will return this same total but can't access all of them as well

For your example, if you see 166 is the total, and then you count them, are there 166 or 160? Last night I downloaded an account with 141 rows of 3 images which is 423 photos. But the account and tool both said there should have been 460. Yet I could only access and download the 423.

I bet if you count the posts, you'll see that there are 160, and that means there are 6 archived/hidden posts

**Comment by MonkeyKingViper** [comment]
> I don't think you're actually experiencing a bug. I think you don't realize that the total post count (what IG says exists) includes hidden/archived posts. The tool will return this same total but can't access them.
> 
> For your example, if you see 166 is the total, and then you count them, are there 166 or 160? Last night I downloaded an account with 141 rows of 3 images which is 423 photos. But the account and tool both said there should have been 460. Yet I could only access and download the 423.
> 
> I bet if you count the posts, you'll see that there are 160, and that means there are 6 archived/hidden posts. That or they have 6 reels that count in the total but are not on the posts page. Not sure about the reels part though.

Another example I tested just now. The profile "emily.feld" at the end of a full download returns 558/607. When I actually count the posts online, there are 168 rows of 3 posts which makes 558 total posts. The tool downloaded matches the posts that exist, though the total count is 49 posts higher. It seems profiles that have larger numbers of posts or have been around longer tend to have the discrepancy due to the archiving of posts or ones taken down by content mods.
