### ISSUE TITLE
401 prevents fetching from reaching actual posts to download

### ISSUE THREAD

**Issue by Nadineli** [instaloader/instaloader#2344]
**Describe the bug**
This is less of a bug and maybe more of a (newer?) limitation from IG.
I am trying to download an entire profile which has over 1300 posts (mostly long videos and some images). It reached a point where I am being blocked from IG while Instaloader is still fetching the posts, before the fetching reaches an old enough post which Instaloader hasn't downloaded yet. Waiting and different IPs aren't helping. 

**To Reproduce**
By using the command "$ instaloader target", I was able to download about 150 posts before I got the first 401 error. I then waited and repeated the command twice until Instaloader had downloaded about 700 posts in total. But whenever I run the command again now, Instaloader can only fetch about 150-300 posts (which it correctly detects as being present on the disk) before showing the 401 error again.

I also tried to use the script from https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period to set a time period of a day that lies right before the 700 posts which Instaloader had downloaded already. However, whenever I run the script, it gives me the same 401 error before starting to download anything. I wonder if its doing the same query in the background that the normal command does, and that is fetching the entire list of posts (which seems to be enough to get me blocked from IG even with waiting and using a different IP).

**Expected behavior**
Is it possible to somehow "pause" and "resume" the fetching process?
For example, when you run the basic command "$ instaloader target" and in case Instaloader gets the 401 error while fetching the posts (which are already present on disk), Instaloader "pauses" the fetching and you would be able to resume the process after waiting for a while (without Instaloader having to fetch all the previous newer posts again). 
Alternatively, maybe the fetching could be set to start at a specific post count? Therefore allowing you to skip fetching the first 700 posts for example. 
I'd be happy for any other suggestions/workarounds and thanks for this great tool.

**Error messages and tracebacks**
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query [retrying; skip with ^C]

**Instaloader version**
4.13

**Comment by tenseiken** [comment]
They do seem to have ramped up their scrape detection. Even updating a series of existing profiles is causing 400/401 errors after just a few minutes.

**Comment by berbunda** [comment]
is there any way to slow down the download speed and take a break between downloading each picture?
I downloaded source files and found this line (https://github.com/instaloader/instaloader/blob/2a3e5980ff540eb4dbf79db44fccec1fa55c9091/instaloader/instaloadercontext.py#L56) and changed from 1000, 20000 to 100, 500. But it is not help me to avoid instagram defence.

I don't know python and I don't know what's responsible for what.
But a function to limit the speed and delay between downloading each post would be very useful

**Comment by enricoaquilina** [comment]
I found if you download posts without logging in, it lets you for a while (haven't determined limits). Then once you start hitting 401, you can login with an account to continue downloading for another bit. (just my 2 cents observation...)

**Comment by mumixam** [comment]
@berbunda  that line you edited has nothing to do with download speed. that line inserts a random integer into a http header

**Comment by danielmatiello** [comment]
> @berbunda that line you edited has nothing to do with download speed. that line inserts a random integer into a http header
> 
> I made this change and are currently testing it. So far have downloaded over 150 posts grabbed in a single session but its super slow. maybe my delay times are way higher than they need to be (random time between 13 and 55 seconds between posts)
> 
> ```
> diff --git a/instaloader/instaloader.py b/instaloader/instaloader.py
> index 30ea42b..04b8da7 100644
> --- a/instaloader/instaloader.py
> +++ b/instaloader/instaloader.py
> @@ -7,6 +7,8 @@ import shutil
>  import string
>  import sys
>  import tempfile
> +import random
> +import time
>  from contextlib import contextmanager, suppress
>  from datetime import datetime, timezone
>  from functools import wraps
> @@ -1054,6 +1056,7 @@ class Instaloader:
>                                       end="", flush=True)
>                  else:
>                      self.context.log("[{:3d}] ".format(number), end="", flush=True)
> +                time.sleep(random.randint(13,55))
>                  if post_filter is not None:
>                      try:
>                          if not post_filter(post):
> ```

Thanks for share, but here, this bug continue even with this modification. =/

**Comment by ggogel** [comment]
It seems like they have massively restricted access without login. In the past, I was able to work around this by changing the User-Agent but since a couple of days, I've been unable to download anything, even though my IP changes every night.

**Comment by aandergr** [comment]
You can pause the downloading process by pressing `Control + C`, or you can set the option `--abort-on=401` to automatically pause when a 401 error occurs. Instaloader is designed to resume downloading from where it last stopped, making it easier to manage interruptions.

Regarding the reported problem, it's important to note that Instaloader has built-in logic to track requests to Instagram and respect their rate limits. The rate controller operates under the assumption that Instaloader is the only application making requests at any given time. This means that if other applications (like the Instagram browser or mobile app) are running simultaneously, or if you frequently restart Instaloader in a short timeframe, you may encounter an error.

**Comment by cassws** [comment]
> Regarding the reported problem, it's important to note that Instaloader has built-in logic to track requests to Instagram and respect their rate limits. The rate controller operates under the assumption that Instaloader is the only application making requests at any given time. This means that if other applications (like the Instagram browser or mobile app) are running simultaneously, or if you frequently restart Instaloader in a short timeframe, you may encounter an error.

Just wanted to emphasize closing open browser windows fixed the issue as I experienced it in January 2025. Thank you @aandergr !
