### ISSUE TITLE
WinError 10061

### ISSUE THREAD

**Issue by forjoke2013** [instaloader/instaloader#2346]
**Describe the bug**
The same command used to work but now gives an error

**To Reproduce**
D:\instaloader\instaloader xxxxx

**Expected behavior**
begin to download photos

**Error messages and tracebacks**
JSON Query to api/v1/users/web_profile_info/?username=xxxxx: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/web_profile_info/?username=jvdasberra (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002222DC3DEE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))) [retrying; skip with ^C]

**Instaloader version**
4.13

**Comment by aandergr** [comment]
Connection problem, not related to Instaloader.
