### ISSUE TITLE
help followed users

### ISSUE THREAD

**Issue by JavierHck** [instaloader/instaloader#2347]
How is the command written in Instaloader to download the profiles followed by a user (not oneself, another)?

**Comment by Showmaster3000** [comment]
Afaik this is only possible when using instaloader as python module.
An similar example is posted in the [manual](https://instaloader.github.io/codesnippets.html#likes-of-a-profile-ghost-followers).
You need `Profile.get_followees()` (see [here](https://instaloader.github.io/module/structures.html#profiles))
