### ISSUE TITLE
Upgrading Instaloader to 4.13

### ISSUE THREAD

**Issue by AdamJMilton** [instaloader/instaloader#2349]
Good afternoon.

BLUF - I am having issues upgrading instaloader from 4.9.5 to version 4.13. Or installing version 4.13 at all.

I recently started running to the 12 post download limit and after some research I found out that my version of instaloader was a little out of date. 4.9.5 to be exact. I tried to upgrade it with "**pip install --upgrade instaloader**" and that resulted in.

> Defaulting to user installation because normal site-packages is not writeable
> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> Requirement already satisfied: instaloader in /home/pi/.local/lib/python3.7/site-packages (4.9.5)
> Requirement already satisfied: requests>=2.4 in /usr/lib/python3/dist-packages (from instaloader) (2.21.0)

Which made me wonder at first about providing pip with additional indexes but decided to just download the tar file Instaloader, upload it to my raspberry pi and install it like that.

After I did that I tried to run the "**setup.py**". I had an old version of python, so I upgrsded from 3.7.3 to 3.9, set python 3.9 to my primary python version, rebooted and ran "**setup.py**" again. I was then told I "**Instaloader requires Python >= 3.8**".

So I am stumped. I am not sure what to do because when I run "**pip install --upgrade instaloader**" I can see it reaches out to https://pypi.org/ which has the newest version available on their website.

I have also tried "pip uninstall instaloader" to uninstall and "**pip install instaloader**" to reinstall it and version 4.9.5 was reinstalled. I am not sure what I am doing wrong.

This is my version of Raspbian:

> PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
> NAME="Raspbian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=raspbian
> ID_LIKE=debian
> HOME_URL="http://www.raspbian.org/"
> SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
> BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by mumixam** [comment]
how did you update python. It appears you have a userspace copy of python3.7 in /home/pi. depending on your $PATH you might be invoking the old 3.7 verison.
What happens when your type ```which python3```

**Comment by AdamJMilton** [comment]
I upgraded python following these **[instructions](https://stackoverflow.com/questions/64718274/how-to-update-python-in-raspberry-pi)**.

Suffice to say I used wget and reached out to the ftp server hosted by python.org and downloaded s tar file. Then I ran _sudo ./configure --enable-optimizations_ followed by _sudo make -j 4_ and _sudo make altinstall_.

When I type "**which python3**"  it get "_/usr/bin/python3_".

And when I type "**which pip**" the output is "_/home/pi/.local/bin//pip_".

**Comment by mumixam** [comment]
safe to say you have some python installation issues.

what does it show when you do the following.

```python -V```
```/usr/bin/python3 -V```
```/home/pi/.local/bin/python3 -V```

**Comment by AdamJMilton** [comment]
Thats what I thought of also. So i spend last night and this morning reinstalling and upgrading python, again.

**python -V** gives me '_Python 3.12.4_'. The version I upgraded to.

And **/home/pi/.local/bin/python3 -V** gives me '_-bash: /home/pi/.local/bin/python3: No such file or directory_'.

**/usr/bin/python3 -V** gives me '_Python 3.7.3_'. This confuses me because I went to **/usr/bin/** and ran the commands _sudo rm python_ and _sudo ln -s /usr/local/bin/python3.12 python_. Didn't that set up a link?
