### ISSUE TITLE
Load and close the session, with no content download ("solved")

### ISSUE THREAD

**Issue by PreylCnd** [instaloader/instaloader#2350]
**Describe the bug**
Load my user session, not download the pict and vid from the account and close the session .
I'm using the standalone version. And i never had this probleme before. I always used this line to download pict and vid
I've changed nothing 

**To Reproduce**
***instaloader --no-captions --no-video-thumbnails --no-profile-pic --no-metadata-json --no-compress-json --login=USER PROFILE***

**Expected behavior**
***Loaded session from C:\Users\USER \AppData\Local\Instaloader\session-USER .
Logged in as USER .
[1/1] Downloading profile PROFILE
Retrieving posts from profile PROFILE.
Saved session to C:\Users\USER \AppData\Local\Instaloader\session-USER .***

**Instaloader version**
V.4.13 on Windows 10

**Comment by ekalin** [comment]
I can't reproduce it, I was able to download posts normally.

This looks like the recently fixed bug. Are you 100% sure you're using 4.13?

**Comment by mumixam** [comment]
can't reproduce issue either. @PreylCnd try grabbing posts from account instagram to see if that works

**Comment by DucTienDo** [comment]
I've crawled about 800 profiles, and 1 or 2 profile had the same issue as yours (fixed it by using Python module instead of command line). 
Now I can't reproduce it (dont know why) but i can confirm that the issue did happen

**Comment by PreylCnd** [comment]
Sorry for the delay of the repond.
Thx for the help ! I have re install instaloader and python from scratch, and now it's working. So i don't know what was the issue.
(Also that was not the version of python or pip, I had updated them and it hadn't changed anything)
So i think the problem is solved
Thx again I didn't except so much help
