### ISSUE TITLE
Scraping a profile's posts without a session no longer works on version Version 4.13+

### ISSUE THREAD

**Issue by maledictionmeyerson** [instaloader/instaloader#2353]
**Describe the bug**
Previously you could get up to 12 posts from a profile without having a session logged in. Now it fails every time unless you revert before 4.13.

**To Reproduce**
Use an instaloader session that's not logged in and try to access the posts iterator from a profile instance, it will not work.

**Expected behavior**
I expect up to 12 posts to be returned (including pinned posts) but instead I always get the login redirects.

**Error messages and tracebacks**
KeyError: 'edge_media_to_parent_comment'

**Instaloader version**
4.13 + 

So I'm wondering if there's a way to have the best of both world's and use the old query when not logged in.

**Comment by aandergr** [comment]
Unclear and confusing bug report. Even version unprecise.
