### ISSUE TITLE
Downloading 100+ profiles at once

### ISSUE THREAD

**Issue by nihelmasell** [instaloader/instaloader#236]
**Describe the bug**
I have a 500mbps downstream connection. I am attempting to download almost 200 profiles (the ones I follow). The download process seems to be slow (only downloaded 12 profiles, 1.4g) in 12 hours. Can this app be used with parallel with many instances running at once? O do you suspect a ban from IG? (I am using a VPN, though).

**To Reproduce**
Use command line CAT plus instagram username list to download to be fed into the app. Make sure you have dozens or hundreds of profiles.

**Expected behavior**
Higher download speed. 10 or more profiles per hour.

**Error messages and tracebacks**
No error message.

**Instaloader version**
Latest. Pip3 install instaloader.

**Additional context**
High Internet download speed link. Dedicated computer.

**Comment by hgkmaxymus** [comment]
The issue might be the VPN. I often add new profiles and it downloads about 2GB in 30min-1h.

Note: I use the "--no-captions" and "--no-metadata-json" parameters since I don't care about those. Who knows, maybe it takes longer because you are downloading all the info from each photo? (I am not a dev, but who knows, I might be of some help.)

**Comment by jlntrt** [comment]
Like @hgkmaxymus said, might be the VPN connection. Currently I'm scraping 566 profiles with captions and meta data every 30 minutes, and that works fine.

**Comment by nihelmasell** [comment]
> The issue might be the VPN. I often add new profiles and it downloads about 2GB in 30min-1h.
> 
> Note: I use the "--no-captions" and "--no-metadata-json" parameters since I don't care about those. Who knows, maybe it takes longer because you are downloading all the info from each photo? (I am not a dev, but who knows, I might be of some help.)

> Like @hgkmaxymus said, might be the VPN connection. Currently I'm scraping 566 profiles with captions and meta data every 30 minutes, and that works fine.

I tried with and WITHOUT the VPN. I even tried other software, like instalooter and instagram-scraper. What I notice at my end is that IG bans my connection every 30/40 minutes. Inslaloader knows when to retry and waits, but never downloads profiles  completely (there are always missing pictures). Tried different countries also. Maybe is a ban on my username. I have only been able to download 15gb in three days, maybe 60 profiles, with the 500mbps barely being used by other apps. I don't really know what happens. Are you really able to download, say, 50 gb per day? I got a similar problem with RipMe app, that's why I switched to this "specialized" software. I used to fully download 10/20, then I got blocked at the third. I cant really tell what is happening.

**Comment by nihelmasell** [comment]
> What I have over here:
> 
> * A "download-all" no-login shell-script which will download public profiles I have never downloaded;
> * A "download-new" no-login shell-script which will download public profiles I have fully downloaded;
> * A "download-all" with login shell-script which will download private profiles I have never downloaded;
> * A "download-new" with login shell-script which will download private profiles I have fully downloaded;
> * And finally, a script which calls all of the above if needed/wanted.
> 
> So, when you have to force a login to the instagram API to download new pictures and all, it will register your login on their servers, so it will "consume your cap" or whatever. So I only use my login to download the private profiles. And, when I do, if it has to download a good amount of posts, after some time it will halt on a post numbered 12 or 62 (0+12 or 50+12, and the hundreds alike - 112, 162, 212, etc) and it can take 10 mins or 1h to be able to continue.
> 
> My public "download-all" is the one who takes longer, it takes 30min to START (it has almost 1000 profiles, sorry!!) because it is checking the profile list and sorting it. The others start in about 1min or 2 right after the call and end in less than 5min (depending of the amount of new downloads/profiles, of course).
> 
> My recommendation is, then, to try downloading the public profiles without using your login.
> Or... Try using the JDownloader (just remember, it is JAVA based), it can download instagram picures/videos, but don't expect much.

Hi, first of all, thanks for your long and complete answer. It’s not a bad idea, but I have scripts for downloading Reddit, Twitter, Flickr, Google images, etc, so I want to keep it as simple as I can, as errors are easier to detect. The second problem is that I have to go one by one of my followees to see which of them are private and which are not. I won’t notice from my instagram feed, so I’d have to log off and go to each users page to tell. 

But I didn’t know the cap was related to being logged in, and that’s precious information. My further attempts will be based into that assumption. Jdownloader is a mess for mass downloading. It can hang almost any computer. More than 30k files will collapse the app (and probably the system itself). Therefore, your last affirmation is totally true. I will try to write an intermediate solution from what you have (multiple scripts) and what I have (only one, at least per social network). Thank you very much!

**Comment by MRThundrcleese** [comment]
> So, when you have to force a login to the instagram API to download new pictures and all, it will register your login on their servers, so it will "consume your cap" or whatever.

Thanks bro, you're a life saver.

**Comment by nihelmasell** [comment]
> Hello,
> You can do a no-login first run. The instaloader will show the private profiles :)
> 
> The log/output will have:
> `<private profile>: --login=USERNAME required.`
> 
> So you can get the private profiles that way. That's what I do when I add a bunch of mixed profiles.

Thank you very much! Have you tried downloading hashtags? It is my intention to download hashtags with 30k+ posts. Have you tried that too? Thank you again for your precious help!

**Comment by github-userx** [comment]
@hgkmaxymus Do You only use people’s usernames or also keep track via UserID converting to userName? E.g. if people changed their username.

**Comment by hgkmaxymus** [comment]
> @hgkmaxymus Do You only use people’s usernames or also keep track via UserID converting to userName? E.g. if people changed their username.

My calls use the username, but I also have their IDs stored in the folders (there is a `id` file there).

What I use here is a bash script, which logs when the usernames have been changed.
```
if [ `grep -c "changed its name" $log` -ne 0 ]; then
	echo " " | tee -a $log
	echo " Profile(s) name(s) have been altered:" | tee -a $log
	echo "$(grep -i 'changed its name' $log)" | tee -a $log
	date "+Date: %d/%m/%y%tHour: %H:%M:%S" >> $alteredprofiles
	grep -i 'changed its name' $log >> $alteredprofiles
	unix2dos -q $alteredprofiles
fi
```

So I can always double check it just by looking the logs (the `$alteredprofile` log), like:
```
Date: 12/07/19	Hour: 15:48:28
Profile <old_profile_name> has changed its name to <new_profile_name>.
```

Also, sorry for my coding, I am not a developer. But I hope it helps you in some way :)

**Comment by github-userx** [comment]
@hgkmaxymus you’re definitely a coder :) I could never do these things with bash scripts
