### ISSUE TITLE
The example of loading top posts https://instaloader.github.io/codesnippets.html#top-x-posts-of-user  doesnt work in current version, while CLI (for loading all) works in instaloader --version 4.13.1

### ISSUE THREAD

**Issue by fozak** [instaloader/instaloader#2362]
**Describe the bug**
The example of loading top posts https://instaloader.github.io/codesnippets.html#top-x-posts-of-user doesnt work in current version, while CLI works in instaloader --version 4.13.1

**To Reproduce**
Jupyter Lab: 
from itertools import islice
from math import ceil

from instaloader import Instaloader, Profile

PROFILE = "daviosthecolony"        # profile to download from
X_percentage = 1    # percentage of posts that should be downloaded

L = Instaloader()

profile = Profile.from_username(L.context, PROFILE)
posts_sorted_by_likes = sorted(profile.get_posts(),
                               key=lambda p: p.likes + p.comments,
                               reverse=True)

for post in islice(posts_sorted_by_likes, ceil(profile.mediacount * X_percentage / 100)):
    L.download_post(post, PROFILE)

**Expected behavior**
A clear and concise description of what you expected to happen (even if it seems obvious).

**Error messages and tracebacks**
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22C_CAy7QRw1I%22%7D [retrying; skip with ^C]
JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22C_CAy7QRw1I%22%7D [retrying; skip with ^C]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File [C:\Python312\Lib\site-packages\instaloader\structures.py:355](file:///C:/Python312/Lib/site-packages/instaloader/structures.py#line=354), in Post._field(self, *keys)
    354 for key in keys:
--> 355     d = d[key]
    356 return d

KeyError: 'edge_media_to_parent_comment'

During handling of the above exception, another exception occurred:

ConnectionException                       Traceback (most recent call last)
File [C:\Python312\Lib\site-packages\instaloader\instaloadercontext.py:456](file:///C:/Python312/Lib/site-packages/instaloader/instaloadercontext.py#line=455), in InstaloaderContext.get_json(self, path, params, host, session, _attempt, response_headers, use_post)
    455 if resp.status_code != 200:
--> 456     raise ConnectionException(self._response_error(resp))
    457 else:

ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22C_CAy7QRw1I%22%7D

During handling of the above exception, another exception occurred:

ConnectionException                       Traceback (most recent call last)
File C:\Python312\Lib\site-packages\instaloader\instaloadercontext.py:456, in InstaloaderContext.get_json(self, path, params, host, session, _attempt, response_headers, use_post)
    455 if resp.status_code != 200:
--> 456     raise ConnectionException(self._response_error(resp))
    457 else:

ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22C_CAy7QRw1I%22%7D

During handling of the above exception, another exception occurred:

ConnectionException                       Traceback (most recent call last)
File C:\Python312\Lib\site-packages\instaloader\instaloadercontext.py:456, in InstaloaderContext.get_json(self, path, params, host, session, _attempt, response_headers, use_post)
    455 if resp.status_code != 200:
--> 456     raise ConnectionException(self._response_error(resp))
    457 else:

ConnectionException: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22C_CAy7QRw1I%22%7D

The above exception was the direct cause of the following exception:

ConnectionException                       Traceback (most recent call last)
Cell In[14], line 12
      9 L = Instaloader()
     11 profile = Profile.from_username(L.context, PROFILE)
---> 12 posts_sorted_by_likes = sorted(profile.get_posts(),
     13                                key=lambda p: p.likes + p.comments,
     14                                reverse=True)
     16 for post in islice(posts_sorted_by_likes, ceil(profile.mediacount * X_percentage / 100)):
     17     L.download_post(post, PROFILE)

Cell In[14], line 13, in <lambda>(p)
      9 L = Instaloader()
     11 profile = Profile.from_username(L.context, PROFILE)
     12 posts_sorted_by_likes = sorted(profile.get_posts(),
---> 13                                key=lambda p: p.likes + p.comments,
     14                                reverse=True)
     16 for post in islice(posts_sorted_by_likes, ceil(profile.mediacount * X_percentage / 100)):
     17     L.download_post(post, PROFILE)

File C:\Python312\Lib\site-packages\instaloader\structures.py:627, in Post.comments(self)
    625     return comments['count']
    626 try:
--> 627     return self._field('edge_media_to_parent_comment', 'count')
    628 except KeyError:
    629     return self._field('edge_media_to_comment', 'count')

File [C:\Python312\Lib\site-packages\instaloader\structures.py:358](file:///C:/Python312/Lib/site-packages/instaloader/structures.py#line=357), in Post._field(self, *keys)
    356     return d
    357 except KeyError:
--> 358     d = self._full_metadata
    359     for key in keys:
    360         d = d[key]

File [C:\Python312\Lib\site-packages\instaloader\structures.py:335](file:///C:/Python312/Lib/site-packages/instaloader/structures.py#line=334), in Post._full_metadata(self)
    333 @property
    334 def _full_metadata(self) -> Dict[str, Any]:
--> 335     self._obtain_metadata()
    336     assert self._full_metadata_dict is not None
    337     return self._full_metadata_dict

File [C:\Python312\Lib\site-packages\instaloader\structures.py:322](file:///C:/Python312/Lib/site-packages/instaloader/structures.py#line=321), in Post._obtain_metadata(self)
    320 def _obtain_metadata(self):
    321     if not self._full_metadata_dict:
--> 322         pic_json = self._context.graphql_query(
    323             '2b0673e0dc4580674a88d426fe00ea90',
    324             {'shortcode': self.shortcode}
    325         )
    326         self._full_metadata_dict = pic_json['data']['shortcode_media']
    327         if self._full_metadata_dict is None:

File [C:\Python312\Lib\site-packages\instaloader\instaloadercontext.py:511](file:///C:/Python312/Lib/site-packages/instaloader/instaloadercontext.py#line=510), in InstaloaderContext.graphql_query(self, query_hash, variables, referer)
    507         tmpsession.headers['referer'] = urllib.parse.quote(referer)
    509     variables_json = json.dumps(variables, separators=(',', ':'))
--> 511     resp_json = self.get_json('graphql/query',
    512                               params={'query_hash': query_hash,
    513                                       'variables': variables_json},
    514                               session=tmpsession)
    515 if 'status' not in resp_json:
    516     self.error("GraphQL response did not contain a \"status\" field.")

File [C:\Python312\Lib\site-packages\instaloader\instaloadercontext.py:480](file:///C:/Python312/Lib/site-packages/instaloader/instaloadercontext.py#line=479), in InstaloaderContext.get_json(self, path, params, host, session, _attempt, response_headers, use_post)
    478         if is_other_query:
    479             self._rate_controller.handle_429('other')
--> 480     return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
    481                          response_headers=response_headers)
    482 except KeyboardInterrupt:
    483     self.error("[skipped by user]", repeat_at_end=False)

File [C:\Python312\Lib\site-packages\instaloader\instaloadercontext.py:480](file:///C:/Python312/Lib/site-packages/instaloader/instaloadercontext.py#line=479), in InstaloaderContext.get_json(self, path, params, host, session, _attempt, response_headers, use_post)
    478         if is_other_query:
    479             self._rate_controller.handle_429('other')
--> 480     return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1,
    481                          response_headers=response_headers)
    482 except KeyboardInterrupt:
    483     self.error("[skipped by user]", repeat_at_end=False)

File [C:\Python312\Lib\site-packages\instaloader\instaloadercontext.py:468](file:///C:/Python312/Lib/site-packages/instaloader/instaloadercontext.py#line=467), in InstaloaderContext.get_json(self, path, params, host, session, _attempt, response_headers, use_post)
    466         raise QueryReturnedNotFoundException(error_string) from err
    467     else:
--> 468         raise ConnectionException(error_string) from err
    469 self.error(error_string + " [retrying; skip with ^C]", repeat_at_end=False)
    470 try:

ConnectionException: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22C_CAy7QRw1I%22%7D

**Instaloader version**
`instaloader --version` output.

**Additional context**

**Comment by RazyRo** [comment]
Traceback (most recent call last):
  File "c:\Users\ROHIT\Downloads\Tut\vid25.py", line 25, in <module>
    profile = Profile.from_username(L.context, PROFILE)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ROHIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\structures.py", line 737, in from_username   
    profile._obtain_metadata()  # to raise ProfileNotExistsException now in case username is invalid
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ROHIT\AppData\Local\Programs\Python\Python311\Lib\site-packages\instaloader\structures.py", line 809, in _obtain_metadata
    raise ProfileNotExistsException('Profile {} does not exist.'.format(self.username))
instaloader.exceptions.ProfileNotExistsException: Profile thesenuka does not exist.
