### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by repo-cyber** [instaloader/instaloader#2363]
### Feedback Help: Instaloader Customization

**Hello,**

I apologize for this off-topic question, but I have nowhere else to ask. As a NOT Python coding expert, I'm currently customizing Instaloader and have successfully integrated a `tqdm` progress bar to monitor the download process. However, I've encountered an issue: after each progress update, the file path is displayed, disrupting the output.

#### Current Output:

```
Downloading posts:  50%|███████            | 50/100 [00:30<00:30,  2.00post/s]
Downloads/example/@example_5890-08-22_19-34-55_GraphImage.jpg
```

#### Desired Output:

```
Downloading posts:  50%|███████            | 50/100 [00:30<00:30,  2.00post/s]
Downloading posts:  51%|████████           | 51/100 [00:30<00:30,  2.00post/s]
Downloading posts:  52%|█████████          | 52/100 [00:30<00:30,  2.00post/s]
```

### Help Needed:
Could you guide me on how to modify the script so that only the progress bar is displayed, omitting the directory and file path? Any suggestions would be greatly appreciated!

---

**CODE LINE:**

<details>
<summary>Click to expand code</summary>

```Python
# Create a progress bar
for post in tqdm(posts, desc="Downloading posts", unit="post"):
    self.download_post(post, target=profile.username)

self.save_profile_details(profile)
```

---

**Comment by DucTienDo** [comment]
Have you tried adding quiet=True to the Instaloader class?
