### ISSUE TITLE
cannot load IG pictures, need browser-cookies3 library

### ISSUE THREAD

**Issue by Nilsonfsilva** [instaloader/instaloader#2365]
Hi!
I'm an installaloader maintainer on Debian/Ubuntu.

Recently a bug was opened for installaloader:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1080525

Grateful!

Nilson Silva

**Comment by Showmaster3000** [comment]
It would be better to post the full report here, not just a link to another page.
The bug report mentions v4.12.1. We are currently at v4.13.1. v4.13 fixed the problem that no posts could be downloaded. So check the latest version if it is fixed. If not try again with a full report according to the issue template.
