### ISSUE TITLE
issues on metadata

### ISSUE THREAD

**Issue by GeminiKiller** [instaloader/instaloader#2366]
I managed to download and login but not comments

Errors or warnings occurred:
--comments: Fetching Post metadata failed.
--no-pictures: Fetching Post metadata failed.
--no-compress-json: Fetching Post metadata failed.

using the latest version

**Comment by Showmaster3000** [comment]
incomplete bug report
- command line missing
- error message(s) including traceback if available
- explicit instaloader version - latest is no version number - use `instaloader --version`

**Comment by GeminiKiller** [comment]
instaloader -post -- -C_VIniGzTER --no-compress-json 
-C_VIniGzTER/2024-08-31_10-02-39_UTC_1.jpg -C_VIniGzTER/2024-08-31_10-02-39_UTC_2.jpg -C_VIniGzTER/2024-08-31_10-02-39_UTC_3.jpg -C_VIniGzTER/2024-08-31_10-02-39_UTC_4.jpg -C_VIniGzTER/2024-08-31_10-02-39_UTC_5.jpg [look 👀   [240831 wang yibo we…] json 
--no-compress-json: Fetching Post metadata failed.

**Comment by GeminiKiller** [comment]
ok i know why it should be
instaloader --no-compress-json -- -C_VIniGzTER
