### ISSUE TITLE
What loading speed is expected to display a batch of 12 images?

### ISSUE THREAD

**Issue by andupotorac** [instaloader/instaloader#2373]
I've seen many people say downloading is either fast, or slow. But there is no reference point to what we should expect as speed. On my end it looks like it may take even a few minutes. Is that normal?

Are there some guidelines we should follow to be sure there is no ban from Facebook?

**Comment by andupotorac** [comment]
Is it normal to be blocked by Instagram with 401 unauthorized messages after running this script only 2-3 times, for only 12 images?

**Comment by MonkeyKingViper** [comment]
The longer it takes, the safer it is. You do not want this to happen faster than human speed for too long or you look like automation. As far as guidelines, don't be greedy and do things too often. Remember, you're trying to trick an AI into thinking you're a human somehow doing all this stuff. If you're not logged in, or not logged in AND using a VPN, you're gonna get blocked pretty fast

**Comment by andupotorac** [comment]
> The longer it takes, the safer it is. You do not want this to happen faster than human speed for too long or you look like automation. As far as guidelines, don't be greedy and do things too often. Remember, you're trying to trick an AI into thinking you're a human somehow doing all this stuff. If you're not logged in, or not logged in AND using a VPN, you're gonna get blocked pretty fast.
> 
> Also, for god's sake, do not use your real account for this. Make a burner (on PC), then make about 5 more (change your IP address each time so your burners aren't linked). Add posts to the burners to make them look like real accounts. Do things normal human beings would on the accounts. Refresh your IP when you log into a new account. NEVER use any on a mobile device. Take time between runs until the AI thinks you're just scrolling pages really fast. And don't try to do anything on an account that's not a couple weeks old. DON'T LOOK LIKE A BOT
> 
> These are some tips. You'll get banned eventually cause you'll fuck up somewhere without thinking. Happens to everyone. Then you swap to your next account and go forward.

Thanks :)
