### ISSUE TITLE
Private but not followed

### ISSUE THREAD

**Issue by lovelykamjade** [instaloader/instaloader#2374]
Hello everyone, 

is it possible to download photos from a profile tagged as Private but not followed? If, how do I do that?

Thank you.

**Comment by MonkeyKingViper** [comment]
Yes. Pretty easy fix. You just need to click the "Follow" button, and after they've accepted you, you'll be able to download them.

Joking aside, no, you can't download private profiles unless you follow them. Hiding them from public view is exactly why that exists, so you'll have to hope they accept you. This tool can't violate the functionality of private profiles

**Comment by lambemia** [comment]
> Yes. Pretty easy fix. You just need to click the "Follow" button, and after they've accepted you, you'll be able to download them.
> 
> Joking aside, no, you can't download private profiles unless you follow them. Hiding them from public view is exactly why that exists, so you'll have to hope they accept you. This tool can't violate the functionality of private profiles

So in short terms, it is useless. Any animal with two hands can downloader instagram profiles that you have access. No need to a python script.
