### ISSUE TITLE
Update profiles

### ISSUE THREAD

**Issue by hdma** [instaloader/instaloader#238]
Hi, and sorry for my English!

There was a question about the updates profiles. I downloaded a profile in which 3000+ publications, from which 700 publications downloaded. Now, when I want to download this profile with the option `--fast-update` - the download stops on the files already downloaded. And when I want to download this profile without the `--fast-update` option - the download starts, but the already downloaded files go along for a long time, along with pauses and "Too Many Requests" messages. Is there a solution for this situation?

Full command I am using:

`"%PYTHON%" "%FOLDER%\instaloader.py" --sessionfile="%FOLDER%\.session" --login=LOGIN --password=PASS --comments --geotags --stories --highlights --no-metadata-json --no-video-thumbnails --max-connection-attempts=0 --post-metadata-txt="{caption}" --dirname-pattern={profile} --filename-pattern={date_utc}_UTC.{shortcode} PROFILE`

**Comment by aandergr** [comment]
There has been a short discussion related to your concern in #216, however we are not aware of any solution for this problem.
