### ISSUE TITLE
comment answers don't get all data

### ISSUE THREAD

**Issue by xyjw** [instaloader/instaloader#2381]
![image](https://github.com/user-attachments/assets/c838af45-faef-4107-8734-2967ceb1992b)

When the number of comment answers exceeds 10, only 9 pieces of data can be obtained，for example， shortcode is C69wIdpKMQ5

**Comment by Showmaster3000** [comment]
Incomplete bug report. Tending to close as not planned.
- missing steps to reproduce your issue, f.e. command line or script snippet
- no version mentioned
- what about the screenshot?
