### ISSUE TITLE
add support for --dms

### ISSUE THREAD

**Issue by realies** [instaloader/instaloader#2382]

**Comment by realies** [comment]
@Showmaster3000 why not planned?

**Comment by Showmaster3000** [comment]
@realies  As the label says, you missed using the issue template to describe your suggestion in detail. What can we get out of the issue title? So this issue has no content. so closing.

**Comment by realies** [comment]
@Showmaster3000, jeez, can't you derive what it means from the context of this repository?

Anyway, now it has a 'plan'. You can safely reopen the issue.
