### ISSUE TITLE
Stories not getting downloaded

### ISSUE THREAD

**Issue by luciano-fiandesio** [instaloader/instaloader#2383]
**Describe the bug**

Stories are not downloaded

**To Reproduce**
(e.g. Instaloader command line)
`instaloader --login=xxxxxxxx --stories xxxxxxxx`

**Expected behavior**
I assume that the _archived_ stories for the user specified in the command line flags should be downloaded.

**Error messages and tracebacks**
No errors, but stories are not downloaded, only profile posts (images).

This is the output:

```
instaloader --login=xxxxxxxx --stories xxxxxxxx
Logged in as xxxxxxxx.
[1/1] Downloading profile xxxxxxxx
xxxxxxxx/2017-10-25_19-55-59_UTC_profile_pic.jpg already exists
Retrieving posts from profile xxxxxxxx.
[  1/542] xxxxxxxx/2024-09-12_05-45-35_UTC.jpg [#a #b 2024] json
...
[542/542] xxxxxxxx/2015-11-07_19-28-32_UTC.jpg json
Downloading stories
Saved session to /Users/xyz/.config/instaloader/session-xxxxxxxx.
```

**Instaloader version**
4.13.1

**Comment by Showmaster3000** [comment]
`--stories` is for current visible elements within 24 hours.
`--highlights` is for visible archived stories
