### ISSUE TITLE
Cant access video_duration

### ISSUE THREAD

**Issue by kevit-Jay-Dhakan** [instaloader/instaloader#2386]
**Describe the bug**
Raises 501, and 402 when accessing the **video_duration** field. Because Instagram removed this field from their APIs.

**To Reproduce**
just try to access **video_duration** when the post **is_video**.

**Expected behavior**
402, 501 status codes.

**Instaloader version**
latest version 4.13

**Additional context**
This problem happened in the past also, I don't remember the exact date but it happened.

**Comment by aandergr** [comment]
Thank you for your report. We have not been able to reproduce the issue you're experiencing, and accessing the **video_duration** field works fine on our end. Could you please provide more detailed steps to reproduce the problem? It may be important to understand how the post instance is created, as the information in the "To Reproduce" section isn’t specific enough to diagnose the issue effectively.
