### ISSUE TITLE
Is there a way to login?

### ISSUE THREAD

**Issue by aborruso** [instaloader/instaloader#2388]
Hi,
I have tested `L.interactive_login("username")`, but it does not work (#1217 ).

Is there another documented way to login? I have read about `--load-cookies`, but I don't understand how to use it.
Is there same sample code or same sample cli procedure?

Thank you

**Comment by MonkeyKingViper** [comment]
**--login** will prompt you to log in with user and password, and you can use an arg file to store your user and pass with **--login=XXXX** and **--password=YYYY** and call it in the CLI.

The cookie method doesn't seem to work in Brave for me, and I always use the CLI

**Comment by aborruso** [comment]
> **--login** will prompt you to log in with user and password, and you can use an arg file to store your user and pass with **--login=XXXX** and **--password=YYYY** and call it in the CLI.

I know it, but the `--login` does not work. I receive the verification code and I receive always `2FA error` (as you can see in #1217) 😢

```
Session file does not exist yet - Logging in.
Enter Instagram password for aborruso:
Enter 2FA verification code: 207661
2FA error: This code is no longer valid. Please request a new one.
Enter 2FA verification code:
```

**Comment by aborruso** [comment]
Thank you @Showmaster3000 I have a debian machine without GUI and without browsers :(

I will study your links, bt I think I am not able to overcome the obstacle. I had hoped that the login via cli would work as documented.

In any case, this is a really nice project!
