### ISSUE TITLE
 Views count on video

### ISSUE THREAD

**Issue by heyt0ny** [instaloader/instaloader#239]
Hello!

Is there any way to get views count on video?

Thank you.

**Comment by aandergr** [comment]
It is not yet accessible through Instaloader's Post structure directly, but it is saved in the JSON files and you can access it e.g. with

```
$ jq .node.video_view_count 2019-01-23_04-05-33_UTC.json
```

**Comment by heyt0ny** [comment]
Excuse me for my ignorance, I never used command line for that and I can't find the answer in documentation :sweat:, but  what is the command to download the `json` for the specific post ?

**Comment by maddingamer** [comment]
The json is downloaded automaticly for each post, unless you use the command `--no-metadata-json` 

More on that here: https://instaloader.github.io/codesnippets.html#metadata-json-files
and here: https://instaloader.github.io/cli-options.html#cmdoption-no-metadata-json
