### ISSUE TITLE
What's Our Guess Regarding The Recent GraphQL Changes?

### ISSUE THREAD

**Issue by brunohaid** [instaloader/instaloader#2400]
Given the recent bug reports / questions it seems like Instagram moved more functionality like get_post or video_duration behind a login or disabled them altogether. A question for people with more experience with Meta's policies:

Are those more likely permanent changes or is there a chance that it's a temporary test?

Our issue is that we can't get video_duration anymore, as Instaloader fires a secondary request after getting the timeline to get those post details, and this returns a 401 / "Wait a couple of minutes" even with a fresh IP etc. Would be great to know if we should just remove indexing the video length, or if there's a chance of finding a workaround / policy reversal.

**Comment by maliayas** [comment]
This is working for single post: https://github.com/Aristarhys/instaloader/commit/fda388d2d59151454c47e4f33792e8b56354b09e

**Comment by brunohaid** [comment]
Sweet, much appreciated @maliayas!
