### ISSUE TITLE
No .txt file generated when requesting tagged_users

### ISSUE THREAD

**Issue by elia-orsini** [instaloader/instaloader#2401]
**Describe the bug**
Instaloader doesn't generate any `.txt` file when the requested data includes `tagged_users` i.e. when using the following option `--post-metadata-txt="{caption}-{tagged_users}"`

**To Reproduce**
run `instaloader instagram  --post-metadata-txt="{caption}-{tagged_users}"`

**Expected behavior**
A `.txt` file is generated for every post with the caption and the array of tagged users for that post.

**Error messages and tracebacks**
none.

**Instaloader version**
4.13.1

**Comment by aandergr** [comment]
Fixed in [version 4.13.2](https://github.com/instaloader/instaloader/releases/tag/v4.13.2).
