### ISSUE TITLE
Pinned stories are not downloaded

### ISSUE THREAD

**Issue by Norde** [instaloader/instaloader#2403]
Hello,

Using Instaloader 4.13.1, the pinned stories are ignored during the download of a private profile (despite being logged in with access to this profile).

Is this a know limitation of instaloader ?

**Comment by otakukz17** [comment]
I can't load any stories at all. It gives an error: stories = self.context.graphql_query("303a4ae99711322310f25250d988f3b7", KeyError: 'data'
