### ISSUE TITLE
cookiefile Schema?

### ISSUE THREAD

**Issue by TheSinfulKing** [instaloader/instaloader#2406]
Hi, thanks for all the hard work on this tool.

I use an anti-detect browser with multiple profile management. One for each IG account. I can export the cookies from them to JSON using Cookie-Editor. However, I do not know the format or how --cookiefile is to be used.

I cannot just use the ones that take cookies from browser, because my browser is managed by the anti-detect program. But I should have the information for the cookie in JSON form.

Thanks!

**Comment by TheSinfulKing** [comment]
Right now I sometimes get a challenge_required when I first try to use any particular account. I then stop the program, open my anti-detect browser with the profile assigned to that account and manually clear the challenge.

However, I assume it would be better to take the cookies from that session in the anti-detect browser than having instaloader do its own thing?

**Comment by Showmaster3000** [comment]
Did you read the [manual](https://instaloader.github.io/cli-options.html#cmdoption-load-cookies) describing the parameters?
I don't know what anti-detect browser is. If you can't find it out, just use a supported browser to login to Instagram.
More options mentioned [here](https://github.com/instaloader/instaloader/issues/2388#issuecomment-2396884637).

**Comment by TheSinfulKing** [comment]
Yes, I saw that but I do not sign into my accounts with my normal browser and never will. Just think of the anti-detect browser as another browser. Like I use FireFox, but I installed Chrome only for this purpose. 

I have a file with cookies from Chrome in this instance, but I'm not sure what it is supposed to look like. Is there anywhere we can see an example of a valid Instagram cookie?

**Comment by TheSinfulKing** [comment]
Ah nvm, I just used the script and it worked well. I suppose my question is now can I run Firefox in a sandbox / some environment where my personal and alt accounts never mix?

**Comment by TheSinfulKing** [comment]
Well I've answered my own question. I can make profiles for Firefox in my Sandbox program. Each alt account has a profile in the Sandbox. That profile contains the specific cookies for that session. This way there is no intermingling of my normal use accounts and alt ones.

Thanks!
