### ISSUE TITLE
Biography download parameter

### ISSUE THREAD

**Issue by hgkmaxymus** [instaloader/instaloader#241]
**Feature**
Save the profile biography in a .txt file, named somewhat like the profile picture. You probably can't know the date/time, but maybe create a requested date filename with the bio and somehow check the contents every time you run with that parameter?

**Describe alternatives you've considered**
Currently, the software can download everything BUT the bios by themselves. I read the documentation and noticed you have the methods, just not implemented as a parameter for normal users.

Would be great if it don't save a .json file.

Thanks and keep the awesome work! :)

**Comment by aandergr** [comment]
Why? / For what?

The biography is included in the JSON file that is saved along with each profile. There are many ways to further process these files and extract the biography, e.g.

- With [jq](https://stedolan.github.io/jq/):
   ```xzcat PROFILE/PROFILE_ID.json.xz | jq -r .node.biography```

- With Instaloader:
   ```python
   from instaloader import Instaloader, load_structure_from_file
   print(load_structure_from_file(Instaloader().context, "PROFILE/PROFILE_ID.json.xz").biography)
   ```

> Would be great if it don't save a .json file.

What is the problem with JSON files?

**Comment by hgkmaxymus** [comment]
Hello.

Weird. A long time ago I tried the --no-captions parameter and it required the --no-metadata-json, if I am not mistaken. Now I tried and it was all ok, it only downloaded the profile JSON. That is nice. :)

I would prefer a text file just for better viewing. I understand the JSON has all the info and is great, I just want to know if it is possible to add a parameter to be able to download(parse?) it directly. If not, that's ok! The software is great and already helped me a lot.

Thanks for your time :)

**Comment by hgkmaxymus** [comment]
Er, I just noticed it creates a JSON for each post. That's what I had issues with. I don't want a JSON for each single post... And I noticed the general profile JSON file is updated(replaced) every time I run instaloader, so If I wanted to save an old profile bio/info, would I have to make a backup?

Thanks.
