### ISSUE TITLE
Stuck in a log-in loop. (Cannot download anything, Keeps asking me to log in when I'm already logged in.)

### ISSUE THREAD

**Issue by SilverlinedEagletip** [instaloader/instaloader#2417]
**Describe the bug**
I am stuck in a login loop that never registers me as logged in. I've logged in, I've gotten cookies from my browser. It just won't let me use it at all.

**To Reproduce**
Open Instaloader
 .\instaloader [PROFILENAME]

**Expected behavior**
Instaloader taking a second to parse the page, and then begin saving posts until complete.

**Error messages and tracebacks**
HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=[PROFILENAME] to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
[PROFILENAME] Redirected to login page. Use --login or --load-cookies.

and when I log in:
PS E:\instaloader-v4.10.3-windows-standalone> .\instaloader --login [MYUSER]
Loaded session from C:\Users\MYNAME\AppData\Local\Instaloader\session-[MY USER].
Logged in as [MYUSER].
Saved session to C:\Users\MYNAME\AppData\Local\Instaloader\session-[MY USER].
No targets were specified, thus nothing has been downloaded.

And then when I try to download anything, the top error happens again. 

**Instaloader version**
PS E:\instaloader-v4.10.3-windows-standalone>

**Additional context**
I've logged in, I've re-entered my password, I've downloaded the newest version of Instaloader. I've deleted my session and re-logged in with password. What the fuck is happening.

**Comment by SilverlinedEagletip** [comment]
<html><body>

message | "useragent mismatch"
-- | --
status | "fail"


</body>
</html>

This is whats in the links it sends me to upon attempt to login.

**Comment by SilverlinedEagletip** [comment]
to import cookies from browser: `python3 /615_import_firefox_session.py  -c /mnt/tmp/firefox/default_profile/cookies.sqlite`

to download
`instaloader --login=USER    --user-agent "Mozilla/5.0 (X11; Linux x86_64; ......................." --abort-on=302,400,401,429,403  --stories  --tagged --highlights PROFILE/`

Better to have also open instagram, and be a "real" profile (activity, likes, comments etc). 

You may use `trickle` to limit download rate.

_Originally posted by @estatistics in https://github.com/instaloader/instaloader/issues/2218#issuecomment-2006287990_
            
            
            I did the second above (running the commands in instaloader) and I can download images but still won't register me as being logged in. I don't know how to do the first thing in this solution (I have no coding experience whatsoever) so I am not sure if it would help me or not.

**Comment by SilverlinedEagletip** [comment]
> use **instaloader --login [MYUSER] [PROFILENAME]** put login and profile in **one** command

IT WORKED! THANK YOU! Do I need to do this for every pull from the site? Just for future reference c:

**Comment by SilverlinedEagletip** [comment]
> > > use **instaloader --login [MYUSER] [PROFILENAME]** put login and profile in **one** command使用 instaloader --login [MYUSER] [PROFILENAME] 将登录和配置文件放在一条命令中
> > 
> > 
> > IT WORKED! THANK YOU! Do I need to do this for every pull from the site? Just for future reference c:它成功了！谢谢！我是否需要每次从网站调用都这样做？仅供今后参考：
> 
> yes, and I recommend you to use --load-cookies command

In addition to the login? And is this a new issue and this is a workaround, or is this just how I need to do it from now on?

**Comment by Showmaster3000** [comment]
And most important: use an actual version of instaloader. v4.10 is ancient!
