### ISSUE TITLE
Instaloader STANDALONE commands to EXE don't respond. Double Click?

### ISSUE THREAD

**Issue by ejbytes** [instaloader/instaloader#2423]
How does the instaloader.exe stand-alone application work? I tried double-click to run, and Windows 7 responds, "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item." Nor does it work, Right-Click, run as admin.

I love executables because I'm an avid Windows User. I have used the pip install and command line works fine.

**Comment by Showmaster3000** [comment]
instaloader.exe is a command line tool. no double click with fancy gui.
You mentioned Windows 7? This is way old and no longer supported. Afaik the latest instaloader.exe uses a newer Python version which doesn't work on Win7. So the only option is to use an old Python (3.8?) with the source code or pip.

**Comment by ejbytes** [comment]
@Showmaster3000 I am running python 3.8.4
![vers](https://github.com/user-attachments/assets/e5d980b6-f4bd-4822-8afa-f49d52aef9f4)
Instaloader via pip3 install works fine, via cmd. Just not the instaloader.exe.
