### ISSUE TITLE
stories

### ISSUE THREAD

**Issue by gnu-like** [instaloader/instaloader#243]
Hi,Is it possible to download old stories?

**Comment by Thammus** [comment]
Short answer: No.

Extended answer: If you had downloaded the story earlier and still have the metadata JSON file you can pass this file to Instaloader to re-download the story. If you do not have the metadata and the owner of the story did not highlight it, then you will have no luck on getting an expired story from the Instagram servers.

**Comment by gnu-like** [comment]
@Thammus like [storiesig](https://storiesig.com/) but this website can not support private followers
