### ISSUE TITLE
Windows Defender blocks Instaloader

### ISSUE THREAD

**Issue by Galowyn** [instaloader/instaloader#2433]
Hi !

Never had an issue like this before, Windows Defender block Instaloader from today with this message : 

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Program%3AWin32%2FWacapew.C!ml&threatid=265744

**Comment by Showmaster3000** [comment]
This is a false positive. Instaloader does not contain any malware.
You could report this false-positive to your antivirus vendor, helping them to ship better software and sparing other users that scary message.
See also #1002.
