### ISSUE TITLE
How to download only the captions of an Instagram profile?

### ISSUE THREAD

**Issue by Ecdldaiiere** [instaloader/instaloader#2434]
Hello, I read the documentation for Instaloader but I couldn't see exactly if there was a way to download all of the captions from an Instagram profile without downloading the pictures. Is this possible? Could someone help me because I'm not sure how to go about doing this.

**Comment by gitdoluquita** [comment]
You should use `--no-pictures --no-videos --no-video-thumbnails`. See the [docs](https://instaloader.github.io/cli-options.html#cmdoption-no-pictures)
