### ISSUE TITLE
L.get_hashtag_posts(HASHTAG)  can not work

### ISSUE THREAD

**Issue by VFGcdgt63** [instaloader/instaloader#2435]
The obtained status is 404    resp = sess.post('https://{0}/{1}'.format(host, path), data=params, allow_redirects=False)

Error ：JSON Query to explore/tags/nba/: 404 Not Found when accessing https://www.instagram.com/explore/tags/nba/?__a=1&__d=dis [retrying; skip with ^C]

**Comment by Showmaster3000** [comment]
incomplete bug report. no issue template used.
description cannot be reproduced.
