### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Jeroitsme** [instaloader/instaloader#2436]
after typing 
--login

this shows up:
At line:1 char:3
+ --login
+   ~
Missing expression after unary operator '--'.
At line:1 char:3
+ --login
+   ~~~~~
Unexpected token 'login' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

version 4.14

what do i do??

**Comment by Showmaster3000** [comment]
incomplete bug report. no issue template. at least the complete command line is missing.
