### ISSUE TITLE
Login Failure - window._sharedData

### ISSUE THREAD

**Issue by mitchellm95** [instaloader/instaloader#2437]
After using logging in I get:

JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Fatal error: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.

User and pass is correct. Worked previosuly in the day, and then broke randomly. Reinstalled everything, no progress.

**Comment by Showmaster3000** [comment]
too less information for helping out.
Login is buggy, use workarounds desrcibed in other issues and manual.

**Comment by varundeva** [comment]
Im also facing same issue. 
`python ig.py 

/Users/varundeva/Projects/media-tools/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Failed to log in: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.
 * Serving Flask app 'ig'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
/Users/varundeva/Projects/media-tools/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Failed to log in: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.
 * Debugger is active!
 * Debugger PIN: 131-502-822
 * Detected change in '/Users/varundeva/Projects/media-tools/ig.py', reloading
 * Restarting with stat
/Users/varundeva/Projects/media-tools/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Failed to log in: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.
 * Debugger is active!
 * Debugger PIN: 131-502-822
^C%                                                                                                                                                   
(venv) varundeva@Varuns-MacBook-Pro media-tools % python ig.py

/Users/varundeva/Projects/media-tools/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Failed to log in: JSON Query to accounts/login/: Could not find "window._sharedData" in html response.
 * Serving Flask app 'ig'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit`
