### ISSUE TITLE
bug reporting on login with CLI

### ISSUE THREAD

**Issue by Youshin** [instaloader/instaloader#2442]
**Describe the bug**
Does not successfully login and use instaloader.

<img width="1330" alt="image" src="https://github.com/user-attachments/assets/2e6b5d15-8157-45dd-88ed-2678d9b4d289">

**To Reproduce**
1. instaloader profile --login={id}
2. type password and 2FA

**Expected behavior**
A clear and concise description of what you expected to happen (even if it seems obvious).

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.
```
Profile profile does not exist.
The most similar profiles are: photo__.profile._, studio92.profile, ius.profile, niveau_profile, profile_hollin.
Trying again anonymously, helps in case you are just blocked.

HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=profile to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
Redirected to login page. Use --login or --load-cookies.
Saved session to /Users/youshin/.config/instaloader/session-youshin1411.
```
**Instaloader version**
`instaloader --version` output.
4.14

**Additional context**

**Comment by Showmaster3000** [comment]
The word "profile" is a placeholder for the nickname of the profile you want to download and must be omited!

**Comment by Youshin** [comment]
> The word "profile" is a placeholder for the nickname of the profile you want to download and must be omited!

I know it is placeholder, but doesn't it be a nickname on error? 

```
JSON Query to api/v1/users/web_profile_info/?username=profile: 404 Not Found when accessing https://i.instagram.com/api/v1/users/web_profile_info/?username=profile [retrying; skip with ^C]
JSON Query to api/v1/users/web_profile_info/?username=profile: 404 Not Found when accessing https://i.instagram.com/api/v1/users/web_profile_info/?username=profile [retrying; skip with ^C]
Profile profile does not exist.
The most similar profiles are: photo__.profile._, studio92.profile, ius.profile, niveau_profile, profile_hollin.
Trying again anonymously, helps in case you are just blocked.

HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=profile to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
Redirected to login page. Use --login or --load-cookies.
```

This error also occurs even when using the profile command with a valid nickname: `instaloader profile youshin1411 --login=youshin1411.`

Isn’t it reasonable to expect the placeholder “profile” to be replaced with the nickname in the error message instead?

**Comment by Youshin** [comment]
o I see. I totally misunderstood command. 

Thank you for your comments @Showmaster3000 @MonkeyKingViper !
