### ISSUE TITLE
Is it instagram blocked the graphql api?

### ISSUE THREAD

**Issue by sdhiki** [instaloader/instaloader#2448]
I am having trouble fetching comments for an Instagram post. Has anyone encountered and solved this issue?

"name": "QueryReturnedBadRequestException",
	"message": "400 Bad Request - \"fail\" status, message \"feedback_required\" when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22DC32CXfy4aK%22%7D",

Output of the URL:
{'errors': [{'message': 'execution error', 'severity': 'CRITICAL'}],
 'status': 'ok'}

**Comment by Showmaster3000** [comment]
incomplete bug report
- no version information
- no command line

**Comment by sdhiki** [comment]
instaloader version 4.14

**Comment by Eff1c** [comment]
I try get reels (`profile.get_reels()`), but get this errors:
```
  File "/Users/me/PycharmProjects/project/.venv/lib/python3.12/site-packages/instaloader/instaloadercontext.py", line 468, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: 401 Unauthorized - "fail" status, message "Please wait a few minutes before you try again." when accessing https://www.instagram.com/graphql/query?variables=%7B%22data%22%3A%7B%22page_size%22%3A12%2C%22include_feed_video%22%3Atrue%2C%22target_user_id%22%3A%221501916106%22%7D%2C%22__relay_internal__pv__PolarisFeedShareMenurelayprovider%22%3Afalse%7D&doc_id=7845543455542541&server_timestamps=true
```
I waited a few minutes, hours and tried again, but have the same error. Im confident that I authorized because I can get some info from profile instance like biography.

I use:
MacBook (Intel), MacOS 14.5
Instaloader 4.14
Python 3.12
