### ISSUE TITLE
Error: Bad stories reel JSON.

### ISSUE THREAD

**Issue by eltoro0815** [instaloader/instaloader#2454]
**Describe the bug**
Working script now gives back the error message: Bad stories reel JSON.

The error occurs on this line in the script:
```php
for story in loader.get_stories():
```

The error is raised in file `instaloader.py` on line `809`:

```php 
        if not userids:
            data = self.context.graphql_query("d15efd8c0c5b23f0ef71f18bf363c704",
                                              {"only_stories": True})["data"]["user"]
            if data is None:
                raise BadResponseException('Bad stories reel JSON.')
```

**To Reproduce**
```php
#!/usr/local/bin/python3.9

import os
import requests
from instaloader import Instaloader

# Benutzername und Passwort von Instagram aus Umgebungsvariablen lesen
USERNAME = "USERNAME"
PASSWORD = "PASSWORD"

# Erstelle Instaloader-Objekt
loader = Instaloader(download_pictures=False,download_video_thumbnails=False,save_metadata=False,dirname_pattern="/volume1/video/tmp/stories", filename_pattern="{profile}_{date_utc}_UTC")

# Zielverzeichnis für die heruntergeladenen Stories
target_directory = "stories"  # Ändere diesen Pfad nach Bedar

try:
    # Einloggen
    loader.login(USERNAME, PASSWORD)

    for story in loader.get_stories():

        # story is a Story object
        for item in story.get_items():
            # item is a StoryItem object
            # print(item.owner_profile.username)
            loader.download_storyitem(item, "")


except Exception as e:
    print(f"Ein Fehler ist aufgetreten: {e}")
```

**Expected behavior**
Instead of an error message I expect to see messages about the current file downloading

**Error messages and tracebacks**
Bad stories reel JSON.

**Instaloader version**
Output of `python -m pip list`
instaloader        4.14

**Additional context**
Output of `python -m pip list`

```
Package            Version
------------------ ---------
certifi            2024.8.30
charset-normalizer 3.3.2
idna               3.10
instaloader        4.14
pip                24.3.1
requests           2.32.3
setuptools         75.1.0
urllib3            2.2.3
wheel              0.44.0
```

**Comment by anmv** [comment]
i get same error

instaloader 4.14
python 3.12 & 3.13

**Comment by aandergr** [comment]
I have tried the `get_stories()` function both with and without providing `userids`, and it works for me without encountering the "Bad stories reel JSON" error.

**Comment by eltoro0815** [comment]
Error no longer shown.
Looks like Problem was caused and fixed by Instagram itself

**Comment by eltoro0815** [comment]
Can be closed

**Comment by eltoro0815** [comment]
Hey,
the script worked for a view days.

Now the "Bas stories reel JSON" error is back.

Here are some more infos:

- the script runs every 24 hours
- the error occurs when running the script on a server
- the error also occurs when running it on a desktop PC where opening Instagram in a browser works.

You probably can't reproduce the error just by running the script once.

Maybe there is some behaviour on Instagram side which leeds to this error after calling the script from a server.

Which information do you send with a request? Maybe we need to add some information, so that instagram does not block (if it does so).

I mean information like Browser Version, OS Version, etc.

Like a browser does it, when it's calling an URL.

What do you think?
