### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Rcola1987** [instaloader/instaloader#246]
I am having 2 issues that may be related. When running the current version of Instaloader 4.2.1 on windows 7 64bit and attempt to login to my own profile to create a new session file it gets an invalid password error.

I have validated that I am using the correct password by logging into the Instagram website.

Also if I use a valid session file with instaloader 4.2.1 it will authenticate my account but when attempting to download pictures I will get traceback errors similar to issue #242  

Sometimes the session file will work and download pictures but it is intermittent and at this point, I cannot create a new session file.

**Comment by Showmaster3000** [comment]
Please post the command line you use and the complete output (you can mask private data like password, usernames).

**Comment by aandergr** [comment]
> I will get traceback errors similar to issue #242

Which traceback error do you get exactly? 

> Also one of the prompts in this path has a spelling error.

Which one?

The way this issue is written it does not help anyone at all. Please provide us exact information about the errors you get. Also, use our issue template for bug reports.
