### ISSUE TITLE
 Redirected to login page. Use --login or --load-cookies.

### ISSUE THREAD

**Issue by DavidKim2002** [instaloader/instaloader#2460]
Redirected to login page. Use --login or --load-cookies.

**Comment by klapauciuz** [comment]
HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=usernameto https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/

same, trying to get highlights


  [X] Exception: Redirected to login page. You've been logged out, please wait some time, recreate the session and try again

**Comment by Showmaster3000** [comment]
I see no question, just a message from instaloader output.
Check the description how to create a good issue.
