### ISSUE TITLE
Sleep (pause) when downloading comments separately

### ISSUE THREAD

**Issue by hdma** [instaloader/instaloader#248]
Hi, and sorry for my English!

I noticed that if I download media files without comments, the “Too Many Requests” messages do not appear. Therefore, I decided to download all media files first, and then download comments without media files. However, when I download comments without media files and without “post-metadata-txt” files, the messages “Too Many Requests” appear. As I suppose, this is connected with the simultaneous attempt to download all sub-pages for comments of one post (while expanding comments for a post) and it seems to me that if you add a pause between requests for loading pages for comment, you could get rid of the messages “Too Many Requests”. Is there such a possibility? Could you tell me where in the code you can add a pause, so that between calls to the sub-comnarimate commenarium there is a short sleep?

**Comment by hdma** [comment]
Please tell me where in the code parts of the comments are downloaded so that you can pause each request?

**Comment by hdma** [comment]
What is the reason that I have a lot of such messages —
```
"The request will be retried in 7 seconds. at 21:55"
"The request will be retried in 16 seconds. at 21:55"
"The request will be retried in 10 seconds. at 21:55"
"The request will be retried in 35 seconds. at 21:55"
"The request will be retried in 518 seconds. at 21:55"
...
```
and so on and so forth — with a small amount of downloads for the whole day? Parallel Instagram/Instaloader is not used anywhere else. Is it all so?

**Comment by aandergr** [comment]
> if you add a pause between requests for loading pages for comment, you could get rid of the messages “Too Many Requests”. Is there such a possibility?

Instaloader keeps track of its requests to Instagram and adds pauses to not exceed their rate limits.

> Could you tell me where in the code you can add a pause

The logic for pauses between requests is in InstaloaderContext.get_json():

https://github.com/instaloader/instaloader/blob/a0b7804fd2cfa45b06111e66537015964517f007/instaloader/instaloadercontext.py#L282-L304

Instaloader has a (hidden) command line flag `--graphql-rate-limit=NUMBER` with which you can control how many requests should be done within a certain time.
