### ISSUE TITLE
Failed to get profile from_id

### ISSUE THREAD

**Issue by Holfz** [instaloader/instaloader#249]
**Describe the bug**
If profile didn't has any post. Getting Username from userid will result in error

**Error messages and tracebacks**
> instaloader.exceptions.ProfileHasNoPicsException: Profile with ID xxxxxxxxxx: no pics found.

**Instaloader version**
4.2.1

**Code**
```
import instaloader

L = instaloader.Instaloader()
USER = '******'
USERID= "xxxxxxxxxxx"
L.load_session_from_file(USER, './session-******')

profile = instaloader.Profile.from_id(L.context, USERID).username
print(profile)
```

**Comment by torchinz** [comment]
Receiving multiple traceback errors and exceptions, as per the following screenshot

![image](https://user-images.githubusercontent.com/17811608/52123976-c9b60f80-264d-11e9-9816-8fe7c069d261.png)
