### ISSUE TITLE
Program only saves the Profile Picture and they are in 320x320 resolution 

### ISSUE THREAD

**Issue by no0t** [instaloader/instaloader#250]
Hey there,
So I've downloaded this program recently (and thanks for writing tutorial in a very open detail) I'm using its Windows version as in others I couldn't figure out how can I install it with Python.
Anyway, I'm using the codes you gave. I'm trying to get "posts/pictures" from a private Instagram Profile, though the program is only downloading 320x320 profile picture and rar'd .json file and that's it. Though I wanted to download that private profile's all photos instead of its profile pic.

Is there way to fix this?

**Comment by Showmaster3000** [comment]
you need to use the latest version 4.2.1 of instaloader to download full size profile pic. also you have to login, because instagram changed that. anyway if you want to download a private profile you have to be a follower. otherwise you cannot download anything else than the profile pic.

**Comment by no0t** [comment]
Thanks for the answer. 
I wish we could download pics from private profiles as well, it could be more useful
