### ISSUE TITLE
filtering out by hashtag and location ID 

### ISSUE THREAD

**Issue by sydwiener** [instaloader/instaloader#254]
Hello! 
Thank you so much for creating this program. I am trying to find a way to filter through downloaded instagrams by hashtag and location. So for instance, I am using this for my thesis and I would love to only see posts with #artselfie within the location for MoMA but nothing I have tried so far has worked. 
Thanks in advance for any help! 
Sydney

**Comment by aandergr** [comment]
Hello!

Unfortunately, filtering my multiple criteria is always inefficient - we'd have to scrape by one criteria, and check for each post whether the others are met. For your case, there are two options

1. Go through posts located at MoMA and take only those with #artselfie:
```instaloader %2999512 --post-filter="'artselfie' in caption_hashtags"```

2. Go through posts with hashtag #artselfie and take only those located at MoMA:
```instaloader "#artselfie" --post-filter="location and location.id==2999512"```

Alex

**Comment by Bilall003** [comment]
> Hello!
> 
> Unfortunately, filtering my multiple criteria is always inefficient - we'd have to scrape by one criteria, and check for each post whether the others are met. For your case, there are two options
> 
> 1. Go through posts located at MoMA and take only those with #artselfie:
>    `instaloader %2999512 --post-filter="'artselfie' in caption_hashtags"`
> 2. Go through posts with hashtag #artselfie and take only those located at MoMA:
>    `instaloader "#artselfie" --post-filter="location and location.id==2999512"`
> 
> Alex



> Hello!
> 
> Unfortunately, filtering my multiple criteria is always inefficient - we'd have to scrape by one criteria, and check for each post whether the others are met. For your case, there are two options
> 
> 1. Go through posts located at MoMA and take only those with #artselfie:
>    `instaloader %2999512 --post-filter="'artselfie' in caption_hashtags"`
> 2. Go through posts with hashtag #artselfie and take only those located at MoMA:
>    `instaloader "#artselfie" --post-filter="location and location.id==2999512"`
> 
> Alex

I'm trying to filter using location ID can you help me in that?
