### ISSUE TITLE
download first image

### ISSUE THREAD

**Issue by ziggii42** [instaloader/instaloader#256]
Hello.

I downloaded a lot of instagram profiles with an other program and want to update my archive without downloading all images again. It would be very useful if you could download the first picture of a profile with instaloader so you can use the --fast-update function.

**Comment by aandergr** [comment]
Hello.

Can you change the filename-pattern (https://instaloader.github.io/basic-usage.html#filename-specification) such that Instaloader stores the files the same way your other program did? Then it would recognize the files that were already downloaded by the other program.

There is no flag to tell Instaloader to just download one picture for each profile. However, a simple script would do that:
```python
from instaloader import Instaloader, Profile

# Instaloader instantiation - you may pass additional arguments to the constructor here
L = Instaloader()

# If desired, load session previously saved with `instaloader -l USERNAME`:
#L.load_session_from_file(USERNAME)

profile_names = ["profile1", "profile2"]

for profile in (Profile.from_username(L.context, profile_name)
                for profile_name in profile_names):
    for post in profile.get_posts():
        L.download_post(post, profile.username)
        break
```

**Comment by ziggii42** [comment]
Thank you for your response. Your script did exactly that what i want.
