### ISSUE TITLE
Can't create sessionfile

### ISSUE THREAD

**Issue by Moquo** [instaloader/instaloader#258]
**Describe the bug**
I can't create a new session file or use an existing one. I get a permission error everytime.

**To Reproduce**
`instaloader --login=********* --sessionfile=.instaloader-session`

**Expected behavior**
The session file should be created without any problem.

**Error messages and tracebacks**
```
[Errno 2] No such file or directory: '.instaloader-session'
Session file does not exist yet - Logging in.
Enter Instagram password for *********:
Enter 2FA verification code:
Logged in as *********.
Traceback (most recent call last):
	File "/usr/local/bin/instaloader", line 11, in <module>
		load_entry_point('instaloader==4.2.3', 'console_scripts', 'instaloader')()
	File "/usr/local/lib/python3.6/site-packages/instaloader/__main__.py", line 410, in main
		storyitem_filter_str=args.storyitem_filter)
	File "/usr/local/lib/python3.6/site-packages/instaloader/__main__.py", line 198, in _main
		instaloader.save_session_to_file(sessionfile)
	File "/usr/local/lib/python3.6/site-packages/instaloader/instaloader.py", line 47, in call
		return func(instaloader, *args, **kwargs)
	File "/usr/local/lib/python3.6/site-packages/instaloader/instaloader.py" ,line 368, in save_session_to_file
		os.chmod(filename, 0o600)
PermissionError: [Errno 1] Operation not permitted: '.instaloader-session'
```

**Instaloader version**
`4.2.3`

**Additional context**
I own the folder and have full access to the folder instaloader is working in. Moved to a new system recently and since then, instaloader isn't working.

**Comment by aandergr** [comment]
It seems the chmod is failing. Is this some strange filesystem? Can you create a file and chmod it to 0600 in the shell?

**Comment by ailinykh** [comment]
You have to specify an absolute path, not relative

```bash
instaloader --login=********* --sessionfile=`pwd`.instaloader-session
```

**Comment by aandergr** [comment]
> You have to specify an absolute path, not relative

I can specify a relative path for the session file without any problems.
