### ISSUE TITLE
private but not followed

### ISSUE THREAD

**Issue by kurttian** [instaloader/instaloader#260]
how can I download target private account photos without following them?

**Comment by aandergr** [comment]
You have to follow a private account to access its posts. That's exactly what private means.

**Comment by Noobie777** [comment]
So you cannot download photos from a private profile unless you're following them making them visible to your account?
Then there's no point in detailing it as can download private profile's images.. it's a scam lol

**Comment by dimasputrairfandanu** [comment]
scaaam

**Comment by dimasputrairfandanu** [comment]
How can i download private instagram account, instaloader private download is a scam,

**Comment by dimasputrairfandanu** [comment]
How can i download private instagram account, instaloader private download is a scam, you should update your docs.

**Comment by mrengineer38** [comment]
If I can't download from a profile I don't follow, it's just nonsense to use this software. I can simply download pictures and videos of an account I already follow. Then this program is a useless big scam. lol

**Comment by ManikSinghSarmaal** [comment]
> If I can't download from a profile I don't follow, it's just nonsense to use this software. I can simply download pictures and videos of an account I already follow. Then this program is a useless big scam. lol

did you find something to download pictures and videos of an account you don't follow ?
