### ISSUE TITLE
[Question] Recommended interval for crontab

### ISSUE THREAD

**Issue by juanspeed** [instaloader/instaloader#261]
Hello Sorry for my bad English, I want to use Instaloader with crontab, I would like to know which is the recommendable interval to update the profiles.
- I use "crontab" with this configuration:  */15 * * * *  (This works well and so far I have no problems, but I wanted to know if I can disminish the 15 min)
- Every 10 min would be fine ?.
- The profiles that I will update are 6
Thank you

**Comment by jlntrt** [comment]
If you use an ubuntu based OS, you can use `run-one`.
https://manpages.ubuntu.com/manpages/bionic/man1/run-one.1.html

You can start instaloader every minute with this command. It will only start a new process of instaloader if no other process is already running. This makes ist possible to run instaloader as often as possible.
