### ISSUE TITLE
Difficulty with filenames including captions (emojis in particular?)

### ISSUE THREAD

**Issue by rivke41levp656** [instaloader/instaloader#262]
**Describe the bug**
I want the filename to be along the lines of: caption-date-username, but I am having difficulty saving profiles when I include caption in the filename. I think it's an issue with emojis. I'm running Windows 8.1. 
I encounter same issue with both Windows executable and Python installation. 

**To Reproduce**
>instaloader --login * --filename-pattern={caption} profile cristiano
breaks upon the first post, which is https://www.instagram.com/p/BubxcOFANRv/, as of writing this. If I remove the caption from filename it works as expected. 
It does not occur for all posts containing emojis, e.g. : https://www.instagram.com/p/BuXJorflk92/ works as expected. 
Maybe it's only newer emojis or something?

**Error messages and tracebacks**
Above command gives following error:

Retrieving posts from profile cristiano.
[  1/2485] cristiano/Portugal. É de fibra que somos feitos!!!
💪🇵🇹⚽🏍 🧢
#afibradosportugueses.jpg Traceback (most recent call last):
  File "__main__.py", line 442, in <module>
  File "__main__.py", line 438, in __main
  File "__main__.py", line 413, in main
  File "__main__.py", line 189, in _main
  File "instaloader\instaloader.py", line 985, in download_profiles
  File "instaloader\instaloader.py", line 447, in download_post
  File "instaloader\instaloader.py", line 65, in call
  File "instaloader\instaloader.py", line 227, in download_pic
  File "instaloader\instaloadercontext.py", line 523, in get_and_write_raw
  File "instaloader\instaloadercontext.py", line 489, in write_raw
OSError: [Errno 22] Invalid argument: 'cristiano/Portugal. É de fibra que somos
feitos!!!\n💪🇵🇹⚽🏍 🧢\n#afibradosportugueses.jpg'
[9444] Failed to execute script __main__

I should add that this command:

instaloader --login * --filename-pattern={caption} profile leomessi  

fails at https://www.instagram.com/p/Bt3nFrJokI9/

which is currently the 5th post on his profile, with this error (different from the above one): 
[  5/421] leomessi/Fui con todo y me sumé al reto por la última lata de @pepsi.
/// Going all in for the love of it as we compete for the Last Can Standing.  #F
ORTHELOVEOFIT.jpg Traceback (most recent call last):
  File "__main__.py", line 442, in <module>
  File "__main__.py", line 438, in __main
  File "__main__.py", line 413, in main
  File "__main__.py", line 189, in _main
  File "instaloader\instaloader.py", line 985, in download_profiles
  File "instaloader\instaloader.py", line 447, in download_post
  File "instaloader\instaloader.py", line 65, in call
  File "instaloader\instaloader.py", line 227, in download_pic
  File "instaloader\instaloadercontext.py", line 523, in get_and_write_raw
  File "instaloader\instaloadercontext.py", line 489, in write_raw
FileNotFoundError: [Errno 2] No such file or directory: 'leomessi/Fui con todo y
 me sumé al reto por la última lata de @pepsi. /// Going all in for the love of
it as we compete for the Last Can Standing.  #FORTHELOVEOFIT.jpg'
[4916] Failed to execute script __main__

It downloads properly when I remove caption from the filename.
So there may also be an issue with videos that contain illegal characters (e.g. '/') when caption is part of the filename? 

**Instaloader version**
4.2.3

**Additional context**
I've fiddled with this a bit, and there seems to be a problem with certain emojis, or maybe more broadly illegal characters in Windows filenames such as / and *. It's strange though, as those emojis are not illegal characters, I can create filenames that contain those successfully. I don't know, it seems the caption parameter is failing in many cases.

**Comment by e5150** [comment]
I think the problem with the first one might be the newline character, `\n`. Can't confirm on my non-windows machines, but you could try adding `.replace('\n', ' ')` to line 110 in instaloader.py. 

The second one seems to be a problem with `/`. On linux `Fui con todo... /// Going all in...` resolves to the directory `Fui con todo...` plus the file(s) `Going all in...`. I'm guessing windows treats the `Fui...///Going...` as two folders with no name at all (which is probably illegal), which results in the error. But the result isn't really what one would expect on either platform. @aandergr: `/` can't really be blacklisted, if one want's to create subdirectories, but it should be possible for `_PostPathFormatter` to sanitize `"{caption}"` (which ought to be the only problematic one) prior to the `vformat`.

**Comment by Showmaster3000** [comment]
I think it's a similar problem as in issue #197 having emojis on highlight titles or issue #199 where the colon is an invalid character (which is btw. closed but not really solved for Windows users)

**Comment by gituzzer** [comment]
I had a similar problem with illegal chars in stories, inside instaloader.py --> download_storyitem() , fixed with:
...
        filename = dirname + '/' + self.format_filename(item, target=target)
        filename = re.sub('[!@#$: ]', '', filename)  #FIX illegal chars go here
        if (filename[-1]='.')            # FIX last char as . gives problems
           filename = filename+'X';

**Comment by gituzzer** [comment]
For downloading tagged, also an illegal char is the folder :/tagged that gets created as Windows does not allow this folder. So:

        if target is None:
            target = profile.username + '/tagged' # FIX /: --> /

**Comment by Thammus** [comment]
Using captions for filename patterns is not officially supported.
As @e5150 pointed out, the problems you are facing originate from the fact that the captions contain slashes ('/') and newlines ('\n') which are not allowed in filenames on some/most systems. The emojis should not be a problem, even on Windows. In order to replace the problematic characters you could override [`get_value()`](https://docs.python.org/3/library/string.html#string.Formatter.get_value) inside [`_PostPathFormatter`](https://github.com/instaloader/instaloader/blob/adb9f3a346a4330858d064924eec5a194bfcdafb/instaloader/instaloader.py#L105-L112) like the following:
```python
    def get_value(self, key, args, kwargs):
        """Replaces '/' with similar looking fullwidth solidus and on windows newline with space"""
        ret = super().get_value(key, args, kwargs)
        if not isinstance(ret, str):
            return ret
        ret = ret.replace('/', '\uff0f')
        if platform.system() == 'Windows':
            ret = ret.replace('\n', ' ')
        return ret
```

After doing so, there still persists a problem with the length of the caption strings which may exceed the maximal file length on some systems.
As you can see, supporting this feature would require some ugly hacks whilst offering little benefits. We  
therefore discourage to use captions in filenames.
