### ISSUE TITLE
Anonymous download when possible

### ISSUE THREAD

**Issue by gituzzer** [instaloader/instaloader#267]
**Provide us a use case of the feature**
Some profiles can be downloaded anonymously, some not. When downloading a bunch of profiles, do not login when not needed, and attempt to download anonymously.

**Describe the solution you'd like**
Currently, when logging in to download profile data from a user, we get a message "profile xxxxx could also be downloaded anonymously" for the non-private profiles. As the script is able to detect it, it could skip logging in and download data anonymously by default (or per cmd line option)

As I observed in instaloader.py, "anonymous_retry_profiles" is already in use, but it only takes place when it cannot download when logged in (because of block issues, etc). The implementation would reverse this logic, so by default downloading anonymously, and if failing, then logging in and downloading logged-in.

**Comment by github-userx** [comment]
Great idea!
