### ISSUE TITLE
How download only last post ? without downlaoding all photo

### ISSUE THREAD

**Issue by Dobe12** [instaloader/instaloader#270]
i known i can use "instaloader --post-filter="date_utc <= datetime(2018, 5, 31)" target", but after dowloading right photos it scanning other photos. And if profile have more then 1000 photos i have problems. How to limit downloading ? Why "-count" not work with loading from profile ?
(sory for bad english ;) )

**Comment by hgkmaxymus** [comment]
You can try something like this python example (note this example checks the hashtags): https://instaloader.github.io/codesnippets.html#only-one-post-per-user

Good luck!
