### ISSUE TITLE
How to delete a post? ...any solutions?

### ISSUE THREAD

**Issue by AndreySurikov** [instaloader/instaloader#274]
From Subject Title... thanks for the help )))

**Comment by aandergr** [comment]
We consider this beyond the scope of Instaloader. Instaloader's goal is to mimick the browser's behavior to access the data that is available through the Instagram web interface, pack this data into complete and easily-(re)usable python objects, and provide a user interface for the most common downloading and metadata collection tasks, without changing any of the online data.
