### ISSUE TITLE
Log of last saved data to transfer to new drive

### ISSUE THREAD

**Issue by beakwood** [instaloader/instaloader#275]
**Provide us a use case of the feature**
How could the user invoke the new function? Which problem would it solve? If new information is obtained, how would it be further processed?
python +names ++logs 
**Describe the solution you'd like**
Basically to update from a log file of the last files downloaded and continue downloading

**Describe alternatives you've considered**
Individually leaving the last downloaded items in each folder intact

**Additional context**
Want to be able to delete or start on a new hard drive pick up where I left off without having to start over downloading usernames from scratch one, have a log file recognized the last files downloaded per username. Something like found in this script https://github.com/notcammy/PyInstaLive "log_to_file = True"

**Comment by sargent-penguin** [comment]
I like that idea!

I would suggest something like a timestamp file, where the time of downloading the content is saved.
Similar to the id file.

**Comment by MatthieuBonenfant** [comment]
Good idea, much better than moving all the files but the last one to another drive one folder at the
time. Would love that feature as well.

**Comment by e5150** [comment]
I think this would be solved with the idea of keeping a database of timestamps of last run for a given target, that was discussed in #72.
