### ISSUE TITLE
filename-pattern id

### ISSUE THREAD

**Issue by gnu-like** [instaloader/instaloader#277]
instead `--filename-pattern {date_utc}_UTC`
need of the instagram id of the media 
`--filename-pattern {id}`

**Comment by aandergr** [comment]
There is `--filename-pattern {shortcode}`, see https://instaloader.github.io/basic-usage.html#filename-specification

**Comment by gnu-like** [comment]
@aandergr please look .json before short code you will see `"__typename":"GraphImage","id":"1393618864990238258"` exactly what I need. thanks for response
