### ISSUE TITLE
Command Clarification

### ISSUE THREAD

**Issue by nevadarain** [instaloader/instaloader#281]
I would like some clarification on the following command please.

instaloader --login=your_username profile [profile ...]

I'm not clear on what is happening here. If my username is "nevadarain", Do i do the following command,

instaloader --login=nevadarain profile [profile ...]   ?

And also, how is nevadarain being logged into without a password in this command?

Thanks.

**Comment by aandergr** [comment]
> Do i do the following command [...]?

Yes.

> how is nevadarain being logged into without a password in this command?

Instaloader will ask for the password.

Just try it out...
