### ISSUE TITLE
Single post download

### ISSUE THREAD

**Issue by Coriou** [instaloader/instaloader#283]
Unless I'm mistaken, there's right now no way to download a single Instagram post. I think this feature would be quite nice. 

My use case is a bot I have running, interacting with various posts and I'm building an UI to see the reports. I have a list of posts the bot interacted with, and I'd like to download those posts with all the neat instaloader features. Except, I just want one post each time.

For the implementation, I think it's all there already and should leverage [`download_pic()`](https://github.com/instaloader/instaloader/blob/87d877e650cd8020b04b8b51be120599a441fd5b/instaloader/instaloader.py#L209-L229)

Here's how I see the minimal CLI implementation `instaloader --single https://www.instagram.com/p/xxx`

The output should be similar to the actual instaloader imho.

**Comment by aandergr** [comment]
Please have a look at our documentation: https://instaloader.github.io/basic-usage.html#what-to-download

> -post
The single post with the given shortcode. Must be preceeded by -- in the argument list to not be mistaken as an option flag.

**Comment by Coriou** [comment]
My bad. Thanks

**Comment by LaticePrime** [comment]
This doesn’t work for me. I have tried:

instaloader -shortcode
Instaloader -post
Instaloader — -shortcode
Instaloader — -post

All followed by the shortcode and none of them work. 

Thoroughly searched the online help including the document linked above and can’t get a concise syntax that works

**Comment by devyzr** [comment]
This works for public posts, but not for single posts. Using a meme account as an example, this works for a publicly available post:

instaloader -- -CKoUHyGlKQX

But this doesn't work for a private post:
instaloader -- -CKmhzlcDuPeXnPePKXNC-NQeRSXdy57ZZ6zPI80
instaloader --login=devyzr -post CKmhzlcDuPeXnPePKXNC-NQeRSXdy57ZZ6zPI80
instaloader --login=devyzr -CKmhzlcDuPeXnPePKXNC-NQeRSXdy57ZZ6zPI80
