### ISSUE TITLE
Add date time to post

### ISSUE THREAD

**Issue by Regina21** [instaloader/instaloader#284]
When I extract the posts of an instagram profile (see code below) I do not get the date of the post. How can I extract posts and the date of the post?
Thank you for the help!

`from datetime import datetime
from itertools import dropwhile, takewhile

import instaloader

from instaloader import Instaloader, Post, Profile, load_structure_from_file

USERNAME = 'rafaelnadal'
L = instaloader.Instaloader()
profile = Profile.from_username(L.context, USERNAME)

for post in profile.get_posts():
    L.download_post(post, USERNAME)`

**Comment by aandergr** [comment]
There is `post.date_utc`: https://instaloader.github.io/as-module.html#instaloader.Post.date_utc
