### ISSUE TITLE
How to not load metadata with python library?

### ISSUE THREAD

**Issue by mgcbureiii** [instaloader/instaloader#285]
In cli it's --no-metadata-json attribute, but how to do it in Python?
And how to just update my Instagram "repo" with new images like cli's -F flag?
Thanks.

**Comment by aandergr** [comment]
Pass `save_metadata=False` to your Instaloader instantiation. The parameters and their mappings to the CLI arguments are presented here: https://instaloader.github.io/as-module.html#instaloader-main-class
