### ISSUE TITLE
very strange code 429 

### ISSUE THREAD

**Issue by macd2** [instaloader/instaloader#287]
**Describe the bug**

I'm using instaloader on my local dev machine (ubuntu 16.4) since weeks without any issues,
now i moved the code to the server (ubuntu 16.4) and all of a sudden im getting 429 all the time without doing anything different than before, what could that be?

**Expected behavior**
A clear and concise description of what you expected to happen (if not obvious).

**Error messages and tracebacks**
JSON Query to graphql/query: 429 Too Many Requests [retrying; skip with ^C]
HTTP error code 429 was returned because too many queries occured in
the last time. Please do not use Instagram in your browser or run
multiple instances of Instaloader in parallel.
Made 5 GraphQL requests.
The request will be retried in 26 seconds, at 17:54.

**Instaloader version**
`instaloader --version` output.
`4.2.1`

**Additional context**

**Comment by e5150** [comment]
Is your server a rented one, where other users might be trying to access the instagram servers from the same IP? Or running behind a VPN? The instagram servers seems to be more lenient on "local dev machines" running from home (at least wrt login challenge/error 400).
Otherwise, if your server is running from the same connection, I don't know… make sure you havn't accidentally spawned hundreds of instaloader processes due to a bad cronjob, or something.

**Comment by aandergr** [comment]
> **Instaloader version**
> `instaloader --version` output.
> `4.2.1`

The current version is 4.2.4 and there have been changes to the rate control logic (the logic that avoids the 429 error) in 4.2.3, so upgrading to the current Instaloader version might fix the problem. 

Also, ensure that neither the Instagram browser interface, nor a mobile app, nor another Instaloader instance is accessing your Instagram in parallel.

**Comment by macd2** [comment]
@e5150  Im using didgital ocean and they say each droplet got a unique IP since this was my suspicion at first. 
@aandergr I also tried `4.2.4` with the same result, instaloader is part of a bigger program and only there to get the Username from user_id. On the local machine it worked perfectly and in 4 Weeks i never had any issues with 429 on the server i get i on the first Iteration.
