### ISSUE TITLE
Dumb question - What does [profile ...] do?

### ISSUE THREAD

**Issue by bbHood925** [instaloader/instaloader#289]
Like the title says. Using the command instaloader profile [profile ...] I understand putting the target username in place of that first profile. But I didn't change the profile in brackets and the script still managed to pull all the data I needed. What does it do?

**Comment by aandergr** [comment]
It loads every profile you specify. `instaloader profile1` loads profile1. `instaloader profile1 profile2` loads profile1 and profile2 (and so on).

Our denotion, `instaloader profile [profile ...]` is based on a convention that is typically used to describe how to invoke CLI applications, which is well described here:

http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html

(Point 7 and 9 in chapter 12.1)
