### ISSUE TITLE
Outputs folder to same directory.

### ISSUE THREAD

**Issue by warmsweater** [instaloader/instaloader#292]
Hello, thank you for this wonderful program.  I'm a bit in a rush but I wanted to make this before I forgot.  I don't have the output with me give you an exact example, so I'll go with what I have.

Updating to this latest version  (4.2.5 I believe) via python-pip3 now outputs anything that would've normally gone into a subdirectory into the same directory.  I believe its because the character `∕` is used instead of `/`.  I have also done a major system upgrade and changed Desktops, so it could be on my end instead.  Downgrading to the previous version does not have this problem.

For example, if I were to do `instaloader --tagged instauser` it would output as:
`/instauser∕:tagged`
instead of
`/instauser/:tagged` <- with `:tagged` as a directory.

Let me know if you need any more examples or if I can clarify.  I'm also using Fedora if that matters at all.  Thank you again for the great program.

**Comment by aandergr** [comment]
This is fixed with version 4.2.6. Thanks for reporting!
