### ISSUE TITLE
Do posts get updated when using get_hashtag_posts?

### ISSUE THREAD

**Issue by thomasthomas11235** [instaloader/instaloader#296]
Hello,

I was wondering if posts meta-data is updated when using the get_hashtags_posts function? I want to update likes and comments count if the post already exists.

Thanks!

**Comment by aandergr** [comment]
`get_hashtag_posts` does not write or update anything. It is a generator of `Post` instances of the posts that are currently returned for the given hashtag.

When using the Instaloader CLI, the json files and the txt metadata files are updated with each run. There is a feature suggestion, #224, to provide a way to control this behavior.
