### ISSUE TITLE
"Profile does not exist" (KeyError: 'rhx_gis')

### ISSUE THREAD

**Issue by arne-kerstin** [instaloader/instaloader#297]
**Describe the bug**
When I try to download a profile, it says that the profile does not exist. I tried different ways already, for example, downloading anonymously, downloading with an account that follows the profile, downloading with an account that doesn't follow the profile, downloading with an account via session files, changing IP via VPN each time, restarting my device, even using older versions (I've tried 4.0.7, 4.1, and 4.2.6)

**To Reproduce**
python3 $instaloaderdirectory/instaloader.py $username
I've been using instaloader like this for almost 2 years now.

**Error messages and tracebacks**
$username: Profile $username does not exist.

**Instaloader version**
4.0.7, 4.1, 4.2.6

**Additional context**
I also tried logging in to the various accounts mentioned and checking different profiles to try download. It doesn't look like I am blocked in any of them since I can still interact with the profiles I've tried, nevermind the public ones. I'm running Ubuntu 18.04.

**Comment by arne-kerstin** [comment]
![Screenshot from 2019-05-16](https://user-images.githubusercontent.com/44148553/57825584-0c04f600-77d2-11e9-962d-fed22e9477ef.png)
I tried using it with the instructions provided (installing via pip3) and it still doesn't work

**Comment by hgkmaxymus** [comment]
I think instagram is having some API issues or they changed something. I am also having trouble.

```
Traceback (most recent call last):
  File "C:\Users\hgkmaxymus\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 528, in _metadata
    d = d[key]
KeyError: 'has_blocked_viewer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hgkmaxymus\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 520, in _obtain_metadata
    self._rhx_gis = metadata['rhx_gis']
KeyError: 'rhx_gis'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hgkmaxymus\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\__main__.py", line 157, in _main
    if instaloader.context.is_logged_in and profile.has_blocked_viewer:
  File "C:\Users\hgkmaxymus\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 609, in has_blocked_viewer
    return self._metadata('has_blocked_viewer')
  File "C:\Users\hgkmaxymus\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 531, in _metadata
    self._obtain_metadata()
  File "C:\Users\hgkmaxymus\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 522, in _obtain_metadata
    raise ProfileNotExistsException('Profile {} does not exist.'.format(self.username)) from err
instaloader.exceptions.ProfileNotExistsException: Profile <profile_here> does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hgkmaxymus\AppData\Local\Programs\Python\Python37\Scripts\instaloader-script.py", line 12, in <module>
  File "C:\Users\hgkmaxymus\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\__main__.py", line 410, in main
    storyitem_filter_str=args.storyitem_filter)
  File "C:\Users\hgkmaxymus\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\__main__.py", line 174, in _main
    anonymous_retry_profiles.add(anonymous_loader.check_profile_id(target))
  File "C:\Users\hgkmaxymus\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloader.py", line 910, in check_profile_id
    profile_from_id = Profile.from_id(self.context, profile_id)
  File "C:\Users\hgkmaxymus\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\structures.py", line 496, in from_id
    rhx_gis=context.root_rhx_gis)['data']['user']
  File "C:\Users\hgkmaxymus\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloadercontext.py", line 534, in root_rhx_gis
    self._root_rhx_gis = self.get_json('', {})['rhx_gis']
KeyError: 'rhx_gis'
```

**Comment by bleshik** [comment]
Yeah, I'm seeing this as well... Looks like they got rid of rhx_gis and it is not needed anymore

**Comment by ZRDG** [comment]
I have the same problem.

**Comment by heyt0ny** [comment]
Having the same problem. Seems like all of repos with ig profile parsing having the same issue with "rhx_gis" - https://github.com/rarcega/instagram-scraper/issues/377

**Comment by reliefs** [comment]
same problem

**Comment by bleshik** [comment]
Just correct the code locally, until it's fixed here properly.

The fix is simple: all rhx_gis fields and variables should be just an empty string.

**Comment by bleshik** [comment]
This code works fine for me: https://github.com/bleshik/instaloader

**Comment by VasiliPupkin256** [comment]
@bleshik aren't you effectively turning off the code by testing `self._rhx_gis == None` later on?

**Comment by bleshik** [comment]
@VasiliPupkin256 yup, my bad, fixed here https://github.com/bleshik/instaloader/commit/49af9c4bf9d63a46302df3e22e99a9a3e908598e

**Comment by ZRDG** [comment]
@bleshik self._rhx_gis_str = pic_json['rhx_gis']
KeyError: 'rhx_gis

**Comment by bleshik** [comment]
@ZRDG nope, it should be empty string

**Comment by bleshik** [comment]
@ZRDG please check it: https://github.com/bleshik/instaloader/commit/1d46fa5418d6ecc45f85b404696fd63e85ebb48d

I haven't tested it, because my bot does not seem to reach these pieces of code.

**Comment by gnu-like** [comment]
@bleshik I tested,Solved.+1

**Comment by arne-kerstin** [comment]
@bleshik I did bleshik@1d46fa5 and bleshik@49af9c4. It's working

**Comment by aandergr** [comment]
@bleshik thanks for fixing this. Could you make a pull request so that we can discuss and merge the changes and release a version with your fix included?

**Comment by roboshim** [comment]
Thank you all for this fast fix! :+1:

**Comment by clb92** [comment]
@bleshik Thank you for the temporary fix. Not sure if it breaks some features of Instaloader, but it seems to work fine for just downloading stories and profile pictures in the meantime, while a permanent fix is developed.

**Comment by gituzzer** [comment]
temp fix works for stories and profiles, although I had to change the code a bit for my best running version, 4.0.8, as it differs from the more current 4.2.x.
Thanks for the fix.

**Comment by onedrawingperday** [comment]
@bleshik Thank you!

The following options work fine for me once again after applying the [temp fixes](https://github.com/instaloader/instaloader/issues/297#issuecomment-492988425):

```
instaloader --only-if="date_utc >= datetime(2019, 5, 14) and 'some-tag' in caption_hashtags" some-profile
```

Looking forward to the new release.

**Comment by psylenced** [comment]
The issue with tagged (and highlights?) is it's not joining the path correctly.

So instead of:

```\profile\:tagged\image.jpg```

It's downloading to:

```\profile[?] :tagged\image.jpg```

**Comment by Thammus** [comment]
Hi there :tada:
Thank you all for the reporting and the solution suggestions. We fixed this `KeyError` in a new release, [Version 4.2.7](/instaloader/instaloader/releases/tag/v4.2.7).

**Comment by somera** [comment]
Can you publish instaloader-v4.2.7-windows-standalone.zip too?

**Comment by Thammus** [comment]
> Can you publish instaloader-v4.2.7-windows-standalone.zip too?

done :slightly_smiling_face:

**Comment by bugraayan1** [comment]
I want to look stories as visible , not invisible. With my profile name. Is it possible ?
Android’de Yahoo Postadan gönderildi 
 
  23:57’’17e’ 17 May 2019 Cum tarihinde, André Koch-Kramer<notifications@github.com> şunu yazdı:   

Can you publish instaloader-v4.2.7-windows-standalone.zip too?


done 🙂

**Comment by FrothySolutions** [comment]
> This code works fine for me: https://github.com/bleshik/instaloader
> 
> These are the required changes: [bleshik@c8c05f5](https://github.com/bleshik/instaloader/commit/c8c05f571403a886412d46c597cb75672a1fd31b)
> 
> Though I'm pretty sure my fix is a quick and dirty solution

Is anyone here? How do I get the patched version of Instaloader?

**Comment by FrothySolutions** [comment]
I'm looking for @bleshik .

**Comment by clb92** [comment]
> Is anyone here? How do I get the patched version of Instaloader?

@FrothySolutions Just download the new version like normal. It's been fixed.

**Comment by FrothySolutions** [comment]
> > Is anyone here? How do I get the patched version of Instaloader?
> 
> @FrothySolutions Just download the new version like normal. It's been fixed.

@clb92 So I re-download Instaloader like I did the first time I downloaded Instaloader?

**Comment by clb92** [comment]
> @clb92 So I re-download Instaloader like I did the first time I downloaded Instaloader?

Yes. You can find it in the Releases section [here](https://github.com/instaloader/instaloader/releases) or via a package manager like PIP (```pip install instaloader --upgrade```).

**Comment by IbragimovaS** [comment]
Have anyone found some solution?
When i try to get profile: `profile = instaloader.Profile.from_id(L.context, id)`
while logged in there is no problem
but as soon as I remove the logging in I get the following error: "`instaloader.exceptions.ConnectionException: JSON Query to graphql/query: HTTP error code 403.`"

**Comment by hgkmaxymus** [comment]
> Have anyone found some solution?
> When i try to get profile: `profile = instaloader.Profile.from_id(L.context, id)`
> while logged in there is no problem
> but as soon as I remove the logging in I get the following error: "`instaloader.exceptions.ConnectionException: JSON Query to graphql/query: HTTP error code 403.`"

Instagram is really unstable since yesterday.
[https://downdetector.com/status/instagram/](https://downdetector.com/status/instagram/)

Better keep trying.

**Comment by seisdr** [comment]
Session file does not exist yet - Logging in.

Fatal error: Login error: JSON decode fail, 400 - Bad Request.
