### ISSUE TITLE
v4.2.5 and v4.2.6 Release Notes duplicated 

### ISSUE THREAD

**Issue by pjw91** [instaloader/instaloader#299]
On Github [Releases](https://github.com/instaloader/instaloader/releases) page, the messages of v4.2.5 and v4.2.6 are identical.

**Comment by aandergr** [comment]
4.2.5 was broken (#293), we shortly released 4.2.6 afterwards to fix the breakage. Hence, 4.2.6 and 4.2.5 addressed the same issues and have the same release notes.

Thanks for pointing this out. I updated the 4.2.6 release notes to avoid further confusion about this.
