### ISSUE TITLE
Get accounts but not a generator

### ISSUE THREAD

**Issue by GolvenLD** [instaloader/instaloader#303]
Hello,

Thank you for your work on this library. Here is my question: I am getting a list of followers and followees to process them later. The way you would normally do it is through profile.get_followers, but this a generator, so for big accounts, (like the instagram one, with over 300m followers) it takes an incredibly long amount of time (I gave up after 4 hours) to create the generator, especially with the delay imposed by Instagram (I am talking about the "too many queries" message). Is there a way to modify structures.py to get the accounts as they are pulled from instagram so they can be written to a file for example, in real time?

Thank you for your help.

**Comment by aandergr** [comment]
I feel like I don't understand this question. Could you provide us a minimal code example to explain the problem?

> but this a generator, so for big accounts, (like the instagram one, with over 300m followers) it takes an incredibly long amount of time (I gave up after 4 hours) to create the generator

The generator is created in no time. `profile.get_followers()` returns immediately. The accounts are pulled from Instagram as you iterate over it. That's the exactly the idea of a generator.
