### ISSUE TITLE
Q: Store profile pictures in 1 directory

### ISSUE THREAD

**Issue by nocturnae** [instaloader/instaloader#308]
Hi,

I'm creating something that downloads profile pictures from the post owners who posted in certain hashtags, but by default, instaloader creates a separate directory for each owner. 

Is there a way to have automatically just put all the profile pictures in one folder, grouping them all together? 

Thanks!

**Comment by aandergr** [comment]
If you want to download only profile pics, you could do:
```
instaloader -l login --dirname-pattern="profilepics" --no-posts profile [profile ...]
```
