### ISSUE TITLE
Low video quality

### ISSUE THREAD

**Issue by leonardofficial** [instaloader/instaloader#311]
Hi,

When using Instaloader to download content from an Instagram account all the pictures are downloaded in high resolution (1080x1080), but the videos are only downloaded in 480x480 or if the video is in 16:9 in 480x720. As far as I know a resolution of 1080x1080 is also possible for videos on instagram. I have tried this on multiple accounts and while being not logged in and being logged in: Always with the same problem.
Is this a limitation from Instagram or somehow fixable?

Thanks!

I'm using Instaloader version 4.2.7

**Comment by starvedhorror** [comment]
There are 1440p pictures & 720p videos available via the mobile API. Unfortunately instaloader works via the web API, and right now it is not possible to get the highest possible quality with it.

**Comment by github-userx** [comment]
@starvedhorror wow, that’s a shame - for archiving purposes it’s always recommended to get the highest quality available :(

Makes a big difference whether a video is HD or SD quality. I always assumed InstaLoader is already retrieving the highest quality of photos and videos available.

**Comment by starvedhorror** [comment]
This is a fairly recent change on instagram's side. [There's a bit more info here.](https://github.com/notcammy/PyInstaStories/issues/14)

**Comment by github-userx** [comment]
Hopefully this can be added soon @aandergr

**Comment by github-userx** [comment]
@starvedhorror check out our recent discussion about getting high resolution videos from Instagram here: https://github.com/rarcega/instagram-scraper/issues/436

**Comment by starvedhorror** [comment]
Not sure why it's closed, since it's as relevant as ever. As it stands, you can only get the higher resolution pictures/videos via the mobile api. Though to be fair it seems that the desktop versions of the videos seems to be using higher quality encoding preset, so it manages to occasionally look better despite the lower resolution.
