### ISSUE TITLE
is there a way to only download post with atleast n likes?

### ISSUE THREAD

**Issue by ishandutta2007** [instaloader/instaloader#315]
Currently I am downloading everything and then writing another script to filter it using the metadata file, it would be great if the cli implicitly supported it.

**Comment by e5150** [comment]
See the [documentation](https://instaloader.github.io/basic-usage.html#filter-posts), `instaloader --post-filter="likes > n" ...`.

**Comment by ishandutta2007** [comment]
Sure, thanks , I have also found out a way via modules here (ie to sort by likes), https://instaloader.github.io/codesnippets.html#top-x-posts-of-user
But the sorting is taking too long for large profiles so we can modify the example to do filter as well.
