### ISSUE TITLE
ModuleNotFoundError Instabot

### ISSUE THREAD

**Issue by saidch1** [instaloader/instaloader#317]
**Describe the bug**
Hello everyone, 

I am trying to launch my instabot. I have windows 10 64 bit , downloaded python 3.7
I keep getting this : 

Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "C:\Users\Said\Downloads\instabot.py-master\instabot_py\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\Said\Downloads\instabot.py-master\instabot_py\instabot.py", line 19, in <module>
    import instaloader
ModuleNotFoundError: No module named 'instaloader'

how can I fix it ? Thank you!

**Comment by aandergr** [comment]
Hi. Most probably you can fix it with `pip install instaloader`.

**Comment by ledgreve** [comment]
@aandergr 
Hello! I am sorry for disturbing you, but I have the same promblem as saidch1. I have installed instaloader using pip and can use the command line to run a simple command, but I need to try to build a script that will give me the username, location name, caption, likes, the UTC and local date, the comments, the amount of likes for the comments, and the username of whoever commented divided by ";" in a txt/ or csv-file. However, when I try to run the code:

`import instaloader

# Get instance
L = instaloader.Instaloader()`

I still get the following error message: 

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-bd65c83a9f8a> in <module>
----> 1 import instaloader
      2 
      3 # Get instance
      4 L = instaloader.Instaloader()

ModuleNotFoundError: No module named 'instaloader'
`

How could I solve this problem? 
Thank you in advance and I apologise for disturbing you, as I see you are busy.

**Comment by HighOctane** [comment]
> @aandergr
> Hello! I am sorry for disturbing you, but I have the same promblem as saidch1. I have installed instaloader using pip and can use the command line to run a simple command, but I need to try to build a script that will give me the username, location name, caption, likes, the UTC and local date, the comments, the amount of likes for the comments, and the username of whoever commented divided by ";" in a txt/ or csv-file. However, when I try to run the code:
> 
> `import instaloader
> 
> # Get instance
> L = instaloader.Instaloader()`
> 
> I still get the following error message:
> 
> `---------------------------------------------------------------------------
> ModuleNotFoundError Traceback (most recent call last)
> in
> ----> 1 import instaloader
> 2
> 3 # Get instance
> 4 L = instaloader.Instaloader()
> 
> ModuleNotFoundError: No module named 'instaloader'
> `
> 
> How could I solve this problem?
> Thank you in advance and I apologise for disturbing you, as I see you are busy.

same here ;(

**Comment by HighOctane** [comment]
> Hi. Most probably you can fix it with `pip install instaloader`.

pip3 install instaloader
beacuse you need a python above 3.5

**Comment by deepakdarakhsha01** [comment]
it is still not working

**Comment by fbwogi** [comment]
Yes I still have the same problem

**Comment by Blackzinkkkj** [comment]
I have this problem in termux Whenever I run a program it appears: 

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/CrackerX/crackerx.py", line 6, in <module>
    import instaloader
ModuleNotFoundError: No module named 'instaloader'

How to solve?

**Comment by ametuku** [comment]
Did you ever find a solution to this?

**Comment by etaka90** [comment]
This can happen when you have two or more versions of Python installed—one has the instaloder module installed, and the other does not. Try running python main.py and python3 main.py.
