### ISSUE TITLE
The @profile flag is not working

### ISSUE THREAD

**Issue by samsepiol59** [instaloader/instaloader#319]
**Describe the bug**
The @profile flag is not working

This is the command I'm running `instaloader @profile --stories --no-captions --no-metadata-json --fast-update --dirname-pattern /home/samsepiol/Downloads/instaloader/{profile} --filename-pattern "{profile} - {date_utc} - {shortcode}" --login=myusername --password=mypassword`

and this is the result I get 
`Loaded session from /tmp/.instaloader-samsepiol/session-myusername.`
`Logged in as myusername.`
`Retrieving followees of profile...`
`Saved session to /tmp/.instaloader-samsepiol/session-myusername.`
`samsepiol@home:~home$`

Am I doing something wrong?

**Comment by tehgarra** [comment]
This is also confusing. It was working for me a few days ago, and then I made a new account and then it stopped working for me

**Comment by tehgarra** [comment]
It's broken for me as well. Worked not too long ago on multiple runs and stopped out of nowhere. I wonder what caused this

**Comment by samsepiol59** [comment]
It's working for me now... weird! I'd love to be able to use timestamps or something similar, so I can move the files somewhere else

**Comment by tehgarra** [comment]
Did you change anything? I still can't get it to work for myself

**Comment by aandergr** [comment]
Thanks for reporting. However, I cannot reproduce this. For me, @profile works fine.
