### ISSUE TITLE
cronjob

### ISSUE THREAD

**Issue by amd1105** [instaloader/instaloader#320]
Hello

I set up a cronjob. However, it says: Command line not found after it has tried to run. Please help?

**Comment by clb92** [comment]
Do ```which instaloader``` in your terminal and use that full path in your cronjob. See if that makes a difference.

**Comment by amd1105** [comment]
# download IG archive every Mon at 1230pm
28 12 * * 2 /Library/Frameworks/Python.framework/Versions/3.7/bin/instaloader sh /Users/MYNAME/Desktop/sort/_archive_instagram/\~shellscript/instaloader_shell_script_w_video.sh

This is what my cronjob looks like. Ignore the note. I changed the time to match today to see if it would run. Now its saying "sh: Profile sh does not exist." I put everything in a shell script btw. Is something on the wrong line?

**Comment by clb92** [comment]
/Library/Frameworks/Python.framework/Versions/3.7/bin/instaloader

So this is your instaloader binary?

Why are you putting a shell script as an argument for instaloader? Do you have any experience with command line at all?

If you want to run the script, just do:

    28 12 * * 2 /Users/MYNAME/Desktop/sort/_archive_instagram/~shellscript/instaloader_shell_script_w_video.sh

I assume your script then runs some instaloader commands?

**Comment by amd1105** [comment]
Thanks. I'll try this. No. I don't have experience with command line. My friend who helped me set this up advised me to use shell script. It wasn't working so I figured this was best place to ask.

**Comment by clb92** [comment]
I think you'll need to learn some of the basics about the command line then (especially the Linux command line).

Do you have a working Instaloader command you would like to run via Cron?

**Comment by amd1105** [comment]
Yeah. I can get the script to work fine if I type it out (or paste) and run it manually. It works no problem. But because I have this big film project I have to do, I don't always have time or memory to remember to run it myself. You're right. I've been reading up about the command line all day.

**Comment by clb92** [comment]
>Yeah. I can get the script to work fine if I type it out (or paste) and run it manually. It works no problem.

In that case, the edited cronjob i posted earlier should work for you.
