### ISSUE TITLE
[Question] load_structure_from_file

### ISSUE THREAD

**Issue by wherethedevildances** [instaloader/instaloader#322]
Hello,

I'm using load_structure_from_file to read saved data into a database, but how can I force it to use the saved info from the file instead of querying instagram again? For example if I do 
P = instaloader.load_structure_from_file(L.context, path)  then P.comments tries to access instagram instead of reading the value from the file. 

Thanks for any help.

**Comment by aandergr** [comment]
Instaloader already uses the data from the file given that the requested data is included in the file. However, the comments are not saved into that file, unless they are very few. You can use the `--comments` flag to download the comments and store them in a separate JSON.
