### ISSUE TITLE
--highlights does not download the highlights profile picture

### ISSUE THREAD

**Issue by thewracl** [instaloader/instaloader#323]
using --highlights I thought it would also download the profile picture for that highlight, I mean the picture of the highlight button itself. It is not downloaded as of the moment.

instaloader profile --highlights

I would assume highlights also would download the picture for it. I would prefer it would download the picture in full resolution but if that is not possible I would also take the 150x150 verson

**Comment by aandergr** [comment]
Thanks for this suggestion. We implemented downloading and saving the highlight cover picture. This feature will be included in version 4.3, and can already be tested in 4.3a2.
