### ISSUE TITLE
scrape users' information automatically

### ISSUE THREAD

**Issue by blrg87** [instaloader/instaloader#324]
I planned to use the Instaloader to collect profiles' followees for my project, and I need thousands of profiles' information, therefore I hope I can get that information automatically. I have written some code to loop the function "profile.get_followees()", and it works. However, this only problem is I always met the '429 - Too Many Requests', so I would like to know except for use 'time.sleep(t)" to slow down the scraping, it there any better way to meet my requirement ( like change IP or proxy)?

**Comment by aandergr** [comment]
When obeying the note at https://instaloader.github.io/troubleshooting.html#too-many-requests, 429 should not occur. 

If you're logged in, the rate limit seems to be per-user, otherwise it's per-IP.

**Comment by blrg87** [comment]
Yes, I found that the rate limit is about both per-user and per-IP, actually, I built a proxy pool and cookie pool to solve the 'request problem', and it really helps. Anyway, thank you for your reply and this great project!

**Comment by Kesavadas** [comment]
Hey blrg87

can you share the code to loop between different proxy IP addresses.
i am trying to do it but unsuccessful.
this will be of great help 
thank you
