### ISSUE TITLE
show that story has been viewed

### ISSUE THREAD

**Issue by pixelcatcher** [instaloader/instaloader#326]
All of my story downloads work fine but I won't be visible to the person who posted the story. 

**Provide us a use case of the feature**
I want to be visible to the profiles of which I downloaded the stories from... just like if i did when watching it on the phone.

**Describe the solution you'd like**
option to be visible or invisible

**Comment by aandergr** [comment]
Instaloader should remain read-only, and not change the online state. Anyway, it's most likely to implement this in an external script using Instaloader's methods.
