### ISSUE TITLE
Download only last 10 posts

### ISSUE THREAD

**Issue by rabe398** [instaloader/instaloader#327]
**Provide us a use case of the feature**
Is it possible to add a feature to only download last 10 posts instead of all posts? 

**Describe the solution you'd like**
To add an argument to enable downloading x last posts.

The reason I want this, is because i'm scraping large list of users, and I only want to download the newest posts. This would help limit API calls

**Comment by aandergr** [comment]
Duplicate of #141.

**Comment by rabe398** [comment]
@aandergr I'm not sure how to do this correctly, since I have no coding experience in python.
Could please guide me how to do it correctly ?
