### ISSUE TITLE
Timeout for HTTP requests

### ISSUE THREAD

**Issue by marty90** [instaloader/instaloader#330]
Hi all,
thank you for maintaining `instaloader`! It is a really great tool!

I am downloading Instagram data using `instaloader` API, in particolare the `get_comments()` method. Sometimes the underlying **HTTP request** (made by the `requests` library) **hangs**, and my script gets **blocked** forever. Is there any simple way to put a timeout to HTTP requests? `requests` support timeout, but currently `instaloader` do not use this feature.

Thank You
Martino

**Comment by lhzwb2008** [comment]
same problem to you

**Comment by lhzwb2008** [comment]
It seems that the --comment/-C parameter can not work any more
