### ISSUE TITLE
How do I download posts made in the previous 30 hours?

### ISSUE THREAD

**Issue by samsepiol59** [instaloader/instaloader#331]
```--post-filter="date_utc <= datetime(2018, 5, 31)"```

I've got this, but I'm not sure how to change it in a way that would allow me to download only posts made in the previous 30 hours from the moment I run the command (so if the command is run on June 2nd at 16:00, I only want to download posts made after June 1st at 10:00.

**Comment by mdPlusPlus** [comment]
Under Linux:

`--post-filter="date_utc <= datetime($(date -d "@$(expr $(date +%s) - 108000)" "+%Y, %m, %d, %H, %m"))"`
