### ISSUE TITLE
Download X last posts

### ISSUE THREAD

**Issue by ghost** [instaloader/instaloader#332]
Thank you guys for doing all of this hard work on instaloader, and I'm sorry for reopening the ticket as I didn't understand what to do as I don't have any python experience.
Could you guide me on what to do? and what code to modify?  

**Provide us a use case of the feature**
Is it possible to add a feature to only download x last posts instead of all posts?

**Describe the solution you'd like**
To add an argument to enable downloading x last posts.

The reason I want this, is because i'm scraping large list of users, and I only want to download the newest posts. This would help limit API calls

**Comment by rabe398** [comment]
Please don't close the ticket

**Comment by samsepiol59** [comment]
I think - -count [count] should do the trick?

**Comment by rabe398** [comment]
Please explain futher @samsepiol59

**Comment by notcammy** [comment]
@rabe398 https://instaloader.github.io/cli-options.html#cmdoption-count
does what you asked for

**Comment by samsepiol59** [comment]
Sorry I forgot about the thread, it doesn't work though - "Applies only to #hashtag, %location id, and :feed."

**Comment by notcammy** [comment]
What about --fast-update? https://instaloader.github.io/cli-options.html#cmdoption-fast-update

**Comment by samsepiol59** [comment]
That's the one, only of you store the pictures locally though! I upload daily to Google Drive so it's not great for me unfortunately (I've tried writing directly to the gdrive mount but it's soooo slow).

I gave up for the moment, and I use instaloader to download stories 6 times a day, instagram-scraper to download posts twice a day (they have a timestamps file, which saves the latest downloaded post for each user and stops when it reaches that, so 100% what I was looking for - akin to youtube-dl archive option) and I upload daily to gdrive during the night!

**Comment by rabe398** [comment]
@notcammy the fast update option makes the script stop at last file downloaded in your local directory.
This is not what i’m looking for

**Comment by rabe398** [comment]
@notcammy 
Let's say i want  to download only last 15 posts:
so I did an ugly hack and added a simple if statement ( on line 1003) that would check if count== 15: then break
but it would only download last 13 posts, any idea why this happens?
![image](https://user-images.githubusercontent.com/37730040/59978323-eabed300-95e3-11e9-82d5-fa8c862236e9.png)

**Comment by rabe398** [comment]
This is the simplest solution i could think of
@samsepiol59 
@notcammy

**Comment by samsepiol59** [comment]
Could it be because there a post with three pictures or something like that?

**Comment by rabe398** [comment]
My test user had posts with carousel photos, each post with -/+ 3 photos.
And it downloaded 13 posts, so no.

**Comment by samsepiol59** [comment]
Maybe it counts the profile pic, plus it breaks at fifteen and doesn't download the 15th?!

**Comment by notcammy** [comment]
Put the counter at the end of the for loop, not at the beginning
