### ISSUE TITLE
Ability to pause the script

### ISSUE THREAD

**Issue by rabe398** [instaloader/instaloader#333]
**Provide us a use case of the feature**
I'm currently having a problem with getting too many requests, and one of the solutions that I think will help as changing the ip every couple of thousands API requests, and to be able to do that without disrupting the script, I'm gonna need to know how to pause it so I can change the ip. 

**Describe the solution you'd like**
Adding a keystroke to pause the script

**Comment by aandergr** [comment]
In a typical bash environment, Ctrl+Z should pause the execution, later it can be resumed with `fg`. This is a feature of your operating system and as such works with every command and does not need to be implemented by us. 

There is an article about that here: https://www.digitalocean.com/community/tutorials/how-to-use-bash-s-job-control-to-manage-foreground-and-background-processes

**Comment by rabe398** [comment]
will try it out, thanks !
