### ISSUE TITLE
In the event that @profile doesn't work, is it possible to print a list of accounts followed by user?

### ISSUE THREAD

**Issue by tehgarra** [instaloader/instaloader#335]
For reasons I don't understand, `@profile` command hasn't worked for in my case for a while and just saves to session.

If the user has a lot of accounts that are followed, wouldn't it make sense to have those accounts stored into a file to be used for passing arguments. I don't know how to work with not being able to use the profile command otherwise

**Comment by shashankTwr** [comment]
Can you show the command that you have been using ??

**Comment by tehgarra** [comment]
> Can you show the command that you have been using ??
i've used this with success before
`instaloader --login username --no-posts --no-profile-pic @profile`

`Loaded session from e:\users\Admin1\appdata\local\temp/.instaloader-admin1/session-username.
Logged in as username.
Retrieving followees of profile...
Saved session to e:\users\admin1\appdata\local\temp/.instaloader-admin1/
session-username.`

I have no issues when logging in and downloading from other profiles.
#319

**Comment by shashankTwr** [comment]
Try python module that gives you flexibility and it is more powerful. Maybe that could help you with your issue. It is working for me. There doesn't seem to be an issue with your command.

**Comment by tehgarra** [comment]
the python module gives the same results unfortunately. i'm not sure what the problem is. i've tried 2 accounts so far and still nothing. I wish I could see what was going on underneath to understand why there's nothing being written

**Comment by tehgarra** [comment]
i'm not exactly sure of how to do that

I understood this part but I'm unsure of where to go from here
`import instaloader

#class Profile(context, node) possibly needed?

L = instaloader.Instaloader()
profile = Profile.from_username(L.context, USER)
print("{} follows these profiles:".format(profile.username))
for followee in profile.get_followees():
    print(followee.username)`

`Traceback (most recent call last):
  File "E:/instaloader-master/test/main.py", line 6, in <module>
    profile = Profile.from_username(L.context, USER)
NameError: name 'Profile' is not defined

Process finished with exit code 1
`

**Comment by shashankTwr** [comment]
```
import instaloader
from instaloader import Instaloader, Post, Profile, load_structure_from_file
from datetime import datetime
from itertools import dropwhile, takewhile
L = instaloader.Instaloader()
L.interactive_login('your_way_of_login')      
# Your preferred way of logging in:
profile = instaloader.Profile.from_username(L.context, 'id_username_in')
```
Perform the operation now :) also so Profile is the class and you'd have to import profile too. Hope it works now.

**Comment by tehgarra** [comment]
Thank you! That got everything needed. I'll be studying the documentation and python quite a bit more in the meantime
