### ISSUE TITLE
IMPORTANT: Pictures are missing from the feed

### ISSUE THREAD

**Issue by thewracl** [instaloader/instaloader#336]
**Describe the bug**
Posts from the feed of a private user will not be downloaded. I only noticed it now on one account be the problem could be sign of a larger problem. Instagram-Scraper the problem also

**To Reproduce**
just a normal instaloader profile with the user and password to use (can't remember the exact syntax as I'm writing that from memory

**Comment by aandergr** [comment]
Too incomplete...
