### ISSUE TITLE
how to save just photo links?

### ISSUE THREAD

**Issue by zero59** [instaloader/instaloader#338]
how to download just photo's file link?

I want to just download photo's link! but I don't know which syntax using for this!

**Comment by shashankTwr** [comment]
Are you looking for the link of a particular post ?? 
```
shortcode
Media shortcode. URL of the post is instagram.com/p/<shortcode>/.
``` 
This is the thing you're looking for. To get all the links you can do this I guess.
```
mediaLink=[]
for post in profile.get_posts():
   mediaLink.append(post.shortcode)
for media in mediaLink:
   media='https://instagram.com/p/'+media+'/' 
   print(media)
```
This media is the link you're looking for.

**Comment by zero59** [comment]
tnq 
no i looking for "display_url" without downloading photo.

```
display_url | "https://instagram.fevn1-3.fna.fbcdn.net/vp/******************************0a/5DA62973/t51.2885-15/e15/1389136_100589160276015_1669077837_n.jpg?_nc_ht=instagram.fevn1-3.fna.fbcdn.net"
-- | --

```

**Comment by shashankTwr** [comment]
Sure then you'd need to use the ``` url ``` attribute of the post instead of shortcode
If you are using python
```
for post in profile.get_posts():
   mediaLink.append(post.url)
   print(post.url)
```
This will store all the media_url for a post in mediaLink list without downloading anything.

 If you want to do it with the command line you'd need to use the ```--no-pictures --no-videos ``` this will not download any pictures and videos then you can go individually to the json file and you will see that there's a display_url attribute which saves the link

**Comment by zero59** [comment]
> Sure then you'd need to use the `url` attribute of the post instead of shortcode
> If you are using python
> 
> ```
> for post in profile.get_posts():
>    mediaLink.append(post.url)
>    print(post.url)
> ```
> 
> This will store all the media_url for a post in mediaLink list without downloading anything.
> 
> If you want to do it with the command line you'd need to use the `--no-pictures --no-videos ` this will not download any pictures and videos then you can go individually to the json file and you will see that there's a display_url attribute which saves the link

Tnq so much!
