### ISSUE TITLE
Cannot use -post

### ISSUE THREAD

**Issue by ScribbleGhost** [instaloader/instaloader#339]
**Describe the bug**
This is most probably NOT a bug. I just cannot get my head around how to use the new feature `-post` and I really just need some clarification.

The documentation says:

> -post
> The single post with the given shortcode. Must be preceeded by -- in the argument list to not be mistaken as an option flag.

**To Reproduce**

What I am doing is using CMD in Windows and running `instaloader +args.txt` and in the file `args.txt` I have:

```
-post --By-GvWDncfq
```

**Expected behavior**
Expected instaloader to download the single post with the post shortcode `By-GvWDncfq`

**Error messages and tracebacks**
I just get the `instaloader --help`

**Instaloader version**
4.2.8

**Additional context**
Perhaps a working example on how to use `-post` to download a single post would help?

**Comment by pjw91** [comment]
The file should be:
```
--
-By-GvWDncfq
```
