### ISSUE TITLE
Using a "profiles.txt" input, skip non-existing accounts

### ISSUE THREAD

**Issue by m4gnet98** [instaloader/instaloader#340]
> **Provide us a use case of the feature**

This might be a bug, I'm not sure. Anyway.

While using a file with a list of accounts as an input, a non-existing etc account stops the script, and then exits.
My idea is simply a "--skip-broken" or something, to keep running the script, just without those accounts.

> **Describe the solution you'd like** 

A command to skip broken or non-existent accounts.

> **Describe alternatives you've considered**

Removing accounts from the list.

> **Additional context**

I'm running the script as a scheduled task in Windows, so I can't keep my eyes on it all the time. Sometimes I've found a couple of instances of Instaloader in the task manager. Running Instaloader from the CLI then shows an account in my list is no longer on Instagram, and it locks up.

**Comment by aandergr** [comment]
I cannot reproduce this - Instaloader skips nonexisting accounts with a message that they do not exist.
