### ISSUE TITLE
Question about using a .txt file with usernames as input

### ISSUE THREAD

**Issue by github-userx** [instaloader/instaloader#343]
I have usernames.txt like this:

    # British Singers
    edsheeran
    # Actors
    halleberry

How can I use the txt file as input while keeping my descriptions after the # symbol?

    Python3 instaloader.py +usernames.txt

Gives me errors.

**Comment by mdPlusPlus** [comment]
Under Linux: `grep -v "^#" argsfile.txt | xargs -t ~/.local/bin/instaloader`

**Comment by juanbrena** [comment]
> Under Linux: `grep -v "^#" argsfile.txt | xargs -t ~/.local/bin/instaloader`

That's one way but I would think instaloader should accept a txt file. Is it in the works?

**Comment by aandergr** [comment]
No, comments in the arguments text file are not supported.
