### ISSUE TITLE
Error in Checkpoint when using --login command

### ISSUE THREAD

**Issue by asnahu** [instaloader/instaloader#344]
Instaloader Version: 4.2.8/MacOS Mojave

The following command will lead to a checkpoint link, and can not download images from instagram:

`instaloader ovors --login='xxxxxx@gmail.com'`

Every time run the upper code will generate a new check point link.

> Session file does not exist yet - Logging in.
Enter Instagram password for 'xxxxxx@gmail.com:
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/xxxxxxxxxx/C9HqjI1SEf/, follow the instructions, then retry

If no `login` command, it will retrieve a JSON item list.

how to resolve this problem?  Thx!

**Comment by dreisix** [comment]
Do you manage to resolve this problem? I still can't login to my account.
