### ISSUE TITLE
How to save the location for every post? Maybe also the first comment?

### ISSUE THREAD

**Issue by RualLozun** [instaloader/instaloader#346]
Hi all! for full disclosure, I have no idea how I got here, I probably shouldn't even be here, this is above my skills. But I happen to be quite amazed by the potential of this tool! so as a total beginner I am wondering about the following:
1.
 --post-metadata-txt="{location} location" doesn't work. Is there any other function besides {location} to extract the location metadata of a given post?
2.
How do you guys read the json files? with excel? the power query thing? And how about the json.xz? I guess I am not supposed to unzip all the files one by one no? These zipped json files contain the location info, but it's  a bit too hard to get, there must be an easier way...
3.
Is it possible to scrape only the first comment of every post? or would that have the same number of API requests as scraping them all? often the hashtags of the post are found in the first comment.

Thank you in advance for any guidance in any of these issues!

**Comment by Syl0pt** [comment]
In order to get location (if available) you would need to do --geotags. I'm pretty sure the {location} part of --post-metadata refers to which folder you want your metadata saved in. It doesn't have anything to do with GPS locations. That would be --geotags.

**Comment by RualLozun** [comment]
> 
> 
> In order to get location (if available) you would need to do --geotags. I'm pretty sure the {location} part of --post-metadata refers to which folder you want your metadata saved in. It doesn't have anything to do with GPS locations. That would be --geotags.

Hi Syl0pt! Thanks for answering. Geotags saves the location as a google maps link. So you would have to follow the link with the browser and find out where that is. It is a bit troublesome... I was hoping I could get the location in a txt straight away. In the json file that's zipped inside the json.xz file the location appears like this: "location":{"id":567008008,"name":"Gal\u00e1pagos","slug":"galapagos"

**Comment by Showmaster3000** [comment]
You can use --no-compress-json if you do more like uncompressed json files instead of the xz ones.
See: https://instaloader.github.io/cli-options.html#cmdoption-no-compress-json

**Comment by RualLozun** [comment]
> 
> 
> You can use --no-compress-json if you do more like uncompressed json files instead of the xz ones.
> See: https://instaloader.github.io/cli-options.html#cmdoption-no-compress-json

oh I see, that's great! That will save me quite some time. Much appreciated Showmaster

**Comment by shashankTwr** [comment]
If you can work with the python module it provides far more options than the command line and is very powerful.
1) for scraping the first comment you can probably just save the comment with the minimum timestamp value and for a single user, this will depend on the number of comments and posts and usually, the number of posts affects much more than the comments as I found by my personal experience.  
2)If you make use of location property in the python module you'd probably get the location tags if they're specified in the post.

**Comment by RualLozun** [comment]
> 
> 
> If you can work with the python module it provides far more options than the command line and is very powerful.
> 
>     1. for scraping the first comment you can probably just save the comment with the minimum timestamp value and for a single user, this will depend on the number of comments and posts and usually, the number of posts affects much more than the comments as I found by my personal experience.
>        2)If you make use of location property in the python module you'd probably get the location tags if they're specified in the post.

Thanks ShashankTwr! That's a very helpful answer. I will do some tests. I am learning more and more stuff, slowly... but I enjoy it. I got a pretty decent script working already : )
