### ISSUE TITLE
download Instagram photos with captions and comments using a .csv file with URLs

### ISSUE THREAD

**Issue by juliavassey** [instaloader/instaloader#347]
**Describe the bug**

I'm trying to download Instagram images with captions using a .csv file with URLs to images. The code I am trying to use does not seem to be correct and gives a syntax error:

SyntaxError: invalid syntax

**To Reproduce**

Two code that I tried:

instaloader --post --gender-detection-keras-master/detect_gender_url_final.py -i recalculatedejuice.csv

The .py file contains the code, including url in enumerate to download the images using the URLs in the .csv

**Expected behavior**

Expect all images with captions to be downloaded as per my .csv file

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

**Instaloader version**
`instaloader --version` output.

File "<ipython-input-12-4c12d39fc324>", line 1
    instaloader --post --gender-detection-keras-master/detect_gender_url_final.py -i recalculatedejuice.csv
                                                                                                      ^
SyntaxError: invalid syntax

**Additional context**

installed pip-19.1.1

**Comment by aandergr** [comment]
Your invocation does not make any sense at all. There is no `-i` flag, there is no support for reading csv files, and you cannot pass other python scripts as argument to Instaloader. Please read our documentation to see how Instaloader is invocated.
