### ISSUE TITLE
After renaming of an account, instaloader does not move old files to new one

### ISSUE THREAD

**Issue by jlntrt** [instaloader/instaloader#348]
**Describe the bug**
On my server, I run instaloader in a period of time with the following command:
`instaloader --sessionfile ../session --login=x --password=x --stories --fast-update --count=100 --commit-mode --no-profile-pic $(dir -1 | shuf)`

Today I saw in the log file the following situation.

1. IG-Account "A" changed its name to "B"
2. Instaloader created a folder "B" containing the "id" file and the current story of this account
3. Instaloader keeps the folder "A" with all existing images and stories
4. Next run, Instaloader logs: `
Trying to find profile A using its unique ID 123456.
Profile A has changed its name to B.
`

Can anyone reproduce it?

**To Reproduce**
Create a folder named as an IG user. Run instaloader with the command above. Rename the IG user to any available user name. Run instaloader again.

**Expected behavior**
All steps like described above in addition moving all files to the new created folder "B" and remove the old folder "A".

**Error messages and tracebacks**
No errors were shown up.

**Instaloader version**
4.2.8

**Additional context**
No additional information. If some other information needed, please ask. :)

**Comment by aandergr** [comment]
We cannot reproduce this. In our case, after renaming a profile folder and running Instaloader again with the folder's name as parameter, Instaloader renames the folder back to the profile's current name as expected.

**Comment by jlntrt** [comment]
Hi @aandergr, thank you for your response. In my case, this issue doesn't appear for a while since I opened this ticket. It seems to be an unclear case. I guess we can close it. Thanks! :)
