### ISSUE TITLE
Never ending "Too many queries in the last time. Need to wait"

### ISSUE THREAD

**Issue by BabyRdx** [instaloader/instaloader#349]
When trying to download a large profile the program hits a point where it produces the error "Too many queries in the last time. Need to wait " but no matter how long you wait it repeats itself.

An example of this

> [ 52/???] sydwilder/:tagged/2019-06-21_18-45-42_UTC_1.jpg exists sydwilder/:tagged/2019-06-21_18-45-42_UTC_2.jpg exists [What?s your motivation? ?? Wha?] unchanged geo 
> Too many queries in the last time. Need to wait 16 seconds, until 01:24.
> Too many queries in the last time. Need to wait 576 seconds, until 01:33.
> Too many queries in the last time. Need to wait 16 seconds, until 01:34.
> Too many queries in the last time. Need to wait 19 seconds, until 01:34.

These have continued for over 24hours with no new downloads.

For example I get this with:
`instaloader --comments --geotags --tagged --stories --highlights sydwilder`

**Expected behavior**
I would expect the program  to start grabbing new files after X time has passed.

**Instaloader version**
4.2.8

**Additional context**
I am not running Instagram on any other browsers, tablets, phones or devices of any type.

**Comment by Showmaster3000** [comment]
The problem is your parameter --comments
You try to download a large profile, so every post has a huge amount of comments to download which hits the limit even more often.

**Comment by BabyRdx** [comment]
Ahh thank you. So I should just persevere?

**Comment by shashankTwr** [comment]
I will suggest you do it in chunks like divide it in dates so that your work doesn't get lost or you'd have to restart it. For example, You could download posts of a large profile for 5 days and if this doesn't encounter an error you could continue it and if it does you can break it down for a day or so. Currently in your case, If it hits the limit and you'd restart it I guess that it will restart in the command line which will be quite hectic so python module should be your go-to approach if you're working with larger profiles.

**Comment by aandergr** [comment]
Because of rate controling, this is exactly the expected behavior. Your log indicates that everything works fine, Instaloader *does* grab continuously new data, but in a slow manner to not hit Instagram's rate limits. Also see https://instaloader.github.io/troubleshooting.html#too-many-requests

**Comment by thewasta** [comment]
And with Python? How do I have to do?
I'm doing this
```
for post in profile.get_posts():
    if one_week < post.date_local:
        L.download_post(post, target=profile.username)
```
Thanks
