### ISSUE TITLE
instaloader processes never/seldom end themselves

### ISSUE THREAD

**Issue by feraxis** [instaloader/instaloader#350]
**Describe the bug**
Instaloader generally works as intended, but the process itself never(/seldom) quits, so I have multiple idle processes.

**To Reproduce**
crontab line: `*/1 * * * * /media/x/y/instaloader-script.sh`
instaloader-script.sh: `cd /media/x/y/z && pip3 install --upgrade instaloader && /usr/local/bin/instaloader +'/media/x/y/z/profiles.txt'`

**Expected behavior**
Every process stops itself after finishing its work.

**Instaloader version**
4.2.8

**Additional context**
As I am scraping the profiles to an external drive, I always have to manually stop all the open processes before I can unmount that drive.
I changed the execution time from 3 hours to 10 minutes earlier today and after seeing it works to 1 minute afterwards, now I get a lot of open processes, but even with 3 hours I always had 2 to 3 open processes all the time.
These processes were open even when I had the login challenge for about 10 days two weeks ago without noticing, so I guess it has nothing to do with the time the script needs to scrape all the profiles.
![instaloader-1](https://user-images.githubusercontent.com/28827902/61006938-e0cefb00-a36b-11e9-812f-bf71eab818dd.png)

**Comment by clb92** [comment]
Do you have output logs from these processes?

One solution could be to put a time limit on the processes. In most Linux distros you can use the GNU Timeout utility:

    */1 * * * * timeout 3h /media/x/y/instaloader-script.sh

Beware that the script is now forcefully killed once 3 hours have passed. This may lead to corrupt data, if it wasn't done writing whatever!

I highly recommend not blindly doing this! Instead, log the output of Instaloader and find out the source of the problems.

**Comment by feraxis** [comment]
Well, I guess it is related to the VPN I use, it is delaying the script because of too many requests and therefore needs several hours to complete the list of profiles.
