### ISSUE TITLE
download followers list

### ISSUE THREAD

**Issue by hephaestus33** [instaloader/instaloader#353]
how we can download followers list?

**Comment by akalinhi** [comment]
import instaloader
from instaloader import Profile

username="username"
password="password"

L = instaloader.Instaloader()
L.login(username, password)

target = 'nickname'

profile = instaloader.Profile.from_username(L.context, target)

file = open(target + '_followers.txt', "a+")

for followers in profile.get_followers():
    username = followers.username
    file.write(username + "\n")
    print(username)
file.close()

print("***************************************************************************************** \n")



If I understand clearly you can use that python codes.
