### ISSUE TITLE
Creating a Profile instance. 

### ISSUE THREAD

**Issue by gracekull21** [instaloader/instaloader#359]
The Python documentation of Instaloader:
When using the Profile class methods such as Profile.from_username(L.context, USERNAME), I noticed that you need to use instaloader.Profile instead of Profile. Otherwise, I would get an error saying that "Profile" is not defined.

**Comment by aandergr** [comment]
With basic knowledge of Python and how modules work, it is obvious that classes have to be imported before using them.

You can use
```python
from instaloader import Instaloader, Profile

L = Instaloader()
profile = Profile(L.context, "profile")
```
or
```python
import instaloader

L = instaloader.Instaloader()
profile = instaloader.Profile(L.context, "profile")
```
