### ISSUE TITLE
Download tagged stories from given profile

### ISSUE THREAD

**Issue by blabla123ble** [instaloader/instaloader#360]
Given a downloaded storie, the application could see, as tagged (maybe im understanding tagging (:tagged) in a different way) could go to the profile to the person that marked the one that im downloading the stories and download from the original source. If the profile that you are trying to download the stories that the profile that im following is private, it could return something like "private profile, cannot download tagged stories" and if the profile is public, it would skip all stories that has not the user that im following and just download the ones that it is tagged. 

I could do this manually but checking a big number of profiles is quiet time consuming.

I'm not someone experiencied with coding but I could take a look and try to see if there is any workaround to this situation other than going to the folder of each profile and see if they got marked.

**Comment by aandergr** [comment]
Interesting idea, but I don't see how to obtain this information at the moment.
