### ISSUE TITLE
Get Photo/Video from Public Post Link

### ISSUE THREAD

**Issue by cyberboysumanjay** [instaloader/instaloader#361]
**Query:**
Suppose I have a public post link like [https://www.instagram.com/p/B0FgQaZh8Kq/](https://www.instagram.com/p/B0FgQaZh8Kq/) and I want to download this using instaloader.

Can I do that?

**What I need**
A method to download from post link will be helpful.

**Thanks**

**Comment by IvanMazzoli** [comment]
I was searching the same thing, and I've found out how to do it.
First, for the given URL, you'll need to filter out the unnecessary parts and obtain the **shortcode** for the post. In your case the shortcode is `B0FgQaZh8Kq`.

Then you get the post associated with that shortcode using `Post.from_shortcode(context, shortcode)`.

Please take a look to the docs: https://instaloader.github.io/as-module.html#instaloader.Post.from_shortcode

**Comment by cyberboysumanjay** [comment]
Thanks for your help. I got this working!
