### ISSUE TITLE
Error, directory not found while scraping highlits and its texts folders

### ISSUE THREAD

**Issue by blabla123ble** [instaloader/instaloader#363]
I'm using this arguments. After this error, it terminates the execution

instaloader.exe -l AAA -p BBB --highlights --tagged --no-posts --no-profile-pic --no-video-thumbnails --no-captions --no-metadata-json @AAA

Retrieving highlights "#amor meu..." from profile ZZZ
[  1/ 13] ZZZ﹨#amor meu.../2019-07-06_16-16-59_UTC.jpg Traceback (most recent call last):
  File "__main__.py", line 442, in <module>
  File "__main__.py", line 438, in __main
  File "__main__.py", line 413, in main
  File "__main__.py", line 189, in _main
  File "instaloader\instaloader.py", line 993, in download_profiles
  File "instaloader\instaloader.py", line 49, in call
  File "instaloader\instaloader.py", line 651, in download_highlights
  File "instaloader\instaloader.py", line 585, in download_storyitem
  File "instaloader\instaloader.py", line 67, in call
  File "instaloader\instaloader.py", line 239, in download_pic
  File "instaloader\instaloadercontext.py", line 529, in get_and_write_raw
  File "instaloader\instaloadercontext.py", line 495, in write_raw
FileNotFoundError: [Errno 2] No such file or directory: 'ZZZ﹨#amor meu.../2019-07-06_16-16-59_UTC.jpg'
[732] Failed to execute script __main__

Version 4.2.8

Also, the directory where the error is indicating, doesnt include the picture that it tries to download. So maybe its trying to mark as downloaded a picture that wasnt even downloaded?

**Comment by blabla123ble** [comment]
So, the folder in which it occurs this error, is like, the highlight is named "something something...", those 3 dots at the end werent created at the folder in which they were supposed to be named together. I tried to manually put a picture there with the same name that it says "2019-07-06_16-16-59_UTC.jpg" but its actually searching for the directory. Also, when I tried to rename the folder with the 3 dots at the end, file explorer wouldnt me do it, it would just wipe it out and get back without the dots. Now, I dont know if this is a behaviour from the program or a bug in windows explorer.

**Comment by blabla123ble** [comment]
Can this be edited in a way that when downloading such highlights, the ones that ends with such special characters that Win32 doesnt like to work with, to add an blank character? Like char(128)?

**Comment by blabla123ble** [comment]
I came back and read some old threads claiming that -q would solve some of this issues but still getting the same error. The folder cant be created because of those 3 dots at the end. My solution would be to add a blank character at the end of the folder creation name, this way it works.

**Comment by blabla123ble** [comment]
@aandergr could you take a look?

**Comment by aandergr** [comment]
Duplicate of #263.
