### ISSUE TITLE
KeyError: 'graphql' when Anonymously Downloading Posts by Location

### ISSUE THREAD

**Issue by ugrosha** [instaloader/instaloader#376]
**Describe the bug**
HTTP redirect from https://www.instagram.com/explore/locations/236717556/ to https://www.instagram.com/accounts/login/?next=/explore/locations/236717556/
Traceback (most recent call last):
  File "milf.py", line 34, in <module>
    L.download_post(post, target='#memory')
  File "C:\Users\Асус\lib\site-packages\instaloader\instaloader.py", line 490, in download_post
    if self.download_geotags and post.location:
  File "C:\Users\Асус\lib\site-packages\instaloader\structures.py", line 418, in location
    params={'__a': 1})['graphql']['location']
KeyError: 'graphql'

**To Reproduce**

Instaloader command line

**Expected behavior**

I'd expect it to download the files after the redirect. These files can be skipped. 
**Error messages and tracebacks**
KeyError: 'graphql'

**Instaloader version**
4.2.8

**Additional context**

**Comment by sleiter88** [comment]
Idem to me, when i try to get the location of post now the throw me that error.

**Comment by aandergr** [comment]
Thanks for reporting! Instagram removed the option to explore locations without being logged in. Hence, `--login` is now required for downloading posts by location.

**Comment by github-userx** [comment]
Same error happened to me when I downloaded a users posts anonymously, @aandergr .

But I think I had geotags for the posts enabled,

**Comment by andrewtmarvin** [comment]
Anyway around this without logging in?

**Comment by joalro** [comment]
I'm donwloading without geotags, and I'm just using the download post method but it is sitll breaking. 

I just need the posts, no additional info.  I've tried putting in as many parameters to avoid any additional info, but I'm still getting errors.  Any advice?
