### ISSUE TITLE
Instaloader _main_ error

### ISSUE THREAD

**Issue by FarewellAngelina** [instaloader/instaloader#383]
**Describe the bug**
Instaloader won't start, it fails right after  "authenticated" (login) with the following error:

Traceback (most recent call last):
  File "__main__.py", line 442, in <module>
  File "__main__.py", line 438, in __main
  File "__main__.py", line 413, in main
  File "__main__.py", line 92, in _main
  File "instaloader\instaloader.py", line 425, in login
  File "instaloader\instaloadercontext.py", line 223, in login
KeyError: 'authenticated'
[21888] Failed to execute script __main__

I've tried the previous 5 versions, still same error, i'm on 4.2.8 (latest)

**To Reproduce**
/c instaloader.exe --login  --password --fast-update --stories userprofile

**Instaloader version**
4.2.8
EDIT: This also happens in 4.2.9

**Additional context**
Stopped working about 20h for me, i know nothing about php nor web dev so i can't help, appreciate your time in making this for free.

**Comment by aandergr** [comment]
> **To Reproduce**
> /c instaloader.exe --login --password --fast-update --stories userprofile

This is not a syntactically correct Instaloader invocation. After `--login` you have to provide your username, after `--password` (which we discourage to use), you have to provide your password.

**Comment by FarewellAngelina** [comment]
> 
> 
> > **To Reproduce**
> > /c instaloader.exe --login --password --fast-update --stories userprofile
> 
> This is not a syntactically correct Instaloader invocation. After `--login` you have to provide your username, after `--password` (which we discourage to use), you have to provide your password.

...

Well, i do provide those two things, obviously i removed them before posting here, didn't feel the need to dummy down the command by putting "FarewellAngelina" "Farewell_PW" ... this is not an issue with my syntax, this is an issue with instaloader as i've used proxies and tested other things.

**Comment by dausruddin** [comment]
I am having the same issue
