### ISSUE TITLE
Only download real posts?

### ISSUE THREAD

**Issue by TarekSalama** [instaloader/instaloader#386]
I have noticed that when downloading a profile, there were extra files like JSON files, and an image for each video. Is there a way to not download the extra files?
Also, is it possible to name each video/image with whatever the user named it as (i.e description/title)?

**Comment by XxbrandoXx** [comment]
@TarekSalama You'll want to use : 
--no-captions
--no-metadata-json
--no-video-thumbnails
See more here : https://instaloader.github.io/cli-options.html
I don't know any option to name each post with what the user wrote. See what you can do for name here : https://instaloader.github.io/basic-usage.html#filename-specification
