### ISSUE TITLE
Problem downloading profile's posts while unauthenticated

### ISSUE THREAD

**Issue by loganstartoni** [instaloader/instaloader#387]
Your question here...
I noticed yesterday that one of the scripts I have to download posts while unauthenticated does not work anymore. Instead it says that the profile is not able to be found. It is a public profile and before the "outage" yesterday things were working normally, and I was able to download the public posts while unauthenticated.

Any Suggestions on what I may have to change to fix this issue?

I am using the most recent release 4.2.9.

**Comment by Showmaster3000** [comment]
Looks like its the same problem as in #381

**Comment by loganstartoni** [comment]
I looked at that issue before I submitted and it seemed like the behavior exhibited was different but I see how it could be tied to it now that I look a little closer. 

Here is the last block of the traceback in case it provides more context:
`  return self._metadata('biography')
  File "/usr/local/lib/python3.7/site-packages/instaloader/structures.py", line 541, in _metadata
    self._obtain_metadata()
  File "/usr/local/lib/python3.7/site-packages/instaloader/structures.py", line 532, in _obtain_metadata
    raise ProfileNotExistsException('Profile {} does not exist.'.format(self.username)) from err
instaloader.exceptions.ProfileNotExistsException: Profile PROFILE does not exist.`

**Comment by andrewtmarvin** [comment]
I'm getting the same issue with my script. Weirdly enough, it works in my local dev environment but not on my server.
