### ISSUE TITLE
Incorrect ProfileNotExistsException when scan is rate limited: redirect to https://www.instagram.com/accounts/login/

### ISSUE THREAD

**Issue by corpone** [instaloader/instaloader#388]
**Describe the bug**
IG now begins to redirect to login page when scan limit is exhausted.

This shows up as:

`HTTP redirect from https://www.instagram.com/<profile>/ to https://www.instagram.com/accounts/login/`

**To Reproduce**
Scan too fast.

**Instaloader version**
Latest.

**Additional context**

Solution:
1. Special case redirect to `https://www.instagram.com/accounts/login/` on scan in https://github.com/instaloader/instaloader/blob/a88316224bab83603e0652265ef1558f778905c8/instaloader/instaloadercontext.py#L359

**Comment by goker67** [comment]
I didn't understand clearly that solution. When I attempt to scrape, I still take the HTTP redirect message. How can I overcome to it?

**Comment by marty90** [comment]
+1

**Comment by marty90** [comment]
it appears like there is a new rate limit in scraping `https://www.instagram.com/<profile>/` pages :(

**Comment by hgkmaxymus** [comment]
> it appears like there is a new rate limit in scraping `https://www.instagram.com/<profile>/` pages :(

Yeah. When logged in, the rate is greater than anonymous.

Weirdly enough, I didn't scrap anything yesterday and today I still had the same issue. Trying to check some profiles while logged out redirects me to the login webpage (using Chrome Private Browsing).

I think Instagram is having some massive server issues and is limiting everything now. I hope it is temporary, but who knows...

**Comment by psylenced** [comment]
I tried the pull request last night and doesn't seem to be working.

**Comment by aandergr** [comment]
Thanks for reporting and for your pull request!

I could not reproduce this behavior, in my experiments I always got the regular 429 response when exceeding the rate limit. I merged your pull request anyway, since it looks very good and doesn't introduce any side effects. However, for now we defer releasing 4.2.10 just with this fix included, since we do not see enough evidence yet that this bug still exists.

**Comment by marty90** [comment]
Thank You.
It would be interesting to understand some further details about the new policies of Instagram.

**Comment by corpone** [comment]
@aandergr not ideal to share research on this in a public forum, but I have a good idea of the factors that cause it. 

While we're on this topic, one suggestion I'd make is to add variable or exponential backoff and acceleration to the rate limiter. It's not capturing a lot of variables that I'm aware of, so picking fixed numbers that work in two scenarios will not be optimal for many users.

**Comment by alrifqi** [comment]
i just tried to add proxy into the script and it's working. the code like this:
os.environ['http_proxy'] = 'http://proxyurl'

**Comment by goker67** [comment]
It doesn't seem to be effective @alrifqi . A few hours ago, instaloader run again for a few minutes but now, crashed again.

**Comment by nOOBIE-nOOBIE** [comment]
The  redirect is still happening when downloading posts.

```
from datetime import datetime
from itertools import dropwhile, takewhile

import instaloader

L = instaloader.Instaloader()

posts = L.get_hashtag_posts('urbanphotography')
# or
# posts = instaloader.Profile.from_username(L.context, PROFILE).get_posts()

SINCE = datetime(2015, 5, 1)
UNTIL = datetime(2015, 3, 1)

for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
    print(post.date)
    L.download_post(post, '#urbanphotography')

```


Error

```
#urbanphotography/2019-10-21_06-29-36_UTC.jpg [11. Regarde comme il faut bea…] 
HTTP redirect from https://www.instagram.com/explore/locations/213097372/ to https://www.instagram.com/accounts/login/?next=/explore/locations/213097372/
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/dist-packages/instaloader/instaloader.py", line 490, in download_post
    if self.download_geotags and post.location:
  File "/usr/local/lib/python3.6/dist-packages/instaloader/structures.py", line 418, in location
    params={'__a': 1})['graphql']['location']
KeyError: 'graphql'

```

**Comment by cofalcao** [comment]
Hey guys, does anybody solved this issue?

**Comment by rosefun** [comment]
> i just tried to add proxy into the script and it's working. the code like this:
> os.environ['http_proxy'] = 'http://proxyurl'

Can you provide `proxyurl` available?

**Comment by sabant** [comment]
It worked again for me after changing the path from https://www.instagram.com/ to https://api.instagram.com. not sure for how long...

**Comment by marty90** [comment]
@sabant , which is the exact URL you use?
