### ISSUE TITLE
HTTP redirect from https://www.instagram.com/username/ to https://www.instagram.com/accounts/login/

### ISSUE THREAD

**Issue by goker67** [instaloader/instaloader#390]
When I attempt to scrape who have username such as "username" I see a message like
"HTTP redirect from https://www.instagram.com/username/ to https://www.instagram.com/accounts/login/" and nothing happens.
What is this exactly and how can I fix it?

**Comment by corpone** [comment]
@goker67 Duplicate of https://github.com/instaloader/instaloader/issues/388

**Comment by goker67** [comment]
When rate limit exceeded, how long does it take? How I long should I wait before another scraping attempt?

**Comment by aandergr** [comment]
Duplicate of #388.
