### ISSUE TITLE
429 redirect PR does not work

### ISSUE THREAD

**Issue by psylenced** [instaloader/instaloader#392]
I was testing the PR https://github.com/instaloader/instaloader/pull/389 and found it doesn't work.

**This is the behaviour I'm experiencing:**

I'm attempting to download about 900 logged-in profiles.

The download process from this app (from my understanding) consists of 2 parts:

1 - pre-processing which detects profile IDs with renames, etc.
2 - the actual download images/videos part.

The 429 issue starts occurring in the pre-processing part, this happens about half way through. Every profile detection after that point will error out with a 429, meaning they will never be marked as "valid" for the downloading part.

**Possible fix:**
What I think needs to be done to fix this is by adding a 429 timeout to the profile pre-processing. 

From the looks of it, it simply tries each profile 3 times after each other, errors out and moves on to the next.

**Example log below:**

# Pre-processing
```
JSON Query x****/: 429 Too Many Requests [retrying; skip with ^C]
JSON Query x****/: 429 Too Many Requests [retrying; skip with ^C]
x****: JSON Query x****/: 429 Too Many Requests
JSON Query x****/: 429 Too Many Requests [retrying; skip with ^C]
JSON Query x****/: 429 Too Many Requests [retrying; skip with ^C]
x****: JSON Query x****/: 429 Too Many Requests
JSON Query x****/: 429 Too Many Requests [retrying; skip with ^C]
JSON Query x****/: 429 Too Many Requests [retrying; skip with ^C]
x****: JSON Query x****/: 429 Too Many Requests
JSON Query y****/: 429 Too Many Requests [retrying; skip with ^C]
JSON Query y****/: 429 Too Many Requests [retrying; skip with ^C]
y****: JSON Query y****/: 429 Too Many Requests
JSON Query y****/: 429 Too Many Requests [retrying; skip with ^C]
JSON Query y****/: 429 Too Many Requests [retrying; skip with ^C]
y****: JSON Query y****/: 429 Too Many Requests
JSON Query z****/: 429 Too Many Requests [retrying; skip with ^C]
JSON Query z****/: 429 Too Many Requests [retrying; skip with ^C]
z****: JSON Query z****/: 429 Too Many Requests
JSON Query z****/: 429 Too Many Requests [retrying; skip with ^C]
JSON Query z****/: 429 Too Many Requests [retrying; skip with ^C]
z****: JSON Query z****/: 429 Too Many Requests
JSON Query z****/: 429 Too Many Requests [retrying; skip with ^C]
JSON Query z****/: 429 Too Many Requests [retrying; skip with ^C]
z****: JSON Query z****/: 429 Too Many Requests
JSON Query z****/: 429 Too Many Requests [retrying; skip with ^C]
JSON Query z****/: 429 Too Many Requests [retrying; skip with ^C]
z****: JSON Query z****/: 429 Too Many Requests
JSON Query z****/: 429 Too Many Requests [retrying; skip with ^C]
JSON Query z****/: 429 Too Many Requests [retrying; skip with ^C]
z****: JSON Query z****/: 429 Too Many Requests
JSON Query z****/: 429 Too Many Requests [retrying; skip with ^C]
JSON Query z****/: 429 Too Many Requests [retrying; skip with ^C]
z****: JSON Query z****/: 429 Too Many Requests
```

# Normal download process (for half of profiles)
```
Downloading 478 profiles: a**** a**** b*** ... k****

[downloading part works correctly here]
```
**(The above should have 900 profiles)**

# Final Error log
```
Errors occured:
a****: JSON Query a****/: Could not find "window._sharedData" in html response.
c****: JSON Query c****/: Could not find "window._sharedData" in html response.
d****: JSON Query d****/: Could not find "window._sharedData" in html response.
e****: JSON Query e****/: Could not find "window._sharedData" in html response.
g****: JSON Query g****/: Could not find "window._sharedData" in html response.
g****: JSON Query g****/: Could not find "window._sharedData" in html response.
l****: JSON Query l****/: 429 Too Many Requests
l****: JSON Query l****/: 429 Too Many Requests
l****: JSON Query l****/: 429 Too Many Requests
l****: JSON Query l****/: 429 Too Many Requests
l****: JSON Query l****/: 429 Too Many Requests
l****: JSON Query l****/: 429 Too Many Requests

...

x****: JSON Query x****/: 429 Too Many Requests
x****: JSON Query x****/: 429 Too Many Requests
y****: JSON Query y****/: 429 Too Many Requests
y****: JSON Query y****/: 429 Too Many Requests
z****: JSON Query z****/: 429 Too Many Requests
z****: JSON Query z****/: 429 Too Many Requests
z****: JSON Query z****/: 429 Too Many Requests
z****: JSON Query z****/: 429 Too Many Requests
z****: JSON Query z****/: 429 Too Many Requests
z****: JSON Query z****/: 429 Too Many Requests
```

**Comment by rabe398** [comment]
And here I though i was the only one having this issue, it seems Instagram implemented some new server rules regarding requests made per hour, whenever i run the script i would encounter the same errors as you, and if you visit Instagram on a browser you would encounter " Error
Please wait a few minutes before you try again. "
I tried changing accounts and ip and that didn't help, i would encounter the same errors after about 6 minutes in. The only possible solution that I could think of, is to have some kind of dynamic delay between each request that are made, and to have a cool down period after each user in order to mimic mobile user behavior.

**Comment by noamb3** [comment]
I already tried what you are suggesting with dynamic delay and a cool down period.
It works for a few hours and than stopped again.

Any ideas ?

**Comment by psylenced** [comment]
I guess what I was probably meant to say then is that the 429 fix doesn't address all their server changes made over past few days.

I've also noticed my anonymous requests are now all failing with 429 too - so I'm possibly IP banned for non-logged in.

What I'll probably need to do in the mean time is split my logged in users into multiple batches.

**Comment by rabe398** [comment]
I tired downloading 200 profiles and I still get the same 429 error.

**Comment by rabe398** [comment]
@psylenced Did splitting the main batch file into multiple batches work for you?
if yes, how many times do you run the script per day?

**Comment by beakwood** [comment]
> 
> 
> @psylenced Did splitting the main batch file into multiple batches work for you?
> if yes, how many times do you run the script per day?

Definitely didn't work for me. I basically cut my batches from a mass 1000 to 100 per batch. I still get 429. I can't even do a full 100 anymore. 

using simple 

instaloader +100inst.txt --fast-update --no-profile-pic --no-captions --no-metadata-json --no-video-thumbnails --filename-pattern "{profile}_{mediaid}_{date_utc}" --quiet

As I'm trying to also find the private profiles to separate them into their own batch. Since I did a full download of 1000 profiles to get the names and put them in .txt over several days ago and been trying to go 100 batches at a time trying. But I can't even scrape fully my first 100. Been like this past 3-4 days. (with and without VPN).

**Comment by rabe398** [comment]
Same problem over here, I guess we will need to wait on developer response..
@aandergr  @Thammus

**Comment by rabe398** [comment]
> > @psylenced Did splitting the main batch file into multiple batches work for you?
> > if yes, how many times do you run the script per day?
> 
> Definitely didn't work for me. I basically cut my batches from a mass 1000 to 100 per batch. I still get 429. I can't even do a full 100 anymore.
> 
> using simple
> 
> instaloader +100inst.txt --fast-update --no-profile-pic --no-captions --no-metadata-json --no-video-thumbnails --filename-pattern "{profile}_{mediaid}_{date_utc}" --quiet
> 
> As I'm trying to also find the private profiles to separate them into their own batch. Since I did a full download of 1000 profiles to get the names and put them in .txt over several days ago and been trying to go 100 batches at a time trying. But I can't even scrape fully my first 100. Been like this past 3-4 days. (with and without VPN).

**Comment by psylenced** [comment]
I had my private/public split anyway, as I'd run public ones in parallel and only use logged in API calls for ones that needed it.

It looks like the initial get profile ID call is now massively rate limited, so need to do it a different way.

From the looks of it you can get the id from the source html of ig.com/profilename which may or may not be rate limited. If it's a standard web request and not through the api, hopefully it wont be rate limited.

Might need to change the process from:

* get all ids
* loop each id 
* * download profile with 429 check

to:

* loop
* * get 1 id
* * download profile with 429 check

**Comment by clublek** [comment]
When using :stories as parameter, i do not encounter the rate limit. Does this really utilize a lot less API requests and could this methodology possibly also being extended when scraping a lot of usernames in a text file?

**Comment by psylenced** [comment]
From my testing - had no account activity for a few days. Using fast update (most profiles only had a couple of downloads)

Did batch size of 20 with 5 mins sleep in between each batch. 

After 4 hours at batch 24 started getting 429s.

Going to try increasing it to 10 min sleeps once the 429s time out. Will keep slowly adjusting until it works.

**Comment by rabe398** [comment]
> From my testing - had no account activity for a few days. Using fast update (most profiles only had a couple of downloads)
> 
> Did batch size of 20 with 5 mins sleep in between each batch.
> 
> After 4 hours at batch 24 started getting 429s.
> 
> Going to try increasing it to 10 min sleeps once the 429s time out. Will keep slowly adjusting until it works.
> 
> Edit:
> Ban lasted about 18-23 hours.

I'm guessing there won't be any response from the developer

**Comment by psylenced** [comment]
Today's test:

Batch size: 20
Sleep between each: 15 mins

Duration before 429s: 7.5 hrs
Batches processed: 24

From the looks of it, 24 batch x 20 profiles = 480 profiles. 2-3 api calls per profile (not sure how many are actually being called) means the api limit is around 1000-1500 per 24 hrs.

**Comment by clublek** [comment]
That's not cool :( I would never manage to download 6000 profiles in 24 hours then...

**Comment by rabe398** [comment]
> Today's test:
> 
> Batch size: 20
> Sleep between each: 15 mins
> 
> Duration before 429s: 7.5 hrs
> Batches processed: 24
> 
> From the looks of it, 24 batch x 20 profiles = 480 profiles. 2-3 api calls per profile (not sure how many are actually being called) means the api limit is around 1000-1500 per 24 hrs.

Thank you for sharing your test results with us

**Comment by werid** [comment]
The solution seems to be using more accounts. At the moment, I have 4 accounts that my script rotates between, with 40 seconds pause inbetween each profile's stories being grabbed. With 1800 profiles, it's taking about 24 hours. The 40 seconds pause might be adjusted downards, and more accounts being used would help too. 

I also noticed they appear to have reduced the bantime you get from reaching the limit. 

A month ago there was a story in the news about an ad partner collecting stories and geo data from ig profiles, ig viewed it as abuse... and this reduction in api calls is most likely a response to that.

**Comment by psylenced** [comment]
I also think the ban is a rolling (possibly hourly) ban and not a complete ban.

Checking through my logs when I started getting 429s the first few batches some would work and some would fail, after 2-3 more batches after that all would fail.

Because some later requests were getting through after the initial fail - that means there is a certain limit over a time period.

**Comment by hgkmaxymus** [comment]
Yeah, people with 1k+ profiles lists would need to let the computer running for a huge amount of time just to be able to UPDATE the old profiles.

I might try the multiple instagram accounts per list (500 profiles each?). Thanks for a possible work around.

Also, the stories/highlights over there also take a really large time to crawl and download? Here, I had to split my calls with 2 different accounts, 15 profiles per call and they take 1h to download, each. And a lot of those profiles have like 1-5 highlights and rarely post stories. My calls ignore posts, videos, meta-data, captions, everything. Instagram is really a mess? :/

**Comment by psylenced** [comment]
Still an issue.

**Comment by psylenced** [comment]
Still an issue.

**Comment by beakwood** [comment]
Yes, this is still an issue. Constantly getting this.

**Comment by FelipeCost** [comment]
I noticed that I get this error even when using 1 cron job that check an unique profile stories 4 times a day (6 hours between each attempt) using python. That's a test (I plan to increase the profiles list when I have all working fine, but now, I have no idea on when that'll happen?). 

I've already used usual login and now am using the session loaded from json file. I try it with 3 different accounts and always get the exact same error: 
Number of requests within last 10/11/20/22/30/60 minutes grouped by type:
 * xxxxxxxxxxxxxxxxxxxxxxx:    1    1    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please

Please note that the "xxxxxxxxxxxxxxxxxxxxxxx" part is exactly the same, no matter which loaded session I use, what makes me think 

What worked once, was uninstalling instaloader from this server and installing it again, but it might be coincidentally because just tried it now and had no success.

Shall I assume it is somehow related to an instaloader identification?

Will this issue be reopened?
