### ISSUE TITLE
get image URL

### ISSUE THREAD

**Issue by Kesavadas** [instaloader/instaloader#393]
is there a way to get the URL of every post while scraping likes and comments of each post from a profile?

**Comment by aandergr** [comment]
The URL of a post is instagram.com/p/{shortcode}. You can easily get the shortcode of each Post.

**Comment by jschmue** [comment]
I think th question was meant to get a URL that directly leads to the .jpg-file, not to the page where comments etc. are enlisted on the right hand side.

Should look somewhat like:
https://scontent-frt3-2.cdninstagram.com/v/t51.2885-15/e35/92094xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx01133551_n.jpg?_nc_ht=scontent-frt3-2.cdninstagram.com&_nc_cat=110&_nc_ohc=qJhMxxxxxxxxxxxxwYfYQ&oh=4b4d8xxxxxxxxxxxxxxxxxxxxxx6d8f75f&oe=5ExxxxBC

I am also interested in this issue.
