### ISSUE TITLE
how do i download a single post. Documentation is confusing and provides no example.

### ISSUE THREAD

**Issue by NIXOYE** [instaloader/instaloader#398]
It would help a lot if the documentation listed an example so people understood how to use the flags etc.

**Comment by RoseWebb** [comment]
You can use `-post` option where post=shortcode

For example to download https://www.instagram.com/p/B135NL8AK9s use the following line:
`instaloader -- -B135NL8AK9s`

**Comment by aandergr** [comment]
Please propose a PR for the doc issue.
