### ISSUE TITLE
Adding a delay between each request to avoid rate limiting

### ISSUE THREAD

**Issue by avekifes** [instaloader/instaloader#400]
I keep getting rate limited by Instagram's API changes. Does anyone have a script that would cycle through a list of accounts, updating a single one at a time, with a delay between each?

**Comment by gituzzer** [comment]
> I keep getting rate limited by Instagram's API changes. Does anyone have a script that would cycle through a list of accounts, updating a single one at a time, with a delay between each?

This has been working for me the last days.. 20s at least, depending on which profiles..30s or more is safer.

#!/bin/bash
filename=$HOME/Desktop/profiles-full.txt

cd /media/sf_SHARE/instaprofiles

i=1
while read -r line
do
 echo -e "Profile: $i"
 let "i++"
 profile="$line"
 python3 <path-to-instaloader>/instaloader.py -l <login> -p <password> $profile --no-captions --fast-update --filename-pattern={date} --no-metadata-json --no-profile-pic
 sleep 20
done < "$filename"

When/if it starts failing, simply go to the file profiles-full.txt (where all the profiles are stored, one per line), delete the profiles that you already updated/downloaded and 30 mins later restart the script.

**Comment by avekifes** [comment]
Thanks for sharing.

I can't seem to figure my paths out. Assuming I have Instaloader and profiles-full.txt in C:\Users\user\Desktop\instaloader-master but want my downloads to go to E:\Instaloader, what would the proper syntax be?

Also, how does Instaloader know to use profiles-full.txt in your script? (Sorry if these questions are stupid, but I'm totally new to Python/scripting.)

**Comment by slarrain** [comment]
> Also, how does Instaloader know to use profiles-full.txt in your script?

It doesn't. @avekifes is using a shell script. So it is actually the shell script that reads the `profiles-full.txt` file. He creates a variable call `profile` with every line in the file, and then calls `instalaoder`. 
He is not even using python (besides for calling instaloader as a script).

Can you show us how your code looks? Maybe is as easy as adding a `sleep(30)` on your python script.

> Sorry if these questions are stupid, but I'm totally new to Python/scripting.

No worries. They are not stupid. Remember that even the most advanced programmer, at a time, knew less than what you know now.

**Comment by avekifes** [comment]
Here's what I have so far, but when I execute the script, nothing happens.

#!/bin/bash
filename=/mnt/c/Users/USER/Desktop/Instagram.txt

cd /mnt/e/Instagram/Instaloader

i=1
while read -r line
do
echo -e "Profile: $i"
let "i++"
profile="$line"
python3 /instaloader.py -l -p $profile --no-captions --fast-update --filename-pattern={date} --no-metadata-json --no-profile-pic
sleep 20
done

I suspect that instaloader.py isn't being called. I get nothing even when I enter the complete directory (/mnt/c/Users/USER/Desktop/instaloader-master/instaloader.py).

**Comment by slarrain** [comment]
You seem to be missing this part: `< "$filename"`

**Comment by avekifes** [comment]
It's in there; I accidentally left it out of my previous post.

**Comment by harshamv** [comment]
@gituzzer can you share the instaloader.py code please
