### ISSUE TITLE
How do I download a specific number of pictures only using instaloader python module? Please respond!

### ISSUE THREAD

**Issue by jhjjj12** [instaloader/instaloader#405]
I'm trying to download 25 pictures ONLY (no metadata, comments or anything else) from a list of profiles. I tried using download_pic but I keep getting an error message saying "url is not defined". Here is my code

     from instaloader import *
     import os
     import pathlib

     data_path = pathlib.Path(os.getcwd())/"data"

     L = instaloader.Instaloader()

     L.login("sdrawkcabbackwardssdrawkcab", "Pazzword12345")     # (login)
     
     #profile array
     profile_names = ["kyliejenner", "justinbieber", "instagram"]
          
     #for every profile in the array
          for p_name in profile_names:
          i=0
         profile = Profile.from_username(L.context, p_name)
         i+=1
        L.download_pic(data_path/p_name, url, mtime, filename_suffix=None, _attempt=1)
         if i==25:
            break

**Comment by kartikay08** [comment]
add a break statement in the loop when it reaches a limit of 25

**Comment by jhjjj12** [comment]
> add a break statement in the loop when it reaches a limit of 25

I know that part but it's not letting me download anything to begin with.

**Comment by e5150** [comment]
Well, `url` is not defined anywhere in your code. Use `profile.get_posts()` to get the user's posts, then the url is available as`post.url`.
Also, your code won't break, since `i` will always be `1` when it's checked.
