### ISSUE TITLE
ProfileNotExistsException occurs whenever I try doing multiple Iterations

### ISSUE THREAD

**Issue by kartikay08** [instaloader/instaloader#406]
HTTP redirect from https://www.instagram.com/ashishjeweller/ to https://www.instagram.com/accounts/login/
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\instaloader\structures.py in _obtain_metadata(self)
    527                 metadata = self._context.get_json('{}/'.format(self.username), params={})
--> 528                 self._node = metadata['entry_data']['ProfilePage'][0]['graphql']['user']
    529                 self._has_full_metadata = True

KeyError: 'ProfilePage'

The above exception was the direct cause of the following exception:

ProfileNotExistsException                 Traceback (most recent call last)
<ipython-input-30-8d04c68f1d62> in <module>()
----> 1 scraper('delhi')

<ipython-input-29-3ff23d59965c> in scraper(hashtag)
     22           time.append(i.date.strftime("%H:%M:%S"))
     23           image_url.append(i.url)
---> 24           profile = instaloader.Profile.from_username(L.context, i.owner_username)
     25           username.append(i.owner_username)
     26           following.append(profile.followees)

~\Anaconda3\lib\site-packages\instaloader\structures.py in from_username(cls, context, username)
    482         # pylint:disable=protected-access
    483         profile = cls(context, {'username': username.lower()})
--> 484         profile._obtain_metadata()  # to raise ProfileNotExistException now in case username is invalid
    485         return profile
    486 

~\Anaconda3\lib\site-packages\instaloader\structures.py in _obtain_metadata(self)
    530                 self._rhx_gis = metadata.get('rhx_gis')
    531         except (QueryReturnedNotFoundException, KeyError) as err:
--> 532             raise ProfileNotExistsException('Profile {} does not exist.'.format(self.username)) from err
    533 
    534     def _metadata(self, *keys) -> Any:

ProfileNotExistsException: Profile ashishjeweller does not exist.

Is there any way i can avoid this error

**Comment by aandergr** [comment]
We cannot help you with that unless you provide more information.

**Comment by kartikay08** [comment]
Iam trying to extract images of a particular hashtag from instaloader after let's say 400 iterations it shows this error
