### ISSUE TITLE
Example showing how to get posts of a user without logging in using the python module?

### ISSUE THREAD

**Issue by JSpenced** [instaloader/instaloader#407]
I am trying to scrape images from public accounts but it makes me use login details to extract where from the command line it doesn't require login details. Is it possible or within the python module you have to login to get_posts() from an account.

**Comment by iDustbin** [comment]
`@app.route('/update', methods=['GET', 'POST'])
def update_profile():
    login = instaloader.Instaloader( compress_json=False )
    USER = ''
    PASSWORD = ''
    L.login(USER, PASSWORD)

    PROFILE = ''
    profile = instaloader.Profile.from_username(login.context, PROFILE)
    posts = list(profile.get_posts())
    for post in profile.get_posts():
        login.download_post(post, target=profile.username)`

**Comment by iDustbin** [comment]
```
@app.route('/update', methods=['GET', 'POST'])
def update_profile():
    login = instaloader.Instaloader( compress_json=False )
    USER = ''
    PASSWORD = ''
    L.login(USER, PASSWORD)
    PROFILE = ''
    profile = instaloader.Profile.from_username(login.context, PROFILE)
    posts = list(profile.get_posts())
    for post in profile.get_posts():
        login.download_post(post, target=profile.username)
```

**Comment by JSpenced** [comment]
Yes, I have figured out how to extract if I login with my USER and PASSWORD. From command line, you don't have to put in a user and password. Is it possible to do this without inputting a user and password? Also, what is the best way to limit the number of posts this grabs? Just having a counter?

**Comment by iDustbin** [comment]
if the profile is public you dont need to define any credentials.
do you want to work on cli  ?

**Comment by JSpenced** [comment]
Yeah but I want to download from many accounts but only 50 photos from each for an image recognition application. I thought it was easiest to not use the command line and use the python package directly. It seems that it requires you to login to download posts. Not sure why you have to login if you don't when you use the command line to download public posts.

**Comment by iDustbin** [comment]
limitization is also possible, im working on an flask api... please check out my issue https://github.com/instaloader/instaloader/issues/408

**Comment by iDustbin** [comment]
curl -X POST http://localhost:5000/api/instagram/update -d '{"profile": "instagram_profile"}' -H 'Content-Type: application/json'
