### ISSUE TITLE
Best way to specify directory path to output the request

### ISSUE THREAD

**Issue by JSpenced** [instaloader/instaloader#409]
I don't see a way to specify the output directory from command line or the Python module? Can the download_post or other functions be modified to accept a directory path? Or is there a good workaround for this?

**Comment by hgkmaxymus** [comment]
For the command line, you can use this: https://instaloader.github.io/cli-options.html#cmdoption-dirname-pattern

**Comment by e5150** [comment]
For the module, specify `dirname_pattern` when initializing your `Instaloader` instance. E.g:
```
import instaloader as il
l = il.Instaloader(dirname_pattern="...")
...
l.download_post(post, filename)
```
See the [filename specification](https://instaloader.github.io/basic-usage.html#filename-specification) for possible tokens.

**Comment by JSpenced** [comment]
I understand how to pass in a dirname pattern but if you pass in a full directory it doesn't work. It only accepts patterns not for example...

`/Users/user/thispath/savehere/`

**Comment by e5150** [comment]
I don't know how you're doing it, but it works perfectly fine here ("`dirpath`" is not an accepted keyword argument):
```
$ python3
>>> import instaloader as il
>>> l = il.Instaloader(dirname_pattern="/tmp/pure/path/without/tokens", download_comments=False)
>>> p = il.Post.from_shortcode(l.context, "B2hiXYpBKwm")
>>> l.download_post(p, "test")
/tmp/pure/path/without/tokens/2019-09-17_19-26-45_UTC.jpg [#DoYouFollow footballer broth…] json 
True
>>> exit()
$ ls /tmp/pure/path/without/tokens
2019-09-17_19-26-45_UTC.jpg  2019-09-17_19-26-45_UTC.json.xz  2019-09-17_19-26-45_UTC.txt
```

**Comment by JSpenced** [comment]
I'll try again. I tried exactly that and it would put a folder int he current directory named "`/tmp/pure/path/without/tokens"` and not put the actual file at that path.

**Comment by e5150** [comment]
Then I suggest you file a proper bug report. It's hard to figure out what's going wrong when you don't show what commands and/or code you're running, and the corresponding output.
