### ISSUE TITLE
Store stories in subdirectory?

### ISSUE THREAD

**Issue by ealgase** [instaloader/instaloader#410]
The current command that I run is `instaloader @myname --dirname-pattern "~instaarchive/{target}" --stories --highlights --tagged --comments --login=myname --fast-update"`.  While this successfully downloads all files, stories appear in ~/instaarchive/profile instead of ~/instaarchive/profile/stories.  Is there a way to do this?

**Comment by e5150** [comment]
Currently it's not possible, it is however a suggested feature, see #253.
Until it's been implemented you could strip `--stories` from your invocation and separately run: `instaloader --dirname-pattern "~instaarchive/{target}/stories" :stories --login=myname`

**Comment by TemporaryUsername12481** [comment]
Wouldn't `{target}` just be `:stories` in this case?

**Comment by e5150** [comment]
My mistake, the pattern should be "~instaarchive/{profile}/stories".
