### ISSUE TITLE
Post is skipped if first image returns 404

### ISSUE THREAD

**Issue by rEnr3n** [instaloader/instaloader#413]
**Describe the bug**
There are some instances where a post contains some missing images. (e.g. https://www.instagram.com/p/Bjj0wkjjOwo/)
Instaloader skips this post without retrieving the images that still exist. Instaloader moves on to the next posts.

**To Reproduce**
```
$ cat config.txt
--commit-mode
--max-connection-attempts=0
--no-videos
--no-video-thumbnails
--no-caption
--no-profile-pic
--filename-pattern={date_utc} {shortcode}/{mediaid}
--user-agent='Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0'
```
```
$ instaloader gfriendofficial +config.txt
```

**Expected behavior**
It should at least download the valid images in that offending post.

**Error messages and tracebacks**
```
Errors occured:
Download <Post Bjj0wkjjOwo> of gfriendofficial: 404 when accessing https://instagram.fmnl14-1.fna.fbcdn.net/vp/7c07049ca712cfb6d86208a6dcba57c7/5E1A65A3/t51.2885-15/e35/33239800_223107691618308_7290368537242107904_n.jpg?_nc_ht=instagram.fmnl14-1.fna.fbcdn.net&_nc_cat=100.
```
**Instaloader version**
```
$ instaloader --version
4.2.9
```

**Comment by aandergr** [comment]
Duplicate of #146.
