### ISSUE TITLE
Proxy IP rotation

### ISSUE THREAD

**Issue by Kesavadas** [instaloader/instaloader#419]
I am trying to have the requests jump between proxy addresses as mentioned in 
https://www.scrapehero.com/how-to-rotate-proxies-and-ip-addresses-using-python-3/

i am trying to use instaloader module in python 3.
please provide any suggessions

is it possible to achieve in instaloader?

please assist.

**Comment by harshamv** [comment]
Was this solved?

**Comment by Kesavadas** [comment]
I don't think so. There was no update and I think it was automatically
closed by bot.
