### ISSUE TITLE
The options --no-pictures and or --no-videos downloads images randomly.

### ISSUE THREAD

**Issue by Hashnoob** [instaloader/instaloader#426]
**Describe the bug**
If you set --no-pictures and or --no-videos, instaloader will still download photos at random.

**To Reproduce**
Use --no-pictures and or --no-videos on a good sized profile.

**Comment by Thammus** [comment]
If you use `--no-pictures` AND `--no-videos`, Instaloader only downloads the profile pic (suppressible with `--no-profile-pic`), the metadata files (suppressible with`--no-metadata-json`) and the caption text files (suppressible with `--no-captions`).

See ["What to download"](https://instaloader.github.io/cli-options.html#what-to-download-of-each-post) for further information.

**Comment by Hashnoob** [comment]
Ok, so lets say I only wanted to download videos, here are the options I would use. But instaloader still download's images from the profile randomly along with all the videos.

Perhaps I missed something?

--no-pictures --no-captions --no-metadata-json --no-video-thumbnails  --stories --highlights --tagged

**Comment by Thammus** [comment]
I admit this can be a bit confusing. `--no-pictures` has no effect on stories or highlights. If you only want to download stories and highlights that are videos you can use [`--storyitem-filter="is_video"`](https://instaloader.github.io/cli-options.html#cmdoption-storyitem-filter).

**Comment by Hashnoob** [comment]
I appreciate the reply, I think I understand. When I'm just trying to download metadata I have the same issue using the options below.

--no-pictures --no-videos --no-video-thumbnails --no-profile-pic --no-captions --no-compress-json --stories --highlights --tagged

Using --post-filter or --storyitem-filter, how would the expression go if you wanted to exclude videos and pictures "not is_video and not is_picture" or something like that?

**Comment by Hashnoob** [comment]
I appreciate the reply, I think I understand. If I try to only download metadata I end up having the same issue with the options below. My goal is to download metadata from every possible post on the profile and nothing else.

`--no-pictures --no-videos --no-video-thumbnails --no-profile-pic --no-captions --no-compress-json --stories --highlights --tagged`

"`--no-pictures` has no effect on stories or highlights" - So how could I still get the metadata from the stories and highlights and not download the photos?

Or am I not thinking about it in the right way?

**Comment by Hashnoob** [comment]
I appreciate the reply, I think I understand. If I try to only download metadata I end up having the same issue with the options below. My goal is to download metadata from every possible post on the profile and nothing else.

`--no-pictures --no-videos --no-video-thumbnails --no-profile-pic --no-captions --no-compress-json --stories --highlights --tagged`

"`--no-pictures` has no effect on stories or highlights" - So what could I do to still get the metadata from the video or photo stories and highlight posts and not download the photos?

Or am thinking about it in the wrong way?
