### ISSUE TITLE
 --post-filter='date_utc == datetime(2019,10,19)' not working

### ISSUE THREAD

**Issue by srburton** [instaloader/instaloader#427]
Strange I am trying to download image only of a specific day 10/19/2019 and it brings everyday ... Am I doing something wrong?

`instaloader --login=?  --password=? --post-filter='date_utc == datetime(2019,10,19)' --tagged --no-videos --no-captions  --no-metadata-json --no-compress-json  my_profile`

**Comment by srburton** [comment]
Any solution?

**Comment by e5150** [comment]
`datetime` includes both date and time, and with `datetime(2019, 10, 19)` you get the implied time of midnight. You'd have to specify the entire day: `datetime(2019, 10, 19) <= date_utc < datetime(2019, 10, 20)`
