### ISSUE TITLE
What code do I need to run for what i need? (I'm really new - please help)

### ISSUE THREAD

**Issue by DGKore** [instaloader/instaloader#428]
Dear all,

I would like to start of by explaining that I am entirely new at this, so please bear with me.

The problem is that I because I am so new at this, am a bit overwhelmed by all of the information and became confused because I don't know most of the terminology. I am following an online course, but I have only just started and I really need this data as soon as possible. Therefore I would  be extremely grateful if someone would be so kind as to help me!

What I need to extract are two things (public posts and profiles only):

1. all posts of one user, containing for each post:
          - username
          - biography of user
          - name (if included by the user)
          - the number of posts of the user
          - the number of followers of the user
          - the numbers of people the user is following
          - the caption of the post (including the hashtags)
          - the location of the post (if included by the user)
          - the number of views or likes of the post (NOT the images/video's themselves)
          - the date on which it was posted

2. all posts containing a specific hashtag, containing for each post:
          - username
          - biography
          - username
          - biography of user
          - name (if included by the user)
          - the number of posts of the user
          - the number of followers of the user
          - the numbers of people the user is following
          - the caption of the post (including the hashtags)
          - the location of the post (if included by the user)
          - the number of views or likes of the post (NOT the images/video's themselves)
          - the date on which it was posted

Now I realise that it's probably all there, but I don't know anything about Python and I don't really understand how I am supposed to mix and match in order to get what I need. Because of this I wanted to ask whether someone would either be willing to set up an example for me, on what my code would need to look like to get these data via Instaloader, or to provide me with some simplified layman instructions.

Thank you so much in advance and kind regards!

DGKore

**Comment by srburton** [comment]
@DGKore 

Basic example

```shell
$ instaloader --login=email@teste.com --password="1234YouPassword"  --tagged --stories url_profile_download_info
```

**Comment by DGKore** [comment]
@srburton 

Thank you for sending me the example. I tried to use it as a model for my code, but I am not certain I succeeded. Would you please take a look?

`$ instaloader  --no-pictures --no-videos --no-compress-json --no-profile-pic
--dirname-pattern={target} --filename-pattern={date_utc:%d-%m-%Y}_UTC_{profile} “#cat” url_profile_download_info`

Is my code correct? Am I correct to assume that now I will NOT get pictures and videos, but I WILL get all captions of all posts with the hashtag #cat and the date on which they were posted? 
What other information will this code give me? 
And what does the "url_profile_download_info" you added at the end do? 

What things can I add to get the number of likes/views, the location, the username, biography, the number of posts of the user, the number of followers and following of the user. 

Thank you so much for helping me! You're a great help!

**Comment by srburton** [comment]
@DGKore 

Instagram link:  https://www.instagram.com/barbearia777/

url_profile_download_info: **barbearia777**

**Comment by DGKore** [comment]
@srburton 
Hi! I tried to run my code in both Jupyter Notebook and in IDLE, but I always get this "SyntaxError: invalid syntax"-notification. Do you know what I did wrong? 

I also tried to run the very simple "instaloader profile [profile ...]" (as "instaloader profile barbearia777") as a test, but had the exact same problem. Do I need to run it in a different programme? 

Thank you for helping me!

**Comment by e5150** [comment]
> Hi! I tried to run my code in both Jupyter Notebook and in IDLE, but I always get this "SyntaxError: invalid syntax"-notification. Do you know what I did wrong?

You're not supposed to run instaloader in IDLE, it is a complete python program, run it from your system shell.

**Comment by DGKore** [comment]
@e5150 Hello! Thank you!
Is that the same as your computer's command prompt? or is it Powershell?

**Comment by srburton** [comment]
@DGKore 
Simple use :
![image](https://user-images.githubusercontent.com/15394508/67715420-94eea300-f9a8-11e9-832f-a156601e21cf.png)

**Comment by DGKore** [comment]
@srburton 
Thank you! It works now! 
I have one final problem concerning the Python module.  
In Instaloader's Github documentation (https://instaloader.github.io/as-module.html) it says you need to "start with getting an instance of Instaloader" by entering the following code:

`import instaloader

# Get instance
L = instaloader.Instaloader()`

I typed this code into a Jupyter notebook and in an IDLE file. However, when I run the code, I get the following error message:

`---------------------------------------------------------------------------
ModuleNotFoundError Traceback (most recent call last)
<ipython-input-1-bd65c83a9f8a> in <module>
----> 1 import instaloader
2
3 # Get instance
4 L = instaloader.Instaloader()

ModuleNotFoundError: No module named 'instaloader'`

So I don't really know how I can solve this problem. I checked it again and instaloader is indeed installed with pip, so I don't think that's the problem.

Thank you very much for helping me! I really appreciate it!
