### ISSUE TITLE
How to build for windows

### ISSUE THREAD

**Issue by bbepis** [instaloader/instaloader#431]
There was a recent fix implemented for #429 that is currently not in the latest windows release. I would like to manually build this application to be able to use a working version of instaloader, however there are no instructions on how to create my own standalone .exe. I do not wish to use the pip install method as it just creates clutter in my system directory, and requires many prerequisites.

**Comment by ahmedtds** [comment]
Can you please build 32-bit windows executable?
Thanks.

**Comment by Thammus** [comment]
We now have automated the EXE creation process (dc289024c8f8017e29bcec52fbd83818cbc04530). By executing the python script [create_exe.py](/instaloader/instaloader/blob/master/deploy/windows/create_exe.py) you can easily build it for yourself.

**Comment by ahmedtds** [comment]
@Thammus but you still don't provide a 32-bit exe on the releases page? :(
