### ISSUE TITLE
Accessing property "comments" on Post significantly slows down crawling

### ISSUE THREAD

**Issue by fredrik-smedberg** [instaloader/instaloader#436]
**Describe the bug**
Accessing the property `comments` for each iteration of `Post` significantly slows down the crawling.

**To Reproduce**
Crawl any profile with at leasts 2-3 posts. You'll see that when accessing `.comments` on every `Post`, the crawler will stop for each iteration.

**Expected behavior**
To not slow down and instead use the already available number of comments in the received data. This is accomplished by switching what field that is tried first in the `def comments` property. See my proposed fix below.

**Error messages and tracebacks**
-

**Instaloader version**
4.2.9

**Additional context**
My proposed solution, which significantly speeds up the crawling. Just switch the order of `edge_media_to_comment` and `edge_media_to_parent_comment`.

`structures.py`

current code:
```
    @property
    def comments(self) -> int:
        """Comment count including answers"""
        try:
            return self._field('edge_media_to_parent_comment', 'count')
        except KeyError:
            return self._field('edge_media_to_comment', 'count')
```

patched code:
```
    @property
    def comments(self) -> int:
        """Comment count including answers"""
        try:
            return self._field('edge_media_to_comment', 'count')
        except KeyError:
            return self._field('edge_media_to_parent_comment', 'count')
```

**Comment by aandergr** [comment]
Thanks for that suggestion! I just did a few trials and it seems that indeed the field `edge_media_to_comment.count` is present in the data structure retrieved from a profile, whereas `edge_media_to_parent_comment` isn't. 

Could you please make a Pull Request to propose that code change? Pull Requests are our preferred way for code changes, since it is a great tool for reviewing the code and accepting it such that the author is honored as a contributor.

**Comment by fredrik-smedberg** [comment]
Hello Alexander!

I've created a pull request now :-)
_______________________________
Med vänliga hälsningar / Best regards
*Fredrik Smedberg*

+46 705 69 45 39  |  fredrik@doriantull.us


Den ons 30 okt. 2019 kl 19:03 skrev Alexander Graf <notifications@github.com

**Comment by Thammus** [comment]
This speedup will be experiencable with the next release.
