### ISSUE TITLE
short question: how to export location to metadata txt-file

### ISSUE THREAD

**Issue by ledgreve** [instaloader/instaloader#437]
Hello! At the moment, I am using the following code in my computer's command line:

`instaloader --no-pictures --no-videos --no-compress-json --no-profile-pic --post-metadata-txt=" owner_username: {owner_username}; caption: {caption}; date_local: {date_local}; date_utc: {date_utc}; likes: {likes}; comments: {comments}." --filename-pattern={date_utc:%d-%m-%Y}_UTC_{profile} “#cat”`

The code works fine, but I would also like to export the text containing the location (if one was included in the post). Does anyone know what I should add to my "post-metadata-txt"-line in order to do this? I already tried {location}, {location_name} and {%location ID}, but this doesn't work. 

Thank you!

**Comment by aandergr** [comment]
`--post-metadata-txt="{location}" produces text files in the format

```
PostLocation(id=442131488, name='Valencia, Spain', slug='valencia-spain', has_public_page=True, lat=39.4667, lng=-0.366667)
```

Also, there is `--geotags` which exports the location name and its longitude/latitude in a Google Maps URL.

Either way, accessing the post locations requires to be logged in.
