### ISSUE TITLE
Doesn't extract all posts

### ISSUE THREAD

**Issue by ledgreve** [instaloader/instaloader#439]
Hello!

I am extracting posts with a certain hashtag (I'd like to work with the module, and extract the name of the location tot txt as well, but unfortunately that isn't working right now). I use the following code in my command line:

`instaloader --no-pictures --no-videos --no-compress-json --no-profile-pic --post-metadata-txt=" {owner_username}; {caption}; {date_local}; {date_utc}; {likes}; {comments}" --filename-pattern={date_utc:%d-%m-%Y}_UTC_{profile} “#fintroliteratuurprijs”`

When you type this hashtag into Instagram itsefl, you see there are 119 posts with this tag (https://www.instagram.com/explore/tags/fintroliteratuurprijs/). However, after scraping I only have 77. Could someone explain how this happened and how I can solve this problem? 

Thank you!

**Comment by Thammus** [comment]
This is a problem on Instagram's side. They claim to have 119 posts with this hashtag but they only provide 77 of them in their web interface. Open the link you provided and simply count the posts in your browser. There are 9 shown under "most popular posts" and 68 "latest" posts.

**Comment by ledgreve** [comment]
@Thammus 
Thank you for the explanation! 
Is there any way I can still get the other posts as well? I really need then for my research.

**Comment by Thammus** [comment]
Sorry, I think it is not possible to get the other posts. Even the official Instagram App only gives access to those 77 public posts. The missing 42 posts could belong to private profiles but there is no way to find out which profiles those are, thus you cannot systematically follow/subscribe them to get access to their posts

**Comment by ledgreve** [comment]
@Thammus 
Thank you for letting me know! I really appreciate your help!
I have one final unrelated question:  I need to try to build a script that will give me the username, location name, caption, likes, the UTC and local date, the comments, the amount of likes for the comments, and the username of whoever commented divided by ";" in a txt/ or csv-file. However, I can't do this using the command line. 
I have installed instaloader using pip and can use the command line to run a simple command, but  when I try to run the following code in Jupyter Notebooks or in IDLE:

`import instaloader
Get instance

L = instaloader.Instaloader()`

I still get the following error message:

`---------------------------------------------------------------------------
ModuleNotFoundError Traceback (most recent call last)
in
----> 1 import instaloader
2
3 # Get instance
4 L = instaloader.Instaloader()

ModuleNotFoundError: No module named 'instaloader'
`
Can I solve this problem?
Thank you so much in advance for helping me! You are a saving angel for someone who is new to all of this!

**Comment by Thammus** [comment]
If simply running Python scripts from command-line does not serve your needs, the following blog post may give you enough insight to solve the problem:
[https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/](https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/)
