### ISSUE TITLE
instaloader: command not found (installed uninstalled reinstalled)

### ISSUE THREAD

**Issue by CochinoChingon** [instaloader/instaloader#440]
**Describe the bug**
installed instaloader 4.2.09 ran fine for a few weeks. Began having issue #433 replaced ...instaloadercontext.py. Worked for a run until I realized that I forgot some flags/variables. ran again and got **instaloader: command not found** searched my shell history for las known working call with variables and again **instaloader: command not found**

`$ pip3 uninstall instaloader`
`$pip3 install instaloader`

saw that I had instaloader 4.2.09 and 4.2.10, deleted those folders, reran `pip3 un/install instaloader`, still have **instaloader: command not found** 

**To Reproduce**
`$ instaloader +/path/to/args.txt
instaloader: command not found`

**Expected behavior**
instaloader downloads jpg/mp4 of specified profiles
**Error messages and tracebacks**
```
gallo@dirty_debbie:~ pip3 install instaloader
Collecting instaloader
Collecting requests>=2.4 (from instaloader)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.4->instaloader)
  Using cached https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests>=2.4->instaloader)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.4->instaloader)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.4->instaloader)
  Using cached https://files.pythonhosted.org/packages/e0/da/55f51ea951e1b7c63a579c09dd7db825bb730ec1fe9c0180fc77bfb31448/urllib3-1.25.6-py2.py3-none-any.whl
Installing collected packages: certifi, idna, chardet, urllib3, requests, instaloader
Successfully installed certifi-2019.9.11 chardet-3.0.4 idna-2.8 instaloader-4.2.10 requests-2.22.0 urllib3-1.25.6
gallo@dirty_debbie:~ instaloader 
instaloader: command not found
gallo@dirty_debbie:~ ls -a .local/lib/python3.6/site-packages/
./        certifi-2019.9.11.dist-info/  idna/                instaloader-4.2.10.dist-info/  urllib3/
../       chardet/                      idna-2.8.dist-info/  requests/                      urllib3-1.25.6.dist-info/
certifi/  chardet-3.0.4.dist-info/      instaloader/         requests-2.22.0.dist-info/
gallo@dirty_debbie:~
```
**Instaloader version**
`instaloader 4.2.10`

**Additional context**
no clue

(please also see https://instaloader.github.io/contributing.html for how to report a bug)

**Comment by aandergr** [comment]
Hi. Maybe `~/.local/bin` is not part of your `$PATH` environment variable. That's the location where pip installs a script to run Instaloader. If it's missing, add a line like

```bash
export PATH="$HOME/.local/bin:$PATH"
```

to your `~/.bashrc` file.

**Comment by renataghisloti** [comment]
For me it was 

./Library/Python/3.8/bin/instaloader profile

who did the trick.
