### ISSUE TITLE
KeyError: 'graphql'

### ISSUE THREAD

**Issue by tedmundtan** [instaloader/instaloader#441]
**Describe the bug**
tried scraping location posts and unable to get the posts owner_id. 
When running code, a ```KeyError :'graphql' ``` occurs in line 135 of structures.py

```
~/anaconda3/lib/python3.7/site-packages/instaloader/structures.py in _obtain_metadata(self)
    133         if not self._full_metadata_dict:
    134             pic_json = self._context.get_json("www.instagram.com/p/{0}/".format(self.shortcode), params={})
--> 135             self._full_metadata_dict = pic_json['entry_data']['PostPage'][0]['graphql']['shortcode_media']
    136             self._rhx_gis_str = pic_json.get('rhx_gis')
    137             if self.shortcode != self._full_metadata_dict['shortcode']: 
```

**To Reproduce**

```
loader = instaloader.Instaloader()
loader.login(USER, PASSWORD) 
info = loader.get_location_posts(215634585)

for things in info:
    print(things.owner_id)
```

**Expected behavior**
return owner_id 

**Error messages and tracebacks**
```KeyError: 'graphql' ```

**Instaloader version**
```instaloader 4.2.10```

**Additional context**

(please also see https://instaloader.github.io/contributing.html for how to report a bug)

**Comment by claudiofrancesconi** [comment]
i wait the fix

**Comment by aandergr** [comment]
Thanks for reporting. I'm closing this in favor of #433, which seems to describe the same bug.
