### ISSUE TITLE
How to download top posts?

### ISSUE THREAD

**Issue by 2tunnels** [instaloader/instaloader#442]
Let's say I want to download only top posts for given hashtag (https://www.instagram.com/explore/tags/puppies/ in our example).

Using:

```bash
instaloader "#puppies" --no-pictures --no-videos
```

Everything works fine, but I'm getting all posts after "top" ones. How to get only top posts?

**Comment by aandergr** [comment]
Commit 83a0f52c60906631b53edef159f4194fee4a9bc0 implements a method `Hashtag.get_top_posts()` to access the top posts of a hashtag.
