### ISSUE TITLE
Several Post-filter arguments?

### ISSUE THREAD

**Issue by jay-p-boop** [instaloader/instaloader#446]
Thanks for your great work!

I can't get post-filter to accept two filter arguments e.g. `instaloader "#workout" --post-filter="is video" and "likes>400"`

invalid syntax, I've tried different approaches :/

Hope somebody can help

**Comment by aandergr** [comment]
`instaloader "#workout" --post-filter="is_video and likes>400"`

should work. Your invocation had too many `"` and a space between `is` and `video` whereas it should be `is_video` (with an underscore between the two words).

**Comment by jay-p-boop** [comment]
Thank you! 

Can the like filter also handle a range, say > 400 and < 1000?
