### ISSUE TITLE
Instaloader fails to download all private profiles and downloads all public ones anonymously.

### ISSUE THREAD

**Issue by mr-prez** [instaloader/instaloader#447]
**Bug Description**
Preface: I am not blocked from the tested Instagram accounts and can access them while logged in on a web browser.  I've also tested this on multiple computers from multiple IP addresses.  It's present on MacOS and the prepackaged executable on Windows.  Version 4.2.10

I enter the command: instaloader profileToDownload --login=myUsername.  Each time I attempt this, instaloader says the profile has changed its name.  The changed name is the same as the original one.  Then it states that the profile doesn't exist.  Next, it tries to download anonymously, which fails because the profile is private.  It gives the error that login=USERNAME is required, even though I logged in already.  An example output is below:

```
instaloader testProfile --login=myUsername
Loaded session from PATH\session-myUsername
Logged in as myUsername
Trying to find profile testProfile using its unique ID 11111111111.
Profile testProfile has changed its name to testProfile.
Profile testProfile does not exist.
Trying again anonymously, helps in case you are just blocked.
Warning: testProfile will be downloaded anonymously ("Profile testProfile does not exist.").
Downloading anonymously: testProfile
testProfile/2019-04-28_06-07-45_UTC_profile_pic.jpg already exists
testProfile: --login=USERNAME required.
Saved session to PATH

Errors occured:
Warning: testProfile will be downloaded anonymously ("Profile testProfile does not exist.").
testProfile: --login=USERNAME required.
```

A similar situation happens with public profiles, although the requested files *are*  downloaded.  In this case, I get the following output:
```
instaloader testProfile --login=myUsername
Loaded session from PATH\session-myUsername.
Logged in as myUsername.
Trying to find profile testProfile using its unique ID 11111111111.
Profile testProfile has changed its name to testProfile.
Profile testProfile does not exist.
Trying again anonymously, helps in case you are just blocked.
Warning: testProfile will be downloaded anonymously ("Profile testProfile does not exist.").
Downloading anonymously: testProfile
testProfile/2019-10-25_12-03-24_UTC_profile_pic.jpg already exists
Retrieving posts from profile testProfile.
<instaloder downloads profile pictures>
Errors occured:
Warning: testProfile will be downloaded anonymously ("Profile testProfile does not exist.").
```

**To Reproduce**
instaloader *profile* --login=*myProfile*

**Instaloader version**
4.2.10

**Additional context**
Again, I'm not blocked from the profiles I've been testing.  This happens with every public and private profile.  Either it's private and not downloaded or public and downloaded anonymously.

**Comment by everdrone** [comment]
Duplicate of #381, there doesn't seem to be a solution yet.

**Comment by aandergr** [comment]
Thanks for describing this issue. There have been other similar reports in #381. However, we did not figure out yet how to reproduce it, and as such, it is hard for us to investigate and fix this issue.

- The latest mentions of this behavior were in December. Sometimes, we observe temporal abnormalities in how the Instagram web API behaves. Does this error still occur?
- Some comment suspects a "temporal IP ban" or something similar. In this case however, accessing the profile with Instagrams web interface shouldn't be possible either. Did you try accessing the profile immediately after observing described behavior?
- Is there any reliable way to reproduce this behavior, like a profile name / id where this happens?

**Comment by Smart123s** [comment]
The same issue is present for me.
I tried to debug the code and I've found out the following thing:

In structures.py line 528 I get a KeyError.
The `metadata['entry_data']['ProfilePage'][0]` variable is empty for me, so there's no `metadata['entry_data']['ProfilePage'][0]['graphql']['user']`

**Comment by stevesbrain** [comment]
@aandergr I'm one of the early ones who had this issue:

- Still ongoing
- I don't think temporal IP ban as I can still access via the web interface, albeit sometimes at a slower/reduced rate (however, even when going for an entirely fresh IP, same issue was encountered - so unless it's a case of any IP this account ever uses, and only for this account on this IP?). Would be odd though as the second account - which is still fine - I use far more for this scripted behaviour, and the one I use for more "normal" behaviour is the one that gets banned (if this is what happened)
- It happens for every profile/ID under my main account, so unfortunately no way to reproduce without handing over control of my account

**Comment by Naheel-Azawy** [comment]
Hi, any updates on this? (commenting so that it doesn't get closed by the bot)

**Comment by Smart123s** [comment]
The issues seems to be resolved for me.
I am adding this comment because this issues was closed by a bot.

**Comment by Naheel-Azawy** [comment]
@Smart123s yep, seems to be working now. Thanks for letting me know
