### ISSUE TITLE
Option to also download Profile Picture when using :feed

### ISSUE THREAD

**Issue by calvinthefreak** [instaloader/instaloader#454]
**Provide us a use case of the feature**
How could the user invoke the new function? Which problem would it solve? If new information is obtained, how would it be further processed?

Add an option so also store the profile picture of the user in the :feed function. I currently use this statements: 
``instaloader/instaloader.py -l $USERNAME -p $PASSWORD :feed --fast-update --no-captions --dirname-pattern= --filename-pattern={owner_id}/{date_utc:%Y}/{date_utc:%m}/{date_utc:%d}/{date_utc:%Y-%m-%d_%H-%M-%S}_{profile}``
I know username and pw in Console is unsafe blabla... (It's not a problem if account gets hacked.)

**Describe the solution you'd like**

Maybe store the picture like this too, because currently it only stores it like this when I use ``instaloader.py @user --no-posts`` it stores it like this:
```
/{username}/
	id
	..._profile_picture.jpg
```
the thing is, I have an structure, to parse it into a database for a little webapp for me at home here, because my instagram app doesn't work correctly sometimes, that sorts the posts like this for parsing:
```
/:feed/
	{owner_id}/
		year/
			month/
				day/
					2010-04-20_04-20-00_username.jpg
and what i want:			2010-04-20_04-20-00_profile_pic.jpg
```
maybe we can add the functionality, that it can store it like this too... so that the profilepicture can be stored like in the example above. I know, there is json.xz and so on also, but I did not include it here in this examples because of simplicity.

so in short: its a foldername problem.

**Describe alternatives you've considered**

If this is not possible, maybe make it possible, that ``instaloader.py @user`` will be possible to use same filestructure like the ``instaloader.py :feed`` ... it does this at the moment ``/username/{content}``

**If the feature request is accepted, would you be willing to submit a PR?**

Yes / No _(Help can be provided if you need assistance submitting a PR)_

Ehhmm... I don't know what PR is currently... but if you tell me maybe. 

**Additional context**
Add any other context about the feature request here.

I need this "Permanent" Structure of filenames, because the database that runns in combination with instaloader keeps only static paths to the files on the webserver (running local here).

(please also see https://instaloader.github.io/contributing.html for how to suggest a feature)

**Comment by aandergr** [comment]
This would be a typical case for using [Instaloader as a module](https://instaloader.github.io/as-module.html) rather than its CLI, since it is a very specific use case.
