### ISSUE TITLE
Scrape stories with hashtag & getting metadata

### ISSUE THREAD

**Issue by mcmenkes** [instaloader/instaloader#455]
How can i scrape stories with a specific hashtag?

e.g. `instaloader --login user --stories-only "#myhashtag"`

AND getting metadata for these stories. 

Thanks.

#instaloader #awesome #stories #hashtags ;-)

**Comment by ledgreve** [comment]
I am not sure whether it will give you exactly what you need, but you could try this : 
`instaloader --login user --stories-only --post-metadata-txt="{owner_username};{date_local};{date_utc};{likes};{comments}." --filename-pattern={date_utc:%d-%m-%Y}_UTC_{profile} “#xxx”`

**Comment by maxiannunziata** [comment]
hi guys, i need this implementation
