### ISSUE TITLE
Instaloader extracts empty posts - please help!

### ISSUE THREAD

**Issue by ledgreve** [instaloader/instaloader#456]
Hello!

I am extracting instagram _**posts with a certain hashtag**_ (f.e. "bachmannpreis") via the command line of my computer. I use following code:

 `instaloader --no-pictures --no-videos --no-compress-json --no-profile-pic --post-metadata-txt="{owner_username}\{caption}\{date_local}\{date_utc}\{likes}\{comments}\\\" --filename-pattern={date_utc:%d-%m-%Y}_UTC_{profile} “#bachmannpreis”`

As you can see, I am extracting the caption in the metadata. 

Everything works just fine, _but_ I noticed that Instaloader extracted a large number of posts for this hashtag that contain _no caption_, although I am looking for posts _with a caption containing a certain hashtag_. These posts have no caption and therefore also _do not_ contain the tag I am looking for. 

I don't understand why these posts were extracted in my search for a specific hashtag if they _do not_ actually contain this hashtag. Could someone explain why instaloader is extracting these wrong/useless posts? And how can I prevent this? 

Thank you in advance!

**Comment by aandergr** [comment]
Posts match that hashtag search if their caption or any of the comments contains the given hashtag. If you only want to include posts that have the hashtag in their caption you could do
```
instaloader ... --post-filter='"bachmannpreis" in caption_hashtags' '#bachmannpreis'
```
