### ISSUE TITLE
Download Top X comments from a post

### ISSUE THREAD

**Issue by amitupreti** [instaloader/instaloader#457]
**Provide us a use case of the feature**
It is very useful when we have to get the top comments from a post. In instagram browser/app, the comments are sorted by their popularity i.e top comments appear at first. But with instaloader we pull latest comments first.

**Describe the solution you'd like**
Option 1 : add param in `get_comments` function to indicate if we want top post or post by date

**Describe alternatives you've considered**
I browsed through snippets given in the documentation. We can also use the same logic as we used for top posts. But this would mean that we iterate through all the comments and use a lot of requests.

**If the feature request is accepted, would you be willing to submit a PR?**

Yes I already have a PR ready.

One solution on code snippet
```py
from itertools import islice
from math import ceil

from instaloader import Instaloader, Post

SHORTCODE = 'B41c_1dlf3X'        # post to download from
X_percentage = 10    # percentage of comment that should be downloaded

L = Instaloader()

post = Post.from_shortcode(L.context, SHORTCODE)
comments_sorted_by_likes = sorted(post.get_comments(),key=lambda p: p.likes_count, reverse=True)

for comment in islice(comments_sorted_by_likes, ceil(post.comments * X_percentage / 100)):
    print(comment.text)
```

But again, in case of large number of comment in a post, We would be sending a ton of requests.

**Comment by nOOBIE-nOOBIE** [comment]
Alternatively if we just want to load the top 12 comments. we could do
`https://www.instagram.com/p/B07dk0OnnzE/?__a=1`
This will load the first top 12 comments that are displayed in browser.

What do you think?

**Comment by Thammus** [comment]
These 12 top comments you describe are only intended to be used as a preview. We do not see any possibility to implement this feature of providing the top x comments without first fetching all comments followed by sorting.

**Comment by Miracleikechi** [comment]
Nice one

**Comment by Miracleikechi** [comment]
Nice one

**Comment by Miracleikechi** [comment]
Nice one
