### ISSUE TITLE
How to incorporate proxies with my code (Instaloader python module)

### ISSUE THREAD

**Issue by jhjjj12** [instaloader/instaloader#459]
I was trying to find out how to incorporate proxies in my code and was directed to this webpage https://requests.kennethreitz.org/en/master/user/advanced/#proxies  . They tell me to do the following

     import requests

     proxies = {
       'http': 'http://10.10.1.10:3128',
       'https': 'http://10.10.1.10:1080',
     }

     requests.get('http://example.org', proxies=proxies)
How am I supposed to incorporate this in my code?
Here is my code so far

     import requests
     import instaloader
     L = instaloader.Instaloader()

     # Login or load session
     L.login(username, password)        # (login)

     # Obtain profile metadata
     profile = instaloader.Profile.from_username(L.context, "prada")

     # Print list of followees

     file = open("prada_followers.txt","a+")
     for followee in profile.get_followers():
          username = followee.username
          file.write(username + "\n")
          print(username)

     file.close()

**Comment by Axomme87** [comment]
I'm also interested in this question because I think that all the errors I get at scraping instagram stories might be  because I'm reaching an instagram limit of some kind. I'm wondering if using proxies and the do_sleep() method makes my life easier because I have a huge load of requests for thousands of influencers periodically.

**Comment by fer0m** [comment]
Hi all! I found a solution. 
It's best for developers to add this to the library.

But local solution might be this:
nstaloadercontext.py -> def login (line 178) ->line 199.

`login = session.post('https://www.instagram.com/accounts/login/ajax/',
                             data={'password': passwd, 'username': user}, allow_redirects=True)`

Just add a variable, like here:

`login = session.post('https://www.instagram.com/accounts/login/ajax/',
                             data={'password': passwd, 'username': user}, allow_redirects=True,
                             proxies=proxies)`

and variable proxies:

```
proxies={
'http':'YOUR PROXY',
'https':YOUR PROXY
}
```

That all :)

**Comment by asimejaz14** [comment]
@fer0m Just read your solution. Did you try it? Did it work? What if I have multiple proxies? Like for example I want to get all the followers(50,000) of a user, this program stops for 10 mins after every 1000 requests. I would like to use multiple proxies in this case to avoid waiting for 10 mins.

**Comment by harshamv** [comment]
@fer0m when you install it via pip3 how can I change the settings inside `instaloadercontext.py`

**Comment by geekysid** [comment]
Any Idea how to add rotating residential proxy???

**Comment by evilgenius786** [comment]
Still no answer?

**Comment by RamilaSun** [comment]
how use with tor?

**Comment by vanishinggradient** [comment]
`
proxies = {}

# # in case proxy is from free-proxy-list
# proxies = {
# 	'http': f"http://{proxy}",
# 	'https': f"https://{proxy}"
# }

# # in case of proxy broker
# parsed = urlparse(proxy)
# proxies = {
# 	'http': f"http://{parsed.hostname}:{parsed.port}",
# 	'https': f"https://{parsed.hostname}:{parsed.port}"
# }

# # in case of tor proxy running on localhost
# proxies = {
#     'http': 'socks5://127.0.0.1:9050',
#     'https': 'socks5://127.0.0.1:9050'
# }
`

`loader.context._session.proxies = proxies`

is how used to do it 4-5 months

**Comment by vic2nik** [comment]
Hello, I have the solution to rotate proxies:

in instaloader.py (in the current version on row 593) add proxies argument to def login:
  def login(self, user: str, passwd: str, proxies: dict) -> None:

and add proxies to the calling of self. context.login (row 601):
  self.context.login(user, passwd, proxies)

then go to in instaloadercontext.py and update def login there (row 194):
  def login(self, user, passwd, proxies)

and add proxies argument to the calling of session.post() (row 222):
  login = session.post('https://www.instagram.com/accounts/login/ajax/',
                             data={'enc_password': enc_password, 'username': user}, allow_redirects=True, proxies=proxies) 

After that, you can do your script proxies in this easy way. For example:

proxy = 'http://125.43.22.66'
proxies = {'http': proxy,  'https': proxy}

loader.login(login_name, psswd, proxies=proxies)

That's it :)

**Comment by thebeautyofcoding** [comment]
Hey this looks like a great solution. However, when trying it, nothing has changed for me, still getting:
`    raise ConnectionException("Login error: Unexpected response, this might indicate a blocked IP.")
instaloader.exceptions.ConnectionException: Login error: Unexpected response, this might indicate a blocked IP.`
If the proxy worked with instaloader, they shouldnt be able to still block me, right?

**Comment by thebeautyofcoding** [comment]
Sometimes I am also getting:
`   raise ConnectionException("Login error: \"{}\" status, message \"{}\".".format(resp_json['status'],
instaloader.exceptions.ConnectionException: Login error: "fail" status, message "".`

**Comment by igorcspm** [comment]
InstaloaderContext uses a request.Session object behind the scenes, i guess you can just set proxies like that:
L = Instaloader()
L.context._session.proxies = {'http': proxy,  'https': proxy}

**Comment by sibrcode** [comment]
Tried what igorcspm mentioned, but didn't seem to have any effect.

This did work for me though:

`import os`
`os.environ["HTTPS_PROXY"] = 'http://proxy.domain.com:443'`

**Comment by kalyuzhin** [comment]
Is there any solution?

**Comment by zakrian07** [comment]
how to disble verify ssl ?

**Comment by zakrian07** [comment]
some resedential proxies need ssl i could not find a way how to disable verify ssl ERROR:root:An error occurred while fetching user info: JSON Query to api/v1/users/web_profile_info/?username=eruner89: HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/users/web_profile_info/?username=eruner89 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

**Comment by brunohaid** [comment]
If you want to add your proxies outside of instaloadercontext.py via `L.context._session.proxies` as described by @igorcspm above, and not mess with your environment variables either, you still need to add

> `new.proxies = session.proxies.copy()`

to the `copy_session()` function at the top (line ~24) of instaloadercontex.py. Instaloader creates a new session regularely to get data, but only copies over a couple of things like headers and cookies, but not the proxies. Might be worth adding to the official distribution.

**Comment by graceshaoy** [comment]
When I tried 
`os.environ["HTTP_PROXY"] = proxy_url
os.environ["HTTPS_PROXY"] = proxy_url`
I immediately get a 401.

Basically, my code does
`os.environ["HTTP_PROXY"] = proxy_url
os.environ["HTTPS_PROXY"] = proxy_url

source = instaloader.Profile.from_username(L.context, username)
while not finished:
   post_iterator = source.get_posts()
   post_iterator = takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, post_iterator))
   for i,post in enumerate(post_iterator):
       post_data = get_post_data(username, post)
`

I also tried removing the `os.environ` lines and using 
`L.context._session.proxies = {
        'http': f'http://{username}:{password}@{endpoint}',
        'https': f'http://{username}:{password}@{endpoint}'
    }`
I also immediately get a 401.

**Comment by instasck** [comment]
anything changed now ? I get 429 almost all the time

**Comment by brunohaid** [comment]
Same here.

**Comment by instasck** [comment]
I used a more realistic browser and bigger IP pool
