### ISSUE TITLE
Not all comments scraped

### ISSUE THREAD

**Issue by MoroZvlg** [instaloader/instaloader#460]
Hi! Can you help me, please? Why I get only 100 comments instead of 500+ that exists (post: https://www.instagram.com/p/B4rStghnt_h/)
options that I used: instaloader --comments -- -B4rStghnt_h

**Comment by arkwismb** [comment]
Also running into this issue. For example, `post.comments` returns 1244 total comments count but `get_comments()` only pulled 790.

**Comment by Thammus** [comment]
It seems like Instagram changed something concerning comments in their web interface. We tested several posts, both logged in and anonymous. In all cases Instaloader fetches all the comments that are available through the web interface. It is sad to see that there are posts that do not have all the announced comments browsable there anymore. However, the official Instagram app is still able to browse all those comments, so there is still hope that Instaloader will be able to scrape all the comments again through the mobile API in the future.

**Comment by shepurev** [comment]
Duplicate of https://github.com/instaloader/instaloader/issues/680#

I suppose methon dosnt return comments written in response to other comments.
