### ISSUE TITLE
To bash loop or not + multiple instances/profiles at once?

### ISSUE THREAD

**Issue by sotiris-bos** [instaloader/instaloader#462]
Hello! I am currently running a bash loop for instaloader but I read at https://github.com/instaloader/instaloader/issues/313 that I don't have to.

Is there any benefit in not running it as a loop?

Also, is there any way to speed up synchronization of multiple profiles?

Thank you

**Comment by psylenced** [comment]
If you're not running it in a loop (with error checking), that means that if a profile gets multiple 429s it'll skip that profile (after 3 I believe).

Currently best way is:

* Split into segments
* Attempt segment
  * If successful - sleep and try next segment
  * If 429 detected - sleep longer and then repeat same segment.
