### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by omtspain** [instaloader/instaloader#463]
I would need some help for the code.
I need to extract the following information into an excel 
1. Likes
2. Post caption 
3. Picture 

Thank you

**Comment by ledgreve** [comment]
Hello! Are you working with the command line option? I might be able to help (somewhat) with that, but I never got the python module to work, so I can't help you with that version. And do you want to extract this information about pots with a certain hashtag or posts belonging to a specific profile?

**Comment by omtspain** [comment]
I need to download the posts between august 2019 to December 2019 for 15 different posts of 40 profiles.
Would be awesome if you can help us.
