### ISSUE TITLE
No rate-control for is_html_query

### ISSUE THREAD

**Issue by pjw91** [instaloader/instaloader#464]
**Describe the bug**
"JSON Query to &lt;account&gt;/: 429 Too Many Requests [retrying; skip with ^C]"

**Expected behavior**
Rate control when querying account.

**Instaloader version**
4.2.10

**Additional context**
In [InstaloaderContext.get_json()](https://github.com/instaloader/instaloader/blob/v4.2.10/instaloader/instaloadercontext.py#L335), queries are categorized into 3 groups: `is_graphql_query`(L348), `is_iphone_query`(L349), and `is_html_query`(L377).

However, only the former 2 groups are rate-controlled (L353-L356, L409-L412).

That is, the `html_query` makes `max_connection_attemps` without any `sleep()`.

Moreover, queries not belong to those groups (if any) are not rate-controlled either.

**Comment by Thammus** [comment]
The provided error message indeed indicates that the 429 error occurred during fetching of a `html_query`. However, we are not able to reproduce any 429 errors for non rate-controlled queries and thus have no reason to handle the HTML-queries in question as rate-limited.

With a 429 response a server condemns too many requests and it might not be the best behavior to directly retry the full amount of attempts. Anyway, without further knowledge of the rate limiting for this kind of request, we do not know how to determine an appropriate sleep time between request attempts.

**Comment by aandergr** [comment]
Recent extensive testing on our side showed that there are indeed rate limits for the endpoints that are neither graphql nor iphone endpoints, and we should address these, investigating the rate limits and implementing rate controlling.

Thanks for reporting!
