### ISSUE TITLE
URLOPEN Error 101 in AWS EC2 INSTANCE

### ISSUE THREAD

**Issue by Axomme87** [instaloader/instaloader#466]
I'm scrapping the stories of certain instagram profiles at a time and I get this urlopen() error 101 Network unreachable quite often and all my scrappers stop. What could be the reason for this ?

"
L.get_stories(instagram_ids)  --->
stories = self.context.graphql_query("bf41e22b1c4ba4c9f31b844ebb7d9056", {"reel_ids": userid_chunk, "precomposed_overlay": False})["data"]  --->
resp_json = self.get_json('graphql/query', params={'query_hash': query_hash,  'variables': variables_json}, session=tmpsession)  --->
if resp.status_code != 200:  --->
except (ConnectionException, json.decoder.JSONDecodeError, requests.exceptions.RequestException) as err:
"

Is it because the AWS's EC2 instance network is crappy ?

**Comment by aandergr** [comment]
Looks like a network problem.
