### ISSUE TITLE
--[post|storyitem]-metadata-txt Output split into multiple lines

### ISSUE THREAD

**Issue by nowag** [instaloader/instaloader#470]
Hi!

When creating metadata txt files I want to have the output splitted in multiple lines. So logically speaking I'd have to use a linebreak to achieve this. Using `\n` either in parentheses or without does not lead to the desired result but rather gets interpreted as text.

Ex.:
`--post-metadata-txt={caption} \n {likes}`
`--post-metadata-txt="{caption}" \n "{likes}"`
`--post-metadata-txt="{caption} \n {likes}"`

How could I achieve this?

Thank you already. :)

**Comment by pjw91** [comment]
If you're using bash (not Windows, not sh), try `--post-metadata-txt=$'{caption} \n {likes}'`.

(I didn't test it.)
