### ISSUE TITLE
Experiencing difficulty with obtaining story items

### ISSUE THREAD

**Issue by rinku-27** [instaloader/instaloader#476]
Hello. I'm experiencing general difficulty obtaining story items in a manner I'd like (stories from specific users and even being unable to prevent json files from generating).

I've been running batch files that run the commands from txt files. One such file as written below:
--login=
--password=
--filename-pattern=[{profile}][Story]{date_local:[%Y-%m-%d](%a@%H;%M)}
--no-metadata-json 
:stories

gave weird results. An error I got was "--no-metadata-json : 404 Not Found" and the json files ended up being generated. Moving that command to being placed between the password and filename resulted in a different error: "instaloader: error: unrecognized arguments: :stories".

I'm also not getting all the story items of some users. The command prompt states the "exists" message for these instances. I suspect in these cases the user uploaded those items at the same time, thus the naming scheme would be the same and instaloader would recognize the additional item as already existing and thus skipping it.

However, working around :stories and using --stories works (it does not skip anything). My problem with the latter method is that I think it sends too many requests (I get the "too many requests" message). [The most profiles I've attempted at once is under 120]

Additionally, I tried to filter out the story items to no avail. I tried variations like:
--storyitem-filter="owner_id (*number here*) | (*number here*)"
--stories-only

Couldn't get owner_username to work either. 
So generally, issues with getting specific stories in a manner I'd like. I'm running the latest version.

**Comment by Thammus** [comment]
The message "Too many queries in the last time. Need to wait xx seconds" is no problem if you are patient to wait the required amount of time until the task finishes and as long as you do not get any 429 errors.

The value for the storyitem filter needs to be a [Python boolean expression](https://docs.python.org/3/reference/expressions.html#boolean-operations). For example to filter for specific accounts you could use `--storyitem-filter="owner_username in ['account1', 'account2', 'account3']"`.
