### ISSUE TITLE
What is the best practice to minimize the 'too many queries.. wait for n seconds'?

### ISSUE THREAD

**Issue by giaccomgl** [instaloader/instaloader#477]
Hi, first of all my pleasure for the great project, I think it's the best for doing this kind of things.
I have a question:
I have a list of some thousands of users and I want to get all followings account verified.
The script works great. It returns me no problem, anyway I want to ask if there's any way to make it better:
There are some times in which it returns frequently 'too many queries... wait for n seconds'.
I use to put a pause of 180/190 seconds among every user, and then a little sleep (throught do_sleep()) when I check if the account is privated or not. then starts the following scrape.
How could I change my code in order to minimize the number of 'too many queries' or to minimize the moment of waiting?
I hope you answer well. If I get an answer that really helps me I will be happy to do a donation 'cause the project looks great.
Thank you in advice.

That's the code, on pastebin:
[https://pastebin.com/Yd1ENcrF](url)

**Comment by psylenced** [comment]
I've found the following works best for me (using fast-update).

Split private and public profiles.

Private profiles: 
* Download 2 profiles
* Sleep 340 seconds

Public profiles:
* Create 2 dummy users and alternate between them
* Download 5 profiles
* Sleep 320 seconds

**Comment by giaccomgl** [comment]
What you mean by ‘two dummy users’?

Il giorno lun 16 dic 2019 alle 03:10 Chris <notifications@github.com> ha
scritto:

**Comment by psylenced** [comment]
The rate limiter appears to be on username, not IP address.

So if you create 2 (or more) new users, without any followers - you can log in and use those dummy accounts to speed up the process.

Won't work on private profiles because you arent following them, but for public/open it works fine.

That's also why i split them - i run both the above processes (private /  public) at the same time.

**Comment by rinku-27** [comment]
@psylenced Is there a way to instead limit the queries per profile? Some profiles have 300+ images and I usually just need the x recent images. Is there a way to have the program check the x-most recent images of a profile only?

**Comment by psylenced** [comment]
I use fast-update so it stops on first duplicate.

Depends if you're updating the same profiles or completely new ones. If you have a look through the options there might be something to help you.

**Comment by 1keyz1** [comment]
@psylenced How do you set the download 5  users/ sleep 320 seconds?

**Comment by psylenced** [comment]
@1keyz1 I do it manually. 

1. Split my master user list into smaller files of 5 lines each . (using gnu `split` utility)
2. Have a counter that runs a loop from 0..999
3. Run instaloader on `split.000`
4. Run `sleep` utility for 320 seconds
5. Increment counter
6. Repeat until file doesn't exist.
