### ISSUE TITLE
Reducing posts downloaded to prevent "Too many requests ... wait n seconds"

### ISSUE THREAD

**Issue by rinku-27** [instaloader/instaloader#480]
Some profiles have many posts, sometimes crossing a 1000, which results in a lot of server requests. I am interested in only downloading the first n posts of any profile. 

Ideally, I'd like to ONLY download all posts from a particular date, which I can do. However, the program still checks the remaining images and each <skipped> result is a server request wasted. I'd like to reduce these "skipped" results by enabling the program to move on to the next profile.

So for example:
Profile A has 900 posts. I want all their posts from December 1st 2019, which would be 3.
When the program reaches the 4th post, it identifies the rest are irrelevant and moves on to Profile B. It'll look something like:

"Retrieving posts from profile Bob
[1/900] downloaded
[2/900] downloaded
[3/900] downloaded
[4/900] skipped
Retrieving posts from profile Asa
[1/60] downloaded
..."

Is this possible?

**Comment by Showmaster3000** [comment]
As described in https://instaloader.github.io/basic-usage.html#filter-posts you can use the following parameters:

instaloader --post-filter="date_utc >= datetime(2019, 12, 1)" targetprofile

**Comment by rinku-27** [comment]
> As described in https://instaloader.github.io/basic-usage.html#filter-posts you can use the following parameters:
> 
> instaloader --post-filter="date_utc >= datetime(2019, 12, 1)" targetprofile

Yea, I've explained that I specify a date to download pics from, unless I'm doing something wrong. It states the rest are skipped, but I think each of those skipped are still a server request wasted?

**Comment by arthuranst** [comment]
If you found a solution, I would be very interested about it!

**Comment by aandergr** [comment]
> Ideally, I'd like to ONLY download all posts from a particular date, which I can do. However, the program still checks the remaining images and each result is a server request wasted.

https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period

I think this code snippet might do what you want.
