### ISSUE TITLE
instaloader in cronjob not working

### ISSUE THREAD

**Issue by Octenisept** [instaloader/instaloader#485]
Hello everyone,

my instaloader is running fine under Linux and from within the shell (online). However, I'm a little desperate, as I cannot get it to work with a cronjob to run every X minutes/hours/etc.

I've installed instaloader via 
`pip3 install instaloader`

Made a simple test via the shell with
`instaloader --login=your_username profile [profile ...]`
which created the profile directory in my corresponding path and downloaded the files.

Afterwards I've created the sessionfile via
`instaloader --login=your_username --sessionfile=/home/user/sessionfile`

To test if everything works as I wish, I tested the first request again, but with the sessionfile now
`instaloader --login=your_username --sessionfile=/home/user/sessionfile profile [profile ...]`
which does also work correctly. It does also run correct, if I apply the `--quiet` option while running online.

However, it doesn't work if I create a bash file to run from within crontab. My bash file contains the following simple lines:
`echo "script started"`
`instaloader --login=your_username --sessionfile=/home/user/sessionfile profile [profile ...] --quiet`
`echo "script finished"`
The first and third line is to test, whether the bash script is called correctly.
_Edit:_ What might be important at this point is the fact, that when running the bash file via `sh bash.sh` instaloader is called and executed successfully.

In crontab it looks like this
`* * * * * /home/user/cron.sh > /home/user/testlog.log`

The testlog.log file is written. However, instaloader is obviously never called correctly.

I'd appreciate any help, as to how to solve my issue.

Thanks a lot!

**Comment by DigiOhhh** [comment]
Mine isn't working as well. Python raises an exception: 
`Traceback (most recent call last):
  File "/usr/bin/instaloader", line 11, in <module>
    load_entry_point('instaloader==4.2.10', 'console_scripts', 'instaloader')()
  File "/usr/lib/python3.8/site-packages/instaloader/__main__.py", line 401, in main
    _main(loader,
  File "/usr/lib/python3.8/site-packages/instaloader/__main__.py", line 81, in _main
    instaloader.load_session_from_file(username, sessionfile)
  File "/usr/lib/python3.8/site-packages/instaloader/instaloader.py", line 414, in load_session_from_file
    self.context.load_session_from_file(username, sessionfile)
  File "/usr/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 167, in load_session_from_file
    session.cookies = requests.utils.cookiejar_from_dict(pickle.load(sessionfile))
_pickle.UnpicklingError: could not find MARK`

**Comment by pjw91** [comment]
Make sure `instaloader` in `$PATH`.

Generally speaking, the `$PATH` of a cronjob does not contains `$HOME/.local/bin`.
If your instaloader is in venv, `~/.local/bin` (eg. pip install --user), it cannot be found.

You may want to use
`* * * * * /home/user/cron.sh > /home/user/testlog.log 2> /home/user/testlog.err`
to see the error message.
It might look like "sh: instaloader: command not found".

**Comment by Octenisept** [comment]
Hello Patrick,

thanks a lot. First  I did 
`* * * * * /home/user/cron.sh > /home/user/testlog.log 2> /home/user/testlog.err`
and received the error message you mentioned
`sh: instaloader: command not found`

I've then added these lines to my crontab
```
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:$HOME/.local/bin
```

Works now! Thanks a lot!
