### ISSUE TITLE
How can I set the download-location/path?

### ISSUE THREAD

**Issue by Akashic101** [instaloader/instaloader#486]
I couldn't find any info in the documentation for this. If I want it to download for example to my desktop how would I do that?

**Comment by shawnbarton** [comment]
You can use --dirname-pattern for this.

[](https://instaloader.github.io/cli-options.html#how-to-download)

**Comment by Akashic101** [comment]
I think I am doing something wrong, it only stores the profile-pic, the .json for it and the id in the specified folder if I do this:
`instaloader account --dirname-pattern=C:\Users\Desktop\test`

What am I missing?

**Comment by shawnbarton** [comment]
You're missing the replacement pattern.
``--dirname-pattern=/path/to/main/directory/{profile}``

**Comment by Akashic101** [comment]
So it's partially working now, it creates new folders where it's storing everything, but it's still in the main directory.

`instaloader account --dirname-pattern=C:/Users/Desktop/test/{profile}`
creates following folder-structure: C:\Users\C꞉\Users\Desktop\test\account

How would that argument look like if I would like to download them to my Desktop? That's the one thing I can't figure out

**Comment by shawnbarton** [comment]
It looks like your path isn't complete. Try `C:\Users\your.username\Desktop\`?

**Comment by Akashic101** [comment]
I knew my username was missing, this was simply a pre-caution by me. I directly copied the path from the windows-explorer, All it does when using that command is download the profile-pic, the id and the .json, that's all, The rest still goes to the instaloader-folder
![explorer_NEgmFDACRh](https://user-images.githubusercontent.com/39961794/72081457-cec01c00-32fe-11ea-9c9e-9798e7b6cb15.png)

**Comment by BubiBalboa** [comment]
Same issue here. Seems like `--dirname-pattern` isn't working properly on Windows.

**Comment by theFilipko** [comment]
I had the same issue on the Windows platform. The issue is on the "instaloader.py" on the line 110: `ret = ret.replace(':', '\ua789').replace('<', '\ufe64').replace('>', '\ufe65').replace('\"', '\uff02')` where they change the ':' character for the unicode one. They mention that with this they have solved the issue [#84](https://github.com/instaloader/instaloader/issues/84) but now it confuses the Windows if you put the absolute path with "C:/..." because it changes the regular character for that unicode one. For my purpose I just removed this `.replace(':', '\ua789')` from that line and it works!!! Hope it will help you too.

**Comment by simasima121** [comment]
How do you overwrite this when using the module? `download_post` Unions the str you give with your Path, not sure how to overwrite.

Thanks in advance.

**Comment by EmmanuelAdeiza** [comment]
I am having an issue. How do I specify that I want to upload the scraped images to somewhere like cloudinary instead of my local PC ?
please help

**Comment by GulShow** [comment]
> I am having an issue. How do I specify that I want to upload the scraped images to somewhere like cloudinary instead of my local PC ? please help

Did you solve this problem?

**Comment by Akashic101** [comment]
As far as I know Instaloader does not provide an option to cloud-services, so this would have to be done manually after the files have been downloaded

**Comment by EagerCadet11** [comment]
i am a newbie can someone guide me how to change the default folder for all downloads ?

**Comment by karpuzikov** [comment]
> i am a newbie can someone guide me how to change the default folder for all downloads ?

Hi, i finally figured out. in the terminal type "cd" and chosen path for example
`cd C:\test`
press enter
after this use instaloader as usual
