### ISSUE TITLE
--stories --highlights --tagged --no-captions --no-metadata-json -F not working  (with login)

### ISSUE THREAD

**Issue by Catralitos** [instaloader/instaloader#487]
Currently i try the following command:

instaloader --login=USERNAME --password=PASSWORD --stories --highlights --tagged --no-captions --no-metadata-json -F PROFILE

and I get the following error:
Loaded session from /tmp/.instaloader-USER/session-USERNAME.
JSON Query to graphql/query: HTTP error code 500. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 500. [retrying; skip with ^C]
Fatal error: JSON Query to graphql/query: HTTP error code 500.

I'm running on an Ubuntu shell in Windows 10, it's worked before and this is the most recent version so I don't know why it stopped working.

Anyone know why? Thanks in advance.

**Comment by rinku-27** [comment]
I'm experiencing this problem as well. However, I cycle through three different accounts. The account with the most profiles to download from is the only one giving this error. Not sure if it's related, but when I explore this account on desktop the home feed is not loading fully. Last night, no posts were loading up. This morning, the first 6 or so posts loaded, but beyond that it loads forever.

**Comment by Catralitos** [comment]
Apparently it was because I was logged in on that account on the browser, when I shut it off it worked.
