### ISSUE TITLE
Scrape suggested users / similar users for a given profile?

### ISSUE THREAD

**Issue by ianscottknight** [instaloader/instaloader#489]
On Instagram's app you can click the arrow next to the follow button on a user's profile and then receive a list of similar profiles determined by Instagram. Is there a way to scrape these suggestions with Instaloader?

**Comment by aandergr** [comment]
We implemented this feature with one of our latest commits, and it will be included in the upcoming version, Instaloader 4.4. To already try it out, upgrade Instaloader with:

```
pip3 install --upgrade git+https://github.com/instaloader/instaloader@v4.4-dev
```

**Comment by ianscottknight** [comment]
Nice, my teammate and I will try it out. Thanks!

**Comment by nullsaint** [comment]
`import instaloader
from instaloader import Profile
L = instaloader.Instaloader()
L.login('******','*******')
profile = Profile.get_similar_accounts('profile_name')
for i in profile:
    print(i.username)`

Tried this way. Didn't work. Can someone help with the code?

**Comment by the-helel** [comment]
Can You give me sample pthon code to get similar accounts using instaloader

**Comment by ThomHollands** [comment]
Hi what is the target to scrape these suggestions? I can't seem to find it in the docs. Thanks!
