### ISSUE TITLE
Changed profiles are not downloaded

### ISSUE THREAD

**Issue by pjw91** [instaloader/instaloader#491]
**Describe the bug**
When a profile changed from `p_old` to `p_new`, it logs:
```
Trying to find profile p_old using its unique ID XXXXXX.
Profile p_old has changed its name to p_new.
...
Downloading 3 profiles: a b c
```
and move the directory `p_old` to `p_new`.

**To Reproduce**
`instaloader p_old a b c`

**Expected behavior**
It should download 4 profiles: a, b, c **and** p_new.

**Instaloader version**
4.2.10

**Comment by aandergr** [comment]
We cannot reproduce this. In our case, after renaming a profile folder and running Instaloader again with the folder's name as parameter, Instaloader renames the folder back to the profile's current name as expected and downloads it along with all given profiles.

Please feel free to reopen this issue if there's new information regarding this.

**Comment by pjw91** [comment]
You're correct.
However, I need to "run it again" with new profile name.

As Instaloader does know the profile changing, I would expect it to download the new profile in the same invocation.
