### ISSUE TITLE
How can I view my Instagram backup data in a friendly way?

### ISSUE THREAD

**Issue by minanagehsalalma** [instaloader/instaloader#494]
recently i have downloaded a backup of my Instagram account ...

and the zip file contained a lot of ".json" files and i have no idea how to view

it like... the way that Instagram did
![5xQkq](https://user-images.githubusercontent.com/20546638/72681851-4268e280-3ad0-11ea-9fae-0593955412bf.png)
I think it's an important feature ... And it's not available anywhere else ... So you would be the first to do it !

**Comment by minanagehsalalma** [comment]
tell that to @aandergr

**Comment by mainigautam** [comment]
Have a Look (https://github.com/mainigautam/instagram_backup_manager)

**Comment by minanagehsalalma** [comment]
> Have a Look (https://github.com/mainigautam/instagram_backup_manager)

thanks mate but it needs some optimization.

**Comment by mainigautam** [comment]
> > Have a Look (https://github.com/mainigautam/instagram_backup_manager)
> 
> thanks mate but it needs some optimization.

Yes I Know , It's like sprint code of 2-3 days to get it working to see some messages, wasn't intended for public use but i thought it would be good to share . btw u used ? any suggestions where the optimization is required . except for setting this up . i'm working in it

**Comment by minanagehsalalma** [comment]
> any suggestions where the optimization is required . except for setting this up . i'm working in it

the setup needs to be reduced ... it produces tons of file makes it so annoying when moving or copying the folder.

**Comment by mainigautam** [comment]
> > any suggestions where the optimization is required . except for setting this up . i'm working in it
> 
> the setup needs to be reduced ... it produces tons of file makes it so annoying when moving or copying the folder.

Yes , i totally get it , Thanks i'll try work on it . Also Convert this into Android App for further convinience

**Comment by minanagehsalalma** [comment]
> Also Convert this into Android App for further convinience

that would be really amazing too.

**Comment by mainigautam** [comment]
Try It Now , Made a lot of changes You'll see Yourself

**Comment by minanagehsalalma** [comment]
> Try It Now , Made a lot of changes You'll see Yourself
> 
> https://www.github.com/mainigautam/instagram_backup_manager
> 
> go for branch igbm-1.0 and follow Instructions hope you love it more this time

testing it now the setup seems to take forever

**Comment by minanagehsalalma** [comment]
@mainigautam still tons of files and takes long to install ( less than the first time so )

![image](https://user-images.githubusercontent.com/20546638/100025403-5caad580-2df1-11eb-8196-cace19dc511e.png)

but the interface is now better and good job on the upload zip file feature.

**Comment by mainigautam** [comment]
> @mainigautam still tons of files and takes long to install ( less than the first time so )
> 
> ![image](https://user-images.githubusercontent.com/20546638/100025403-5caad580-2df1-11eb-8196-cace19dc511e.png)
> 
> but the interface is now better and good job on the upload zip file feature.

Will be reduced this weekend
