### ISSUE TITLE
"Could not find "window._sharedData" in html response"

### ISSUE THREAD

**Issue by floodx** [instaloader/instaloader#495]
Hello,

tried to get it up and running on Ubuntu 18.04. First at all login with username and password is not possible, like it is described in [Login issue #472](https://github.com/instaloader/instaloader/issues/472).

I wanted to transfer my session Cookie from Windows machine, but there is also following error output if I download there:
`profile: JSON Query to profile/: Could not find "window._sharedData" in html response.`

Anyway it seems that I can't import this session cookie to the Ubuntu machine, because it I get:
`JSON Query to graphql/query: HTTP error code 403.`

**Comment by iliv** [comment]
I was able to download entire profile target twice on the same day, with and without --login option a few days ago. 

Today I can't download a single post using the profile target due to:

```
$ instaloader --login=myinstagramusername --geotags profile --stories
Loaded session from /tmp/.instaloader-iliv/session-myinstagramusername.
Logged in as myinstagramusername.
JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
profile: JSON Query to profile/: Could not find "window._sharedData" in html response.
Saved session to /tmp/.instaloader-iliv/session-myinstagramusername.

Errors occured:
profile: JSON Query to profile/: Could not find "window._sharedData" in html response.
```

However, downloading the :feed target still works.

What is wrong?

I'm running the most recent instaloader version 4.2.10 on Ubuntu 18 LTS.

**Comment by navjotjsingh** [comment]
Downloading works for me but keep hitting this error.

```
Errors occured:
profile: JSON Query to profile/: Could not find "window._sharedData" in html response.

```
Ubuntu 19.10 here.

**Comment by pvita** [comment]
Hello, I have the same problem with --login and profile target

**Comment by andreasnico06** [comment]
i'm having the same problem the last couple days, already update it but still same problem. If i delete my login session file it fix the problem but you need to delete it again to download another one which is a problem since instagram detect it as unusual login etc.

**Comment by jadc** [comment]
Same issue as well

**Comment by pvita** [comment]
Try to insert your mail as username, it should work.
