### ISSUE TITLE
Can't use --request-timeout N

### ISSUE THREAD

**Issue by ACBozzi** [instaloader/instaloader#500]
I'm trying to use the --request-timeout N option of instaloader.

I'm running the command bellow:

`instaloader "#deolhonoscorais"  --no-compress-json --no-captions --request-timeout 10`

The instaloader returns the following error:

`usage: 
instaloader [--comments] [--geotags] [--stories] [--highlights] [--tagged]
            [--login YOUR-USERNAME] [--fast-update]
            profile | "#hashtag" | %location_id | :stories | :feed | :saved
instaloader --help
instaloader: error: unrecognized arguments: --request-timeout 10`

Typing `instaloader --version` I get:
`4.2.10`

Link to documentation: https://instaloader.github.io/cli-options.html?highlight=timeout#cmdoption-request-timeout

**Comment by aandergr** [comment]
This feature is recently added and not yet included in a released version of Instaloader. To upgrade to the latest development state, where `--request-timeout N` works, do:

```
pip3 install --upgrade git+https://github.com/instaloader/instaloader
```

**Comment by ACBozzi** [comment]
When I running:

 `pip3 install --upgrade git+https://github.com/instaloader/instaloader`

The instaloader returns the following error:

`Cannot unpack file /tmp/pip-1oh7o78p-unpack/instaloader (downloaded from /tmp/pip-v_mkxi2p-build, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-v_mkxi2p-build`
