### ISSUE TITLE
Provide a way to set custom requests.Session object to override features like timeouts, and proxies

### ISSUE THREAD

**Issue by alexeysofin** [instaloader/instaloader#501]
**Provide us a use case of the feature**
Currently instaloader initializes custom requests.Session inside a InstaloaderContext, and passes request timeout though from instaloader.Instaloader.

What I want now, is to add proxies dict *only* for instaloader, because setting env variables may result in unnecessary use of proxy when other libraries make http requests, and we have to always ensure no_proxy is set properly, but this is quite fragile :)

**Describe the solution you'd like**
What I suggest to have a way of passing custom requests.Session right in instaloader.Instaloader.__init__

**Describe alternatives you've considered**
A different solution is to make a PR on each separate Session change like it has been with request_timeout.

**If the feature request is accepted, would you be willing to submit a PR?**

Yes

**Comment by aandergr** [comment]
Sounds good!

It needs to be considered that there is not only one place where a requests.Session object is generated. Instead, there are at least
- InstaloaderContext.get_anonymous_session()
- InstaloaderContext.load_session_from_file()
- copy_session()

So I think we cannot implement this by passing directly a custom session into Instaloader.init, rather it might be some kind of factory function or hook pattern. We are very open for any idea suggestions and PRs!
