### ISSUE TITLE
Define Download Directory for .download_hashtag when using module

### ISSUE THREAD

**Issue by vexersa** [instaloader/instaloader#502]
Hello, 

Please could someone indicate how to set the download directory when using Instaloader as a module when using loader.download_hashtag?

Thanks!

**Comment by aandergr** [comment]
Hello,

you can pass `dirname_pattern` and `filename_pattern` to the [Instaloader constructor](https://instaloader.github.io/as-module.html#instaloader-main-class).
Alternatively, you can change your working directory with [os.chdir](https://docs.python.org/3/library/os.html#os.chdir).
