### ISSUE TITLE
ProfileNotExistsException

### ISSUE THREAD

**Issue by AlexGouv** [instaloader/instaloader#504]
Hi, 

I am new to Instaloader and I am running into a problem when trying to pull in Bio information. We have scraped google for a list of Instagram handles for our accounts, unfortunately the data isn't perfect and some of the handles we have pulled in are no longer active(User has changed profile handle or deleted account). This causes the ProfileNotExistsException error to come up and stops pulling in the information for all subsequent accounts.

Is there a way to ignore this and continue pulling in the rest of the bios while just leaving this one blank?

Here is the code that is throwing me the error. _handles_ is the list of handles we have.
`bios = []
for element in handles:
    if element == '':
        bios.append('NULL')
    else:
        bios.append(instaloader.Profile.from_username(L.context, element).biography)`

I have tried using the workaround found in this forum(can't find the post) but it is not working for me. No errors, just not solving the issue. The code they suggested was:
`def _obtain_metadata(self):
        try:
            if self._rhx_gis == None:
                metadata = self._context.get_json('{}/'.format(self.username), params={})
                self._node = metadata['entry_data']['ProfilePage'][0]['graphql']['user']
                self._rhx_gis = metadata['rhx_gis']
            metadata = self._context.get_json('{}/'.format(self.username), params={})
            self._node = metadata['entry_data']['ProfilePage'][0]['graphql']['user']
        except (QueryReturnedNotFoundException, KeyError) as err:
            raise ProfileNotExistsException('Profile {} does not exist.'.format(self.username)) from err`

Thanks in advance!

**Comment by Daquisu** [comment]
You can catch the error and add a 'NULL' or just pass

```
except ProfileNotExistsException:
    bios.append('NULL')
```

or

```
except ProfileNotExistsException:
    pass # it ignores the ProfileNotExistsException error
```

**Comment by AlexGouv** [comment]
@Daquisu 

Thanks for the reply. Unfortunately when I do that the error does get suppressed but the loop stops. Do you know of any way around this?

**Comment by Daquisu** [comment]
@AlexGouv I'm glad to help

Use the try except inside the loop.
```
for post in posts:
    try:
        normal_routine()
    except:
        pass
```

Or with while:

```
while condition:
    try:
        normal_routine()
    except:
        pass
```
