### ISSUE TITLE
How could I properly slow down Profile.get_followers() ?

### ISSUE THREAD

**Issue by leprodude** [instaloader/instaloader#505]
I looked at the documentation, old issues here #118 , and the code snippets, but somehow still cannot figure out how I would properly slow down the get_followers() method.

When calling it on a 600 followers profile it worked, on a 90k profile it fails.

I create the session, login, and do the following:
```
>>> profile = instaloader.Profile.from_username(L.context, PROFILE)
>>> profile_followers = list(profile.get_followers())
```

Which gives me:
```
Too many queries in the last time. Need to wait 626 seconds, until 15:25.
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/instaloader/structures.py", line 745, in get_followers
    self._rhx_gis))
  File "/usr/local/lib/python3.7/site-packages/instaloader/structures.py", line 740, in <genexpr>
    yield from (Profile(self._context, node) for node in
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 483, in graphql_node_list
    data = _query()
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 465, in _query
    return edge_extractor(self.graphql_query(query_hash, query_variables, query_referer, rhx_gis))
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 450, in graphql_query
    session=tmpsession)
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 354, in get_json
    self._ratecontrol_graphql_query(params['query_hash'])
  File "/usr/local/lib/python3.7/site-packages/instaloader/instaloadercontext.py", line 316, in _ratecontrol_graphql_query
    time.sleep(waittime)
```

I'm wondering if looping over the profile.get_followers() generator object, paired with a sleep in each iteration would work, but then I would need to keep it running until the whole list is done, otherwise it will restart from the beginning...

Instaloader is supposed to limit requests automatically, yet what if I need to slow it down further?
Any ideas on how I could do that?

Thank you already for any help!

**Comment by leprodude** [comment]
Okay I went into the code for get_followers(), read up on 'yield' and generators.
It was simply enough to loop over the generator and add a timeout after each 50 followers (that's the count that get retrieved with each request).

So this is working for me so far:

```
try:
    counter = 0

    # for every one, save the basic info
    for follower in profile.get_followers():
        
        # every request should give 50 followers, so wait after each request 
        if (counter % 50 == 0):
            # print a counter 
            for remaining in range(int(TIMEOUT), 0, -1):
                sys.stdout.write("\r")
                sys.stdout.write("TIMEOUT: {:2d}S".format(remaining))
                sys.stdout.flush()
                time.sleep(1)

            sys.stdout.write("\r-----------------------\n")

        # console output
        print('Gathering list of followers...')
        print (f"username: {follower.username} userid: {follower.userid}")

        f = {}
        f["username"] = follower.username
        f["userid"] = follower.userid
        f["is_private"] = follower.is_private
        
        followers.append(f)

        # save files every time a new entry has been fetched, so progress doesn't get lost
        save_as_json(followers)
        save_as_csv(followers)

        counter += 1
            
except Exception as e:
    print(e)
    pass
```

I'm letting it run and see wether I hit the limits at some point.
If I do, I'll just increase my delay which is currently at 19 seconds.

**Comment by leprodude** [comment]
Okay I have hit the fabulous '429 too many requests' after gathering 485 profiles...

Does anybody have a solution for skipping the already retrieved ones when restarting?

**Comment by leprodude** [comment]
Okay, so I attempted to save these three parts per profile as I had looked at the uncomplete metadata of another download and saw these were in it without additional request.
```
        f["username"] = follower.username
        f["userid"] = follower.userid
        f["is_private"] = follower.is_private
```

Turns out that when I only save the username it works perfectly fine, currently doing 50 profiles ( == 1 request) with a 35s timeout and I have downloaded 60k profile names so far.

**Comment by roncam82** [comment]
@zerotraceme does this still works ? If yes can you share the complete code please ?

thanks

**Comment by zerotraceme** [comment]
@roncam82 haven't used it in ages and honestly no idea if it still works...
