### ISSUE TITLE
private profile is not opening

### ISSUE THREAD

**Issue by sanjaysahu3603** [instaloader/instaloader#506]
Your question here...
the private profiles cannot be opened through your code

**Comment by Showmaster3000** [comment]
You can download other private accounts as long as you are following them and they accepted that. And you need to login. It's just like if you use the normal app or browser.

**Comment by sanjaysahu3603** [comment]
> You can download other private accounts as long as you are following them and they accepted that. And you need to login. It's just like if you use the normal app or browser.

**Comment by sanjaysahu3603** [comment]
what's the point of following a private profile and downloading? lol . You need to scrape without following, that's the point.
