### ISSUE TITLE
Search with hashtag, download post contents(.txt) only 

### ISSUE THREAD

**Issue by snoop2head** [instaloader/instaloader#507]
## Search with hashtag, download post contents(.txt) only 

For the people who are interested in Natural Language Processing(NLP), like me, find Instagram attractive field to mine some data. Since NLP focused guys collects contents searched with keyword(hashtags), I am thinking of providing them with the following code as sample code to help them out. 

```python
import instaloader

def getContentsWithTags(searchKeywordTag, numbersOfPosts):
    #get contents only
    L = instaloader.Instaloader(download_pictures=False,
                                download_video_thumbnails=False,
                                download_videos=False,
                                download_geotags=True,
                                download_comments=False,
                                save_metadata=False)

    while numbersOfPosts > 0:
        for post in L.get_hashtag_posts(searchKeywordTag):
            L.download_post(post, target='#'+searchKeywordTag)
            numbersOfPosts-=1
            # print(numbersOfLoop)
            if numbersOfPosts ==0:
                break
```
As an output, directory will be established as "#searchKeywordTag". Inside of the directory, each search result(post contents) will be saved as text file.

<img width="380" alt="Screen Shot 2020-01-31 at 10 06 30 PM" src="https://user-images.githubusercontent.com/28736695/73541679-646e4780-4476-11ea-9017-2ac3e9721703.png">

**Comment by snoop2head** [comment]
What do you guys think? Anyone who utilizing Instagram as source of data for NLP ?

**Comment by Razafimahery** [comment]
Hi snoop2head, I am interested to use instaloader for Image Classification - to download pictures related to a given hashtag. Can you help me?

**Comment by snoop2head** [comment]
Hi @Razafimahery! 
Gladly. 
But are you referring to the issue https://github.com/instaloader/instaloader/issues/513#issue-560278040 that you recently posted?

**Comment by Razafimahery** [comment]
Hi @snoop2head 
I managed to solve this issue by adding parameter in the `instaloader.Instaloader()` function. How can I make sure to collect only 'streetart' image than come from a given public profile?
