### ISSUE TITLE
Constant 429 errors

### ISSUE THREAD

**Issue by stiflermt** [instaloader/instaloader#510]
Hi I seem to have encountered an issue with a new install, of constantly triggering 429 errors. Nothing is downloaded. I am able to download if I do not pass any credentials to the script (obviously exception being private profiles) has something changed in the API?

**Comment by stiflermt** [comment]
JSON Query to profile/: 429 Too Many Requests [retrying; skip with ^C]

**Comment by psylenced** [comment]
Wait 24 hours (or less) and it should work again.

You've most likely used too many API calls.

Anonymous has it's own counter - so you can run anonymous and logged in concurrently and they wont mess with each other.
