### ISSUE TITLE
Is it possible to get all the usernames who posted under a specific hashtag?

### ISSUE THREAD

**Issue by 1keyz1** [instaloader/instaloader#511]
realy need some help

**Comment by Daquisu** [comment]
`import instaloader

def get_usernames(hashtag_label):
    usernames = []
    L = instaloader.Instaloader()
    posts = L.get_hashtag_posts(hashtag_label)
    for post in posts:
        if post.owner_username not in usernames:
            usernames.append(post.owner_username)
    return usernames`

Every post has a 'owner_username' attribute. You can create a list of owner_usernames (usernames in the code above) and for every post verify if the owner_username is already in your list. Add the owner_username if it isn't in your list, do nothing if it is.

**Comment by 1keyz1** [comment]
@Daquisu Thank you very much. I'am not that advanced so it would be nice if you could show me your code for eg. "#cats". when I run this nothing happens and I'm not sure where to paste the hashtags in...

**Comment by Daquisu** [comment]
```
import instaloader

def get_usernames(hashtag_label):
    usernames = []
    L = instaloader.Instaloader()
    posts = L.get_hashtag_posts(hashtag_label)
    for post in posts:
        if post.owner_username not in usernames:
            usernames.append(post.owner_username)
        if len(usernames) == 100:
            break
    return usernames

print(get_usernames('cat'))
```

Prints the last 100 users who posted under #cat

**Comment by 1keyz1** [comment]
@Daquisu You're realy helping me out dude, thanks. I'am currently using this code couse its a bit faster:

```
from instaloader import Instaloader

HASHTAG = 'cats'

loader = Instaloader(
    sleep=False
)

for post in loader.get_hashtag_posts(HASHTAG):
    print(post.owner_username)

```


but i don't get how to avoid dublicates like you did. I'll tryed the `  if post.owner_username not in usernames: usernames.append(post.owner_username)`   but it doesn't work. Do you have any suggestions?

**Comment by Daquisu** [comment]
You can try:
```
from instaloader import Instaloader

HASHTAG = 'cats'

loader = Instaloader(
    sleep=False
)

users = []
for post in loader.get_hashtag_posts(HASHTAG):
    if post.owner_username not in users:
        users.append(post.owner_username)
        print(post.owner_username)
```
