### ISSUE TITLE
Switching ip address when using rotating proxies

### ISSUE THREAD

**Issue by alexeysofin** [instaloader/instaloader#512]
Instaloader heavily uses sleeps around the code, so if used with rotating proxies, the rate limiter does not consider the ip address from which the request was made, and it becomes really hard to catch the 429 errors and switch the ip address :)

How do you deal with that use case if that's appropriate?

**Comment by harshamv** [comment]
Were you able to do this?

**Comment by attajutt** [comment]
Yes... There shall be a way to change ip address per each request somehow.... This will bypass rate limitations plus we can multi thread a lot workload....
