### ISSUE TITLE
Implementation in Jupyter notebook

### ISSUE THREAD

**Issue by Razafimahery** [instaloader/instaloader#513]
Hello, could you please advise how to use instaloader in python module. I would like to use the following script: `$ instaloader --no-videos --no-metadata-json --no-captions "#streetart"` Jupyter notebook. Many thanks in advance for your help.

**Comment by snoop2head** [comment]
Dear @Razafimahery, I am here to continue our conversation at https://github.com/instaloader/instaloader/issues/507#issuecomment-582368320. 

Your question was following: 
> How can I make sure to collect only 'streetart' image than come from a given public profile?

In order to clarify your question, you want to collect images that captured with streetart only, right? For example, I assume you want to exclude [these kinds of images.](https://www.instagram.com/p/B8KL_gqBXuw/). With Instaloader, if you search with "#streetart" tag, every pictures that comes with the hashtag will be included in the search result(even though they don't contain portraits of streetarts). 

Am I right?

**Comment by Razafimahery** [comment]
@snoop2head 

That's correct, the picture I get are not very representative of 'streetart'. That is why I try to collect images from a profile. Do you have another idea? I appreciate your support.

**Comment by snoop2head** [comment]
@Razafimahery 

I will first approach it with metadata, which is json file that Instaloader provides, since it briefly describe about the picture. Will reply you, if I figure it out how to do it.

**Comment by Razafimahery** [comment]
@snoop2head 
Amazing. I look forward to your reply :)

**Comment by snoop2head** [comment]
Make python file to get instagram data 

```python
import instaloader

# download pictures, download json file, but don't compress json file.
L = instaloader.Instaloader(download_pictures=True,
                            download_video_thumbnails=False,
                            download_videos=False,
                            download_geotags=True,
                            download_comments=False,
                            save_metadata=True,
                            compress_json=False
                            )

# two arguments: keyword and number of files
def get_it(keyword,numbers_of_files):
    while numbers_of_files > 0:
        for post in L.get_hashtag_posts(keyword):
            # post is an instance of instaloader.Post
            L.download_post(post, target='#'+keyword)
            numbers_of_files-=1
            # print(numbers_of_files)
            if numbers_of_files ==0:
                break
        print("loop ended for " + keyword)

# sample function
get_it("streetarts",20)
```

Make another python file to sort and move images 
```python
import glob
import json
import shutil
import os

# using Instagram's image recognition: it is written on json file, with key of "__typename"
def discern_image_file(keyword):
    # read file list that is previously downloaded through get_it
    read_files_list = glob.glob("#"+keyword+"/*.json")
    print(read_files_list)
    write_files_list = []
    # open every json file, check whether it is streetart image
    # It seems like streetart image is either classified as "GraphSidecar" or "GraphImage" through Instagram image recognition
    for json_file_name in read_files_list:
        # open json file
        with open(json_file_name,'r',encoding="UTF8") as data_file:
            # read json file
            data = json.load(data_file)
            file_name = json_file_name[:-5]
            # print(data)
            if data["node"]["__typename"] == "GraphSidecar":
                print(file_name + " is streetarts image")
                write_files_list.append(file_name)
            elif data["node"]["__typename"] == "GraphImage":
                print(file_name + " is streetarts image")
                write_files_list.append(file_name)
            else:
                print(file_name + " is not streetarts image")
                pass
    # print(write_files_list)
    return write_files_list

def sort_and_move_image_file(keyword):   
    # change the source directory to your project directory
    # source = '/path/to/source_folder'
    source = "/Users/noopy/FitCuration/"
    dest = "/Users/noopy/FitCuration/" + "#" + keyword + "_sorted"
    os.mkdir(dest)
         
    all_image_file_list = glob.glob("#"+keyword+"/*.jpg")
    write_files_list = discern_image_file(keyword)
    print(all_image_file_list)
    print(write_files_list)
    for item in write_files_list:
        matching_list = [s for s in all_image_file_list if item in s]
        print(matching_list)
        for matching_item in matching_list:
            print(matching_item)
            shutil.move(source+matching_item, dest)

# discern image files only
# discern_image_file("streetarts")

# discern, sort, and move image files to separate directory
sort_and_move_image_file("streetarts")
```

It's not 100% accurate, but it utilizes Instagram Image Recognition feature which is known to be quite accurate.

**Comment by Razafimahery** [comment]
@snoop2head 

That's great, I can modify your code and adapt to my need. Just one question, please. How can I install the Python shutil module. I tried with pip and conda but it didn't work. Appreciate your help as always.

**Comment by snoop2head** [comment]
@Razafimahery 
shutil is part of standard Python3 library. You don't have to download it. Just
>import shutil

**Comment by Razafimahery** [comment]
@snoop2head 

I am using Google Colab and it does not seem to find the shutil.py in my Python 3.6 library. I think it's not installed.

**Comment by snoop2head** [comment]
@Razafimahery 
I think Google Colab is inadequate for your project. In order to maintain files and directory, Google Colab should be approached with different module, not shutil. It is as such: 

>from google.colab import drive
>drive.mount("/content/gdrive", force_remount = True)

Afterwards is quite complicated. I recommend to change your IDE to Pycharm.

**Next time, specify your developing environment in order to prevent miscommunication.** 

**Specify as such:** 
* Operating System: Windows 10 
*  IDE: Google Colab
* Python ver: Python 3.6.2
* Version of Package/Module: Instaloader v.4.2.10

**Comment by Razafimahery** [comment]
@snoop2head 
Sorry, I didn't know. I am new using Python. I learned R for Statistics, but I find Python easier for machine learning (codes are easier to understand).
I will install PyCharm and try it again.
