### ISSUE TITLE
Highlights in external folder

### ISSUE THREAD

**Issue by 9dc** [instaloader/instaloader#514]
**Describe the bug**
If i download profiles like this:

instaloader --login xxx --password xxx --fast-update --stories --highlights --no-metadata-json --dirname-pattern /home/insta/data/{profile} --no-video-thumbnails +/home/insta/data/usernames.txt

It downloads Highlights, but not in an external folder. It did it with the same command on another machine. Any ideas?

**Instaloader version**
4.2.10

**Comment by Thammus** [comment]
How exactly does the behavior differ on the other machine? Could you please provide us more information? For example, do both computers use the same OS?

**Comment by fishermansfriendsachet** [comment]
This happens on Windows as per this bug-

https://github.com/instaloader/instaloader/issues/514

I really hope that it gets resolved soon.

**Comment by aandergr** [comment]
> How exactly does the behavior differ on the other machine? Could you please provide us more information? For example, do both computers use the same OS?

Without the information @Thammus asked for, there is little chance for us to address this issue. Please reopen this once you can provide more input.
