### ISSUE TITLE
Having issues with a Private Account.

### ISSUE THREAD

**Issue by typothomas** [instaloader/instaloader#515]
Hi, I'm using instaloader for Windows 10.  Keep in my mind I'm new to this.

I'm having trouble downloading images from a private profile. I am able to successfully login into my account and attempt to download images from the private account.

Even though I'm logged in, it says "[Username]: --login=USERNAME required.". 

I don't know what is wrong. I would really appreciate it if someone would help me out.

**Comment by aandergr** [comment]
Do

```
instaloader --login=your_username profile_to_download
```

(specify both `--login` and the profile to download)
