### ISSUE TITLE
I keep getting "HTTP error code 500" 

### ISSUE THREAD

**Issue by adamkkkkkk** [instaloader/instaloader#516]
**Describe the bug**
After using a command to download my 'saved' Instagram posts,. I keep getting this error

**To Reproduce**
`instaloader --login USERNAME --fast-update --no-captions --no-metadata-json --no-video-thumbnails --filename-pattern="{profile} - {shortcode}" ":saved" --dirname-pattern={profile}
`

**Expected behavior**
To download my Instagram 'saved' posts

**Error messages and tracebacks**
Fatal error: JSON Query to graphql/query: HTTP error code 500.

**Instaloader version**
4.2.10

**Comment by nbmrjuhneibkr** [comment]
I'm getting the same error over and over again. However, it works fine when I log in with a different account. So it appears to be a server-side issue that affects individual accounts. Obviously, there's no reason to expect that Instagram/Facebook will help to solve it. I hope that it at least will not spread to my other account, because creating new accounts every day to keep using Instaloader is not a viable solution.

**Comment by aandergr** [comment]
Error code 500 means [Internal Server Error](https://http.cat/500), a problem on the server side which we cannot fix. If that error appears, Instaloader retries the request a few times, and if it continues to fail, it aborts.

**Comment by SeNeOEH** [comment]
I had the same issue. It seems to be related to the use of session file. After deleting the file, and entering the password as prompted it works. When launched again with the new sessionfile, same error as previous `JSON Query to graphql/query: HTTP error code 500`.

**Comment by parasiteoflife** [comment]
Why wont this be fixed? It can at least be added an option to re-create the session file if an error occurs. As explained by @SeNeOEH this can be fixed by deleting the session file and re-entering the credentials.

**Comment by aandergr** [comment]
> Why wont this be fixed? It can at least be added an option to re-create the session file if an error occurs. 

Please, always feel free to create a pull request so that we can discuss your suggestions.
