### ISSUE TITLE
Is it possible to download posts in separate folder!!

### ISSUE THREAD

**Issue by hustlerwolf** [instaloader/instaloader#517]
Hey guys

First of all thanks for this python scripts for downloading images from Instagram, it helps a lot. Due to the recent increase usage of album type posts, I was wondering if we can download all posts to separate folder so if any post will have more than one image that all will go to the same folder, so we can easily keep track of all posts separately.

Thanks in advance

**Comment by aandergr** [comment]
Sure! Instaloader allows some [flexibility and creativity regarding where to store downloaded media](https://instaloader.github.io/basic-usage.html#filename-specification). For example, you could do

```
instaloader --filename-pattern={shortcode}/post target
```

**Comment by hustlerwolf** [comment]
The thing I am asking for is whether I can start the bulk download of all posts from single account and store that all posts in separate folders?

For eg. I have 3 posts in one account:
1: single image post
2: carousel Type post containing 2 images
3: carousel Type post containing 5 images

When I start downloading all posts from this particular account all the post images will go to 3 different folders for each post?
