### ISSUE TITLE
Instagram Story videos are not being downloaded at full resolution

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [instaloader/instaloader#520]
I have noticed that Instaloader downloads story videos at 640p resolution, which isn't the highest one, as evidenced by services such as https://www.storieswatch.com/ , which can save videos at 720p.
It's obvious that higher-resolution videos (maybe even 1080p) are possible to retrieve, so why is Instaloader limited to 640p?

**Comment by AnneteR** [comment]
Hey! I had the same problem, I don't even know why it happened. At that moment, when I need to download storys, I use this service https://instastories.watch or https://storiesig.me - check!
