### ISSUE TITLE
How to collect all the links of the group / profile?

### ISSUE THREAD

**Issue by Iskander1220** [instaloader/instaloader#521]
Your question here...
Hi, and sorry for my English!

Is it possible in the program to collect all the links of the group / profile? For example:

```
https://www.instagram.com/p/B77gyF83A2j/
https://www.instagram.com/p/337gyF78A8jl/
...
```

**Comment by Daquisu** [comment]
Hi @Iskander1220 

Yes you can

You may try:
```

from instaloader import Instaloader

HASHTAG = 'cats'

loader = Instaloader(
    sleep=False
)

users = []
for post in loader.get_hashtag_posts(HASHTAG):
    print('https://www.instagram.com/p/' + post.shortcode + '/')
```

**Comment by Iskander1220** [comment]
Thank you, @Daquisu Daquisu! Excuse me, but how can I start a second code? Where should he write?

**Comment by Daquisu** [comment]
What do you mean by "start a second code" ?
