### ISSUE TITLE
is there an option to download IGTV Videos?

### ISSUE THREAD

**Issue by WaseemRkab** [instaloader/instaloader#523]
Your question here...
is there an option to download IGTV?

**Comment by ungenio** [comment]
Download it as single post:

`instaloader -- -SHORTCODE`

for example:

https://www.instagram.com/tv/Bq0OCtth_aQ/

`instaloader --no-metadata-json --dirname-pattern {profile} --filename-pattern {date_utc}_{profile} -- -Bq0OCtth_aQ`

**Comment by WaseemRkab** [comment]
> Download it as single post:
> 
> `instaloader -- -SHORTCODE`
> 
> for example:
> 
> https://www.instagram.com/tv/Bq0OCtth_aQ/
> 
> `instaloader --no-metadata-json --dirname-pattern {profile} --filename-pattern {date_utc}_{profile} -- -Bq0OCtth_aQ`
thank you, is there a way to download the whole IGTV videos as single post?
for example: https://www.instagram.com/natgeo/channel/

**Comment by WaseemRkab** [comment]
> Download it as single post:
> 
> `instaloader -- -SHORTCODE`
> 
> for example:
> 
> https://www.instagram.com/tv/Bq0OCtth_aQ/
> 
> `instaloader --no-metadata-json --dirname-pattern {profile} --filename-pattern {date_utc}_{profile} -- -Bq0OCtth_aQ`

**Comment by aandergr** [comment]
Thanks for the suggestion! [Version 4.3b1](https://github.com/instaloader/instaloader/releases/tag/v4.3b1) introduces `--igtv` to download all IGTV videos of a profile.
