### ISSUE TITLE
How to download a video by simply giving the Video story URL ?

### ISSUE THREAD

**Issue by TechRova** [instaloader/instaloader#527]
I want to download by giving a video post URL directly ? 

ex: https://www.instagram.com/p/B8uguWWH5aa/?igshid=6czbf87d7drh

is it possible ?

**Comment by ungenio** [comment]
Yes, you must use the shortcode:

`instaloader -- -B8uguWWH5aa`

if you want to save it with the profile name:

`instaloader --no-metadata-json --dirname-pattern {profile} --filename-pattern {date_utc}_{profile} -- -B8uguWWH5aa`
