### ISSUE TITLE
_PostPathFormatter breaks Windows-style path

### ISSUE THREAD

**Issue by fireattack** [instaloader/instaloader#529]
**Describe the bug**

_PostPathFormatter is used too aggressively in multiple places, which results in wrong folder name and structure.

Example no.1:

```
instaloader --dirname-pattern "D:\test" instagram
```
in command line on Windows, it will download files to `.D꞉﹨test`, instead of proper `D:\test` (because both `:` and `\` are substituted).

Example no.2:

When downloading highlights, it by default download to a subfolder  `Path(name) / Path(user_highlight.title)`:

https://github.com/instaloader/instaloader/blob/819426efdb722596088fe80705c947e6b20815cb/instaloader/instaloader.py#L671

However, this Path-object later is butchered by `_PostPathFormatter` at

https://github.com/instaloader/instaloader/blob/819426efdb722596088fe80705c947e6b20815cb/instaloader/instaloader.py#L597

which broke all the `\`s on Windows.

![image](https://user-images.githubusercontent.com/4130991/75097179-54292400-556d-11ea-8d4c-3817aebba230.png)

My suggestion is to re-think where we want to substitute the invalid characters. Maybe only do it against filename/foldername (and should also replace "/" there for any OS, if we want to avoid unexpected subdirectory creation), not fullpath. Probably only against automatically generated fields, too.

Version: 4.3a1

**Comment by fireattack** [comment]
I feel like we should only replace "\" to "＼" if it's from any automatically generated fields (`{profile}` etc.). If the user intentionally feeds in a "\" themselves it should be treated just like "/".

Actually, now I think about it, we don't do anything special to "/" (regardless of the platform). So while seems practically impossible, having "/" in automatically generated fields will cause it to create subfolders in any OS.

**Comment by fireattack** [comment]
Also, I feel like full-width colon (U+FF1A) would be a better substitution for ":" than what we were using now (MODIFIER LETTER COLON, "U+A789"). It would be more consistent will others (we use full-width backslash, pipe, etc. already).

**Comment by fireattack** [comment]
Updated the description and title to reflect some new information.

This problem is more prominent than I think; it happens all the time when you download highlights (which by default saved to a subdir in the main dir).

**Comment by blablable123456** [comment]
Theres a trick that I use for quite a while and it works wonders. Simple put a 1 at the end of line 671. Of course this is just a fix for this isolated issue. By the way, this issue of folder formatting doesnt bug on linux, only on windows.

` else Path(name) / Path(user_highlight.title + '1')) `

**Comment by fireattack** [comment]
> Theres a trick that I use for quite a while and it works wonders. Simple put a 1 at the end of line 671. Of course this is just a fix for this isolated issue. By the way, this issue of folder formatting doesnt bug on linux, only on windows.
> 
> `else Path(name) / Path(user_highlight.title + '1'))`

This doesn't seem to work. From the look of it, it would just change the folder name to {title}1 (and I tried it indeed didn't work.)

![image](https://user-images.githubusercontent.com/4130991/75099354-5e0b5100-5586-11ea-844b-269df5753aa5.png)

**Comment by fishermansfriendsachet** [comment]
I really hope that this gets patched soon or somebody finds a workaround. It's stopping me from downloading highlights.

**Comment by fireattack** [comment]
> I really hope that this gets patched soon or somebody finds a workaround. It's stopping me from downloading highlights.

Just remove `.replace('\\', '\ufe68')` from 
https://github.com/instaloader/instaloader/blob/819426efdb722596088fe80705c947e6b20815cb/instaloader/instaloader.py#L111
will fix it.
