### ISSUE TITLE
Get latest post from users list

### ISSUE THREAD

**Issue by arthuranst** [instaloader/instaloader#533]
Hi!

How can I download the latest posts from a user ? (not using instaloader -post -- -shortcode but the profile name only) 
And is it possible to load the same action for a predefined user list (differents accounts) ?

Thx.

**Comment by MatyiFKBT** [comment]
> How can I download the latest posts from a user ? 

There is no way. You can do `--count 1` to get the first post only, but that doesn't seem to apply to user profiles, only #hashtag, %location id, and :feed.
https://instaloader.github.io/cli-options.html#cmdoption-count

> And is it possible to load the same action for a predefined user list (differents accounts) ?

You can save the profiles to a .txt file.

args.txt file: 
```
profile1
profile2
```
Then you just run `instaloader +args.txt`

**Comment by arthuranst** [comment]
Ok. Thank you.

I picked another option to focus on posts, with the 'X percentage most liked'.

I still have some issues with it.. I want 10% of posts, but only from the previous year. Any idea where I'm wrong?

`from itertools import islice
from math import ceil

from datetime import datetime
from itertools import dropwhile, takewhile

from instaloader import Instaloader, Profile

PROFILE = 'arthuranst'
X_percentage = 10   

L = Instaloader()

SINCE = datetime(2020, 9, 1)
UNTIL = datetime(2018, 9, 1)

profile = Profile.from_username(L.context, PROFILE)
posts_sorted_by_likes = sorted(profile.get_posts(),
                               key=lambda p: p.likes + p.comments,
                               reverse=True)

for post in islice(posts_sorted_by_likes, ceil(profile.mediacount * X_percentage / 100)):
    if (post.datetime <= UNTIL ):
        L.download_post(post, PROFILE)

    `

**Comment by MatyiFKBT** [comment]
You are importing `Profile` class as `il`, you should swap your imports:
`from instaloader import Profile, Instaloader as il`
Also, can you attach the exact error python is giving you? That might help more in understanding the problem.

**Comment by arthuranst** [comment]
With this code
```
from itertools import islice
from math import ceil

from datetime import datetime
from itertools import dropwhile, takewhile

from instaloader import Profile, Instaloader as il
l = il.Instaloader(dirname_pattern="/Users/arthuranst/Desktop/memoire/DL-PATH")
l.download_post(post, filename)

USERSPROFILE = 'arthuranst'
X_percentage = 10   

L = Instaloader()

SINCE = datetime(2020, 9, 1)
UNTIL = datetime(2018, 9, 1)

profile = Profile.from_username(L.context, USERSPROFILE)
posts_sorted_by_likes = sorted(profile.get_posts(),
                               key=lambda p: p.likes + p.comments,
                               reverse=True)

for post in islice(posts_sorted_by_likes, ceil(profile.mediacount * X_percentage / 100)):
    if (post.datetime <= SINCE and post.datetime >= UNTIL):
        print var(post)
        L.download_post(post, USERSPROFILE)
```

I received this traceback : 

> Traceback (most recent call last):
>   File "/Users/arthuranst/Desktop/memoire/PYTHON/X-percentage-most-liked.py", line 8, in <module>
>     l = il.Instaloader(dirname_pattern="/Users/arthuranst/Desktop/memoire/DL-PATH")
> AttributeError: type object 'Instaloader' has no attribute 'Instaloader'

**Comment by MatyiFKBT** [comment]
You don't need to write `il.Instaloader`, since `il` itself refers to the `Instaloader` class in the `instaloader` module. (notice the lower-case i in the module name, and the upper-case I in the class).
You don't need line 9 as it's not doing anything, since post and filename are both not defined.
I suggest you should import the Instaloader class as it is (so no `il`) and refering to it as `Instaloader`.

Try this:
```python
from itertools import islice
from math import ceil

from datetime import datetime
from itertools import dropwhile, takewhile

from instaloader import Profile, Instaloader

USERSPROFILE = 'arthuranst'
X_percentage = 10   

L = Instaloader(dirname_pattern="/Users/arthuranst/Desktop/memoire/DL-PATH")
# You're initializing the Instaloader class here with your dirname_pattern argument

SINCE = datetime(2020, 9, 1)
UNTIL = datetime(2018, 9, 1)

profile = Profile.from_username(L.context, USERSPROFILE)
posts_sorted_by_likes = sorted(profile.get_posts(),
                               key=lambda p: p.likes + p.comments,
                               reverse=True)

for post in islice(posts_sorted_by_likes, ceil(profile.mediacount * X_percentage / 100)):
    if (post.datetime <= SINCE and post.datetime >= UNTIL):
        print var(post)
        L.download_post(post, USERSPROFILE)
```

**Comment by MatyiFKBT** [comment]
This isn't gonna work also,cause the post class does not have `datetime` property 😄, I've changed it to `date`.
Also you're not using `dropwhile` and `takewhile` so there's no reason to import those.
Updated code that did work for me:
```py
from itertools import islice
from math import ceil

from datetime import datetime

from instaloader import Profile, Instaloader

USERSPROFILE = 'arthuranst'
X_percentage = 10   

L = Instaloader(dirname_pattern="/Users/arthuranst/Desktop/memoire/DL-PATH")
# You're initializing the Instaloader class here with your dirname_pattern argument

SINCE = datetime(2020, 9, 1)
UNTIL = datetime(2018, 9, 1)

profile = Profile.from_username(L.context, USERSPROFILE)
print(profile) # <Profile arthuranst (7569736126)>

posts_sorted_by_likes = sorted(profile.get_posts(),
                               key=lambda p: p.likes + p.comments,
                               reverse=True)
print(posts_sorted_by_likes)  # should output the sorted list

for post in islice(posts_sorted_by_likes, ceil(profile.mediacount * X_percentage / 100)):
    if (post.date <= SINCE and post.date >= UNTIL):
        #changed datetime to date here
        print('Downloading post with the caption:',post.caption)
        # Downloading post with the caption: coloris — publication and program 
        L.download_post(post, USERSPROFILE)
```

**Comment by arthuranst** [comment]
Thank you for the corrections you made! Very helpful. It’s working with my account but if I try with ‘elleusa’ for example, it’s taking so long after the `print(profile)` to show anything. Mostly I do not get anything at all, without any error. I do not understand why.

**Comment by MatyiFKBT** [comment]
Hey! I remember seeing your comment about how long it takes for an account with more posts than your account, but now I can't find it. 😕 
The reason why it takes more time is because the script is going trough all posts of that account and for an account with more posts, that obviously leads to more time.

**Comment by arthuranst** [comment]
Yes this is exactly why I deleted my comment, I understood it yesterday night! :D
Thanks a lot again for all your help!

**Comment by MatyiFKBT** [comment]
Ah, alright! If you have any more questions, feel free to ask, otherwise, you can close this issue if there's nothing else

**Comment by arthuranst** [comment]
Before closing. Is it possible to tell the script to not go through ALL the posts as they are sorted later in the percentage and the during-since filter ? Example : Post 1 -->post 14/25 posts, it print only those and do not even look at the others before continuing the script.

**Comment by MatyiFKBT** [comment]
Don't think so. The script uses Instagram's API to fetch posts, and the API returns posts ordered by date.

**Comment by aandergr** [comment]
> I want 10% of posts, but only from the previous year.

(I assume you want the "top-liked 10%" of posts)

To achieve that efficiently, combine the example "Top X Posts of User" and "Download Posts in a Specific Period" from our [Advanced Instaloader Examples](https://instaloader.github.io/codesnippets.html) section, and you get

```python
from datetime import datetime
from itertools import dropwhile, islice, takewhile
from math import ceil

from instaloader import Instaloader, Profile

PROFILE = "<insert profile name here>"
SINCE = datetime(2019, 1, 1)
UNTIL = datetime(2018, 1, 1)
PERCENTAGE = 10

L = Instaloader()

posts = Profile.from_username(L.context, PROFILE).get_posts()
posts_in_date_range = takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts))
posts_sorted_by_likes = sorted(posts_in_date_range, key=lambda p: p.likes, reverse=True)
top_posts = islice(posts_sorted_by_likes, ceil(len(posts_sorted_by_likes) * PERCENTAGE / 100))

for post in top_posts:
    L.download_post(post, PROFILE)
```

This way, it does not iterate through all posts. Thanks to [takewhile()](https://docs.python.org/3/library/itertools.html#itertools.takewhile) and the fact that get_posts() returns the profile's posts sorted by date, it stops iterating as soon as it arrives at posts that are older than required.

**Comment by RashminDungrani** [comment]
> > I want 10% of posts, but only from the previous year.
> 
> (I assume you want the "top-liked 10%" of posts)
> 
> To achieve that efficiently, combine the example "Top X Posts of User" and "Download Posts in a Specific Period" from our [Advanced Instaloader Examples](https://instaloader.github.io/codesnippets.html) section, and you get
> 
> ```python
> from datetime import datetime
> from itertools import dropwhile, islice, takewhile
> from math import ceil
> 
> from instaloader import Instaloader, Profile
> 
> PROFILE = "<insert profile name here>"
> SINCE = datetime(2019, 1, 1)
> UNTIL = datetime(2018, 1, 1)
> PERCENTAGE = 10
> 
> L = Instaloader()
> 
> posts = Profile.from_username(L.context, PROFILE).get_posts()
> posts_in_date_range = takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts))
> posts_sorted_by_likes = sorted(posts_in_date_range, key=lambda p: p.likes, reverse=True)
> top_posts = islice(posts_sorted_by_likes, ceil(len(posts_sorted_by_likes) * PERCENTAGE / 100))
> 
> for post in top_posts:
>     L.download_post(post, PROFILE)
> ```
> 
> This way, it does not iterate through all posts. Thanks to [takewhile()](https://docs.python.org/3/library/itertools.html#itertools.takewhile) and the fact that get_posts() returns the profile's posts sorted by date, it stops iterating as soon as it arrives at posts that are older than required.

How to avoid download json metadata and comment json in this script ? 
And is there any way to detect which is one post and which is multiple post ?

**Comment by roncam82** [comment]
this is not working for me :(

**Comment by r1495** [comment]
hi is there is any tool that can by pass the login detail of private instagram account
