### ISSUE TITLE
Writing Captions to a List

### ISSUE THREAD

**Issue by AlexGouv** [instaloader/instaloader#535]
Hi,

I have successfully downloaded bios for a list of accounts I have, and now need to download the captions from their posts but cannot figure out what needs to change to get them. Right now I use this to get the bio information:
`instaloader.Profile.from_username(L.context, handles[r]).biography`

However, switching the biography part to get_posts( )(which is what I thought would be the fix based on the documentation) is not working. 

If there is a way to write the captions to a list that would be ideal.
Thanks!

**Comment by Thammus** [comment]
Hi,
`Profile.get_posts()` returns an [Iterator](https://docs.python.org/3/library/typing.html#typing.Iterator). So, for each account you will need to iterate over its posts and access the [`caption`](https://instaloader.github.io/as-module.html?highlight=get_posts#instaloader.Post.caption) property.
