### ISSUE TITLE
request_timeout parameter not included when using as a module

### ISSUE THREAD

**Issue by arkwismb** [instaloader/instaloader#536]
**Describe the bug**
Parameter `request_timeout` is not included when using the module.

**To Reproduce**
`
from instaloader import Instaloader
L = Instaloader(request_timeout=5)
`

**Expected behavior**
Script does not break

**Error messages and tracebacks**
`TypeError: __init__() got an unexpected keyword argument 'request_timeout'`

**Instaloader version**
4.2.10

**Additional context**

(please also see https://instaloader.github.io/contributing.html for how to report a bug)

**Comment by aandergr** [comment]
That makes little sense. Maybe an older Instaloader version is loaded when you import it as a module?

What is printed by?:

```python
import instaloader
instaloader.__version__
```

**Comment by arkwismb** [comment]
You are correct, I'm still on 4.2.10 and just noticed request_timeout is part of the 4.3 pre-release. Closing this.
