### ISSUE TITLE
Can't create session file

### ISSUE THREAD

**Issue by ipkpjersi** [instaloader/instaloader#539]
**Describe the bug**
I am unable to create session file, it prompts me for my password, and then never creates the file. The folder has full read/write/execute permissions so it should not be a problem, therefore it is a bug. I am already using the latest instaloader 4.2.10 with Python 3.6.9 on Ubuntu 18.04.

**To Reproduce**
`instaloader --login=username profile profilenamehereobviously --sessionfile=/home/name/.instaloder-session`

**Expected behavior**
I expect the session file to be created after being prompted for my password.

**Error messages and tracebacks**
There are no errors.

**Instaloader version**
`4.2.10`

**Additional context**
None.

**Comment by aandergr** [comment]
> **To Reproduce**
> `instaloader --login=username profile profilenamehereobviously --sessionfile=/home/name/.instaloder-session`

Most probably this wrong invocation is the cause for Instaloader not behaving as expected. The correct option is `--sessionfile=...`, without `--` and `sessionfile` being separated.

**Comment by ipkpjersi** [comment]
Hi @aandergr 

Thanks for your response.

I'm kind of confused. I did `--sessionfile=...` without `--` and `sessionfile` being separated?

I don't think this bugreport is invalid, it literally specifies that the session file does not exist - which means that the argument *is* being read: 
![](https://i.imgur.com/qp6yqK6.png)
