### ISSUE TITLE
No IGTV videos get downloaded

### ISSUE THREAD

**Issue by Donearm** [instaloader/instaloader#541]
**Describe the bug**
No output nor exception, I receive the message "Retrieving IGTV videos for profile" etc. followed by the correct number of IGTV videos present for the profile but nothing gets downloaded.

**To Reproduce**
This code:

`L.download_igtv(instaloader.Profile.from_username(L.context, profilename))`

where `profilename` is a str with the profile name. `download_post` with the same instance, calling structure and profile works correctly. No filters given, profile is public (I follow it), downloading as logged in user or anonymous doesn't change anything.

**Expected behavior**
IGTV videos of a profile downloaded.

**Instaloader version**
4.3

**Comment by aandergr** [comment]
> **Describe the bug**
> No output nor exception, I receive the message "Retrieving IGTV videos for profile" etc. followed by the correct number of IGTV videos present for the profile but nothing gets downloaded.

We're confused about this description. The message "Retrieving IGTV videos for profile" is not followed by any number.

On which profile does downloading IGTV videos not work?

**Comment by Donearm** [comment]
That's the only output I see:

https://imgur.com/Son6gWf

and then the program exits. The [0/1] is correct as for profile biernatagata there's a single IGTV  video of 3 weeks ago. If I try with different profiles the count is always correct and it progressively outputs [0/4]..[1/4]..[2/4] and so on but nothing gets downloaded.

I should add that from the command line using `instaloader --igtv profile` **does** work.

**Comment by aandergr** [comment]
Could you show us how you invoke Instaloader such that this bug appears, especially how you instantiate Instaloader?

**Comment by Donearm** [comment]
Instaloader is instantiated as such:

    L = instaloader.Instaloader(download_video_thumbnails=False, download_geotags=False, 
            download_comments=False, save_metadata=False, 
            post_metadata_txt_pattern="", request_timeout=10.0)

Then I try to download the videos with:

`L.download_igtv(instaloader.Profile.from_username(L.context, profilename))`

**Comment by aandergr** [comment]
Tested the exact invocation and it just works in my case.

```
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import instaloader
>>> L = instaloader.Instaloader(download_video_thumbnails=False, download_geotags=False, 
...         download_comments=False, save_metadata=False, 
...         post_metadata_txt_pattern="", request_timeout=10.0)
>>> profilename='biernatagata'
>>> L.download_igtv(instaloader.Profile.from_username(L.context, profilename))
Retrieving IGTV videos for profile biernatagata.
[1/1] biernatagata/2020-02-22_11-02-20_UTC.mp4 
```

(with Instaloader from current master)

**Comment by Donearm** [comment]
You're right, I've retried exactly as you did from the Python prompt and it does. It has to be the logic of my script somewhere else perhaps.

Besides, does using `download_videos=False` include IGTV videos? Is there a way to not download videos in feed but download IGTV ones only instead?

**Comment by aandergr** [comment]
> You're right, I've retried exactly as you 
> Besides, does using `download_videos=False` include IGTV videos? Is there a way to not download videos in feed but download IGTV ones only instead?

IGTV videos are treated just like regular posts, hence `--no-videos` behaves in the same way. So with `download_videos=False`, IGTV videos are not downloaded. With the CLI there is no way to download IGTV videos but exclude regular post videos. In a script which uses Instaloader as a module, one could change the `download_videos` property of the Instaloader instance. I see that this might not be elegant, merely because we once decided to keep these options centrally in the Instaloader class rather than e.g. as kwargs of the actually affected methods. Either way, at least for the CLI, I'm against adding a too complex logic to handle probably seldomly used edge cases.

**Comment by Donearm** [comment]
I understand. It would be an edge case for me too and can live with downloading the occasional video/IGTV with the CLI and keeping my script for images only. Thanks for your answer.
