### ISSUE TITLE
Is there an easy way of getting the filename of the downloaded post? (Instaloader python module)

### ISSUE THREAD

**Issue by Gertje823** [instaloader/instaloader#542]
Is there an easy way of getting the filename of the downloaded post with the Instaloader python module?
Like in the output if the post already exists. (_pictures.by.tam/2020-03-18 15-01-14 2267639160066243630_7690536370.jpg_ exists txt unchanged geo comments json)

Here is my code so far:

```
import instaloader

USER = ""
PASSWORD = ""

PROFILE = "pictures.by.tam"
DIR = "{target}"
Name = "{date:%Y-%m-%d %H-%M-%S} {mediaid}_{owner_id}"
L = instaloader.Instaloader(dirname_pattern=DIR, filename_pattern=Name)
L.login(USER, PASSWORD)


profile = instaloader.Profile.from_username(L.context, PROFILE)

for post in profile.get_posts():
    L.download_post(post, target=profile.username)
    filename = 
```

**Comment by bastiaanbiester** [comment]
To my knowledge it is not currently possible to get the filename of a post, but it is an interesting feature that I would like to see added.

**Comment by aandergr** [comment]
It's easily possible with [Instaloader.format_filename()](https://instaloader.github.io/as-module.html#instaloader.Instaloader.format_filename):

```python
for post in profile.get_posts():
    L.download_post(post, target=profile.username)
    filename = profile.username + '/' + L.format_filename(post, target=profile.username)
```

**Comment by Gertje823** [comment]
@aandergr Thank you, but if I do this I get this "pictures.by.tam /2020-03-18 15-01-14 2267639160066243630_7690536370". Is there also a way of getting the correct file extension?

**Comment by aandergr** [comment]
The file extension is `jpg` if not `post.is_video`, else `mp4`.

**Comment by e5150** [comment]
Well, with sidecars the filename needs to be suffixed as well. There might be a valid use case for having download_* return a list of the paths to the files actually downloaded. I don't think that would interfere with other logic since `bool([]) == False`.

**Comment by aandergr** [comment]
Ah right, didn't think of that case. Returning a list of the paths to the actually downloaded files is a great idea!
