### ISSUE TITLE
Executing instaloader.py error "No name '__main__' in module 'instaloader"

### ISSUE THREAD

**Issue by silverar** [instaloader/instaloader#543]
Your question here...
Windows 10 + pip + python installed

Excuting instaloader.py

results:-
H:\>cd H:\Storage\Instagram downloader
H:\Storage\Instagram downloader>instaloader.py

H:\Storage\Instagram downloader>
 [main 2020-03-22T15:52:36.318Z] update#setState idle
(node:21192) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:21192) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:21192) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:21192) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:21192) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:21192) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:7064) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:7064) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
[main 2020-03-22T15:53:06.319Z] update#setState checking for updates
[main 2020-03-22T15:53:06.440Z] update#setState idle

then Microsoft Code will open and there is error "No name '__main__' in module 'instaloader'"

**Comment by Thammus** [comment]
What is your question? What are you trying to achieve?

**Comment by silverar** [comment]
> What is your question? What are you trying to achieve?

I want to use the script to download pictures from instagram but i'm facing these errors.

**Comment by Thammus** [comment]
We still need much more information about what you are doing. With "the script" you mean Instaloader? What are you doing with Visual Studio Code? Did you try to simply execute Instaloader from the command line? How does your "Instagram downloader" directory look like? Are all necessary files of Instaloader present?
