### ISSUE TITLE
Multiple account logins

### ISSUE THREAD

**Issue by DankMemeGuy** [instaloader/instaloader#550]
I have a few accounts that follow a bunch of private accounts. it would be nice if I could somehow use a multi-login approach to maintain the private accounts.

Right now I have textfiles with the account login info, and the list of corresponding users, however this means automation isn't really possible.

**Comment by aandergr** [comment]
Please use our [Feature Suggestion Template](https://github.com/instaloader/instaloader/issues/new?labels=feature+suggestion&template=feature_request.md) for suggesting new features, as this makes it easier to see how the new feature could fit into Instaloader.
