### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by DankMemeGuy** [instaloader/instaloader#551]
Currently the .exe will download all folders (tagged, stories, profile, etc) into the main folder it's in. How do I get this to save the other folders into a subdirectory?

It would be nice if I could keep .exe in /parent/ then users get downloaded to /parent/users/username1; /parent/users/username2, etc.

And all stories, tagged, etc are stores in: /parent/users/username1/tagged, /parent/users/username1/stories,  /parent/users/username2/tagged/stories, etc.

Any way of maintaining the folder structure more nestled?

Note:

--dirname-pattern doesn't accomplish this. This method creates folders for users that uploaded the tagged photo in the main directory instead of the actual user's 'tagged folder'

**Comment by aandergr** [comment]
Please use our [Bug Report Template](https://github.com/instaloader/instaloader/issues/new?labels=bug&template=bug_report.md) for bug reports, as this makes it easier to address the reported issue.
