### ISSUE TITLE
Multiple Account Logins

### ISSUE THREAD

**Issue by DankMemeGuy** [instaloader/instaloader#555]
**Provide us a use case of the feature**
I have a few accounts that follow a bunch of private accounts. it would be nice if I could somehow use a multi-login approach to maintain the private accounts.

Right now I have textfiles with the account login info, and the list of corresponding users, however this means automation isn't really possible.

**Describe the solution you'd like**
In a textfile when inputting the account details the usernames that follow should be tied to that account. When the textfile has another account, any users under that should be tied to that. So the script uses the first credentials, downloads the profiles, then logs into the next account, downloads those profiles etc.

**Describe alternatives you've considered**
N/A

**If the feature request is accepted, would you be willing to submit a PR?**

No; but can help

**Comment by Thammus** [comment]
You can simply use a script (for example a batch script on Windows) to automatically invoke Instaloader separately with each account. There is no advantage in implementing this feature on Instaloader's side and would add unnecessary complexity.
