### ISSUE TITLE
Setting a Location of posts when downloading them

### ISSUE THREAD

**Issue by ItsYoBoiExo1234** [instaloader/instaloader#559]
I'm having a hard time trying to find an answer to this online, I wanna be able to set a path of which the posts I download will go to, here my example code

```python
import instaloader

L = instaloader.Instaloader()

USER = 'Username Here'
PROFILE = instaloader.Profile.from_username(L.context, USER)

for post in PROFILE.get_posts():
    L.download_post(post)
```

**Comment by Thammus** [comment]
As described in our [docs](https://instaloader.github.io/as-module.html#instaloader-main-class), you can pass parameters when creating the Instaloader instance. You can adjust the `dirname-pattern` according to the [Filename Specification](https://instaloader.github.io/basic-usage.html#filename-specification) to specify the directory where to store posts.

For example:
```python
L = instaloader.Instaloader(dirname_pattern='custom_dirname/{target}')
```
