### ISSUE TITLE
Download stories in python module

### ISSUE THREAD

**Issue by annanny** [instaloader/instaloader#561]
I need to download all stories from a lot of profiles. How can I do it? 
I try to run example from the documentation like this 

for story in L.get_stories():
    for item in story.get_items():
        L.download_storyitem(item, ':stories')

but I get error "TypeError: expected str, got bool"

And if I am right to understand in this case I'll get all stories from my profile, but I want to get stories from any profile if it is open.

I use the last version of Instaloader

**Comment by asuna-cz** [comment]
```
L = instaloader.Instaloader()
L.login(USER, PASSWORD)

for story in L.get_stories():
    for item in story.get_items():
        L.download_storyitem(item, ':stories')
```

This following code from docs will download all stories you can see on your friends profile and it works just fine for me. 

_Python 3.6.9
Instaloader 4.3.2_

You can download stories from specific user like this
```
L = instaloader.Instaloader()
L.login(USER, PASSWORD)
L.download_stories(userids=[460563723])
# You can pass multiple ids like [460563723, 460563723, 460563723]
```

To get profile ID you can use
```
L = instaloader.Instaloader()
profile = L.check_profile_id("SelenaGomez")
```
```
>>> profile.userid
460563723
```

**Comment by 9dc** [comment]
Is there any possibility to pass the "dirname_pattern" to 
`L.download_stories(userids=[])`
?
If i download it, all content goes in the `: Stories` folder and not in the `{target}` folder.

**Comment by kyemets** [comment]
> If i download it, all content goes in the `: Stories` folder and not in the `{target}` folder.

I had the same problem. I solved this problem like this:


```
from instaloader import Instaloader, Profile 
L = Instaloader()
L.login("login", "password")

profile = L.check_profile_id("profile.username")
L.download_stories(userids=[profile.userid],filename_target='{}/stories'.format(profile.username))
```

**Comment by pc11000** [comment]
Hi is story downloading still working?
I try to download it with above examples, but nothing happens..

**Comment by faith277** [comment]
> 

I have no idea, didn't used it for a long time

**Comment by Joaogmbd** [comment]
@pc11000 

Just tried using those snippets, still working for me
