### ISSUE TITLE
Missing fields for "GraphVideo" post when using `save_metadata_json()`

### ISSUE THREAD

**Issue by shubhams** [instaloader/instaloader#562]
**Describe the bug**
When calling `L.save_metadata_json(path, post)` on a post, the saved JSON file has missing fields like `video_duration`, `product_type`, and `title`.

**To Reproduce**
To save the JSON using instaloader:
```python
for post in profile.get_posts():
        path = get_file_path(ig_username, str(post.mediaid))
        L.save_metadata_json(path, post)
```
To cross-verify using Instagram response, hit `https://www.instagram.com/<username>/?__a=1` with the `<username>` substituted for a correct Instagram username, and look `node` with `"__typename": "GraphVideo"`.

**Expected behavior**
The `node` JSON retrieved using `save_metadata_json()` should be identical to the one received when hitting the above URL for `"__typename": "GraphVideo"`.

**Error messages and tracebacks**
A screenshot showing the JSON diff:
<img width="1234" alt="Screen Shot 2020-04-09 at 5 14 11 PM" src="https://user-images.githubusercontent.com/6473299/78945515-1a14d280-7a86-11ea-8793-6a8e2940875e.png">

**Instaloader version**
4.3.1

**Comment by aandergr** [comment]
> **Expected behavior**
> The `node` JSON retrieved using `save_metadata_json()` should be identical to the one received when hitting the above URL for `"__typename": "GraphVideo"`.

No. The documentation of [Metadata JSON Files](https://instaloader.github.io/codesnippets.html#metadata-json-files) states:

> Instaloader tries to do as few metadata requests as possible, so, depending on how Instaloader has been invoked, it may occur that these files do not contain the complete available metadata structure.

**Comment by shubhams** [comment]
Thanks for pointing out the justification in the documentation. 
However, I was wondering if `video_duration` is available as `property` attribute to the `Post` class, why would Instaloader need to make additional requests?
