### ISSUE TITLE
:saved Profile does not exist.

### ISSUE THREAD

**Issue by Xaelias** [instaloader/instaloader#563]
**Describe the bug**
When trying to download the saved from my profile, the program errors out, saying the profile doesn't exist, but that one with the exact same name is the closest.

**To Reproduce**
```
❯ instaloader --login=<profile_name> -f <profile_name>_session :saved
Loaded session from <profile_name>_session.
Logged in as <profile_name>.
Retrieving saved posts...
:saved: Profile <profile_name> does not exist.
The most similar profile is: <profile_name>.
Saved session to <profile_name>_session.

Errors occured:
:saved: Profile <profile_name> does not exist.
The most similar profile is: <profile_name>
```

**Instaloader version**
4.3.2

**Additional context**
```
❯ pip freeze
certifi==2020.4.5.1
chardet==3.0.4
idna==2.9
instaloader==4.3.2
requests==2.23.0
urllib3==1.25.8
```
The profile is private, mostly brand new (I just created this account) and I'm testing out ways to backup the content and saved things.
There is no post from that account, if that matters.

Thanks for the help!
PS: Looks like the exact same problem from https://github.com/instaloader/instaloader/issues/540 but that was closed because the person didn't follow the template.

**Comment by Xaelias** [comment]
It looks like `metadata['entry_data']` is empty when logging in? It shows up as `{'ProfilePage': [{}]}`.

**Comment by aandergr** [comment]
[Version 4.4.5rc1](https://github.com/instaloader/instaloader/releases/tag/v4.4.5rc1) includes a change of how profile medata is accessed (#727). This might affect the here reported problem.

To upgrade:
```
pip3 install --upgrade --pre instaloader
```

**Comment by aandergr** [comment]
Closing this, as it is likely fixed in [Version 4.4.5](https://github.com/instaloader/instaloader/releases/tag/v4.4.5). Please comment if the problem still occurs.

**Comment by threnbo** [comment]
Problem still occurs for me.

**Instaloader version**
4.5

**Additional context**
`➜  ~ pip freeze
certifi==2020.6.20
chardet==3.0.4
idna==2.10
instaloader==4.5
pip-autoremove==0.9.1
requests==2.24.0
urllib3==1.25.10`

Thanks.

**Comment by Thammus** [comment]
The new feature to cache profiles on first load should solve the here described problem of loading saved posts.

You can install and try it with pip using the following command:
```
pip install git+https://github.com/instaloader/instaloader@feature/profile-cache
```

**Comment by threnbo** [comment]
Thanks a lot for your answer.

I uninstalled instaloader, deleted the session file of my logged-in profile and installed instaloader with your command.

Unfortunately, the error stays the same (as described in the first post).

**Comment by Xaelias** [comment]
Sorry for my silence. I haven't answered because I switched to another project to do this :-)

But. I did give this version (with the profile-cache) a try, and I agree with @threnbo, I get the exact same error I used to.
