### ISSUE TITLE
Retrieving latest posts is ignored: --post-filter="date_utc <= datetime(2018, 5, 31)"

### ISSUE THREAD

**Issue by asoretmadolell** [instaloader/instaloader#564]
**Describe the bug**
I'm sorry if it's not a bug and there's something I'm not doing correctly. I'm just trying to use the documentation's own example of downloading posts in a specific time frame. The effect is that, even if the CLI says:
`Only download posts with property "'--post-filter="date_utc <= datetime(2018, 5, 31)'".`
every post will be downloaded regardless of the date. I've looked into other issues like this but none were failing like mine.

**To Reproduce**
My command line is as follows:
`instaloader --login=? --sessionfile=? PROFILE --post-filter='date_utc <= datetime(2018, 5, 31)' --highlights --tagged --igtv -dirname-pattern={target} --filename-pattern={date_utc}_{profile}`

**Error messages and tracebacks**
None

**Instaloader version**
`4.3.2`

**Comment by e5150** [comment]
Could you post the (possibly anonymised) output? For me it works as intended, however, the post filter does not apply to igtv or highlights, you'd have to specify `--storyitem-filter` as well.

**Comment by asoretmadolell** [comment]
Sure!
So you were right about me missing that option, but it still made no difference. So here's my updated command line:
`instaloader --login=? --sessionfile=? PROFILE --post-filter='date_utc >= datetime(2020, 3, 31)' --storyitem-filter='date_utc >= datetime(2020, 3, 31)' --highlights --tagged --igtv -dirname-pattern={target} --filename-pattern={date_utc}_{profile}`
And here's what I received (anonymysed before posting, and as for the results I'm only showing some of each, enough to be clear that the date query is ignored)
**First output:**
`
Only download posts with property "'date_utc >= datetime(2020, 3, 31)'".
Only download storyitems with property "'date_utc >= datetime(2020, 3, 31)'".
Loaded session from /instaloader/session.
Logged in as ????.
Stored ID 123456 for profile profile.
/instaloader/profiles/profile/2020-03-18_20-18-01_UTC_profile_pic.jpg
`
**Then I start receiving tagged posts:**
`
Retrieving tagged posts for profile profile.
[  1/???] /instaloader/profiles/profile/:tagged/2019-01-10_19-51-33_UTC_profile.jpg json
[  2/???] /instaloader/profiles/profile/:tagged/2018-12-07_20-01-21_UTC_profile.jpg json
[  3/???] /instaloader/profiles/profile/:tagged/2018-12-07_17-02-40_UTC_profile.jpg json
[  4/???] /instaloader/profiles/profile/:tagged/2018-12-07_14-40-33_UTC_profile.jpg json
[  5/???] /instaloader/profiles/profile/:tagged/2018-12-07_14-40-12_UTC_profile.jpg json
[  6/???] /instaloader/profiles/profile/:tagged/2018-12-07_01-30-29_UTC_profile.jpg json
`
**Then, the IGTV videos**
`
Retrieving IGTV videos for profile profile.
[1/3] /instaloader/profiles/profile/2018-08-27_19-00-00_UTC_profile.jpg /instaloader/profiles/profile/2018-08-27_19-00-00_UTC_profile.mp4 json
[2/3] /instaloader/profiles/profile/2018-08-21_21-49-46_UTC_profile.jpg /instaloader/profiles/profile/2018-08-21_21-49-46_UTC_profile.mp4 json
[3/3] /instaloader/profiles/profile/2018-06-20_22-14-31_UTC_profile.jpg /instaloader/profiles/profile/2018-06-20_22-14-31_UTC_profile.mp4 json
`
**Then, the highlights**
`
Retrieving highlights "hl" from profile profile
/instaloader/profiles/profile/hl/2020-03-31_07-47-19_UTC_cover.jpg
[  1/ 18] /instaloader/profiles/profile/hl/2020-04-11_07-15-26_UTC_profile.jpg /instaloader/profiles/profile/hl/2020-04-11_07-15-26_UTC_profile.mp4 json
[  2/ 18] /instaloader/profiles/profile/hl/2020-04-11_07-13-58_UTC_profile.jpg json
[  3/ 18] /instaloader/profiles/profile/hl/2020-04-09_07-48-47_UTC_profile.jpg json
[  4/ 18] /instaloader/profiles/profile/hl/2020-04-08_00-13-07_UTC_profile.jpg /instaloader/profiles/profile/hl/2020-04-08_00-13-07_UTC_profile.mp4 json
[  5/ 18] /instaloader/profiles/profile/hl/2020-04-07_20-33-22_UTC_profile.jpg json
[  6/ 18] /instaloader/profiles/profile/hl/2020-04-06_19-49-37_UTC_profile.jpg json
[  7/ 18] /instaloader/profiles/profile/hl/2020-04-05_03-50-02_UTC_profile.jpg /instaloader/profiles/profile/hl/2020-04-05_03-50-02_UTC_profile.mp4 json
[  8/ 18] /instaloader/profiles/profile/hl/2020-04-01_21-44-04_UTC_profile.jpg /instaloader/profiles/profile/hl/2020-04-01_21-44-04_UTC_profile.mp4 json
[  9/ 18] /instaloader/profiles/profile/hl/2020-04-01_20-48-04_UTC_profile.jpg /instaloader/profiles/profile/hl/2020-04-01_20-48-04_UTC_profile.mp4 json
[ 10/ 18] /instaloader/profiles/profile/hl/2020-04-01_20-47-50_UTC_profile.jpg json
[ 11/ 18] /instaloader/profiles/profile/hl/2020-04-01_20-47-36_UTC_profile.jpg json
[ 12/ 18] /instaloader/profiles/profile/hl/2020-03-31_07-47-17_UTC_profile.jpg json
[ 13/ 18] /instaloader/profiles/profile/hl/2020-03-28_07-09-53_UTC_profile.jpg json
[ 14/ 18] /instaloader/profiles/profile/hl/2020-03-26_23-49-23_UTC_profile.jpg /instaloader/profiles/profile/hl/2020-03-26_23-49-23_UTC_profile.mp4 json
[ 15/ 18] /instaloader/profiles/profile/hl/2020-03-26_23-44-28_UTC_profile.jpg /instaloader/profiles/profile/hl/2020-03-26_23-44-28_UTC_profile.mp4 json
[ 16/ 18] /instaloader/profiles/profile/hl/2020-03-26_21-08-18_UTC_profile.jpg /instaloader/profiles/profile/hl/2020-03-26_21-08-18_UTC_profile.mp4 json
[ 17/ 18] /instaloader/profiles/profile/hl/2020-03-26_21-08-17_UTC_profile.jpg /instaloader/profiles/profile/hl/2020-03-26_21-08-17_UTC_profile.mp4 json
[ 18/ 18] /instaloader/profiles/profile/hl/2020-03-26_21-05-03_UTC_profile.jpg /instaloader/profiles/profile/hl/2020-03-26_21-05-03_UTC_profile.mp4 json
`
**Finally, the posts**
`
Retrieving posts from profile profile.
[  1/4545] /profile/2020-04-10_09-04-03_UTC_profile.jpg json
[  2/4545] /profile/2020-04-10_09-03-51_UTC_profile.jpg /profile/2020-04-10_09-03-51_UTC_profile.mp4 json
[  3/4545] /profile/2020-04-09_19-31-54_UTC_profile.jpg json
[  4/4545] /profile/2020-04-09_18-54-46_UTC_profile.jpg json
[  5/4545] /profile/2020-04-09_18-53-35_UTC_profile.jpg json
[  6/4545] /profile/2020-04-08_19-14-11_UTC_profile_1.jpg /profile/2020-04-08_19-14-11_UTC_profile_2.jpg /profile/2020-04-08_19-14-11_UTC_profile_2.mp4 /profile/2020-04-08_19-14-11_UTC_profile_3.jpg /profile/2020-04-08_19-14-11_UTC_profile_3.mp4 /profile/2020-04-08_19-14-11_UTC_profile_4.jpg /profile/2020-04-08_19-14-11_UTC_profile_4.mp4 json
[  7/4545] /profile/2020-04-08_03-25-18_UTC_profile_1.jpg /profile/2020-04-08_03-25-18_UTC_profile_1.mp4 /profile/2020-04-08_03-25-18_UTC_profile_2.jpg json
[  8/4545] /profile/2020-04-08_00-10-46_UTC_profile.jpg /profile/2020-04-08_00-10-46_UTC_profile.mp4 json
[  9/4545] /profile/2020-04-06_19-44-36_UTC_profile.jpg /profile/2020-04-06_19-44-36_UTC_profile.mp4 json
[ 10/4545] /profile/2020-04-06_02-15-51_UTC_profile_1.jpg /profile/2020-04-06_02-15-51_UTC_profile_2.jpg /profile/2020-04-06_02-15-51_UTC_profile_2.mp4 json
[ 11/4545] /profile/2020-04-05_19-21-35_UTC_profile.jpg /profile/2020-04-05_19-21-35_UTC_profile.mp4 json
[ 12/4545] /profile/2020-04-05_04-50-09_UTC_profile.jpg json
[ 13/4545] /profile/2020-04-04_00-22-33_UTC_profile.jpg json
[ 14/4545] /profile/2020-04-01_18-52-39_UTC_profile.jpg /profile/2020-04-01_18-52-39_UTC_profile.mp4 json
[ 15/4545] /profile/2020-03-31_21-38-22_UTC_profile_1.jpg /profile/2020-03-31_21-38-22_UTC_profile_2.jpg /profile/2020-03-31_21-38-22_UTC_profile_3.jpg /profile/2020-03-31_21-38-22_UTC_profile_4.jpg /profile/2020-03-31_21-38-22_UTC_profile_5.jpg /profile/2020-03-31_21-38-22_UTC_profile_6.jpg /profile/2020-03-31_21-38-22_UTC_profile_7.jpg /profile/2020-03-31_21-38-22_UTC_profile_8.jpg /profile/2020-03-31_21-38-22_UTC_profile_9.jpg /profile/2020-03-31_21-38-22_UTC_profile_10.jpg json
[ 16/4545] /profile/2020-03-29_19-56-58_UTC_profile.jpg json
[ 17/4545] /profile/2020-03-29_18-45-41_UTC_profile_1.jpg /profile/2020-03-29_18-45-41_UTC_profile_2.jpg /profile/2020-03-29_18-45-41_UTC_profile_3.jpg /profile/2020-03-29_18-45-41_UTC_profile_4.jpg /profile/2020-03-29_18-45-41_UTC_profile_4.mp4 /profile/2020-03-29_18-45-41_UTC_profile_5.jpg /profile/2020-03-29_18-45-41_UTC_profile_5.mp4 json
[ 18/4545] /profile/2020-03-28_06-14-54_UTC_profile.jpg json
[ 19/4545] /profile/2020-03-28_00-31-04_UTC_profile.jpg json
[ 20/4545] /profile/2020-03-27_03-59-33_UTC_profile_1.jpg /profile/2020-03-27_03-59-33_UTC_profile_2.jpg /profile/2020-03-27_03-59-33_UTC_profile_3.jpg /profile/2020-03-27_03-59-33_UTC_profile_4.jpg /profile/2020-03-27_03-59-33_UTC_profile_5.jpg /profile/2020-03-27_03-59-33_UTC_profile_6.jpg /profile/2020-03-27_03-59-33_UTC_profile_7.jpg /profile/2020-03-27_03-59-33_UTC_profile_8.jpg /profile/2020-03-27_03-59-33_UTC_profile_9.jpg /profile/2020-03-27_03-59-33_UTC_profile_9.mp4 /profile/2020-03-27_03-59-33_UTC_profile_10.jpg json
[ 21/4545] /profile/2020-03-24_20-35-49_UTC_profile.jpg /profile/2020-03-24_20-35-49_UTC_profile.mp4 json
[ 22/4545] /profile/2020-03-24_19-57-18_UTC_profile.jpg json
[ 23/4545] /profile/2020-03-19_23-16-47_UTC_profile.jpg /profile/2020-03-19_23-16-47_UTC_profile.mp4 json
[ 24/4545] /profile/2020-03-18_20-21-15_UTC_profile.jpg json
[ 25/4545] /profile/2020-03-18_20-14-56_UTC_profile.jpg /profile/2020-03-18_20-14-56_UTC_profile.mp4 json
[ 26/4545] /profile/2020-03-17_22-52-04_UTC_profile.jpg ^C
Interrupted by user.
`
As you can see, every operation ends up retrieving posts or storyitems whose date_utc is less than the one given. :(

**Comment by e5150** [comment]
> `Only download posts with property "'date_utc >= datetime(2020, 3, 31)'". 

That's weird, how are you invoking instaloader? Might be a quoting issue on windows or  non-sh unix shell. Try putting the filters in double quotes insted, i.e.   `--post-filter="date_utc >= datetime(2020, 3, 31)"`

@Thammus, this might be considered a bug. If a filter describes a string literal the user could at least be warned, something like: 
```
x = TransformFilterAst().visit(...)
if isinstance(x.body, ast.Constant):
    raise TautologicalFilterException
compiled_filter = compile(x, ...)```

**Comment by asoretmadolell** [comment]
I am invoking instaloader from a Debian 10 machine, through SSH, locally, via CRON, (tried several things) and with single or double quotes. Already tried that, the result is always the same.

I forgot to mention that I am using an "args" file, invoking the switch +args in the shell. All the arguments are in a separate file, including these filter arguments. Do you see any relevance in this?

Thank you all :)

**Comment by e5150** [comment]
> I forgot to mention that I am using an "args" file, invoking the switch +args in the shell. All the arguments are in a separate file, including these filter arguments. Do you see any relevance in this?

Yes, the quoting tells the shell that the filter string is a single argument and to not interpret special characters. When in an argument file the parsing is done internally by python, and escaping/quoting is taken as being part of the argument verbatim. Remove the quotes and I'll be good to go.

**Comment by asoretmadolell** [comment]
Awesome. Works. Great, that was it.
Quick question, is this condition checked locally in the json file, or remotely? In other words, is a query done per post to determine the filter? I'm trying to avoid the "too many queries" error.

**Comment by e5150** [comment]
The timestamp of a post is included in the basic response, so no extra queries are incurred. However, to see which posts match the filter, instaloader has to scroll through all available posts. In this particular case it doesn't really matter. But downloading a profile with "date ≥ 2020" would be suboptimal, since the program doesn't know that profiles are still chronologically sorted and as soon as a 2019 post is found, no futher processing would be necessary.
And there might be some other targets and specific filtering conditions that require extra queries, I'm not sure.

**Comment by asoretmadolell** [comment]
I understand. So a date entry such as "≥ March" would be just like scrolling a little bit, and in that case it would be optimal, right?

**Comment by e5150** [comment]
No, Instaloader will "scroll" through all posts regardless. If you're looking for posts earlier than some date that doesn't matter, since you'd have to scroll past the later posts first, and all the way to the bottom anyway. But if you only want posts after a date (`date_utc > datetime(...)`), the program will keep scrolling to check all posts. In which case [--fast-update](https://instaloader.github.io/cli-options.html#cmdoption-fast-update) or [a custom script](https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period) might be better suited.

**Comment by asoretmadolell** [comment]
Thank you so much. Donation sent.
