### ISSUE TITLE
Can you list a command example by flags\options like -post in the documentation

### ISSUE THREAD

**Issue by NIXOYE** [instaloader/instaloader#565]
I want to download a specific post. The documentation doesn't list any examples of what the commands are like 

Download all users photos
`instaloader @aandergr`
Download a specifc post
`instaloader idkhow`

**Comment by e5150** [comment]
Use [`instaloader -- -post`](https://instaloader.github.io/cli-options.html#targets), where "`post`" is to be replaced by the shortcode of the given post.

**Comment by NIXOYE** [comment]
Whats a shortcode? Will you be adding examples for different commands to the documentation?

**Comment by e5150** [comment]
To download the post [https://www.instagram.com/p/B8rgVdbA88z/](https://www.instagram.com/p/B8rgVdbA88z/) use `instaloader -- -B8rgVdbA88z`

**Comment by NIXOYE** [comment]
@e5150 oh thanks. that very difficult to discern from the documentation as it currently is
