### ISSUE TITLE
JSON has tags written in Korean saved as Unicode

### ISSUE THREAD

**Issue by Wazaki-Ou** [instaloader/instaloader#567]
Hi there.

So list the title says, after I download some posts based on hashtags, I am looking at the JSON files to try to understand how to parse them to retrieve the tags used for each post. The issue is that since my focus is on tags related to Korea, some people put tags written in the Korean alphabet (Hangul), so I end up with hashtags written in Korean. I was wondering if there was any way I can solve that without having to write some code to do that myself. This is the code with an example:

```
import instaloader

L = instaloader.Instaloader(download_video_thumbnails=False,download_comments=False,compress_json=False)

i = 0
for post in L.get_hashtag_posts('seoul'):
    if i == 30:
        break
    # post is an instance of instaloader.Post
    L.download_post(post, target='#seoul) 
    i+=1
```

![image](https://user-images.githubusercontent.com/33216367/79062340-93a20000-7cd4-11ea-8457-d2ea036d4949.png)

(extra question. is it possible to use more than one tag to retrieve posts ?)

Also, which part of the JSON file says how many pictures/videos are in each post ? I tried finding, but the element I found had a number different from the actual number of pictures. 

Thanks a lot !!

**Comment by e5150** [comment]
You can use this script to convert your json files to get the actual unicode characters:
```
import sys, json
for file in [a for a in sys.argv[1:] if a.endswith('.json')]:
	with open(file, 'rt') as fp:
		data = json.load(fp)
	with open(file, 'wt') as fp:
		json.dump(data, fp, indent=4, sort_keys=True, ensure_ascii=False)
```
