### ISSUE TITLE
Save to separate folders

### ISSUE THREAD

**Issue by snss806** [instaloader/instaloader#569]
Hello!

I would like to know if it is possible for the IG's savings to be made in separate folders having the name, for example, the collection / story /user, etc.

Example: the top folder is the user name(X) and in the subfolders we can have Stories, Collections, Posts etc. and within Stories we have a folder called Y where Y is the name of the user that posted the story. In the Collections folder let's say we have the following folders Dev, Nature, Sports which corresponds with the name of the Collecttion.

Graphical represention: 
X(X=username) <-Top Folder/Root Folder
      |__Stories
      |------|_Y(Y=username of the user that posted the story)
      |------|_Z(Z=username of the user that posted the story)
      |__Collections
      |------|_Dev(Bookmarks saved by the user)
      |------|_Nature(Bookmarks saved by the user)
      |------|_Sports(Bookmarks saved by the user)
      |__Posts

If this facility already exists, please let me know where I find it.

Thank you.

**Comment by aandergr** [comment]
Not implemented yet, see #544.
