### ISSUE TITLE
How to filter by post caption using several tags?

### ISSUE THREAD

**Issue by renox92** [instaloader/instaloader#570]
Filter `--post-filter="'tag1' in caption_hashtags` works for me, but I can't figure out how to add a second tag to make it work, I either download everything or nothing when I do that. I've tried `'tag1 or tag2'`,` 'tag1, tag2'` and `'tag1' or 'tag2'`. What should example for something like `'T1 or T2 or (T3 and T4)' in caption_hashtags` actually look like?

**Comment by aandergr** [comment]
As described in the documentation, section [Filter Posts](https://instaloader.github.io/basic-usage.html#filter-posts), the filter string follows the syntax of [Boolean Operations in Python](https://docs.python.org/3/reference/expressions.html#boolean-operations).

Hence, `--post-filter="'T1' in caption_hashtags and 'T2' in caption_hashtags"` should work.
