### ISSUE TITLE
Error code 429 with just 1 request!

### ISSUE THREAD

**Issue by alessiomassini** [instaloader/instaloader#573]
**Describe the bug**
I first encountered this error after just 126 followers were scraped from the account I'm trying to obtain a full followers list. But after that it continuously kept giving me this error after the waiting time. After one hour that it didn't restart the scraping but continued to give me the error 429 I decided to stop it.
I tried another time after a couple of hours and set max_connection_attempts=0 as suggested (here)[https://instaloader.github.io/troubleshooting.html#too-many-requests] and this is the error that it gives me after writing just the header in the csv file.

I don't understand what's wrong.

**Error messages and tracebacks**

> HTTP error code 429 was returned because too many queries occured in
> the last time. Please do not use Instagram in your browser or run
> multiple instances of Instaloader in parallel.
> GraphQL requests:
>   other
>     last 10 minutes: 1 requests
>     last 11 minutes: 1 requests
>     last 15 minutes: 1 requests
>     last 20 minutes: 1 requests
>     last 30 minutes: 1 requests
>     last 60 minutes: 1 requests

**Instaloader version**
4.3.2

_PS: In the error there's written "occured" but it's a typo, there should be 2 Rs. I don't want to grumble ahah, just want to signal an error._

Thank you so much to those who'll help me.

**Comment by rocailler** [comment]
I have that problem when I'm trying to do os.environ proxy. 
Check your proxy/vpn

**Comment by aandergr** [comment]
429 are always frustrating. Some other [429 related issues](https://github.com/instaloader/instaloader/search?q=429&type=Issues) indicate this might be some kind of blocking which may be released within 24 hours.

> _PS: In the error there's written "occured" but it's a typo, there should be 2 Rs. I don't want to grumble ahah, just want to signal an error._

Thanks for that hint! At least something that we can fix here…
