### ISSUE TITLE
How to run a cron job?

### ISSUE THREAD

**Issue by renox92** [instaloader/instaloader#574]
The job looks like this
`49 *    * * *   root    cd /IG_folder/ && instaloader +stories.txt`

With stories.txt containing
```
-l=login
-p=password
--no-profile-pic
--no-posts
--stories
--no-video-thumbnails
--no-compress-json
--dirname-pattern={profile}/stories
--filename-pattern={date_local:%y%m%d_%H꞉%M꞉%S} {profile} [{shortcode}]
profile1
profile2
```
The command runs fine manually, but fails to run as a cron job. Even simple `instaloader profile1` doesn't do anything. Replacing instaloader command with something like `touch 123.txt` works fine though, so I don't understand what I'm doing wrong here.

**Comment by e5150** [comment]
What does your cron log have to say? My guess would be that `instaloader` is not in the `$PATH` of root. (I'd also advise against running as root in general.)

**Comment by renox92** [comment]
Says `/bin/sh: 1: instaloader: not found` both when running as root and as pi.

**Comment by e5150** [comment]
If Instaloader is installed under the user `pi`, python won't know where to find the module when running as `root`. And cron doesn't know to search ~pi/.local/bin for executables, as it's unlikely to included in `$PATH` prior to crond being started.
