### ISSUE TITLE
remove saved file after download

### ISSUE THREAD

**Issue by rigatron1986** [instaloader/instaloader#578]
Your question here...
HI is there any way to remove the post from the saved collections once the download is done.

**Comment by Thammus** [comment]
As our contribution guidelines states in the [Suggesting Features](https://instaloader.github.io/contributing.html#suggesting-features) section:
> Instaloader’s goal is to mimick the browser’s behavior [...] without changing any of the online data.

Therefore, Instaloader does not remove anything from your account.
