### ISSUE TITLE
List of all the accounts/profiles that i follow

### ISSUE THREAD

**Issue by itskiyomi** [instaloader/instaloader#579]
Your question here...
Is there any way to dump the name of all the Instagram profile that i follow to a text file.
For eg  if say my account name is @itskiyomi  and i want to save the names of all the account that i follow,  
some command like   $ instaloader  -l its-kiyomi -p password  -(all accounts i follow) >> profiles.txt 
thanks

**Comment by susodapop** [comment]
I searched through the code but I don't see this implemented.
