### ISSUE TITLE
Download followers from terminal

### ISSUE THREAD

**Issue by alessiomassini** [instaloader/instaloader#581]
I’d like to know if there’s a way to scrape followers from terminal using the `$ instaloader` command and not recurring to instaloader.py . 
The equivalent for followers as you can scrape the followings with `$ instaloader @profile`.
I ask this since I’m having a hard time with instaloader.py and always end up with infinite recurring errors 429 when tying to loop over `profile.get_followers()`. 
I’m also often implementing several `sleep()` (random, short, and long), still no success. 

Thanks in advance.

**Comment by Deleora** [comment]
Try [this ](https://pastebin.com/LQz7i153) code that i wrote
You may optimize the code if you want. Just enter your and target profile's username and also make sure session file already exists, else make some modifications accordingly. Then simply run the code and it'll save both followers and followings of the target profile in a csv file with respective counts as well. Let me know if it works. Peace

**Comment by premchugh** [comment]
> Try [this ](https://pastebin.com/LQz7i153) code that i wrote
> You may optimize the code if you want. Just enter your and target profile's username and also make sure session file already exists, else make some modifications accordingly. Then simply run the code and it'll save both followers and followings of the target profile in a csv file with respective counts as well. Let me know if it works. Peace
> 
> EDIT 1: It sorts the followers and followings based on their IDs

Hi, I am new to Python. I am trying to learn how to run the code you have provided.

I used command line to install instaloader. I also tried to download the posts of a public profile. However, I am trying to get a list of all followers from a public profile. I assume the script provided above does the job. But I'm just stuck on how to execute it.

If there is any guide you can refer, it will be helpful.

Thank you.

**Comment by Deleora** [comment]
> > Try [this ](https://pastebin.com/LQz7i153) code that i wrote
> > You may optimize the code if you want. Just enter your and target profile's username and also make sure session file already exists, else make some modifications accordingly. Then simply run the code and it'll save both followers and followings of the target profile in a csv file with respective counts as well. Let me know if it works. Peace
> > EDIT 1: It sorts the followers and followings based on their IDs
> 
> Hi, I am new to Python. I am trying to learn how to run the code you have provided.
> 
> I used command line to install instaloader. I also tried to download the posts of a public profile. However, I am trying to get a list of all followers from a public profile. I assume the script provided above does the job. But I'm just stuck on how to execute it.
> 
> If there is any guide you can refer, it will be helpful.
> 
> Thank you.

Copy and past the above code in Notepad and save the file with `.py` extention (ex, followersScrapper.py) then open your command promt in the directory where you saved the file and give the following command on your cmd

`py followersScrapper.py`

That's it. now all the 'Followers' and 'Following' of the profile you specify in the code will be downloaded and saved in a `.csv` file.

Note: You need to have Python installed on your system.

Let me know if this works or if you need more clarification.
Pleasure helping you :)

**Comment by premchugh** [comment]
> > > Try [this ](https://pastebin.com/LQz7i153) code that i wrote
> > > You may optimize the code if you want. Just enter your and target profile's username and also make sure session file already exists, else make some modifications accordingly. Then simply run the code and it'll save both followers and followings of the target profile in a csv file with respective counts as well. Let me know if it works. Peace
> > > EDIT 1: It sorts the followers and followings based on their IDs
> > 
> > 
> > Hi, I am new to Python. I am trying to learn how to run the code you have provided.
> > I used command line to install instaloader. I also tried to download the posts of a public profile. However, I am trying to get a list of all followers from a public profile. I assume the script provided above does the job. But I'm just stuck on how to execute it.
> > If there is any guide you can refer, it will be helpful.
> > Thank you.
> 
> Copy and past the above code in Notepad and save the file with `.py` extention (ex, followersScrapper.py) then open your command promt in the directory where you saved the file and give the following command on your cmd
> 
> `py followersScrapper.py`
> 
> That's it. now all the 'Followers' and 'Following' of the profile you specify in the code will be downloaded and saved in a `.csv` file.
> 
> Note: You need to have Python installed on your system.
> 
> Let me know if this works or if you need more clarification.
> Pleasure helping you :)

Hello,

Thank you for your help.

While I was reading the guidance document, I noticed that I had to login before running my followers_scraper script.

I am such a newbie that I do not even know how to login and create or place a session file for a user. If you could please guide me, it will be helpful. Thanks !

**Comment by Deleora** [comment]
No problem. Though the documentation is pretty straight-forward I'll explain
### To create session file
1.  Open cmd and execute the following command
`instaloader --login YOUR-USERNAME`
2. It'll ask you to enter your password, enter it and you are good to go.

NOTE: No input will be shown on cmd while typing password so don't panic. just make sure you are typing it without errors.

Now whenever you run Instaloader on your PC, it'll load the session from this file which is by default saved in your TEMP folder (Windows).

Now you just need to edit the code you got and enter your username and the username of the profile you want to download. Then run the script as explained before.

**Comment by premchugh** [comment]
> No problem. Though the documentation is pretty straight-forward I'll explain
> 
> ### To create session file
> 1. Open cmd and execute the following command
>    `instaloader --login YOUR-USERNAME`
> 2. It'll ask you to enter your password, enter it and you are good to go.
> 
> NOTE: No input will be shown on cmd while typing password so don't panic. just make sure you are typing it without errors.
> 
> Now whenever you run Instaloader on your PC, it'll load the session from this file which is by default saved in your TEMP folder (Windows).
> 
> Now you just need to edit the code you got and enter your username and the username of the profile you want to download. Then run the script as explained before.

Hello Deleora,

Thank you for your help. It worked. I was able to create a session file.

When I ran the script which you had referenced, I got an error stating
"Too many queries in the last time. Need to wait 631 seconds, until 21:20."

Trying to look into the documentation for this error.

Thank you for  your help.

**Comment by Deleora** [comment]
You got that error probably because you are trying to download 'followers' of a profile that has a lot of followers and Instagram does not allow unofficial apps to query it's servers in bulk (like spamming) so that's just a measure to avoid spamming. At least this is what I have understood.
Though rest assured it's completely normal.

Also the code I shared is not well optimized so if you execute it for a profile with large number of followers, you are bound to get that message.

Anyway, I'm glad I could help you :)

**Comment by premchugh** [comment]
> You got that error probably because you are trying to download 'followers' of a profile that has a lot of followers and Instagram does not allow unofficial apps to query it's servers in bulk (like spamming) so that's just a measure to avoid spamming. At least this is what I have understood.
> 
> Though rest assured it's completely normal.
> 
> 
> 
> Also the code I shared is not well optimized so if you execute it for a profile with large number of followers, you are bound to get that message.
> 
> 
> 
> Anyway, I'm glad I could help you :)

Hi,

Is there a way wherein, I can tweak the code to only capture / scrape 10 followers every 10 minutes.

It would be helpful if I can get support.

Thank you.

**Comment by Deleora** [comment]
Why do you wanna do that?

**Comment by premchugh** [comment]
> Why do you wanna do that? 

That’s because I’m trying to scrape the list of followers from a public profile. Since my target profile has more than a million followers, Instagram will not allow me to scrape all of them in one instance. I will need to run Instaloader in batches to extract list of followers in a limited quantity.

All I need is their username, their profile status (Private or Public)

Is this something you can help me with ? Thank you.

**Comment by Deleora** [comment]
But I'm not able to understand why you want 10 profiles/10 mins (basically 1 profile per minute).
If you use the script with little modifications, which I think you already have done, it'll download approximately 100 profiles in 10 mins (i.e, 10 profiles per minute) including the wait time.

I tired with a profile having 3.3m followers and was able to scrape 200 followers in approx 22 minutes. Also you get that 'Too many queries in the last time. Need to wait xxx seconds, until hh:mm.' after every 100 queries. And it automatically resumes the script after that many seconds.

So getting 1 profile per minute is just a waste of time if you ask me.

**Comment by bipsen** [comment]
@Deleora, could you possile repost the code you wrote? It's gone on the bin, and I'd love to see it.

**Comment by Deleora** [comment]
[https://pastebin.com/W1mcmNQz](https://pastebin.com/W1mcmNQz)
This should be working fine though I haven't executed and checked.
