### ISSUE TITLE
post_filter - stop iteration

### ISSUE THREAD

**Issue by rocailler** [instaloader/instaloader#584]
In download_profiles it's checking all posts, how to add stop condition after achieve the older date value? Sometimes i need few newest posts but instaloader is checking few thousands of posts.

`Instaloader.download_profiles(profiles, post_filter=lambda post: post.date_utc >= datetime(2020, 4, 10))`

**Comment by e5150** [comment]
You'd have to implement your own loop, using `takewhile` [for example](https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period).
