### ISSUE TITLE
URL list of instagram posts 

### ISSUE THREAD

**Issue by test2a** [instaloader/instaloader#585]
can we use instaloader to get a list of all URLs of the posts and stories and profile and highlights, the one which the software later downloads?

**Comment by rocailler** [comment]
yes, with instaloader module. This is the link for all answers in profile, the rest goes similary.

```
profile = Profile.from_id(Instaloader.context, userId)
posts = profile.get_posts()
for post i posts:
    comments = post.get_comments()
    for comment in comments:
        answers = comment.answers
        for answer in answers:
            url = 'https://www.instagram.com/p/{}/c/{}/r/{}'.format(post.shortcode, comment.id, answer.id)
```

**Comment by test2a** [comment]
ok. some progress but not complete
 I did manage to get some errors out but its not working. That said, simply using the instaloader command in terminal works just fine.

> #!/usr/bin/env python
import instaloader
L = instaloader.Instaloader()
>profile = Profile.from_username(Instaloader.context, timcook)
posts = profile.get_posts()
for post in posts:
    comments = post.get_comments()
    for comment in comments:
        answers = comment.answers
        for answer in answers:
            url = 'https://www.instagram.com/p/{}/c/{}/r/{}'.format(post.shortcode, comment.id, answer.id)

now after removing some errors i am now facing 
>./url.py
Traceback (most recent call last):
  File "./url.py", line 2, in <module>
    import instaloader
ImportError: No module named instaloader


but i am able to do
>instaloader --fast-update --highlights --stories --login myusername --password mypassword profile timcook | tee -a `date +"%d-%m-%Y"`

and if i did  pip install instaloader, i get 
>pip install instaloader
Collecting instaloader
  Using cached https://files.pythonhosted.org/packages/86/be/95b14652bc85ce9c43da508d2d63954a736aa22ffedfb8b9cbed4d752a12/instaloader-2.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Instaloader requires Python >= 3.5.
    
    ----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-HPpjco/instaloader/
`

any help would be appreciated

**Comment by rocailler** [comment]
> Instaloader requires Python >= 3.5

do you have it? 
tried pip3 command? 

my personal newbie suggestion - download anaconda3 and lunch jupyter if you have no idea what are you doing on setup stage. 

you still have a lot of errors in code. My code was a simple sample of path templates. You need to modify it for own purpose.
timcook account is an private account - you need to be logged in and follow the account. 

code for posts urls (with login to download private accounts which you are following on THIS account):

`from instaloader import Instaloader, Profile
L = Instaloader()

#login
user = ''
password = ''
L.login(user, password)

nickname = 'timcook'
profile = Profile.from_username(L.context, nickname)
posts = profile.get_posts()
for post in posts:
    url = 'https://www.instagram.com/p/{}'.format(post.shortcode)
    print(url)`

**Comment by Thammus** [comment]
> and if i did pip install instaloader, i get
> >...
> > Instaloader requires Python >= 3.5.

See [Install Instaloader](https://instaloader.github.io/installation.html#install-instaloader).
