### ISSUE TITLE
downloading all stories that have a certain hashtag

### ISSUE THREAD

**Issue by kaiott** [instaloader/instaloader#586]
I'm trying to download all stories of the people I follow that have a certain hashtag or mention.
So something of the sort:

`instaloader --login=my_username --storyitem-filter=" '#desiredHashtag' in hashtags " :stories`

Where `'#desiredHashtag' in hashtags` is the condition I need to change. However, reading through the documentation I did not come across a way to do this, for the storyitem-filter there is no such attribute yet and I don't know how else I should go about this.
Help is appreciated!

**Comment by Thammus** [comment]
Accessing hashtags and other tappable objects like mentions in stories is not yet supported.
