### ISSUE TITLE
Download posts based on geotag and hashtag combined

### ISSUE THREAD

**Issue by Wazaki-Ou** [instaloader/instaloader#587]
I have been trying few things since I came across this library and so far I had some successful attempts downloading posts either by 1 geotag or 1 hastag within a restricted date period.

However, I am trying to find whether there is some way to combine both attributes to specify the posts I am interested in. When I try to select the posts I either use:

`posts = L.get_hashtag_posts('hashtag')  #for one hashtag`

or

`posts = L.get_location_posts(geotagid)  #for one geotag`

and then I call a loop to download the posts one by one. However, I would like to know if it's possible to combine both lines in one so that the posts have the hashtag AND the geotag I specified. Also, if possible, specifying more than 1 hashtag (for geotag, we can't have multiple, but for hashtag it's possible and more common). 

Example: I want to download posts that are geotagged with "New York time square" and that contain hashtags "#holiday" "#broadway". Would that be possible or do I have to settle for either one geotag or one hashtag ??

Thanks a lot for any help !!

**Comment by Wazaki-Ou** [comment]
@e5150 Thanks lot for your answer. I was actually considering a loop to filter the results as you said, but is there a way to check the hashtags for every post to see if the ones I need are included? I tried to check if posts have attributes I can get to do that, but the only filtering mentioned in the documentation is about what we want to download in a post. 
I am also considering accessing the JSON file for each post and parse it to retrieve hashtags, but that would be a lot more work.

**Comment by e5150** [comment]
`Post` objects have `.caption` and `.caption_hashtag` attributes (as well as `.location`, which however might incur extra queries to the IG servers).
These are the same attributes used by instaloader's internal filtering if you pass `--post-filter="'something' in caption` in the CLI or `post_filter=lambda p: 'something' in p.caption` to `download_location()`.
