### ISSUE TITLE
Infinite "Fatal error: Login: Checkpoint required." loop

### ISSUE THREAD

**Issue by Hexalyse** [instaloader/instaloader#589]
**Describe the bug**
I have a script running instaloader twice a day.
A few days ago apparently, it stopped working. I just noticed today. Checking the logs, indeed, it says the session file is not present (weird, because it always was).    
When trying to launch instaloader (with --stories for example) it asks to type password. Then is displays `Fatal error: Login: Checkpoint required. Point your browser to [URL] - follow the instructions, then retry.`.

Problem : even if I open URL, click on "it was me", next time I run instaloader, the same thing happens.

**To Reproduce**
- Try to launch an instaloader command requiring login. An error happen, saying a checkpoint it required.
- Open URL given, and click "It was me"
- Relaunch the command : same thing happen

**Expected behavior**
After opening the URL and validating the login, it should work.

**Instaloader version**
4.3.2

**Comment by e5150** [comment]
There's not a lot that instaloader can do when the IG servers finds suspicious usage. Are you running instaloader on your own computer, using a vpn or proxy? You could try [this](https://github.com/instaloader/instaloader/issues/92#issuecomment-451403508) code snippet to fill the session file with trusted cookies.

**Comment by marty90** [comment]
I am having this error too.

I am using the **Firefox** Cookie workaround. However, I notice that Instaloader sometimes re-write the session file after use, and, after, that, it can no longer be used.  Is this behavior expected?

I **solved** this by disabling the write permissions on that file with `chmod` but it seems a dirty workaround...

**Comment by aandergr** [comment]
> I am using the **Firefox** Cookie workaround. However, I notice that Instaloader sometimes re-write the session file after use, and, after, that, it can no longer be used. Is this behavior expected?

Instaloader always re-writes the session file after use (unless it aborts due to an error). However, it is absolutely not expected that it corrupts the session file. Is that reproducible?

**Comment by marty90** [comment]
My goal is to download the most recent posts of a given profile.
I use the --post-filter option with a check on the date.
However, the --post-filter option would check all the posts of a given profile, resulting in a long and unnecessary scan.
As such, I do the following:

```
instaloader $profile  $LOGIN    --no-pictures \
                                        --no-videos \
                                        --no-video-thumbnails \
                                        --no-captions \
                                        --post-filter="date_utc >= datetime($MIN_DATE)" \
                                        --dirname-pattern="$OUTDIR/{profile}" \
                                        > /tmp/instaloader_output_$profile 2>&1 &

PID=$!

while ( true ) ; do

if ps -p $PID > /dev/null
then
                :
else
    break
fi

if grep 'skipped' /tmp/instaloader_output_$profile 2>&1 > /dev/null
then
    break
else
                :
fi

done

kill -INT $PID
cat /tmp/instaloader_output_$profile
echo -e "\n"

```
