### ISSUE TITLE
Set download number

### ISSUE THREAD

**Issue by cineebay** [instaloader/instaloader#591]
Hi please how to set download post number like --count  also --post-filter="date_utc ... didn"t work for me

**Comment by e5150** [comment]
> how to set download post number like --count

Just pass the flag, followed by the number of posts you want, as an argument to the program. `--count` does however not apply to user profiles.

> didn't work for me

It works for me, so you're obviously doing something wrong. File a proper bug report if you think there is an error in the program. Or provide sufficient context if you're expecting a useful answer.

**Comment by cineebay** [comment]
For example how to download last 10 post videos from  profile something like this :

`instaloader profile 10 --post-filter="is_video"`

**Comment by cineebay** [comment]
i want to specify how much post will be downloaded
