### ISSUE TITLE
bug found

### ISSUE THREAD

**Issue by gs2713089** [instaloader/instaloader#592]
Describe the bug
I have a script running instaLoder twice a day.
A few days ago apparently, it stopped working. I just noticed today. Checking the logs, indeed, it says the session file is not present (weird, because it always was).
When trying to launch instaloader (with --stories for example) it asks to type the password. Then is displays Fatal error: Login: Checkpoint required. Point your browser to [URL] - follow the instructions, then retry...

Problem: even if I open URL, click on "it was me", next time I run instaloader, the same thing happens.

To Reproduce

Try to launch an instaloader command requiring a login. An error happens, saying a checkpoint it required.
Open URL is given, and click "It was me"
Relaunch the command: the same thing happen
Expected behavior
After opening the URL and validating the login, it should work.

Instaloader version
4.3.2

**Comment by e5150** [comment]
@gs2713089 are you a spam bot? If not, in what way do you think copy-pasting #589 as a new issue, with a nondescript title such as "bug found", would be useful?

**Comment by gs2713089** [comment]
No, it got paste by mistake.
