### ISSUE TITLE
Download tagged stories

### ISSUE THREAD

**Issue by gonzam88** [instaloader/instaloader#593]
How can I download all stories where my user is tagged ?

Thanks in advance

**Comment by Thammus** [comment]
Instaloader is not able to iterate stories by mentions. Does Instagram provide you a listing with stories where your user is tagged?

**Comment by gonzam88** [comment]
Kind of. I receive a direct message whenever someone tags me on either a story or post.

**Comment by Thammus** [comment]
Without Instagram providing us a listing of stories where your user is tagged, preferably through their web app, Instaloader will not support this feature.
