### ISSUE TITLE
Not installing on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by sidvud98** [instaloader/instaloader#596]
I am not able to install the program using this command `pip3 install instaloader`

I get this error

> Defaulting to user installation because normal site-packages is not writeable
Collecting instaloader
  Using cached instaloader-4.3.2.tar.gz (40 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-crhzc323/instaloader/setup.py'"'"'; __file__='"'"'/tmp/pip-install-crhzc323/instaloader/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-amvg1qhl
         cwd: /tmp/pip-install-crhzc323/instaloader/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/sidvud98/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 19, in <module>
        from setuptools.dist import Distribution
      File "/home/sidvud98/.local/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/home/sidvud98/.local/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Previously I had Ubuntu 18.04. It used to work like a charm. After upgrading to 20.04 it removed the package. And now I am not able to install.

**Comment by aandergr** [comment]
Doesn't look like a Instaloader bug. Fix your Python installation.
