### ISSUE TITLE
Logging indicates all images weren't downloaded

### ISSUE THREAD

**Issue by hotsauceio** [instaloader/instaloader#597]
**Describe the bug**
When downloading a profile (_marina.mari), the log never gets to the total amount. i.e. after running today the last output says [277/280]. When looking at how many metadata files were downloaded, only 278 (1 extra for profile pic) were downloaded. No other error messages are logged.

**To Reproduce**
instaloader _marina.mari

**Expected behavior**
A clear and concise description of what you expected to happen (if not obvious).
Last output should either be [277/277] or [280/280] (I'm unsure how many posts are actually there or what is causing this offset)

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.
No error messages in logs.

**Instaloader version**
`instaloader --version` output.
4.3.2

**Additional context**

(please also see https://instaloader.github.io/contributing.html for how to report a bug)

**Comment by Thammus** [comment]
This seems to be an error on Instagram's side. The web interface also shows only 277 posts while the `count` variable states 280.
