### ISSUE TITLE
Download Post from Shortcode

### ISSUE THREAD

**Issue by jingwuk** [instaloader/instaloader#598]
I need to know how can i download post from shortcode. 
I know that i need to use `Post.from_shortcode(L.context, SHORTCODE)`, n make new variable `SHORTCODE = 'B_uICfrlSd6'`.
But i havent figure out how to download it, ive tried to use the looping but it said that variable Post not iterable
Pls help

**Comment by Thammus** [comment]
Simply use [Instaloader.download_post()](https://instaloader.github.io/as-module.html#instaloader.Instaloader.download_post).
