### ISSUE TITLE
Download comments only from the post

### ISSUE THREAD

**Issue by jingwuk** [instaloader/instaloader#599]
when i use this code 
<pre>
from instaloader import Instaloader, Profile

PROFILE = 'ayutingting92'

L = Instaloader(download_pictures=False,
                download_video_thumbnails=False,
                download_videos=False,
                download_geotags=False,
                download_comments=True,
                save_metadata=False)

profile = Profile.from_username(L.context, PROFILE)

for post in profile.get_posts():
    L.download_post(post, PROFILE)
</pre>
i get 2 file, comment.json and a .txt containing the post maker comments. how can i only download the comment.json file?

**Comment by Thammus** [comment]
See parameter `post_metadata_txt_pattern` of [Instaloader constructor](https://instaloader.github.io/as-module.html#instaloader.Instaloader):
> post_metadata_txt_pattern (Optional[str]) – --post-metadata-txt, default is {caption}. Set to empty string to avoid creation of post metadata txt file.
