### ISSUE TITLE
Can I scrape some data of the last year?

### ISSUE THREAD

**Issue by pepe1325** [instaloader/instaloader#600]
Hello! Im trying to use Instaloader to scrape all the data from certain place from Feb 2019 - Feb 2020. It can be done? I tried the following code in a terminal: 
instaloader -l ******* -p ********* %214881134 --no-videos -G -C --post-filter='datetime(2019, 10, 19) <= date_utc < datetime(2019, 10, 20)'
Only download posts with property "datetime(2019, 10, 19) <= date_utc < datetime(2019, 10, 20)".
Session file does not exist yet - Logging in.
Logged in as *******.
Retrieving pictures for location 214881134...
JSON Query to explore/locations/214881134/: 429 Too Many Requests [retrying; skip with ^C]
HTTP error code 429 was returned because too many queries occured in
the last time. Please do not use Instagram in your browser or run
multiple instances of Instaloader in parallel.
The request will be retried in 666 seconds, at 21:34.
GraphQL requests:
  other
    last 10 minutes: 1 requests
    last 11 minutes: 1 requests
    last 15 minutes: 1 requests
    last 20 minutes: 1 requests
    last 30 minutes: 1 requests
    last 60 minutes: 1 requests

Im trying to do this like a month ago, and I Always get that message or "Need to wait x Seconds". And i know that after that the program can go on. But I dont know if i can scrape data that is that old, like a year old.

**Comment by aandergr** [comment]
See

- [429 - Too Many Requests](https://instaloader.github.io/troubleshooting.html#too-many-requests) and
- [Download Posts in a Specific Period](https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period).
