### ISSUE TITLE
Add is_business_account and business_category_name properties to Profile structure

### ISSUE THREAD

**Issue by cocohub** [instaloader/instaloader#601]
**Provide us a use case of the feature**
Filter profiles depending on if they have a business account or not, also if you wanna filter further, you could match the business category name as well.

**Describe the solution you'd like**
Add above mentioned properties to the Profile structure.

**Describe alternatives you've considered**
Current solution:
```
import requests
import json

url = 'https://www.instagram.com/username/?__a=1'

r = requests.get(url)
info = r.json()

print(info['graphql']['user']['is_business_account'])
print(info['graphql']['user']['business_category_name'])
```

![image](https://user-images.githubusercontent.com/15689511/81091790-fcf5e700-8eff-11ea-858a-f59fb615fc48.png)

**If the feature request is accepted, would you be willing to submit a PR?**
Yes.

**Comment by aandergr** [comment]
Sounds good! Feel free to propose a Pull Request, ideally based on our `v4.4-dev` branch.

**Comment by aandergr** [comment]
Merged. Thanks!
