### ISSUE TITLE
Include "address_json" in non-logged in download_post call. 

### ISSUE THREAD

**Issue by Mokhir** [instaloader/instaloader#603]
**Provide us a use case of the feature**
So https://github.com/instaloader/instaloader/blob/master/instaloader/structures.py#L80 says that `post._node = post._full_metadata`. 

But in **_full_metadata** property exists the **address_json** which is incredibly useful.
```
"location":{
      "id":"259038973",
      "has_public_page":True,
      "name":"Rockland County, New York",
      "slug":"rockland-county-new-york",
      "address_json":"{\"street_address\": \"\", \"zip_code\": \"10956\", \"city_name\": \"Rockland County, New York\", \"region_name\": \"\", \"country_code\": \"US\", \"exact_city_match\": true, \"exact_region_match\": false, \"exact_country_match\": false}"
   },
```

However, the **_node** object missing the **address_json** field.
```
"location":{
      "id":"259038973",
      "has_public_page":True,
      "name":"Rockland County, New York",
      "slug":"rockland-county-new-york"
   },
```

There is a workaround in calling the **_full_metadata** property separately, but it slows down the computation times of download_post(...) significantly. A full call for 10 posts is 4 seconds w/o, and 28 seconds with the _full_metadata additional call.

Also, `post._field("address_json")` has a KeyError here: https://github.com/instaloader/instaloader/blob/master/instaloader/structures.py#L163

**Describe the solution you'd like**
Fix the bug or issue or whatever it is that stops the address_json from being written into the post file.

**Describe alternatives you've considered**
Here is a code workaround that has a 10x increase in operation time and sucks.
```
if (post._full_metadata['location']['address_json']):
                            address_dict = json.loads(post._full_metadata['location']['address_json'])
                            city_name = address_dict['city_name']
                            post_dict['city_name'] = str(city_name)
```

**If the feature request is accepted, would you be willing to submit a PR?**

Yes I would, but I would need assistance with the code base. Also my first PR.

**Additional context**

**Comment by Mokhir** [comment]
To clarify, this is NOT LOGGED IN.

**Comment by aandergr** [comment]
Thanks for sharing your observations! 

A few things we noticed regarding this:

- It seems that it is now possible to access the location field anonymously, so we probably could revert 0aa1ec7c76dbb75e3d695f9489df087113bc74c8.
- We can access `address_json` via `Post._field("location", "address_json")` (no KeyError there). We would accept a Pull Request that exposes the `address_json` as a Post property or adding it to the `PostLocation` NamedTuple returned by `Post.location`. Of course we can assist with the code base.
- It's unlikely that there exists a workaround for the "10x increase in operation time". If the `location` field is not contained in `Post._node`, the full metadata fetch needs to be done to access the field.
