### ISSUE TITLE
Is there a way to download messages?

### ISSUE THREAD

**Issue by Deleora** [instaloader/instaloader#607]
I want to backup all of my DMs to my laptop. Instagram provides this option with a limit of 1 request per 4 days through 'Request data' in settings. So I was wondering, is it possible to download my messages by overcoming this limit using instaloader?

**Comment by aandergr** [comment]
Nice idea; hiowever, Instaloader does not yet support accessing DMs.

**Comment by Deleora** [comment]
Any possibility of adding it to instaloader?

**Comment by Deleora** [comment]
> Nice idea; hiowever, Instaloader does not yet support accessing DMs.

Any possibility of adding it to instaloader?

**Comment by aandergr** [comment]
Sure, we would love to review a PR for that feature! Just had a look with Chrome DevTools into it and it doesn't seem that hard to access. Surprisingly, it doesn't use the GraphQL API, but on the first glance it still seems compatible with our existing structures. It will require some engineering to cleanly access the according endpoints and to nicely present the data structures (the threads with metadata such as `users` and `inviter` and the message items of at least two types, `text` and `reel_share`).

**Comment by Deleora** [comment]
Sounds good, looking forward for this feature soon. Loving instaloader 👍👍
