### ISSUE TITLE
Story visible to closed friends?

### ISSUE THREAD

**Issue by Deleora** [instaloader/instaloader#608]
When my friend puts a story which is visible just to followers in his/her 'Close Friends' list, is there a way to separate out such stories with normal ones while downloading?

**Comment by aandergr** [comment]
Currently we don't see any way to access this information.

**Comment by Deleora** [comment]
> Currently we don't see any way to access this information.

Ok

**Comment by Deleora** [comment]
> Currently we don't see any way to access this information.

I think now we can know if the stories are visible to all or only close friends.
I checked in 2 stories one which was normal and the other which was visible only to close friends. When we see the JSON file downloaded along with the story item, the `"node"` of the JSON files has a new field called `"audience"`.
For normal stories this has a value `"MediaAudience.DEFAULT"` and the ones visible to close friends has the value `"MediaAudience.BESTIES"`

For better reference:
Normal Story JSON file snippet:
```
{
    "instaloader": {
        "node_type": "StoryItem",
        "version": "4.6"
    },
    "node": {
        "__typename": "GraphStoryVideo",
        "audience": "MediaAudience.DEFAULT",
        "dimensions": {
            "height": 1233,
            "width": 750
        },
...
```

Close Friends Story JSON file snippet:
```
{
    "instaloader": {
        "node_type": "StoryItem",
        "version": "4.6"
    },
    "node": {
        "__typename": "GraphStoryImage",
        "audience": "MediaAudience.BESTIES",
        "dimensions": {
            "height": 1233,
            "width": 750
        },
...
```

**Comment by Thammus** [comment]
Ah, cool. 🤩 Thank you very much for sharing this observation!
