### ISSUE TITLE
Add Captions to Images Error

### ISSUE THREAD

**Issue by Deleora** [instaloader/instaloader#609]
**Describe the bug**
When trying to [add captions to posts](https://instaloader.github.io/codesnippets.html#add-captions-to-images) which has emojis, the emoji part does not come as it is. It either does not show anything or adds some symbol in it's place

**To Reproduce**
Execute:
`from io import BytesIO`
`from requests import get`
`from PIL import Image, ImageDraw`
`from instaloader import *`
`your_username = USERNAME`
`L = Instaloader()`
`L.load_session_from_file(your_username)`
`post = load_structure_from_file(L.context, JSON_FILE_NAME.json)`
`image = Image.open(BytesIO(get(post.url).content))`
`draw = ImageDraw.Draw(image)`
`color = 'rgb(0, 0, 0)'  # black color`
`draw.text((300,700), post.caption.encode('latin1', errors='ignore'), fill=color)`
`image.save('test.jpg')`

Original image : https://imgur.com/h2Vemme
Output Image : https://imgur.com/My3KsNt
JSON File text: `edge_media_to_caption":{"edges":[{"node":{"text":"😂Be anything but predictable."}}]} `

**Expected behavior**
I expected the caption to come like "😂Be anything but predictable." on the output image

**Error messages and tracebacks**
No error messages

**Instaloader version**
`instaloader --version` output.
4.3.2

**Additional context**

(please also see https://instaloader.github.io/contributing.html for how to report a bug)

**Comment by aandergr** [comment]
That code snipped is an approach only, it does not intend to fully cover that use case. However, if you find a simple way to do that, feel free to share it with us!
