### ISSUE TITLE
get_locations() has a Key error with [loc'lat'] ?

### ISSUE THREAD

**Issue by spellcaster88** [instaloader/instaloader#610]
**Describe the bug**
in get_locations
    yield PostLocation(int(loc['pk']), loc['name'], slug, None, loc['lat'], loc['lng'])
KeyError: 'lat'

**To Reproduce**

instaloader.TopSearchResults(L.context,search_string).get_locations():

**Expected behavior**

get Locations strings 

**Instaloader version**
`instaloader --4.4lb

![Screenshot (294)](https://user-images.githubusercontent.com/17952986/81491736-28395700-92af-11ea-86d0-794acf987e19.png)

**Comment by Thammus** [comment]
Hi,
while trying to reproduce this, I tested `TopSearchResults.get_locations()` and the KeyError did not occur. Is there a reliable way to reproduce this error?
