### ISSUE TITLE
Non-english hashtags not downloading

### ISSUE THREAD

**Issue by tuominteemo** [instaloader/instaloader#614]
Hashtags with non-english characters are not downloading anymore with the latest version of Instaloader.

For example, this hashtag https://www.instagram.com/explore/tags/кошка/

`instaloader "#кошка"`

gives an error:

```
Errors occurred:
#кошка: Invalid hashtag #кошка
```

Downloading hashtags with foreign letters worked before the latest update (with both Windows and Linux versions).

**Comment by aandergr** [comment]
Thanks for reporting! We released [Instaloader 4.4.1](https://github.com/instaloader/instaloader/releases/tag/v4.4.1) where this is fixed.
