### ISSUE TITLE
Is there a way to get the exact/approximate time at which my story was seen by each viewer?

### ISSUE THREAD

**Issue by Deleora** [instaloader/instaloader#617]
I wanna extract the list of all the viewers of my story along with the time at which they viewed my story. Is this possible?

**Comment by Thammus** [comment]
Instagram states in their [help section](https://help.instagram.com/202055156863605) to hold this information available for 48 hours. However, it is unlikely that we can get this information through the web API. At the moment Instaloader does not provide any information about own stories.

**Comment by Deleora** [comment]
But we can get just the list of accounts who have viewed my story. Right?

**Comment by Deleora** [comment]
> But we can get just the list of accounts who have viewed my story. Right?

Can we?

**Comment by aandergr** [comment]
As @Thammus said before:

> At the moment Instaloader does not provide any information about own stories.
