### ISSUE TITLE
CLI command to save stories / highlights folders inside the profile folder instead of saving it in another folder

### ISSUE THREAD

**Issue by marcin-przywoski** [instaloader/instaloader#619]
Does anyone know what is the CLI command to save stories / highlights folders inside the profile folder instead of saving it in another folder? I'm tired of having to move it every time.

**Comment by Deleora** [comment]
Create a .bat file that creates a new folder to location you want and then calls the Instaloader with the arguments you want. 
For eg, I execute this .bat file from my desktop and it saves the profile to a custom directory created based on my current system date and time...

> E:
> cd "E:\Instaloader"
>//_Creates folder in YYYY-MM-DD format_
> mkdir %date:~6,4%-%date:~3,2%-%date:~0,2%
>//_Goes inside the created folder_
> cd %date:~6,4%-%date:~3,2%-%date:~0,2%
>//_Creates folder in HHMM format_
> mkdir %time:~0,2%%time:~3,2%
>//_Goes inside the created folder_                    
> cd %time:~0,2%%time:~3,2%
>//_Execute instaloader_
> instaloader --stories --highlights --comments --geotags --tagged --no-compress-json --login USERNAME PROFILE

Copy past this snippet in a notepad and save the file as .bat. Also remove the lines with '//' as that is not part of commands and will give error.
You can modify the base directory (in my case E:\Instaloader) and how the folders are created according to your needs. Let me know if it helps or if facing any issues. Peace
