### ISSUE TITLE
Fatal error: Login error: JSON decode fail, 400 - Bad Request.

### ISSUE THREAD

**Issue by rjvs7** [instaloader/instaloader#620]
I'm trying to get the profile info using --login option and it errors out with:

[root@xxxx ~]# instaloader --login xxxx yyyy
Session file does not exist yet - Logging in.
Enter Instagram password for xxxx:
Fatal error: Login error: JSON decode fail, 400 - Bad Request.

How do i create a session file or overcome this issue?

I have enabled mobile code verification on my insta profile.

**Comment by tmrwlsn** [comment]
I'm having this same problem. I tried different accounts, made sure to get the latest version, even restarted computer. Linux user. Can't say I can help, but you're not alone. Might be a new issue

**Comment by Infinitay** [comment]
> There have been changes regarding the login on Instagram's side and Instaloader's login functionality is currently broken. As long as there does not exist any solution, we can only present the following advice:
> 
> * The workaround described in [Troubleshooting - Login Error](https://instaloader.github.io/troubleshooting.html#login-error), which creates the sessionfile from the Firefox cookie database, still works.
> * Always keep your sessionfile. I have never seen a sessionfile expire. If you have your sessionfile, no login is required, and thus, no login can fail.
> 
> The snippet posted in this issue to allegedly fix the login error does not seem to work. As always, we are very open to discuss ideas in Pull Requests.



Taken from the fourth issue down prior to the creation of this one. 
https://github.com/instaloader/instaloader/issues/615#issuecomment-629699078

**Comment by ELR12** [comment]
@Infinitay thanks for posting the Troubleshooting - Login Error workaround link, however that snippet is outdated as Mozilla has updated their query column names, making the SQL statements fail in that snippet. I have created a fix for this, and I can create a PR for it.  How should I proceed?
