### ISSUE TITLE
How Can I Scrape All Hashtags of a Profile?

### ISSUE THREAD

**Issue by abtvah2** [instaloader/instaloader#622]
Hello and thanks for this hassle-free job, I have a question, is there any way to scrape all hashtags of posts from a certain profile? 
Currently I am successful with scraping all captions of posts, but hashtags are mixed with other descriptions too. Sure, one way is to write a code to look into all .txt files related to captions and extract all hashtags, but just curious if there is an easy way to scrape hashtags only from captions at first hand.

**Comment by e5150** [comment]
Instaloader does not extract hashtags from posts. But on unix it's easy enough to do by yourself:
`awk '{for (i=0; i < NF; ++i) {if (substr($i, 0, 1) == "#") print $i}}' < 2020-05..._UTC.txt`
However, a user can put hashtags in comments on their posts. If you have scaped comments the following can be used to get the poster's comments, to be passed to awk for hashtag parsing:
`jq --arg user USERNAMEHERE -r 'select(.[].owner.username == $user) | .[].text' < 2020-05..._comments.json`

**Comment by e5150** [comment]
`Post` objects have the `caption_hashtag` attribute.
However,  user can put hashtags in comments on their posts aswell. If you are on unix and have scraped comments, you can use the following:
```
cat 2020-05..._comments.json \
| jq --arg user PROFILENAMEHERE -r 'select(.[].owner.username == $user) | .[].text' \
| awk '{for (i=1; i < NF; ++i) {if (substr($i, 0, 1) == "#") print $i}}'
```
To get the hashtags a user has posted in the comments.

**Comment by abtvah2** [comment]
That was a nice trick, thanks

**Comment by abtvah2** [comment]
So I have to access that caption_hashtag property through instaloader module only?

**Comment by e5150** [comment]
It can be accessed for metadata storage, i.e. `--post-metadata-txt "{caption_hashtags}"`, which would save only the hashtags in your .txt-files.
(And sorry, it's `caption_hashtags`, plural-s at the end.)

**Comment by abtvah2** [comment]
Many thanks, very clean solution.
