### ISSUE TITLE
Abort on first skip

### ISSUE THREAD

**Issue by stiflermt** [instaloader/instaloader#627]
Your question here...
Hi, is there a means to terminate the post download loop on the first skipped post that failed the python expression. Let's say a profile has 10k posts, but after evaluating the first 100 based on post date, post 101 evaluates to false. This means that all other posts would also fail the check and hence would be more efficient to break the loop. I had a look at the python module documentation but could not identify any call to do this

**Comment by stiflermt** [comment]
Made some small progress on getting this to work but noticed that my implementation is unstable for tags with heavy traffic, it works fine for a small profile but once there is a lot of images it seems to loop to infinity triggering the IG rate limiter. Any suggestions?

`import instaloader
import datetime
from termcolor import colored

CUTOFF_DATE="2020-05-09 00:00:00" # Holds the cutoff download date
CURRENT_DATE=datetime.datetime.now() # Holds the current date
date_time_obj = datetime.datetime.strptime(CUTOFF_DATE, '%Y-%m-%d %H:%M:%S') # cast string as datetime for use in IF statements`

`def function_download_post(session,profile):
    """
    Function to download posts from Instagram for a given proile
    :param session: The Instaloader session object
    :param profile: Profile to scrape / download
    :return: N/A
    """
    for post in instaloader.Profile.from_username(session.context,profile).get_posts():
        if post.date >= date_time_obj:
            # If post timestamp is within rage - download
            Instagram_Session.download_post(post, target=profile)
        else:
            print(colored("Cutoff date exceeded - exiting loop",'red'))
            break # Break loop since cutoff date exceeded`

Example two - trying to download highlights

`def function_download_hashtag(session,hashtag):
    """
    Function to download Instagram hashtags
    :param session: The instaloader session object
    :param hashtag: hashtag to scrape / download
    :return: N/A
    """
    for post in instaloader.Hashtag.from_name(session.context, hashtag).get_posts():
        if post.date >= date_time_obj:
            # If post timestamp is within rage - download
            Instagram_Session.download_post(post, target=hashtag)
        else:
            print(colored("Cutoff date exceeded - exiting loop",'red'))
            break # Break loop since cutoff date exceeded`

In the above code dump, I left out the routines to retrieve the UID from profile name etc.. as I doubt they are the source of the issue

**Comment by aandergr** [comment]
You may want to have a look at the [takewhile()](https://docs.python.org/3/library/itertools.html#itertools.takewhile) function and this example: https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period for an efficient way to achieve this.
