### ISSUE TITLE
get_followees() not returning any data.

### ISSUE THREAD

**Issue by JayGrieve** [instaloader/instaloader#629]
**Describe the bug**
When calling get_followees(), the genreator yields no results. This is not an issue I was having yesterday. This is happening across all accounts I have tried.

**To Reproduce**
Load any account and attempt to retrieve the followees.

**Expected behavior**
The followees

**Error messages and tracebacks**
No error is created.

**Instaloader version**
4.3.2

**Additional context**
None

**Comment by aandergr** [comment]
I cannot reproduce this, get_followees() works for me.
