### ISSUE TITLE
instaloader doesn't download the highest resolution images

### ISSUE THREAD

**Issue by fireattack** [instaloader/instaloader#630]
**Describe the bug**

Instagram serves a higher resolution of images to its App clients, which you can also get by a little bit reverse engineering once you are logged in.

Currently, it seems instaloader doesn't use it.

**To Reproduce**

`instaloader --login={yourusername} -- -CAcwc-NDSWU`

**Expected behavior**
It should get the 1440x960 version of the first image:
 
https://scontent-dfw5-2.cdninstagram.com/v/t51.2885-15/e35/98421488_278962616829644_2517508973627414945_n.jpg?_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_ohc=HW1l4SpzdLwAX_mv9wA&oh=4c35180fb607380b860dfb1677afa52f&oe=5EEFFF97

However, instaloader will download a interior 1080x720 version:

https://scontent-dfw5-2.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/98421488_278962616829644_2517508973627414945_n.jpg?_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_ohc=HW1l4SpzdLwAX_mv9wA&oh=3fdbf984790eea0a74e1ceb4de05e330&oe=5EF26245

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

**Instaloader version**
4.4.2

**Comment by aandergr** [comment]
Implemented with 4.4.4.

**Comment by fireattack** [comment]
@aandergr thanks for the fix! but jsut one more thing.

I believe we need to remove some queries from the direct image link to actually get hte maximum quality. 

Specifically, the `se=xxx`, will cause it to give inferior results.

In the case above, the direct link returned is `https://scontent-dfw5-2.cdninstagram.com/v/t51.2885-15/e35/98421488_278962616829644_2517508973627414945_n.jpg?_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_cat=108&_nc_ohc=swTIX95uJyMAX-sOowR&se=7&oh=f4a82f93b1bd71bd9da72320e2bd7e7b&oe=5F03C617&ig_cache_key=MjMxMzkzNzQwMjE4MTk5MTU4MQ%3D%3D.2`, which is a 107KB image;

But  if you remove se=7, i.e. `https://scontent-dfw5-2.cdninstagram.com/v/t51.2885-15/e35/98421488_278962616829644_2517508973627414945_n.jpg?_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_cat=108&_nc_ohc=swTIX95uJyMAX-sOowR&oh=f4a82f93b1bd71bd9da72320e2bd7e7b&oe=5F03C617&ig_cache_key=MjMxMzkzNzQwMjE4MTk5MTU4MQ%3D%3D.2`, it give a 130KB image.

And it's not just about the number; I compared the two the larger one indeed has slightly better quality. 

There are some other query values that are not needed,  namely `["_nc_cat", "_nc_rid", "efg", "ig_cache_key"]`, but I will let you decide if you want to keep them since they don't seem to affect quality. 

Please see https://github.com/qsniyg/maxurl/issues/239 for more details and thanks qsniyg for his great project.

**Comment by aandergr** [comment]
Thanks, 610b624, included in  [Version 4.4.4rc2](https://github.com/instaloader/instaloader/releases/tag/v4.4.4rc2), removes the `se` parameter.
