### ISSUE TITLE
UI 

### ISSUE THREAD

**Issue by manishdashsharma** [instaloader/instaloader#634]
Your question here...
Is it possible to create an UI for this module rather typing commands in command prompt ?

**Comment by aandergr** [comment]
Too unspecific question to give a good answer. You can always wrap some kind of UI around a module.

**Comment by manishdashsharma** [comment]
To work on this module we have to give commands on our command prompt i.e instaloader profile [profil name...] . Is there any UI already developed for instaloader ? 
what i mean rather typing a command in command prompt we can use the UI to download the post . There should be a input box which will take user name and next box will have commands . after that when i press enter the post will get downloaded .

**Comment by aandergr** [comment]
From what we notice from our users, our CLI is typically considered simple to use and well documented, so I don't think there are any serious efforts on a graphical user interface to Instaloader.

**Comment by psonnosp** [comment]
I would love to have a GUI for instaloader, been using jdownloader up until now but it went dead yesterday.
Been using this to get stories but for someone not used to CLI it's very time consuming. And **a lot** of try and (mostly) error :wink:
Let's hope someone that knows what they are doing get some free time some day and creates one...
