### ISSUE TITLE
Continuing using a stored cursor token

### ISSUE THREAD

**Issue by salehio** [instaloader/instaloader#636]
To avoid throttling, I wanted the ability to fetch data only after a certain date. Trying the method listed [here](https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period) it appears that the filter is client side, and would page through all the GraphQL requests grabbing the cursor token to build the next one.

Is it possible anywhere in the client to pass in a previously stored continuation token? Do you know how long these are normally valid for?

If there's no supported way to do that currently, I'd be interested in contributing it as a feature the the module itself, but not necessarily wiring it up to the CLI.

**Comment by aandergr** [comment]
> Is it possible anywhere in the client to pass in a previously stored continuation token?

That is not yet possible. However, it might be a smart way to resume an interrupted download loop. Our client for [GraphQL Cursor Connections](https://relay.dev/graphql/connections.htm), which are typically used for paginated data, is implemented in InstaloaderContext.graphql_node_list():

https://github.com/instaloader/instaloader/blob/72d86533f25180bc7e1df467718c568ac2b77d53/instaloader/instaloadercontext.py#L496-L525

In theory, you could pass as first_data an object that has data['page_info'] setup up such that graphql_node_list() starts with a previously stored end_cursor. However, there is no way to inject such a token into the functions that call graphql_node_list() yet.

> Do you know how long these are normally valid for?

I don't know how long the cursors last, but I am optimistic that they last forever. Some backend implementations use an encoding of the node type and an id unique within types of the same node. In the case of Instagram post connections, I do not know what is is exactly.

**Comment by salehio** [comment]
I'll try passing in the first_post soon to see if that works smoothly.

Implementing this seems dirty. Either we can create an optional parameter for the token and add it to all functions that call `graphql_node_list` --  or have it be something you set on the `Profile` class, and it gets implicitly used, but the user can reset it if they don't want to use it anymore. That's not very clean, since (I guess) a token would only be valid for a single method. You couldn't use a token for getting all the posts for also paging through `similar accounts`.

Any preferences?

**Comment by salehio** [comment]
Just realized, we would also have to expose a way for the module user to retrieve the token for storing.

**Comment by aandergr** [comment]
Cleanly implementing this would require some refactoring. An approach could be making the graphql_node_list iterator to an iterator class which exposes some way to handle setting the token, and make all functions using graphql_node_list to iterators inherited by the new graphql node list class, thereby also allowing the user to set an initial cursor token.

**Comment by r786786** [comment]
@salehio I was wondering the same thing. I'm not that familiar with python but I've tested a solution that worked on the instagram site. Can I contact you anywhere else on discord or something? If not, I can explain my idea here as well if you'd like.

**Comment by tonycpsu** [comment]
I did a quick and dirty implementation of this in #683 without any major refactoring.  I found two ways to get the end_cursor value, both of which come with their own problems.

My first try was to used `Post._full_metadata["edge_media_to_parent_comment"]["page_info"]["end_cursor"]`.  The good news attribute seems to be available and unique for every post, but the bad news is that using this cursor value yields duplicates, and not a predictable number of them.  The caller could keep track of this and ignore the items they already have, but that seems like a hassle.

So instead, I just used the `end_cursor` from the graphql pagination in `InstaLoaderContext`.  This seems to be an accurate value of the cursor for the last post on each page, which ensures there are no duplicates or missed posts, but this requires the user to know how the data is paginated by the API.  So I added `page_size` parameters to `InstaLoader` and `InstaLoaderContext`, and it appears to work fine.

I've only added this support to `Profile.get_posts()` so far, and haven't bothered to add it to the CLI yet, either.  Will wait for feedback before considering adding those.

**Comment by r786786** [comment]
@tonycpsu Ah, also say for example I am able to manually retrieve the correct value for the end_cursor. Is there a way I can use that value to resume a session? I have tried implementing this by using the end_cursor value and setting it as the max_id, so I know this is possible, but I just need someone who's well versed in python to do this for me, I can explain further of how this would be possible to someone who understands python. If you're interested, I can explain on discord.

**Comment by tonycpsu** [comment]
@r786786 , yeah, that should work.  This is roughly how I'm using it:

```python
    import itertools
    from instaloader import Instaloader, Profile

    limit = 50
    loader = Instaloader(page_size=limit)

    def fetch(user_name, cursor=None):
        profile = self.session.profile_from_username(user_name)
        for post in islice(profile.get_posts(end_cursor=cursor), limit):
            # do stuff with the post
            end_cursor = post.end_cursor # save end_cursor somewhere
```
The first time, it's called with `fetch(user_name)` to get the first 50 posts, then the next time it's called with `fetch(user_name, end_cursor=[saved value]`.  In your case it sounds like you just want to start by passing in an `end_cursor` you've already saved, which should work fine.

**Comment by aandergr** [comment]
https://github.com/instaloader/instaloader/pull/732 implements continuing a previously-interrupted download loop by storing the iterator's status into a JSON file when interrupted, similar to how I suggested here: https://github.com/instaloader/instaloader/pull/683#issuecomment-645549520.
