### ISSUE TITLE
how to handle login informations with facebook

### ISSUE THREAD

**Issue by kikieri** [instaloader/instaloader#638]
hey,
wanna download something from a private profile I follow.
My login is with facebook.
Mail / Username is not accepted :
"Fatal error: Login error: User *********** does not exist."

Has something to do with the facebook login bcs its not a normal login no?

any suggestions?

thanks for you project! great idea

**Comment by aandergr** [comment]
Instaloader does not yet support logging in to Instagram via Facebook. To still login, you could e.g. set a password for your Instagram account and use that for logging in, see https://help.instagram.com/409847499070242
