### ISSUE TITLE
Private Accounts don't exist?

### ISSUE THREAD

**Issue by Butitistrue123** [instaloader/instaloader#640]
**Describe the bug**
Private Profile does not exist. But downloads their profile pic but nothing else. 

**To Reproduce**
Instaloader --login=(myusername) --password:(mypassword) profile (celebrity)

**Expected behavior**
I expected the private profile to download normally. I login with password successfully. Public profiles are unaffected.

**Error messages and tracebacks**
Errors occur:
- Could not find "windows._sharedData" in html response.
- 404 NOT found
- Private profiles do not exist.  
- The most similar profiles are..... (generic1)
- (Celebrity profile): private but not followed.

**Instaloader version**
V.4.4.3

**Additional context**
I am new to this :) Great app! Help?

**Comment by Deleora** [comment]
Is this happening with just one profile or all the private profiles followed by you?

**Comment by Butitistrue123** [comment]
Every profile. I have tried 3 private profiles now. Same message every time.

**Comment by aandergr** [comment]
Could you please show us your complete Instaloader log output, rather than a summary of the messages? (of course, you may anonymize profile names etc.)

**Comment by Butitistrue123** [comment]
![Instaloader](https://user-images.githubusercontent.com/66082307/83326794-b2515b80-a26e-11ea-94dc-879702ccec5b.png)

I've attached a screenshot. Not sure how to produce an output.

**Comment by Deleora** [comment]
After your password you are giving 'profile' which Instaloader takes as an Instagram account. You are suppose to give the account name directly. Remove 'profile'.

That's why it's suggesting possible accounts with username containing 'profile'

Change your command to:
instaloader --login=butitistrue1234 --password=****** grace_cassidy1

**Comment by Deleora** [comment]
> **Describe the bug**
> Private Profile does not exist. But downloads their profile pic but nothing else.
> 
> **To Reproduce**
> Instaloader --login=(myusername) --password:(mypassword) profile (celebrity)
> 
> **Expected behavior**
> I expected the private profile to download normally. I login with password successfully. Public profiles are unaffected.
> 
> **Error messages and tracebacks**
> Errors occur:
> 
> * Could not find "windows._sharedData" in html response.
> * 404 NOT found
> * Private profiles do not exist.
> * The most similar profiles are..... (generic1)
> * (Celebrity profile): private but not followed.
> 
> **Instaloader version**
> V.4.4.3
> 
> **Additional context**
> I am new to this :) Great app! Help?

Also you have given wrong **To Reproduce** 😅
It should be:
instaloader --login=(myusername) --password=(mypassword) profile (celebrity)
But you gave:
Instaloader --login=(myusername) --password:(mypassword) profile (celebrity)

**Comment by Butitistrue123** [comment]
I used your command but I get the exact same message as in my screenshot.

**Comment by Deleora** [comment]
> I used your command but I get the exact same message as in my screenshot.

Send the new ss plz.

**Comment by aandergr** [comment]
The log says two things:

1. You try to download a profile named `profile`, which doesn't exist, 
1. You try to download a private profile that you don't follow, which is not possible. 

I don't see any bug here.
