### ISSUE TITLE
raise 429 Error instead of sleep

### ISSUE THREAD

**Issue by heyt0ny** [instaloader/instaloader#641]
Hi!

I'm parsing Instagram from multiple servers, that are getting ig_names from master server. And I want to detect that current server is temporary down for new ig_names if it hits 429 status code. So I need to know if latest request from server to IG was with 429 status. 

I'm using
```
L = instaloader.Instaloader(sleep=False,
                                    quiet=False,
                                    user_agent=ua.random,
                                    max_connection_attempts=0)
insta_profile = instaloader.Profile.from_username(L.context, link)
```
But if it hits 429 status - it sleeps and prints:
```
JSON Query to <ig-name>: 429 Too Many Requests: redirected to login [retrying; skip with ^C]
HTTP error code 429 was returned because too many queries occurred in
the last time. Please do not use Instagram in your browser or run
multiple instances of Instaloader in parallel.
GraphQL requests:
  other
    last 10 minutes: 1 requests
    last 11 minutes: 1 requests
    last 15 minutes: 1 requests
    last 20 minutes: 1 requests
    last 30 minutes: 1 requests
    last 60 minutes: 1 requests
```

How can I make it raise Exception instead of sleep behaviour ?

**Comment by aandergr** [comment]
Instaloader always invokes its 429 handling logic when a 429 is encountered. You could change the corresponding code in instaloadercontext.py to make it raise some custom exception on a TooManyRequestsException:

https://github.com/instaloader/instaloader/blob/72d86533f25180bc7e1df467718c568ac2b77d53/instaloader/instaloadercontext.py#L439-L457
