### ISSUE TITLE
429 Error when only 1 requests

### ISSUE THREAD

**Issue by heyt0ny** [instaloader/instaloader#643]
**Describe the bug**
After parsing profile for 1 time, I get immediately 429 error for second,... request
```JSON Query to <ig_profile>/: 429 Too Many Requests: redirected to login [retrying; skip with ^C]
HTTP error code 429 was returned because too many queries occurred in
the last time. Please do not use Instagram in your browser or run
multiple instances of Instaloader in parallel.
GraphQL requests:
  other
    last 10 minutes: 1 requests
    last 11 minutes: 1 requests
    last 15 minutes: 1 requests
    last 20 minutes: 1 requests
    last 30 minutes: 1 requests
    last 60 minutes: 1 requests
```
**To Reproduce**
```
L = instaloader.Instaloader(sleep=False,
                                    quiet=False,
                                    user_agent=ua.random,
                                    max_connection_attempts=0)
insta_profile = instaloader.Profile.from_username(L.context, link)

```
**Expected behavior**
Not raise 429 error when parsing profile after 1 requests

**Error messages and tracebacks**
If applicable, add error messages and tracebacks to help explain your problem.

**Instaloader version**
4.4.1

**Comment by aandergr** [comment]
Please consider reading [429 - Too Many Requests](https://instaloader.github.io/troubleshooting.html#too-many-requests) in our Troubleshooting section, where this is most likely answered.
