### ISSUE TITLE
Mutual Followers

### ISSUE THREAD

**Issue by Deleora** [instaloader/instaloader#646]
Is there a way to get all the mutual followers of a profile?
I checked with Chrome dev tools but no luck, maybe i missed something.

**Comment by aandergr** [comment]
This is trivial to achieve with what Instaloader provides:

```python
from instaloader import Instaloader, Profile

MY_PROFILE = "..."
OTHER_PROFILE = "..."

L = Instaloader()
L.load_session_from_file(MY_PROFILE)

my_followers = set(Profile.from_username(L.context, MY_PROFILE).get_followers())
other_followers = set(Profile.from_username(L.context, OTHER_PROFILE).get_followers())

mutual_followers = my_followers & other_followers

for follower in mutual_followers:
    print(follower)
```

**Comment by Deleora** [comment]
For this to work I need to have access to all the followers of the target profile. What if I am not following the target profile which is private? Is it possible then?

**Comment by aandergr** [comment]
That is stored in the profile JSON.

```
$ cat profile/profile_*.json | jq .node.edge_mutual_followed_by
```

**Comment by Deleora** [comment]
> "edge_mutual_followed_by": {
>             "count": 52,
>             "edges": [
>                 {
>                     "node": {
>                         "username": "..."
>                     }
>                 },
>                 {
>                     "node": {
>                         "username": "..."
>                     }
>                 },
>                 {
>                     "node": {
>                         "username": "..."
>                     }
>                 }
>             ]
>         }


This is the JSON file I got, in this the count says 52 but only 3 profiles are displayed. What is expect to get is all 52 profiles.
Any idea?

**Comment by aandergr** [comment]
It is unlikely that we can get all mutual followers in this case. This is a privacy feature since it is a private profile that you do not follow.

**Comment by Deleora** [comment]
Alright. No worries. I'll go with your method. Thanks for helping  👍👍
