### ISSUE TITLE
Download post shared on story

### ISSUE THREAD

**Issue by Deleora** [instaloader/instaloader#647]
From what I know Instaloader does not downloads the post shared in the story, it just downloads story as an image or video without the link to the actual post shared. So is there a way to download the post shared on the story as well?

Also I checked in the story JSON file (downloadable along with story)and it also contains no link to the post shared.

**Comment by aandergr** [comment]
Thanks for your observation. Instaloader does not yet use the JSON Query that returns this information (`GraphTappableFeedMedia`), neither does it somehow generally evaluate the `tappable_objects` of a story yet.

**Comment by Deleora** [comment]
No problem. Looking forward to this feature sir!!

**Comment by Deleora** [comment]
So now is it possible to download the actuals posts shared in stories?

**Comment by aandergr** [comment]
> So now is it possible to download the actuals posts shared in stories?

Yes, there is a field `tappable_objects` in the JSON that is now returned for each StoryItem. So with the JSON saved, something like the following will give you an `id` and a `shortcode` of a post shared in a story:

```sh
$ xzcat 2021-01-30_05-57-43_UTC.json.xz | jq .node.tappable_objects[0].media
```

or download it:

```sh
$ instaloader -- -`xzcat 2021-01-30_05-57-43_UTC.json.xz | jq -r .node.tappable_objects[0].media.shortcode`
```

However, the tappable objects are not yet exposed in the programmatic interface of StoryItem.

_Originally posted by @aandergr in https://github.com/instaloader/instaloader/issues/872#issuecomment-770195401_
