### ISSUE TITLE
instaloader redownloads posts after user name change

### ISSUE THREAD

**Issue by jenlunds** [instaloader/instaloader#648]
**Describe the bug**
Posts are redownloaded after the user changes their instagram user name. This happened to me the second time I ran my download script. The first time i ran instaloader after the user changed it's name it renamed the folder as it should. But on second time it redownloaded all the posts with the new user name add to file name.

**To Reproduce**
instaloader --igtv --dirname-pattern=Instaloader/{profile} --filename-pattern={date_utc:%Y}/{date_utc:%Y%m%d_%H%M%S}-{profile}-{shortcode} -F

**Expected behavior**
Either rename files to the new username or leave them be but don't redownload every single thing.

**Instaloader version**
instaloader --version 4.4.2

**Comment by aandergr** [comment]
> **Expected behavior**
> Either rename files to the new username or leave them be but don't redownload every single thing.

When Instaloader detects a user name change, only the directory is renamed. Instaloader does not rename any files.
