### ISSUE TITLE
How to sort igtv, stories and posts into their own folders?

### ISSUE THREAD

**Issue by jenlunds** [instaloader/instaloader#649]
Is there a way to sort igtv, stories, photos and videos into their own folders? It's hard to know what is what currently. Can it be done with --dirname-pattern?

**Comment by Thammus** [comment]
The Instaloader CLI does not have the flexibility to distinguish between those with its path patterns. However, this is a typical use case for [Instaloader as a module](https://instaloader.github.io/as-module.html).
