### ISSUE TITLE
Return email for a Profile

### ISSUE THREAD

**Issue by nsuaifan** [instaloader/instaloader#651]
I would LOVE if you could return the email associated with a Profile, if the user has uploaded a public email to their account.

Emails are available on IG profiles through this button:
![Screenshot 2020-06-01 at 2 59 39 PM](https://user-images.githubusercontent.com/5383745/83443984-ab664c80-a418-11ea-863c-9f60a0bacb16.jpg)

Btw, thanks for this Python library, it is amazing and so useful!

**Comment by e5150** [comment]
You need to be logged in, but it is available. Through module:
```
il = Instaloader()
...
p = Profile.from_username(il.context, 'amberfillerup')
p._iphone_struct.get('public_email')
```
And in metadata stored by the CLI:
`xzcat amberfillerup_*.json.xz | jq -r .node.iphone_struct.public_email`

**Comment by nsuaifan** [comment]
Wow, thank you!! This is awesome.
