### ISSUE TITLE
Instaloader on AWS

### ISSUE THREAD

**Issue by Nodeak** [instaloader/instaloader#652]
Have there been any known issues regarding using Instaloader on an AWS EC2 instance?
When using both the Python Module and CLI Instaloader on an EC2 Ubuntu 18.04 LTS the 429 error is received after just 1 request:

```
HTTP redirect from https://www.instagram.com/[profile]/ to https://www.instagram.com/accounts/login/?next=/[profile]/
JSON Query to [profile]/: 429 Too Many Requests: redirected to login [retrying; skip with ^C]
HTTP error code 429 was returned because too many queries occurred in
the last time. Please do not use Instagram in your browser or run
multiple instances of Instaloader in parallel.
The request will be retried in 666 seconds, at 23:28.
GraphQL requests:
  other
    last 10 minutes: 1 requests
    last 11 minutes: 1 requests
    last 15 minutes: 1 requests
    last 20 minutes: 1 requests
    last 30 minutes: 1 requests
    last 60 minutes: 1 requests
[profile]: JSON Query to [profile]/: 429 Too Many Requests: redirected to login

Errors occurred:
[profile]: JSON Query to [profile]/: 429 Too Many Requests: redirected to login
```

However, when the same command or script is executed on a local machine, it works as intended, on Ubuntu, Windows, and MacOS. I've read the Docs regarding the 429 - Too Many Requests section however I am just a bit stumped regarding this situation.

I've also tried this on a DigitalOcean Droplet with Ubuntu but ended up with the same result as AWS.

Thanks in advance.

**Comment by kzCassie** [comment]
I am encountering exactly the same issue here. I used EC2 for crawling a few months ago. Back then, the scraping on EC2 works fine. But when I tried the same thing this morning, I keep getting 429.

**Comment by pgurazada** [comment]
We are facing the same issue when querying through Google Colab. 429 is triggered multiple times and the data collection is very slow.

**Comment by rasiksuh** [comment]
We are facing exactly same issue across all cloud-servers (AWS & Azure). When running in a local machines, seems to be working fine. Looking for an alternative.

**Comment by datanizing** [comment]
Probably related to #654 

I cannot even wget a profile or a post from these servers. I have tried many server providers, all seem to be blocked. Maybe they just whitelisted access provider IPs?

**Comment by jkadry** [comment]
Same issue on my ec2 instance

**Comment by youthzech** [comment]
There seems to be a separate IP restriction policy.
It also happens on company public IP.
I have one more company public IP and I changed it and it works fine again. Blocked IP is still not working.

**Comment by Nodeak** [comment]
Hey guys, so I've spent the past couple of days attempting to find a work around for this. I'll explain further down how I came to the conclusion for anyone that is curious.

What I've concluded is that if you are using a cloud hosting service or even a VPN you will need to provide login credentials when using Instaloader.

So what I might do is use a throwaway Instagram account I have from a while back and test it to see if it gets flagged and/or blocked. I'll update y'all if this happens.

***

The reasoning I found is that when attempting to connect to Instagram from an IP that is known to be related to a VPN or cloud-hosting service, Instagram redirects you to a log-in page, as the now-obvious error: 
`HTTP redirect from https://www.instagram.com/[profile]/ to https://www.instagram.com/accounts/login/?next=/[profile]/`
states for us lol.

I attempted to re-engineer the library to utilize this [requests wrapper](https://github.com/erdiaker/torrequest) which allows you to use the Tor network when using the requests library, I think I got close but couldn't figure it out so I switched over to attempting to use a VPN.

I used ExpressVPN and manually installed it on my AWS instance using OpenVPN but at the end of the day I believe Instagram has flagged any traffic from these Cloud and VPN services and force them to log in before accessing any account on Instagram.com (probably to be able to analyze unknown traffic).
This was confirmed with a simple test, locally on my machine I browsed to instagram.com/github:
- VPN Off, No login: I can view GitHub's Instagram Page
- VPN On, No Login: I am redirected to a login page
- VPN On, Login: I can view GitHub's Instagram Page

Hope this helps anyone!

**Comment by cloudrac3r** [comment]
> I attempted to re-engineer the library to utilize this requests wrapper which allows you to use the Tor network when using the requests library, I think I got close but couldn't figure it out so I switched over to attempting to use a VPN.

Like VPNs, Tor is also blocked from looking at profile pages. This may be a deliberate block at Tor IPs specifically, or it may the generic IP rate limit rules and there are just too many people trying to use Instagram on the Tor network.

**Comment by datanizing** [comment]
For me it appears to be working again. Instagram has maybe changed the rules.

**Comment by cloudrac3r** [comment]
My server from Vultr is still blocked even though it has not made any requests this month. @datanizing what provider are you using?

**Comment by datanizing** [comment]
@cloudrac3r I am using Hetzner, a German cloud provider (highly recommended if you need physical hardware BTW). OVH also works for me.

A freshly started AWS server is however still blocked.

So it looks like they have relaxed the rules.

**Comment by cloudrac3r** [comment]
My OVH in Singapore is blocked without making any requests. What region was yours in?
