### ISSUE TITLE
Download Meta Data Without JPG/MP4

### ISSUE THREAD

**Issue by barrywilson9** [instaloader/instaloader#655]
Your question here...
How do I download just the meta-data about posts without having to save a copy of the JPG or MP4 files?

I am using args.txt as follows:

```
--login=my_username
--password=my_password
--fast-update
--post-metadata-txt="{likes} likes."
--post-filter="date_utc >= datetime(2020, 2, 1)"
target
```

Thank-you

**Comment by aandergr** [comment]
See our documentation: [What to Download of each Post](https://instaloader.github.io/cli-options.html#what-to-download-of-each-profile)
