### ISSUE TITLE
Question about total followers count and hashtag volume.

### ISSUE THREAD

**Issue by jpramirez87** [instaloader/instaloader#656]
Hello! Just a couple of questions about Instaloader. I'm using "tokens" to sort the information I download from Instagram ({profile} {likes} {shortcode}). Is there an specific token for the number of followers in a profile? For example:

`    dirname_pattern="{***FOLLOWERCOUNT-HERE***}_{profile}/{likes}_{shortcode}"`

I know I can use `followers = profile.get_followers()` but I have no idea how to "print" the number obtained into `dirname_pattern`.

Second question: I have a list of approximately 700 hashtags. I need to obtain the total number of publications for each one, in other words, its **volume**. I found the hashtag property "mediacount", but I don't know how to apply it. It would be a simple procedure, analyze each hashtag and store in a TXT its name and volume separated by a comma, so I can import them into Excel. Can this be achieved with Instaloader? If not, what other tool could I use?

Something like this:

    travel,495131269
    
    traveling,73940293
    
    worldtraveler,6720999

I would very much appreciate any help or example. Thanks!

**Comment by Deleora** [comment]
About the issue with showing followers count in filename you can refer to [this](https://github.com/instaloader/instaloader/issues/581#issuecomment-629452813)
It basically downloads all the 'followers' & 'following' of the target profile and saves them separately into csv file. 
Let me know if this gets the job done.
