### ISSUE TITLE
Fetch only the users who has stories based one request

### ISSUE THREAD

**Issue by MrJmpl3** [instaloader/instaloader#657]
**Provide us a use case of the feature**
Show and fetch only the users who has stories in one request

**Describe the solution you'd like**
Instagram has the url , that return a graphql response in list of the users who has stories actives.

`https://www.instagram.com/graphql/query/?query_hash=b7b84d884400bc5aa7cfe12ae843a091&variables={"only_stories"%3Atrue%2C"stories_prefetch"%3Afalse%2C"stories_video_dash_manifest"%3Afalse}`

**Describe alternatives you've considered**
Nothing

**If the feature request is accepted, would you be willing to submit a PR?**

I don't know Python sorry.

**Additional context**

(please also see https://instaloader.github.io/contributing.html for how to suggest a feature)

**Comment by aandergr** [comment]
`Instaloader.get_stories()` returns the visible stories. The `Story` objects returned by `get_stories()` have an `owner_profile` property. So you could just iterate through `get_stories()` to fetch the users who have stories.
