### ISSUE TITLE
"Over 18" profiles problem?

### ISSUE THREAD

**Issue by m4gnet98** [instaloader/instaloader#658]
So I just stumbled upon some profiles I can't seem to access on neither Instagram or with Instaloader. For example the profile for Carlsberg (probably the best bear in the world), which btw happens to be 25+, not only 18. https://www.instagram.com/carlsberg/

Instaloader seems unable to even see the profile, and returns

```
JSON Query to carlsberg/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to carlsberg/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
carlsberg: Profile carlsberg does not exist.
The most similar profiles are: ___.carlsberg.___, carlsbergsport, carlsberg_jp, carlsberg.az, carlsberg.mongolia.
```

I also seem to be unable to set my age on Instagram, but that's none of your problems. 

Ideas, thought? 
Thanks!

**Comment by m4gnet98** [comment]
Doesn't work when I'm logged in either, but as I said that's probably because I'm not aged on Instagram.
So I guess Instagram hides the profiles from the API unless you're logged in and above required age?
```
instaloader --login=*** --password=*** --no-metadata-json --no-captions --stories --highlights carlsberg
Loaded session from c:\users\***\appdata\local\temp/.instaloader-***/session-***.
Logged in as ***.
JSON Query to carlsberg/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to carlsberg/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Profile carlsberg does not exist.
The most similar profiles are: ___.carlsberg.___, carlsbergsport, carlsberg.az, carlsbergbyen, visitcarlsberg.
Trying again anonymously, helps in case you are just blocked.
JSON Query to carlsberg/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to carlsberg/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Profile carlsberg does not exist.
The most similar profiles are: ___.carlsberg.___, carlsberg.az, carlsberg_jp, carlsbergsport, visitcarlsberg.
Saved session to c:\users\***\appdata\local\temp/.instaloader-***/session-***.

Errors occurred:
Profile carlsberg does not exist.
The most similar profiles are: ___.carlsberg.___, carlsberg.az, carlsberg_jp, carlsbergsport, visitcarlsberg.
```

**Comment by 9dc** [comment]
Currently the only option is to login to you IG App and accept, that you want to see the content..
After that its possible to download that content.

**Comment by m4gnet98** [comment]
> Currently the only option is to login to you IG App and accept, that you want to see the content..
> After that its possible to download that content.

That actually worked, thanks!
Nothing indicating that using the browser, that's stupid.
