### ISSUE TITLE
Proper way to retrieve historical hashtag data

### ISSUE THREAD

**Issue by e2tovar** [instaloader/instaloader#666]
Hi, i want to reopen this issue. I have tried different ways to retrieve posts chronologically from a hashtag and i could not do it. The problem is that posts are not fully sorted based on publish date
While iterating over L.get_hashtag_posts(hashtag) some posts have totally different post date:

'2020-06-06 13:16:09
2020-06-06 13:14:33
2020-06-06 13:14:18
2020-06-06 13:13:34
2020-06-06 13:13:03
2020-06-06 13:07:40
2020-06-06 13:07:05
2020-06-06 13:06:41
2020-06-06 13:04:49
2020-06-06 13:04:43
2020-06-06 13:03:18
2020-06-06 13:01:04
2020-06-06 13:00:11
2020-06-04 12:18:24--->??
2020-05-31 17:41:29--->??
2020-05-23 18:09:34--->??
2020-06-06 13:00:02
2020-06-06 12:59:52
2020-06-06 12:59:33
2020-06-06 12:59:15
2020-06-06 12:56:32'

As a result, [this](https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period) example is not working.

My question is: Is there another way to issue this problem?

**Comment by aandergr** [comment]
Also discussed in #681.

> The code example with dropwhile and takewhile makes the assumption that the post iterator returns posts in exact chronological order. This seems no longer true for hashtag posts. It might be helpful to analyze the degree and kind of deviation from chronological order. If e.g. only up to k older posts are inserted into an otherwise chronological order (as your comment suggests with k=3), we could break the loop when encountering the (k+1):th too-old post rather than the first one.

**Comment by e2tovar** [comment]
> Also discussed in #681.
> 
> > The code example with dropwhile and takewhile makes the assumption that the post iterator returns posts in exact chronological order. This seems no longer true for hashtag posts. It might be helpful to analyze the degree and kind of deviation from chronological order. If e.g. only up to k older posts are inserted into an otherwise chronological order (as your comment suggests with k=3), we could break the loop when encountering the (k+1):th too-old post rather than the first one.

Thanks, I solved it. After some samples i got the k factor. These missing posts come in group of no more than 30. So to be sure, i think it's safe to use a deviation of k=50.   I have rewritten a functional code and i'm happy to share it. 

```
from datetime import datetime
import instaloader

L = instaloader.Instaloader()

posts = instaloader.Hashtag.from_name(L.context, 'urbanphotography').get_posts()

SINCE = datetime(2020,5,10) #further from today, inclusive 
UNTIL = datetime(2020,5,11) #closer to today, not inclusive

k = 0 #initiate k
k_list = [] #uncomment this to tune k

for post in posts:
    postdate = post.date

    if postdate > UNTIL:
        continue
    elif postdate <= SINCE:
        k+=1
        if k == 50:
            break
        else:
            continue            
    else:
        L.download_post(post, '#urbanphotography')              
        k = 0 #set k to 0
        #if you want to tune k, uncomment below to get your k max
        #k_list.append(k)
#max(k_list)
```

**Comment by aandergr** [comment]
Looks nice – may we enhance our documentation with your code snippet?

**Comment by e2tovar** [comment]
> Looks nice – may we enhance our documentation with your code snippet?

Yes of course

**Comment by Lerring** [comment]
Hi sorry for posting it here, I'm having trouble using this block of code with the error `Too many queries in the last time. Need to wait 418 seconds, until 23:44.`

I'm trying to sample the BLM hashtag for a research project. 

`hits = 0
postsByDateRange=[]
for post in hashtags.get_posts():
    postdate=post.date_utc
    if postdate > UNTIL:
        continue
    elif postdate <= SINCE:
        hits +=1
        if hits == 50:
            break
        else:
            continue
    else:
        postsByDateRange.append(post)
`

**Comment by DanSchmitt** [comment]
WIth this script I get a "429 - Too Many Requests" error. Anyone getting the same and knows why?

I tried multiple different accounts and all work for other instaloader purposes, just not this one.

**Comment by e2tovar** [comment]
> WIth this script I get a "429 - Too Many Requests" error. Anyone getting the same and knows why?
> 
> I tried multiple different accounts and all work for other instaloader purposes, just not this one.

Hi, it's normal, as we are doing too many request. You need to wait and be patient, it will re-start the search in few minutes.

**Comment by meberhar-a11y** [comment]
Trying to reproduce this, when I get to last 'else:' returns SyntaxError: invalid syntax. Any help on this? I am brand new.
