### ISSUE TITLE
Comments formatting

### ISSUE THREAD

**Issue by anseml** [instaloader/instaloader#67]
Would it be possible to get the comment file formatted a little nicer. Such as the username time stamp and comment on one line? Instead of including the profile id, multiple lines, and profile picture links.

As well is it possible to just have one file created for each image that would include any vairables passed such as comments, getotags etc? That way one neatly formatted txt file would include the caption and if selected the comments/geotags?

Is there a way to download who is taagged in a picture or who liked the image?

**Comment by aandergr** [comment]
With some effort, this would all be possible. However: **Which problem would it solve? How would the newly formatted data be further processed?**

The `instaloader.Post` class cleanly exposes this information, perhaps it would be most appropriate to write a separate "Post formatter".

----

Regarding your last questions:

> Is there a way to download who is taagged in a picture

Yes. There is `Post.tagged_users`, see https://instaloader.readthedocs.io/as-module.html#post-class.

> or who liked the image?

Not yet, only the pure number of likes, `Post.likes`. Refer to issue #70.

**Comment by anseml** [comment]
I was thinking it would be more convenient contained in one file for the sake of organization. As for having the comment data cleaned up I thought it would be helpful for readability and then possibly other processing.

**Comment by nathalipaz** [comment]
it is possible to have comments using an id?

**Comment by aandergr** [comment]
For [version 4](https://github.com/instaloader/instaloader/projects/1) we plan to make it easier for the user to customize how Instaloader exports Post metadata such as comments.

> it is possible to have comments using an id?

I am not sure what you mean. It is possible to access the comments of a Post if you have its shortcode with [`instaloader.Post.get_comments()`](https://instaloader.github.io/as-module.html#instaloader.Post.get_comments), i.e.
```python
from instaloader import Instaloader, Post
L = Instaloader()
P = Post.from_shortcode(L, "SHORTCODE")
for comment in P.get_comments():
    ...
```

**Comment by aandergr** [comment]
We no longer see a priority in implementing comments formatting, and the inactivity of the issue implies 
that it not that relevant.

There are two ways to access the comments:
- Post.get_comments()
- `--comments` and read the JSON that is generated (and updated in the next runs)

They can then be read by a separate script and formatted the way you want.

**Comment by LuminairPrime** [comment]
For me this is the only feature missing from Instaloader! Each picture should be accompanied by one human-readable text file with the same text as on the website. Right now the output is very esoteric and not convenient enough for me to use.

Example of how it could look for picture1.jpg:

picture1.txt:

May 10, 2022
Caption: Hi there!
100 likes
2 comments

George (May 10, 2022, 1 likes): I like your picture!

Jeff (May 11, 2022, 0 likes): Yeah great pic!
