### ISSUE TITLE
Dockerized Flask API Running into: Login Error ? CLI also not working 

### ISSUE THREAD

**Issue by iDustbin** [instaloader/instaloader#672]
Your question here...
`except json.decoder.JSONDecodeError:
            raise ConnectionException("Login error: JSON decode fail, {} - {}.".format(login.status_code, login.reason))
        if resp_json.get('two_factor_required'):
            two_factor_session = copy_session(session)
            two_factor_session.headers.update({'X-CSRFToken': csrf_token})
            two_factor_session.cookies.update({'csrftoken': csrf_token})
            self.two_factor_auth_pending = (two_factor_session,
instaloader.exceptions.ConnectionException: Login error: JSON decode fail, 400 - Bad Request.`

is https://www.instagram.com/accounts/login/ajax/ is not working on my site ? any idea ? login is not working also from CLI tool... 

login error :/ any idea ? i enabled & disabled MFA Auth but its not working ? 

My Dockerfile 

`FROM python:3.5-alpine
MAINTAINER iDustBin "info@idustbin.de"

RUN apk add build-base jpeg-dev zlib-dev
ENV LIBRARY_PATH=/lib:/usr/lib

COPY . /app
WORKDIR /app

RUN pip3 install -r requirements.txt
EXPOSE 5000/tcp

CMD python /app/app.py`

Best Regards and thanks in advance

**Comment by iDustbin** [comment]
'  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/app.py", line 220, in instagram_update
    L.login(USER, PASSWORD)
  File "/usr/local/lib/python3.5/site-packages/instaloader/instaloader.py", line 460, in login
    self.context.login(user, passwd)
  File "/usr/local/lib/python3.5/site-packages/instaloader/instaloadercontext.py", line 242, in login
    resp_json['message']))
instaloader.exceptions.ConnectionException: Login error: "fail" status, message "Please wait a few minutes before you try again.".

-->'

is instaloader dead ?

**Comment by susodapop** [comment]
Do you have two factor authentication enabled for your Instagram account? It looks like your API is not properly passing in the OTP code.

**Comment by iDustbin** [comment]
hi, mfa is disabled... this instagram login, does you have this session.load integration ? i think its enough to login 1x times a day and see how long the session is valid... 
any idea ? i know instaloader supports load.session() but have no clue to solve my issue...
