### ISSUE TITLE
Download stories within an interval without logging in everytime

### ISSUE THREAD

**Issue by luizamazo** [instaloader/instaloader#673]
So I'm building a javascript bot that automatizes posting stuff from IG and I'm using a child process to use the download stories feature from Instaloader. The thing is, I need to call the main function every 20 seconds, so this function will open a child process and it will check if it has new stories etc. 
 
```
setIntervalAsync(
    async () => {
        await callMaster()
    }, 20000)

```
The problem is that after the second call or so, it starts to give this error:

```
stderr: Traceback (most recent call last):
  File "instaloader/download-stories.py", line 17, in <module>    ig.login(USER, PASSWORD)
  File "C:\Users\luiza\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader\instaloader.py", line 460, in login
    self.context.login(user, passwd)
  File "C:\Users\luiza\AppData\Local\Programs\Python\Python38\lib\site-packages\instaloader\instaloadercontext.py", line 241, in login
    raise ConnectionException("Login error: \"{}\" status, message \"{}\".".format(resp_json['status'],
instaloader.exceptions.ConnectionException: Login error: "fail" status, message "Please wait a few minutes before you try again.".
```

I was sure it was going to be a problem to be logging in every 20 seconds, but when I tried to login only once before starting the setInterval thing, when I open the child process to download stories, it doesn't recognize I'm logged in and then it asks me to give a username.

What can I do? I'm very new to this lib and I'm using it as a module, so I'm pretty confused how the logging in part works, how to create a session, if the problem is that after my login child process ends the login session ends along with it so thats why it doesnt recognize I'm logged in later on...

I really need some help. Thanks in advance.

**Comment by aandergr** [comment]
I do not understand how you invoke Instaloader (from within Node.js?). To avoid having to login each time, it may be handy to use a sessionfile, see [Instaloader.save_session_to_file()](https://instaloader.github.io/as-module.html#instaloader.Instaloader.save_session_to_file) and [Instaloader.load_session_from_file()](https://instaloader.github.io/as-module.html#instaloader.Instaloader.load_session_from_file) if you're invoking Instaloader from within Python, or the [--sessionfile](https://instaloader.github.io/cli-options.html#cmdoption-sessionfile) option if you're invoking the Instaloader CLI as a process..

**Comment by susodapop** [comment]
> I do not understand how you invoke Instaloader (from within Node.js?).

Ditto. It would be helpful to understand how you're calling `instaloader` from Javascript.

**Comment by luizamazo** [comment]
Oh, thanks for the replies! 

I'm building a bot that is going to scrape an instagram user to automatize posts somewhere else. I was using npm libs but the one that made requests to get IG Stories stopped working, I guess it was because IG changed their api, so I started to search for alternatives and I saw that instaloader is pretty complete. To invoke instaloader (and tweepy, also python lib that I'm working with) I use node's childprocess. So this is what I'm doing:
```

let master = async () => {
   await childProcessLogin()
   setIntervalAsync(
    async () => {
        await callMaster()
    }, 20000)
}
```

callMaster consists of a function that call the libs that are going to scrape posts and stories. I'm scraping posts through a npm lib I modified, but now I'm calling stories with Instaloader. 

```
 let callMaster = async () => {
    let igPost = await instagramPost.getInstagramPosts()
    igPost = igPost[0]   
    
    if(igPost.duplicate == false){
        await childProcessTweepyInstagramPosts(igPost)
    } 

    let teste = {},
    stories = [],
    obj = await childProcessInstaloaderStories()

    if(obj == 0){
        console.log('No new stories')
    }else{
        let json = JSON.parse("[" + obj + "]")
        stories = json[0].reverse()
        teste = await instagramStory.formatInstagramStories(stories)
        for(value of teste){ 
            if(value[0]){
                if(value[0].duplicate == false){ 
                    await childProcessTweepyInstagramStories(value[0]).then(res => console.log(res))
                }     
            } 
        } 
    }
```
I invoke Instaloader like this 

```
const { spawn } = require('child_process')
const child = spawn('python', ['instaloader/download-stories.py'])

```
So in the end, I'm "watching" for new stories/posts every 20 seconds, because of IG's rate limit. However, since to make requests to IG Stories api I need to be logged in, its problematic like @aandergr said. What I thought of doing was: Open a child process to login with Instaloader when my bot starts and then only after that, when the child process is closed, I would call the interval function from javascript, to do requests after I'm logged in. But I guess when my child process ends, instaloader instance or session also ends, so when the interval function starts it gives me the "you're not logged in".  So for what I understand, I should try saving the session to a file? How long would that session work until I would need to do it again?

I think now I could login, save it to a file and then when I start the interval and I open instaloader child process to get stories I would just load from the session file, is that correct? Sorry for so many questions, I'm pretty new to instaloader and python as well

**Comment by aandergr** [comment]
> So for what I understand, I should try saving the session to a file?

Exactly. You can run `instaloader --login=USERNAME --sessionfile=FILE`, then Instaloader asks for your password, logs in to Instagram and saves a file `FILE`. This file contains the set of session cookies. In your `download_stories.py` you can then start with `instaloader.load_session_from_file("USERNAME", "FILE")` and Instaloader  loads the session cookies instead of logging in again, providing you a logged-in Instaloader instance without having to use the strongly rate-limited login endpoint.

> How long would that session work until I would need to do it again?

Session files have proven to be very reliable, I have never seen a session file expire. You can do the login once, keep the session file, and never have to login again (similarly as you don't have to login each time you visit a web page, thanks to the browser saving the session cookies).

What I said in my earlier comment, however, was that while this approach will work at first, there are other rate limits we have to be aware of. Instagram will only allow to request the story endpoint 20 times within 11 minutes, so after a while we will run into a "429 Too Many Requests" HTTP response if we query for new stories each 20 seconds, so we have to change the interval to at least 35 seconds – if you still want to try it with 20 seconds, and it works for more than 7 minutes, please tell us ;)

**Comment by luizamazo** [comment]
Thanks for your help, as of now, it works pretty well! Also, I tested and requesting every 20 seconds works fine, up until now no errors! It used to throw 429 at 10 secs but 20 secs seems to work fine. Thank you, I'm really happy for your help and this great lib!

**Comment by aandergr** [comment]
Nice, I am glad I could help! Thanks for sharing your observation regarding the query rates. I myself started some tests, which suggest that the rate limits may have become less strict for logged-in users.

I am closing this issue now, since it seems resolved :)

**Comment by Deleora** [comment]
@luizamazo If you don't mind, I would like to see the full working code for this operation. Even I want to automate story downloading and you seem to have accomplished it without any problems. So if it's possible plz tag the code.
Thanks!!!
