### ISSUE TITLE
Is it possiple to use args.txt to download list of single post?

### ISSUE THREAD

**Issue by renox92** [instaloader/instaloader#675]
I can download posts using `instaloader -- -shortcode1 -- -shortcode2`, but using the same syntax with args.txt give me `JSON Query to p/- -shortcode/: 404 Not Found` error. Reducing `-- -shortcode` to just `-shortcode` (i.e removing what seemed like extra bits in the error message) doesn't work either.

**Comment by e5150** [comment]
The `--` tells the argument parser that there are no more option arguments, therefore all following arguments are treated as targets. So `-- -SC1 -- -SC2` gets treated as shortcodes `SC1`, `-` and `SC2`.
 `instaloader -- -shortcode1 -shortcode2`  should work. In an argument file each shortcode, with its preceding dash, should be placed on a separate line, i.e:
```
--
-shortcode1
-shortcode2
```

**Comment by renox92** [comment]
This does indeed work. Thank you.
