### ISSUE TITLE
New photos downloadafter moving files to new catalog

### ISSUE THREAD

**Issue by arlido** [instaloader/instaloader#677]
Your question here...
Hi. I have question about somethig. I want to create schedule backup of profile and I do it by download photos to my local folder. Then I moved these catalog to external hard drive. When I want to --fast-update Instaloader download all files (exactly at first time) to my local folder. Otherwise when I delete photo from my local folder (even one) and do fast update Instaloade4 download missing things. Is it possible to download only new photos from last "date of use" instaloader and not to download all files when I moved oldest to external HDD? I think You know what I mean. Thanks for reply and have a nice day.

**Comment by susodapop** [comment]
The way I did this in the past was to copy the images to my server or external HD. Then use a script to replace the files on my local disk with zero-length files of the same name/type/extension. The replacement files take almost no hard disk space and they "trick" `instaloader` into not re-downloading the files.

In my experience it is difficult to implement a `download_posts_after()` method without emitting a bunch of unnecessary API requests.

**Comment by ungenio** [comment]
Keep the last downloaded file in your local folder, Instaloader will stop when it detects this file.

**Comment by psonnosp** [comment]
> 
> 
> The way I did this in the past was to copy the images to my server or external HD. Then use a script to replace the files on my local disk with zero-length files of the same name/type/extension. The replacement files take almost no hard disk space and they "trick" `instaloader` into not re-downloading the files.
> 
> Alternatively you can use [this behavior](https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period) from the documentation to only pull posts from the time-period you specify.
> 
> [Edited to remove my speculation about downloading posts within a period]

Would you mind sharing this script if it's something that's possible to do in Windows?

Or has anyone come up with another solution to this?

**Comment by ungenio** [comment]
> Would you mind sharing this script if it's something that's possible to do in Windows?
> 
> Or has anyone come up with another solution to this?

I found this command on PowerShell. I tested it and it works well.

`dir | New-Item -Force -Value ""`

https://www.tenforums.com/general-support/110727-how-zero-size-all-files-folder-post1377664.html#post1377664
