### ISSUE TITLE
@profile Could not find "window._sharedData" in html response

### ISSUE THREAD

**Issue by valdearg** [instaloader/instaloader#678]
**Describe the bug**
When running with @profile it gives the error:

`Retrieving followees of profile...`
`JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]`
`JSON Query to profile/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]`
`@profile: Profile profile does not exist.`
`The most similar profiles are: profile._pictures._, profile._girls, nailfilepro, leftprofile, highprofilenola.`

**To Reproduce**
`instaloader @profile --login {my user}`

**Expected behaviour**
Download all followed by my user and download everything by them.

**Instaloader version**
`instaloader --version` output.
4.4.4rc3

**Comment by haresh14** [comment]
I'm facing the same issue

**Comment by Thammus** [comment]
As the output of Instaloader tells you, the target `@profile` instructs Instaloader to download the followees of the actual profile named "profile". You have to substitute "profile" by the actual name of the target profile. Instaloader also tells you that the profile named "profile" does not exist. There is no bug or issue here.

**Comment by haresh14** [comment]
Great Thanks @Thammus It works like a charm :)
`I had to do instaloader @{myusername} --login {my user}`
