### ISSUE TITLE
Bump in the word HTTP error code 429

### ISSUE THREAD

**Issue by iOSGenesis** [instaloader/instaloader#679]
Im a noob. Can explain to me whats going on and how I can fix this. I would greatly appreciate. Thank you.
"HTTP error code 429 was returned because too many queries occurred in
the last time. Please do not use Instagram in your browser or run
multiple instances of Instaloader in parallel."

**Comment by aandergr** [comment]
Most probably answered here: [Troubleshooting – 429 Too Many Requests](https://instaloader.github.io/troubleshooting.html#too-many-requests).

**Comment by valdearg** [comment]
I swear I started receiving this error immediately after upgrading to the latest instaloader. Happens constantly now.

Not logged in via browser, I have the app logged in but not running.

**Comment by iOSGenesis** [comment]
I figured it out. Are you using a vpn? I turned mine off and it worked.

**Comment by valdearg** [comment]
It's running on one of my servers, so kinda.
