### ISSUE TITLE
Can't Get All Comments from Post

### ISSUE THREAD

**Issue by luthfirrahmanb** [instaloader/instaloader#680]
Hi, I've got a little problem here, when I try to get all comments, it seems I just got a half of total comments on the post when I loop data from `.get_comments()`. Is it my code problem? or have you any idea why this can be happen?(Image below)
![Annotation 2020-06-09 185251](https://user-images.githubusercontent.com/18209502/84144551-9f1a6900-aa82-11ea-894a-db89ae881eb7.jpg)

**Comment by shepurev** [comment]
There is a hypothesis why ` .get_comments()` method does not load all comments. I made it by looking at such cases manually.

It returns only the basic _(directly below the publication)_ comments. Comments written in response to basic ones are not included. Check it out

**Comment by luthfirrahmanb** [comment]
> There is a hypothesis why ` .get_comments()` method does not load all comments. I made it by looking at such cases manually.
> 
> It returns only the basic _(directly below the publication)_ comments. Comments written in response to basic ones are not included. Check it out
> 
> Duplicate of #460, #590

Hi @shepurev Thanks for your answer

**Comment by Thammus** [comment]
In your given example [`get_comments()`](https://instaloader.github.io/as-module.html#instaloader.Post.get_comments) does in fact load all comments. Comments written in response to basic ones are included and can be accessed through the `answers` field which is nested inside each comment.

```python
import instaloader
L = instaloader.Instaloader()

post = instaloader.Post.from_shortcode(L.context, 'CBAQLopB6d3')

comments_from_loop_including_answers = []

for comment in post.get_comments():
    comments_from_loop_including_answers.append(comment)
    for answer in comment.answers:
        comments_from_loop_including_answers.append(answer)

print(len(comments_from_loop_including_answers))    # output: 8
print(post.comments)                                # output: 8
```

**Comment by Vivek-doc** [comment]
Hi,
Does this work?
I tried the above code but I get the following error message:

> QueryReturnedBadRequestException: 400 Bad Request - "fail" status, message "feedback_required" when accessing https://www.instagram.com/graphql/query?query_hash=2b0673e0dc4580674a88d426fe00ea90&variables=%7B%22shortcode%22%3A%22vivek.sundriyal%22%7D

I wonder if anyone has tried this function recently?

Thanks,
