### ISSUE TITLE
How to embed Instaloader and Python into UI project?

### ISSUE THREAD

**Issue by manishdashsharma** [instaloader/instaloader#684]
Or if you are a developer you can code it yourself, it shouldn't be hard. Even I've been thinking of doing this myself but I'm caught up with other things as well. If I ever start, I'll let the community know. Peace

_Originally posted by @Deleora in https://github.com/instaloader/instaloader/issues/639#issuecomment-636262417_

**Comment by manishdashsharma** [comment]
I have created a UI but the problem is i need this ui to work even if there is no python in the system . I have created an exe file but python is required to run it cause its uses the instaloader module which required python

**Comment by Deleora** [comment]
Instaloader is written in Python so obviously Python needs to be installed in system for it to work. 
Or if it's possible to change the whole source code to some other language, you may try that. (I'm not sure about this) 

Btw i was wondering, this UI is for personal use or you gonna share with some other ppl as well?

**Comment by susodapop** [comment]
The user won't need to install Python if you bundle an interpreter in your `.exe`. This is how tools like `PyInstaller` and `py2exe` work. But if you wrote your UI in another language then you probably should use an Instagram API client from that language instead of embedding this Python version.

**Comment by manishdashsharma** [comment]
> The user won't need to install Python if you bundle an interpreter in your `.exe`. This is how tools like `PyInstaller` and `py2exe` work. But if you wrote your UI in another language then you probably should use an Instagram API client from that language instead of embedding this Python version.

I have crreated an UI with python and then converted it to `.exe`  . when i tried runing in a system where python is not there , it gave error that instaloader is not found but the ui is working .

**Comment by manishdashsharma** [comment]
> Instaloader is written in Python so obviously Python needs to be installed in system for it to work.
> Or if it's possible to change the whole source code to some other language, you may try that. (I'm not sure about this)
> 
> Btw i was wondering, this UI is for personal use or you gonna share with some other ppl as well?

i will share with people .

**Comment by susodapop** [comment]
> when i tried runing in a system where python is not there , it gave error that instaloader is not found but the ui is working .

Sounds like you need to tweak the settings when converting to `exe`.

**Comment by manishdashsharma** [comment]
> > when i tried runing in a system where python is not there , it gave error that instaloader is not found but the ui is working .
> 
> Sounds like you need to tweak the settings when converting to `exe`.

What should be done can you please suggest?

**Comment by Deleora** [comment]
> > > when i tried runing in a system where python is not there , it gave error that instaloader is not found but the ui is working .
> > 
> > 
> > Sounds like you need to tweak the settings when converting to `exe`.
> 
> What should be done can you please suggest?

Simplest thing I can suggest is that 
1. When the user installs/opens the app, it informs the user that it needs to download Instaloader modules to work OR,
2. You tweak the app to download Instaloader modules without any prompt to the user (which I don't recommend)

**Comment by Deleora** [comment]
> > Instaloader is written in Python so obviously Python needs to be installed in system for it to work.
> > Or if it's possible to change the whole source code to some other language, you may try that. (I'm not sure about this)
> > Btw i was wondering, this UI is for personal use or you gonna share with some other ppl as well?
> 
> i will share with people .

I'm curious, plz share soon 😅😅👍

**Comment by manishdashsharma** [comment]
> > > Instaloader is written in Python so obviously Python needs to be installed in system for it to work.
> > > Or if it's possible to change the whole source code to some other language, you may try that. (I'm not sure about this)
> > > Btw i was wondering, this UI is for personal use or you gonna share with some other ppl as well?
> > 
> > 
> > i will share with people .
> 
> I'm curious, plz share soon 😅😅👍



I could do it . Now the exe doesnot required neither python nor instaloader module in a system to run . Now the problem how can i deploy to a server .
