### ISSUE TITLE
Does this scrape pictures of a private profile that I don't follow ?

### ISSUE THREAD

**Issue by iOSGenesis** [instaloader/instaloader#685]
For some reason I thought this was able to give me private instagram profile pictures I don't follow. I want to snoop someones profile but they rejected my friend request ... I ran the code and it said that their profile is private. Any help ? im still new to all of this sorry .

**Comment by susodapop** [comment]
_Of course not._ If you could see a private feed after they rejected your friend request then the feed wouldn't be "private" 😉`instaloader` is just an API client. Not "god mode".
