### ISSUE TITLE
Add HTTPS/SOCKS5 Proxy Support?

### ISSUE THREAD

**Issue by GuyMight44** [instaloader/instaloader#687]
**Provide us a use case of the feature**
Setting a SOCKS5/HTTPS proxy so we can scrape Instagram if our IP is currently blocked (rate limited)

**Describe the solution you'd like**
I work with the Python module and dont use the command line version but something like:
```
proxyinfo = { "https": "1.1.1.1:80"}
proxyinfo = { "socks5": "1.1.1.1:80"}

L = instaloader.Instaloader(proxy=proxyinfo)

```

**Describe alternatives you've considered**
Dont have any alternative ideas

**If the feature request is accepted, would you be willing to submit a PR?**
Sure but how does Instaloader connect? Eyeballing the code, I assume it uses requests? If so, you could probably use:

```    
After installing PySocks: https://pypi.org/project/PySocks/

        proxies = {
        "http": "socks5://{}".format(IPAddr)
        }

        proxies = {
        "https": "{}".format(IPAddr)
        }


 r = requests.get('https://instagram.com/', proxies=proxies)
```
Yes / No _Y_(Help can be provided if you need assistance submitting a PR)_

**Additional context**
Add any other context about the feature request here.

(please also see https://instaloader.github.io/contributing.html for how to suggest a feature)

**Comment by Thammus** [comment]
> **Describe alternatives you've considered**
> Dont have any alternative ideas

As described in [this comment](https://github.com/instaloader/instaloader/pull/174#issuecomment-577011167), you can use environment variables to set a proxy for requests.
