### ISSUE TITLE
Won't instagram ban me?

### ISSUE THREAD

**Issue by alistvt** [instaloader/instaloader#688]
Hi. yesterday I used this repo [PyInstaStories](https://github.com/dvingerh/PyInstaStories/) and downloaded one user's story. But today I found out that my account has been banned!
I wanted to know if is this repo will ban my account too or not?

Thanks.

**Comment by GuyMight44** [comment]
I looked at that repo, where does it even call instagram.com?

**Comment by alistvt** [comment]
@GuyMight44 it uses this repo [instagram_private_api](https://github.com/ping/instagram_private_api)

**Comment by Deleora** [comment]
> Hi. yesterday I used this repo [PyInstaStories](https://github.com/dvingerh/PyInstaStories/) and downloaded one user's story. But today I found out that my account has been banned!
> I wanted to know if is this repo will ban my account too or not?
> 
> Thanks.

I've been using it for like a month and downloaded so many posts, stories, etc and no issues till date.

And according to [this](https://github.com/instaloader/instaloader/issues/692#issuecomment-645298773), I don't think there is any chance as Instaloader is kinda web interface.
