### ISSUE TITLE
How do I download from all pages I follow?

### ISSUE THREAD

**Issue by goodboi69** [instaloader/instaloader#689]
I am pretty new here and to this program. I cannot figure out how to download all of the pages that my profile is following. How do I do so?

**Comment by Deleora** [comment]
By 'pages' do you mean PROFILEs? Plz be more clear.
Also does 'download all of the pages' mean all the posts on that page/profile?

**Comment by goodboi69** [comment]
> 
> 
> By 'pages' do you mean PROFILEs? Plz be more clear.
> Also does 'download all of the pages' mean all the posts on that page/profile?

I apologize. Let me be more descriptive.

I follow around 500 profiles, currently. I would like to download all the profiles that I follow on a currently updated basis. I have been using 4KStogram for a while but the program doesn't have a way to check for Instagram's rate limits. It's only downfall really. So the steps I would to take would be:

1. Download all profiles I follow.
2. Update said profiles when I run the program.
3. Be able to add/check for new profiles I follow and download.

**Comment by Thammus** [comment]
It sounds like you simply want to download all followees. This can be achieved by using the target @YOUR_PROFILENAME like described in the [documentation](https://instaloader.github.io/basic-usage.html#what-to-download).
To update the profiles you can use [`--fast-update`](https://instaloader.github.io/cli-options.html#cmdoption-fast-update).

**Comment by goodboi69** [comment]
OK. I almost got it... I think. What am I missing?
".\instaloader  --login=_username_ @profile"
Do I enter my profile username for @profile like "@username"? I tried that and it doesn't work.
