### ISSUE TITLE
Python Script downloading Stories

### ISSUE THREAD

**Issue by 9dc** [instaloader/instaloader#691]
When downloading stories with python script, it doesnt put the stories in the right directory.

`L = Instaloader(dirname_pattern="/home/insta/data/{target}", download_comments=False, download_video_thumbnails=False, save_metadata=False,)

if args.ds :
    L.load_session_from_file('USERNAME')
    for user in args.ds :
        profile = Profile.from_username(L.context, user)
        print('Downloading ', profile.username, ' ', profile.userid)
        if profile.has_viewable_story:
            L.download_stories([profile.userid])`

if i run this script, it downloads all stories of all profiles in the directory ":stories"!

**Comment by Deleora** [comment]
What do you mean by 'right directory'?
Also ':stories' is the default directory, you may change it in the module according to your needs

**Comment by 9dc** [comment]
@Deleora sorry, i mean corrent directory.
I have set the dirname_pattern, it still doesnt work for Stories. For Posts there is no problem.

**Comment by Thammus** [comment]
You can set `L.dirname_pattern` to a concrete directory (without using `{target}` which gets substituted by ":stories") before each invocation of `L.download_stories()`.

**Comment by 9dc** [comment]
Thanks it works now 
/close
