### ISSUE TITLE
Retrieve all posts where user is mentioned in comments (Activity)

### ISSUE THREAD

**Issue by dumbud16** [instaloader/instaloader#698]
**Provide us a use case of the feature**
This feature would gather information from the "Activity" pane. The Activity pane lists follows and likes, but it also includes comments where the (logged-in) user is mentioned. My feature suggestion is to add a function that grabs the posts associated with the comments where the logged-in Instagram user is mentioned. This feature requires that Instaloader is signed in to an Instagram account.

Example use of function:

```
loader = Instaloader()
loader.load_session_from_file('USER')
for post in loader.posts_where_mentioned(): # Post instances returned
    ...
```

This feature would be useful for building a bot that responds to an Instagram comment when called upon (like most Twitter bots).

**Describe alternatives you've considered**
The only other way to get mentioned comments is to:

1. Scan a wide range of posts, either from a hashtag or other list
2. Go through the list and scan each comment of each post, checking for a mention.
3. Repeat

**If the feature request is accepted, would you be willing to submit a PR?**
Too sick right now to get some code in, but maybe I could submit a PR once I get better.

**Additional context**
This feature should be easy to implement. The flow would look something like this:
1. All information from the Activity pane is scraped. 
2. Entries featuring "...mentioned you in a comment..." are filtered out.
3. The post shortcode featured in each entry can be stripped and turned into a Post object.
4. Return Post object. (and possibly the comment itself)

Searching the posts for the specified comments is a task that can either be left to the module itself, or to those who use the function.

**Comment by Thammus** [comment]
Nice feature suggestion! The infos from the activity pane could be fetched and provided similarly to the `TopSearchResults`. This could be implemented in a new class for the activities with methods to access new followers, likes and comments.

**Comment by valessiobrito** [comment]
Nice feature suggestion!    I needed to create a monitoring panel for referral activities;  In special: "...mentioned you in a comment...".   Can someone help me?
