### ISSUE TITLE
Download specific highlights

### ISSUE THREAD

**Issue by Deleora** [instaloader/instaloader#699]
Is it possible to download only specific highlights and not all?
Or the other way, is it possible to skip specific highlights? If so then how?

**Comment by 9dc** [comment]
What do you mean by specific?
You could filter with datetime.

**Comment by Deleora** [comment]
I said specific in terms of highlight label /name (folders are created by the name so I was hoping to download only when the name of highlight matches with the one I specify). But if there is anything like short code or something then also it's fine. 

In filter by datetime, is it the datetime of creation or last update? And how may I do this datetime filter?

**Comment by aandergr** [comment]
I think with the CLI it is not possible to download only specific highlights or skip specific highlights of a profile. All highlights are downloaded when `--highlight` is given. Also, there is no `--storyitem-filter` attribute that could be use to filter by the originating highlight.

If you wanna script it, you could have a look at Instaloader.download_highlights(): https://github.com/instaloader/instaloader/blob/e21d34124dac3e5f384ca5d233eafb977c2f48ee/instaloader/instaloader.py#L694-L714

Likewise, you could loop through Instaloader.get_highlights(user), skip the unwanted highlights, and download the ones that you want.

**Comment by Deleora** [comment]
When I try to execute the above code after little modifications I'm getting error in line 694 while passing PROFILE as 'user' to get_highlights().
Error: 
```
Traceback (most recent call last):
  File "C:/Users/LAPTOP/PycharmProjects/InstaloaderTesting/downloadHighlights.py", line 20, in <module>
    for user_highlight in L.get_highlights(user):
  File "C:\Users\LAPTOP\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloader.py", line 648, in get_highlights
    userid = user if isinstance(user, int) else user.userid
AttributeError: 'str' object has no attribute 'userid'

Process finished with exit code 1
```
How can I pass the PROFILE in `user: Union[int, Profile]` format?

> instaloader --version: 4.4.2

**Comment by Deleora** [comment]
> When I try to execute the above code after little modifications I'm getting error in line 694 while passing PROFILE as 'user' to get_highlights().
> Error:
> 
> ```
> Traceback (most recent call last):
>   File "C:/Users/LAPTOP/PycharmProjects/InstaloaderTesting/downloadHighlights.py", line 20, in <module>
>     for user_highlight in L.get_highlights(user):
>   File "C:\Users\LAPTOP\AppData\Local\Programs\Python\Python37\lib\site-packages\instaloader\instaloader.py", line 648, in get_highlights
>     userid = user if isinstance(user, int) else user.userid
> AttributeError: 'str' object has no attribute 'userid'
> 
> Process finished with exit code 1
> ```
> 
> How can I pass the PROFILE in `user: Union[int, Profile]` format?
> 
> > instaloader --version: 4.4.2

Ok I fixed this error by 
```
...
user = P.userid
for user_highlight in L.get_highlights(user):
...
```
Thank you for the help!!

**Comment by Deleora** [comment]
This is the [final code](https://pastebin.com/t3ZG3TyQ) that I'm using to download specific highlights, but it downloads compressed JSON files. Can anyone plz help me in passing `--no-compress-json` to this snippet?

**Comment by aandergr** [comment]
> Can anyone plz help me in passing `--no-compress-json` to this snippet?

Invoke Instaloader with `compress_json=False` (https://instaloader.github.io/as-module.html#instaloader.Instaloader)

```
L = instaloader.Instaloader(compress_json=False)
```

**Comment by Deleora** [comment]
Alright, Thanks!!
