### ISSUE TITLE
Retrieve stories and getting 403 when accessing some url

### ISSUE THREAD

**Issue by DanielZhu03** [instaloader/instaloader#704]
**Describe the bug**
I was downloading stories and it kept getting  `403 when accessing [URL]`, and I opened the link, it showed "Bad URL hash
" or "url signature mismatch". I tried to switch different accounts to download these stories again and it still didn't work. I also noticed all the links that couldn't downtown was video links. 

**To Reproduce**
Like when I retrieve stories from account **`tottapala`**

**Error messages and tracebacks**

`Download story from user tottapala: 403 when accessing https://scontent-lax3-1.cdninstagram.com/v/t50.2886-16/0_0_0_ .mp4?_nc_ht=scontent-lax3-1.cdninstagram.com&_nc_cat=100&_nc_ohc=YcbhOxH4_wwAX8Yu_T4&oe=5EF6E5D4&oh=d27714578d5c35512a073fbb6e45aa59.`

**Instaloader version**
4.4.4

**Comment by AyluinReymaer** [comment]
I have this issue as well, I was troubleshooting it and apparently its not an issue with instaloader, it's on instagram itself.

I have this same issue in my PC with chrome when trying to access video stories.

However, the android instagram app seems fine.

I'm also trying to investigate a workaround as this is an issue for me.

**Comment by marioaugustorama** [comment]
it is not every profile that has presented this problem, I tested it with another 100 and less than 15% presented this problem.

**Comment by AyluinReymaer** [comment]
Also, not all story videos from the same profile have this problem.
From what I've understood, when a profile has this issue, most story items will have this issue but not all of them.

I've installed an android emulator to see what kind of graphql query hash they use on the instagram app.

Maybe they've updated the query hash on the android app but not on the web app??

Dunno... I'll keep you posted in my findings

**Comment by AyluinReymaer** [comment]
Instagram is a big pain in the a**...

The app uses tls1.3 for it's https queries. Using a web proxy debugger doesn't work because most (if not all) proxy debuggers only support up to tls1.2...

In other words, the only way to know which queries the app is doing, is to check the app's code (at least to my knowledge it's the only way).

Sooo... we will need to wait until instagram fixes the issue.

**Comment by ungenio** [comment]
The video thumbnails do download, but not the video.

storyinsta.com can access the public stories without problems

**Comment by tim54000** [comment]
Same issue with versions 4.4.2 and 4.4.4. 
It seems that it only crashes on video stories, not systematically.
Probably due to an instagram API change, as the URL seems to be badly formatted (try to find a video named `0_0_0_.mp4`).

**Comment by tim54000** [comment]
It would appear that the Instagram API has been fixed. I no longer have any problem downloading video stories, even the ones that crashed instaloader yesterday.

**Comment by AyluinReymaer** [comment]
I can confirm the same, its working for me now.

**Comment by tim54000** [comment]
The bug appeared at the same time as the feature (currently under test) Real (content similar to TikToks). Could it be a bug that happened only in the countries where the Reals ones were being tested? (France, Germany & Brazil).

For my part, I live in France and so I had the Real feature. Were you in a country with the Reals?

**Comment by DanielZhu03** [comment]
I don't think so. I live in China and I use VPN to get access to the Instagram. I tried to switch my ip address with different countries and none of these worked. So I think maybe it's not the Real feature causes the problem.
