### ISSUE TITLE
Download direct messages of all the PROFILES

### ISSUE THREAD

**Issue by Deleora** [instaloader/instaloader#705]
**Provide us a use case of the feature**
command line argument which downloads the direct messages of the PROFILE specified

**Describe the solution you'd like**
Download all the messages including all media like posts, pics and videos for complete offline readability. Also if the messages are formatted with the time at which each message was sent it would be good. And at the end, if all this can be visualized in an html which loads all the messages and media would be good.

**Describe alternatives you've considered**
Nothing I can think of right now. But I have used another [repository](https://github.com/firmanjml/IGDM2Convo) which requires some manual work.

**If the feature request is accepted, would you be willing to submit a PR?**
It won't be possible to be spontaneous but I would like to try if required

**Additional context**
I've used this [repository](https://github.com/firmanjml/IGDM2Convo) which gave me this idea in the first place. It needs `messages.json` (can get by requesting your data from Instagram under settings) file to parse it into HTML. But it can create the HTML for only one PROFILE at a time, which means we need to clean up the `messages.json` file to contain only that particular PROFILE's chat node.

**Comment by aandergr** [comment]
I think there are at least two suitable alternatives to integrating such a feature into Instaloader:

- Use the `messages.json` which seems to contain the messages 

- A separate script for downloading DMs, which uses Instaloader only for its login functionality, get_json(), and eventually its structures for representing Profiles etc.

I recently had a look with Chrome DevTools into accessing DMs and it doesn't seem that hard to access. Surprisingly, it doesn't use the GraphQL API and it will require some engineering to cleanly access the according endpoints and to nicely present the data structures (the threads with metadata such as `users` and `inviter` and the message items of at least two types, `text` and `reel_share`).

What would be the advantage of integrating such a feature into Instaloader?

**Comment by Deleora** [comment]
Well, before I answer that I would like to know What's the advantage of having Instaloader in the first place? In general, I feel that your answer would answer the question you asked me. (I apologize if this sounds rude, but believe me it's not).

Now I would like to answer your question. First, I think it'll make Instaloader more complete. In one of your replies to an issue you said that Instaloader mimics the Instagram web interface. So, adding this feature will be like one more step towards it.
One more reason/advantage I can think of is, like other features (downloading posts, stories etc) allow us to save the profile for complete offline browsing this will allow us to read and more importantly search through the chats without any problem.
Also let's say some user X blocks me, then I'll lose all my chats with them. This feature can allow us to save the chats before hand (something like weekly backup) so that even if we lose chats on the server, we'll still have it saved with us.

What do you say?

**Comment by aandergr** [comment]
For archiving the own account, Instagram already provides the download of this abovely-mentioned "Personal Data" ZIP, which contains all personal data in a structured manner which is easy to process. 

Instaloader's biggest advantage is probably that with its automation it makes it easy to access the Big Data from Instagram, making it the tool of choice for many data intensive research. The direct messages on the other hand, are easy to obtain and process without any extra effort (with the `messages.json` in the personal data zip), and they are usually not such a treasure of data.

However, I am inclined to agree with the reasoning that accessing the direct messages makes it more complete for the use case of archiving the own account in a more automated fashion to allow for a scheduled backup.

**Comment by Deleora** [comment]
So do you think this feature suggestion is worth the time and effort and worth integrating into Instaloader?

**Comment by aandergr** [comment]
As stated above, I don't think this is worth the effort, since Instagram itself also kind of provides this feature. However, I think the effort-gain ratio is very subjective.

We would accept a PR implementing this in a clean manner, well documented and with unit tests to allow for easy maintenance of the feature.

**Comment by Deleora** [comment]
Alright, no problem.
So I was wondering if i would get a little help from you or anyone else in this.

I looked into the structures of Instaloader but i'm not sure where to start. I feel `def _obtain_metadata(self):` might be the place.
Also I'm not able to figure out what to lookup in Chrome dev tools to implement this.

A little help to start with this would be really appreciated.

**Comment by aandergr** [comment]
When I go to my direct messages with the Network tab open in Chrome Devtools, I see a request to `https://www.instagram.com/direct_v2/web/inbox`. DevTools shows the exact request with its parameters and its response. That is a good starting point for mimicking the request with Instaloader, which provides the InstaloaderContext.get_json() method for easy access.

**Comment by Deleora** [comment]
> When I go to my direct messages with the Network tab open in Chrome Devtools, I see a request to `https://www.instagram.com/direct_v2/web/inbox`. DevTools shows the exact request with its parameters and its response. That is a good starting point for mimicking the request with Instaloader, which provides the InstaloaderContext.get_json() method for easy access.

Hi,
I tried the above steps but I'm not seeing any such request on the Network tab. Could you please share where and how exactly to look for? Or if explaining all that would be too much maybe you can share the query hash which I may start with?
Thanks!!

**Comment by aandergr** [comment]
It's not a query hash because it is not a graphql query. I see many queries on `/api/v1/direct_v2/inbox` when clicking on the direct messages in Instagram. This query will be a good starting point.
