### ISSUE TITLE
I get an error on certain profiles. 

### ISSUE THREAD

**Issue by instaloadererror** [instaloader/instaloader#709]
Instaloader will just stop after a few posts.

Stored ID 240759746 for profile loren.
Warning: Use --login to download HD version of profile pictures.
loren/2020-05-09_18-00-08_UTC_profile_pic.jpg
Retrieving posts from profile loren.
[  1/1312] loren/2020-06-26_16-42-00_UTC.jpg [what time is it for u ? 🌙] json
[  2/1312] loren/2020-06-21_17-03-24_UTC_1.jpg Traceback (most recent call last):
  File "__main__.py", line 459, in <module>
  File "__main__.py", line 455, in __main
  File "__main__.py", line 412, in main
  File "__main__.py", line 192, in _main
  File "instaloader\instaloader.py", line 1106, in download_profiles
  File "instaloader\instaloader.py", line 492, in download_post
  File "instaloader\structures.py", line 231, in get_sidecar_nodes
KeyError: 'video_url'
[3428] Failed to execute script __main__

**Comment by Showmaster3000** [comment]
- You didn't use the issue template!
- You didn't mention the version you use!

error message looks like an older bug, which is solved. Please update to the latest version!

**Comment by instaloadererror** [comment]
> Please update to the latest version!

How do I do that? I tried downloading the newest version, but when I open it it doesn't work. When I try to open it I get an error. I unzipped the file in the same folder as the 4.3 version I had been using. The two folders for each version are right next to each other so I don't know why one works and the other doesn't. 

& : The term 'C:\Users\student\Videos\1' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:3
+ & C:\Users\student\Videos\1 - Instagram Downloader\instaloader-v4.4.4 ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\student\Videos\1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
