### ISSUE TITLE
Some thoughts on "stories on web site"

### ISSUE THREAD

**Issue by e5150** [instaloader/instaloader#71]
So.. I've done a bit of digging since IG has started putting stories on the web page. I think it would be nicer not having to pretend to be a smartphone app and do some voodoo to the headers to fetch stories. 
The official site sends a graphql query with `id=17890626976041463`, which roughly equates to `_get(url_reels_tray)`. But it is "empty", in the sense that it has no `"items"` (comparable to the issue that commit [`82ae31c`](https://github.com/Thammus/instaloader/commit/82ae31cea58c7d1361a2e5e9eea8174881874b72) dealt with).
It returns `['data']['user']['feed_reels_tray']['edge_reels_tray_to_reel']['edges']`, with a list of nodes:
```
"node": {
	"expiring_at": 1515777284,
	"id": "...",
	"latest_reel_media": 1515690884,
	"ranked_position": 1,
	"user": {
		"id": "37...",
		"profile_pic_url": "https:...jpg",
		"username": "d..."
	}
}
```

So users whose stories are sought need to be queried for their actual stories: GQL `id=17873473675158481` with `{'reel_ids' = [uid(s)]}`. Though I think it would be possible to make use the `latest_media_reel` timestamp to avoid polling for a user's stories unnecessarily, somewhat like what is done for `fast_update`.
Anyway, the "web-reels_media" query returns a list in `['data']['reels_media']` that roughly contains:
```
"items": [
	{
		"__typename": "GraphStoryImage" / "GraphStoryVideo",
		"display_url": "https://sconte...44320_n.jpg",
		"id": "168...",
		"is_video": true / false,
		"taken_at_timestamp": 1515621936
		if is_video:
		"video_resources": [ { "src": "https://scontent...02434186091_n.mp4" } ]
	},
	...
],
"latest_reel_media": 1515697130,
"user": {
	"id": "49165...",
	"profile_pic_url": "https://...8528_n.jpg",
	"username": "b..."
}
```
Which to me looks more in line with what is returned by the other website-GQL calls, and might be able to integrate with the `Post` class (if that even makes sense for stories).

I don't have any plans to work on migrating story-related methods from the app-spoofing at the moment, but I don't think it would be all that hard.

**Comment by aandergr** [comment]
Hi Lars,

thanks for all the effort with reverse engineering this and sharing this with us! We will definitely soon work on implementing to use this more consistent way of accessing Instagram.

(We are still laughing about the 'some voodo too the headers', but it really well describes what was happening there)

Best regards
Alex

**Comment by e5150** [comment]
It is apparently possible to get both feed and story tray with GQL `id=17842794232208280` and `{'has_stories': True}`, used by [instagram_private_api](https://github.com/ping/instagram_private_api/blob/master/instagram_web_api/client.py). Such a GQL query could replace the first feed-page fetch `data = self.get_json(...)` in `:meth:get_feed_posts`.
It returns `['data']['user']['edge_web_feed_timelame']['edges']` with a node list that looks like what GQL `id=17863003771166879` (used currently for all but the first feed page) plus the same `feed_reels_tray` response of the dedicated story tray GQL `...1463` mentioned in the first post.
(GQL `...8280` could also replace the subsequent `...6879` calls, without `has_stories`, fetching stories would make most sense for only the first feed page, to emulate browser behaviour.)
That said, it would only save one request, but probaby require some significant refactoring to put story fetching together with feed fetching, so I'm not sure it would be worth it.

But the [API](https://github.com/ping/instagram_private_api) mentioned seems quite interesting. It contains two separate APIs, one for web-site emulation and one with sophisticated app spoofing. And by doing event more voodoo to the headers it's able to fetch live video and live video replay information. After some rudimentary testing I've been able to get replays. Actual live broadcasts are more troublesome, several downloaded segments have been invalid (bad moov atoms in mp4 video/audio streams), and required manual processing before passing to `ffmpeg` for merging.
Anyway, with some luck Instagram may add live videos (and replays) to the web page in the future, making it easier to implement in Instaloader. (I'm not suggesting switching to `instagram_{private,web}_api`, just that its code is quite nice, and looking at how others are doing things might ease the task of reverse engineering and such.)

**Comment by aandergr** [comment]
Implemented in `v4-dev` branch for [Version 4](https://github.com/instaloader/instaloader/projects/1). Thanks again!
