### ISSUE TITLE
Too many queries all the time 

### ISSUE THREAD

**Issue by axeldotjara** [instaloader/instaloader#713]
Hi, 

I have the next problem , i know the too many queries message its normal, but if i wait it continues downloading images. Well right now that doesnt happend. All the time it send the too many queries message and it doesnt come back to download. 

can i have some help with this?

im using the next code, when its starts it work fine, but after five hours the problem starts.

import instaloader
L = instaloader.Instaloader(sleep=True,
                            quiet=None,
                            user_agent=None,
                            #dirname_pattern=, # diectorio
                            filename_pattern="{profile};{date_utc}",
                           # filename_pattern=None,
                            download_pictures=True,
                            download_videos=None,
                            download_video_thumbnails=None,
                            download_geotags=None,
                            download_comments=True,
                            save_metadata=True,
                            compress_json=None,
                            #post_metadata_txt_pattern="",
                            storyitem_metadata_txt_pattern=None,
                            max_connection_attempts=1000000,
                            request_timeout=1000,
                            commit_mode=None)

L.login()
L.download_location('')

![Anotación 2020-07-01 094317](https://user-images.githubusercontent.com/65202743/86251653-25a50080-bb80-11ea-84f8-545db546fb90.jpg)

Plz any comments helps me.

Thanx.

> [](url)

**Comment by axeldotjara** [comment]
i fix it changing the max_connection_attempts value

**Comment by sourface94** [comment]
What did you change the max_connection_attempts value to?

**Comment by axeldotjara** [comment]
> What did you change the max_connection_attempts value to?

I did it because i was trying to fix it, but it dosent work at all. Do you have any comments or alternative about the problem?

**Comment by axeldotjara** [comment]
> i fix it changing the max_connection_attempts value

it didnt work at all.

**Comment by Neurotoxin001** [comment]
Same issue only after 20 downloaded videos, wtf

**Comment by sourface94** [comment]
> > What did you change the max_connection_attempts value to?
> 
> I did it because i was trying to fix it, but it dosent work at all. Do you have any comments or alternative about the problem?

Just saw this but no the only solution I had was to limit the number of times I tried to get images or anything else like that
