### ISSUE TITLE
Follower

### ISSUE THREAD

**Issue by milankhatir** [instaloader/instaloader#718]
I need to check that a user follow specific page or not ! I didn't find any methods that do it. Is there any way?

**Comment by Deleora** [comment]
Yes, write a little code to loop through the list of all followers of the profile and check if it matches with the one you want. That's actually a basic logic

**Comment by milankhatir** [comment]
tnx @Deleora  , But Its take alots time , based of program rules after take 1000 followers ,its stop fetching for 10 minutes . It takes more than 7 days for a page with more than one million followers

**Comment by Deleora** [comment]
Well, that's a server side protection (to avoid overloading the servers with bot requests (automation)) which can't be overridden as far as I know.
So, the only way to do what you want is one mentioned above. One more way I can think of is using Instagram APIs (there are plenty on GitHub), but I haven't used them so I don't know how that works.
