### ISSUE TITLE
How do I update Instaloader to the newest version?

### ISSUE THREAD

**Issue by instaloadererror** [instaloader/instaloader#719]
I've been using v4.3, but there's a bug with that one so it won't work on some profiles. I was told to update to the newest version, v4.4.4, but it won't work. I downloaded the new version, but when I open the .exe I get an error and another error when I try to use the command to download a profile. I included a picture of the errors.
<img width="676" alt="instaloader" src="https://user-images.githubusercontent.com/67607076/86663230-80dd5580-bfbb-11ea-9c71-620d651185a6.png">

**Comment by Showmaster3000** [comment]
Once again, duplicated question from #709. 
I use Windows, but not the standalone exe which is build for powershell instead of cmd since v4.4.
Hint: If you read the error message, the solution seems to be written in - exactly: 
> [...] instead type ".\instaloader"
