### ISSUE TITLE
Post mediaid to shortcode conversion not work properly

### ISSUE THREAD

**Issue by kraw** [instaloader/instaloader#721]
**Describe the bug**
Post search by media id not work properly because the mediaid to shortcode conversion is broken. I saw that behind the scene Post.from_mediaid generate a shortcode and then Post.from_shortcode search for results, however the conversion function is not working. 
Example with data from facebook api graph integration:
mediaid =  **17976461317132572**
shortcode = **BqtFyd1F5_q** //this shortcode is returned by facebook api
instaloader_shortcode = **_3X8PIFEc** //this sortcode was returned by instaloader.Post.mediaid_to_shortcode 

**To Reproduce**
mediaid= 17976461317132572
post = Post.from_mediaid(L.context, mediaid)

**Expected behavior**
shortcode = Post.mediaid_to_shortcode(mediaid)
Actual shortcode retrieved by instagram: **BqtFyd1F5_q**
Shortcode generated by Post.mediaid_to_shortcode(mediaid): **_3X8PIFEc**
post = Post.from_shortcode(L.context, shortcode)

**Error messages and tracebacks**
instaloader.exceptions.QueryReturnedNotFoundException: JSON Query to p/_3X8PIFEc/: 404 Not Found 
This error happen because not post with this **shortcode** exists.  

**Instaloader version** 4.4.4

**Comment by Thammus** [comment]
If [this](https://www.instagram.com/p/BqtFyd1F5_q/) is the post you mean, then the mediaid "17976461317132572" which is provided by the Facebook Graph API is not the one that is used by Instagram and Instaloader to identify this post. As Instaloader converts correctly, the post which is identified by the shortcode "BqtFyd1F5_q" has the mediaid "1922218074192715754" which is also present in the metadata returned by Instagram when accessing the post. 

Hence Instaloader's mediaid to shortcode conversion is not broken but you cannot simply use this sort of mediaids provided by the Facebook Graph API to fetch the corresponding posts on Instagram.
