### ISSUE TITLE
How to download the top posts of a hashtag from instaloader

### ISSUE THREAD

**Issue by huiguo85** [instaloader/instaloader#722]
I am using instaloader to download hashtag posts using the "download_hashtag" method from the python module. Some context, when you search a hashtag in instagram, it shows up 2 types of posts. The first one is top posts, which are selected by instagram's proprietary algorythm; the second one is the most recent posts.

"download_hashtag" method appears to download the most recent posts and I couldn't find the method or arguments that allow me to download the top posts. Is there any existing method from instagram that I can download the top posts? Or if there is other package that I can use to perform this task?

**Comment by aandergr** [comment]
There is
- [Hashtag.get_top_posts()](https://instaloader.github.io/as-module.html#instaloader.Hashtag.get_top_posts) which only yields the top posts,
- [Hashtag.get_posts()](https://instaloader.github.io/as-module.html#instaloader.Hashtag.get_posts), which yields the posts that Instagram lists as "recent" posts,
- [Hashtag.get_all_posts()](https://instaloader.github.io/as-module.html#instaloader.Hashtag.get_all_posts) which yields a merge of these two lists.

The download_hashtag() method internally uses Hashtag.get_all_posts().
