### ISSUE TITLE
Can anyone help me learn how to login? Getting 429 error (New at coding/python)

### ISSUE THREAD

**Issue by Jablinski-hub** [instaloader/instaloader#728]
Ive been trying to run instaloader,

Ive Installed Instaloader and updated as directed in the readme and ive tried to do a basic command of instaloader "Username" and its coming up with this error:
![Error](https://user-images.githubusercontent.com/68208751/87305137-565e4000-c559-11ea-900f-75f38f32ccb6.PNG)

This is the terminal transcript from when ive been trying stuff. Just wanted to make sure there isnt anything im doing that is obviously not right so i can learn what not to do next time?

I've seen that i need to enter password and username for it to work again, do i do that in my code editor (im using Visual studio code).

Thanks in advance anyone who can quickly look over this!
<3

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\MMCS\Desktop\Repository\Instaloader Repository Source Code\Instaloader
test>C:/Users/MMCS/AppData/Local/Programs/Python/Python38-32/python.exe "c:/Users/MMCS/Desktop/Repository/Instaloader Repository Source Code/Instaloader test/Jablinski_Scraper.py"
  File "c:/Users/MMCS/Desktop/Repository/Instaloader Repository Source Code/Inst
aloader test/Jablinski_Scraper.py", line 1
    $pip3 install instaloader
    ^
SyntaxError: invalid syntax

C:\Users\MMCS\Desktop\Repository\Instaloader Repository Source Code\Instaloader
test>C:/Users/MMCS/AppData/Local/Programs/Python/Python38-32/python.exe "c:/Users/MMCS/Desktop/Repository/Instaloader Repository Source Code/Instaloader test/Jablinski_Scraper.py"
  File "c:/Users/MMCS/Desktop/Repository/Instaloader Repository Source Code/Instaloader test/Jablinski_Scraper.py", line 1
    instaloader [--login jonathan_cervantes92]
                         ^
SyntaxError: invalid syntax

C:\Users\MMCS\Desktop\Repository\Instaloader Repository Source Code\Instaloader test>C:/Users/MMCS/AppData/Local/Programs/Python/Python38-32/python.exe "c:/Users/MMCS/Desktop/Repository/Instaloader Repository Source Code/Instaloader test/Jablinski_Scraper.py"
  File "c:/Users/MMCS/Desktop/Repository/Instaloader Repository Source Code/Instaloader test/Jablinski_Scraper.py", line 1
    instaloader [--login jonathan_cervantes92]
                         ^
SyntaxError: invalid syntax

C:\Users\MMCS\Desktop\Repository\Instaloader Repository Source Code\Instaloader test>
C:\Users\MMCS\Desktop\Repository\Instaloader Repository Source Code\Instaloader test>pip3 install --upgrade instaloader
Requirement already up-to-date: instaloader in c:\users\mmcs\appdata\local\programs\python\python38-32\lib\site-packages (4.4.4)
Requirement already satisfied, skipping upgrade: requests>=2.4 in c:\users\mmcs\appdata\local\programs\python\python38-32\lib\site-packages (from instaloader) (2.24.0)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in c:\users\mmcs\appdata\local\programs\python\python38-32\lib\site-packages (from requests>=2.4->instaloader) (2.10)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\mmcs\appdata\local\programs\python\python38-32\lib\site-packages (from requests>=2.4->instaloader) (2020.6.20)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in c:\users\mmcs\appdata\local\programs\python\python38-32\lib\site-packages (from requests>=2.4->instaloader) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\mmcs\appdata\local\programs\python\python38-32\lib\site-packages (from requests>=2.4->instaloader) (1.25.9)

C:\Users\MMCS\Desktop\Repository\Instaloader Repository Source Code\Instaloader test>instaloader 6amfeeling

HTTP redirect from https://www.instagram.com/6amfeeling/ to https://www.instagram.com/accounts/login/?next=/6amfeeling/
JSON Query to 6amfeeling/: 429 Too Many Requests: redirected to login [retrying; skip with ^C]
HTTP error code 429 was returned because too many queries occurred in
the last time. Please do not use Instagram in your browser or run
multiple instances of Instaloader in parallel.
The request will be retried in 664 seconds, at 22:42.
GraphQL requests:
  other
    last 10 minutes: 1 requests
    last 11 minutes: 1 requests
    last 15 minutes: 1 requests
    last 20 minutes: 1 requests
    last 30 minutes: 1 requests
    last 60 minutes: 1 requests

**Comment by Showmaster3000** [comment]
As I replied in #726 check/change your ip address. It seems to be blocked by instagram. refer to: https://instaloader.github.io/troubleshooting.html#too-many-requests
If you use your account to login now, it also will be blocked by instagram.
Everything else is well described in the manual: https://instaloader.github.io/
