### ISSUE TITLE
Option to unsave posts after downloading them

### ISSUE THREAD

**Issue by DigiOhhh** [instaloader/instaloader#729]
**Provide us a use case of the feature**
I'd like being able to unsave the posts downloaded using _:saved_.

**Describe the solution you'd like**
Passing an additional parameter to the invocation of instaloader would be the perfect solution.

**Describe alternatives you've considered**
There isn't really any alternative. I mean, of course you could always go look for those pictures you want to delete and manually unsave them.

**If the feature request is accepted, would you be willing to submit a PR?**
Sorry, I don't think I am proficient enough in Python to implement this feature myself.

**Additional context**
—

**Comment by Thammus** [comment]
This is against Instaloader's goal not to manipulate any of the online data.

> Instaloader’s goal is to mimic the browser’s behavior to access the data that is available through the Instagram web interface, pack this data into complete and easily-(re)usable python objects, and provide a user interface for the most common downloading and metadata collection tasks, **without changing any of the online data**.

**Comment by DigiOhhh** [comment]
k, I'll look for something more useful then
