### ISSUE TITLE
What's the best way to query more data from instagram

### ISSUE THREAD

**Issue by huiguo85** [instaloader/instaloader#731]
I tried to query large set of data (10 thousand of posts at a time) using instaloader. I received messages "query too many times, need to wait xxx seconds". My questions is there any way we can solve this problem? through new ip or new accounts etc?

Also, is there any risk Instagram will block the account if querying too many data?

**Comment by rocailler** [comment]
Instaloader have it own rate limit so no - this is instaloader message, not instagram. the limit is something about 200req/hour
it's too lot for Instaloader. 
To do this try selenium with proxy instances and queries. for ex. query with 50 user posts:
`'https://www.instagram.com/graphql/query/?query_id=17888483320059182&id={}&first=50'.format(user_id)`
or form hashtag:
`'https://www.instagram.com/graphql/query/?query_id=17875800862117404&variables=%7B%22tag_name%22%3A%22{}%22%2C%22first%22%3A50%7D'.format(hashtag)`

**Comment by septfish** [comment]
> Instaloader have it own rate limit so no - this is instaloader message, not instagram. the limit is something about 200req/hour
> it's too lot for Instaloader.
> To do this try selenium with proxy instances and queries. for ex. query with 50 user posts:
> `'https://www.instagram.com/graphql/query/?query_id=17888483320059182&id={}&first=50'.format(user_id)`
> or form hashtag:
> `'https://www.instagram.com/graphql/query/?query_id=17875800862117404&variables=%7B%22tag_name%22%3A%22{}%22%2C%22first%22%3A50%7D'.format(hashtag)`

what's the query_id?
How can I get it?

**Comment by rocailler** [comment]
> what's the query_id?
> How can I get it?

it's an ID of instagram endpoint
[https://github.com/MohanSha/InstagramResearch](url)

**Comment by septfish** [comment]
> > what's the query_id?
> > How can I get it?
> 
> it's an ID of instagram endpoint
> https://github.com/MohanSha/InstagramResearch

Thanks very much.
But when I query user data, I user the endpoint '?__a=1', but I must login In to get data.How can I get the user data?
