### ISSUE TITLE
I want to download Only Photos Without any json and Videos

### ISSUE THREAD

**Issue by imshub** [instaloader/instaloader#733]
I am new in **coding** and can't finger out how to filter videos and metadata to not download.

- I am able to login 
- I Am able to filter data when I am using cmd and I want codes to do the same. 
- Able to download all post and metadata with videos.

please help me out if anyone has any examples please help me.

**Comment by Deleora** [comment]
Please explain your problem more clearly and all methods you have tried.
What I understood is that you wish to download only photos without and video and JSON. However, I didn't understand if by photos you mean only post photos or only story/highlight photos or both.

**Comment by imshub** [comment]
@Deleora thank for reply 

I Just Want to download only post photos.

**Comment by Deleora** [comment]
You may refer to [this](https://instaloader.github.io/cli-options.html#command-line-options) documentation. It pretty much contains everything on what you wanna do.

**Comment by DennisPing** [comment]
This is your template:
instaloader --no-metadata-json --no-captions --no-profile-pic --no-video-thumbnails <targetname>

If your targetname is a private account you need to login:
instaloader --no-metadata-json --no-captions --no-profile-pic --no-video-thumbnails --login=<myname> <targetname>

Example:
instaloader --no-metadata-json --no-captions --no-profile-pic --no-video-thumbnails taylorswift
