### ISSUE TITLE
Related hashtags

### ISSUE THREAD

**Issue by ubi78** [instaloader/instaloader#734]
Hello, I'm new to coding and I need some help. I'd like to know if there is a way to get the hashtags related to a certain hashtag. I can't find anything about it. Thank you.

**Comment by aandergr** [comment]
> get the hashtags related to a certain hashtag.

[Hashtag.get_related_tags()](https://instaloader.github.io/as-module.html#instaloader.Hashtag.get_related_tags).

> I can't find anything about it.

Where did you search?

**Comment by ubi78** [comment]
Thank you! I didn't see it. Could you explain how to use it? For example, if I want to get the hashtags related to "#word", how am I suppose to write the code? Sorry, I just started coding at university and I don't understand much yet.

**Comment by aandergr** [comment]
We cannot give a programming course here, but there's plenty of resources online:
- [The Python Tutorial](https://docs.python.org/3/tutorial/index.html),
- [Python for Beginners](https://www.python.org/about/gettingstarted/),
- [Python for Non-Programmers](https://wiki.python.org/moin/BeginnersGuide/NonProgrammers).

**Comment by ubi78** [comment]
Okay thanks!
