### ISSUE TITLE
Change downloaded profile picture name

### ISSUE THREAD

**Issue by Daydream404** [instaloader/instaloader#738]
Hey, 
I want to change name for downloaded Instagram profile picture. I tried this: 

``` import instaloader
Profile = "instagram"
Name = "{mediaid}_{owner_id}"

instg = instaloader.Instaloader(filename_pattern=Name)

instg.download_profile(Profile, profile_pic_only=True)
```

but it doesn't work. What I want is profile picture  to be named just instagram.jpg not 2020-06-01_15-40-43_UTC_profile_pic.jpg. How do I change that?

**Comment by Deleora** [comment]
Do you want this for specific profile or all profiles?

**Comment by aandergr** [comment]
Given a `Profile` instance you can access the URL of the profile picture with [`Profile.profile_pic_url`](https://instaloader.github.io/as-module.html#instaloader.Profile.profile_pic_url) and just download it wherever you want.

**Comment by Daydream404** [comment]
> Given a `Profile` instance you can access the URL of the profile picture with [`Profile.profile_pic_url`](https://instaloader.github.io/as-module.html#instaloader.Profile.profile_pic_url) and just download it wherever you want. There are convenience methods in the [`InstaloaderContext`](https://instaloader.github.io/as-module.html#instaloadercontext-low-level-functions) to allow for easy downloading into a file:
> 
> ```python
> profile = instaloader.Profile.from_username(instg.context, Profile)
> instg.context.get_and_write_raw(profile.profile_pic_url, "instagram.jpg")
> ```

Thanks this will do it!
