### ISSUE TITLE
Add the option to only download the first, last or x image from an account

### ISSUE THREAD

**Issue by Akashic101** [instaloader/instaloader#739]
**Provide us a use case of the feature**
Many comic-artists post their comics slide-by-slide and provide a combined picture of all together as the last picture ([example](https://www.instagram.com/p/CC3x1p9Jx--/)). Other artists post their creative work on the first slide since it's too wide and cut the image in half and post those after that ([example](https://www.instagram.com/p/CCYHAIkhvcg/)). If the user could specify which slide to download it could save a lot of time instead of manually filtering them out after download

**Describe the solution you'd like**
An argument like `--slide` could be added which takes the parameter `first`, `last` or a number, for example 2 would only download the second slide 

**Describe alternatives you've considered**
The only alternative would be to do filter out the slides manually after the download is finish which is very tedious since many artists have hundreds of comic

**If the feature request is accepted, would you be willing to submit a PR?**
Yes

**Additional context**
There is no additional context

**Comment by aandergr** [comment]
We think that's a cool feature and we'll be happy to see a PR for this.

Just for clarification of terms:

> slide-by-slide

We assume, the *slide-by-slide* pictures are what we call *sidecars* internally in Instaloader (and in the Instagram's API response), and this would affect the downloading of sidecars. Sidecars are posts that contain multiple media (pictures or videos) bundled into one post object.

> An argument like `--slide` could be added which takes the parameter `first`, `last` or a number

What is `first`? Is it the first media, i.e. the one with number=1? Or is it the slide that is pre-selected, i.e. the slide that is shown before the user makes any swipe on the picture (which is not necessarily the first picture)?

What happens, if a sidecar does not have as many pictures as selected by the `--slide` parameter?

**Comment by Akashic101** [comment]
With `first` I'd expect to download the picture with number=1, so the slide on the furthest left. `last` would in that case be the picture the furthest to the right

If a sidecar has for example only 3 images but the user used --slide 4 I'd say the post will be skipped and the download will continue with the next sidecar. 

I haven't programmed any of this features in since Python is not a language I'd call myself good in. That was on me, I mistook the meaning of PR

**Comment by aandergr** [comment]
> With `first` I'd expect to download the picture with number=1, so the slide on the furthest left. `last` would in that case be the picture the furthest to the right
> 
> If a sidecar has for example only 3 images but the user used --slide 4 I'd say the post will be skipped and the download will continue with the next sidecar.

I think that makes sense.

> I haven't programmed any of this features in since Python is not a language I'd call myself good in. That was on me, I mistook the meaning of PR

We are usually very patient with pull requests, they don't have to be perfect on the first try. Either way, we can leave this open, maybe someone finds time and interest to implement it.

Thanks for the note regarding the meaning of PR – it's actually bad practice to use abbreviations that have not been introduced before, maybe we should fix that.
