### ISSUE TITLE
Browser Login

### ISSUE THREAD

**Issue by Deleora** [instaloader/instaloader#740]
Can I use the session files to login to Instagram with the help of [EditThisCookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en) chrome extension?
I am able to figure out some of the values required by the extension in the session file. If it's possible plz let me know. Thanks

**Comment by Deleora** [comment]
I figured. It's possible.

**Comment by psonnosp** [comment]
@Deleora 
Can you please share your findings? Trying to create a session file but the only thing I find here involves running scripts and that's sadly out of my league.

**Comment by Deleora** [comment]
@psonnosp Creating a session file does not involve any script (I mean you can use script but it isn't mandatory)
If you have Instaloader installed on your system simply run the following command on your terminal
`instaloader --login YOUR-USERNAME`
Then it'll prompt you to enter your password (which you won't be able to see on the screen), then hit Enter and your session file would be created in the default folder. You may also be asked to enter 2FA code in case you have it enabled.

If you need more help feel free to ask.
Cheers!
