### ISSUE TITLE
Instaloader.login() fails when password contains ":"

### ISSUE THREAD

**Issue by cebrito** [instaloader/instaloader#741]
**Describe the bug**
When the password contains ":", the account fails to login. Instagram just returns a "wrong password" response

**To Reproduce**
```
import instaloader
USER = "someusername"
PASSWORD = "correctpassword:"
L = instaloader.Instaloader(quiet=False, download_geotags=False, download_comments=False, save_metadata=False,
                            compress_json=False)
L.login(USER, PASSWORD)       
```

**Expected behavior**
Correct login

**Instaloader version**
4.4.5

**Comment by aandergr** [comment]
Does it work when escaping the colon with a backslash, or when putting the password within quotes? I.e.

```python
PASSWORD = "correctpassword\\:"
```

or

```python
PASSWORD = "\"correctpassword:\""
```

**Comment by cebrito** [comment]
Tried both, also tried from the terminal and base64'ing the pass but it allways raises instaloader.exceptions.BadCredentialsException: Login error: Wrong password.

For what i can gather Instagram app/web encrypts password in enc_password, which gets rid of the issue, but on instaloadercontext.py, password is used as plaintext (line 220) to form enc_password, then instagram interprets the colon as a json separator and not part of the actual pass.

I'm guessing some characters like {} , or [] would have the same effect.

**Comment by aandergr** [comment]
Yes, encrypting the password will get rid of the issue. We have a branch [feature/encrypt-password](https://github.com/instaloader/instaloader/tree/feature/encrypt-password), where Instaloader encrypts the password, at the cost of some extra dependencies. You can install it with:

```
pip3 install --upgrade git+https://github.com/instaloader/instaloader@feature/encrypt-password
```
