### ISSUE TITLE
Is it possible to use IGTV title in filename-pattern?

### ISSUE THREAD

**Issue by piersjonesprivate** [instaloader/instaloader#745]
Hello! I found documentation to include post caption, but I can't get IGTV title to work. 
The title is in the post JSON as name 'title', but both {post.title} and {title} result in an error. I think if this is not possible, it's an omission!

**Comment by Deleora** [comment]
I think it's possible, but you might have to change the code. It might not be possible through terminal.

**Comment by Thammus** [comment]
The [Post class](https://instaloader.github.io/module/structures.html#posts) of Instaloader does indeed not have a `title` property, but feel free to implement it.
