### ISSUE TITLE
Foreign letters support

### ISSUE THREAD

**Issue by myangelaku** [instaloader/instaloader#748]
**Describe the bug**
I'm not too sure about whether this is an issue at my end or at the end of Instaloader as this is my first time using foreign letters in cmd, but I think that Instaloader doesn't support foreign letters.

**To Reproduce**
```
G:\public_archives\Instagram>instaloader "#汉语"
#??: Invalid hashtag #??

Errors or warnings occurred:
#??: Invalid hashtag #??

G:\public_archives\Instagram>instaloader "#брух"
#????: Invalid hashtag #????

Errors or warnings occurred:
#????: Invalid hashtag #????

G:\public_archives\Instagram>
```

Basically simply using foreign letters. I tried with Korean, Russian, Chinese and Japanese. 

**Expected behavior**
Obviously it should look for posts under the hashtags, even if they contain foreign letters

**Error messages and tracebacks**
As seen above

**Instaloader version**
4.4.5, installed today so it should be the most recent one.

**Additional context**
-
![firefox_LQSwFtanfH](https://user-images.githubusercontent.com/28674643/88974050-516af180-d2b8-11ea-9e18-0755d2059323.png)

**Comment by Deleora** [comment]
I'm using version 4.4.2 and `instaloader "#汉语"` seems to be working fine for me.
It might be some issue in later versions OR
I see in the image that you have given `"#6 p y x"` which is of course not a valid hashtag.
First I tried `instaloader "#брух"` which worked as usual:

> E:\Temp>instaloader "#брух"
#брух/2019-06-10_02-56-53_IST_profile_pic.jpg
Retrieving pictures with hashtag #брух...
[  1] #брух/2020-07-25_21-29-17_IST.jpg [Our vows are no longer vows, …]
Interrupted by user.

but when I gave spaces between the characters like you, I got the error:

> E:\Temp>instaloader "#б р у х"
#б р у х: Invalid hashtag #б р у х
> 
> Errors occurred:
#б р у х: Invalid hashtag #б р у х

**Comment by myangelaku** [comment]
> but when I gave spaces between the characters like you, I got the error:

Actually, those aren't spaces in the first place, it just looks like it because of the shell (I used a WIN+R thing to open a Chinese one)

`C:\Users\Eshkere>instaloader "#вцыыв"
#?????: Invalid hashtag #?????

Errors or warnings occurred:
#?????: Invalid hashtag #?????

C:\Users\Eshkere>`

This is what happens in a normal one

**Comment by Deleora** [comment]
Well. there doesn't seem to be any error in the command. Though the hashtag `вцыыв` doesn't exist. You may check that by navigating to [https://www.instagram.com/explore/tags/вцыыв/](https://www.instagram.com/explore/tags/%D0%B2%D1%86%D1%8B%D1%8B%D0%B2/) web-page.

I would suggest to uninstall and reinstall Instaloader. If that also doesn't help it might have something to do with your system because I'm using a lower version and not getting any such error.
OR
Wait for contributors to respond.

When I executed `instaloader "#вцыыв"` I got following output:

```
E:\Temp>instaloader "#вцыыв"
JSON Query to explore/tags/вцыыв/: 404 Not Found [retrying; skip with ^C]
JSON Query to explore/tags/вцыыв/: 404 Not Found [retrying; skip with ^C]
Get hashtag #вцыыв: JSON Query to explore/tags/вцыыв/: 404 Not Found

Errors occurred:
Get hashtag #вцыыв: JSON Query to explore/tags/вцыыв/: 404 Not Found
```

**Comment by myangelaku** [comment]
>  Though the hashtag `вцыыв` doesn't exist
That doesn't matter as my Instaloader seems to acknowledge foreign letters in general just as ?'s

```
C:\Users\Eshkere>instaloader "#блять"
#?????: Invalid hashtag #?????

Errors or warnings occurred:
#?????: Invalid hashtag #?????

C:\Users\Eshkere>
```



> If that also doesn't help it might have something to do with your system
Yep, that's what I am suspecting now... Still; I hope I'll be able to get help here

**Comment by aandergr** [comment]
I cannot reproduce this error. I have tried downloading "#汉语" with our v4.4.5 Windows standalone exe, executed both from within PowerShell and CMD on Windows [Version 10.0.19041.388], and it works without any problems.

So I have no clue. How did you install Instaloader? Which Python version do you use? Is it Windows 10? Which terminal do you use to start Instaloader? Does the standalone exe work for you?

**Comment by myangelaku** [comment]
First off, I get the same issues in PowerShell, but I also tried with cmd and other shells..
I installed Instaloader over pip, I have Python 3.9.0b5 
> Does the standalone exe work for you?

After typing `chcp 65001`, it works with the standalone .exe 
No idea what caused it, but I guess my issue is fixed.

Thanks!
