### ISSUE TITLE
Too many queries in the last time

### ISSUE THREAD

**Issue by Neurotoxin001** [instaloader/instaloader#750]
**Describe the bug**
After only 20 downloaded videos from my "saved" I got limit with message:
`Too many queries in the last time. Need to wait 630 seconds`

**To Reproduce**
1. save 22+ videos in instagram
2. run `instaloader --login your_nick --no-pictures --no-captions --no-metadata-json --no-compress-json :saved`

**Error messages and tracebacks**
`Too many queries in the last time. Need to wait 630 seconds`

**Instaloader version**
4.4.5

**Additional context**
If I remove a few videos from my "saved" on instagram and restart loader all remaining videos is downloading fine without any limits

**Comment by Thammus** [comment]
["Too many queries in the last time"](https://instaloader.github.io/troubleshooting.html#too-many-queries-in-the-last-time) is not a bug. It is a notice that the rate limit has almost been reached, according to Instaloader’s own rate accounting mechanism.

[Instaloader 4.5](https://github.com/instaloader/instaloader/releases/tag/v4.5) uses a weaker limiting of the queries and allows to more easily override the rate controlling behavior.
