### ISSUE TITLE
The command --dirname-pattern={profile} is giving an error in v4.5

### ISSUE THREAD

**Issue by adamkkkkkk** [instaloader/instaloader#751]
**Describe the bug**
The `--dirname-pattern={profile}` command is supposed to sort downloaded images into folders with the name of the profile's username from which it was downloaded. In the v4.5 update, this command now gives an error.

**To Reproduce**
Using the `--dirname-pattern={profile}` command will give you the error.

**Expected behavior**
Sort downloaded images into folders with the name of the profile's username from which it was downloaded.

**Error messages and tracebacks**
`instaloader.exe: error: unrecognized arguments: -encodedCommand cAByAG8AZgBpAGwAZQA= -inputFormat xml -outputFormat text`

[Screenshot](https://i.imgur.com/yCXjM9T.jpg)

**Instaloader version**
4.5

**Additional context**
In the above screenshot, I try again without using the `--dirname-pattern={profile}` command and everything works as intended.

**Comment by aandergr** [comment]
This is due to how [PowerShell](https://docs.microsoft.com/en-us/powershell/) processes a command.

Simply put at least `{profile}` in quotes, i.e.
```
.\instaloader --dirname-pattern="{profile}" ...
```

This has changed with [Version 4.4.4] where we changed Instaloader to start PowerShell instead of legacy CMD.

**Comment by nagualcode** [comment]
Instaloader on linux (and osx), I used to:
--dirname-pattern="{date_utc}"_"{profile}"_"{shortcode}"

After the last update I get:

KeyError: 'date_utc

**Comment by aandergr** [comment]
@nagualcode This has nothing to do with the here-reported problem. Please open a separate issue.
