### ISSUE TITLE
comments extracting from post give KeyError: 'entry_data'

### ISSUE THREAD

**Issue by AhmadTariqAlflahat** [instaloader/instaloader#752]
I use this command
`instaloader -- -B_K4CykAOtf --comments`

to extract the post with the comments that it hold, but it gave me the error 
> `KeyError: 'entry_data'`

the full error is:

`
> Traceback (most recent call last):
>  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
>  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
>  File "C:\Users\user\Desktop\Workspace\venv\Scripts\instaloader.exe\__main__.py", line 7, in <module>
>  File "c:\users\user\desktop\workspace\venv\lib\site-packages\instaloader\__main__.py", line 429, in main
    _main(loader,
>  File "c:\users\user\desktop\workspace\venv\lib\site-packages\instaloader\__main__.py", line 153, in _main
    instaloader.download_post(Post.from_shortcode(instaloader.context, target[1:]), target)
>  File "c:\users\user\desktop\workspace\venv\lib\site-packages\instaloader\structures.py", line 83, in from_shortcode    
    post._node = post._full_metadata
>  File "c:\users\user\desktop\workspace\venv\lib\site-packages\instaloader\structures.py", line 161, in _full_metadata
    self._obtain_metadata()
>  File "c:\users\user\desktop\workspace\venv\lib\site-packages\instaloader\structures.py", line 153, in _obtain_metadata 
    + json.dumps(pic_json['entry_data'], indent=2))
> KeyError: 'entry_data'
`

**Comment by aandergr** [comment]
Welcome to the community! Please see [Reporting Bugs](https://instaloader.github.io/contributing.html#reporting-bugs) for how to report a bug. There is little chance to understand an issue if the requested information is missing.
