### ISSUE TITLE
The command --dirname-pattern={shortcode} is giving an error since 4.4.3

### ISSUE THREAD

**Issue by nagualcode** [instaloader/instaloader#757]
I am using instaloader on Linux and Osx.

The command --dirname-pattern="{shortcode}" is giving an error since 4.4.3

Although --dirname-pattern="{profile}" works.

**Comment by aandergr** [comment]
Please have a look at the documentation. `--dirname-pattern` supports the fields `{profile}` and `{target}`. Using `{shortcode}` in a dirname pattern is not supported.

Note that version 4.4.3 is not the current version of Instaloader. Even on 4.4.x there were two bug-fixing releases after 4.4.3. We recommend to always use the latest version to get the best bug-free experience.

Further, this has absolutely nothing to do with version 4.4.3 itself. As clearly denoted in the [release notes](https://github.com/instaloader/instaloader/releases/v4.4.3) of that particular version, there were *no changes for non-Windows systems*. A look at the [changes between v4.4.3 and v4.4.4](https://github.com/instaloader/instaloader/compare/v4.4.2...v4.4.3) gives more details about that.

**Comment by nagualcode** [comment]
What I wanted to say was: shortcode used to work on --dirname-pattern, up until to 4.4.2.
