### ISSUE TITLE
Can't download only videos with --no-pictures from post with 2+ videos

### ISSUE THREAD

**Issue by Neurotoxin001** [instaloader/instaloader#763]
**Describe the bug**
When I trying to download videos from post with 2+ videos there is nothing is downloading if I use `--no-pictures` command

**To Reproduce**
1. Try to download this https://www.instagram.com/p/CDpWTbOlU-T/ with `instaloader --login your_nick --no-pictures --no-captions --no-metadata-json --no-compress-json :saved`
2. You can't until you remove `--no-pictures` command (instaloader just skips that post)
3. Without `--no-pictures` there is 3 images is downloading but I only need a videos

**Expected behavior**
All videos must be downloaded from post with multiple videos even with `--no-pictures` command

**Instaloader version**
4.4.5

**Comment by Thammus** [comment]
Thank you for reporting this bug. It is indeed unintended that sidecars with videos are skipped if `--no-pictures` is used.

**Comment by aandergr** [comment]
Fixed in [Version 4.5.1](https://github.com/instaloader/instaloader/releases/tag/v4.5.1).
