### ISSUE TITLE
Requesting for large follower sets

### ISSUE THREAD

**Issue by Obinnn** [instaloader/instaloader#770]
I have attempted to write a script that utilises the Instaloader python module to fetch followers from profiles that have very large follower numbers. I have encountered an issue with my attempt, and I am wondering if anyone might be able to help me understand what is going wrong and how to mitigate the issue.

Is my result (shown bellow) to be expected when targeting such a large list of followers with Instaloader? If so, Is there an advised limit to the number of same type requests one should make in one session? And if there is something inherently problematic with fetching large volumes of followers from any one profile, can anyone advise me on any possible workarounds?

My code is as follows:

```
# Please note that TARGET, USERNAME & FILENAME are placeholders for the real values that I use.
# Please note that I have also removed some irrelevant code (except blocks etc.) for simplicity.

import json
import instaloader

target_username = TARGET

record = {"Username": target_username, "ID": "", "Followers": []}

loader = instaloader.Instaloader()
profile = instaloader.Profile.from_username(loader.context, target_username)

target_id = str(profile.userid)
record["ID"] = target_id

loader.load_session_from_file(USERNAME, filename=FILENAME)

try:
	for follower in profile.get_followers():
		record["Followers"].append(str(follower.userid))
	
finally:
	loader.save_session_to_file(filename=FILENAME)

	with open("export/" + target_id + "_" + date + ".json", "w") as export:
		json.dump(record, export)
```

I ran this script to fetch followers from a profile that had roughly 37543 followers at the time. I ran the script remotely with pythonanywhere.com. The script ran successfully until it was able to fetch 35723 of the 37543 followers. At this point, however, "QueryReturnedBadRequestException: 400 Bad Request" was thrown.

The output of the above script was as follows. Please keep in mind that I have inserted some generic placeholder words here again (and also removed my Python Anywhere username from each path that was printed).

> Loaded session from FILENAME.
> Too many queries in the last time. Need to wait 358 seconds, until 06:19.
> Too many queries in the last time. Need to wait 325 seconds, until 06:30.
> Too many queries in the last time. Need to wait 19 seconds, until 06:34.
> Too many queries in the last time. Need to wait 300 seconds, until 06:41.
> HTTP Error 400 (Bad Request) on GraphQL Query. Retrying with shorter page length.
> HTTP Error 400 (Bad Request) on GraphQL Query. Retrying with shorter page length.
> Saved session to FILENAME.
> Traceback (most recent call last):
>   File "/home/-/.local/lib/python3.8/site-packages/instaloader/nodeiterator.py", line 96, in _query
>     self._context.graphql_query(
>   File "/home/-/.local/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 418, in graphql_query
>     resp_json = self.get_json('graphql/query',
>   File "/home/-/.local/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 335, in get_json
>     raise QueryReturnedBadRequestException("400 Bad Request")
> instaloader.exceptions.QueryReturnedBadRequestException: 400 Bad Request
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/-/.local/lib/python3.8/site-packages/instaloader/nodeiterator.py", line 96, in _query
>     self._context.graphql_query(
>   File "/home/-/.local/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 418, in graphql_query
>     resp_json = self.get_json('graphql/query',
>   File "/home/-/.local/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 335, in get_json
>     raise QueryReturnedBadRequestException("400 Bad Request")
> instaloader.exceptions.QueryReturnedBadRequestException: 400 Bad Request
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/-/project/main.py", line 23, in <module>
>     for follower in profile.get_followers():
>   File "/home/-/.local/lib/python3.8/site-packages/instaloader/nodeiterator.py", line 129, in __next__
>     query_response = self._query(self._data['page_info']['end_cursor'])
>   File "/home/-/.local/lib/python3.8/site-packages/instaloader/nodeiterator.py", line 108, in _query
>     return self._query(after)
>   File "/home/-/.local/lib/python3.8/site-packages/instaloader/nodeiterator.py", line 108, in _query
>     return self._query(after)
>   File "/home/-/.local/lib/python3.8/site-packages/instaloader/nodeiterator.py", line 96, in _query
>     self._context.graphql_query(
>   File "/home/-/.local/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 418, in graphql_query
>     resp_json = self.get_json('graphql/query',
>   File "/home/-/.local/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 335, in get_json
>     raise QueryReturnedBadRequestException("400 Bad Request")
> instaloader.exceptions.QueryReturnedBadRequestException: 400 Bad Request

I ran no further scripts that queried Instagram for roughly the next 24 hours that followed the above result. After this approx. 24 hour period, I attempted to login to my Instagram user account with the Python module again, which threw a ConnectionException and resulted in the following output:

> Traceback (most recent call last):
>   File "/home/-/project/login.py", line 7, in <module>
>     loader.login(login[0], login[1])
>   File "/home/-/.local/lib/python3.8/site-packages/instaloader/instaloader.py", line 483, in login
>     self.context.login(user, passwd)
>   File "/home/-/.local/lib/python3.8/site-packages/instaloader/instaloadercontext.py", line 236, in login
>     raise ConnectionException("Login: Checkpoint required. Point your browser to "
> instaloader.exceptions.ConnectionException: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge/XXXXXXXXXXX/XXXXXXXXXX/ - follow the instructions, then retry.

On following the output checkpoint link, I was advised that unusual activity was noticed from my account, and was instructed to complete a reCAPTCHA challenge and supply a phone number with which I could receive a confirmation code over SMS.

Any help/insight would be greatly appreciated!

**Comment by Obinnn** [comment]
Hi Thammus, thank you very much for your response.

Upon reading your response, I realise that I miss-worded my initial question slightly. By "session," I meant a sequence of requests made within short succession, not a login session. While I assume your answer to my question remains the same, I just thought I should mention this for clarity.

I now understand that requesting for large sets of data should be possible, so I am wondering if anyone might kindly offer any insights into why I may have encountered this result?

I should mentioned that I proceeded to complete the reCAPTCHA challenge, supply my phone number and relay a pin to revive my account. Once successfully completing this, I was instructed to reset my password and presented with the following notice:

> Your Account Was Compromised
> 
> It looks like you shared your password with a service to help you get more likes or followers, which goes against our Community Guidelines.
> 
> Change your password to continue using Instagram. If you share your new password with one of these services, you may get blocked from following, liking or commenting.

I have reflected on what I might have done wrong to cause the issue, and there are four areas that I can think of.

- Before running the script to fetch the 37K+ followers, I did run one test on a seperate login session (but same account). I waited an hour of time before logging back in save a new session before loading it and proceeding with my script. Would this have been enough to throw Instaloader’s rate limit logic out, causing this result? (Although, I wonder why I wasn’t thrown a 429 response if this is the case?)
- I fetch the user id before logging in with my saved session and proceeding with the requests for followers. Could this be problematic, possibly?
- The account that I used was only very recently created, and I did not conduct any “normal activity” with it before launching straight into this long set of requests. Perhaps this set off some alarm bells?
- My activity was over multiple IP addresses. I created the account locally, but then logged back, saved a login session and ran the script with pythonanywhere.com. Perhaps the response was triggered by this?

I will try to mitigate these points that I have thought of, and will reattempt the script with a new account. 

In the meantime, any further wisdom would be greatly appreciated. Thanks!

**Comment by Thammus** [comment]
As mentioned before, downloading huge amounts of data should not be a problem or trigger any 'unusual activity' detection no matter which account is used or how new it is. Also fetching the userid or creating the profile object before loading the session should not be a problem either. However, using the same session with different IP addresses within short sequence could indeed look suspicious. For Instagram this looks like your account is shared with some people or services, because it is very unlikely that you are in that many different locations in such short time. Thus, your account might be interpreted as compromised.

**Comment by valessiobrito** [comment]
Hello guys, I don't understand if it's possible. However, I would like to export the list of followers. It is possible?
"Export followers" to CSV/txt

**Comment by zecsn** [comment]
Facing the same issue, I have 54k+ followers and it failed after 20k.

**Comment by zecsn** [comment]
Is there any way I can fetch in installments? First 10k-20k form one account, then next 10k-20k from a different one and so on.

**Comment by Obinnn** [comment]
Thanks for your guidance Thammus.

After reading your advice, I went on to conduct a further trial to see how far I could get. You suggested that activity over different IP addresses, within a short time period, may be the key issue here. Taking this into consideration, I devised a way to conduct all activity from the remote server with the same IP address, from initial account creation to requesting for the set of followers.

The following is a timeline of my actions:

1. I ran a script to create a new account with Selenium from the remote server. For this task, I ensured that my user-agent string matched that of Instaloader. I also verified that the IP address from which I was working remained the same before and after running this script. After successfully creating my new account, I had the script log out by hitting the log out button on the Instagram home page.
 
2. Concerned that the above activity might throw out Instaloader's rate limit handling logic, I decided to wait for over 24 hours before proceeding with the following steps.

3. After more than 24 hours had passed, I verified that I was indeed working from the same IP address with which I created my account over 24 hours earlier.

4. I ran my original python script (as described in previous posts, although modified to print a record for every 1000 followers successfully fetched to the console) to request for a large set of followers. The total follower count of the target account exceeded 1 million. The script ran successfully until 26,126 followers were recorded. At this point, I hit the HTTP 400 Error in the same manner as previous attempts, and the script crashed.

5. To finish up, I checked my IP address one more time and found that it remained the same.

The above trial seems to demonstrate that activity over different IPs is not the key issue here. If this is indeed the case, is there anything else that anyone can see I might be doing wrong?

When running these trials, one odd thing that I have noticed is that Instaloader is able to record very large sets of followers before throwing the "Too many queries in the last time" notice and needing to wait. This is contrary to what I have previously experienced with my use of older versions of Instaloader on other projects. In previous projects, Instaloader has typically pulled itself up and waited after fetching sets of less than 2000 followers. With these recent attempts, however, Instaloader seems to be getting beyond 9000 followers before needing to wait. The following console output from this most recent trial demonstrates this:

> 1000 recorded.
> 2000 recorded.
> 3000 recorded.
> 4000 recorded.
> 5000 recorded.
> 6000 recorded.
> 7000 recorded.
> 8000 recorded.
> 9000 recorded.
> 
> Too many queries in the last time. Need to wait 357 seconds, until 04:14.
> 10000 recorded.
> 11000 recorded.
> 12000 recorded.
> 13000 recorded.
> 14000 recorded.
> 15000 recorded.
> 16000 recorded.
> 17000 recorded.
> 18000 recorded.
> 19000 recorded.
> 
> Too many queries in the last time. Need to wait 317 seconds, until 04:25.
> 20000 recorded.
> 21000 recorded.
> 22000 recorded.
> 23000 recorded.
> 24000 recorded.
> 25000 recorded.
> 26000 recorded.
> HTTP Error 400 (Bad Request) on GraphQL Query. Retrying with shorter page length.
> HTTP Error 400 (Bad Request) on GraphQL Query. Retrying with shorter page length.
> 26126 recorded.

Is Instaloader perhaps not resting frequently enough? It just seems to be fetching data too quickly... It was able to fetch 26,126 followers in less than 25 minutes, which is much faster than anything I have experienced with Instaloader previously.

Any help would be appreciated as always. Thanks!

**Comment by desthalia** [comment]
Hi, I also seem to face the same problem similar @Obinnn. I'm trying to get all the followers from an account with 41k followers using the code from #240 in a vanilla way since I'm trying to get used to Instaloader. The error shows up after fetching 1000 records which seems to be in line with someone in the same issue saying that Instaloader throws Error 429 after 1000 records as a cool down period, but apparently Instaloader actually can fetch all the followers in one go. Now I'm confused, why Error 429 shows up after 1000 records and instead of trying again a few minutes later, it throws Error QueryReturnedBadRequestException: 400 Bad Request similar to Obinnn.

Any help about this issue would be greatly appreciated :")

**Comment by Thammus** [comment]
Thanks for your detailed description of the problem and the extensive testing. It is interesting to see, that a clean invocation of Instaloader with a new account runs into the "HTTP Error 400 (Bad Request)". It does indeed look like Instagram started using some sort of new bot detection algorithm. I suspect that this new detection might be more sophisticated than simply counting the amount of requests per time frame. 

The less frequent waits you noticed could be explained by stronger limiting of the queries in previous versions of Instaloader. It would be interesting to know if more followers (or data in general) can be fetched without getting the Bad Request Error by using a stronger limiting of the queries. Instaloader allows to [adjust the rate controlling behavior](https://instaloader.github.io/module/instaloadercontext.html#ratecontroller) by overriding `count_per_sliding_window()`, for example limiting the amount of queries to 20 per sliding window like it was in Instaloader 4.4:

```python
class MyRateController(instaloader.RateController):
    def count_per_sliding_window(self, query_type):
        return 20

L = instaloader.Instaloader(rate_controller=lambda ctx: MyRateController(ctx))
```

**Comment by s10-steve** [comment]
Same issue here. Returning the 'count_per_sliding_window' setting to 20 doesn't help, I still getting the same error as @Obinnn when trying to get large follower sets (100k+)
> HTTP Error 400 (Bad Request) on GraphQL Query. Retrying with shorter page length

**Comment by ramidzamzam** [comment]
Create randomness in your script.

**Comment by Obinnn** [comment]
> Create randomness in your script.

As in to cause the requests to occur at random intervals?

**Comment by ramidzamzam** [comment]
Yes and add for each X reqs sleep Y time.

**Comment by Zer0v87** [comment]
Having the same issue as @Obinnn 
Instagram has terminated about more than 7+ of my accounts now because of this, and I have not found a solution.

> Create randomness in your script.
> Yes and add for each X reqs sleep Y time.

I tried adding random behaviour by generating a random float in between 1.0 and 5.0 to use as the delay before each query in seconds. For every 200 queries I would furthermore wait about 30 seconds. I was able to retrieve 38900+ queries before the 400 exception. (For comparison, without introducing this random behaviour, I was only able to retrieve 8000+ queries before my account got a 400 error, and got terminated). @ramidzamzam have you got any ideas on how to implement better random behaviour? 

I'm thinking that if X amount of requests exceed Y amount of time, then the account gets flagged. So far, instaloader has a sliding window of 11 minutes, but I'm thinking the sliding window might be multi-hourly, and with count per sliding window in the 10's of thousands (with the random behaviour I used). Of course, I'll need more testing on this.

**Comment by ramidzamzam** [comment]
@Zer0v87 My script is running more than two months now with no issues. Basically, I scheduled it to run twice a day in random time through the day and for random time 2H-4H per session and using the below setting, plus catching TooManyReqException to sleep for random time 20M-30M before retrying.
 
```
# Get instance
class MyRateController(instaloader.RateController):
    def wait_before_query(self, query_type):
        # Get random sleep time
        sleep_per_req = getRandomNumber(20, 40)
        sleep(sleep_per_req)
        return
```

**Comment by joaroque** [comment]
Hey i have a similar issue. Please help me!

**Comment by emailFalcatrua** [comment]
did anyone find a viable solution to this issue? 
Is it possible to gather a list of followers from users with a  large follower set?
