### ISSUE TITLE
429 error on first post retrieval from logged in account, successive attempts also fail

### ISSUE THREAD

**Issue by MrC0D3** [instaloader/instaloader#774]
**Describe the bug**
429 error on first or second attempt at post retrieval from logged in account, even after waiting several minutes or hours between requests. No 429 error when logged out of the account, but account login is necessary to download media from private profiles and for high quality images.

**To Reproduce**
instaloader <target> --no-captions --no-profile-pic --no-metadata-json --no-video-thumbnails --login=xxx --post-filter="date_utc >= datetime(2020, 1, 1)"

Same 429 error if I use my local IP address or switch to a VPN for the account.

**Expected behavior**
Successful download of media that meets criteria

**Error messages and tracebacks**
This error was displayed on the first run from the logged in account. 
```
Loaded session from /Users/xxx/.config/instaloader/session-xxx.
Logged in as xxx.
Stored ID xxx for profile xxx.
Retrieving posts from profile xxx.
[  1/286] <target>/2020-08-15_xxx_UTC.mp4 
[  2/286] JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests [retrying; skip with ^C]
HTTP error code 429 was returned because too many queries occurred in
the last time. Please do not use Instagram in your browser or run
multiple instances of Instaloader in parallel.
The request will be retried in 666 seconds, at 11:54.
GraphQL requests:
  xxx
    last 10 minutes: 1 requests
    last 11 minutes: 1 requests
    last 15 minutes: 1 requests
    last 20 minutes: 1 requests
    last 30 minutes: 1 requests
    last 60 minutes: 1 requests
  other
    last 10 minutes: 1 requests
    last 11 minutes: 1 requests
    last 15 minutes: 1 requests
    last 20 minutes: 1 requests
    last 30 minutes: 1 requests
    last 60 minutes: 1 requests
  iphone
    last 10 minutes: 1 requests
    last 11 minutes: 1 requests
    last 15 minutes: 1 requests
    last 20 minutes: 1 requests
    last 30 minutes: 1 requests
    last 60 minutes: 1 requests
^C[skipped by user]
JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests Unable to fetch high quality image version of <Post xxx>.
```

**Instaloader version**
$ instaloader --version
4.5

**Additional context**

- I reviewed 429 error section on https://instaloader.github.io/troubleshooting.html but although the documentation says "Too many queries in the last time is not an error", I'm not able to retrieve any media through the logged in account when this error is displayed and also after waiting the prescribed time
- I reviewed https://github.com/instaloader/instaloader/issues/654 but opened this issue because it was mentioned here https://github.com/instaloader/instaloader/issues/654#issuecomment-669761510:

> Also, these restrictions do not seem to apply for logged-in users. As far as already has been reported, logging in should solve the problem. Do you have problems on your server even if logged-in?

But I am specifically having this issue while logged in. If I log out, I can download media, but I'm not able to download the high quality images because I am not logged in (which is what I am looking for).

**Comment by lapourgagner** [comment]
I think I have a similar issue. Yesterday I've started downloading of about 7k photos, after around 1k, I got this error. I tried with a VPN, it's the same. I've also waited 12 hours and it's also the same.
It's true that I've kept my browser open on IG and maybe reloaded the tab.
I've tried to delete the session file in case the problem is from the session, apparently not.

Maybe new anti-spam measures from IG ?

**Comment by MrC0D3** [comment]
Thanks for commenting, Glad someone else seems to be encountering a similar error while logged in. I also had tried deleting the session file, but received the same error. Looks like some new anti-spam or anti-bot measures to me (not too much experience with Instagram API itself), unless there were some changes on how Instaloader handles this case in version 4.5.

I am planning to wait a full 24 hours before my last attempt yesterday, and also try a different user agent, to see if I'm able to start downloading again. I'll post later today on how it goes.

**Comment by lapourgagner** [comment]
It's now about 24 hours for me and it seems to work.
But I'm afraid that some posts were skipped yesterday, I've added `--max-connection-attempts 0` this time.

I hope I was ban bc i was also connected in browser...

**Comment by schleeb** [comment]
I believe I've encountered this as well. After logging out of all other instances, and waiting the night, I was able to start up today, but eventually it hit the issue again. From previous attempts, it looked like it won't redo "lower quality" versions (e.g. it won't get the 1440 pics if it grabbed a 1080), which is also really annoying!

Looking at the GraphQL requests after encountering an issue:
```
GraphQL requests:
  d6f4427fbe92d846298cf93df0b937d3
    last 10 minutes: 0 requests
    last 11 minutes: 0 requests
    last 15 minutes: 0 requests
    last 20 minutes: 0 requests
    last 30 minutes: 0 requests
    last 60 minutes: 0 requests
  other
    last 10 minutes: 0 requests
    last 11 minutes: 0 requests
    last 15 minutes: 0 requests
    last 20 minutes: 0 requests
    last 30 minutes: 0 requests
    last 60 minutes: 0 requests
  iphone
    last 10 minutes: 66 requests
    last 11 minutes: 72 requests
    last 15 minutes: 102 requests
    last 20 minutes: 136 requests
    last 30 minutes: 276 requests
    last 60 minutes: 830 requests
  e31a871f7301132ceaab56507a66bbb7
    last 10 minutes: 1 requests
    last 11 minutes: 1 requests
    last 15 minutes: 1 requests
    last 20 minutes: 1 requests
    last 30 minutes: 4 requests
    last 60 minutes: 17 requests
  2b0673e0dc4580674a88d426fe00ea90
    last 10 minutes: 5 requests
    last 11 minutes: 5 requests
    last 15 minutes: 9 requests
    last 20 minutes: 10 requests
    last 30 minutes: 40 requests
    last 60 minutes: 184 requests
```
I'm interpreting those each as sessions making requests, but I don't even have an iphone, and I was logged out of all other sessions. I've since logged in and kicked any existing session that showed, but they all traced back to me, so no one else was logged in as me...

Confusing and annoying, to say the least, particular since I don't see an easy way to get the higher res versions to replace the lower res fallbacks.

**Comment by lapourgagner** [comment]
Well, some news of mine, I just remember my IP is kinda shared and maybe other people are on IG on my IP but not in my IG account. In this case, I don't think ban algorithm evolve...

Does anyone knows if it is possible to be blocked by IP or by account or both ? Last question: Does anyone knows if it is possible to slow down request flow to allow using instaloader in public WiFi for example ?

**Comment by corsair99** [comment]
im also hitting a wall after my first grab, had zero issues before then. logged in. no other users on network. 

seems like an auto block. i waited all day and can still use my account but then waiting and trying instaloader trips something and it doesn't work anymore. im not banned from my account but i had to change my password and stop using this til people are in the clear

**Comment by lapourgagner** [comment]
But yesterday, when I was ban to download, I was still able to use IG on my phone.

**Comment by MrC0D3** [comment]
Update from my side: After waiting 24 hours, I've been able to log in and download at least a few hundred images/videos from different profiles while logged in. At this point it does seem like some type of auto-block, I haven't yet encountered another block. I'd like to try again with a higher number of images/videos to see if I get blocked again.

While I was banned, though, I was also able to access IG from my browser, so the ban doesn't seem to be on the account. The ban seems to be with some way that Instaloader is fetching the media to download (from my understanding, I could be wrong).

**Comment by schleeb** [comment]
Building on what everyone is saying, I was never prevented from logging into my account via browser or Android app, but I couldn't get the higher-res pictures - this included via MaxURL, which seemed to indicate it too hit the 429 response. After giving it several hours, I was able to grab the URLs via MaxURL; presumably I could get them via Instaloader, but it would likely hit the limit again quickly. Still, perhaps small batches w/ use of "Pause" will help mitigate it, temporarily.

**Comment by MrC0D3** [comment]
Looks like I ran into the 429 error today after a few hundred requests, below is an example output. Instaloader was not running in parallel and Instagram was not accessed via browser during this time.

```
JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests [retrying; skip with ^C]
HTTP error code 429 was returned because too many queries occurred in
the last time. Please do not use Instagram in your browser or run
multiple instances of Instaloader in parallel.
GraphQL requests:
  xxx
    last 10 minutes: 0 requests
    last 11 minutes: 0 requests
    last 15 minutes: 0 requests
    last 20 minutes: 0 requests
    last 30 minutes: 0 requests
    last 60 minutes: 1 requests
  other
    last 10 minutes: 0 requests
    last 11 minutes: 0 requests
    last 15 minutes: 0 requests
    last 20 minutes: 0 requests
    last 30 minutes: 0 requests
    last 60 minutes: 30 requests
  iphone
    last 10 minutes: 79 requests
    last 11 minutes: 86 requests
    last 15 minutes: 139 requests
    last 20 minutes: 204 requests
    last 30 minutes: 374 requests
    last 60 minutes: 598 requests
  xxx
    last 10 minutes: 5 requests
    last 11 minutes: 5 requests
    last 15 minutes: 6 requests
    last 20 minutes: 9 requests
    last 30 minutes: 73 requests
    last 60 minutes: 82 requests
  xxx
    last 10 minutes: 5 requests
    last 11 minutes: 8 requests
    last 15 minutes: 33 requests
    last 20 minutes: 63 requests
    last 30 minutes: 71 requests
    last 60 minutes: 146 requests
JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests Unable to fetch high quality image version of <Post xxx>.

```

**Comment by aandergr** [comment]
Version 4.5.2 adjusts the rate controlling mechanism to reduce the number of 429 responses.

**Comment by spetztest** [comment]
currently on 4.5.3 now and it is the same. but i was in 4.3.3 before when it started, now I have to wait for i think 24hrs

**Comment by MrC0D3** [comment]
Thanks for updating @aandergr, I'm on version 4.5.2 and it seems to partially solve the issue, I can go longer downloading images from a logged in session but I do still inevitably hit the 429 error after several hundred requests. I suppose to entirely avoid the issue I will have to go with multiple accounts and proxies.

**Comment by aandergr** [comment]
Thanks for trying out 4.5.2. It's a little frustrating that the 429 problem still occurs despite our change. When the 429 is happening, Instaloader automatically retries the failing request a few times. What has been the result of these retries? Also, could you please share Instaloader's error output with the request counts?

**Comment by MrC0D3** [comment]
I'm retrying Instaloader after a couple of days so I'll see if the problem is getting better. I don't have the error output from before but if I encounter the error again I will update here. My main use case is to download from different profiles so I have added a 10 minute sleep between downloads to see if that changes things too.

What had happened earlier was that Instaloader would retry a few more times and returned more 429. Eventually it started to return 400 Bad Request, which made me thought I had got banned or something, but I logged into Instagram via browser and was presented the Security Challenge. I completed that, and now Instaloader is working again.

**Comment by MrC0D3** [comment]
Here is the 429 error:

```
JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
   d6f4427fbe92d846298cf93df0b937d3:    1    1    1    1    1    1
                              other:    1    1    1    1    1    1
 *                           iphone:   24   24   24   24   24   24
   472f257a40c653c64c666ce877d59d2b:    1    1    1    1    1    1
   2b0673e0dc4580674a88d426fe00ea90:    4    4    4    4    4    4
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 612 seconds, at 20:51.
JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
   d6f4427fbe92d846298cf93df0b937d3:    0    0    1    1    1    1
                              other:    0    0    1    1    1    1
 *                           iphone:    1   22   25   25   25   25
   472f257a40c653c64c666ce877d59d2b:    0    1    1    1    1    1
   2b0673e0dc4580674a88d426fe00ea90:    0    4    4    4    4    4
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 8 seconds, at 20:51.
JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests Unable to fetch high quality image version of <Post CDZ16qNpE6->.
[ 29/174] graceboor/2020-08-02_22-31-48_UTC.jpg 
JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
   d6f4427fbe92d846298cf93df0b937d3:    0    0    1    1    1    1
                              other:    0    0    1    1    1    1
 *                           iphone:    3   19   27   27   27   27
   472f257a40c653c64c666ce877d59d2b:    0    1    1    1    1    1
   2b0673e0dc4580674a88d426fe00ea90:    1    5    5    5    5    5
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 6 seconds, at 20:51.
```

This continues for a while, but I CTRL+C'd out of the script.

**Comment by aandergr** [comment]
We did some intensive own experiments and updated the rate controller once again for version 4.5.3. Thanks for pointing out that there was something wrong.

**Comment by spetztest** [comment]
oh yeah!!! 😀 time to test again.

**Comment by MrC0D3** [comment]
I appreciate the update, I will give it another shot in the next couple days and update here on the results.

**Comment by MrC0D3** [comment]
Gave it a try overnight, seemed to encounter a similar 429 error:

```
$ instaloader --version
4.5.3

```
```
JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
   d6f4427fbe92d846298cf93df0b937d3:    0    0    1    1    1    1
                              other:    0    0    1    1    1    1
 *                           iphone:   43   72  117  117  117  117
   472f257a40c653c64c666ce877d59d2b:    1    2    3    3    3    3
   2b0673e0dc4580674a88d426fe00ea90:    1    1    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 7 seconds, at 15:20.
JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
   d6f4427fbe92d846298cf93df0b937d3:    0    0    1    1    1    1
                              other:    0    0    1    1    1    1
 *                           iphone:   43   68  118  118  118  118
   472f257a40c653c64c666ce877d59d2b:    1    2    3    3    3    3
   2b0673e0dc4580674a88d426fe00ea90:    0    1    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 7 seconds, at 15:20.
JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests Unable to fetch high quality image version of <Post B8RaLTCATVu>.
[127/561] xxx/2020-02-07_16-15-43_UTC.jpg 
JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
   d6f4427fbe92d846298cf93df0b937d3:    0    0    1    1    1    1
                              other:    0    0    1    1    1    1
 *                           iphone:   45   64  120  120  120  120
   472f257a40c653c64c666ce877d59d2b:    1    2    3    3    3    3
   2b0673e0dc4580674a88d426fe00ea90:    0    1    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 9 seconds, at 15:20.
JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
   d6f4427fbe92d846298cf93df0b937d3:    0    0    1    1    1    1
                              other:    0    0    1    1    1    1
 *                           iphone:   46   60  121  121  121  121
   472f257a40c653c64c666ce877d59d2b:    1    1    3    3    3    3
   2b0673e0dc4580674a88d426fe00ea90:    0    1    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 7 seconds, at 15:20.
JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests Unable to fetch high quality image version of <Post B8Pp-kVAH2m>.
[128/561] xxx/2020-02-06_23-55-18_UTC.jpg 
JSON Query to api/v1/media/2235979998928425354/info/: 429 Too Many Requests [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
   d6f4427fbe92d846298cf93df0b937d3:    0    0    1    1    1    1
                              other:    0    0    1    1    1    1
 *                           iphone:   48   57  123  123  123  123
   472f257a40c653c64c666ce877d59d2b:    1    1    3    3    3    3
   2b0673e0dc4580674a88d426fe00ea90:    0    1    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 7 seconds, at 15:20.
JSON Query to api/v1/media/2235979998928425354/info/: 429 Too Many Requests [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
   d6f4427fbe92d846298cf93df0b937d3:    0    0    1    1    1    1
                              other:    0    0    1    1    1    1
 *                           iphone:   49   55  124  124  124  124
   472f257a40c653c64c666ce877d59d2b:    1    1    3    3    3    3
   2b0673e0dc4580674a88d426fe00ea90:    0    1    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 6 seconds, at 15:20.
JSON Query to api/v1/media/2235979998928425354/info/: 429 Too Many Requests Unable to fetch high quality image version of <Post B8Hy_ZZAdGK>.
[129/561] xxx/2020-02-03_22-40-08_UTC.jpg 
JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
   d6f4427fbe92d846298cf93df0b937d3:    0    0    1    1    1    1
                              other:    0    0    1    1    1    1
 *                           iphone:   51   51  126  126  126  126
   472f257a40c653c64c666ce877d59d2b:    1    1    3    3    3    3
   2b0673e0dc4580674a88d426fe00ea90:    0    0    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 488 seconds, at 15:29.
JSON Query to api/v1/media/xxx/info/: 429 Too Many Requests [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
   d6f4427fbe92d846298cf93df0b937d3:    0    0    0    0    1    1
                              other:    0    0    0    0    1    1
 *                           iphone:   29   49   74  121  127  127
   472f257a40c653c64c666ce877d59d2b:    1    1    2    3    3    3
   2b0673e0dc4580674a88d426fe00ea90:    0    0    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 9 seconds, at 15:29.
```

This continued for a while but I exited with CTRL+C.

**Comment by aandergr** [comment]
> I have added a 10 minute sleep between downloads to see if that changes things too.

Did you do that by extending the rate controller to somehow detect a profile query to a new profile and wait in that case? Or outside of Instaloader, and if so, do you maintain the Instaloader instance? Would you mind sharing more details about how you implemented the 10 minute sleep between downloads?

**Comment by Kikiss18** [comment]
Hello aandergr, 

I have a similar error. "429 too many requests unable to fetch high-quality image."
Please found attached my screenshot.  I hope it can help. Thx!

![Scr-error-Instagram](https://user-images.githubusercontent.com/58808904/92970367-d849e700-f47e-11ea-80e5-41424412bec5.jpg)

**Comment by LouisVA** [comment]
I can literally not download anything:

> JSON Query to api/v1/media/2476648287284918078/info/: HTTP error code 403. [retrying; skip with ^C]
> JSON Query to api/v1/media/2476648287284918078/info/: HTTP error code 403. [retrying; skip with ^C]
> JSON Query to api/v1/media/2476648287284918078/info/: HTTP error code 403. Unable to fetch high quality image version of <Post CJe0n7VMnc->.
>  somfilepath unchanged
> HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
> JSON Query to graphql/query: Redirected to login [retrying; skip with ^C]
> Requests within last 10/11/20/22/30/60 minutes grouped by type:
>                               other:    1    1    1    1    1    1
>                              iphone:    3    3    3    3    3    3
>    2b0673e0dc4580674a88d426fe00ea90:    1    1    1    1    1    1
>  * 97b41c52301f77ce508f55e66d17620e:    1    1    1    1    1    1
> Instagram responded with HTTP error "429 - Too Many Requests". Please
> do not run multiple instances of Instaloader in parallel or within
> short sequence. Also, do not use any Instagram App while Instaloader
> is running.
> The request will be retried in 666 seconds, at 13:24.
