### ISSUE TITLE
instaloader.exceptions.QueryReturnedBadRequestException: 400 Bad Request

### ISSUE THREAD

**Issue by axeldotjara** [instaloader/instaloader#780]
Hi,

Someone can help me with this issue plz, i dont know why this happend. 

This is the error, 

![image](https://user-images.githubusercontent.com/65202743/90715614-bc389880-e278-11ea-9d5a-c487f65b9c42.png)

And here is my code. 

`from datetime import datetime
from itertools import dropwhile, takewhile
import sys
import instaloader

sys.setrecursionlimit(10**8)

import instaloader

L = instaloader.Instaloader(sleep=None,
                            quiet=None,
                            user_agent=None,
                            #dirname_pattern=, # diectorio
                            filename_pattern="{profile};{date_utc}", # archivo
                           #filename_pattern=None,
                            download_pictures=True,
                            download_videos=None,
                            download_video_thumbnails=None,
                            download_geotags=None,
                            download_comments=True,
                            save_metadata=True, # no creo q sea nesesario extraer json al tener formateado el TXT
                            compress_json=None,  # compresion json
                            #post_metadata_txt_pattern="perfil;{profile}\nfecha;{date}\nmensaje;{caption}\nhashtags;{caption_hashtags}\nmenciones;{caption_mentions}\ne$
                            storyitem_metadata_txt_pattern=None,
                            max_connection_attempts=0,# 0 es infinito
                            #request_timeout=1000000,
                            commit_mode=None)

SINCE = datetime(2019, 9, 1)
UNTIL = datetime(2020, 5, 30)

L.login(credentials)

L.download_location('290640698345736', post_filter=lambda p: SINCE <= p.date <= UNTIL)

`

Any comment help me, thanx.

**Comment by gituzzer** [comment]
Getting 400 Bad Request too. They are detecting that it is not the App downloading data, so they lock the account for security and force a password change.

**Comment by axeldotjara** [comment]
> Getting 400 Bad Request too. They are detecting that it is not the App downloading data, so they lock the account for security and force a password change.

Thnx for your comment, just as you say the account was blocken and instagram requires a second auth step.

**Comment by axeldotjara** [comment]
I have to do new accounts for continue scraping.

**Comment by bugfinder5000** [comment]
Is there any way around this? I'm tired of having to manually "unblock" my 4 accounts every once in a while. I can't create any more new accounts, because it requires mandatory phone number verification now.
