### ISSUE TITLE
Limit number of days in downloading FEEDS

### ISSUE THREAD

**Issue by spetztest** [instaloader/instaloader#782]
How can I limit the number of days for the FEEDS to get downloaded? It seems it is downloading nearly everything, so maybe there is a way or command to download the FEEDS of an IG profile for say 1month only? or for a specific month?

thanks :-)

**Comment by Thammus** [comment]
Our documentation has an example to download [Posts in a Specific Period](https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period). Also, Instaloader can automatically stop downloading after encountering the first already-downloaded picture by using [`--fast-update`](https://instaloader.github.io/cli-options.html?highlight=fast%20update#cmdoption-fast-update).
