### ISSUE TITLE
Save multi-item posts to sub-directory

### ISSUE THREAD

**Issue by M-Watson** [instaloader/instaloader#783]
**Provide us a use case of the feature**
This could potentially be invoked with a new option --multi-pattern

**Describe the solution you'd like**
If --multi-pattern is specified with a pattern then during a download if an album or multi-image post is found a new directory will be created and the mult-image post will be saved into the new directory.

**Describe alternatives you've considered**
This could be a True/False option as well.

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes

**Additional context**
When downloading my own :saved I have a lot that are exercise/yoga positions. If all of the posts images were in one folder it would be easier to sort on my side.

**Comment by Thammus** [comment]
As an alternative, have you considered using `--filename-pattern` to save all posts in their own directory, not only the sidecars? For example `--filename-pattern={date_utc}_UTC/{date_utc}_UTC`.

**Comment by M-Watson** [comment]
I did consider it but thought it might be useful to have the sub-directory only trigger when a post with sidecars exists. A trigger like that could be useful as base code infrastructure for future feature additions as well, some conditional directory format triggers potentially.

**Comment by Thammus** [comment]
The CLI should be kept simple and clear while covering most of the use cases. Providing flags and options for every edge case would unnecessarily bloat the tool. For uncommon use cases like finer tweaking of the target directory, Instaloader can easily be used as a module. Besides, moving sidecar posts into their own sub-directory is a task that could be easily achieved afterwards using a simple script (for example Bash or PowerShell).

**Comment by M-Watson** [comment]
You are right, I was over complicating things. I will close it out.
