### ISSUE TITLE
Please add support for using the command line to download posts from a specific period

### ISSUE THREAD

**Issue by RipMe-Throwaway** [instaloader/instaloader#784]
**Provide us a use case of the feature**
Currently, the only way to download posts from a specific period is to create a custom python script, which is complicated for users with little programming experience, especially if you want to use additional filters that can easily be invoked with the command line but are more complicated to implement within a script.

**Describe the solution you'd like**
I would like to be able to specify a date range for posts to download from an Instagram profile from the command line. Example: "instaloader --startdate(2020,01,01) --enddate(2020,08,26) InstagramProfile" (or whatever the correct syntax for entering the date would be)

**Describe alternatives you've considered**
I have attempted to do this by following the "Advanced Instaloader Examples" documentation, but was not able to implement other filters that can easily be invoked from the command line, such as "--no-videos" and "--no-compress-json".

**If the feature request is accepted, would you be willing to submit a pull request?**
No, due to my lack of programming experience.

**Comment by MrC0D3** [comment]
https://instaloader.github.io/basic-usage.html#filter-posts

date_utc (datetime), date_local (datetime)
Creation timestamp. Since datetime objects can be created inside filter strings, this easily allows filtering by creation date. E.g.:

`instaloader --post-filter="date_utc <= datetime(2018, 5, 31)" target`

**Comment by RipMe-Throwaway** [comment]
> 
> 
> https://instaloader.github.io/basic-usage.html#filter-posts
> 
> date_utc (datetime), date_local (datetime)
> Creation timestamp. Since datetime objects can be created inside filter strings, this easily allows filtering by creation date. E.g.:
> 
> `instaloader --post-filter="date_utc <= datetime(2018, 5, 31)" target`

This is what I was looking for. Thanks to MrC0D3!

**Comment by psonnosp** [comment]
Are there any more help regarding this anywhere except the technical mumbo jumbo linked on that page? Cause I can't get it to work. 
I just want to download stuff after a certain date, like last week, but no matter how I change the example above I can only get it do either download the whole profile or everything before the date I set and I'm out of ideas for ways to combine < and =
