### ISSUE TITLE
Instaloader Stops Working Once New Saved Posts Are Downloaded

### ISSUE THREAD

**Issue by Water-in-Black** [instaloader/instaloader#786]
**Describe the bug**
It downloads the newest posts from my Saved folder and ignores the rest of the older ones that weren't donwloaded yet. Considering "A", "B", "C" and "D" as posts to be downloaded, where "B" and "C" were already downloded to the foler before adding "A" to the list and "D" wasn't downloaded yet, once "A" is added, the download stops on "B". 

**To Reproduce**
python -m instaloader --login=LOGINUSER --filename-pattern={profile}_({mediaid}) --dirname-pattern="FOLDERNAME" --no-metadata-json --no-captions --stories --fast-update :saved

**Error messages and tracebacks**
Loaded session from  C:\Users\USERNAME\AppData\Local\Instaloader\session-USERNAME.
Logged in as LOGINUSER.
Retrieving saved posts...
[   1/3943] "IMAGENAME".jpg
[   2/3943] "IMAGENAME".jpg "FOLDERNAME"\"IMAGENAME".mp4
exists
Saved session to C:\Users\USERNAME\AppData\Local\Instaloader\session-USERNAME.

C:\Users\USERNAME \Downloads>pause
Press any key to continue . . .

**Instaloader version**
Version 4.5.2

**Additional context**
I have tried deleting the folder's content and beginning it from zero and it works too. Once there are too many posts to be downloaded and I've already downloaded half of it, I would like to continue from where I stopped. I'm far away from being a programmer. Sorry for any misunderstandings.

**Comment by aandergr** [comment]
This is exactly the behavior to be expected with [`--fast-update`](https://instaloader.github.io/cli-options.html#cmdoption-fast-update), isn't it?

> For each target, stop when encountering the first already-downloaded picture.

**Comment by Water-in-Black** [comment]
> This is exactly the behavior to be expected with [`--fast-update`](https://instaloader.github.io/cli-options.html#cmdoption-fast-update), isn't it?
> 
> > For each target, stop when encountering the first already-downloaded picture.

Yes! That is the expected behavior indeed. The issue I'm having is the following:
- I run the command to download my :saved posts
- Before it is finnished, I terminate it (I have a LOT of saved posts)
- When I run the command again, it stops on the first one, instead of resuming where it stoped last time

Maybe I can "sort by oldest" or something similar?

**Comment by aandergr** [comment]
I cannot reproduce the described bug.
