### ISSUE TITLE
Change download directory for media when in with Python Module

### ISSUE THREAD

**Issue by itisyeetimetoday** [instaloader/instaloader#788]
In the python module, when, I use the download media example from the documentation. `			for post in profile.get_posts():
				L.download_post(post, target=profile.username)`. In the command line interface, a flag exists for specifying the download directory, but in the python documentation, I could not find an example about how to specify the download directory when using the python module. Does anyone know how to specify the download directory in the python module?

**Comment by aandergr** [comment]
Duplicate of #502.
