### ISSUE TITLE
How long until 429 "Too many Request' error passes?

### ISSUE THREAD

**Issue by itisyeetimetoday** [instaloader/instaloader#790]
Currently, I just ran into a 429 error, after downloading 300 images, stopping, and making some modifications to my code and resuming, and repeating that list a couple of times. Currently, as of tomorrow morning, it will be around 16 hrs but does anyone know if the sliding window passes in 12hr, or 24 hr? Also, has anyone observed sliding window for 429 errors? That may sound confusing, but I was wondering if someone gets too many 429 errors in a week or over a certain time period, can they get banned temporarily from all requests, or even banned permanently?

**Comment by gituzzer** [comment]
Limit is 500 every 24hrs from personal experience from when the first pic was downloaded, counting towards that limit. 
Change was made by insta a few years ago.

**Comment by itisyeetimetoday** [comment]
> Limit is 500 every 24hrs from personal experience from when the first pic was downloaded, counting towards that limit.
> Change was made by insta a few years ago.

Thanks for the advice. Does instaloader rate limit so that only 500 can be downloaded in a day?

**Comment by MrC0D3** [comment]
See #774 for some discussion on the 429 rate limit, Instaloader has its own mechanisms for rate handling and Instagram also has its own rate limits.

Most recent version 4.5.3 has some changes to how the rate handling works, I'm trying it out and will update that issue in the next few days.

**Comment by aboutqx** [comment]
it works after 20 minutes viz twice try.
