### ISSUE TITLE
How does Instaloader count downloads towards 429 query limit?

### ISSUE THREAD

**Issue by salehio** [instaloader/instaloader#791]
Given that instaloader keeps an internal tracker for number of requests, and given that media seems to be served from the same endpoints as the API (ex: instagram-p3-shv-01-sea1.fbcdn.net), does instaloader count media downloads towards this internal limit?

Taking a quick look at the code, it appears that it doesn't, and instead the get_raw() function will just issue a request without going through the same system that graph queries go through.

Could this be the cause of people hitting the 429s without instaloader being able to throttle itself internally?

**Comment by aandergr** [comment]
Instaloader does not keep track of its requests to these CDN servers, i.e. the media downloads themselves are not counted by Instaloader's internal rate controller. So get_raw() indeed just issues a request without that it is recorded anywhere within Instaloader. 

This behavior is based on the assumption that there is no rate limiting on the servers where the media files are hosted. The domain names of the CDNs are completely different than the domain names of the servers for the GraphQL or iPhone queries.

The 429 problems reported in #774 could be reproduced without doing any request to a CDN server. These were completely explicable by the rate controller being misconfigured regarding the allowed rates of the iPhone queries.
