### ISSUE TITLE
Tips for scraping large amount of media, 24/7

### ISSUE THREAD

**Issue by itisyeetimetoday** [instaloader/instaloader#792]
I have been playing with instaloader for a couple of days, and I've noticed that in built in rate limiter does not seem to work, even with only around 50 request before starting instaloader. To try to combat this, after instaloader scans downloads a profile, even if no media is scraped, I tried to add sleep values. Does anyone recommend any sleep values for 24/7 downloading? I'm currently experimenting with 45 sec, 60 sec, 75 sec, and 90 sec.

**Comment by krisetyafebriandisalomo** [comment]
for me, if it reach limit, i will throw to random time 600-900 s

**Comment by Daquisu** [comment]
You can use try except to ignore that error and keep trying to download. Something like

`
some_loop:
    try:
        download()
    except <<Error when instaloader is scraping too fast>>:
        pass
`

**Comment by Thammus** [comment]
When using [Instaloader as a Python module](https://instaloader.github.io/as-module.html) you should be able to use its [download_*()](https://instaloader.github.io/search.html?q=download_) methods in an endless loop as often as you like. Instaloader keeps track of its requests to Instagram to obey their rate limits. If only using one instance, it should not be necessary to add additional sleeps. However, [Instaloader's rate controlling behavior](https://instaloader.github.io/module/instaloadercontext.html#ratecontroller) can easily be adjusted.

**Comment by itisyeetimetoday** [comment]
Oh interesting. For me though, when downloading multiple profile, I never seen to rate limit for me at least.
