### ISSUE TITLE
How to compose the correct code to download the short link?

### ISSUE THREAD

**Issue by markdrrr** [instaloader/instaloader#793]
My code:
```
from instaloader import *

L = Instaloader()
post = Post.from_shortcode(L.context, 'https://www.instagram.com/p/CEpmU2cjybd/')
L.download_post(post)
```
does not work....

**Comment by Daquisu** [comment]
Use only the shortcode, not the entire URL:


    from instaloader import *
    
    L = Instaloader()
    post = Post.from_shortcode(L.context, 'CEpmU2cjybd')
    L.download_post(post, './Instagram')
