### ISSUE TITLE
Any efficient way to download every saved post of a particular profile?

### ISSUE THREAD

**Issue by DigiOhhh** [instaloader/instaloader#794]
I'm currently using `:saved` in combination with `--post-filter="owner_username == '<someone>'"`.
This way I'm basically checking every saved post in my account against the post filter: having many saved posts, this requires lots of queries. What I'd like to do instead is download every post of _someone_, but only if it's saved in my account: this would need a number of queries equal to the number of posts by _someone_, which at least for me is way better.
I was hoping specifying `<someone>` and `:saved` would result in the desired effect, but it doesn't seem like that's the case.
is this implemented? if there was a post filter like 'is_saved' or something, I could use it by passing `<someone>` to `instaloader` instead of `:saved`.

**Comment by aandergr** [comment]
There is a `viewer_has_saved` field in the JSON response for a Post, however, Instaloader does not expose it as a Post property. Still, there is a hacky way to use it in a post filter:

```
instaloader --login=YOU --post-filter='_full_metadata["viewer_has_saved"]' TARGET
```

**Comment by DigiOhhh** [comment]
Thanks, I'll try it and let you know c:

**Comment by Deleora** [comment]
> There is a `viewer_has_saved` field in the JSON response for a Post, however, Instaloader does not expose it as a Post property. Still, there is a hacky way to use it in a post filter:
> 
> ```
> instaloader --login=YOU --post-filter='_full_metadata["viewer_has_saved"]' TARGET
> ```

By this method we can download saved posts of target profile or only ours?

**Comment by DigiOhhh** [comment]
> Thanks, I'll try it and let you know c:

Works great, thanks again!

**Comment by aandergr** [comment]
> @aandergr By this method we can download saved posts of target profile or only ours?

Only we can see which posts we saved.

> Works great, thanks again!

Nice, glad I could help!

**Comment by DigiOhhh** [comment]
Was this removed recently?
it doesn't seem to work anymore, plus there's no `viewer_has_saved` property in some of the json files I've downloaded.

**Comment by aandergr** [comment]
Strange, it still works for me.

**Comment by DigiOhhh** [comment]
Now both the Windows standalone version and the one I installed via `pip` say:
`Invalid filter: viewer_has_saved not a Post attribute.`

**Comment by aandergr** [comment]
How do you invoke Instaloader, what is the command line?

**Comment by DigiOhhh** [comment]
I've been using PowerShell ever since I switched to Windows.

I just tried Command Prompt and it seems to be working, but every post of `TARGET` are downloaded. This is how I invoke instaloader:
```
instaloader --login=ME -V --no-video-thumbnails --no-captions --no-metadata-json --post-filter='_full_metadata["viewer_has_saved"]' --dirname-pattern="C:\Users\…\Downloads\instagram\{profile}"  TARGET
```

**Comment by aandergr** [comment]
PowerShell seems to require the quotes to be escaped with a `\` when using double quotes within single quotes.

So, instead of `--post-filter='_full_metadata["viewer_has_saved"]'`, use `--post-filter='_full_metadata[\"viewer_has_saved\"]'` and then it works. Alternatively, you can use singles quotes inside double quotes: `--post-filter="_full_metadata['viewer_has_saved']"`,

**Comment by DigiOhhh** [comment]
k, it's working now. Thank you!
