### ISSUE TITLE
:stories: JSON Query to graphql/query: HTTP error code 500

### ISSUE THREAD

**Issue by clublek** [instaloader/instaloader#795]
**Describe the bug**
After using a command to download the most recent stories off my followees. I keep getting this error. The :stories command should use the least amount of API calls i thought....
Also when recreating the session file using the firefox cookies python script it does not help anymore.
Used from here: https://instaloader.github.io/troubleshooting.html#login-error

**To Reproduce**
instaloader -l USERNAME -p PASSWORD :stories --dirname-pattern={profile} --filename-pattern={date} --no-metadata-json --no-captions --fast-update --quiet

**Expected behavior**
To download the most recent visible stories of followees (150 in total, at every command). I'm pausing within the bash script for 10 minutes when invoking the same command again.

**Error messages and tracebacks**
JSON Query to graphql/query: HTTP error code 500. [retrying; skip with ^C]
:stories: JSON Query to graphql/query: HTTP error code 500.

**Instaloader version**
4.5.3

**Comment by clublek** [comment]
Could this probably help? 
https://github.com/arc298/instagram-scraper/issues/585

**Comment by aandergr** [comment]
I just tried the command and it works fine for me.

Error code 500 means [Internal Server Error](https://http.cat/500), a problem on the server side which we cannot fix. If that error appears, Instaloader retries the request a few times, and if it continues to fail, it aborts.

**Comment by clublek** [comment]
the problem is that it never goes correct again, since last week. At every try, I'm getting this error unfortunately :(

**Comment by daprofessa19** [comment]
Hi,

I'm having this same issue when using the :stories argument.

**Comment by clublek** [comment]
@daprofessa19: I'm also having this problem still. How many followees does your account have? Mine is about 7400 at the moment.

**Comment by aleph4** [comment]
The issue here is that Instagram no longer supports 100 user IDs per query, as defined here:

https://github.com/instaloader/instaloader/blob/f4ecfea64cc11efba44cda2b44c8cfe41adbd28a/instaloader/instaloader.py#L580-L589

so things break once the earlier query returns more than 50 available stories.

Reducing userids_per_query to 50 fixes things (for me at least) for now.

@aandergr it's a pretty trivial change, but I can submit a pull request for it if you want.

**Comment by aandergr** [comment]
@aleph4 That is a nice finding! I would appreciate a pull request for it (based on our master branch).
