### ISSUE TITLE
Downloading private insta accounts.

### ISSUE THREAD

**Issue by sayedsaddam** [instaloader/instaloader#796]
Hi, I'm trying to download a private account, I've tried it many times, the scripts runs but doesn't download any data from the account. I wrote the script, provided login credentials, but of no use. I even tried using via the command line.
Will you guys please help me how can I do it?
I can post the script here if you need it.

any help would be highly appreciated.
Regards
Saddam

**Comment by Deleora** [comment]
Please share complete log of the error you are getting. Also let us know what is the exact command you tried to execute (hiding your credentials of course)

**Comment by sayedsaddam** [comment]
Thank you for your response. I've written the script in Python. Here's the snippet.

import instaloader
from instaloader import Instaloader, Profile

L = instaloader.Instaloader()
# L.login('username', 'password')
# Download full profile.
username = 'target_profile'
profile = Profile.from_username(L.context, username)
for post in profile.get_posts():
    L.download_post(post, target=profile.username)
print('Profile has been downloaded!')

**Comment by Deleora** [comment]
The code snippet seems to be fine. I'm able to download any profile I want with it.

Are you sure you follow that 'private account' which you want to download? Because that's a primary condition in this process. If you don't follow that private account, you won't be able to download anything of that account.

**Comment by sayedsaddam** [comment]
Hmm, I'm not following that private account. Isn't there any way to do it without one follows the account ?

**Comment by Deleora** [comment]
No, Instaloader is not a hack tool. If you have access to the account then only you can download them.

**Comment by sayedsaddam** [comment]
OK bro. Thank you for your precious time.

**Comment by mrgravity0** [comment]
which tool can i use to get Instagram password?
