### ISSUE TITLE
Only meta-data options ?

### ISSUE THREAD

**Issue by Kikiss18** [instaloader/instaloader#797]
Hello, 

I have been using Instaloader from Dec 2019 without any problems. Thank you by the way! : ) 

Recently, I have many 429 Errors in the last few months (v 4.5.3). Even if I am really careful about respecting the limits. 
This morning, my account was suspended for the first time.
Seems that Facebook doesn't like Instaloader to download high-quality pictures. 

I am only interested in meta-data (JSON Files of each post). 
I saw the options **--no-pictures** and **--no-videos** in the documentation. 

Is it possible to just download a profile but only meta-data?
Thx!

**Comment by aandergr** [comment]
Hello,

> Is it possible to just download a profile but only meta-data?

With `--no-pictures --no-videos --no-captions --no-profile-pic`, Instaloader only saves JSON files.

> Recently, I have many 429 Errors in the last few months (v 4.5.3). Even if I am really careful about respecting the limits.

That is not so good. Would you mind sharing more details (especially the log output) about these 429 errors in #774?

**Comment by Kikiss18** [comment]
Hello aandergr, 

Thank you for the tip! 
I wrote my log output in the other post. 

Best,
