### ISSUE TITLE
Is it possible to reimport all data in a new account on instagram ?

### ISSUE THREAD

**Issue by easysofts** [instaloader/instaloader#800]
I have use your script to rapidly backup and create a memorial of my instagram account who has hacked yesterday, a hacker demand a ransom and I afraid that he delete my account.

I need to recreate it, 8 years on Instagram deleted... 1900 posts.

I search a solution tu re-import this data (picture,video and captions) on a fresh new IG account ?

I think to use wordpress but I don't now python.
A guy had created a script to import json from Instagram backup :
https://github.com/olind/ig-to-wp/blob/master/wp-content/igtowp.php

instaloader > WP > instagram

Ask
1- is possible to import all data directly on IG ?
2 - Is possible to adapt the script on top to use on Wp ?

Best regards.

**Comment by aandergr** [comment]
> I search a solution tu re-import this data (picture,video and captions) on a fresh new IG account ?

Instaloader does not change any of the online data.

**Comment by easysofts** [comment]
Ok, but backup isn't structured like backup of Instagram app

Screenshot of the official instagram backup structure :
![image](https://user-images.githubusercontent.com/2520158/92991367-aae35480-f4e3-11ea-8a71-304401e3f76c.png)
