### ISSUE TITLE
--fast-update command issue while downloading saved photos of my profile.

### ISSUE THREAD

**Issue by angentanewbe** [instaloader/instaloader#802]
**Describe the bug**
I am trying to download the saved photos on my instagram account to my pc using instaloader. after giving the commands (commnads given below) the instaloader starts downloading the saved posts. In the middle of saving posts my pc restarted due to electricity cut but when I started the instaloader again with the same command it started downloading the posts but after verifying 3 or 4 posts the --fast-update command skips the downloading of all the saved posts. It seems it is verifying 4 posts and then skip all wether the other posts are downloaded in the pc or not,

**To Reproduce**
to reproduce it use the following command

instaloader --login=username --password=password --fast-update :saved

and then download 30 to 40 saved posts then exit the terminal or command. then start the terminal again with the same command it will verify some posts and skip the rest of the posts. session ends.

**Expected behavior**
I expect --fast-update command tp skip only downloaded posts that are in my pc. --fast-update command should be used to verify what is already downloaded on the pc and then instaloader resume downloading the rest of the posts.

**Error messages and tracebacks**
(I replaced my username by "username" for privacy)
instaloader --login=username --password=password --fast-update :saved
Loaded session from C:\Users\Username\AppData\Local\Instaloader\session-username.
Logged in as username.
Retrieving saved posts...
[ 1/43] ：saved\2020-08-17_16-44-02_UTC.jpg exists json
Saved session to  C:\Users\Username\AppData\Local\Instaloader\session-username.

**Instaloader version**
instaloader --version 4.5.3

**Comment by Showmaster3000** [comment]
--fast-update is not intended to support the case you described. It stops the download process if there is a post that has previously been downloaded - as you found out. Just cut --fast-update in your case and download all the things again, 43 posts are not that large block to hit the 429 download limit.

**Comment by angentanewbe** [comment]
> 
> 
> --fast-update is not intended to support the case you described. It stops the download process if there is a post that has previously been downloaded - as you found out. Just cut --fast-update in your case and download all the things again, 43 posts are not that large block to hit the 429 download limit.

Ok. I also tried it with an account having 5000 saved posts and the results are the same. Why there is a limit of 429 posts. I saw 4k stogram downloads the posts just fine regardless of number of posts.

**Comment by Showmaster3000** [comment]
429 means error 429 which is the rate limiting by Instagram if you are too fast requesting data, not a download limit. You can download 5000 posts, but it takes quite a time to finish that.
Have a look at the documentation for error 429: https://instaloader.github.io/troubleshooting.html#too-many-requests

**Comment by angentanewbe** [comment]
> 
> 
> 429 means error 429 which is the rate limiting by Instagram if you are too fast requesting data, not a download limit. You can download 5000 posts, but it takes quite a time to finish that.
> Have a look at the documentation for error 429: https://instaloader.github.io/troubleshooting.html#too-many-requests

Can Instaloader add a feature to support use of multiple accounts at once and automatically follow the profiles when added. So that when one ID get restricted to access more posts then the other ID could be used by the program and thus so on. I think this feature can help a lot because it will set aside the limit of downloads by Instagram. Also is there any way to adopt the method of 4kstogram for downloading posts without limiting downloads. Is it possible to merge the 4kstogram feature of downloading post without limit to the Instaloader.

**Comment by angentanewbe** [comment]
> 
> 
> 429 means error 429 which is the rate limiting by Instagram if you are too fast requesting data, not a download limit. You can download 5000 posts, but it takes quite a time to finish that.
> Have a look at the documentation for error 429: https://instaloader.github.io/troubleshooting.html#too-many-requests

I used it with my ig account to download those 5000 posts but I got 429 error.

**Comment by aandergr** [comment]
> **Expected behavior**
> I expect --fast-update command tp skip only downloaded posts that are in my pc. --fast-update command should be used to verify what is already downloaded on the pc and then instaloader resume downloading the rest of the posts.

As already explained by @Showmaster3000, this is not how [`--fast-update`](https://instaloader.github.io/cli-options.html#cmdoption-fast-update) should behave.

> I used it with my ig account to download those 5000 posts but I got 429 error.

That is not so good. Would you mind sharing more details (especially the log output) about these 429 errors in #774?
