### ISSUE TITLE
Scrape product information from posts

### ISSUE THREAD

**Issue by tetekos** [instaloader/instaloader#803]
There are many posts in mobile apps that tag products along with their names and prices. As far as I am concerned this type of information is not available on a browser but its worth asking if anyone has any idea or managed to scrape such data via instaloader.

Check examples from mobile on the imgs attached:
- they have a shopping bag on the top right corner
![Screenshot_20200914-155738_Instagram](https://user-images.githubusercontent.com/24527375/93102634-8df57f80-f6a3-11ea-83c1-206d3c37c550.jpg)
- or the post when opened and show tags
![Screenshot_20200914-155755_Instagram](https://user-images.githubusercontent.com/24527375/93102695-a1084f80-f6a3-11ea-805f-e98839136e48.jpg)

Thanks a lot!

**Comment by aandergr** [comment]
Welcome to the community! Please use our [Feature Suggestion Template](https://github.com/instaloader/instaloader/issues/new?labels=feature+suggestion&template=feature_request.md) for suggesting new features, as this makes it easier to see how the new feature could fit into Instaloader.
