### ISSUE TITLE
501 Error Code when trying to scrape hashtag

### ISSUE THREAD

**Issue by monney** [instaloader/instaloader#804]
**Describe the bug**
When scraping a Hashtag I get a 501 error code from the server
**To Reproduce**
loader.download_hashtag("#dogs",fast_update = False)

**Expected behavior**
The Hashtag should have its images downloaded

**Error messages and tracebacks**
 HTTP error code 501. [retrying; skip with ^C]

**Instaloader version**
Version: 4.5.3
**Additional context**

**Comment by chlloeeyan** [comment]
got the same issue:(

**Comment by ScrapeScrapeScrape** [comment]
Same here, unfortunately! Hope someone could help us.

**Comment by barkays** [comment]
I think it's error on instagram web itself, because when I open hashtag search on the web it got 501 error too.
Example : https://www.instagram.com/explore/tags/python/

**Comment by mahooi** [comment]
> I think it's error on instagram web itself, because when I open hashtag search on the web it got 501 error too.
> Example : https://www.instagram.com/explore/tags/python/

yepp yepp, tried instaloader.Hashtag.from_name() and still got errors since it uses the same. hope this isn't permanent, cant even beautiful soup anything

**Comment by Showmaster3000** [comment]
I have the same error 501 thing since about two days while using the --geotags parameter to get the location data of a post. Maybe Instagram changed something in their data structure?

**Comment by GeorgesTS** [comment]
I have the same error while yesterday it was working

**Comment by robson-fernandes** [comment]
got the same issue:(

**Comment by jlntrt** [comment]
I have the same 501 problem by scraping regular user names too.

**Comment by tetekos** [comment]
realised that the same occurs with location as well as @Showmaster3000 mentioned
examples: [https://www.instagram.com/explore/locations/1798859803700949/the-villa-balluta/](url)

**Comment by ScrapeScrapeScrape** [comment]
I contacted Instagram's services and they fixed it (at least for hashtags)!

**Comment by monney** [comment]
Closing this issue now, since instagram fixed the bug!
