### ISSUE TITLE
Way to download profiles alphabeticaly?

### ISSUE THREAD

**Issue by psonnosp** [instaloader/instaloader#806]
Win10 x64

If you put in a series of profiles to download instaloader seem to download them in a random(?) order, is it possible to make it go through the profiles in an alphabetic order instead?

Cause this behavior in combination with #710 makes it very tiresome if you have a a lot of profiles and then run into a profile with a highlight that make the process crash. If instaloader were to process the list in an alphabetic order it would be easy to just remove the profiles prior the one that crashed and run again. Now you have to go through the log and remove the ones processed one by one so you don't have to "waste" requests on profiles you already processed.

**Comment by aandergr** [comment]
Internally a [`set`](https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset) is used to store the profiles specified on command line, so the order of profiles is lost: https://github.com/instaloader/instaloader/blob/4ad4584b0d636b463fb4af2ee127f6eb55ab39bd/instaloader/__main__.py#L112

I think that could be changed to a `list` without causing problems. Then, with using an ordered collection, one could specify the profiles on the command line in alphabetic order to make instaloader go through them in alphabetic order.

**Comment by psonnosp** [comment]
> 
> 
> Internally a [`set`](https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset) is used to store the profiles specified on command line, so the order of profiles is lost:
> 
> https://github.com/instaloader/instaloader/blob/4ad4584b0d636b463fb4af2ee127f6eb55ab39bd/instaloader/__main__.py#L112
> 
> I think that could be changed to a `list` without causing problems. Then, with using an ordered collection, one could specify the profiles on the command line in alphabetic order to make instaloader go through them in alphabetic order.

Even though I appreciate the answer it didn't help me at all since I'm completely lost with anything more advanced than a simple batch file in DOS 😄 

But I guess that this is something I can't fix while using the Windows standalone? Just realized I didn't mention in my first post that that's what I'm using.

**Comment by psonnosp** [comment]
@aandergr Why did you change it to a feature suggestion? It's still a question, or follow up question, and I'd rather see that someone fix #710 than putting time into this since this wouldn't be an issue if it didn't crash because of #710

**Comment by aandergr** [comment]
> But I guess that this is something I can't fix while using the Windows standalone?

No, I think it is not possible to change the code within the Windows standalone EXE. However, it is possible to install Python on Windows, allowing to change the executed code.
