### ISSUE TITLE
Instaloader triggering Instagram phishing detection

### ISSUE THREAD

**Issue by gm489n6sowtg6i** [instaloader/instaloader#813]
Hello, I've been running Instaloader for several months with no problems. At the moment I'm using the latest release (version 4.5.3).

In the last few days I noticed that Instaloader would scrape profiles with no problems. However, when trying to log into my profile from instagram.com afterwards, I got a warning saying that I was a victim of phishing and that I had to change my password before continuing.

At first I though Instagram might have been monitoring password leaks and my password was actually found in one of them. However, after changing the password with a random string, the following day the same problem occurred again.

Does anybody have any idea about what could be causing Instaloader to trigger Instagram's phishing detection algorithm?

**Comment by XPanniX** [comment]
I'm having the same problem. Facebook/Instagram probably changed the way they detect bots or something. After having to change my password twice I even had to add a phone number to unlock my account. So you should probably be careful using instaloader, if you don't have a phone number at hand. Maybe they'll block your entire account if you misbehave again (that's just a guess)?

I'll try to add a delay before running instaloader periodically so it's not that obvious that it's a bot/script that executed every hour.

**Comment by tymorpheus** [comment]
@gm489n6sowtg6i 
The problem probably is you use new IG account without history of activity (created not long ago, no post published, etc).
Try to use more older IG acc with history of activity.
I face such issue from time to time.

**Comment by swissalps9** [comment]
That's not true @tymorpheus. My account is over 5 years old, with hundreds of posts and tens of thousands of followers. I am getting the same thing, even when I only run instaloader once a day.

**Comment by VasiliPupkin256** [comment]
Users start reporting this or similar issues in another project arc298/instagram-scraper#598 too. Today my account was also blocked, and instagram demanded me to add phone number to it.

**Comment by twitter-79** [comment]
Hey guys,

I had the same problem, starting probably around midday yesterday. It would not let me log in with username and password even when completing the challenge on the same device and with an old session file it always gave me a 400 Bad Request.

I was able to solve the problem by using the exact same user-agent as on the browser I completed the challenge with. Afterwards it was working fine again using the session file. However, I'm not sure yet if instagram also checks if the challenge was completed using the same IP address, so this might not be a solution for using instaloader on a server.

**Comment by daddancer** [comment]
Same thing happened to me, also starting yesterday. Even after adding a phone number to my account, it would get blocked as soon as I logged in from Instaloader. Maybe it's a coincidence, but I had an internet outage a few hours before my problems started, and I ended up with a new IP address after a couple of months on the old IP. I made sure to delete all old session files after resetting passwords, but as soon as I let Instaloader log in, I would be blocked immediately.

I have a handful of accounts to spread my ripping load across randomly, and a couple are literally used for downloading, whereas the one which got blocked was the one which actually gets used normally (i.e. it is public, it has regular content, and interacts with other users via the official app). I'm only accessing from this one IP (not on my phone) and not via any kind of VPN.

The solution by @twitter-79 of specifying the browser's UA (in my case, Firefox) got it working again immediately.

**Comment by Tydoki** [comment]
I really hope this gets addressed soon. This is making instaloader unusable for me. 

Even using my browser UA I still get locked out like once a day.

**Comment by swissalps9** [comment]
I am willing to fund a small bounty , paid via bitcoin, to anyone who is able to make this not detectable.

**Comment by 501st-alpha1** [comment]
I don't see any changes to this project (or to the other mentioned project, [instagram-scraper](https://github.com/arc298/instagram-scraper)) that would fix this, so I believe this is still a problem and the issue should remain open.

**Comment by sysoppl** [comment]
I had this issue when my cron was executed at ~3AM. When I changed it to ~19 it suddenly stopped. Also, I'm not browsing instagram from other device at this hour and I'm using it with firefox agent. Cron is executed once a day

**Comment by ripandtearr** [comment]
have also had accounts locked from this

**Comment by quietsecret123** [comment]
Any updates on this and how it can be avoided? I'm burning through many old and new accounts this month. A lot of them are disabled now. Only a matter of time before I run out of accounts to work with.

P.S. I use a different program (not Instaloader). Sorry to hop in here, but I figured the trigger/solution is similar.

**Comment by ripandtearr** [comment]
i found if you "warm up" an account for about 3-4 weeks it won't get disabled, that's the only fix i've found
google warming up instagram accounts for reference

**Comment by quietsecret123** [comment]
> i found if you "warm up" an account for about 3-4 weeks it won't get disabled, that's the only fix i've found
> google warming up instagram accounts for reference

Ugh, that means I have to invest time into these accounts I use just for downloading. Do you still get flagged for phishing or suspicious activity?

**Comment by quietsecret123** [comment]
> That's not true @tymorpheus. My account is over 5 years old, with hundreds of posts and tens of thousands of followers. I am getting the same thing, even when I only run instaloader once a day.
> 
> Account is now locked unless I provide a phone number.

Were you able to get back into the account? Also, do you have much activity on the account still?

I post on one of my "main" accounts but it still got flagged and it's now "stuck". It's not actually disabled, I'm just stuck at the "need help logging in" screen and can't find a way to get back in.

**Comment by 501st-alpha1** [comment]
Was there a reason the `leave open` label was removed?  AFAICT this is still an issue.

**Comment by Mubelotix** [comment]
Still an issue
