### ISSUE TITLE
EOFError: Ran out of Input 

### ISSUE THREAD

**Issue by Kikiss18** [instaloader/instaloader#814]
Hello, 

I was using Instaloader. I stopped the script by doing Ctrl + C.
And I got this error "EOFError: Ran out of Input " each time I trying to used Instaloader. 

![EOF-ERROR](https://user-images.githubusercontent.com/58808904/94171170-3b7d4580-fe91-11ea-95fb-edb1b678b79d.jpg)

I uninstall and reinstall. Then, I changed the password of my IG account. 
Nothing changed, always the same error.

Thank you for your help,

**Comment by Lum1nanz** [comment]
Hi, i had the very same problem today. To fix it, i deleted the session-file via the command:
`rm -f ~/.config/instaloader/*`

After that I started the instaloader with the --username and --password attributes via the command line and a new session-file was created.

The reason why my session-file was corrupted, was that my raspberry pi had no more free space, so the write-process of the session-file failed and the file was corrupted. I hope this helps.

**Comment by Kikiss18** [comment]
Hello Lum1nanz, 

Thank you for the tip. It worked!
I deleted it manually, because I am a beginner. : )

Have a great weekend,

**Comment by UnixCro** [comment]
Confirmed. It works again.
