### ISSUE TITLE
Can i pass instagram post's full URL

### ISSUE THREAD

**Issue by harshjadon9** [instaloader/instaloader#816]
Can i pass instagram post's full URL?

**Comment by alenavarshavskaya** [comment]
I didn't see any methonds that pass a full URL. 
Just use a regular expression, what the problem?

```python
def url_to_short_code(post_url):
    regexp = '^(?:.*\/(p|tv)\/)([\d\w\-_]+)'
    post_short_code = re.search(regexp, post_url).group(2)
    print('From url {} extracted shorcode:{}'.format(post_url, post_short_code))
    return post_short_code
```

**Comment by chrisg991** [comment]
@alenavarshavskaya Will this work for posts by people who have private acounts? (I understand that you'd need to be following them to access the post) As far as I can tell, only public posts have shortcodes? Copying the links to posts with different audiences gives different length URLs.

**Comment by aandergr** [comment]
@chrisg991 Yes, this will also work for posts from private accounts. The URL is longer, but that part of the URL still is called shortcode.
