### ISSUE TITLE
download_profile() directory

### ISSUE THREAD

**Issue by pauloventurab** [instaloader/instaloader#817]
Hello,

I'm working with Flask and using Instaloader to scrap some data to use in my app.

The questions is:

1º Which the best way to save the pictures (profile and posts)? When some user put the instagram I can return all the data, texts is not problem for me, but I dont know how to storage images.

2º How set a directory such as /static/imgs/instagram_profile_pictures when I download the pictures using profile_picture = L.download_profile(instauser,profile_pic_only=True)

Thank you so much.

**Comment by aandergr** [comment]
It's quite trivial to save the URLs to a file and serve them with Flask, and Instaloader provides helper functions such as [`get_and_write_raw()`](https://instaloader.github.io/module/instaloadercontext.html#instaloader.InstaloaderContext.get_and_write_raw). For example to provide a route which serves a HTML with an img to a downloaded profile pic, something like the following suffices.

```python
import instaloader
from flask import Flask, render_template

app = Flask(__name__)
L = instaloader.Instaloader()


@app.route('/profilepic/<username>')
def profilepic(username: str):
    profile = instaloader.Profile.from_username(L.context, username)
    L.context.get_and_write_raw(
        profile.profile_pic_url, f'static/profilepic_{username}.jpg'
    )
    return render_template('profilepic.html', username=username)


if __name__ == '__main__':
    app.run()
```

```jinja2
<!doctype html>
<title>Profile pic of {{ username }}</title>
  <h1>Profile pic of {{ username }}!</h1>
<img src="{{ url_for('static', filename='profilepic_'+username+'.jpg') }}"/>
```

**Comment by pauloventurab** [comment]
Thank you so much, working!

**Comment by html-proof** [comment]
https://github.com/html-proof/Instagram_pic_downloder/blob/master/Instagram_pix.py


please check your code there is an error in 404 port
