### ISSUE TITLE
Limits while parsing data with Python

### ISSUE THREAD

**Issue by tymorpheus** [instaloader/instaloader#818]
Hello everyone!

I face the limits when I parse IG data with Python.
For example I get only 100 post comments instead of 1000 using download_post() or only 400 post likes instead of 1100 using get_likes().

Any Idea how to handle it?

**Comment by aandergr** [comment]
Welcome to the community! Please see [Reporting Bugs](https://instaloader.github.io/contributing.html#reporting-bugs) for how to report a bug. There is little chance to understand an issue if the requested information is missing.
