### ISSUE TITLE
Reels viewcount 

### ISSUE THREAD

**Issue by isaac1902** [instaloader/instaloader#821]
When I retrieve **viewcount** of a _REEL_ post, I get a number that is lower of the real one that I see on Instagram. This doesn't happen with the normal VIDEO posts, only with REELS. It seems that they are unique views.
Can you please check?

Thanks.

**Comment by isaac1902** [comment]
Any input on this?

**Comment by HuunoAdmin** [comment]
has anyone experienced the same issue?

**Comment by terry-zc** [comment]
any update for this solution?
