### ISSUE TITLE
Is my account blocked?

### ISSUE THREAD

**Issue by psonnosp** [instaloader/instaloader#822]
Sorry for the title sucking ass but don't really know how to shorten this down to a simple sentance :D

Last night I used .\instaloader PROFILE --fast-update --stories --igtv --no-metadata-json -l USERNAME for a profile that has 304 posts and after downloading about 250 images/videos I got a 429 error with a lot of very short request pauses followed by some longer ones without nothing more being downloaded so I gave up.
So I tried it again today and it found some resume file (iterator_CpV8_juh.json.xz) and picked up where I ended it last night but it at once stopped with
```
429 Too Many Requests [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
   somehashimnotsureifishouldpublish:    1    1    1    1    1    1
                              other:    1    1    1    1    1    1
 *                           iphone:    2    2    2    2    2    2
   somehashimnotsureifishouldpublish:    1    1    1    1    1    1
```
And I haven't used instagram at all on any device from my IP since last night.
After this I checked to see if my account had been limited or something but nothing odd when I logged in with a browser.
So why is instaloader getting blocked? I get that it was blocked last night when the requests in the last 60 minutes was around 130 but not when it looks like above.
Is it possible to limit at what rate it downloads? I'd rater have it take an hour than having my this kind of thing happening and maybe get my account deleted or something.

**Comment by aandergr** [comment]
There are two similar issues regarding current problems which we suspect being related to rate limiting: #770 ("Bad Request" and having to pass a login challenge after many queries) and #774 (429); unfortunately both without a real solution yet.

When invoking Instaloader from within Python, it is possible to limit at what rate Instaloader downloads:

> [...]
> Instaloader allows to [adjust the rate controlling behavior](https://instaloader.github.io/module/instaloadercontext.html#ratecontroller) by overriding `count_per_sliding_window()`, for example limiting the amount of queries to 20 per sliding window like it was in Instaloader 4.4:
> 
> ```python
> class MyRateController(instaloader.RateController):
>     def count_per_sliding_window(self, query_type):
>         return 20
> 
> L = instaloader.Instaloader(rate_controller=lambda ctx: MyRateController(ctx))
> ```



_Originally posted by @Thammus in https://github.com/instaloader/instaloader/issues/770#issuecomment-700218388_

**Comment by micoots** [comment]
Hi. I'm a new user to this script, using it for the past week (under a Windows 10 desktop), and initially, things seemed to work well but very quickly, within a day or so, I started getting blocked with my account. Trying a few times and over and over, the blocks seem permanent hassling with challenge responses, which I pass in the browser, but then when using the instaloader script again get challenged again.

Essentially, it leaves instaloader as a non-functioning tool.

Going through these support requests on Git others are experiencing the same problems. I intend to do some more testing later using new accounts I will create, but for the moment IG cobbles the ability for instaloader use.
