### ISSUE TITLE
Trojan.Python.Psw

### ISSUE THREAD

**Issue by nerdysciencegrl** [instaloader/instaloader#823]
Ikarus Antivirus have been detected this program as Malware

**Comment by Terrobility** [comment]
It's a false positive. I checked on [VirusTotal](https://www.virustotal.com/gui/file/c21671e16cf6de1a50ea08866fd3ef39a1d3f3ece370d651f5c4f5b63260eaaa/detection) to see if other antiviruses detect it. The result was 2 out of 70 detections - one from Ikarus like you said and the other from SecureAge APEX.

Anyways, I sent Ikarus support an email letting them know about the false positive. Let's see if they fix it! I'll share any updates if they respond.

**Comment by Terrobility** [comment]
Good news! The false positive should be fixed. Here is their response:

> *****   false-positive   *****
> 
> The false positive was removed and should not occur any more after our next database update.
> 
> This is an automatic generated e-mail, please do not reply.

**Comment by Terrobility** [comment]
All false positives have been removed. There are now zero detections on [VirusTotal](https://www.virustotal.com/gui/file/c21671e16cf6de1a50ea08866fd3ef39a1d3f3ece370d651f5c4f5b63260eaaa/detection), at least for the current version (v4.5.3 executable).

You should be able to close the issue now.

**Comment by aandergr** [comment]
Thanks for taking care of this and contacting antivirus vendors, @Terrobility!
