### ISSUE TITLE
Highest resolution images isn't downloaded when using -post

### ISSUE THREAD

**Issue by psonnosp** [instaloader/instaloader#827]
**Describe the bug**
When using -post instaloader doesn't get the highest resolution as described in #630

**To Reproduce**
Use instaloader natgeo -l USER to get [this post](https://www.instagram.com/p/CFz6yfxjY1o/) in a 1440 version then use instalaoder -- -CFz6yfxjY1o -l USER and you only get the 1080 version.
**Expected behavior**
That instaloader fetch the same resolution image when using the -- -post command as when downloading an entire profile

**Instaloader version**
4.5.3

**Comment by ungenio** [comment]
Works well for me. You may not be logging in correctly.

**Comment by psonnosp** [comment]
I have to sign in in a different way when grabbing a single post then when getting a whole profile?
I used the same session when trying both and didn't get an error indicating that I wasn't logged in.

**Comment by Thammus** [comment]
You need to specify `-l USER` before `--`, i.e.  `instaloader -l USER -- -CFz6yfxjY1o`. Command options (like `--login`) are not accepted after the [double-dash](https://unix.stackexchange.com/a/11382) `--`.

**Comment by psonnosp** [comment]
Oh, OK.
Thanks for explaining what was wrong and not just leave with pointing it out.
