### ISSUE TITLE
"instaloader : command not found" after installation (v.4.5.3)

### ISSUE THREAD

**Issue by sltgc** [instaloader/instaloader#829]
Hi,
I've just installed the lastest instaloader's version (4.5.3) on Linux Mint 20.
Installation was successfull, but when I type "instaloader profilename", my terminal says _instaloader : command not find_ whatever profile's name I put.

When I was using instaloader 4.2. on Mint 18, no problem.

Maybe I miss something ?

**Comment by aandergr** [comment]
Duplicate of #440
