### ISSUE TITLE
invalid literal for int() with base 10: b''

### ISSUE THREAD

**Issue by DonnaRosa** [instaloader/instaloader#83]
Hello!
When I try to test the new version of instaloader (3.3.1) I've got this error:
$ python3 instaloader.py  mag_bush 
Traceback (most recent call last):
  File "instaloader.py", line 1754, in <module>
    main()
  File "instaloader.py", line 1748, in main
    filter_str=args.only_if)
  File "instaloader.py", line 1574, in main
    filter_func=filter_func)
  File "instaloader.py", line 1434, in download_profile
    name_updated, profile_id = self.check_profile_id(name, profile_metadata)
  File "instaloader.py", line 1349, in check_profile_id
    profile_id = int(id_file.read())
ValueError: invalid literal for int() with base 10: b''

$ python --version
Python 3.6.4

I've also noticed that the directory "bush_mag" was created with the file called "id" in it. But the file is empty.

Best regards

**Comment by DonnaRosa** [comment]
I've just noticed that the directory "bush_mag" was created with the file called "id" in it. But the file is empty.

**Comment by aandergr** [comment]
> I've also noticed that the directory "bush_mag" was created with the file called "id" in it. But the file is empty.

Could you delete that id file and then try again? This file probably has been created while Instaloader was broken with bug #81, and now it should work fine.

**Comment by DonnaRosa** [comment]
Oh,  now it works perfectly! )
Thank you very much!
