### ISSUE TITLE
Time lag during comments scraping

### ISSUE THREAD

**Issue by alenavarshavskaya** [instaloader/instaloader#831]
Hello everyone! 

I have some troubles with comments scraping from random posts and have no idea what is the reason. I tried looking for similar topics, but couldn't find 

My app is checking weather the user leave a comment on the specific post. But sometimes not all the comments are returned by `get_comments()` iteration just after the publication. If you wait for 10-20 mins, the comment will be found. 

**The question is**: why do the 90% of all checkings are great and for some situtaions I face a problem? _I know that instaloader uses instagram's web interface parser. But it doesn't matter i think: i see these searched comments in this webinterface_

Script's order:

- login: 
    - `instaloader_instance = Instaloader()`
    - `instaloader_instance.load_session_from_file(username=insta_login)`
- post import
    - `post = Post.from_shortcode(instaloader_instance.context, post_shortcode))`
- iteration over the comments:
    - `comments_iterator = post.get_comments()`
    - `for comment in comments_iterator: ... `
    - `if comment.owner.username == insta_nick: ...`

**Comment by shepurev** [comment]
Hmmm. I have the same question. 
For such situations I ve made a crutch: when comment isn't found i parse html from post url.

**Comment by e5150** [comment]
If the comments are visible on the website, they should be accessible through Instaloader. A comment that is in reply to a previous comment is stored in `comment.answers`. That doesn't explain why your code would access them after a few minutes though.

**Comment by alenavarshavskaya** [comment]
Thanks for an answer! 

I know and understand these subtleties, read in other issures. Comments that are not found for ~7-10 mins are right below the post, not in response to others.

**Comment by alenavarshavskaya** [comment]
Friends, the problem is still actual. Am i the only one who face with it ?

**Comment by Thammus** [comment]
The endpoint Instaloader uses to fetch the comments has not been updated for a while. There is a chance that newer query hashs for fetching comments could have a shorter time lag.
