### ISSUE TITLE
2FA via authentication apps

### ISSUE THREAD

**Issue by luthfirrahmanb** [instaloader/instaloader#832]
I just login to my account and I'm using command prompt, when do input 2FA, I'm input right 2FA but it continuously ask for 2FA code, capture below:

![image](https://user-images.githubusercontent.com/18209502/95184774-0efeed00-07f2-11eb-8cf4-3598d2a55b4d.png)

how can I reproduce it? thank you

**Comment by aandergr** [comment]
Instaloader repeats asking for the 2FA verification code if the entered code is not accepted by Instagram.

**Comment by sometowngeek** [comment]
I have the same issue.

I tested the 2FA verification code by logging out of and logging back in instagram. Each time I log back in, it prompts for 2FA code and I keyed it in. My password manager generates the 2FA and all the codes worked.

When I tried to use the 2FA with instaloader, I get the same issue as @luthfirrahmanb did.

**Comment by aandergr** [comment]
Login with 2FA works for me.

> My password manager generates the 2FA and all the codes worked.

2FA via authentication apps is not supported, Instaloader supports 2FA with the code being sent per SMS to a phone number, or per email.

**Comment by sometowngeek** [comment]
> Login with 2FA works for me.
> 
> > My password manager generates the 2FA and all the codes worked.
> 
> 2FA via authentication apps is not supported, Instaloader supports 2FA with the code being sent per SMS to a phone number, or per email.

I abhor the use of SMS-based 2FA because they are not secure enough.

Is there a reason why Instaloader does not support 2FA via authentication apps?

**Comment by aandergr** [comment]
> Is there a reason why Instaloader does not support 2FA via authentication apps?

No, there is no reason. Support for 2FA via authentication apps would be a welcome contribution.

**Comment by sometowngeek** [comment]
> > Is there a reason why Instaloader does not support 2FA via authentication apps?
> 
> No, there is no reason. Support for 2FA via authentication apps would be a welcome contribution.

Ah ok.

I will look into this then and see if I can contribute to it starting this coming weekend.

**Comment by luthfirrahmanb** [comment]
I see, thank you @aandergr for the information. Will wait @sometowngeek , thank you guys

**Comment by sometowngeek** [comment]
@luthfirrahmanb I think this issue should remain open until there is a pull request that tags this.

If I am unable to figure it out, someone else might be able to.

**Comment by luthfirrahmanb** [comment]
> @luthfirrahmanb I think this issue should remain open until there is a pull request that tags this.
> 
> If I am unable to figure it out, someone else might be able to.

Got it, I re-open the Issue

**Comment by munhitsu** [comment]
still an issue
