### ISSUE TITLE
Login error 

### ISSUE THREAD

**Issue by HAKKA667** [instaloader/instaloader#833]
After putting my password I needed to pass the Checkpoint challenge. It didn't work for me so I used the script at this page: https://instaloader.github.io/troubleshooting.html
But when I was trying to execute the script it told me that "ModuleNotFoundError" doesn't exist. What can I do?

**Comment by e5150** [comment]
You can post the full traceback.

**Comment by HAKKA667** [comment]
> You can post the full traceback.

Could you tell me how I can do that please?

**Comment by Showmaster3000** [comment]
just execute your command, copy the output and paste/post it here.

**Comment by chrisg991** [comment]
@HAKKA667 I had the same problems that you have had. I couldn't get around the checkpoint challenge and had trouble running the Firefox cookie script. Turns out you need to specify python3 when you run the script - it won't work with previous versions of python

**Comment by HAKKA667** [comment]
> @HAKKA667 I had the same problems that you have had. I couldn't get around the checkpoint challenge and had trouble running the Firefox cookie script. Turns out you need to specify python3 when you run the script - it won't work with previous versions of python

How can I do that ?

**Comment by HAKKA667** [comment]
> @HAKKA667 I had the same problems that you have had. I couldn't get around the checkpoint challenge and had trouble running the Firefox cookie script. Turns out you need to specify python3 when you run the script - it won't work with previous versions of python

@chrisg991 How can I do that please?

**Comment by HAKKA667** [comment]
> just execute your command, copy the output and paste/post it here.

@Showmaster3000 here you go
![instaloader](https://user-images.githubusercontent.com/72337909/97080929-4bf31e00-15ff-11eb-9f41-9a29b85422c4.jpg)

**Comment by chrisg991** [comment]
Assuming you have downloaded the Firefox cookie script, just run it but
specify python3 rather than python, like so:

python3 615_import_firefox_session.py

**Comment by HAKKA667** [comment]
Ok thanks it worked! 👍
