### ISSUE TITLE
Fast post/comment extraction from instagram profiles using instaloader

### ISSUE THREAD

**Issue by cimentadaj** [instaloader/instaloader#835]
This question was added already in SO for a few days and haven't received any answers. Just looking for some ideas from experienced `instaloader` folks.

I'm using `instaloader` to automatically grab the posts and comments of 50 big instagram profiles (over 8K posts and thousands of comments). I'm looking to update each profile every 30 mins, meaning that I want to grab all new posts and comments (these could be comments of the new posts or **old ones**). 

`instaloader` successfully allows me to grab this information but it takes a long time to grab all posts/comments, as I have to download all of this information every 30 minutes (essentially, I'm downloading all posts/comments and then cross-check which ones are new based on the post/comment ID and only push those. However, I still have to downloading everything, circa 7K post + thousands of comments). For example, downloading the posts/comments for a single profile with over 7K posts can take up to more than 1 or two hours.

* Using instaloader, is there a way to download only the posts/comments which are new? Perhaps through HTTP etags that contain a hash for each post?

* Is there any alternative to downloading all posts/comments quickly (let's say 1 minute)? For example, through the IG API directly or other third party APIs (https://github.com/dilame/instagram-private-api)?

**Comment by aandergr** [comment]
Given that the comments of a post are not ordered chronologically, I have unfortunately no idea how we could achieve a speed-up.

There is a structure of up to three levels to fetch, namely 
1. posts, 
1. their comments and 
1. their answers.

For the first level, we have `--fast-update`, which stops the iteration when arriving at the first already-downloaded post. This is based on the assumption that posts come strictly newest-to-oldest. However, it does not update the comments with their answers of older posts.

An obvious approach would be to go through all posts and their comments and use the "abort at the first already-seen node" logic for the answers. However, it seems that the necessary assumption of chronologically ordered nodes does not hold for 
the comments, at least not for how Instaloader currently obtains the comment list. Neither in the web interface.

**Comment by janakan97** [comment]
> This question was added already in SO for a few days and haven't received any answers. Just looking for some ideas from experienced `instaloader` folks.
> 
> I'm using `instaloader` to automatically grab the posts and comments of 50 big instagram profiles (over 8K posts and thousands of comments). I'm looking to update each profile every 30 mins, meaning that I want to grab all new posts and comments (these could be comments of the new posts or **old ones**).
> 
> `instaloader` successfully allows me to grab this information but it takes a long time to grab all posts/comments, as I have to download all of this information every 30 minutes (essentially, I'm downloading all posts/comments and then cross-check which ones are new based on the post/comment ID and only push those. However, I still have to downloading everything, circa 7K post + thousands of comments). For example, downloading the posts/comments for a single profile with over 7K posts can take up to more than 1 or two hours.
> 
> * Using instaloader, is there a way to download only the posts/comments which are new? Perhaps through HTTP etags that contain a hash for each post?
> * Is there any alternative to downloading all posts/comments quickly (let's say 1 minute)? For example, through the IG API directly or other third party APIs (https://github.com/dilame/instagram-private-api)?

How are you trying to download the comments using instaloader
