### ISSUE TITLE
Facing error 429. Suggest a proper way to download many Instagram accounts data.

### ISSUE THREAD

**Issue by angentanewbe** [instaloader/instaloader#836]
I want to download posts and other data of many instagram profiles. I am getting error 429 after some limit and --resume-prefix command works sometimes but sometimes it don't.  Also  --resume-prefix does not work when logged in with a different account. It happened when after hitting the 429 error I logged in with another account and thought it would resume from where I left the downloading of posts but it started from the beginning.

I want a proper way of downloading multiple instagram account pictures videos and mainly the tagged photos. I have around 150
accounts to download. Is there any way to use proxy accounts efficiently. I have to create new account and follow individual profile with each new account and it is a very painful task for me. How you guys download so many accounts data? Please suggest me. Also on the website  https://instaloader.github.io/ there are command lines and some details about them but the details for how the command works is less and a new user like me struggle to learn what the commands do. It seems Instaloader needs a youtube tutorial channel for detailed explanation of each command.

Post your reply with a proper way of downloading bulk account posts and details with a way to tackel this error 429 issue.

**Comment by Showmaster3000** [comment]
Similar problem like in #770 and other issues like #834

**Comment by angentanewbe** [comment]
> Similar problem like in #770 and other issues like #834

Not helping me! Answer me in detail below in easy step by step approach.

**Comment by royalh23** [comment]
Same! He also closed my issue (#838)  by referring to this bug and another one.

**Comment by aandergr** [comment]
We don't accept multiple issues discussing the same topic, that's why they were labelled as duplicate and closed.
