### ISSUE TITLE
Add support for retriving a list of users we have requested to follow

### ISSUE THREAD

**Issue by tathastu871** [instaloader/instaloader#837]
**Provide us a use case of the feature**
How could the user invoke the new function? Which problem would it solve? If new information is obtained, how would it be further processed?

**Describe the solution you'd like**

Please just as there is feature to retrive followers and followees list, please add feature for  **_retrieving list of users we have requested to follow._**

The list of users we have requested to follow can be obtained by following url in logged in account

```https://www.instagram.com/accounts/access_tool/current_follow_requests```

Tried using json query but it list only first 10 users.
The page is having cursor based pagination to load all users list

Please include this feauture to get list by scraping above url.
**Describe alternatives you've considered**

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes / No

**Additional context**
Add any other context about the feature request here.

**Comment by tathastu871** [comment]
> ```python
> from pprint import pprint
> 
> import instaloader
> 
> L = instaloader.Instaloader()
> L.load_session_from_file(USERNAME)
> 
> pprint(
>     L.context.get_json(
>         "accounts/access_tool/current_follow_requests", params={"__a": 1}
>     )["data"]["data"]
> )
> ```

It display only first 10 entries and not all

**Comment by bryanseah234** [comment]
> > ```python
> > from pprint import pprint
> > 
> > import instaloader
> > 
> > L = instaloader.Instaloader()
> > L.load_session_from_file(USERNAME)
> > 
> > pprint(
> >     L.context.get_json(
> >         "accounts/access_tool/current_follow_requests", params={"__a": 1}
> >     )["data"]["data"]
> > )
> > ```
> 
> It display only first 10 entries and not all

is it possible to get more than 10? i would like to know who i requested to follow, and if possible cancel that request.

**Comment by tathastu871** [comment]
Please provide some coee

**Comment by Smart123s** [comment]
If anyone comes across this, I've modified the code from above to load every username, not just the first 10.

```python
import instaloader

L = instaloader.Instaloader()
L.load_session_from_file(USERNAME)

cursor=""
data=[]

while True:
    req = L.context.get_json(
            "accounts/access_tool/current_follow_requests", params={"__a": 1, "cursor":cursor}
        )['data']

    cursor = req['cursor']
    [ data.append(i['text']) for i in req['data']]

    if cursor == None:
        break

print(data)
```

**Comment by tathastu871** [comment]
will it work recursively

**Comment by Smart123s** [comment]
For me it returned all 93 of my followers.
