### ISSUE TITLE
Location + date post filter = infinite skip?

### ISSUE THREAD

**Issue by mauro-cb** [instaloader/instaloader#839]
Hi there!

So ... I'm trying to download posts from a nearby city just from the last 2 days and It is happening as it should be... the problem appears when arrive at the 3rd day, it enter in a infinite skip. It make sense when we are talking about profiles, but if we are talking about location there are so many posts that it becomes impracticable.

of course, I could simply press "CRTL + C" to stop the downloads when it was finished, but I intend to put it in an "automatic-daily-collect", so I need some automatic solution as well...

there are some parameter that stop the process when it starts to skip the posts? Or some another alternative solution?

the command line code:

instaloader -l my_user -p my_password %code_of_location --post-filter="date_utc >= datetime(2020, 10, 12)" --no-profile-pic --no-pictures -V --no-video-thumbnails --no-compress-json

![Screenshot_58](https://user-images.githubusercontent.com/62271732/95907288-a8d61500-0d71-11eb-9f2b-cf63d3b4d3c0.png)

and it keep going ....

![Screenshot_59](https://user-images.githubusercontent.com/62271732/95907102-6f9da500-0d71-11eb-99ab-dd6cb109372c.png)

if i simply let it go the instagram would block my account faster, don't it?

**Comment by aandergr** [comment]
Hi!

`--post-filter` naively evaluates for each post whether the given condition is met or not. It is unaware of the fact that the posts come in chronological order and its implications on which posts have to be filtered.

So what you could do instead is to loop through the posts and *take* them, *while* they are newer than 2 days, stopping as soon as they don't fulfill that condition anymore. This is not possible with the CLI program *instaloader*, however, an example for how this can be achieved with an easy script using the *takewhile()* function can be found here: https://instaloader.github.io/codesnippets.html#download-posts-in-a-specific-period
