### ISSUE TITLE
Posts that I have liked - The directory name is invalid: ':feed'

### ISSUE THREAD

**Issue by MatthieuBonenfant** [instaloader/instaloader#84]
Hi, I just updated to 3.2.2. Good job on fixing the latest issues and revamping the documentation.

I never tried this before so I do not know necessarily if I am hitting the right parameters but as suggested on page 1 of the documentation I tried downloading the images I liked over the years.

copy pasted and added my username + typed my password like this
instaloader --login=mmathab --only-if=viewer_has_liked :feed

Getting this error

```
Only download posts with property "viewer_has_liked".
Loaded session from c:\users\mmath\appdata\local\temp/.instaloader-mmath/session-mmathab.
Logged in as mmathab.
Retrieving pictures from your feed...
[  1] starwarsinfographic Traceback (most recent call last):
  File "c:\python\scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==3.3.2', 'console_scripts', 'instaloader')()
  File "c:\python\lib\site-packages\instaloader.py", line 1742, in main
    filter_str=args.only_if)
  File "c:\python\lib\site-packages\instaloader.py", line 1542, in main
    filter_func=filter_func)
  File "c:\python\lib\site-packages\instaloader.py", line 1232, in download_feed_posts
    downloaded = self.download_post(post, target=':feed')
  File "c:\python\lib\site-packages\instaloader.py", line 1001, in download_post
    os.makedirs(os.path.dirname(filename), exist_ok=True)
  File "c:\python\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] The directory name is invalid: ':feed'

```
Not sure if I need to type something instead of :feed. 

Thanks again.

**Comment by aandergr** [comment]
It seems that the problem here is [Windows heavily restricting the set of allowed characters in a directory name](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#file_and_directory_names), which we didn't know when designing that feature and choosing `:feed` (likewise `:saved` and `:stories`) as default directory name.

At the moment, a workaround is to use the `--dirname-pattern` flag to override that default and choose a name that Windows accepts, e.g. `instaloader --dirname-pattern=feed`.

Thanks for pointing us as this issue! As a next step, we probably should change Instaloader's default dirname pattern setting on Windows regarding targets that start with a colon. Unfortunately, that OS imposes incredibly many restrictions requiring extra considerations, and due to neither @Thammus nor I using Windows, there might be more bad surprises waiting to be discovered. Here we depend on our community showing us our Windows-related problems.

**Comment by MatthieuBonenfant** [comment]
Thanks, glad to be your Windows tester :)

**Comment by MatthieuBonenfant** [comment]
By "workd around IS..." I am not sure you meant there is a work around in 3.2.2 or not right now. It does not appear to work though.

```
C:\python\Scripts>instaloader --login=mmathab --filename-pattern={profile}_{date} --only-if=viewer_has_liked --dirname-pattern=feed
Only download posts with property "viewer_has_liked".
Loaded session from c:\users\mmath\appdata\local\temp/.instaloader-mmath/session-mmathab.
Logged in as mmathab.
Saved session to c:\users\mmath\appdata\local\temp/.instaloader-mmath/session-mmathab.

C:\python\Scripts>
```

**Comment by Thammus** [comment]
It seems you forgot to specify a target for Instaloader to download. Just add `:feed` to the command and it should work.

**Comment by MatthieuBonenfant** [comment]
Added :feed at the end but it is now skipping all likes and giving an error

`C:\python\Scripts>c:\python\scripts\instaloader --login=mmathab --filename-pattern={profile}_{date} --only-if=viewer_has_liked --dirname-pattern=feed :feed
Only download posts with property "viewer_has_liked".
Loaded session from c:\users\mmath\appdata\local\temp/.instaloader-mmath/session-mmathab.
Logged in as mmathab.
Retrieving pictures from your feed...
<pic by davidchoe skipped>
<pic by sexyimperial skipped>
<pic by filthysith skipped>
<pic by seduced_by_the_darkside skipped>
<pic by darrenmacalvert skipped>
<pic by force_girls skipped>
<pic by hodgesart skipped>
<pic by thatkevinsmith skipped>
<pic by davidchoe skipped>
<pic by anticssmess skipped>
<pic by rickcelis skipped>
<pic by forceboys skipped>
<pic by seduced_by_the_darkside skipped>
<pic by anticssmess skipped>
<pic by darrenmacalvert skipped>
<pic by forceboys skipped>
<pic by johnboyega skipped>
<pic by hodgesart skipped>
<pic by starwars_runner skipped>
<pic by hodgesart skipped>
<pic by forceboys skipped>
<pic by anticssmess skipped>
<pic by starwars skipped>
<pic by hodgesart skipped>
[  1] dirtydroid Traceback (most recent call last):
  File "c:\python\scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==3.3.2', 'console_scripts', 'instaloader')()
  File "c:\python\lib\site-packages\instaloader.py", line 1742, in main
    filter_str=args.only_if)
  File "c:\python\lib\site-packages\instaloader.py", line 1542, in main
    filter_func=filter_func)
  File "c:\python\lib\site-packages\instaloader.py", line 1232, in download_feed_posts
    downloaded = self.download_post(post, target=':feed')
  File "c:\python\lib\site-packages\instaloader.py", line 988, in download_post
    needs_profilename = (format_string_contains_key(self.dirname_pattern, 'profile') or
  File "c:\python\lib\site-packages\instaloader.py", line 133, in format_string_contains_key
    if field_name == key or field_name.startswith(key + '.'):
AttributeError: 'NoneType' object has no attribute 'startswith'`

**Comment by Thammus** [comment]
The pictures will be saved in the folder specified by the `--dirname-pattern` flag. In your described scenario this will be "feed". 
Commit 90a1b73 fixes the `AttributeError`. Thanks for reporting.

**Comment by aandergr** [comment]
Just committed 3640e9c in `bug_84_fix` branch. On Windows, it replaces the colon symbol in all paths by a character that looks  like a colon but has a different binary representation, thus should be accepted by the Windows filesystem.

```
pip3 install --upgrade git+https://github.com/Instaloader/instaloader@bug_84_fix
```

**Comment by aandergr** [comment]
The new release, version 3.3.3, includes these fixes. Thanks a lot for your help!
In our [Releases](https://github.com/instaloader/instaloader/releases) section, we now offer a zipfile including a `instaloader.exe` file with Python already bundled. This should make it much easier to run Instaloader on Windows.
