### ISSUE TITLE
Downloading Instagram collections to folders

### ISSUE THREAD

**Issue by JunedKhan101** [instaloader/instaloader#843]
Instagram Collections or saved collections are stored in folders in the Instagram app.<br>
When I download the Instagram saved collections it downloads all in one folder it would be good if it creates a folder for all the saved collections folder and then downloads it in that folder<br>
Example:<br>
A user might have a "AeroPress", "Coffee", "Poems" Collections.<br>
![Instagram-app-showing-Save-to-Collections-screen-on-iPhone](https://user-images.githubusercontent.com/47941768/96679671-b99a1280-1391-11eb-98bc-69809757c2ab.png)
But when you download the Instagram collections using the command<be>
**Instaloader --login USERNAME :saved**<br>
it downloads all in one folder. Is there a way to download to folders "AeroPress", "Coffee", "Poems"

**Comment by aandergr** [comment]
This is not yet supported.

**Comment by KhanJuned** [comment]
@aandergr please remind me when you have solved this problem.
