### ISSUE TITLE
Create a LaunchDaemon

### ISSUE THREAD

**Issue by UnixCro** [instaloader/instaloader#848]
Hello, dear developers.  Let me be brief, before I begin, I would like to wholeheartedly praise those who developed this project.  This project is just breathtaking.  It works reliably and worked right away.  It also downloads the best possible quality you can get that way.  

Let me come to my question, I use macOS and my intention was to run a service that continuously downloads profiles of Instagram users at a certain time.  

As I am not inexperienced, I created a LaunchDaemon job without any problems.  A plist that executes an executable file.  

for example in the executable file: sleep 20s instaloader -profile Arianagrande.  That works fine.  But as soon as I type —login or —login —password there it no longer works.  Without this function I am restricted.  My .config file is in the home directory and does not work without problems when entering the terminal manually, only with launchd.  Can you help me please?

**Comment by aandergr** [comment]
Hello! Thanks, nice to hear that you like our project :)

It would be interesting to know, why it does not work with launchd, i.e. the error message and stack trace it shows. In the launchd documentation, [*Debugging launchd Jobs*](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html#//apple_ref/doc/uid/10000172i-SW7-SW5) shows an example for how to modify the plist such that we get a log with the output and errors of the job, by adding something like this to the plist

```xml
<key>StandardOutPath</key>
<string>/var/log/myjob.log</string>
<key>StandardErrorPath</key>
<string>/var/log/myjob.log</string>
```

Also, can you log in with Instaloader when typing `instaloader --login <USER>` in the terminal? Do you have two-factor authentication activated?

**Comment by UnixCro** [comment]
Thank you for your quick response.
I have your code in the plist file and have results that I unfortunately do not fully understand and will show here.

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>InstaDownloadDaemon</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>/Library/UDaemons/InstaDownloadDaemon</string>
    </array>
    <key>RunAtload</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/var/log/InstaDownloadout.log</string>
    <key>StandardErrorPath</key>
    <string>/var/log/InstaDownloaderror.log</string>
    <key>StartInterval</key>
    <integer>60</integer>
</dict>
</plist>`

This is my plist file that works fine as long as the executable doesn't have other parameters like ("--login" "--password"
"--stories").


My executable file:

`cd /opt/Instagram

/usr/local/bin/instaloader -profile theprofilewhatIwant`

as I said without problems, but if, for example, the following parameters appear 

("--login myuseraccount" "--password mypassword" " --stories"), launchd can't handle them


In /var/log/InstaDownloaderror.log it says: Fatal error: Login error: "fail" status, message "Please wait a few minutes before you try again.".

In /var/log/InstaDownloadout.log it says: Session file does not exist yet - Logging in.

My session file works fine with the real terminal and is recognized directly by instaloader.

Yes, I can easily download profiles with instaloader as long as I use the real terminal, all options work with all of my 5 accounts and no, I don't use 2FA.

I look forward to hearing from you soon

**Comment by UnixCro** [comment]
Thank you for your quick response.
I have your code in the plist file and have results that I unfortunately do not fully understand and will show here.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>InstaDownloadDaemon</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>/Library/UDaemons/InstaDownloadDaemon</string>
    </array>
    <key>RunAtload</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/var/log/InstaDownloadout.log</string>
    <key>StandardErrorPath</key>
    <string>/var/log/InstaDownloaderror.log</string>
    <key>StartInterval</key>
    <integer>60</integer>
</dict>
</plist>
```

My executable file:

```
cd /opt/Instagram

/usr/local/bin/instaloader -profile theprofilewhatIwant
```


as I said without problems, but if, for example, the following parameters appear

("--login myuseraccount" "--password mypassword" " --stories"), launchd can't handle them



In /var/log/InstaDownloaderror.log it says: Fatal error: Login error: "fail" status, message "Please wait a few minutes before you try again.".

In /var/log/InstaDownloadout.log it says: Session file does not exist yet - Logging in.



My session file works fine with the real terminal and is recognized directly by instaloader.

Yes, I can easily download profiles with instaloader as long as I use the real terminal, all options work with all of my 5 accounts and no, I don't use 2FA.


I look forward to hearing from you soon

**Comment by aandergr** [comment]
> My executable file:
> 
> ```
> cd /opt/Instagram
> 
> /usr/local/bin/instaloader -profile theprofilewhatIwant
> ```

That's why it doesn't work. `-profile` stands for `-p rofile`, which is equivalent to `--password=rofile`, and that is most probably not your password. Don't pass `-profile` to Instaloader.

I wonder why the session file is not recognized when called from launchd. Does it work when you let launchd explicitly pass the path to that file with `--sessionfile`?

**Comment by UnixCro** [comment]
It worked! Thanks alot! 

I wrote this and it worked right away

`/usr/local/bin/instaloader --login myaccount --password=mypassword theprofilewhatiwant`

launchd has probably made its own session file
`Saved session to /var/root/.config/instaloader/session-myuseraccount`

If I specify my session file exactly, launchd gets problems I just configure my passwords in` /var/root/.config` for launchd and then everything works.

Thanks again

**Comment by aandergr** [comment]
Alright, glad we could help :)
