### ISSUE TITLE
"Login error: Wrong password" even when password is 100% the good one

### ISSUE THREAD

**Issue by knoppyx** [instaloader/instaloader#849]
I'm beginner in python programming and i want to export my Instagram followers and following list into an excel file using the code below:
```
# Get instance
import instaloader

L = instaloader.Instaloader()

# Login or load session
username = "myusername"
password = "mypassword"
L.login(username, password)  # (login)

# Obtain profile metadata
profile = instaloader.Profile.from_username(L.context, username)

# Print list of followees
follow_list = []
count = 0
for followee in profile.get_followers():
    follow_list.append(followee.username)
    file = open("prada_followers.txt", "a+")
    file.write(follow_list[count])
    file.write("\n")
    file.close()
    print(follow_list[count])
    count = count + 1
# (likewise with profile.get_followers())
```
After my first try to run the code i realised that i forgot my password and i reseted my password. Although i reseted it, i'm still getting the following error:
```
Traceback (most recent call last):
  File "D:\ ..... \insta_followers.py", line 9, in <module>
    L.login(username, password)  # (login)
  File "D:\ ..... \venv\lib\site-packages\instaloader\instaloader.py", line 483, in login
    self.context.login(user, passwd)
  File "D:\ ..... \venv\lib\site-packages\instaloader\instaloadercontext.py", line 254, in login
    raise BadCredentialsException('Login error: Wrong password.')
instaloader.exceptions.BadCredentialsException: Login error: Wrong password.
```
I'm 100% the password is working because i tested on both browser and phone. My password contains uppercase and lowercase letters, numbers and signs. It is possible to get this error because one of the characters from the password (one of the signs)? Or maybe because i recently reset the password? Can you give me some advice please?

I'm using PyCharm Community 2020.2 and Python 3.9.

Thank you

**Comment by dieechtenilente** [comment]
i was experience a similar problem when using special characters (can't recall which one specific) in my password. Probably the password string isn't escaped properly..

**Comment by aandergr** [comment]
Instaloader's login fails when the password contains a colon (`:`) – #741.

You can still login with the workaround described there, or in [Troubleshooting – Login Error](https://instaloader.github.io/troubleshooting.html#login-error).

**Comment by jehudaRivaldoS** [comment]
instaloader cannot login and failed 

mport instaloader
import time

L = instaloader.Instaloader()
try:
    L.login("xx", "xx8")
    time.sleep(3)
    username = "xx"
    commentCount = 0
    profile = instaloader.Profile.from_username(L.context, username)
    posts = profile.get_posts()
    time.sleep(3)
except instaloader.exceptions.LoginRequiredException:
    print("Login failed. Please check your credentials.")
