### ISSUE TITLE
 429 Too Many Requests on first request

### ISSUE THREAD

**Issue by alesservin** [instaloader/instaloader#850]
**Describe the bug**
I am trying to get the list of my followees. But I get a "429 Too Many Requests" in this first request.

**To Reproduce**
I have a python script that does this: login to my Instagram account (I do the login with a session file, if not I get the same result as described in #845), get the list of my followees and then get their posts in order to analyze them.

At the second step (get the followees list) I get this 429 Too Many Requests

**Expected behavior**
Complete the process without getting a 429 Too Many Requests

**Error messages and tracebacks**
```
JSON Query to account_/feed/: 429 Too Many Requests [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
 *                            other:    1    1    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 665 seconds, at 15:52.
```

**Instaloader version**
4.5.3

**Comment by rocailler** [comment]
it can be proxy/VPN/own IP problem. If not, try do the steps manually, not by script and without login. I'm not sure but to get followees from public account you don't need to login. 
Login is a problem for few months. don't use it if you don't need it.

If you log into the phone app or website, this could also be the cause

**Comment by alesservin** [comment]
Thanks for your answer @rocailler.
About getting the followees, I tried to get them without loggin in, but I get this:
```
    raise LoginRequiredException("--login required to get a profile's followees.")
instaloader.exceptions.LoginRequiredException: --login required to get a profile's followees.
```
Today I tested the script again and I'm not getting the 429 To Many Requests on the "get followees" step. I will wait for the complete process to see if I get that response on next steps (takes 1-2 hours when it works)

**Comment by alesservin** [comment]
Now it is working.  What I did was change the session file and not use the instaloader for a day.  I also have account sessions closed on all devices except the browser, but I don't use it.  If someone has the problem I had, maybe it helps to do the same as me.
