### ISSUE TITLE
Hashtag download stops after 8 posts

### ISSUE THREAD

**Issue by monney** [instaloader/instaloader#853]
**Describe the bug**
Hashtag download stops after 8 posts
**To Reproduce**
loader= Instaloader(download_comments=False,
                    download_videos=False,
                    download_geotags=False,
                    save_metadata=False,request_timeout=100) loader.download_hashtag(hashtag,max_count=max_count,fast_update = False,)

**Expected behavior**
Posts should be downloaded
**Error messages and tracebacks**
No Errors
**Instaloader version**
4.5.3

**Additional context**
macOS and Linux

**Comment by chengren** [comment]
Got a similar error here, download nothing and break. No idea, what happened.

**Comment by aandergr** [comment]
> **To Reproduce**
> loader= Instaloader(download_comments=False,
> download_videos=False,
> download_geotags=False,
> save_metadata=False,request_timeout=100) loader.download_hashtag(hashtag,max_count=max_count,fast_update = False,)

This is hardly how to reproduce this bug. Running these commands works fine for me, downloading max_count hashtags with hashtag set to a hashtag that has enough posts.

**Comment by monney** [comment]
@aandergr are you logged into an account or using it as is? I’m trying figure out what could be causing it if it’s working for you. I’ve tried on multiple hashtags and systems

**Comment by monney** [comment]
Im not currently logged in with an account. here's a screenshot:
https://ibb.co/3vGLQp1

**Comment by monney** [comment]
It just stops without error, I print the DONE

**Comment by monney** [comment]
Other scrapers are also having this issue it seems

**Comment by evdutt** [comment]
Having this issue as well. Stopping on the 8th post for any hashtag I try.
Also on MacOS Catalina, using Python 3.7.6, instaloader 4.5.3
Issue occurs whether logged in or not.
The hashtag cars has more than 8 posts, so I would expect it to pull the requested 25.

`
import instaloader
L = instaloader.Instaloader(download_videos = False, download_comments = False, save_metadata = False)
L.download_hashtag('cars', max_count = 25, profile_pic = False)
`

![Screen Shot 2020-11-12 at 9 09 38 PM](https://user-images.githubusercontent.com/35197215/99019893-639d3280-252b-11eb-98ef-09cf0b91ec8f.png)

**Comment by aandergr** [comment]
![Screenshot_20201114_182630](https://user-images.githubusercontent.com/17130992/99153177-3e353380-26a7-11eb-8fe1-a1d7f7301045.png)

**Comment by evdutt** [comment]
> ![Screenshot_20201114_182630](https://user-images.githubusercontent.com/17130992/99153177-3e353380-26a7-11eb-8fe1-a1d7f7301045.png)

Hah, it works on your machine! What OS are you on? OP and I are on MacOS. Might be related to that.

**Comment by monney** [comment]
I’ve tried on Ubuntu with command line, and get the same issue. Tried different IP addresses as well, same issue.

**Comment by aandergr** [comment]
So I tried different IPs in different regions to investiage this. Indeed, in one region, Instaloader returned only 8 hashtag posts. But accessing Instagram in a browser quickly revealed the reason:

![Screenshot_20201114_195622](https://user-images.githubusercontent.com/17130992/99154912-c9b4c180-26b3-11eb-8cff-135e185fb634.png)

(_Recent posts from all hashtags are temporarily hidden to help prevent the spread of possible false information and harmful content related to the election._)

So of course, Instaloader does not return the hashtag posts in this case.

The hashtag posts that are accessible are just the 9 top posts. These are correctly returned by `Hashtag.get_top_posts()`. The only bug that we still have here is that Instaloader downloads 8 instead of 9 posts in this case.

**Comment by evdutt** [comment]
Ahhh that would explain it. Duh, I should have thought to go check on Instagram proper. Good catch. Darn Americans :) I appreciate your responsiveness.

**Comment by monney** [comment]
@aandergr thanks!

**Comment by monajalal** [comment]
@aandergr thanks a lot for your responsiveness and guidances.

Do you know why it is retreieving only 10 entries despite asking for 1000 entries?
Also, how can I ask it to download all the posts for a specific hashtag if I don't have a time constraint?
```
(base) mona@mona:~/research/insta-scrape$ python instaloader_tester.py 
Retrieving pictures with hashtag #book...
[   1/1000] #book/2020-11-30_00-22-21_UTC.jpg exists [Uma semana linda se inicia pr…] unchanged 
[   2/1000] #book/2020-11-30_00-04-39_UTC.jpg exists [Uma foto não planejada] unchanged 
[   3/1000] #book/2020-11-29_22-08-44_UTC.jpg exists [Eu sou apaixonada no por do ☀️] unchanged 
[   4/1000] #book/2020-11-29_21-39-19_UTC.jpg exists [sem efeito✨ . . . . . . . . .…] unchanged 
[   5/1000] #book/2020-11-29_21-33-55_UTC_1.jpg exists #book/2020-11-29_21-33-55_UTC_2.jpg exists #book/2020-11-29_21-33-55_UTC_3.jpg exists #book/2020-11-29_21-33-55_UTC_4.jpg exists #book/2020-11-29_21-33-55_UTC_5.jpg exists #book/2020-11-29_21-33-55_UTC_6.jpg exists #book/2020-11-29_21-33-55_UTC_7.jpg exists #book/2020-11-29_21-33-55_UTC_8.jpg exists #book/2020-11-29_21-33-55_UTC_9.jpg exists [• VOCÊ JÁ ESCUTOU ALGUMA DESS…] unchanged 
[   6/1000] #book/2020-11-29_20-12-30_UTC.jpg exists [Asking for book recommendatio…] unchanged 
[   7/1000] #book/2020-11-29_20-10-12_UTC.jpg exists [La sensación visual 📸  🎬 Esa …] unchanged 
[   8/1000] #book/2020-11-29_19-40-22_UTC.jpg exists [Lazy Sunday ⚡️  #bath #bathti…] unchanged 
[   9/1000] #book/2020-11-29_19-16-53_UTC.jpg exists [New pic from my new book Repr…] unchanged 

```

Here's the code:

```
import instaloader
  
loader= instaloader.Instaloader(download_comments=False,
                    download_videos=False,
                    download_geotags=False,
                    save_metadata=False,request_timeout=100)
loader.download_hashtag('book', max_count=1000, fast_update=False, profile_pic=False)

```
