### ISSUE TITLE
Get the information about post

### ISSUE THREAD

**Issue by GhostXu11** [instaloader/instaloader#857]
Hi,

I tried to use this code to get the information about the posts of hashtag, but it didn't work and returned nothing.

loader = Instaloader()
for post in loader.get_hashtag_posts('rebook'):
    print(post.owner_id)

Can you help me? I'm still a fresher about this.

**Comment by chengren** [comment]
Same issue, it looks get_hashtag_posts return nothing currently.

**Comment by aandergr** [comment]
Yes, Instagram disabled the listing of recent hashtag posts in some regions:

_Recent posts from all hashtags are temporarily hidden to help prevent the spread of possible false information and harmful content related to the election._

(also see https://github.com/instaloader/instaloader/issues/853#issuecomment-727251951)
