### ISSUE TITLE
Likes are not scrapped

### ISSUE THREAD

**Issue by Shadowsrik** [instaloader/instaloader#860]
Hi,

At the moment, I'm able to scrap comments but the likes are not scrapped. I'm trying to extract usernames for a instagram post likes.

It worked initially and then it stopped. I assume something was changed, might be in the instagram itself, not sure.

My code: 

`
import instaloader
from instaloader import *

L = instaloader.Instaloader()

post =  instaloader.Post.from_shortcode(L.context, 'CD9x9uHDM_O')

post_likes = post.get_likes()
i=0

for likee in post_likes:
    print(post_likes.username)
`
The error I get is 

`
import instaloader
from instaloader import *

L = instaloader.Instaloader()

post =  instaloader.Post.from_shortcode(L.context, 'CD9x9uHDM_O')

post_likes = post.get_likes()
i=0

for likee in post_likes:
    print(post_likes.username)
`

I tried to printout the likes from structure.py line 442
`likes_edges = self._field('edge_media_preview_like', 'edges')
  print(likes_edges)`

It return empty list although the post contains more than 10K likes.

Could you please help me with this?

**Comment by tejasbhatt17** [comment]
Hi,
I am also facing same issue from last 4 days, is there any solution?

**Comment by aandergr** [comment]
Thanks for reporting this issue. I just tried it and I can confirm that accessing likes of a post without being logged-in is directly responded with a *429 Too Many Requests* error.

Being logged in, it works fine.

I doubt that there exists any other solution than to log in.

Most probably unrelated, but when reading your issue, I also noticed this minor mistake:

> for likee in post_likes:
> print(post_likes.username)

It should be print(**likee**.username).

**Comment by tejasbhatt17** [comment]
> Thanks for reporting this issue. I just tried it and I can confirm that accessing likes of a post without being logged-in is directly responded with a _429 Too Many Requests_ error.
> 
> Being logged in, it works fine.
> 
> I doubt that there exists any other solution than to log in.
> 
> Most probably unrelated, but when reading your issue, I also noticed this minor mistake:
> 
> > for likee in post_likes:
> > print(post_likes.username)
> 
> It should be print(**likee**.username).

Thanks for reply

I have tried it with login, but in that case my insta account getting blocked very frequently.

Can you suggest me any hack until you find any solution without login ?

**Comment by Shadowsrik** [comment]
> Thanks for reporting this issue. I just tried it and I can confirm that accessing likes of a post without being logged-in is directly responded with a _429 Too Many Requests_ error.
> 
> Being logged in, it works fine.
> 
> I doubt that there exists any other solution than to log in.
> 
> Most probably unrelated, but when reading your issue, I also noticed this minor mistake:
> 
> > for likee in post_likes:
> > print(post_likes.username)
> 
> It should be print(**likee**.username).

Hi,

Thank you very much for the reply. How ever, even after login to Instagram from my chrome browser, I still face the same problem. To be sure, I removed all the cookies and logged in again. Just to compare, could you please post your snippet you used to test the code?

**Comment by chengren** [comment]
I also face this issue in the last a few days. The code I used before was not changed and I test both log in and guest mode. It does not work so far.

**Comment by flipso** [comment]
Hey Folks,

If i download the comments its counting the comments likes without any problem. Same with posts. 

@Shadowsrik You wrote: "I'm trying to extract usernames for a instagram post likes."
Haha 10k likes is a little bit extreme for testing.

I tested it with the correct version of your code snippet on a post with only 490 likes and get immediately the same problem. **I guess that they have certainly restricted it.**
Because they directly forbid, i guess they changed the behavior of the "endpoint" with the query_hash 1cb6ec562846122743b61e492c85999f 

So i think we need new possibilities to extract these data

Cheers

**Comment by aandergr** [comment]
> How ever, even after login to Instagram from my chrome browser, I still face the same problem.

Log in with Instaloader, e.g. by adding directly after the instantiation of `Instaloader`

```python
L.load_session_from_file(YOUR_USERNAME)
```

and running `instaloader --login YOUR_USERNAME` prior starting your script.
