### ISSUE TITLE
Confused about usage on Windows for downloading photos

### ISSUE THREAD

**Issue by BBlayne** [instaloader/instaloader#863]
Hello, I read the documentation but it is still a little confusing for me. I'd like to download ALL photos, and nothing else from an instagram account (i.e for example lets suppose an artist IG account). 

When I open the Windows 10 Instaloader executable, it brings up a command prompt window.

In this window I seem to need to run commands as ./instaloader.exe {commands}

I did ./instaloader.exe {profilename}

It is currently taking a long time to download all posts from the account, and seems to also be producing a lot of JSON files that I don't want. What would the clean command be to download all photos and nothing else from an account? And ideally specify a folder.

**Comment by slickag** [comment]
./instaloader.exe --help will give you a list of all the options.

If you strictly want the pictures posted then it'd be something like instaloader --no-videos --no-video-thumbnails --no-captions --no-metadata-json profilename (replacing profilename with the IG account of course).

If you want higher quality pictures or to download stories and/or highlights then you'll have to pass the --login command to instaloader as well.

**Comment by BBlayne** [comment]
Thanks! That worked perfectly. I don't really see any issues with the quality though, I'm mostly just scraping art accounts for reference images and 2d drawn art doesn't seem to hugely go up in quality with more resolution.
