### ISSUE TITLE
Encoding issues 

### ISSUE THREAD

**Issue by flipso** [instaloader/instaloader#865]
Hey Folks,

you have some Encoding problems. 

Found in (JSON files):

**every node with text attribute have these problem**

If you want to know how to fix you can use my fork. I commited the solution a few minutes ago.

5b3b30d69b1b21563cef9daff1f5f0b7f57d9040

Cheers,
Flipso

**Comment by flipso** [comment]
For example

        "edge_media_to_caption": {
            "edges": [
                {
                    "node": {
                        "text": "miss \u2018em already"
                    }
                }
            ]
        }

and comments:

 {
        "id": 17900333401126918,
        "created_at": 1514483509,
        "text": "Aww love you skippy \u2764\ufe0f\ud83d\ude14",
       
    }

**Comment by aandergr** [comment]
The encoding is fine.

**Comment by flipso** [comment]
How can this be understood? As shown in the example, emoticons are currently not supported by you. Should this be a feature?
