### ISSUE TITLE
Add Followers to Commandline parameter

### ISSUE THREAD

**Issue by flipso** [instaloader/instaloader#866]
Hey Folks,

why no option for downloading Followers? 

I think the code design is too much oveheat rn. From my point of view its better to download the Profiles only and not to download all the Followees or Followers recursive.

In my fork i have fixed these behavior and added the option to download Followers and Followers&Followee at once

Feel free to merge into instaloader: 44e9c01

Im not comfortable with the code redundancy. Any ideas how to get rid of it? Because the __main__.py per design no additional Functions allowed and i would like not to break your conventions until its necessary. 

Cheers

**Comment by aandergr** [comment]
Please use our [Feature Suggestion Template](https://github.com/instaloader/instaloader/issues/new?labels=feature+suggestion&template=feature_request.md) for suggesting new features, as this makes it easier to see how the new feature could fit into Instaloader.
