### ISSUE TITLE
Automatically check every given time

### ISSUE THREAD

**Issue by SxS46** [instaloader/instaloader#869]
Hello, I'm actually running this inside a docker container and every time the script ends it stops the container, it would be much better if the program keeps running and automatically check for new content every given time.
Is this possible?
Thank you

**Comment by aandergr** [comment]
Please use our [Feature Suggestion Template](https://github.com/instaloader/instaloader/issues/new?labels=feature+suggestion&template=feature_request.md) for suggesting new features, as this makes it easier to see how the new feature could fit into Instaloader.
