### ISSUE TITLE
Not Able to find the directory

### ISSUE THREAD

**Issue by achkeir** [instaloader/instaloader#87]
Hello,

I am kind of new to python and i am trying to run the code. However, I don;t know where is the default destination to find the downloaded photos. In other words, how can i specify my own target destination?

Is there a demo or video to do it ?

Thanks

**Comment by aandergr** [comment]
Hello,

there is no video that I am aware of, but we wrote an exhaustive [Documentation of Instaloader](https://instaloader.github.io/). Good starting points are

- [Install Instaloader](https://instaloader.github.io/installation.html),
- [Download Pictures from Instagram](https://instaloader.github.io/basic-usage.html) and
- [Specify where Instaloader Stores Posts](https://instaloader.github.io/basic-usage.html#filename-specification).

Per default, downloaded photos are stored in a directory within the current working directory, named exactly like the profile that is downloaded.

Happy Instaloading,
Alex
