### ISSUE TITLE
How to add save-progress functionality for Hashtag?

### ISSUE THREAD

**Issue by coderektor** [instaloader/instaloader#874]
Greetings!

I am Scraping metadata from hashtags on Instagram Using the following Code:

import instaloader

L = instaloader.Instaloader(download_pictures=False, 
                 download_videos=False, 
                 download_video_thumbnails=False,
                 download_geotags = False,
                 download_comments = False,
                 compress_json=False, 
                 post_metadata_txt_pattern=""
                )

posts = instaloader.Hashtag.from_name(L.context, 'sunup').get_posts()

users = set()

for post in posts:
    if not post.owner_profile in users:
        L.download_post(post, '#sunup')
        users.add(post.owner_profile)
    else:
        print("{} from {} skipped.".format(post, post.owner_profile))

It works fine Until I encounter 429 error and all the Progress is Lost, and I have to Restart from Scratch. 
Please, Help me add resumable_iteration functionality to the above code so that I can resume from Where it left off.

**Comment by aandergr** [comment]
Hashtag.get_posts() does not currently support to resume the iteration due to not using a graphql pagination. However, it seems we can get a [resumable iterator](https://instaloader.github.io/module/nodeiterator.html) for the recent hashtag posts like this:

```python
post_iterator = instaloader.NodeIterator(
    L.context, "9b498c08113f1e09617a1703c22b2f32",
    lambda d: d['data']['hashtag']['edge_hashtag_to_media'],
    lambda n: instaloader.Post(L.context, n),
    {'tag_name': HASHTAG},
    f"https://www.instagram.com/explore/tags/{HASHTAG}/"
)
```

With that, you can use [resumable_iteration()](https://instaloader.github.io/module/nodeiterator.html#resumable-iteration) as usual.

**Comment by Nicopdev** [comment]
If you are searching for a more general reply you can check the answers on [this duplicate](https://github.com/instaloader/instaloader/issues/926)

**Comment by Migliorin** [comment]
> Hashtag.get_posts() does not currently support to resume the iteration due to not using a graphql pagination. However, it seems we can get a [resumable iterator](https://instaloader.github.io/module/nodeiterator.html) for the recent hashtag posts like this:
> 
> ```python
> post_iterator = instaloader.NodeIterator(
>     L.context, "9b498c08113f1e09617a1703c22b2f32",
>     lambda d: d['data']['hashtag']['edge_hashtag_to_media'],
>     lambda n: instaloader.Post(L.context, n),
>     {'tag_name': HASHTAG},
>     f"https://www.instagram.com/explore/tags/{HASHTAG}/"
> )
> ```
> 
> With that, you can use [resumable_iteration()](https://instaloader.github.io/module/nodeiterator.html#resumable-iteration) as usual.

Thank you, you save me.
