### ISSUE TITLE
Get the hashtags a profile follows

### ISSUE THREAD

**Issue by pdinnen** [instaloader/instaloader#875]
**Provide us a use case of the feature**
Similar to Profile.get_followees() but for the hashtags a profile follows instead of users.

**Describe the solution you'd like**
A direct equivalent of get_followees()

**If the feature request is accepted, would you be willing to submit a pull request?**
I'd love to. But I don't think you want my low-grade code polluting your project :)

**Additional context**
This functionality may be in the project somewhere. I can't see it in docs or taking a look through the code. 

The query to get the data I'm referring to looks like:
https://www.instagram.com/graphql/query/?query_hash=e6306cc3dbe69d6a82ef8b5f8654c50b&variables=%7B%22id%22%3A%226344354573%22%7D

**Comment by aandergr** [comment]
That would be a nice feature.

Thanks for already showing us a query that provides the data. get_followees() seems a good example how such a query could be implemented. It seems the edge_extractor for the query you provided would be `lambda d: d['data']['user']['edge_following_hashtag']`.

> **If the feature request is accepted, would you be willing to submit a pull request?**
> I'd love to. But I don't think you want my low-grade code polluting your project :)

No need to worry about that, pull requests are reviewed before we click on the merge button :)

**Comment by FadiBitar** [comment]
I'm here to upvote this feature request! I thought I'd be able to hack it into my own local version of instaloader in the meantime but I'm not sure I really know what I'm doing 😬  (what's a query hash and where do you get one?)
