### ISSUE TITLE
thaw post_iterator: AttributeError: 'list' object has no attribute 'query_hash'

### ISSUE THREAD

**Issue by MrTomRod** [instaloader/instaloader#876]
I want to be able to resume a scrape using the `freeze` and `thaw` functions, as explained [here](https://instaloader.github.io/module/nodeiterator.html#nodeiterator).

However, I get an error. Is this a bug or am I making a mistake?

**To Reproduce**
```python3
import os
import json
import instaloader


username ='lincolnredimpsfc'

freezer = '/tmp/resume_information.json'

L = instaloader.Instaloader()

profile = instaloader.Profile.from_username(L.context, username=username)

post_iterator = profile.get_posts()

if os.path.isfile(freezer):
    print('resuming...')
    with open(freezer) as f:
        post_iterator.thaw(json.load(f))

for p in post_iterator:
    # do something...

    # freeze post_iterator
    with open(freezer, 'w') as f:
        json.dump(post_iterator.freeze(), f)
```

**Traceback**

```
Traceback (most recent call last):
  File "/project/socialmediascraper/main.py", line 25, in <module>
    load_instagram()
  File "/project/socialmediascraper/main.py", line 20, in load_instagram
    instagram_scraper.analyze_profile(username)
  File "/project/socialmediascraper/instagram/InstagramScraper.py", line 93, in analyze_profile
    post_iterator.thaw(json.load(f))
  File "/venv/socialmediascraper/lib64/python3.8/site-packages/instaloader/nodeiterator.py", line 191, in thaw
    if (self._query_hash != frozen.query_hash or
AttributeError: 'list' object has no attribute 'query_hash'
```

Indeed, there is no string `query_hash` in `resume_information.json`.

**Comment by coderektor** [comment]
Hi. I am tried to implement Thaw & Freeze functionality in My code as Well, but I wasn't successful. Please, Could You help me Out?

This is my Code:

import instaloader

L = instaloader.Instaloader(download_pictures=False,
download_videos=False,
download_video_thumbnails=False,
download_geotags = False,
download_comments = False,
compress_json=False,
post_metadata_txt_pattern=""
)

posts = instaloader.Hashtag.from_name(L.context, 'sunup').get_posts()

users = set()

for post in posts:
if not post.owner_profile in users:
L.download_post(post, '#sunup')
users.add(post.owner_profile)
else:
print("{} from {} skipped.".format(post, post.owner_profile))

**Comment by MrTomRod** [comment]
Freeze and thaw seem to be broken.

Had to find another way to store my progress.

**Comment by coderektor** [comment]
> Freeze and thaw seem to be broken.
> 
> Had to find another way to store my progress.

That's Awesome. Please, Share Your knowledge about it. Thanks.

**Comment by MrTomRod** [comment]
I just made it very slow and let it run for 2 days. It may not work for you, if you need more data.

**Comment by coderektor** [comment]
Got it!

By the way, Is there a Method to get the Profiles of all those who like a post on Instagram?

**Comment by aandergr** [comment]
As already indicated in the traceback you posted, the call to thaw() in your code is faulty.

The signature of thaw() is as follows:

https://github.com/instaloader/instaloader/blob/e70faf506dfec440c0442e0fcda2f07df7263c91/instaloader/nodeiterator.py#L179

It expects to be passed a `FrozenNodeIterator` object, whereas your code passes a `list`.

You might want to create a FrozenNodeIterator out of your JSON data, for example as follows.

```python
if os.path.isfile(freezer):
    print('resuming...')
    with open(freezer) as f:
        post_iterator.thaw(instaloader.FrozenNodeIterator(*json.load(f)))
```

Alternatively, there are convenient ready-to-use type-aware manners of serializing/deserializing data, such as Instaloader's [save_structure_to_file() and load_structure_from_file()](https://instaloader.github.io/module/structures.html#loading-and-saving) or Python's [pickle](https://docs.python.org/3/library/pickle.html).

**Comment by MrTomRod** [comment]
Thanks! Consider changing the [example code](https://instaloader.github.io/module/nodeiterator.html#nodeiterator) as follows:

```python3
post_iterator = profile.get_posts()
try:
    for post in post_iterator:
        do_something_with(post)
except KeyboardInterrupt:
    with open('resume_information.json', 'w') as f:
        json.dump(post_iterator.freeze(), f)
```

and

```python3
post_iterator = profile.get_posts()
with open('resume_information.json') as f:
    post_iterator.thaw(instaloader.FrozenNodeIterator(*json.load(f)))
```

**Comment by aandergr** [comment]
Thanks for that comment. However, I think the documentation is fine at this place, using generic black box load() and save() functions. Also, Instaloader is completely typed, making it trivial for the user to spot this kind of mistake, at the latest when being pointed to the exact line in a error traceback.

**Comment by MrTomRod** [comment]
Just to clarify my confusion:

I understood that I needed a `FrozenNodeIterator` object. but I didn't know how to create one.

That wasn't obvious from the code, although I could have figured it out by studying the docs better. At one point, there is this code: `FrozenNodeIterator(**json.load(open(path)))`
