### ISSUE TITLE
Downloading age-restricted profiles?

### ISSUE THREAD

**Issue by cacquejousteau** [instaloader/instaloader#880]
Hello! I'm trying to download the profiles for various alcohol brands and have been unsuccessful thus far. For example:

PS C:\Users\x> .\instaloader greygoose
JSON Query to greygoose/feed/: 404 Not Found [retrying; skip with ^C]
JSON Query to greygoose/feed/: 404 Not Found [retrying; skip with ^C]
greygoose: Profile greygoose does not exist.
The most similar profiles are: greygoosejlu, greygoosecat, greygooseconnoisseur, greygoose_goldens, jimothylacoste.

I thought the age verification on alcohol pages might block downloads, so I signed in via Instaloader to see if that would bypass it (I'm 21+, follow these pages from my account with no problem). Still no luck. I've tried many, many brands.

I can download pretty much any other public profile without issue, just stuck on these age-restricted ones. Any suggestions?

**Comment by Showmaster3000** [comment]
duplicate of #658 - have a look there.

**Comment by cacquejousteau** [comment]
Thanks! Unfortunately, my IG does have my verified age, and when I followed these accounts I was not prompted to accept the content because I pass the age-gating. If I try to download while signed in it *should* work but it still doesn't.
