### ISSUE TITLE
Have the program always running

### ISSUE THREAD

**Issue by SxS46** [instaloader/instaloader#885]
**Provide us a use case of the feature**
It would be useful to have the option to leave the program always running checking the presence of new posts to download every given minutes, with this option you can leave the program running in a docker container or a server so you won't miss any new content.

**Describe the solution you'd like**
Have the option to leave the program always running and auto download every new content

**Describe alternatives you've considered**
I tried to restart the program every few minutes but instagram is not happy with it and stops

**If the feature request is accepted, would you be willing to submit a pull request?**
No

**Additional context**
No additional context

Thank you

**Comment by Showmaster3000** [comment]
You can find a similar discussion in #792

**Comment by SxS46** [comment]
Sorry but I'm not a coder, can you guide me to implement this?

**Comment by aandergr** [comment]
> It would be useful to have the option to leave the program always running checking the presence of new posts to download every given minutes, with this option you can leave the program running in a docker container or a server so you won't miss any new content.

I don't think this is something that Instaloader itself should provide. When using [Instaloader as a Python module](https://instaloader.github.io/as-module.html) you can simply call its [download_*()](https://instaloader.github.io/search.html?q=download_) methods in a loop and wait a few minutes between iterations, keeping the Instaloader instance intact to obey the rate limits.
