### ISSUE TITLE
JSON Query to API.... HTTP error code 403

### ISSUE THREAD

**Issue by madelinekinnaird** [instaloader/instaloader#886]
I am scraping the following properties using instaloader

    processed = 1
    for post in profile.get_posts():
    	if processed > config.POSTS_PER_USERNAME:
    		break
    
    	print("...scraping info for post %s" % post.shortcode)
    
    	post_info = {
    		"shortcode": post.shortcode,
    		"username": username,
    		"date_utc": post.date_utc.strftime("%Y-%m-%d %H:%M"),
    		"url_thumbnail": post.url,
    		"url_media": post.video_url if post.is_video else post.url,
    		"is_video": "yes" if post.is_video else "no",
    		"is_sponsored": post.is_sponsored,
    		"hashtags": ",".join(post.caption_hashtags),
    		"mentions": ",".join(post.caption_mentions),
    		"caption": emoji.demojize(post.caption),
    		"video_view_count": post.video_view_count if post.is_video else 0,
    		"video_length": post.video_duration if post.is_video else 0,
    		"likes": post.likes,
    		"comments": post.comments,
    		"likes+comments": (post.likes + post.comments),
    		"location_name": post.location.name if post.location else "",
    		"location_latlong": " ".join((str(post.location.lat), str(post.location.lng))) if post.location else ""
    	}
    
    	processed += 1
    
    	post_writer.writerow(post_info)
    
    print("...scraped %i posts for %s" % (processed - 1, username))

For context, I used [this issue suggestion](https://github.com/instaloader/instaloader/issues/92) to login to instagram using my firefox session. 

My scraper seems to work, in that it seems to download each chronological post eventually, but it oftentimes showing these warning/errors (below) on the command line before downloading. Then I inevitably get the too many queries warning...

![image](https://user-images.githubusercontent.com/14099908/99995684-b88d4400-2d88-11eb-91ec-6ff7e3bac8b8.png)

What do these JSON Query messages mean, what can I do to make my scraper run better??

Here is my [current full version](https://github.com/madelinekinnaird/quantifying-greenwashing/blob/main/ig_scraper/post_scraper.py), if it is helpful.

Thank you!

**Comment by aandergr** [comment]
Hi! These *JSON Query to ...* messages mean that the query for obtaining the URL of the high-quality version of the post picture has been responded with *403 Forbidden*, which should not happen. Instaloader then retries this query up to three times, and then, as a fallback, uses the normal-quality version of the picture. These retries "consume" queries, leading to Instaloader having to wait to not exceed Instagram's rate limits. You could set the `max_connection_attempts` parameter of the Instaloader constructor to `1` to not retry failing queries, allowing to fetch more data before Instaloader's rate controller kicks in.

**Comment by madelinekinnaird** [comment]
Hi @aandergr , thanks for the response! I set the `max_connection_attempts` when I saved the session [here](https://github.com/madelinekinnaird/quantifying-greenwashing/blob/main/ig_scraper/ig_login.py), do I need to specify that again once I load the session into my scraper file?

**Comment by aandergr** [comment]
Yes. The saved session is merely a dictionary of the cookies for the instagram.com domain, it does not store any additional configuration for Instaloader. The parameters have to be specified each time Instaloader is instantiated.

**Comment by madelinekinnaird** [comment]
Ok I see, thank you! I reran with max_connection attempts set to 1 when instantiated Instaloader in my scraper file.

![image](https://user-images.githubusercontent.com/14099908/100011525-dc0fb900-2d9f-11eb-88fa-7740eaa2395d.png)


 It is unclear to me if this error is related to the JSON Query errors that I still see (but with less frequency!) or if it is something else?

**Comment by aandergr** [comment]
Seems accessing the metadata failed with a *429 Too Many Request* error for this post. Normally, Instaloader retires in such a case, but with setting max_connection_attempt to 1 we disabled retrying.
