### ISSUE TITLE
429 too many request error when running the advanced examples

### ISSUE THREAD

**Issue by ThomasAn73** [instaloader/instaloader#889]
Running instaloader on the advanced example page ([here](https://instaloader.github.io/codesnippets.html#likes-of-a-profile-ghost-followers)) repeatedly produces a 429 error. I tried it once a few days ago and then tried it again ONCE today. The error was instant on a single try.

**To Reproduce**
All I did is copy/paste the code from [here](https://instaloader.github.io/codesnippets.html#likes-of-a-profile-ghost-followers)

The code -->

```
import instaloader

def ghostFollowers (UserName):
    L = instaloader.Instaloader()

    # Load session previously saved with `instaloader -l USERNAME`:
    #L.load_session_from_file(UserName)

    profile = instaloader.Profile.from_username(L.context, UserName)

    likes = set()
    print("Fetching likes of all posts of profile {}.".format(profile.username))
    for post in profile.get_posts():
        print(post)
        likes = likes | set(post.get_likes())

    print("Fetching followers of profile {}.".format(profile.username))
    followers = set(profile.get_followers())

    ghosts = followers - likes

    print("Storing ghosts into file.")
    with open("inactive-users.txt", 'w') as f:
        for ghost in ghosts:
            print(ghost.username, file=f)

#RUN program
ghostFollowers(".... place username here....")
```

The error --> ([screen grab](https://snipboard.io/fW8Iix.jpg))

**Comment by ThomasAn73** [comment]
This is an issue because a login is required for most instaloader functionality to work. The confusion arose because the documentation mentions that login (to a main account) is optional, but in reality it is not possible to access followers/followings without being logged in to an account. It's probably an Instagram restriction.

**Comment by aandergr** [comment]
Accessing likes requires login (#860), accessing followers also does. 

> The confusion arose because the documentation mentions that login (to a main account) is optional, but in reality it is not possible to access followers/followings without being logged in to an account.

Where does the documentation mention that login is optional for that example/functionality to work?
- The ghost follower example does login.
- get_likes(): *Require being logged in (as required by Instagram).*
- get_followers(): *To use this, one needs to be logged in and private profiles has to be followed.*

> All I did is copy/paste the code from [here](https://instaloader.github.io/codesnippets.html#likes-of-a-profile-ghost-followers)

... and comment out the line that loads the session.

**Comment by ThomasAn73** [comment]
Maybe it's a documentation thing.
These are the factors that might confuse someone new:
1. As a new user I started from the beginning at https://instaloader.github.io/as-module.html
2. The comments mention "login is optional"
```
Start with getting an instance of Instaloader:

import instaloader

# Get instance
L = instaloader.Instaloader()

# **Optionally**, login or load session 
L.login(USER, PASSWORD)        # (login)
L.interactive_login(USER)      # (ask password on terminal)
L.load_session_from_file(USER) # (load session created w/
                               #  `instaloader -l USERNAME`)
```

3. Without having to investigate every single line of code against the documentation I assumed the examples page is plug-and-play. Found the examples page (https://instaloader.github.io/codesnippets.html#likes-of-a-profile-ghost-followers) and plugged-in the code to see what it does.  

The problem started due to the nature of the exception. Many methods will throw an exception that specifically says "login is required", but in this instance the exception was a 429 which created a momentary confusion.

Maybe in those example pages a basic login code ought to be included to make them plug-and-play ? Maybe something like:
```
def newInstaloaderObj (UserName, Password):
    L = instaloader.Instaloader()
    
    try: 
        L.load_session_from_file(UserName)
        print('Continuing saved session for:' + UserName)
    except:
        print('Attempting to login for:' + UserName)
        L.login(UserName, Password) 
        L.save_session_to_file()
    
    return L 
```

Also the examples do not mention the importance of save_session_to_file(). Initially I erroneously assumed that the load_session_from_file() method will save a session if one is not found because the documentation says:
```
load_session_from_file(username, filename=None)
Internally **stores** requests.Session object loaded from file.
```
