### ISSUE TITLE
How to stop all downloading after reaching the first already downloaded picture?

### ISSUE THREAD

**Issue by aaaxx** [instaloader/instaloader#890]
I thought `--fast-update` is supposed to do this, but it doesn't seem to work that way.

For example, if I have a folder containing a single picture (let's say the third most recent picture), I would expect it to download the most recent picture and the second most recent picture, and then stop when it reaches the third most recent one. However, right now, it keeps downloading all the old missing pictures.

**Comment by AplhaSlayer1964** [comment]
Just tested and --fast-update works only downloads till the last most recent photo.

**Comment by aaaxx** [comment]
Well, this is embarrassing. I was using an older version of Instaloader.

It seems to work as expected now. Sorry for wasting everyone's time.
