### ISSUE TITLE
how to retrieve posts by a hashtag?

### ISSUE THREAD

**Issue by monajalal** [instaloader/instaloader#894]
How can I download posts that are in regards to a specific hashtag? For example, how can I download all the posts with all the following metadata for the hashtag #book? I could not find it in the documents.

1. image
2. accessibility_caption
3. caption
4. Either all comments or most recent comments or most popular (upvoted) comments.

Thanks a bunch.

**Comment by AplhaSlayer1964** [comment]
https://instaloader.github.io/basic-usage.html
