### ISSUE TITLE
Where can i find the comments that where downloaded?

### ISSUE THREAD

**Issue by jschmidt1510** [instaloader/instaloader#900]
Whenever i try to download comments it only downloads the pictures and captions of each post. I am not sure where and how the comments would be saved in case it worked. Hope somebody can help.

**Comment by Deleora** [comment]
> Whenever i try to download comments it only downloads the pictures and captions of each post. I am not sure where and how the comments would be saved in case it worked. Hope somebody can help.

Comments are saved in a separate JSON files of each post
File name is something like this `2020-08-17_21-13-06_UTC_comments.json`
But if you have specified extra parameters like `--no-metadata-json` you might not see the comments file
