### ISSUE TITLE
Comments not getting collected

### ISSUE THREAD

**Issue by user101-student** [instaloader/instaloader#903]
**Describe the bug**
Instaloader is not collecting the comments

**To Reproduce**
I used Instaloader profile [profile name] --comments -V --no-pictures to collect the comments.

**Expected behavior**
The expected behavior would be to collect comments and captions according to documentation.

**Error messages and tracebacks**
It doesn't throw an error but it doesn't collect comments. It just collects the captions.

**Comment by aandergr** [comment]
Not reproducible, downloading comments works for me.

**Comment by aandergr** [comment]
Might be the bug that is reported in #910.
