### ISSUE TITLE
Freeze and resume comment collection?

### ISSUE THREAD

**Issue by alansalimov** [instaloader/instaloader#904]
Hello, I've been trying to collect comments.

With residental rotating proxies I am still getting frequent 429 errors a few pages into the comments (especially for >100 comment posts)

First off - why is this happening with a rotating proxy?

Second - how can I freeze comment iteration at that page so I can return to it at a later time instead of starting from scratch?

I've tried to just save the "after" hash and resume comment pagination from there, but I noticed the hash is different on subsequent scrapes.

**Comment by cruzdany** [comment]
> 
> 
> Hello, I've been trying to collect comments.
> 
> With residental rotating proxies I am still getting frequent 429 errors a few pages into the comments (especially for >100 comment posts)
> 
> First off - why is this happening with a rotating proxy?
> 
> Second - how can I freeze comment iteration at that page so I can return to it at a later time instead of starting from scratch?
> 
> I've tried to just save the "after" hash and resume comment pagination from there, but I noticed the hash is different on subsequent scrapes.

How did you do the rotating proxy? Could you help me with that?
