### ISSUE TITLE
Top X Posts of User¶

### ISSUE THREAD

**Issue by nafanko** [instaloader/instaloader#906]
after importing instaloader with 

pip install instaloader on terminal. on the script, i put the following:

from itertools import islice
from math import ceil

from instaloader import Instaloader, Profile

PROFILE = ...        # profile to download from
X_percentage = 10    # percentage of posts that should be downloaded

L = Instaloader()

profile = Profile.from_username(L.context, PROFILE)
posts_sorted_by_likes = sorted(profile.get_posts(),
                               key=lambda p: p.likes + p.comments,
                               reverse=True)

for post in islice(posts_sorted_by_likes, ceil(profile.mediacount * X_percentage / 100)):
    L.download_post(post, PROFILE)

>> i change the PROFILE = ... with the instagram id #820 
i am getting this error. 

  File "C:\Users\check\AppData\Local\Programs\Python\Python39\lib\site-packages\instaloader\structures.py", line 560, in from_username
    profile = cls(context, {'username': username.lower()})
AttributeError: 'int' object has no attribute 'lower'

How do I fix this? Thank you

**Comment by anton-sidorov** [comment]
You should use username instead of id.

**Comment by nafanko** [comment]
> You should use username instead of id.

thank you for your response, now when I replace the id with the name instagram.
it now says.

"PROFILE = instagram        # profile to download from
NameError: name 'instagram' is not defined "



" from itertools import islice
from math import ceil

from instaloader import Instaloader, Profile

PROFILE = instagram        # profile to download from
X_percentage = 10    # percentage of posts that should be downloaded

L = Instaloader()

profile = Profile.from_username(L.context, PROFILE)
posts_sorted_by_likes = sorted(profile.get_posts(),
                               key=lambda p: p.likes + p.comments,
                               reverse=True)

for post in islice(posts_sorted_by_likes, ceil(profile.mediacount * X_percentage / 100)):
    L.download_post(post, PROFILE) "

thank you once again for your response

**Comment by anton-sidorov** [comment]
Put username in quotes (it must be a string and without quotes "instagram" is considered a variable).

**Comment by nafanko** [comment]
thank you that worked! 

now its telling me 

>HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
JSON Query to graphql/query: 429 Too Many Requests: redirected to login [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
                              other:    1    1    1    1    1    1
   472f257a40c653c64c666ce877d59d2b:    5    5    5    5    5    5
   2b0673e0dc4580674a88d426fe00ea90:    1    1    1    1    1    1
 >*  97b41c52301f77ce508f55e66d17620e:    1    1    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader        
is running.
The request will be retried in 666 seconds, at 09:53.

there is no other instance of instagram running on my computer, what is a good work around for this?
