### ISSUE TITLE
Persistent Download Location

### ISSUE THREAD

**Issue by Kekerykek** [instaloader/instaloader#911]
Yo, is there a way to make the download location persist so I don't have to write in the save path on every run? Like how youtube-dl does it, with a configuration file or something.

**Comment by Thammus** [comment]
Instaloader does not support configuration files, but you can save some arguments to a text file and pass it to Instaloader like described in our [documentation](https://instaloader.github.io/cli-options.html?highlight=args%20txt#cmdoption-arg-args-txt).
