### ISSUE TITLE
Doesn't work with passwords that start with a hyphen

### ISSUE THREAD

**Issue by inhahe** [instaloader/instaloader#916]
**Describe the bug**
The password automatically generated for me for Instagram didn't work with Instaloader. It started with a hyphen. The error I kept getting was "instaloader: error: argument -p/--password: expected one argument", even when I tried enclosing the password in quotes.  

**To Reproduce**
Run instaloader like so: instaloader --login test --password "-test"
or like so: instaloader --login test --password -test

**Expected behavior**
The login should be successful as long as the username and password are correct. It may be understandable to error out if the password isn't enclosed in quotes, but it should at least work if it is. Otherwise you have to change your password in order to use instaloader.

**Error messages and tracebacks**
D:\>instaloader --login test --password "-a-b"
usage:
instaloader [--comments] [--geotags]
            [--stories] [--highlights] [--tagged] [--igtv]
            [--login YOUR-USERNAME] [--fast-update]
            profile | "#hashtag" | %location_id | :stories | :feed | :saved
instaloader --help
instaloader: error: argument -p/--password: expected one argument

**Instaloader version**
4.5.5

**Additional context**
Windows 10. Python 3.8.6-32.

**Comment by AplhaSlayer1964** [comment]
I know this doesn't fix the problem but it is recommended you use the session file for security reasons and you will not encounter this error. Here is a link to how to create a session file https://instaloader.github.io/troubleshooting.html#login-error

**Comment by aandergr** [comment]
> instaloader: error: argument -p/--password: expected one argument

That error message indicates that this is due to how arguments are parsed. The hyphen has a special role here, since flags start with a hypen.

The following options are expected to work:
- `instaloader --login=test --password=-a-b`,
- `instaloader --login=test` and enter password when asked.
