### ISSUE TITLE
How to get a list of the usernames that liked a comment?

### ISSUE THREAD

**Issue by ashkan-khd** [instaloader/instaloader#917]
Hello. I'm new to instaloader.
I've been using the following code to get a list of comments on a specific post:
```
    loader = Instaloader()
    insta_post = Post.from_shortcode(loader.context, SOME_POST_SHORTCODE_HERE)
    comments = insta_post.get_comments()
    # later logics here
```
it gives me a fine iterator of PostComment objects. for every comment you could use following attributes:
```
    comment.id
    comment.created_at_utc
    comment.text
    comment.owner
    comment.likes_count
    comment.answers
```
but as you can see there is no attribute that shows the usernames of those who liked each comment, there is only the number of likes on each comment.
Is there any way to get a list of usernames of those who liked a comment?

**Comment by aandergr** [comment]
Hello! The PostComment objects do not contain who liked the comment. However, when opening Instagram in a browser and monitoring the requests in the browser's DevTools, you can see that when clicking on the likes of a comment the browser does a query with query_hash `5f0b1f6281e72053cbc07909c8d154ae` that returns all the likes for a particular comment. With that information, it is easy to let Instaloader get all comment likers for us and even wrap them in a Profile structure, like so:

```python
from instaloader import *


def get_comment_likers(
    context: InstaloaderContext, post: Post, comment: PostComment
) -> NodeIterator[Profile]:
    return NodeIterator(
        context,
        "5f0b1f6281e72053cbc07909c8d154ae",
        lambda d: d["data"]["comment"]["edge_liked_by"],
        lambda n: Profile(context, n),
        {"comment_id": comment.id},
        f"https://www.instagram.com/p/{post.shortcode}/",
    )


loader = Instaloader()
insta_post = Post.from_shortcode(loader.context, SOME_POST_SHORTCODE_HERE)
comments = insta_post.get_comments()

for comment in comments:
    print(f'"{comment.text}" by {comment.owner.username} has been liked by:')
    for liker in get_comment_likers(loader.context, insta_post, comment):
        print(f" - {liker.username}")
```

**Comment by aandergr** [comment]
This would actually be nice to have as a method in `PostComment`.

**Comment by Obinnn** [comment]
> This would actually be nice to have as a method in `PostComment`.

Agreed, this would be fantastic to have!
