### ISSUE TITLE
Encountering the "429 - Too Many Requests" error with no instagram parallels running.

### ISSUE THREAD

**Issue by nafanko** [instaloader/instaloader#918]
Hello everyone! I seem to have encountered this problem. 
I am not logged in to instagram through any browser or through instaloader. 
This error comes up as soon as I input my code.

>HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
JSON Query to graphql/query: 429 Too Many Requests: redirected to login [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
other: 1 1 1 1 1 1
472f257a40c653c64c666ce877d59d2b: 5 5 5 5 5 5
2b0673e0dc4580674a88d426fe00ea90: 1 1 1 1 1 1
97b41c52301f77ce508f55e66d17620e: 1 1 1 1 1 1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 666 seconds, at 09:53.

Thank you for your help!

**Comment by AplhaSlayer1964** [comment]
Make sure your account hasn't been locked by instagram. If it hasn't, try waiting half a day and try again. If you run instaloader for like an hour you will always run into 429 sadly there is no real work around besides waiting your request ban out. I'm sure the devs are working on a better way to get around the timeouts (there are like 100+ other people asking about the same 429 error).

**Comment by nafanko** [comment]
> Make sure your account hasn't been locked by instagram. If it hasn't, try waiting half a day and try again. If you run instaloader for like an hour you will always run into 429 sadly there is no real work around besides waiting your request ban out. I'm sure the devs are working on a better way to get around the timeouts (there are like 100+ other people asking about the same 429 error).

Thank you for your reply. Would using a proxy help? Is the pull request ip related maybe? The weird thing is when I use the instaloader to just download photos from a page it'll do it, but when you use the python code to download top posts by user it crashes right away.

**Comment by AplhaSlayer1964** [comment]
So if you are using the login it seems to be a combination of ip and account. If you switch your ip a lot you account can get flagged and you are using the same ip as another account it will flag you. I recommend having a seperate account and ip for instaloader but I would be careful about making a new account and right away and using it because they seem to flag new accounts worse. My bad solution for now is running a vm with a vpn in the background that way using instagram on my pc won't affect instaloader in any way.

Sorry I don't know anything about top posts as I never use it. You may want to make a seperate bug report for that.

**Comment by nafanko** [comment]
> So if you are using the login it seems to be a combination of ip and account. If you switch your ip a lot you account can get flagged and you are using the same ip as another account it will flag you. I recommend having a seperate account and ip for instaloader but I would be careful about making a new account and right away and using it because they seem to flag new accounts worse. My bad solution for now is running a vm with a vpn in the background that way using instagram on my pc won't affect instaloader in any way.
> 
> Sorry I don't know anything about top posts as I never use it. You may want to make a seperate bug report for that.

I’m not logged in do you think that would make a difference? I’ll look into using an ip. I’ve been able to download pages and the 429 only comes up after 1500 or so downloaded items but with the top code it happens after the first photo. Thank you again

**Comment by somera** [comment]
> > So if you are using the login it seems to be a combination of ip and account. If you switch your ip a lot you account can get flagged and you are using the same ip as another account it will flag you. I recommend having a seperate account and ip for instaloader but I would be careful about making a new account and right away and using it because they seem to flag new accounts worse. My bad solution for now is running a vm with a vpn in the background that way using instagram on my pc won't affect instaloader in any way.
> > Sorry I don't know anything about top posts as I never use it. You may want to make a seperate bug report for that.
> 
> I’m not logged in do you think that would make a difference? I’ll look into using an ip. I’ve been able to download pages and the 429 only comes up after 1500 or so downloaded items but with the top code it happens after the first photo. Thank you again

I have same problem. My account is locked often. I think, that Instagram is checking more how active is an account. Sometimes some actions are locked for me when I'm using Instagram in browser.

**Comment by restyler** [comment]
> I have same problem. My account is locked often. I think, that Instagram is checking more how active is an account. Sometimes some actions are locked for me when I'm using Instagram in browser.

If you are trying to download content from public account - you should try https://rapidapi.com/restyler/api/instagram40 /proxy endpoint or just use good residential proxy to get the info, instagram still allows not logged in access for clean ips, though it is getting very hard to find good proxy. My project which gets public account and posts info works fine 95 out of 100 requests, in December 2020, via RapidAPI approach.

**Comment by somera** [comment]
> > I have same problem. My account is locked often. I think, that Instagram is checking more how active is an account. Sometimes some actions are locked for me when I'm using Instagram in browser.
> 
> If you are trying to download content from public account - you should try https://rapidapi.com/restyler/api/instagram40 /proxy endpoint or just use good residential proxy to get the info, instagram still allows not logged in access for clean ips, though it is getting very hard to find good proxy. My project which gets public account and posts info works fine 95 out of 100 requests, in December 2020, via RapidAPI approach. (This approach won't work if you need to get followers, because this requires logging in)

Thx for the info.

Or this is time to use less instagram. ;)

**Comment by aandergr** [comment]
> I am not logged in to instagram through any browser or through instaloader.
> This error comes up as soon as I input my code.
> 
> > HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
> > JSON Query to graphql/query: 429 Too Many Requests: redirected to login [retrying; skip with ^C]

Fixed with [version 4.5.5](https://github.com/instaloader/instaloader/releases/tag/v4.5.5). Generally we recommend to always ensure that the latest version of Instaloader is used when encountering a 429 error. Also see https://instaloader.github.io/troubleshooting.html.

```
pip install --upgrade instaloader
```

**Comment by litebringer** [comment]
i would suggest use another account it works.
