### ISSUE TITLE
429 Too Many Requests and locked account

### ISSUE THREAD

**Issue by somera** [instaloader/instaloader#922]
Your question here...

I'm using the current version (4.5.5). And I get often "429 Too Many Requests". After one day my Instagram account is locked. It's possible to setup sleep between every image download?

**Comment by Showmaster3000** [comment]
There are different reasons why you reach error 429. You can find multiple discussions in the issue archive, f.e. #864 #889 #834
Instaloader has a internal mechanism to throttle down if it is near the request limit.
Furthermore you do not say anythiny about your setup. How many profiles do you download? How often do you check them? Are you logged in? Do you use a proxy? And some other questions...

**Comment by somera** [comment]
> There are different reasons why you reach error 429. You can find multiple discussions in the issue archive, f.e. #864 #889 #834
> Instaloader has a internal mechanism to throttle down if it is near the request limit.
> Furthermore you do not say anythiny about your setup. How many profiles do you download? How often do you check them? Are you logged in? Do you use a proxy? And some other questions...

sorry.

I'm logged in. I start the script with

instaloader.exe --no-compress-json --login <myprofile> %%x -F

where %%x ist one profile from a list with ~200 profiles. I run it every 2-3 days.
