### ISSUE TITLE
can i save all ‘following’ profiles by my account?

### ISSUE THREAD

**Issue by rukvty** [instaloader/instaloader#924]
Hi, I would like to download all the ‘following’ profiles of my account, with their stories, highlights, igtv, tagged.

In ‘What to download’, I saw the @profile command. 
It says it is for ‘All profiles that are followed by profile, i.e. the followees of profile (requires --login).’

I tried to use it. 

1st try:
.\instaloader -l profile @profile
Loaded session from C:\Users\user\AppData\Local\Instaloader\session-profile.
Logged in as profile.
Saved session to C:\Users\user\AppData\Local\Instaloader\session-profile.
No targets were specified, thus nothing has been downloaded.

2nd try:
.\instaloader -l profile @profile profile
Then it ended up downloading profiles with a single letter ‘c’ ‘u’ ‘e’ ‘r’

So can anyone help me with this issue? Thanks a lot!

**Comment by aandergr** [comment]
Hi. With Powershell, the following should work.

```powershell
.\instaloader -l profile "@profile"
```
