### ISSUE TITLE
Can I specify the path of a Instalodader saved session?

### ISSUE THREAD

**Issue by joaopm33** [instaloader/instaloader#928]
Hello,

I managed to create an Instagram saved session file in my AppData\Local\Instaloader folder. I wanted to upload this file to a server where I use Instaloader from. The problem is: I dont have access to instalation folders in this server, so I cant drop the session file in the exact same spot.

Is it possible to load an session in a python script with the Instaloader.load_session_from_file() function with a path as an argument instead of a username?

Thanks.

**Comment by roboshim** [comment]
`instaloader --help` shows you the options and there is option
```
-f SESSIONFILE, --sessionfile SESSIONFILE
Path for loading and storing session key file.
Defaults to /home/USERNAME/.config/instaloader/session-<login_name>
```

and for the python script, the function is defined as:
`def load_session_from_file(self, username: str, filename: Optional[str] = None) -> None:`
so you can set optional parameter `filename` too.

is this answer to your question?

**Comment by joaopm33** [comment]
It does, thank you for your time and patience.

**Comment by hobzcalvin** [comment]
This feature was removed, apparently? Can we reopen this issue?
