### ISSUE TITLE
Login error: "fail" status, message "feedback_required". in a server

### ISSUE THREAD

**Issue by joaopm33** [instaloader/instaloader#929]
I have a working python script with instaloader. What I do is pretty basic: I scrap1 account follower count posts likes and comment count once a hour. 

I works like a charm in my local machine, but when deploying it to a server I am redirected to the login page. Adding the login argument, a new error happens: 

`Login error: "fail" status, message "feedback_required". `

here is my code:

```
import pandas as pd
from instaloader import Instaloader, Profile
from datetime import datetime

  loader = Instaloader(
                      user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763',
                      download_pictures=False, 
                       download_videos=False, 
                       download_video_thumbnails=False,
                       download_geotags = False,
                       download_comments = False,
                       )
  loader.login('user', 'pswd')
 
  target_profile = 'profile'
  profile = Profile.from_username(loader.context, target_profile)   
  followers = pd.DataFrame({'data':[datetime.now()], 'seguidores mush':[profile.followers]}) 
  
  profile = Profile.from_username(loader.context, target_profile)
  posts = pd.DataFrame(columns = ['post_id','date','num_likes', 'num_comments'])

  for post in profile.get_posts():
      posts.loc[len(posts_mush)] = [post.shortcode,post.date_local,post.likes, post.comments] 
```

**Comment by joaopm33** [comment]
I managed to make it work by uploading a session file to my server. I dont remembeer where I found the session file code, but here is it:
`
from glob import glob
from os.path import expanduser
from sqlite3 import connect

from instaloader import ConnectionException, Instaloader

#FIREFOXCOOKIEFILE = r"your cookie path if bellow doesnt work"
FIREFOXCOOKIEFILE = glob(expanduser("~/.mozilla/firefox/*.default/cookies.sqlite"))[0]

instaloader = Instaloader(max_connection_attempts=1)
instaloader.context._session.cookies.update(connect(FIREFOXCOOKIEFILE)
                                            .execute("SELECT name, value FROM moz_cookies "
                                                     "WHERE host='.instagram.com'"))

try:
    username = instaloader.test_login()
    if not username:
        raise ConnectionException()
except ConnectionException:
    raise SystemExit("Cookie import failed. Are you logged in successfully in Firefox?")

instaloader.context.username = username
instaloader.save_session_to_file()
`
This code creates a session file in my local machine. Then, i uploaded this file to my server and used it in my script:
`loader.load_session_from_file('user', filename='file_path')`

I dont know for how long this will work, but for now I consider this issue closed.

**Comment by LinqLover** [comment]
@joaopm33 Eight months later, could you maybe share your experiences concerning how long your session file was valid? I'm facing the same problem right now.
