### ISSUE TITLE
Download a list of profiles according to given files.

### ISSUE THREAD

**Issue by rosefun** [instaloader/instaloader#931]
Now if I download a list of profiles, I have to list them `instaloader profile [profile ...]`.

I suggest put list of profiles to a file like `txt` format, 

```
profile1
profile2
profile3
```

Then I can only read this `txt` file by  `instaloader profilefile profile_file.txt`.

**Comment by Showmaster3000** [comment]
The feature is already supported, see manual for parameter `+args.txt`
https://instaloader.github.io/cli-options.html#cmdoption-arg-args-txt
