### ISSUE TITLE
Option for correcting file modified timestamps of already downloaded media

### ISSUE THREAD

**Issue by thomas694** [instaloader/instaloader#934]
**Provide us a use case of the feature**
The user would invoke it by a new option (e.g. --correct-timestamps). It would not only check, if a file already exists, but also whether it's modified date is that of the post. In that way erroneous blog downloads from other tools could be refreshed without the need to re-download everything, especially if meta data is missing and an external script cannot be used.

**Describe the solution you'd like**
A new option that modifies the file check/download behavior to not only check if a file has already been downloaded before, but also compare the already existing file's modified date to the post's date and adjust the file time if necessary.

**Describe alternatives you've considered**
If meta data would exist, an external script could be used. But even it would exist, that may be too difficult to do for the average user.

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes

**Additional context**

**Comment by Thammus** [comment]
Timestamps do not get changed once created. Therefore it would be a barely useful feature to be able to change them afterwards. It might be better to fix the other tools rather than having Instaloader support a feature that is not useful for itself.
