### ISSUE TITLE
Automatically download new/ongoing IG-Live videos

### ISSUE THREAD

**Issue by camp2-dev** [instaloader/instaloader#935]
I've seen many questions and ways documented on how to download past / existing IGTV videos or in general a user's posts, vidoes, feed, etc.

But in my case what I'd like to do is have a constantly running instaloader process run, to check every so often if a certain user has started an IG-Live.
If they did, I'd like to download this while the stream is ongoing (or at the end, just the full thing in some way).

I'm requesting this because instead of using a way to download past IGTV  videos or Stories of a user, because the user in question rarely keeps their IG-Lives visible on their profile after they end, so anyone who's missed them ends up not being able to view them at all.

Please tell me if this is possible with the current feature-set of instaloader.
If there are any workaround that might work, I'd be happy to hear those as well.
Thanks!

**Comment by Showmaster3000** [comment]
There was a discussion in #208 some time ago. Currently I do not know any working solution, both projects mentioned there are no longer supported.
Afaik there are no plans to integrate recording of livestreams in instaloader.
Generally for live recording, you permanently have to check if there is a new live, but you are running into instagram limitations if you check too often.

**Comment by camp2-dev** [comment]
That's what I guessed in terms of limitations, so that's why I suggested/said check every 5 minutes instead of "constantly" checking.


I had a look at the two projects listed in there and they do seem relatively outdated, I'll see if I can find any leads but for now I'm still looking.

Thanks for the info though.
