### ISSUE TITLE
Keep an ATOM feed update for each folder

### ISSUE THREAD

**Issue by somini** [instaloader/instaloader#938]
**Describe the solution you'd like**
Everytime you create or update a folder (hashtag, profile, etc), generate a valid ATOM feed with all the existing media files.

**Describe alternatives you've considered**
This can be sort-of worked around with a wrapper script.

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes

**Comment by aandergr** [comment]
> **Describe alternatives you've considered**
> This can be sort-of worked around with a wrapper script.

This should be the way to go then. I do not see any need to have this supported by Instaloader.
