### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by P-T1ps** [instaloader/instaloader#941]
Error:

JSON Query to api/v1/media/2382353258200128313/info/: HTTP error code 403. [retrying; skip with ^C]
JSON Query to api/v1/media/2382353258200128313/info/: HTTP error code 403. [retrying; skip with ^C]
JSON Query to api/v1/media/2382353258200128313/info/: HTTP error code 403. Unable to fetch high quality image version of <Post CEP0aqEg1s5>.
Targets.PERSON\2020-08-23_21-37-41_UTC.jpg exists [sunsets;)] unchanged geo 
JSON Query to graphql/query: Redirected to login [retrying; skip with ^C]
Requests within last 10/11/20/22/30/60 minutes grouped by type:
                              other:    3    3    3    3    3    3
                             iphone:    3    3    3    3    3    3
   aaaa:    1    1    1    1    1    1
 * bbbb:    1    1    1    1    1    1
Instagram responded with HTTP error "429 - Too Many Requests". Please
do not run multiple instances of Instaloader in parallel or within
short sequence. Also, do not use any Instagram App while Instaloader
is running.
The request will be retried in 666 seconds, at 00:47.
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/

I am not on my phone or anything just instaloader is running

**Comment by aandergr** [comment]
Welcome to the community! Please see [Reporting Bugs](https://instaloader.github.io/contributing.html#reporting-bugs) for how to report a bug. There is little chance to understand an issue if the requested information is missing.
