### ISSUE TITLE
Image download count

### ISSUE THREAD

**Issue by b3z** [instaloader/instaloader#943]
I want to download the first 6 images of a profile.

So rn I am this far.

```
instaloader --post-filter="not is_video" myProfile --no-metadata-json --no-captions --no-compress-json
```

Now I want to restrict with `--count 6` but that's not possible as the documentation states. So how would I handle this?

**Comment by miclejackson12** [comment]
I have the same problem.
I dont know why they are not allowing count for profile.
Count is there for feed, hashtags and location

**Comment by b3z** [comment]
Unfortunately noone cares :(
