### ISSUE TITLE
How to add delay / sleep between download(s) to avoid suspicious activity?

### ISSUE THREAD

**Issue by skeith** [instaloader/instaloader#944]
I was trying to download 6761 items but after reaching 200ish downloaded post, Instagram starts to notice bot-like behavior and mark my account as suspicious (temporary locked until password change is done).

Is there a way to make the script delay / sleep between download(s) to make it more human-like?

**Comment by almondWilde** [comment]
You can specify a rate controller as a param to instaloadercontext, (https://instaloader.github.io/module/instaloadercontext.html#ratecontroller)

**Comment by skeith** [comment]
> You can specify a rate controller as a param to instaloadercontext, (https://instaloader.github.io/module/instaloadercontext.html#ratecontroller)

Any command line option already made for this? because I couldn't find any when search the documentation

**Comment by almondWilde** [comment]
Nope, it looks like the rate controller feature is only part of the python module

**Comment by skeith** [comment]
> Nope, it looks like the rate controller feature is only part of the python module

Would it be fair if I were to request sleep/delay/rate limit feature implemented as command line option? or maybe as the default behaviour?

**Comment by almondWilde** [comment]
i like the idea of having that as a command line argument. The instaloadercontext file has a default RateController class, one could update the sleep() paramaters at initialization of the instaloader

**Comment by vanishinggradient** [comment]
`
class MyRateController(instaloader.RateController):
	
	def sleep(self, secs:30):
		wait_time=random.uniform(30, 120)
		print(wait_time)
		# time.sleep(secs)
		time.sleep(wait_time)
	
    def count_per_sliding_window(self, query_type):
        return 20

loader = instaloader.Instaloader(rate_controller=lambda ctx: MyRateController(ctx))
`

Is the above code block a correct use of the rate_controller as a param function?

**Comment by skeith** [comment]
I found that if after starting instaloader, we go to instagram website -> settings -> login activity, then acknowledge instaloader login activity, Instagram won't flag your account.

I am currently at 677 download and still going.

**Comment by estatistics** [comment]
@vanishinggradient on linux i made a python file with your code. 
then `python3 ./instaloader_wait.py` in directory of instaloader. 


however i got relative path error.
I removed all dots `from .file import module` --> `from file import module` in order to fix relative path

however, i got now circular error. What i made wrong?

**Comment by tari3x** [comment]
Following advice from @vanishinggradient I just modified instaloadercontext.py in place and was able to download a 1300k profile without getting blocked.
```
    def sleep(self, secs: float):
        wait_time = random.uniform(10, 20)
        print(wait_time)
        time.sleep(wait_time)
```

Also further down I had to remove the guard condition from all occurrences of 
```
if waittime > 0 self.sleep(waittime)
```

**Comment by parametricCHAOS** [comment]
> Following advice from @vanishinggradient I just modified instaloadercontext.py in place and was able to download a 1300-post profile without getting blocked.
> 
> ```
>     def sleep(self, secs: float):
>         wait_time = random.uniform(10, 20)
>         print(wait_time)
>         time.sleep(wait_time)
> ```
> 
> Also further down I had to remove the guard condition from all occurrences of
> 
> ```
> if waittime > 0 self.sleep(waittime)
> ```

can you explain what you meant by the last quote about the guard condition?
which part did you remove as in the quote its incorrect syntax so im confused as what to modify

**Comment by sapphirepro** [comment]
Someone got it solved? I still need solution. There was a solution long ago in pull request but author dropped it seems. Instagram bans account withing some 20 images in a row downloaded. I need 2-5 seconds wait between every image processing

**Comment by tari3x** [comment]
This work well for me:  
https://github.com/instaloader/instaloader/pull/2177

If someone would care to bring into shape that gets accepted, I'd appreciate!

**Comment by sapphirepro** [comment]
> This work well for me: #2177
> 
> If someone would care to bring into shape that gets accepted, I'd appreciate!

Thanks. I also added this to mine. But what I fail to find, is dalay between photos/videos. One from pull request you mentioned affects delays between posts (which can be for example 10 videos in a bunch and instagram still counts it bot like if downloaded too fast those), so ideally need slow down between images/videos from same post as well, but I fail to find where to change that. I am senior at C++, but noob at python
