### ISSUE TITLE
instaloader --login

### ISSUE THREAD

**Issue by drapelli** [instaloader/instaloader#945]
how can i do to create a login session in instaloader.
i use python and i need kwon how i create 

thansk

**Comment by Showmaster3000** [comment]
on command line type ``python instaloader.py --login xxx`` where xxx is the username you want to use for downloading.
scripting examples are in the src repo: https://github.com/instaloader/instaloader/tree/master/docs/codesnippets

**Comment by drapelli** [comment]
thanks
i want save the sassion on thee code note call externally
its possible




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remetente
notificado por
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
30/12/20
19:55:00

Em seg., 28 de dez. de 2020 às 19:18, Showmaster3000 <
notifications@github.com> escreveu:
