### ISSUE TITLE
Redirecting to login

### ISSUE THREAD

**Issue by harshjadon9** [instaloader/instaloader#946]
*ubuntu
**command**
`instaloader --no-compress-json --no-metadata-json --no-captions --dirname-pattern=/django/instaloader/static/downloads/{profile} --filename-pattern={shortcode} -- -CJPM6GKJI_a`

**error**
```
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
-CJPM6GKJI_a: Redirected to login page. Use --login.

Errors or warnings occurred:
-CJPM6GKJI_a: Redirected to login page. Use --login.
```

**Comment by restyler** [comment]
In case you try to access public account and don't want to log in, try clean residential proxy or https://rapidapi.com/restyler/api/instagram40 which uses proxy network balancer and response health checks.
