### ISSUE TITLE
Download Story Only?

### ISSUE THREAD

**Issue by DReaper** [instaloader/instaloader#949]
Currently, you can run the --stories command to download stories alongside the posts. However, with all the 429 errors lately, I figured running for stories often, while running for posts more infrequently would help out.

Is it possible for Instaloader to run for stories only, or is there an existing command that has this? Thank you.

**Comment by Showmaster3000** [comment]
Yes, this is possible.
There is an old (no longer documented but still working) parameter  ``--stories-only`` but this is deprecated.
Instead use ``--stories`` in combination with ``--no-posts`` to exclude posts (introduced in version 4.1)
manual: https://instaloader.github.io/cli-options.html?highlight=posts#cmdoption-no-posts
