### ISSUE TITLE
Redirected to login page. Use --login.

### ISSUE THREAD

**Issue by ky456** [instaloader/instaloader#951]
HTTP redirect from https://www.instagram.com/explore/tags/motorcyclephotos/ to https://www.instagram.com/accounts/login/
Get hashtag #motorcyclephotos: Redirected to login page. Use --login.

Errors or warnings occurred:
Get hashtag #motorcyclephotos: Redirected to login page. Use --login.

After downloading so much photos i got this error. İ logined it won't working.

**Comment by arquicanedo** [comment]
I just started using this library recently but I'm getting the same error message. I successfully logged in already but keep getting this error:

```
raise LoginRequiredException("Redirected to login page. Use --login.")
instaloader.exceptions.LoginRequiredException: Redirected to login page. Use --login.

```

**Comment by arquicanedo** [comment]
I was able to get Hashtags by logging in and using `load_session_from_file(MYUSERNAME)` prior to fetching any hashtags.

**Comment by aandergr** [comment]
Welcome to the community! Please see [Reporting Bugs](https://instaloader.github.io/contributing.html#reporting-bugs) for how to report a bug. There is little chance to understand an issue if the requested information is missing.

**Comment by ivmhub** [comment]
Also in my case if I try to download without the login it gives me an error but if I use the login it works perfectly.
i tried to upgrade instaloader but nothing has changed.

**Comment by bishalnepali** [comment]
Any other way to get the hashtags without login > 🗡️

**Comment by RAiZ0K** [comment]
me too
