### ISSUE TITLE
Add fast update to highlight and tagged options

### ISSUE THREAD

**Issue by blablable123456** [instaloader/instaloader#952]
**Provide us a use case of the feature**
Avoid manually deleting highlighted photos downloaded again. An example of an option would be --fast-update-h/--fast-update-t

**Describe the solution you'd like**
Since fast-update only work on feed photos, I'd like to have an option to just work the same way on highlights sections and tagged ones since it goes through everyone over and over.

**Describe alternatives you've considered**
Delete all old files and just keep the most recent ones.

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes, but I don't have time right now since im working two jobs.

**Comment by aandergr** [comment]
> **Describe the solution you'd like**
> Since fast-update only work on feed photos, I'd like to have an option to just work the same way on highlights sections and tagged ones since it goes through everyone over and over.

`--fast-update` should already work both with highlights and tagged.

**Comment by blablable123456** [comment]
oh well, didn't know about that. thanks.
