### ISSUE TITLE
Owner_ID error

### ISSUE THREAD

**Issue by DankMemeGuy** [instaloader/instaloader#955]
**Describe the bug**
I am downloading a list of users and when it attempts to download the first user it shoots the traceback error. I have tried other usernames with no luck. It says 'successfully logged in as <usernmame>' prior to this error.

**To Reproduce**
instaloader --dirname-pattern=Users/{profile}_{owner_id} +users.txt

**Expected behavior**
Download the user to the folder inside Users with their username_userid folder name.

**Error messages and tracebacks**
```
Traceback (most recent call last):
  File "__main__.py", line 462, in <module>
  File "__main__.py", line 459, in __main
  File "__main__.py", line 429, in main
  File "__main__.py", line 167, in _main
  File "instaloader\instaloader.py", line 1040, in check_profile_id
  File "instaloader\instaloader.py", line 1007, in _get_id_filename
KeyError: 'owner_id'
[35596] Failed to execute script __main__
```

**Instaloader version**
4.5.5 on Windows 10

**Additional context**

**Comment by Showmaster3000** [comment]
As described in the [manual](https://instaloader.github.io/basic-usage.html#filename-specification), ``--dirname-pattern`` supports ``{target}`` and ``{profile}``. The list down below refers to ``--filename-pattern``.

**Comment by DankMemeGuy** [comment]
> As described in the [manual](https://instaloader.github.io/basic-usage.html#filename-specification), `--dirname-pattern` supports `{target}` and `{profile}`. The list down below refers to `--filename-pattern`.

Ahh. Can you convert this into a feature request then?

**Comment by aandergr** [comment]
> Ahh. Can you convert this into a feature request then?

Why would anyone need this as a feature? Can't you just use `--dirname-pattern=Users --filename-pattern={profile}_{owner_id}/{date}_UTC` like described in the documentation?
