### ISSUE TITLE
How to make all tagged/stories/etc go inside their user folder

### ISSUE THREAD

**Issue by DankMemeGuy** [instaloader/instaloader#956]
I have it set to --dirname-pattern=Users/{profile}, however when I'm downloading tagged/stories/highlights/etc it will put it inside that /Users/ folder instead of the /Users/profile/ folder. Is there a way to to create the username folder, then have all their content in that folder only?

For example I could be downloading 2 users but end up with 50 folders in the Users folder.

**Comment by Deleora** [comment]
I think by default Instaloader downloads each profile in separate folders with folder names in `username` format.
So let's say you are trying to download 2 profiles `therock` and `tomcruise`. If you don't specify `--dirname-pattern` attribute, there will be 2 folders created named `therock` and `tomcruise` for respective profiles and all other stuff will be download inside these folders.

**Comment by MrJmpl3** [comment]
I made a script with the commands, maybe help you: https://github.com/MrJmpl3/social-scraper-downloader-organizer

**Comment by DankMemeGuy** [comment]
> I think by default Instaloader downloads each profile in separate folders with folder names in `username` format.
> So let's say you are trying to download 2 profiles `therock` and `tomcruise`. If you don't specify `--dirname-pattern` attribute, there will be 2 folders created named `therock` and `tomcruise` for respective profiles and all other stuff will be download inside these folders.

That isn't what I meant. 

Lets say you set a directory called 'users' and download "tomcruise"

With /users/ there will be every user that tagged tomcruise, etc instead what should happen is that all the tagged photos, highlights, etc goes inside /users/tomcruise

does that make sense? To test this create a folder called Users, and download TomCruise including highlights, stories etc. In a perfect scenrario the users folder should ONLY have 1 folder, and that is called "tomcruise" and inside THAT folder will be a "tagged" folder, "highlights" folder, etc.
