### ISSUE TITLE
HTTP redirect when downloading json file

### ISSUE THREAD

**Issue by EpiPhobe** [instaloader/instaloader#960]
**Describe the bug**
I am trying to use Instaloader to download the thousands of tagged posts of a user, with the help of resumable iterations but I am only able to do about 100 to 200 a day before the json files are skipped due to a HTTP redirect message.

**To Reproduce**
I am using the following instaloader settings to download tagged posts:
`L = instaloader.Instaloader(download_comments = False, compress_json = False)`
And the following code:
```
for post in post_iterator:
    try:
        L.download_post(post, target = foldername)
```

**Expected behavior**
I expect Instaloader to download all three parts of the post: the post image/videos, the caption in a txt file, and the metadata as an uncompressed json file: 
`targetdir\2020-01-01_01-01-01_UTC.jpg [Post Caption1] json`
Currently, Instaloader does this for about 150 posts before only downloading the image/video and caption, and skipping the json file completely.

**Error messages and tracebacks**
```
targetdir\2020-01-01_01-01-01_UTC.jpg [Post Caption1]
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/

targetdir\2020-02-02_02-02-02_UTC.jpg [Post Caption2]
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/

targetdir\2020-03-03_03-03-03_UTC.jpg [Post Caption3]
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
```
(does this for remaining posts until I interrupt the program)

**Instaloader version**
4.5.5

**Additional context**
The reason for `try:` in my for loop is due to several posts not downloading due to missing images.

**Comment by aandergr** [comment]
Thanks for your bug description!

It seems that `Post._obtain_metadata()` currently fails when not being logged in, resulting in this HTTP redirect and throwing a `LoginRequiredException` with this message. Instaloader needs to do this call e.g. when downloading a sidecar post (a post that contains multiple media) or a video post that is not on the first page of a profile.

This bug is also reproducible by running `instaloader` in its default configuration on any profile target that has sidecars or videos, or on a single post.

We changed the query in `Post._obtain_metadata()` with #727, back then to fix access from VPNs, Tor, cloud servers, etc.. Going back to the original `p/{shortcode}/` query will fix this issue.

**Comment by EpiPhobe** [comment]
Thank you for your reply!

I am sorry if this is straight forward, but how would I go back the the original `p/{shortcode}/` query?

**Comment by aandergr** [comment]
This requires a code change in Instaloader unfortunately, it cannot be easily done from the user side.

**Comment by aandergr** [comment]
To me it seems that this works again (v4.6) without that we changed anything – I can no longer reproduce the here-described problem. Downloading post metadata anonymously currently works fine for me.

In case it doesn't work for you, I pushed a commit to get the post metadata with a different query. It can be installed with:
```
pip3 install --upgrade git+https://github.com/instaloader/instaloader@fix/anonymous-post-metadata
```

However, since it currently seems well as is, I will not merge this commit into master.

**Comment by EpiPhobe** [comment]
I also believe that with v4.6, I have not been able to encounter this problem. But thank you, I will make sure to use your fix in case I ever face this issue again.

**Comment by Jong-Sig** [comment]
> To me it seems that this works again (v4.6) without that we changed anything – I can no longer reproduce the here-described problem. Downloading post metadata anonymously currently works fine for me.
> 
> In case it doesn't work for you, I pushed a commit to get the post metadata with a different query. It can be installed with:
> 
> ```
> pip3 install --upgrade git+https://github.com/instaloader/instaloader@fix/anonymous-post-metadata
> ```
> 
> However, since it currently seems well as is, I will not merge this commit into master.

I just encountered the problem (v.4.6.1).
```
HTTP redirect from https://www.instagram.com/graphql/query to https://www.instagram.com/accounts/login/
Traceback (most recent call last):
  File "post_info_mass_extension_200.py", line 240, in <module>
    unwrap_function(x)
  File "post_info_mass_extension_200.py", line 233, in unwrap_function
    obj.extract_info()
  File "post_info_mass_extension_200.py", line 169, in extract_info
    for post in takewhile(lambda p: p.date > until, dropwhile(lambda p: p.date > since, posts)):
  File "C:\Users\jc88876\Desktop\Anaconda3\lib\site-packages\instaloader\nodeiterator.py", line 129, in __next__
    query_response = self._query(self._data['page_info']['end_cursor'])
  File "C:\Users\jc88876\Desktop\Anaconda3\lib\site-packages\instaloader\nodeiterator.py", line 98, in _query
    self._context.graphql_query(
  File "C:\Users\jc88876\Desktop\Anaconda3\lib\site-packages\instaloader\instaloadercontext.py", line 416, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "C:\Users\jc88876\Desktop\Anaconda3\lib\site-packages\instaloader\instaloadercontext.py", line 324, in get_json
    raise LoginRequiredException("Redirected to login page. Use --login.")
instaloader.exceptions.LoginRequiredException: Redirected to login page. Use --login.
```

**Comment by aandergr** [comment]
@Jong-Sig This looks like a different issue. Could you please create a bug report for that?

**Comment by Jong-Sig** [comment]
> @Jong-Sig This looks like a different issue. Could you please create a bug report for that?

Thanks for letting me know! I created a new bug report.
