### ISSUE TITLE
How can get all of the images in Instagram posts with multiple images (or videos)?

### ISSUE THREAD

**Issue by valakhosravi** [instaloader/instaloader#963]
I'm using **Instaloader** to develop an Instagram scraper bot. here's part of my code that is getting images url from install by each profile:

    def scrapImageAddresses(PROFILE):
        print(PROFILE)
        L = Instaloader()
        L.login('####', "####")
        profile = Profile.from_username(L.context, PROFILE)
        imageList = []
        for post in profile.get_posts():
            imageList.append({
                'url': post.url,
                'media_id': post.mediaid
            })
        return imageList
But for a post like [this][1], it only gets the **first** image of the post. I want **all** images in the post.
How can I do that?

  [1]: https://www.instagram.com/p/CH3R89pAG7B/

**Comment by ashkan-khd** [comment]
I had sort of the same problem.
I think you should use ``get_sidecar_nodes()`` method. in your case:
```
    for post in profile.get_posts():
        pictures = []
        for node in post.get_sidecar_nodes():
            pictures.append(node.display_url)
        if len(pictures) == 0:
            pictures.append(post.url)
        imageList.append({
            'pictures': pictures,
            'media_id': post.mediaid
        })
```
please note that ``get_sidecar_nodes()`` is a generator and works only if the post itself has more than one picture. that's why ``if len(pictures) == 0`` is used in the code above.

**Comment by nripendratimilsina** [comment]
```
imageList = []
for post in profile.get_posts():
    if(post.mediacount>1):
      urls=[]
      for node in post.get_sidecar_nodes():
        urls.append(node.display_url)
      imageList.append({
          'urls':urls,
          'caption':post.caption,
      })
    else:
      imageList.append({
            'urls': [post.url],
            'caption': post.caption
        })
```
Check the media count of each post and if a post has over one content, then only **get_sidecar_nodes()** is used.
