### ISSUE TITLE
Comments failing with a silent login redirect (invalid json) after N paginations

### ISSUE THREAD

**Issue by alansalimov** [instaloader/instaloader#965]
**Describe the bug**
 
Up until several days ago I was having no problems running my scraper using rotating res proxies per request. Then all of a sudden my rate of silently redirects (instead of JSON, an html login, with **status code 200**) page shot through the roof and I couldn't get more than at max 1000 comments for any post.

**To Reproduce**
A simple get_comments() on a post with a lot of comments.

**Expected behavior**
I expected the paginations to continue without any silent redirects

**Error messages and tracebacks**
`JSON Query to graphql/query: Expecting value: line 1 column 1 (char 0) [retrying; skip with ^C]`,
majority of comment paginations. 

**Instaloader version**
`4.6` output.

**Additional context**

I tried to change the query hash in `structures.py:462` to `bc3296d1ce80a24b1b6e40b1e72903f5` as I found in my browser. No change. Our headers are automatically taken care of. I set retries to 15 and got a lot of wasted requests. Absolutely no problems until a few days ago.

**Comment by aandergr** [comment]
Why did you close this issue? Has the problem been resolved?

**Comment by alansalimov** [comment]
It was resolvable via a different proxy settings, but it leads me to ask - how long until an `end_cursor` stales on instagram? If I get the end cursor for `N` comment page, how long until it's no longer valid?

**Comment by aandergr** [comment]
Alright, thanks for the update!

> how long until an `end_cursor` stales on instagram? If I get the end cursor for `N` comment page, how long until it's no longer valid?

I do not know that for sure, but I have never seen one expire. The resumable iterator feature, which depends on the validity of the end_cursor as they are used to resume an iteration, does have a "best before date" with a shelf life of about 30 days, but the limiting factor here is the validity of post media URLs rather than the validity of the end_cursor.
