### ISSUE TITLE
Download all stories :stories .. error if two profiles shared a story at same_time

### ISSUE THREAD

**Issue by boboyoyo7** [instaloader/instaloader#966]
Hi,

My question is about downloading stories.
When the user downloads stories from the list of followed profiles, what happens if two users shared a story at the exact same time(which is very possible), would the program generate an error?
I think he should because when stories are download, they have this format: 2021-01-09_21-57-39_UTC.mp4, date-UTC.ext
and this means that stories are distinguished only by their date and extension(jpg/mp4).
I think this is problematic!

Personally, I will try to create a directory for each followed accounts inside of the :stories directory. Or save the name of the followed account in the name of the downloaded file.

I hope I was clear,
Thanks, Great project!

**Comment by boboyoyo7** [comment]
Fixed for my part! But for upcoming users in order to distinguish between downloaded items you should modify the filename here https://github.com/instaloader/instaloader/blob/3fe6b1e139eccb26f2322f5353b515dcf153d7ea/instaloader/instaloader.py#L197

**Comment by aandergr** [comment]
See [Filename Specification](https://instaloader.github.io/basic-usage.html#filename-specification) in our documentation for how to customize the filenames.
