### ISSUE TITLE
Number of likes per post yielding '-1' instead of actual number 

### ISSUE THREAD

**Issue by harrisoncomfort3030** [instaloader/instaloader#968]
Hi there, 

Thank you for creating this amazing project, the documentation is great !
I am just struggling when using the post.likes query.
I am getting a '-1' for the answer to post.likes.

For background:

- I am logged in
- I define a UserName
- I run this code:

profile = instaloader.Profile.from_username(L.context, USERNAME)
posts = profile.get_posts()
for post in posts:
      likes = post.likes
      print(likes)

And it just repeats as "-1"

Has anyone come across this before? Please advise and I appreciate the consideration !!!

**Comment by Showmaster3000** [comment]
Maybe it has something to do with Instagram's plans to remove the counter? Their plan is to not show the amount of likes anymore. Which number do you see if you open the post in browser or app?
Btw. it helps to mention the profile/post you get this problem, if its not a privacy thing for you.

**Comment by harrisoncomfort3030** [comment]
Thank you so much for the response ! 
That makes sense.
In browser, it just says liked by "[user profile] and others"
The account in question I was looking at is a public: @champagnepapi 
I guess the punchline is that Instagram won't allow us to know the number of likes on a post?

**Comment by Showmaster3000** [comment]
Ok, just checked the profile you mentioned: in not logged-in browser I can see like counts (about 500k to 1,5m). Maybe there is another problem or Instagram is just behaving different for you and me. 
Yeah, I read about the plan to hide the like count. But I don't know the current situation, it was a test back in end of 2019.

**Comment by harrisoncomfort3030** [comment]
Do you have a US account by chance? I believe that for US accounts this feature has been introduced (not seeing number of likes on a post) but not for non-US ones.

**Comment by Showmaster3000** [comment]
No, sorry. I'm located in Germany and I didn't experiment with proxies or vpn to access Instagram. But I think I also saw that "[user profile] and others" in the app on my smartphone some time ago. So I think we sooner or later will see the counter nowhere anymore.
An interesting thing would be, what happens if it makes a difference when you anonymously access the profiles.
