### ISSUE TITLE
How to upgrade to latest version?

### ISSUE THREAD

**Issue by creativehelm** [instaloader/instaloader#97]
Hello,

Just trying to upgrade via pip3 in Terminal passing '--upgrade', but I'm getting an error: 

'unrecognized arguments: --upgrade'

What I'm trying: 'instaloader --upgrade'

**Comment by MatthieuBonenfant** [comment]
you are missing the word install i think

pip3 install —upgrade instaloader-master.zip

**Comment by aandergr** [comment]
To upgrade to a newer Instaloader release, do
```
pip3 install --upgrade instaloader
```
