### ISSUE TITLE
Empty results regarding following and followers from Profile

### ISSUE THREAD

**Issue by raphaelbernardino** [instaloader/instaloader#970]
**Describe the bug**
The last update (v4.6) may have broke something in the ``get_followees()`` and ``get_followers()`` functions from ``Profile``. It is returning an empty ``sorted``.

**To Reproduce**
```
L = Instaloader()
L.login(user, pwd)
P = Profile.from_username(L.context, target_username)
following = P.get_followees()
following_sorted = sorted(following, key=lambda x: x.userid)
```

**Expected behavior**
Even though the ``target_username`` has a public profile that returns an empty list, which is kinda weird. Every profile that I tested returned an empty list, but I can provide some usernames if you need them.

**Error messages and tracebacks**
I couldn't find a way to enable verbose output.

**Instaloader version**
4.6

**Additional context**
The old version 4.5.5 was working fine. Maybe recently Instagram updated some directives? All I know is Whatsapp and Facebook are "merging" information, so Instagram can be doing that too?

**Comment by aandergr** [comment]
Hi! That is strange, both get_followers() and get_followees() seem to work fine for me on public profiles.

> **Additional context**
> The old version 4.5.5 was working fine.

Does downgrading to version 4.5.5 resolve this?

**Comment by raphaelbernardino** [comment]
Thanks for the reply. Just solved removing sessions files located in ``~/.config/instaloader``. So there's another "bug" probably, because that should say something like "invalid session" or password, right?

**Comment by aandergr** [comment]
> So there's another "bug" probably, because that should say something like "invalid session" or password, right?

Instaloader verifies that the session is valid and that it belongs to the given username, and discards it otherwise.
