### ISSUE TITLE
Make Instaloader break or quit on „429 Too many Request“

### ISSUE THREAD

**Issue by Snickbrack** [instaloader/instaloader#972]
Is there a built-in way to make Instaloader quit when Errors like the 429-Error occur?

I dont want to wait the Timespan after this Error occur as I am calling Instaloader from a cron job and other work with the new downloaded data needs to be done.

**Comment by Showmaster3000** [comment]
You can create your own RateController which has a method handle_429 that sleeps by default. Instead you can raise an exception to end the process.
See source code and [manual](https://instaloader.github.io/module/instaloadercontext.html#instaloader.RateController)

But the download is not complete in this case. So it is possible that you miss some elements. (potential case: you use fast-update, the user has 10 new elements, the process stops f.e. after 6 elements - next time you start, the missing 4 elements are not seen as new cause they are older than the 6 downloaded before)
