### ISSUE TITLE
HTTP error code 410 and the probability of incomplete download on user's posts

### ISSUE THREAD

**Issue by buttermybun** [instaloader/instaloader#973]
**Describe the bug**
This issue has been addressed on #703 before, with only difference is that I'm downloading a public profile. HTTP error code 410 appeared several times on user's highlights, while I'm still able to view the whole thing on android app. Additionally instaloader skipped one user post and stopped at `[ 451/ 452]` at the end of the process without showing error message.

**To Reproduce**
The command I have use is `instaloader --login=my_username profile --highlights --igtv --no-metadata-json`

**Expected behavior**
Download the entire profile.

**Error messages and tracebacks**
The following error or warning appeared at the end:
```
Download highlights "highlights" from user profile: download_pic(): HTTP error code 410.
Download highlights "highlights" from user profile: download_pic(): HTTP error code 410.
Download highlights "highlights" from user profile: download_pic(): HTTP error code 410.
```

**Instaloader version**
Version 4.4.4

**Additional context**
This is for the first time I've encountered that instaloader didn't fully downloaded the user's posts. I might've try manually counting it to check whether it's just a miscalculation bug or not.

**Comment by Showmaster3000** [comment]
You are using a ancient version of instaloader which was released before the bug you mentioned. Pleas update to the latest version and check if the error still exists.

**Comment by buttermybun** [comment]
Apparently I have trouble upgrading it to the latest version because it says that the upgrade were successful but when I checked it out again using ` --version` it's still on the version of 4.4.4. This is what occured at my second attempt:

```
C:\wegetdown>python -m pip install --upgrade instaloader
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: instaloader in c:\users\buttermybun\appdata\roaming\pyth
on\python38\site-packages (4.6)
Requirement already satisfied: requests>=2.4 in c:\program files\python38-32\lib
\site-packages (from instaloader) (2.24.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python38-3
2\lib\site-packages (from requests>=2.4->instaloader) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\program files\python38-32\lib\
site-packages (from requests>=2.4->instaloader) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\pro
gram files\python38-32\lib\site-packages (from requests>=2.4->instaloader) (1.25
.9)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\program files\python38-32
\lib\site-packages (from requests>=2.4->instaloader) (3.0.4)

C:\wegetdown>instaloader --version
4.4.4
```
For context I'm still on windows 7, so was wondering if this has something to do with my old OS as well.

**Comment by aandergr** [comment]
Looks like a problem with your PATH, refer to the documentation of your operating system for more information.
