### ISSUE TITLE
400 Bad Request: Flagged for suspicious activity

### ISSUE THREAD

**Issue by Jong-Sig** [instaloader/instaloader#974]
I imported the session cookies from Firefox to workaround login issues [as recommended](https://instaloader.github.io/troubleshooting.html) and it worked for a day.

However, I encountered 400 Bad Request while I was scraping about 400 posts today, even though I already created the session file to login, and my account was blocked--requiring my mobile phone number authentification.

Does anyone know how to deal with such a frustrating situation?

Thanks!

**Comment by raphaelbernardino** [comment]
Every account now needs a verified mobile phone number. Guess you can buy a burner and do it?

**Comment by Showmaster3000** [comment]
We have a similar discussion in #942.
Question is: are these 400 posts from one profile or different profiles?

**Comment by Sik-Tired** [comment]
> We have a similar discussion in #942.
> Question is: are these 400 posts from one profile or different profiles?

They are from one profile.

**Comment by Sik-Tired** [comment]
> Every account now needs a verified mobile phone number. Guess you can buy a burner and do it?

I actually tried it with my real account, which was linked to my phone number. 
In the end, they blocked my real account (and my phone number), and I was not able to get access using my real account.

**Comment by llacb47** [comment]
> Every account now needs a verified mobile phone number. Guess you can buy a burner and do it?

Really?

![image](https://user-images.githubusercontent.com/16567977/104830978-25d1c880-5852-11eb-8e09-42e8b330283f.png)

**Comment by bebunw** [comment]
> > Every account now needs a verified mobile phone number. Guess you can buy a burner and do it?
> 
> Really?



If you trigger some more times suspicious activity, they mandatory ask for phone number and your account is screwed, if you give a phone number they manually check and can ban your phone number is they 've seen you used a temporary phone number or seen you had botted by scrapping

**Comment by CJSparrow** [comment]
try to create another session file + DONT LOGIN to the account from any device. This works for me

**Comment by CJSparrow** [comment]
I just got this error, and i did this solution. (worked for me)
- login to any account you wanna make instaloader to use from your browser, and DONT login to your account from anywhere else, even your laptop after that.
- create a new session file:
```instaloader -l <USERNAME> --user-agent '<your browser's User-agent>' ```

- copy the path and use the session anytime.

**again: dont use the account or even open it in your browser after you get the session file**

**Comment by parasiteoflife** [comment]
Is there any shortcode for --user-agent?
I can't use it because I get "Invalid shortcode --user-agent '...", I'm using a txt file with all the args there. For user and password I have to use the shortcodes otherwise instaloader doesn't recognize those args, I don't know why it needs them to be -l and -p.

**Comment by CJSparrow** [comment]
> 
> 
> Is there any shortcode for --user-agent?
> I can't use it because I get "Invalid shortcode --user-agent '...", I'm using a txt file with all the args there. For user and password I have to use the shortcodes otherwise instaloader doesn't recognize those args, I don't know why it needs them to be -l and -p.
> 
> > > > Every account now needs a verified mobile phone number. Guess you can buy a burner and do it?
> > > 
> > > 
> > > Really?
> > 
> > 
> > If you trigger some more times suspicious activity, they mandatory ask for phone number to unlock your account and your account is screwed, if you give a phone number they manually check and can ban your phone number is they 've seen you used a temporary phone number or noticed you had botted by scrapping
> 
> Yes, they have been asking me for my phone number these days, goddamn Facebook, makes it harder for us to scrape but the bot accounts continue to increase more and more lol.

try text me now app

**Comment by Jong-Sig** [comment]
> I just got this error, and i did this solution. (worked for me)
> 
> * login to any account you wanna make instaloader to use from your browser.
> * create a new session file:
>   `instaloader -l <USERNAME> --user-agent '<your browser's User-agent>' `
> * copy the path and use the session anytime.
> 
> **Note: dont use the account or even open it in your browser after you get the session file, no logout no missing with it**

Thanks for your suggestion!

It worked for a day, until I face 429 too many requests--I could get information about 1,334 posts of 2 users.  

But when I ran the script again yesterday, I encountered 400 bad request--I could only scrape 177 posts this time. 
I created a session file again before I resume my instaloader script yesterday.

Did you also get the same error?

**Comment by CJSparrow** [comment]
> > I just got this error, and i did this solution. (worked for me)
> 
> > 
> 
> > * login to any account you wanna make instaloader to use from your browser.
> 
> > * create a new session file:
> 
> >   `instaloader -l <USERNAME> --user-agent '<your browser's User-agent>' `
> 
> > * copy the path and use the session anytime.
> 
> > 
> 
> > **Note: dont use the account or even open it in your browser after you get the session file, no logout no missing with it**
> 
> 
> 
> Thanks for your suggestion!
> 
> 
> 
> It worked for a day, until I faced 429 too many requests--I could get information about 1,334 posts of 2 users.  
> 
> 
> 
> But when I ran the script again yesterday, I encountered 400 bad request--I could only scrape 177 posts this time. 
> 
> It was weird since I created a session file again before I resumed my instaloader script yesterday to avoid Instagram's detection.
> 
> 
> 
> Did you also get the same error?
> 
> 

No, i hope I don't get it. Anyway, you need to know the limits of user's usage on Instagram, how many request per 30 mins and so on. Don't get over the limits, always give the bot some breaks for some minutes then￼ continue￼ scrapping.

**Comment by CJSparrow** [comment]
hey bro i got it lmao 
```Instagram responded with HTTP error "429 - Too Many Requests".```

**Comment by Jong-Sig** [comment]
> hey bro i got it lmao
> `Instagram responded with HTTP error "429 - Too Many Requests".`
> i think we need more than 1 account to use instaloader :(.
> i tried all the ways that i mentioned before, none of them worked.

Haha I got banned after this :/
Honestly, I did not pause 24 hours after I faced 429, which was generally recommended.

By the way, just curious if your account will get banned (400) if you resume the scrapping after 24 hours.

**Comment by CJSparrow** [comment]
> hours

how many posts to scrape to get band?

**Comment by Jong-Sig** [comment]
> > hours
> 
> how many posts you scraped so u got ban?

400 posts after 429 requests

**Comment by CJSparrow** [comment]
so no one knows how to fix the issue yet?
