### ISSUE TITLE
get_related_tags() returns an empty iterator

### ISSUE THREAD

**Issue by bluedrops** [instaloader/instaloader#975]
**Describe the bug**
Calling get_related_tags() returns an empty iterator regardless of what hashtag is provided.

**To Reproduce**
```
L = instaloader.Instaloader()
L.login('USERNAME', 'PASSWORD')
hashtag = instaloader.Hashtag.from_name(L.context, 'travel')
related_tags = hashtag.get_related_tags()

print(related_tags) #<generator object Hashtag.get_related_tags at 0x000001976FDAE970>

print(next(related_tags) # StopIteration
```

Has this feature been deprecated/removed, or am I doing something wrong?

**Comment by aandergr** [comment]
I think this feature has been removed from Instagram, the mobile app and the web interface neither show related hashtags anymore.

**Comment by bluedrops** [comment]
I see; that's unfortunate. Thank you for the reply!
