### ISSUE TITLE
JSON Query to graphql/query: HTTP error code 500.

### ISSUE THREAD

**Issue by creativehelm** [instaloader/instaloader#98]
I upgraded from 3.3.7 to 3.3.8.

I'm now getting the following error in Terminal after 12 photos download:

JSON Query to graphql/query: HTTP error code 500.

**Comment by Rcola1987** [comment]
I'm having a similar issue but while logged in an on both 3.3.7 and 3.3.8.

As of a few days ago this was working properly on 3.3.7

JSON Query to graphql/query: HTTP error code 400. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 400. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 400.
Saved session to c:\users\ryan\appdata\local\temp/.instaloader-####/######

Errors occured:
JSON Query to graphql/query: HTTP error code 400.

**Comment by aandergr** [comment]
Duplicate of #94
