### ISSUE TITLE
HTTP error code 403 on instaloader.Post.from_shortcode()

### ISSUE THREAD

**Issue by realSamy** [instaloader/instaloader#980]
**Describe the bug**
unable to make post object using instaloader.Post.from_shortcode() in python 3.8

**To Reproduce**
```python
from instaloader import Instaloader, Post

L = Instaloader()
L.load_session_from_file('username', 'session_name')
post = Post.from_shortcode(L.context, 'SHORTCODE')
print(post.url)

```

**Expected behavior**
I wanted to make a true Post object from an instagram post shortcode

**Error messages and tracebacks**
```
Loaded session from session_name.
JSON Query to graphql/query: HTTP error code 403. [retrying; skip with ^C]
JSON Query to graphql/query: HTTP error code 403. [retrying; skip with ^C]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloadercontext.py", line 339, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 403.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloadercontext.py", line 339, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 403.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloadercontext.py", line 339, in get_json
    raise ConnectionException("HTTP error code {}.".format(resp.status_code))
instaloader.exceptions.ConnectionException: HTTP error code 403.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "insta.py", line 5, in <module>
    post = Post.from_shortcode(L.context, 'CF0KFB8pWsa')
  File "/usr/local/lib/python3.8/dist-packages/instaloader/structures.py", line 83, in from_shortcode
    post._node = post._full_metadata
  File "/usr/local/lib/python3.8/dist-packages/instaloader/structures.py", line 157, in _full_metadata
    self._obtain_metadata()
  File "/usr/local/lib/python3.8/dist-packages/instaloader/structures.py", line 144, in _obtain_metadata
    pic_json = self._context.graphql_query(
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloadercontext.py", line 416, in graphql_query
    resp_json = self.get_json('graphql/query',
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloadercontext.py", line 382, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloadercontext.py", line 382, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/usr/local/lib/python3.8/dist-packages/instaloader/instaloadercontext.py", line 372, in get_json
    raise ConnectionException(error_string) from err
instaloader.exceptions.ConnectionException: JSON Query to graphql/query: HTTP error code 403.
```

**Instaloader version**
4.6

**Additional context**
Thanks for your great works and support! <3

**Comment by aandergr** [comment]
Hi! I cannot reproduce this, Post.from_shortcode() works for me.

The response `403 Forbidden` looks like trying to access a Post of a not-followed private profile.

**Comment by realSamy** [comment]
I tested some stuffs and found the problem was that Instagram has blocked my server's IP! so I can't login to my account on my server, I tried to add proxy support to instaloader to have session objects (and methods that copy the session info to use proxies too!) with proxy support and it worked just fine! so I'll fork the project and add my edits to have a proxy support in this great module <3 !!

**Comment by Aniskonig** [comment]
> I tested some stuffs and found the problem was that Instagram has blocked my server's IP! so I can't login to my account on my server, I tried to add proxy support to instaloader to have session objects (and methods that copy the session info to use proxies too!) with proxy support and it worked just fine! so I'll fork the project and add my edits to have a proxy support in this great module <3 !!

I have the same problem like and I was thinking about the same way to solve...Did you did it ?

**Comment by omidhttp** [comment]
> I tested some stuffs and found the problem was that Instagram has blocked my server's IP! so I can't login to my account on my server, I tried to add proxy support to instaloader to have session objects (and methods that copy the session info to use proxies too!) with proxy support and it worked just fine! so I'll fork the project and add my edits to have a proxy support in this great module <3 !!

How to use this now? Can you give an example?

**Comment by realSamy** [comment]
> @Aniskonig: I have the same problem like and I was thinking about the same way to solve...Did you did it ?

> @omidhttp: How to use this now? Can you give an example?

Yes, when I needed that feature I added that but I couldn't continue development and I don't know if the other developers added the feature to the module's repo, because I haven't done that, you could find proxy support on my fork but it's not up to date based on module's repo
