### ISSUE TITLE
Scraping IG Stories is getting very slow since 13/01

### ISSUE THREAD

**Issue by clublek** [instaloader/instaloader#981]
Since 13/01 the behavior of scraping IG Stories is getting very slow for me. 
I am using the command:
instaloader -l USERNAME -p PASSWORD :stories --dirname-pattern={profile} --filename-pattern={date} --no-metadata-json --no-captions --fast-update --quiet
Then i'm using a sleep command for 15 minutes and repeat the command.

It's now only scraping like 10 accounts per hour :(
I thought that the :stories command used the least amount of requests to fulfill the job.
Do other users also have these issues since then? Did Instagram changed something again perhaps?

Using Instaloader 4.6.

**Comment by skrull** [comment]
I am seeing the same behavior. Instaloader :stories download around 10-15 posts then hangs indefinitely.

**Comment by aandergr** [comment]
Version 4.6 gets higher Post video and StoryItem image quality if logged-in (#712). This requires more queries and makes the download process slower.
