### ISSUE TITLE
Can't type or paste the password when asked

### ISSUE THREAD

**Issue by Kn0p3XX** [instaloader/instaloader#984]
**Describe the bug**
I can't type or paste the password when asked (I'm not sure if the line should be empty or should showing stars)

**To Reproduce**
I execute the .exe and type .\instaloader.exe --login=kn0p3xx
And then trying to paste the password in, but nothing happens, even trying by manually typing in.

**Expected behavior**
I should be able to see if I type it and should be able to paste the password.

**Error messages and tracebacks**
Says password is incorrect, perhaps the line is still empty I was trying to put in the password...?

**Instaloader version**
4.6

**Additional context**
I'm using Windows 10 2004
And the Windows release of Instaloader 4.6.

**Comment by Showmaster3000** [comment]
There are no stars or other place holders if you type the password.
According to #849 and #741 the login fails if your password contains a colon (:).
Another option is to use the workaround described in #741 there, or in [Troubleshooting – Login Error](https://instaloader.github.io/troubleshooting.html#login-error).

**Comment by Kn0p3XX** [comment]
I don't have a colon in my password, but neither of em works. I tried using the 615_import_firefox_session.py script in the Troubleshooter, and it works from there now. So thank you. :)

**Comment by AdamHardix** [comment]
> There are no stars or other place holders if you type the password. According to #849 and #741 the login fails if your password contains a colon (:). Another option is to use the workaround described in #741 there, or in [Troubleshooting – Login Error](https://instaloader.github.io/troubleshooting.html#login-error).

Is the workaround usable with the standalone executable for Windows? If so, how would one go about that?

**Comment by cieramartinez** [comment]
> > There are no stars or other place holders if you type the password. According to #849 and #741 the login fails if your password contains a colon (:). Another option is to use the workaround described in #741 there, or in [Troubleshooting – Login Error](https://instaloader.github.io/troubleshooting.html#login-error).
> 
> Is the workaround usable with the standalone executable for Windows? If so, how would one go about that?

i was able to get it to world by adding --password [MY PW] at the end of the login command
