### ISSUE TITLE
I cannot log into my account!

### ISSUE THREAD

**Issue by CJSparrow** [instaloader/instaloader#985]
**Describe the bug**
Hi, i logged in my account, I turned trust this device on from Instagram settings, but still keep telling my that my password is wrong.

**Instaloader version**
4.6

this affect me so I cannot use any additional features, i have telegram bot uses this library to download content :/

**Comment by Showmaster3000** [comment]
Too less information to help you.
maybe problem described in #984 or #849 or #741

**Comment by CJSparrow** [comment]
> 
> 
> Too less information to help you.
> maybe problem described in #984 or #849 or #741

i don't use special characters btw.
this tool might be broken

**Comment by CJSparrow** [comment]
and now i got an error when i logged in 
```
Fatal error: Login error: "fail" status, message "feedback_required".
```

**Comment by CJSparrow** [comment]
solved! this is because instaloader needs session file to login. check [989](https://github.com/instaloader/instaloader/issues/989).
