### ISSUE TITLE
extend Resumable Iterations to handle other interrupts other than KeyboardInterrupt

### ISSUE THREAD

**Issue by fsantagostinobietti** [instaloader/instaloader#986]
HI,
**resumable_iteration** works great with KeyboardInterrupt, saving current iteration state so that you can resume it later.
But sometimes iteration is interrupted by some other exceptions (e.g. io error or login redirect) and in such cases iteration state is not saved.

Is it possible to modify resumable_iteration so that it can intercept any exception that occurs during iteration?

**Comment by aandergr** [comment]
Please use our [Feature Suggestion Template](https://github.com/instaloader/instaloader/issues/new?labels=feature+suggestion&template=feature_request.md) for suggesting new features, as this makes it easier to see how the new feature could fit into Instaloader.
