### ISSUE TITLE
(SOLVED)

### ISSUE THREAD

**Issue by saad-sifar** [instaloader/instaloader#987]
(ISSUE SOLVED)

**Comment by Showmaster3000** [comment]
refering to the [manual](https://instaloader.github.io/module/instaloader.html), you can pass a set of parameters while creating the instance of Instaloader.
parameters you may like are ``save_metadata=false``, ``filename_pattern(...)``.

**Comment by Showmaster3000** [comment]
@saad-sifar deleting title and issue text is a bad idea. Other people who want to look after their problem can't use the information anymore!
