### ISSUE TITLE
Anyone have tips for downloading more than tens of posts from Hashtags

### ISSUE THREAD

**Issue by monney** [instaloader/instaloader#988]
Without an account I can't download any posts from a hashtag. With an account It blocks you (429 error) at <100 posts per hashtag. I tried using the instaloader get_all_posts function with long sleep in the loop as I iterate over it. Like this:

```python
L = instaloader.Instaloader()
hashtag = Hashtag.from_name(L.context, "python")
for i,post in enumerate(hashtag.get_posts()):
   L.download_post(post, target="#"+hashtag.name)
   time.sleep(1)
```

but this still occurs.

Are others experiencing this issue for hashtags? Does anyone know a way around this?

**Comment by Thammus** [comment]
When using Instaloader as a python module, downloading of comments and geotags is enabled by default which requires additional requests. If you do not want to download them while fetching hashtag posts they can be disabled. For example, change the first line to the following:
```python
L = instaloader.Instaloader(download_geotags=False, download_comments=False)
```
Have a look at our [documentation](https://instaloader.github.io/module/instaloader.html#instaloader-main-class) for a more complete description of the parameters that are used with the Instaloader Class along with its default values.

**Comment by monney** [comment]
Hi! Thanks for the reply. I turned off all extra downloading, and my timeout is like 6 seconds between posts. I always get 429 eventually. I thinking Instagram may have just blocked this type of scraping permanently. If you have any suggestions I would love to hear them.
