### ISSUE TITLE
Fatal error: Login error: "fail" status, message "feedback_required".

### ISSUE THREAD

**Issue by CJSparrow** [instaloader/instaloader#989]
Hello, i'm trying to use ```instaloader``` in my script.
so i logged in my account and i got an error :
```
Fatal error: Login error: "fail" status, message "feedback_required".
```

using commandline : 
```
os.system(f"instaloader --login {user} -p {pwd}")
```
i'm using debian linux server VPS. 
instaloader version : 4,6

**Comment by Showmaster3000** [comment]
no bug, see #929

**Comment by CJSparrow** [comment]
> 
> 
> no bug, see #929

his solution code does not work

**Comment by CJSparrow** [comment]
anyways i got another error on my windows while trying to login:
```
Fatal error: Login: Checkpoint required. Point your browser to https://www.instagram.com/challenge... - follow the instructions, then retry.
```
the issue here no matter how many times i do the challenge, it keeps sending me it.

**Comment by CJSparrow** [comment]
as I realized that Instagram asks you for verification code to let you in. the request session of instaloader should wait until the user enter the code then login. Why? because the challenge  URL does not work with any browser -_-. Even when i already logged in my account

**Comment by CJSparrow** [comment]
i used 3 brain cells to solve all the issues, 
just setting the user-agent of the browser which has my account already logged in.
```
instaloader -l <USERNAME> --user-agent <MY BROWSER'S USER-AGENT>
```
