### ISSUE TITLE
Like and comment count is inconsistent depending on method used

### ISSUE THREAD

**Issue by FadiBitar** [instaloader/instaloader#991]
**Describe the bug**
In the Post class, there are ".likes" and ".comments" properties which return the (correct) number of likes and comments, but invoking the methods ".get_likes()" and ".get_comments()" returns generators with an incorrect amount of items. So if I want to get the list of accounts that liked a specific post, then I'd often get a lower count than what I would get using "post.likes".

**To Reproduce**
`post = instaloader.Post.from_shortcode(L.context, post_short_code)
all_likers = [liker.username for liker in post.get_likes()]
count1 = len(all_likers)
count2 = post.likes`

count1 and count2 will not be identical (not sure if this is for all posts, but I've seen this happen for too many posts for this to be a fluke). The same behaviour can be seen for get_comments() (+ looping over comment answers) and .comments

**Expected behavior**
I expect the two methods to return consistent results: I get the total number of likes using the .likes property, and a more detailed answer but still the same count using .get_likes()

**Instaloader version**
4.6

**Comment by Thammus** [comment]
All likes and comments that are accessible through Instagram should be retrievable by Instaloader. However, like in the official Instagram Web Interface and Apps, the actual listed likes (or comments respectively) are usually fewer than the displayed count indicates. We do not know for sure why these counts diverge.
