### ISSUE TITLE
Resuming hashtag posts searches

### ISSUE THREAD

**Issue by brilam** [instaloader/instaloader#992]
Hi,

I was wondering if there was a way to resume retrieval of hashtag posts. From the documentation, I noticed that it mentioned that we can freeze and thaw a NodeIterator to resume iterations, but from what I've seen in the documentation, not all searches allow this. In the documentation, the example given was [Profile.get_posts()](https://instaloader.github.io/module/structures.html#instaloader.Hashtag.get_posts) which returns a NodeIterator.  I am using [Hashtag.get_posts()](https://instaloader.github.io/module/structures.html#instaloader.Hashtag.get_posts). Is there any way that I can resume a hashtag search? I am looking to get a large amount of posts (around 100k), and from what I can tell, I've been locked out after about 40k. I was thinking of splitting my retrieval of posts across different days, so I will need some way of resuming my retrieval of hashtag posts.

**Comment by aandergr** [comment]
Hi,

> Hashtag.get_posts() does not currently support to resume the iteration due to not using a graphql pagination. However, it seems we can get a [resumable iterator](https://instaloader.github.io/module/nodeiterator.html) for the recent hashtag posts like this:
> 
> ```python
> post_iterator = instaloader.NodeIterator(
>     L.context, "9b498c08113f1e09617a1703c22b2f32",
>     lambda d: d['data']['hashtag']['edge_hashtag_to_media'],
>     lambda n: instaloader.Post(L.context, n),
>     {'tag_name': HASHTAG},
>     f"https://www.instagram.com/explore/tags/{HASHTAG}/"
> )
> ```
> 
> With that, you can use [resumable_iteration()](https://instaloader.github.io/module/nodeiterator.html#resumable-iteration) as usual.

_(from https://github.com/instaloader/instaloader/issues/874#issuecomment-731561430)_
