### ISSUE TITLE
Sidecar post filename numbering sequence pattern breaks sort order

### ISSUE THREAD

**Issue by iliv** [instaloader/instaloader#994]
**Description**

This is best illustrated by looking at a complete listing of files for a single sidecar post:

```
$ ls -la 2017-08-26_09-22-20_UTC*
-rw-rw-r-- 1 iliv iliv 232329 Aug 26  2017 2017-08-26_09-22-20_UTC_10.jpg
-rw-rw-r-- 1 iliv iliv 170695 Aug 26  2017 2017-08-26_09-22-20_UTC_1.jpg
-rw-rw-r-- 1 iliv iliv 126951 Aug 26  2017 2017-08-26_09-22-20_UTC_2.jpg
-rw-rw-r-- 1 iliv iliv 158445 Aug 26  2017 2017-08-26_09-22-20_UTC_3.jpg
-rw-rw-r-- 1 iliv iliv 155530 Aug 26  2017 2017-08-26_09-22-20_UTC_4.jpg
-rw-rw-r-- 1 iliv iliv 162829 Aug 26  2017 2017-08-26_09-22-20_UTC_5.jpg
-rw-rw-r-- 1 iliv iliv 132665 Aug 26  2017 2017-08-26_09-22-20_UTC_6.jpg
-rw-rw-r-- 1 iliv iliv 160194 Aug 26  2017 2017-08-26_09-22-20_UTC_7.jpg
-rw-rw-r-- 1 iliv iliv 137903 Aug 26  2017 2017-08-26_09-22-20_UTC_8.jpg
-rw-rw-r-- 1 iliv iliv 125067 Aug 26  2017 2017-08-26_09-22-20_UTC_9.jpg
-rw-rw-r-- 1 iliv iliv  13248 Jan 20 12:25 2017-08-26_09-22-20_UTC.json.xz
-rw-rw-r-- 1 iliv iliv    221 Aug 26  2017 2017-08-26_09-22-20_UTC.txt
```
As you can see _UTC_10.jpg precedes _UTC_1.jpg. This results in broken sort order in photo management applications (e.g. native Photos in macOS).

**To Reproduce**

`instaloader --login=$profilename --no-video-thumbnails --no-profile-pic --geotags $profilename`

**Expected behavior**
Filenames should have the following numbering pattern: UTC_01.jpg, UTC_02.jpg ... UTC_10.jpg

**Error messages and tracebacks**
None

**Instaloader version**
4.6

PS: I checked out official documentation but I'm not sure if --filename-pattern can be used to have this particular numbering pattern. Regardless, I would argue that the "UTC_01.jpg, UTC_02.jpg ... UTC_10.jpg" pattern should be used by default.

**Comment by aandergr** [comment]
Interesting. What do you suggest to solve this in a backwards-compatible manner?

**Comment by iliv** [comment]
wontfix? why?

To answer your question, I have no idea. I just thought I should point out this problem and hopefully developers (you?) could fix it.

**Comment by aandergr** [comment]
Right, 'wontfix' is probably wrong here, since there is nothing to fix and this doesn't suggest any feature. We now decided for 'invalid', which might be more appropriate for a nonsense issue followed by a derogatory comment.
