### ISSUE TITLE
Do regular iterator backups

### ISSUE THREAD

**Issue by thomas694** [instaloader/instaloader#998]
**Provide us a use case of the feature**
Sometimes instaloader stops. Instaloader only saves an iterator backup for resume if Ctrl+C has been pressed. But it's too late if the error already happened.

**Describe the solution you'd like**
Regular iterator backups after every page downloaded, so that instaloader can resume from the last backup point.

**Describe alternatives you've considered**
There are none.

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes.

**Additional context**
In issue #920 and #986 something similar was discussed.

**Comment by Thammus** [comment]
Instead of storing the resume iterator after every page it would probably be easier to trigger it when Instaloader stops due to an error for example by somehow reacting on `InstaloaderException`.

**Comment by thomas694** [comment]
Isn't it a very optimistic approach to say you know when/where the error occurs and that you can catch all errors?
Probably it's easier to exchange the caught exception ([PR990](https://github.com/instaloader/instaloader/pull/990)), but as said above.
Besides I don't think it's inefficient to save 1KB every few seconds despite writing dozens of MB and files to the disk.

**Comment by Thammus** [comment]
> Isn't it a very optimistic approach to say you know when/where the error occurs and that you can catch all errors?

Like described in #920 one could trigger the resume logic depending on failing requests and the error codes they get responded. This feels like a cleaner solution for the provided use case.

> Besides I don't think it's inefficient to save 1KB every few seconds despite writing dozens of MB and files to the disk.

Inefficiency was never a point regarding this issue. What makes storing the resumable iterator after every page kind of complex is to keep features like `--fast-update` working.

**Comment by thomas694** [comment]
> What makes storing the resumable iterator after every page kind of complex is to keep features like --fast-update working.

I don't get your point. So using Ctrl+C or the new option `--abort-on` discussed in #920, both doing the same (storing the resumable iterator), breaks the `--fast-update` feature too?

**Comment by Thammus** [comment]
No, the problem only arises when the post on which the resumable iterator gets created differs from the one Instaloader gets aborted. The logic for the current resume cases (including the `--abort-on` option) uses sophisticated methods to properly support the `--fast-update` behavior.
