### ISSUE TITLE
On rescans load existing GraphSidecar json instead of downloading again

### ISSUE THREAD

**Issue by thomas694** [instaloader/instaloader#999]
**Provide us a use case of the feature**
For every GraphSidecar node that has videos in it, a graph query is executed. Especially on rescans that is a waste of api calls.

**Describe the solution you'd like**
Instead of downloading that json again, just load it from disk if it has been downloaded and saved before.

**Describe alternatives you've considered**
None found.

**If the feature request is accepted, would you be willing to submit a pull request?**
Yes.

**Additional context**

**Comment by aandergr** [comment]
> Especially on rescans that is a waste of api calls.

We fixed this rescan inefficiency with 672b0b184019bf840e3003e90a1c662fcb4df79a in `upcoming/v4.7`. Now, that graph query is only executed if one of the files that should be downloaded is missing.

**Comment by thomas694** [comment]
The current `upcoming/v4.7` ([640066d](https://github.com/instaloader/instaloader/commit/640066dd607f191eba6a2bf7cfb5446acda88490)) is runnable (and contains latest master too), right?

Sorry, I don't know how to use the upcoming version. Please help.
On a re-run it does a query for every sidecar node.
<br/>

As for every post the json is saved anyway (default parameters), so why not reload that one, if needed in case of a sidecar node?
For a re-run of 62 posts (12+50) I need two query/api calls, regardless of how many sidecar nodes therein. And it works independent from the chosen filename template. Imho that's effiecency.

**Comment by aandergr** [comment]
This feature suggestion seems a great idea to me.

Instaloader goes through the posts online, determines the filenames that would be created for each post, and skips the post if it already exists in the target's folder locally. For sidecars in a profile that are not at the first page, e.g. posts with index > 12, the sidecar details are not included in the page overview returned by Instagram, and so Instaloader currently needs to do an extra graphql query to obtain the information that is needed to determine which filenames would be created, and as such, to determine whether something has to be downloaded. (my previous comment was wrong)

The information in the 'old' JSON files from a previous run should be sufficient to determine the filenames yield by the Post in question. So your suggestion is a nice idea to save that query and so speed up rescans of profiles (and most probably other targets as well) that have some sidecars.

I think that the number of media in a sidecar post cannot change, i.e. that it is not possible to add or remove photos/videos after posting the sidecar. This is a prerequisite for this feature to work properly.

To not introduce side-effects, the information from the 'old' JSON file probably should only be used to determine whether the Post needs to be re-downloaded or not.

> The current `upcoming/v4.7` ([640066d](https://github.com/instaloader/instaloader/commit/640066dd607f191eba6a2bf7cfb5446acda88490)) is runnable (and contains latest master too), right?
> 
> Sorry, I don't know how to use the upcoming version. Please help.

Yes, `upcoming/v4.7` should work and includes the latest master too. With pip, it can be installed with

```
pip3 install --upgrade git+https://github.com/instaloader/instaloader@upcoming/v4.7
```

> For a re-run of 62 posts (12+50) I need two query/api calls, regardless of how many sidecar nodes therein. And it works independent from the chosen filename template. Imho that's effiecency.

Awesome :)
